### ISSUE TITLE
Smater buffer switching to frame

### ISSUE THREAD

**Issue by tuhdo** [emacs-helm/helm#1001]
When I have some buffer on a frame, when switching that buffer with `helm-mini` or `helm-buffers-list`, I would like it switch to the frame automatically instead of opening the buffer  in my current frame. This is useful when using frames. `ido-switch-buffer` has this feature and I really like it. This feature should not  affect people who don't use frame.

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> When I have some buffer on a frame, when switching that buffer with
> helm-mini or helm-buffers-list, I would like it switch to the frame
> automatically instead of opening the buffer in my current frame. This
> is useful when using frames. ido-switch-buffer has this feature and I
> really like it. This feature should not affect people who don't use
> frame.

C-c C-o.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment]
I know that. That's why I said smarter buffer switching. That is, when pressing `RET` and buffer is in other frame, automatically switch to it instead of me having to manually press `C-c C-o`. `C-c C-o` should only be used to init a buffer in a frame.

**Comment by tuhdo** [comment]
If you want to see how it works:
t
- Open a buffer in another frame.
- `ido-switch-buffer` and select that buffer.
- Instead of opening the buffer in current frame, it switches to the frame that contains the buffer.

Now, with `helm-mini`, it opens that buffer in the current frame which is not what I want, because if I want to use current frame, why do I have to open a frame in the first place?

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> If you want to see how it works:

No need to see how it works, it is simple enough.

If you want to switch to buffer in current frame use RET.
If you want to switch to buffer in other frame use C-c C-o,
creating the frame if the buffer is not already displayed in some frame.

Please close this bug report.

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment]
What I want is simple: 

- if a buffer is already in a different frame, switch to that frame instead, using `RET` without having to press `C-c C-o` **again**.

Reason: I don't want to remember which buffer is in which frame and select key bindings appropriately. It's distracting and make using frame inconvenient. Do you use any tilling window manager? If so, frames are very useful.

Anyway, if you don't want to add, may I add this?

**Comment by thierryvolpiatto** [comment]
You don't have to remember anything, if the buffer is not in your current frame C-c C-o will bring you where you want, and if you want to stay in THIS frame RET will keep you in THIS frame.
Please stop insisting.

**Comment by tuhdo** [comment]
@thierryvolpiatto No, I don't want to look at the buffer names in the current frame. I just want when I select a buffer and it's in other frame, it switches automatically with just pressing `RET`. Ok, I repeat again: I don't want to look at the current buffers in current frame; I want this to be automated. Initially, I open the buffers with `C-c C-o` and that it. I don't want to use it again until I want a buffer in other frame.

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> @thierryvolpiatto No, I don't want to look at the buffer names in the
> current frame. I just want when I select a buffer and it's in other
> frame, it switches automatically with just pressing RET. Ok, I repeat
> again: I don't want to look at the current buffers in current frame; I
> want this to be automated. Initially, I open the buffers with C-c C-o
> and that it. I don't want to use it again until I want a buffer in
> other frame.

What YOU want is not necessarily what I want or what OTHERS want.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
