### ISSUE TITLE
Can't rebind any commands

### ISSUE THREAD

**Issue by MichaelLiuzzi** [emacs-helm/helm#1002]
I have tried to rebind several keys to new commands. 
For instance, i've tried to rebind "s" to helm-do-grep with no success. 
I've tried to set it to nil first as per a previous issue and that did not work. I also tried to define it in the helm-find-files map as per another issue and that did not work either.

Does anyone have an idea as to why I can't rebind?

**Comment by thierryvolpiatto** [comment]
MichaelLiuzzi <notifications@github.com> writes:

> I have tried to rebind several keys to new commands.  For instance,
> i've tried to rebind "s" to helm-do-grep with no success.  I've tried
> to set it to nil first as per a previous issue and that did not
> work. I also tried to define it in the helm-find-files map as per
> another issue and that did not work either.
>
> Does anyone have an idea as to why I can't rebind?

You are trying to rebind helm-do-grep to "s" which is
`self-insert-command', a bad idea.
It is handled specially by emacs and you should not do this (for obvious
reasons too).
Note that helm-do-grep will be removed at one point, so use
helm-find-files as a starting point.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment]
@MichaelLiuzzi I guess you are using Evil? If so, try this:

```elisp
(define-key evil-normal-state-map (kbd "s") 'helm-do-grep)
```

It should work.

**Comment by MichaelLiuzzi** [comment]
No, I was trying to rebind the "s" command after the helm command prefix. Right now, surfraw is bound  to it. I don't use surfraw so I would like to rebind to a more useful command.

**Comment by MichaelLiuzzi** [comment]
Also, @tuhdo : thanks for your tutorials. They're really helpful.

**Comment by thierryvolpiatto** [comment]
MichaelLiuzzi <notifications@github.com> writes:

> No, I was trying to rebind the "s" command after the helm command
> prefix. Right now, surfraw is bound to it. I don't use surfraw so I
> would like to rebind to a more useful command.

(define-key helm-command-map (kbd "s")   'helm-<xxx>)


-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
