### ISSUE TITLE
error when opening ansi-term

### ISSUE THREAD

**Issue by sfischme** [emacs-helm/helm#1003]
```M-x term``` or ```M-x ansi-term``` cause the following error to appear in ```*Messages*```:

```
Error in post-command-hook (helm--maybe-update-keymap): (error "No buffer named *helm*")
```

**Comment by thierryvolpiatto** [comment]
sfischme <notifications@github.com> writes:

> M-x term or M-x ansi-term cause the following error to appear in *Messages*:
>
> Error in post-command-hook (helm--maybe-update-keymap): (error "No buffer named *helm*")

Not reproductible, please try from ./emacs-helm.sh.
Also if the error persists, send the full backtrace.
But I hardly see why this would happen without something else (not helm)
in the way.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by sfischme** [comment]
You are correct. No reproducible with emacs-helm.sh.
