### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by camdez** [emacs-helm/helm#1004]
It would be super cool if the project had a Changelog. As is, new releases come out and its unclear what features they add. A couple bullet points per release would be enough.

**Comment by thierryvolpiatto** [comment]
Cameron Desautels <notifications@github.com> writes:

> It would be super cool if the project had a Changelog.

No, changelog files are a nuisance.

> As is, new releases come out and its unclear what features they add. A
> couple bullet points per release would be enough.

Actually I don't add comments about the new features each release have,
the only comment is "Version x.x.x".

I will try to add more comments about new features starting to next
version.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by camdez** [comment]
Hi @thierryvolpiatto,

I don't mean a GNU-style changelog noting every single function change...that kind of thing is a nuisance.

If you do add more comments about new features, where will these comments be? Wherever those comments are, that is your changelog.

**Comment by thierryvolpiatto** [comment]
Cameron Desautels <notifications@github.com> writes:

> If you do add more comments about new features, where will these
> comments be? Wherever those comments are, that is your changelog.

You can click on "xx releases" on the github page to see each release.
https://github.com/emacs-helm/helm/releases


-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by camdez** [comment]
Ah, ok, so you'll add the notes on the GitHub releases. Very good. Thanks!

**Comment by thierryvolpiatto** [comment]
Cameron Desautels <notifications@github.com> writes:

> Ah, ok, so you'll add the notes on the GitHub releases. Very good. Thanks!

I have added some infos (brief) to the 1.7.0 tag, I will try to be
better on next release ;-).

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
