### ISSUE TITLE
Helm source header vanishes when scrolling to end then beginning of buffer

### ISSUE THREAD

**Issue by tuhdo** [emacs-helm/helm#1008]
To reproduce:

- Run any Helm command.
- `M->` to go to the end.
- `M-<` to go to the beginning.
- Header vanishes.

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> To reproduce:
>
>   * Run any Helm command.
>   * M-> to go to the end.
>   * M-< to go to the beginning.
>   * Header vanishes.

Not reproductible, try to reproduce from ./emacs-helm.sh.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment]
Indeed. Closing for now.
