### ISSUE TITLE
ffap broken when helm-mode is active

### ISSUE THREAD

**Issue by mgrbyte** [emacs-helm/helm#1009]
I have helm 20150426.2119 from melpa, installed via `list-packages`
I have the following helm config set:
https://github.com/mgrbyte/dot-files/blob/master/emacs/.emacs-custom.el#L138-L168

When invoking ffap from the M-x prompt, with the cursor over a URLin a buffer,
the resulting URL is malformed. Example below is when the URL is `http://www.google.com`:

http://www.http.com//www.google.com

Upon subsequent invokations, the error: http/80 Name or service not known is shown in the mini-buffer.

I tried unbinding: `helm-M-x` - the same behaviour as above was observed.

After disabling helm-mode, ffap works as expected.

**Comment by thierryvolpiatto** [comment]
Matt Russell <notifications@github.com> writes:

> When invoking ffap from the M-x prompt, with the cursor over a URLin a buffer,
> the resulting URL is malformed. Example below is when the URL is http://www.google.com:

Thanks should work now.

BTW you will be better served by M-x helm-find-files for all you tasks
related to files.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by mgrbyte** [comment]
@thierryvolpiatto thanks! (Also, helm is *awesome*!)
