### ISSUE TITLE
dired-goto-file with helm enabled should auto-select candidates

### ISSUE THREAD

**Issue by dakrone** [emacs-helm/helm#1011]
When I hit the `j` key in a dired buffer (bound to `dired-goto-file`), I expect to the able to type a substring of a filename and then hit `enter` to move the point to that file, instead, whatever I type goes on a "[?]" line in helm and I have to hit `C-n` to select the file in order to actually go to it.

If I hit enter on the "[?]" line, nothing happens.

Here's a screenshot:

![screen shot 2015-05-01 at 10 50 11 am](https://cloud.githubusercontent.com/assets/19060/7433572/09652140-eff0-11e4-8849-5f158fe737e1.png)

It seems like the "[?]" would only be useful if I were creating a file, but `dired-goto-file` is just for jumping to a file.

**Comment by thierryvolpiatto** [comment]
Lee Hinman <notifications@github.com> writes:

> When I hit the j key in a dired buffer (bound to dired-goto-file), I expect to the able to type a substring of a filename and then hit enter to move the point to that
> file, instead, whatever I type goes on a "[?]" line in helm and I have to hit C-n to select the file in order to actually go to it.
>
> If I hit enter on the "[?]" line, nothing happens.
>
> Here's a screenshot:
>
> screen s

It is working as expected here, I guess it is not working because you
entered in pattern crassh which doesn't exists.
                      ^^
-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by dakrone** [comment]
> I guess it is not working because you entered in pattern crassh which doesn't exists.

It happens even if it is a match, see:

![screen shot 2015-05-01 at 11 20 19 am](https://cloud.githubusercontent.com/assets/19060/7434009/f974e8f2-eff3-11e4-92b4-d0bef08e7900.png)

**Comment by thierryvolpiatto** [comment]
Lee Hinman <notifications@github.com> writes:

>     I guess it is not working because you entered in pattern crassh which doesn't exists.
>    
> It happens even if it is a match, see:
>
> screen s

Try from ./emacs-helm.sh, it is working, your cursor in this case will
be on the second line.
Probably you have disabled a hook in your config.

BTW Using directly helm-find-files instead of prehistoric dired+j would
help.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by dakrone** [comment]
> Try from ./emacs-helm.sh, it is working, your cursor in this case will be on the second line. Probably you have disabled a hook in your config.

From emacs-helm.sh I get the same thing:

![screen shot 2015-05-01 at 11 37 23 am](https://cloud.githubusercontent.com/assets/19060/7434220/56827a8a-eff6-11e4-9de8-f1f8fd340c49.png)

> BTW Using directly helm-find-files instead of prehistoric dired+j would help.

I do use `helm-find-files`, but only if I want to do something with a file, here I want to just move the cursor to the file line, so I can perform some dired action on it (mark it, unmark it, chmod in diredw mode, etc)

**Comment by thierryvolpiatto** [comment]
Lee Hinman <notifications@github.com> writes:

>     Try from ./emacs-helm.sh, it is working, your cursor in this case will be on the second line. Probably you have disabled a hook in your config.
>    
> From emacs-helm.sh I get the same thing:
>
> screen s
>
>     BTW Using directly helm-find-files instead of prehistoric dired+j would help.
>    
> I do use helm-find-files, but only if I want to do something with a
> file, here I want to just move the cursor to the file line, so I can
> perform some dired action on it (mark it, unmark it, chmod in diredw
> mode, etc)

Ok, so you have better time to disable helm for this command even if it
works correctly (there is no bug here).

FYI you can chmod any file(s) from helm-find-files.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
BTW the [?] is here because dired original code doesn't use a must-match argument (and it should).

**Comment by dakrone** [comment]
> BTW the [?] is here because dired original code doesn't use a must-match argument (and it should).

Oh okay, good to know, maybe I can submit a patch to emacs core to fix that :)

Thanks!

**Comment by michael-heerdegen** [comment]
I can reproduce the problem.  I remember that we intentionally made it to behave this way in
https://github.com/emacs-helm/helm/commit/01205d25fd87306a9f19873ca667f03e9f09b096

The effect is not desired in this case, however.  Maybe we should find a more suitable condition.

I agree that using MUST-MATCH in the sources would be good.
