### ISSUE TITLE
Question about opening helm buffers for first time

### ISSUE THREAD

**Issue by justbur** [emacs-helm/helm#1012]
Sorry if this has been answered already, but there is a delay in opening helm buffers for the first time (such as helm-find-files). I haven't investigated but my guess is it's related to recent files or helm's history. It doesn't bother me much, but I was wondering if there was a way to trigger the initialization in the background through init.el. Say I load emacs as a daemon on startup for example.

**Comment by michael-heerdegen** [comment]
I'm not sure what you mean.  Trying helm-find-files from helm.sh, I don't experience any notable delay.

**Comment by justbur** [comment]
Never mind. I figured out where the delay was coming from. Helm was being lazily loaded and I didn't realize it. Sorry for the stupid question
