### ISSUE TITLE
`helm-add-action-to-source' cannot add a new action at 0th?

### ISSUE THREAD

**Issue by xuchunyang** [emacs-helm/helm#1013]
```elisp
(defvar foo-helm-source
  (helm-build-sync-source "foo"
    :candidates '(foo bar baz)
    :action (helm-make-actions
             "AAA" #'message
             "BBB" #'message)))

(helm-add-action-to-source "CCC"
                           #'message
                           foo-helm-source
                           0)           ; Not work here?
⇒ (("AAA" . message)
   ("BBB" . message))

(helm-add-action-to-source "CCC"
                           #'message
                           foo-helm-source
                           1)
⇒ (("AAA" . message)
   ("CCC" . message)
   ("BBB" . message))
```

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

> (defvar foo-helm-source
>   (helm-build-sync-source "foo"
>     :candidates '(foo bar baz)
>     :action (helm-make-actions
>              "AAA" #'message
>              "BBB" #'message)))
>
> (helm-add-action-to-source "CCC"
>                            #'message
>                            foo-helm-source
>                            0)           ; Not work here?
> ⇒ (("AAA" . message)
>    ("BBB" . message))
>
> (helm-add-action-to-source "CCC"
>                            #'message
>                            foo-helm-source
>                            1)

=> (("CCC" . message) ("AAA" . message) ("BBB" . message))

Fixed thanks!

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
