### ISSUE TITLE
helm-find-files and go to specified lines (enhancement)

### ISSUE THREAD

**Issue by yangyingchao** [emacs-helm/helm#1014]
Hi There,

 Helm is great and I love it. I just have a question about helm-find-files: can we open a
 file to goto speicified line automatically?

 I often use eshell as a shell to analyze crash logs, and the logs contains file name and
 line number, for example:

/tmp/testcode/test1.c:100

 When I moved cursor to this line, and called: helm-file-files, test1.c will be opened, and
 then I need to call: goto-line to move to line 100.

 Is it possible for helm-find-files do this for me?

 I took a rough look at current implementation, it seems requires quite lot of work to do
 so...

Thanks,
Tubo

**Comment by thierryvolpiatto** [comment]
Yang, Ying-chao <notifications@github.com> writes:

> Hi There,
>
> Helm is great and I love it. I just have a question about helm-find-files: can we open a
> file to goto speicified line automatically?
>
> I often use eshell as a shell to analyze crash logs, and the logs contains file name and
> line number, for example:
>
> /tmp/testcode/test1.c:100
>
> When I moved cursor to this line, and called: helm-file-files, test1.c will be opened, and
> then I need to call: goto-line to move to line 100.
>
> Is it possible for helm-find-files do this for me?

Yes, but it is not already implemented.

Something like this should work (not fully tested!):

(defun helm-ff-goto-line (candidate)
  (let ((linum (helm-read-string
                "LineNumber: "
                (let ((str (with-helm-current-buffer
                             (buffer-substring-no-properties
                              (point-at-bol) (point-at-eol)))))
                  (when (string-match ":\\([0-9]+\\)\\'" str)
                    (match-string 1 str))))))
    (find-file candidate)
    (and linum (not (string= linum ""))
         (goto-line (string-to-number linum)))))

(helm-add-action-to-source-if
 "Find file to line" 'helm-ff-goto-line helm-source-find-files
 (lambda (_candidate)
   (string-match
    ":\\([0-9]+\\)\\'"
    (with-helm-current-buffer
      (buffer-substring-no-properties
       (point-at-bol) (point-at-eol))))))

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Thierry Volpiatto <thierry.volpiatto@gmail.com> writes:

>> Is it possible for helm-find-files do this for me?

Here something better (allow adding the action at source creation
instead of adding after the source is created).

(defun helm-ff-goto-line (candidate)
  (let ((linum (let ((str (with-helm-current-buffer
                            (buffer-substring-no-properties
                             (point-at-bol) (point-at-eol)))))
                 (when (string-match ":\\([0-9]+\\)\\'" str)
                   (match-string 1 str)))))
    (find-file candidate)
    (and linum (not (string= linum ""))
         (helm-goto-line (string-to-number linum) t))))

(defmethod helm-setup-user-source :after ((source helm-source-ffiles))
  (helm-source-add-action-to-source-if
   "Find file to line" 'helm-ff-goto-line source
   (lambda (_candidate)
     (let ((str (with-helm-current-buffer
                  (buffer-substring-no-properties
                   (point-at-bol) (point-at-eol)))))
       (and (not (string-match-p ffap-url-regexp str))
            (string-match-p ":\\([0-9]+\\)\\'" str))))
   0))

Also the prompt for line number is removed.
This is the user configuration, but I could add this to helm-files.el
definitely.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by yangyingchao** [comment]
Great, I'll try.

Thank you very much!

**Comment by thierryvolpiatto** [comment]
I reopen this until it is added to helm.
Once done, probably today, you will be able to remove the snippet of code I sent from your config.

Thanks.

**Comment by thierryvolpiatto** [comment]
Added.
You can now remove the snippet from your config and close again if working fine.

Thanks.

**Comment by yangyingchao** [comment]
Thanks, will do after next update.

**Comment by yangyingchao** [comment]
works great!

**Comment by xuchunyang** [comment]
Can we support more general case, not just only `filename:linum` on a single line? for example:
```
gawk: /Users/xcy/repos/translate-shell/translate.awk:29: error: can't open source file `metainfo' for reading (No such file or directory)
```

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

> Can we support more general case, not just only filename:linum on a
> single line?

Should work now with last changes.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by xuchunyang** [comment]
Works fine.  Thank you!

**Comment by thierryvolpiatto** [comment]
hesting15 <notifications@github.com> writes:

> Open file under a cursor work great, thanks!  But if I use M-x
> helm-find-files and insert filename from clipboard in format
> filename:linum , it creates new file filename:linum, instead of
> opening the file and goto line

But if you have under cursor /foo.txt:123 and open helm-find-files from
there and hit RET, helm will go to foo.txt to line 123.

> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or mute the thread.*


--
Thierry

**Comment by hesting15** [comment]
Yes, this works as expected

**Comment by agzam** [comment]
I know it's an old issue, but I can't make it work for some reason. Can somebody help me. I'm using Spacemacs in Emacs 27. I've tried all sorts of things, but I can't make it work. I can't find a way to open a file and jump to a specific line in it. Trying something like `file.txt:200` just opens new buffer for non-existing file.

**Comment by thierryvolpiatto** [comment]
Ag Ibragimov <notifications@github.com> writes:

> I know it's an old issue, but I can't make it work for some reason.

You can't make it work because you are using Spacemacs, it is working
fine from emacs-helm.sh.
Since recently a new variable
(`helm-ff-allow-non-existing-file-at-point`) have been added that
prevent using this feature, it is nil by default.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Now it is working even when `helm-ff-allow-non-existing-file-at-point` is enabled.

**Comment by agzam** [comment]
I've tried tweaking it `helm-ff-allow-non-existing-file-at-point`, I set it to `t` but still unable to make it work. What am I missing? Do I need to somehow "reset" helm after setting the var?

**Comment by thierryvolpiatto** [comment]
Ag Ibragimov <notifications@github.com> writes:

> I've tried tweaking it helm-ff-allow-non-existing-file-at-point, I set
> it to t but still unable to make it work. What am I missing? Do I need
> to somehow "reset" helm after setting the var?

No, if you read the full post, you will see I made some changes to not
affect this feature (jumping to numbering lines) when modifying
helm-ff-allow-non-existing-file-at-point.  If you start from
emacs-helm.sh, you will see it is working fine, IOW don't use Spacemacs
to reproduce bugs.

> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or mute the thread.*


--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
