### ISSUE TITLE
Helm not using Solarized theme

### ISSUE THREAD

**Issue by ephexeve** [emacs-helm/helm#1015]
I am trying to get Helm to use my [solarized theme](https://github.com/sellout/emacs-color-theme-solarized). Right now (by default) looks like this:
![Image of Solarized/Helm]
(http://i.imgur.com/5qz39SQ.png)

How can I get rid of this grey color for highlighting and title and use the default from Solarized?

Thanks.

**Comment by tuhdo** [comment]
@ephexeve I think that's the color the theme defines for the highlighter. Otherwise Helm will use its default color.

**Comment by ephexeve** [comment]
@tuhdo, thanks for the quick reply.
More specifically I am trying to change the "title" where you see C-j describe and etc.
Any hint where I could change the color here?

**Comment by ephexeve** [comment]
I got it fixed (hopefully without messing anything import) with:

```
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(header-line ((t (:background "brightcyan" :foreground "black" :inverse-video t)))))
```

**Comment by thierryvolpiatto** [comment]
Ephexeve M <notifications@github.com> writes:

> I got it fixed (hopefully without messing anything import

You will mess nothing if you use the customize interface. 

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
