### ISSUE TITLE
Broken helm-dabbrev.

### ISSUE THREAD

**Issue by proofit404** [emacs-helm/helm#1016]
Here is whats happens when I try to run `helm-dabbrev` command:
```lisp
Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
  helm-dabbrev()
  eval((helm-dabbrev) nil)
  eval-expression((helm-dabbrev) nil)
  funcall-interactively(eval-expression (helm-dabbrev) nil)
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)
```

**Comment by thierryvolpiatto** [comment]
Malyshev Artem <notifications@github.com> writes:

> Here is whats happens when I try to run helm-dabbrev command:

Typically a bad install, reinstalling and restart emacs should fix the
problem.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Thierry Volpiatto <thierry.volpiatto@gmail.com> writes:

> Malyshev Artem <notifications@github.com> writes:
>
>> Here is whats happens when I try to run helm-dabbrev command:
>
> Typically a bad install, reinstalling and restart emacs should fix the
> problem.

Sorry I am wrong, I could reproduce when helm-dabbrev-cycle-threshold is
0 or null.

Should work now.

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by proofit404** [comment]
Fixed. Thanks!
