### ISSUE TITLE
Prefix argument to enter dired listing switches for helm-find-files

### ISSUE THREAD

**Issue by tuhdo** [emacs-helm/helm#1017]
With `C-x d`, we can supply a prefix argument to enter Dired listing switches so we can enter `-R` option to recursively list a directory, but it does not work for `helm-find-files`.

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> With C-x d, we can supply a prefix argument to enter Dired listing
> switches so we can enter -R option to recursively list a directory,
> but it does not work for helm-find-files.

You have to use C-u C-x C-d

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment]
`C-u C-x d` works too, and it inserts sub-directories instead of listing all files with nice highlighting (if you add `-R` option). Since `RET` on a directory run `dired`, should we just feed it `helm-current-prefix-arg` if available?

**Comment by thierryvolpiatto** [comment]
RET on a directory doesn't run `dired`.
As you said `C-u C-x d` is working fine, so you can use it (with `helm-mode` enabled) just like `helm-find-files`.
As I always say I personally don't use `dired` at all and I discourage its usage in favor of `helm-find-files` workflow (`C-x C-f` + `C-x C-d`).
