### ISSUE TITLE
Lisp error with empty string in helm-find-files

### ISSUE THREAD

**Issue by PythonNut** [emacs-helm/helm#1018]
When executing <kbd>M-x</kbd> <kbd>helm-find-files</kbd>, and deleting the entire contents of the minibuffer, I get a variety of errors.
```emacs
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  expand-file-name(nil)
  helm-find-files-get-candidates()
  apply(helm-find-files-get-candidates nil)
  helm-funcall-with-source((name . "Find Files") (header-name lambda (name (concat name helm-find-files-doc-header)) (init lambda nil (setq helm-ff-auto-update-flag helm-ff-auto-update-initial-value) (setq helm-ff--auto-update-state helm-auto-update-flag) (helm-set-local-variable (quote bookmark-make-record-function) (function helm-ff-make-bookmark-record)) (candidates . helm-find-files-get-candidates) (keymap keymap (right . helm-execute-persistent-action) (left . helm-find-files-up-one-level)
```
And
```emacs
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  expand-file-name(nil)
  helm-find-files-get-candidates(confirm)
  [byte code]
  helm-funcall-with-source([byte code])
  helm-interpret-value([byte code])
  [...]
```

I copied all of this by hand (beware of typos!) from `emacs -Q` on the latest MELPA helm.

The error looks pretty scary, but is non-fatal. (Although it pops up immediately on sourced that contain `helm-source-find-files`)

**Comment by thierryvolpiatto** [comment]
PythonNut <notifications@github.com> writes:

> When executing M-x helm-find-files, and deleting the entire contents
> of the minibuffer, I get a variety of errors.

Should be fixed now.

> Debugger entered--Lisp error: (wrong-type-argument stringp nil)
>   expand-file-name(nil)
>   helm-find-files-get-candidates()

This one comes from helm-find-files.

> And
>
> Debugger entered--Lisp error: (wrong-type-argument stringp nil)
>   expand-file-name(nil)
>   helm-find-files-get-candidates(confirm)

But this one comes from somewhere else (find-file or something else
helmized).

Also these errors happen only when debug-on-error is turned on.

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by PythonNut** [comment]
Ah. Sorry. I never confirmed that this was fixed. But it is.
