### ISSUE TITLE
Inconsistency with `helm-man`?

### ISSUE THREAD

**Issue by vspinu** [emacs-helm/helm#1019]
I want `helm-man-woman` to behave exactly as `helm-info` does. That is, 

  - Preselect candidate at point
  - Open the man page in the same  window as helm window.

I am adding ` (preselect . (symbol-at-point))` to that source and it doesn't work. 

To be honest, I am looking at that source and have no idea what is happening. What is `persistent-action`, `candidates-in-buffer`, `filtered-candidate-transformer` etc? There is no `helm-xxx` equivalent of those defined anywhere. Is there a doc for developers somewhere?

**Comment by thierryvolpiatto** [comment]
Vitalie Spinu <notifications@github.com> writes:

> I want helm-man-woman to behave exactly as helm-info does. That is,
>
>   * Preselect candidate at point

For this, in all helm command just hit M-n (or C-w several times).
I don't want the same behavior as `man' which is silly.
If you really want the same as the vanilla `man' command, enable
`helm-mode' and use M-x man.

>   * Open the man page in the same window as helm window.

You have several variables to configure the windows behavior in helm.

> I am adding (preselect . (symbol-at-point)) to that source and it doesn't work.

preselect is not a valid attribute.

> To be honest, I am looking at that source and have no idea what is
> happening. What is persistent-action, candidates-in-buffer,
> filtered-candidate-transformer etc?

With M-x helm-apropos search directly for these attributes or look at
the docstring of helm-source, helm-source-in-buffer etc...

> There is no helm-xxx equivalent of those defined anywhere. Is there a
> doc for developers somewhere?

I have started a section in the wiki, but it is not finished.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by vspinu** [comment]
> For this, in all helm command just hit M-n (or C-w several times). I don't want the same behavior as `man' which is silly.

I said I want the same UI as `helm-info`. I think info and man is conceptually very similar things and should provide same UI. 

What is silly in proposing the default candidate? With `helm-info` once you started typing the original narrowing disappears anyways, it's a perfect UI, really.

> You have several variables to configure the windows behavior in helm.

I am using those, but behavior of `heml-man` and `helm-info` is different. Info displays in the same window where the action was started, `helm-man` displays in other buffer.

Set `helm-split-window-default-side` to 'same and try `helm-info` and `helm-man-woman` to see what I mean. This is clearly a bug AFAIC.

> With M-x helm-apropos search directly for these attributes or look at the docstring of helm-source, helm-source-in-buffer etc.

Thanks! That was exactly the explanation that I was missing.

**Comment by vspinu** [comment]
> I said that I want the same UI as helm-info.

It's actually called `helm-info-at-point`, sorry. So I would like to have that behavior for all the helm help sources. Would that be possible?

**Comment by thierryvolpiatto** [comment]
Vitalie Spinu <notifications@github.com> writes:

> I said I want the same UI as helm-info. I think info and man is
> conceptually very similar things and should provide same UI.

You have to set yourself `Man-notify-method', I use "pushy" personally
and the man pages are popping up in the full window.

> What is silly in proposing the default candidate?

I misunderstand, I was referencing `man'.

Anyway you can use M-n with what we have actually.

I don't want to have the same behavior of helm info for this because we
may have too much candidates for this and preselection will fail unless
user set candidate-number-limit have a very hight value (which is not
what we want generally).

> I am using those, but behavior of heml-man and helm-info is
> different. Info displays in the same window where the action was
> started, helm-man displays in other buffer.

See above, use Man-notify-method.

> Set helm-split-window-default-side to 'same and try helm-info and
> helm-man-woman to see what I mean. This is clearly a bug AFAIC.

It is not, see above.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Thierry Volpiatto <thierry.volpiatto@gmail.com> writes:

> I don't want to have the same behavior of helm info for this because we
> may have too much candidates for this and preselection will fail unless
> user set candidate-number-limit have a very hight value (which is not
> what we want generally).

Forget to mention that most of the time (contrarily to Info) man is
called from an unrelated buffer with unrelated stuff at point.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by vspinu** [comment]
> You have to set yourself `Man-notify-method', I use "pushy" personally and the man pages are popping up in the full window.

Aha. Got it. Thanks!

> Anyway you can use M-n with what we have actually.

M-n is cool and I wish emacs default minibuffer completion would also have that (any ideas of how to achieve this?).

My point is that Helm has at least two nicer non-intrusive alternatives. First as in `helm-info-at-point` where the narrowing is happening but you still have the freedom to type whatever you want. Second, is as in `helm-apropos` where the candidate at point (if matched) is selected. 

IMO both of the above strategies are uniformly better than showing nothing. 

> Anyway you can use M-n with what we have actually. I don't want to have the same behavior of helm info for this because we may have too much candidates for this and preselection will fail unless user set candidate-number-limit have a very hight value (which is not what we want generally).

I don't quite understand the technicalities, but if you already can display all candidates and narrow fluently on user input, why would it break with preselection? Just display helm-candidate-number-limit and be done with it, isn't it that simple?

For me helm-man is instantious so I would like to at least have an option for narrowing by default.

> Forget to mention that most of the time (contrarily to Info) man is called from an unrelated buffer with unrelated stuff at point.

I have just installed [cppreference](https://github.com/jeaye/stdman) manpages and was planning to use `helm-man` as a dynamic help at point ;)  Not a big deal as such, I will probably end up writing a specialized source for that,  but I just want all my "helms" to behave consistently whenever possible.

Helm-occur also doesn't display anything by default, and I think it should.  Wouldn't it make sense to have a global option for the narrowing on startup?

**Comment by thierryvolpiatto** [comment]
Vitalie Spinu <notifications@github.com> writes:

> M-n is cool and I wish emacs default minibuffer completion would also
> have that (any ideas of how to achieve this?).

read-from-minibuffer, completing-read and friends have a DEFAULT option,
as soon you feed this option, M-n become available.

For helm, you may like also C-w.

> I don't quite understand the technicalities, but if you already can
> display all candidates and narrow fluently on user input, why would it
> break with preselection?  Just display helm-candidate-number-limit and
> be done with it, isn't it that simple?

Hmm, yes I see now what you want, just like helm-apropos.
helm-man.el is old and haven't been reworked, I will try to add these
feature while making its rewrite ASAP.

> I have just installed cppreference manpages and was planning to use
> helm-man as a dynamic help at point ;) Not a big deal as such, I will
> probably end up writing a specialized source for that, but I just want
> all my "helms" to behave consistently whenever possible.

Ok, so I understand why you want to narrow immediately with
thing-at-point.

> Helm-occur also doesn't display anything by default, and I think it
> should. Wouldn't it make sense to have a global option for the
> narrowing on startup?

This would be a good idea, the problem is that on huge buffers it is
not such a good idea, you may have a long delay before being able to
type in something.
The problem is the same with multiples buffers.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Vitalie Spinu <notifications@github.com> writes:

> I have just installed cppreference manpages and was planning to use
> helm-man as a dynamic help at point ;) Not a big deal as such, I will
> probably end up writing a specialized source for that, but I just want
> all my "helms" to behave consistently whenever possible.
>
> Helm-occur also doesn't display anything by default, and I think it
> should. Wouldn't it make sense to have a global option for the
> narrowing on startup?

Sorry I completely forget to tell you about
`helm-sources-using-default-as-input'.

You can add sources there to have the behavior you request.
I have added helm-source-man-pages to it by default.

HTH

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Thierry Volpiatto <thierry.volpiatto@gmail.com> writes:

> Vitalie Spinu <notifications@github.com> writes:
>
>> I have just installed cppreference manpages and was planning to use
>> helm-man as a dynamic help at point ;) Not a big deal as such, I will
>> probably end up writing a specialized source for that, but I just want
>> all my "helms" to behave consistently whenever possible.
>>
>> Helm-occur also doesn't display anything by default, and I think it
>> should. Wouldn't it make sense to have a global option for the
>> narrowing on startup?
>
> Sorry I completely forget to tell you about
> `helm-sources-using-default-as-input'.
>
> You can add sources there to have the behavior you request.
> I have added helm-source-man-pages to it by default.

And it works better than expected with helm-source-(m)occur.

(add-to-list 'helm-sources-using-default-as-input 'helm-source-occur)
(add-to-list 'helm-sources-using-default-as-input 'helm-source-moccur)

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by vspinu** [comment]
> And it works better than expected with helm-source-(m)occur. (add-to-list 'helm-sources-using-default-as-input 'helm-source-occur) (add-to-list 'helm-sources-using-default-as-input 'helm-source-moccur)

Thanks. That's definitely something.

But it has no effect for `man-woman`:

```
(add-to-list 'helm-sources-using-default-as-input 'helm-man-woman)
```

**Comment by thierryvolpiatto** [comment]
Vitalie Spinu <notifications@github.com> writes:

> But it has no effect for man-woman:
>
> (add-to-list 'helm-sources-using-default-as-input 'helm-man-woman)
                                                     ^^^^^^^^^^^^^^
                                                     not a source name
Use the source name i.e helm-source-man-pages.
But no need to add it yourself, it is now the default ;-).

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by vspinu** [comment]
> But no need to add it yourself, it is now the default ;-).

Nice. Thanks!
