### ISSUE TITLE
Error specifcying C-u prefix with helm-M-x

### ISSUE THREAD

**Issue by Jehops** [emacs-helm/helm#1020]
I'm trying emulate `C-u M-x align` with helm-M-x.  I do `M-x C-u` and I see `prefarg:4` in the modeline. Then I type 'a' and I get four 'a' characters in the mini-buffer.

**Comment by thierryvolpiatto** [comment]
Joseph Mingrone <notifications@github.com> writes:

> I'm trying emulate C-u M-x align with helm-M-x. I do M-x C-u and I see
> prefarg:4 in the modeline. Then I type 'a' and I get four 'a'
> characters in the mini-buffer.

This have been already discussed, when you hit C-u you enable prefix arg
for the next command beeing called.
So if you type M-x C-u and then type "a" what you do is just adding a
prefix arg to `self-insert-command' which have the expected result of
inserting "aaaa".

IOW type M-x, then start narrowing by typing in minibuffer and when
you find the command you want to run type in your prefix arg and RET.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
