### ISSUE TITLE
How is M-n ('"next-history-element") used to yank the symbol at point?

### ISSUE THREAD

**Issue by xuchunyang** [emacs-helm/helm#1021]
"next-history-element" is a command from simple.el, how does it work? Why not use a function like "helm-yank-text-at-point"?

It works fine, I just want to know how it works.

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

> "next-history-element" is a command from simple.el, how does it work?

See the documentation of read-from-minibuffer, the relevant part is:

,----[ read-from-minibuffer ]
|   Whatever the value of READ, DEFAULT-VALUE is made available via the
|   minibuffer history commands.  DEFAULT-VALUE can also be a list of
|   strings, in which case all the strings are available in the history,
|   and the first string is the default to `read' if READ is non-nil.
`----

And in helm it is the default arg of helm which is used for M-n.
When it is not specified in a helm call, the default value is
thing-at-point which is set in helm-read-pattern-maybe.

(helm :sources (helm-build-sync-source "test"
                 :candidates '(a b c d e))
      :buffer "*helm test*"
      :default '("c" "d"))

> Why not use a function like "helm-yank-text-at-point"?

It is a different thing which allow yanking from point.
e.g with foo-!bar where ! is the cursor, M-n will return "foo-bar" and
first hit on C-w will return "bar".

NOTE: there is a variable which allow C-w yanking the symbol at point,
but it is not enabled by default, is confusing and will be removed soon.


-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by xuchunyang** [comment]
I see, M-n ("next-history-element") is used to active the default value.

>> Why not use a function like "helm-yank-text-at-point"?

> It is a different thing which allow yanking from point.
> e.g with foo-!bar where ! is the cursor, M-n will return "foo-bar" and
> first hit on C-w will return "bar".
> 
> NOTE: there is a variable which allow C-w yanking the symbol at point,
> but it is not enabled by default, is confusing and will be removed soon.

I was wondering, to yank symbol-at-point, making a new command should clearer.
```elisp
(defun helm-yank-symbol-at-point ()
  (interactive)
  (with-helm-current-buffer
    (helm-set-pattern
     (concat
      helm-pattern (thing-at-point 'symbol)))))

(define-key helm-map [?\M-w] #'helm-yank-symbol-at-point)


```

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

> I was wondering, to yank symbol-at-point, making a new command should clearer.

No, M-n is the way to do for this.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by xuchunyang** [comment]
Ok.
