### ISSUE TITLE
open image file on helm-bookmark

### ISSUE THREAD

**Issue by Enrico68** [emacs-helm/helm#1022]
Hello,

I have several images bookmarked. When I use helm-bookmark to narrow the search and pressing `C-z` for persisten-action, I have just the annotation displayed not the image. If I want to see the image I have to press `Enter` loosing the helm-buffer. Is there a way to get the image file correctly display with helm-bookmark ?

**Comment by thierryvolpiatto** [comment]
Enrico Pirani <notifications@github.com> writes:

> Hello,
>
> I have several images bookmarked. When I use helm-bookmark to narrow
> the search and pressing C-z for persisten-action, I have just the
> annotation displayed not the image.

Not reproductible, either with helm-filtered-bookmarks and helm-bookmarks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by Enrico68** [comment]
If you dont annotate the bookmark helm displays correctly the image associated. But with annotation it  displays just the note not the image.

**Comment by thierryvolpiatto** [comment]
Enrico Pirani <notifications@github.com> writes:

> If you dont annotate the bookmark helm displays correctly the image
> associated. But with annotation it displays just the note not the
> image.

It doesn't here, I tried.
When you hit TAB, what is the first action popping up ?
To what C-z is binded in the helm-bookmark-map ?

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by Enrico68** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> It doesn't here, I tried.
> When you hit TAB, what is the first action popping up ?
> To what C-z is binded in the helm-bookmark-map ?

Yes the problem is that C-z is mapped to evil-state. Which variable I
need to change for mapping C-z
helm-persistent-action-use-special-display or  helm-persistent-action-display-window ?
> -- 
> Thierry
> Get my Gnupg key:
> gpg --keyserver pgp.mit.edu --recv-keys 59F29997 
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/emacs-helm/helm/issues/1022#issuecomment-103554999

-- 
Dr. Enrico Pirani
Medico Chirurgo
Specialista in Chirurgia Toracica
FMH Chirurgia Cardiaca 
Via Matteotti 7
35042 Este (Padova)

Cell:392-6224668
Tel: 0429-17660135

  Ai sensi del D.Lgs. 196/2003 si precisa che le informazioni contenute in
  questo messaggio sono riservate ed a uso esclusivo del destinatario.
  Qualora il messaggio Le fosse pervenuto per errore, La invitiamo ad
  eliminarlo senza copiarlo e a non inoltrarlo a terzi, dandocene gentilmente
  comunicazione. Grazie.

  Pursuant to Legislative Decree No. 196/2003, you are hereby informed that
  this message contains confidential information intended only for the use of
  the addressee. If you are not the addressee, and have received this message
  by mistake, please delete it and immediately notify us. You may not copy or

**Comment by thierryvolpiatto** [comment]
Enrico Pirani <notifications@github.com> writes:

> Thierry Volpiatto <notifications@github.com> writes:
>
>> It doesn't here, I tried.
>> When you hit TAB, what is the first action popping up ?
>> To what C-z is binded in the helm-bookmark-map ?
>
> Yes the problem is that C-z is mapped to evil-state.

Ah! Unfortunately I don't know evil enough to help you.

> Which variable I need to change for mapping C-z
> helm-persistent-action-use-special-display or
> helm-persistent-action-display-window ?

None of them.

Note that `helm-persistent-action-display-window` is a function and not
a variable.

`helm-persistent-action-use-special-display` will use a new frame to
display your persistent action window if the buffer you are displaying
in this window is matched in `special-display-regexps` or is one of
`special-display-buffer-names`.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by Enrico68** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> Ah! Unfortunately I don't know evil enough to help you.
>

Thanks Thierry,

I will try to remap evil-state...
> -- 
> Thierry
> Get my Gnupg key:
> gpg --keyserver pgp.mit.edu --recv-keys 59F29997 
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/emacs-helm/helm/issues/1022#issuecomment-103589372

-- 
Dr. Enrico Pirani
Medico Chirurgo
Specialista in Chirurgia Toracica
FMH Chirurgia Cardiaca 
Via Matteotti 7
35042 Este (Padova)

Cell:392-6224668
Tel: 0429-17660135

  Ai sensi del D.Lgs. 196/2003 si precisa che le informazioni contenute in
  questo messaggio sono riservate ed a uso esclusivo del destinatario.
  Qualora il messaggio Le fosse pervenuto per errore, La invitiamo ad
  eliminarlo senza copiarlo e a non inoltrarlo a terzi, dandocene gentilmente
  comunicazione. Grazie.

  Pursuant to Legislative Decree No. 196/2003, you are hereby informed that
  this message contains confidential information intended only for the use of
  the addressee. If you are not the addressee, and have received this message
  by mistake, please delete it and immediately notify us. You may not copy or

**Comment by thierryvolpiatto** [comment]
Ok closing for now, feel free to reopen if you still have problems.
