### ISSUE TITLE
helm-projectile crashes after update 1.7.1

### ISSUE THREAD

**Issue by lpsz-** [emacs-helm/helm#1023]
After upgrading to helm 1.7.1 I'm getting this error when using helm-projectile it crashes with this error 

    Symbol's function definition is void: async-bytecomp-package-mode

package list output is 

    helm               1.7.1        installed  Helm is an Emacs incremental and narrowing framework

I'm using GNU Emacs 24.3.1.

I guess is related with [this](https://github.com/emacs-helm/helm/commit/2774d30b5ead938fee1bbcd86e2f35f0acec6564) but not sure.

**Comment by tuhdo** [comment]
If so, you should consider upgrading to Emacs 24.5; before that, reinstalling Helm and Helm Projectile first.  And that's not a crash; it is simply an error returned when a function definition not found.

**Comment by thierryvolpiatto** [comment]
Abel González <notifications@github.com> writes:

> After upgrading to helm 1.7.1 I'm getting this error when using helm-projectile it crashes with this error
>
> Symbol's function definition is void: async-bytecomp-package-mode

Try reinstalling both helm and helm-projectile.
Also be sure you restart emacs when upgrading a package.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by lpsz-** [comment]
Thanks, I tried upgrading emacs and it worked.
