### ISSUE TITLE
Using helm 1.7.1 with use-package it gives me issues and the keybindings do not work anymore

### ISSUE THREAD

**Issue by azynheira** [emacs-helm/helm#1025]
Using helm 1.7.1 with use-package it gives me issues and the key binding do not work anymore. With helm 1.7.0 no problem was there. Following is my 'use-package' statement for configuring helm.

(use-package helm
  :ensure helm
  :diminish helm-mode
  :pin melpa-stable
  :init (progn
          (require 'helm-config)
          (require 'helm-grep)
          (setq helm-idle-delay 0.0        ; update fast sources immediately (doesn't).
                helm-input-idle-delay 0.01 ; this actually updates things reeeelatively quickly.
                helm-scroll-amount 4 ; scroll 4 lines other window using M-<next>/M-<prior>
                helm-quick-update t  ; do not display invisible candidates
                helm-ff-search-library-in-sexp t ; search for library in `require' and `declare-function' sexp.
                helm-split-window-in-side-p t ;; open helm buffer inside current window, not occupy whole other window
                helm-candidate-number-limit 500 ; limit the number of displayed canidates
                helm-ff-file-name-history-use-recentf t
                helm-move-to-line-cycle-in-source t ; move to end or beginning of source when reaching top or bottom of source.
                helm-buffers-fuzzy-matching t ; fuzzy matching buffer names when non-nil - useful in helm-mini that lists buffers
                helm-recentf-fuzzy-match t
                helm-M-x-requires-pattern nil
                helm-ff-skip-boring-files t
                helm-M-x-fuzzy-match t)
          (add-to-list 'helm-sources-using-default-as-input 'helm-source-man-pages)
          ;; The default "C-x c" is quite close to "C-x C-c", which quits Emacs.
          ;; Changed to "C-c h". Note: We must set "C-c h" globally, because we
          ;; cannot change `helm-command-prefix-key' once `helm-config' is loaded.
          (global-set-key (kbd "C-c h") 'helm-command-prefix)
          (global-unset-key (kbd "C-x c"))

          (when (executable-find "curl")
            (setq helm-google-suggest-use-curl-p t)))
  :bind (("C-x b" . helm-mini)
         ("C-h f"  . helm-apropos)
         ("C-x C-b" . helm-buffers-list)
         ("M-x" . helm-M-x)
         ("M-y"  . helm-show-kill-ring)
         ("C-c h C-c w" . helm-wikipedia-suggest)
         ("C-c h o" . helm-occur)
         ("C-c h x" . helm-register)
         ("C-h C-l" . helm-locate-library)
         ("C-h SPC" . helm-all-mark-rings)
         ("C-h r" . helm-info-emacs)
         ("C-x C-f" . helm-find-files)
         ("C-x r j" . jump-to-register)
         ("C-x C-r" . helm-recentf))

  :config (progn
            (define-key helm-map (kbd "<tab>") 'helm-execute-persistent-action) ; rebihnd tab to do persistent action
            (define-key helm-map (kbd "C-i") 'helm-execute-persistent-action) ; make TAB works in terminal
            (define-key helm-map (kbd "C-z")  'helm-select-action) ; list actions using C-z

            (define-key helm-grep-mode-map (kbd "<return>")  'helm-grep-mode-jump-other-window)
            (define-key helm-grep-mode-map (kbd "n")  'helm-grep-mode-jump-other-window-forward)
            (define-key helm-grep-mode-map (kbd "p")  'helm-grep-mode-jump-other-window-backward)

            (define-key 'help-command (kbd "C-f") 'helm-apropos)
            (define-key 'help-command (kbd "r") 'helm-info-emacs)
            (define-key 'help-command (kbd "C-l") 'helm-locate-library)
            (custom-set-faces
             '(helm-selection ((t (:background "ForestGreen" :foreground "black")))))

            (helm-mode)
            (helm-autoresize-mode 1)))

I am using Emacs 24.5 compiled from source on Elementary OS Freya. helm was installed from ELPA via 'use-package'.

**Comment by thierryvolpiatto** [comment]
Pedro Gomes <notifications@github.com> writes:

> Using helm 1.7.1 with use-package it gives me issues

Which issues? bugreport?  backtrace?

> and the key binding do not work anymore.

Which keybindings? Why?

> With helm 1.7.0 no problem was there. Following is my 'use-package'
> statement for configuring helm.

Please try helm from emacs-helm.sh, if it works correctly, fix your
use-package config in consequence.
I am not in charge of fixing use-package config, I don't know how it
works.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by azynheira** [comment]
I know that. I just reported it, since it might hide other issues in helm.

A fundamental keybind that does not work is 'M-x'

**Comment by thierryvolpiatto** [comment]
Pedro Gomes <notifications@github.com> writes:

> I know that. I just reported it, since it might hide other issues in helm.
>
> A fundamental keybind that does not work is 'M-x'

Did you try from ./emacs-helm.sh ?

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by azynheira** [comment]
Hi,
Using ./emacs-helm.sh  works :)

I have this error on the *Warning* buffer which I forgot to mention yesterday,
'Error (use-package): helm :init: Symbol's function definition is void: async-bytecomp-package-mode Warning (initialization): An error occurred while loading `/home/pedrog/.emacs.d/init.el':'

Which I traced back to line 26 of helm-config.el. I have async-1.2 installed via elpa.

**Comment by thierryvolpiatto** [comment]
Pedro Gomes <notifications@github.com> writes:

> Hi,
> Using ./emacs-helm.sh works :)
>
> I have this error on the Warning buffer which I forgot to mention yesterday,
> 'Error (use-package): helm :init: Symbol's function definition is void: async-bytecomp-package-mode Warning (initialization): An error occurred while loading `/home/
> pedrog/.emacs.d/init.el':'
>
> Which I traced back to line 26 of helm-config.el. I have async-1.2 installed via elpa.

Ah! I think I understand the problem (which is the same as #1023), I
guess you are using melpa-stable right ?
If so because I haven't tagged async yet people who use stable version of
melpa are using an async package that doesn't have
async-bytecomp-package-mode.

I will tag right now async package, and as soon you can sync with melpa,
it should work.

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by azynheira** [comment]
Correct I am using melpa-stable. I will wait for the tag and try again!

Thanks

**Comment by azynheira** [comment]
Rock and Roll ! Its working fine with async-1.3. 

Maybe it could be a good idea to change the dependencies for helm-1.7.1 in elpa to refer to async-1.3 correct?

Thanks
