### ISSUE TITLE
Specific keybinding for one Helm source only? 

### ISSUE THREAD

**Issue by ReneFroger** [emacs-helm/helm#1026]
When I do use `helm-colors`, I would like to bind the `helm-color-run-insert-rgb` to RET when I'm inside helm-colors.                                
When I look it up in the documentation, there is the functionality of `helm-map`. But this affects all helm sources, which I clearly don't want it. I would like to use this keybinding for the source `helm-colors` only.  It seems there is no `helm-colors-map` or something. 

Any suggestion? 

Thanks in advance.

**Comment by michael-heerdegen** [comment]
You can get the same effect with just reordering the actions of the source, so that helm-color-run-insert-rgb is the first action. That would be the cleaner approach I think. The first action is always the one that is executed when hitting RET.  You can do it like this:

```
(with-eval-after-load 'helm-color
  (let* ((action-list (helm-attr 'action helm-source-colors))
         (action (rassq 'helm-color-insert-rgb action-list)))
    (helm-attrset 'action (cons action (delq action action-list))  helm-source-colors)))
```

**Comment by ReneFroger** [comment]
@michael-heerdegen, I'm trying to learn from it, in order to figure my way out of it. But you still manage to amaze me with your clever Lisps. 

My issue is solved as now. Thanks for that, I really appreciate it. 

(May I ask how you get the idea of the functions such as action-list/attrset/rassq? I never saw them in the documentation.. . )

**Comment by michael-heerdegen** [comment]
ReneFroger <notifications@github.com> writes:

> (May I ask how you get the idea of the functions such as
> action-list/attrset/rassq? I never saw them in the documentation.. . )

Configuring sources' action lists is something that is not yet easy to
do for the normal user without knowing internals (that are not in the
docs) - see also the related #781.  This can surely be improved in
general.  I've read the sources, so I know how to hack it, that's all.


Regards,

Michael.
