### ISSUE TITLE
Empty completion buffer in geiser.

### ISSUE THREAD

**Issue by duud** [emacs-helm/helm#1030]
Here are the affected functions:
    
    (add-to-list 'helm-completing-read-handlers-alist '(geiser-doc-symbol-at-point . nil))
    (add-to-list 'helm-completing-read-handlers-alist '(geiser-doc-module . nil))
    (add-to-list 'helm-completing-read-handlers-alist '(geiser-doc-look-up-manual . nil))

I can't debug this myself so I post it here - maybe it's something trivial.

**Comment by thierryvolpiatto** [comment]
duud <notifications@github.com> writes:

> Here are the affected functions:
>
> (add-to-list 'helm-completing-read-handlers-alist '(geiser-doc-symbol-at-point . nil))
> (add-to-list 'helm-completing-read-handlers-alist '(geiser-doc-module . nil))
> (add-to-list 'helm-completing-read-handlers-alist '(geiser-doc-look-up-manual . nil))

This have for effect to disable helm completions for these functions.
So what do you expect ?

> I can't debug this myself so I post it here - maybe it's something trivial.

You will have to be more explicit if you want somebody help you.
Try first to see if completion on your functions works with helm
disabled (which is the case with the code above).

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by duud** [comment]
Sorry if I wasn't precise enough. The intention of the above code was to show which functions I had to disable since they aren't working with helm. All of the 3 functions work properly when helm is disabled. With helm enabled I'm getting an empty completion buffer.

**Comment by thierryvolpiatto** [comment]
duud <notifications@github.com> writes:

> Sorry if I wasn't precise enough. The intention of the above code was
> to show which functions I had to disable since they aren't working
> with helm. All of the 3 functions work properly when helm is
> disabled. With helm enabled I'm getting an empty completion buffer.

The problem was the completion code should be called from the related
buffer, in our case the REPL or a buffer linked to it.

Should work now, have a look.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by duud** [comment]
That was fast....
It works now as expected
Thx

**Comment by thierryvolpiatto** [comment]
Good ;-) Thanks.
