### ISSUE TITLE
Disable helm completion for multi-occur by default? Its prompt is very confusing

### ISSUE THREAD

**Issue by xuchunyang** [emacs-helm/helm#1031]
I have the following in my init.el, but I want to know if we can disable it by default

```lisp
(add-to-list 'helm-completing-read-handlers-alist
             '(multi-occur . nil))
```

**Comment by xuchunyang** [comment]
I decide to use helm-multi-occur instead, sorry for the interrupt.

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

> I decide to use helm-multi-occur instead, sorry for the interrupt.

Yes you have better time, even better use M-x helm-buffers-list and C-s
(after marking some candidates).
You can narrow down your candidates before lauching multi occur with
"@", see the documentation of helm-buffers-list for more infos (C-c ?).

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by xuchunyang** [comment]
Great! Thanks for the tip.
