### ISSUE TITLE
Problem on using more than one helm-source-buffers objects at one time

### ISSUE THREAD

**Issue by xuchunyang** [emacs-helm/helm#1034]
It's unable to use more than one helm-source-buffers objects, which are all built via `:buffer-list`, for example:

```elisp
(helm :sources (list (helm-make-source "AAA" 'helm-source-buffers
                       :buffer-list (lambda () '("*scratch*")))
                     (helm-make-source "BBB" 'helm-source-buffers
                       :buffer-list (lambda () '("*Messages*")))))
```

(I guess because AAA and BBB use  the `helm-buffers-list-cache` variable at the same time)

This issue is related to https://github.com/bbatsov/projectile/issues/750

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

> It's unable to use more than one helm-source-buffers objects, which are all built via :buffer-list, for example:
>
> (helm :sources (list (helm-make-source "AAA" 'helm-source-buffers
>                        :buffer-list (lambda () '("*scratch*")))
>                      (helm-make-source "BBB" 'helm-source-buffers
>                        :buffer-list (lambda () '("*Messages*")))))
>
> (I guess because AAA and BBB use the helm-buffers-list-cache variable at the same time)

Well yes, probably, but you will have to live with this...
I have no motivation to fix this.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

> (I guess because AAA and BBB use the helm-buffers-list-cache variable at the same time)

BTW you can use another init function using no cache.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by xuchunyang** [comment]
OK.
