### ISSUE TITLE
Font size in helm buffers

### ISSUE THREAD

**Issue by duud** [emacs-helm/helm#1038]
Is ther a way to set the font size of candidates in a helm buffer?
I couldn't find any customization for this.
I don't like this method, but currently I'm using:

    (defun helm-buffer-face-mode ()
      "Helm buffer face"
      (interactive)
      (setq line-spacing 2)
      (buffer-face-set '(:family "Source Code Pro" :height 100)))

    (add-hook 'helm-update-hook 'helm-buffer-face-mode)

**Comment by thierryvolpiatto** [comment]
duud <notifications@github.com> writes:

> Is ther a way to set the font size of candidates in a helm buffer?

No.

> I don't like this method, but currently I'm using:

Good, but not supported in previous emacs versions.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
duud <notifications@github.com> writes:

> Is ther a way to set the font size of candidates in a helm buffer?

No.

> I couldn't find any customization for this.

There is not yet for compatibility with older emacs.

> I don't like this method, but currently I'm using:
>
> (defun helm-buffer-face-mode ()
>   "Helm buffer face"
>   (interactive)
>   (setq line-spacing 2)
>   (buffer-face-set '(:family "Source Code Pro" :height 100)))

Good, but wrap your code in `with-helm-buffer`:

     (defun helm-buffer-face-mode ()
       "Helm buffer face"
       (interactive)
       (with-helm-buffer
         (setq line-spacing 2)
         (buffer-face-set '(:family "Source Code Pro" :height 100))))

> (add-hook 'helm-update-hook 'helm-buffer-face-mode)

Probably using helm-after-initialize-hook is better.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by xuchunyang** [comment]
> Probably using helm-after-initialize-hook is better.

Off-topic: I have a question on this hook, its docstring says "This hook run inside ‘helm-buffer’ once created." Does it mean that function in this hook has `helm-buffer` as its current buffer? But the following demo tells me it's not true (its current buffer is `helm-current-buffer`):
```elisp
(add-hook 'helm-after-initialize-hook (lambda () (message (buffer-name))))
```
or am I misunderstanding anything?

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

>     Probably using helm-after-initialize-hook is better.
>    
> Off-topic: I have a question on this hook, its docstring says "This
> hook run inside ‘helm-buffer’ once created." Does it mean that
> function in this hook has helm-buffer as its current buffer? But the
> following demo tells me it's not true (its current buffer is
> helm-current-buffer):
>
> (add-hook 'helm-after-initialize-hook (lambda () (message
> (buffer-name))))
>
> or am I misunderstanding anything?

You're right the docstring is wrong, you have to ensure your code run in
the helm-buffer.

Will fix soon.

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by duud** [comment]
Thanks
