### ISSUE TITLE
Can't kill buffers

### ISSUE THREAD

**Issue by angrybakon** [emacs-helm/helm#1039]
I'm displaying the list of cached buffers with `helm-buffers-list `. I tried to kill a buffer with `C-c k`, it messaged:

```text
Killed: views.py<directo...	    159                 Python  (in `~/path/to/directory/')
```

But when I display the list again, the buffer is still there.

**Comment by thierryvolpiatto** [comment]
`C-c k` is undefined, use `C-c d`.
To avoid similar questions, please read the doc via `C-c ?`.

**Comment by angrybakon** [comment]
I actually found `C-c C-k` with the documentation (typo in the question, I meant `C-c C-k`, not `C-c k`.

`C-c d` works, thanks.

**Comment by thierryvolpiatto** [comment]
Mathieu Marques <notifications@github.com> writes:

> I actually found C-c C-k with the documentation (typo in the question, I meant C-c C-k, not C-c k.

`(C-u) C-c C-k` will copy the current selection in kill-ring.
This is not specific to helm-buffers-list so I don't know which
documentation you looked at.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by angrybakon** [comment]
`helm-kill-selection-and-quit`. I naively searched for "kill" in the documentation, and misunderstood its meaning as it is closer to *cut*. Thanks for your time :)
