### ISSUE TITLE
Change the display of major modes in the buffer list

### ISSUE THREAD

**Issue by angrybakon** [emacs-helm/helm#1040]
Listing buffers with `helm-buffers-list`, can we have the modes displayed with their [`delight`][10]ed strings ?

![screen shot 2015-05-29 at 10 27 42](https://cloud.githubusercontent.com/assets/5608624/7879104/8526cb36-05ed-11e5-8a85-b8ec1ef0f63b.png)

[10]: http://www.emacswiki.org/emacs/DelightedModes

**Comment by thierryvolpiatto** [comment]
No.

**Comment by angrybakon** [comment]
Why not ? It could be an option, leaving no undesired behavior to those who don't use it.

**Comment by michael-heerdegen** [comment]
I too think it's not worth a (boolean type) option.
OTOH it could be worth to factor out
```
(with-current-buffer buffer (format-mode-line mode-name))
```
(appears multiple times in the code) and make it a defun or the value of a defcustom.

Dunno if Thierry would find that acceptable.  If he does, I guess we could help him with a PR.

**Comment by angrybakon** [comment]
> I too think it's not worth a (boolean type) option.

I know it sounds selfish, but those who don't have the time and/or will to dig deeper in Emacs Lisp can't really appreciate Emacs' extensibility to its fullest, even for such a minor change.

But yeah I can live without it :)

**Comment by michael-heerdegen** [comment]
> > I too think it's not worth a (boolean type) option.

> I know it sounds selfish, but those who don't have the time and/or
> will to dig deeper in Emacs Lisp can't really appreciate Emacs'
> extensibility to its fullest, even for such a minor change.

I didn't say making possible what you want is not useful.  Personally,
I'm pro a change.  I just meant a boolean option is not good.  You like
"DelightedModes".  Others might prefer "DiminishedModes", or a different
package, or use their own hack.  That's why a boolean option is not
useful here.

**Comment by angrybakon** [comment]
Ok I didn't give enough details (and I didn't talk about a boolean option specifically).

I'm not your regular Elisp guru and I don't know how Diminish and Delight actually work. But they both are configured in init.el and they both alter the end result which lives in the mode-line. So from my point of view it looked definitely possible for helm to display that end result instead of the package's default mode string.

I can be wrong. Again I'm no Emacs Lisp guru, so when Thierry said no I instantly agreed. But I like to understand things :)

**Comment by michael-heerdegen** [comment]
I didn't say it's impossible.  Actually I was just thinking about how to help you.

Looking at the code of "delight.el", it's delight itself that prevents helm to get the delighted mode name.  It does this by a defadvice of format-mode-line.  So your issue IMHO should better be fixed in "delight.el".

Anyway, you can easily get what you want by just redefining this advice:

```
(defadvice format-mode-line (around delighted-modes-are-glum activate)
  (let ((inhibit-mode-name-delight
         (not (eq this-command 'helm-buffers-list))))
    ad-do-it))
```

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> I didn't say it's impossible. Actually I was just thinking about how
> to help you.
>
> Looking at the code of "delight.el", it's delight itself that prevents
> helm to get the delighted mode name. It does this by a defadvice of
> format-mode-line. So your issue IMHO should better be fixed in
> "delight.el".

I didn't look at the code of delight.el, but I tend to agree with
Michael.

Ideally these packages, delight and the other (don't
remember the one you mentionned Michael) should define a mode
that modify the behavior of format-mode-line.
IOW on our side we should change nothing, enabling one of the modes
should provide the desired effect.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
