### ISSUE TITLE
allow sort by modification time as an option in `helm-find-files'

### ISSUE THREAD

**Issue by holtzermann17** [emacs-helm/helm#1041]
I've come up with a bit of code to allow sorting the file list by modification time.  This implementation isn't ideal, since users may want this behavior only _optionally_ and may like to be able to switch between the alphabetical order and modification-time order.  However, it shows that modification time ordering is straightforward. I also think it's very useful!

``` diff
diff --git a/helm-files.el b/helm-files.el
index d1e927f..d8349e8 100644
--- a/helm-files.el
+++ b/helm-files.el
@@ -1672,8 +1672,12 @@ systems."
                    (expand-file-name directory)))
   (let* (file-error
          (ls   (condition-case err
-                   (directory-files
-                    directory full directory-files-no-dot-files-regexp)
+                   (mapcar #'car
+                           (sort (directory-files-and-attributes
+                                  directory full
+                                  directory-files-no-dot-files-regexp t)
+                                 #'(lambda (x y)
+                                     (not (time-less-p (nth 6 x) (nth 6 y))))))
                  ;; Handle file-error from here for Windows
                  ;; because predicates like `file-readable-p' and friends
                  ;; seem broken on emacs for Windows systems (always returns t).
```

**Comment by thierryvolpiatto** [comment]
Thanks, but I am not interested by such sorting, at least in helm-find-files.
Also we are already sorting candidates (after narrowing) for fuzzy matching and adding more
sorting would decrease performances on large directories.
Anyway such sorting should happen in a transformer, not here (the effect of your sorting function will be defeated as soon as you narrow down candidates).
Be sure I appreciate your contribution though ;-)

**Comment by holtzermann17** [comment]
> Anyway such sorting should happen in a transformer, not here (the effect of your sorting function will be defeated as soon as you narrow down candidates).

Ah, thanks I didn't notice that.  Still, the patch lets me look for files in a combination of two ways ("`ls -lt | helm`" in addition to the normal Helm fuzzy match), and I think both are useful.  I completely understand if you don't want to incorporate the change into Helm.  If I can figure out how to do it, as an exercise I may rewrite it as a transformer.  Thanks for the feedback.

**Comment by thierryvolpiatto** [comment]
Jonathan Gregory <notifications@github.com> writes:

> Another option, instead of sorting all candidates, is to preselect the
> last modified file. This is useful, for example, when exporting Org
> files to latex.  In this case I think helm-find-files should preselect
> the corresponding .tex file. This is what the ido-sort-mtime package
> does for Ido, so here's a first attempt at doing something similar
> with helm:

Thanks for your code, but I don't think it is the way to go, such code
is incredibly costly to know the name of a file you already know
(i.e. foo.org will be foo.tex), I could at least add a command to sort
the full list by file-newer-than-file-p for such situations.

> (defvar helm-preselect-list
>   (lambda ()
>     (cl-remove-if (lambda (elt)
>                     (or (string-match "#" elt)   ;skip autosave files
>                         (backup-file-name-p elt) ;skip backup files
>                         (file-directory-p elt)   ;skip directories
>                         (file-symlink-p elt)))   ;skip symlink files
>                   (helm-list-directory "."))))
>
> (defun helm-last-modified-file ()
>   "Return the last modified file in the current directory."
>   (file-name-nondirectory
>    (car (sort (funcall helm-preselect-list)
>               (lambda (a b)
>                 (file-newer-than-file-p a b))))))
>
> (helm-find-files-1 "./" (helm-last-modified-file)))
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.*


--
Thierry

**Comment by jagrg** [comment]
You could sort the list using file-newer-than-file-p, but you would still need to filter those files if that's what you mean by costly. For example, the .git directory is updated frequently but you probably don't want that preselected. Also, I used the tex file as an example. The most recent file could be anything. What I'm proposing is to sort all files and return the first on the list, so I'm not sure how that's different from what you're suggesting.

**Comment by holtzermann17** [comment]
Given that this is being discussed now, I'm reopening the issue -- still a fan of having entries sorted by date.  

Maybe we could use [partial sorting](https://en.wikipedia.org/wiki/Partial_sorting) to get the 10 most recent items to float to the top.  That seems better from a user standpoint than just the 1 most recent, and also more efficient than sorting everything only to discard the information gained.

**Comment by thierryvolpiatto** [comment]
Have a try with this patch (not fully tested):

``` diff
diff --git a/helm-files.el b/helm-files.el
index ab27517..bd0f879 100644
--- a/helm-files.el
+++ b/helm-files.el
@@ -368,6 +368,16 @@ directories but is more portable.
 NOTE that `helm-list-dir-external' needs ls and awk as dependencies."
   :type 'function
   :group 'helm-files)
+
+(defcustom helm-ff-initial-sort-method nil
+  "Sort method to use when initially listing a directory.
+Note that this doesn't affect the listing when matching inside the
+directory (i.e. filenames)."
+  :group 'helm-files
+  :type '(choice
+          (const :tag "alphabetically" nil)
+          (const :tag "newest" newest)
+          (const :tag "size" size)))
 
 ;;; Faces
 ;;
@@ -2452,12 +2462,28 @@ If DIRECTORY is remote use `helm-list-directory-function' otherwise use
          (helm-list-directory-function
           (if (and remote (not (string= remote "ftp")))
               helm-list-directory-function
-            #'helm-list-dir-lisp)))
+            #'helm-list-dir-lisp))
+         (remote-fn-p (eq helm-list-directory-function
+                          'helm-list-dir-external))
+         (sort-method (cl-case helm-ff-initial-sort-method
+                        (newest (if (and remote remote-fn-p)
+                                    "-t" #'file-newer-than-file-p))
+                        (size (if (and remote remote-fn-p)
+                                  "-S" #'helm-ff-file-larger-that-file-p))
+                        (t nil))))
     (if remote
-        (funcall helm-list-directory-function directory)
-      (directory-files directory t directory-files-no-dot-files-regexp))))
-
-(defun helm-list-dir-lisp (directory)
+        (funcall helm-list-directory-function directory sort-method)
+      (if sort-method
+          (sort (directory-files directory t directory-files-no-dot-files-regexp)
+                sort-method)
+        (directory-files directory t directory-files-no-dot-files-regexp)))))
+
+(defsubst helm-ff-file-larger-that-file-p (f1 f2)
+  (let ((attr1 (file-attributes f1))
+        (attr2 (file-attributes f2)))
+    (> (nth 7 attr1) (nth 7 attr2))))
+
+(defun helm-list-dir-lisp (directory &optional sort-method)
   "List DIRECTORY with `file-name-all-completions' as backend.
 
 Add a `helm-ff-dir' property on each fname ending with \"/\"."
@@ -2466,7 +2492,7 @@ Add a `helm-ff-dir' property on each fname ending with \"/\"."
   ;; the displayed files will be plain wrong in this case, even worst
   ;; the filenames will be splitted in two or more filenames.
   (cl-loop for f in (sort (file-name-all-completions "" directory)
-                          'string-lessp)
+                          (or sort-method 'string-lessp))
            unless (or (string= f "")
                       (member f '("./" "../"))
                       ;; Ignore the tramp names from /
@@ -2478,7 +2504,7 @@ Add a `helm-ff-dir' property on each fname ending with \"/\"."
            else collect (propertize (expand-file-name f directory)
                                     'helm-ff-file t)))
 
-(defun helm-list-dir-external (dir)
+(defun helm-list-dir-external (dir &optional sort-method)
   "List directory DIR with external shell command as backend.
 
 This function is fast enough to be used for remote files and save the
@@ -2497,7 +2523,8 @@ transformer."
                   ;; "foo*" for the real file foo. The downside is
                   ;; that we need an extra step to remove the quotes
                   ;; at the end which impact performances.
-                  "ls -A -1 -F -b -Q | awk -v dir=%s '{print dir $1}'"
+                  "ls -A -1 -F -b -Q %s | awk -v dir=%s '{print dir $1}'"
+                  (or sort-method "")
                   (shell-quote-argument default-directory))
                  nil t nil)
                 0)
```

**Comment by thierryvolpiatto** [comment]
To change sorting use something like `(setq helm-ff-initial-sort-method 'newest)` or even better use the customize interface.

**Comment by thierryvolpiatto** [comment]
And now adding command to change sorting is easy with something like this:

``` elisp
(defun helm-ff-sort-by-size ()
  (interactive)
  (setq helm-ff-initial-sort-method 'size)
  (helm-update))
(define-key helm-find-files-map (kbd "S-<f1>") 'helm-ff-sort-by-size)

(defun helm-ff-sort-by-newest ()
  (interactive)
  (setq helm-ff-initial-sort-method 'newest)
  (helm-update))
(define-key helm-find-files-map (kbd "S-<f2>") 'helm-ff-sort-by-newest)

(defun helm-ff-sort-alpha ()
  (interactive)
  (setq helm-ff-initial-sort-method nil)
  (helm-update))
(define-key helm-find-files-map (kbd "S-<f3>") 'helm-ff-sort-alpha)
```

**Comment by jagrg** [comment]
I'm giving your patch a try and I'll see how it goes. Works well so far with the sort set to newest, it does what it says, although to make sorting smarter we'd probably have to exclude some files from being sorted. For example, ATM I have projectile-bookmarks.eld on top, which is updated in the background automatically, and is not what I want to see.

BTW I'm not sure if this is any different from using file-newer-than-file-p or the other sorting methods mentioned above, but another way of preselecting recent files is to use recentf-list:

(helm-find-files-1 "./" (file-name-nondirectory (car recentf-list)))

I'm not familiar with partial sorting, but maybe we could get the first 10 files in recentf-list and move them to the top of the list.

**Comment by thierryvolpiatto** [comment]
Jonathan Gregory <notifications@github.com> writes:

> I'm giving your patch a try and I'll see how it goes. Works well so
> far with the sort set to newest, it does what it says, although to
> make sorting smarter we'd probably have to exclude some files from
> being sorted. For example, ATM I have projectile-bookmarks.eld on top,
> which is updated in the background automatically, and is not what I
> want to see.

Probably you can exclude this kind of files with the boring regexp.
If not enough you can add a function of your choice to
filtered-candidate-transformer attribute using defmethod and
helm-setup-user-source, see
https://github.com/emacs-helm/helm/wiki/FAQ#why-is-a-customizable-helm-source-nil
and
https://github.com/thierryvolpiatto/emacs-tv-config/blob/master/init-helm.el#L345
for examples.

> BTW I'm not sure if this is any different from using
> file-newer-than-file-p

We do use file-newer-than-file-p.

> or the other sorting methods mentioned above, but another way of
> preselecting recent files is to use recentf-list:

No as long as you don't visit a file with emacs your file will not be listed
in file history, note that you can access file history (not directory
history) with `C-c h`.

> (helm-find-files-1 "./" (file-name-nondirectory (car recentf-list)))
>
> I'm not familiar with partial sorting, but maybe we could get the
> first 10 files in recentf-list and move them to the top of the list.

We have not such partial sorting function in emacs, the only way to
implement one is to use elisp and I doubt the function (even if it is
doing partial sorting) will be faster than the emacs `sort` function
implemented in C and quite fast.

--
Thierry

**Comment by jagrg** [comment]
The sorting doesn't always work with helm-ff-initial-sort-method set to newest. Sometimes the first line is preselected (the one that ends with a dot) and sometimes it selects not the last modified file but the penultimate (e.g. when I try to open the .tex file after calling C-c C-e l l from an Org file). I'm not sure what the problem is, and I will try to trace it more carefully, but the following code works well in case it helps:

(helm-find-files-1 "./" (string-trim (shell-command-to-string "ls -t $* 2> /dev/null | head -n 1")))

**Comment by thierryvolpiatto** [comment]
Jonathan Gregory <notifications@github.com> writes:

> The sorting doesn't always work with helm-ff-initial-sort-method set
> to newest. Sometimes the first line is preselected (the one that ends
> with a dot) and sometimes it selects not the last modified file but
> the penultimate (e.g. when I try to open the .tex file after calling
> C-c C-e l l from an Org file).

Note that sorting with different methods is available onlt in
helm-find-files.
Don't know what `C-c C-e l l` is but I guess it is just a read-file-name
or such helmized, but not helm-find-files.

> I'm not sure what the problem is, and I will try to trace it more
> carefully, but the following code works well in case it helps:
>
> (helm-find-files-1 "./" (string-trim (shell-command-to-string "ls -t $* 2> /dev/null | head -n 1")))
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or mute the thread.*


--
Thierry

**Comment by jagrg** [comment]
With helm-ff-initial-sort-method set to newest:

1. Open an Org file
2. M-x org-export-dispatch
3. Press l l
4. M-x helm-find-files

I see the Org file preselected. This is wrong. The newest file should be the newly created tex file.

**Comment by thierryvolpiatto** [comment]
Jonathan Gregory <notifications@github.com> writes:

> With helm-ff-initial-sort-method set to newest:
>
> 1. Open an Org file
> 2. M-x org-export-dispatch
> 3. Press l l
> 4. M-x helm-find-files
>
> I see the Org file preselected. This is wrong. The newest file should be the newly created tex file.

No, there is nothing wrong, the tex file is on top which is expected and
the org file is preselected because it is the file relative to current
buffer which is expected too.

Sorting is one thing, preselection something else.

> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or mute the thread.*


-- 
Thierry

**Comment by jagrg** [comment]
On 06 Apr 2019, Thierry Volpiatto <notifications@github.com> wrote:

> No, there is nothing wrong, the tex file is on top which is expected
> and the org file is preselected because it is the file relative to
> current buffer which is expected too.
>
> Sorting is one thing, preselection something else.
>

You're right.

What do you think of also adding an option to preselect files according to modification time?
