### ISSUE TITLE
Helm split window settings broken since update

### ISSUE THREAD

**Issue by nivekuil** [emacs-helm/helm#1042]
I use the following settings to have helm windows split the current window vertically:
```
(setq helm-split-window-in-side-p t)
(setq helm-split-window-default-side 'below)
```
Since 2ea44573d5f562a0d20cf04b7fdbd3f03f07aa3d, opening a helm window will split the current window vertically once, and then split the original window again with helm appearing at the bottom of that one. 

So it looks like:
25% original
25% helm
50% split of original

Thanks for the package.

**Comment by YorkZ** [comment]
I started suffering from window spiting problem since I pulled the latest Helm yesterday. A minute ago, I pulled f14ac02 but it doesn't fix the problem for me.

My emacs window layout is always two side by side Windows. When the left window is the current window Helm split window horizontally (two side by side windows) which is the way it used to work, and nice. However, now if the right side window is the current window, Helm would split window vertically (top - bottom layout). To me, this doesn't make sense and I've been having a difficult time adapting to this new behavior.

**Comment by xuchunyang** [comment]
@YorkZ This issue has been fixed. 

You are talking another thing, the new behaviour is wanted while fixing #1036, though people who use the default helm setting may find that the window layout changes sharply after https://github.com/emacs-helm/helm/commit/2ea44573d5f562a0d20cf04b7fdbd3f03f07aa3d.

**Comment by nivekuil** [comment]
Looks like this was fixed with f14ac02db9390de28e1422735efcc68e83b5fa5a. Thanks.

**Comment by thierryvolpiatto** [comment]
York Zhao <notifications@github.com> writes:

> My emacs window layout is always two side by side Windows. When the
> left window is the current window Helm split window horizontally (two
> side by side windows) which is the way it used to work, and
> nice. However, now if the right side window is the current window,
> Helm would split window vertically (top - bottom layout).

Yes, this is the behavior of `window-in-direction' with 'below arg, if
it find a window at its right it consider it as a 'below window and use
this window, if no window to the right it display window to bottom and
this is what is happening to you.
It was working more or less as you expect until now by chance.
I agree this would be fixed, either on emacs or with a workaround on
helm.

What you really want is:

(setq helm-split-window-default-side 'left)

or

(setq helm-split-window-default-side 'right)

If you want a split always to bottom, use
helm-always-two-windows (I use this).


-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by xuchunyang** [comment]
> if no window to the right it display window to bottom

How about the leftmost when possible?  for example,

    +-----+-----+----+
    |     |     |    |
    |  1  |  2  | 3  |
    |     |     |    |
    |     |     |    |
    +-----+-----+----+

when invoke helm from 1 to 3, helm will show in 2, 3 and 1. The key is avoiding changing helm-current-buffer's position.

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

>     if no window to the right it display window to bottom
>    
> How about the leftmost when possible? for example,

To achieve this use:

(setq helm-split-window-default-side 'left)
(setq helm-always-two-windows t)

Of course the third window will disapear during the helm session.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by xuchunyang** [comment]
Thierry Volpiatto writes:

> Chunyang Xu <notifications@github.com> writes:
>
>>     if no window to the right it display window to bottom
>>    
>> How about the leftmost when possible? for example,
>
> To achieve this use:
>
> (setq helm-split-window-default-side 'left)
> (setq helm-always-two-windows t)
>
> Of course the third window will disapear during the helm session.

I mean when only invoking helm from the rightmost window, let helm
display in the leftmost existing window, actually I'd like helm to
display in another existing window, which position is not important,
for example, I have the following window layout (two window/buffer side
by side):

    | 1 | 2 |

run helm from buffer 1, display helm in 2
run helm from buffer 2, display helm in 1

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

> Thierry Volpiatto writes:
>
>> Chunyang Xu <notifications@github.com> writes:
>>
>>> if no window to the right it display window to bottom
>>>
>>> How about the leftmost when possible? for example,
>>
>> To achieve this use:
>>
>> (setq helm-split-window-default-side 'left)
>> (setq helm-always-two-windows t)
>>
>> Of course the third window will disapear during the helm session.
>
> I mean when only invoking helm from the rightmost window, let helm
> display in the leftmost existing window, actually I'd like helm to
> display in another existing window, which position is not important,
> for example, I have the following window layout (two window/buffer side
> by side):
>
> | 1 | 2 |
>
> run helm from buffer 1, display helm in 2
> run helm from buffer 2, display helm in 1

Use 'other as value of helm-split-window-default-side.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by xuchunyang** [comment]
Thierry Volpiatto writes:

> Chunyang Xu <notifications@github.com> writes:
>
>> Thierry Volpiatto writes:
>>
>>> Chunyang Xu <notifications@github.com> writes:
>>>
>>>> if no window to the right it display window to bottom
>>>>
>>>> How about the leftmost when possible? for example,
>>>
>>> To achieve this use:
>>>
>>> (setq helm-split-window-default-side 'left)
>>> (setq helm-always-two-windows t)
>>>
>>> Of course the third window will disapear during the helm session.
>>
>> I mean when only invoking helm from the rightmost window, let helm
>> display in the leftmost existing window, actually I'd like helm to
>> display in another existing window, which position is not important,
>> for example, I have the following window layout (two window/buffer side
>> by side):
>>
>> | 1 | 2 |
>>
>> run helm from buffer 1, display helm in 2
>> run helm from buffer 2, display helm in 1
>
> Use 'other as value of helm-split-window-default-side.

This is what I want. Thank you.

**Comment by YorkZ** [comment]
Thierry Volpiatto writes:
 Chunyang Xu <notifications@github.com> writes:

>>> I mean when only invoking helm from the rightmost window, let helm
>>> display in the leftmost existing window, actually I'd like helm to
>>> display in another existing window, which position is not important,
>>> for example, I have the following window layout (two window/buffer side
>>> by side):
>>>
>>> | 1 | 2 |
>>>
>>> run helm from buffer 1, display helm in 2
>>> run helm from buffer 2, display helm in 1

>> Use 'other as value of helm-split-window-default-side.

> This is what I want. Thank you.

This is also exactly what I wanted! Thank you very much. On the other hand, I can't find the `other` value of `helm-split-window-default-side` being mentioned anywhere.

I Also noticed that `helm-always-two-windows` has to be set to `nil` in order for this to work. In my opinion, `helm-always-two-windows` is really confusing here because it doesn't make much sense that it has to be set to `nil` in this case. Also, I think the name of `helm-always-two-Windows` is a bit confusing.

**Comment by YorkZ** [comment]
I've just added the `other` value in `helm-split-window-default-side` docstring, and have sent a pull request for this.

**Comment by xuchunyang** [comment]
York Zhao writes:

> Thierry Volpiatto writes:
>  Chunyang Xu <notifications@github.com> writes:
>
>>>> I mean when only invoking helm from the rightmost window, let helm
>>>> display in the leftmost existing window, actually I'd like helm to
>>>> display in another existing window, which position is not important,
>>>> for example, I have the following window layout (two window/buffer side
>>>> by side):
>>>>
>>>> | 1 | 2 |
>>>>
>>>> run helm from buffer 1, display helm in 2
>>>> run helm from buffer 2, display helm in 1
>
>>> Use 'other as value of helm-split-window-default-side.
>
>> This is what I want. Thank you.
>
> This is also exactly what I wanted! Thank you very much. On the other hand, I can't find the `other` value of `helm-split-window-default-side` being mentioned anywhere.

Already documented, see the second paragraph of its docstring, but that
docstring is obviously contradictory.

> I Also noticed that `helm-always-two-windows` has to be set to `nil` in order for this to work. In my opinion, `helm-always-two-windows` is really confusing here because it doesn't make much sense that it has to be set to `nil` in this case. Also, I think the name of `helm-always-two-Windows` is a bit confusing.

its default value is nil.

**Comment by YorkZ** [comment]
> Already documented, see the second paragraph of its docstring, but that
> docstring is obviously contradictory.

Oop, I didn't see that. And yes, it's contradictory.

>> I Also noticed that `helm-always-two-windows` has to be set to `nil` in order
>> for this to work. In my opinion, `helm-always-two-windows` is really confusing
>> here because it doesn't make much sense that it has to be set to `nil` in this
>> case. Also, I think the name of `helm-always-two-Windows` is a bit confusing.

> its default value is nil.

Yes, it's default value is nil. What happened was that I followed the previous posts and changed it. Then I noticed that setting `helm-split-window-default-side` to `other` didn't work as expected, and further figured out that `helm-always-two-Windows` has to be set back to `nil`.
