### ISSUE TITLE
Turning on helm-mode is super slow

### ISSUE THREAD

**Issue by KenetJervet** [emacs-helm/helm#1045]
My office network is weird but unfortunately I can't tell exactly how. Whether I add (helm-mode 1) in my .emacs or M-x helm-mode it gets stuck for ~2 min and then loads successfully. I have to disconnect my network (by disabling my NIC or pulling off my cable) to workaround this problem. *Messages* looks normal to me.

I don't know emacs lisp and I have no clue how to debug it. I'm glad to provide more information if you need.

Can't live without helm so I would really appreciate it if this problem gets solved.

Thanks!

**Comment by tuhdo** [comment]
Are you on Arch linux? A user told me that he had to set ssh connection timeout to 1 to get Helm starts properly.

**Comment by KenetJervet** [comment]
@tuhdo Yes! I will try it. Thanks a lot!

**Comment by KenetJervet** [comment]
@tuhdo It did work but I still want to further look into it. When I start emacs I see this process with ps aux | grep emacs:
```
/usr/bin/ssh -o ControlPath=%C host.does.not.exist
```

**Comment by KenetJervet** [comment]
I think it's due to an update of Tramp. In my system /usr/share/emacs/24.5/lisp/net/tramp-loaddefs.el:121
There is this line
```
(with-temp-buffer (call-process "ssh" nil t nil "-o" "ControlPath=%C" "host.does.not.exist")
...
```
adding ConnectTimeout=1 as an argument works good.

**Comment by tuhdo** [comment]
Is your Emacs 24.5?

**Comment by thierryvolpiatto** [comment]
KenetJervet <notifications@github.com> writes:

> I think it's due to an update of Tramp. In my system /usr/share/emacs/24.5/lisp/net/tramp-loaddefs.el:121
> There is this line
>
> (with-temp-buffer (call-process "ssh" nil t nil "-o" "ControlPath=%C" "host.does.not.exist")
> ...
>
> adding ConnectTimeout=1 as an argument works good.

This is a tramp bug that have been discussed on emacsbug and probably
fixed, so it looks your emacs version is affected by this.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by KenetJervet** [comment]
@tuhdo yes. I can wait for my distro to include a newer release of emacs and see if it's fixed. Let's close this issue for now.

**Comment by tsdh** [comment]
Just in case: could this issue be related to https://github.com/bbatsov/projectile/issues/777?

I'm also on Arch though I use a self-compiled git emacs.  And there, the slow display of completions only happen because of the projectile sources, and only for buffers which belong to no project at all.

**Comment by thierryvolpiatto** [comment]
Tassilo Horn <notifications@github.com> writes:

> Just in case: could this issue be related to bbatsov/projectile#777?
>
> I'm also on Arch though I use a self-compiled git emacs. And there,
> the slow display of completions only happen because of the projectile
> sources, and only for buffers which belong to no project at all.

I don't use projectile, and actually helm-mode load instantly or nearly.

Probably you should report this to projectile.

BTW why are you using projectile instead of
helm-browse-project+helm-ls-git?

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tsdh** [comment]
I already have reported it with projectile, I actually cited the issue. ;-)
I just wanted to make sure that this helm issue might actually be a projectile issue.

`helm-browse-project` doesn't seem to work for me (and I didn't know it so far).  It shows something like `Buffers in project (~/path/to/project/src/foo/bar/)` but I'm also interested in files, and actually the project is `~/path/to/project/`, not `~/path/to/project/src/foo/bar/`.  And what's up with `helm-ls-git`?  I can't find neither a function or variable of that name.

**Comment by tuhdo** [comment]
@thierryvolpiatto actually, @tsdh is using Arch which is related to this issue: https://github.com/emacs-helm/helm/issues/1000, and we know that Emacs build on Arch has issue with Helm, and [even Magit](http://www.reddit.com/r/emacs/comments/3a8ovf/magit_and_helm_became_unusably_slow/).

**Comment by xuchunyang** [comment]
> And what's up with helm-ls-git? I can't find neither a function or variable of that name.

You need to install https://github.com/emacs-helm/helm-ls-git, `helm-browse-projec` also supports other VCS like hg and svn

**Comment by thierryvolpiatto** [comment]
Tassilo Horn <notifications@github.com> writes:

> I already have reported it with projectile, I actually cited the issue. ;-)
> I just wanted to make sure that this helm issue might actually be a projectile issue.
>
> helm-browse-project doesn't seem to work for me (and I didn't know it
> so far). It shows something like Buffers in project
> (~/path/to/project/src/foo/bar/) but I'm also interested in files,

In non VC controlled directory, Use C-u C-x C-d otherwise you have only
the buffers showing up, at next call (files are cached) you only need
C-x C-d.


> and actually the project is ~/path/to/project/, not
> ~/path/to/project/src/foo/bar/.

On Non VC directory you have both buffers and files from
~/path/to/project listed recursively.

> And what's up with helm-ls-git? I can't find neither a function or
> variable of that name.

Actually helm-browse-project supports only Git, Hg and recently SVN.
You can get helm-ls-git/hg from emacs-helm or Melpa and helm-ls-svn from
Melpa also.
See docstring of helm-browse-project.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Here helm-browse-project in action:

![screenshot - 18062015 - 13 24 17](https://cloud.githubusercontent.com/assets/1533939/8230155/ced85832-15bd-11e5-8050-cc80ba616454.png)

**Comment by thierryvolpiatto** [comment]
And you can bookmark your directories from helm-find-files with C-x C-m.
You retrieve them from helm-find-files with C-x r b or from M-x helm-filtered-bookmarks

**Comment by tsdh** [comment]
@thierryvolpiatto I already found and fixed the issue for the projectile slowness (which has been my fault, actually).

As far as I can see, the helm-projectile helm-sources enable the same functionality as helm-browse-project but with the interface I'm already used to and have configured to my liking. I also use projectile directly, i.e., without helm.  And projectile works with all common VCS and is also able to get to know what a project is in terms of build files and similar things, so I see no reason to switch.

**Comment by fvaresi** [comment]
In my case, the delay was caused by a VPN client using a different DNS server while trying to solve the host provided by tramp (host.does.not.exist).

Mapping host.does.not.exist to 127.0.0.1 in /etc/hosts fixed the issue for me.

**Comment by tsdh** [comment]
@fvaresi I think the intention of trying to contact host.does.not.exist (I think TRAMP does that) is to check something ssh does when a host does not exists, and now it does exist for you.  This might have non-intended side-effects.

**Comment by fvaresi** [comment]
@tsdh You are right. I modified it to an invalid IP just to be sure.
