### ISSUE TITLE
helm-M-x breaks macro recording

### ISSUE THREAD

**Issue by ryrun** [emacs-helm/helm#1048]
It seems its not possible to record functional macros, when you use helm-M-x to invoke commands.
I tried to record a macro with several "join-line" commands, invoked via M-x. Playing this macro stops at the step for the join-line command. I need to turn of helm-mode to get it working again.

I'm using emacs 24.5.1 on windows with helm 20150606.2301.

**Comment by michael-heerdegen** [comment]
A precise recipe, preferably for emacs-helm.sh, would help us to reproduce.  I think something like lossage (C-h l) would already be enough.  Thanks.

BTW, AFAICT helm should fall back to vanilla completion when recording a keyboard macro (due to incompatibility).  Did you see that?

**Comment by ryrun** [comment]
C-h l output:
```
T e s t <return> t e s t <return> t t <return> <help-echo>
<up> <up> <f3> M-x j o i n - l i n e <return> <f4>
<down> <home> <f4>
```

Helm doesn't fallback to vanilla on my system, when i start macro recording. So this could be my problem?
My .emacs file is here: https://github.com/ryrun/dotfiles/blob/master/.emacs

I'm not sure, how i can just enable helm on emacs -Q mode.

**Comment by michael-heerdegen** [comment]
Andreas <notifications@github.com> writes:

> Helm doesn't fallback to vanilla on my system, when i start macro
> recording. So this could be my problem?

Oh, your init file is fine, but helm does only fall back for helm-M-x:

  (global-set-key (kbd "M-x") #'helm-M-x)

Is doing this acceptable for you to do this (helm-M-x is like M-x but
has some additional features)?

In an ideal world, we would fall back to vanilla completion for
helminized commands too, I think, but that's probably quite a pain to
implement.

> I'm not sure, how i can just enable helm on emacs -Q mode.

That's exactly what emacs-helm.sh is for.  It is part of the helm
distribution.  It can be found in the installation folder when installed
via the package manager.  But I think we have got enough info from you
now.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> A precise recipe, preferably for emacs-helm.sh, would help us to reproduce. I think something like lossage (C-h l) would already be enough. Thanks.
>
> BTW, AFAICT helm should fall back to vanilla completion when recording
> a keyboard macro (due to incompatibility). Did you see that?

helm-M-x is switching correctly here to vanilla M-x.
Are you sure you are using helm-M-x for M-x, IOW is helm-M-x bound to
M-x ?

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by ryrun** [comment]
Ok, when i add 
```lisp
(global-set-key (kbd "M-x") #'helm-M-x)
```
to my .emacs file it works.
I thought following
```lisp
(helm-mode 1)
```
does it automatically.

**Comment by thierryvolpiatto** [comment]
Andreas <notifications@github.com> writes:

> Ok, when i add
>
> (global-set-key (kbd "M-x") #'helm-M-x)
>
> to my .emacs file it works.

Good.

> I thought following
>
> (helm-mode 1)
>
> does it automatically.

No helm-mode give you a basic helmization of commands, M-x and others
like C-x C-f, C-h f etc...

So when possible (available) you have better time using the helm native
command instead of the vanilla emacs command helmized.

e.g:

M-x => helm-M-x
C-x C-f => helm-find-files
C-h f/v => helm-apropos

etc... The list is long...

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by ryrun** [comment]
Ok, thanks.
