### ISSUE TITLE
N. of characters (width) for buffer/file name in helm-buffers-list

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [emacs-helm/helm#1050]
When using `helm-buffers-list` I see multiple columns:
```<buffer name> <file size> <Major mode> <path to the file>```

Most of the space is taken up by `<path to the file>`. Is there any way to increase the number of characters used for `<buffer name>`?

**Comment by xuchunyang** [comment]
Increase `helm-buffer-max-length` or set to nil.
