### ISSUE TITLE
Invalid function: helm-build-sync-source

### ISSUE THREAD

**Issue by psibi** [emacs-helm/helm#1051]
I have seen that there are some closed issue which are similar to this one I'm filing. I have tried those steps and since those solutions aren't working, I'm creating a new issue.

I tried installing through MELPA as well as through the git clone method, but nothing works for me. This is the error report I get when invoked through --debug-init option:

Debugger entered--Lisp error: (invalid-function helm-build-sync-source)
  helm-build-sync-source("imenu-anywere" :candidates helm-imenu-anywhere-candidates :persistent-action #[(elm) "\301\302\"\210\303\304!?\205
  require(helm)
  byte-code("\300\301!\210\300\302!\210\300\303!\210\304\305\306\307\310\302%\210\311\312\313\314\315DD\316\310\305\317\320&\210\311\321\313\314\322DD\323\310\305\317\324&\210\311\325\313\314\326DD\327\310\305\317\330&\210\311\331\313\314\332DD\333\310\305\317\330&\210\311\334\313\314\335DD\336\310\305\317\330&\210\311\337\313\314\340DD\341\310\305\317\330&\207" [require cl-lib helm helm-files custom-declare-group helm-mode nil "Enable helm completion." :group custom-declare-variable helm-completing-read-handlers-alist funcall function #[0 "\300\207" [((describe-function . helm-completing-read-symbols) (describe-variable . helm-completing-read-symbols) (debug-on-entry . helm-completing-read-symbols) (find-function . helm-completing-read-symbols) (trace-function . helm-completing-read-symbols) (trace-function-foreground . helm-completing-read-symbols) (trace-function-background . helm-completing-read-symbols) (find-tag . helm-completing-read-with-cands-in-buffer) (ffap-alternate-file) (tmm-menubar))] 1 "\n\n(fn)"] "Alist of handlers to replace `completing-read', `read-file-name' in `helm-mode'.\nEach entry is a cons cell like (emacs_command . completing-read_handler)\nwhere key and value are symbols.\n\nEach key is an Emacs command that use originaly `completing-read'.\n\nEach value maybe an helm function that take same arguments as\n`completing-read' plus NAME and BUFFER, where NAME is the name of the new\nhelm source and BUFFER the name of the buffer we will use.\nThis function prefix name must start by \"helm\".\n\nSee `helm-completing-read-symbols' for example.\n\nNote that this function will be reused for ALL the `completing-read'\nof this command, so it should handle all cases, e.g\nIf first `completing-read' complete against symbols and\nsecond `completing-read' should handle only buffer,\nyour specialized function should handle the both.\n\nIf the value of an entry is nil completion will fall back to\nemacs vanilla behavior.\ne.g If you want to disable helm completion for `describe-function':\n(describe-function . nil).\n\nIdo is also supported, you can use `ido-completing-read' and\n`ido-read-file-name' as value of an entry or just 'ido.\ne.g ido completion for `find-file':\n(find-file . ido)\nsame as\n(find-file . ido-read-file-name)\nNote that you don't need to enable `ido-mode' for this to work." :type (alist :key-type symbol :value-type symbol) helm-comp-read-case-fold-search #[0 "\207" [helm-case-fold-search] 1 "\n\n(fn)"] "Default Local setting of `helm-case-fold-search' for `helm-comp-read'.\nSee `helm-case-fold-search' for more info." symbol helm-mode-handle-completion-in-region #[0 "\300\207" [t] 1 "\n\n(fn)"] "Whether to replace or not `completion-in-region-function'.\nThis enable support for `completing-read-multiple' and `completion-at-point'\nwhen non--nil." boolean helm-mode-reverse-history #[0 "\300\207" [t] 1 "\n\n(fn)"] "Display history source after current source in `helm-mode' handled commands." helm-mode-no-completion-in-region-in-modes #[0 "\300\207" [nil] 1 "\n\n(fn)"] "A list of modes that do not want helm for `completion-in-region'." helm-completion-in-region-fuzzy-match #[0 "\300\207" [nil] 1 "\n\n(fn)"] "Whether `helm-completion-in-region' use fuzzy matching or not.\nAffect among others `completion-at-point', `completing-read-multiple'."] 8)
  (helm-mode 1)
  eval-buffer(#<buffer  *load*> nil "/home/sibi/.emacs.d/init.el" nil t)  ; Reading at buffer position 4357
  load-with-code-conversion("/home/sibi/.emacs.d/init.el" "/home/sibi/.emacs.d/init.el" t t)
  load("/home/sibi/.emacs.d/init" t t)
  #[0 "\205\262

This is what is in my relevant init.el file

    (add-to-list 'load-path "/home/sibi/.emacs.d/emacs-async/")
    (add-to-list 'load-path "/home/sibi/.emacs.d/helm/")

    (require 'helm-config)
    (helm-mode 1)

After installing, I did try invoking `emacs-helm.sh` and it worked properly. But when I invoke emacs with my `init.el` file this breaks. Let me know if you need any additional information.

**Comment by thierryvolpiatto** [comment]
Sibi <notifications@github.com> writes:

> This is what is in my init.el file
>
> (add-to-list 'load-path "/home/sibi/.emacs.d/emacs-async/")
> (add-to-list 'load-path "/home/sibi/.emacs.d/helm/")

If you have installed from MELPA the two lines above are not needed, you
just need:

(package-initialize)

Otherwise if you installed from git, are you sure
"/home/sibi/.emacs.d/helm/" is a valid path?

> (require 'helm-config)
> (helm-mode 1)

This is correct.

> After installing, I did try invoking emacs-helm.sh and it worked
> properly.

That's mean everything works fine (not a helm bug), 
just a problem with your config.

> But when I invoke emacs with my init.el file this breaks.

So something else is wrong in your config.
Follow carefully the instalation described in README and it should work.


-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by psibi** [comment]
> If you have installed from MELPA the two lines above are not needed, you just need: `(package-initialize)`

Sorry, I should have been more clear. I do have that thing when installing using MELPA. The configuration I show is there for installing using `git clone` method.

> Otherwise if you installed from git, are you sure "/home/sibi/.emacs.d/helm/" is a valid path?
Yes, that's a valid path. If I try to evaluate `(helm-mode 1)` in my buffer, after two or three attempts it starts working.

**Comment by thierryvolpiatto** [comment]
Sibi <notifications@github.com> writes:

>     If you have installed from MELPA the two lines above are not needed, you just need: (package-initialize)
>    
> Sorry, I should have been more clear. I do have that thing when
> installing using MELPA. The configuration I show is there for
> installing using git clone method.

First compile your files:

cd /home/sibi/.emacs.d/helm/ && make

Now start from emacs -Q, then in scratch buffer eval:

(add-to-list 'load-path "/home/sibi/.emacs.d/helm/")
(require 'helm-config)
(helm-mode 1)

That's all, now you can do e.g M-x helm-find-files.

>     Otherwise if you installed from git, are you sure "/home/sibi/.emacs.d/helm/" is a valid path?
>     Yes, that's a valid path. If I try to evaluate (helm-mode 1) in my
>     buffer, after two or three attempts it starts working.

No, it works or not, I don't see why it would work after two or three
attempts if it didn't work at first try.

And what do you mean by "it starts working" ?
What starts working ?
 
-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by psibi** [comment]
Thanks, figured this out. The problem was because of a plugin named `imenu-anywhere`.  I think [this function](https://github.com/vspinu/imenu-anywhere/blob/c4ea83c1465518a09a31762e14a614558c0de392/imenu-anywhere.el#L221) was causing the problem. Disabling it makes helm work smoothly as before. Thanks.

**Comment by vspinu** [comment]
I have no idea why you have this issue. We call `helm-build-sync-source` in  [`(eval-after-load "helm")`](https://github.com/vspinu/imenu-anywhere/blob/c4ea83c1465518a09a31762e14a614558c0de392/imenu-anywhere.el#L201-L213). At that stage that function is already defined. Are you sure you are using the newest `imenu-anywhere`?

**Comment by psibi** [comment]
@vspinu Yes, I was using the latest `imenu-anywhere`.

**Comment by thierryvolpiatto** [comment]
Vitalie Spinu <notifications@github.com> writes:

> I have no idea why you have this issue. We call helm-build-sync-source
> in (eval-after-load "helm").

You should not use eval-after-load in your sources files:

   Normally, well-designed Lisp programs should not use
‘eval-after-load’.  If you need to examine and set the variables defined
in another library (those meant for outside use), you can do it
immediately—there is no need to wait until the library is loaded.  If
you need to call functions defined by that library, you should load the
library, preferably with ‘require’ (*note Named Features::).

Also I have provided a function `helm-imenu-in-all-buffers' 
that provide the same I think that yours.  It is reusing the code of
helm-imenu with few changes.
Have a look probably we could use this one and improve it here.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by vspinu** [comment]
> to examine and set the variables defined

I am using one function and don't want to introduce a helm dependency for that.    When #592 is fixed I will reconsider.

> Also I have provided a function `helm-imenu-in-all-buffers'

Good to know. I will check it up.

**Comment by thierryvolpiatto** [comment]
Vitalie Spinu <notifications@github.com> writes:

>     to examine and set the variables defined
>    
> I am using one function and don't want to introduce a helm dependency
> for that.

Maybe try with-eval-after-load which is the same but run as a macro.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by vspinu** [comment]
> Maybe try with-eval-after-load which is the same but run as a macro.

The original issue [fixed itself](https://github.com/vspinu/imenu-anywhere/issues/20#issuecomment-111827104). It was an old helm lying around or something of that kind.
