### ISSUE TITLE
helm-org-in-buffer-headings doesn't work on a headings of certain length.

### ISSUE THREAD

**Issue by LeoUfimtsev** [emacs-helm/helm#1052]
I have come across a very peculiar bug.

If I have a hierarchy structure like so , (EXACT number of characters are necessary to reproduce)
    * aaaaaaaaaaa
    ** bbbbbb
    *** ccccccc
    **** dddddddddd
    ***** eeeeeeee
    ****** ffff
    ******* gggggg

Then when I run `helm-org-in-buffer-headings` I get an error:

   setq: Args out of range: "gggggg", 0, -7

Now If I edit the structure above and 
 - remove 3 `'a'` characters **OR** 
 - add many `'a'` characters (e.g 50)
Then it works again. 
I can similarly remove/add  some b's, c's, d's g's etc.. to make it work.

It seems the issue is a certain range of length for the headings for a certain depth of headings.

This bug also affects `helm-org-agenda-files-headings` since it is called on each buffer.

I used newest versions from this morning for testing:
 - Emacs: 25.0.50.6
 - Helm:20150610.1327 

I have no idea how to debug/fix this, but I'm happy to test newest beta versions/fixes.

~It took me 2 1/2 hours to narrow it down to this scenario, I found it burried deep in my notes as my helm-org-agenda-files-headings wasn't working for a while. I hope it get's fixed :-).

**Comment by thierryvolpiatto** [comment]
LeoUfimtsev <notifications@github.com> writes:

> I have come across a very peculiar bug.
>
> If I have a hierarchy structure like so , (EXACT number of characters are necessary to reproduce)
> * aaaaaaaaaaa
> ** bbbbbb
> *** ccccccc
> **** dddddddddd
> ***** eeeeeeee
> ****** ffff
> ******* gggggg
>
> Then when I run helm-org-in-buffer-headings I get an error:
>
> setq: Args out of range: "gggggg", 0, -7

I can't reproduce, can you try from ./emacs-helm.sh and if you can
reproduce from there provide a backtrace?

To have a backtrace, (setq debug-on-error t) or M-x
toggle-debug-on-error.
 
> I used newest versions from this morning for testing:
>
>   * Emacs: 25.0.50.6

Didn't try from emacs-25 though, only emacs-24.5.

>   * Helm:20150610.1327
>
> I have no idea how to debug/fix this, but I'm happy to test newest beta versions/fixes.
>
> ~It took me 2 1/2 hours to narrow it down to this scenario,

Would have been faster with the debugger turned on ;-)


-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Here a screenshot from ./emacs-helm.sh on emacs-24.5 running `M-x helm-org-in-buffer-headings`:
![screenshot - 11062015 - 06 31 59](https://cloud.githubusercontent.com/assets/1533939/8099911/97ffea6e-1004-11e5-8c0b-e75ffc106668.png)

**Comment by thierryvolpiatto** [comment]
Works fine also with emacs-25, just tried.
