### ISSUE TITLE
helm-buffers directory on its own line

### ISSUE THREAD

**Issue by nmaludy** [emacs-helm/helm#1055]
Hello,

Today i pulled the latest version of helm and noticed that helm-buffers has changed its format. Previously the format was:

filename     size   mode
directory
filename     size   mode
directory
....

The new format has changed to:
filename     size   mode   directory
filename     size   mode   directory
....

I often work in deep directory trees and with this format i'm only able to see the first 2-3 directories in the file's path. Is there a way that i can revert this format so that the directory is back on its own line?

Thanks,
Nick

**Comment by nmaludy** [comment]
I did some digging and i was wrong about the exact format.

The old format was indeed:

filename size mode directory
filename size mode directory

However the directory names (when long) wrapped lines. It worked like this through v1.6.6 and changed in v1.6.7 to the non-line wrapping behavior.

Is there a variable that i can set to regain the line-wrapping format?

Thanks,
Nick

**Comment by thierryvolpiatto** [comment]
nmaludy <notifications@github.com> writes:

> I did some digging and i was wrong about the exact format.
>
> The old format was indeed:
>
> filename size mode directory
> filename size mode directory
>
> However the directory names (when long) wrapped lines. It worked like
> this through v1.6.6 and changed in v1.6.7 to the non-line wrapping
> behavior.
>
> Is there a variable that i can set to regain the line-wrapping format?

Sorry but I don't understand what you want, actually the lines are
truncated if too long, what do you mean by "wrapped"?

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by nmaludy** [comment]
I would like the lines to not be truncated and for the extra portion of the line to be continued onto the next like aka "wrapped". 

Example of truncated:

MyLongFileName.el    12k         Emacs-Lisp   ~/src/lisp/my_project/s

Examle of line wrapping:
MyLongFileName.el    12k         Emacs-Lisp   ~/src/lisp/my_project/s
rc/some/deep/directory/structure/


In the "line wrapping" example you can see that the directory is continued on the next line. This happened in previous versions of helm (v1.6.6 and earlier).

**Comment by thierryvolpiatto** [comment]
nmaludy <notifications@github.com> writes:

> I would like the lines to not be truncated and for the extra portion
> of the line to be continued onto the next like aka "wrapped".
>
> Example of truncated:
>
> MyLongFileName.el 12k Emacs-Lisp ~/src/lisp/my_project/s
>
> Examle of line wrapping: MyLongFileName.el 12k Emacs-Lisp
> ~/src/lisp/my_project/s rc/some/deep/directory/structure/
>
> In the "line wrapping" example you can see that the directory is
> continued on the next line. This happened in previous versions of helm
> (v1.6.6 and earlier).

Thanks for explaining.

You should now be able to modify this with new var
`helm-buffers-truncate-lines'.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by nmaludy** [comment]
Works perfect thanks!
