### ISSUE TITLE
Can helm-mini function be moved into helm-buffers.el

### ISSUE THREAD

**Issue by sewkokot** [emacs-helm/helm#1057]
helm-buffers-list function is in helm-buffers.el while helm-mini is in helm-misc.el. Both functions have the same purpose (with minor difference: recentf, ido-virtual-buffers), so it would be useful (maintenace, refactoring, comparison) to have them in the same source file.

**Comment by thierryvolpiatto** [comment]
sewkokot <notifications@github.com> writes:

> helm-buffers-list function is in helm-buffers.el while helm-mini is in
> helm-misc.el. Both functions have the same purpose (with minor
> difference: recentf, ido-virtual-buffers), so it would be useful to
> have them in the same source file.

Make sense, will do soon.

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Done.
