### ISSUE TITLE
No buffer named *helm*

### ISSUE THREAD

**Issue by maniux** [emacs-helm/helm#1059]
Hi, I'm coding in python with jedi enabled and company as completion tool.
company-jedi has also been installed.

helm does not work in the python environment:
When editing a py file, nothing popup, and if i press TAB, mini-buffer gives the information of the title.

**Comment by thierryvolpiatto** [comment]
X.Arthur <notifications@github.com> writes:

> Hi, I'm coding in python with jedi enabled and company as completion
> tool.  company-jedi has also been installed.
>
> helm does not work in the python environment: When editing a py file,
> nothing popup, and if i press TAB, mini-buffer gives the information
> of the title.

Please explain clearly what is your problem, give a backtrace if you
have errors.

I don't understand your bugreport.

Also try helm with your python buffer in ./emacs-helm.sh

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
Looking at jedi-core.el, this library seems to call helm in the background to get completions (when available).  I guess something with their code is wrong.

@maniux Do you use helm at all?  Have you installed it?  Have you initialized helm accordingly?  I guess if you are a company user, it doesn't make sense to use helm in parallel?

Anyway, this is quite surely no bug in Helm.

**Comment by maniux** [comment]
@michael-heerdegen Yes I'm a new user helm, and it is installed correctly. It works every other places. I just try to build a python environment yesterday and encounter this.
I just looked at the init.el and found <TAB> was bind to helm-execute-persistent-action.
If I commented that out, company seems work fine.
( I then found this is not the problem because once I changed to another auto-completion backend for company on python code, everything seems fine.).

Sorry for the confusion.

**Comment by michael-heerdegen** [comment]
"X.Arthur" <notifications@github.com> writes:

> If I commented that out, company seems work fine.  ( I then found this
> is not the problem because once I changed to another auto-completion
> backend for company on python code, everything seems fine.).

That's good.

So, if there is nothing to do from our side, please close.


Regards,

Michael.
