### ISSUE TITLE
Error when using M-a on "Files from Current Directory" source

### ISSUE THREAD

**Issue by vjohansen** [emacs-helm/helm#1062]
helm version: ~/.emacs.d/elpa/helm-20150608.2057/helm.el

From what I can see from the source code in helm-mark-all
- bn is nil so the string match fails
- bn is because because (helm-file-completion-source-p) is nil

Oddly there is some special handling for this source above the failure

                             (and (or (helm-file-completion-source-p)
                                      (string=
                                       src-name "Files from Current Directory"))
                                  (or (string-match
                                       "^[.]?#.*#?$\\|[^#]*[.]\\{1,2\\}$" bn)
                                      ;; We need to test here when not using
                                      ;; a transformer that tag prefix
                                      ;; (i.e on tramp).
                                      (not (file-exists-p cand))))

Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match("^[.]?#.*#?$\\|[^#]*[.]\\{1,2\\}$" nil)
  (or (string-match "^[.]?#.*#?$\\|[^#]*[.]\\{1,2\\}$" bn) (not (file-exists-p cand)))
  (and (or (helm-file-completion-source-p) (string= src-name "Files from Current Directory")) (or (string-match "^[.]?#.*#?$\\|[^#]*[.]\\{1,2\\}$" bn) (not (file-exists-p cand))))
  (if (and (or (helm-file-completion-source-p) (string= src-name "Files from Current Directory")) (or (string-match "^[.]?#.*#?$\\|[^#]*[.]\\{1,2\\}$" bn) (not (file-exists-p cand)))) nil (helm-make-visible-mark))
  (progn (if (and (or (helm-file-completion-source-p) (string= src-name "Files from Current Directory")) (or (string-match "^[.]?#.*#?$\\|[^#]*[.]\\{1,2\\}$" bn) (not (file-exists-p cand)))) nil (helm-make-visible-mark)))
  (if (and (not (helm-this-visible-mark)) (not (or (string= prefix "[?]") (string= prefix "[@]")))) (progn (if (and (or (helm-file-completion-source-p) (string= src-name "Files from Current Directory")) (or (string-match "^[.]?#.*#?$\\|[^#]*[.]\\{1,2\\}$" bn) (not (file-exists-p cand)))) nil (helm-make-visible-mark))))
  (let* ((prefix (get-text-property (point-at-bol) (quote display))) (cand (helm-get-selection)) (bn (and (helm-file-completion-source-p) (helm-basename cand))) (src-name (assoc-default (quote name) (helm-get-current-source)))) (if (and (not (helm-this-visible-mark)) (not (or (string= prefix "[?]") (string= prefix "[@]")))) (progn (if (and (or (helm-file-completion-source-p) (string= src-name "Files from Current Directory")) (or (string-match "^[.]?#.*#?$\\|[^#]*[.]\\{1,2\\}$" bn) (not (file-exists-p cand)))) nil (helm-make-visible-mark)))))
  (while (< (point) maxpoint) (helm-mark-current-line) (let* ((prefix (get-text-property (point-at-bol) (quote display))) (cand (helm-get-selection)) (bn (and (helm-file-completion-source-p) (helm-basename cand))) (src-name (assoc-default (quote name) (helm-get-current-source)))) (if (and (not (helm-this-visible-mark)) (not (or (string= prefix "[?]") (string= prefix "[@]")))) (progn (if (and (or (helm-file-completion-source-p) (string= src-name "Files from Current Directory")) (or (string-match "^[.]?#.*#?$\\|[^#]*[.]\\{1,2\\}$" bn) (not ...))) nil (helm-make-visible-mark))))) (if (helm-pos-multiline-p) (progn (goto-char (or (helm-get-next-candidate-separator-pos) (point-max))) (forward-line 1)) (forward-line 1)) (end-of-line))
  (let* ((next-head (helm-get-next-header-pos)) (end (and next-head (save-excursion (goto-char next-head) (forward-line -1) (point)))) (maxpoint (or end (point-max)))) (while (< (point) maxpoint) (helm-mark-current-line) (let* ((prefix (get-text-property (point-at-bol) (quote display))) (cand (helm-get-selection)) (bn (and (helm-file-completion-source-p) (helm-basename cand))) (src-name (assoc-default (quote name) (helm-get-current-source)))) (if (and (not (helm-this-visible-mark)) (not (or (string= prefix "[?]") (string= prefix "[@]")))) (progn (if (and (or ... ...) (or ... ...)) nil (helm-make-visible-mark))))) (if (helm-pos-multiline-p) (progn (goto-char (or (helm-get-next-candidate-separator-pos) (point-max))) (forward-line 1)) (forward-line 1)) (end-of-line)))
  (save-excursion (goto-char (helm-get-previous-header-pos)) (helm-next-line) (let* ((next-head (helm-get-next-header-pos)) (end (and next-head (save-excursion (goto-char next-head) (forward-line -1) (point)))) (maxpoint (or end (point-max)))) (while (< (point) maxpoint) (helm-mark-current-line) (let* ((prefix (get-text-property (point-at-bol) (quote display))) (cand (helm-get-selection)) (bn (and (helm-file-completion-source-p) (helm-basename cand))) (src-name (assoc-default (quote name) (helm-get-current-source)))) (if (and (not (helm-this-visible-mark)) (not (or ... ...))) (progn (if (and ... ...) nil (helm-make-visible-mark))))) (if (helm-pos-multiline-p) (progn (goto-char (or (helm-get-next-candidate-separator-pos) (point-max))) (forward-line 1)) (forward-line 1)) (end-of-line))))
  (if nomark (message "Marking not allowed in this source") (save-excursion (goto-char (helm-get-previous-header-pos)) (helm-next-line) (let* ((next-head (helm-get-next-header-pos)) (end (and next-head (save-excursion (goto-char next-head) (forward-line -1) (point)))) (maxpoint (or end (point-max)))) (while (< (point) maxpoint) (helm-mark-current-line) (let* ((prefix (get-text-property ... ...)) (cand (helm-get-selection)) (bn (and ... ...)) (src-name (assoc-default ... ...))) (if (and (not ...) (not ...)) (progn (if ... nil ...)))) (if (helm-pos-multiline-p) (progn (goto-char (or ... ...)) (forward-line 1)) (forward-line 1)) (end-of-line)))) (helm-mark-current-line) (message "%s candidates marked" (length helm-marked-candidates)))
  (unwind-protect (if nomark (message "Marking not allowed in this source") (save-excursion (goto-char (helm-get-previous-header-pos)) (helm-next-line) (let* ((next-head (helm-get-next-header-pos)) (end (and next-head (save-excursion ... ... ...))) (maxpoint (or end (point-max)))) (while (< (point) maxpoint) (helm-mark-current-line) (let* ((prefix ...) (cand ...) (bn ...) (src-name ...)) (if (and ... ...) (progn ...))) (if (helm-pos-multiline-p) (progn (goto-char ...) (forward-line 1)) (forward-line 1)) (end-of-line)))) (helm-mark-current-line) (message "%s candidates marked" (length helm-marked-candidates))) (helm-follow-mode follow) (message nil))
  (let ((nomark (assq (quote nomark) (helm-get-current-source))) (follow (if helm-follow-mode 1 -1))) (helm-follow-mode -1) (unwind-protect (if nomark (message "Marking not allowed in this source") (save-excursion (goto-char (helm-get-previous-header-pos)) (helm-next-line) (let* ((next-head (helm-get-next-header-pos)) (end (and next-head ...)) (maxpoint (or end ...))) (while (< (point) maxpoint) (helm-mark-current-line) (let* (... ... ... ...) (if ... ...)) (if (helm-pos-multiline-p) (progn ... ...) (forward-line 1)) (end-of-line)))) (helm-mark-current-line) (message "%s candidates marked" (length helm-marked-candidates))) (helm-follow-mode follow) (message nil)))
  (progn (select-window (car save-selected-window--state) (quote norecord)) (let ((nomark (assq (quote nomark) (helm-get-current-source))) (follow (if helm-follow-mode 1 -1))) (helm-follow-mode -1) (unwind-protect (if nomark (message "Marking not allowed in this source") (save-excursion (goto-char (helm-get-previous-header-pos)) (helm-next-line) (let* ((next-head ...) (end ...) (maxpoint ...)) (while (< ... maxpoint) (helm-mark-current-line) (let* ... ...) (if ... ... ...) (end-of-line)))) (helm-mark-current-line) (message "%s candidates marked" (length helm-marked-candidates))) (helm-follow-mode follow) (message nil))))
  (unwind-protect (progn (select-window (car save-selected-window--state) (quote norecord)) (let ((nomark (assq (quote nomark) (helm-get-current-source))) (follow (if helm-follow-mode 1 -1))) (helm-follow-mode -1) (unwind-protect (if nomark (message "Marking not allowed in this source") (save-excursion (goto-char (helm-get-previous-header-pos)) (helm-next-line) (let* (... ... ...) (while ... ... ... ... ...))) (helm-mark-current-line) (message "%s candidates marked" (length helm-marked-candidates))) (helm-follow-mode follow) (message nil)))) (internal--after-with-selected-window save-selected-window--state))
  (save-current-buffer (unwind-protect (progn (select-window (car save-selected-window--state) (quote norecord)) (let ((nomark (assq (quote nomark) (helm-get-current-source))) (follow (if helm-follow-mode 1 -1))) (helm-follow-mode -1) (unwind-protect (if nomark (message "Marking not allowed in this source") (save-excursion (goto-char ...) (helm-next-line) (let* ... ...)) (helm-mark-current-line) (message "%s candidates marked" (length helm-marked-candidates))) (helm-follow-mode follow) (message nil)))) (internal--after-with-selected-window save-selected-window--state)))
  (let ((save-selected-window--state (internal--before-with-selected-window (helm-window)))) (save-current-buffer (unwind-protect (progn (select-window (car save-selected-window--state) (quote norecord)) (let ((nomark (assq ... ...)) (follow (if helm-follow-mode 1 -1))) (helm-follow-mode -1) (unwind-protect (if nomark (message "Marking not allowed in this source") (save-excursion ... ... ...) (helm-mark-current-line) (message "%s candidates marked" ...)) (helm-follow-mode follow) (message nil)))) (internal--after-with-selected-window save-selected-window--state))))
  helm-mark-all()
  call-interactively(helm-mark-all nil nil)
  command-execute(helm-mark-all)
  read-from-minibuffer("pattern: " nil (keymap (C-M-left . paren-backward-sexp) (C-M-right . paren-forward-sexp) (23 . helm-yank-text-at-point) (3 keymap (63 . helm-generic-file-help) (64 . helm-ff-run-insert-org-link) (88 . helm-ff-run-open-file-with-default-tool) (24 . helm-ff-run-open-file-externally) (15 . helm-ff-run-switch-other-frame) (111 . helm-ff-run-switch-other-window) (61 . helm-ff-run-ediff-merge-file)) (67108925 . helm-ff-run-ediff-file) (27 keymap (46 . helm-ff-run-etags) (105 . helm-ff-properties-persistent) (68 . helm-ff-run-delete-file) (72 . helm-ff-run-hardlink-file) (83 . helm-ff-run-symlink-file) (76 . helm-ff-run-load-file) (66 . helm-ff-run-byte-compile-file) (67 . helm-ff-run-copy-file) (82 . helm-ff-run-rename-file) (103 keymap (112 . helm-ff-run-pdfgrep) (122 . helm-ff-run-zgrep) (115 . helm-ff-run-grep))) (19 . helm-ff-run-grep) (29 . helm-ff-run-toggle-basename) keymap (94 . helm-swoop-caret-match) (f13 lambda nil (interactive) (helm-select-nth-action 12)) (f12 lambda nil (interactive) (helm-select-nth-action 11)) (f11 lambda nil (interactive) (helm-select-nth-action 10)) (f10 lambda nil (interactive) (helm-select-nth-action 9)) (f9 lambda nil (interactive) (helm-select-nth-action 8)) (f8 lambda nil (interactive) (helm-select-nth-action 7)) (f7 lambda nil (interactive) (helm-select-nth-action 6)) (f6 lambda nil (interactive) (helm-select-nth-action 5)) (f5 lambda nil (interactive) (helm-select-nth-action 4)) (f4 lambda nil (interactive) (helm-select-nth-action 3)) (f3 lambda nil (interactive) (helm-select-nth-action 2)) (f2 lambda nil (interactive) (helm-select-nth-action 1)) (menu-bar keymap (help-menu keymap (describe keymap (describe-mode . helm-help)))) (help keymap (109 . helm-help)) (f1 lambda nil (interactive) (helm-select-nth-action 0)) (8 keymap (109 . helm-help) (104 . undefined) (8 . undefined) (4 . helm-debug-output)) (20 . helm-toggle-resplit-and-swap-windows) (C-tab . undefined) (67108897 . helm-toggle-suspend-update) (3 keymap (21 . helm-force-update) (6 . helm-follow-mode) (9 . helm-copy-to-buffer) (11 . helm-kill-selection-and-quit) (25 . helm-yank-selection) (4 . helm-delete-current-selection) (45 . helm-swap-windows)) (67108987 . helm-enlarge-window) (67108989 . helm-narrow-window) (19 . undefined) (18 . undefined) (23 . helm-yank-text-at-point) (24 keymap (2 . helm-resume-list-buffers-after-quit) (98 . helm-resume-previous-session-after-quit) (6 . helm-quit-and-find-file)) (11 . helm-delete-minibuffer-contents) (67108896 . helm-toggle-visible-mark) (0 . helm-toggle-visible-mark) (C-M-up . helm-scroll-other-window-down) (C-M-down . helm-scroll-other-window) (M-prior . helm-scroll-other-window-down) (M-next . helm-scroll-other-window) (12 . helm-recenter-top-bottom-other-window) (15 . helm-next-source) (10 . helm-execute-persistent-action) (26 . helm-execute-persistent-action) (9 . helm-select-action) (13 . helm-maybe-exit-minibuffer) ...) nil nil "probe1" t)
  helm-read-pattern-maybe(nil nil nil nil nil nil nil)
  #[0 "\311\211\211\211\305\206\n

**Comment by thierryvolpiatto** [comment]
Should work now, thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
