### ISSUE TITLE
Feature request: support for Bookmark+

### ISSUE THREAD

**Issue by WorldsEndless** [emacs-helm/helm#1067]
As far as I know the best incarnation of bookmarking functionality in Emacs is Bookmark Plus[1]. By default helm will work for selection, but it allows only one action with the bookmarks (identity). It would be tremendously useful if most of the find-file functionality was available, such as inserting as an org link (also supported by the latest versions of Bookmark Plus) and open externally. Viewing annotations/tags is also not possible in conjunction with Bookmark Plus right now.

I'm not skilled enough with elisp to tell yet whether this would be a pretty simple matter of adjusting existing libraries/functions, or whether it would be a considerable work effort to add support for Bookmark Plus. Any ideas? 

Footnotes: 
[1]  http://www.emacswiki.org/emacs/BookmarkPlus#BookmarkTags

**Comment by thierryvolpiatto** [comment]
Tory S. Anderson <notifications@github.com> writes:

> As far as I know the best incarnation of bookmarking functionality in
> Emacs is Bookmark Plus[1]. By default helm will work for selection,
> but it allows only one action with the bookmarks (identity). It would
> be tremendously useful if most of the find-file functionality was
> available, such as inserting as an org link (also supported by the
> latest versions of Bookmark Plus) and open externally. Viewing
> annotations/tags is also not possible in conjunction with Bookmark
> Plus right now.

I am not aware of all the actual features of bookmark+, I was one of the
initial developers of bookmark+ and then switch to my own version more
simple for my needs.
I nearly don't use it anymore (except for bookmarking from firefox), I
use instead `helm-filtered-bookmarks'.
Have you tried it ?
What are the features missing compared to bookmark+ ?

> I'm not skilled enough with elisp to tell yet whether this would be a
> pretty simple matter of adjusting existing libraries/functions, or
> whether it would be a considerable work effort to add support for
> Bookmark Plus. Any ideas?

It is not a considerable work, the only thing is knowing well the code
and features of bookmark+ and create a helm interface for it.
I don't use it personally, but maybe someone would like to create this
package ?
I would be happy to put it in emacs-helm.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by WorldsEndless** [comment]
I'm not familiar with helm-filtered-bookmarks and don't see any ready reading about it online or in the docs, but I assume it is just basic bookmark functionality with options for bookmark libraries. Bookmarks+ (BMKP) has a fairly ridiculous number of features; you can see just the contents list at the beginning of http://www.emacswiki.org/emacs/BookmarkPlus. The features I use the most (though with little relevance to Helm) include complex tagging and filtering options from the BKMP display screen, the ability to bookmark whole sets of occurence results (such as locate results on Linux), the ability to make org links to a bookmark rather than a file (so that as progress in the file changes I can just update the bookmark and all links are changed appropriately, as with recurring tasks), and the ability to bookmark dired buffers and sets of information. 

Most of the Find File functions would be useful for bmkp (open externally, insert org-link) combined with some of the bookmark options (see tags, bookmark information, open-in-other-window, etc).

**Comment by WorldsEndless** [comment]
I've tried to make a start by editing the following lines as a starting point, just to see what works and what doesn't, but I can't seem to get the changes to take effect with any amount of evaluating, recompiling the byte file, and starting new emacs instances. What am I doing wrong? 

```lisp
(define-helm-type-attribute 'bookmark
    `((coerce . helm-bookmark-get-bookmark-from-name)
      (action . ,(helm-make-actions
                  "Jump to bookmark" 'helm-bookmark-jump
                  "Jump to BM other window" 'helm-bookmark-jump-other-window
                  "Bookmark+ info" 'bmkp-describe-bookmark ;; added
                  "Bookmark+ add tags" 'bmkp-add-tags ;; added
                  "Bookmark+ remove tags" 'bmkp-remove-tags ;; added
		  "Open externally" 'helm-ff-run-open-file-externally ;; added
                  "Delete bookmark(s)" 'helm-delete-marked-bookmarks
                  "Rename bookmark" 'helm-bookmark-rename
                  "Relocate bookmark" 'bookmark-relocate))
      (keymap . ,helm-bookmark-map)
      (mode-line . helm-bookmark-mode-line-string))
  "Bookmark name.")```

**Comment by thierryvolpiatto** [comment]
Tory S. Anderson <notifications@github.com> writes:

> I'm not familiar with helm-filtered-bookmarks and don't see any ready
> reading about it online or in the docs, but I assume it is just basic
> bookmark functionality with options for bookmark libraries.

No, just try it. It handle all kind of categories (w3m, gnus, mu4e,
info, helm-find-files, addressbook etc...) in separate sources.

> Bookmarks+ (BMKP) has a fairly ridiculous number of features;

This is the problem, a lot of these features are most of the time unneeded.

> you can see just the contents list at the beginning of
> http://www.emacswiki.org/emacs/BookmarkPlus.

No, I know the basic features of bookmark+ which are filtering bookmarks
by categories, the only thing I am interested by personally.
As I said I am not interested to write this, I will never use it, but if
somebody want to write this I am ok to put it on emacs-helm as a
separate package.

> The features I use the most (though with little relevance to Helm)
> include complex tagging and filtering options from the BKMP display
> screen,

Same as helm-filtered-bookmarks except the tagging stuff I am not
interested by due to the nature of helm-filtered-bookmarks that don't
need this.

> the ability to bookmark whole sets of occurence results (such as
> locate results on Linux), the ability to make org links to a bookmark
> rather than a file (so that as progress in the file changes I can just
> update the bookmark and all links are changed appropriately, as with
> recurring tasks),

Not interested by.

> and the ability to bookmark dired buffers

Already available in vanilla bookmark.

> and sets of information.
>
> Most of the Find File functions would be useful for bmkp (open
> externally, insert org-link) combined with some of the bookmark
> options (see tags, bookmark information, open-in-other-window, etc).

I can add some actions to helm-filtered-bookmarks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Tory S. Anderson <notifications@github.com> writes:

> I've tried to make a start by editing the following lines as a
> starting point, just to see what works and what doesn't, but I can't
> seem to get the changes to take effect with any amount of evaluating,
> recompiling the byte file, and starting new emacs instances. What am I
> doing wrong?

See helm-type-bookmark in helm-source.el, what you are using is here
just for compatibility with old sources and is deprecated.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Ok I leave this open in case a bookmark+ user want to write such package (will not go in main helm repo but as an independent package in emacs-helm).

**Comment by WorldsEndless** [comment]
I'm actually (slowly) working on it myself, in communication with the developer of Bookmark+. I'll post here when I have something worth sharing.

**Comment by michael-heerdegen** [comment]
Greetings to Drew!

**Comment by thierryvolpiatto** [comment]
As this is happening outside of helm I am closing.
