### ISSUE TITLE
Helm logo

### ISSUE THREAD

**Issue by doubleagent** [emacs-helm/helm#1070]
Any reason why Helm does not have a logo?

**Comment by thierryvolpiatto** [comment]
Probably because I have no idea of what to do with a logo :-)

**Comment by michael-heerdegen** [comment]
I thought this would be the logo: https://avatars3.githubusercontent.com/u/1541688?v=3&s=200

**Comment by doubleagent** [comment]
I like it. Should be on the README.

**Comment by thierryvolpiatto** [comment]
Done (also modified the image).
