### ISSUE TITLE
Merge and display current source name as  pattern prompt

### ISSUE THREAD

**Issue by tuhdo** [emacs-helm/helm#1073]
With the new setting `helm-echo-input-in-header-line` is really great.
However, we can save even more space and bring the input and best match closer together by merging the pattern prompt with the current helm source header and use its name as pattern prompt (or appending the current source name). Why? Consider this case:

![helm-header-duplicate](https://cloud.githubusercontent.com/assets/4818719/8303870/58845bb0-19cb-11e5-98cd-3ca2fd54a5c2.jpg)

For helm source built on the fly, the prompt name duplicates the command name, and basically the Helm source header is not useful.

But, aside from saving space, it closes the gap between input and best output and improve usability. So, the new interface shall look like this in `helm-mini` for example:

```
----------------------------
| [Buffers] pattern:
----------------------------
   candidate1
   candidate2
   candidate3
   ....
   candidaten
----------------------------
| Recentf
----------------------------
   candidate1
   candidate2
    .....
----------------------------
| Create buffer
----------------------------
````
```

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> With the new setting helm-echo-input-in-header-line is really great.
> However, we can save even more space and bring the input and best
> match closer together by merging the pattern prompt with the current
> helm source header and use its name as pattern prompt (or appending
> the current source name).

The answer is no, I want to keep the source header.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment]
Can we at least have an option?

**Comment by tuhdo** [comment]
We could have a slightly modification: when the pattern is empty, it looks like the current Helm with all source headers. But when we start typing, the top source is merged with pattern prompt.

**Comment by michael-heerdegen** [comment]
@tuhdo If you do that, how will you see which source is current for a multi-source session, e.g. "helm-multi-files"?  The prompt is the same for either source.

For saving space, I would customize the "helm-source-header" face.

**Comment by tuhdo** [comment]
@michael-heerdegen We use the current header line as prompt and as header for the current source i.e. in the example above,  if in `helm-mini`, buffers are top source then it is merged with the header line and becomes something like this:

```text
----------------------------
| [Buffers] pattern:
----------------------------
   candidate1
   candidate2
```

**Comment by michael-heerdegen** [comment]
Tu Do <notifications@github.com> writes:

> ----------------------------
> | [Buffers] pattern:
> ----------------------------
>    candidate1
>    candidate2

Interesting proposition.
