### ISSUE TITLE
helm M-x recent commands not shown?

### ISSUE THREAD

**Issue by zeltak** [emacs-helm/helm#1082]
Hi all.
I use helm m-x alot. but as opposed to smex or other such commands i dont get my previous command i used next time i launch it.
this is the relevant config part
```
(helm-mode 1)
(global-set-key (kbd "M-x") 'helm-M-x)
(setq helm-M-x-fuzzy-match t) ;; optional fuzzy matching for helm-M-x
```
then for example i issue M-x and enter end-kbd-macro
this runs but when i issue M-x again its not there on top (under the emacs command history)
is this a bug or does helm-x have a recent commands shown (on top) option at all?

kind regards

Z

**Comment by thierryvolpiatto** [comment]
zeltak <notifications@github.com> writes:

> then for example i issue M-x and enter end-kbd-macro
> this runs but when i issue M-x again its not there on top (under the emacs command history)
> is this a bug or does helm-x have a recent commands shown (on top) option at all?

You have your last command on top of history, which is perfectly fine.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
Generally it works for me as expected.

In the case of "end-kbd-macro":  If you were not recording a keyboard macro, calling "end-kbd-macro" raises an error, and the command is not added to the history.  But this can be configured by setting "helm-M-x-always-save-history".

If our answers didn't help, a more specific recipe, please.
