### ISSUE TITLE
Nesting calls to helm does not work correctly when a custom action is selected in the outer helm call

### ISSUE THREAD

**Issue by IvanMalison** [emacs-helm/helm#1084]
Here is a bit of elisp that can reproduce the issue https://gist.github.com/c11e85651b714c3e36ad

You need to select a custom action in the first helm call and NOT do so in the second one to see the issue. You will end up in an infinite loop.

The problem is that `helm-execute-selection-action-1` pulls the selected action from helm-action-buffer

``` elisp
(setq action (helm-get-default-action
                (or action
                    helm-saved-action
                    (if (get-buffer helm-action-buffer)
                        (helm-get-selection helm-action-buffer)
                      (helm-get-actions-from-current-source)))))
```
`(get-buffer helm-action-buffer)` will be truthy in our example because the outer helm made a custom selection, but this selection was not meant to be read by the inner selection.

I have some ideas about how to fix this, but I'd like to get your input @thierryvolpiatto

**Comment by IvanMalison** [comment]
Is there any particular reason the action selection can't be stored in a variable that is set in a let body to the rest of the invocation.

Why do we get the selection so 'late'?

**Comment by thierryvolpiatto** [comment]
You have to use `helm-run-after-quit' for such situation:

     (defun outer-action (_candidate)
       [...]
       (helm-run-after-quit
        (lambda () (helm :sources inner-helm-source :buffer "*helm inner*")))
       (message "finished calling outer helm action"))

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by IvanMalison** [comment]
So this is expected behavior? Why is `(helm-run-after-quit` necessary in this case?

**Comment by thierryvolpiatto** [comment]
IvanMalison <notifications@github.com> writes:

> So this is expected behavior?

Well, no, in a better world (threaded emacs) this should work as
expected (i.e without running the new session in helm-run-after-quit).

> Why is (helm-run-after-quit necessary in this case?

Because the previous helm session have not the time to terminate,
cleanup etc... before the new one popup, so you have to quit properly
the first session before running the next one.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by IvanMalison** [comment]
I'm not convinced that there isn't a better way to do this. If we obtained the value immediately upon selection i.e. did not look at the buffer so late to look up the value, this could be made to work in the existing world.

Are you against the idea of changing the way that selection values are obtained?

**Comment by thierryvolpiatto** [comment]
IvanMalison <notifications@github.com> writes:

> I'm not convinced that there isn't a better way to do this. If we
> obtained the value immediately upon selection i.e. did not look at the
> buffer so late to look up the value, this could be made to work in the
> existing world.
>
> Are you against the idea of changing the way that selection values are
> obtained?

No, see the changes in execute-actions branch that allow running
helm-find-files-grep for example easily wrapped in
helm-quit-and-execute-action.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
