### ISSUE TITLE
[Question] option: remove source-header if only one source

### ISSUE THREAD

**Issue by sewkokot** [emacs-helm/helm#1086]
How to make the source-header disapear if there is only one source? Is there an variable to make it? Now having the option to display pattern in header-line, removing the source header in particular cases would give us the candidates closer to the pattern and eliminating the redundant source header.

**Comment by thierryvolpiatto** [comment]
sewkokot <notifications@github.com> writes:

> How to make the source-header disapear if there is only one source? Is
> there an variable to make it?

No but you can modify the font size in helm-source-header.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by sewkokot** [comment]
Thank you Thierry! I found also similar issue
https://github.com/emacs-helm/helm/issues/918
