### ISSUE TITLE
Why was helm-pp-bookmarks removed?

### ISSUE THREAD

**Issue by darkfeline** [emacs-helm/helm#1087]
Why was `helm-pp-bookmarks` removed in this commit?

https://github.com/emacs-helm/helm/commit/f07e624e58b1f1350279fc5c8012b3dda2bf6d93

I quite liked it over the regular `helm-bookmarks`.

**Comment by thierryvolpiatto** [comment]
darkfeline <notifications@github.com> writes:

> Why was helm-pp-bookmarks removed in this commit?
>
> f07e624
>
> I quite liked it over the regular helm-bookmarks.

Use helm-filtered-bookmarks instead.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by darkfeline** [comment]
Thanks.
