### ISSUE TITLE
Error: wrong-type-argument listp helm-find-files-actions

### ISSUE THREAD

**Issue by sewkokot** [emacs-helm/helm#1088]
After todays melpa update I got this error at emacs startup:

Debugger entered--Lisp error: (wrong-type-argument listp helm-find-files-actions)
  copy-alist(helm-find-files-actions)
  helm-projectile-hack-actions(helm-find-files-actions helm-ff-browse-project helm-insert-file-name-completion-at-point helm-ff-find-sh-command helm-ff-cache-add-file (helm-ff-switch-to-eshell . helm-projectile-switch-to-eshell) (helm-ff-etags-select . helm-projectile-ff-etags-select-action) (helm-find-files-eshell-command-on-file . helm-projectile-find-files-eshell-command-on-file-action) (helm-find-file-as-root . "Find file as root `C-c r'") (helm-projectile-dired-files-new-action . "Create Dired buffer from files `C-c f'") (helm-projectile-dired-files-add-action . "Add files to Dired buffer `C-c a'"))
  byte-code("\301\302\206\n

**Comment by zeusdeux** [comment]
Can confirm. I am stuck with the same error on emacs 24.4.1

**Comment by thierryvolpiatto** [comment]
sewkokot <notifications@github.com> writes:

> After todays melpa update I got this error at emacs startup:
>
> Debugger entered--Lisp error: (wrong-type-argument listp helm-find-files-actions)
> copy-alist(helm-find-files-actions)
> helm-projectile-hack-actions

This bug belong to helm projectile which is not part of helm.
Don't know why they are using copy-alist.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
After looking at the code in helm-projectile this patch should fix the bug (fully not tested as I do not use projectile):

```diff
diff --git a/helm-projectile.el b/helm-projectile.el
index 781b3a4..ea29ec2 100644
--- a/helm-projectile.el
+++ b/helm-projectile.el
@@ -355,8 +355,9 @@ CANDIDATE is the selected file.  Used when no file is explicitly marked."
 
 (defvar helm-projectile-file-actions
   (helm-projectile-hack-actions
-   (cdr (assq 'action (or helm-source-find-files
-                          (helm-make-source "Find files" 'helm-source-ffiles))))
+   (cdr (helm-attr 'action (or helm-source-find-files
+                               (helm-make-source "Find files" 'helm-source-ffiles))
+                   'ignorefn))
    ;; Delete these actions
    'helm-ff-browse-project
    'helm-insert-file-name-completion-at-point
```

BTW helm comes with `helm-browse-project` which is always in sync with helm core because it is part of emacs-helm (need [helm-ls-git](https://github.com/emacs-helm/helm-ls-git) and [helm-ls-hg](https://github.com/emacs-helm/helm-ls-hg)).

**Comment by thierryvolpiatto** [comment]
And probably it is better to just customize actions starting from now.

**Comment by sewkokot** [comment]
The fix removes the error at startup but still something is wrong. For example helm-projectile-find-file does not open the file, it only opens the dired buffer...

**Comment by thierryvolpiatto** [comment]
sewkokot <notifications@github.com> writes:

> The fix removes the error at startup but still something is wrong. For
> example helm-projectile-find-file does not open the file, it only
> opens the dired buffer...

As I said the patch I sent is just informative and fully untested,
report the bug to projectile, they will fix it there.

Also note that now helm allow customization of actions, so probably this
hack used by projectile is no more needed.


-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by sewkokot** [comment]
As Brian Suh wrote in https://github.com/bbatsov/projectile/pull/795, removing 'cdr' fixes the issue. Thanks a lot!
