### ISSUE TITLE
Feature request: Going deeper one level in helm-find-files (and bounding it to C-r)?

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [emacs-helm/helm#1090]
Do people see value in being able to go *back* (deeper) one level with e.g. `C-r` in `helm-find-files` ?

 Currently `C-l` actually goes `up` (in filesystem speak), one level. i.e. it goes to the parent path, and one could argue that a symmetrical (and reverse) action is also very handy.

For example:
```
/A/B/C/D
C-l
/A/B/C/
C-r
/A/B/C/D/
```
Note that there is never ambiguity in what going *deeper* in the filesystem means given the history of paths visited.

Conceptually speaking (implementation should be easier), when a user navigates paths with `helm-find-files`, she is basically creating a tree of paths visited. In this context: `C-l` always means go up to the parent directory (current behavior), and `C-r` would just simply mean to go deeper in the tree following the *specific branches of the tree* that you *just* came from. 

All the implementation of `C-r` needs to do is remember the list of paths that are being visited in consecutive calls to `C-l`. As soon as the user drops **down** to *any* folder, this list is reset. If the list is empty `C-r` would do nothing (and maybe display a message like "the current list of of visited descendant paths is empty").

**Comment by thierryvolpiatto** [comment]
Amelio Vazquez-Reina <notifications@github.com> writes:

> Do people see value in having the ability to being able to go back one level with e.g. C-r in helm-find-files ?
>
> Currently C-l actually goes up (in filesystem speak), one level. i.e. it goes to the parent pat, and one could argue that a symmetrical (and reverse) action is also
> very handy.
>
> For example:
>
> /A/B/C/D
> C-l
> /A/B/C/
> C-r
> /A/B/C/D/
>
> Note that there is never ambiguity in what going deeper in the
> filesystem means here.
>
> Conceptually speaking (implementation should be easier), when a user
> navigates paths with helm-find-files, she is basically creating a tree
> of paths visited. In this context: C-l always means go up to the
> parent directory (current behavior), and C-r would just simply mean,
> go deeper in the tree following the specific branches of the tree that
> you came from.
>
> All the implementation of C-r needs to do is remember the list of
> paths that are being visited in consecutive calls to C-l. As soon as
> the user drops down to any folder, this list is reset. If the list is
> empty C-r would do nothing (and maybe display a message like "the list
> of recently visited descendant paths is empty").

Interesting.

Note that actually you can return to initial point easily:

C-x C-f
=> /A/B/C/D/
C-l C-l
=> /A/B/
Enter at prompt "./"
=> /A/B/C/D/

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by amelio-vazquez-reina** [comment]
Yes, thanks @thierryvolpiatto I knew that, and that's definitely handy as well.

**Comment by thierryvolpiatto** [comment]
Amelio Vazquez-Reina <notifications@github.com> writes:

> All the implementation of C-r needs to do is remember the list of
> paths that are being visited in consecutive calls to C-l. As soon as
> the user drops down to any folder, this list is reset. If the list is
> empty C-r would do nothing (and maybe display a message like "the list
> of recently visited descendant paths is empty").

I made a first shot in exp branch, not fully polished but it seems to
work fine for now, have a try.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by amelio-vazquez-reina** [comment]
Thanks @thierryvolpiatto  I currently update Helm from the Emacs package manager (I use `async`). I presume there is no easy way of testing it there since that pulls from `master`, correct?

**Comment by thierryvolpiatto** [comment]
Amelio Vazquez-Reina <notifications@github.com> writes:

> Thanks @thierryvolpiatto I currently update Helm from the Emacs
> package manager (I use async). I presume there is no easy way of
> testing it there since that pulls from master, correct?

The changes are on the exp branch.
No need to make a full install from git.
You can clone from git, then checkout the exp branch, cd to the helm
directory, make and then ./emacs-helm.sh.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Now merged, you will get the changes soon in melpa.

**Comment by amelio-vazquez-reina** [comment]
Fantastic @thierryvolpiatto It works like a charm!

**Comment by amelio-vazquez-reina** [comment]
Thanks for the quick response, and for the fix by the way. Helm has become an indispensable part of my workflow -- it's simply incredible how much better my programming and work experience is today thanks to it.

**Comment by thierryvolpiatto** [comment]
Thanks, closing now, feel free to reopen if something wrong.
