### ISSUE TITLE
Use key map syntax that Emacs requires 

### ISSUE THREAD

**Issue by joshuaeckroth** [emacs-helm/helm#1092]
helm-20150710.1024 fails to load due to this error:

```
error: To bind the key C-M-SPC, use [?\C-\M- ], not [C-M-SPC]
```

with Emacs version:

```
GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21)
 of 2015-04-10 on builder10-9.porkrind.org
```

The code in question is line 126 in commit 570bc0f5f6ec4d47f095a0e3e08df6f7d9ffe8bc

https://github.com/emacs-helm/helm/commit/570bc0f5f6ec4d47f095a0e3e08df6f7d9ffe8bc#diff-2b946d5d1b82ff6d9e172c158b84b267R126

The code should set the key map with `[?\C-\M- ]` instead (apparently).

**Comment by thierryvolpiatto** [comment]
Joshua Eckroth <notifications@github.com> writes:

> helm-20150710.1024 fails to load due to this error:
>
> error: To bind the key C-M-SPC, use [?\C-\M- ], not [C-M-SPC]
>
> with Emacs version:
>
> GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21)
>  of 2015-04-10 on builder10-9.porkrind.org
>
> The code in question is line 126 in commit 570bc0f
>
> 570bc0f#diff-2b946d5d1b82ff6d9e172c158b84b267R126
>
> The code should set the key map with [?\C-\M- ] instead (apparently).

No, as long as we use kbd.
I can't reproduce this bug, I guess it is due to binding in your own
config.
Please try to reproduce starting from ./emacs-helm.sh.
(Use the -P option to specify your emacs path if needed)

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by joshuaeckroth** [comment]
Thanks for your response. I updated to the latest helm (just a few days newer) and now it's happy, without changes to my emacs config. I think it was some issue related to byte compiling (what was defined when the byte compiling happened the first time vs. second time). Everything's ok now. Thanks!
