### ISSUE TITLE
Helm-find-files in python mode always pops up py-shell

### ISSUE THREAD

**Issue by jagguli** [emacs-helm/helm#1095]
In python-mode move cursor on top of any text and do helm-find-files

New python shell window opens, 

very annoying is there a fix pls

**Comment by thierryvolpiatto** [comment]
Steven <notifications@github.com> writes:

> In python-mode move cursor on top of any text and do helm-find-files
>
> New python shell window opens,
>
> very annoying is there a fix pls

Can't reproduce, can you reproduce from ./emacs-helm.sh ?

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by jagguli** [comment]
(custom-set-variables
 '(py-complete-function (quote py-indent-or-complete))
 '(py-ffap-p (quote py-ffap))
)

this fixed it, issue was with python-mode not helm sorry.

**Comment by thierryvolpiatto** [comment]
Steven <notifications@github.com> writes:

> (custom-set-variables
> '(py-complete-function (quote py-indent-or-complete))
> '(py-ffap-p (quote py-ffap))
> )
>
> this fixed it, issue was with python-mode not helm sorry.

Ok thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
