### ISSUE TITLE
helm-projectile action dones't work with shorcut

### ISSUE THREAD

**Issue by LuoPX-15510486969** [emacs-helm/helm#1096]
when i use prelude on windows, i find that the shortcut of action such as "M-D","C-d"dones't work,but "C-s" can work well. So do the find-file shotcut such as "M-R" and so on.

![helm](https://cloud.githubusercontent.com/assets/13256245/8696436/d96ec7ba-2b1e-11e5-9fc7-68739586b864.png)

**Comment by thierryvolpiatto** [comment]
LuoPX-15510486969 <notifications@github.com> writes:

> when i use prelude on windows,

Please people stop sending projectile, prelude and else bugs here.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
