### ISSUE TITLE
Error running timer: (error "helm-interpret-value: Symbol must be a function or a variable")

### ISSUE THREAD

**Issue by swwwfactory** [emacs-helm/helm#1097]
After latest update this message from topic occurs when trying to run helm-ls-git-ls and filter something.

**Comment by swwwfactory** [comment]
helm-20150710.2034 and helm-ls-git-20150710.2214 works well before, so I've downgraded to this versions

**Comment by thierryvolpiatto** [comment]
swwwfactory <notifications@github.com> writes:

> helm-20150710.2034 and helm-ls-git-20150710.2214 works well before, so
> I've downgraded to this versions

Fixed 1 hour ago.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by swwwfactory** [comment]
Im keep elpa packages in local repo, and now after update I see that helm, helm-ls-git seems works for me NOW.

These new updates I see when run update elpa:
```
        elpa/alect-themes-20150712.625/
        elpa/ample-theme-20150714.1739/
        elpa/electric-operator-20150714.311/
        elpa/helm-20150715.225/
        elpa/helm-core-20150714.917/
        elpa/helm-ls-git-20150715.617/
        elpa/js2-mode-20150713.signed
        elpa/js2-mode-20150713/
        elpa/magit-20150715.508/
        elpa/magit-popup-20150711.505/
        elpa/markdown-mode-20150715.623/
        elpa/names-20150714.437/
        elpa/org-20150713.signed
        elpa/org-20150713/
        elpa/projectile-20150714.241/
        elpa/solarized-theme-20150714.1020/
```
Assume these versions fixes issues.

Thank you Thierry for your responsiveness and efficiency.
