### ISSUE TITLE
How to disable input inside Helm minibuffer, from the word under cursor? 

### ISSUE THREAD

**Issue by ReneFroger** [emacs-helm/helm#1098]
To be clear, I found nothing on this yet when I looked around in the Helm wiki on the input possibilities. 

Trying other variables didn't help either, like `(setq helm-completing-read-with-cands-in-buffer 'nil)`

My issue is, for example, in `PHP-mode` and my pointer is on the word `function`,  and I call `helm-for-files`, then I notice that the word `function` is set in the input field.  It will automatically search for that symbol.

I don't want that. How could I disable this? 

However, there would be another option too. Maybe when someone start typing it will delete the word at point in the mini-buffer and search for what I type. Is this even possible? But in basis, it would be great if there is a way to disable this.

**Comment by thierryvolpiatto** [comment]
ReneFroger <notifications@github.com> writes:

> Trying other variables didn't help either, like (setq
> helm-completing-read-with-cands-in-buffer 'nil)

Again you are confused with variables and functions ;-)

> My issue is, for example, in PHP-mode and my pointer is on the word
> function, and I call helm-for-files, then I notice that the word
> function is set in the input field. It will automatically search for
> that symbol.

No, if it behave like this, it's you have configured helm to do so, by
default helm is not doing this.

What you are describing is default as input, that is helm is using its
default value argument as input value.

> I don't want that. How could I disable this?

Check your own configuration, something is wrong there.
If you don't find let me see your helm config.


-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
