### ISSUE TITLE
helm-ff auto update expands to directory although the match is not unique

### ISSUE THREAD

**Issue by tnielens** [emacs-helm/helm#1099]
helm-ff auto update expands to directory although the match is not unique

For example,
with the following directories :

dir
dir1
dir2

when typing dir in the minibuffer, helm automatically expands into it, hindering the user if he wants to select another one.
Default behavior could be to expand only on unique match.

**Comment by thierryvolpiatto** [comment]
tnielens <notifications@github.com> writes:

> helm-ff auto update expands to directory although the match is not unique
>
> For example,
> with the following directories :
>
> dir
> dir1
> dir2
>
> when typing dir in the minibuffer, helm automatically expands into it,
> hindering the user if he wants to select another one.

When you get used to it, you rarely type "dir" unless you really want
"dir", instead you type "dr1" or "dr2".

Expanding only on unique match would mean most of the time not expanding
at all, (due to fuzzy matching) so deciding for a default behavior here
is not easy.

> Default behavior could be to expand only on unique match.

Could be, but not sure it is the best option.

I personally use auto expanding all the time and I am happy with its
current behavior.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tnielens** [comment]
In am not using fuzzy matching. But indeed I should type something like ir1 if I want to expand to the dir1 folder.
But what I think is not natural is that : 
When your pattern is a full word for word match (which shouldn't bother you since you're searching by fuzzy matching), helm expands (despite longer matching directories). This is unpleasant, since you have to erase the trailing slash and type a new character. 
If you actually have this set of directories : 
dir, dira, dirab, dirabc, 
you are going to sequentially expand all directories one by one and erase the slash until you reach dirabc. 
What I think is a more natual behavior : 
If helm matches word for word a folder, but still other directories are matching, it shouldn't expand.

This is actually the only case I have experienced where helm expands when the matching completion is not unique.

**Comment by thierryvolpiatto** [comment]
tnielens <notifications@github.com> writes:

> In am not using fuzzy matching.

But helm-find-files is fuzzy matching.

> But indeed I should type something like ir1 if I want to expand to the
> dir1 folder.  But what I think is not natural

It is not, but when you get used to it it gets handy.

> is that : When your pattern is a full word for word match

I understood what is the problem here, it have been discussed several
times here, be I am still unsure which default adopt here.

I may modify this if I find a good compromise without loosing what we
have actually (it is not trivial to fix).

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tnielens** [comment]
Ok. Didn't notice about the fuzzy matching ^^. 
Get what you mean.  Maybe it could be a customizable feature ?
Thanks, for the time.

**Comment by thierryvolpiatto** [comment]
tnielens <notifications@github.com> writes:

> Ok. Didn't notice about the fuzzy matching ^^.
> Get what you mean. Maybe it could be a customizable feature ?

No, actually one can use or not auto expansion of directories, you can
also toggle it with C-<backspace> when needed, which is enough for now.

I will try to find a better behavior around this later (not the time
now).

Thanks for your feedback.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Should work as you expect now.

**Comment by michael-heerdegen** [comment]
FWIW, I noticed that even with autoexpand off, when entering a directory file name into the minibuffer in helm-find-files (and helminized funs that read file names), now a slash is automatically added if the name is complete.  Is that intended?

If you don't understand what I mean: suppose you have a dir "~/test".  In helm-find-files, I type "~/test", and a slash is automatically added: "~/test/", and the candidates are now the files in "~/test/".  Until recently that did not happen with autoexpand off.  Dunno if it's a bug or feature; in general it's ok, but it also sometimes gets in my way.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> FWIW, I noticed that even with autoexpand off, when entering a
> directory file name into the minibuffer in helm-find-files (and
> helminized funs that read file names), now a slash is automatically
> added if the name is complete. Is that intended?

No, it should behave as before, I have hard time actually to implement
this without breaking other stuff like this (this one should be easy to
fix) or particularly tramp which is a nightmare as soon you change
something in this area.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Revert all changes for now.

**Comment by thierryvolpiatto** [comment]
Should work as expected now.

**Comment by michael-heerdegen** [comment]
> Should work as expected now.

Confirmed - thanks!
