### ISSUE TITLE
open selected candidate in horizontal or vertical split

### ISSUE THREAD

**Issue by blaenk** [emacs-helm/helm#1100]
I'm switching over from vim so I'm settling into my flow. One flow I had in vim with the ctrlp plugin was that I could open the selected candidate in either a horizontal or vertical split, without having to decide this before hand. Further still, I could mark multiple candidates with <kbd>C-z</kbd> and then open them all in a vertical split for example with <kbd>C-v</kbd>.

I've searched around and looked at the manual and documentation but I see no mention of splitting. I figure this would be for something like `helm-find-files` since that is specifically for files, but I can't find anything related to splitting. I'm wondering if this functionality is possible, or if not, if it would possibly be added, or if there may be some way that I can hack it on.

I'm getting the impression that I have to have created the split before-hand to then let helm open the buffer in the split from which I run the helm command. This seems to work, but it'd be much faster and nicer I think if we could delay that decision to after we have found and chosen from the candidates.

**Comment by thierryvolpiatto** [comment]
Jorge Israel Peña <notifications@github.com> writes:

> I'm switching over from vim so I'm settling into my flow. One flow I
> had in vim with the ctrlp plugin was that I could open the selected
> candidate in either a horizontal or vertical split, without having to
> decide this before hand. Further still, I could mark multiple
> candidates with C-z and then open them all in a vertical split for
> example with C-v.
>
> I've searched around and looked at the manual and documentation but I
> see no mention of splitting. I figure this would be for something like
> helm-find-files since that is specifically for files, but I can't find
> anything related to splitting. I'm wondering if this functionality is
> possible, or if not, if it would possibly be added, or if there may be
> some way that I can hack it on.
>
> I'm getting the impression that I have to have created the split
> before-hand to then let helm open the buffer in the split from which I
> run the helm command. This seems to work, but it'd be much faster and
> nicer I think if we could delay that decision to after we have found
> and chosen from the candidates.

Not sure to understand what you want, correct me if I am wrong.

1) M-x helm-find-files
2) navigate to have selection on "foo" file.
3) C-c o (find-file-other-window)

You expect "foo" opened vertically or horizontally in other window.

Right ?

If so helm is not handling this, this is currently handled in emacs
according to the value of `split-width-threshold'.

e.g if split-width-threshold is nil, C-c o will display "foo" in a
vertical layout, but is split-width-threshold value is an integer < to
the size of window (window-width), "foo" will be displayed in an
horizontal layout.

Which make sense because if your window is not very large, you wont
display "foo" in an horizontal layout.

So probably what you want is just setting split-width-threshold so that
when your window is large enough you split vertically and if your window
is too small split is done horizontally.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by blaenk** [comment]
Thank you! The only thing remaining is that I want to be able to mark multiple files and open them all in splits with with C-c o, but it seems to only work with one file. Can this be done?

**Comment by thierryvolpiatto** [comment]
Jorge Israel Peña <notifications@github.com> writes:

> Thank you! The only thing remaining is that I want to be able to mark
> multiple files and open them all in splits with with C-c o, but it
> seems to only work with one file. Can this be done?

Use C-u RET.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by blaenk** [comment]
Nice! But doing that replaced the window I had, is there a way to open them on their own windows, like C-c o does?

**Comment by thierryvolpiatto** [comment]
Jorge Israel Peña <notifications@github.com> writes:

> Nice! But doing that replaced the window I had, is there a way to open them on their own windows, like C-c o does?

Just mark your current file in addition of others ;-)

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by blaenk** [comment]
Aww, that would require me to find and mark every single existing window I have along with the ones I have to open, something that is needlessly tedious. Is there a way this can be automated, or can I somehow hack around this?

**Comment by thierryvolpiatto** [comment]
Jorge Israel Peña <notifications@github.com> writes:

> Aww, that would require me to find and mark every single existing
> window I have along with the ones I have to open, something that is
> needlessly tedious.

So I don't understand what you want to do.

I thought you wanted to open several files from your current-buffer which
is already displaying a file and display other files in the
selected-window along with this current file.
In this scenario, it is easy to find current file because it is selected
automatically by helm-find-files as soon you kick in.

> Is there a way this can be automated,

I need first to understand what you want to do.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by blaenk** [comment]
Yeah you understood correctly. But imagine if I already have open
_multiple_ files in separate windows, not just one, and I want to open
several files in new windows in the same frame, are all of the currently
open files automatically selected?

1. Open one file; only one file and one window currently
2. Open another file with C-c o, now there's two windows and two files
3. Repeat step 2 to have 3 windows and 3 files open

Now I want to use helm to open say 4 new files in their own _new_ windows,
i.e. not replacing any of the existing split windows.

On Monday, July 20, 2015, Thierry Volpiatto <notifications@github.com>
wrote:

>
> Jorge Israel Peña <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> writes:
>
> > Aww, that would require me to find and mark every single existing
> > window I have along with the ones I have to open, something that is
> > needlessly tedious.
>
> So I don't understand what you want to do.
>
> I thought you wanted to open several files from your current-buffer which
> is already displaying a file and display other files in the
> selected-window along with this current file.
> In this scenario, it is easy to find current file because it is selected
> automatically by helm-find-files as soon you kick in.
>
> > Is there a way this can be automated,
>
> I need first to understand what you want to do.
>
> --
> Thierry
> Get my Gnupg key:
> gpg --keyserver pgp.mit.edu --recv-keys 59F29997
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/emacs-helm/helm/issues/1100#issuecomment-122993168>.
>


-- 
- Jorge Israel Peña

**Comment by thierryvolpiatto** [comment]
Jorge Israel Peña <notifications@github.com> writes:

> Yeah you understood correctly. But imagine if I already have open
> _multiple_ files in separate windows, not just one, and I want to open
> several files in new windows in the same frame, are all of the currently
> open files automatically selected?
>
> 1. Open one file; only one file and one window currently
> 2. Open another file with C-c o, now there's two windows and two files
> 3. Repeat step 2 to have 3 windows and 3 files open

Repeating step 2 will not give you 3 windows, but two windows and the
last opened file will take the place of the first you opened in step 1.

What you want is:

1) M-x helm-find-files => open one file "foo" in one window.
2) M-x helm-find-files => C-c o open another file "bar" in other window.
3) You are now in the second window displaying buffer "bar".
4) M-x helm-find-files and mark "bar" => navigate and mark files "baz"
and "test", Hit C-u RET.

You have now "foo", "bar", "baz", and "test" displayed in separate
windows.

What's wrong with this?

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by blaenk** [comment]
Ohhh I see, so I just have to mark the file of the buffer I'm in in order to preserve it? Thanks I'll try that. It's not that it's wrong, it'd just be nice if there were a binding I could create that allowed me to skip the step of having to mark the current file, sure, it may be straightforward, but it's unrelated to the task I'm doing: opening other files in their own windows. Could this be done? Perhaps I'll take a look at the function bound to `C-u RET` to see if I can make it keep the existing window.

**Comment by xuchunyang** [comment]
> Now I want to use helm to open say 4 new files in their own _new_ windows,
> i.e. not replacing any of the existing split windows.

For opening buffers like the `helm-buffers-list` command, I guess this might be what you want: (you may need to add it to your init file and restart emacs to try this)
```lisp
(defun helm-buffer-switch-new-window (candidate)
  "Display buffers in new windows."
  ;; Select the bottom right window
  (require 'winner)
  (select-window (car (last (winner-sorted-window-list))))
  ;; Display buffers in new windows
  (dolist (buf (helm-marked-candidates))
    (select-window (split-window-right))
    (switch-to-buffer buf))
  ;; (optional) Adjust size of windows
  (balance-windows))

(add-to-list 'helm-type-buffer-actions
             '("Display buffer(s) in new window(s)" .
               helm-buffer-switch-new-window))
```

this assumes: you want to open buffers in new vertical windows created from the right. 

Also notes, when you mark some candidates, i.e., buffers, the current selection may not work, see the docstring of the `helm-marked-candidates` function, the last of marked candidates will always be selected, of course you can tweak this if you don't like this behaviour.

To do this when opening file, customize the `helm-type-file-actions` option similarly.

**Comment by blaenk** [comment]
@xuchunyang Thanks!!! I'll take a look at that.

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

>
> To do this when opening file, customize the helm-type-file-actions option similarly.

Note that for helm-find-files, it is `helm-find-files-actions'.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by blaenk** [comment]
Is it possible to add a key binding for this in the helm map? So that I don't have to go to the action menu, but can instead press the binding (preferably it'll apply to all of the selected candidates if possible).

**Comment by xuchunyang** [comment]
Yes, you can make a wrapper (interactive command) for that action and assign a key for it. The following is a working example for helm-buffer commands (`helm-mini` and `helm-buffers-list` etc):

```elisp
(defun helm-buffer-switch-to-new-window (_candidate)
  "Display buffers in new windows."
  ;; Select the bottom right window
  (require 'winner)
  (select-window (car (last (winner-sorted-window-list))))
  ;; Display buffers in new windows
  (dolist (buf (helm-marked-candidates))
    (select-window (split-window-right))
    (switch-to-buffer buf))
  ;; Adjust size of windows
  (balance-windows))

(add-to-list 'helm-type-buffer-actions
             '("Display buffer(s) in new window(s) `M-o'" .
               helm-buffer-switch-new-window) 'append)

(defun helm-buffer-switch-new-window ()
  (interactive)
  (with-helm-alive-p
    (helm-quit-and-execute-action 'helm-buffer-switch-to-new-window)))

(define-key helm-buffer-map (kbd "M-o") #'helm-buffer-switch-new-window)
```

To custom the command `helm-find-files`, modify `helm-find-files-actions` and corresponding keymap,
to custom the command `helm-recentf` etc, modify `helm-type-file-actions` and corresponding keymap,
etc.

**Comment by blaenk** [comment]
Thanks a lot @xuchunyang! You are amazing :+1:
