### ISSUE TITLE
does helm-projectile generate .# files ?

### ISSUE THREAD

**Issue by sunwukung** [emacs-helm/helm#1105]
Sorry if this is a little off-topic - but I've been struggling to prevent the generation of these files in my projects. I have experimented with auto-save settings etc (see below) and verified them through M-x configuration:

    ;; disable auto-save and auto-backup
    (setq auto-save-default nil)
    (setq auto-save-mode nil)
    (setq make-backup-files nil)

Howver, these files continue to appear. I'm asking because the leading dot suggests that they might not be the standard auto-save back up file? I noticed that I was seeing them in my Helm buffer, so I tried deactivating helm, and they seemed to go away - although this is entirely anecdotal

**Comment by thierryvolpiatto** [comment]
Marcus Kielly <notifications@github.com> writes:

> Sorry if this is a little off-topic - but I've been struggling to
> prevent the generation of these files in my projects. I have
> experimented with auto-save settings etc (see below) and verified them
> through M-x configuration:
>
> ;; disable auto-save and auto-backup (setq auto-save-default nil)
> (setq auto-save-mode nil) (setq make-backup-files nil)
>
> Howver, these files continue to appear. I'm asking because the leading
> dot suggests that they might not be the standard auto-save back up
> file? I noticed that I was seeing them in my Helm buffer, so I tried
> deactivating helm, and they seemed to go away - although this is
> entirely anecdotal

This is unrelated to helm, .# files are autosave files.

Please don't report helm-projectile bugs here.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by sunwukung** [comment]
my apologies - I have been struggling with the issue for days. Those files by the way, are not auto-saves (which is why I had such limited success). They are lock files, which can be disabled. Nonetheless, they are not an artefact originating in Helm.

**Comment by thierryvolpiatto** [comment]
Marcus Kielly <notifications@github.com> writes:

> my apologies - I have been struggling with the issue for days. Those
> files by the way, are not auto-saves (which is why I had such limited
> success). They are lock files, which can be disabled.

Yes right lock files, sorry I always confuse auto save and these
symlinks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
