### ISSUE TITLE
Invoke helm-all-mark-rings result in "Invalid-function (lambda \.\.\. \.\.\.)"

### ISSUE THREAD

**Issue by leodream** [emacs-helm/helm#1106]
When invoking `helm-all-mark-rings`, it does shows all marked spaces. But when trying to access any of them, Emacs throws a `invalid-function(lambda \.\.\. \.\.\.)` error.

GNU Emacs 24.3.1 x86_64-suse-linux-gun
Helm installed from elpa, helm-20150722.413/

Backtrace,
```
Debugger entered--Lisp error: (invalid-function (lambda \.\.\. \.\.\.))
  (lambda \.\.\. \.\.\.)("    592:   \"Copy the current buffer file name to the clipboard.\"")
  apply((lambda \.\.\. \.\.\.) "    592:   \"Copy the current buffer file name to the clipboard.\"")
  helm-funcall-with-source(((name . "mark-ring") (candidates . helm-mark-ring-get-candidates) (action ("Goto line" lambda \.\.\. \.\.\.)) (persistent-action . #[257 "\300\301!!\210\302 \207" [helm-goto-line string-to-number helm-highlight-current-line] 4 "\n\n(fn CANDIDATE)"]) (persistent-help . "Show this line") (filtered-candidate-transformer helm-fuzzy-highlight-matches) (match helm-mp-exact-match helm-mp-match) (header-line . "C-j: Show this line (keeping session)") (dont-plug helm-compile-source--match-plugin helm-compile-source--persistent-help) (matchplugin)) (lambda \.\.\. \.\.\.) "    592:   \"Copy the current buffer file name to the clipboard.\"")
  helm-execute-selection-action-1()
  helm-execute-selection-action()
   #[0 "\311\211\211\211\305\206\n&^@^N&^^(^^)^^*\312\313^N+\"\314\315\316\317\320\321!\322\"\323\324%DC\216\325\303\301\307\300$\210\326&!\210,\203?...
  helm-internal((helm-source-mark-ring helm-source-global-mark-ring) nil nil noresume nil "*helm mark ring*" nil nil nil)
  apply(helm-internal ((helm-source-mark-ring helm-source-global-mark-ring) nil nil noresume nil "*helm mark ring*" nil nil nil))
  helm((helm-source-mark-ring helm-source-global-mark-ring) nil nil noresume nil "*helm mark ring*" nil nil nil)
  apply(helm ((helm-source-mark-ring helm-source-global-mark-ring) nil nil noresume nil "*helm mark ring*" nil nil nil))
  helm(:sources (helm-source-mark-ring helm-source-global-mark-ring) :resume noresume :buffer "*helm mark ring*")
  helm-all-mark-rings()
  call-interactively(helm-all-mark-rings nil nil)
```

On the other hand, `helm-show-kill-ring`  is working fine.
Also noticed that, deleting the `.session` file could bring it back to work, but after restart, the problem returned.

**Comment by thierryvolpiatto** [comment]
Leo He <notifications@github.com> writes:

> On the other hand, helm-show-kill-ring is working fine.
> Also noticed that, deleting the .session file could bring it back to
> work, but after restart, the problem returned.

Yes it is a bug with session.el, it have been reported several times,
look in the closed issues, there is a session variable to modify, don't
remember which one as I don't use it (I use psession.el, my own
package).


-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by leodream** [comment]
I guess you mean https://github.com/emacs-helm/helm/issues/94 (did not find this previously, sorry).
It seems to work. Thank you.

**Comment by thierryvolpiatto** [comment]
Nice, I have added an entry in the FAQ of wiki.

Thanks.
