### ISSUE TITLE
helm-register-candidates in helm-ring.el 

### ISSUE THREAD

**Issue by cmccloud** [emacs-helm/helm#1107]
When building out string-actions in helm-register-candidates, the final clause of the conditional
returns a string - the subsequent calls to car and cdr will error out and the source list is never built.
The code in question is:
``` 
(defun helm-register-candidates ()
  "Collecting register contents and appropriate commands."
  (cl-loop for (char . val) in register-alist
        for key    = (single-key-description char)
        for string-actions =
        (cond
         //clauses...//
          (t
           "GARBAGE!"))
        ;; when (listp string-actions) 
        collect (cons (format "Register %3s:\n %s" key (car string-actions))
                      (cons char (cdr string-actions)))))
```
Adding the commented line fixed the issue for me.

Thanks so much for all of the work, Helm is really incredible.

**Comment by thierryvolpiatto** [comment]
Christopher McCloud <notifications@github.com> writes:

> When building out string-actions in helm-register-candidates, the final clause of the conditional
> returns a string - the subsequent calls to car and cdr will error out
> and the source list is never built.

Indeed, fixed by 2942cbe. 

Thanks!

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
