### ISSUE TITLE
error "To bind the key C-M-SPC, use [?\\C-\\M- ], not [C-M-SPC]

### ISSUE THREAD

**Issue by semanticart** [emacs-helm/helm#1108]
I've been getting this error lately when updating helm. 

Updating helm-buffers.el's `helm-buffers-mark-similar-buffers` binding to be 

```lisp
    (define-key map (kbd "<C-M- >") 'helm-buffers-mark-similar-buffers)
```

Makes emacs happier, but then

> Debugger entered--Lisp error: (error "To bind the key M-RET, use \"\\M-\\r\", not [M-RET]")

Making the suggested change to helm-files.el and helm-mode.el result in everything being ok.

I don't know much about emacs plugins and compatibility so I'm not submitting a PR yet. Is this the right solution or is there a better approach?

**Comment by thierryvolpiatto** [comment]
Jeffrey Chupp <notifications@github.com> writes:

> I've been getting this error lately when updating helm.
>
> Updating helm-buffers.el's helm-buffers-mark-similar-buffers binding to be
>
>     (define-key map (kbd "<C-M- >") 'helm-buffers-mark-similar-buffers)
>
> Makes emacs happier, but then
>
>     Debugger entered--Lisp error: (error "To bind the key M-RET, use \"\M-\r\", not [M-RET]")

See Issue #1092.
    
-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
