### ISSUE TITLE
Helm loading time is high

### ISSUE THREAD

**Issue by rrittwikc** [emacs-helm/helm#1109]
First of all Hi! and thank you for helm. I really like helm and use it everyday!

I have cloned the helm repo today (thought update it after a long time :) ).

While byte-compiling using make, I noticed the following output line
`ad-handle-definition: 'tramp-read-passwd' got redefined`
The compilation took around 11 seconds before showing this output line.

After that whenever I am opening emacs, it is taking 12-13 seconds and showing this output line. However if I disable helm, emacs is taking 1-2 seconds.

My emacs version is 24.5.1 I am using fedora 22 64bit KDE.

Sorry for my very bad english!

**Comment by thierryvolpiatto** [comment]
Rittwik Chatterjee <notifications@github.com> writes:

> First of all Hi! and thank you for helm. I really like helm and use it everyday!
>
> I have cloned the helm repo today (thought update it after a long time :) ).
>
> While byte-compiling using make, I noticed the following output line
> ad-handle-definition: 'tramp-read-passwd' got redefined

Not a problem, this what is expected.

> The compilation took around 11 seconds before showing this output line.

It take here actually: 2.798s
So probably a problem on your side.

> After that whenever I am opening emacs, it is taking 12-13 seconds and
> showing this output line. However if I disable helm, emacs is taking
> 1-2 seconds.

My emacs is loading in around 3s with a huge .emacs absolutely not
optimized.

Your delay is maybe due to issue #1000 and maybe the compilation too.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by rrittwikc** [comment]
Thanks thierryvolpiatto for the reply.

I disable all my other settings and plugins only helm is enabled. But the lag is still there.
So is it the case that the problem is with fedora's or kde's emacs?

Below is my helm settings 
;; -------------------------------------------------------------
;; Helm settings
;; -------------------------------------------------------------

;;(add-to-list 'load-path "~/.emacs.d/plugins/async/")

(add-to-list 'load-path "~/.emacs.d/plugins/helm/")
(require 'helm-config)

;; -------------------------------------------------------------

(setq helm-split-window-in-side-p           t ; open helm buffer inside current window, not occupy whole other window
      helm-buffers-fuzzy-matching           t ; fuzzy matching buffer names when non--nil
      helm-move-to-line-cycle-in-source     t ; move to end or beginning of source when reaching top or bottom of source.
      helm-ff-search-library-in-sexp        t ; search for library in `require' and `declare-function' sexp.
      helm-scroll-amount                    8 ; scroll 8 lines other window using M-<next>/M-<prior>
      helm-ff-file-name-history-use-recentf t)

(setq helm-split-window-default-side (quote right))

(helm-mode 1)

;; -------------------------------------------------------------

(provide 'init-helm-settings)

;; -------------------------------------------------------------

**Comment by thierryvolpiatto** [comment]
Rittwik Chatterjee <notifications@github.com> writes:

> Thanks thierryvolpiatto for the reply.
>
> I disable all my other settings and plugins only helm is enabled. But the lag is still there.
> So is it the case that the problem is with fedora's or kde's emacs?

Please read Issue #1000

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Closing this because it is probably related to #1000
