### ISSUE TITLE
helm-eval-expression feedback

### ISSUE THREAD

**Issue by michael-heerdegen** [emacs-helm/helm#1110]
Hi,

I want to suggest to make "helm-eval-expression" give feedback in the minibuffer after hitting RET.

At least the result of the calculation  (I often hit RET and wondered what the result was before realizing that it had been already shown on the fly).  Or even better "result  [stored in kill-ring]".  WDYT?

**Comment by thierryvolpiatto** [comment]
You already can store in kill-ring

**Comment by michael-heerdegen** [comment]
Yes, it's what the default (the only) action does (good).  But when the user hits RET, he doesn't notice that (bad).  That's why I want to show  "result  [stored in kill-ring]" in the echo area  (whereby "result" is the result of the computation).

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Yes, it's what the default (the only) action does (good).

No you have two actions.

> But when the user hits RET, he doesn't notice that (bad). That's why I
> want to show "result [stored in kill-ring]" in the echo area (whereby
> "result" is the result of the computation).

Should not be too hard...

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
But don't add the result of computation in the message (it may be too big).

**Comment by michael-heerdegen** [comment]
Now I see where the confusion comes from - I wrote the wrong function name in the issue title.  My suggestion originally had been about "helm-calcul-expression".  Is it ok to add the result of the computation to the message there?

But of course we should treat helm-eval-expression the same way.

 Last but not least, I guess we should add a "(kill-new helm-input)" like action to the "helm-source-calculation-result" source as well.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Now I see where the confusion comes from - I wrote the wrong function
> name in the issue title. My suggestion originally had been about
> "helm-calcul-expression". Is it ok to add the result of the
> computation to the message there?

Yes.

> But of course we should treat helm-eval-expression the same way.

Yes but without the result in the message.

> Last but not least, I guess we should add a "(kill-new helm-input)"
> like action to the "helm-source-calculation-result" source as well.

Agreed.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
Thanks!  But didn't we want to message the result of the computation in case of "helm-calcul-expression"?

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Thanks! But didn't we want to message the result of the computation in
> case of "helm-calcul-expression"?

Finally I didn't add it as it is displayed anyway in helm buffer.
Add it if you think it is useful.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
