### ISSUE TITLE
"*" should not have a higer precedence than "/" in helm-calcul-expression

### ISSUE THREAD

**Issue by leodream** [emacs-helm/helm#1111]
![selection_522](https://cloud.githubusercontent.com/assets/2774809/8876997/a6095bd6-3255-11e5-8e7f-7b79e602c690.png)

`8/2*2` should return `8`, instead of `2`.

Helm Version: 20150722.413

**Comment by michael-heerdegen** [comment]
That's just what the "Calc" package does, try M-x quick-calc.  If that's not what you want, maybe there is a calc option for that.  Or just talk to the calc people.

**Comment by thierryvolpiatto** [comment]
Use parenthesis

(8/2)*2
