### ISSUE TITLE
helm-resume won't resume the point in the helm session buffer 

### ISSUE THREAD

**Issue by c02y** [emacs-helm/helm#1112]
Say, I use `helm-occur` to search a word in the buffer and it will list all the candidates in the **helm occur** buffer, if I hit `Enter` at the 5th candidate to view/modify, after that use `helm-resume` to resume the session, the best thing is it will resume my point to the 5th candidate instead the first candidate. 

Is there any variable to do that?

**Comment by thierryvolpiatto** [comment]
c02y <notifications@github.com> writes:

> Say, I use helm-occur to search a word in the buffer and it will list
> all the candidates in the helm occur buffer, if I hit Enter at the 5th
> candidate to view/modify, after that use helm-resume to resume the
> session, the best thing is it will resume my point to the 5th
> candidate instead the first candidate.
>
> Is there any variable to do that?

No, this is a bug, following in a few minutes a fix.

For memory, it is non sense to kick in default as input when an input
already exists in minibuffer.

Thanks for catching this.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
