### ISSUE TITLE
Add ability to adjust width of buffer name column

### ISSUE THREAD

**Issue by dakrone** [emacs-helm/helm#1113]
It would be great if I could configure the column width for the buffer name in `helm-buffers-list`,

For example, see how these are cut off:

![screenshot from 2015-07-24 15-36-48](https://cloud.githubusercontent.com/assets/19060/8885123/0de8e532-321a-11e5-8926-5775d405caf4.png)

(as you can see, I work with Java, hence the stupid-long file/buffer names)

**Comment by dakrone** [comment]
Hmm... also, I wonder if helm could get 2 extra characters out of the buffer by using unicode elipsis (`…`) instead of three periods?

**Comment by xuchunyang** [comment]
increase the `helm-buffer-max-length` user option (default 20) or just type `C-]` (`helm-toggle-buffers-details`) to view full name of buffer.

**Comment by dakrone** [comment]
@xuchunyang thanks! That fixes it for me. (I do still think using an ellipsis instead three periods would save space too though).

**Comment by michael-heerdegen** [comment]
There is an official variable for the eliding string (no option though): "truncate-string-ellipsis".  Thierry, should we respect it?

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> There is an official variable for the eliding string (no option
> though): "truncate-string-ellipsis". Thierry, should we respect it?

No, we have our own function, thus this var seems to be available only
on 25.
If we want to use ellipsis, it is simple, there is just two calls to
helm-substring-by-width that use default value of last arg, just need to
provide this value there (i.e "…" instead of "...").

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> If we want to use ellipsis, it is simple, there is just two calls to
> helm-substring-by-width that use default value of last arg, just need to
> provide this value there (i.e "…" instead of "...").

Are there any problems to expect?  I checked console and
xterm here (Debian), and the character displays ok.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Thierry Volpiatto <notifications@github.com> writes:
>
>> If we want to use ellipsis, it is simple, there is just two calls to
>> helm-substring-by-width that use default value of last arg, just need to
>> provide this value there (i.e "…" instead of "...").
>
> Are there any problems to expect?

AFAIK no.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
@thierryvolpiatto  and everyone else: I changed the default ellipsis string in https://github.com/emacs-helm/helm/commit/241ec5fbb9fcaed98d61f53e7b23edaedd429bea.  I avoided to put the unicode character directly into the source code, because this can cause problems.

I also added a trivial fix that makes true what the docstring says: the return value should have the given width (that was not the case with the original version; when given a string that was one char longer than the given width, it removed one char and added three dots).

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> @thierryvolpiatto and everyone else: I changed the default ellipsis
> string in 241ec5f. I avoided to put the unicode character directly
> into the source code, because this can cause problems.
>
> I also added a trivial fix that makes true what the docstring says:
> the return value should have the given width (that was not the case
> with the original version; when given a string that was one char
> longer than the given width, it removed one char and added three
> dots).

Perhaps I wrote wrongly the docstring ?
Anyway it doesn't behave as expected now i.e:

(helm-substring-by-width "thierry" 5 "...")
=> I expect "thier..." but have now "th..."

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> Anyway it doesn't behave as expected now i.e:
>
> (helm-substring-by-width "thierry" 5 "...")
> => I expect "thier..." but have now "th..."

What you expect is 8 characters long, not 5.  How would a
limit-to-column function make sense when it returns results that go
beyond that column?

**Comment by michael-heerdegen** [comment]
Michael Heerdegen <michael_heerdegen@web.de> writes:

> What you expect is 8 characters long, not 5.  How would a
> limit-to-column function make sense when it returns results that go
> beyond that column?

And with the old version, a string with length less than 5 (in this
example) had been returned as string of width 5, not 8.  So, the
returned strings did not all have equal widths, as opposed to what the
doc said.

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> (helm-substring-by-width "thierry" 5 "...")
> => I expect "thier..." but have now "th..."

And when you allow the returned string to be wider than 5, wouldn't it
make more sense to leave it as "thierry"?  Why use eliding when it makes
the result longer???

**Comment by michael-heerdegen** [comment]
Michael Heerdegen <michael_heerdegen@web.de> writes:

> Thierry Volpiatto <notifications@github.com> writes:
>
> > (helm-substring-by-width "thierry" 5 "...")
> > => I expect "thier..." but have now "th..."

I think I begin to understand now how the code was supposed to work.  You
take into account that the elided string is longer.  In
`helm-highlight-buffers', you add a whitespace string of length 3 to the
buffer names that are not truncated, to compensate the added length of
"..." when truncating.  The number "3" is hardcoded (!).  We would have
to change that one way or the other when allowing arbitrary ellipses.

My commit makes such appending of a string with length of the used
ellipsis for non-elided string superfluous, IMHO this makes the code
much cleaner.

> And when you allow the returned string to be wider than 5, wouldn't it
> make more sense to leave it as "thierry"?  Why use eliding when it makes
> the result longer???

Of cause this still applies.

Anyway, you are surely on vacation or so.  This doesn't hurry, have a
good time.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Michael Heerdegen <michael_heerdegen@web.de> writes:
>
>> Thierry Volpiatto <notifications@github.com> writes:
>>
>> > (helm-substring-by-width "thierry" 5 "...")
>> > => I expect "thier..." but have now "th..."
>
> I think I begin to understand now how the code was supposed to work. You
> take into account that the elided string is longer. In
> `helm-highlight-buffers', you add a whitespace string of length 3 to the
> buffer names that are not truncated, to compensate the added length of
> "..." when truncating. The number "3" is hardcoded (!). We would have
> to change that one way or the other when allowing arbitrary ellipses.
>
> My commit makes such appending of a string with length of the used
> ellipsis for non-elided string superfluous, IMHO this makes the code
> much cleaner.
>
>> And when you allow the returned string to be wider than 5, wouldn't it
>> make more sense to leave it as "thierry"? Why use eliding when it makes
>> the result longer???
>
> Of cause this still applies.
>
> Anyway, you are surely on vacation or so. This doesn't hurry, have a
> good time.

Thanks, I will be able to look at all this more carefully probably next
week.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
