### ISSUE TITLE
`helm-M-x` error

### ISSUE THREAD

**Issue by srustamo** [emacs-helm/helm#1114]
Calling `helm-M-x` fails. Debugger output below. What's wrong?

GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, Carbon Version 157 AppKit 1265.21) of 2015-05-01 on srmbp.local

`Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  intern(nil)
  helm-M-x-read-extended-command()
  byte-code("\301 D\207" [current-prefix-arg helm-M-x-read-extended-command] 2)
  #<subr call-interactively>(helm-M-x record nil)
  ad-Advice-call-interactively(#<subr call-interactively> helm-M-x record nil)
  apply(ad-Advice-call-interactively #<subr call-interactively> (helm-M-x record nil))
  call-interactively(helm-M-x record nil)
  command-execute(helm-M-x record)
  execute-extended-command(nil "helm-M-x")
  #<subr call-interactively>(execute-extended-command nil nil)
  ad-Advice-call-interactively(#<subr call-interactively> execute-extended-command nil nil)
  apply(ad-Advice-call-interactively #<subr call-interactively> (execute-extended-command nil nil))
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)`

**Comment by thierryvolpiatto** [comment]
srustamo <notifications@github.com> writes:

> Calling helm-M-x fails. Debugger output below. What's wrong?

Please start from ./emacs-helm.sh and see if you can reproduce.

It is not reproductible here (Ubuntu and Windows7).

Looks like something is modified in your emacs, how do you call
`helm-M-x' ?

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by srustamo** [comment]
I tried to call it both by `(global-set-key (kbd "M-x") 'helm-M-x)` and interactively, using `ido`. Also disabled all other completion packages, and just run `M-x helm-M-x`. All methods produce the above error.

Incidentally, I have this in my config `(global-set-key "\C-x\C-m" 'execute-extended-command)
`, and running this command brings up `helm` buffer, if `(helm-mode 1)`.

**Comment by michael-heerdegen** [comment]
Please also start from ./emacs-helm.sh and see if you can reproduce.

**Comment by srustamo** [comment]
I installed Helm using package manger. It installed Helm to `/Users/s3/.emacs.d/elpa/helm-20150724.256`. Inside this dir I run `./emacs.sh` and get the following error:
`byte-code: Cannot open load file: no such file or directory, helm`

**Comment by michael-heerdegen** [comment]
srustamo <notifications@github.com> writes:

> I installed Helm using package manger. It installed Helm to
> /Users/s3/.emacs.d/elpa/helm-20150724.256. Inside this dir I run ./emacs.sh and get
> the following error:
> byte-code: Cannot open load file: no such file or directory, helm

Indeed!  The current Melpa package doesn't include helm.el, but we
require it in helm.sh.  Thierry, why is that?

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> srustamo <notifications@github.com> writes:
>
>> I installed Helm using package manger. It installed Helm to
>> /Users/s3/.emacs.d/elpa/helm-20150724.256. Inside this dir I run ./emacs.sh and get
>> the following error:
>> byte-code: Cannot open load file: no such file or directory, helm
>
> Indeed! The current Melpa package doesn't include helm.el, but we
> require it in helm.sh. Thierry, why is that?

helm.el is in helm-core now.
I have commited a fix, didn't test though, but should work.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by srustamo** [comment]
Yeah, `helm-M-x` works with this minimal helm config. Let me see what could be causing this error in my config. 
Please chime-in if you have any ideas.

**Comment by srustamo** [comment]
Ah, actually, the latest helm from elpa does not give this error, now that I checked.
