### ISSUE TITLE
Helm preselect does not select correct car of history

### ISSUE THREAD

**Issue by cslux** [emacs-helm/helm#1115]
Hey,

in the package [helm-make (line 115)](https://github.com/abo-abo/helm-make/blob/master/helm-make.el#L115), helm gets as candidates the makefile targets and stores the history in `helm-make-target-history`,  preselect gets the `car` of `helm-make-target-history`. 

Now consider the following targets (candidates)

```
("default_target" "$(VERBOSE).SILENT" "cmake_force" "install/strip"
 "install/strip/fast" "edit_cache" "edit_cache/fast" "rebuild_cache" 
"rebuild_cache/fast" "install" "install/fast" "list_install_components" 
"list_install_components/fast" "test" "test/fast" "install/local" 
"install/local/fast" "all" "clean" "clean/fast" "preinstall" "preinstall/fast" 
"depend" "uninstall" "uninstall/fast" "help" "cmake_check_build_system")
```
When calling `helm-make-projectile` and entering "all" into the minibuffer the target "all" gets selected as intended. When calling `helm-make-projectile` again I would expect that the target "all" gets preselected. However, this is not the case, instead "install/strip" gets preselected as it is the first element of the `targets` list containing "all".

So my question is now, how can I insure that the correct target gets preselected?

`Ivy` f.i. does this correctly.

Thanks,
Christian

**Comment by xuchunyang** [comment]
I think you mean the following example will pre-select "foobar" but not "bar", then you can use `(concat "\\_<" (regexp-quote "bar") "\\_>")` instead of `"bar".
```lisp
(helm :sources (helm-build-sync-source "test"
                 :candidates '("foobar" "bar" "baz"))
      :preselect "bar")
```
the doc for `:preselect` is a bit misleading.

**Comment by thierryvolpiatto** [comment]
Please report bugs of projectile to projectile, not here, thanks.

**Comment by cslux** [comment]
I'll close this issue as `helm-comp-read` solves the problem.
