### ISSUE TITLE
Port helm-ff-run-switch-to-history to helm read-file-name implementation

### ISSUE THREAD

**Issue by tnielens** [emacs-helm/helm#1118]
Is it possible to use the helm-ff-run-switch-to-history (bound to M-p) available within helm-find-files in helm read-file-name implementation ?

**Comment by thierryvolpiatto** [comment]
Of course it is possible, use `helm-read-file-map`.
I will not enable this by default because I know there is users that want to have the regular `M-p` behavior in `find-file` and friends.

**Comment by michael-heerdegen** [comment]
What should the user do in his config to "use helm-read-file-map"?

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> What should the user do in his config to "use helm-read-file-map"?

(define-key helm-read-file-map (kbd "M-p") 'helm-ff-run-switch-to-history)

Note that will allow switching to a directory in helm-find-files but
NOT with original function.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
> (define-key helm-read-file-map (kbd "M-p") 'helm-ff-run-switch-to-history)

Thanks.

**Comment by tnielens** [comment]
> (define-key helm-read-file-map (kbd "M-p") 'helm-ff-run-switch-to-history) 
It works fine but shows only the subdirectories of the buffer's current dir. (Rename function of the dired mode for example). It is possible to get the full list of last used dirs ?

**Comment by thierryvolpiatto** [comment]
tnielens <notifications@github.com> writes:

>     (define-key helm-read-file-map (kbd "M-p")
>     'helm-ff-run-switch-to-history) It works fine but shows only the
>     subdirectories of the buffer's current dir. (Rename function of
>     the dired mode for example). It is possible to get the full list
>     of last used dirs ?

Please a complete recipe of what you are doing.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tnielens** [comment]
Except:
> (define-key helm-read-file-map (kbd "M-p") 'helm-ff-run-switch-to-history)

I didn't put anything special in my init.el file. 
Scenario : 
In a dired buffer, I use the dired-do-rename command ( R key ).
This asks for a file name. When I use M-p to display the list of last used directories (the helm-find-files way), I get the list of last used directories that are subdirectories of the current one and not the full list.

**Comment by thierryvolpiatto** [comment]
tnielens <notifications@github.com> writes:

> Except:
>
>     (define-key helm-read-file-map (kbd "M-p") 'helm-ff-run-switch-to-history)
>    
> I didn't put anything special in my init.el file.  Scenario : In a
> dired buffer, I use the dired-do-rename command ( R key ).  This asks
> for a file name. When I use M-p to display the list of last used
> directories (the helm-find-files way), I get the list of last used
> directories that are subdirectories of the current one and not the
> full list.

Because you have the current dir in minibuffer.
This will not do the same as helm-find-files for copying/renaming etc...
IOW it will not help binding ff-history to read-file-name.

Instead you have better time using directly helm-find-files with cursor
on filename you want to rename:
C-x C-f => M-R

Even better use always helm-find-files and get rid of dired.
(yes I am not a fan of dired :-))

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tnielens** [comment]
> Instead you have better time using directly helm-find-files with cursor on filename you want to rename: C-x C-f => M-R

I use a lot the file actions avalaible in helm-find-files. But I
somtimes find the dired-mode handy, because it persists across the
session, you can get back in the buffer and operate on the files you
marked a while ago.
It'd be great if the helm-ff-run-switch-to-history would behave the same way for that kind of operations or others (diff, vc-dir, etc).

**Comment by thierryvolpiatto** [comment]
tnielens <notifications@github.com> writes:

>     Instead you have better time using directly helm-find-files with cursor on filename you want to rename: C-x C-f => M-R
>    
> I use a lot the file actions avalaible in helm-find-files. But I
> somtimes find the dired-mode handy, because it persists across the
> session, you can get back in the buffer and operate on the files you
> marked a while ago.

You can retrieve your directories by bookmarking them:
From helm-find-files, navigate to your favorite directory and hit `C-x r
m', then next time you start helm-find-files you can do `C-x r b' to
retrieve easily your favorites directories.

> It'd be great if the helm-ff-run-switch-to-history would behave the
> same way for that kind of operations or others (diff, vc-dir, etc).

All of these should behave as much as possible as they are in vanilla
emacs, no more.
Also many people are using e.g find-file helmized and do not want
helm-ff-run-switch-to-history.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tnielens** [comment]
I just find the helm-ff-run-switch-to-history super handy and wish it was available in read-file-name with the sale list of dirs as in helm-find-files. It doesn't need to be the default behavior or bound to the M-p key or anything. Just available through customization  would be great  :)

**Comment by thierryvolpiatto** [comment]
tnielens <notifications@github.com> writes:

> I just find the helm-ff-run-switch-to-history super handy and wish it
> was available in read-file-name with the sale list of dirs as in
> helm-find-files. It doesn't need to be the default behavior or bound
> to the M-p key or anything. Just available through customization would
> be great :)

You have to understand that the history you have in helm-find-files when
e.g copying files is given to the `history' argument of
`helm-read-file-name'.
However `read-file-name' have no `history' argument, this is the reason
why there is no history when you use e.g "C" or "R" from dired.

The best would be that emacs provide a history argument to
`read-file-name', this would allow having same behavior than in
helm-find-files where needed (in places like in dired)
without adding history where it is not needed.

Many people are asking for additional features in helmized functions,
but they have to understand that helm-mode is providing a generic code
that works for everything and can't be specialized for this or that,
it is why it is better when possible to use native helm commands
instead.

Hopefully we have a mechanism that allow writing specialized functions
when needed, these functions being added to
`helm-completing-read-handlers-alist'.
So one can add an entry like (dired-do-copy . my-fn-for-dired-do-copy)
in `helm-completing-read-handlers-alist'.

This would be a lot of effort for few benefit though when you know that
all this is handled in helm-find-files.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
Would it be possible to bind M-p in the OP's case to something more
suitable than "helm-ff-run-switch-to-history"?

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Would it be possible to bind M-p in the OP's case to something more
> suitable than "helm-ff-run-switch-to-history"?

No, M-p is of no help for him in the case of dired-do-*, you need an
extra history source in helm-read-file-name for this particular case.
As I said read-file-name doesn't provide a history argument, it is hard
coded to file-name-history.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
Would it make sense for the OP to

    (defvaralias 'file-name-history 'helm-ff-history)

I think that could be reasonable if you want a shared history all the
time anyway.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Would it make sense for the OP to
>
> (defvaralias 'file-name-history 'helm-ff-history)
>
> I think that could be reasonable if you want a shared history all the
> time anyway.

No, as I said it will not be available in the helm interface due to the
lack of history argument in read-file-name.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> > (defvaralias 'file-name-history 'helm-ff-history)
> >
> No, as I said it will not be available in the helm interface due to the
> lack of history argument in read-file-name.

But if he binds

  (define-key helm-read-file-map (kbd "M-p")
    'helm-ff-run-switch-to-history)

and has done

  (defvaralias 'file-name-history 'helm-ff-history)

just after starting Emacs, the both vars will always share the same
value, and "'helm-ff-run-switch-to-history" will always show the history
of both helm and Vanilla file completion, no?

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> just after starting Emacs, the both vars will always share the same
> value, and "'helm-ff-run-switch-to-history" will always show the history
> of both helm and Vanilla file completion, no?

Not when copying/renaming etc...

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
