### ISSUE TITLE
Helm-projectile won't find files in Windows 10

### ISSUE THREAD

**Issue by rschuetzler** [emacs-helm/helm#1119]
Initially I received an error that `FIND: Parameter format not correct`. I'm not sure what changed, but now when I look at `*Messages*` all it tells me is: `Aborting an helm session running in background`. This happens even when I run helm-projectile immediately after opening Emacs.

**Comment by thierryvolpiatto** [comment]
Please people DO NOT SEND projectile bugs HERE.

**Comment by tuhdo** [comment]
Please open this issue in Projectile repo. The reason it cannot find file is because Emacs is using the built-in find. You have to provide the GNU find for better, version control binaries like `git`, `svn`... by installing Cygwin.

**Comment by rschuetzler** [comment]
So sorry. Brainfart led me to put the bug here.
