### ISSUE TITLE
do not hard-code helm-find-files-doc-header

### ISSUE THREAD

**Issue by listx** [emacs-helm/helm#1120]
In https://github.com/emacs-helm/helm/blob/576cc21f381977e1d3c509d94f73853a74612cff/helm-files.el#L385 we can see that the message hardcodes the keymap "C-l". I've remapped this key and would prefer if it was not displayed at all. For now I've set `helm-find-files-doc-header` to `nil`, but it's a sub-optimal solution.

I am new to helm and I wonder if we hardcode such messages elsewhere.

**Comment by thierryvolpiatto** [comment]
It is fixed now.

Thanks.
