### ISSUE TITLE
option for helm-find-files not to expand symbolic links in path

### ISSUE THREAD

**Issue by 2mc** [emacs-helm/helm#1121]
Is there a way to make helm-find-files not to expands symblic links in the selected path, such that the resulting buffer-file-name transparently respects the very path with all it's symlinks?

Even if not using helm-find-files directly but calling M-x find-file instead, the helm completion pops up and expands my path while warking through the symbolic links always up to the final file-truename.

If there is no such option, possibly there are some workarounds?

**Comment by thierryvolpiatto** [comment]
2mc <notifications@github.com> writes:

> Is there a way to make helm-find-files not to expands symblic links in
> the selected path, such that the resulting buffer-file-name
> transparently respects the very path with all it's symlinks?
>
> Even if not using helm-find-files directly but calling M-x find-file
> instead, the helm completion pops up and expands my path while warking
> through the symbolic links always up to the final file-truename.
>
> If there is no such option, possibly there are some workarounds?

No, the actual behavior is perfectly fine.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
2mc <notifications@github.com> writes:

> Is there a way to make helm-find-files not to expands symblic links in
> the selected path, such that the resulting buffer-file-name
> transparently respects the very path with all it's symlinks?

Note that helm is not doing something particular, the behavior you are
seeing is the one of emacs vanilla `find-file'.

- If you true file is under version control you are asked to follow
  symlink unless the buffer is already displayed under its true name, in
  this case a message is sent telling you that the symlink and the true
  file are the same thing.

- If your file is not under version control emacs is finding the file
  under its symlink name.

 
-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by 2mc** [comment]
Dear Thierry, 
thank your for the quick response.
Maybe I didn't make may case clear enough, or I miss something important here.
Let's condsider this very simple case:

If I try to open a file in my home directory with helm-find-files by typing in the minibuffer promt:

    ~/

The path in the minibuffer get's immediately expanded to:

    /Users/admin/

So, if I continue to open (e.g. somefile) this way, the resulting buffer-file-name will be absolute and will start with /Users/admin/somefile as well, instead the wanted ~/somefile as this is well the case with standard M-x find-file.

My desperate question is how can I achieve this with helm or how can I avoid this unwanted path expansion of helm right there in the minibuffer?

Best, mc

But what I desperatly need to achieve is

**Comment by 2mc** [comment]
Elaborating on the above simple case a bit further: 

If somefile is a symbolic link, let's say pointing to another file system, the same thing happens and 

the symlink get's immediately expanded in the minibuffer.

Then this expansion is -- but should NOT -- be reflected in the buffer-file-name, too.

**Comment by thierryvolpiatto** [comment]
2mc <notifications@github.com> writes:

> Dear Thierry,
> thank your for the quick response.
> Maybe I didn't make may case clear enough, or I miss something important here.
> Let's condsider this very simple case:
>
> If I try to open a file in my home directory with helm-find-files by typing in the minibuffer promt:
>
> ~/
>
> The path in the minibuffer get's immediately expanded to:
>
> /Users/admin/
>
> So, if I continue to open (e.g. somefile) this way, the resulting
> buffer-file-name will be absolute and will start with
> /Users/admin/somefile as well, instead the wanted ~/somefile as this
> is well the case with standard M-x find-file.
>
> My desperate question is how can I achieve this with helm or how can I
> avoid this unwanted path expansion of helm right there in the
> minibuffer?

Sorry but helm is not handling this.
Is it really a problem to have the true name as buffer name?

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by 2mc** [comment]
Dear Thierry, 

thank you for confirming that helm is actually the culprit and that I am addressing the right forum here.

Yes, it is absolutely indispensable for my workflow that relative and symlinked paths do survive and are stored in the buffer-file-name var.

If you work on different computers (with non identical file systems) and you synchronise 

- your emacs desktop, 
- or (more typically perhaps), your current workgroups2 (wg2) setup
- or (most importantly and most common), your daily changing list of org-agenda-files 

between your machines, you are depending on relative paths and maintained symbolic links in the path.


I think these examples explain well, why it is important not to convert all files you open via helm to their true filename.

I'd like to say that I really love helm, for its speed, clarity of interface and generality. But at this crucial point it is not yet general enough! 

If this shortcoming cannot be solved in some way, I would need to sacrifice all helm's path completion in order to gain back the common emacs functionality of visiting files.

I hope this horror scenario can be avoided.
Best, 
mc

**Comment by thierryvolpiatto** [comment]
2mc <notifications@github.com> writes:

> Yes, it is absolutely indispensable for my workflow that relative and
> symlinked paths do survive and are stored in the buffer-file-name var.

d2ba6a8 should fix your problem, but not fully sure as I am not sure to
understand how your system is configured.

Probably I will have also to improve highlighting to notify user she is
actually following a symlinked directory.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
2mc <notifications@github.com> writes:

> Dear Thierry,
> thank your for the quick response.
> Maybe I didn't make may case clear enough, or I miss something important here.
> Let's condsider this very simple case:
>
> If I try to open a file in my home directory with helm-find-files by typing in the minibuffer promt:
>
> ~/
>
> The path in the minibuffer get's immediately expanded to:
>
> /Users/admin/
>
> So, if I continue to open (e.g. somefile) this way, the resulting
> buffer-file-name will be absolute and will start with
> /Users/admin/somefile as well, instead the wanted ~/somefile as this
> is well the case with standard M-x find-file.

I am affraid I can't do anything on the helm side for what you want.

If you do from emacs -Q: 

M-x find-file ~/somefile

AFAIK, the resulting buffer-file-name will be:

(expand-file-name "~/somefile") => "/Users/admin/somefile".

Or did I miss something ?

To where "/Users/admin/" is symlinked ?

I never saw such a system configuration, I guess you are using Mac OS ?

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by 2mc** [comment]
YES, it fixes my problem. Thank you so much!

True, I am on a mac, but that makes no difference here.

Yes, you are right, Emacs expands ~/ to $(HOME). But, if ~/somefile is a symlink, it gets not expanded any further to its truename. As a result, with your above fix, we have the same behaviour now with helm. Great!

In order to get the relative path of ~./somefile back, we can now RELIABLY use the below standard method, which we could not before the fix:

    (concat "$home/" (file-relative-name (buffer-file-name) (expand-file-name "~")))



Highlighting of symlinks is a nice idea!
If we would have some sort of highlighting symlinks in the path, we would gain transparency about what paths to choose.

**Comment by thierryvolpiatto** [comment]
2mc <notifications@github.com> writes:

> YES, it fixes my problem. Thank you so much!

Great!

> True, I am on a mac, but that makes no difference here.
>
> Yes, you are right, Emacs expands ~/ to $(HOME). But, if ~/somefile is
> a symlink, it gets not expanded any further to its truename. As a
> result, with your above fix, we have the same behaviour now with
> helm. Great!

So the behavior is the same as here on GNU/Linux, good.

> In order to get the relative path of ~./somefile back, we can now
> RELIABLY use the below standard method, which we could not before the
> fix:
>
> (concat "$home/" (file-relative-name (buffer-file-name)
> (expand-file-name "~")))

Yes using substitute-in-file-name would help also.

> Highlighting of symlinks is a nice idea!

Now when expanding a symlinked directory the top dotted file is
highlighted differently, you can have info on it as always with M-i and
if you hit C-u C-j to expand a symlinked directory, you will endup in
the true directory (as before).

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
