### ISSUE TITLE
Hard to get the desired character in `insert-char`

### ISSUE THREAD

**Issue by DamienCassou** [emacs-helm/helm#1122]
Hi,

with `helm-mode` enabled, when I type `C-x 8 RET` (`M-x insert-char`) I have a hard time getting the character I want. For example, if I type `downards ar` I don't see the character `DOWNARDS ARROW` in the list (0x2193):

![helm-2](https://cloud.githubusercontent.com/assets/217543/9091549/16a00ca6-3ba1-11e5-80cd-8d4173a7e6cb.png)

Additionally, when I type the full name of the character I want, there is no clue I got it right:

![helm-1](https://cloud.githubusercontent.com/assets/217543/9091548/169f8894-3ba1-11e5-94e1-d6c3d506382d.png)

Only if I press enter at this point will I get the character I want.

**Comment by thierryvolpiatto** [comment]
Damien Cassou <notifications@github.com> writes:

> Hi,
>
> with helm-mode enabled, when I type C-x 8 RET (M-x insert-char) I have
> a hard time getting the character I want. For example, if I type
> downards ar I don't see the character DOWNARDS ARROW in the list
> (0x2193):

This is an helmized command that reuse what emacs completion is
displaying, the character is not shown.
All what can be done here is write a specialized function for
insert-char and add it to helm-completing-read-handlers-alist.

Otherwise, if you have helm-descbinds installed, try `C-x 8 C-h'.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by DamienCassou** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> This is an helmized command that reuse what emacs completion is
> displaying, the character is not shown.


I understand that, thanks. What I don't understand is why I don't see a
line with "DOWNARDS ARROW" written: it's a valid character, it's in the
list when helm is not enabled, and "downwards arr" matches it. Is there
a reason why no line "DOWNWARDS ARROW" appears?

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by michael-heerdegen** [comment]
It appears at line 80 for me.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> It appears at line 80 for me.

Same for me.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
Though, it is another question if the exact match should/could be made
appear first (or be preselected?).  That would be nice to have; dunno if
it would be hard to do.

**Comment by DamienCassou** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Though, it is another question if the exact match should/could be made
> appear first (or be preselected?).  That would be nice to have; dunno if
> it would be hard to do.

yes

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by thierryvolpiatto** [comment]
I have reverted this change as it break of course other helmized functions.
Perhaps you can use `helm-ucs` instead which is better.

Normally exact matches come to top, but here emacs is providing a function that give completion not sorted, it seems it revert its result later (why I don't know).

**Comment by thierryvolpiatto** [comment]
Now exact match should come on top.

**Comment by DamienCassou** [comment]
I confirm, thank you very much
