### ISSUE TITLE
sorting generic completion breaks kill-buffer

### ISSUE THREAD

**Issue by blaazee** [emacs-helm/helm#1123]
Normally when killing a buffer, I quickly type C-x k RET. This no longer works as the highlighted buffer is an emacs buffer beginning with * . As of now, to kill a buffer requires users to select from the menu (almost) always.

I think this is because of the recent commit 0a8235f8311939167f0443341b4d134ee3192447

**Comment by spirani** [comment]
I am having the same issue.

Commenting out the additions made in commit 0a8235f seems to fix the problem.

**Comment by thierryvolpiatto** [comment]
blaazee <notifications@github.com> writes:

> Normally when killing a buffer, I quickly type C-x k RET. This no longer works as the highlighted buffer is an emacs buffer beginning with * . As of now, to kill a
> buffer requires users to select from the menu (almost) always.
>
> I think this is because of the recent commit 0a8235f

Indeed, it was a bad idea, thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
