### ISSUE TITLE
kill-buffer doesn't select the current buffer after upgrading to 20150808.1327

### ISSUE THREAD

**Issue by Jehops** [emacs-helm/helm#1124]
Calling `kill-buffer` shows `Kill buffer (default *current buffer*)` in the minibuffer, but this isn't the buffer highlighted in the `kill-buffer` buffer.  So, `C-x k` `Enter` kills a buffer other than the current buffer.

**Comment by thierryvolpiatto** [comment]
See #1123 which is already fixed.
