### ISSUE TITLE
helm-semantic-or-imenu fails to offer the type of semantic tags in c-mode, but works in c++-mode 

### ISSUE THREAD

**Issue by oracleyue** [emacs-helm/helm#1128]
As the title described, illustrated as follows. 
Could you confirm whether you have such problems? According the demo given by http://tuhdo.github.io/helm-intro.html, helm should not have this bug. Could it be a problem of **semantic-mode**'s configuration? I guess the **semantic** gives two types of tags for c/c++-mode, if these tags ("Variables", "Functions" are not added by **helm**). Any ideas on its configuration? Many thanks!
Problem:
In c-mode, it fails to offer types of tags, like "Dependencies, Variables, Functions, ..."
![screen shot 2015-08-14 at 11 30 23](https://cloud.githubusercontent.com/assets/5046605/9271137/e85e1cd8-4277-11e5-8f42-6fd248e8010c.png)
In c++-mode, it works, as shown below
![screen shot 2015-08-14 at 11 07 59](https://cloud.githubusercontent.com/assets/5046605/9270820/fbe0cb32-4274-11e5-88a6-87e68bef9416.png)

Version:
Emacs 24.4.1
Helm: 20150813 (the newest in elpa)

**Comment by tuhdo** [comment]
You get the original UI by using this code:

```elisp
(with-eval-after-load 'helm-semantic
      (push '(c-mode . semantic-format-tag-summarize) helm-semantic-display-style)
      (push '(c++-mode . semantic-format-tag-summarize) helm-semantic-display-style))
```

It was changed because of this issue : that a user complained `helm-semantic-or-imenu` is too verbose: https://github.com/emacs-helm/helm/issues/1027, while such a verbosity is needed for languages with types like C/C++, imo.

**Comment by oracleyue** [comment]
@tuhdo Thanks a lot! It works well now, both in c-mode and c++-mode. I prefer to have these tags, making things more clear. 

Giving two different types of UI by default for c/c++-mode respectively is slightly strange. (I immediately thought it were a bug, instead of your UI design preference.) If you could keep it for both modes or remove in both, and add the configurations in wiki/doc to show how to bring it back or remove it, that would be perfect for me.

Thanks a lot for your prompt help!!

**Comment by tuhdo** [comment]
Just a note: I didn't write Helm :). That's @thierryvolpiatto.
