### ISSUE TITLE
file name completion and huge directories

### ISSUE THREAD

**Issue by michael-heerdegen** [emacs-helm/helm#1129]
Hello,

this issue applies to helm commands reading file names, e.g. "helm-find-files", as well as helminized file name completion a la "helm-read-file-name".

When completing in a directory with thousands of files, helm gets sluggish, proportionally to the number of files - you have to wait seconds until Emacs unfreezes; for no real gain.

We should define a reasonable upper limit (probably a defcustom) for the number of candidates shown in the Completions buffer.  You'll still get a notable delay, but Emacs would remain usable in such cases.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> When completing in a directory with thousands of files, helm gets
> sluggish, proportionally to the number of files - you have to wait
> seconds until Emacs unfreezes; for no real gain.

I already explained several times that helm-ff use a big number to match
its preselection, so this is the "real gain".
Hopefully, in recents versions of helm there is no more error when the
preselection is not found, so the CNL can be reduced with no risks even
if it is inconvenient if preselection is not matched.

> We should define a reasonable upper limit (probably a defcustom) for
> the number of candidates shown in the Completions buffer. You'll still
> get a notable delay, but Emacs would remain usable in such cases.

default is now 5000 and it is customizable.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
