### ISSUE TITLE
helm-init-candidates-in-buffer and helm-current-buffer

### ISSUE THREAD

**Issue by michael-heerdegen** [emacs-helm/helm#1131]
Hello,

this problem is described best with my use case.

I use a class like this:

```
(defclass my-helm-ediff-this-file-source (helm-source-in-buffer)
  ((init :initform
         (lambda ()
           (helm-init-candidates-in-buffer 'local
                  ...)))))
   ))
```

for ediffing the buffer-file against old versions etc.  "helm-init-candidates-in-buffer" calls "helm-candidate-buffer" to get the caching buffer.  "helm-candidate-buffer" uses the value of "helm-current-buffer" to build a local buffer name.  In my use case, this is bad: since this is all in the init function, "helm-current-buffer" is outdated (at least I guess so.  "helm-current-buffer" has a wrong value at that moment, that's what I checked).  As a result, the 'local cache buffer for the same source, but for a different base buffer is filled with candidates.  So, the bug is, when I run the above source, I sometimes get a wrong candidate list.
TIA.

**Comment by michael-heerdegen** [comment]
BTW, what markup should I use for elisp symbols in text at github?  backquote and quote are misinterpreted, and quoting "like this" seems odd.

**Comment by michael-heerdegen** [comment]
BTW to reproduce the problem, define a class like the above, and use it in different buffers.

**Comment by michael-heerdegen** [comment]
Mmh, no, it's not so easy.  I try to find a recipe that works.

**Comment by michael-heerdegen** [comment]
Shame on me, it was not Helm's fault.

This was my init function:
```
      (init :initform
             (lambda ()
               (helm-init-candidates-in-buffer 'local
                 (if-let ((this-file          (buffer-file-name))
                          (this-file-nondir   (file-name-nondirectory  this-file))
                          (backup-name        (make-backup-file-name-1 this-file))
                          (backup-dir         (file-name-directory    backup-name))
                          (backup-name-prefix (file-name-nondirectory backup-name)))
                     (nconc
                      (if (vc-backend this-file)
                          '("Revision" "Index") '())
                     ...
```

See the "nconc" and the quoted list?  The code was altered every time it was executed!

What remains is that (helm-candidate-buffer 'local) returns a name containing the last current helm buffer, not the current buffer.  I guess this inapt name is used consequently in the session, as this does not seem to do harm.  If you don't want to fix this detail, just close.  Thanks for reading all this...

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Hello,
>
> this problem is described best with my use case.
>
> I use a class like this:
>
> (defclass my-helm-ediff-this-file-source (helm-source-in-buffer)
>   ((init :initform
>          (lambda ()
>            (helm-init-candidates-in-buffer 'local
>                   ...)))))
>    ))
>
> for ediffing the buffer-file against old versions
> etc. "helm-init-candidates-in-buffer" calls "helm-candidate-buffer" to
> get the caching buffer.  "helm-candidate-buffer" uses the value of
> "helm-current-buffer" to build a local buffer name. In my use case,
> this is bad: since this is all in the init function,
> "helm-current-buffer" is outdated (at least I guess
> so. "helm-current-buffer" has a wrong value at that moment, that's
> what I checked). As a result, the 'local cache buffer for the same
> source, but for a different base buffer is filled with candidates. So,
> the bug is, when I run the above source, I sometimes get a wrong
> candidate list.  TIA.

I don't think it is due to this, but more by your init code, anyway if
'local is not what you want, use 'global or just any name as a string.
You can use also :data instead of :init to not bother about this.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> See the "nconc" and the quoted list? The code was altered every time it was executed!

Ah, of course, this is THE error not to do with nconc.

> What remains is that (helm-candidate-buffer 'local) returns a name
> containing the last current helm buffer, not the current buffer. I
> guess this inapt name is used consequently in the session, as this
> does not seem to do harm.

It doesn't harm indeed, it is just a buffer name like any buffer name
you use to store data.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> BTW, what markup should I use for elisp symbols in text at github?
> backquote and quote are misinterpreted, and quoting "like this" seems
> odd.

Quote with two backquote, <backquote>foo<backquote> => `foo`.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Quote with two backquote, <backquote>foo<backquote> => `foo`.

Which is not working when sending by email, but works with the webform.

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> Quote with two backquote, foo => foo.
>
> Which is not working when sending by email, but works with the
> webform.

Ah, ok, thanks!
