### ISSUE TITLE
Helm-locate fuzzy by default.

### ISSUE THREAD

**Issue by smandy** [emacs-helm/helm#1132]
Trying helm-locate with pattern `\.cs' in a c-sharp project gives fuzzy matching even though `helm-locate-fuzzy-match` is nil.

For example the pattern `\.cs` is returning a file named

`build/git/Documentation/docbook-xsl.css`

Any help appreciated.

Running helm-20150802.2312 from melpa.

Regards,

A.

**Comment by thierryvolpiatto** [comment]
Andy Smith <notifications@github.com> writes:

> Trying helm-locate with pattern \.cs' in a c-sharp project gives fuzzy
> matching even though helm-locate-fuzzy-match` is nil.
>
> For example the pattern \.cs is returning a file named
>
> build/git/Documentation/docbook-xsl.css

Which is normal ".cs" is matched in extension of file (".css").

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by smandy** [comment]
Aaargg.. very bad example on my part. Sorry. I think it might be the *highlighting* is matching fuzzily. You're right the selection is matching in non-fuzzy fashion (correctly against the .cs extension), but if the file happens to be a fuzzy match the highlighting will be on the fuzzy match. 

I'd actually snipped off my home directory from the example I sent. The full path is 

```/home/andrew.smith/build/git/Documentation/docbook-xsl.css```

So although it looks like it correctly non-fuzzy matched the filename. The three letters highlighted were ...

1/ The '.' in Andrew.smith
2/ The 'c' in 'Documentation.
3/ The 's' in xsl.

I think because the *highlighting* showed a fuzzy match was the cause of my confusion.

Andy.

**Comment by smandy** [comment]
Sorry... bad edit... the full file that was matched is 

```
/home/andrew.smith/build/git/Documentation/docbook-xsl.css
```

**Comment by thierryvolpiatto** [comment]
Andy Smith <notifications@github.com> writes:

> Aaargg.. very bad example on my part. Sorry. I think it might be the highlighting is matching fuzzily. You're right the selection is matching in non-fuzzy fashion (correctly against the .cs extension), but
> if the file happens to be a fuzzy match the highlighting will be on the fuzzy match.
>
> I'd actually snipped off my home directory from the example I sent. The full path is
>
> So although it looks like it correctly non-fuzzy matched the filename. The three letters highlighted were ...
>
> 1/ The '.' in Andrew.smith
> 2/ The 'c' in 'Documentation.
> 3/ The 's' in xsl.
>
> I think because the *highlighting* showed a fuzzy match was the cause of my confusion.

The highlighting is not exact actually in helm (specially in locate) but
matching (fuzzy and not fuzzy) is working fine.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by smandy** [comment]
Ah okay - thanks for looking. As long as filtering is fine the highlighting isn't really as important.
