### ISSUE TITLE
Request to bring back the support of alists as helm sources

### ISSUE THREAD

**Issue by oracleyue** [emacs-helm/helm#1133]
In recent changes in helm, it removed the support of alists as helm sources, which makes other minor modes based on helm fail to function well. As indicated here  https://github.com/abo-abo/function-args/issues/27.

May I request to bring this function back? If not possible, could you briefly explain why removing this feature? Many thanks!

**Comment by thierryvolpiatto** [comment]
Zuogong Yue <notifications@github.com> writes:

> In recent change in helm, it removes the support of alists as helm
> sources,

No, this have never been removed.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by oracleyue** [comment]
@thierryvolpiatto OK, thanks! I will inform the author to check his/her package.
