### ISSUE TITLE
helm-M-x-fuzzy-match does not sort categories by matched results

### ISSUE THREAD

**Issue by 4DA** [emacs-helm/helm#1135]
Helm with helm-M-x-fuzzy-match enabled (setq helm-M-x-fuzzy-match t)
weirdly suggests commands from emacs command history first even though there are obviously much more suitable (fully matched) choices available.

![pic](http://dump.bitcheese.net/images/usidanu/helm.png)

Not sure whether this is a bug or feature, but certainly it doesn't DWIM.

**Comment by thierryvolpiatto** [comment]
Dmitry Cherkassov <notifications@github.com> writes:

> Helm with helm-M-x-fuzzy-match enabled (setq helm-M-x-fuzzy-match t)
> weirdly suggests commands from emacs command history first even though
> there are obviously much more suitable (fully matched) choices
> available.

You have just to switch to next source.
There is no bug here.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by 4DA** [comment]
can i make "emacs commands" source more preferrable than "emacs commands
history" ?

On Fri, Aug 21, 2015 at 1:03 PM, Thierry Volpiatto <notifications@github.com
> wrote:

>
> Dmitry Cherkassov <notifications@github.com> writes:
>
> > Helm with helm-M-x-fuzzy-match enabled (setq helm-M-x-fuzzy-match t)
> > weirdly suggests commands from emacs command history first even though
> > there are obviously much more suitable (fully matched) choices
> > available.
>
> You have just to switch to next source.
> There is no bug here.
>
> --
> Thierry
> Get my Gnupg key:
> gpg --keyserver pgp.mit.edu --recv-keys 59F29997
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/emacs-helm/helm/issues/1135#issuecomment-133361972>.
>



-- 
With best regards,
Dmitry

**Comment by thierryvolpiatto** [comment]
Dmitry Cherkassov <notifications@github.com> writes:

> can i make "emacs commands" source more preferrable than "emacs commands
> history" ?

You can customize helm-M-x-reverse-history.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by PythonNut** [comment]
@4DA This is probably a duplicate of #837.
