### ISSUE TITLE
Add ability to toggle line truncation in helm buffer

### ISSUE THREAD

**Issue by dakrone** [emacs-helm/helm#1136]
You can configure helm to truncate (or not truncate) lines in the helm buffer, however, this is a semi-static configuration.

It would be great to be able to toggle this from within helm itself, so I could see the full filename for something like:

![screenshot_2015-08-21_16-32-06](https://cloud.githubusercontent.com/assets/19060/9420394/626fe98e-4822-11e5-8886-69188be1bfc8.png)

**Comment by thierryvolpiatto** [comment]
Something like this ?

```elisp
(defun helm-buffers-toggle-truncate-line ()
  (interactive)
  (with-helm-alive-p
    (with-helm-buffer
      (let ((preselect (helm-buffers--quote-truncated-buffer
			(helm-get-selection))))
	(setq truncate-lines (not truncate-lines))
        (helm-force-update preselect)))))

(define-key helm-buffer-map (kbd "C-c >") 'helm-buffers-toggle-truncate-line)
```

**Comment by thierryvolpiatto** [comment]
You can use now `C-c >` everywhere, not only in buffers.
Note that in async sources, candidates are recomputed and selection comes back on top.

**Comment by dakrone** [comment]
This works great, thanks @thierryvolpiatto!

**Comment by azzamsa** [comment]
@thierryvolpiatto how to make it activated by default? I have to do `c-c >` every time I call helm-mini even if I've set `(setq helm-buffers-truncate-lines t)`

**Comment by thierryvolpiatto** [comment]
azzamsa <notifications@github.com> writes:

> @thierryvolpiatto how to make it activated by default? I have to do
> c-c > every time I call helm-mini even if I've set (setq
> helm-buffers-truncate-lines t)

That's weird, I can't reproduce, I use the default for
helm-buffers-truncate-lines which is `t`.


-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by azzamsa** [comment]
I have reported this behavior here https://github.com/emacs-helm/helm/issues/2172
