### ISSUE TITLE
helm-ucs is slow 

### ISSUE THREAD

**Issue by robbyoconnor** [emacs-helm/helm#1137]
`helm-ucs` is slow when compared to [helm-unicode][] -- this is not a good thing. I am using **24.4.1**.  It's not at all performant -- I noticed this when testing for https://github.com/syl20bnr/spacemacs/pull/2728 -- and it was really, really slow, whereas [helm-unicode][] was near instantaneous. 

[helm-unicode]: https://github.com/shosti/helm-unicode

**Comment by thierryvolpiatto** [comment]
Should be fixed now.

**Comment by robbyoconnor** [comment]
:+1: thank you!

**Comment by OrionRandD** [comment]
I am getting this error 
collecting ucs names...99% 
sort: Symbol’s function definition is void: helm-generic-sort-fn [2 times]
Quit
sort: Symbol’s function definition is void: helm-generic-sort-fn

when calling 
helm-ucs

**Comment by thierryvolpiatto** [comment]
OrionRandD ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
> I am getting this error
> collecting ucs names...99%
> sort: Symbol’s function definition is void: helm-generic-sort-fn [2 times]
> Quit
> sort: Symbol’s function definition is void: helm-generic-sort-fn

This is not reproductible, double check your installation following the
instructions and if it persists open a new bug report starting from
emacs-helm.sh.

Thanks.

-- 
Thierry
