### ISSUE TITLE
helm-header changes in some themes clash with custom-theme-set-faces header-line

### ISSUE THREAD

**Issue by issue-dispenser** [emacs-helm/helm#1139]
I'm new to Emacs so I'm not entirely sure that it's Helm or Emacs that causes this (sorry), but here goes:

Certain themes (namely [Zenburn](https://github.com/bbatsov/zenburn-emacs) and [Jazz](https://github.com/donderom/jazz-theme)) that have a different header-line (specified in custom-set-faces) and helm-header produce an inconsistency as shown below at the top right:

![helm-header](https://cloud.githubusercontent.com/assets/13922417/9458624/97e1a70a-4aad-11e5-8034-04c542229386.png)

In both themes, the default header-line was defined in custom-theme-set-faces as follows:
```Emacs-Lisp
`(header-line ((t (:foreground ,zenburn-yellow
                                  :background ,zenburn-bg-1
                                  :box (:line-width -1 :style released-button)))))
```
and the helm-header:
```Emacs-Lisp
`(helm-header
     ((t (:foreground ,zenburn-green
                      :background ,zenburn-bg
                      :underline nil
                      :box nil))))
```
The box and background colour on the default header-line somehow aren't getting completely overwritten by the helm-header. Is this helm-header's fault, or am I looking in the wrong place?

This was reproduced starting from `./emacs-helm.sh` and then loading either theme.

**Comment by thierryvolpiatto** [comment]
issue-dispenser <notifications@github.com> writes:

> `(helm-header
>      ((t (:foreground ,zenburn-green
>                       :background ,zenburn-bg
>                       :underline nil
>                       :box nil))))
>
> The box and background colour on the default header-line somehow
> aren't getting completely overwritten by the helm-header.

helm is inheriting from `header-line', the definition above is
redefining some attributes but not `inherit', IMO it should.
(unchecking inherit in custom interface should fix your problem).

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by issue-dispenser** [comment]
Using M-x customize helm-header already has an unchecked `inherit'.

Inserting an :inherit nil in the definition also didn't seem to do anything.
I'm sorry if I misunderstood you.

**Comment by thierryvolpiatto** [comment]
issue-dispenser <notifications@github.com> writes:

> Using M-x customize helm-header already has an unchecked `inherit'.
>
> Inserting an :inherit nil in the definition also didn't seem to do anything.
> I'm sorry if I misunderstood you.

So I don't know, anyway there is nothing to do on the helm side,
probably report this to the theme maintainer.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by issue-dispenser** [comment]
Alright, I'll do that. Thanks for checking.

**Comment by michael-heerdegen** [comment]
@thierryvolpiatto I guess the OP meant the short end part in the header line visible above the fringe and scroll bar of the window.  That has nothing to do with themes or inheritance at all.  This happens because in `helm-display-mode-line` when `helm-echo-input-in-header-line` is nil  and `helm-display-header-line` we set `header-line-format`to a string that is too short (the header-line is longer than the `window-width`, we need to add one more space character or so).

**Comment by issue-dispenser** [comment]
Yes, that's what I meant, thanks.

That is also indeed where the issue seems to be, as I added 4 to the make-string call of hlend and the problem went away.

**Comment by issue-dispenser** [comment]
Sadly it's still a bit off. Normally it now cuts off about halfway through the scrollbar (so it's about half the size now). Though in helm find/locate it starts off as the same size as before.

Changing the 2 to a 4 fixes it on my end, but helm find/locate still display that hanging bit apparently because they don't actually write a message in the header until results appear.

**Comment by issue-dispenser** [comment]
Thanks, this fixes the issue outside of the aforementioned helm find/locate when there are no search results. Is there a way to display the source header at the start of these functions instead of just when there's just search results?

If not, then it's not much of an issue at this point. It looks fine most of the time now.

**Comment by thierryvolpiatto** [comment]
issue-dispenser <notifications@github.com> writes:

> Thanks, this fixes the issue outside of the aforementioned helm
> find/locate when there are no search results. Is there a way to
> display the source header at the start of these functions instead of
> just when there's just search results?

No.

> If not, then it's not much of an issue at this point. It looks fine most of the time now.

Great.

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
