### ISSUE TITLE
helm-apropos should show key bindings for commands like helm-M-x

### ISSUE THREAD

**Issue by hmelman** [emacs-helm/helm#1140]
helm-apropos shows emacs commands but I think it should include key-bindings for those commands that have one like helm-M-x does. See http://emacs.stackexchange.com/questions/15051/can-helm-apropos-display-the-key-bindings-for-commands-the-way-helm-m-x-does

The solution presented is to change helm-def-source--emacs-commands to include
:candidate-transformer 'helm-M-x-transformer-1
which seems like something reasonable to be built in or at least enabled via a user option.

**Comment by thierryvolpiatto** [comment]
Howard Melman <notifications@github.com> writes:

> helm-apropos shows emacs commands but I think it should include
> key-bindings for those commands that have one like helm-M-x does.

This have not been added for two reasons, one is that when you need such
info you generally run helm-M-x first, the second is that would alter
performances of helm-apropos which is displaying much more than emacs
commands, so this will not be added.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by hmelman** [comment]
Fair enough, though the performance hit on my machine seems negligible.  For someone like me is there a cleaner way to enable this other than to redefine helm-def-source--emacs-commands? As I said, a user option to enable this (defaulted to off for performance reasons) would be fine, and would be much more discoverable a solution.

**Comment by Ambrevar** [comment]
Quick update: this does not seem to work anymore.  It broke around summer 2017 if that can help bisecting.
Any clue why?

For the record, here is the "hack":
```
(defun helm-def-source--emacs-commands (&optional default)
  (helm-build-in-buffer-source "Commands"
    :init `(lambda ()
             (helm-apropos-init 'commandp ,default))
    :fuzzy-match helm-apropos-fuzzy-match
    :filtered-candidate-transformer (and (null helm-apropos-fuzzy-match)
                                         'helm-apropos-default-sort-fn)
    :candidate-transformer 'helm-M-x-transformer-1
    :nomark t
    :action '(("Describe Function" . helm-describe-function)
              ("Find Function" . helm-find-function)
              ("Info lookup" . helm-info-lookup-symbol))))
```

@thierryvolpiatto: Do you still refrain from making this the default?
My rationale:

- Performance impact seems negligible.  `apropos` is quite slow itself considering the huge load of data it mangles, so here it might amount to saying adding a feather on an elephant will make it heavier.

- The whole point of `apropos` is to discover emacs features you don't know yet, and in particular whose _type_ you don't know yet.  Whether they are variables, functions, faces and... why not keybinding?

- If the user knows s/he is looking for a command with bindings, s/he might just invoke `helm-M-x`.  Fair enough, but what if she does not know what she is looking for?  See my previous point.

**Comment by piyo** [comment]
I am also interested in this functionality.

On helm-20210920.520, I implemented it using advice. Note the ```(require 'helm-command)``` since ```helm-M-x-transform-1``` is not an autoloaded function.

``` emacs-lisp
(use-package helm-elisp
  :config
  (defun helm-def-source--emacs-commands-show-keybind (oldfun-retval)
    ""
    (let* ((src oldfun-retval))
      (require 'helm-command)
      (helm-set-attr 'candidate-transformer #'helm-M-x-transformer-1 src)
      src))
  (advice-add 'helm-def-source--emacs-commands
              :filter-return 'helm-def-source--emacs-commands-show-keybind)
  )
```

I also agree that performance impact seems negligible for me.

**Comment by thierryvolpiatto** [comment]
piyo ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
> @thierryvolpiatto
> Unfortunately 0dafe79 is broken because the last parameter of the
> append is not a list.

Thanks, fixed.



-- 
Thierry
