### ISSUE TITLE
helm-documentation cleanup and key binding

### ISSUE THREAD

**Issue by hmelman** [emacs-helm/helm#1141]
I've been using helm for a few weeks now and only just discovered helm-documentation. It seems quite useful and more helpful for trying to learn all of helm than just using C-h m.

1. I think it should have its own key binding, perhaps `helm-command-prefix-key ?'
2. The helm buffer of the outline is a bit wide. In the org buffer I shortened the two star headings for tips and specific commands to just "Tips" and "Commands" and I feel it helped a lot. The outline structure provided context so it wasn't confusing between sections.
3. There were a few places where the org buffer had double blank lines. Collapsing these to single blank lines made the helm-doc.org buffer much cleaner IMHO when showing just the outline with org-shifttab.

**Comment by thierryvolpiatto** [comment]
Howard Melman <notifications@github.com> writes:

> I've been using helm for a few weeks now and only just discovered
> helm-documentation. It seems quite useful and more helpful for trying
> to learn all of helm than just using C-h m.


>  1. I think it should have its own key binding, perhaps
>  `helm-command-prefix-key ?'

Ok, needs also an entry in menu.

>  2. The helm buffer of the outline is a bit wide. In the org buffer I
>     shortened the two star headings for tips and specific commands to
>     just "Tips" and "Commands" and I feel it helped a lot. The outline
>     structure provided context so it wasn't confusing between
>     sections.

Agreed.

>  3. There were a few places where the org buffer had double blank
>     lines. Collapsing these to single blank lines made the
>     helm-doc.org buffer much cleaner IMHO when showing just the
>     outline with org-shifttab.

Instead of modifying in helm-doc.org generated by helm-documentation,
could you remove these newlines in the helm helm strings located in
helm-help.el ?
To see the result of your changes once evaled the strings (C-M x) rerun
helm-documentation with a prefix arg to regenerate helm-doc.org.
Once you are happy with your changes, perhaps you can send a PR, would
be great (same for 1 and 2), don't hesitate to ask for help on this.

Thanks for your feedback.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by hmelman** [comment]
Thanks. I'll do the cleanup of the doc strings in helm-help and submit a PR. I'm learning git and github so this seems like an easy first experiment. :)

**Comment by thierryvolpiatto** [comment]
Howard Melman <notifications@github.com> writes:

> Thanks. I'll do the cleanup of the doc strings in helm-help and submit
> a PR. I'm learning git and github so this seems like an easy first
> experiment. :)

Be sure also that after modifying the help strings the documentation is
displayed clearly in C-h m in all sources.
i.e removing newlines in some places may be nice in the org file
generated by helm-documentation, but may not be so nice in the outline
buffers displayed with C-h m.

Thanks.

-- 
Thierry

https://emacs-helm.github.io/helm/

**Comment by thierryvolpiatto** [comment]
Ok I think I can close this now.
Thanks for the great work.
