### ISSUE TITLE
Add ability to capture helm results to perform a different helm selection on

### ISSUE THREAD

**Issue by dakrone** [emacs-helm/helm#1142]
Here's a real-life example I would love to be able to do, first, I hit `C-c p s s` to do `helm-ag` for my project:

![screenshot_2015-08-27_15-11-18](https://cloud.githubusercontent.com/assets/19060/9533240/e4597230-4ccd-11e5-950a-3b6af5e95da9.png)

Next, I'd really like to be able to hit `*something*` to capture those 108 candidates so I can further narrow by other helm metadata, in this case, the filename that matches the query. For example, searching for all TODOs in files that have "Role" in the name of the file. Or searching for all TODOs that occur on line 211 in files.

Unfortunately, the only way I know to do this now is to pop open an eshell buffer and do `ag "TODO" **/*MyFilePattern*`

**Comment by thierryvolpiatto** [comment]
Lee Hinman <notifications@github.com> writes:

> Here's a real-life example I would love to be able to do, first, I hit
> C-c p s s to do helm-ag for my project:
>
> screensh
>
> Next, I'd really like to be able to hit *something* to capture those
> 108 candidates so I can further narrow by other helm metadata, in this
> case, the filename that matches the query. For example, searching for
> all TODOs in files that have "Role" in the name of the file. Or
> searching for all TODOs that occur on line 211 in files.
>
> Unfortunately, the only way I know to do this now is to pop open an
> eshell buffer and do ag "TODO" **/*MyFilePattern*

If you use a backend supported by helm (grep, ack-grep or git-grep) you
can just do C-x C-s to save results, unfortunately helm-ag is not part
of helm.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Lee Hinman <notifications@github.com> writes:

> Here's a real-life example I would love to be able to do, first, I hit
> C-c p s s to do helm-ag for my project:
>
> screensh
>
> Next, I'd really like to be able to hit *something* to capture those
> 108 candidates so I can further narrow by other helm metadata, in this
> case, the filename that matches the query. For example, searching for
> all TODOs in files that have "Role" in the name of the file. Or
> searching for all TODOs that occur on line 211 in files.
>
> Unfortunately, the only way I know to do this now is to pop open an
> eshell buffer and do ag "TODO" **/*MyFilePattern*

I have provided a new helm-grep-ag that support saving, editing,
reverting etc... like current helm grep.
You can run it from helm-find-files as always to run on a different
directory than current, otherwise, from current-buffer a command is
provided to directly run on default-directory => helm-do-grep-ag.

It is new, so you may have bugs or diverses inconveniences.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by dakrone** [comment]
I tested the `C-x C-s` output for the output and it works great! I'll check out the `helm-grep-ag` also, thanks for adding it!

I'm closing this since there's a valid way around it, thanks again, helm is super useful!
