### ISSUE TITLE
Pass parameters for the source helm-locate

### ISSUE THREAD

**Issue by ReneFroger** [emacs-helm/helm#1143]
## Setup:
GUI version GNU Emacs 25.0.50.1 (x86_64-w64-mingw32) of 2015-07-25 on KAEL
[Compiled from EmacsW64.](http://emacsbinw64.sourceforge.net/)

Helm, using the latest version of Helm from MELPA

Windows 7 x64 bit.

Locate Windows binary, http://locate32.cogit.net/

## Situation:
I have locate in my PATH installed. I noticed I couldn't set any settings for the locate source. 
For example, when I evaluate the setting

    (setq helm-locate-command "locate -ld %s")

I noticed the source `helm-locate`  will fuzzy filtering filenames. Or with the setting

    (setq helm-locate-command "locate -n 15 %s")

I still get more than thousands results for the source `helm-locate`.
So I suspect I'm doing something wrong. When looking up another variables for the `helm-locate` with <kbd>C-h v</kbd>, I found not another relevant command.

Any suggestion?

**Comment by thierryvolpiatto** [comment]
ReneFroger <notifications@github.com> writes:

> (setq helm-locate-command "locate -ld %s")

See docstring, you need two format specs.

> I noticed the source helm-locate will fuzzy filtering filenames.

No unless you enable it.

> Or with the setting
>
> (setq helm-locate-command "locate -n 15 %s")
>
> I still get more than thousands results for the source helm-locate.

Don't know why you have results with this, it is wrong too.

> Any suggestion?

Read docstring of helm-locate-command.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by ReneFroger** [comment]
I already have read the docstring of `helm-locate-command`. So that's why I opened this issue. 

For example, I use Windows, so Helm is by default set to use `es` command:

  (setq helm-locate-command 'nil)

 By default, he should use the es source since it's a Windows platform. I get the message that the `es` is not recognized, which is logical, becuase I don't have Everything/ES source installed anymore. 

But I configured it to use the Locate binary for Windows. 

For example, the docstring gives the following parameters for loacte

    Gnu/linux: "locate %s -e -A %s"
    berkeley-unix: "locate %s %s"
    windows-nt: "es %s %s"
    Others: "locate %s %s"

So I tried it out:

  (setq helm-locate-command "locate %s -ld %s")

or 

  (setq helm-locate-command "locate %s -e -A -ld %s")

When typing "modules", it gives me weird results in both cases:

![untitled](https://cloud.githubusercontent.com/assets/5211845/9563386/7ce5aa5e-4e82-11e5-9a7c-6690935009bb.png)

 Maybe something went wrong while parsing. When I try it with (setq helm-locate-command "locate %s"), even it's not mentioned in the docstring, I get less weird results, but it gives me also unusable results: 

![untitled](https://cloud.githubusercontent.com/assets/5211845/9563433/86fc2de6-4e83-11e5-8ade-b82ea4588deb.png)

In the command prompt, I get normal results anyway: 

![untitled](https://cloud.githubusercontent.com/assets/5211845/9563468/de5c48c2-4e84-11e5-977f-1837e924387d.png)

So that's why I opened this issue, to figure out what the parameters should be. The difficulty is that I use Locate, because the `es` source for Windows lets Helm crash too many times. But it seems I can't figure out what the proper command is for locate. If it might help, these are the parameters for the Locate binary: 

![test22](https://cloud.githubusercontent.com/assets/5211845/9563485/89f6419c-4e85-11e5-8223-c14c662bc22b.png)

**Comment by thierryvolpiatto** [comment]
ReneFroger <notifications@github.com> writes:

> So that's why I opened this issue, to figure out what the parameters
> should be. The difficulty is that I use Locate, because the es source
> for Windows lets Helm crash too many times.

Seems you are the only one with this problem.

> But it seems I can't figure out what the proper command is for
> locate. If it might help, these are the parameters for the Locate
> binary:

There is many locate versions for Windoze, I don't know this one and its
arguments.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
ReneFroger <notifications@github.com> writes:

> Setup:
>
> GUI version GNU Emacs 25.0.50.1 (x86_64-w64-mingw32) of 2015-07-25 on KAEL
> Compiled from EmacsW64.
>
> Helm, using the latest version of Helm from MELPA
>
> Windows 7 x64 bit.
>
> Locate Windows binary, http://locate32.cogit.net/

The GNU locate for windows is located here:

https://www.gnu.org/software/findutils/findutils.html

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by ReneFroger** [comment]
I tried it, and searched around the site and the web, but there seems no locate binaries available for Windows on the [link](https://www.gnu.org/software/findutils/findutils.html) that you provided. 

On the web I found  the Locate32 that I linked earlier. So could you explain what you mean with that there are many locate versions for Windows? 

And I know, Windows might not be a good system, but due to work- and environment requirements, I'm bound to Windows unfortunately.

**Comment by thierryvolpiatto** [comment]
ReneFroger <notifications@github.com> writes:

> I tried it, and searched around the site and the web, but there seems
> no locate binaries available for Windows on the link that you
> provided.

 The tools supplied with this package are:

    find - search for files in a directory hierarchy
    locate - list files in databases that match a pattern
    updatedb - update a file name database
    xargs - build and execute command lines from standard input 

Please help yourself and use google to search, here are the binaries:

http://gnuwin32.sourceforge.net/packages/findutils.htm

I don't say this is better than something else, I didn't try as I am not
using Windows.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
ReneFroger <notifications@github.com> writes:

> I tried it, and searched around the site and the web, but there seems
> no locate binaries available for Windows on the link that you
> provided.

http://en.lmgtfy.com/?q=findutils+binaries+for+windows

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by ReneFroger** [comment]
I googled for `locale binaries windows`, and there were no relevant results for GNU locale. 
Not on findutils binaries. 

But I noticed something else. The Locale-source for helm starts with searching after a space. For example, there is a file, called `foo.txt`. But `helm-locale`  will not search for `foo`, until you put a space afterwards. Is that correct behaviour?

**Comment by thierryvolpiatto** [comment]
No of course.

**Comment by ReneFroger** [comment]
Thanks for your reply. I tried it again with empty configuration without another plugins (except Helm and Projectile), to no avail. But that's currently out of the scope of this issue. 

I get Locate working with Helm, but only after I put a space afterwards. I can live with that restriction. Your help is appreciated.

**Comment by acml** [comment]
I'm observing the same incorrect behaviour. helm-locate searches only after a space character or if i enter more than a word.

GNU Emacs 24.5.1 (x86_64-w64-mingw32)

Everything Search Engine http://www.voidtools.com/
