### ISSUE TITLE
helm-find-library does not discover libraries in .emacs.d

### ISSUE THREAD

**Issue by Wilfred** [emacs-helm/helm#1144]
I have `"~/.emacs.d/user-lisp"` on my `load-path`. I've noticed that `find-library` includes libraries from that directory, but the helm equivalent command does not.

**Comment by thierryvolpiatto** [comment]
Wilfred Hughes <notifications@github.com> writes:

> I have "~/.emacs.d/user-lisp" on my load-path. I've noticed that
> find-library includes libraries from that directory, but the helm
> equivalent command does not.

Hmm, can't reproduce, if I create "~/.emacs.d/user-lisp" directory and
add "foo.el" file inside, then add "~/.emacs.d/user-lisp" to load-path,
find-library is finding "foo".
I have also lisp files in "~/.emacs.d/emacs-config" directory and they
are all detected.

Perhaps try from emacs-helm.sh ?

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by Wilfred** [comment]
Thanks for investigating. I think this just an issue with my configuration, so I'm going to close this. I'll reopen if I encounter this using vanilla helm (unlikely).

**Comment by michael-heerdegen** [comment]
A strange issue, I can't image what a configuration could case this problem.

I wonder whether you can find your stuff in the return value of `helm-locate-library-scan-list`.

And of course note that `helm-find-library` shows only the first `helm-candidate-number-limit` matches, so you may need to enter a reasonable input to make your stuff appear.
