### ISSUE TITLE
user-error: Can't find the ... manpage

### ISSUE THREAD

**Issue by emelin** [emacs-helm/helm#1145]
Hi,
cannot guess what's wrong here:

If I invoke 

    M-x helm-man-woman

I can choose a man page, it seems be found and processed but finally is not displayed but saying, e.g.:

    Invoking man -l /usr/share/man/man1/emacs.1 in the background
    Please wait: formatting the -l /usr/share/man/man1/emacs.1 man page...
    /usr/share/man/man1/emacs.1 man page formatted
    user-error: Can't find the /usr/share/man/man1/emacs.1 manpage

If I choose the same manpage using either
    
    M-x man
or

    M-x woman

while starting emacs with -q, the manpage gets rendered and displayed perfectly.

Would be great, if this could be traced down. 
emelin

Btw: I followed the recommendation on the helm-webpage by adding this to my .emacs:

    (add-to-list 'helm-sources-using-default-as-input 'helm-source-man-pages)

**Comment by thierryvolpiatto** [comment]
emelin <notifications@github.com> writes:

> Hi,
> cannot guess what's wrong here:
>
> If I invoke
>
> M-x helm-man-woman
>
> I can choose a man page, it seems be found and processed but finally is not displayed but saying, e.g.:
>
> Invoking man -l /usr/share/man/man1/emacs.1 in the background
> Please wait: formatting the -l /usr/share/man/man1/emacs.1 man page...
> /usr/share/man/man1/emacs.1 man page formatted
> user-error: Can't find the /usr/share/man/man1/emacs.1 manpage
>
> If I choose the same manpage using either
>
> M-x man
>
> or
>
> M-x woman
>
> while starting emacs with -q, the manpage gets rendered and displayed perfectly.
>
> Would be great, if this could be traced down.

Can't reproduce here.
Please try from emacs-helm.sh.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by xuchunyang** [comment]
Guess you are on OS X, try `(setq helm-man-format-switches "%s")` and read the docstring of if.

**Comment by emelin** [comment]
Your are absolutely right. So simple and solved!

Thank you so much, for pointing me there!

(Maybe it's worth hinting to that OS X specifics somewhere more prominently.)
