### ISSUE TITLE
`helm-grep-mode-hook` is not triggered.

### ISSUE THREAD

**Issue by vspinu** [emacs-helm/helm#1151]
I cannot make `wgrep-helm` work with most recent helm and emacs 25.  

The issues seems to be that `helm-grep-mode` is not triggered anymore: No effect from:

```
(add-hook 'helm-grep-mode-hook (lambda () (message "here")) )
```

**Comment by thierryvolpiatto** [comment]
Vitalie Spinu <notifications@github.com> writes:

> I cannot make wgrep-helm work with most recent helm and emacs 25.

It is perfectly working here, what are you trying to do ?
This need zero config, it works out of the box.

-- 
Thierry

https://emacs-helm.github.io/helm/

**Comment by vspinu** [comment]
I expect it to work as in normal grep buffers with the same shortcuts (C-c C-e, C-c C-p etc). Or how is it supposed to work with  helm?

**Comment by xuchunyang** [comment]
> I expect it to work as in normal grep buffers with the same shortcuts (C-c C-e, C-c C-p etc)

It is.  The only setup of `wgrep-helm` is `(require 'wgrep-helm)` (you need to run it explicitly in your init.el, since it is not a clean package).

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

>     I expect it to work as in normal grep buffers with the same shortcuts (C-c C-e, C-c C-p etc)
>    
> It is. The only setup of wgrep-helm is (require 'wgrep-helm) (you need
> to run it explicitly in your init.el, since it is not a clean
> package).

It is soft required in helm-grep.el, so he should have nothing to do.

-- 
Thierry

https://emacs-helm.github.io/helm/

**Comment by xuchunyang** [comment]
> It is soft required in helm-grep.el, so he should have nothing to do.

You are right.

**Comment by vspinu** [comment]
> The only setup of wgrep-helm is (require 'wgrep-helm)

`helm-grep.el` (v. 20150904.534) already does that. I am looking at the code of wgrep-helm (v. 20140528.1427) and it does `(add-hook 'helm-grep-mode-hook 'wgrep-helm-setup)`. There is no way this could work with the current helm as that hook is never run.

**Comment by thierryvolpiatto** [comment]
Vitalie Spinu <notifications@github.com> writes:

>     The only setup of wgrep-helm is (require 'wgrep-helm)
>    
> helm-grep.el (v. 20150904.534) already does that. I am looking at the
> code of wgrep-helm (v. 20140528.1427) and it does (add-hook
> 'helm-grep-mode-hook 'wgrep-helm-setup). There is no way this could
> work with the current helm as that hook is never run.

Really I still don't know where you want to go.

wgrep is working fine in all versions of grep and also in occur/moccur,
so what is the problem ?

Check your installation if something is not working, there is no problem
with this package.

-- 
Thierry

https://emacs-helm.github.io/helm/

**Comment by vspinu** [comment]
> Check your installation if something is not working, there is no problem with this package.

I have done this already in 2 ways. Re-installed from scratch all helm related packages from MELPA and installed from helm/wgrep from source and run ./emacs-helm.sh. It's not my problem. 

  > Really I still don't know where you want to go. 

If a package loads in helm-grep hook and the hook i not run, then the package is not activated? It's really basic isn't it. 

Here is what I do step by step:

 1) clone helm git
  2) make with emacs 25
  3) ./emacs-helm.sh
  4) eval the sources of wgrep.el and wgrep-helm.el
  5) invoke helm-do-grep in that diretory
  6) start typing till some candidates appear
  7) Invoke C-c C-p (wgrep-toggle-readonly-area)

No effect. The wgrep functionality is just not loaded within helm.

**Comment by thierryvolpiatto** [comment]
Vitalie Spinu <notifications@github.com> writes:

> Here is what I do step by step:
>
> 1) clone helm git
> 2) make with emacs 25
> 3) ./emacs-helm.sh
> 4) eval the sources of wgrep.el and wgrep-helm.el
> 5) invoke helm-do-grep in that diretory
> 6) start typing till some candidates appear
> 7) Invoke C-c C-p (wgrep-toggle-readonly-area)

Don't you forget a step between 6) and 7) :-)

-- 
Thierry

https://emacs-helm.github.io/helm/

**Comment by vspinu** [comment]
>> On Sat, Sep 05 2015 03:57, Thierry Volpiatto wrote:

> Vitalie Spinu <notifications@github.com> writes:
>> 5) invoke helm-do-grep in that diretory
>> 6) start typing till some candidates appear
>> 7) Invoke C-c C-p (wgrep-toggle-readonly-area)

> Don't you forget a step between 6) and 7) :-)

What do you mean? There is no step between 6 and 7 with normal grep/igrep
buffers.  C-c C-p to toggle wgrep and start editing then C-c C-c to commit the
edit.

**Comment by vspinu** [comment]
> Don't you forget a step between 6) and 7) :-)

There is a directory selection step between 5 and 6 which I omitted as self obvious.

**Comment by thierryvolpiatto** [comment]
Vitalie Spinu <notifications@github.com> writes:

>     Don't you forget a step between 6) and 7) :-)
>    
> There is a directory selection step between 5 and 6 which I omitted as self obvious.

No between 6) and 7) you forget C-x C-s ...

-- 
Thierry

https://emacs-helm.github.io/helm/

**Comment by thierryvolpiatto** [comment]
Vitalie Spinu <notifications@github.com> writes:

>>> On Sat, Sep 05 2015 03:57, Thierry Volpiatto wrote:
>
>> Vitalie Spinu <notifications@github.com> writes:
>>> 5) invoke helm-do-grep in that diretory
>>> 6) start typing till some candidates appear
>>> 7) Invoke C-c C-p (wgrep-toggle-readonly-area)
>
>> Don't you forget a step between 6) and 7) :-)
>
> What do you mean? There is no step between 6 and 7 with normal grep/igrep
> buffers. C-c C-p to toggle wgrep and start editing then C-c C-c to commit the
> edit.

NO, this is why you asked for the hook, you never reached
helm-grep-mode.

-- 
Thierry

https://emacs-helm.github.io/helm/

**Comment by thierryvolpiatto** [comment]
https://github.com/emacs-helm/helm/wiki#save-grep-session

-- 
Thierry

https://emacs-helm.github.io/helm/

**Comment by thierryvolpiatto** [comment]
The problem was OP was not running `C-x C-s` and BTW never reach `helm-grep-mode`.
I have added a line about emacs-wgrep in the doc.
Closing now.

**Comment by vspinu** [comment]
>> On Sat, Sep 05 2015 09:18, Thierry Volpiatto wrote:

> No between 6) and 7) you forget C-x C-s ...

Hm. That was tricky. I guess it's high time to go through that wiki head to
tail. Thank you!
