### ISSUE TITLE
Helm integration with Eshell doesn't work

### ISSUE THREAD

**Issue by rgtk** [emacs-helm/helm#1153]
Helm completion for Eshell using `helm-eshell.el` doesn't work.

After putting code below inside init I still get standard \**Completions*\* buffer.

    (require 'helm-eshell)

    (add-hook 'eshell-mode-hook
            #'(lambda ()
                (define-key eshell-mode-map [remap pcomplete] 'helm-esh-pcomplete)))

**Comment by thierryvolpiatto** [comment]
Ralph Gutkowski <notifications@github.com> writes:

> Helm completion for Eshell using helm-eshell.el doesn't work.
>
> After putting code below inside init I still get standard *Completions* buffer.
>
> (require 'helm-eshell)

Please install helm as recommended in readme.

> (add-hook 'eshell-mode-hook
>         #'(lambda ()
>             (define-key eshell-mode-map [remap pcomplete] 'helm-esh-pcomplete)))

Depend the emacs version you use, older emacs version have TAB bound to
eshell-pcomplete and others to pcomplete.

It is working fine here.

-- 
Thierry

https://emacs-helm.github.io/helm/
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
For info here my config for eshell:

```elisp
;; Eshell-prompt
(setq eshell-prompt-function
      #'(lambda nil
          (concat
           (getenv "USER")
           "@"
           (system-name)
           ":"
           (abbreviate-file-name (eshell/pwd))
           (if (= (user-uid) 0) " # " " $ "))))

;; Compatibility 24.2/24.3
(unless (fboundp 'eshell-pcomplete)
  (defalias 'eshell-pcomplete 'pcomplete))
(unless (fboundp 'eshell-complete-lisp-symbol)
  (defalias 'eshell-complete-lisp-symbol 'lisp-complete-symbol))

(add-hook 'eshell-mode-hook #'(lambda ()
                                (setq eshell-pwd-convert-function (lambda (f)
                                                                    (if (file-equal-p (file-truename f) "/")
                                                                        "/" f)))
                                ;; Helm completion with pcomplete
                                (setq eshell-cmpl-ignore-case t)
                                (eshell-cmpl-initialize)
                                (define-key eshell-mode-map [remap eshell-pcomplete] 'helm-esh-pcomplete)
                                ;; Helm lisp completion
                                (define-key eshell-mode-map [remap eshell-complete-lisp-symbol] 'helm-lisp-completion-at-point)
                                ;; Helm completion on eshell history.
                                (define-key eshell-mode-map (kbd "M-p") 'helm-eshell-history)
                                ;; Eshell prompt
                                (set-face-attribute 'eshell-prompt nil :foreground "DeepSkyBlue")
                                ;; Allow yanking right now instead of returning "Mark set"
                                (push-mark)))

;; Eshell history size
(setq eshell-history-size 1000) ; Same as env var HISTSIZE.

;; Eshell-banner
(setq eshell-banner-message (format "%s %s\nwith Emacs %s on %s"
                                    (propertize
                                     "Eshell session started on"
                                     'face '((:foreground "Goldenrod")))
                                    (propertize
                                     (format-time-string "%c")
                                     'face '((:foreground "magenta")))
                                    (propertize emacs-version
                                                'face '((:foreground "magenta")))
                                    (propertize
                                     (with-temp-buffer
                                       (call-process "uname" nil t nil "-r")
                                       (buffer-string))
                                     'face '((:foreground "magenta")))))
```

**Comment by rgtk** [comment]
Thank you.

Code below works as intented:

     (add-hook 'eshell-mode-hook
               #'(lambda ()
                   ;; Helm completion with pcomplete
                   (setq eshell-cmpl-ignore-case t)
                   (eshell-cmpl-initialize)
                   (define-key eshell-mode-map [remap eshell-pcomplete] 'helm-esh-pcomplete)
                   ;; Helm lisp completion
                   (define-key eshell-mode-map [remap eshell-complete-lisp-symbol] 'helm-lisp-completion-at-point)
                   ;; Helm completion on eshell history.
                   (define-key eshell-mode-map (kbd "M-p") 'helm-eshell-history)))



Is usage example in `helm-eshell.el` (one used in first message) obsolete?

**Comment by thierryvolpiatto** [comment]
Ralph Gutkowski <notifications@github.com> writes:

> Thank you.
>
> Code below works as intented:
>
>  (add-hook 'eshell-mode-hook
>            #'(lambda ()
>                ;; Helm completion with pcomplete
>                (setq eshell-cmpl-ignore-case t)
>                (eshell-cmpl-initialize)
>                (define-key eshell-mode-map [remap eshell-pcomplete] 'helm-esh-pcomplete)
>                ;; Helm lisp completion
>                (define-key eshell-mode-map [remap eshell-complete-lisp-symbol] 'helm-lisp-completion-at-point)
>                ;; Helm completion on eshell history.
>                (define-key eshell-mode-map (kbd "M-p") 'helm-eshell-history)))
>
> Is usage example in helm-eshell.el (one used in first message) obsolete?

Hmm, yes probably, I will fix this ASAP.

Thanks.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by thierryvolpiatto** [comment]
I have updated wiki and comment in helm-eshell.

Thanks.
