### ISSUE TITLE
helm-browse-project: bookmark recent (history) projects automaticity?

### ISSUE THREAD

**Issue by xuchunyang** [emacs-helm/helm#1159]
I find the concept of recent projects is useful for me, like recent files, for now, I bookmark `helm-find-files` sessions manually, then add that source to `helm-mini-default-sources`.  How can I let `helm-browse-project` to do it automatically for me when really in a project, like in a git repo?

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

> I find the concept of recent projects is useful for me, like recent
> files, for now, I bookmark helm-find-files sessions manually, then add
> that source to helm-mini-default-sources. How can I let
> helm-browse-project to do it automatically for me when really in a
> project, like in a git repo?

Interesting, I have no ideas for now, will think at it.

-- 
Thierry

https://emacs-helm.github.io/helm/
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by dmh43** [comment]
@xuchunyang this might be a bit late, but have you tried [projectile](https://github.com/bbatsov/projectile) with [Helm-projectile](tuhdo.github.io/helm-projectile.html)? It does what you want and much much more (C-c p p by default to switch between projects previously opened by projectile)

**Comment by xuchunyang** [comment]
Yes, I had used it for a long time and it worked well.  Except this function, all other functions provided by projectile are not needed to me, so I implemented this function myself in my [init.el](https://github.com/xuchunyang/emacs.d/blob/a55a7d8eb5ef536a3c57fb9f23c20d37e96525d7/init.el#L1161-L1231).

**Comment by thierryvolpiatto** [comment]
@xuchunyang I have no idea what need to be fixed here, what should be the behavior of this new functionality if implemented?

**Comment by xuchunyang** [comment]
```diff
diff --git a/helm-files.el b/helm-files.el
index ca1735d..6a8bb7e 100644
--- a/helm-files.el
+++ b/helm-files.el
@@ -3225,6 +3225,18 @@ Set `recentf-max-saved-items' to a bigger value if default is too small.")
         :ff-transformer-show-only-basename nil
         :buffer "*helm browse project*"))
 
+(defvar helm-browse-project-history nil)
+
+(defun helm-browse-project-history ()
+  (interactive)
+  (helm :sources
+        (helm-build-sync-source "Project history"
+          :candidates helm-browse-project-history
+          :action (lambda (candidate)
+                    (with-helm-default-directory candidate
+                        (helm-browse-project nil))))
+        :buffer "*helm browse project history*"))
+
 ;;;###autoload
 (defun helm-browse-project (arg)
   "Preconfigured helm to browse projects.
@@ -3252,7 +3264,9 @@ and
         (helm-buffers-in-project-p t))
     (cond ((and (require 'helm-ls-git nil t)
                 (fboundp 'helm-ls-git-root-dir)
-                (helm-ls-git-root-dir))
+                (let ((root (helm-ls-git-root-dir)))
+                  (and root (cl-pushnew root helm-browse-project-history
+                                        :test #'string=))))
            (helm-ls-git-ls))
           ((and (require 'helm-ls-hg nil t)
                 (fboundp 'helm-hg-root)
```

(For simplicity, only git project is considered.)

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

> diff --git a/helm-files.el b/helm-files.el
> index ca1735d..6a8bb7e 100644

> (For simplicity, only git project is considered.)

Applied with some more changes.

Thanks.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

> diff --git a/helm-files.el b/helm-files.el
> index ca1735d..6a8bb7e 100644
> --- a/helm-files.el
> +++ b/helm-files.el
> +                  (and root (cl-pushnew root helm-browse-project-history
> +                                        :test #'string=))))

Perhaps we could always push the last visited project on top ?
cl-pushnew is doing that only if project haven't been already added to
history.
So we could use instead something like `(push project (remove project
history)`.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
I have intermitent access to internet actually, so I didn't see your change and make the change myself slighly differently, when merging I finally choose mine.

Thanks, closing now.
