### ISSUE TITLE
helm-do-grep-ag not working on OSX, always show no result

### ISSUE THREAD

**Issue by xuchunyang** [emacs-helm/helm#1160]
The `*Message*` buffer also says:

> Error during redisplay: (eval (helm-show-candidate-number (car-safe helm-mode-line-string))) signaled (wrong-type-argument integer-or-marker-p nil) [2 times]

It works normal when don't let-bind `process-connection-type` to `nil` in `helm-grep-ag-init`.

--
Using Emacs 24.5.1 and Ag
```
 ~  ag --version
ag version 0.30.0

Features:
  +jit +lzma +zlib
```

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

> It works normal when don't let-bind process-connection-type to nil in helm-grep-ag-init.
>
> Using Emacs 24.5.1 and Ag
>
>  ~  ag --version
> ag version 0.30.0

This related to the version, I was using 19.2 (ubuntu) which support a
nil value for process-connection-type, when switching to 30 it fail
also.
Should work now.

Thanks.

-- 
Thierry

https://emacs-helm.github.io/helm/
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by xuchunyang** [comment]
Great!
