### ISSUE TITLE
helm-buffers-list: @ broken

### ISSUE THREAD

**Issue by michael-heerdegen** [emacs-helm/helm#1162]
Hello,

in a fresh emacs-helm.sh, M-x helm-buffers-list RET and enter an "@" into the minibuffer (without quotation marks)

 ==> "Helm issued errors: helm-match-from-candidates in source `Buffers': wrong-type-argument (stringp nil)"

The error persists when you enter a string after "@".  This also happens when you prepend a normal buffer search pattern before the "@", so, more or less, whenever you try to use the "@" operator.

Thanks in advance.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Hello,
>
> in a fresh emacs-helm.sh, M-x helm-buffers-list RET and enter an "@"
> into the minibuffer (without quotation marks)
>
> ==> "Helm issued errors: helm-match-from-candidates in source
> `Buffers': wrong-type-argument (stringp nil)"

Should work now, thanks.

-- 
Thierry

https://emacs-helm.github.io/helm/
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
Looks good, thanks!
