### ISSUE TITLE
helm-etags-select doesn't work with identifiers containing apostrophes

### ISSUE THREAD

**Issue by arybczak** [emacs-helm/helm#1164]
In Haskell symbols can have apostrophes (') in them, but when `helm-etags-select` is invoked on such symbol, it just displays a list of tags with empty prompt. Also, even if I choose the symbol from the list, it's jumping to the first occurrence of the identifier in the file its definition is as opposed to jumping to definition directly (find-tag function works as expected, i.e. jumps to definition).

**Comment by thierryvolpiatto** [comment]
Andrzej Rybczak <notifications@github.com> writes:

> In Haskell symbols can have apostrophes in them, but when
> helm-etags-select is invoked on such symbol, it just displays a list
> of tags with empty prompt. Also, even if I choose the symbol from the
> list, it's jumping to the first occurrence of the identifier in the
> file its definition is as opposed to jumping to definition directly
> (find-tag function works as expected, i.e. jumps to definition).

Try to customize `helm-etags-match-part-only' to see if it fix your
problem.
If not, could you provide a sample file so that I can reproduce the
problem ?
(With instructions for eventually install what needed for haskell, I
know nothing of it)

Thanks.

-- 
Thierry

https://emacs-helm.github.io/helm/
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by arybczak** [comment]
I tried setting helm-etags-match-part-only to 'all, but it didn't help.

The files to reproduce are here: http://rybczak.net/gh/ (A.hs, B.hs and corresponding TAGS). I don't think you need any additional packages (you won't get syntax highlighting, but that's not a big problem).

Currently, when you try to jump from B to A using helm-etags-select while the point is on:
1) foo, it shows you a choice between foo' and foo (I'm not sure why) and then when you select foo jumps to the first occurrence of foo in the A file (instead of definition), which is in the comment.
2) foo', it shows you a list of all tags with empty prompt as if the point was not on a symbol.
3) bar, it jumps correctly to the definition. However, if you try to jump to bar by invoking helm-etags-select while the point is not on a symbol (so you start with a list of tags and empty prompt), after you select bar it will jump to the first occurrence in the comment instead of the definition.
4) baz, it jumps correctly to the definition.

find-tag on the other hand handles all of these cases properly.

Btw, helm is overall pretty amazing, you did a great job!

**Comment by thierryvolpiatto** [comment]
Andrzej Rybczak <notifications@github.com> writes:

> I tried setting helm-etags-match-part-only to 'all, but it didn't help.
>
> The files to reproduce are here: http://rybczak.net/gh/ (A.hs, B.hs and corresponding TAGS). I don't think you need any additional packages (you won't get syntax
> highlighting, but that's not a big problem).
>
> Currently, when you try to jump from B to A using helm-etags-select while the point is on:
> 1) foo, it shows you a choice between foo' and foo (I'm not sure why) and then when you select foo jumps to the first occurrence of foo in the A file (instead of
> definition), which is in the comment.
> 2) foo', it shows you a list of all tags with empty prompt as if the point was not on a symbol.
> 3) bar, it jumps correctly to the definition. However, if you try to jump to bar by invoking helm-etags-select while the point is not on a symbol (so you start with a
> list of tags and empty prompt), after you select bar it will jump to the first occurrence in the comment instead of the definition.
> 4) baz, it jumps correctly to the definition.
>
> find-tag on the other hand handles all of these cases properly.

Thanks for the files, I will see what I can do in next week.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by thierryvolpiatto** [comment]
Andrzej Rybczak <notifications@github.com> writes:

> I tried setting helm-etags-match-part-only to 'all, but it didn't help.
>
> The files to reproduce are here: http://rybczak.net/gh/ (A.hs, B.hs
> and corresponding TAGS). I don't think you need any additional
> packages (you won't get syntax highlighting, but that's not a big
> problem).

No, I need haskell-mode to find where are the comments :-)
IOW Emacs need a syntax table to find this.

> Currently, when you try to jump from B to A using helm-etags-select while the point is on:
> 1) foo, it shows you a choice between foo' and foo (I'm not sure why)

This etags that have added foo and foo' in the tag file, don't know why too.

> and then when you select foo jumps to the first occurrence of foo in
> the A file (instead of definition), which is in the comment.

Yes I think I have fixed this it is the main problem IMO.

Hmm no, not fully I am jumping now to => foo . (*2)
which is wrong, I should jump to foo :: right ?
 
> 2) foo', it shows you a list of all tags with empty prompt as if the
> point was not on a symbol.

I have only two tags now in helm buffer in this case:

foo
foo'

> 3) bar, it jumps correctly to the definition. However, if you try to
> jump to bar by invoking helm-etags-select while the point is not on a
> symbol (so you start with a list of tags and empty prompt), after you
> select bar it will jump to the first occurrence in the comment instead
> of the definition.

Ok I think this one is fixed too.

What is wrong is that helm should jump directly to bar without
displaying all tags (need to fix the default entry).

> 4) baz, it jumps correctly to the definition.

Yes, normal there is only one occurence and no comments where it could
be found.

> Btw, helm is overall pretty amazing, you did a great job!

Thanks.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by arybczak** [comment]
> No, I need haskell-mode to find where are the comments :-)
> IOW Emacs need a syntax table to find this.

Comments are just lines prefixed with --. Does search depend on them being comments?

**Comment by thierryvolpiatto** [comment]
See PR #1166

**Comment by thierryvolpiatto** [comment]
Andrzej Rybczak <notifications@github.com> writes:

>     No, I need haskell-mode to find where are the comments :-)
>     IOW Emacs need a syntax table to find this.
>    
> Comments are just lines prefixed with --. Does search depend on them being comments?

I don't need anymore this information which was needed for syntax-ppss.
You can try the branch fix_etags if you want (unfinished work, but
mostly working).

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by thierryvolpiatto** [comment]
Most issues have been addressed now.
- Now jumping to `foo` and `foo'` is working.
- When point is on `foo'` or `foo` you will have the helm buffer displaying
 `foo'` and `foo` but no more all candidates as before.
I can't make helm jumping directly to them because of regexp symbol matching
enclosers that don't understand the ending "'".

So I am merging now, let me know if it is ok for you like this.

Thanks.

**Comment by arybczak** [comment]
Confirmed that It works now, thank you!

**Comment by arybczak** [comment]
Unfortunately it stopped working properly at some point. If you hover over a symbol without `'` at the end and bring a list of tags, it copies the symbol to the minibuffer, but you end up with empty minibuffer if you hover over a symbol with `'` at the end.

If you manually type the symbol and select it, jumping to its definition works fine, it seems it's just copying it to the minibuffer that's broken.

This is with `helm-20190418.1750`.

**Comment by thierryvolpiatto** [comment]
Can you provide a recipe?
Thanks.

**Comment by thierryvolpiatto** [comment]
@arybczak If you want I fix this I need an haskell file with a clear recipe to reproduce.
Thanks.

**Comment by arybczak** [comment]
Sorry, here it is.

[test.tar.gz](https://github.com/emacs-helm/helm/files/3145531/test.tar.gz)

There are two files, A.hs and B.hs, in A.hs there are references to `foo` and `foo'` from B.hs. Jumping to `foo` works fine, but jumping to `foo'` doesn't.

**Comment by thierryvolpiatto** [comment]
Thanks, I can't reproduce from your files but maybe I missed something, here some screenshots (this is from emacs-26.2):

![Capture d’écran_2019-05-05_17-10-19](https://user-images.githubusercontent.com/1533939/57196038-27ae0800-6f59-11e9-8690-98b81f52f10b.png)
![Capture d’écran_2019-05-05_17-11-02](https://user-images.githubusercontent.com/1533939/57196045-3399ca00-6f59-11e9-9105-e5c3e8ef0b30.png)
![Capture d’écran_2019-05-05_17-11-20](https://user-images.githubusercontent.com/1533939/57196048-3dbbc880-6f59-11e9-8c8b-b908d2d495c4.png)

**Comment by arybczak** [comment]
Yes, jumping to definition works and the tag is present on the list. However, compare:
- if you hover over `foo` in `A.hs` and you execute `helm-etags-select`, you get `foo` and `foo'` on the list (btw, can't helm restrict it to `foo'` only and jump immediately? `symbol-at-point` returns `foo'`).
- if you hover over `foo'` in `A.hs` and you execute `helm-etags-select`, you get all of the tags present in `TAGS` file, so no filtering happens, though it used to restrict the list.

**Comment by thierryvolpiatto** [comment]
Andrzej Rybczak <notifications@github.com> writes:

> Yes, jumping to definition works and the tag is present on the list. However, compare:
>
>   * if you hover over foo in A.hs and you execute helm-etags-select,
>   you get foo and foo' on the list



>   (btw, can't helm restrict it to foo' only and jump immediately?
>   symbol-at-point returns foo').

>   * if you hover over foo' in A.hs and you execute helm-etags-select,
>   you get all of the tags present in TAGS file, so no filtering
>   happens, though it used to restrict the list.

Ok, by "hover" you mean selecting region right ?
You should have in minibuffer "\_<foo'\>_" (verify with M-n) right ?

In this case, yes you get all tags, but if you just move cursor (point)
on foo' you get same results as with foo, you have foo and foo' in helm
buffer because the default is now "\_<foo\_>" and not "\_<foo'\_>"
because (thing-at-point 'symbol) returns foo but not foo', foo is not
considered as a symbol in emacs, perhaps the Haskell mode should define
a special function for thing-at-point:

    (defun forward-hsymbol (arg)
      (interactive "^p")
      (if (natnump arg)
          (re-search-forward "\\(\\sw\\|\\s_\\|[']\\)+" nil 'move arg)
        (while (< arg 0)
          (if (re-search-backward "\\(\\sw\\|\\s_\\|[']\\)+" nil 'move)
    	  (skip-syntax-backward "w_"))
          (setq arg (1+ arg)))))


Now with something like this, you can eval (with M-:): 
    
    (thing-at-point 'hsymbol)

which on foo' returns "foo'" unlike (thing-at-point 'symbol) which
returns "foo".

What I can do on the Helm side is defining a variable where a user can
set a function which returns the right symbol according to the mode.
Note also that I will have to fix the enclosing regexp "\_<" and "\_>"
which doesn't understand foo'.

--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Try this patch:

```diff
diff --git a/helm-tags.el b/helm-tags.el
index 17d8242e..4fe4651b 100644
--- a/helm-tags.el
+++ b/helm-tags.el
@@ -292,6 +292,16 @@ If FILE is nil return nil."
     (and last-modif
          (/= last-modif (helm-etags-mtime file)))))
 
+(defun forward-hsymbol (arg)
+  "Same as `forward-symbol' but for Haskell."
+  (interactive "^p")
+  (if (natnump arg)
+      (re-search-forward "\\(\\sw\\|\\s_\\|[']\\)+" nil 'move arg)
+    (while (< arg 0)
+      (if (re-search-backward "\\(\\sw\\|\\s_\\|[']\\)+" nil 'move)
+	  (skip-syntax-backward "w_"))
+      (setq arg (1+ arg)))))
+
 ;;;###autoload
 (defun helm-etags-select (reinit)
   "Preconfigured helm for etags.
@@ -305,13 +315,14 @@ This function aggregates three sources of tag files:
   2) `tags-file-name', which is commonly set by `find-tag' command.
   3) `tags-table-list' which is commonly set by `visit-tags-table' command."
   (interactive "P")
-  (let ((tag-files (helm-etags-all-tag-files))
-        (helm-execute-action-at-once-if-one
-         helm-etags-execute-action-at-once-if-one)
-        (str (if (region-active-p)
-                 (buffer-substring-no-properties
-                  (region-beginning) (region-end))
-               (thing-at-point 'symbol))))
+  (let* ((tag-files (helm-etags-all-tag-files))
+         (helm-execute-action-at-once-if-one
+          helm-etags-execute-action-at-once-if-one)
+         (sym (if (eq major-mode 'haskell-mode) 'hsymbol 'symbol))
+         (str (if (region-active-p)
+                  (buffer-substring-no-properties
+                   (region-beginning) (region-end))
+                (thing-at-point sym))))
     (if (cl-notany 'file-exists-p tag-files)
         (message "Error: No tag file found.\
 Create with etags shell command, or visit with `find-tag' or `visit-tags-table'.")

Assuming the mode you use is haskell-mode it should work.
```

**Comment by thierryvolpiatto** [comment]
With haskell-mode installed thing-at-point returns foo', so the only thing you have to do is when cursor is on foo' to press twice M-n after calling helm-etags-select.
"\_<" and "\_>" don't understand such symbols.

**Comment by arybczak** [comment]
I'm not sure I understand.

It looks like when I press M-n twice, I indeed get the symbol in the minibuffer, but why can't `helm-etags-select` make use of `thing-at-point` function when it's called to restrict the list of symbols without my manual intervention?

**Comment by arybczak** [comment]
I tried your patch, it doesn't seem to help :(

**Comment by arybczak** [comment]
Hmmm.

Alright, I took a closer look at the code and it looks like when I set `helm-etags-fuzzy-match` then matching symbols with `'` works fine (even without your patch) because they aren't wrapped in `_<` and `_>`.

Now your explanation makes sense. So there is no way to have exact matching if a symbol has apostrophes (or potentially other unusual symbols)?

**Comment by arybczak** [comment]
ping

**Comment by thierryvolpiatto** [comment]
Andrzej Rybczak <notifications@github.com> writes:

> ping

Sorry.

Is this patch working?

diff --git a/helm-tags.el b/helm-tags.el
index 17d8242e..0794378c 100644
--- a/helm-tags.el
+++ b/helm-tags.el
@@ -329,7 +329,9 @@ Create with etags shell command, or visit with `find-tag' or `visit-tags-table'.
                 (helm-etags-build-source)))
         (helm :sources 'helm-source-etags-select
               :keymap helm-etags-map
-              :default (if helm-etags-fuzzy-match
+              :default (if (or helm-etags-fuzzy-match
+                               (and (eq major-mode 'haskell-mode)
+                                    (string-match "[']\\'" str)))
                            str
                            (list (concat "\\_<" str "\\_>") str))
               :buffer "*helm etags*"))))


-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by arybczak** [comment]
This doesn't solve the problem, it actually breaks `helm-etags-select` when `thing-at-point 'symbol` gives you `nil`, i.e. when cursor is not on top of any symbol.

The problem is not when `helm-etags-fuzzy-match` is enabled, it's when `helm-etags-fuzzy-match` is disabled, i.e. the case of `(list (concat "\\_<" str "\\_>") str))`.

The question is why doesn't this case support symbols with `'` in them?

**Comment by arybczak** [comment]
This seems to work:

```diff
diff --git a/helm-tags.el b/helm-tags.el
index 04e8b5a6..2e073664 100644
--- a/helm-tags.el
+++ b/helm-tags.el
@@ -329,11 +329,9 @@ Create with etags shell command, or visit with `find-tag' or `visit-tags-table'.
                 (helm-etags-build-source)))
         (helm :sources 'helm-source-etags-select
               :keymap helm-etags-map
-              :default (if (or helm-etags-fuzzy-match
-                               (and (eq major-mode 'haskell-mode)
-                                    (string-match "[']\\'" str)))
+              :default (if helm-etags-fuzzy-match
                            str
-                         (list (concat "\\_<" str "\\_>") str))
+                         (list str))
               :buffer "*helm etags*"))))
 
 (provide 'helm-tags)
```

**Comment by arybczak** [comment]
This seems to work:

```diff
diff --git a/helm-tags.el b/helm-tags.el
index 04e8b5a6..4863cfd0 100644
--- a/helm-tags.el
+++ b/helm-tags.el
@@ -311,7 +311,7 @@ This function aggregates three sources of tag files:
         (str (if (region-active-p)
                  (buffer-substring-no-properties
                   (region-beginning) (region-end))
-               (thing-at-point 'symbol))))
+               (or (thing-at-point 'symbol) ""))))
     (if (cl-notany 'file-exists-p tag-files)
         (message "Error: No tag file found.\
 Create with etags shell command, or visit with `find-tag' or `visit-tags-table'.")
@@ -329,11 +329,14 @@ Create with etags shell command, or visit with `find-tag' or `visit-tags-table'.
                 (helm-etags-build-source)))
         (helm :sources 'helm-source-etags-select
               :keymap helm-etags-map
-              :default (if (or helm-etags-fuzzy-match
-                               (and (eq major-mode 'haskell-mode)
-                                    (string-match "[']\\'" str)))
+              :default (if helm-etags-fuzzy-match
                            str
-                         (list (concat "\\_<" str "\\_>") str))
+                         (list (concat "\\_<"
+                                       (replace-regexp-in-string "[^[:alnum:]_-]"
+                                                                 ""
+                                                                 str)
+                                       "\\_>")
+                               str))
               :buffer "*helm etags*"))))
 
 (provide 'helm-tags)
```

Though I don't know if the replacement is not too restrictive.

**Comment by thierryvolpiatto** [comment]
Andrzej Rybczak <notifications@github.com> writes:

> This seems to work:

Fail anywhere else.

> +              :default (if helm-etags-fuzzy-match
>                             str
> -                         (list (concat "\\_<" str "\\_>") str))
> +                         (list str))

Same as :default str

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Andrzej Rybczak <notifications@github.com> writes:

> This doesn't solve the problem,

You have two symbols, foo and foo'

When you want to match foo you will match foo and foo', it will never be
better as \\<_foo'\\_> is NOT supporting symbols ending with "'".

When you want to match foo' it will match only foo' and jump to it
because we are not enclosing foo' in special regexp \\_<...\\_>

The list (list "\\_<foo\\_>" "foo") is here to provide two alternatives,
see documentation of history in completing-read and friends.

> it actually breaks helm-etags-select when thing-at-point 'symbol gives
> you nil, i.e. when cursor is not on top of any symbol.

Right, fixed, thanks.

>
> The problem is not when helm-etags-fuzzy-match is enabled, it's when
> helm-etags-fuzzy-match is disabled, i.e. the case of (list (concat
> "\\_<" str "\\_>") str)).
>
> The question is why doesn't this case support symbols with ' in them?

    ‘\_<’
         matches the empty string, but only at the beginning of a symbol.  A
         symbol is a sequence of one or more word or symbol constituent
         characters.  ‘\_<’ matches at the beginning of the buffer (or
         string) only if a symbol-constituent character follows.

I guess foo' is not considered by elisp regexp matcher as a
symbol-constituent character.

--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by arybczak** [comment]
You're right. Both of my proposed solutions don't really work 100%, yours is fine now.

Thank you for taking care of it :heart:
