### ISSUE TITLE
why spacemacs helm mini does not use regexp to filter the candicate

### ISSUE THREAD

**Issue by LuoPX-15510486969** [emacs-helm/helm#1165]
i love helm so much and i use spacemacs which is built on helm .But i found a problem that with spacemacs i can not use filter * to filter mode and regexp and "@" to filter the content which are powerful feature in helm mini . I open an issue in spacemacs but i got no answer.so i post it here fo find sth.

**Comment by michael-heerdegen** [comment]
Sounds like #1162 I had reported two days ago and that has been fixed.

Dunno how Helm is integrated into spacemacs.  I guess loading an up to date helm-buffers.el should make the problem disappear for you until the change makes it into spacemacs.  All with the assumption that it's the same problem as #1162 of course.

**Comment by LuoPX-15510486969** [comment]
the [#1162](https://github.com/emacs-helm/helm/issues/1162) has only @ broken,but in spacemacs it can noly use fuzzy match to filter. the mode filter "*" and the regexp were broken too.

**Comment by thierryvolpiatto** [comment]
This issue is related to spacemacs, all this is working fine outside of evil.
I don't know evil, but I think they bind "*" to something, it is why it doesn't work for you.
You should report this to spacemacs.

Thanks.
