### ISSUE TITLE
helm-fuzzy-sort-function not used in helm-find-files

### ISSUE THREAD

**Issue by PythonNut** [emacs-helm/helm#1167]
For some reason `helm-fuzzy-sort-function` is not used for `helm-find-files`. I've verified this with Emacs 24.5 and `debug-on-entry` (my fuzzy sorting function is never called).

p.s. Love the new logo :+1:

**Comment by thierryvolpiatto** [comment]
PythonNut <notifications@github.com> writes:

> For some reason helm-fuzzy-sort-function is not used for
> helm-find-files. I've verified this with Emacs 24.5 and debug-on-entry
> (my fuzzy sorting function is never called).

Fuzzy is enabled by default and working differently in hff.
(Don't expect I will change this)

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by PythonNut** [comment]
@thierryvolpiatto then the sorting is not customizable?

**Comment by thierryvolpiatto** [comment]
PythonNut <notifications@github.com> writes:

> @thierryvolpiatto then the sorting is not customizable?

No.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by PythonNut** [comment]
@thierryvolpiatto is this also the case for `helm-buffers`?

**Comment by thierryvolpiatto** [comment]
PythonNut <notifications@github.com> writes:

> @thierryvolpiatto is this also the case for helm-buffers?

Yes.

-- 
Thierry
https://emacs-helm.github.io/helm/
