### ISSUE TITLE
helm-find-files: enter a tilde to go to home directory

### ISSUE THREAD

**Issue by shoichit** [emacs-helm/helm#1169]
HI there,

I hope I am posting at the correct page. Please let me know if I should do this in a different page.

I just installed helm ("helm-20140724.548") and started using helm-find-files. When I enter a tilde '~' wanting to visit my home directory, it just try to create a new file "~". Is there any way to change this behavior? If not, I would appreciate if you could recommend how to fix this in most efficient way.

Thank you!
Shoichi

**Comment by thierryvolpiatto** [comment]
shoichit <notifications@github.com> writes:

> I just installed helm ("helm-20140724.548") and started using
> helm-find-files. When I enter a tilde '~' wanting to visit my home
> directory, it just try to create a new file "~".

This should be fixed now, thanks.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by thierryvolpiatto** [comment]
shoichit <notifications@github.com> writes:

> I just installed helm ("helm-20140724.548")

However I don't know this version of helm,
where did you get it ?

-- 
Thierry
https://emacs-helm.github.io/helm/
