### ISSUE TITLE
helm-match-item background not used

### ISSUE THREAD

**Issue by dato** [emacs-helm/helm#1170]
Hello!

I’m a new Helm user, and I’m struggling to solve the following issue: the background of _helm-selection_ overrides that of _helm-match-item_, as can be seen here:

![helm-match](https://cloud.githubusercontent.com/assets/73768/9865493/83b2cb00-5b57-11e5-9443-d5fa7cdefdef.png)

This is with an empty init file on OS X. As you can see, _helm-match-item_ has a magenta background, but the ‘helm-match’ word in the first line has a green background, not magenta.

Thanks.

**Comment by xuchunyang** [comment]
I guess you are running `helm-colors` without any theme, the left is the face name, the right is its value. Your current input should be `helm-match`, and its foreground is red. Your cursor is on the first candidate, so that line has green background.  IMO, everything is fine.

**Comment by dato** [comment]
The first 10 characters on the first candidate should have a magenta background, I should think.

**Comment by xuchunyang** [comment]
Nope, `helm-match` is used for that, not `helm-match-item`.

**Comment by dato** [comment]
_helm-match-item_: “Face used to highlight item matched in a selected line.”

(With my theme it becomes unreadable, that's how I know it's being used.)

**Comment by xuchunyang** [comment]
`helm-match-item` is used to highlight matches in user's buffer (not in helm's buffer), you can try it by type `C-j` (or `C-z`) while using `helm-occur`, for example

![2015-09-15 9 37 46](https://cloud.githubusercontent.com/assets/4550353/9865832/33415c68-5b8e-11e5-8379-29f5e02af362.png)

**Comment by dato** [comment]
Oh, I see. Okay.

Then:

In the examples above, the _helm-match_ face specified a foreground, but not a background. And _helm-selection_ specified a background. It worked nicely.

However, I'm having problems because my _helm-match_ face specifies a background, but the corresponding part of the selected line doesn't use it: it uses _helm-selection_ in its entirety.

(I can create a screenshot if my description is not enough.)

Thanks for your help.

**Comment by thierryvolpiatto** [comment]
`helm-selection` overrides all faces in `helm-buffer` because it have hight priority on all other faces.
`helm-match-item` as stated by @xuchunyang  is to highlight matched item in `helm-current-buffer`
(the current-buffer when you started helm) when performing persistent action.
Here a screenshot of helm occur in persistent action:
![screenshot - 15092015 - 06 40 44](https://cloud.githubusercontent.com/assets/1533939/9868142/ce1f517c-5b75-11e5-9ae3-33160f94386f.png)

**Comment by dato** [comment]
Thanks for your response.

I miss having the term highlighted in the selected line, as in the other lines.

Is there a way it can work?

**Comment by thierryvolpiatto** [comment]
No, it is a feature, as I said the `helm-selection` should override all other faces.
You can see in the screenshot above `helm-selection` overriding matched items in the `helm-buffer`,
this is wanted, `helm-selection` have hight priority on other faces.

**Comment by dato** [comment]
Ok, thanks.

**Comment by transtone** [comment]
this is completely wrong:`the helm-selection should override all other faces.`!!

how can I use a face like this? (find-file-in-project)
<img width="519" alt="2016-07-30 14 25 00" src="https://cloud.githubusercontent.com/assets/46688/17275488/01b56a62-573d-11e6-968d-12f1d8364180.png">
