### ISSUE TITLE
Infinite loop of helm-browse-project caused by (helm-browse-project-get--root-dir "~/")

### ISSUE THREAD

**Issue by xuchunyang** [emacs-helm/helm#1171]
In `*scratch*` buffer (its local value of  `default-directory` is "~/"), using `helm-browse-project` command blocks my Emacs, and `(helm-browse-project-get--root-dir (helm-current-directory))` will enter an endless loop.

Making sure the directory name returned by `helm-current-directory` gets expanded seems fix this issue.

```diff
diff -u --label /Users/xcy/.emacs.d/elpa/helm-core-20150915.1340/helm-lib.el --label \#\<buffer\ helm-lib.el\> /Users/xcy/.emacs.d/elpa/helm-core-20150915.1340/helm-lib.el /var/folders/50/hxvm95r941s0v977bj7cnl0c0000gn/T/buffer-content-10197yVk
--- /Users/xcy/.emacs.d/elpa/helm-core-20150915.1340/helm-lib.el
+++ #<buffer helm-lib.el>
@@ -422,9 +422,10 @@
 (defun helm-current-directory ()
   "Return current-directory name at point.
 Useful in dired buffers when there is inserted subdirs."
-  (if (eq major-mode 'dired-mode)
-      (dired-current-directory)
-    default-directory))
+  (expand-file-name
+   (if (eq major-mode 'dired-mode)
+       (dired-current-directory)
+     default-directory)))
 
 (defun helm-w32-prepare-filename (file)
   "Convert filename FILE to something usable by external w32 executables."

Diff finished.  Wed Sep 16 22:26:42 2015
```

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

> In *scratch* buffer (its local value of default-directory is "~/"),
> using helm-browse-project command blocks my Emacs, and
> (helm-browse-project-get--root-dir (helm-current-directory)) will
> enter an endless loop.

Thanks to catch this.
Applied.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
