### ISSUE TITLE
emacs crashes - please help

### ISSUE THREAD

**Issue by abelardojarab** [emacs-helm/helm#1173]
the people here are super experts

please help me. i have issue with emacs

can someone help me please with this?

my emacs keeps crashing all the time, no matter if im under Mac OS X or Linux. What package should i disable to make this go away?

i use configuration as here https://github.com/abelardojarab/emacsfull.git

bt gives this:
(gdb) bt
#0 0x00002aaaafa6b755 in raise () from /lib64/libc.so.6
#1 0x00002aaaafa6cd31 in abort () from /lib64/libc.so.6
#2 0x00002aaaafaa9c1f in __libc_message () from /lib64/libc.so.6
#3 0x00002aaaafaaf338 in malloc_printerr () from /lib64/libc.so.6
#4 0x00002aaaafaaf91f in malloc_consolidate () from /lib64/libc.so.6
#5 0x00002aaaafab0e30 in _int_free () from /lib64/libc.so.6
#6 0x00002aaaafab437c in free () from /lib64/libc.so.6
#7 0x000000000054fc73 in Fgarbage_collect ()
#8 0x0000000006b1c406 in ?? ()
#9 0x00000000000080f7 in ?? ()
#10 0x0000000000000001 in ?? ()
#11 0x01000000065b4ae8 in ?? ()
#12 0x0000000002e70000 in ?? ()
#13 0x0000000002e702c0 in ?? ()
#14 0x0000000000000000 in ?? ()

the gdb output after crashing is:
*** glibc detected *** /nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs: corrupted double-linked list: 0x0000000004d61210 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x76338)[0x2aaaafaaf338]
/lib64/libc.so.6(+0x7691f)[0x2aaaafaaf91f]
/lib64/libc.so.6(+0x77e30)[0x2aaaafab0e30]
/lib64/libc.so.6(cfree+0x6c)[0x2aaaafab437c]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x54fc73]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x59e9d8]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x5677af]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x56698a]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs(eval_sub+0x3a3)[0x566de3]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs(eval_sub+0x808)[0x567248]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x5695a1]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs(Ffuncall+0x484)[0x567da4]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x5661a4]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x43531b]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x4353ef]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x44b53e]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x44b6f9]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x44b6f9]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x450808]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x450af1]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x4682ab]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x46b61e]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x565efa]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x455572]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x455ee7]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x4f8912]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x5a9860]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x4288e3]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x4fb6d5]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x4fcfd0]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs(command_loop_1+0x1f9)[0x4fe499]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x565db0]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x4f16b3]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x565c9b]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x4f3913]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x4f3c85]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x41e59f]
/lib64/libc.so.6(__libc_start_main+0xe6)[0x2aaaafa57c16]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x41f355]
======= Memory map: ========
00400000-00634000 r-xp 00000000 00:28 6470881 /nfs/site/itools/em64t_SLES11/pkgs/emacs/24.4/bin/emacs-24.4
00834000-01368000 rw-p 00234000 00:28 6470881 /nfs/site/itools/em64t_SLES11/pkgs/emacs/24.4/bin/emacs-24.4
01368000-06c16000 rw-p 00000000 00:00 0 [heap]
2aaaaaaab000-2aaaaaaca000 r-xp 00000000 08:02 32634 /lib64/ld-2.11.3.so
2aaaaaaca000-2aaaaaacb000 r-xp 00000000 00:00 0 [vdso]
2aaaaaacb000-2aaaaaacd000 rw-p 00000000 00:00 0 
2aaaaacc9000-2aaaaacca000 r--p 0001e000 08:02 32634 /lib64/ld-2.11.3.so
2aaaaacca000-2aaaaaccb000 rw-p 0001f000 08:02 32634 /lib64/ld-2.11.3.so
2aaaaaccb000-2aaaaaccc000 rw-p 00000000 00:00 0 
2aaaaaccc000-2aaaaad2c000 r-xp 00000000 00:28 2898131 /nfs/site/itools/em64t_SLES11/pkgs/tiff/3.9.1-64/lib64/libtiff.so.3.9.1
2aaaaad2c000-2aaaaaf2c000 ---p 00060000 00:28 2898131 /nfs/site/itools/em64t_SLES11/pkgs/tiff/3.9.1-64/lib64/libtiff.so.3.9.1
2aaaaaf2c000-2aaaaaf2e000 r--p 00060000 00:28 2898131 /nfs/site/itools/em64t_SLES11/pkgs/tiff/3.9.1-64/lib64/libtiff.so.3.9.1
2aaaaaf2e000-2aaaaaf2f000 rw-p 00062000 00:28 2898131 /nfs/site/itools/em64t_SLES11/pkgs/tiff/3.9.1-64/lib64/libtiff.so.3.9.1
2aaaaaf2f000-2aaaaaf30000 rw-p 00000000 00:00 0 
2aaaaaf30000-2aaaaaf4e000 r-xp 00000000 00:28 5340277 /nfs/site/itools/em64t_SLES11/pkgs/jpeg/6b-64/lib/libjpeg.so.62.0.0
2aaaaaf4e000-2aaaab04d000 ---p 0001e000 00:28 5340277 /nfs/site/itools/em64t_SLES11/pkgs/jpeg/6b-64/lib/libjpeg.so.62.0.0
2aaaab04d000-2aaaab051000 rw-p 0001d000 00:28 5340277 /nfs/site/itools/em64t_SLES11/pkgs/jpeg/6b-64/lib/libjpeg.so.62.0.0
2aaaab051000-2aaaab076000 r-xp 00000000 00:28 18211497 /nfs/site/itools/em64t_SLES11/pkgs/libpng/1.2.40-64/lib/libpng12.so.0.40.0
2aaaab076000-2aaaab275000 ---p 00025000 00:28 18211497 /nfs/site/itools/em64t_SLES11/pkgs/libpng/1.2.40-64/lib/libpng12.so.0.40.0
2aaaab275000-2aaaab276000 r--p 00024000 00:28 18211497 /nfs/site/itools/em64t_SLES11/pkgs/libpng/1.2.40-64/lib/libpng12.so.0.40.0
2aaaab276000-2aaaab277000 rw-p 00025000 00:28 18211497 /nfs/site/itools/em64t_SLES11/pkgs/libpng/1.2.40-64/lib/libpng12.so.0.40.0
2aaaab277000-2aaaab28a000 r-xp 00000000 00:28 3086824 /nfs/site/itools/em64t_SLES11/pkgs/zlib/1.2.x-64/lib64/libz.so.1.2.3
2aaaab28a000-2aaaab389000 ---p 00013000 00:28 3086824 /nfs/site/itools/em64t_SLES11/pkgs/zlib/1.2.x-64/lib64/libz.so.1.2.3
2aaaab389000-2aaaab38b000 rw-p 00012000 00:28 3086824 /nfs/site/itools/em64t_SLES11/pkgs/zlib/1.2.x-64/lib64/libz.so.1.2.3
2aaaab38b000-2aaaab38c000 r--p 00000000 08:05 254032 /usr/lib/locale/en_US.utf8/LC_IDENTIFICATION
2aaaab38c000-2aaaab393000 r--s 00000000 08:05 13411 /usr/lib64/gconv/gconv-modules.cache
2aaaab393000-2aaaab394000 r--p 00000000 08:05 261916 /usr/lib/locale/en_US.utf8/LC_MEASUREMENT
2aaaab394000-2aaaab395000 r--p 00000000 08:05 261911 /usr/lib/locale/en_US.utf8/LC_TELEPHONE
2aaaab395000-2aaaab396000 r--p 00000000 08:05 251910 /usr/lib/locale/en_US.utf8/LC_ADDRESS
2aaaab396000-2aaaab397000 r--p 00000000 08:05 260579 /usr/lib/locale/en_US.utf8/LC_NAME
2aaaab397000-2aaaab398000 r--p 00000000 08:05 260566 /usr/lib/locale/en_US.utf8/LC_PAPER
2aaaab398000-2aaaab399000 r--p 00000000 08:05 261912 /usr/lib/locale/en_US.utf8/LC_MESSAGES/SYS_LC_MESSAGES
2aaaab399000-2aaaab39a000 r--p 00000000 08:05 254033 /usr/lib/locale/en_US.utf8/LC_MONETARY
2aaaab39a000-2aaaab39b000 r--p 00000000 08:05 254034 /usr/lib/locale/en_US.utf8/LC_TIME
2aaaab39b000-2aaaab39c000 r--p 00000000 08:05 260632 /usr/lib/locale/en_US.utf8/LC_NUMERIC
2aaaab3ab000-2aaaab406000 r-xp 00000000 08:02 32403 /lib64/libm-2.11.3.so
2aaaab406000-2aaaab605000 ---p 0005b000 08:02 32403 /lib64/libm-2.11.3.so
2aaaab605000-2aaaab606000 r--p 0005a000 08:02 32403 /lib64/libm-2.11.3.so
2aaaab606000-2aaaab624000 rw-p 0005b000 08:02 32403 /lib64/libm-2.11.3.so
2aaaab624000-2aaaab625000 rw-p 00000000 00:00 0 
2aaaab625000-2aaaab636000 r-xp 00000000 00:28 32887742 /nfs/site/itools/em64t_SLES11/pkgs/X11/R7.5-64/lib/libXpm.so.4.11.0
2aaaab636000-2aaaab835000 ---p 00011000 00:28 32887742 /nfs/site/itools/em64t_SLES11/pkgs/X11/R7.5-64/lib/libXpm.so.4.11.0
2aaaab835000-2aaaab836000 r--p 00010000 00:28 32887742 /nfs/site/itools/em64t_SLES11/pkgs/X11/R7.5-64/lib/libXpm.so.4.11.0
2aaaab836000-2aaaab837000 rw-p 00011000 00:28 32887742 /nfs/site/itools/em64t_SLES11/pkgs/X11/R7.5-64/lib/libXpm.so.4.11.0
2aaaab837000-2aaaabc34000 r-xp 00000000 00:28 16585724 /nfs/site/itools/em64t_SLES11/pkgs/gtk+/2.18.6-64/lib64/libgtk-x11-2.0.so.0.1800.6
2aaaabc34000-2aaaabe34000 ---p 003fd000 00:28 16585724 /nfs/site/itools/em64t_SLES11/pkgs/gtk+/2.18.6-64/lib64/libgtk-x11-2.0.so.0.1800.6
2aaaabe34000-2aaaabe3b000 r--p 003fd000 00:28 16585724 /nfs/site/itools/em64t_SLES11/pkgs/gtk+/2.18.6-64/lib64/libgtk-x11-2.0.so.0.1800.6
2aaaabe3b000-2aaaabe3f000 rw-p 00404000 00:28 16585724 /nfs/site/itools/em64t_SLES11/pkgs/gtk+/2.18.6-64/lib64/libgtk-x11-2.0.so.0.1800.6
2aaaabe3f000-2aaaabe41000 rw-p 00000000 00:00 0 
2aaaabe41000-2aaaabee7000 r-xp 00000000 00:28 6779303 /nfs/site/itools/em64t_SLES11/pkgs/gtk+/2.18.6-64/lib64/libgdk-x11-2.0.so.0.1800.6
2aaaabee7000-2aaaac0e6000 ---p 000a6000 00:28 6779303 /nfs/site/itools/em64t_SLES11/pkgs/gtk+/2.18.6-64/lib64/libgdk-x11-2.0.so.0.1800.6
2aaaac0e6000-2aaaac0ea000 r--p 000a5000 00:28 6779303 /nfs/site/itools/em64t_SLES11/pkgs/gtk+/2.18.6-64/lib64/libgdk-x11-2.0.so.0.1800.6
2aaaac0ea000-2aaaac0ec000 rw-p 000a9000 00:28 6779303 /nfs/site/itools/em64t_SLES11/pkgs/gtk+/2.18.6-64/lib64/libgdk-x11-2.0.so.0.1800.6
2aaaac0ec000-2aaaac0ed000 rw-p 00000000 00:00 0 
2aaaac0ed000-2aaaac10b000 r-xp 00000000 00:28 29753415 /nfs/site/itools/em64t_SLES11/pkgs/atk/1.28.0-64/lib64/libatk-1.0.so.0.2809.1
2aaaac10b000-2aaaac30b000 ---p 0001e000 00:28 29753415 /nfs/site/itools/em64t_SLES11/pkgs/atk/1.28.0-64/lib64/libatk-1.0.so.0.2809.1
2aaaac30b000-2aaaac30d000 r--p 0001e000 00:28 29753415 /nfs/site/itools/em64t_SLES11/pkgs/atk/1.28.0-64/lib64/libatk-1.0.so.0.2809.1
2aaaac30d000-2aaaac30e000 rw-p 00020000 00:28 29753415 /nfs/site/itools/em64t_SLES11/pkgs/atk/1.28.0-64/lib64/libatk-1.0.so.0.2809.1
2aaaac30e000-2aaaac3b3000 r-xp 00000000 00:28 9290844 /nfs/site/itools/em64t_SLES11/pkgs/glib/2.22.3-64/lib64/libgio-2.0.so.0.2200.3
2aaaac3b3000-2aaaac5b3000 ---p 000a5000 00:28 9290844 /nfs/site/itools/em64t_SLES11/pkgs/glib/2.22.3-64/lib64/libgio-2.0.so.0.2200.3
2aaaac5b3000-2aaaac5b5000 r--p 000a5000 00:28 9290844 /nfs/site/itools/em64t_SLES11/pkgs/glib/2.22.3-64/lib64/libgio-2.0.so.0.2200.3
2aaaac5b5000-2aaaac5b6000 rw-p 000a7000 00:28 9290844 /nfs/site/itools/em64t_SLES11/pkgs/glib/2.22.3-64/lib64/libgio-2.0.so.0.2200.3
2aaaac5b6000-2aaaac5b7000 rw-p 00000000 00:00 0 
2aaaac5b7000-2aaaac5df000 r-xp 00000000 00:28 23448439 /nfs/site/itools/em64t_SLES11/pkgs/pango/1.26.2-64/lib64/libpangoft2-1.0.so.0.2600.2
2aaaac5df000-2aaaac7de000 ---p 00028000 00:28 23448439 /nfs/site/itools/em64t_SLES11/pkgs/pango/1.26.2-64/lib64/libpangoft2-1.0.so.0.2600.2
2aaaac7de000-2aaaac7df000 r--p 00027000 00:28 23448439 /nfs/site/itools/em64t_SLES11/pkgs/pango/1.26.2-64/lib64/libpangoft2-1.0.so.0.2600.2
2aaaac7df000-2aaaac7e0000 rw-p 00028000 00:28 23448439 /nfs/site/itools/em64t_SLES11/pkgs/pango/1.26.2-64/lib64/libpangoft2-1.0.so.0.2600.2
2aaaac7e0000-2aaaac7e1000 rw-p 00000000 00:00 0 
2aaaac7e1000-2aaaac7fc000 r-xp 00000000 00:28 16585719 /nfs/site/itools/em64t_SLES11/pkgs/gtk+/2.18.6-64/lib64/libgdk_pixbuf-2.0.so.0.1800.6
2aaaac7fc000-2aaaac9fb000 ---p 0001b000 00:28 16585719 /nfs/site/itools/em64t_SLES11/pkgs/gtk+/2.18.6-64/lib64/libgdk_pixbuf-2.0.so.0.1800.6
2aaaac9fb000-2aaaac9fc000 r--p 0001a000 00:28 16585719 /nfs/site/itools/em64t_SLES11/pkgs/gtk+/2.18.6-64/lib64/libgdk_pixbuf-2.0.so.0.1800.6
2aaaac9fc000-2aaaac9fd000 rw-p 0001b000 00:28 16585719 /nfs/site/itools/em64t_SLES11/pkgs/gtk+/2.18.6-64/lib64/libgdk_pixbuf-2.0.so.0.1800.6
2aaaac9fd000-2aaaaca08000 r-xp 00000000 00:28 23448437 /nfs/site/itools/em64t_SLES11/pkgs/pango/1.26.2-64/lib64/libpangocairo-1.0.so.0.2600.2
2aaaaca08000-2aaaacc08000 ---p 0000b000 00:28 23448437 /nfs/site/itools/em64t_SLES11/pkgs/pango/1.26.2-64/lib64/libpangocairo-1.0.so.0.2600.2
2aaaacc08000-2aaaacc09000 r--p 0000b000 00:28 23448437 /nfs/site/itools/em64t_SLES11/pkgs/pango/1.26.2-64/lib64/libpangocairo-1.0.so.0.2600.2
2aaaacc09000-2aaaacc0a000 rw-p 0000c000 00:28 23448437 /nfs/site/itools/em64t_SLES11/pkgs/pango/1.26.2-64/lib64/libpangocairo-1.0.so.0.2600.2
2aaaacc0a000-2aaaacc7f000 r-xp 00000000 00:28 25890820 /nfs/site/itools/em64t_SLES11/pkgs/cairo/1.8.8-64/lib/libcairo.so.2.10800.8
2aaaacc7f000-2aaaace7f000 ---p 00075000 00:28 25890820 /nfs/site/itools/em64t_SLES11/pkgs/cairo/1.8.8-64/lib/libcairo.so.2.10800.8
2aaaace7f000-2aaaace81000 r--p 00075000 00:28 25890820 /nfs/site/itools/em64t_SLES11/pkgs/cairo/1.8.8-64/lib/libcairo.so.2.10800.8
2aaaace81000-2aaaace82000 rw-p 00077000 00:28 25890820 /nfs/site/itools/em64t_SLES11/pkgs/cairo/1.8.8-64/lib/libcairo.so.2.10800.8
2aaaace82000-2aaaace83000 rw-p 00000000 00:00 0 
2aaaace83000-2aaaacecb000 r-xp 00000000 00:28 23448435 /nfs/site/itools/em64t_SLES11/pkgs/pango/1.26.2-64/lib64/libpango-1.0.so.0.2600.2
2aaaacecb000-2aaaad0cb000 ---p 00048000 00:28 23448435 /nfs/site/itools/em64t_SLES11/pkgs/pango/1.26.2-64/lib64/libpango-1.0.so.0.2600.2
2aaaad0cb000-2aaaad0cd000 r--p 00048000 00:28 23448435 /nfs/site/itools/em64t_SLES11/pkgs/pango/1.26.2-64/lib64/libpango-1.0.so.0.2600.2
2aaaad0cd000-2aaaad0ce000 rw-p 0004a000 00:28 23448435 /nfs/site/itools/em64t_SLES11/pkgs/pango/1.26.2-64/lib64/libpango-1.0.so.0.2600.2
2aaaad0ce000-2aaaad14d000 r-xp 00000000 00:28 134817 /nfs/site/itools/em64t_SLES11/pkgs/freetype/2.3.7-64/lib/libfreetype.so.6.3.18
Program received signal SIGABRT, Aborted.
[Switching to Thread 0x2aaab1a8c880 (LWP 38558)]
0x00002aaaafa6b755 in raise () from /lib64/libc.so.6
(gdb)

**Comment by xuchunyang** [comment]
> What package should i disable to make this go away?

Please figure it out by yourself.  You shouldn't ask for help here unless you think the crash is caused by helm.
