### ISSUE TITLE
Add migemo support

### ISSUE THREAD

**Issue by thierryvolpiatto** [emacs-helm/helm#1175]
I have added a PR at #1174 please migemo users test as much as possible.
You can test with helm-occur among others which use by default the migemo support.
I tested also with helm-kill-ring which works also.
The only dependencies needed is migemo.el and of course a migemo backend.
The only one I found was cmigemo and for me migemo.el was broken with this backend (see 
https://github.com/emacs-jp/migemo/issues/21).
I also lack of examples to fully test this, if one can provide examples that would be great.

Thanks.

**Comment by thierryvolpiatto** [comment]
Now merged.

**Comment by thierryvolpiatto** [comment]
No body interested, closing.

**Comment by momomo5717** [comment]
Thank you for the migemo support! It is a big help for migemo users.


I'd like to use `helm-mini` with migemo.
Could a function like the following be added to use predefined sources with migemo?

```emacs-lisp
(defun helm-migemo-migemize-sorce (source)
  "Migemize SOURCE."
  (let* ((source (cond ((listp source) source)
                       ((symbolp source) (symbol-value source))
                       (t nil)))
         (match (assq 'match source))
         (migemo (assq 'migemo source)))
    (when match
      (unless (or (member 'helm-mm-3-migemo-match match)
                  (eq (cdr match) 'helm-mm-3-migemo-match))
        (setcdr match
                (if (functionp (cdr match))
                    (list (cdr match) 'helm-mm-3-migemo-match)
                  (append (cdr match) (list 'helm-mm-3-migemo-match)))))
      (unless migemo
        (nconc source (list '(migemo))))))
  source)
```

The function is used like the following.

``` emacs-lisp
;; Setting for helm-mini with migemo
(require 'helm-files)
(require 'helm-buffers)
(unless helm-source-buffers-list
  (setq helm-source-buffers-list
        (helm-make-source "Buffers" 'helm-source-buffers)))
(dolist (s helm-mini-default-sources)
  (helm-migemo-migemize-sorce s))
```

Thank you.

P.S. Sorry for the delayed response. It took me some time to dig it.

**Comment by thierryvolpiatto** [comment]
momomo5717 <notifications@github.com> writes:

> Thank you for the migemo support! It is a big help for migemo users.
>
> I'd like to use helm-mini with migemo.
> Could a function like the following be added to use predefined sources with migemo?

No this will not work.
It is working because you still have a helm-migemo.el somewhere, now
things are different, it's much simpler to enable:

;; for buffers
(defmethod helm-setup-user-source ((source helm-source-buffers))
  (set-slot-value source 'migemo t))

;; for recentf
(defmethod helm-setup-user-source ((source helm-recentf-source))
  (set-slot-value source 'migemo t))

This is to add in your init file.
Depending which sources you use, this may not work if the source have
not its own class, let me know in this case.

OTOH If you tell me which sources are safe for use with migemo, 
I could add the migemo slot into them.
(It's hard for me to have examples files/buffers/etc... to test)

Thanks.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by thierryvolpiatto** [comment]
Thierry Volpiatto <thierry.volpiatto@gmail.com> writes:

> No this will not work.
> It is working because you still have a helm-migemo.el somewhere, now
> things are different, it's much simpler to enable:
>
> ;; for buffers
> (defmethod helm-setup-user-source ((source helm-source-buffers))
>   (set-slot-value source 'migemo t))
>
> ;; for recentf
> (defmethod helm-setup-user-source ((source helm-recentf-source))
>   (set-slot-value source 'migemo t))

This wont work too, here is what to use:

(defmethod helm-setup-user-source ((source helm-source-buffers))
  (set-slot-value source 'candidate-number-limit 200)
  (set-slot-value source 'migemo t)
  (set-slot-value source 'match
                  (helm-source-mm-get-search-or-match-fns source 'match)))

(defmethod helm-setup-user-source ((source helm-recentf-source))
  (set-slot-value source 'migemo t)
  (set-slot-value source 'match
                  (helm-source-mm-get-search-or-match-fns source 'match)))

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by thierryvolpiatto** [comment]
I have added migemo to buffers source and recentf, let me know other candidates for migemo.

**Comment by momomo5717** [comment]
Wow! `helm-mini` works fine. Thank you!

> I have added migemo to buffers source and recentf, let me know other candidates for migemo.

Now, I'd like to use the following finctions with migemo:
- helm-bookmarks
- helm-find-file

Thank you.

**Comment by momomo5717** [comment]
I tried `helm-find-file` by adding `helm-mm-3-migemo-match` to `helm-source-find-files`.
It seems one space after the current path  would be needed to get candidates via migemo,
but otherwise it works fine.

**Comment by thierryvolpiatto** [comment]
momomo5717 <notifications@github.com> writes:

> I tried helm-find-file by adding helm-mm-3-migemo-match to helm-source-find-files.
> It seems one space after the current path would be needed to get candidates via migemo,
> but otherwise it works fine.

Not sure it will fully works like this, I will have a look soon, same
for buffers list, it is only partially working (only simple regexp
matching against buffer name, as soon as we mix major-mode filter or
others it stops working).

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
momomo5717 <notifications@github.com> writes:

> Wow! helm-mini works fine. Thank you!
>
>     I have added migemo to buffers source and recentf, let me know other candidates for migemo.
>    
> Now, I'd like to use the following finctions with migemo:
>
>   * helm-bookmarks

Should work easily.

>   * helm-find-file

Perhaps needs some more work.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
I have added support for HFF, unfortunately we loose fuzzy matching for now when helm-migemo-mode is enabled, I think I can fix this soon to have the best of both worlds.

**Comment by momomo5717** [comment]
> I have added support for HFF, unfortunately we loose fuzzy matching for now when helm-migemo-mode is enabled, I think I can fix this soon to have the best of both worlds.

Thank you for adding it!
I'm happy with just using helm functions via migemo.

There is another problem.
When a regular expression (e.g. `.lisp$`) is included in a pattern. Matching doesn't work.
I suppose `(concat pattern "\\|" (migemo-get-pattern pattern))` would be needed in `helm-mm-migemo-string-match`.

Thank you.

**Comment by thierryvolpiatto** [comment]
momomo5717 <notifications@github.com> writes:

> There is another problem.
> When a regular expression (e.g. .lisp$) is included in a pattern. Matching doesn't work.
> I suppose (concat pattern "\\|" (migemo-get-pattern pattern)) would be
> needed in helm-mm-migemo-string-match.

That make sense, will use something like this.

Thanks.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by thierryvolpiatto** [comment]
Migemo state:

- kill-ring => OK
- occur    => OK
- buffers  => OK (even with filters e.g *lisp foo)
- HFF      => Partially (only regexp matching, no fuzzy as now)
- recentf  => OK
- minibuffer history => Untested, should work though.

Think that's all, tell me if I forget some.

**Comment by thierryvolpiatto** [comment]
Argh! forget bookmarks, it works as well, filtered bookmarks too.

**Comment by momomo5717** [comment]
Thank you for the implementation!

> Think that's all, tell me if I forget some.

It's perfect!

Helm minibuffer histroy works fine.

It seems helm bookmarks does't work with regexp.
I suppose it's from `migemo-forward` because migemo is used like `regexp-quote`.
So we would need a new function like the following.

```emacs-lisp
(declare-function migemo-search-pattern-get "ext:migemo.el")

(defun helm-migemo-forward (word &optional bound noerror count)
  (re-search-forward
   (if (delq 'ascii (find-charset-string word)) word
     (concat (migemo-search-pattern-get word) "\\|" word))
   bound noerror count))

(defun helm-mm-3-migemo-search (pattern &rest _ignore)
  (and helm-migemo-mode
       (helm-mm-3-search-base pattern 'helm-migemo-forward 'helm-migemo-forward)))
```

And sorry, now I think (concat (cdr helm-mm--previous-migemo-info) "\\|" pattern) could be better in `helm-mm-migemo-string-match`,
because if a string has the pattern and characters which can be matched by migemo, 
I suppose migemo users expects `helm-migemo-mode` gives priority to the latter.
Sorry if my interpretation is mistaken.


Thank you.

**Comment by thierryvolpiatto** [comment]
momomo5717 <notifications@github.com> writes:

> Thank you for the implementation!
>
>     Think that's all, tell me if I forget some.
>    
> It's perfect!
>
> Helm minibuffer histroy works fine.
>
> It seems helm bookmarks does't work with regexp.
> I suppose it's from migemo-forward because migemo is used like regexp-quote.
> So we would need a new function like the following.
>
> (declare-function migemo-search-pattern-get "ext:migemo.el")
>
> (defun helm-migemo-forward (word &optional bound noerror count)
>   (re-search-forward
>    (if (delq 'ascii (find-charset-string word)) word
>      (concat (migemo-search-pattern-get word) "\\|" word))
>    bound noerror count))
>
> (defun helm-mm-3-migemo-search (pattern &rest _ignore)
>   (and helm-migemo-mode
>        (helm-mm-3-search-base pattern 'helm-migemo-forward 'helm-migemo-forward)))

Ok I will look into this tonight, (I forget to push changes that
implement some of the features described in previous posts :-().

> And sorry, now I think (concat (cdr helm-mm--previous-migemo-info)
> "\|" pattern) could be better in helm-mm-migemo-string-match, because
> if a string has the pattern and characters which can be matched by
> migemo, I suppose migemo users expects helm-migemo-mode gives priority
> to the latter.  Sorry if my interpretation is mistaken.

Make sense, same I will modify this tonight.

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by momomo5717** [comment]
Thank you for the reply.

>Ok I will look into this tonight, (I forget to push changes that
>implement some of the features described in previous posts :-().

I'm really looking forward to having the best of both worlds.

Thank you.

**Comment by thierryvolpiatto** [comment]
Ok, I pushed the missing commit and I have also applied your changes (couldn't commit with your name because I couldn't get your email address).

Thanks!

**Comment by thierryvolpiatto** [comment]
So now the only thing missing is helm-find-files fully working:
- regexp matching like actually with migemo.
- fuzzy matching like when migemo-mode is disabled.

Of course with what we have actually, one can bind a key in helm-map to turn off migemo-mode
and continue fuzzy matching everything else, but it would be nice to match both even in migemo-mode.

Also what is missing (but not urgent IMO) is highlighting migemo matches.

**Comment by momomo5717** [comment]
>Ok, I pushed the missing commit and I have also applied your changes (couldn't commit with your name because I couldn't get your email address).

Thank you for using it and the message!

There is a typo (missing `-mm-`) at the last argument of `helm-mm-3-search-base` in `helm-mm-3-migemo-search`.

It works fine.

>So now the only thing missing is helm-find-files fully working:
> 
>regexp matching like actually with migemo.
>fuzzy matching like when migemo-mode is disabled.
>Of course with what we have actually, one can bind a key in helm-map to turn off migemo-mode
>and continue fuzzy matching everything else, but it would be nice to match both even in migemo-mode.

Migemo users will probably understand and toggling migemo-mode is easy to use. 
I'm looking forward to matching both.

>Also what is missing (but not urgent IMO) is highlighting migemo matches.

I think so too. I'm glad with just using helm with migemo.

Thank you.

**Comment by thierryvolpiatto** [comment]
momomo5717 <notifications@github.com> writes:

> There is a typo (missing -mm-) at the last argument of
> helm-mm-3-search-base in helm-mm-3-migemo-search.

Thanks, fixed.

> I'm looking forward to matching both.

Hope I will find a solution soon.

Also I have added migemo to *-file-name-history (C-c h in HFF).

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by thierryvolpiatto** [comment]
momomo5717 <notifications@github.com> writes:

> Migemo users will probably understand and toggling migemo-mode is easy to use.
> I'm looking forward to matching both.

For now I have removed automatic addition of space in hff when
migemo-mode is enabled.
This allow continuing matching fuzzy, and when needed, migemo user can
enter a space to match with migemo.
I will keep this until I find something better.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by momomo5717** [comment]
>Also I have added migemo to *-file-name-history (C-c h in HFF).

Oh, I didn't know about this command. It's very useful.
I tried it and it works too. I will use it heavily.


>For now I have removed automatic addition of space in hff when
>migemo-mode is enabled.
>This allow continuing matching fuzzy, and when needed, migemo user can
>enter a space to match with migemo.
>I will keep this until I find something better.

Now I think it would be better too.

Thank you for your consideration.

If something happens, I would report it.

Thank you.

**Comment by thierryvolpiatto** [comment]
See PR #1184 for highlighting migemo matches.

Thanks.

**Comment by momomo5717** [comment]
>> I suppose it would be helpful if there are some doc to extend plug-in
>> with migemo. e.g. helm-source-sync can be used with migemo. (Sorry if
>> my interpretation is mistaken.)
> 
>Will add soon some examples in wiki.

Thank you for your consideration.

I tried modifing helm-elscreen for migemo.
and added helm-elscreen-history.

helm-elscreen-history is used for going to another screen which was selected recently,
so its candidates in history order doesn't include the current screen.

I'll link it to this issue #1175.

I suppose it could be a simple example for migemo.

Thank you.

**Comment by thierryvolpiatto** [comment]
momomo5717 <notifications@github.com> writes:

> I tried modifing helm-elscreen for migemo.
> and added helm-elscreen-history.
>
> helm-elscreen-history is used for going to another screen which was selected recently,
> so its candidates in history order doesn't include the current screen.
>
> I'll link it to this issue #1175.
>
> I suppose it could be a simple example for migemo.

Thanks, looking forward for your PR.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by momomo5717** [comment]
I found migemo returns a invalid regex when a pattern including a regex (e.g. "[abc]") is inputted.
So I suppose it would be better to ignore the migemo's invalid regex.

Could the following code be added for replacing `migemo-get-pattern`/`migemo-search-pattern-get`
in `helm-mm-migemo-string-match`/`helm-mm-migemo-forward`?

```emacs-lisp
(defun helm-mm-migemo-get-pattern (pattern)
  (let ((regex (migemo-get-pattern pattern)))
    (if (ignore-errors (string-match regex "") t)
        (concat regex "\\|" pattern) pattern)))

(defun helm-mm-migemo-search-pattern-get (pattern)
  (let ((regex (migemo-search-pattern-get pattern)))
    (if (ignore-errors (string-match regex "") t)
        (concat regex "\\|" pattern) pattern)))
```

If so, I'd like to send the PR.

Thank you.

**Comment by thierryvolpiatto** [comment]
momomo5717 <notifications@github.com> writes:

> Could the following code be added for replacing
> migemo-get-pattern/migemo-search-pattern-get
> in helm-mm-migemo-string-match/helm-mm-migemo-forward?

Yes definitely, go ahead, send the PR, I will merge.

Thanks.

-- 
Thierry
https://emacs-helm.github.io/helm/
