### ISSUE TITLE
Cannot tell helm-find-files to ignore something that looks like a filename at point

### ISSUE THREAD

**Issue by mikecrowe** [emacs-helm/helm#1178]
I bind helm-find-files to C-x C-f since I generally prefer to use it when opening files. However, when I decide to open a file it usually has nothing to do with something that might look a bit like a filename at point.

I'd prefer it if I could tell helm-find-files to never consult ffap when opening a file. There doesn't appear to be a way to do that.

Issue #870 and the associated emacs.stackexchange question seem to be requesting this but the issue was closed.

**Comment by mikecrowe** [comment]
Thanks for looking at this.

Perhaps I'm doing something wrong but this doesn't appeared to have fixed the problem for me. The default value of helm-ff-guess-ffap-filenames appears to be nil, yet if my point is within something that looks like a filename then helm-find-files still offers that filename.

I barely understand what helm-find-files-initial-input is doing, but https://github.com/emacs-helm/helm/commit/3617c687603781a50d59c763f98b071ce999ad05 looks like it disables ffap yet leaves thing-at-point operational. If this is true, is there a way to disable using thing-at-point too?

**Comment by thierryvolpiatto** [comment]
Mike Crowe <notifications@github.com> writes:

> Thanks for looking at this.
>
> Perhaps I'm doing something wrong but this doesn't appeared to have
> fixed the problem for me. The default value of
> helm-ff-guess-ffap-filenames appears to be nil, yet if my point is
> within something that looks like a filename then helm-find-files still
> offers that filename.

If it is a valid filename yes it is used as default-input, this is
wanted and will not be disabled, it is useful for filename completion,
urls etc...
What `helm-ff-guess-ffap-filenames' disable when nil is the nasty effect
of ffap for example when cursor is on an autoload cookie.

> I barely understand what helm-find-files-initial-input is doing, but
> 3617c68 looks like it disables ffap yet leaves thing-at-point
> operational. If this is true, is there a way to disable using
> thing-at-point too?

No, it would break other things, see above.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by mikecrowe** [comment]
I have no doubt that it is a desired behaviour for some, but I find it annoying when using helm-find-file as a much-improved replacement for find-file.

**Comment by michael-heerdegen** [comment]
I don't like the default behavior too, but we have to live with it.  It is better if not everyone is pleased than blowing up everything with tons of variables.  Such code soon gets harder to  maintain, that's why Thierry is reluctant with adding options.

Anyway, just add /./ to "clear" the unwanted default minibuffer input.

**Comment by mikecrowe** [comment]
It appears that this was fixed as issue 1563 by the addition of helm-find-file-ignore-thing-at-point in 1ae230e5fa8dbbdbb4ed49b484f53b5d8c427c0b.
