### ISSUE TITLE
Proper way to start a helm session as an action of some other helm session

### ISSUE THREAD

**Issue by iqbalansari** [emacs-helm/helm#1179]
Thank you very much for this awesome package. 

I have just started using helm so the terms used in the title might not be accurate. I was trying to solve [emacs-helm/helm-mu#4](https://github.com/emacs-helm/helm-mu/issues/4). The idea is to add an action to source `helm-mu-contacts` which starts the source `helm-mu` with search string let bound to appropriate query constructed from the selected candidates. 

I managed to get it [working](https://github.com/iqbalansari/helm-mu/blob/7db272764d56e7b879f549dda19f833b66ca7b1f/helm-mu.el#L373-L391), except for when I hit `RET` in the `helm-mu` session launched from the action in `helm-mu-contacts` the action from `helm-mu-contacts` is executed instead of the one from `helm-mu`. This happens only if `helm-mu` was started from the action buffer of `helm-mu-contacts`. 

On some digging I found out that [`helm-execute-selection-action-1`](https://github.com/emacs-helm/helm/blob/a9a053a64a5d284dba6504a81fce2747a119c5f5/helm.el#L3610-L3611) uses existing action buffer to get the action to execute and since the action buffer from `helm-mu-contacts` was still around it was used leading to the error. 

I can [workaround](https://github.com/iqbalansari/helm-mu/blob/7db272764d56e7b879f549dda19f833b66ca7b1f/helm-mu.el#L423-L424) the above by explicitly killing the action buffer (if present) in `helm-mu`. I was wondering whether this recommended way to achieve what I want or if I am doing something wrong. Any guidance would be appreciated.

**Comment by michael-heerdegen** [comment]
I didn't look at the links.  But it seems that `helm-exit-and-execute-action' might be appropriate (to officially end the old Helm session and replace it with the new one).  See the helm-ff-run-* functions for example; I guess your use case is similar.

**Comment by iqbalansari** [comment]
@michael-heerdegen Thanks for your help. But looking at the documentation of `helm-exit-and-execute-action` it seems that it would only work for helm actions, I want to invoke `helm-mu` which is an a different helm source altogether.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> I didn't look at the links. But it seems that
> `helm-exit-and-execute-action' might be appropriate (to officially end
> the old Helm session and replace it with the new one). See the
> helm-ff-run-* functions for example; I guess your use case is similar.

He do not need this for an action (an action is a function that is
called from the action menu), `helm-exit-and-execute-action' is more
when you want to create a wrapper function bound to a key 
that call this action.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by michael-heerdegen** [comment]
Yes, I see.  And I see too that in the Helm sources in similar situations, we call

```
    (kill-buffer helm-action-buffer)
```

as well, so what @iqbalansari suggests seems to be right.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Yes, I see. And I see too that in the Helm sources in similar situations, we call
>
>     (kill-buffer helm-action-buffer)
>
> as well, so what @iqbalansari suggests seems to be right.

No he don't need to kill action buffer.

-- 
Thierry
https://emacs-helm.github.io/helm/
