### ISSUE TITLE
helm-insert-match: Attempt to modify read-only object errors

### ISSUE THREAD

**Issue by Szunti** [emacs-helm/helm#1180]
I am a newbie, so sorry if I can't give the most useful infos.

After installing spacemacs I got a lot of these errors.
eg. SPC-f-e-h gives:
helm-insert-match: Attempt to modify read-only object: "colors"

@TheBB found that the commit 85946e0 cause them.

**Comment by thierryvolpiatto** [comment]
I have no errors here and I don't use spacemacs and/or evil.
Please report such problems to spacemacs.

**Comment by TheBB** [comment]
> Please report such problems to spacemacs.

Where do you think we come from?

This reproduces the problem for me, on `emacs -Q`, Emacs version 24.5.1, latest Helm master (`85946e0f0913e3405c36f87443595faf77484e87`).

```lisp
(require 'helm)
(helm :buffer "doot"
      :sources '(((name . "Layers")
                  (candidates chinese)
                  (candidates-number-limimt))))
```

Note: It has to be *chinese*. Only this and a few other symbols trigger the bug.

**Comment by TheBB** [comment]
Other symbols triggering this bug include: colors, d, dash, elm, emacs-lisp, erc, games, gnus, html, ibuffer, java, python, rcirc, semantic, shell, sql and version-control

**Comment by thierryvolpiatto** [comment]
Eivind Fonn <notifications@github.com> writes:

> Where do you think we come from?

Spacemacs, no doubt, people there are very nervous generally.

> This reproduces the problem for me, on emacs -Q, Emacs version 24.5.1,
> latest Helm master (85946e0f0913e3405c36f87443595faf77484e87).
>
> (require 'helm)
> (helm :buffer "doot"
>       :sources '(((name . "Layers")
>                   (candidates chinese)
>                   (candidates-number-limimt))))

You example is bad, but after a quick look I see I forget to remove an
unneeded line I have added when fixing #1176.
This is fixed now.

Thanks.

-- 
Thierry
https://emacs-helm.github.io/helm/
