### ISSUE TITLE
Scoring oddities in helm-find-files

### ISSUE THREAD

**Issue by hmelman** [emacs-helm/helm#1182]
I'm not understanding how scoring works in helm-find-files. I'm having an issue when I start emacs and use helm-find-files in my $HOME. I want to open a file in my elisp directory, so I start typing elisp. It's the only item in the directory that begins with "e". There are other items but here's the top of what helm shows me as I type:

  Matching "e"

  News
  Sites
  elisp
  .Xcode
  .emacs
  .netrc
  Movies
  .eshell

  Matching "el"

  helm.el
  helm-help.el
  elisp
  .eshell

  Matching "eli"

  elisp

I don't understand why News and Sites are higher than elisp after just "e" is entered. After "el" I guess I see that both .el files have "el" in their name more than once but I still think a pattern matching exactly the beginning of a pattern should have a higher score (I'm fine if that's a scoring option that I'd need to tweak myself).

I tried tracking this down but got a little confused. 

I played with helm-score-candidate-for-pattern adding a 50 bonus for 

    (string-match (concat "\\<" (regexp-quote pattern)) cand) 

but that didn't quite work. With input of just "e" elisp moved to the top, but with input of "el" it moved down to third (same as above).

An explanation or a little guidance to point me to places in the code would help.

**Comment by thierryvolpiatto** [comment]
Howard Melman <notifications@github.com> writes:

> I don't understand why News and Sites are higher than elisp after just
> "e" is entered. After "el" I guess I see that both .el files have "el"
> in their name more than once but I still think a pattern matching
> exactly the beginning of a pattern should have a higher score (I'm
> fine if that's a scoring option that I'd need to tweak myself).

Fuzzy matching and sorting start at third char entered.
Before helm is just sorting alpha.

When you want "elisp" you don't have to type "elisp", just type
"elp" or "elsp" for example.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by hmelman** [comment]
I don't believe I'm using fuzzy matching here (helm-mode-fuzzy-match is nil). As I pointed out, I know that "eli" would work for me (and would to me make more sense than typing elp or elsp but I get that that's personal choice). It seems to me, in this case "e" should work, I understand that you might not think so.

But I'm looking for ways for me to customize helm to enable this. Is writing my own scoring function the right place to plug this in? There isn't a user option to plugin my own helm-score-candidate-for-pattern, maybe that would be a good addition? If not, how else should I plug in something in a clean manner?

**Comment by thierryvolpiatto** [comment]
Howard Melman <notifications@github.com> writes:

> I don't believe I'm using fuzzy matching here (helm-mode-fuzzy-match
> is nil).

Yes you are using fuzzy in helm-find-files, it have nothing to do with
helm-mode-fuzzy-match.


> As I pointed out, I know that "eli" would work for me (and would to me
> make more sense than typing elp or elsp but I get that that's personal
> choice). It seems to me, in this case "e" should work, I understand
> that you might not think so.

You should get used to this it is really powerfull when you get used to
it.
Use also helm-ff-auto-update-initial-value set to t.

> But I'm looking for ways for me to customize helm to enable this. Is
> writing my own scoring function the right place to plug this in?

No, the default is using a fuzzy scoring function because
helm-find-files is fuzzy matching

> There isn't a user option to plugin my own
> helm-score-candidate-for-pattern, maybe that would be a good addition?

No, fuzzy is quite complex and I don't want this.

> If not, how else should I plug in something in a clean manner?

You can write your own sort function and add it to hff like this
in your init file:

(defmethod helm-setup-user-source ((source helm-source-ffiles))
  (set-slot-value source 'filtered-candidates-transformer
                  '(fn1 fn2 etc...)))

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by hmelman** [comment]
> Yes you are using fuzzy in helm-find-files, it have nothing to do with helm-mode-fuzzy-match.

> You should get used to this it is really powerfull when you get used to it. Use also helm-ff-auto-update-initial-value set to t.

All right, I will play with these to try to get used to them. I will also read through the ff fuzzy code to better understand it.

I've been using helm for a few months and I make use of multiple patterns to match file names (e.g. "hrm he" to match all my hrm-*.el files in a directory and then the hrm-helm-*.el ones). Works great. I know that "hrmhe" would work too but prefer the space since it eliminates some other matches I'm not interested in. I also know that "hh" would match these files pretty well too (based on first letter of words).

Can you perhaps describe what part of fuzzy I'm not getting? I get how "elp" would work in my example, I don't see why matching "News" over "elisp" when typing just "e" is better. I suspect my brain will always think of words from their beginning and not their middle.

**Comment by thierryvolpiatto** [comment]
Howard Melman <notifications@github.com> writes:

> I've been using helm for a few months and I make use of multiple
> patterns to match file names (e.g. "hrm he" to match all my hrm-.el
> files in a directory and then the hrm-helm-.el ones). Works great. I
> know that "hrmhe" would work too but prefer the space since it
> eliminates some other matches I'm not interested in. I also know that
> "hh" would match these files pretty well too (based on first letter of
> words).

Why not using just "helm" or "hlm" here, you don't need the prefix
"hrm-" (assuming all files in this dir are prefixed by "hrm-")

> Can you perhaps describe what part of fuzzy I'm not getting? I get how
> "elp" would work in my example, I don't see why matching "News" over
> "elisp" when typing just "e" is better.

Fuzzy is kicking in at third char entered, so when you type "e" helm is
just sorting alphabeticaly (it is why you see upcased words first) 
waiting some more chars to complete better.

> I suspect my brain will always think of words from their beginning and
> not their middle.

maybe it is the same for everybody, yes, but some words contains
separators (e.g "-") like "hrm-helm", so it it is easy to think just
"helm" IMO.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by hmelman** [comment]
FYI, here's another example from the helm source tree. I wanted to open helm-files.el so knowing that the files begin with "helm-" I started typing "files" until it matched. But unfortunately, Makefile stayed at the top of the list until I typed all of "files". I know I could have seen those two at the top and jumped to typing "fs", but that process seemed slower than just continuing to type what I knew to be a substring of the file I wanted. In my view, the scoring of helm-files.el should be higher because "files" is proceeded by a non-word character.

**Comment by hmelman** [comment]
> Why not using just "helm" or "hlm" here, you don't need the prefix
"hrm-" (assuming all files in this dir are prefixed by "hrm-")

All the files were not prefixed with "hrm-", which I why I used it :)

> Fuzzy is kicking in at third char entered, so when you type "e" helm is
just sorting alphabeticaly (it is why you see upcased words first)
waiting some more chars to complete better.

Thanks, that makes sense. I'm guessing for the first two characters you're just using alphabetical on any name that matches the characters anywhere for speed (on the assumption that one character will rarely be enough). Still giving precedence to substring matches from the beginning of the string (or subwords in the case of separators) seems like a worthwhile thing to do here IMHO.

**Comment by thierryvolpiatto** [comment]
In this case you would not match "helm" in "hrm-helm" (i.e in the 2 first chars helm is matching ".*he" instead of "he" so there is no prefix match).
Also you can completely disable fuzzy matching in `helm-find-files` with `helm-ff-fuzzy-matching`.
Closing now, let me know if you have some more problems.

**Comment by hmelman** [comment]
Thanks, closing this is fine. I've been reading through helm-files.el and helm.el but while I've been writing elisp for 30 years, I'm new to eieio and am having problems following a lot of what's going on. I've started looking through eieio.info but do really wish helm had a little more developer documentation :)

What's the best way to ask questions about things? I have questions about sources and pattern matching and a few other things. Open issues here? Stack Exchange? gmame.emacs.helm.user? I've started writing a helm overview for new users so I'm trying to help the situation :)

**Comment by thierryvolpiatto** [comment]
Howard Melman <notifications@github.com> writes:

> Thanks, closing this is fine. I've been reading through helm-files.el
> and helm.el but while I've been writing elisp for 30 years, I'm new to
> eieio and am having problems following a lot of what's going on. I've
> started looking through eieio.info but do really wish helm had a
> little more developer documentation :)

Yes, I have started something on the wiki, but I didn't find the time to
continue.

> What's the best way to ask questions about things?

Our mailing list is fine, accessible through gmane yes or directly
suscribe on google list. 

> I have questions about sources and pattern matching and a few other
> things. Open issues here? Stack Exchange?  gmame.emacs.helm.user? I've
> started writing a helm overview for new users so I'm trying to help
> the situation :)

Great, thanks.

-- 
Thierry
https://emacs-helm.github.io/helm/
