### ISSUE TITLE
Bitcoin address to donate

### ISSUE THREAD

**Issue by msx** [emacs-helm/helm#1183]
I would love to donate, however because the conditions in the 'place' I live in I would prefer to not do so using my CC.
If you guys have a cryptowallet to which I could donate please let me know.

Helm <3

**Comment by thierryvolpiatto** [comment]
Thanks for supporting helm.
I am not easy with bitcoins and have no address to give you apart the paypal one unfortunately.

**Comment by thierryvolpiatto** [comment]
Thanks anyway for the intention ;-)
Closing now.
