### ISSUE TITLE
`helm-output-filter--collect-candidates` does not properly collect more than two chunks of output

### ISSUE THREAD

**Issue by iqbalansari** [emacs-helm/helm#1187]
If a process produces large enough output such that one line arrives in more than 2 chunks only the last two chunks are concatenated all previous chunks are lost. 

**Steps to reproduce**

The error can be reproduced by creating a helm source for a program outputting a large amount of text in one single line, one such example is posted [here](https://gist.github.com/iqbalansari/8e1cabd2144f0adc14b0).

The following is the helm source (this is just for illustrating the bug) for the program above, it simply inserts the process output passed to the transformer in the helm-buffer

```emacs-lisp

(defun helm-large-output-transformer (candidates)
  (with-current-buffer "*helm large output*"
    (insert "\n\n--- *** ---\n\n") (insert (prin1-to-string candidates))))

(defun helm-large-output-init ()
  "Initialize async mu process for `helm-source-mu'."
  (let ((process-connection-type nil))
    (start-process-shell-command "helm-mu" helm-buffer
                                 "sh large_output.sh")))

(defvar helm-large-output-source
  (helm-build-async-source "Testing helm"
    :candidates-process #'helm-large-output-init
    :candidate-transformer
    '(helm-large-output-transformer)
    :delayed t))

(helm :sources 'helm-large-output-source
      :buffer "*helm large output*")
```

On running the above you will see that only a part of the output produces by the process is passed to the `helm-large-output-transformer`. The expected result is that entire output of the process is passed to `helm-large-output-transformer`.

**Possible cause**

On some investigation it seems that the problem is on [this line](https://github.com/emacs-helm/helm/blob/3691ae9bcc52e3cbaf2aa43692388bf1284bf4dc/helm.el#L3541). Perhaps `incomplete-line-info` should be set to the value of `newline` (concatenation of last incomplete chunk and current chunk), since the current chunk might also be incomplete and would need to concatenated with later chunk(s) to get complete process response

**Comment by thierryvolpiatto** [comment]
Iqbal Ansari <notifications@github.com> writes:

> If a process produces large enough output such that one line arrives
> in more than 2 chunks only the last two chunks are concatenated all
> previous chunks are lost.

Indeed, we lived with this until now because it is rare to have such
situation.

> On some investigation it seems that the problem lies in this line. It
> seems incomplete-line-info should be set to the value of newline
> (concatenation of last incomplete output and current, potentially
> incomplete, output), since the current chunk might also be incomplete
> and would need to concatenated with later chunk to get complete
> process response

Yes this makes sense, I have applied this change.

Thanks.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by iqbalansari** [comment]
@thierryvolpiatto Thanks for the fix. I confirm that it works.
