### ISSUE TITLE
On Emacs 25, the helm-sexp-eval def for old Emacs versions is used

### ISSUE THREAD

**Issue by michael-heerdegen** [emacs-helm/helm#1188]
because on my machine, (helm-btf--usable-p) returns nil.  backtrace-frame does accept two arguments, though, so our test is bad.

I suggest to change the definition to
```
(defun helm-btf--usable-p ()
  "Return t if current version of `backtrace-frame' accept 2 arguments."
  (condition-case nil
      (progn (backtrace-frame 1 'condition-case) t)
    (wrong-number-of-arguments nil)))
```

Regards,

Michael.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> because on my machine, (helm-btf--usable-p) returns nil. backtrace-frame does accept two arguments, though, so our test is bad.
>
> I suggest to change the definition to
>
> (defun helm-btf--usable-p ()
>   "Return t if current version of `backtrace-frame' accept 2 arguments."
>   (condition-case nil
>       (progn (backtrace-frame 1 'condition-case) t)
>     (wrong-number-of-arguments nil)))

Please apply.

Thanks.

-- 
Thierry
https://emacs-helm.github.io/helm/
