### ISSUE TITLE
helm-M-x can't start

### ISSUE THREAD

**Issue by shenhai-ran** [emacs-helm/helm#1189]
helm-mode works fine with original M-x command, so I do have "helm-mode-execute-extended-command" function.
but if I call helm-M-x or bind it to any key, I got this:
"if: Symbol's value as variable is void: it" and can't start helm-M-x

I used Emacs 24.4.1 on Mac OS and installed helm from melpa-stable (1.7.9)
only put 
(require 'helm-config)
(helm-mode 1)
in init file.

I am new to emacs and no clue what extra message you will need. Thanks a lot.

**Comment by thierryvolpiatto** [comment]
Shenhai Ran <notifications@github.com> writes:

> helm-mode works fine with original M-x command, so I do have "helm-mode-execute-extended-command" function.
> but if I call helm-M-x or bind it to any key, I got this:
> "if: Symbol's value as variable is void: it" and can't start helm-M-x
>
> I used Emacs 24.4.1 on Mac OS and installed helm from melpa-stable (1.7.9)
> only put
> (require 'helm-config)
> (helm-mode 1)
> in init file.

Please read the README file carefully, you have to call
`package-initialize' first in your init file.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by shenhai-ran** [comment]
Thanks for your reply.
I did put 'package-initalizei' in the init file. Actually I read everything I can find.
```lisp
require 'package)
(add-to-list 'package-archives
             '("melpa-stable" . "https://stable.melpa.org/packages/"))
(package-initialize)

(require 'helm-config)
(helm-mode 1)
```
Nothing else and helm was installed. The problem is everything in Helm works so far, including "Helm-Find-Files", "Helm-Buffer-list"... ,even helm complete in original M-X; except "Helm-M-x"

I tried once on Mint, same config file, It works, so I guess it has to be related to my Mac OS?

**Comment by thierryvolpiatto** [comment]
Shenhai Ran <notifications@github.com> writes:

> Thanks for your reply.
> I did put 'package-initalizei' in the init file. Actually I read everything I can find.
>
> require 'package)
> (add-to-list 'package-archives
>              '("melpa-stable" . "https://stable.melpa.org/packages/"))
> (package-initialize)
>
> (require 'helm-config)
> (helm-mode 1)
>
> Nothing else and helm was installed. The problem is everything in Helm works so far, including "Helm-Find-Files", "Helm-Buffer-list"... ,even helm complete in
> original M-X; except "Helm-M-x"
>
> I tried once on Mint, same config file, It works, so I guess it has to be related to my Mac OS?

Try from a terminal:

    cd /your/helm/directory
    ./emacs-helm.sh

Then from there just do M-x and see if it works.

NOTE: Generally MacOs users have to give explicitely the path to their
emacs to emacs-helm.sh, do this with the "-P" option:

    ./emacs-helm.sh -P /path/to/your/emacs

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by shenhai-ran** [comment]
Thanks for your reply!

I try with the emacs-helm.sh. It has the some problem. 
BTW, I overlooked something, at the start of emacs or from emacs-helm.sh
*ad-handle-definition: `tramp-read-passwd' got redefined*
can be found at the message buffer. Does it has anything to do with my problem?

**Comment by xuchunyang** [comment]
> BTW, I overlooked something, at the start of emacs or from emacs-helm.sh
> ad-handle-definition: `tramp-read-passwd' got redefined
> can be found at the message buffer. Does it has anything to do with my problem?

No, it is because helm redefines that function, while redefining function in package is discouraged by Emacs, so Emacs warns you about that, you `(setq ad-redefinition-action 'accept)` to silence it if you like.

**Comment by shenhai-ran** [comment]
@xuchunyang thanks, still can't figure out what's wrong with *helm-M-x*.
@thierryvolpiatto thanks as well anyway. Since it works fine on Mint, so I guess it has noting to do with the package itself nor my settings. Probably I should close the session and give up for a while.

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

>     BTW, I overlooked something, at the start of emacs or from emacs-helm.sh
>     ad-handle-definition: `tramp-read-passwd' got redefined
>     can be found at the message buffer. Does it has anything to do with my problem?
>    
> No, it is because helm redefines that function,

Not exactly.
helm _advice_ this function which is different and we have a warning
because we use defadvice for backward compatibility, once we will have
removed this defadvice, the warning should disapear (we keep it as long
as there is people using emacs-24.3 and inferiors).

> while redefining function in package is discouraged by Emacs,

Redefining probably, advicing is a common action on packages.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
This seems like an error related to `helm-aif', but I don't understand how such an error can be triggered, even with a broken installation.

If you have the time, can you send us a backtrace?

Do it like this:

1.  Load all helm source files (the .el files), e.g. mark them in dired (m) and hit L to load them.

2. M-: (setq debug-on-error t) RET

3. Trigger the bug (call helm-M-x).  This should pop up a backtrace buffer.  Please send us the output.

Thanks.

**Comment by shenhai-ran** [comment]
@michael-heerdegen definitely! I really would like to know what's going on there.

So I did what you said, and tried a bit more. Here is the situation:
* If I started a plain Emacs with basic helm config or use emacs.helm.sh (I guess they are similar) and mark all the *.el files in helm-\<version> and helm-core-\<version> folders, _helm-M-x_ works! After a bit trial, I found that if (I can't promise only if) I load the file _helm-source.el_  in the helm-core-\<version> fold. this happens.

* if I use my own emacs init files (I've loaded quite a few things), no matter how many *.el files I loaded, it doesn't work. Doesn't it mean some conflicts between packages?

* regarding the debug mode, it gives a lot messages, so I don't think you want me to put them here. If you are interested in them, I will send them by email, is that OK?

**Comment by shenhai-ran** [comment]
@michael-heerdegen, @thierryvolpiatto:  hey I figure it out, but still I don't understand it.

* I use CEDET package from the [homepage](http://cedet.sourceforge.net/setup.shtml) rather then the one bounded inside Emacs, so put
```Lisp
(load-file "~/cedet-1.1/common/cedet.el")
```
in my init file according to the setup. If I load cedet **ONLY AFTER** I put 
```Lisp
(load-file "path/to/helm-core-<version>/helm-source.el")
```
 helm-M-x starts to work.  But I have no clue whether it will influence cedet yet.

* still I don't understand why at the beginning and now if I don't load helm-source.el by myself, it doesn't work. On Mint I tried without install cedet package, it works. I guess when I started to use cedet for the first time, it created somethings which is in confliction with helm-M-x? Not sure.

Thanks! if you want the debug file or want to reproduce this wired thing, I can send you all my emacs settings, I am really wondering about it.

I PC from work is Windows platform with cedet already installed, I will try on that one later as well next week.
It has already eaten up my weekend :)

**Comment by thierryvolpiatto** [comment]
Shenhai Ran <notifications@github.com> writes:

>   * still I don't understand why at the beginning and now if I don't
>     load helm-source.el by myself, it doesn't work. On Mint I tried
>     without install cedet package, it works. I guess when I started to
>     use cedet for the first time, it created somethings which is in
>     confliction with helm-M-x?

Not with helm-M-x particularly I guess, but with helm-source which need
the eieio that comes with emacs.
I am not sure what your cdet version is doing, but perhaps it load some
incompatible eieio code?

This is just a thought, may be I am wrong...

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by michael-heerdegen** [comment]
Shenhai Ran <notifications@github.com> writes:

> * regarding the debug mode, it gives a lot messages, so I don't think
> you want me to put them here. If you are interested in them, I will
> send them by email, is that OK?

Yes, please do!  Just try to get a backtrace without byte code in it
(that's why you need to load all related .el sources).  Thanks!

**Comment by shenhai-ran** [comment]
@thierryvolpiatto 

>I am not sure what your cdet version is doing, but perhaps it load some
>incompatible eieio code?

I guess you are quite close. Now I load cedet after settings of helm, helm m x works but if I trigger the Emacs help Ctrl h, it gives the error:
_Autoloading failed to define fun eieio-help-coustructor_
Not sure about other side effect yet.

**Comment by michael-heerdegen** [comment]
I have a guess - can you please check if the following patch for helm-source.el fixes the original problem:

```

*** /tmp/ediff17684amM	2015-09-28 01:49:17.047197779 +0200
--- /home/micha/gnu-emacs/elisp/helm/helm-source.el	2015-09-28 01:48:13.627223499 +0200
***************
*** 907,916 ****
                   (and (null (eq 'helm-default-init-source-in-buffer-function
                                  cur-init))
                        cur-init)
!                  (lambda ()
!                    (helm-init-candidates-in-buffer
!                        'global
!                      (if (functionp it) (funcall it) it))))))))
    (when (slot-value source 'fuzzy-match)
      (helm-aif (slot-value source 'search)
          (set-slot-value source 'search (append (helm-mklist it)
--- 907,916 ----
                   (and (null (eq 'helm-default-init-source-in-buffer-function
                                  cur-init))
                        cur-init)
!                  `(lambda ()
!                     (helm-init-candidates-in-buffer
!                         'global
!                       (if (functionp ,it) (funcall ,it) ,it))))))))
    (when (slot-value source 'fuzzy-match)
      (helm-aif (slot-value source 'search)
          (set-slot-value source 'search (append (helm-mklist it)
```

**Comment by michael-heerdegen** [comment]
@thierryvolpiatto btw do we need to migrate to cl-defmethod?  defmethod is declared obsolete in 25.1.  cl-defmethod is a different thing, though.

**Comment by michael-heerdegen** [comment]
Oops, better use this:

```
*** /tmp/ediff31288_0n	2015-09-28 03:35:59.201423300 +0200
--- /home/micha/software/helm/helm-source.el	2015-09-28 03:34:23.709508374 +0200
***************
*** 907,916 ****
                   (and (null (eq 'helm-default-init-source-in-buffer-function
                                  cur-init))
                        cur-init)
!                  (lambda ()
!                    (helm-init-candidates-in-buffer
!                        'global
!                      (if (functionp it) (funcall it) it))))))))
    (when (slot-value source 'fuzzy-match)
      (helm-aif (slot-value source 'search)
          (set-slot-value source 'search (append (helm-mklist it)
--- 907,916 ----
                   (and (null (eq 'helm-default-init-source-in-buffer-function
                                  cur-init))
                        cur-init)
!                  `(lambda ()
!                     (helm-init-candidates-in-buffer
!                         'global
!                       (if (functionp ',it) (funcall #',it) ',it))))))))
    (when (slot-value source 'fuzzy-match)
      (helm-aif (slot-value source 'search)
          (set-slot-value source 'search (append (helm-mklist it)
```

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> @thierryvolpiatto btw do we need to migrate to cl-defmethod?

No.

    (fboundp 'cl-defmethod) => nil (emacs-24.5)

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> No.
>
> (fboundp 'cl-defmethod) => nil (emacs-24.5)

I don't mean we should do it now.  We will have to switch one day.
But it seems cl-defmethod is compatible with the old eieio version.
Just contemplating...

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Thierry Volpiatto <notifications@github.com> writes:
>
>> No.
>>
>> (fboundp 'cl-defmethod) => nil (emacs-24.5)
>
> I don't mean we should do it now. We will have to switch one day.

Yes sure, but it is not the time, we are actually trying to be
compatible with 24.3...

> But it seems cl-defmethod is compatible with the old eieio version.

Didn't try as I am rarely using emacs-25 nowaday, but yes it should work
with our code.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by michael-heerdegen** [comment]
@shenhai-ran About your current problem: I guess you can't use Helm with any CEDET loaded state.  You probably have to recompile the helm sources, and in particular, recreate the autoloads (loaddefs), for a sane environment, and afterwards, this built probably only works with that state of CEDET loaded or not.

**Comment by michael-heerdegen** [comment]
I have had a look at the CEDET homepage you cited, and downloaded its sources.  It seems the page is orphaned since 2011, and the code from there is similarly old.  This version of eieio's defmethod ignores lexical binding.  And that's the problem.

The method implementation for helm-source-in-buffer requires lexical binding.  And helm-M-x leads to a call to this method, which contains non-working code when this CEDET version is loaded.

Summa summarum, there is no bug in Helm.  Don't use that old CEDET version.

**Comment by shenhai-ran** [comment]
Great, you guys are awesome! I am new to helm and like it. So I will continue with helm and give up on old CEDET. Actually I only use Semantic to parse the code and the one inside Emacs is sufficient for me.

**Comment by michael-heerdegen** [comment]
Shenhai Ran <notifications@github.com> writes:

> Actually I only use Semantic to parse the code and the one inside
> Emacs is sufficient for me.

But why were you using this old version?  Out of purpose, or did you
think the version available there would be newer or have different
features?

I wonder why the page you cited has been orphaned for so long but is
still online.  If they don't update it anymore, or have a new homepage
now, it would be better to delete this old site, so that people don't
get confused about it.

Regards, Michael.

**Comment by tuhdo** [comment]
The new CEDET is merged in Emacs itself. The one on website is much older than the built-in CEDET in current Emacs 24.5. You can clone the git repo here:

```sh
git clone http://git.code.sf.net/p/cedet/git cedet
```
