### ISSUE TITLE
*terminal* does not appear in helm-mini list

### ISSUE THREAD

**Issue by tomasorti** [emacs-helm/helm#1191]
Hi!
When I tried to switch to buffer with `C-x b` which I have binded to `helm-mini`, I am not able to switch to a terminal buffer which I created with `M-x term`.  
The name of terminal buffer is __\*terminal\*__, but it does not appear listed.
Is there a way to achieve this?

**Comment by xuchunyang** [comment]
I can't reproduce, how did you switch to `*terminal*` buffer? (Note: key binding in term-mode is unusual)

**Comment by tomasorti** [comment]
I just started `emacs-helm.sh` and then:

  1. M-x term
  - RET (Run program: /bin/bash)
  - C-c C-j (Switches to line mode, that allows M-x, etc..)
  - C-x b sc RET (Switches to \*scratch* buffer)
  - C-x b te RET (Switches to \*terminal* buffer)

This works.
But for some reason in my personal config, step 5 does not show *terminal.
I'll have to review my `init.el`.

**Comment by thierryvolpiatto** [comment]
nephewtom <notifications@github.com> writes:

> But for some reason in my personal config, step 5 does not show *terminal.

What is the value of helm-boring-buffer-regexp-list ?

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tomasorti** [comment]
helm-boring-buffer-regexp-list is a variable defined in `helm-buffers.el'.
    Its value is ("\\` " "\\*helm" "\\*helm-mode" "\\*Echo Area" "\\*Minibuf")

I have opened one Emacs with `emacs-helm.sh` (left on attached image) and one with my personal conf (right on attached image). The value of `helm-boring-buffer-regexp-list` is the same on both.
The one with my personal conf sometimes does not show \*magit: myconf* buffer in `helm-buffers-list`.

It is the same that happened with \*terminal* before.
If I have the buffer visible (loaded in one frame), `helm-buffers-list` does list it.
How can I troubleshoot this? The helm stuff on my `init.el` is the following:

    (require 'helm)
    (require 'helm-config)
    (helm-mode 1)
    (helm-autoresize-mode t)
    (global-set-key (kbd "M-x") 'helm-M-x)
    (global-set-key (kbd "C-x C-b") 'helm-buffers-list)
    (global-set-key (kbd "C-x C-f") 'helm-find-files)
    (global-set-key (kbd "C-x b") 'helm-mini)

    (define-key helm-map (kbd "<tab>") 'helm-execute-persistent-action)
![helm-magit-buffers](https://cloud.githubusercontent.com/assets/2485147/10169228/704a5928-66d0-11e5-9bc3-6afc1731a7f6.png)

**Comment by thierryvolpiatto** [comment]
nephewtom <notifications@github.com> writes:

> helm-boring-buffer-regexp-list is a variable defined in `helm-buffers.el'.
> Its value is ("\\` " "\\*helm" "\\*helm-mode" "\\*Echo Area" "\\*Minibuf")
>
> I have opened one Emacs with emacs-helm.sh (left on attached image)
> and one with my personal conf (right on attached image). The value of
> helm-boring-buffer-regexp-list is the same on both.

So i have no idea of what happen with your init file.
Anyway it is not an helm bug as it is not reproductible here and it
seems to work as well on your side with ./emacs-helm.sh.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by tomasorti** [comment]
Ok. I think I found it.
Since I was using ido, I had these lines to ignore some buffers:

    (require 'ido)
    (ido-mode t)
    (defvar ido-dont-ignore-buffer-names '("*scratch*" "*eshell*" "*shell*"))
    (defun ido-ignore-most-star-buffers (name)
    "This function make ido ignore NAME buffers with star except those of previous variable."
    (and
    (string-match-p "^*" name)
    (not (member name ido-dont-ignore-buffer-names))))
    (setq ido-ignore-buffers (list "\\` " #'ido-ignore-most-star-buffers))

Those seem to change the behavior on helm too.
I guess helm is looking at that ido variable.

**Comment by thierryvolpiatto** [comment]
nephewtom <notifications@github.com> writes:

> Those seem to change the behavior on helm too.
> I guess helm is looking at that ido variable.

Yes, we are using ido to list buffers.

-- 
Thierry
https://emacs-helm.github.io/helm/
