### ISSUE TITLE
Complete usernames along with tramp hosts

### ISSUE THREAD

**Issue by PythonNut** [emacs-helm/helm#1192]
In `helm-find-files`, helm tries to complete possible hosts after typing `/ssh:`. Unfortunately, this is of limited usefulness because the usernames on those hosts are not completed, leaving you with something like `/ssh:192.168.0.120`, which will only work if you just happen to have the same username on both machines.

I'm not exactly sure how this would work, but it would be nice for `helm` to offer completions for `username@host` pairs instead of just `host`.

**Comment by thierryvolpiatto** [comment]
PythonNut <notifications@github.com> writes:

> In helm-find-files, helm tries to complete possible hosts after typing
> /ssh:. Unfortunately, this is of limited usefulness because the
> usernames on those hosts are not completed, leaving you with something
> like /ssh:192.168.0.120,

This is a machine on your local network, isn't it, just name it in your
conf file with the corresponding host (see below).

> I'm not exactly sure how this would work, but it would be nice for
> helm to offer completions for username@host pairs instead of just
> host.

You have just to setup your "~/.ssh/config" file.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by PythonNut** [comment]
@thierryvolpiatto it certainly is, but that's not the point. My machines come and go, and not all of them have `~/.ssh/config` setup. 

My use case is the same as in #894. I work on large pool of machines which is always changing (batches of Raspberry Pis that come and go). I would really rather not rely on a static config file somewhere, because it would take a lot of work and discipline to always keep it synchronized with the environment I work in.

`helm` shouldn't need to depend on some other (non-emacs) configuration, should it?

**Comment by thierryvolpiatto** [comment]
PythonNut <notifications@github.com> writes:

> @thierryvolpiatto it certainly is, but that's not the point. My
> machines come and go, and not all of them have ~/.ssh/config setup.
>
> My use case is the same as in #894. I work on large pool of machines
> which is always changing (batches of Raspberry Pis that come and
> go). I would really rather not rely on a static config file somewhere,
> because it would take a lot of work and discipline to always keep it
> synchronized with the environment I work in.

Maybe yes...

> helm shouldn't need to depend on some other (non-emacs) configuration, should it?

Why? We are constantly relaying on external config files and/or env var,
not only in helm but in all emacs, what's the problem.

Anyway I will not add something else than what we have for tramp, it is
too much work for the small benefit it would provides.
IOW Don't expect changes on this.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by PythonNut** [comment]
Alright. Thanks.
