### ISSUE TITLE
Lisp error for particular inputs in helm-mini

### ISSUE THREAD

**Issue by AlKapote** [emacs-helm/helm#1197]
GNU Emacs 24.5.1
magit-20150930.1331

Triggering helm-mini and inputting "? " (any character, followed by a space),  barfs with 
```
Error running timer: (wrong-type-argument number-or-marker-p nil) 
```

It doesn't happen with " " (single space) nor with "?? " or longer strings.

Changing [this line](https://github.com/emacs-helm/helm/blob/395bb373eecafd86ad8f86247f33253feb804b3e/helm.el#L2695) to
```
(setq helm-pattern (replace-regexp-in-string " +" "" input))
```

makes it go away, but that's just the quickest hack I could find.

backtrace:
```
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
helm-fuzzy-matching-default-sort-fn
helm-compose
helm-funcall-with-source
helm-composed-funcall-with-source
helm-process-filtered-candidate-transformer
helm-compute-matches
helm--compute-sources
helm-update()
helm-check-new-input("x ")
helm-check-minibuffer-input()
timer-event-handler
helm-read-pattern-maybe
helm-internal
helm
helm
helm-mini
command-execute(helm-mini)
```

**Comment by thierryvolpiatto** [comment]
AlKapote <notifications@github.com> writes:

> GNU Emacs 24.5.1
> magit-20150930.1331
>
> Triggering helm-mini and inputting "? " (any character, followed by a space), barfs with
>
> Error running timer: (wrong-type-argument number-or-marker-p nil) 

Can't reproduce here, either from a plain emacs or from ./emacs-helm.sh.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by michael-heerdegen** [comment]
I cannot reproduce either.  @AlKapote for the backtrace: Can you please send one that is complete (yours shows only the current frame's function names).  With the sources loaded before to avoid it to be cluttered with byte code.

Could this problem be caused by your settings?  Does it happen with emacs-helm.sh?  Do you have a recipe for reproducing it there?  Thanks.

**Comment by AlKapote** [comment]
Nope, I can't repro with `emacs-helm` either.

`.emacs` bisection turned up [this snippet](https://github.com/emacs-helm/helm/issues/145#issuecomment-69478087) as the culprit. Honestly, I can't remember what 90% of the stuff in there does anymore. I don't remember this error occuring in the past and I just updated helm to tip yesterday after many months.  
 
@michael-heerdegen, for future reference how exactly do I get rid of the bytecode in backtraces? it was a pain editing it out so I could at least post the functions on stack.

**Comment by michael-heerdegen** [comment]
@AlKapote Yes, I thought that it would have been a lot of work ;-)

There's no other way than to load the sources of all functions into Emacs.  It's mostly sufficient to load only the sources of the affected package - all helm source files, in this case.
