### ISSUE TITLE
helm-boring-buffer-regexp-list is not enough

### ISSUE THREAD

**Issue by MikeSanMichel2** [emacs-helm/helm#1202]
My particualr problem is having many buffers of the form `*name-suffix*`, which are split about half and half between utterly boring and rather useful. Examples: \*ansi-term<2>\*, \*magit: ...", \*irony-server build\*, \*Flycheck error messages\*.

I care about the first 2 but not the last two, and as I start using new packages more of these special cases pop up and need constant maintenance of a a monster regex. 
I'd like to excluding "^*" and have a whitelist instead. a hook for user predicate function would be useful, perhaps even more so.

Of course I can do this now by redefining some helm internal fun, but having some official hook
would be better, I've had enough of monkey-patch-related-tail-chasing to last me forever.

**Comment by MikeSanMichel2** [comment]
Here's what I'm using now:

```elisp
(setq helm-boring-buffer-regexp-list
	  (quote
	   ("\\*temp"
        "\\*helm" "\\*helm-mode" "\\*Echo Area" "\\*Minibuf"
                  "\\Minibuf.+\\*"
                  "\\` "
               "\\*.+\\*"
                  )))

;; implement buffer whitelist for helm to augment 'helm-boring-buffer-regexp-list
(setq _helm-exciting-buffer-regexp-list
	  (quote
	   ("\\*magit:"
		"\\*ansi-term"
		)))

(with-eval-after-load "helm-buffers.el"
  (defun _helm-keep-entries (seq regexp-list)
	"Remove entries which matches one of REGEXP-LIST from SEQ."
	(cl-loop for i in seq
        if (cl-loop for regexp in regexp-list
                     thereis (and (stringp i)
                                  (string-match regexp i)))
        collect i))

  (defun helm-skip-boring-buffers (buffers _source)
	(let ((keepers (_helm-keep-entries buffers _helm-exciting-buffer-regexp-list))
		  (endangered (helm-skip-entries buffers _helm-exciting-buffer-regexp-list))
		  )
	  (append
	   keepers
	   (helm-skip-entries endangered helm-boring-buffer-regexp-list)
	   ))))
```

**Comment by thierryvolpiatto** [comment]
MikeSanMichel2 <notifications@github.com> writes:

> My particualr problem is having many buffers of the form
> *name-suffix*, which are split about half and half between utterly
> boring and rather useful. Examples: ansi-term<2>, magit: ...",
> *irony-server build, Flycheck error messages.

Sorry but I don't understand how you ended up with such buffers.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by MikeSanMichel2** [comment]
Sorry, not sure I understand what you're asking.
GH picked up the asterisks as markdown, I fixed that now. It should \*ansi-term\* and so on.
If that's not what you meant, then: I ran magit, ansi-term, flycheck and irony and those are the buffer names they create.

**Comment by thierryvolpiatto** [comment]
I don't understand what are your boring buffers you want to remove, please list them with a newline as separator.

**Comment by MikeSanMichel2** [comment]
Boring buffers:
```
*irony-server build* 
*Flycheck error messages*
*some_buffer_with_asterisk_prefix*
```
Interesting buffers:
```
*magit: .+
*ansi-term.+
```

The problem is that whenever I use a new package, more boring buffers need to be added to the boring list. Instead, I'd like helm to allow ignoring every buffer matching "^*" **except** those matching the patterns in a whitelist.

**Comment by thierryvolpiatto** [comment]
MikeSanMichel2 <notifications@github.com> writes:

> Boring buffers:
>
> *irony-server build* 
> *Flycheck error messages*
> *some_buffer_with_asterisk_prefix*
>
> Interesting buffers:
>
> *magit: .+
> *ansi-term.+
>
> The problem is that whenever I use a new package, more boring buffers
> need to be added to the boring list. Instead, I'd like helm to allow
> ignoring every buffer matching "^" *except** those matching the
> patterns in a whitelist.

Ok, that's clearer, sorry for misunderstanding, will make a fix soon.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by MikeSanMichel2** [comment]
Thank you! :)
