### ISSUE TITLE
Relative numbering for candidates

### ISSUE THREAD

**Issue by jgarvin** [emacs-helm/helm#1203]
I use the linum-relative package to get line numbers relative to the cursor in the margin. The reason this is useful to me is I drive emacs with speech recognition, and the speech recognizer has a specialized more accurate mode for numbers than it does for general speech, so I try to navigate using commands based on numbers where possible. So with relative line numbers I can say "up 5" or "down 29" and know exactly where I will end up. Relative numbers are better than absolute because they are smaller and easier to say; if I'm in the middle of a big file and I want to go down 3 lines I don't want to say "goto line three thousand four hundred and twenty six." I just want to say, "down 3".

Now I'm trying to give helm a spin and I noticed that when I use helm-M-x the relative line numbers don't work in the completion window. They appear, but always consider the first line of the buffer to be 0 regardless of where the cursor is. That is until you scroll down past the end of the window, then they move again but stay still after that until you go outside the window boundary again. I think this is because the cursor is actually in the minibuffer and you're driving the completion window off input events.

Originally I was going to try some hacks to get linum-relative working properly in the completion window, but then I experimented some more and discovered that relative line numbers aren't even really what I want with helm, I want relative candidate numbers. When browsing the kill ring for example a lot of the candidates are going to be multiple lines, but pressing up/down jumps candidates, not lines, so candidates are really what I want numbered so I can use the right voice command.

I could see this being useful even for keyboard users. It'd be nice to press say, alt-3 and have it pick the 3rd entry without having to move down to it first (similar to choosing a candidate in company-mode's popup window), but in order to eyeball that easily you'd want the relative candidate numbering in the margin.

**Comment by thierryvolpiatto** [comment]
jgarvin <notifications@github.com> writes:

> Now I'm trying to give helm a spin and I noticed that when I use
> helm-M-x the relative line numbers don't work.

I had a quick look at the package.

It seems it is not adapted for helm, on the helm side apart writing a
complete linum-relative-mode for helm I can't do much.

However, it seems your package is configurable.

Did you try to customize `relative-line-numbers-motion-function'
(helm-next-line) and run the mode (and not the global-mode)
`relative-line-numbers-mode' in the helm buffer with a hook (e.g
`helm-after-initialize-hook') ?

If it doesn't work I will have a closer look at the package to see what
is needed to make it working in helm and possibly send a PR to the
author if I find what to do.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by xuchunyang** [comment]
Numbering visible candidates for easily selecting/executing sounds useful, but I don't think "relative" is necessary, as long as we limit the number of candidates to display, for example, in company-mode:

![2015-10-08 2 34 27](https://cloud.githubusercontent.com/assets/4550353/10359441/5d18f4f2-6dcb-11e5-904a-c050022fc75e.png)

I think this feature is better to be implemented from helm, instead of using `linum-mode` or `linum-relative`.

**Comment by michael-heerdegen** [comment]
@thierryvolpiatto I think you looked at "relative-line-numbers.el", but @jgarvin spoke about "linum-relative.el", a different thing.

@jgarvin My first try:
```
(defun my-linum-for-helm ()
  (when (fboundp 'helm-buffer-get)
    (let ((helm-buf (get-buffer (helm-buffer-get))))
      (when (buffer-live-p helm-buf)
        (with-current-buffer helm-buf
          (setq-local linum-relative-last-pos (line-number-at-pos)))
        (linum-update helm-buf)))))

(add-hook 'post-command-hook #'my-linum-for-helm)
```
linum-relative.el is a hack that really doesn't fit this use case.  The above is a hack that hacks this hack to do what you want.

Note that linum-relative.el is based on linum.el which will once be obsoleted by nlinum.el.

BTW have you tried the package that Thierry had found?  Maybe it suits your case better?

**Comment by michael-heerdegen** [comment]
@jgarvin And if you want to count candidates instead of lines, you would have to redefine `linum-relative'.  Then you already have nearly as much code changing the package as the package has itself.

**Comment by thierryvolpiatto** [comment]
@michael-heerdegen I looked at relative-line-number-mode package in melpa

https://github.com/Fanael/relative-line-numbers

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> @thierryvolpiatto I think you looked at "relative-line-numbers.el", but @jgarvin spoke about "linum-relative.el", a different thing.
>
> @jgarvin My first try:
>
> (defun my-linum-for-helm ()
>   (when (fboundp 'helm-buffer-get)
>     (let ((helm-buf (get-buffer (helm-buffer-get))))
>       (when (buffer-live-p helm-buf)
>         (with-current-buffer helm-buf
>           (setq-local linum-relative-last-pos (line-number-at-pos)))
>         (linum-update helm-buf)))))
>
> (add-hook 'post-command-hook #'my-linum-for-helm)

IMO it is better to use `helm-move-selection-after-hook' instead of
`post-command' which allow to call your function only when moving to
next line/source etc..., it allow also simplifying checking in your
function:

(defun my-linum-for-helm ()
  (with-helm-buffer
    (setq-local linum-relative-last-pos (line-number-at-pos)))
  (linum-update helm-buffer))

(add-hook 'helm-move-selection-after-hook 'my-linum-for-helm)

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> (defun my-linum-for-helm ()
> (with-helm-buffer
> (setq-local linum-relative-last-pos (line-number-at-pos)))
> (linum-update helm-buffer))
>
> (add-hook 'helm-move-selection-after-hook 'my-linum-for-helm)

That's indeed better, thanks, I didn't think of
helm-move-selection-after-hook at that moment.

**Comment by thierryvolpiatto** [comment]
I finally had a closer look at linum-relative.el and could make it working with helm, both with multiline candidates and normal candidates, here what need to be modified:

1) Add this function like described in previous post to `helm-move-selection-after-hook`:

```elisp

(defun my-linum-for-helm ()
  (with-helm-buffer
    (make-local-variable 'linum-relative-last-pos))
  (linum-update helm-buffer))

(add-hook 'helm-move-selection-after-hook 'my-linum-for-helm)

```

2) Modify the `linum-update` advice and the `linum-relative` function in linum-relative.el:

```elisp
;;;; Advices
(defadvice linum-update (before relative-linum-update activate)
  "This advice get the last position of linum."
  (if helm-alive-p
      (setq linum-relative-last-pos (helm-candidate-number-at-point))
      (setq linum-relative-last-pos (line-number-at-pos))))

;;;; Functions
(defun linum-relative (line-number)
  (when helm-alive-p
    (with-helm-buffer
      (if (looking-at helm-candidate-separator)
          (setq line-number (save-excursion
                              (forward-line 1) (helm-candidate-number-at-point)))
          (setq line-number (helm-candidate-number-at-point)))))
  (let* ((diff1 (abs (- line-number linum-relative-last-pos)))
	 (diff (if (minusp diff1)
		   diff1
		 (+ diff1 linum-relative-plusp-offset)))
	 (current-p (= diff linum-relative-plusp-offset))
	 (current-symbol (if (and linum-relative-current-symbol current-p)
			     (if (string= "" linum-relative-current-symbol)
				 (number-to-string line-number)
			       linum-relative-current-symbol)
			   (number-to-string diff)))
	 (face (if current-p 'linum-relative-current-face 'linum)))
    (if (and helm-alive-p
             (with-helm-buffer
               (or (looking-at helm-candidate-separator)
                   (helm-pos-header-line-p))))
        (propertize (format linum-relative-format current-symbol) 'invisible t)
        (propertize (format linum-relative-format current-symbol) 'face face))))

```

Probably this code can be polished and integrated to linum-relative.el with a PR.
Feel free to do so.

**Comment by thierryvolpiatto** [comment]
>Probably this code can be polished and integrated to linum-relative.el with a PR.

Done https://github.com/coldnew/linum-relative/pull/19

**Comment by jgarvin** [comment]
Wow, thanks all for the super responsive work. I'm trying the code from @thierryvolpiatto and it seems to work pretty well with one minor hiccup. When I use helm to show the kill ring, if there are blank lines in any of the kill ring entries they get the wrong line number. When all of the lines are non-blank, every line within a candidate gets the relative candidate number as its number in the margin, but if there is a blank line the blank line seems to get the absolute candidate number.

**Comment by jgarvin** [comment]
@michael-heerdegen I tried relative-line-numbers but it handled visual-line-mode worse (neither one handles it correctly though) so I went back to linum-relative. I filed an issue but the author closed it: https://github.com/Fanael/relative-line-numbers/issues/6 Eventually I might get around to trying to fix it, I think using the format variable to fix the width of the numbers to the digit width of the greatest line number so far seen and regenerating when a new widest number is found would work but I haven't had time to code it up.

**Comment by thierryvolpiatto** [comment]
jgarvin <notifications@github.com> writes:

> Wow, thanks all for the super responsive work. I'm trying the code
> from @thierryvolpiatto and it seems to work pretty well with one minor
> hiccup. When I use helm to show the kill ring, if there are blank
> lines in any of the kill ring entries they get the wrong line
> number. When all of the lines are non-blank, every line within a
> candidate gets the relative candidate number as its number in the
> margin, but if there is a blank line the blank line seems to get the
> absolute candidate number.

Because I guess you used only the first patch, the second patch is
fixing this.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by jgarvin** [comment]
@thierryvolpiatto By second patch you mean the code you listed under "2)"? If so I am using it but still see it happening. It looks like it only happens though when the blank line is the last line in the candidate. If it's the first line or a line in the middle it numbers fine.

**Comment by thierryvolpiatto** [comment]
jgarvin <notifications@github.com> writes:

> @thierryvolpiatto By second patch you mean the code you listed under
> "2)"? If so I am using it but still see it happening. It looks like it
> only happens though when the blank line is the last line in the
> candidate. If it's the first line or a line in the middle it numbers
> fine.

No, just checkout https://github.com/thierryvolpiatto/linum-relative
and enable the mode with M-x linum-relative-mode
(not need to run global-linum-mode).

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by jgarvin** [comment]
@thierryvolpiatto oh of course. Works great now :)

**Comment by thierryvolpiatto** [comment]
Great, so I am closing this now, I hope the PR on linum-relative will be merged.

**Comment by YorkZ** [comment]
linum-relative-mode is cool. Unfortunately, it takes too much screen real estate. Therefore, I would like to enable this mode only in helm buffers. Is there an easy way to do so?

**Comment by thierryvolpiatto** [comment]
York Zhao <notifications@github.com> writes:

> linum-relative-mode is cool. Unfortunately, it takes too much screen
> real estate. Therefore, I would like to enable this mode only in helm
> buffers. Is there an easy way to do so?

Yes, you have to enable the mode localy in helm buffers only, I didn't
have the time to push the code, and I didn't have the time to decide
where to push it also.

1) One hook is enabled in linum-relative.el, remove it like in
http://tinyurl.com/zs65552

2) Put this code in your init file:

(defun helm--turn-on-linum-relative ()
  (with-helm-buffer (linum-relative-mode 1)))

(define-minor-mode helm-linum-relative-mode
    "Turn on linum-relative in helm.
Allow to execute default action on nth candidate.
Commands prefixed with C-x will use nth candidate before selection
the ones prefixed with C-c will use nth candidate after selection."
  :group 'helm
  (if helm-linum-relative-mode
      (progn
        (add-hook 'helm-move-selection-after-hook 'linum-relative-for-helm)
        (add-hook 'helm-after-initialize-hook 'helm--turn-on-linum-relative)
        (add-hook 'helm-after-preselection-hook 'linum-relative-for-helm))
      (remove-hook 'helm-move-selection-after-hook 'linum-relative-for-helm)
      (remove-hook 'helm-after-initialize-hook 'helm--turn-on-linum-relative)
      (remove-hook 'helm-after-preselection-hook 'linum-relative-for-helm)))

3) Once loaded or emacs restarted:
M-x helm-linum-relative-mode RET 

PS: If not well formated, copy the code above from
http://tinyurl.com/ogwg2oj

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by YorkZ** [comment]
Thank you very much Thierry!
