### ISSUE TITLE
sort the list of helm-semantic-or-imenu

### ISSUE THREAD

**Issue by c02y** [emacs-helm/helm#1204]
I already got this:

    (with-eval-after-load 'helm-semantic
      (push '(emacs-lisp-mode . semantic-format-tag-summarize) helm-semantic-display-style))

So it will show the types in the result window of `helm-semantic-or-imenu` for elisp file, but the order of the list for my init.el is a mess, `Functions`->`Dependencies`->`Functions`->`Functions`->`Variables`...

Weird thing is the default order for the CPP file is fine: `Dependencies`->`Variables`->`Functions`

I changed it to this:

    (with-eval-after-load 'helm-semantic
      (push '(emacs-lisp-mode . semantic-format-tag-summarize) helm-semantic-display-style)
      (setq-default semantic-imenu-sort-bucket-function 'semantic-sort-tags-by-type))

But this doesn't work, so what should I do?

**Comment by thierryvolpiatto** [comment]
c02y <notifications@github.com> writes:

> I change it to this:
>
> (with-eval-after-load 'helm-semantic
>   (push '(emacs-lisp-mode . semantic-format-tag-summarize) helm-semantic-display-style)
>   (setq-default semantic-imenu-sort-bucket-function 'semantic-sort-tags-by-type))
>
> But this doesn't work, so what should I do.

Hmm, I am not a semantic-mode fan myself, I only use it for python
buffers.  I guess this is a problem with semantic-mode itself which
doesn't sort candidates at all (IIRC it seems they come in the same order
they are in the source code buffer).
If sorting is better in other modes, I guess it is just that
semantic-mode is handling specialy these modes in a better (and
different) way.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by thierryvolpiatto** [comment]
Perhaps @tuhdo can help you on this.

**Comment by c02y** [comment]
**UPDATE**

Sorry about this.

~~Weird thing is the default order for the CPP file is fine: Dependencies->Variables->Functions~~

is my misunderstanding.

@thierryvolpiatto you are right
`semantic-mode` doesn't sort candidates at all, it seems they come in the same order they are in the source code buffer.
