### ISSUE TITLE
Helm-bookmark error

### ISSUE THREAD

**Issue by igorepst** [emacs-helm/helm#1207]
Hello,
If there are no bookmarks at all, helm-bookmark prints this to the 'Messages':

```
Error during redisplay: (eval (helm-show-candidate-number (car-safe helm-mode-line-string))) signaled (wrong-type-argument integer-or-marker-p nil)
Invalid face reference: t [2 times]
```
However, upon adding a bookmark, the first error vanishes, and only the invalid face reference is left.
Thank you

**Comment by michael-heerdegen** [comment]
Do you use helm-echo-input-in-header-line -> t?  I found that this setting leads to
```
Invalid face reference: t
```
messages.  Will install a fix for for that problem soon.

**Comment by michael-heerdegen** [comment]
The other error message
```
Error during redisplay: (eval (helm-show-candidate-number (car-safe helm-mode-line-string))) signaled (wrong-type-argument integer-or-marker-p nil)
```
comes from the mode-line.  `helm-show-candidate-number' should probably treat that case correctly, but the
```
(helm-empty-source-p)
```
test returns nil, which seems wrong to me.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> (helm-empty-source-p)
>
> test returns nil, which seems wrong to me.

It is not, the source is not empty, nor the helm-buffer.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> It is not, the source is not empty, nor the helm-buffer.

Then I don't understand what "empty source" means.  The docstring of
`helm-empty-source-p' seems to mean the absence of any candidates, which
is the case here.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Thierry Volpiatto <notifications@github.com> writes:
>
>> It is not, the source is not empty, nor the helm-buffer.
>
> Then I don't understand what "empty source" means. The docstring of
> `helm-empty-source-p' seems to mean the absence of any candidates, which
> is the case here.

Not for dummy sources, which imply no candidates until you enter
something in minibuffer.
I have fixed this by adding a default candidate that do nothing when
helm-pattern is empty.

So there is no bug in `helm-empty-source-p', if the header of the source
is here, the source is not considered empty.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by michael-heerdegen** [comment]
Ok, great.  @igorepst can you confirm the problem is gone?

**Comment by igorepst** [comment]
Both problems are fixed. Thank you
