### ISSUE TITLE
Helm-recentf seems not finding filenames with hyphen, when input is without hyphen

### ISSUE THREAD

**Issue by ReneFroger** [emacs-helm/helm#1208]
I have my configuration stored in many files, with the prefix `config-`

For example, when I want to find the file `config-keybinding.el`, it's not listed in Helm-for-files.

Only when I add a hyphen (`-`), he will find it. So it makes me to wonder if I could configure it that he will find the file, even when the hyphen is omitted and the words together? A screencast to illustrate this.

![helm input window](https://cloud.githubusercontent.com/assets/5211845/10410343/4e18545a-6f3f-11e5-9bd1-2bb090d9128a.gif)

**Comment by xuchunyang** [comment]
Type `config key` (with a white space in middle)  instead or turn on fuzzy-match by setting `helm-recentf-fuzzy-match` to `nil`.

**Comment by ReneFroger** [comment]
(setq helm-recentf-fuzzy-match t)

Solved my issue. Thanks @xuchunyang :+1:!

**Comment by zilongshanren** [comment]
@xuchunyang 
The `helm-recentf-fuzzy-match` seems broken for me with latest update from MELPA.
Any clue?
Thanks.

**Comment by thierryvolpiatto** [comment]
子龙山人 <notifications@github.com> writes:

> @xuchunyang
> The helm-recentf-fuzzy-match seems broken for me with latest update from MELPA.
> Any clue?

Should be fixed now.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by zilongshanren** [comment]
@thierryvolpiatto  thanks. I will test it when the MELPA updated.

**Comment by manuel-uberti** [comment]
I have latest Helm from MELPA. Fuzzy matching in recentf still doesn't work with `(setq helm-recentf-fuzzy-match t)`.

The workaround posted [here](https://emacs.stackexchange.com/a/14257/5514) works for me:
```
(setq helm-source-recentf 
  (helm-make-source "Recentf" 'helm-recentf-source
    :fuzzy-match t))
```

**Comment by thierryvolpiatto** [comment]
Manuel Uberti <notifications@github.com> writes:

> I have latest Helm from MELPA. Fuzzy matching in recentf still doesn't
> work with (setq helm-recentf-fuzzy-match t).

It is not that it is not working, it is you have to use customize to set
this.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by manuel-uberti** [comment]
Great, thanks for the tip. It works fine without the workaround.
