### ISSUE TITLE
No command 'helm-execute-helm-command'

### ISSUE THREAD

**Issue by sac7e** [emacs-helm/helm#1210]
When I read wiki, I try to enter `helm-execute-helm-command` under helm buffer. But there is no candidate.

**Comment by thierryvolpiatto** [comment]
There is no such command in helm, also what mean "enter helm-execute-helm-command under helm-buffer"?

**Comment by michael-heerdegen** [comment]
@thierryvolpiatto Please read the wiki under  "Overview of preconfigured helm commands".  Whatever is meant there is outdated.

**Comment by thierryvolpiatto** [comment]
The wiki is editable and any body can write in it.
And yes many things are outdated there.
I will fix this when I have time if no body do it.

**Comment by sac7e** [comment]
Ok, I see.
Thank you for your reply.
