### ISSUE TITLE
Make the key to select exisiting candidate in `must-match-map` in `helm-comp-read` customizable

### ISSUE THREAD

**Issue by iqbalansari** [emacs-helm/helm#1211]
Right now the key to select existing candidate in `helm-comp-read`, when `must-match` is non-nil is [hard-coded](https://github.com/emacs-helm/helm/blob/08edbe1ca9c658cba36ea538d981ae4c3af647fa/helm-mode.el#L390-L394) to <kbd>RET</kbd>. It would be great if that key is customizable. 

One use case is that I want <kbd>RET</kbd> in `helm-read-file-map` to behave similarly to how it does it in `ido`. However rebinding `RET` in `helm-read-file-map` does not work if the function calling `read-file-name` passes the argument `mustmatch` as `t` since helm then overrides the `RET` binding to call `helm-confirm-and-exit-minibuffer`. Right now have to resort to [advicing](https://github.com/iqbalansari/dotEmacs/blob/ebf641d9ec43caff4c4a8f415df55d678bcd6603/config/helm.org#remap-ret-in-helm-read-file-map) `helm--maybe-update-keymap` to override the helm `RET` keybinding.

**Comment by thierryvolpiatto** [comment]
See `helm-comp-read-must-match-map`, if it is what you want, confirm and close.

Thanks.

**Comment by iqbalansari** [comment]
I confirm that this has been fixed, thanks!
