### ISSUE TITLE
Make helm-find-files's action find-file-other-window (C-c o) handle multi selection?

### ISSUE THREAD

**Issue by xuchunyang** [emacs-helm/helm#1212]
Someone wants it to work according to [this question](http://emacs.stackexchange.com/q/14076/3889)'s second comment.

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

> Someone wants it to work according to this question's second comment.

He have to use C-u RET after marking files.
The split is done with `dired-simultaneous-find-file'.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by xuchunyang** [comment]
Now I am not sure what he wants, but I though `helm-find-files`'s `C-c o` should have similar function to `helm-buffers-list`'s `C-c o`, i.e., keep `helm-current-buffer`'s window and open marked files with other new windows.

**Comment by blaenk** [comment]
Hey @xuchunyang thanks for creating this! In fact, I had already created an issue (#1100) about this, and you actually [helped me with it](https://github.com/emacs-helm/helm/issues/1100#issuecomment-128939418)! It works great! The only annoyance is that I have to add this for every helm command that I want it in.

Is the solution you gave me there different from what I was asking here? I honestly don't remember.

**Comment by xuchunyang** [comment]
> Is the solution you gave me there different from what I was asking here? I honestly don't remember.

@blaenk yes, there are a little different, that solution was for opening *buffers*, while you were asking for opening *files*, though it should be very easy to change that solution to fit your needs.

Anyway, now `C-c o` now can handle multi selection since #1213 has been merged.
