### ISSUE TITLE
Display the number of marked candidates somewhere in the mode line?

### ISSUE THREAD

**Issue by xuchunyang** [emacs-helm/helm#1214]
Just a random idea and I don't know whether this is a good one.  This afternoon, I had to learn how many marked candidates by accident and count myself with some difficulty.

**Comment by thierryvolpiatto** [comment]
Yes, a good idea, not difficult to add, I have difficulty though to find a convenient string, I am actually using `MC:n`, but maybe you have a better idea ?
![screenshot - 13102015 - 11 38 29](https://cloud.githubusercontent.com/assets/1533939/10451265/62fc78f8-719f-11e5-81e3-2cf3ff4916a2.png)

**Comment by xuchunyang** [comment]
my thought is `[3/56 Candidate(s)]` since it can save some space.

**Comment by michael-heerdegen** [comment]
I think [3/56 Candidate(s)] could misinterpreted with the number of the current candidate.

@thierryvolpiatto If you propertize the number with the face used for marking, maybe we can even avoid an additional string entirely.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> I think [3/56 Candidate(s)] could misinterpreted with the number of the current candidate.

Yes, I think too.

> @thierryvolpiatto If you propertize the number with the face used for
> marking, maybe we can even avoid an additional string entirely.

Hmm, a good idea but not enough IMO, what about a single char like:

M3

With same face as marking.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> Hmm, a good idea but not enough IMO, what about a single char like:
>
> M3
>
> With same face as marking.

Good, would be ok for me.

**Comment by thierryvolpiatto** [comment]
Looks like this:

![screenshot - 13102015 - 13 28 59](https://cloud.githubusercontent.com/assets/1533939/10453675/8dfabfb0-71ae-11e5-9c1f-1e5022d08a86.png)

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> screensh

Mmh, I would rather prefer "M:2" or "2M" or only "2".  In any case, I
would apply the face only to the number "2".

BTW, what do you display if there are zero marked candidates?  Nothing
at all (I would prefer that)?

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Thierry Volpiatto <notifications@github.com> writes:
>
>> screensh
>
> Mmh, I would rather prefer "M:2" or "2M" or only "2". In any case, I
> would apply the face only to the number "2".

Feel free to modify, I have commited the change.
BTW I don't like the face only on number, prefer the whole string with
the face.

> BTW, what do you display if there are zero marked candidates?

Nothing.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by michael-heerdegen** [comment]
Ok, let's try it for some time and see how it "feels", and what people think.

**Comment by xuchunyang** [comment]
Current implement shows the number of marked candidates across *all* sources, I think it is more reasonable to limit that to current source, like other two numbers in mode-line. 

(I've tried to make a PR while function `helm-get-current-source` doesn't do what I expect and I have to filter the value of variable `helm-marked-candidates`, it is a bit complicated to me)

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

> Current implement shows the number of marked candidates across all
> sources, I think it is more reasonable to limit that to current
> source, like other two numbers in mode-line.

Agreed, good idea, done.

This show me a new bug though, when there is marked candidates in one
source and you run the action of another (unrelated) source.

Thanks.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by thierryvolpiatto** [comment]
> This show me a new bug though, when there is marked candidates in one source and you run the action > of another (unrelated) source.

Fixed, `helm-marked-candidates` should always return at least one candidate (the selection), but never nil.
