### ISSUE TITLE
helm-grep breaks with helm-git-grep on binary file match after PR #1218

### ISSUE THREAD

**Issue by razzmatazz** [emacs-helm/helm#1219]
I think https://github.com/emacs-helm/helm/pull/1218 broke my helm-git-grep tool (maybe helm-grep as well?).

I get these stack traces:
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-name-nondirectory(nil)
  helm-grep--filter-candidate-1("Binary file docs/something.pdf matches")
  helm-grep-filter-one-by-one("Binary file docs/something.pdf matches")
...
```

Setting `(setq helm-grep-file-path-style 'absolute)` fixes the problem.

I am not good at neither helm-grep.el nor helm-git-grep.el to fix them..

**Comment by thierryvolpiatto** [comment]
Saulius Menkevičius <notifications@github.com> writes:

> I think #1218 broke my helm-git-grep tool (maybe helm-grep as well?).

helm-grep is working fine with this change, git-grep too when it run
from helm-ls-git, I don't know what helm-git-grep is, probably you
should report to the author of this package.

BTW If you want to run git-grep from helm, you should use helm-ls-git,
which is developed in emacs-helm, this ensure the code is always up to
date with helm.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by razzmatazz** [comment]
Thanks, will look into it.

The difference is that helm-ls-git (apparently) doesn't provide a way to do git-grep immediately, you have to do helm-ls-git-ls and then helm-ls-git-run-grep (via `C-s`).

**Comment by thierryvolpiatto** [comment]
Saulius Menkevičius <notifications@github.com> writes:

> Thanks, will look into it.
>
> The difference is that helm-ls-git (apparently) doesn't provide a way
> to do git-grep immediately, you have to do helm-ls-git-ls and then
> helm-ls-git-run-grep (via C-s).

Indeed, I haven't implemented this because we have now helm-grep-ag
which is as fast as git-grep but of course doesn't take the files at
lower level if you are in a subdir of your project (though we have
helm-gid that does this).
Perhaps I will add a helm-grep-git command that does what you ask.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Saulius Menkevičius <notifications@github.com> writes:

> Thanks, will look into it.

Hmm, you're right, last changes are breaking git-grep, my bad.
I will install a fix as soon as possible.

Sorry for inconvenience.

-- 
Thierry
https://emacs-helm.github.io/helm/
