### ISSUE TITLE
helm-execute-persistent-action in describe-function, describe-variable, and helm-apropos

### ISSUE THREAD

**Issue by issue-dispenser** [emacs-helm/helm#1222]
I really like using helm-execute-persistent-action (C-j by default) in helm-M-x where it opens a temporary window with the whole function documentation. Then a simple C-j closes that window.

Would this feature be possible with helm-mode-describe-function and helm-mode-describe-variable? Currently doing helm-execute-persistent-action in either of these opens up a brief docstring in the mode-line, which is not nearly as useful as the above helm-M-x functionality.

Additionally, in helm-apropos, doing helm-execute-persistent-action after another helm-execute-persistent-action doesn't close the temporary window like helm-M-x does. I believe this is unintended.

**Comment by xuchunyang** [comment]
> Would this feature be possible with helm-mode-describe-function and helm-mode-describe-variable?

Yes, you can customize the user option `helm-elisp-help-function` (default value is `'helm-elisp-show-doc-modeline`):

    (setq helm-elisp-help-function #'helm-elisp-show-help)

> Additionally, in helm-apropos, doing helm-execute-persistent-action after another helm-execute-persistent-action doesn't close the temporary window like helm-M-x does. I believe this is unintended.

I also found this.

**Comment by issue-dispenser** [comment]
>Yes, you can customize the user option helm-elisp-help-function (default value is 'helm-elisp-show-doc->modeline):

Ah, that's nice, thanks. However, just changing the user option results in the same issue that helm-apropos has, where doing another helm-execute-persistent-action does not close the temporary window.

Also, changing the value does not change the helm header's string (that is, it still shows `C-j: Show brief doc in mode-line (keeping session)` when it should change to `Describe this function...` or `Describe this variable...` similar to what helm-M-x shows.

**Comment by xuchunyang** [comment]
> Ah, that's nice, thanks. However, just changing the user option results in the same issue that helm-apropos has, where doing another helm-execute-persistent-action does not close the temporary window.

Yes, you are right. I have a quick and dirty fix for `helm-mode-describe-*`.

```elisp
(setq helm-elisp-help-function #'my-helm-elisp-show-help)

(setq in-help nil
      help-cand nil)

(defun my-helm-elisp-show-help (candidate)
  "Show full help for the function."
  (let ((hbuf (get-buffer (help-buffer))))
    (if (and in-help (string= candidate help-cand))
        (progn
          ;; When M-x is started from a help buffer,
          ;; Don't kill it as it is helm-current-buffer.
          (unless (equal hbuf helm-current-buffer)
            (kill-buffer hbuf)
            (set-window-buffer (get-buffer-window hbuf)
                               helm-current-buffer))
          (setq in-help nil))
      (let ((sym (intern-soft candidate)))
        (cl-typecase sym
          (fbound   (describe-function sym))
          (bound    (describe-variable sym))
          (face     (describe-face sym))))
      (setq in-help t))
    (setq help-cand candidate)))
```


> However, just changing the user option results in the same issue that helm-apropos has, where doing another helm-execute-persistent-action does not close the temporary window.

`helm-apropos` s not affected by `helm-elisp-help-function`, we need fix its persistent-action.

> Also, changing the value does not change the helm header's string

Right, we also need to fix this.

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

>     Would this feature be possible with helm-mode-describe-function
>     and helm-mode-describe-variable?
>    
> Yes, you can customize the user option helm-elisp-help-function
> (default value is 'helm-elisp-show-doc-modeline):
>
> (setq helm-elisp-help-function #'helm-elisp-show-help)

It is now the default.

>     Additionally, in helm-apropos, doing
>     helm-execute-persistent-action after another
>     helm-execute-persistent-action doesn't close the temporary window
>     like helm-M-x does. I believe this is unintended.
>    
> I also found this.

Should be fixed now.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by issue-dispenser** [comment]
Thanks, it now seems to work in all cases.

One minor thing that is more noticeable now is that when showing help for describe-variable/function, a message `Type "q" to restore previous buffer` shows up in the modeline and stays there for a second or so.

The same thing happens with helm-M-x or helm-apropos, but instead the same message there disappears very quickly. Is there an easy way to shorten or disable the minibuffer message for the help toggle on describe-variable/function?

**Comment by issue-dispenser** [comment]
Actually, I just found an issue. If there's a variable sharing the same name as a function, then toggling the help in helm-describe-variable actually shows the help for the function and not the variable.

**Comment by thierryvolpiatto** [comment]
issue-dispenser <notifications@github.com> writes:

> Actually, I just found an issue. If there's a variable sharing the
> same name as a function, then toggling the help in
> helm-describe-variable actually shows the help for the function and
> not the variable.

Yes, I saw this too, but I don't know how to fix for now, the function
we are using is a generic function that have to guess what we are
completing against, it is why I used until now the mode-line function
that just extract the first line of doctring, no matter it is a function
or a variable or whatever.
I will probably switch back to the help in mode-line until fixed.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by thierryvolpiatto** [comment]
Thierry Volpiatto <thierry.volpiatto@gmail.com> writes:

> issue-dispenser <notifications@github.com> writes:
>
>> Actually, I just found an issue. If there's a variable sharing the
>> same name as a function, then toggling the help in
>> helm-describe-variable actually shows the help for the function and
>> not the variable.
>
> Yes, I saw this too, but I don't know how to fix for now,

I finally found something suitable, should work fine now.

Thanks.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by issue-dispenser** [comment]
Seems to work now, thanks.
