### ISSUE TITLE
Augmenting fuzzy match sorting with helm-adaptive. Code rot in helm-adaptive?

### ISSUE THREAD

**Issue by AlKapote** [emacs-helm/helm#1228]
https://github.com/PythonNut/helm-flx/issues/4
https://github.com/emacs-helm/helm/issues/145#issuecomment-148177275

I'm using [helm-flx](https://github.com/PythonNut/helm-flx) to rank the fuzzy matches from helm with the flx algo which works very well. One thing that's still missing is for helm to keep a history of my actions in order to boost some matches based on my habits, beyond the the ranking of the query itself. This is the functionality the existing `helm-adaptive` package is supposed to provide. 

In principle, turning on `helm-adaptive-mode`, generating some actions/history, and wrapping the sorting function provided by helm-flx (or whatever is used) with `helm-adaptive-sort` should be enough, but this doesn't work because...

**Issue 1**
1. Turning on `helm-adaptive-mode` hooks into `helm-select-action-hook` and  `helm-before-action-hook` to  call `helm-adaptive-store-selection` which stores the selection away for future lookup when sorting. 
2. `helm-adaptive-store-selection` checks whether the mode is configured for using helm-adaptive using `helm-adapt-use-adaptive-p` which checks the contents of the `(filtered)-candidates-transformer`.
3. For practically all the sources provided by helm (M-x, apropos, etc') it isn't present,
and I don't know how one can override it since it seems to be hardcoded in the helm source.

**Issue 2**
1. Even if you shortcirctuit the `helm-adapt-use-adaptive-p` check, so `helm-adaptive` always stores  history for all sources, there's something wrong with the entries generated. 
2. It looks like the history is stored as in alist keyed by source-name, but the entries generated
all have `nil` as their source. 
3. Because of this, when `helm-adaptive-sort` is called and looks up the history for the current source it can't find anything, and does nothing.

Sidenote, I've edited the history file manually to fix the key, and with
```elisp
  (setq helm-fuzzy-sort-fn
		(lambda (candidates source &optional use-real)		  
		  (-> candidates
			  (my/helm-fuzzy-matching-sort-fn source use-real)	; helm-flx	snippet
			  (helm-adaptive-sort source)
			  ))
```
Got adaptive to sort the result of the flx ranking of the helm fuzzy matching.... which sounds
awful, but is actually awesome.

Augmenting fuzzy matching/flx ranking with adaptive would be a wonderful feature that makes
the helm experience even better. Now that `helm-flx` is a proper package, it is even easier
to get a really first-class filtering solution with helm.

Would it possible to:
1. Enable users to explicitly enable the storage of adaptive history for a given source (list of sources). (`helm-adapt-use-adaptive-p` assumes transformers are used, instead of the sort function using
the history explicitly)
2. Fix `helm-adaptive-store-selection` so the history generated is valid.

If I can help make this happen, please let me know.

**Comment by thierryvolpiatto** [comment]
AlKapote <notifications@github.com> writes:

> Would it possible to:
> 1. Enable users to explicitly enable the storage of adaptive history
> for a source.

No, not yet at least, a rework (possibly a full rewrite) of
helm-adaptative would be necessary and it is not a priority for me now.

> 2. Fix helm-adaptive-store-selection so the history generated is
> valid.

Probably yes, like said above a rewrite would be necessary.

I made a rework of this in 2009 or 2010, don't remember, adaptative was
completely broken, I had to disable it during some months, now it is
working more or less but still fragile, it is why I enabled it in only
some places, and it is also why there is a mode to disable it without
touching source code in case the helm-adaptative-history file get corrupted.

Anyway as said many times, I don't think it is really useful for things
like symbols (apropos, M-x etc...) and is really unwanted in things like
helm-find-files and others.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by AlKapote** [comment]
I think it's quite a useful feature but well ok, thank you.

**Comment by AlKapote** [comment]
I've put this in my `.emacs`and now together with `helm-flx` installed this is working for me. 

```elisp
(with-eval-after-load 'helm-adaptive
  (defcustom helm-adaptive-enabled-sources  '()
	"Source who name appears on this list will have their history stored for use by helm-adaptive."
	:type '(repeat string)
	:group 'helm-adapt)

  ;; Remember history for these sources
  (add-to-list 'helm-adaptive-enabled-sources "Commands")
  (add-to-list 'helm-adaptive-enabled-sources "Variables")

  ;; Clobber helm's implementation
  (defun helm-adapt-use-adaptive-p (&optional source-name)
	"Return current source only if it use adaptive history, nil otherwise."
	(when helm-adaptive-mode
	  (let* ((source (or source-name (helm-get-current-source)))
			 (adapt-source (or (assoc-default 'filtered-candidate-transformer
											  (assoc (assoc-default 'type source)
													 helm-type-attributes))
							   (assoc-default 'candidate-transformer
											  (assoc (assoc-default 'type source)
													 helm-type-attributes))
							   (assoc-default 'filtered-candidate-transformer source)
							   (assoc-default 'candidate-transformer source))))
		(cond
		  ((member (cdr (assoc 'name source)) helm-adaptive-enabled-sources)
		   source)
		  ((listp adapt-source)
		   (and (member 'helm-adaptive-sort adapt-source) source))
		  ((eq adapt-source 'helm-adaptive-sort)
		   source)))))

  (setq helm-fuzzy-sort-fn
		(lambda (candidates source &optional use-real)

		  (-> candidates
			  (helm-flx-fuzzy-matching-sort source use-real)
			  (helm-adaptive-sort source)
			  ))
        helm-fuzzy-matching-highlight-fn #'my/helm-fuzzy-highlight-match))

(helm-adaptive-mode 1)
```

If anyone wants to use this, you need to add every source you want to have history for
to the new `helm-adaptive-enabled-sources` variable. After running and interacting for a bit
run `(helm-adaptive-save-history)` and check the contents of  `~/.emacs.d/helm-adaptive-history`
to see if it's working, or examine the `helm-adaptive-history-variable` directly. 

Just making a selection once should bring it up as the first hit next time around for the same query if the source has been added to `helm-adaptive-enabled-sources`.

**Comment by priyadarshan** [comment]
@AlKapote Thanks, this fits my workflow perfectly, too. Perhaps it could be added to `helm-flx` somehow.

**Comment by AlKapote** [comment]
Glad it helps you. It's not really specific to helm-flx, you could use this to add adaptive to any source, if you do the same thing for the default sort function. 
I turned it on for "Emacs Commands" (M-x) too and it saves keystrokes quite nicely, though it's been just a couple of days and problem may surface after more use.

**Comment by halbtuerke** [comment]
> If anyone wants to use this, you need to add every source you want to have history for
to the new helm-adaptive-enabled-sources variable. 

Is there an easy way to find the names of the sources?

**Comment by AlKapote** [comment]
The name appears in the header of the source. To take "helm-M-X" as an example, you'll see "Emacs Commands History" and "Emacs Commands" are the two sources used.

**Comment by halbtuerke** [comment]
Thanks, that is quite easy.
