### ISSUE TITLE
Helm occur - Face of highlighted text for a match

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [emacs-helm/helm#1230]
When using `occur`with helm, if I do `C-z` on a given match Helm displays the buffer with the match. What color is it used to display this match? (seen on yellow on the left in the screenshot below)
<img width="1245" alt="screen shot 2015-10-18 at 5 27 26 pm" src="https://cloud.githubusercontent.com/assets/1993919/10566741/8b0ee228-75bd-11e5-812d-f4328617e9fd.png">

I am hoping to change it, but I am unable to switch windows (i.e. panes) to navigate to the text in yellow to describe the face.

**Comment by thierryvolpiatto** [comment]
Amelio Vazquez-Reina <notifications@github.com> writes:

> When using occurwith helm, if I do C-z on a given match Helm displays
> the buffer with the match. What color is it used to display this
> match? (seen on yellow on the left in the screenshot below) screen
> shot 2015-10-18 at 5 27 26 pm
>
> I am hoping to change it, but I am unable to navigate to the text in
> yellow to describe the face.

The face is `helm-grep-match', you can customize it.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by amelio-vazquez-reina** [comment]
Thanks @thierryvolpiatto I think that face is for the face *on the menu* (i.e. right window in my screenshot). I was hoping to be able to update the face for how things are highlighted on the left in my screenshot (hard to read in my example with green foreground and yellow background)

**Comment by michael-heerdegen** [comment]
The yellow colored face is "helm-selection-line", the match part is "helm-match-item".

If you set "helm-prevent-escaping-from-minibuffer" to t, you can select the "base" buffer and just hit C-u C-x = to find out.

**Comment by michael-heerdegen** [comment]
Oops, set "helm-prevent-escaping-from-minibuffer" to nil of course, t is the default.
