### ISSUE TITLE
Bad assumption in helm--compute-marked

### ISSUE THREAD

**Issue by death** [emacs-helm/helm#1231]
Since https://github.com/emacs-helm/helm/commit/2eec56801a070e6255c1f3526a69eece1d0cbd42 helm assumes the (coerced) selection is a string if wildcard is non-null.  Since in my case I have a list, I get an error:

```
helm--compute-marked: Wrong type argument: stringp, (...)
```

My current workaround is to have another condition-case around the unless form, but there's likely to be a better way...

**Comment by thierryvolpiatto** [comment]
death <notifications@github.com> writes:

> Since 2eec568 helm assumes the (coerced) selection is a string if
> wildcard is non-null. Since in my case I have a list,

Why do you have a list, can you show an example of your code where it
fail ?

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by thierryvolpiatto** [comment]
Also a backtrace would be useful.

Thanks.

**Comment by death** [comment]
Code and backtrace: https://gist.github.com/death/bf4af64d7c3cfcf94fb3
It's a small helm helper for https://github.com/pft/mingus (I have my own patches on top of it, but I don't think they make a difference for this code).
It is possible that I misunderstood something about helm, but this code has been working for me for about a year now.

**Comment by thierryvolpiatto** [comment]
death <notifications@github.com> writes:

> Code and backtrace: https://gist.github.com/death/bf4af64d7c3cfcf94fb3
> It's a small helm helper for https://github.com/pft/mingus (I have my
> own patches on top of it, but I don't think they make a difference for
> this code).  It is possible that I misunderstood something about helm,
> but this code has been working for me for about a year now.

Why are you using :with-wildcard in helm-marked-candidates?
Just removing this flag should work.

I assume that when :with-wildcard is used, candidates are filenames which
generally are strings.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by death** [comment]
Yep, you are right. Thanks!
