### ISSUE TITLE
BUG: helm-match-from-candidates can exceed LIMIT when len(matchfns)>1

### ISSUE THREAD

**Issue by AlKapote** [emacs-helm/helm#1232]
If the first matchfn returns LIMIT candidates, the equality check in [`helm--accumulate-candidates`](https://github.com/emacs-helm/helm/blob/master/helm.el#L3074)
will occur only after the count is incremented for the first hit on the next matchfn. At that point 
the check will always fail and subsequent matchfn will return all they can.
If I change  `helm--accumulate-candidates` and move the check prior to the push the result limit is enforce, but it is also enforced in the initial candidate list passed into it (seems like `helm-search-from-candidate-buffer` is relying on this behavior?) Adding a `when` to the outer loop in [`helm-match-from-candidates`](https://github.com/emacs-helm/helm/blob/master/helm.el#L3117) looks ok.

**Comment by thierryvolpiatto** [comment]
AlKapote <notifications@github.com> writes:

> If the first matchfn returns LIMIT candidates, the equilty check in
> helm--accumulate-candidates will occur only after the count is
> increment for the first hit on the next matchfn.

No, when helm--accumulate-candidates reachs limit it just returns and
helm-match-from-candidates just returns the list of candidates up to
limit.

What make you think there is a bug here ?
Do you have a recipe showing an anormal amount of candidates ?

> At that point the check will always fail and subsequent matcfn will
> return all they can.

No subsequent matches will never happen.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by AlKapote** [comment]
> No, when helm--accumulate-candidates reachs limit it just returns and helm-match-
> from-candidates just returns the list of candidates up to limit.

No, when it reaches the limit it only exits the inner loop it's inside.

> Do you have a recipe showing an anormal amount of candidates ?

```elisp
(setq helm-candidate-number-limit 10)

(helm (helm-build-sync-source
          "M-x "        
        :name "Foo"
        :persistent-action (lambda (candidate)
                             (helm-elisp--persistent-help
                              candidate 'helm-describe-function))
        :nomark t
        :candidates (cl-loop for n in (number-sequence 1 (+ 100 helm-candidate-number-limit ))
                       collect (format "item%d" n))
        :match (list 'identity 'identity)))
```

a query of "1" returns 110 candidates when the limit is 10.

**Comment by thierryvolpiatto** [comment]
AlKapote <notifications@github.com> writes:

>     No, when helm--accumulate-candidates reachs limit it just returns and helm-match-
>     from-candidates just returns the list of candidates up to limit.
>    
> No, when it reaches the limit it only exits the inner loop it's inside.

Hmm, bad indeed, I will look into this more closely ASAP.

Thanks.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by thierryvolpiatto** [comment]
AlKapote <notifications@github.com> writes:

>             (when (< item-count limit)   ; <=======

Applied, thanks.

-- 
Thierry
https://emacs-helm.github.io/helm/
