### ISSUE TITLE
Popwin integration broken

### ISSUE THREAD

**Issue by Pitometsu** [emacs-helm/helm#1239]
![screenshot](http://i.imgur.com/tsWk9rX.png)
On pop-up `helm` buffer it erase all other windows and split current window by two.
[Issue](https://github.com/m2ym/popwin-el/issues/129) for *Popwin*.

**Comment by thierryvolpiatto** [comment]
Netsu <notifications@github.com> writes:

> screensh
> On pop-up helm buffer it erase all other windows and split current window by two.

IIRC you regularly send this bugreport which belong to popwin, not helm.
Also perhaps your helm configuration for windows don't fit well with popwin.
Please close this bugreport.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by Pitometsu** [comment]
@thierryvolpiatto Please, note: this behavior have been *fixed* for my by `Helm Split Window In Side P:` set to `on`. With `off` it's *buggy*.

**Comment by thierryvolpiatto** [comment]
Netsu <notifications@github.com> writes:

> @thierryvolpiatto Please, note: this behavior have been fixed for my
> by Helm Split Window In Side P: set to on. With off it's buggy.

It's not, it is the correct behavior.

-- 
Thierry
https://emacs-helm.github.io/helm/
