### ISSUE TITLE
helm-mode breaks smart-dash-mode badly

### ISSUE THREAD

**Issue by NateEag** [emacs-helm/helm#1240]
If helm-mode and [smart-dash-mode](http://malsyned.net/smart-dash.html) are both activated, opening files breaks.

This is a recent occurrence - I've used them together without issue for a very long time.

Here's a script for a clean reproduction of the issue (tested on Emacs 24.4, OS X 10.6.8):

```bash
#! /bin/bash

# Recipe to reproduce helm breaking smart-dash-mode.

if [ ! -d helm ]; then
    git clone https://github.com/emacs-helm/helm.git

    pushd helm
    make
    popd
fi

if [ ! -f smart-dash-mode.tar.gz ]; then
    curl -L http://bitbucket.org/malsyned/smart-dash/get/tip.tar.gz > smart-dash-mode.tar.gz
fi

if [ ! -d smart-dash-mode ]; then
    tar -xzf smart-dash-mode.tar.gz
    mv malsyned-smart-dash-* smart-dash-mode
fi

cat > init.el <<EOF
(require 'helm-config)
(require 'smart-dash)
(helm-mode 1)
(smart-dash-mode)
EOF

emacs -Q -L helm/ -L smart-dash-mode/ \
      -l "init.el"

# After boot:
#
# C-x b <RET>
# C-x b <RET>
# C-x C-f
#
# The minibuffer will show the error
#
# Wrong type argument: consp, nil
```

It looks to me like helm-mode is removing one of smart-dash-mode's minibuffer hooks (it installs one in `minibuffer-setup-hook` and `minibuffer-exit-hook`).

[This line in helm-mode.el](https://github.com/emacs-helm/helm/blob/master/helm-mode.el#L693) seems likely to be at fault, but I haven't had time to dig further.

**Comment by thierryvolpiatto** [comment]
Nate Eagleson <notifications@github.com> writes:

> If helm-mode and smart-dash-mode are both activated, opening files breaks.
> This line in helm-mode.el seems likely to be at fault, but I haven't had time to dig further.

I didn't try to reproduce with your script above, but yes helm-mode was
removing all hooks from minibuffer-setup-hook.
I have commited a change that should fix your issue, please let me know
if now your mode is working aside helm-mode.

Thanks.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by NateEag** [comment]
Yep, that seems to have solved it.

Thanks!
