### ISSUE TITLE
debugging functions called within a helm session

### ISSUE THREAD

**Issue by ghost** [emacs-helm/helm#1241]
@thierryvolpiatto, I'd like to use edebug to break in a function called by helm when invoked,
but some kind of timer always kicks in and interrupts this. Is there some variable I can set?

**Comment by michael-heerdegen** [comment]
Completion is performed in a timer.  That can be a problem when debugging.  Maybe setting "helm-input-idle-delay" and/or "helm-idle-delay" to a really large value can help in your specific case.  Depends on which part of the code you need to debug.
