### ISSUE TITLE
Not closed recent buffers

### ISSUE THREAD

**Issue by Pitometsu** [emacs-helm/helm#1243]
![screenshot](http://i.imgur.com/YObe48O.png)
Few recent `*helm ...` buffers still in list.
Is it correct behavior, shouldn't it be closed?

**Comment by thierryvolpiatto** [comment]
Netsu <notifications@github.com> writes:

> screensh
> Few recent *helm ... buffers still in list.
> Is it correct behavior,

Yes.

> shouldn't it be closed?

No.

-- 
Thierry
https://emacs-helm.github.io/helm/
