### ISSUE TITLE
helm-org regression

### ISSUE THREAD

**Issue by simonthum** [emacs-helm/helm#1246]
Today I updated helm and lost my ability to helm search over my agenda files. I don't know the previous version, it might be a bit older since the helm view shew or searched only a single level heading.

Anyway, I get an opaque error that (to me at least) suggests the heading's depth may be a problem, and indeed it is. Explicitly passing a much larger max-depth (16) to `helm-source-org-headings-for-files` makes it work again, although the heading in Question is only level 9.

In general, I would have expected the max depth to be a limit for discovery, not for failure.

This might be an Org problem too, but it happened with the upgrade so I'm reporting here. IMO it either needs clarification or a fix.

Org-mode is Org-mode version 8.3.2 (release_8.3.2-6-g72c5d8 @ /home/... i.e. with some local additions.

```
Debugger entered--Lisp error: (args-out-of-range "LoD" 0 -3)
  substring("LoD" 0 -6)
  (setq h (substring h 0 (- maxwidth 2)) total (+ total maxwidth 1))
  (if (< (length h) maxwidth) (progn (setq total (+ total (length h) 1)) h) (setq h (substring h 0 (- maxwidth 2)) total (+ total maxwidth 1)) (if (string-match "[ 	]+\\'" h) (setq h (substring h 0 (match-beginning 0)))) (setq h (concat h "..")))
  (lambda (h) (setq n (1+ n)) (if (and (= n nsteps) (< maxwidth 10000)) (setq maxwidth (- total-width total))) (if (< (length h) maxwidth) (progn (setq total (+ total (length h) 1)) h) (setq h (substring h 0 (- maxwidth 2)) total (+ total maxwidth 1)) (if (string-match "[ 	]+\\'" h) (setq h (substring h 0 (match-beginning 0)))) (setq h (concat h ".."))) (org-add-props h nil (quote face) (nth (% (1- n) org-n-level-faces) org-level-faces)) h)("LoD")
  mapconcat((lambda (h) (setq n (1+ n)) (if (and (= n nsteps) (< maxwidth 10000)) (setq maxwidth (- total-width total))) (if (< (length h) maxwidth) (progn (setq total (+ total (length h) 1)) h) (setq h (substring h 0 (- maxwidth 2)) total (+ total maxwidth 1)) (if (string-match "[ 	]+\\'" h) (setq h (substring h 0 (match-beginning 0)))) (setq h (concat h ".."))) (org-add-props h nil (quote face) (nth (% (1- n) org-n-level-faces) org-level-faces)) h) (#("CityServer3D" 0 12 (face org-level-1)) #("Archive" 0 7 (face org-level-2)) #("Portrayal" 0 9 (face org-level-3)) #("Konzeption" 0 10 (face org-level-4)) #("Symbolizer" 0 10 (face org-level-5)) "Einsatzgebiete" "LoD") "/")
  (concat prefix (if prefix (or separator "/")) (mapconcat (function (lambda (h) (setq n (1+ n)) (if (and (= n nsteps) (< maxwidth 10000)) (setq maxwidth (- total-width total))) (if (< (length h) maxwidth) (progn (setq total (+ total ... 1)) h) (setq h (substring h 0 (- maxwidth 2)) total (+ total maxwidth 1)) (if (string-match "[ 	]+\\'" h) (setq h (substring h 0 ...))) (setq h (concat h ".."))) (org-add-props h nil (quote face) (nth (% (1- n) org-n-level-faces) org-level-faces)) h)) path (or separator "/")))
  (let* ((nsteps (length path)) (total-width (+ nsteps (apply (quote +) (mapcar (quote length) path)))) (maxwidth (if (<= total-width width) 10000 (/ (- width nsteps) nsteps))) (org-odd-levels-only nil) (n 0) (total (1+ (length prefix)))) (setq maxwidth (max maxwidth 10)) (concat prefix (if prefix (or separator "/")) (mapconcat (function (lambda (h) (setq n (1+ n)) (if (and (= n nsteps) (< maxwidth 10000)) (setq maxwidth (- total-width total))) (if (< (length h) maxwidth) (progn (setq total ...) h) (setq h (substring h 0 ...) total (+ total maxwidth 1)) (if (string-match "[ 	]+\\'" h) (setq h ...)) (setq h (concat h ".."))) (org-add-props h nil (quote face) (nth (% ... org-n-level-faces) org-level-faces)) h)) path (or separator "/"))))
  (if (not path) (or prefix "") (let* ((nsteps (length path)) (total-width (+ nsteps (apply (quote +) (mapcar (quote length) path)))) (maxwidth (if (<= total-width width) 10000 (/ (- width nsteps) nsteps))) (org-odd-levels-only nil) (n 0) (total (1+ (length prefix)))) (setq maxwidth (max maxwidth 10)) (concat prefix (if prefix (or separator "/")) (mapconcat (function (lambda (h) (setq n (1+ n)) (if (and ... ...) (setq maxwidth ...)) (if (< ... maxwidth) (progn ... h) (setq h ... total ...) (if ... ...) (setq h ...)) (org-add-props h nil (quote face) (nth ... org-level-faces)) h)) path (or separator "/")))))
  org-format-outline-path((#("CityServer3D" 0 12 (face org-level-1)) #("Archive" 0 7 (face org-level-2)) #("Portrayal" 0 9 (face org-level-3)) #("Konzeption" 0 10 (face org-level-4)) #("Symbolizer" 0 10 (face org-level-5)) "Einsatzgebiete" "LoD") 80 "projects.org:")
  helm-get-org-candidates-in-file("/home/simon/org/fraunhofer/projects.org" 1 8 nil nil)

```

**Comment by thierryvolpiatto** [comment]
simonthum <notifications@github.com> writes:

> Today I updated helm and lost my ability to helm search over my agenda
> files. I don't know the previous version, it might be a bit older
> since the helm view shows/ searched only a single level heading.

Looks like the error is coming from org itself
(org-format-outline-path).

> Anyway, I get an opaque error that (to me at least) suggests the
> heading's depth may be a problem, and indeed it is.

From where comes this error, helm or org?

> Explicitly passing a much larger max-depth (16) to
> helm-source-org-headings-for-files makes it work again, although the
> heading in Question is only level 9.

Can you provide a sample org file where I can reproduce ?

> In general, I would have expected the max depth to be a limit for
> discovery, not for failure.

Yes but it looks like a org error, perhaps our code is no more supported
in new org versions due to incompatible changes as they regularly do?

> Org-mode is Org-mode version 8.3.2 (release_8.3.2-6-g72c5d8 @ /home/... i.e. with some local additions.

Ah! here it is 8.2.10, perhaps it is why I can't reproduce.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by simonthum** [comment]
I'll make myself a clean user for those emacs SSECE/MCVE/MWEs. But don't expect anything before Wednesday.

**Comment by simonthum** [comment]
OK, for ehatever eason it now breaks consistently, no matter what that depth argument is. I'm bringing this to the Org mode list.

FWIW, I was on Org 8.3 beta when it still worked. Then it broke when I upgraded helm. In response I upgraded to 8.3.2. So I suppose the bug must have been introduced between 8.3 beta and your version.

**Comment by simonthum** [comment]
It's window-width which governs this bug. Increasing my window size "fixes" it, meaning `org-outline-path` needs improvement not to descend into illegal calls.

Perhaps helm-org could use a min-width or fixed width? After all, I want my search results to be independent from the window width.

I'm closing though, for me it's reasonably fixed from a helm-org perspective.
