### ISSUE TITLE
'helm-occur' produces no results when searching for Unicode characters

### ISSUE THREAD

**Issue by promethial** [emacs-helm/helm#1247]
I'm unable to search for Unicode characters using `helm-occur`. For example, searching in the buffer for ⟹ ("long rightwards double arrow", U+27F9) produces no results.

Emacs version: 24.4
Helm version: 20141123.57

**Comment by xuchunyang** [comment]
`helm-occur` didn't get started to search because the length of your input is less than two, so for now you have to type at least one more character. However, I think your request still makes sense.

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

> helm-occur didn't get started to search because the length of your
> input is less than two, so for now you have to type at least one more
> character.

e.g "⟹+"

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by promethial** [comment]
@thierryvolpiatto and @xuchunyang, thanks for the speedy response. The two character constraint slipped my mind, and the Regex solution does work.

Excellent work on Helm. I've only begun to explore its functionality, and I'm hooked!
