### ISSUE TITLE
helm-dabbrev-always-search-all has no effect

### ISSUE THREAD

**Issue by jguenther** [emacs-helm/helm#1248]
As far as I can tell from the documentation, setting `helm-dabbrev-always-search-all` to non-nil should make `helm-dabbrev` try to expand symbols in all buffers regardless of any of the other settings, but this does not work.

Also, is there a way to customize the sources that `helm-dabbrev` uses? I'd like to replace `hippie-expand` with `helm-dabbrev`.

**Comment by thierryvolpiatto** [comment]
Justin Guenther <notifications@github.com> writes:

> As far as I can tell from the documentation, setting
> helm-dabbrev-always-search-all to non-nil should make helm-dabbrev try
> to expand symbols in all buffers regardless of any of the other
> settings, but this does not work.

When non-nil helm-dabbrev search in all buffers in addition of
current-buffer and it does (perhaps the helm tool I use the most).
Not sure what you are expecting with "expand all symbols".
Try to put a silly word in any of your buffer (not current-buffer) and
try to complete in current-buffer this same word, you will see
helm-dabbrev find it.

> Also, is there a way to customize the sources that helm-dabbrev uses?

No.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by jguenther** [comment]
Not sure what you mean by "expand all symbols", my use case in the original report was to expand a lisp symbol that's present in a different buffer than `current-buffer`, but this issue also applies to expanding words in `fundamental-mode`, etc.

I'm still having this issue. I'm running homebrew emacs 25.0.50 (built off HEAD at commit `54e2ed9`), if that helps, but I've also tried several different emacs-25 builds off of http://emacsformacosx.com/builds/. What version did you try?

Here are the reproduction steps that I used:

* using emacs 25
* start with `emacs -Q`

```lisp
(require 'helm-config)
(require 'helm-dabbrev)
(setq helm-dabbrev-always-search-all t)
(global-set-key (kbd "M-/") 'helm-dabbrev)
;; create a new buffer, insert some text that isn't in the original buffer
;; type the first few characters of the inserted word in the original buffer
;; M-/
;; ==> word isn't expanded as expected
;; echo area error => "[Helm-dabbrev: No expansion found]"
```

Please let me know if you need any more information. I tried using `Edebug` to find the cause of this bug but I wasn't successful.

> No.

Would you consider merging a PR to implement customizable sources for `helm-dabbrev` if I were to prepare one? (assuming the implementation is reasonable etc.) This is something that I'd definitely find useful.

**Comment by thierryvolpiatto** [comment]
Justin Guenther <notifications@github.com> writes:

> Not sure what you mean by "expand all symbols", my use case in the original report was to expand a lisp symbol that's present in a different buffer than
> current-buffer, but this issue also applies to expanding words in fundamental-mode, etc.
>
> I'm still having this issue. I'm running homebrew emacs 25.0.50 (built off HEAD at commit 54e2ed9), if that helps, but I've also tried several different emacs-25
> builds off of http://emacsformacosx.com/builds/. What version did you try?
>
> Here are the reproduction steps that I used:
>
>   * using emacs 25
>   * start with emacs -Q
>
> (require 'helm-config)
> (require 'helm-dabbrev)
> (setq helm-dabbrev-always-search-all t)
> (global-set-key (kbd "M-/") 'helm-dabbrev)

You can use directly emacs-helm.sh.

> ;; create a new buffer, insert some text that isn't in the original
> buffer

What is the original buffer ?

> Would you consider merging a PR to implement customizable sources for
> helm-dabbrev if I were to prepare one?

I am not sure what you want to customize, but take in account the cyclic
completion, if you move out the source, be sure to know what you do
otherwise you will break all the logic of this.
So yes I am reluctant to changes on this as it is working fine as it is.


-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by jguenther** [comment]
> What is the original buffer ?

I can reproduce this in all major modes I've tried. In that example, the original buffer was `*scratch*`, but I also tried others. I tried `helm-dabbrev` using word prefixes in python, help mode, elisp, fundamental, and maybe a couple more modes.

> I am not sure what you want to customize, but take in account the cyclic completion, if you move out the source, be sure to know what you do otherwise you will break all the logic of this. So yes I am reluctant to changes on this as it is working fine as it is.

I wouldn't change the default behaviour. I'd like to customize the sources that `helm-dabbrev` uses for completion, similar to `hippie-expand`. *e.g.* all lisp symbols, kill ring contents, etc. If the default behaviour doesn't change at all, would you consider a PR to implement that functionality?

**Comment by thierryvolpiatto** [comment]
Justin Guenther <notifications@github.com> writes:

>     What is the original buffer ?
>    
> I can reproduce this in all major modes I've tried. In that example,
> the original buffer was *scratch*, but I also tried others. I tried
> helm-dabbrev using word prefixes in python, help mode, elisp,
> fundamental, and maybe a couple more modes.

Please be clear, start with a recipe e.g:

- In *scratch* buffer I have the word "awordicantfindanywhereelse"
- I create a new buffer (in which mode?)
- I start writing "awordic", hit "M-/" (helm-dabbrev) and I expect
  helm-dabbrev complete to complete to "awordicantfindanywhereelse".

Keep in mind your new buffer have to be in the same mode than the
scratch buffer, i.e `lisp-interaction-mode', or associed to
`lisp-interaction-mode' according to `helm-dabbrev-major-mode-assoc'.
 
> I wouldn't change the default behaviour. I'd like to customize the
> sources that helm-dabbrev uses for completion, similar to
> hippie-expand. e.g. all lisp symbols, kill ring contents, etc. If the
> default behaviour doesn't change at all, would you consider a PR to
> implement that functionality?

No, thanks, I want helm-dabbrev completing only dabbrev completion.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by jguenther** [comment]
> Keep in mind your new buffer have to be in the same mode than the scratch buffer, i.e `lisp-interaction-mode', or associed to `lisp-interaction-mode' according to `helm-dabbrev-major-mode-assoc'.

That's not what the documentation for `helm-dabbrev-always-search-all` says:

> helm-dabbrev-always-search-all is a variable defined in `helm-dabbrev.el'.
> Its value is t

> Documentation:
> Always search in **all buffers** when non--nil.
> Note that even if nil, a search in all buffers
> will occur if the length of candidates is <= than
> `helm-dabbrev-max-length-result'.

Is this the expected behaviour, that `helm-dabbrev-always-search-all` only searches buffers in the current major mode? Should the docstring instead say something like "always search in all buffers with the same major mode as the current buffer"?

> No, thanks, I want helm-dabbrev completing only dabbrev completion.

Again, I'm not proposing that `helm-dabbrev`'s default behaviour change in the least, but simply that the sources that it uses be customizable. I don't think i'm the only helm user that wants this functionality, and it seems like a waste of effort to create an entire package around this feature rather than add it as an optional feature of `helm-dabbrev`.

Is there a specific reason you don't want to accept a PR to allow this customization, other than that you don't personally want to use it?

**Comment by thierryvolpiatto** [comment]
Justin Guenther <notifications@github.com> writes:

> Is this the expected behaviour, that helm-dabbrev-always-search-all
> only searches buffers in the current major mode?

IIRC yes.

> Should the docstring instead say something like "always search in all
> buffers with the same major mode as the current buffer"?

Probably yes.

> Again, I'm not proposing that helm-dabbrev's default behaviour change
> in the least, but simply that the sources that it uses be
> customizable.

I know what you want, as soon this variable will be enabled, many users
will jump on it, add many sources to it and then send bug report telling
this is too slow, or just not working, so no thanks.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by jguenther** [comment]
> I know what you want, as soon this variable will be enabled, many users
will jump on it, add many sources to it and then send bug report telling
this is too slow, or just not working, so no thanks.

Is it your general policy not to accept PRs that implement new functionality, then?

**Comment by thierryvolpiatto** [comment]
Justin Guenther <notifications@github.com> writes:

> Is it your general policy not to accept PRs that implement new functionality, then?

No, but by experience I know which ones will give me more work for
something I will not use.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by jganong** [comment]
i think what the OP needs is this:

 '(helm-dabbrev-related-buffer-fn (quote nil)))

This makes it so all buffers and considered for abbrevs.
