### ISSUE TITLE
Helm C-x k

### ISSUE THREAD

**Issue by Pitometsu** [emacs-helm/helm#1249]
`kill-buffer` for `helm-mode` slow as hell because of history perhaps.
I got the [same problem](http://stackoverflow.com/questions/18490534/emacs-and-helm-how-to-not-show-buffer-history-when-i-do-kill-buffer), so is it possible just turn off history for kill-buffer?

**Comment by xuchunyang** [comment]
> kill-buffer for helm-mode slow as hell because of history perhaps.

It is not slow at all for me, the length of my `buffer-name-history` is 431, and `helm-mode-fuzzy-match` and `helm-candidate-number-limit` are kept as defaults.

> I got the same problem,

Now, helm-mode displays history source at the bottom (not the top) by default, so that problem doesn't make sense any more.

**Comment by Pitometsu** [comment]
Hm, strange, after some time from launch, it becomes more and more slow, and then it even not show buffers at all.

**Comment by thierryvolpiatto** [comment]
Netsu <notifications@github.com> writes:

> kill-buffer for helm-mode slow as hell because of history perhaps.
> I got the same, so is it possible just turn off history for kill-buffer?

Not reproductible too, please always use ./emacs-helm.sh if possible to
see if your bug is reproductible there.

-- 
Thierry
https://emacs-helm.github.io/helm/
