### ISSUE TITLE
Helm completion for arbitrary word order

### ISSUE THREAD

**Issue by Pitometsu** [emacs-helm/helm#1251]
Is it possible to customize *helm* in next way (I remember, *anything* have work like this):

When I type:
```
foo bar
```
I got:
```
toolbar-footer
```

Now I can use:
```
foo\|bar
```
But matched regions is not highlighted.

**Comment by thierryvolpiatto** [comment]
Netsu <notifications@github.com> writes:

> Is it possible to customize helm in next war (I remember, anything have work like this):
> When I type:
>
> foo bar
>
> I got:
>
> toolbar-footer

Of course, there is nothing to customize:

M-x file find => find-file

> Now I can use:
>
> foo\|bar

No just enter a space.

NOTE: 
Highlighting is not fully working in multi regexp matching and fuzzy
matching.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by Pitometsu** [comment]
@thierryvolpiatto Maybe I mistaken because for `M-x file find` it highlight `file` only somewhy. Or it's just for me?

**Comment by thierryvolpiatto** [comment]
Netsu <notifications@github.com> writes:

> @thierryvolpiatto Maybe I mistaken because for M-x file find it
> highlight file only somewhy. Or it's just for me?

No, it is not just you, as I said highlihting is not always right
actually.

So M-x file find

=> find-file
        ^^^^

Only "file" is highlighted, but "find" and "file" should be highlighted.

Otherwise, multi matching is working as expected everywhere.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by Pitometsu** [comment]
@thierryvolpiatto thanks. So, only highlighting don't work well, for me it's ok. You may close issue, please, or just leave it as a highlighting bug, up to you.

**Comment by thierryvolpiatto** [comment]
Netsu <notifications@github.com> writes:

> @thierryvolpiatto thanks. So, only highlighting don't work well, for
> me it's ok. You may close issue, please, or just leave it as a
> highlighting bug, up to you.

Highlighting should be fixed now, at least for such case, please confirm
and close if working fine for you.

Thanks.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by Pitometsu** [comment]
For space work, for `\|` -- no.

**Comment by Pitometsu** [comment]
Also `helm-flx` broke it.

**Comment by thierryvolpiatto** [comment]
Netsu <notifications@github.com> writes:

> For space work, for \| -- no.

It is working as expected with e.g "file\|find", in this case only find
should be highlighted.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by thierryvolpiatto** [comment]
Netsu <notifications@github.com> writes:

> Also helm-flx broke it.

I am not concerned by this.

-- 
Thierry
https://emacs-helm.github.io/helm/
