### ISSUE TITLE
Action the # candidate directly [1-9] ?

### ISSUE THREAD

**Issue by xuchunyang** [emacs-helm/helm#1257]
Number the first 9 visible candidates and assign <kbd>M-1</kbd> ~ <kbd>M-9</kbd> for them, for example, <kbd>M-5</kbd> to select `client.c` and execute its default action, this way a little more convenient than enter "client" into minibuffer to continue to filter or run <kbd>C-n</kbd> for 4 times.

![2015-11-05 2 00 46](https://cloud.githubusercontent.com/assets/4550353/10961157/a96f7bee-83c6-11e5-9dab-f5bb4fbd3b05.png)

---

(I've tried to implemented for several times but have always ended in failure.)

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

> Number the first 9 visible candidates and assign M-1 ~ M-9 for them,
> for example, M-5 to select client.c and execute its default action,
> this way a little more convenient than enter "client" into minibuffer
> to continue to filter or run C-n for 4 times.

This was existing in original version of "anything".
I removed it when I started cleaning "anything" which was a mess.
Perhaps we can reenable it now, (you will find it in early versions of
anything.el in our git history) but perhaps using a new code not
limiting us to first 9 by taking advantage of linum-relative.el.
(actually with linum-relative-mode enabled, you can do C-u 5 C-n RET to
execute default action on the nth 5 candidates starting from selection)

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by xuchunyang** [comment]
> Perhaps we can reenable it now

Yes, I'd like to have it.

> you will find it in early versions of anything.el in our git history

I've found it (controlled by variable [`anything-enable-shortcuts`](https://github.com/emacs-helm/helm/blob/970de92/anything.el#L146-L147)).

> but perhaps using a new code not
> limiting us to first 9 by taking advantage of linum-relative.el.

9 is just a reasonable default since its display-width is one and corresponding key bindings can be very  straightforward, e.g., use M-1 ~ M-9 or C-1 ~ C-9.

> (actually with linum-relative-mode enabled, you can do C-u 5 C-n RET to
> execute default action on the nth 5 candidates starting from selection)

This is a different way, though it might be handy as well. I want to count candidate from the beginning of helm-window (in other word, the first visible candidate to the user).

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

> 9 is just a reasonable default since its display-width is one and
> corresponding key bindings can be very straightforward, e.g., use M-1
> ~ M-9 or C-1 ~ C-9.

Agree.

>     (actually with linum-relative-mode enabled, you can do C-u 5 C-n RET to
>     execute default action on the nth 5 candidates starting from selection)
>    
> This is a different way, though it might be handy as well. I want to
> count candidate from the beginning of helm-window (in other word, the
> first visible candidate to the user).

Yes but with the linum-relative-mode it is exactly the same when
selection is on top and when the selection is lower you could count from
there ;-)

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by issue-dispenser** [comment]
Would this be disabled in helm-M-x where M-# would give a prefix argument to the candidate? Otherwise this sounds nice.

**Comment by thierryvolpiatto** [comment]
issue-dispenser <notifications@github.com> writes:

> Would this be disabled in helm-M-x where M-# would give a prefix
> argument to the candidate?

Why ?

The new function should accept prefix arg (just like helm-next-line
does), so C-u M-4 would pass '(4) to the 4th command after selection.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by thierryvolpiatto** [comment]
Thierry Volpiatto <thierry.volpiatto@gmail.com> writes:

> issue-dispenser <notifications@github.com> writes:
>
>> Would this be disabled in helm-M-x where M-# would give a prefix
>> argument to the candidate?
>
> Why ?
>
> The new function should accept prefix arg (just like helm-next-line
> does), so C-u M-4 would pass '(4) to the 4th command after selection.

Of course M-n is not a good example for a key because it is itself a
prefix arg, perhaps it is what you mean ?

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by thierryvolpiatto** [comment]
Here a sample code:

(defun helm-execute-selection-action-at-nth (linum)
  (let ((prefarg current-prefix-arg))
    (if (>= linum 0)
        (helm-next-line linum)
        (helm-previous-line (lognot (1- linum))))
    (setq current-prefix-arg prefarg)
    (helm-exit-minibuffer)))

(dotimes (n 9)
  (let* ((key (format "C-c %d" n))
         (key- (format "C-x %d" n))
         (fn (lambda () (interactive) (helm-execute-selection-action-at-nth n)))
         (fn- (lambda () (interactive) (helm-execute-selection-action-at-nth (- n)))))
    (define-key helm-map (kbd key) fn)
    (define-key helm-map (kbd key-) fn-)))

With this you can do C-x 5 which execute default action on the 5th
candidate BEFORE selection, and C-c 5 which execute default action on
the 5th candidate AFTER selection. 

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by issue-dispenser** [comment]
>Of course M-n is not a good example for a key because it is itself a
prefix arg, perhaps it is what you mean ?

Yes, I think it's too commonly used as a prefix to be used as a special key here. Perhaps C-M-# (which also is globally bound to digit-argument) would be better than just M-# as it's probably used less commonly as a prefix arg.

Your code seems to work nicely (I believe it has to be (dotimes (n 10)...).
Though I would think that C-x 0 or C-c 0 would just select the current candidate (currently it selects the next).

**Comment by thierryvolpiatto** [comment]
issue-dispenser <notifications@github.com> writes:

>     Of course M-n is not a good example for a key because it is itself a
>     prefix arg, perhaps it is what you mean ?
>    
> Yes, I think it's too commonly used as a prefix to be used as a
> special key here.

Yes of course and it would fail in helm-M-x (it will understand it as a
prefix arg).

> Perhaps C-M-# (which also is globally bound to digit-argument) would
> be better than just M-# as it's probably used less commonly as a
> prefix arg.

Hmm, no, in addition it is very difficult to type on non US keyboards 
(on my keyboard I have to press Ctrl Shift Alt and num simultaneously!).

> Your code seems to work nicely (I believe it has to be (dotimes (n
> 10)...).  Though I would think that C-x 0 or C-c 0 would just select
> the current candidate (currently it selects the next).

Yeah, I quickly wrote it as example, need to be polished.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by cute-jumper** [comment]
This feature would be nice. IIRC, `anything.el` can use either number or letter to select a candidate. I wrote [ace-jump-helm-line](https://github.com/cute-jumper/ace-jump-helm-line) which does a similar thing, but its implementation is too simple, and using [avy](https://github.com/abo-abo/avy) is kind of too heavy for this simple task. A helm built-in function would be much better.

**Comment by manuel-uberti** [comment]
I agree with @cute-jumper, this one would be a nice add.

**Comment by thierryvolpiatto** [comment]
This would not be very helpful as some source popup with a preselection very far from the first 9 cands.
What is needed is a function that allow jumping to <n> candidates from selection (not from top).
If you use linum-relative-mode + the code I provided above (slighly modified) you can already do this.
What I want now is overlay displaying the first and previous 9 candidates from selection (similar to linum-relative but only for 9 first and previous).

**Comment by thierryvolpiatto** [comment]
I have merged the code above (slighly modified), so one can now use it with linum-relative to visualize first and previous nine candidates.

C-x <n> => execute default action on <n> number candidate before selection.
C-c <n> => execute default action on <n> number candidate after selection.

**Comment by thierryvolpiatto** [comment]
Now linum-relative have a minor-mode (not global) and a global-minor-mode, so one can enable linum-relative only for helm with something like this:

```elisp
(defun helm--turn-on-linum-relative ()
  (with-helm-buffer (linum-relative-mode 1)))

(define-minor-mode helm-linum-relative-mode
    "Turn on linum-relative in helm.
Allow to execute default action on nth candidate.
Commands prefixed with C-x will use nth candidate before selection
the ones prefixed with C-c will use nth candidate after selection."
  :group 'helm
  (if helm-linum-relative-mode
      (progn
        (add-hook 'helm-after-initialize-hook 'helm--turn-on-linum-relative)
        (add-hook 'helm-after-preselection-hook 'linum-relative-for-helm))
      (remove-hook 'helm-after-initialize-hook 'helm--turn-on-linum-relative)
      (remove-hook 'helm-after-preselection-hook 'linum-relative-for-helm)))

```
Don't know yet if I have to integrate such code in helm, will see.

**Comment by thierryvolpiatto** [comment]
Closing now as `helm-linum-relative-mode` is now part of linum-relative, thanks @coldnew.
