### ISSUE TITLE
Default tag suggested by emacs is ignored by find tag when helm-mode on

### ISSUE THREAD

**Issue by joeforan** [emacs-helm/helm#1259]
This issue occurs when using gtags. When pressing  M-. over a token in source code, that becomes the default token suggested by emacs. With helm-mode off , pressing enter initiates the search for that default token, however with helm-mode on the first token in the *helm-mode-gtags-find-tag* buffer is searched for which is confusing.
I suggest either removing the default message from the prompt in the message buffer or using the default that emacs picks.

**Comment by thierryvolpiatto** [comment]
joeforan <notifications@github.com> writes:

> This issue occurs when using gtags. When pressing M-. over a token in
> source code, that becomes the default token suggested by emacs. With
> helm-mode off , pressing enter initiates the search for that default
> token, however with helm-mode on the first token in the
> helm-mode-gtags-find-tag buffer is searched for which is confusing.  I
> suggest either removing the default message from the prompt in the
> message buffer or using the default that emacs picks.


AFAIK the first that comes in the helm-buffer is the default that emacs
uses, isn't it ?
So what's the problem? I don't understand.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by joeforan** [comment]
That's not the behaviour I see. 
In my setup the first tag in the helm-buffer is a completely different tag. For the project I'm working on it's always the same tag so I assume it's the first one defined in the GTAGS file.

**Comment by thierryvolpiatto** [comment]
Because you are using gtags with helm for etags, IIRC there is a helm package for gtags somewhere.
We don't support gtags actually in helm.

**Comment by thierryvolpiatto** [comment]
My suggestion is that you disable helm for find-tag.
