### ISSUE TITLE
helm-timers confused by buffer-local timers with buffers with * or $ in the name?

### ISSUE THREAD

**Issue by jgarvin** [emacs-helm/helm#1260]
When I open helm-timers and press any key to start the pattern I [immediately get this backtrace](https://gist.github.com/jgarvin/6330d44f50f9684b5a26). Sometimes the buffer referenced at the top of the trace changes but it appears to always be buffers with '$' or '*' in their name that were created by my elisp code and have defvar-local timers.

**Comment by manuel-uberti** [comment]
I can confirm is happening to me too, using latest Helm from MELPA on Emacs 25.0.50.1
