### ISSUE TITLE
Accidentally selecting the helm window

### ISSUE THREAD

**Issue by aaronjensen** [emacs-helm/helm#1262]
Hi, I'm new to emacs and have started out with spacemacs. I've accidentally selected the helm window with the mouse a couple of times now. I believe that the way to do it is to open helm, then click and drag with the mouse. This will select the helm window. Once that window is selected, you are stuck. `C-g`, `ESC`, etc do nothing. I can type in the helm window, but I cannot move around. Nothing I knew how to do at the time got me out, so I ended up having to close the window. I know now that I can `switch-to-minibuffer-window`, but it'd be nice if it was either impossible to select the window or very easy/intuitive to get back to the minibuffer.

Reference issue in spacemacs: https://github.com/syl20bnr/spacemacs/issues/3700 which contains a suggestion to add `(no-other-window . t)` to helm windows, which may help.

Thanks!

**Comment by michael-heerdegen** [comment]
Hello,

actually, the default behavior in Helm is exactly as you want, you can click and drag with the mouse in any window you like, the minibuffer is always active.  So it must be a spacemacs issue.  Will join the discussion there, thanks.

**Comment by thierryvolpiatto** [comment]
Aaron Jensen <notifications@github.com> writes:

> Hi, I'm new to emacs and have started out with spacemacs. I've
> accidentally selected the helm window with the mouse a couple of times
> now. I believe that the way to do it is to open helm, then click and
> drag with the mouse. This will select the helm window. Once that
> window is selected, you are stuck. C-g, ESC, etc do nothing. I can
> type in the helm window, but I cannot move around. Nothing I knew how
> to do at the time got me out, so I ended up having to close the
> window. I know now that I can switch-to-minibuffer-window, but it'd be
> nice if it was either impossible to select the window or very
> easy/intuitive to get back to the minibuffer.

It is impossible to select helm-window, if from spacemacs it is
possible, ask the guy at spacemacs.

-- 
Thierry
https://emacs-helm.github.io/helm/
