### ISSUE TITLE
Provide a way to dynamically increase helm-candidate-number-limit

### ISSUE THREAD

**Issue by uu1101** [emacs-helm/helm#1264]
For some sources, there are a large number of candidates that, even after filtering, the user needs to browse in order to decide which one is desired.  For example, using `helm-ucs` one might use "arrow" as a filter and then browse the (dozens) of arrow shapes available until deciding which one to insert.  For this use, `helm-candidate-number-limit` is too strict: it is not possible to inspect more than that number of candidates specified, so many of them are "unreachable" unless one knows in advance the details to filter on.

Having a key binding (or perhaps having a bogus candidate `more...` at the end, as happens in some web pages) inserting another number of candidates would make browsing this kind of collections more discoverable.

Thank you,
uu1101

**Comment by thierryvolpiatto** [comment]
You can actually use `C-M-a` to display all candidates, but yes increasing only the number of candidates to display would be more efficient, I will consider this and try to find a way to provide this ASAP.

Thanks.

**Comment by thierryvolpiatto** [comment]
Ah! I forget I already implemented this with `C-u <n> C-M a` where <n> is the numeric prefix arg.

**Comment by uu1101** [comment]
Ah!  Thank you very much!
