### ISSUE TITLE
Buffer highlighting is lost when Helm buffer opened

### ISSUE THREAD

**Issue by mattford63** [emacs-helm/helm#1265]
Is there a regression of 

https://github.com/emacs-helm/helm/issues/690

the code I have has the fixes from the referenced patch but I loose the visual display of the region selected when using `helm M-x`.

It's particularly annoying when using `M-x comment-region`

GNU Emacs 24.5.1 (x86_64-redhat-linux-gnu, GTK+ Version 3.17.8)
 helm               20151106.2158 installed

**Comment by michael-heerdegen** [comment]
I think you mean something different than what the problem had been in the issue you posted.

In your scenario, the region is not deactivated (M-x comment-region works as expected), but while you enter the command name in the minibuffer, the highlighting of the region is (temporarily) gone.  At least that's what I see when testing with emacs-helm.sh.

Is this a correct description of your issue?

**Comment by mattford63** [comment]
Hi yes that's spot on.

**Comment by michael-heerdegen** [comment]
We can probably fix this, but I want to wait for Thierry's opinion -
dunno if the behavior is intended or a side effect of something we want.

**Comment by thierryvolpiatto** [comment]
Take two windows displaying two differents buffers, mark region in one of these two buffers, switch to the other buffer, what is happening ?
You will see your region is not lost when switching back to the buffer with marked region, so what is the problem ?

**Comment by michael-heerdegen** [comment]
Nothing if you are a computer.  But as a human, you don't see what you are about to do (in the OPs case, commenting) when giving the command in the minibuffer.
That's a detail, but a justified one.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Nothing if you are a computer. But as a human, you don't see what you
> are about to do (in the OPs case, commenting) when giving the command
> in the minibuffer.  That's a detail, but a justified one.

I understand this, but how do you switch to another buffer keeping the
mark visible in the other buffer ?
I don't know a real way to provide this, AFAIK emacs doesn't provide
this.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> I understand this, but how do you switch to another buffer keeping the
> mark visible in the other buffer ?  I don't know a real way to provide
> this, AFAIK emacs doesn't provide this.

emacs -Q, mark a region, hit M-x.  Obviously it makes a difference when
the active buffer is a minibuffer.

But I dunno why Helm behaves different.

**Comment by michael-heerdegen** [comment]
Michael Heerdegen <michael_heerdegen@web.de> writes:

> But I dunno why Helm behaves different.

It's related to our changes of the window arrangement.  If I eval this:

    (defun helm-display-buffer (buffer) (display-buffer buffer))

it "works" (problem gone).

**Comment by michael-heerdegen** [comment]
Michael Heerdegen <michael_heerdegen@web.de> writes:

> It's related to our changes of the window arrangement.

It's not that serious.  I think the cause of the problem is more or less
only the call to "pop-to-buffer" at the end of
"helm-default-display-buffer":

```
(defun helm-default-display-buffer (buffer)
  "Default function to display `helm-buffer' BUFFER.
It uses `switch-to-buffer' or `pop-to-buffer' depending of value of
`helm-full-frame' and/or `helm-split-window-default-side'."
  (if (or (buffer-local-value 'helm-full-frame (get-buffer buffer))
          (and (eq helm-split-window-default-side 'same)
               (one-window-p t)))
      (progn (delete-other-windows) (switch-to-buffer buffer))
    (when (and (or helm-always-two-windows helm-autoresize-mode
                   (and (not helm-split-window-in-side-p)
                        (eq (save-selected-window
                              (funcall helm-split-window-preferred-function
                                       (selected-window)))
                            (get-buffer-window helm-current-buffer))))
               (not (eq helm-split-window-default-side 'same))
               (not (minibufferp helm-current-buffer))
               (not helm-split-window-in-side-p))
      (delete-other-windows))
    (pop-to-buffer buffer)))
```

If I replace it with "display-buffer" (I don't say we should finally do
this), the issue is gone.

The problem with "pop-to-buffer" probably is that it selects a different
window (that new one displaying the helm buffer) and so the information
of what buffer had originally been current is corrupted.

I think we should try to replace that call to "pop-to-buffer" with
something more suitable that doesn't select a different window when not
necessary.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> I think we should try to replace that call to "pop-to-buffer" with
> something more suitable that doesn't select a different window when not
> necessary.

So let try display-buffer instead of pop-to-buffer, can you make the
change ?

Thanks.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> So let try display-buffer instead of pop-to-buffer, can you make the
> change ?

Are there setups possible where helm-default-display-buffer will pop up
a new frame?  In this case, "display-buffer" will not suffice (unlike
pop-to-buffer, it doesn't give the new frame input focus).

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Are there setups possible where helm-default-display-buffer will pop up
> a new frame?

AFAIK no, helm-buffer should be displayed always in same frame.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> AFAIK no, helm-buffer should be displayed always in same frame.

Ok, good.  I'll sleep over it and make the change tomorrow, thanks.

**Comment by michael-heerdegen** [comment]
Ok, I did that now.  Does that work for you @mattford63 ?

**Comment by mattford63** [comment]
Hi, many thanks for working on this :-) Helm is awesome now I'm getting used to it.

So it looks as though the visible region remains highlighted once I return from the `helm M-x`.  However what I would like is the region to be visible whilst browsing the commands within the `helm M-x` search buffer (I often don't quite know what command I'll use on the region so having it remain highlighted whilst I search is handy).  

I see that Thierry says that Emacs may not support it between buffers?  That might be the case :-(  I don't know - however in a normal mini-buffer using M-x this is the behaviour.  It's quite jarring to see highlighting vanish after being so used to it.

**Comment by michael-heerdegen** [comment]
mattford63 <notifications@github.com> writes:

> So it looks as though the visible region remains highlighted once I
> return from the helm M-x. However what I would like is the region to
> be visible whilst browsing the commands within the helm M-x search
> buffer (I often don't quite know what command I'll use on the region
> so having it remain highlighted whilst I search is handy).

I either don't understand, but I think I do, and what you say sounds
like an exact description of what I have uploaded an hour ago.  Are you
sure you are using a version that already includes this change, and/or
have rebuilt properly?

**Comment by mattford63** [comment]
My bad - your changes work as expected.  Hadn't reloaded. Apologies.

**Comment by michael-heerdegen** [comment]
Ok, good that it works...thanks for reporting.
