### ISSUE TITLE
Provide zsh-like path expansion

### ISSUE THREAD

**Issue by cute-jumper** [emacs-helm/helm#1266]
Hi,

In zsh, we can type "/h/f/b" and hit TAB to expand the path to "/home/foo/bar", "/home/foo1/bar", etc., then we can select one of them. This saves a lot of keystrokes. It seems like helm doesn't provide such a path expansion(Do I miss anything?). Do you plan to add this feature to helm?

I'm not familiar with helm's implementation. After about one hour's quick hack, here is what I get for `helm-find-files`(which is pretty similar to what I've imagined before):

![demo](http://i.imgur.com/lmOmPqA.gifv)

EDIT: It seems I don't successfully embedded the image. Here is the link:
http://i.imgur.com/lmOmPqA.gifv

**Comment by thierryvolpiatto** [comment]
> Do you plan to add this feature to helm?

No.

**Comment by Pitometsu** [comment]
> > Do you plan to add this feature to helm?
>
> No.

@thierryvolpiatto  Still no?

**Comment by Pitometsu** [comment]
At least, you can easely implement auto-complete on each `/`.

**Comment by thierryvolpiatto** [comment]
Netsu <notifications@github.com> writes:

> At least, you can easely implement auto-complete on each /.

It is already implemented.

-- 
Thierry

**Comment by Pitometsu** [comment]
@thierryvolpiatto wow, good to know! How can I enable it? Because seems like it don't work for me out-of-the box...

**Comment by thierryvolpiatto** [comment]
Netsu <notifications@github.com> writes:

> @thierryvolpiatto wow, good to know! How can I enable it? Because
> seems like it don't work for me out-of-the box...

See `helm-ff-auto-update-initial-value`

-- 
Thierry

**Comment by Pitometsu** [comment]
@thierryvolpiatto no, first of all I personally don't like "Auto update when only one candidate directory is matched.". Then, it's no the same: it may auto update just current selected value from few when user type `/`

**Comment by Pitometsu** [comment]
[BTW](http://emacsist.com/10641)

**Comment by cute-jumper** [comment]
@Pitometsu I'm the OP and the author of that blog. The solution still works. You need to enable `lexical-binding` to make the it work.

**Comment by Pitometsu** [comment]
@cute-jumper thanks a lot, it's pretty pleasant surprisingly help from your side!

**Comment by Pitometsu** [comment]
@cute-jumper but seems like it work with prefixes only, not any partial strings...

**Comment by cute-jumper** [comment]
@Pitometsu Yes, that's how zsh's path expansion works. However, if you want it to work with any partial strings, change the following code in `helm-ff-try-expand-fname-1`:

```elisp
(directory-files parent t (concat "^" (regexp-quote (car children))))
```

to

```elisp
(directory-files parent t (regexp-quote (car children)))
```

**Comment by Pitometsu** [comment]
@cute-jumper cool, thank you!

**Comment by thierryvolpiatto** [comment]
Netsu <notifications@github.com> writes:

> So in the previous example, using helm, you have to type some letters,
> select the candidate and expand to the selection. Since there are
> multiple levels of directories, you have to do this multiple times until
> you finnaly get to where you want. This is so inefficient and way too
> teeeeeedious! I don't know why I have to do such stupid things if I've
> already known the structures of the directories very well(this is my
> computer anyway)

What is stupid is not learning all the features proposed for such cases.
If you know very well the places where you want to go just bookmark them
from helm-find-files and jump to them also from helm-find-files.
If it is a place often visited you can use also the history (M-p or call
hff with a prefix arg).

> and I know exactly where I wanna go(Yeah, the current behavior of helm
> is useful when you are not sure where you want to go or the path is
> not that deeply nested).

Here it become interesting to have something to jump directly to deeper
level.
Your implementation is not searching very deep, what is interesting is
finding directly the directory you want assuming you know the final path
but not the intermediate directories to reach it.

e.g I want to go from ~/work/ to the bovine directory inside emacs which
is located at ~/work/emacs/lisp/cedet/semantic/bovine/

What is interesting is to allow typing in helm-find-files:

/home/you/work/bov/ C-j and helm showing directly
~/work/emacs/lisp/cedet/semantic/bovine/

I will commit soon a patch allowing doing this (don't know yet the
details about bindings to allow this, actually it is working as
described above).

I am still not believing in efficacity of zsh style expansion which
again assume you already know the path where you want to go, there is
better way to achieve this in emacs and helm. 

-- 
Thierry

**Comment by Pitometsu** [comment]
Purpose to limit output when you already know desired item, but don't want to type all the path. E.g. in default emacs you can type `M-x con-u-m TAB` to get `M-x config-unix-mode`, you see: when you separate parts (like parts in file hierarchy path), you shouldn't than waste time to select item from few, e.g. if you type `M-x con*u*m TAB`.

**Comment by thierryvolpiatto** [comment]
Netsu <notifications@github.com> writes:

> Purpose to limit output when you already know desired item, but don't
> want to type all the path.

You don't need to type all the path.

> E.g. in default emacs you can type M-x con-u-m TAB to get M-x
> config-unix-mode,

And in helm you can type conum, which is even faster.

-- 
Thierry

**Comment by cute-jumper** [comment]
> What is stupid is not learning all the features proposed for such cases. If you know very well the places where you want to go just bookmark them from helm-find-files and jump to them also from helm-find-files. If it is a place often visited you can use also the history (M-p or call hff with a prefix arg).

Yes, using bookmarks is a solution. However:

- I have to at least go through such a typing-selecting-expanding process once
- If I have many nested directories, I would have the mental burden to decide whether to bookmark them or not. Obviously it is not wise to choose to bookmark all of them since I may visit some deeply nested directories occasionally.
- If I have the zsh-style path expansion, why do I need to bookmark? It's not natural. After I invoke `helm-find-files`, I need to think about whether I have put the directories in the bookmarks or not. However, using such a path expansion is natural since all you need to remember is where you wanna go, and it has almost as few keystrokes as using bookmarks. 
- Even if you think my arguments about the bookmarks are wrong, adding such a mechanism doesn't really affect how current helm works. It is more meaningful to expand `/h/f/b/a` to `/home/foo/bar/app` than making a new file `a` under `/h/f/b/` (I might not be correct about this part, but roughly it is what happens). It can be used as a more meaningful action while at the same time it provides an alternative solution to go to deeply nested directories.

> Here it become interesting to have something to jump directly to deeper level. Your implementation is not searching very deep, what is interesting is finding directly the directory you want assuming you know the final path but not the intermediate directories to reach it.

I agree that there should be better solution than using zsh-like path expansion and I hope helm can do better than zsh.

In a word, I think the current proposal to add zsh-like path expansion is not *intrusive*. It basically provides a more meaningful option when the user types something like `/h/f/b/a`. But I'm fine if you don't like this and I would like to use other solutions if they're more efficient.

**Comment by Pitometsu** [comment]
> And in helm you can type conum, which is even faster.
Yes, but if I type `fb` instead of `f/b/` I'll have much more suggestions in addition to `/foo/bar/`

**Comment by Pitometsu** [comment]
> It is more meaningful to expand `/h/f/b/a` to `/home/foo/bar/app` than making a new file `a` under `/h/f/b/` (I might not be correct about this part, but roughly it is what happens).

Anyway on `C-j` *helm* may give you a choice: to create file at exactly that path, or select from suggested expanded variants.

**Comment by thierryvolpiatto** [comment]
Junpeng Qiu <notifications@github.com> writes:

>     What is stupid is not learning all the features proposed for such cases. If you know very well the places where you want to go just bookmark them from
>     helm-find-files and jump to them also from helm-find-files. If it is a place often visited you can use also the history (M-p or call hff with a prefix arg).
>    
> Yes, using bookmarks is a solution. However:
>
>   * I have to at least go through such a typing-selecting-expanding
>   process once

Of course, but if you already know more or less where your paths,
helm-find-files with fuzzy completion + auto update is really fast.

>   * If I have many nested directories, I would have the mental burden
>   to decide whether to bookmark them or not.

You have to remember all the paths of you deeply nested directories,
which isn't better.

>   Obviously it is not wise to choose to bookmark all of them since I
>   may visit some deeply nested directories occasionally.

If you visit such directories occasionally good for you if you remember
their paths exactly, but it is not the case for everybody, also nowaday
many big projects are handled by git or other vc and helm is able to
find files quickly by browsing project at root.

>   * If I have the zsh-style path expansion, why do I need to bookmark?

Maybe you, but bookmarks from helm-find-files are much faster.
   
>   It's not natural.

Sorry but I don't agree with your approach that assume you already know
your paths.

> I agree that there should be better solution than using zsh-like path
> expansion and I hope helm can do better than zsh.
>
> In a word, I think the current proposal to add zsh-like path expansion
> is not intrusive. It basically provides a more meaningful option when
> the user types something like /h/f/b/a.

No I am sorry, but I still think this approach is not good.

> But I'm fine if you don't like this and I would like to use other
> solutions if they're more efficient.

With the future patch you will be able to reach
"/home/qjp/foo/bar/what/the/hell" to type

/home/qjp/hel/ C-j to reach "hell" directory (all the "hell" directories
found on the way will be listed with a relative path), from upper you
start faster it will be.

-- 
Thierry

**Comment by cute-jumper** [comment]
> No I am sorry, but I still think this approach is not good.

That's fine. I don't really want to convince you since it is really a matter of taste. I just want to clarify my opinions.

> /home/qjp/hel/ C-j to reach "hell" directory (all the "hell" directories found on the way will be listed with a relative path), from upper you start faster it will be.

That would be awesome.

**Comment by thierryvolpiatto** [comment]
Junpeng Qiu <notifications@github.com> writes:

> That would be awesome.

Will be available soon, I need to fix some details first.

Thanks.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Junpeng Qiu <notifications@github.com> writes:

> That would be awesome.

Now available, I expect portability problems as this implementation is
using locate as backend, the command is configurable though.
My first implementation was using elisp to recurse, but it is too
slow on big trees (e.g /usr).

Otherwise it seems an handy addition.

Thanks.

-- 
Thierry

**Comment by Pitometsu** [comment]
> Of course, but if you already know more or less where your paths,
> helm-find-files with fuzzy completion + auto update is really fast.

it will not work same way, e.g. `./p/w/h` may be single one variant for path like `./project/work/haskell`, but there a lot matched variants for each path level (lke `product`, `peoples`; `wishes`, `wallpapers`, etc.), so it will force type like `pe`...AUTO UPDATE to <peoples>! UPS! it was just a typo! `C-l` `proj` AUTO UPDATE to <project> `ec` AUTO UPDATE to `eclipse` what happens? where am I? oh, it's projects, it's fine. Wait. No! `C-l` `C-l` DAMN! `p<down><down><down> C-z <down><down><down><up> C-z RET`.

**Comment by thierryvolpiatto** [comment]
Netsu <notifications@github.com> writes:

>     Of course, but if you already know more or less where your paths,
>     helm-find-files with fuzzy completion + auto update is really fast.
>    
> it will not work same way, e.g. ./p/w/h may be single one variant for
> path like ./project/work/haskell, but there a lot matched variants for
> each path level (lke product, peoples; wishes, wallpapers, etc.), so
> it will force type like pe...AUTO UPDATE to ! UPS! it was just a typo!
> C-l proj AUTO UPDATE to ec AUTO UPDATE to eclipse what happens? where
> am I? oh, it's projects, it's fine. Wait. No! C-l C-l DAMN!
> p<down><down><down> C-z <down><down><down><up> C-z RET.

Once you are used to it going to ./project/work/haskell is really easy,
if you don't want to understand that's your problem, anyway this feature
is NOT enabled by default so STOP complaining.

Also I have now implemented a completion on directories under current
one, same if you don't like it, don't use it.
For the zsh style completion, stop asking you will not have it.

Thanks.

-- 
Thierry

**Comment by Pitometsu** [comment]
> Now available

How can I enable to test it?

> STOP complaining

Just wanted provide all my best suggestions in feedback as an user and discuss cases. Sorry If don't understand chosen approaches in helm. Anyway, thank you a lot for so nice plugin and support.

> For the zsh style completion, stop asking you will not have it.

Ok, let's drop zsh abstraction at all, anyway it use prefixes and has no fuzzy matching.
However, still would ask about file path separator (usually it "/"). When I, as user, open file, usually I approximately know where can I find desired file. For few reasons I don't use recursive searching (maybe just miss understanding how to make it useful, but current motivation is: mind to don't loose control and keep understanding where am I here right now).
  So, when I open file, e.g. it `~/.emacs.d/site-lisp/custom.el`, now I do it next way: type `emacs` `<complete>` `site` `<complete>` `cus.el$` `RET`.
  What would be nice to have is ability open it like `emacs/si/cus.el$`, or even `emacs/cus.el$`, so cases like `emacscus.el` or `emacssicus.el` shouldn't match, path separator can be used during file searching.
  Could you, please, suggest me, is there actual possibility to do something like that, or it's completely unnecessary with helm-way approach?  In case if it's unnecessary, which better way could you suggest as choose for the same purposes?
  Surely, you free just don't do any features for your personal reasons, anyway I have no enough time, skills and motivation to fork it, so just, please, let me know if not interested in any feedback from my side in future.

**Comment by thierryvolpiatto** [comment]
Netsu <notifications@github.com> writes:

> How can I enable to test it?

RTFM

-- 
Thierry
