### ISSUE TITLE
Can't hide . and .. entries in file lists

### ISSUE THREAD

**Issue by j0ni** [emacs-helm/helm#1267]
I think I may be missing something here, since the code and docstring:

   https://github.com/emacs-helm/helm/blob/master/helm-files.el#L1758

make it clear that this is intentional behaviour, but I would really like to hide those entries. 

There many situations where finding a file involves navigating through at least one level of single-entry lists (for example I write Clojure code, which tends to be organized with a `src/project-name` structure. Once my cursor is on `src`, I want to just hit C-j twice, but I'm forced by the `.` and `..` entries to either type something from the `project-name` or navigate down two places to get to the entry I want.

I realize this is a fairly minor issue, but is there some reason those entries can't be suppressed?

**Comment by thierryvolpiatto** [comment]
J Irving <notifications@github.com> writes:


> I realize this is a fairly minor issue, but is there some reason those entries can't be suppressed?

Yes.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by j0ni** [comment]
Can you expand, or point me at the rationale?
