### ISSUE TITLE
Add general purpose execute-action-in-other-window command?

### ISSUE THREAD

**Issue by davidshepherd7** [emacs-helm/helm#1269]
Currently various parts of helm seem to implement their own execute-action-in-other-window command. It would be nice if there was a single command in helm core to execute the default action in another window.

In particular it would make it easy for me to bind a key to all the action-in-other-window commands at once :+1:.

**Comment by thierryvolpiatto** [comment]
David Shepherd <notifications@github.com> writes:

> Currently various parts of helm seem to implement their own
> execute-action-in-other-window command. It would be nice if there was
> a single command in helm core to execute the default action in another
> window.
>
> In particular it would make it easy for me to bind a key to all the
> action-in-other-window commands at once :+1.

It is not so simple to add a generic command as all
switch-to-other-window commands in helm work differently, it is a lot of
work for saving some "define-key" entries in your config file.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by davidshepherd7** [comment]
Ok, no problem.
