### ISSUE TITLE
helm 1.9 on melpa-stable not installable

### ISSUE THREAD

**Issue by sometimesfood** [emacs-helm/helm#1272]
helm 1.9.0 is currently not installable via melpa-stable since it depends on async 1.6, which has not been officially released yet.

@thierryvolpiatto: You seem to be a contributor to both helm and async. Any idea on how soon we can expect the release of async 1.6?

**Comment by thierryvolpiatto** [comment]
Sebastian Boehm <notifications@github.com> writes:

> helm 1.9.0 is currently not installable via melpa-stable since it
> depends on async 1.6, which has not been officially released yet.
>
> @thierryvolpiatto: You seem to be a contributor to both helm and
> async. Any idea on how soon we can expect the release of async 1.6?

I have no idea why helm have been updated and not async, I guess all
packages are updated by alphabetically order and when I tagged async its
turn have passed but not helm.
Probably you will have to wait tomorrow or late tonight, if async have
not been updated tomorrow, I will submit a bug on melpa.
If you are really in hurry, you can still use the not stable version
(which is the same as stable actually ;-).

Thanks to report and sorry for the delay.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by thierryvolpiatto** [comment]
Oops, my bad it is my fault I forgot to tag async to 1.6 (or push the tag, was on another computer), it is done now.

Sorry again.

**Comment by sometimesfood** [comment]
No problem at all, thanks for the release!

If it's ok with you, I'll leave this issue open until melpa-stable has caught up with GitHub so you don't get duplicate bug reports.

**Comment by thierryvolpiatto** [comment]
Sebastian Boehm <notifications@github.com> writes:

> No problem at all, thanks for the release!
>
> If it's ok with you, I'll leave this issue open until melpa-stable has
> caught up with GitHub so you don't get duplicate bug reports.

Great, thanks.


-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by sometimesfood** [comment]
This issue is resolved for me. Thanks for the fast response!
