### ISSUE TITLE
Helm-find-file does not work with tramp and pipe

### ISSUE THREAD

**Issue by trivago-igarcia** [emacs-helm/helm#1274]
Trying to open a file like this: helm-find-files then typing:
/ssh:user1@192.168.200.1|sudo:user2@192.168.200.1:/etc/hosts
The pipe ( | ) does not work.

**Comment by thierryvolpiatto** [comment]
Iris García <notifications@github.com> writes:

> Trying to open a file like this: helm-find-files then typing:
> /ssh:user1@192.168.200.1|sudo:user2@192.168.200.1:/etc/hosts
> The pipe ( | ) does not work.

This tramp syntax is not implemented, please use
`tramp-default-proxies-alist'.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by thierryvolpiatto** [comment]
See #981

**Comment by trivago-igarcia** [comment]
I have tons of users/servers it makes no sense to add all of the combinations to the tramp-default-proxies-alist.

**Comment by thierryvolpiatto** [comment]
Iris García <notifications@github.com> writes:

> I have tons of users/servers it makes no sense to add all of the
> combinations to the tramp-default-proxies-alist.

So I guess you are a professional web admin or something similar...

I am not paid to develop helm, and implementing this feature (which is
not useful for my usage) is a lot of work...

So perhaps I will do it one day when I have nothing else to do, sorry.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by trivago-igarcia** [comment]
That's okay.

I just thought it was not too hard since it works with the default emacs lips function "find-file"

Thanks anyway.

**Comment by mattford63** [comment]
+1 for this feature

**Comment by thierryvolpiatto** [comment]
Connect once with regular `find-file`, then if `tramp-save-ad-hoc-proxies` is non-nil your connection will be saved to `tramp-default-proxies-alist`, you will be then able to connect with helm to these proxies.

**Comment by Jehops** [comment]
`M-x helm-find-file /ssh:you@remotehost|sudo:remotehost:/path/to/file RET` (note the second remotehost after sudo)` displays errors [1] after the second colon, but if you ignore those errors it works.  Maybe there is a simple solution to just avoid the spurious errors?

[1] `Error running timer: (error "In ‘Find Files’ source: ‘helm-find-files-get-candidates’ 
 (user-error \"Host name must not match method \\\"sudo\\\"\")")`
