### ISSUE TITLE
emacs helm-do-grep-1 funcall: Wrong type argument: listp, \.\.\.

### ISSUE THREAD

**Issue by aborn** [emacs-helm/helm#1276]
Hi, 
Today, I use helm-do-grep-1 (C-u C-x c M-g s), error as following
```
funcall: Wrong type argument: listp, \.\.\.
```
I found the value of helm-adaptive-history 
```elisp
ELISP> helm-adaptive-history
(("*Ack-grep types*"
  ("java" \.\.\.))
 ("*helm grep extensions*"
  ("*.el" \.\.\.)
  ("*" \.\.\.)))
```
Then I force set the helm-adaptive-history with nil, it can works.
```
ELISP> (setq helm-adaptive-history nil)
```
Then I do helm-do-grep-1, the  value of helm-adaptive-history becomes,
```
ELISP> helm-adaptive-history
(("*Ack-grep types*"
  ("elisp"
   (".el" . 1))))
```
But this error happens again when I reopen emacs.
Debugger Backtrace (omit ...)
```
Debugger entered--Lisp error: (wrong-type-argument listp \.\.\.)
  #[0 "\300..
  funcall(#[0 "\300A\211\205-\...
  #[257 "\300C\301\302\303\300\304\...
  mapcar(#[257 "\300C\301\302\303\300\...
  helm-adaptive-sort((("actionscript [.as .mxml]" . "actionscript") ...
  apply(helm-adaptive-sort ((("actionscript [.as .mxml]" . "actionscript") ...
  helm-compose(((("actionscript [.as .mxml]" . "actionscript") ...
  #[128 "\301\300\"\207" [(helm-adaptive-sort ...
  apply(#[128 "\301\300\"\207" [(helm-adaptive-sort helm-grep-ack-types-transformer helm-fuzzy-highlight-matches) h...
  helm-funcall-with-source(((name . "*Ack-grep types*") (candidates . #[0 "\306\300\301\304\305$\307\30...
  apply(helm-funcall-with-source ((name . "*Ack-grep types*") (candidates . #[0 "\306\300\301\304\305$\307\303\...
  helm-composed-funcall-with-source(((name . "*Ack-grep types*") (candidates . #[0 "\306\300\301\304\305$\307\303...
  helm-process-filtered-candidate-transformer((("actionscript [.as .mxml]" . "actionscript") ("noactionscript [.as .mxm...
  helm-compute-matches(((name . "*Ack-grep types*") (candidates . #[0 "\306\300\301\304\305$\307\303\242\31...
  #[0 "\302\300\303\211:\203@\262\304!B\262A\262\202\211\237\266\203)\207" [(((name . "*Ack-grep types* History") ...
  funcall(#[0 "\302\300\303\211:\203@\262\304!B\262A\262\202\211\237\266\203)\207" [(((name . "*Ack-grep types* History")...
  #[0 "\302\303\304\305\306\307\310\311\300!\312\"\313\314%D\215)\207" [(((name . "*Ack-grep types* History") (candidates . #[0 "\30...
  funcall(#[0 "\302\303\30...
  helm--compute-sources((((name . "*Ack-grep types* History") (candidates . #[0 "...
  helm-update(nil)
  helm-read-pattern-maybe("Types: " nil nil noresume (keymap (keymap (13 . helm-conf..
  #[0 "\311\211\211\211\305\206\n&&'()*\312\313+\"\314\315\316\317\320...
  funcall(#[0 "\311\211\211\211\305\206\n&&'()*\312\313+\"\314\315\316\31...
  helm-internal((((name . "*Ack-grep types* History") (candidates . #[0 "\304\302\300\305\30...
  apply(helm-internal ((((name . "*Ack-grep types* History") (candidates . #[0 "\304\302\300\30...
  helm((((name . "*Ack-grep types* History") (candidates . #[0 "\304\302\300\305\303$\211\205)\3...
  apply(helm ((((name . "*Ack-grep types* History") (candidates . #[0 "\304\302\300\305\303$\211\205)...
  helm(:sources (((name . "*Ack-grep types* History") (candidates . #[0 "\304\302\300\305\303$\211\205)...
  helm-comp-read("Types: " (("actionscript [.as .mxml]" . "actionscript") ("noactionscript [.as .mxml]" . "n...
  helm-grep-read-ack-type()
  helm-do-grep-1(("/Users/aborn/.emacs.d") (4))
  helm-do-grep()
  call-interactively(helm-do-grep nil nil)
  command-execute(helm-do-grep)

```

OSX 10.11.1
emacs 24.5.1
helm-20151126.607

Thanks a lot!

**Comment by aborn** [comment]
now I have to add following code to solve this problem:
```elisp
(add-hook 'after-init-hook
		  (lambda ()
			(load-file helm-adaptive-history-file)))
```

**Comment by thierryvolpiatto** [comment]
Aborn Jiang <notifications@github.com> writes:

> Hi,
> Today, I use helm-do-grep-1 (C-u C-x c M-g s), error as following
>
> funcall: Wrong type argument: listp, \.\.\.
>
> I found the value of helm-adaptive-history
>
> ELISP> helm-adaptive-history
> (("*Ack-grep types*"
>   ("java" \.\.\.))
>  ("*helm grep extensions*"
>   ("*.el" \.\.\.)
>   ("*" \.\.\.)))
>
> Then I force set the helm-adaptive-history with nil, it can works.

You are using helm-adaptative for helm grep, which is not enabled by
default.

Recently a super clever man posted the code on internet to enable helm
adaptative everywhere, are you using this code ?

Otherwise if you tried this code and then removed it from your init
file, it have for sure corrupted your helm-adaptative file, please
delete the file from outside emacs and restart ./emacs-helm.sh,
everything should work fine.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by aborn** [comment]
@thierryvolpiatto here is my config https://github.com/aborn/emacs.d/blob/master/modules/init-helm-aborn.el

**Comment by thierryvolpiatto** [comment]
Aborn Jiang <notifications@github.com> writes:

> @thierryvolpiatto here is my config https://github.com/aborn/emacs.d/blob/master/modules/init-helm-aborn.el

If you have a grep entry in your adaptive history, it is that at one
point, you tried to modify its source to use adaptative, because by
default helm grep is not using adaptive, so the best you have to do is
M-x helm-reset-adaptive-history and restart emacs.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by thierryvolpiatto** [comment]
The backtrace show clearly that at some point the `helm-adaptive-sort` fn is running, which mean it have been added to `filtered-candidate-transformer`, which is not the default and not recommended.

**Comment by aborn** [comment]
@thierryvolpiatto how to disable it?

**Comment by aborn** [comment]
@thierryvolpiatto Thanks a lot!

**Comment by thierryvolpiatto** [comment]
Aborn Jiang <notifications@github.com> writes:

> @thierryvolpiatto how to disable it?

I see we still have one call of `helm-adaptive-sort' in
`helm-grep-read-ack-type' so I was wrong, it is used in one place by
default, my bad :-(.

Just M-x helm-reset-adaptive-history

and restart emacs, it should then works as expected.

If it is still returning an error, let me know I will fix it or remove
it.

Sorry I have few time to read code, backtrace etc... actually.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by aborn** [comment]
@thierryvolpiatto Thanks again! Yeah, I use ack-grep!
