### ISSUE TITLE
hide cursor in helm minibuffers.

### ISSUE THREAD

**Issue by HiCodin** [emacs-helm/helm#1277]
This is not really an issue but how can i hide the box character cursor in helm-find-files for example. My cursor color is yellowish and its showing as box character in helm mini buffers as you can see it in the picture.
![selection_004](https://cloud.githubusercontent.com/assets/13816418/11492901/79344030-9821-11e5-9a9f-0ffd128f42cb.png)

**Comment by thierryvolpiatto** [comment]
HiCodin <notifications@github.com> writes:

> This is not really an issue but how can i hide the box character
> cursor in helm-find-files for example.

You can't ...

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by justmytwospence** [comment]
I'd appreciate such a feature as well. Maybe instead of implementing a special variable for this, a hook could in such a place so as to make it possible. Does that hook already exist? If it does I can't find it.

**Comment by michael-heerdegen** [comment]
Is that really what you want?  If you move around with C-b and C-f (for example), how will you know "where you are" with a hidden cursor?

And why is your cursor color a problem in Helm, and you like it elsewhere?

**Comment by justmytwospence** [comment]
My interpretation of the original question is that it refers to the helm completions buffer, not the minibuffer/echo area as it sounds like you are assuming (correct me if I'm wrong).

**Comment by michael-heerdegen** [comment]
Ah, that would make sense.

I don't see such a box cursor in the Completions buffer, neither with emacs-helm.sh, nor with my config.

**Comment by justmytwospence** [comment]
What do you have `cursor-in-non-selected-windows` set to? I'd prefer to have this set to `t` globally, but with an exception for helm completions. Maybe you have it set to `nil`?

**Comment by thierryvolpiatto** [comment]
Spencer Boucher <notifications@github.com> writes:

> What do you have cursor-in-non-selected-windows set to?

Non-nil.

> I'd prefer to have this set to t globally, but with an exception for
> helm completions. Maybe you have it set to nil?

No.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by justmytwospence** [comment]
Ah, so that non nil setting is why you don't see the cursor like @HiCodin does. I meant to say maybe you have it set to `t` in that last bit.

**Comment by thierryvolpiatto** [comment]
Spencer Boucher <notifications@github.com> writes:

> Ah, so that non nil setting is why you don't see the cursor like
> @HiCodin does. I meant to say maybe you have it set to t in that last
> bit.

non-nil == t


-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by HiCodin** [comment]
well, setting the `cursor-in-non-selected-windows` to nil solves my issue. Should've read the documentation thoroughly. Thanks for the help @justmytwospence and @thierryvolpiatto .

**Comment by thierryvolpiatto** [comment]
Your issue comes from somewhere else, because here with `cursor-in-non-selected-windows` nil or non-nil, it makes no differences.

Here a screeshot with `cursor-in-non-selected-windows` set to non-nil (t).

![screenshot - 18122015 - 18 38 31](https://cloud.githubusercontent.com/assets/1533939/11903073/ce5ed42e-a5b6-11e5-9efe-5df158f3769d.png)

**Comment by nixmaniack** [comment]
Well, since `cursor-in-non-selected-windows` is buffer-local, setting its default value using `(setq-default cursor-in-non-selected-windows nil)` will hide it from every non-selected window.

For completion buffers there's similar approach explained [here](http://emacs.stackexchange.com/questions/13916/how-to-disable-the-hollow-box-cursor-in-auto-completion-buffer/13918#13918) and I was expecting adding it to `helm-mode-hook` would help but it doesn't seem so. 

I would like to keep global value of cursor-in-non-selected-windows to non-nil and just hide it in helm-buffers. Any possibility?

**Comment by michael-heerdegen** [comment]
Muneeb Shaikh <notifications@github.com> writes:

> For completion buffers there's similar approach explained here and I
> was expecting adding it to helm-mode-hook would help but it doesn't
> seem so.

Definitely the wrong hook, that makes absolutely no sense.

I would try `helm-update-hook'.  AFAICT when that hook is run, the
current helm Completions buffer is current (which is what you want).


Michael.

**Comment by nixmaniack** [comment]
Right. Wasn't aware of other helm hooks. syl20bnr provided a fix [here](https://github.com/syl20bnr/spacemacs/blob/522366bbd179bc332a863efeb523daa09c603458/layers/%2Bdistribution/spacemacs-base/packages.el#L681-L685) which now solves this.

**Comment by justmytwospence** [comment]
@nixmaniack that appears to do the trick!

**Comment by HiCodin** [comment]
@thierryvolpiatto yes. it seems that using `Evil-Mode` causes the hollow box to appear and disabling it makes the hollow box to disappear as well. 
@nixmaniack your fix did the trick !
