### ISSUE TITLE
Projectile not using helm's faces.

### ISSUE THREAD

**Issue by it3ration** [emacs-helm/helm#1279]
Projectile doesn't make use of helm's faces when opening files / directories via projectile-find-file:

helm-ff-directory 
helm-ff-dotted-directory 
helm-ff-dotted-symlink-directory 
helm-ff-executable 
helm-ff-file 
helm-ff-invalid-symlink 
helm-ff-prefix 
helm-ff-symlink

Not sure where this belongs, the problem is projectile calls into helm using helm's completing read method, so all context is lost on what each entry is. Thoughts?

Best,
-Kevin

**Comment by thierryvolpiatto** [comment]
Kevin Depue <notifications@github.com> writes:

> Projectile doesn't make use of helm's faces when opening files / directories via projectile-find-file:
>
> helm-ff-directory
> helm-ff-dotted-directory
> helm-ff-dotted-symlink-directory
> helm-ff-executable
> helm-ff-file
> helm-ff-invalid-symlink
> helm-ff-prefix
> helm-ff-symlink
>
> Not sure where this belongs, the problem is projectile calls into helm
> using helm's completing read method, so all context is lost on what
> each entry is. Thoughts?

This is the wrong place to submit projectile bugs (I know nothing about
projectile).

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by it3ration** [comment]
Ok I'll direct it to them, thanks.
