### ISSUE TITLE
Error when requiring helm-config

### ISSUE THREAD

**Issue by rcoedo** [emacs-helm/helm#1281]
Helm-config.el is trying to require the file Helm-aliases.el which seems to be deleted on [this](https://github.com/emacs-helm/helm/commit/4ed3a6c344b3151b4068813ec8c22abe4962b00e) commit.

Could you please fix this?

Thanks!

**Comment by kat-co** [comment]
+1

**Comment by thierryvolpiatto** [comment]
Roman Coedo <notifications@github.com> writes:

> Helm-config.el is trying to require the file Helm-aliases.el which
> seems to be deleted on this commit.

Oops, indeed.

> Could you please fix this?

Done.

Thanks.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by rcoedo** [comment]
yay! :+1:

**Comment by tollerm** [comment]
Hi,
When this fix will be available at Melpa?

**Comment by rcoedo** [comment]
@tollerm as a workaround until melpa updates the package, if you use Cask, change the `(depends-on "helm")` line in your Cask file for `(depends-on "helm" :git "https://github.com/emacs-helm/helm")`.

**Comment by thierryvolpiatto** [comment]
tollerm <notifications@github.com> writes:

> Hi,
> When this fix will be available at Melpa?

Don't know the update frequency on Melpa, I would say late tonight or
tomorrow morning.

Sorry for inconveniency.

-- 
Thierry
https://emacs-helm.github.io/helm/
