### ISSUE TITLE
function helm-do-grep is missing

### ISSUE THREAD

**Issue by dfeich** [emacs-helm/helm#1282]
Installed helm-20151206.1007 from MELPA. `helm-do-grep` is no longer defined as a function. I just scanned the current code in the github repo of helm-grep.el, and I can no longer find the defun.

**Comment by thierryvolpiatto** [comment]
Derek <notifications@github.com> writes:

> Installed helm-20151206.1007 from MELPA. helm-do-grep is no longer
> defined as a function. I just scanned the current code in the github
> repo of helm-grep.el, and I can no longer find the defun.

I removed it as it is unuseful (since long time).
Start from helm-find-files instead.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by dfeich** [comment]
Had overlooked that functionality from helm-find-files. This is much nicer,
indeed

Thanks,
Derek
