### ISSUE TITLE
helm-mm-matching-method set to multi3p fails on paths with hidden directories

### ISSUE THREAD

**Issue by tojo9900** [emacs-helm/helm#1283]
I can reproduce the bug with these steps:

1. Create a path with a hidden directory:
mkdir -p /tmp/.dotdir1/dir2

2. Start Emacs, enable helm and evaluate
(setq helm-mm-matching-method 'multi3p).

3. Open above directory in dired (`C-x d').

=> helm quits with no message and dired doesn't open the directory

I get the same behavior with find-file and it works as expected if I disable
helm. However, it does work if the hidden directory is last item in the path
(eg. /home/user/.emacs.d/).

A workaround is to reset helm-mm-matching-method to the standard 'multi3.

I would really appreciate some insight on this problem. Thanks!

**Comment by thierryvolpiatto** [comment]
This should be fixed, however, you have better time using multi3 method and using also `helm-find-files` for all you files tasks.

**Comment by tojo9900** [comment]
Yes, it's fixed now.

Thanks!
