### ISSUE TITLE
helm-find-files strange behaviour

### ISSUE THREAD

**Issue by MinasMazar** [emacs-helm/helm#1284]
1. Call `helm-find-files`. Everything works.
2. Go to `/this/is/a/directory` [or `/this/is/a/file.txt`]
3. Press `Tab` to see the list of actions.
4. Press `Tab` again to swtich back to file list.
5. Now `C-j` does not autcomplete, but always reset the current path to `/this/is/a/directory`. Whataever directory/file i pick, the `/this/is/a/directory` will be opened (with dired). [or `/this/is/a/file.txt` will be opened]
6. Re-opening `helm-find-files`. Everything works.

Strange behaviour or there's a specific reason for that?

**Comment by thierryvolpiatto** [comment]
MinasMazar <notifications@github.com> writes:

>  1. Call helm-find-files. Everything works.
>  2. Go to /this/is/a/directory [or /this/is/a/file.txt]
>  3. Press Tab to see the list of actions.
>  4. Press Tab again to swtich back to file list.
>  5. Now C-j does not autcomplete, but always reset the current path to /this/is/a/directory. Whataever directory/file i pick, the /this/is/a/directory will be opened
>     (with dired). [or /this/is/a/file.txt will be opened]
>  6. Re-opening helm-find-files. Everything works.
>
> Strange behaviour or there's a specific reason for that?

This is not reproductible here, please try from ./emacs-helm.sh.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by MinasMazar** [comment]
From `emacs-helm.sh` i cannot reproduce it.

**Comment by thierryvolpiatto** [comment]
MinasMazar <notifications@github.com> writes:

> From emacs-helm.sh i cannot reproduce it.

So something in your config or in a 3rd package is wrong.
No helm bug anyway.

-- 
Thierry
https://emacs-helm.github.io/helm/
