### ISSUE TITLE
Set a default starting directory for helm-find-files

### ISSUE THREAD

**Issue by cilia** [emacs-helm/helm#1285]
Is it possible to set a default starting directory when `helm-find-files` is invoked? Currently, using `helm-config`, the starting directory is always the current working directory where `Emacs` is launched. Is there a variable I can set to change this?

**Comment by thierryvolpiatto** [comment]
cilia <notifications@github.com> writes:

> Is it possible to set a default starting directory when
> helm-find-files is invoked? Currently, using helm-config, the starting
> directory is always the current working directory where Emacs is
> launched. Is there a variable I can set to change this?

No, it would be a bad idea to limit yourself to the same directory.
I imagine you work often in this directory, so it is on top of history,
you can do C-u C-x C-f RET (assuming you bounded C-x C-f to
helm-find-files).
When in helm-find-files, you can also at any moment do C-x r m to
bookmark the directory you are actually browsing, and at any moment 
C-x r b to retrieve it.
Starting with helm-filtered-bookmarks allow also to retrieve your
helm-find-files bookmark in a specific section.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by cilia** [comment]
Thanks for the clarification and the tips.

The wiki also says: "Starting helm-find-files with `C-u` will show you a little history of the last visited directories." But I do not see this little history in my `helm` buffer. All I see is the list of files inside the current directory. Where is this history supposed to appear in the buffer? Is there something else I need to configure to enable this?

Related questions, besides using bookmarks, is there any other mechanism for jumping around directories? For example, I can do `C-l` to go to the parent directory. What about jumping to home directory or to whatever is stored in `default-directory`?

**Comment by thierryvolpiatto** [comment]
cilia <notifications@github.com> writes:

> Thanks for the clarification and the tips.
>
> The wiki also says: "Starting helm-find-files with C-u will show you a
> little history of the last visited directories." But I do not see this
> little history in my helm buffer. All I see is the list of files
> inside the current directory. Where is this history supposed to appear
> in the buffer? Is there something else I need to configure to enable
> this?

No you should have it, note that you have to save it yourself for
persistence across sessions, otherwise when you start emacs you have of
course nothing.

You have several programs to save variables, buffers etc...
Mine is called psession.

> Related questions, besides using bookmarks, is there any other
> mechanism for jumping around directories? For example, I can do C-l to
> go to the parent directory. What about jumping to home directory or to
> whatever is stored in default-directory?

See C-h m while you are in helm-find-files, it is all explained there.

-- 
Thierry
https://emacs-helm.github.io/helm/
