### ISSUE TITLE
disable helm for tramp connections?

### ISSUE THREAD

**Issue by percyfal** [emacs-helm/helm#1287]
Hi,

is it possible to disable helm for tramp connections? Since a couple of days, helm seems to hang upon connecting. My helm version is 20151210.2233.

Thanks,

Per

**Comment by thierryvolpiatto** [comment]
Per Unneberg <notifications@github.com> writes:

> Hi,
>
> is it possible to disable helm for tramp connections? Since a couple
> of days, helm seems to hang upon connecting My helm version is
> 201512102233

It is not due to helm but your tramp version.
I will add an entry in FAQ about this.
See https://github.com/emacs-helm/helm/issues/1000

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by percyfal** [comment]
Ok, thanks for the quick response. The odd thing though is that I haven't changed tramp nor emacs version, and two days ago it worked. I'll try changing tramp version again. FYI, I had previously looked at that issue a long time ago when I was experiencing problems after changing from emacs23 to 24. It turned out I had set my bash prompt to PS1="[\u@\h \W]$ ", which worked in emacs 23 but not 24. Setting PS1='[\u@\h \W]\\$ ' solved this issue.

**Comment by thierryvolpiatto** [comment]
Per Unneberg <notifications@github.com> writes:

> Ok, thanks for the quick response. The odd thing though is that I
> haven't changed tramp nor emacs version, and two days ago it
> worked.

Perhaps something has changed with your ISP or the way you connect to
the internet ?

Read carefully the whole thread #1000.

Nothing have changed (and will never change) in helm about this, helm
doesn't try to establish a remote connection on startup. 

> I'll try changing tramp version again. FYI, I had previously looked at
> that issue a long time ago when I was experiencing problems after
> changing from emacs23 to 24. It turned out I had set my bash prompt to
> PS1="[\u@\h \W]$ ", which worked in emacs 23 but not 24. Setting
> PS1='[\u@\h \W]\$ ' solved this issue.

Try modifying `tramp-ssh-controlmaster-options` as described in #1000

-- 
Thierry
https://emacs-helm.github.io/helm/
