### ISSUE TITLE
helm-previous-line with argument failing towards end of list candidates

### ISSUE THREAD

**Issue by Antoine-Patel** [emacs-helm/helm#1288]
Using `emacs-helm.sh` in my `.emacs.d/elpa/helm-20151210.1008`, when I evaluate `
(define-key helm-map (kbd "M-f") '(lambda () (interactive) (helm-previous-line 5)))` in the scratch buffer and try it, it fails towards the end of list candidates:
- On the last one, `M-f` simply does nothing. Expected: point should move 5 lines up.
- On the one before the last one, `M-f` only moves one line up. Expected: same as above.
- On the one before the one before the last one, `M-f` moves only two lines up. Expected: ditto.
- On the K-th candidate starting at 0 from the bottom of the list, `M-f` move only K lines up when K < ARG (of helm-previous-line). Expected: ditto.

`C-u C-p` with default keybindings in helm-map produces the same unexpected behavior as `M-f` above (except that ARG is 4 instead of 5).

The behavior I'd expect, according to the docstring of `helm-previous-line`, is the same as: 
```elisp
(define-key helm-map (kbd "M-f") '(lambda () (interactive) 
				    (helm-previous-line)
				    (helm-previous-line)
				    (helm-previous-line)
				    (helm-previous-line)
				    (helm-previous-line)))
```
The above code works by the way.

My elisp is weak and I tend to stay away from code with `cl-loop` inside, but looking at `helm--next-or-previous-line`, if `pos` is 5, `cand-num` is 7, `ARG` is 5 and direction is `'previous`, `iter` becomes `(min 5 (- 7 5))` -> `2` if I'm not mistaking, so it only goes up by two. But I'm not sure.

------------------------------------------------------
helm version: `20151210.1008` according to `package-list-packages`
helm core: `20151208.2241` according to `package-list-packages`.
emacs: `GNU Emacs 24.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.10.7) of 2014-03-07 on lamiak, modified by Debian`

**Comment by thierryvolpiatto** [comment]
Should work now.

Thanks.
