### ISSUE TITLE
let*: Wrong type argument: commandp, helm-do-grep

### ISSUE THREAD

**Issue by caisah** [emacs-helm/helm#1291]
`Debugger entered--Lisp error: (wrong-type-argument commandp helm-do-grep)
  call-interactively(helm-do-grep)
  (let* ((current-prefix-arg (not non-recursive)) (helm-current-prefix-arg non-recursive)) (call-interactively (quote helm-do-grep)))
  helm-do-grep-recursive(nil)
  call-interactively(helm-do-grep-recursive nil nil)
  command-execute(helm-do-grep-recursive)
`

Hi,
I have noticed this problem recently when I try to call `helm-do-grep-recursive`. Do you have any idea how I could fix this?

Thanks!

**Comment by thierryvolpiatto** [comment]
caisah <notifications@github.com> writes:

> Hi,
> I have noticed this problem recently when I try to call
> helm-do-grep-recursive Do you have any idea how I could fix this?

https://github.com/emacs-helm/helm/wiki#grep-and-multi-occur-commands-have-been-removed-why

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by caisah** [comment]
Thanks!
