### ISSUE TITLE
"Unsupported locate version" when executing helm-projects-find-files

### ISSUE THREAD

**Issue by dbarros** [emacs-helm/helm#1295]
When I try and run helm-projects-find-files I get the aforementioned error: "Unsupported locate version". I've tried googling for more information, but had not luck. Do I need to update my version of locate? I am on OS X 10.11.2.

**Comment by thierryvolpiatto** [comment]
Diego Barros <notifications@github.com> writes:

> When I try and run helm-projects-find-files I get the aforementioned
> error: "Unsupported locate version" I've tried googling for more
> information, but had not luck Do I need to update my version of
> locate? I am on OS X 10112

Hmm, sorry but I know nothing about OSX, but other helm veterans on this
list use OSX, perhaps they can help you...


-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by xuchunyang** [comment]
That version (BSD) of locate is just unsupported: the reason mainly is it doesn't provides `updatedb` and I don't know how to create a locate database for one specific directory.

> Do I need to update my version of locate?

If you don't know either, you can try to use gnu locate, which comes from gnu findutils, I installed it with my package manager (for me, it's macports), the following patch (because of the `-g` prefix) and customizations works for me.

```diff
@@ -349,4 +349,4 @@ With a prefix arg refresh the database in each project."
   (helm-locate-set-command)
-  (cl-assert (and (string-match-p "\\`locate" helm-locate-command)
-                  (executable-find "updatedb"))
+  (cl-assert (and (string-match-p "\\`glocate" helm-locate-command)
+                  (executable-find "gupdatedb"))
              nil "Unsupported locate version")
```

```elisp
(setq helm-locate-command
      "glocate %s %s"
      helm-locate-create-db-command
      "gupdatedb --output='%s' --localpaths='%s'")

(setq helm-locate-project-list
      (list "/Users/xcy/.emacs.d/"))
```

**Comment by dbarros** [comment]
Thanks, @xuchunyang. I'll try you suggestion.

**Comment by tlkahn** [comment]
This works. Thanks!
