### ISSUE TITLE
Case sensitive helm-etags-select

### ISSUE THREAD

**Issue by user471** [emacs-helm/helm#1298]
If ```TAGS``` has two tags ```foo``` and ```Foo``` and you use ```helm-etags-select``` over ```Foo``` helm suggest both tags. Is it possible to go directly to ```Foo``` tags?

**Comment by thierryvolpiatto** [comment]
user471 <notifications@github.com> writes:

> If TAGS has two tags foo and Foo and you use helm-etags-select over
> Foo helm suggest both tags

No, this is not true, at least not reproductible here with default
setting, that is `helm-case-fold-search` set to 'smart.

If pattern == Foo => helm display only Foo.
If pattern == foo => helm display indeed Foo and foo.

Are you sure that you type "Foo" and not "foo" and you have not modified
`helm-case-fold-search`.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by user471** [comment]
```helm-case-fold-search``` is ```'smart```
When you use ```helm-etags-select``` on empty space and type Foo then yes, helm shows only Foo, but if you use ```helm-etags-select``` with cursor over Foo, it shows foo and Foo.

**Comment by thierryvolpiatto** [comment]
user471 <notifications@github.com> writes:

> helm-case-fold-search is 'smart
> When you use helm-etags-select on empty space and type Foo then yes,
> helm shows only Foo, but if you use helm-etags-select with cursor over
> Foo, it shows foo and Foo.

Same I can't reproduce here, start from ./emacs-helm.sh.
With cursor on "Foo" in source file, cursor jump to beginning of line.

Otherwise I see a bug in helm-imenu where both Foo and foo are shown.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by user471** [comment]
>Otherwise I see a bug in helm-imenu where both Foo and foo are shown.

Maybe, it could be about this bug. Instead of jump to ```Foo``` location helm shows ```foo``` and ```Foo```.
![foo](https://cloud.githubusercontent.com/assets/5988253/11938712/bf517756-a82d-11e5-8890-38c03fcf94b1.png)

**Comment by thierryvolpiatto** [comment]
Finally in helm-imenu, the problem occur only with fuzzy matching enabled, (which is not a problem in this case), with etags I see no problems at all.
So I see no bug here.

**Comment by user471** [comment]
TAGS file
```

c:/bar.js,88
Foo14,
foo18,
```
foo.js file
```
Foo
```
When you use ```helm-etags-select``` on Foo do you jump directly to Foo tag in bar.js file?

**Comment by thierryvolpiatto** [comment]
user471 <notifications@github.com> writes:

> TAGS file
>
> c:/bar.js,88
> Foo�14,
> foo�18,
>
> foo.js file
>
> Foo
>
> When you use helm-etags-select on Foo do you jump directly to Foo tag in bar.js file?

If you give me a js file from where I can generate a TAGS file and you
are using a minimal emacs helm configuration, perhaps we can compare our
results...

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by user471** [comment]
you can open foo.js and use helm-etags-select on Foo
[helmtags.zip](https://github.com/emacs-helm/helm/files/71730/helmtags.zip)

**Comment by thierryvolpiatto** [comment]
user471 <notifications@github.com> writes:

> you can open foo.js and use helm-etags-select on Foo
> helmtags.zip

Thanks, for the files, I still can't reproduce, when using
helm-etags-select from foo.js and cursor in on "Foo", it jump immediately
to "Foo" in test.js.

Did you try from a minimal helm setting (only emacs -Q + helm) ?

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by user471** [comment]
Thank, it means something wrong with my settings.
