### ISSUE TITLE
the repeat (C-x z) command is canceled.

### ISSUE THREAD

**Issue by vibrys** [emacs-helm/helm#1299]
Hallo Helm Team.

The following code invokes some command (grep here, but it does not matter) in a 0.5sec latency within post-command-hook.

After evaluating it, I'm doing compare-windows of two "*.txt" files. Then I'm using C-x z to repeat the comparison process.

When buffers being compared are on local host all is well, but if I compare buffers that sit on (tramp) remote host (/sudo::/ in my case), then under SOME CONDITIONS repeating is canceled and of course I end up with additional `z` character pressed into buffer being compared.

This happens only when following package is loaded before remote "*.txt" files to be compared are visited:
(require 'helm-org)

I'm running
helm-20151221.2206

emacs-version:
24.5.1

best regards

#+BEGIN_SRC elisp

  (setq vv-timer nil)
  (setq vv-interval 0.5)
  (setq password-cache-expiry nil)

  (defun vv-fun ()
    (interactive)
    (apply #'start-file-process "grep-grep" nil "grep" (list "." "/bin/grep")))

  (defun vv-fun-timer ()
    (interactive)
    (when (and (buffer-file-name) (string= (file-name-extension (buffer-file-name)) "txt"))
      (when vv-timer
        (cancel-timer vv-timer))
      (setq vv-timer
            (run-with-idle-timer vv-interval nil (function vv-fun)))))

  (add-hook 'post-command-hook (function vv-fun-timer))
#+END_SRC

**Comment by thierryvolpiatto** [comment]
Sorry, but this have nothing to do with helm.

**Comment by vibrys** [comment]
why do You think so, ie. could You be more specific?

**Comment by thierryvolpiatto** [comment]
vibrys <notifications@github.com> writes:

> why do You think so, ie. could You be more specific?

I see no relation with your problem and helm or helm-org, no code is
running there that may affect behavior of emacs on remote files.

-- 
Thierry
https://emacs-helm.github.io/helm/
