### ISSUE TITLE
helm-mini treats the buffer in an inactive split as the current one

### ISSUE THREAD

**Issue by joonro** [emacs-helm/helm#1301]
Hi,

I asked this at stackoverflow (http://emacs.stackexchange.com/questions/19069/), but it seems I should report this here. 

Currently, it seems `helm-mini` treats a buffer as currently active one even if it is open in an inactive split, and puts the buffer on the bottom of the `buffers` list.

For example, suppose I have a two splits and `test.txt` is open in one of them. Sometimes I want to open `test.txt` in the current split, but when I do `helm-mini`, it puts `test.txt` on the bottom of the list as if it is the current one, which makes selecting that file inconvenient.

It would be great if `helm-mini` treats the buffer in an inactive split as the most recent one.

**Comment by thierryvolpiatto** [comment]
Joon Ro <notifications@github.com> writes:

> Hi,
>
> I asked this at stackoverflow
> (http://emacs.stackexchange.com/questions/19069/), but it seems I
> should report this here.
>
> Currently, it seems helm-mini treats a buffer as currently active one
> even if it is open in an inactive split, and puts the buffer on the
> bottom of the buffers list.
>
> For example, suppose I have a two splits and test.txt is open in one
> of them. Sometimes I want to open test.txt in the current split, but
> when I do helm-mini, it puts test.txt on the bottom of the list as if
> it is the current one, which makes selecting that file inconvenient.
>
> It would be great if helm-mini treats the buffer in an inactive split
> as the most recent one.

No, it make sense a visible buffer goes to the bottom of list, because
when you want to go to it, you don't need helm (i.e completion), you
already know where this buffer is so you just have to do `other-window`
to go to it.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by thierryvolpiatto** [comment]
I suggest also that you set `helm-move-to-line-cycle-in-source` to
non-nil, which will allow you to reach bottom of list easily with `C-p`
when you are at first candidate.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by joonro** [comment]
I don't want to go to it - I want to open the buffer in the current split so I have the same buffer in both splits. I find myself doing this quite often. For example, I often have two splits showing the same buffer to edit different parts of the same file simultaneously. Sometimes I switch to another buffer to do a quick edit. Then when I want to come back to the original buffer, it is not convenient because it is on the bottom list.

**Comment by joonro** [comment]
Thanks for the `helm-move-to-line-cycle-in-source` suggestion. I actually have it non-nil, but it does not help much as I have more buffers open, since with many buffers open the buffer I want does not even show up the buffers list so I cannot use `C-p` to go to it quickly. I have to type a part of the name of the buffer for it to show up.

**Comment by thierryvolpiatto** [comment]
Joon Ro <notifications@github.com> writes:

> Thanks for the helm-move-to-line-cycle-in-source suggestion. I
> actually have it non-nil, but it does not help much as I have more
> buffers open, since with many buffers open the buffer I want does not
> even show up the buffers list so I cannot use C-p to go to it
> quickly. I have to type a part of the name of the buffer for it to
> show up.

Because you have many buffers (more than 100) and your
`helm-candidate-number-limit` is to low, increase it, here for example I
use 200:

    (defmethod helm-setup-user-source ((source helm-source-buffers))
      (set-slot-value source 'candidate-number-limit 200))

Or you can set it globally to a higher value.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by thierryvolpiatto** [comment]
And if you really want to have your visibles buffers on top of list, you
can do something like this:

    (add-hook 'ido-make-buffer-list-hook 'helm/modify-ido-temp-list)
    (defun helm/modify-ido-temp-list ()
      (let ((visible-buffers (cl-loop for w in (window-list)
                                      collect (buffer-name (window-buffer w)))))
        (setq ido-temp-list (append visible-buffers
                                    (subseq ido-temp-list 0
                                            (- (length ido-temp-list)
                                               (length visible-buffers)))))))

HTH.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by joonro** [comment]
Thanks a lot. As you said, it seems the problem was `helm-candidate-number-limit`. For some reason I had `(setq helm-candidate-number-limit 25)` before `(helm-mode 1)`. When I increase this using `C-p` becomes much better. 

I have a quick question though - it seems that when I set the limit to 25, my `Buffers` list only shows 14 candidates instead of 25, and that was making the issue bad for me since I could only go 14. (It shows 16 candidates with the limit set to 30, etc). Is this intentional or something is wrong with my setting?

**Comment by thierryvolpiatto** [comment]
Joon Ro <notifications@github.com> writes:

> Thanks a lot. As you said, it seems the problem was
> helm-candidate-number-limit. For some reason I had (setq
> helm-candidate-number-limit 25) before (helm-mode 1).  When I increase
> this using C-p becomes much better.

I use 200 for buffers personally, it is more or less the number of
buffers I have always open.

> I have a quick question though - it seems that when I set the limit to
> 25, my Buffers list only shows 14 candidates instead of 25, and that
> was making the issue bad for me since I could only go 14. (It shows 16
> candidates with the limit set to 30, etc). Is this intentional or
> something is wrong with my setting?

No, it is intentional, I guess helm remove the ignored buffers from the
25 candidates, which may lead to 14 buffers more or less depending which
buffers are open.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by thierryvolpiatto** [comment]
Also for the code above, you may want to remove the duplicates from the list:

```elisp
(defun helm/modify-ido-temp-list ()
  (let ((visible-buffers (cl-loop with bl
                                  for w in (window-list)
                                  for b = (buffer-name (window-buffer w))
                                  unless (member b bl)
                                  collect b into bl
                                  finally return bl)))
    (setq ido-temp-list (append visible-buffers
                                (subseq ido-temp-list 0
                                        (- (length ido-temp-list)
                                           (length visible-buffers)))))))
```

**Comment by thierryvolpiatto** [comment]
Even cleaner is to use `butlast`:

```elisp

(defun helm/modify-ido-temp-list ()
  (let ((visible-buffers (cl-loop with bl
                                  for w in (window-list)
                                  for b = (buffer-name (window-buffer w))
                                  unless (member b bl)
                                  collect b into bl
                                  finally return bl)))
    (setq ido-temp-list (append visible-buffers
                                (butlast ido-temp-list
                                         (length visible-buffers))))))
```

**Comment by joonro** [comment]
Thank you so much - your code works beautifully, except that it would be great if it sends the buffer in the current split to the bottom. Unfortunately, I do not have enough knowledge to modify your code.

I have tried different things, and I found that helmized `switch-to-buffer` actually does pretty much what I want. (It seems it just puts buffers in recent order even if a buffer is open in another split) So I might just use that.

Thank you so much for your help!

**Comment by thierryvolpiatto** [comment]
Joon Ro <notifications@github.com> writes:

> Thank you so much - your code works beautifully, except that it would
> be great if it sends the buffer in the current split to the
> bottom. Unfortunately, I do not have enough knowledge to modify your
> code.

I am not sure to understand what you want exactly, but yes this code can
be modified easily to display the buffers in the order you want.

> I have tried different things, and I found that helmized
> switch-to-buffer actually does pretty much what I want. (It seems it
> just puts buffers in recent order even if a buffer is open in another
> split) So I might just use that.

Yes but you will loose many cool features of helm-buffers-list.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by joonro** [comment]
> Yes but you will loose many cool features of helm-buffers-list.

You are right. I quickly realized this. :)

> I am not sure to understand what you want exactly, but yes this code can
> be modified easily to display the buffers in the order you want.

Sorry, I may not have explained it clearly. Essentially what I want is `helm-mini` to show buffers in the *order they were visited.* It already does that, except that it treats visible buffers differently - it puts all the visible buffers on the bottom of the list, even the ones that are not in the active split. 

I think it makes sense to send the buffer in the currently active split to the bottom, but otherwise it would be more consistent if `helm-mini` sorts other buffers in the order they were visited, even if they are visible in other splits.

Please let me know if this is not clear, and thanks a lot for your patience.

**Comment by thierryvolpiatto** [comment]
Joon Ro <notifications@github.com> writes:

> Sorry, I may not have explained it clearly. Essentially what I want is
> helm-mini to show buffers in the order they were visited. It already
> does that, except that it treats visible buffers differently - it puts
> all the visible buffers on the bottom of the list, even the ones that
> are not in the active split.

So you want the visibles buffers on top of list but sorted as they are
actually in the bottom of the list, right ?

> I think it makes sense to send the buffer in the currently active
> split to the bottom,

This is what I don't understand, which is this buffer ? 
The current-buffer ?

What do you mean by "active split"?

> but otherwise it would be more consistent if helm-mini sorts other
> buffers in the order they were visited, even if they are visible in
> other splits.

Not for everybody.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by joonro** [comment]
> So you want the visibles buffers on top of list but sorted as they are
> actually in the bottom of the list, right ?

No. Please forget about putting visible buffers on the top - I'm sorry I shouldn't have started with this. What I want is `helm-mini` to show all buffers in the order they were visited (except the buffer in the selected window, of course). It acts consistently when I only have one window in Emacs. But when I have 2 windows, `helm-mini` puts not only the buffer in the selected window, but also the one in the other window on the bottom of the list.

So it is not that I want visible buffers on top of the list. I just want `helm-mini` not to treat the buffer in other windows differently.

I attached screenshots. Suppose `delete.txt` is the last visited buffer and `*GNU Emacs*` is in the selected window. When I have only one window, `helm-mini` puts `delete.txt` on the top:

![2015-12-25 22_20_59-calendar](https://cloud.githubusercontent.com/assets/1063143/12005368/35482902-ab56-11e5-96ab-3cb1ca217d96.png)

However, when I have two windows, and if `delete.txt` is open in the other window, `helm-mini` puts `delete.txt` on the second to the bottom of the list, even though `delete.txt` is the last visited buffer. 

![2015-12-25 22_23_14-calendar](https://cloud.githubusercontent.com/assets/1063143/12005369/3a64c2ba-ab56-11e5-8b2d-9f0a9d42f1a3.png)

For me this is inconsistent behavior - I would expect `helm-mini` to show the buffers in the same order as the first case. Hopefully this is clear.

**Comment by thierryvolpiatto** [comment]
Joon Ro <notifications@github.com> writes:

> For me this is inconsistent behavior - I would expect helm-mini to
> show the buffers in the same order as the first case. Hopefully this
> is clear.

I hope :-), is the following code fit your needs?

    (defun helm/modify-ido-temp-list ()
      (let ((bl (mapcar #'buffer-name (buffer-list (selected-frame)))))
        (setq ido-temp-list (append (cdr bl) (list (car bl))))))

This will always show the last visited buffer in first position.
You are right that the last visited buffers should be sorted in the same
way if they are visible or not, even if they appear in end of list or
not.  We are using ido to make the buffer list, but it seems it fails to
do this whereas the regular buffer-list do it correctly.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by joonro** [comment]
Yes I'm not sure if there would be any corner cases, but it seems to be working perfectly. Thank you so much! I'm sorry I should have included those screenshots when I open the issue - it would have been much easier to communicate the issue. You can close this issue unless you want to add anything. 

Happy new year!

**Comment by thierryvolpiatto** [comment]
Great, closing now.
Happy new year!
