### ISSUE TITLE
Could helm-apropos show small description from apropos?

### ISSUE THREAD

**Issue by user471** [emacs-helm/helm#1304]
It would be nice if you could see small descriptions like this
![helm](https://cloud.githubusercontent.com/assets/5988253/12009460/0eab1fa0-ac89-11e5-831d-5047e6583af7.png)
Maybe you could even toggle these descriptions in any helm window.
You can use ```helm-follow-mode```, but it's much slower (UI-wise) approach.

**Comment by michael-heerdegen** [comment]
I think I like the idea.

**Comment by thierryvolpiatto** [comment]
helm-apropos is something that may become really slow if we add to much decorations.
What you are asking for needs a filtered-candidate function that show this line and also align the docstring correctly for visibility, this is costly and will slowdown helm-apropos for a small benefit.
Actually persistent action allow you to see documentation of symbol easily.
OTH if one wants to have such information it could be displayed in mode-line, the code is already there, just need to accomodate it to allow its use in hooks.

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> helm-apropos is something that may become really slow if we add to
> much decorations.  What you are asking for needs a filtered-candidate
> function that show this line and also align the docstring correctly
> for visibility, this is costly and will slowdown helm-apropos for a
> small benefit.

Not necessarily.  This is only done for some hundred candidates.  It
would not cause a notable delay, I think.

> Actually persistent action allow you to see documentation of symbol
> easily.  OTH if one wants to have such information it could be
> displayed in mode-line, the code is already there, just need to
> accomodate it to allow its use in hooks.

I like that idea even more.  Displaying the doc along with the
completions can be distracting.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> I like that idea even more. Displaying the doc along with the
> completions can be distracting.

Ok we could stay on that, if you want @Michael you can make the change.

Thanks.

-- 
Thierry

**Comment by michael-heerdegen** [comment]
I guess I could do that.

@thierryvolpiatto What's the purpose of `helm-show-info-in-mode-line-delay` having such a huge default of 12 seconds?  Is this option so useful at all?

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> I guess I could do that.
>
> @thierryvolpiatto What's the purpose of
> helm-show-info-in-mode-line-delay having such a huge default of 12
> seconds? Is this option so useful at all?

Yes it is important otherwise the mode-line is quickly updated to its
default value and you have not the time to read, the long delay is not
important, you can even increase it, as soon you hit a key on your
keyboard the mode-line info will disapear.

-- 
Thierry

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> > @thierryvolpiatto What's the purpose of
> > helm-show-info-in-mode-line-delay having such a huge default of 12
> > seconds? Is this option so useful at all?
>
> Yes it is important otherwise the mode-line is quickly updated to its
> default value and you have not the time to read, the long delay is not
> important, you can even increase it, as soon you hit a key on your
> keyboard the mode-line info will disapear.

I see.

Should helm-show-info-in-mode-line be moved to a better place (it's
currently in helm-eval.el) so that it is available from anywhere in
helm?

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Should helm-show-info-in-mode-line be moved to a better place (it's
> currently in helm-eval.el) so that it is available from anywhere in
> helm?

Yes, in this case helm-lib seems a good place.

-- 
Thierry

**Comment by michael-heerdegen** [comment]
OTOH I think the header-line, or the echo area respectively when helm-echo-input-in-header-line -> t, would be a better position to show such info.  The mode-line contains more useful content than these.

**Comment by thierryvolpiatto** [comment]
No news since months now, closing.
