### ISSUE TITLE
Helm taking over a minute to start

### ISSUE THREAD

**Issue by nayefc** [emacs-helm/helm#1305]
I've been using Helm for a very long time. I may have updated soon, but now it takes over a minute to start. I even cleared out my init file and just started helm the way the Github README suggests, and I'm facing the same issue.

When the init file is clear, and using the default way to initialise Helm:
```lisp
(require 'helm-config) ;; or even (require 'helm)
(helm-mode 1)
```

Emacs starts up with an empty screen and cursor until Helm loads. When I use `use-package` and have it lazy load, Emacs freezes and displays this message in the bottom as it loads: `Loading dired-x...done`.

Any ideas why this is happening now, or even any ideas on how to profile Helm?

Any suggestions are greatly appreciated as I heavily depend on Helm and this is a big problem for me.

**Comment by thierryvolpiatto** [comment]
There is no reason helm take so long to startup, the only reason I see is related to tramp, see #1000.

**Comment by nayefc** [comment]
Yup this was it. Makes sense why this started happening since I travelled. Thanks a lot.
