### ISSUE TITLE
What's the purpose of `helm-highlight-number-lines-around-point`?

### ISSUE THREAD

**Issue by michael-heerdegen** [emacs-helm/helm#1306]
Hi,

the default binding is 15, but that doesn't seem to have any effect - helm-highlight-current-line always seems to highlight exactly one line.

Second question: Is `helm-highlight-number-lines-around-point` -> `nil` a valid binding?  The definition doesn't say it can be nil, but `helm-highlight-current-line` tests it with `null` (but only after testing with `zerop`, which raises an error when the argument is nil, so it's completely useless).

TIA, Michael.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Hi,
>
> the default binding is 15, but that doesn't seem to have any effect -
> helm-highlight-current-line always seems to highlight exactly one line

No, it is working it is here to highlight the matches around matched
line, 15 before and 15 after.
I use 30 personally.

> Second question: Is helm-highlight-number-lines-around-point -> nil a
> valid binding? The definition doesn't say it can be nil, but
> helm-highlight-current-line tests it with null (but only after testing
> with zerop, which raises an error when the argument is nil, so it's
> completely useless)

Right, good catch, probably we have to invert the tests (i.e null before
zerop).

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by thierryvolpiatto** [comment]
Here a screenshot showing the highlighted item around line:

![screenshot - 29122015 - 18 50 32](https://cloud.githubusercontent.com/assets/1533939/12039019/2c045a6e-ae5d-11e5-970a-c1a542d744ca.png)

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> No, it is working it is here to highlight the matches around matched
> line, 15 before and 15 after.  I use 30 personally.

Ahh, I just misread the doc.  Ok, it's working.

> > Second question: Is helm-highlight-number-lines-around-point -> nil a
> > valid binding? The definition doesn't say it can be nil, but
> > helm-highlight-current-line tests it with null (but only after testing
> > with zerop, which raises an error when the argument is nil, so it's
> > completely useless)
>
> Right, good catch, probably we have to invert the tests (i.e null before
> zerop).

Good, I'll do that, thanks.


Michael.

**Comment by michael-heerdegen** [comment]
BTW, I was wrong because the name `helm-highlight-number-lines-around-point` is misleading.  This is about highlighting matches, not lines.  Thus my dumb question.

**Comment by michael-heerdegen** [comment]
I've fixed the `zerop` bug and the indentation in https://github.com/emacs-helm/helm/commit/86967290b9c957c652a4b1099c4b1984767593f9.

Should we rename the variable?

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> I've fixed the zerop bug and the indentation in 8696729.

Great, thanks.

> Should we rename the variable?

If you think we should, go ahead ;-).

`helm-highlight-matches-around-point-max-lines` or something like that ?

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by thierryvolpiatto** [comment]
For indentation, I use `common-lisp-indent-function` as
`lisp-indent-function` for some reasons, 
this is why you can find in many places cl style
indentation for `if`, but I don't care if you use emacs-lisp style (I
use it when using emacs-25, rarely though, but the switch to emacs-25 is
near now...)

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> `helm-highlight-matches-around-point-max-lines` or something like that
> ?

Probably.  And I think we could temporarily still provide the old name
via define-obsolete-variable-alias.


BTW, I also used to use common-lisp-indent-function, but stopped doing
so, I think because it doesn't support important elisp macros or so.
And because you can't use it when working in Emacs Lisp source files.
It's better to have one standard obligatory indentation rule.


Michael.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Thierry Volpiatto <notifications@github.com> writes:
>
>> `helm-highlight-matches-around-point-max-lines` or something like that
>> ?
>
> Probably. And I think we could temporarily still provide the old name
> via define-obsolete-variable-alias.

Exactly, it is better to do so when changing a variable name enabled
since some time now to not break users settings.

> BTW, I also used to use common-lisp-indent-function, but stopped doing
> so, I think because it doesn't support important elisp macros or so.
> And because you can't use it when working in Emacs Lisp source files.
> It's better to have one standard obligatory indentation rule.

With emacs-24 emacs lisp indentation style sucks with many things like
cl-loop, it is why I use cl indentation style, in emacs-25 indentation is
much better and indeed you don't need cl indentation style.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by michael-heerdegen** [comment]
I've finally done this in https://github.com/emacs-helm/helm/commit/e1780d2e55d98bfeed26ffb589ad836142390dc2.
