### ISSUE TITLE
Mark all on buffer open

### ISSUE THREAD

**Issue by seanirby** [emacs-helm/helm#1310]
I'm trying to write a helm source that starts with all items selected.   I've tried the below but it fails because the current helm window can't be retrieved(I think).  Any ideas on how to make this work?

```
(setq f (lambda ()
	      (helm-mark-all)))

(setq some-helm-source
 `(.... (after-init-hook . f) ....))

**Comment by thierryvolpiatto** [comment]
```elisp
(let ((helm-after-initialize-hook '((lambda () (with-helm-buffer
                                                 (run-at-time 0.01 nil #'helm-mark-all))))))
  (helm :sources (helm-build-sync-source "test"
                   :candidates '(foo bar baz))
        :buffer "*helm test*"))
```

**Comment by seanirby** [comment]
Thanks Thierry!  I think adding the delay did the trick.  I ended up using the code below since it's a bit clearer for me. 

```
(let ((f (lambda () (with-helm-buffer
                      (run-at-time 0.01 nil #'helm-mark-all)))))
  (helm :sources (helm-build-sync-source "test"
                   :candidates '(foo bar baz)
                   :after-init-hook 'f)
        :buffer "*helm test*"))

**Comment by thierryvolpiatto** [comment]
Sean Irby <notifications@github.com> writes:

> I ended up using the code below since it's a bit clearer for me.

Good, you can add the lambda directly in :after-init-hook which is even
simpler than let-bounding f and using the 'f symbol.


-- 
Thierry

**Comment by seanirby** [comment]
I tried to do that originally but it complained that :after-init-hook only accepted a symbol.  Am I missing something?  Is there an inline way to convert an anonymous function into a symbol.

**Comment by thierryvolpiatto** [comment]
Sean Irby <notifications@github.com> writes:

> I tried to do that originally but it complained that :after-init-hook
> only accepted a symbol.

Oh, really ? It should accept a lambda too and a list of
functions/lambda, I will fix this ASAP.
Thanks.

-- 
Thierry

**Comment by michael-heerdegen** [comment]
In Emacs, hooks are symbols bound to a list of functions.  A list of functions, or a function, is not a hook, and will not work: `run-hooks` (which we use) does only accept hooks in that sense.  If you want something else, don't call it a hook, and don't use `run-hooks` to execute it.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> In Emacs, hooks are symbols bound to a list of functions.

Indeed.

> A list of functions, or a function, is not a hook, and will not work:
> run-hooks (which we use) does only accept hooks in that sense. If you
> want something else, don't call it a hook, and don't use run-hooks to
> execute it.

Right.

After revisiting this, I wanted to allow using directly a lambda by
bounding value to a temp symbol, but this would be too complex for this,
so let use a symbol (hook) as value for these slots.

Thanks.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Thierry Volpiatto <thierry.volpiatto@gmail.com> writes:

> Michael Heerdegen <notifications@github.com> writes:
>
>> In Emacs, hooks are symbols bound to a list of functions.
>
> Indeed.
>
>> A list of functions, or a function, is not a hook, and will not work:
>> run-hooks (which we use) does only accept hooks in that sense. If you
>> want something else, don't call it a hook, and don't use run-hooks to
>> execute it.
>
> Right.
>
> After revisiting this, I wanted to allow using directly a lambda by
> bounding value to a temp symbol, but this would be too complex for this,
> so let use a symbol (hook) as value for these slots.

I finally endup with something usable, now one can add a lambda directly
in slot, like:

    (helm :sources (helm-build-sync-source "test"
                     :candidates '(foo bar baz)
                     :after-init-hook
                     (lambda () (with-helm-buffer
                                  (run-at-time 0.01 nil #'helm-mark-all))))
          :buffer "*helm test*")

Or define a hook and use it:

   (defvar test-hook nil)
   (add-hook 'test-hook (lambda () (with-helm-buffer
                                     (run-at-time 0.01 nil #'helm-mark-all))))

   (helm :sources (helm-build-sync-source "test"
                      :candidates '(foo bar baz)
                      :after-init-hook 'test-hook)
         :buffer "*helm test*")

Binding a symbol with let is NOT working:

    (let ((f (lambda () (with-helm-buffer
                          (run-at-time 0.01 nil #'helm-mark-all)))))
      (helm :sources (helm-build-sync-source "test"
                       :candidates '(foo bar baz)
                       :after-init-hook 'f)
            :buffer "*helm test*"))

-- 
Thierry

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> I finally endup with something usable, now one can add a lambda
> directly in slot, like:
> [...]
> Or define a hook and use it:
> [...]

Seems a reasonable fix, thanks.

> Binding a symbol with let is NOT working: [...]

It doesn't have to.


Can we close?

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

>> Binding a symbol with let is NOT working: [...]
>
> It doesn't have to.

Yes.

> Can we close?

Yes please.

Thanks.

-- 
Thierry

**Comment by michael-heerdegen** [comment]
Mmh, it's closed already ;-)   So, ehm, goodbye...
