### ISSUE TITLE
Anyone knows if there is a way to quick move to predefine directories (via bookmarks?) within helm session?

### ISSUE THREAD

**Issue by zeltak** [emacs-helm/helm#1313]
Hi all. Anyone knows if there is a way to quick move to predefine directories (via bookmarks?) within helm session?

For example , i start a helm find-file session or dired-do-copy (using helm backend) from dired.\
i start  in ~/ but want to move to ~/.config/foo/bar/. I dont want to manually traverse the whole file system with arrow keys but rather launch a bookmark to take me (within helm) directly to ~/.config/foo/bar/.

i tried (following the helm help system) to hit C-x r b inside the helm-find-files session but that doesn't
work for me.
any suggestions?

thx!

z

**Comment by thierryvolpiatto** [comment]
zeltak <notifications@github.com> writes:

> Hi all Anyone knows if there is a way to quick move to predefine
> directories (via bookmarks?) within helm session?

From helm-find-files, navigate to your directory, then hit `C-x r m`,
now this directory is accessible at any time with C-x r b from
helm-find-files session, you can also retrieve it starting from
helm-filtered-bookmarks.
You have also the directory history accessible from M-p at any time.

And you have also `C-h m` which is the helm help where all this is
explained...


-- 
Thierry

**Comment by zeltak** [comment]
thx for the quick answer
>From helm-find-files, navigate to your directory, then hit `C-x r m`
i tried this but get the following error
```helm: Error: Trying to run helm within a running helm session```

this also applies when running C-x r b

thx so much 

Z

**Comment by thierryvolpiatto** [comment]
I guess you are not using helm-find-files

**Comment by zeltak** [comment]
ahh i see. for some reason (i guess that normal? :)) the normal find-file has also a helm interface?
now that i launch the proper helm-find-files it works well :)
can i rebind C-x r m to something else? is there a helm-find-files mode or something similar?

thx and happy new years!

Z

**Comment by thierryvolpiatto** [comment]
zeltak <notifications@github.com> writes:

> ahh i see. for some reason (i guess that normal? :)) the normal
> find-file has also a helm interface?

Yes helmized by helm-mode.

> now that i launch the proper helm-find-files it works well :) can i
> rebind C-x r m to something else? is there a helm-find-files mode or
> something similar?

Use helm-find-files for all files tasks if you want the bookmark
feature.

> thx and happy new years!

Happy new year too, and don't forget to read the doc (C-h m is your
friend).
See also the wiki and you will find a link to the excellent @tuhdo
tutorial on the README.

-- 
Thierry
