### ISSUE TITLE
helm-find-files doesn't work with .authinfo.gpg entry

### ISSUE THREAD

**Issue by YorkZ** [emacs-helm/helm#1314]
In the file `~/.authinfo.gpg`, I have the following entry:

machine MY-SYSTEM-NAME port sudo login root password "MY ROOT PASSWORD"

If I start emacs as `emacs -Q,`, then press `C-x C-f /sudo::/etc/hosts`, the root password was successfully read from the file `~/.authinfo.gpg` and sent automatically. However, this is not the case when using `helm-find-files`, where it locked up after producing the message `Decrypting /home/LOGIN-NAME/.authinfo.gpg...done`.

Thanks,

York

**Comment by thierryvolpiatto** [comment]
York Zhao <notifications@github.com> writes:

> In the file ~/authinfogpg, I have the following entry:
>
> machine MY-SYSTEM-NAME port sudo login root password "MY ROOT PASSWORD"

Here the entries I have in my ".authinfo.gpg" file:

machine localhost port sudo login root password xxxxxxx
default port sudo login root password xxxxxxxxx

> If I start emacs as emacs -Q,, then press C-x C-f /sudo::/etc/hosts,
> the root password was successfully read from the file ~/authinfogpg
> and sent automatically However, this is not the case when using
> helm-find-files, where it locked up after producing the message
> Decrypting /home/LOGIN-NAME/authinfogpgdone

It is working fine here, can't reproduce with the entries above in
".authinfo.gpg" (perhaps the localhost entry is no more needed nowaday).

Are you prompted for your gpg password ?

-- 
Thierry

**Comment by YorkZ** [comment]
> (perhaps the localhost entry is no more needed nowaday).

I added the default entry exactly as yours just now, but it still didn't work.

> Are you prompted for your gpg password ?

Yes, I was prompted for entering my gpg password the first time, after that it
has been cached so I no longer had to enter it. My emacs was locked up until I
hit `C-g`.

**Comment by YorkZ** [comment]
I've tried loading helm only, without any other stuff in my .emacs, and it worked! Therefore, it seems that something else in my .emacs was causing this. If that's the case, I apologize for reporting this here. I'll dig it tonight until I find out the culprit, at which time we will close this issue.

Thanks,
York

**Comment by michael-heerdegen** [comment]
I would try setting debug-on-quit -> t, so C-g will pop up a backtrace of what Emacs is doing.

**Comment by YorkZ** [comment]
> I would try setting debug-on-quit -> t, so C-g will pop up a backtrace of what
> Emacs is doing.

I've tried, but the backtrace didn't give me any useful information. In the end, I used binary search to help me finding out the guilty! It was eclim, which actually breaks the plain `find-file` in this case.

York
