### ISSUE TITLE
If I type too fast I get unexpected results in completion

### ISSUE THREAD

**Issue by rrthomas** [emacs-helm/helm#1315]
For example, with `helm-mode` on, if I type `M-x grep RET` really fast, Helm's completion buffer has not yet caught up, and executed `org-move-item-down`, which happens to be the first command in the empty `M-x` buffer. It looks as though the completion buffer is updated asychronously (yay!) but that pressing RET does not wait for the buffer to get to a state consistent with the minibuffer (boo!).

I'm using helm installed from current git.

**Comment by thierryvolpiatto** [comment]
Reuben Thomas <notifications@github.com> writes:

> For example, with helm-mode on, if I type M-x grep RET really fast,
> Helm's completion buffer has not yet caught up, and executed
> org-move-item-down, which happens to be the first command in the empty
> M-x buffer It looks as though the completion buffer is updated
> asychronously (yay!) but that pressing RET does not wait for the
> buffer to get to a state consistent with the minibuffer (boo!)

See #1157 it is probably related. 

Otherwise it seems you are using M-x == execute-extended-command, which
is helmized by helm-mode, but not optimized, you have better time using
instead helm-M-x and bind it to M-x.

-- 
Thierry

**Comment by rrthomas** [comment]
Thanks very much for the tip, that indeed does work around the problem, and as you say, is a better configuration.

**Comment by thierryvolpiatto** [comment]
Ok so your issue was just about using helm-M-x instead of execute-extended-command, closing now.
