### ISSUE TITLE
Can I replace $HOME by ~ in helm-find-files prompt?

### ISSUE THREAD

**Issue by rrthomas** [emacs-helm/helm#1316]
I was used to this from normal Emacs find-file. I can't see how to do this in Helm, and I can't find any mention of it in the source, so maybe it's not possible?

**Comment by thierryvolpiatto** [comment]
Reuben Thomas <notifications@github.com> writes:

> I was used to this from normal Emacs find-file I can't see how to do
> this in Helm, and I can't find any mention of it in the source, so
> maybe it's not possible?

helm-find-files is working with absolute paths, but it is not a problem
as you don't have to type it.
When you want to go to $HOME just type ~/ at end of pattern.
For more info on this (and any other stuff) type C-h m.

So to answer to your question, no it is not possible.

-- 
Thierry

**Comment by rrthomas** [comment]
Thanks. That's a pity, replacing $HOME by ~ is a nice prettification in standard Emacs.

**Comment by thierryvolpiatto** [comment]
Reuben Thomas <notifications@github.com> writes:

> Thanks. That's a pity, replacing $HOME by ~ is a nice prettification
> in standard Emacs.

As long as you will never have to type "/home/you", I don't see the problem.

-- 
Thierry

**Comment by rrthomas** [comment]
It's a little bit of visual clutter.

Some users (not me) may have different home directories on different systems, but still prefer to see "~" to designate their home directory.

I am certainly used to it, even though I always have the same home directory, and now seeing the full path is a (minor) distraction.
