### ISSUE TITLE
Make default `locate` options compatible with mlocate

### ISSUE THREAD

**Issue by rrthomas** [emacs-helm/helm#1317]
mlocate (from RedHat, also packaged in Debian) is a popular alternative `locate`. Unfortunately, it uses `-r` as an alias for `--regexp`, which is a different option from `--regex`. Fortunately, both `locate` and `mlocate` accept `--regex`, and it means the same thing (except that `locate` by default uses Emacs syntax, whereas `mlocate` interprets the regexes as extended regexes; but I think that doesn't affect helm, only the user).

Hence, if you change the default GNU/Linux option from `-r` to `--regex`, then helm will be compatible with both. `--regex` was introduced to GNU locate in 4.2.15, which was released in 2005, so I think it's reasonable to assume it can be handled.

**Comment by thierryvolpiatto** [comment]
Reuben Thomas <notifications@github.com> writes:

> mlocate (from RedHat, also packaged in Debian) is a popular
> alternative locate Unfortunately, it uses -r as an alias for --regexp,
> which is a different option from --regex Fortunately, both locate and
> mlocate accept --regex, and it means the same thing (except that
> locate by default uses Emacs syntax, whereas mlocate interprets the
> regexes as extended regexes; but I think that doesn't affect helm,
> only the user)
>
> Hence, if you change the default GNU/Linux option from -r to --regex,
> then helm will be compatible with both --regex was introduced to GNU
> locate in 4215, which was released in 2005, so I think it's reasonable
> to assume it can be handled

This have been discussed several time and I finally choose this default
setting which works without error for most locate versions, even the
older (--regex is not available in previous locate bundled with ubuntu 12.04).
If you have a modern locate, we all use this:

"locate %s -e -A --regex %s"

-- 
Thierry

**Comment by rrthomas** [comment]
Apologies for resurrecting an old discussion.

However, Ubuntu 12.04LTS has locate 4.4.2, which indeed supports `--regex`; as I said above, that option was introduced in 4.2.15. In fact, all current Ubuntu versions have locate 4.4.2.

**Comment by thierryvolpiatto** [comment]
Reuben Thomas <notifications@github.com> writes:

> Apologies for resurrecting an old discussion.
>
> However, Ubuntu 12.04LTS has locate 4.4.2, which indeed supports
> --regex; as I said above, that option was introduced in 4.2.15. In
> fact, all current Ubuntu versions have locate 4.4.2.

As I said I prefer staying with these default as if I switch to --regex
by default (as I already tried), I will have immediate complain and bug
report.

I prefer having a default setting that works not perfectly but
without errors than something than works fine but may lead to errors.

What I can do at least is documenting this in docstring and in embeded
help.

-- 
Thierry

**Comment by rrthomas** [comment]
Unfortunately, the default setting does not work without errors: on my
system, where "locate" is actually mlocate (installed from the standard
Debian/Ubuntu package), -r causes locate to give an error when more than
one argument is given (this is how I discovered this issue).

It is reasonable to decide at some point not to support older systems. As I
already pointed out, all currently-supported versions of Ubuntu ship with
locate 4.4.2, which supports --regex. I checked, and this is also true of
Debian, back to oldoldstable (squeeze).

Since, as I mentioned earlier, the --regex flag is supported in all
versions of GNU locate released in the last 10 years, it does not seem
unreasonable to require users to have a version that is newer.

On 5 January 2016 at 15:33, Thierry Volpiatto <notifications@github.com>
wrote:

>
> Reuben Thomas <notifications@github.com> writes:
>
> > Apologies for resurrecting an old discussion.
> >
> > However, Ubuntu 12.04LTS has locate 4.4.2, which indeed supports
> > --regex; as I said above, that option was introduced in 4.2.15. In
> > fact, all current Ubuntu versions have locate 4.4.2.
>
> As I said I prefer staying with these default as if I switch to --regex
> by default (as I already tried), I will have immediate complain and bug
> report.
>
> I prefer having a default setting that works not perfectly but
> without errors than something than works fine but may lead to errors.
>
> What I can do at least is documenting this in docstring and in embeded
> help.
>
>
> --
> Thierry
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/emacs-helm/helm/issues/1317#issuecomment-169035906>.
>



-- 
http://rrt.sc3d.org

**Comment by michael-heerdegen** [comment]
You can specify -r multiple times.  This also works from the Helm prompt.  You can also specify other options from the Helm prompt.  This was what we decided would be best for the general case.

If you want something different (I do), just configure `helm-locate-command`.  Maybe we should update the doc to be more informative about this issue.

**Comment by rrthomas** [comment]
You can specify `--regex` multiple times. Specifying `-r` multiple times will work with `locate` but not `mlocate`. But either way, I'm not sure what bearing this has on the default value.

**Comment by thierryvolpiatto** [comment]
There is a lot of locate variants, also on MacOsx they use something else IIRC, and our default settings are IMO the best compromise to have something working more or less on all platforms.
I have updated the wiki page at https://github.com/emacs-helm/helm/wiki#configure

**Comment by michael-heerdegen** [comment]
Reuben Thomas <notifications@github.com> writes:

> You can specify --regex multiple times. Specifying -r multiple times
> will work with locate but not mlocate. But either way, I'm not sure
> what bearing this has on the default value.

Works for me, mlocate version 0.26-1, Debian testing.  Note you have to
specify -A to get an and behavior, else you get or.

**Comment by rrthomas** [comment]
@thierryvolpiatto There are already different default settings for other OSes. I am talking about GNU/Linux systems only. I have retitled the issue to reflect this.

**Comment by rrthomas** [comment]
@michael-heerdegen I'm sorry, I got confused. Yes, mlocate's `-r` can be used multiple times. The problem is not that, it is that with the following `helm-locate-command`:

    locate %s -e -r %s

**Comment by rrthomas** [comment]
@thierryvolpiatto thanks for updating the Wiki. However, I still don't understand why you can't change the default. I entirely agree with the criteria you have proposed so far:

1. The default should work on all OSes. That's fine, I only proposed changing the default for GNU/Linux.
2. The default should work on any current system, not just the latest. That's fine, the change I proposed works on all non-obsolete systems (i.e. any currently-supported system). The specific example was given of Ubuntu 12.04, and it was suggested that `--regex` would not work there, but that is false, as I showed. I have also checked CentOS (I can't check RHEL as I don't have a RedHat account), and that supports a sufficiently new version of findutils in CentOS 6.

I suggest that it's excessive for helm to require a recent Emacs (from at most 3 years ago) but to cater to obsolete GNU findutils (from over 10 years ago).

What other locate variants did you have in mind? slocate is subsumed by GNU locate; rlocate is (unfortunately) obsolete. Given the choice between supporting rlocate (for which `-r` is necessary) and mlocate (for which `--regex` is necessary) it seems sensible to choose the latter, which is still widely packaged (rlocate is not available in any supported version of Debian or Ubuntu).

I searched online, and I can find no other GNU/Linux `locate` other than the ones mentioned above.

**Comment by michael-heerdegen** [comment]
Reuben Thomas <notifications@github.com> writes:

> locate %s -e -r %s

Please specify what "does not work" means.

This is what I try from emacs-helm.sh in the minibuffer, using the above,
default helm-locate-command:

 test -r abc -A

And I get files with names containing both "test" and "abc".  Does this
not work for you, or do you expect something different?

**Comment by rrthomas** [comment]
@michael-heerdegen With the default locate command in helm, using GNU locate, you can type

    test abc

and it finds all files with names that contain either `test` or `abc`.

With mlocate you get the error:

    mlocate: non-option arguments are not allowed with --regexp

**Comment by rrthomas** [comment]
(Note: I would not recommend adding `-A` to the default options for another few years, as it is only supported in mlocate since version 0.26, released in 2013. Therefore, in particular, `-A` does not work in the version of mlocate shipped in Ubuntu 12.04.)

**Comment by michael-heerdegen** [comment]
Reuben Thomas <notifications@github.com> writes:

> With mlocate you get the error:
>
> mlocate: non-option arguments are not allowed with --regexp

Ok.  But are you aware of the fact that --regex is about extended,
whereas -r is about basic regexps?

**Comment by rrthomas** [comment]
@michael-heerdegen I am aware of the difference. In GNU locate, by default, `--regex` uses GNU regex syntax, not basic or extended. Therefore, to use `-r` already activates a different syntax; changing which particular syntax it activates does not seem like a big deal.

**Comment by michael-heerdegen** [comment]
Aha, ok.  Then I think it would sense to make that change.  But if there is a chance that some people have a broken helm-locate then using an older Ubuntu (I can't say how likely that is), we should probably not do it now.

**Comment by rrthomas** [comment]
As I said, this is only possible if they are using an unsupported version of Ubuntu (i.e., no security updates). I don't see any reason to support such users specially: they should be concentrating on upgrading! If they have a good reason not to, they can also install a newer findutils.

**Comment by michael-heerdegen** [comment]
Reuben Thomas <notifications@github.com> writes:

> they should be concentrating on upgrading!

Sure, but that doesn't matter.  People sometimes need to use 10 years
old software where they work.

And how about distributions of Gnu/Linux?

We must be sure that the amount of people for that helm-locate will be
broken is nearly zero.  Are you sure we can?

**Comment by rrthomas** [comment]
I'm sorry, I don't follow. I cannot find a supported distribution of GNU/Linux that has a GNU findutils too old to work with my suggested options. Businesses do not tend to use unsupported OSes that no longer receive security updates. In any case, if users of such old systems can install a version of Emacs from only 3 years ago, they can install a version of findutils from less than 10 years ago.

As I said, I quite understand the idea of being backwards compatible, but this seems out of proportion.

**Comment by michael-heerdegen** [comment]
Reuben Thomas <notifications@github.com> writes:

> I'm sorry, I don't follow. I cannot find a supported distribution of
> GNU/Linux that has a GNU findutils too old to work with my suggested
> options. Businesses do not tend to use unsupported OSes that no longer
> receive security updates. In any case, if users of such old systems
> can install a version of Emacs from only 3 years ago, they can install
> a version of findutils from less than 10 years ago.

MMh, maybe you are right.

It is up to @Thierry to decide this.  Maybe the rest of this discussion
made him change his mind.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> It is up to @Thierry to decide this. Maybe the rest of this discussion
> made him change his mind.

I am not against, I am personally using `locate %s -e -A --regex %s`, I
just remember we already did this switch and have to come back to actual
default settings due to complaint of user.
So go ahead @Michael if you are ok to make the change.

-- 
Thierry

**Comment by rrthomas** [comment]
I would be very interested to see the result, in particular in case I made a mistake somewhere above.

**Comment by michael-heerdegen** [comment]
Let's hope the best.
