### ISSUE TITLE
Cannnot rename file with name starting with bracket

### ISSUE THREAD

**Issue by tollerm** [emacs-helm/helm#1319]
Hi,
When I try to rename a file with a name like "[test].txt" using helm-find-files I get a message "Rename 0 files to /path/to/dir" and the file name remains the same.
Best regards, Toller

**Comment by thierryvolpiatto** [comment]
tollerm <notifications@github.com> writes:

> Hi, When I try to rename a file with a name like "[test]txt" using
> helm-find-files I get a message "Rename 0 files to /path/to/dir" and
> the file name remains the same Best regards, Toller

Should be fixed now.

Thanks.

-- 
Thierry

**Comment by tollerm** [comment]
It works now. Thank you very much for resolving this issue.
