### ISSUE TITLE
Height of helm window not fixed at beginning

### ISSUE THREAD

**Issue by tomhk215** [emacs-helm/helm#1321]
(helm-autoresize-mode 1) 
    (setq helm-autoresize-max-height 35
          helm-autoresize-min-height 35)

The issue only happens in recentf. When invoking recentf, it always gives an initial height about 50% of the frame. After entering the first character, it shrinks back to 35 and height fixed after that even removing all pattern entered.

**Comment by thierryvolpiatto** [comment]
Of course you have exactly what is expected with such setting:
A window resized to 35% max on startup that will never be bigger than this and will never be smaller than this.

Try for example max == 80 and min == 10 to see what I mean.

**Comment by tomhk215** [comment]
I know what you mean. But I want the height to always be fixed at 35% . I found that after I change the `helm-ff-file-name-history-recentf`, the issue occurs occasionally. The frame is having a initial height other than 35%.

**Comment by thierryvolpiatto** [comment]
tomhk215 <notifications@github.com> writes:

> I know what you mean. But I want the height to always be fixed at 35%
> . I found that after I change the helm-ff-file-name-history-recentf,
> the issue occurs occasionally. The frame is having a initial height
> other than 35%.

I don't see any issue here, IIUC you are just trying to use
helm-autoresize-mode for fixing a defined size to your windows, which is
not its purpose, all the contrary, and AFAIK it is working fine in this
sense.

-- 
Thierry

**Comment by michael-heerdegen** [comment]
IIUC what @tomhk215 means is that in this case, unlike for other helm commands, the Completions window first pops up with the wrong size, and is resized not before some input is given.  For other helm commands, the Completions window has the correct size from the beginning on, even if the minibuffer is still empty.

**Comment by tomhk215** [comment]
@michael-heerdegen Thanks for clearifying. That is what I mean.

**Comment by thierryvolpiatto** [comment]
No, here the helm-window popup with the same size for all commands, helm-recentf and others and stay at the same size when I narrow down or up the list.

**Comment by michael-heerdegen** [comment]
I don't see it here, too.  But I vaguely remember that I could reproduce it some days ago when I was trying to understand the issue.  Mmh.

@tomhk215 Is it still reproducible with the newest version?  Does it happen with emacs-helm.sh?  Maybe you have a recipe to reproduce?  Thanks.

**Comment by thierryvolpiatto** [comment]
I have added a new variable `helm-display-buffer-default-size` allowing to set the size of helm-window.
HTH.

**Comment by tomhk215** [comment]
@michael-heerdegen It is not reproducible now.
@thierryvolpiatto Thanks
