### ISSUE TITLE
RFC: override default-process-encoding-system for helm-locate-init for es.exe backend on Windows, Japanese code page 932

### ISSUE THREAD

**Issue by piyo** [emacs-helm/helm#1322]
Hello, thanks for the helm-locate.
I am able to run helm-locate on Windows 7 Pro Japanese with es.exe 1.3.4.686 (Everything.exe command line) and am able to match Japanese filenames if the following is done:

Pattern 1:
- start runemacs.exe -q -Q and note that current-language-environment returns "Japanese", which also means default-process-coding-system is '(japanese-sjis . japanese-sjis)
- manually setup (require 'package)

Pattern 2:
- start runemacs.exe normally with my config that sets current-language-environment to "UTF-8", which also means default-process-coding-system is redefined to '(utf-8 . utf-8)
- package.el is run and done
- PATCH helm-locate-init<f> like this:

```
--- helm-locate.el.orig
+++ #<buffer helm-locate.el.orig>
@@ -252,6 +252,9 @@
           :default default
           :history 'helm-file-name-history)))

+(defvar helm-locate--subprocess-coding-system nil
+  "need to override this on windows")
+
 (defun helm-locate-init ()
   "Initialize async locate process for `helm-source-locate'."
   (let* ((locate-is-es (string-match "\\`es" helm-locate-command))
@@ -279,9 +282,12 @@
     (helm-log "Command line used was:\n\n%s"
               (concat ">>> " (propertize cmd 'face 'font-lock-comment-face) "\n\n"))
     (prog1
-        (start-process-shell-command
-         "locate-process" helm-buffer
-         cmd)
+        (let ((default-process-coding-system default-process-coding-system))
+          (when helm-locate--subprocess-coding-system
+            (setq default-process-coding-system helm-locate--subprocess-coding-system))
+          (start-process-shell-command
+           "locate-process" helm-buffer
+           cmd))
       (set-process-sentinel
        (get-buffer-process helm-buffer)
        (lambda (_process event)
```
- Finally, setq helm-locate--subprocess-coding-system to something like:

```
  (setq helm-locate--subprocess-coding-system
        (progn ;; last one is the winner
          (cons 'shift-jis-dos 'shift-jis-dos)
          (cons 'japanese-cp932-dos 'japanese-cp932-dos) ;; OK
          (cons 'cp932 'cp932)) ;; OK
        ))
```

To be more general, probably this will work. Emacs 24.5 at least has a number of encoding aliases defined generally in mule-conf.el.

```
;; trial test code to be general but I only use Windows 7 JP
(if (boundp 'w32-ansi-code-page)
    (let ((code-page-eol
           (intern (format "cp%s-%s" w32-ansi-code-page "dos")))) ;; Only Windows has the code-page so use dos
      ;; -> cp-932-dos,
      (cons code-page-eol code-page-eol))) ;; prepare the answer for default-process-coding-system
;-->
;(cp932-dos . cp932-dos)
```

Questions:
- Would it be better to just defadvice 'around helm-locate-init instead of this patch?
- The general code-page sniffer needs to be tested on other regional Windows releases. Any way to get help testing this?
- I suspect the code page conversion is active because es.exe is probably compiled for MBCS and does not enforce Unicode encoding conversion that parent Emacs.exe expects. (see the use of GetConsoleCP() in its source.) Is this correct?

I see a tangentially related issue #822, but I don't want to reset default-process-encoding-system to something not utf-8, since it might affect other subprocesses like git.

**Comment by thierryvolpiatto** [comment]
piyo <notifications@github.com> writes:

> Hello, thanks for the helm-locate I am able to run helm-locate on
> Windows 7 Pro Japanese with esexe 134686 (Everythingexe command line)
> and am able to match Japanese filenames if the following is done:
>
> Pattern 1:
>
>   * start runemacsexe -q -Q and note that current-language-environment
>     returns "Japanese", which also means default-process-coding-system
>     is '(japanese-sjis japanese-sjis) * manually setup (require
>     'package)
>
> Pattern 2:
>
>   * start runemacsexe normally with my config that sets
>     current-language-environment to "UTF-8", which also means
>     default-process-coding-system is redefined to ' (utf-8 utf-8)

Did you try toggling input method (C-u C-\)?


-- 
Thierry

**Comment by piyo** [comment]
>> redefined to '(utf-8 utf-8)
> Did you try toggling input method (C-u C-\)?

I gave this a try using Pattern 2, but as expected it does not change default-process-coding-system and running helm-locate this way does not improve.

BTW I use the Google IME which inputs Japanese directly into the minibuffer. I believe MS IME and emacs quail will input and fail in the same way.

To explain in another way, inside the helm-locate minibuffer I insert a japanese phrase like "日本語" or "ローカル", and with Pattern 2 but without the patch, the helm candidate buffer has lines filled with garbage (mojibake). Also I check the *helm-locate* buffer and it is filled with garbage in the same way.

**Comment by thierryvolpiatto** [comment]
Also, did you try playing with `process-coding-system-alist` and `file-coding-system-alist` ?

**Comment by thierryvolpiatto** [comment]
Hi @momomo5717, no clue about this ?

**Comment by momomo5717** [comment]
Hello, @thierryvolpiatto


Sorry, I'm not familiar with Windows and coding systems.
but I have a similar issue on OSX.

I use `default-process-coding-system` of `(utf-8-unix . utf-8-unix)` for grep, git, etc.
and `helm-locate` doesn't work for some Japanese words due to differences of Unicode normalization.


> Also, did you try playing with process-coding-system-alist and file-coding-system-alist ?

It seems `shell-file-name` is used as a program name when `start-process-shell-command` is executed.
So `(add-to-list 'process-coding-system-alist '("locate" . some-value))`
couldn't specify it: 
e.g. `(message "%S" (process-command (get-buffer-process helm-buffer)))` =>
     `("/bin/bash" "-c" "locate -i \\プ\\ロ\\グ\\ラ\\ミ\\ン\\グ ")`


Since `utf-8-hfs` is required on HFS+ file system, the following code works fine.

``` elisp
(let ((process-coding-system-alist `((,shell-file-name . utf-8-hfs))))
  (start-process-shell-command
   "test" "test" (concat "locate -i "
                         (shell-quote-argument "プログラミング")))
  (pop-to-buffer "test"))
```

I think a customization variable @piyo suggested could be useful.
But I'm not sure the following code works on Windows.

``` elisp
(defcustom helm-locate-process-coding-system nil
  "Coding system for `helm-locate'."
  :group 'helm-locate
  :type '(choice (const :tag "Disabled" nil)
                 (cons (symbol :tag "Decoding system")
                       (symbol :tag "Encoding system"))
                 (symbol :tag "Coding system")
                 (function :tag
                           "Return a coding system or a cons of coding systems")))

(defun helm-locate--process-coding-system-alist ()
  (if helm-locate-process-coding-system
      (list (cons (regexp-quote shell-file-name)
                  helm-locate-process-coding-system))
    process-coding-system-alist))

;; around L282
(let ((process-coding-system-alist (helm-locate--process-coding-system-alist)))
  (start-process-shell-command
   "locate-process" helm-buffer
   cmd))
```

Thank you.

**Comment by thierryvolpiatto** [comment]
@momomo5717 Many thanks for your precious comments on this, I am even more unfamiliar with Windows and coding systems :blush:
I will look into this ASAP.
@momomo5717 or @piyo could you provide me two or three filenames, thanks.

**Comment by piyo** [comment]
> Also did you try playing with process-coding-system-alist and file-coding-system-alist ?

I was not familiar with either of these variables, so I tried them out. Using either of these did not resolve my problem.

```emacs-lisp
;; the following does not work:
;; (add-to-list 'process-coding-system-alist
;;              ;; NG '("[eE][sS]" cp932 . cp932)
;;              ;; NG '("[eE][sS][.][eE][xX][eE]" cp932 . cp932)
;;              ;; NG '("[eE][sS].[eE][xX][eE]" shift-jis-dos . shift-jis-dos)
;;              ;; NG '("locate-process" cp932 . cp932)
;;              ;; verified that the process name is "es"
;;              '("[eE][sS]" cp932-dos . cp932-dos))
;;
;; (pop process-coding-system-alist)
;;
;; (advice-add 'find-operation-coding-system :filter-return #'debug-111)
;; (defun debug-111 (origfun-rv &rest args)
;;   (message "debug-111 #%s# |%s|" origfun-rv args))
;;; for removal: (advice-remove 'find-operation-coding-system #'debug-111)
```

I was successful with the shell-file-name<v> workaround that @momomo5717 suggested, but only with "cp932" and "japanese-cp932-dos". The other two "japanese-sjis-dos" and "utf-8" leads to failure.

```emacs-lisp
;; prereq: a file with the target name was created and could be found using everything.exe and es.exe.
(progn
  (with-current-buffer "test"
    (dolist (enc1 '(cp932 japanese-cp932-dos japanese-sjis-dos utf-8-dos))
      (let ((process-coding-system-alist (list (cons shell-file-name enc1))))
        (goto-char (point-max))
        (insert (format ">>> testing %s\n" enc1))
        (start-process-shell-command
         "test" "test" (concat "es -i "
                               (shell-quote-argument "日本語"))))))
  (pop-to-buffer (current-buffer)))
```

> But I'm not sure the following code works on Windows.

The code suggested does not set helm-locate-process-coding-system to a usable value, so in that sense I would need to add (setq helm-locate-process-coding-system 'cp932) for it to work. Also it would be nice if the suggestion had a suggested default, like my example code with w32-ansi-code-page<v>. The assumption here is that my "locate" subprocess which is "es" will give all results in the non-utf-8 code page.

> and helm-locate doesn't work for some Japanese words due to differences of Unicode normalization

I am unfamiliar with this issue. Which two methods of normalization are your referring to? via "locate" and via ... OSX Finder?

> hfs

I do not use OSX, just to be clear.

> Japanese filenames

The examples "プログラミング" and "日本語" should be a start. Also a filename that has normalization issues should be tested. Also this should be tested on different localizations of Windows.

BTW, this is my temporary workaround:
```emacs-lisp
(use-package helm-locate
  :if (boundp 'w32-ansi-code-page)
  :config
  (advice-add 'helm-locate-init :around 'piyo-helm-locate-fix-encoding))
;;for removal (advice-remove 'helm-locate-init 'piyo-helm-locate-fix-encoding)

(defun piyo-helm-locate-fix-encoding (orig-fun &rest args)
  (let ((default-process-coding-system default-process-coding-system)
        code-page-eol)
    (when (boundp 'w32-ansi-code-page)
      (setq code-page-eol (intern (format "cp%s-%s" w32-ansi-code-page "dos")))
      (setq default-process-coding-system (cons code-page-eol code-page-eol)))
    (apply orig-fun args)))
```

Also for completeness my shell-file-name is "sh" because Cygwin is in my PATH for runemacs.exe, and not "cmdproxy.exe" which is the default in a Windows build.

**Comment by thierryvolpiatto** [comment]
piyo <notifications@github.com> writes:

> The examples "プログラミング" and "日本語" should be a start. Also a
> filename that has normalization issues should be tested. Also this
> should be tested on different localizations of Windows.

Thanks.

> BTW, this is my temporary workaround:
>
> (use-package helm-locate
>   :if (boundp 'w32-ansi-code-page)
>   :config
>   (advice-add 'helm-locate-init :around 'piyo-helm-locate-fix-encoding))
> ;;for removal (advice-remove 'helm-locate-init 'piyo-helm-locate-fix-encoding)
>
> (defun piyo-helm-locate-fix-encoding (orig-fun &rest args)
>   (let ((default-process-coding-system default-process-coding-system)
>         code-page-eol)
>     (when (boundp 'w32-ansi-code-page)
>       (setq code-page-eol (intern (format "cp%s-%s" w32-ansi-code-page "dos")))
>       (setq default-process-coding-system (cons code-page-eol code-page-eol)))
>     (apply orig-fun args)))

That's look as a good starting point, could you make a PR ?

> Also for completeness my shell-file-name is "sh" because Cygwin is in
> my PATH for runemacs.exe, and not "cmdproxy.exe" which is the default
> in a Windows build.

Be aware that everything/es expects a runemacs.exe shell, not a sh
shell, we add repeated crashes of emacs with this issue some years ago.

Thanks.

-- 
Thierry

**Comment by momomo5717** [comment]
@thierryvolpiatto Thank you for the message. I hope it could be of some help.

Hello, @piyo

Thank you for posting this issue and the feedback!

>I am unfamiliar with this issue. Which two methods of normalization are your referring to? via "locate" and via ... OSX Finder?

Here is the link for an readable explanation of the normalization issue: 
http://www.sakito.com/2010/05/mac-os-x-normalization.html (written in Japanese)

e.g. character "プ"

NFD ( Apple's modified version )
"\343\203\225"             = "フ"
"\343\203\225\343\202\232" = "フ" + upper right small circle => displayed as "プ"

NFC
"\343\203\227" = "プ"

In Emacs ( emacs-mac-app installed by MacPorts )
```elisp
;; Encoding
(encode-coding-string "プ" 'utf-8-hfs)  ;; => "\343\203\225\343\202\232"
(encode-coding-string "プ" 'utf-8-unix) ;; => "\343\203\227"

;; Decoding
(equal ;; => t
 (decode-coding-string "\343\203\225\343\202\232" 'utf-8-hfs)
 (decode-coding-string "\343\203\227"             'utf-8-unix))

(equal ;; => nil
 (decode-coding-string "\343\203\225\343\202\232" 'utf-8-unix)
 (decode-coding-string "\343\203\227"             'utf-8-unix))

(equal ;; => t
 (decode-coding-string "\343\203\225\343\202\232" 'utf-8-hfs)
 (decode-coding-string "\343\203\227"             'utf-8-hfs))
```
                      
>I do not use OSX, just to be clear. I assume that even if OSX supports HFS and other file systems, the "locate" command coerces the encoding to utf-8-hfs?

It seems the encoding would be needed for searching files which include particular characters on HFS.
e.g. on command line
`locate プログラミング` returned nothing.
`echo プログラミング | iconv -t UTF-8-MAC | xargs locate` returned matched files.

>BTW, this is my temporary workaround, which should be general enough for other localizations of Windows. Tested on Windows XP and 7.

Thank you for your workaround and testing it on two OS!

>The code suggested does not set helm-locate-process-coding-system to a usable value,

I tried writing the following code from your workaround.
I would be grateful if you could try and modify it.
It is just an idea, so feel free to ignore it.

``` elisp
;; simple version
(defcustom helm-locate-default-process-coding-system
  (when (boundp 'w32-ansi-code-page)
    (let ((code-page-eol
           (intern (format "cp%s-%s" w32-ansi-code-page "dos"))))
      (when (ignore-errors (check-coding-system code-page-eol))
        (cons code-page-eol code-page-eol))))
  "Cons of coding systems."
  :group 'helm-locate
  :type '(choice (const :tag "Disabled" nil)
                 (cons (symbol :tag "Decoding system")
                       (symbol :tag "Encoding system"))))

;; more safely version
(defcustom helm-locate-default-process-coding-system nil
  "Cons of coding systems."
  :group 'helm-locate
  :type '(choice (const :tag "Disabled" nil)
                 (cons (symbol :tag "Decoding system")
                       (symbol :tag "Encoding system")))
  :set
  (lambda (s v)
    (when (or (null v) 
              (and (consp v)
                   (ignore-errors (check-coding-system (car v)))
                   (ignore-errors (check-coding-system (cdr v)))))
      (if (boundp s) (set s v)
        (set s (if (and (not (get s 'saved-value))
                        (null v) (boundp 'w32-ansi-code-page))
                   (let ((code-page-eol
                          (intern (format "cp%s-%s" w32-ansi-code-page "dos"))))
                     (when (ignore-errors (check-coding-system code-page-eol))
                      (cons code-page-eol code-page-eol)))
                 v))))
    (unless (boundp s) (set s nil))))


;; in let* form at `helm-locate-init'
(default-process-coding-system (or helm-locate-default-process-coding-system
                                   default-process-coding-system))
```

Thank you.
