### ISSUE TITLE
`C-c >` helm-toggle-truncate-line seems to no longer work

### ISSUE THREAD

**Issue by dakrone** [emacs-helm/helm#1323]
I used to use `C-c >` all the time for toggling truncation on and off in helm buffers, but it looks like recently it broke and no longer toggles between the truncated/non-truncated state.

**Comment by thierryvolpiatto** [comment]
Lee Hinman <notifications@github.com> writes:

> I used to use C-c > all the time for toggling truncation on and off in
> helm buffers, but it looks like recently it broke and no longer
> toggles between the truncated/ non-truncated state.

It is working here, in which source specifically is it not working ?

-- 
Thierry

**Comment by dakrone** [comment]
@thierryvolpiatto in the `helm-ag` project, which I am not sure whether that's something I should open here or with the helm-ag project, should I open it there?

**Comment by thierryvolpiatto** [comment]
Lee Hinman <notifications@github.com> writes:

> @thierryvolpiatto in the helm-ag project, which I am not sure whether
> that's something I should open here or with the helm-ag project,
> should I open it there?

No helm-ag bugs should be reported there, BTW helm support ag natively
and you don't need helm-ag.



-- 
Thierry

**Comment by thierryvolpiatto** [comment]
See `helm-do-grep-ag`
