### ISSUE TITLE
`C-l` in `helm-find-files` does not work on Windows for tramp paths

### ISSUE THREAD

**Issue by jeberger** [emacs-helm/helm#1325]
I have an issue when I hit `C-l` in `helm-find-files` on _remote_ folders.

## To reproduce:

- open a remote tramp file,
- start `helm-find-files` → the search starts in the remote folder (e.g. `/ssh:login@host:/foo/bar/baz/`),
- hit `C-l`.

## Expected result:

The last part of the path is removed (e.g. `/ssh:login@host:/foo/bar/`)

## Actual result:

- The first time, the path is shortened _and looses its original `/`_ (e.g. `ssh:login@host:/foo/bar/`).
- If I hit `C-l` again, the shortened path is appended to the current path (e.g. `ssh:login@host:/foo/bar/ssh:login@host:/foo/`)

## Extra information:

- This works fine with local folders, e.g. `d:/foo/bar/baz/` becomes `d:/foo/bar/`, then `d:/foo/`.
- This might be related to #1308.
- Emacs version 24.5.1 on Windows 7.
- Helm version 20160106.844 installed from ELPA.
- It works fine with the same emacs and helm versions on Linux.

**Comment by thierryvolpiatto** [comment]
Please let me know if it is now working (I have not ssh installed on my Windows virtualbox).

**Comment by jeberger** [comment]
It works with version 20160107.1755. Thanks for the quick reaction!
