### ISSUE TITLE
helm-find-files-action-transformer and dired

### ISSUE THREAD

**Issue by michael-heerdegen** [emacs-helm/helm#1327]
Hi,

when I'm in dired and call helm-find-files, in `helm-find-files-action-transformer`, this branch sometimes matches:

```
((save-match-data
             (and ffap-url-regexp
                  (not (string-match-p ffap-url-regexp str-at-point))
                  (string-match ":\\([0-9]+:?\\)" str-at-point)
                  ))
           (append '(("Find file to line number" . helm-ff-goto-linum))
                   actions))
```

(the time column, probably).

The problem is that the body pushes the a action to the front of the actions (I guess that's intended?).  That gets in the way in that case, because all default actions get a different number - I never know which key executes which action ...

What can we do about this?

Regards, Michael.

**Comment by michael-heerdegen** [comment]
Ok, so you want it to be the first action.

May I ask in which situations you use this?  Maybe we could use a whitelist instead of a blacklist, like ```(derived-mode-p 'text-mode)```.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Ok, so you want it to be the first action.

In certain circumstances yes see below.

> May I ask in which situations you use this?

If you have a valid file at point like foo:123, helm will use as default
action "find file at line number", as you point out, it was popping up
this action as well in dired buffers which was wrong indeed.

Isn't it working as expected now?

> Maybe we could use a whitelist instead of a blacklist, like
> (derived-mode-p 'text-mode).

You lost me here, which blacklist ?

-- 
Thierry

**Comment by michael-heerdegen** [comment]
Yes, it's fixed.  But I mean the problem could also appear in other situations.

Instead of excluding (in our case: dired), maybe limit the behavior to cases where it makes sense (e.g. ```(derived-mode-p 'text-mode)```).

Where do those "foo:123" things "come from"?

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Yes, it's fixed. But I mean the problem could also appear in other situations.

Will see then if someone complain about this in other situation.

> Instead of excluding (in our case: dired), maybe limit the behavior to
> cases where it makes sense (e.g. (derived-mode-p 'text-mode)).

No this feature can be useful in any place i.e adding a comment
somewhere referencing to a file at numline.

> Where do those "foo:123" things "come from"?

This feature have been requested by people often reading/debugging
system/server log files etc...

-- 
Thierry

**Comment by michael-heerdegen** [comment]
Ok, great, then let's keep this, thanks.
