### ISSUE TITLE
Split up the Helm wiki

### ISSUE THREAD

**Issue by xiongtx** [emacs-helm/helm#1328]
I took a look at the wiki for the project, and I think it's too much to put all content on a single page. It's difficult to tell at a glance what functionality is available, especially since the sections are not organized in any logical manner that I can discern.

Other major (and arguably smaller) packages like [smartparens](https://github.com/Fuco1/smartparens/wiki) have wikis that are split into pages by topic. This seems like a better way to go for a complex package like Helm.

Helm is particularly well-suited for such a set-up because the functional areas are largely independent of each other, united by their use of the basic Helm framework. A page on `helm-info`, for example, could be written and understood largely independent of one on `helm-find-files`.

I'll create a page on Info-related functionality if we agree this is the way to go.

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> Other major (and arguably smaller) packages like Smartparens have
> wikis that are split into pages by topic This seems like a better way
> to go for a complex package like Helm

Agreed, but I never found the time to improve Helm wiki, all my sparse
time is used to fix bugs and write code for helm.

-- 
Thierry

**Comment by xiongtx** [comment]
I have created a [page for Info-related functionality](https://github.com/emacs-helm/helm/wiki/Info-files).

I created the page using Org-mode syntax, since that's one of the options GitHub supports. Given that Helm is an Emacs-specific project, I think this should be reasonable.

**Comment by xiongtx** [comment]
@tuhdo has written a [very extensive tutorial](http://tuhdo.github.io/helm-intro.html) about using Helm. I wonder if it would be a good idea to integrate it into the Wiki, or at least link to it somewhere.

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> I have created a page for Info-related functionality.

Great, many thanks for this.
Oh! And I see there is also other pages, great, thanks.


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> @tuhdo has written a very extensive tutorial about using Helm. I
> wonder if it would be a good idea to integrate it into the Wiki, or at
> least link to it somewhere.

I don't know if he would be ok for this, I am not against anyway, would
be great.

-- 
Thierry

**Comment by xiongtx** [comment]
I haven't removed the content from the main Wiki. If we agree that the new pages are satisfactory we should remove the old content as well. No need to scare away new users with a giant Wiki front page :grin:.

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> I haven't removed the content from the main Wiki. If we agree that the
> new pages are satisfactory we should remove the old content as
> well. No need to scare away new users with a giant Wiki front page
> :gr.

Agreed.

-- 
Thierry
