### ISSUE TITLE
About the wiki

### ISSUE THREAD

**Issue by tuhdo** [emacs-helm/helm#1329]
Since issue 1328 was deleted for some reason, I create this thread to reply and continue the discussion.

> I don't know if he would be ok for this, I am not against anyway, would be great.

Yes, it would be fine if you want to use my guide as an introduction to Helm basics for new users. After all, that's the purpose of the guide. Since Helm updated some new features, I will update the guide soon.

**Comment by thierryvolpiatto** [comment]
@tuhdo Great thanks.

BTW What happened with 1328 ?

**Comment by tuhdo** [comment]
@xiongtx it's fine to me if you want to incorporate the content into the Wiki. I still keep the guide just in case someone search on the internet for Helm guides, so they can either find and use the wiki or my guide.

@thierryvolpiatto now #1328 is accessible again. At the time I clicked it, it did not exist for some reason.

**Comment by michael-heerdegen** [comment]
@tuhdo I guess github had some problems, I discovered inaccessible issues some days back in other packages, too.

**Comment by thierryvolpiatto** [comment]
@tuhdo Thanks, I have no idea though what to add to wiki.
@xiongtx I saw you made many pages, many thanks for your work.

**Comment by thierryvolpiatto** [comment]
I don't know what to do here, closing now, feel free to reopen if needed.
