### ISSUE TITLE
helm-get-info-files() complaining about missing /usr/local/share/info

### ISSUE THREAD

**Issue by dinojr** [emacs-helm/helm#1330]
As of this morning and upgrade to the 20160109.942 version of helm, helm-eshell and helm-files won't load because I don't have a /usr/local/share/info dir on my system.

(file-error "Opening directory" "Aucun fichier ou dossier de ce type" "/usr/local/share/info")
  directory-files("/usr/local/share/info/" nil "\\.info")
  helm-get-info-files()

**Comment by dinojr** [comment]
Turns out this dir was added to Info-directory-list in some forgotten part of my configuration. helm didn't use to complain about it not existing before though. I don't think its absence should prevent helm from being loaded.

**Comment by thierryvolpiatto** [comment]
Julien Cubizolles <notifications@github.com> writes:

> I don't think its absence should prevent helm from being loaded.

Absolutely, should be fixed now, thanks.

-- 
Thierry

**Comment by dinojr** [comment]
Thank you.
