### ISSUE TITLE
helm should support tooltip buffer.

### ISSUE THREAD

**Issue by gfZeng** [emacs-helm/helm#1332]
If helm support tooltip buffer, some auto complete package can use helm perfectly.
eg.
[helm-company](https://github.com/yasuyk/helm-company)

**Comment by thierryvolpiatto** [comment]
Please develop.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
No it is not the purpose of helm, you have several packages handling this, namely company and auto-complete.

**Comment by gfZeng** [comment]
Yeah, but company and auto-complete have not fuzzy match. and the helm do this perfectly.

**Comment by thierryvolpiatto** [comment]
Isaac Zeng <notifications@github.com> writes:

> Yeah, but company and auto-complete have not fuzzy match.

But they are (like helm) framework and they allow to create kind of
source IIRC, so one can create easily code to use with one of those
backends.
No need for helm to reinvent the whell, auto-complete and company are
here for this kind of completion.

-- 
Thierry

**Comment by gfZeng** [comment]
Ok. It just if helm support tooltip frontend. company can use it directly.
thanks you @thierryvolpiatto
