### ISSUE TITLE
Improve completion-at-point Helm interface

### ISSUE THREAD

**Issue by michael-heerdegen** [emacs-helm/helm#1339]
Hi,

this is an official issue for continuing the discussion of the improvement of the completion-at-point Helm interface we started in #1308.

See the "better-completion-in-region" branch for my approach.

@thierryvolpiatto Dunno whether my change obsoleted some more parts of `helm--completion-in-region`, I'm still trying out the concept.  But if you think of  a case where my change breaks something due to the concept, please validate and let me know.  Doesn't hurry.  Thanks.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Hi,
>
> this is an official issue for continuing the discussion of the
> improvement of the completion-at-point Helm interface we started in
> #1308
>
> See the "better-completion-in-region" branch for my approach
>
> @thierryvolpiatto Dunno whether my change obsoleted some more parts of
> helm--completion-in-region, I'm still trying out the concept But if
> you think of a case where my change breaks something due to the
> concept, please validate and let me know Doesn't hurry Thanks

Please do not use emacs-25 only functions, i.e instead of if-let use
helm-aif.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Hi,
>
> this is an official issue for continuing the discussion of the improvement of the completion-at-point Helm interface we started in #1308
>
> See the "better-completion-in-region" branch for my approach
>
> @thierryvolpiatto Dunno whether my change obsoleted some more parts of
> helm--completion-in-region, I'm still trying out the concept But if
> you think of a case where my change breaks something due to the
> concept, please validate and let me know Doesn't hurry Thanks

Otherwise, it seems completion-at-point is working fine, shell and
multiple completion also.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
I have modified the `if-let` by `helm-aif` in 04d6773fdb6ab0bfb455f2baaa145514e7e2ce58

**Comment by thierryvolpiatto** [comment]
Feel free to merge once finished.

**Comment by michael-heerdegen** [comment]
Great, will do then.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Great, will do then.

I have commited another change to the better-completion branch, using 
`completion-metadata-get` to decide if we are in file completion.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
I have resolved conflicts with master, merged, and created #1357 PR.
You can now pull new changes in branch and just continue commiting on it, when finished, just merge the PR.

**Comment by michael-heerdegen** [comment]
Thanks.

FWIW, another thing we could do would be to recompute the candidate list dynamically from new input, instead of matching against a constant candidate list.

In particular, this would make it possible to change the initially completed prefix in the minibuffer. We would have to answer the question what the semantics of the search should be.

In my own Helm completion function, i use the following semantics:

The first pattern is delivered to vanilla completion and defines a set of (initial) candidates.  The other patterns (if there are any) are used to narrow down these candidates.  If the first char of the input is a space character, the empty string is used as first pattern (i.e. ask for all possible candidates and narrow them with the following patterns using Helm).

This would be backwards compatible, I think, because we would produce the same results in all cases that make currently sense.  It would complicate the thing OTOH.

WDYT?

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Thanks.
>
> FWIW, another thing we could do would be to recompute the candidate list dynamically from new input, instead of matching against a constant candidate list.
>
> In particular, this would make it possible to change the initially completed prefix in the minibuffer. We would have to answer the question what the semantics of the
> search should be.
>
> In my own Helm completion function, i use the following semantics:
>
> The first pattern is delivered to vanilla completion and defines a set of (initial) candidates. The other patterns (if there are any) are used to narrow down these
> candidates. If the first char of the input is a space character, the empty string is used as first pattern (i.e. ask for all possible candidates and narrow them with
> the following patterns using Helm).
>
> This would be backwards compatible, I think, because we would produce the same results in all cases that make currently sense. It would complicate the thing OTOH.
>
> WDYT?

I want to keep something simple.

I am not sure to understand what you want here, do you want to cycle in
first candidates and then popup in helm for the others ? (like
helm-dabbrev ?)

-- 
Thierry

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> I am not sure to understand what you want here, do you want to cycle
> in first candidates and then popup in helm for the others ? (like
> helm-dabbrev ?)

No, I don't want to cycle.

I mean this: Suppose you are here:

foobar-!

at the "!" and call compl-at-point.  Then you notice made had a typo and
wanted "foo-bar-" (or maybe something completely different).

With the current implementation, you have to abort, change the prefix in
the original buffer, go back to the old position and complete again.
Annoying.

With my proposal, you would be able to edit the prefix in the
minibuffer, and the candidates would be refreshed automatically to
reflect the new prefix.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Thierry Volpiatto <notifications@github.com> writes:
>
>> I am not sure to understand what you want here, do you want to cycle
>> in first candidates and then popup in helm for the others ? (like
>> helm-dabbrev ?)
>
> No, I don't want to cycle.
>
> I mean this: Suppose you are here:
>
> foobar-!
>
> at the "!" and call compl-at-point. Then you notice made had a typo and
> wanted "foo-bar-" (or maybe something completely different).
>
> With the current implementation, you have to abort, change the prefix in
> the original buffer, go back to the old position and complete again.
> Annoying.
>
> With my proposal, you would be able to edit the prefix in the
> minibuffer, and the candidates would be refreshed automatically to
> reflect the new prefix.

Thanks to explain.

This will not be anymore completion, I prefer staying strict on this,
i.e keeping the current behavior.

-- 
Thierry
