### ISSUE TITLE
Fallback to vertical window splitting when horizontal splitting fails (and vice versa)

### ISSUE THREAD

**Issue by tmalsburg** [emacs-helm/helm#1341]
I configured Helm to split the window horizontally (`(setq helm-split-window-default-side 'right)`).  However, in same situations this fails because there is not enough space to split horizontally (e.g., when using writeroom-mode, joostkremers/writeroom-mode#26).  Would it make sense to fall back to splitting vertically in these cases (and vice versa)?  If splitting vertically fails too, we could further fall back to using the full frame. I think splitting the window in a different way than what is preferred by the user is better than failing altogether.

**Comment by thierryvolpiatto** [comment]
Titus von der Malsburg <notifications@github.com> writes:

> I configured Helm to split the window horizontally ((setq
> helm-split-window-default-side 'right)). However, in same situations
> this fails because there is not enough space to split horizontally
> (e.g., when using writeroom-mode,
> joostkremers/writeroom-mode#26). Would it make sense to fall back to
> splitting vertically in these cases (and vice versa)? If splitting
> vertically fails too, we could further fall back to using the full
> frame. I think splitting the window in a different way than what is
> preferred by the user is better than failing altogether.

Perhaps fallback to emacs default behavior with:

```
(setq helm-split-window-preferred-function 'split-window-sensibly)
```

Ensure `split-width-threshold` is non nil which see.

-- 
Thierry

**Comment by joostkremers** [comment]
Some change in the current dev version of Emacs seems to have caused this problem, I got a similar report here: <https://github.com/joostkremers/visual-fill-column/issues/13>. I'll see if I can figure out what exactly and report it on emacs-devel.

**Comment by tmalsburg** [comment]
Thank you @thierryvolpiatto.  Using `split-window-sensibly` solved my problem. I suppose we can close this issue.

**Comment by akater** [comment]
Why doesn't `helm-split-window-preferred-function` default to `split-window-sensibly`, the default Emacs splitter, in the first place?  I have some issues with window splitting which could be resolved by this setting but I hesitate because presumably `helm-split-window-preferred-function` should also do some helm-specific stuff that `split-window-sensibly` doesn't do.  Depending on reasons, it might be worth it to add some clarification to the docstring of `helm-split-window-preferred-function`.

**Comment by thierryvolpiatto** [comment]
akater ***@***.***> writes:

> Why doesn't helm-split-window-preferred-function default to
> split-window-sensibly, the default Emacs splitter, in the first place?
> I have some issues with window splitting which could be resolved by
> this setting

Can you explain what are those issues?

Thanks.

-- 
Thierry

**Comment by akater** [comment]
On my phone in its landscape orientation, Emacs frame is 125x13.  I mostly use it in the landscape orientation but occasionally it's in portrait, and then the frame is 62x48.  A single window in the frame should be split horizontally in the former case and vertically in the latter.  The default splitter `split-window-sensibly` works fine if only I set `split-width-threshold` to 125, and make no other splitting-related customizations.

Helm's default splitter `helm-split-window-default-fn` works mostly fine then but when splitting a single 125x13 window in a frame, it calls `split-window-sensibly` with `split-width-threshold` bound to nil, and so my only splitting customization gets ignored, and the window is split vertically; thus Helm for some reason does not inherit standard behaviour in this case.

**Comment by thierryvolpiatto** [comment]
akater ***@***.***> writes:

> The default splitter split-window-sensibly works fine if only I set
> split-width-threshold to 125, and make no other splitting-related
> customizations.

You can now use `helm-split-width-threshold` to set
`split-width-threshold` for helm windows and use inconditionally
`split-window-sensibly`.

Hope that helps.

-- 
Thierry
