### ISSUE TITLE
bind a key to open helm-ff-file-name-history directly?

### ISSUE THREAD

**Issue by zeltak** [emacs-helm/helm#1342]
Hi!

i was wondering if anyone knows (and if at all possible) to bind a key to open helm-ff-file-name-history directly. when i try to issue this through  M-x get an error saying 
```
helm-read-pattern-maybe: Command attempted to use minibuffer while in minibuffer
````

thx!

z

**Comment by thierryvolpiatto** [comment]
zeltak <notifications@github.com> writes:

> Hi!
>
> i was wondering if anyone knows (and if at all possible) to bind a key
> to open helm-ff-file-name-history directly. when i try to issue this
> through M-x get an error saying
>
> helm-read-pattern-maybe: Command attempted to use minibuffer while in
> minibuffer

Perfectly fine you have this error, this command is not meant to be used
directly but only within a helm-find-files context.
If you were using helm-M-x you would not see it at all.

So please use this only from helm-find-files with C-c h.

Thanks.

-- 
Thierry
