### ISSUE TITLE
Helm not active on C-x C-f

### ISSUE THREAD

**Issue by To1ne** [emacs-helm/helm#1346]
When I press C-x C-f the emacs built-in `find-files` is called. But when I press C-x C-v, the helm buffer is activated.
I am using a basic configuration:
```elisp
      (helm-mode 1)
      (setq helm-candidate-number-limit           100
            helm-idle-delay                       0.0
            helm-input-idle-delay                 0.01
            helm-quick-update                     t
            helm-ff-skip-boring-files             t
            helm-ff-file-name-history-use-recentf t
            helm-M-x-fuzzy-match                  t)
      (bind-keys :map helm-map
                 ("<tab>" . helm-execute-persistent-action)
                 ("C-i"   . helm-execute-persistent-action)
                 ("C-z"   . helm-select-action)))
```

**Comment by thierryvolpiatto** [comment]
Toon Claes <notifications@github.com> writes:

> When I press C-x C-f the emacs built-in find-files is called. But when
> I press C-x C-v, the helm buffer is activated.

See `helm-completing-read-handlers-alist` and configure as needed.

I strongly advice users binding C-x C-f to helm-find-files instead of using
the basic find-file helmization, this is why find-file have been disabled.

-- 
Thierry

**Comment by To1ne** [comment]
OK, thank you for the quick reply. I was searching through the releases hoping to find information about it, but I did not find it.
