### ISSUE TITLE
please, please: cursor in helm help pages needed!

### ISSUE THREAD

**Issue by qmapper** [emacs-helm/helm#1347]
Hallo Helm Team.

I'm visually impaired person.
I advised some functions in emacs like forward/backward: word/sentence/line to let emacs send  them to synthetizer for me.

Unfortunately my simple modifications do not work with helm help context pages, because cursor is not there.

Could YOu please provide some toggle to turn the cursor on so that I could benefit from that very valuable information?

best regards

**Comment by thierryvolpiatto** [comment]
qmapper <notifications@github.com> writes:

> Hallo Helm Team
>
> I'm visually impaired person
> I advised some functions in emacs like forward/backward: word/sentence/line to let emacs send them to synthetizer for me
>
> Unfortunately my simple modifications do not work with helm help context pages, because cursor is not there
>
> Could YOu please provide some toggle to turn the cursor on so that I
> could benefit from that very valuable information?

Yes I can, however note that only scroll commands will be available
there, no C-a C-e etc...

If that help, you have also the command helm-documentation (C-x c h h)
which will provide a simple org buffer (outside of helm session).

-- 
Thierry

**Comment by qmapper** [comment]
how about M-a M-e (forward/backward sentence) ?

**Comment by thierryvolpiatto** [comment]
qmapper <notifications@github.com> writes:

> how about M-a M-e (forward/backward sentence) ?

In addition I have added common keybindings C-a, C-e, C-n etc...
HTH.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
BTW Let me know if you need more commands there.

-- 
Thierry

**Comment by qmapper** [comment]
Hallo Thierry.

Thank You for Your change. I can see the cursor and can move cursor across lines and sentences. The only thing I'm missing about movement is moving across words.

The bigger problem is that neither sentences nor lines are not read.

I think I know what is the reason.
Literally I'm advising these functions:

forward-sentence
backward-sentence
backward-word
forward-word
next-line
previous-line

My advice checks if the functions above ahve been called interactivelly. If yes, then the text is passed to synthetizer. It is so because function above are called in cyclic way, that's why the condition.

Do You think YOu could help me with that?

best regards

**Comment by thierryvolpiatto** [comment]
qmapper <notifications@github.com> writes:

> Hallo Thierry.
>
> Thank You for Your change. I can see the cursor and can move cursor
> across lines and sentences. The only thing I'm missing about movement
> is moving across words.

If you mean forward-word and backward-word, it will be easy to add.
>
> The bigger problem is that neither sentences nor lines are not read.
>
> I think I know what is the reason.
> Literally I'm advising these functions:
>
> forward-sentence
> backward-sentence
> backward-word
> forward-word
> next-line
> previous-line
>
> My advice checks if the functions above ahve been called
> interactivelly. If yes, then the text is passed to synthetizer. It is
> so because function above are called in cyclic way, that's why the
> condition.
>
> Do You think YOu could help me with that?

What about calling these functions interactively ?
Would be good for you ?

-- 
Thierry

**Comment by qmapper** [comment]
If You mean the following example, then Yes, it will be very good!:
(call-interactively 'next-line)

**Comment by thierryvolpiatto** [comment]
qmapper <notifications@github.com> writes:

> If You mean the following example, then Yes, it will be very good!:
> (call-interactively 'next-line)

Yes it's what I meant, will do this tomorrow, thanks.

-- 
Thierry

**Comment by qmapper** [comment]
Thank You very much.

**Comment by thierryvolpiatto** [comment]
Glad it works and you can use helm like this :smile:
