### ISSUE TITLE
Buffer's name in helm-imenu-in-all-buffers

### ISSUE THREAD

**Issue by user471** [emacs-helm/helm#1348]
`helm-imenu-in-all-buffers` should show a buffer's name. It's just an useful information, especially when you have candidates with the same name.

**Comment by thierryvolpiatto** [comment]
user471 <notifications@github.com> writes:

> helm-imenu-in-all-buffers should show buffer's name It's just useful
> information, especially when you have candidates with the same name

See #1072.

-- 
Thierry

**Comment by user471** [comment]
@thierryvolpiatto I don't undestand. There is a function that create imenu candidates for buffer
```
(defun helm-imenu-candidates (&optional buffer)
  (with-current-buffer (or buffer helm-current-buffer)
    (let ((tick (buffer-modified-tick)))
      (if (eq helm-cached-imenu-tick tick)
          helm-cached-imenu-candidates
        (setq imenu--index-alist nil)
        (prog1 (setq helm-cached-imenu-candidates
                     (let ((index (imenu--make-index-alist t))) 
                       (helm-imenu--candidates-1
                        (delete (assoc "*Rescan*" index) index))))
          (setq helm-cached-imenu-tick tick))))))
```
Why is it not possible to get buffer name and put it in every candidate and then use this name when candidate is showing?

**Comment by thierryvolpiatto** [comment]
user471 <notifications@github.com> writes:

> @thierryvolpiatto I don't undestand. There is a function that create
> imenu candidates for buffer

I know, I wrote it.

> Why is it not possible to get buffer name and put it in every
> candidate and then use this name when candidate is showing?

buffer-name is already stored there.

What is the problem with the code proposed in other issue #1072?

-- 
Thierry

**Comment by user471** [comment]
>What is the problem with the code proposed in other issue

The main problem is you need to focus candidate to view the buffer.

**Comment by thierryvolpiatto** [comment]
user471 <notifications@github.com> writes:

>     What is the problem with the code proposed in other issue
>    
> The main problem is you need to focus candidate to view the buffer.

Sorry but it looks good enough for me, and also is usable where needed
and is not specific to imenu.

Also displaying buffers would be slower, it is why I didn't choose to
provide this.

-- 
Thierry

**Comment by user471** [comment]
>Also displaying buffers would be slower, it is why I didn't choose to provide this.

Could you add an option to enable it. Or could you add some sort of hook, so anyone could be able to display any additional information they want for every item in helm. Something like this

```
(setq 'helm-diplay-imenu-additional-information (lambda (candidate) (get-buffer-name candidate)))
```

**Comment by thierryvolpiatto** [comment]
user471 <notifications@github.com> writes:

> Could you add an option to enable it.

Option or not, that's mean I will have to implement this, and it is a
lot of work I haven't decided to do yet.

-- 
Thierry
