### ISSUE TITLE
wish: helm-org-agenda-files-headings should indicate respective org-agenda file for each headline (don't know how to reopen #902)

### ISSUE THREAD

**Issue by GregorZattler** [emacs-helm/helm#1352]
Dear helm developers, this is a duplicate of #902 because I do not know how to reopen an issue.  

My original wish was:
> "There might be serveral or even many org-agenda files with same headlines (e.g. one org-agenda file 
> per project, every projekt with a headline "* Goal" or "* Budged" or whatever). All these identical 
> headlines are shown by helm-org-agenda-files-headings without any indication to which org-agenda 
> file they belong. It would be helpful to have the headings prefixed with the file name:
> projecta: * Budged
> projecta: * Goal
> projecta: * Partners
> project-b: * Budged
> project-b: * Goal
> project-b: * Issues
> ...
> This is how headings are presented in the agenda itself. For me it would be not important if the list 
> was sorted by the headings or by the file names first."

#902 was rightly closed a fixed but since Xmas 2015 the file names are gone again.

With helm sources as of 2016-01-15 I did a git bisect and this is the result:
db86d98 is the first bad commit
commit db86d98
Author: Thierry Volpiatto thierry.volpiatto@gmail.com
Date: Thu Dec 24 08:26:00 2015 +0100

Make more configurable helm org display.

    helm-org.el (helm-org-format-outline-path): New user var. (helm-org-headings--nofilename): Removed. (helm-org-show-filename): New user var. (helm-org--get-candidates-in-file): Ensure window-with is called on helm-window (#1294). Use new user vars.

:100644 100644 41a59406a20e8764e7d482d099f8321d78105076 6bbf80728fbfd63f0c2530eba02eb688b334a9aa M helm-org.el
0 ((db86d98...)|BISECTING)

Is it possible to re-enable/enhance helm to show file names in helm org headings ?

Thanks for looking into this, Gregor

**Comment by thierryvolpiatto** [comment]
GregorZattler <notifications@github.com> writes:

> Is it possible to re-enable/enhance helm to show file names in helm org headings ?

I answered you and never had response, so I closed.
Filenames are always here, just `(setq helm-org-show-filename t)`.

-- 
Thierry

**Comment by GregorZattler** [comment]
Hi Thierry,
* Thierry Volpiatto <notifications@github.com> [22. Jan. 2016]:
> GregorZattler <notifications@github.com> writes:
> 
>> Is it possible to re-enable/enhance helm to show file names in helm org headings ?
> 
> I answered you and never had response, so I closed.

Sorry to hear, it didn't reach me.

> Filenames are always here, just `(setq helm-org-show-filename t)`.

Works like a charm!

But how to find this?  I actually had a peek in the code of
helm-org-agenda-files-headings and even helm itself but didn't
recognise something file name related.

Thank you very much!

Ciao, Gregor
-- 
 -... --- .-. . -.. ..--.. ...-.-

**Comment by thierryvolpiatto** [comment]
GregorZattler <notifications@github.com> writes:

> But how to find this?

M-x customize-group => helm-org

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
GregorZattler <notifications@github.com> writes:

>> I answered you and never had response, so I closed.
>
> Sorry to hear, it didn't reach me.

Hmm, we had problems recently with github loosing some issues, answers
etc...Seems it is working now, sorry for this.


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Thierry Volpiatto <thierry.volpiatto@gmail.com> writes:

> GregorZattler <notifications@github.com> writes:
>
>> But how to find this?
>
> M-x customize-group => helm-org

Also helm-apropos is your friend, you will find quickly from there all
variables, functions etc...

Note that all helm files are autoloaded, so you have to call once a
helm-org commands to see the variable in customize or helm-apropos.

-- 
Thierry
