### ISSUE TITLE
helm+tramp feature request: `//' at the end of path as fallback to remote root dir.

### ISSUE THREAD

**Issue by vibrys** [emacs-helm/helm#1354]
Hallo Helm Team.

I'm running helm as a part of spacemacs since a week. I'm planning to stay with it.

Just went through two wonderful documents: helm-doc.org and "A Package in a league of its own: Helm".

There is still alot to learn, but a few things have already came to my mind, I would like to share with You. I'll put each of them to separate subject.

The first is related to tramp.

Let's assume I visit some remote file:

/scp:user@host:/very/long/path/to/some/dir/file.txt

I would like to make symbolic link of this file into /scp:user@host:/home/user/

In vanilla emacs I do the following:
  1. visit /scp:user@host:/very/long/path/to/some/dir/
  2. move point to file.txt
  3. press `S'.
     /scp:user@host:/very/long/path/to/some/dir/ is displayed as a suggestion to put symbolic name.
  4. I add `/' to the end of path and emacs falls into root dir of REMOTE host. Very convinient trick.
     /scp:user@host:/very/long/path/to/some/dir// => /scp:user@host:/

     This section tells the details:
       https://www.gnu.org/software/tramp/#File-name-completion

     '///' at the end ends up in root dir of local file system, which is also very convinient, for example when I want to copy some file from remote location into local filesystem.

  5. /scp:user@host:/home/user/ <enter>
     symbolic link /scp:user@host:/home/user/file.txt has been created.

What I'm missing in helm is that '//' at the end of path always ends up in root dir of local file system, ie. even for tramp paths.

What do You think about preserving '//' '///' functionality in helm?

Vanilla emacs'es behavior for local path with '//' at the end is of course the same as helm's one: conversion to local `/' is done.

best regards.

**Comment by thierryvolpiatto** [comment]
You can now use `helm-substitute-in-filename-stay-on-remote`.

**Comment by vibrys** [comment]
I like 2 step way to get local root. First '/' goes to remote root. the second '/' goes to local one.
Extra one '~/' is also nice:)
Thank You for fix!

best regards
