### ISSUE TITLE
helm-confirm-and-exit-minibuffer fails when adding filetype icons 

### ISSUE THREAD

**Issue by storax** [emacs-helm/helm#1358]
I tried adding icons for filetypes to helm-find-file candidates.
To achive this I adviced the `helm-ff-filter-candidate-one-by-one` function to add the icon as display property to the first character of the display value of the candidate. Suddenly I got errors when choosing files in certain buffers. Turns out there is a check in `helm-confirm-and-exit-minibuffer` which checks if the display property of the first character matches `"[?]"`.

Part of `helm-confirm-and-exit-minibuffer`. The crucial part is at the end. The rest was stripped.:
```lisp
(defun helm-confirm-and-exit-minibuffer ()
...
  (interactive)
  (if (and (helm--updating-p)
           (null helm--reading-passwd-or-string))
      (progn (message "[Display not ready]")
             (sit-for 0.5) (message nil))
      (let* ((empty-buffer-p (with-current-buffer helm-buffer
                               (eq (point-min) (point-max))))
             (sel (helm-get-selection))
             (unknown (and (not empty-buffer-p)
                           (string= (get-text-property  ; use equal instead of string=
                                     0 'display
                                     (helm-get-selection nil 'withprop))
                                    "[?]"))))
...
```
Now the problem is that the comparison is made with string=.but the display property can also be an image (theoretically, or if someone like in my case fiddled around). My current workaround is to override this function and use `equal` instead.

Now I haven't used this setup long enough to be sure this doesn't cause even more errors. What is your opinion? Is using `equal` "better" or "worse"?

Well I guess, you could argue that adding icons was never intended. Indeed there are a lot of pitfalls in doing so. E.g. yanking the candidate uses the display value and in this case adds the character of the icon as well. Nonetheless having icons is nice eyecandy and sometimes helps identifying files faster.

**Comment by thierryvolpiatto** [comment]
I have already implemented this for helm-find-files several years ago, and it was too slow specially on large directories, I wont enable this again.
You will retrieve the code in the git history (was anything at the time).

**Comment by storax** [comment]
Thanks I will check it out.
