### ISSUE TITLE
helm-locate and errors

### ISSUE THREAD

**Issue by michael-heerdegen** [emacs-helm/helm#1360]
Hello,

with my locate implementation (mlocate), when there are no matches, the process sentinel is called with the string
```
"exited abnormally with code 1\n"
```
With the current code, I get no visual feedback that searching has finished.  I can't know whether I should wait.

I suggest to

  - factor out the sentinel code to a defun
  - make Helm show any string received by the sentinel display in the mode-line, even when searching failed.  The user should be informed in any case.
  - but keep logging in the negative case with `helm-log`

WDYT?

Regards, Michael.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:


> I get no visual feedback that searching has finished I can't know
> whether I should wait

You have now a message in helm-buffer.

-- 
Thierry

**Comment by michael-heerdegen** [comment]
Works great - thanks.

I would change

" Command line was:\n\n " -> " command line was:\n\n "

though (looks strange capitalized since it's not the beginning of a new sentence).
