### ISSUE TITLE
conflict with mu4e contact completion

### ISSUE THREAD

**Issue by foudfou** [emacs-helm/helm#1362]
Hi,

mu4e's original completion for contacts, when composing a message, matches on substrings. For ex: typing `doe<Tab>` proposes `John Doe <jdoe@hello.gov>`.
Now, with `(helm-mode 1)`, `doe<Tab>` returns nothing: I have to type `jo<Tab>`. More strangly, I can type `jo<Tab>de` to get my entry. That is, the completion starts on the beginning of all entries, then follows on substrings.

Here is a minimal `.emacs` to reproduce:
```lisp
(setq package-archives
      '(("gnu" . "http://elpa.gnu.org/packages/")
        ("marmalade" . "https://marmalade-repo.org/packages/")
        ("melpa" . "http://melpa.milkbox.net/packages/")))
(setq package-user-dir "/usr/local/common/emacs.d/elpa")
(package-initialize)

(require 'helm)
(helm-mode 1)

;; mu/mu4e installed with pkg manager.
(add-to-list 'load-path "/usr/share/emacs/site-lisp/mu4e")

(require 'mu4e)
```

Could it be because the [completion setup in mu4e](/djcb/mu/blob/master/mu4e/mu4e-compose.el#L294) is lost by `completion-in-region-function` being overridden with `helm--completion-in-region` ?

This issue is also referenced in mu's issue list: https://github.com/djcb/mu/issues/603

My current workaround is:
```lisp
(add-to-list 'helm-mode-no-completion-in-region-in-modes 'mu4e-compose-mode)
```

Is there anything I can do to help narrowing the problem ?

**Comment by thierryvolpiatto** [comment]
foudfou <notifications@github.com> writes:

> Is there anything I can do to help narrowing the problem ?

It should work as soon as #1357 will be merged (You can try this branch
if you can't wait).

Thanks.

-- 
Thierry

**Comment by foudfou** [comment]
Works like a charm. Thank you!
