### ISSUE TITLE
Follow mode and recentf

### ISSUE THREAD

**Issue by Andre0991** [emacs-helm/helm#1363]
Hello Thierry

I use `helm-follow-mode` a lot, I quite like it.

One thing that bothers me a bit about it is that all the files visited with `helm-follow-mode` show up in `recentf` in `hem-mini`, which I also use quite frequently.

I think it'd be better for them to not show up there because I didn't really visit them interactively, just quickly skimmed the files with `helm-follow-mode`.

Is it possible to avoid this?

Thanks.

Andre

**Comment by xuchunyang** [comment]
The helm-ag has the feature which can be enabled with option [helm-ag-use-temp-buffer](https://github.com/syohex/emacs-helm-ag#helm-ag-use-temp-bufferdefault-nil), with the help of it, the following is a way to add the feature to helm-recentf:

```elisp
(with-eval-after-load "helm-files.el"
  ;; Change persistent action
  (require 'helm-ag)
  (defmethod helm-setup-user-source ((source helm-recentf-source))
    (oset source :persistent-action #'helm-ag--open-file-with-temp-buffer))
  ;; Reset up the source
  (setq helm-source-recentf
        (helm-make-source "Recentf" 'helm-recentf-source
          :fuzzy-match helm-recentf-fuzzy-match)))
```
PS. Here is the definition of `'helm-ag--open-file-with-temp-buffer`: https://github.com/syohex/emacs-helm-ag/blob/8f45c7e/helm-ag.el#L279-L286

**Comment by Andre0991** [comment]
Thanks @xuchunyang 

By the way, sorry, I forgot to mention that the command I used was `helm-locate`.

**Comment by xuchunyang** [comment]
```elisp
(with-eval-after-load "helm-locate.el"
  ;; Change persistent action
  (require 'helm-ag)
  (defmethod helm-setup-user-source ((source helm-locate-source))
    (oset source :persistent-action #'helm-ag--open-file-with-temp-buffer))
  ;; Reset up the source
  (setq helm-source-locate
        (helm-make-source "Locate" 'helm-locate-source
          :pattern-transformer 'helm-locate-pattern-transformer)))
```

**Comment by Andre0991** [comment]
Yeap I understand that the code is the same, of course -  I  just mentioned the command  in the case the maintainers agree that changing the defaults would be a good idea.

So this is solved for my setup - @thierryvolpiatto, feel free to close this issue if you disagree with making this default.
