### ISSUE TITLE
helm-source-locate breaks other sources

### ISSUE THREAD

**Issue by PythonNut** [emacs-helm/helm#1364]
**Minimal example**

```emacs
(setq helm-recentf-fuzzy-match t)
(defun my/helm-omni ()
  (interactive)
  (helm :sources '(helm-source-recentf
                   helm-source-locate)
        :fuzzy-match t))
```

1. Invoke `my/helm-omni`
2. Try to type something that (fuzzy) matches a `recentf` candidate, but not a `locate` candidate:
```
-UUU:**--F1  *scratch*      Bot L12    [(Lisp Interaction)] -------------------
 C-j: Show this file (keeping session)                                         
Recentf                                                                        
* Exit with code 1, no result found, Command line was:                         
                                                                               
 locate -i -e --regex cohel config-helm.el                                     
config-hydras.el
config-hydras.el
config-whitespace.el
company-math-autoloads.el
 *helm*       L1   [7 Candidate(s)]   C-h m:Help TAB:Act RET/f1/f2/f-n:NthAct C
pattern: cohel
```

Notice how the error message from `locate` interferes with the candidates from `recentf`, making the unusable.

**Comment by thierryvolpiatto** [comment]
PythonNut <notifications@github.com> writes:

> Minimal example
>
> (setq helm-recentf-fuzzy-match t)
> (defun my/helm-omni ()
>   (interactive)
>   (helm :sources '(helm-source-recentf
>                    helm-source-locate)
>         :fuzzy-match t))
>
> 1 Invoke my/helm-omni
> 2 Try to type something that (fuzzy) matches a recentf candidate, but not a locate candidate:
>
> -UUU:**--F1  *scratch*      Bot L12    [(Lisp Interaction)] -------------------
>  C-j: Show this file (keeping session)                                         
> Recentf                                                                        
> * Exit with code 1, no result found, Command line was:                         
>
>  locate -i -e --regex cohel config-helmel                                     
> config-hydrasel
> config-hydrasel
> config-whitespaceel
> company-math-autoloadsel
>  *helm*       L1   [7 Candidate(s)]   C-h m:Help TAB:Act RET/f1/f2/f-n:NthAct C
> pattern: cohel
>
> Notice how the error message from locate interferes with the candidates from recentf, making the unusable

This is why helm-locate should not be used with other sources.
Use helm-multi-files if you want to use helm-locate among other sources
or use helm-find-files and C-x C-f if needed.

-- 
Thierry

**Comment by PythonNut** [comment]
> `helm-locate` should not be used with other sources.

What is the reasoning behind this decision? Everything seemed to work fine in the past.

**Comment by thierryvolpiatto** [comment]
PythonNut <notifications@github.com> writes:

>     helm-locate should not be used with other sources.
>    
> What is the reasoning behind this decision? Everything seemed to work
> fine in the past.

No, this never worked fine (e.g helm-for-files).
I just keep helm-for-files because it is popular otherwise I would have
removed it from helm.
Its replacement is helm-multi-files, even better is helm-find-files as a
starting point (it is the only thing I use for files).

Also the files deleted are not appearing in recentf, so when they are
not matched by locate, they are not appearing in recentf unless you have
a problem with your recentf.

As always I will try to fix your problem anyway ASAP :-(.

-- 
Thierry

**Comment by PythonNut** [comment]
> No, this never worked fine

I mean, I assumed that something wasn't fine, but I've personally never bumped into any problems—it's been working beautifully. Is there an issue that discusses the problems with composing `helm-locate` with other sources?

> Also the files deleted are not appearing in recentf, so when they are not matched by locate, they are not appearing in recentf unless you have a problem with your recentf.

I have fuzzy matching enabled for `recentf`, but not for `locate` (too many candidates). So patterns that match the former may not match the latter.

> As always I will try to fix your problem anyway ASAP :-(.

If you don't want to, by no means do you need to. I'm merely wondering how this came to be. To me, one of the things that always made `helm` unique was the ability to use multiple sources in parallel. Other completions frameworks may be precise and fast, but `helm` is the only system that will allow me to cast a truly wide net.

**Comment by thierryvolpiatto** [comment]
Fixed, thanks.

**Comment by PythonNut** [comment]
Thank you!
