### ISSUE TITLE
helm-ucs candidates wrap around

### ISSUE THREAD

**Issue by blaenk** [emacs-helm/helm#1365]
My window width is 85 and as far as I have seen, `helm-ucs` is the only helm command where the candidates seem to wrap around unless I increase my window size to 96.

I imagine this is because the characters are shown right-aligned, and perhaps some fixed-width is being used in the calculation for that alignment. Is there a way base it on the window width? Or at the very least customize the width used for the calculation?

**Comment by thierryvolpiatto** [comment]
Jorge Israel Peña <notifications@github.com> writes:

> My window width is 85 and as far as I have seen, helm-ucs is the only
> helm command where the candidates seem to wrap around unless I
> increase my window size to 96.
>
> I imagine this is because the characters are shown right-aligned, and
> perhaps some fixed-width is being used in the calculation for that
> alignment. Is there a way base it on the window width? Or at the very
> least customize the width used for the calculation?

The aligment is calculated using the longest candidate.

i.e:

aa                       <here>
bbbbbbbbbbbbbbbbbbbbbbbb <here>

You don't see this longest candidate because of candidates-number-limit.
If we align shorter than this longest candidate, when you will match it
candidates will be no more aligned.

-- 
Thierry

**Comment by blaenk** [comment]
Ah yes, that makes sense. Thanks for responding.

I was previously using `helm-unicode` but I found out about this command so I figured I would get rid of that package. I know it seems like an insignificant thing to just resize my window, but it doesn't feel right that I have to simply for this command.

Is there perhaps any way to base the calculation off of the longest candidate within the _currently shown_ candidates? That way this wrap around would only occur if this longest candidate shows up in the results?

Or could we perhaps come up with some alternatives, even if opt-in? For example, perhaps an opt-in option to _not_ right-align the character information, instead just indent it a bit? `helm-unicode` doesn't have this problem because it simply shows the character right after the character name instead of right-aligning it. However, I agree that right-aligning it like `helm-ucs` does is nicer and easier to quickly read/see the characters. Perhaps if we could have a compromise like I mentioned above.

Actually, what if we show each candidate as the reverse of what it is now, this way we can quickly locate the characters at the beginning, and we can know where the name begins --- even if there is no alignment of the information, it is quickly identifiable and easy to locate:

```
§ (#xa7) SECTION SIGN
```

I feel like this would be an amazing way to display it. Could we perhaps have an option for that? If not, could there be a way for me to set that for myself? Please? I would really really really appreciate it.

**Comment by thierryvolpiatto** [comment]
I am working on this, will be ready soon.
I have also added the posibility to find reference of unicode character at point if some.

**Comment by blaenk** [comment]
Wow, that's great to hear! I hadn't considered that idea.

What approach are you taking for the wrapping issue? I'm liking the idea of showing the character first, instead of having to move my eyes to the right side of the screen, but I suppose as long as it stops wrapping I'll be content :smile:

**Comment by thierryvolpiatto** [comment]
Showing the character first complicate matching, so it is now shown after the code and before the name.
Alignment is not perfect because I had difficulties measuring length of characters, but is is not too bad.
Perhaps I will do some more modifications later.
Closing for now.

**Comment by blaenk** [comment]
Cool thanks! The helm-ucs-char color you chose was hardly visible on my end, but I customized it :smile:
