### ISSUE TITLE
helm-comp-read does not honour 'prompt' parameter

### ISSUE THREAD

**Issue by vibrys** [emacs-helm/helm#1367]
Hallo Thierry & Helm Team.

There is a need to print a prompt at helm-comp-read buffer, just as completing-read-default does. Unfortunately, the 'prompt' param is not honoured.

best regards

**Comment by thierryvolpiatto** [comment]
vibrys <notifications@github.com> writes:

> Hallo Thierry & Helm Team
>
> There is a need to print a prompt at helm-comp-read buffer, just as
> completing-read-default does Unfortunately, the 'prompt' param is not
> honoured

(helm-comp-read "test: " '(a b c d e))

Works fine here, "test: " is used as prompt.

-- 
Thierry

**Comment by vibrys** [comment]
Indeed,
I need to go through spacemacs config then.

Thierry,
sorry for the noise.

**Comment by thierryvolpiatto** [comment]
No problems ;-)

**Comment by vkevroletin** [comment]
@vibrys did you find which part of spacemacs config removed prompt?
