### ISSUE TITLE
eieio-defclass: Given parent class helm-type-file is not a class

### ISSUE THREAD

**Issue by vjohansen** [emacs-helm/helm#1368]
just upgraded helm to newest version via list packages

I can launch Emacs and M-x helm- TAB shows a lot of helm functions

when i try to run helm (helm-occur, helm-recentf, .. ) I get

       eieio-defclass: Given parent class helm-type-file is not a class

Windows 7
GNU Emacs 24.5.1 (i686-pc-mingw32) of 2015-04-11 on LEG570

        Debugger entered--Lisp error: (error "Given parent class helm-type-file is not a class")
          signal(error ("Given parent class helm-type-file is not a class"))
          error("Given parent class %s is not a class" helm-type-file)
          eieio-defclass(vj-helm-vps (helm-source-in-file helm-type-file) ((candidates-file :initform (vps-filelist-filename))) nil)
          (progn (eieio-defclass (quote vj-helm-vps) (quote (helm-source-in-file helm-type-file)) (quote ((candidates-file :initform (vps-filelist-filename)))) (quote nil)))
          eval((progn (eieio-defclass (quote vj-helm-vps) (quote (helm-source-in-file helm-type-file)) (quote ((candidates-file :initform (vps-filelist-filename)))) (quote nil))) nil)
          #[128 "\301\302\303B\"D\207" [lexical-binding quote eval progn] 5 1627711]((eieio-defclass (quote vj-helm-vps) (quote (helm-source-in-file helm-type-file)) (quote ((candidates-file :initform (vps-filelist-filename)))) (quote nil)))
          (eval-and-compile (eieio-defclass (quote vj-helm-vps) (quote (helm-source-in-file helm-type-file)) (quote ((candidates-file :initform (vps-filelist-filename)))) (quote nil)))
          (defclass vj-helm-vps (helm-source-in-file helm-type-file) ((candidates-file :initform (vps-filelist-filename))))
          eval-buffer(#<buffer  *load*-989625> nil "c:/users/vagn/site-lisp/emacs-config/helm-vps.el" nil t)  ; Reading at buffer position 1029
          load-with-code-conversion("c:/users/vagn/site-lisp/emacs-config/helm-vps.el" "c:/users/vagn/site-lisp/emacs-config/helm-vps.el" nil t)
          require(helm-vps)
          (lambda nil (require (quote helm-vps)))()
          funcall((lambda nil (require (quote helm-vps))))
          mapc(funcall ((lambda nil (require (quote helm-vps)))))
          do-after-load-evaluation("c:/users/vagn/.emacs.d/elpa/helm-core-20160126.1014/helm.elc")
          require(helm)

**Comment by vjohansen** [comment]
It appears to be related to something in my configuration.

If I remove my .emacs , launch Emacs, and do a (require 'helm) C-x C-e then helm works.

.. time passes,,

The error happens when I load my private helm sources which were recently updated for the new helm API (with help from Thierry*). I guess it is related to my use of

      (defclass helm-test-fav (helm-source-in-file helm-type-file)


https://github.com/vjohansen/emacs-config/blob/master/helm-vps.el

*) http://comments.gmane.org/gmane.emacs.helm.user/1296

**Comment by thierryvolpiatto** [comment]
Vagn Johansen <notifications@github.com> writes:

> just upgraded helm to newest version via list packages
>
> I can launch Emacs and M-x helm- TAB shows a lot of helm functions
>
> when i try to run helm (helm-occur, helm-recentf, ) I get
>
>    eieio-defclass: Given parent class helm-type-file is not a class

I have just updated helm on a Windows7 virtualbox with package.el and I
can't reproduce.
Reading the backtrace I see the error comes from an unknow helm package
called helm-vps.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Vagn Johansen <notifications@github.com> writes:

> It appears to be related to something in my configuration.
>
> https://github.com/vjohansen/emacs-config/blob/master/helm-vps.el

Will try to have a look at this file ASAP.

-- 
Thierry

**Comment by michael-heerdegen** [comment]
How did you load Helm?  Just doing
```
(require 'helm)
```
as seen in the backtrace doesn't load helm-files.el, thus the error.

**Comment by vjohansen** [comment]
The (require 'helm) part is probably a red herring. Because helm is installed as a package  I do not need to add any code to have access to helm functions.

.. time passes..

I got it working. I had (require 'helm-vps) (my private helm source that uses defclass) BEFORE all my helm requires 

        ;;(require 'helm-vps) <--- move below fixes the problem
        (require 'helm-config)
        (require 'helm-files)
        (require 'helm-command)
        (require 'helm-buffers)
        (require 'helm-misc) ;; enables C-r in minibuffer
        (require 'helm-grep) ;for grep to work


If I move after it works, helm-vps only does a require of helm-grep.

**Comment by michael-heerdegen** [comment]
Ok great, so I think everything behaves as expected.
