### ISSUE TITLE
nntp+server:group groups not matched anymore by gnus-group-jump-to-group in helm-mode

### ISSUE THREAD

**Issue by dinojr** [emacs-helm/helm#1371]
For instance, the group nntp+news.gmane.org:gmane.emacs.helm.user that I'm subscribed to isn't proposed by helm when calling gnus-group-jump-to-group in helm-mode and typing "helm". I guess it has to do with the + and : characters but I've checked that helm-find-files doesn't have a problem with a file named "foo+bar:dummy": it's a match for "dummy".

Julien.

**Comment by thierryvolpiatto** [comment]
Julien Cubizolles <notifications@github.com> writes:

> For instance, the group nntp+newsgmaneorg:gmaneemacshelmuser that I'm
> subscribed to isn't proposed by helm when calling
> gnus-group-jump-to-group in helm-mode and typing "helm" I guess it has
> to do with the + and : characters but I've checked that
> helm-find-files doesn't have a problem with a file named
> "foo+bar:dummy": it's a match for "dummy"

Yes it is due to last changes in helm-mode, will fix tomorrow.

Thanks.

-- 
Thierry

**Comment by dinojr** [comment]
Thanks
