### ISSUE TITLE
helm-comp-read support for wildard-aware 'collection' backend.

### ISSUE THREAD

**Issue by vibrys** [emacs-helm/helm#1372]
Hallo Thierry & Helm Team.

This thread is continuation of my work with rtags module adaptation to helm,
but the case seems to be much more generic.

Case description:
'collection' parameter to helm-comp-read is the function that accepts wildcard formatted input.
When '*' is used in the input pattern, helm does not handle function's result properly.

Details:
0. example pattern looks like following: "In*r".
1. pattern is correctly passed to 'collection' function within 'helm-comp-read-get-candidates'.
2. the proper list of results is returned from 'helm-comp-read-get-candidates'.
3. In my case, helm results buffer is either empty (:fuzzy nil), or non-empty subset of pattern treat as regex (:fuzzy t).

I also tried with passing the following parameter to 'helm-comp-read', but no luck.

                                    :fc-transformer (list (lambda (candidates _source)
                                                            candidates))

best regards.

**Comment by thierryvolpiatto** [comment]
vibrys <notifications@github.com> writes:

> Case description:
> 'collection' parameter to helm-comp-read is the function that accepts wildcard formatted input
> When '*' is used in the input pattern, helm does not handle function's result properly

Please provide recipe.

Note that files related stuff should use read-file-name instead.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Same here, it seems you are using wrongly completing-read, use read-file-name instead.
Closing for now.

**Comment by vibrys** [comment]
Please provide "In*::" to both the options below.

Also please note that non-helm version completes the common part at TAB key.

<pre>
;; emacs-helm.sh
    (helm-comp-read "->" (completion-table-dynamic
                          (lambda (s)
                            (message s)
                            '("Inher::Inher" "Inher::m_field" "virtual void Inher::fun(int)")))
                    :requires-pattern 1
                    ;; :fuzzy nil
                    )

;; emacs -Q
;; (icomplete-mode) - extra option.
    (completing-read "->" (completion-table-dynamic
                           (lambda (s)
                             (message s)
                             '("Inher::Inher" "Inher::m_field" "virtual void Inher::fun(int)"))))
</pre>

**Comment by thierryvolpiatto** [comment]
vibrys <notifications@github.com> writes:

> Please provide "In*::" to both the options below.
>
> Also please note that non-helm version completes the common part at TAB key.

helm completion is supporting regexp matching, multi regexp matching and
if enabled fuzzy matching.
What you ask is not supported (and will not be), please just use "^In
::" or "In ::" instead.

Thanks.

-- 
Thierry

**Comment by vibrys** [comment]
my goal was to provide helm support for some module that is using completing-read to get completion.

helm-comp-read says:
     It is helm `completing-read' equivalent.

That's why I used it.

Anyway with that compatibility feature or not I find helm very valuable idea.

Thank You for that.

**Comment by michael-heerdegen** [comment]
Helm can perform any desired type of completion if you use sources.

But what you want would be quite unexpected for users of Helm, I think: nowhere in Helm we imitate vanilla matching styles, they expect that Helm uses the same sort of matching everywhere (with small accomodations here and there).

So, if the standard helm completion works ok for your project, it's probably better to keep it that way.  If it is harder to use or inconvenient, then please elaborate.
