### ISSUE TITLE
Has flex matching with (completing-read) changed?

### ISSUE THREAD

**Issue by Jehops** [emacs-helm/helm#1373]
Hi,

I have some custom elisp code that looks similar to

```
(switch-to-buffer
   (completing-read
    "blah: "
    (mapcar
     (lambda (buf)
       (with-current-buffer buf
         (buffer-name buf)))
     (buffer-list))) nil t)
```
Until today, helm completed this with flex matching, but now I need to supply an exact prefix to make a completion. ` helm-flx-mode` is set to `t` and flex matching works elsewhere.

Thanks for any insight,

Joseph

**Comment by thierryvolpiatto** [comment]
Joseph Mingrone <notifications@github.com> writes:

> Hi,
>
> I have some custom elisp code that looks similar to
>
> (switch-to-buffer
>    (completing-read
>     "blah: "
>     (mapcar
>      (lambda (buf)
>        (with-current-buffer buf
>          (buffer-name buf)))
>      (buffer-list))) nil t)
>
> Until today,

I have reverted some recent changes, should work again now.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Joseph Mingrone <notifications@github.com> writes:

> (switch-to-buffer
>    (completing-read
>     "blah: "
>     (mapcar
>      (lambda (buf)
>        (with-current-buffer buf
>          (buffer-name buf)))
>      (buffer-list))) nil t)

BTW the code below is much simpler and does the same thing.

(switch-to-buffer
   (completing-read "blah: " (mapcar 'buffer-name (buffer-list)))
   nil t)

-- 
Thierry

**Comment by Jehops** [comment]
Hi Thierry,

Everything is back to normal.  Thank you.

Yes, your code is simpler, but the minimal example I provided was just a demonstration.  The full function is shown below, so you can see why I did it the way I did.

Joseph

(defun jrm/sbm (prompt mode-list)
  "PROMPT for buffers that have a major mode matching an element of MODE-LIST."
  (switch-to-buffer
   (completing-read
    prompt
    (delq nil
	  (mapcar
	   (lambda (buf)
	     (with-current-buffer buf
	       (and (member major-mode mode-list) (buffer-name buf))))
	   (buffer-list))) nil t)))
