### ISSUE TITLE
some functions only complete "from the beginning"

### ISSUE THREAD

**Issue by ericdanan** [emacs-helm/helm#1375]
I apologize if this is a dumb question, but I was not able to find an answer.

If I call helm-M-x and type "elm co" I see all functions having "elm" and "co" anywhere in their name (e.g. helm-colors, helm-company ...)

However, if I call find-library and type either "elm" or "hel co", I don't have any candidate left (in both cases I would expect to see helm-color, helm-command, ...). Why do I only see candidates whose name begins by the full string I type?

As I understand, find-library is not a helm function but it calls completing-read, which helm replaces with helm--completing-read-default. If I call

(helm--completing-read-default "Library name: " '("helm-color" "helm-command"))

then I get the same behavior as with find-library, so maybe the issue is with this latter function. Is there a way to get the "nice" completion whenever completing-read is called?

**Comment by michael-heerdegen** [comment]
This looks like the bug Thierry has fixed 22 hours ago.  Maybe retry with the newest version, or just wait until Thierry is online.

**Comment by ericdanan** [comment]
Yes it works with the newest version, thank you!

**Comment by michael-heerdegen** [comment]
Great! - thanks for testing.
