### ISSUE TITLE
Using custom keymaps with custom actions?

### ISSUE THREAD

**Issue by alphapapa** [emacs-helm/helm#1376]
I'm trying to make `C-RET` activate a custom action in a custom source.  The action works fine when activated with `F2` or from the action list, but I can't get it to work correctly from the keymap.

I have it almost working: it activates the action, but it leaves the helm buffer open.  

I've tried to dig through the helm source and follow the path of execution, but I got lost around the call to `(exit-minibuffer)`.  I guess somewhere a hook is added to helm's exit-minibuffer hook that actually calls the selected action, but I'm getting a bit worn out with this.  :)  So I would greatly appreciate any help.

Maybe the ideal solution would be a way to define a key directly in the `:action` list, instead of only separately in a custom keymap...

Here's what I have so far:
```el
(defun my/helm-org-open-heading-in-indirect-buffer (marker)
  (interactive)  ; Is this necessary here?

  (helm-org-goto-marker marker)

  ;; Open in current frame, not a new one
  (let ((org-indirect-buffer-display 'current-window))
    (org-tree-to-indirect-buffer))

  ;; Put the non-indirect buffer at the bottom of the prev-buffers
  ;; list so it won't be selected when the indirect buffer is killed
  (set-window-prev-buffers nil
                           (append (cdr (window-prev-buffers))
                                   (car (window-prev-buffers)))))

(cl-defun my/helm-source-org-headings-for-files (filenames
                                                  &optional (min-depth 1) (max-depth 8) (parents nil))
  (helm-build-sync-source "Org Headings"
    :candidates (helm-org-get-candidates filenames min-depth max-depth parents)
    :candidate-transformer (and parents 'reverse)
    :action '(("Go to heading" . helm-org-goto-marker)
              ("Open in indirect buffer" . my/helm-org-open-heading-in-indirect-buffer)
              ("Refile to this heading" . helm-org-heading-refile)
              ("Insert link to this heading" . helm-org-insert-link-to-heading-at-marker))
              :keymap my/helm-org-map))

(defun my/helm-org-in-buffer-headings ()
  "Preconfigured helm for org buffer headings."
  (interactive)
  (let ((helm-org-headings--nofilename t))
    (helm :sources (my/helm-source-org-headings-for-files (list (current-buffer)))
          :candidate-number-limit 99999
          :buffer "*helm org inbuffer*")))

(setq my/helm-org-map
      (let ((map (make-sparse-keymap)))
        (set-keymap-parent map helm-map)
        (define-key map (kbd "<C-return>")
                                           ;; Is there a cleaner way to do this?
                                           '(lambda ()
                                              (interactive)
                                              (let ((helm-saved-action 'my/helm-org-open-heading-in-indirect-buffer))
                                                (helm-execute-selection-action))))
        (define-key map (kbd "C-w") 'helm-org-heading-refile)
        (define-key map (kbd "C-l") 'helm-org-insert-link-to-heading-at-marker)
        map))
```
Thank you!

**Comment by xuchunyang** [comment]
You can change the `helm-org-headings-actions` user option for your custom action, for example,

```elisp
(setq helm-org-headings-actions
      '(("Go to heading" . helm-org-goto-marker)
        ("Open in indirect buffer `C-RET'" . my/helm-org-open-heading-in-indirect-buffer)
        ("Refile to this heading" . helm-org-heading-refile)
        ("Insert link to this heading" . helm-org-insert-link-to-heading-at-marker)))
```

Your custom action `my/helm-org-open-heading-in-indirect-buffer` doesn't need to be interactive, since it won't be called from any key directly. If you want to call the action with `C-RET`, you need wrap the action with a interactive function, for example,

```elisp
(defun helm-org-headings-run-open-heading-in-indirect-buffer ()
  (interactive)
  (with-helm-alive-p
    (helm-exit-and-execute-action 'my/helm-org-open-heading-in-indirect-buffer)))
```

and because there is no specified keymap in this case, I suggest adding a keymap such as `helm-org-headings-map`, for now, here is a workaround.

```elisp
;; Define keymap
(defvar helm-org-headings-map
  (let ((map (make-sparse-keymap)))
    (set-keymap-parent map helm-map)
    (define-key map (kbd "<C-return>") 'helm-org-headings-run-open-heading-in-indirect-buffer)
    map))

;; Add keymap
(advice-add 'helm-source-org-headings-for-files :filter-return
            (lambda (source)
              "Add `helm-org-headings-map'."
              (push `(keymap . ,helm-org-headings-map) source)))
```

**Comment by alphapapa** [comment]
Thank you very much for your help!  That looks like exactly what I need.  I figured that all the pieces were there, but it can be hard to find them and put them together properly.  I'll report back here after I get it polished up, hopefully suitable for a PR.

**Comment by alphapapa** [comment]
@xuchunyang I'm trying to fix this up, but I'm having trouble with the custom action list.  You said:

> You can change the helm-org-headings-actions user option for your custom action, for example,
```el
(setq helm-org-headings-actions
      '(("Go to heading" . helm-org-goto-marker)
        ("Open in indirect buffer `C-RET'" . my/helm-org-open-heading-in-indirect-buffer)
        ("Refile to this heading" . helm-org-heading-refile)
        ("Insert link to this heading" . helm-org-insert-link-to-heading-at-marker)))
```
But how does setting `helm-org-headings-actions` change the actions in `helm-source-org-headings-for-files`?

I tried to add it the same way that the keymap is added:
```el
(advice-add 'helm-source-org-headings-for-files :filter-return
            (lambda (source)
              (push `(actions . ,helm-org-headings-actions) source)
              (push `(keymap . ,helm-org-headings-map) source)))
```
But that doesn't work.  Am I misunderstanding something?  (There is much that I don't understand about Emacs, of course, haha.)

Thanks for your help.

**Comment by thierryvolpiatto** [comment]
alphapapa <notifications@github.com> writes:

> @xuchunyang I'm trying to fix this up, but I'm having trouble with the custom action list. You said:
>
>     You can change the helm-org-headings-actions user option for your custom action, for example,
>    
>     (setq helm-org-headings-actions
>           '(("Go to heading" . helm-org-goto-marker)
>             ("Open in indirect buffer `C-RET'" . my/helm-org-open-heading-in-indirect-buffer)
>             ("Refile to this heading" . helm-org-heading-refile)
>             ("Insert link to this heading" . helm-org-insert-link-to-heading-at-marker)))
>     
>     But how does setting helm-org-headings-actions change the actions in helm-source-org-headings-for-files?

Because helm-org-headings-actions is a symbol, it is reevaluated when
you call helm-source-org-headings-for-files.

I didn't follow carefully the beginning of this thread, but if the above
don't work, perhaps we need a set function in helm-org-headings-actions
to reload the source.
So no need of an advice for this.
To modify entries in source (e.g keymap), we would need a class for org
headings to facilitate further modifications via defmethod.

Will look at your code more carefully next week.

Thanks.

-- 
Thierry

**Comment by alphapapa** [comment]
> Because helm-org-headings-actions is a symbol, it is reevaluated when you call helm-source-org-headings-for-files.

I just realized that my helm is a bit out-of-date.  :)  The version I had installed was a few months old and had the actions hard-coded instead of using that symbol.  Now the dynamic binding should work...

I'll continue working on this and hopefully make a PR soon.  Thanks to both of you for your help!

**Comment by alphapapa** [comment]
This code is merged now.  Thanks for all of your help.
