### ISSUE TITLE
`helm-do-grep-ag` error in process filter

### ISSUE THREAD

**Issue by vspinu** [emacs-helm/helm#1378]
AFter calling `helm-do-grep-ag` and typing a character or two I am getting `helm-grep--filter-candidate-1: Symbol’s value as variable is void: helm-ff-default-directory`. 

I cannot post the backtrace, I cannot even get into backtrace window, helm hijacks all mouse events. This wasn't true before. Some time ago I could go to non-helm window and copy text from there. Is there a workaround for this?

**Comment by thierryvolpiatto** [comment]
Vitalie Spinu <notifications@github.com> writes:

> AFter calling helm-do-grep-ag and typing a character or two I am
> getting helm-grep--filter-candidate-1: Symbol’s value as variable is
> void: helm-ff-default-directory

As always, see:
https://github.com/emacs-helm/helm#alternate-install-warning


This is not reproductible. (just fixed #1377 with helm-ag+wgrep).
Also could not reproduce from ./emacs-helm.sh.


-- 
Thierry

**Comment by vspinu** [comment]
I have standard installation.. Just `(require 'helm-config)` in my .emacs after package initialization.

`helm-ff-default-directory` is defined in `helm-files.el`. `helm-grep-ag` uses that variable somehow but `helm-grep.el` doens't require `helm-files.el`. If I manually load `helm-files.el` the problem goes away.

I think you should revise your `./emacs-helm.sh` and your own config. You are loading things inadvertently somewhere. Same "non-reproducibility" happened in #1278.

**Comment by michael-heerdegen** [comment]
The thing gets reproducible if you comment out these two lines from helm.sh:
```
(helm-mode 1)

(global-set-key (kbd "M-x") 'helm-M-x)
```
That's still a valid setup, so the report is valid IMHO, as are the explanations of the reasons.
(Background: helm-files.el is required in helm-mode.el and helm-elisp.el)

@vspinu It's not easy to get backtraces from within helm.  The main reason is that completion is induced by a timer, and when the backtrace pops up, the helm session is (necessarily) still running.

Anyway, you may want to set ```helm-prevent-escaping-from-minibuffer -> nil``` and in addition
```
  (define-key helm-map [down-mouse-1] nil)
  (define-key helm-map [mouse-1] nil)
  (define-key helm-map [mouse-2] nil)
```

**Comment by michael-heerdegen** [comment]
But I see now that this has been fixed.

**Comment by vspinu** [comment]
>> On Mon, Feb 08 2016 04:26, Michael Heerdegen wrote:
> (helm-mode 1)

Yeh. This seems to be the trend with helm more recently, using helm without
activating it everywhere is becoming harder and harder.

> you may want to set ```helm-prevent-escaping-from-minibuffer -> nil``` and in addition
> ```
>   (define-key helm-map [down-mouse-1] nil)
>   (define-key helm-map [mouse-1] nil)
>   (define-key helm-map [mouse-2] nil)
> ```

 That's exactly what I was looking for. Thanks!
