### ISSUE TITLE
New command: `helm-describe-modes`

### ISSUE THREAD

**Issue by xiongtx** [emacs-helm/helm#1381]
I recently created a [helm-describe-modes](https://github.com/xiongtx/helm-describe-modes) command; It's a replacement for `describe-mode` in much the same way that `helm-descbinds` is a replacement for `describe-bindings`.

I'm wondering if we can get it included in Helm proper? If not, how about keeping it as a separate package as part of the `emacs-helm` project? I have not submitted it it to MELPA yet.

Do take a look and let me know what you think. I'm not aware of any standard ways to get code review for Emacs packages, so if anyone else does, point me to it.

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> If not, how about keeping it as a separate package as part of the
> emacs-help project?

You should now be able to add your project to emacs-helm and maintain it
there.
Let me know if I did something wrong and you still not allowed to do so.

Thanks.

-- 
Thierry

**Comment by xiongtx** [comment]
Thanks, I have joined the organization.
