### ISSUE TITLE
Q: has the `sources` attribute been deprecated in favor of `candidates`

### ISSUE THREAD

**Issue by xiongtx** [emacs-helm/helm#1384]
The `sources` attribute, which is referred to in the Wiki, is not one of the listed attributes in Helm 1.9.1. Has it been replaced with the `candidates` attribute? If so, we should update the Wiki to avoid confusion.

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> The sources attribute, which is referred to in the Wiki, is not one of
> the listed attributes in Helm 1.9.1. Has it been replaced with the
> candidates attribute? If so, we should update the Wiki to avoid
> confusion.

`:sources` is not a helm attribute, it is an argument keyword of the helm
function, see docstring of `helm` (function section in helm-apropos).
OTH `candidates` is a helm attribute, it have nothing to do with
sources, see docstring of `helm-source` (class section in helm-apropos).

-- 
Thierry

**Comment by xiongtx** [comment]
D'oh, I must have had a brain freeze and mixed up the `helm` part with the `helm-build-*-source` part. Thanks, that makes sense.

**Comment by michael-heerdegen** [comment]
We could use the name "Helm source attributes" to be more precise, yes.  Now that we are using eieio classes, I personally prefer the term "slot".  And for the helm function, "keyword" (arguments).
