### ISSUE TITLE
helm-semantic doesn't work like helm-swoop

### ISSUE THREAD

**Issue by adrsta** [emacs-helm/helm#1385]
would be nice if it scrolled the buffer with preview like swoop does

**Comment by syohex** [comment]
Could you use `helm-follow-mode` ? You can enable it `C-c C-f`in helm-semantic command.

**Comment by michael-heerdegen** [comment]
Or use just C-up C-down instead of up and down to cycle candidates.

**Comment by adrsta** [comment]
Thank you, both work great!
I guess it's not an bug, only some inconsistency.

maybe an additional function `helm-semantic-follow`
with default follow mode on would be nice to add,
then I could would use that instead

the problem comes from that, I am using evil,
and in this case Ctrl+hjkl is bound to arrows already
so cannot press twice Ctrl ;]

**Comment by michael-heerdegen** [comment]
Now that we are using classes to implement sources, you can do this yourself very easily.
The standard definition of the semantic source looks like this:
```
(setq helm-source-semantic
            (helm-make-source "Semantic Tags" 'helm-semantic-source
              :fuzzy-match helm-semantic-fuzzy-match))
```
Just add this to your config, change attributes to your likes, and arrange that it gets loaded after loading the file (typically with `eval-after-load`).
