### ISSUE TITLE
Is `helm-exit-minibuffer-hook` working correctly?

### ISSUE THREAD

**Issue by xiongtx** [emacs-helm/helm#1386]
I'd like to turn `popwin-mode` off when using Helm, and turn it back on after leaving Helm. This is because Helm's persistent action displays Help buffers in the other window. When `popwin-mode` is active, both the persistent action's Help buffer *and* the `popwin` Help buffer are shown.

I've done the following:

```emac-lisp
(defun *-popwin-help-mode-off ()
  (when (boundp 'popwin:special-display-config)
    (customize-set-variable 'popwin:special-display-config
			    (delq 'help-mode popwin:special-display-config))))

(defun *-popwin-help-mode-on ()
  (when (boundp 'popwin:special-display-config)
    (customize-set-variable 'popwin:special-display-config
                            (push 'help-mode popwin:special-display-config))))

(add-hook 'helm-minibuffer-set-up-hook #'*-popwin-help-mode-off)
(add-hook 'helm-exit-minibuffer-hook #'*-popwin-help-mode-on)
```

Turning `popwin-mode` off for Helm works fine. Turning it back on does not work, however, when exiting Helm with <kbd>C-g</kbd>. It *does* work when exiting Helm by selecting a candidate.

This is not what I would expect from the documentation:

> Run just before exiting minibuffer.

Quitting seems as valid a method of "exiting" as selecting a candidate.

I've gotten around this by using `helm-cleanup-hook` instead. Its documentation is:

> Run after helm minibuffer is closed. IOW this hook is executed BEFORE performing action.

Is this the right hook to use? What does "IOW" mean?

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:
    
> Is this the right hook to use? 

Yes.

> What does "IOW" mean?

In Other Words.

-- 
Thierry

**Comment by xiongtx** [comment]
Can we update the documentation of `helm-exit-minibuffer-hook` to:

> Run just before exiting the minibuffer. This hook is run if the minibuffer is exited normally (e.g. via candidate selection). It is NOT run if the minibuffer is exited abnormally (e.g. via `helm-keyboard-quit`).

And that of `helm-cleanup-hook` to:

> Run after exiting the minibuffer and before performing an action. This hook is run even if the minibuffer is exited abnormally (e.g. via `helm-keyboard-quit`).
