### ISSUE TITLE
`C-x C-f` not working after updating via MELPA

### ISSUE THREAD

**Issue by sac7e** [emacs-helm/helm#1388]
Hi,

I just now updated helm via MELPA and `helm-mode` stops working. 
this is the snippet in my init.el
```
;; helm
(require 'helm-config)
(require 'helm)
(helm-mode 1)
```
there is no key-binding with helm-mode enabled.

**Comment by thierryvolpiatto** [comment]
sac7e <notifications@github.com> writes:

> Hi,
>
> I just now updated helm from MELPA and helm stops working.
> this is the snippet in my init.el
>
> ;; helm
> (require 'helm-config)
> (require 'helm)
> (helm-mode 1)
>
> after adding (global-set-key (kbd "M-x") 'helm-M-x)
> only M-x working, other functions are still not working.

I don't see why helm-M-x would work and else not.
Here helm is working as always, please start with emacs-helm.sh to
reproduce.

Thanks.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Ah! I see, now find-file is no more helmized so C-x C-f is now working like in normal emacs.
Just bind helm-find-files to C-x C-f.

**Comment by sac7e** [comment]
yeah, to my emacs, there is no difference enabling helm-mode. I need to bind them manually.
Thank you for help.

**Comment by thierryvolpiatto** [comment]
sac7e <notifications@github.com> writes:

> yeah, to my emacs, there is no difference enabling helm-mode. I need to bind them manually.

`helm-find-files` and what you had before with `C-x C-f` are two different
things, one is a native helm command and the other is `find-file` the
vanilla emacs function helmized by `helm-mode`.
It is not helmized anymore because the use of `helm-find-files` instead is much
more powerful and advised.
You can get it back though by customizing `helm-completing-read-handlers-alist`.

-- 
Thierry

**Comment by sac7e** [comment]
`helm-M-x` is also not helmized by `helm-mode`?

**Comment by thierryvolpiatto** [comment]
sac7e <notifications@github.com> writes:

> helm-M-x is also not helmized by helm-mode?

`helm-M-x` is a native helm command.
The vanilla `M-x` command is `execute-extended-command` which is
disabled in `helm-completing-read-handlers-alist` for the same reasons
than `find-file`.

-- 
Thierry

**Comment by michael-heerdegen** [comment]
Maybe we should define another mode `helm-full-mode` or so, performing all command rebinds (via a keymap).  This is technically not necessary, but the issue confuses people too often.

**Comment by thierryvolpiatto** [comment]
No, people will use only this and never discover the real helm commands.
Thus this add extra work for us for people that make no effort to read custom variables and documentation.
Forget it.

**Comment by sac7e** [comment]
thank you for your help
