### ISSUE TITLE
Keep source title fixed

### ISSUE THREAD

**Issue by xiongtx** [emacs-helm/helm#1389]
In a Helm buffer with multiple sources, is it possible to keep the current source name in view (e.g. as the top line)?

This would be useful for something like [Helm Dash](https://github.com/areina/helm-dash), where I've just submitted a [pull request ](https://github.com/areina/helm-dash/pull/121) to make each "docset" its own source (currently, all docsets are lumped into a single source).

By default, Helm Dash displays candidates in the format `<docset-name> <topic> (<type>)`, e.g. `Common Lisp * (func)`. This is ugly, but necessary to be able to immediately differentiate between topics from different docsets. 

If we make each docset its own source, there would be less need to include the docset name in the candidate string. In large docsets, however, the user may lose track of which docset they are browsing if the docset name is not visible. If we make the source name the docset name and keep it visible at all times, we can safely get rid of the docset name in the candidate string.

**Comment by thierryvolpiatto** [comment]
As soon as helm update you will inevitably display other sources and selection will ends up in first source, doing the contrary would defeat the purpose of having many sources.
Perhaps I misunderstand what you want exactly though as I have no idea what your helm package display.

**Comment by xiongtx** [comment]
![helm-dash-source](https://cloud.githubusercontent.com/assets/1624090/13024280/02acb552-d1b8-11e5-956e-8929660c0069.png)

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> helm-das

Perhaps you can filter sources to use only the current one when needed ?
See `helm-set-source-filter`.

    (defun helm-current-source-only ()
      (interactive)
      (helm-set-source-filter `(,(assoc-default 'name (helm-get-current-source)))))
    (define-key helm-map (kbd "C-c s") 'helm-current-source-only)


    (defun helm-all-sources ()
      (interactive)
      (helm-set-source-filter nil))
    (define-key helm-map (kbd "C-c a") 'helm-all-sources)


-- 
Thierry

**Comment by xiongtx** [comment]
I'll try that, thanks.
