### ISSUE TITLE
last commit removes helm-match-hash

### ISSUE THREAD

**Issue by cremacs** [emacs-helm/helm#1393]
Which breaks at least one extension, [helm-fuzzier](https://github.com/EphramPerdition/helm-fuzzier)

`C-x C-f` gives:

>Symbol's value as variable is void: helm-match-hash

**Comment by thierryvolpiatto** [comment]
cremacs <notifications@github.com> writes:

> Which breaks at least one extension, helm-fuzzier
>
> C-x C-f gives:
>
>     Symbol's value as variable is void: helm-match-hash

Recompile, helm-match-hash is no more needed.

-- 
Thierry

**Comment by swarnendubiswas** [comment]
I have the same problem, and the package is installed from MELPA.

**Comment by cremacs** [comment]
I still get this error with the helm-fuzzier plugin. I don't without it. Maybe it's their problem?

**Comment by rekenerd** [comment]
All helm related packages are broken.

Example, using helm-M-x, `M-x command` gives:

> Error running timer: (void-variable helm-match-hash)

**Comment by thierryvolpiatto** [comment]
Because you have not recompiled your external helm extension, even if I don't know what is helm-fuzzer.
