### ISSUE TITLE
helm-comp-read broken

### ISSUE THREAD

**Issue by michael-heerdegen** [emacs-helm/helm#1394]
Hello,

I discovered that while performing helm-grep.

Try this:
```
(helm-comp-read
 "Search Only in: "
 '("*" "*.el" "*.1" "*.2" "*.REPO" "*.in" "*.m4" "*.sh" "*.cache" "*.bat" "*.log" "*.status" "*.ac")
 )
```

If you enter "el" or "cache", you get no candidates.

**Comment by michael-heerdegen** [comment]
This is probably also caused by the change of `helm-match-from-candidates` in a07cb1e1e741bd8c51c151945ff20e5d415c7a83.

**Comment by thierryvolpiatto** [comment]
Should be fixed now.
