### ISSUE TITLE
helm-occur duplicates results

### ISSUE THREAD

**Issue by mbuczko** [emacs-helm/helm#1395]
For some reason all results found by ```helm-occur``` are duplicated.

```occur``` itself returns perfectly valid data (if it does matter ;)

**Comment by cshtarkov** [comment]
The bug seems to have been introduced by this commit: [https://github.com/emacs-helm/helm/commit/74076188e1f6c11231c52bbfdc1f17948cd1f8bc](https://github.com/emacs-helm/helm/commit/74076188e1f6c11231c52bbfdc1f17948cd1f8bc)

Reverting it fixes it.

**Comment by thierryvolpiatto** [comment]
Should be fixed now.
