### ISSUE TITLE
helm-mode won't find anything but first line

### ISSUE THREAD

**Issue by DamienCassou** [emacs-helm/helm#1397]
I'm using `helm-mode` to get helm completion everywhere. In magit, if I press `b b` I get a list of branches to switch to. Unfortunately, helm refuses to find any match beyond the first line. So, if a branch is named `update-pharo` and this branch appears after the first branch in the branch list, then, typing whatever will never find `update-pharo`.

**Comment by DamienCassou** [comment]
I have the same problem with `M-x bookmark-jump`. With `helm-mode` active, whatever I type, I can't get anything but the first entry.

**Comment by marc0s** [comment]
I can confirm the same behavior with `magit-checkout`.  I have already set `helm-mode-fuzzy-match` to `t` but it didn't help.

**Comment by thierryvolpiatto** [comment]
Should work now.

**Comment by marc0s** [comment]
It does. Thanks @thierryvolpiatto
