### ISSUE TITLE
Cannot open load file: cl-lib

### ISSUE THREAD

**Issue by dfilan** [emacs-helm/helm#1399]
Trying to install helm using git and make. After cloning helm and async, running make inside helm gives me the following error: 
`In toplevel form:`
`helm.el:31:1:Error: Cannot open load file: cl-lib`
`make: *** [batch-compile] Error 1`

I followed the advice [here](http://stackoverflow.com/a/20933791/3109495), but to no avail. Using `M-x package-install` instead also doesn't work, telling me that `helm-core-1.9.1.tar` is not found. Running Mac OS X El Capitan 10.11.3.

**Comment by syohex** [comment]
Which emacs version did you use ? You can check it by `M-x emacs-version`. helm requires Emacs 24.3 or higher versions and cl-lib.el was bundled since Emacs 24.3.

**Comment by dfilan** [comment]
I'm using Emacs 24.5.1.

**Comment by syohex** [comment]
Could you show us output of `emacs --version` command ?

And could you show us your configuration about package.el ? I can install helm with following configuration on Emacs 24.5 without errors. 

```lisp
(require 'package)                                                                
(add-to-list 'package-archives                                                    
             '("melpa" . "https://melpa.org/packages/"))                          
                       
(package-initialize)                                                              
(package-refresh-contents)                                                        
(package-install 'helm) 
```

**Comment by dfilan** [comment]
You're right, running `emacs --version` in shell produces `GNU Emacs 22.1.1`.

Previously, I was using `M-x package-install RET helm RET` to install helm from inside Emacs, but evaluating the elisp you provided worked. Thanks for the help!
