### ISSUE TITLE
Delayed source weird behavior

### ISSUE THREAD

**Issue by mbuczko** [emacs-helm/helm#1400]
It might be not a bug, but something I don't quite understand. Having a source with ```delayed``` set, helm does exactly what description of ```delayed``` says: waits till user stops typing and then waits ```helm-idle-delay``` time. But afterwards instead of one call to generate candidates it tries to generate them as many times as many characters got buffered during typing. 

As I understood ```delayed``` sources were introduced to avoid heavy computation of candidates with each key press. What it does in fact is buffering all those computations and firing them all at once when user stops typing for some time. Is it a bug or kind of design decision?

**Comment by mbuczko** [comment]
One quick note, I didn't notice that described behavior applies to ```delayed``` *and* ```volatile``` sources. non-volatile delayed sources work as expected.

**Comment by michael-heerdegen** [comment]
I tried this test:
```
(setq helm-input-idle-delay 1)

(helm :sources (helm-make-source "Test" 'helm-source-sync
                 :volatile t
                 :delayed t
                 :candidates (lambda () (message "1")
                               '("a" "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"))))
```
I hit "b" in fast succession, but got only two messages of "1".  The result is different with the default value of ```helm-input-idle-delay -> 0.01``` of course.  With what setting did you try; what did you try?

**Comment by mbuczko** [comment]
I tried almost exactly the same example. The only difference was (message) replaced with (print). What I got was n-printed "1" (where n was number of keypresses) which I assume was caused by calculating candidates n-times.

**Comment by michael-heerdegen** [comment]
Michał Buczko <notifications@github.com> writes:

> I tried almost exactly the same example. The only difference was
> (message) replaced with (print). What I got was n-printed "1" (where n
> was number of keypresses) which I assume was caused by calculating
> candidates n-times.

And what example did you try, and is the result reproducible?  And what
was your value of `helm-input-idle-delay'?

**Comment by mbuczko** [comment]
Sorry for confusing, I'll try to clarify things up.

What I want to achieve is to make my delayed source run computation after 1 sec of idle time. All other non-delayed sources should not be affected, ie. their idle time should be 0.01 sec. 

I found in doc 2 variables I could adjust:

- ```helm-input-idle-delay``` which as doc says is also effective for non-delayed sources so I didn't want to mess with this one.
- ```helm-idle-delay``` which is effective for delayed sources, so looks like this is the one I should change

I run your example (with ```print``` instead of ```message```) with following idle values:

    (setq helm-input-idle-delay 0.01) ;; original value
    (setq helm-idle-delay 1) ;; customized value

And seems like computation is hold till 1sec of idle, but immediately right afterwards candidates are computed few times (instead of one time only).

**Comment by michael-heerdegen** [comment]
Michał Buczko <notifications@github.com> writes:

> What I want to achieve is to make my delayed source run computation
> after 1 sec of idle time. All other non-delayed sources should not be
> affected, ie. their idle time should be 0.01 sec.

I'm not sure if the delay variables work "source locally" - I doubt it,
but didn't try.  You may need a wrapper command that let-binds them, or
something like that.


> I run your example (with print instead of message) with following idle values:
>
> (setq helm-input-idle-delay 0.01) ;; original value
> (setq helm-idle-delay 1) ;; customized value

> And seems like computation is hold till 1sec of idle, but immediately
> right afterwards candidates are computed few times (instead of one
> time only).

Helm doesn't really support the case helm-input-idle-delay <
helm-idle-delay AFAIK.  Can you use the same value for the both?

**Comment by mbuczko** [comment]
Yes, I guess so. Thanks for patience and all these explanations.

I'm closing this issue as it's more about my misunderstanding of corelation between ```helm-input-idle-delay``` and ```helm-idle-delay``` rather than actual bug.

Thanks again for help.

**Comment by alphapapa** [comment]
@mbuczko Thank you for reporting this!  I noticed the exact same behavior when using a volatile delayed source with `:delayed 0.5` (or anything other than `t`): I was getting duplicated results, with the `:candidates` function called multiple times, about once for every character entered.  When I finally discovered that it was the custom delay that was the problem, I set it to use the default one, which works, but wasn't quite what I wanted.  

And thanks to @michael-heerdegen, now I have a working version:

```el
(let ((helm-input-idle-delay 0.05)
        (helm-idle-delay 0.05))
    (helm-org-rifle))
```

However, I think that this needs to be fixed somehow.  If `:delayed` is set to a custom value on a volatile source, this bug will happen, and it is hard to figure out what's going on.  I spent...too much time...trying to figure it out.  :)

I would suggest that `:delayed` set both of these values, if not for all sources, at least for volatile ones.

If for some reason that isn't possible, it should be documented that volatile sources should either use `:delayed t` or set both of these values.

**Comment by michael-heerdegen** [comment]
alphapapa <notifications@github.com> writes:

> @mbuczko Thank you for reporting this! I noticed the exact same
> behavior when using a volatile delayed source with :delayed 0.5 (or
> anything other than t): I was getting duplicated results, with the
> :candidates function called multiple times, about once for every
> character entered. When I finally discovered that it was the custom
> delay that was the problem, I set it to use the default one, which
> works, but wasn't quite what I wanted.

@thierryvalpiatto Please consider to raise an error, somewhere in the
code, when helm-input-idle-delay < helm-idle-delay.  This isn't very
useful in any case, and raising an error is better than providing a
broken unforeseeable behavior that users confuses.

> However, for some reason, the variables are not being confined to the
> let, so after running this, they are modified globally. And no matter
> what I try, whether using a let, nested lets, or a :cleanup function, I
> can't get them set back to the original value.

Do you have a recipe to reproduce with emacs-helm.sh?


Thanks,

Michael

**Comment by alphapapa** [comment]
> Do you have a recipe to reproduce with emacs-helm.sh?

I wasn't aware of that script, thanks.  This recipe seems to reproduce it with that script:

```el
(helm :sources
        (let (sources)
          (dotimes (i 2 sources)
            (push (helm-build-sync-source (format "Source #%s" i)
                    :init (lambda ()
                            (message "Source init: %s" (helm-attr 'name)))
                    :candidates (lambda ()
                                  (message "CALLED SOURCE %s: %s" (helm-attr 'name) (float-time))
                                  '("candidate"))
                      :match 'identity
                    :delayed 2
                    :multiline t
                    :volatile t)
                  sources))))
```
Run that and type a single character, then look in `*Messages*`.  You should see that it calls each source twice.  Then `C-g` and then run it again, this time typing, say, 4 characters.  You should see that it calls each source 4-5 times.  When I ran that and typed "1234" (immediately, not with a pause between characters) I got this output:

```
Source init: Source #1
Source init: Source #0
CALLED SOURCE Source #1: 1459384796.5758674
CALLED SOURCE Source #0: 1459384796.5761886
CALLED SOURCE Source #1: 1459384796.5766675
CALLED SOURCE Source #0: 1459384796.5768418
CALLED SOURCE Source #1: 1459384796.5771213
CALLED SOURCE Source #0: 1459384796.5772915
CALLED SOURCE Source #1: 1459384796.577574
CALLED SOURCE Source #0: 1459384796.5777252
CALLED SOURCE Source #1: 1459384796.5780013
CALLED SOURCE Source #0: 1459384796.5781581
```

You can see that it called each source 5 times, while it should have called each source only once.

**Comment by michael-heerdegen** [comment]
alphapapa <notifications@github.com> writes:

> You can see that it called each source 5 times, while it should have
> called each source only once.

I can reproduce this.  But Thierry seems to mean it is irrelevant since
delayed sources are obsolete.  Let's see what he can suggest how to do
your stuff without them.

Anyway, what I had really asked for, sorry if this had not been clear,
was a recipe for this:

> However, for some reason, the variables are not being confined to the
> let, so after running this, they are modified globally. And no matter
> what I try, whether using a let, nested lets, or a :cleanup function,
> I can't get them set back to the original value.

Can you reproduce this behavior with emacs-helm.sh (I guess you can)?

Thanks, Michael.

**Comment by alphapapa** [comment]
Hi Michael,

I just noticed I hadn't replied to your question yet.  I'm not sure about reproducing that issue, but with Thierry's addition of `:input-idle-delay`, the problem is solved for me, so I think I'm going to leave it be.  :)

Thanks for your help.
