### ISSUE TITLE
helm-comp-read :must-match nil is broken

### ISSUE THREAD

**Issue by wang-d** [emacs-helm/helm#1401]
(message "%S" (helm-comp-read "the-prompt" '("foo") :must-match nil))

and then type "bar" and RET into the helm.

I expect to see "bar" in my *Message* buffer afterward, but instead I only get 
helm-maybe-exit-minibuffer
Quit

**Comment by Bad-ptr** [comment]
I second that.

**Comment by Bad-ptr** [comment]
Just updated and it seems to be fixed.

**Comment by thierryvolpiatto** [comment]
No, what you expect is wrong, if you want to be able to have "bar" you have to set `:must-match` to `'confirm`, which was broken indeed.
It have been fixed now.

**Comment by wang-d** [comment]
Ah, sorry.  I was originally calling it through completing-read.  Thanks
for the quick fix!

2016-02-22 6:31 GMT-05:00 Thierry Volpiatto <notifications@github.com>:
