### ISSUE TITLE
helm find files hangs emacs

### ISSUE THREAD

**Issue by jvillasante** [emacs-helm/helm#1402]
When using `(setq helm-echo-input-in-header-line t)` emacs hangs when trying to find/create a file with a long path, if the path doesn't fit the horizontal space of the buffer emacs hangs and only kill works. I have to disable that variable to get multiline prompt.

Any help on how to use header with multiline prompt?

**Comment by michael-heerdegen** [comment]
I never experienced a hang in such a situation.

Is this reproducible for you with emacs-helm.sh?

**Comment by thierryvolpiatto** [comment]
Not reproductible.

Here how to setup this:

```elisp
  (setq helm-echo-input-in-header-line t)
  (setq helm-split-window-in-side-p t)
  (helm-autoresize-mode -1)
  (add-hook 'helm-minibuffer-set-up-hook 'helm-hide-minibuffer-maybe)
```
