### ISSUE TITLE
advice to skip ".." pattern in helm-ff-filter-candidate-one-by-one doesn't work

### ISSUE THREAD

**Issue by velkyel** [emacs-helm/helm#1405]
I'm using following advice to skip ".." pattern in helm-ff-filter-candidate-one-by-one:

    (advice-add 'helm-ff-filter-candidate-one-by-one
                :around (lambda (fcn file)
                          (unless (string-match "\\(?:/\\|\\`\\)\\.\\{2\\}\\'" file)
                            (funcall fcn file))))

GNU Emacs 25.1.50.1 (x86_64-apple-darwin15.3.0, NS appkit-1404.34 Version 10.11.3 (Build 15D21)) of 2016-02-17

helm melpa versions:

helm 20160221.2157
helm-core 20160222.1130

complete .emacs  https://github.com/velkyel/dotfiles/blob/master/.emacs

complete backtrace:

`Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  directory-file-name(nil)
  helm-basename(nil)
  #[514 "\301\302:\203\f

**Comment by thierryvolpiatto** [comment]
velkyel <notifications@github.com> writes:

> I'm using following advice to skip ".." pattern in helm-ff-filter-candidate-one-by-one:

Do you really think I am going to debug all the advices of helm users ?

Anyway as mentionned many times it is a bad idea to remove dotted files
from helm-find-files.

-- 
Thierry

**Comment by velkyel** [comment]
ok. sorry I've bothered you. closing
