### ISSUE TITLE
Helm fails to show line previews, when I use regexp

### ISSUE THREAD

**Issue by AttilaVM** [emacs-helm/helm#1406]
When I use regular expressions in helm occur for narrowing, it does not show line previews
![helm-does-not-show-line-previews](https://cloud.githubusercontent.com/assets/12675000/13252439/f2caa4b4-da36-11e5-87d8-3b8babfd331e.png)

Emacs version: GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.14.13)
helm version: 20160221.2157

It happens when I put a space in a set.

**Comment by thierryvolpiatto** [comment]
Attila Molnar <notifications@github.com> writes:

> When I use regular expressions in helm occur for narrowing, it does not show line previews

Try escaping your spaces, e.g "^\ *(something" instead of "^ *(something".

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
When entering a space without escaping it helm think you want a multi regexp matching.
Here a screenshot using `\s-` for space:

![screenshot - 24022016 - 08 34 00](https://cloud.githubusercontent.com/assets/1533939/13278585/e0ff109e-dad1-11e5-901b-62c947eb6d32.png)

**Comment by AttilaVM** [comment]
Thank you @thierryvolpiatto . That was the solution.
