### ISSUE TITLE
org-insert-link doesn't understand pasting full urls

### ISSUE THREAD

**Issue by olejorgenb** [emacs-helm/helm#1407]
`C-c C-l` gives helm completion of link protocols (http: ftp: ...). But if I simply paste in a full valid url it doesn't work - resulting in "No link selected".

I'm not familiar with helm internals, but seems like it should be simple to just send the entered text verbatim through to the wrapped function?

I could just paste the link into the buffer and org-mode will understand it, but then I have to manually write the description markup.

**Comment by thierryvolpiatto** [comment]
I am not familiar with org but if I open a org buffer, type in C-c C-l, and paste e.g "http://www.google.fr" I am prompted for description, enter it and that's all. What's the problem here ? I don't know what I can do on the helm side for this.

**Comment by thierryvolpiatto** [comment]
>I'm not familiar with helm internals, but seems like it should be simple to just send the entered text >verbatim through to the wrapped function?

You have to understand that what you are using here is a org function helmized by helm-mode and I can't modify it.

**Comment by olejorgenb** [comment]
> I open a org buffer, type in C-c C-l, and paste e.g "http://www.google.fr" I am prompted for description, enter it and that's all
Yup, that didn't happened here. I use helm through spacemacs though, so it might be something they do.

I just double checked that I ran the latest version and there was an update -> problem gone :)
