### ISSUE TITLE
Helm dependent extensions installation breaks via package.el

### ISSUE THREAD

**Issue by kingoftheknoll** [emacs-helm/helm#1410]
I'm relatively new to emacs and especially Helm but I'm noticing across the board that Helm packages like helm-projectile or helm-clojuredocs cannot be installed because they can't find reference to the helm-core .tar on the MELPA servers. 

<img width="537" alt="screen shot 2016-02-28 at 8 29 09 pm" src="https://cloud.githubusercontent.com/assets/2007892/13383674/f5c23da8-de5a-11e5-9f0c-fcdf65cec928.png">

Installing other packages via `M-x package-install <whatever>` still works fine for me so I'm generally confident that it's not my pointers to the package servers.

Love helm so far =)

**Comment by kingoftheknoll** [comment]
Wanted to test with the melpa-stable just to be sure and I'm getting a similar error that a version doesn't exist. 

<img width="663" alt="screen shot 2016-02-28 at 8 41 54 pm" src="https://cloud.githubusercontent.com/assets/2007892/13383731/c4982868-de5b-11e5-8173-843a1d7c5e44.png">

**Comment by syohex** [comment]
Did you update package database ? Please try again after `M-x package-refresh-contents`.

**Comment by kingoftheknoll** [comment]
That did it, sorry that was such a silly mistake! Still new =P
