### ISSUE TITLE
Font used in helm-ucs is unreadable on bright background.

### ISSUE THREAD

**Issue by tmalsburg** [emacs-helm/helm#1411]
The font used for the glyph (`helm-ucs-char`) is defined to be `gold`.  If the background is bright, which it is for many users, this is almost impossible to read.  Perhaps we can do something like this instead:

``` elisp
(defface helm-ucs-char
  '((((class color) (background dark))  (:foreground "Gold")))
  "Face used to display ucs characters."
  :group 'helm-font)
```

**Comment by thierryvolpiatto** [comment]
Titus von der Malsburg <notifications@github.com> writes:

> The font used for the glyph (helm-ucs-char) is defined to be gold. If the background is bright, which it is for many users, this is almost impossible to read. Perhaps
> we can do something like this instead:
>
> (defface helm-ucs-char
>   '((((class color) (background dark))  (:foreground "Gold")))
>   "Face used to display ucs characters."
>   :group 'helm-font)

Done, thanks Titus.

-- 
Thierry
