### ISSUE TITLE
`RET` with `helm-find-files` and `ag`

### ISSUE THREAD

**Issue by xiongtx** [emacs-helm/helm#1412]
In Helm 1.9.2, the `Grep current directory with AG` action for `helm-find-files` does not allow jumping to the candidate's position with `RET`. Instead, `RET` clears the minibuffer.

Invoking the `Find file` action in the `*helm ag*` buffer does the right thing. So does pressing `RET` when calling `helm-do-grep-ag` directly.

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> In Helm 1.9.2, the Grep current directory with AG action for
> helm-find-files does not allow jumping to the candidate's position
> with RET. Instead, RET clears the minibuffer.

Seems you have catched a very old bug, it happens not only with AG, but
with any actions that runs in this context.

Will fix ASAP.

Thanks.

-- 
Thierry

**Comment by cwhatley** [comment]
The commit seems to have broken helm-M-x.

**Comment by thierryvolpiatto** [comment]
Now fixed by #1416

**Comment by aiguofer** [comment]
whew! took me forever to track down that the problem was in `helm-M-x` how long does it take for changes like this to make it into melpa?

**Comment by xiongtx** [comment]
Confirmed as fixed.

*Tip*: to see the changes after upgrading the package, it's necessary to restart Emacs (or manually evaluate the relevant Emacs Lisp code...but restarting is probably easier!).

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> Confirmed as fixed.
>
> Tip: to see the changes after upgrading the package, it's necessary to
> restart Emacs

It is always true not only for helm but all other packages after upgrade.

Thanks.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Diego Fernandez <notifications@github.com> writes:

> how long does it take for changes like this to make it into melpa?

See http://melpa.org/

You will see "Current build started: an hour ago, last took 5 hours"

Builds are made by alphabetically order helm is at "h"...

-- 
Thierry
