### ISSUE TITLE
describe-* not describing

### ISSUE THREAD

**Issue by TheBB** [emacs-helm/helm#1414]
In latest master, the describe functions don't appear to work. They open a helm session but when picking a candidate no help is displayed.

Git bisect blames https://github.com/emacs-helm/helm/commit/d72d7dcd3e8bcfd83c0cf1c58bacfcfec631f4fa

**Comment by TheBB** [comment]
It looks like this affects more than just describe, which is not surprising since that commit changes some very central things.

**Comment by xenodium** [comment]
helm-M-x is affected also.

Reverting https://github.com/emacs-helm/helm/commit/d72d7dcd3e8bcfd83c0cf1c58bacfcfec631f4fa worked around it for me.

**Comment by KZiemian** [comment]
I also have problem with helm-M-x, when I press RET it say ''Quit'' in minibuffer. I also try to reverse changes in helm.el, but don't work in my case. Maybe I just do something wrong when I was rewriting code? I will try to find my way out.

**Comment by thierryvolpiatto** [comment]
Fixed by PR #1416 

Thanks to report.
