### ISSUE TITLE
helm "No method definition: initialize-instance"

### ISSUE THREAD

**Issue by surya46584** [emacs-helm/helm#1417]
After the update recently from melpa, i have issues with helm basic commands like helm find-for-file, helm-show-kill-ring  etc.
see the error below, however on fully deleting all packages and installing packages i dont see this error, but on restarting emacs issue re-appears, is it something to do with package loading i.e i use use-package for loading packages.

Error:

No method definition: initialize-instance, # helm-source-sync Kill Ring
No method definition: initialize-instance, # helm-source-buffers Buffers
No method definition: initialize-instance, # helm-source-ffiles Find Files

I dont have issue on the machine where I did not update helm packages for a month from melpa.

thanks,

**Comment by thierryvolpiatto** [comment]
surya46584 <notifications@github.com> writes:

> After the update recently from melpa, i have issues with helm basic commands like helm find-for-file, helm browse-kill-ring etc.
> see the error below, however on fully deleting all packages and installing packages i dont see this error, but on restarting emacs issue re-appears, is it something
> to do with package loading i.e i use use-package for loading packages.
>
> Error:
>
> No method definition: initialize-instance, "#"
> No method definition: initialize-instance, "#"
> No method definition: initialize-instance, "#"
>
> I dont have issue on the machine where I did not update helm packages for a month from melpa.

There is no such method in helm, the only one I found when grepping the
elpa directory is in slime (and is in lisp files...).

-- 
Thierry

**Comment by surya46584** [comment]
Hi thierrry:

helm error is for not able to find the following:

helm-source-sync
helm-source-buffers
helm-source-ffiles

these are defined as defclass in helm-source.el. any help appreciated.
mostly emacs not able to find these functions at the runtime. thanks.

**Comment by thierryvolpiatto** [comment]
surya46584 <notifications@github.com> writes:

> Hi thierrry:
>
> helm error is for not able to find the following:
>
> helm-source-sync
> helm-source-buffers
> helm-source-ffiles

There is no reason you don't find this if helm is installed as described
in README.
Did you run package-initialize on top of your init.el or .emacs.el ?

> these are defined as defclass in helm-source.el. any help appreciated.
> mostly emacs not able to find these functions at the runtime. thanks.

Seems like a bad installation of helm, if you have changed emacs
version (upgraded), be sure to recompile all your .el files.

Anyway try to delete your .elc files and recompile.

If it still persist, post the backtrace of the error and your
helm configuration.

This is not reproductible here.

Be sure also to try helm from a minimal config (use emacs-helm.sh).

-- 
Thierry

**Comment by surya46584** [comment]
Thierry, thanks for the pointer. I went back and checked the changes I have made recently to my emacs config. and the culprit turns out to be a simple typo in 'use-package' declaration, a simple mistake in use-package :mode is screwing up helm configuration i.e helm wont load properly.

I am not sure why it only impacted the above issue with helm loading up certain defclasses?? either way it is back to normal with my helm now. 

thanks for timely response. I will close this issue.

**Comment by thierryvolpiatto** [comment]
surya46584 <notifications@github.com> writes:

> I am not sure why it only impacted the above issue with helm loading
> up certain defclasses??

Helm is not able to build its sources from classes without helm-core
package which contain helm-source.el.

-- 
Thierry
