### ISSUE TITLE
helm-resume does not update folder after delete

### ISSUE THREAD

**Issue by fm4d** [emacs-helm/helm#1420]
Steps to reproduce: Run helm-find-files, mark few files and delete them with M-D. helm-resume will return you to find-files helm window with deleted files still there and marked.

**Comment by thierryvolpiatto** [comment]
fm4d <notifications@github.com> writes:

> Steps to reproduce: Run helm-find-files, mark few files and delete
> them with M-D. helm-resume will return you to find-files helm window
> with deleted files still there and marked.

It is the expected behavior, you just have to C-c C-u after resuming.
helm-resume resume the state of the source before action is executed and
don't take in account what the action did.
This is true for all sources in helm.

-- 
Thierry

**Comment by fm4d** [comment]
I am aware that helm-refresh helps but I thought that this is just not the behaviour user would expect so maybe there should be refresh called by helm itself automatically. If not then this can be closed I guess.

**Comment by thierryvolpiatto** [comment]
fm4d <notifications@github.com> writes:

> I am aware that helm-refresh helps but I thought that this is just not
> the behaviour user would expect so maybe there should be refresh
> called by helm itself automatically.

The goal of helm-resume is to not recompute candidates, doing so for e.g
helm-find-files is the same as calling it with a prefix arg and load it
from history.

The only one for now that allow this when customized is helm-(m)occur.

> If not then this can be closed I guess.

Will close then thanks.

-- 
Thierry
