### ISSUE TITLE
helm-org breaking on call to org-get-outline-path

### ISSUE THREAD

**Issue by NJBS** [emacs-helm/helm#1421]
It looks like this line specifies 3 arguments to org-get-outline-path, while org-get-outline-path only accepts two, https://github.com/emacs-helm/helm/blob/master/helm-org.el#L194.

**Comment by thierryvolpiatto** [comment]
NJBS <notifications@github.com> writes:

> It looks like this line specifies 3 arguments to org-get-outline-path,
> while org-get-outline-path only accepts two,
> https://github.com/emacs-helm/helm/blob/master/helm-org.el#L194.

Probably your org version is outdated, last versions takes 3 args.
On emacs-24.5 it takes 3 args.

-- 
Thierry

**Comment by NJBS** [comment]
Ah, there appears to be a clash.

http://orgmode.org/cgit.cgi/org-mode.git/tree/lisp/org.el#n11628
http://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/org/org.el#n11430

**Comment by TheBB** [comment]
So it's not an outdated org version, it's too new.

Would helm accept a forward compatibility patch? Presumably this must be fixed sooner or later anyway.

**Comment by thierryvolpiatto** [comment]
Eivind Fonn <notifications@github.com> writes:

> So it's not an outdated org version, it's too new.
>
> Would helm accept a forward compatibility patch? Presumably this must be fixed sooner or later anyway.

No, please update your org copy.

-- 
Thierry

**Comment by TheBB** [comment]
I have. I'm not sure you understood me correctly. Helm works with the *current* org but not the *new* (8.3.4 in my case). I'm proposing a patch to make it work with both. At some point the new org will become the current and this bug must be addressed.

**Comment by TheBB** [comment]
I should also note that 8.3.4 is a stable release and not a development version or anything like that.

**Comment by thierryvolpiatto** [comment]
Eivind Fonn <notifications@github.com> writes:

> I have. I'm not sure you understood me correctly. Helm works with the
> current org but not the new (8.3.4 in my case).

Ah, ok for misunderstanding.

> I'm proposing a patch to make it work with both.  At some point the
> new org will become the current and this bug must be addressed.

Patch is welcome, but I see the arguments have not the same meaning as
before so I am afraid we will break helm-org if we don't understand the
meaning of the new arguments (I don't personally, I have to read the new
org code before and get it of course).

Every two or three years org break helm-org.el...boring!

-- 
Thierry

**Comment by TheBB** [comment]
Sure, no problem. I can have a look at it.
