### ISSUE TITLE
(helm-mode 1) takes 73 seconds!!

### ISSUE THREAD

**Issue by ambjlon** [emacs-helm/helm#1422]
Recently, my emacs starts very slowly. Finally, I found (helm-mode 1) takes 73 seconds!!
Why does this sentence take 73 seconds??

**Comment by thierryvolpiatto** [comment]
Chen Jianglong <notifications@github.com> writes:

> Recently, my emacs starts very slowly. Finally, I found (helm-mode 1) takes 73 seconds!!
> Why does this sentence take 73 seconds??

There is no reason helm take so long to startup, the only reason I see
is related to tramp, see #1000.

(copied from #1305)

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
I have added an entry in FAQ.

-- 
Thierry
