### ISSUE TITLE
helm-mode-fuzzy-match doesn't fuzzify helm-M-x

### ISSUE THREAD

**Issue by angrybakon** [emacs-helm/helm#1423]
But `(setq-default helm-M-x-fuzzy-match t)` does.

**Comment by xuchunyang** [comment]
I think it's expected.

**Comment by angrybakon** [comment]
I think `helm-M-x-fuzzy-match` should default to `helm-mode-fuzzy-match`.

**Comment by thierryvolpiatto** [comment]
Mathieu Marques <notifications@github.com> writes:

> I think helm-M-x-fuzzy-match should default to helm-mode-fuzzy-match.

helm-M-x is not a helmized function and have nothing to do with
helm-mode-fuzzy-match.
Thus helm-mode-fuzzy-match have been added to helm because people asked
persistently for it, but it is a bad idea IMO.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

> I think it's expected.

Right, it is expected.

-- 
Thierry

**Comment by angrybakon** [comment]
@thierryvolpiatto Oh, I see.

> helm-mode-fuzzy-match have been added to helm because people asked
persistently for it, but it is a bad idea IMO

But why do you consider it a bad idea? If not default, it should be something that can be configurable at least, shouldn't it?

**Comment by thierryvolpiatto** [comment]
Mathieu Marques <notifications@github.com> writes:

> @thierryvolpiatto Oh, I see.
>
>     helm-mode-fuzzy-match have been added to helm because people asked
>     persistently for it, but it is a bad idea IMO
>    
> But why do you consider it a bad idea?

It will not work at all in many places, or at best it would be
ineficient compared to multi matching or regexp searching.
I like fuzzy matching but only in few places.

> If not default, it should be something that can be configurable at
> least, shouldn't it?

It is available but it apply on helm-mode only.
i.e on emacs-vanilla commands helmized by helm-mode.

Other helm sources (native) should allow fuzzy (if necessary) only
locally.

-- 
Thierry

**Comment by angrybakon** [comment]
Ok, I understand your point.
