### ISSUE TITLE
Recentf in Helm

### ISSUE THREAD

**Issue by KZiemian** [emacs-helm/helm#1424]
Storing recentf in helm-mini is wonderful idea, make working in Emacs much easier. I try to find a way to store more than 100 files remember in recentf, because updated packages are also remeber, so when I update 30-40 of them, I lost significant amount of information.

I try to change recentf-max-saved-items and recentf-max-menu-items variables, but this don't work, I also don't find something on this problem in Helm Wiki and like always, I try to Google it. Still, I don't find answer, so I thought that is the good place to ask.

**Comment by thierryvolpiatto** [comment]
KZiemian <notifications@github.com> writes:

> Storing recentf in helm-mini is wonderful idea, make working in Emacs
> much easier. I try to find a way to store more than 100 files remember
> in recentf, because updated packages are also remeber, so when I
> update 30-40 of them, I lost significant amount of information.
>
> I try to change recentf-max-saved-items and recentf-max-menu-items
> variables, but this don't work, I also don't find something on this
> problem in Helm Wiki and like always, I try to Google it. Still, I
> don't find answer, so I thought that is the good place to ask.

See helm-candidate-number-limit which is 100 by default.
But even if you don't see candidates in helm-buffer with this limit, you
will get them if they match pattern e.g:

    (helm :sources (helm-build-sync-source "test"
                     :candidates '(a b c d e f g h i)
                     :candidate-number-limit 6)
          :buffer "*helm test*")


When evaling the snippet above you see only the first 6 candidates, but
if you enter at prompt for example "i" i will appear in helm-buffer.


-- 
Thierry

**Comment by KZiemian** [comment]
Thank you, that work perfectly!!! I see all previous entry in helm-mini:).

KZiemian

śr., 9.03.2016 o 20:20 użytkownik Thierry Volpiatto <
notifications@github.com> napisał:

>
