### ISSUE TITLE
helm-find-files doesn't support auto-completing system variables?

### ISSUE THREAD

**Issue by galactica147** [emacs-helm/helm#1425]
Hi All,

I'm pretty new to helm and am currently working with Emacs 24.5 and latest helm from melpa 
In general, I like most of the features helm provides, which really make our Emacs experience better! 

There is only one thing I haven't figured out -- it seems helm-find-files doesn't support auto completion on system or self-defined variables, say $WORKDIR, $HOMEDIR. It does recognize them if i type them the whole name and '/' at the end. Would there be an easy way for for helm-find-files to auto-complete these variables, assuming the bash that emacs is running is has defined these variables? 

Many thanks!

**Comment by thierryvolpiatto** [comment]
galactica147 <notifications@github.com> writes:

> Hi All,
>
> I'm pretty new to helm and am currently working with Emacs 24.5 and
> latest helm from melpa In general, I like most of the features helm
> provides, which really make our Emacs experience better!

Thanks.

> There is only one thing I haven't figured out -- it seems
> helm-find-files doesn't support auto completion on system or
> self-defined variables, say $WORKDIR, $HOMEDIR.

It is not implemented, even if helm-find-files recognize these env vars.

But you have other ways to retrieve your favorites directories, namely
helm-find-files-history and helm bookmarks.
Perhaps what you need is bookmarking helm-find-files directories ?

From helm-find-files try C-x r m and C-x r b for this.

For history hit M-p (always from helm-find-files), or call
helm-find-files with a prefix arg.

> It does recognize them if i type them the whole name and '/' at the
> end.

Yes I have implemented this.

> Would there be an easy way for for helm-find-files to auto-complete
> these variables, assuming the bash that emacs is running is has
> defined these variables?

For the moment no, sorry.

-- 
Thierry

**Comment by galactica147** [comment]
Thanks @thierryvolpiatto for the quick response! 
It's good to know it hasn't been implemented rather than I haven't set it up correctly. 

Your tips on the bookmark and history may just serve me well. 
But certainly i look forward to seeing such a feature soon.

**Comment by thierryvolpiatto** [comment]
galactica147 <notifications@github.com> writes:

> Thanks @thierryvolpiatto for the quick response!
> It's good to know it hasn't been implemented rather than I haven't set it up correctly.
>
> Your tips on the bookmark and history may just serve me well.
> But certainly i look forward to seeing such a feature soon.

Hmm, I will not implement this, sorry.

Using bookmark in helm-find-files achieve the same as storing favorites
directories in env variables but in a much more convenient way, you will
forget about this once you get used to bookmarks.

-- 
Thierry
