### ISSUE TITLE
is it possible to locate files with helm-for-files using ssh ?

### ISSUE THREAD

**Issue by fredbert** [emacs-helm/helm#1427]
I want to use helm-for-files to search for files on remote hosts. It would be great if I could use /ssh: like in helm-find-files to display all hosts in my ssh config file. After choosing one host I'd like to have the recent file and locate helm display like in helm-for-files instead of a dirtree.

**Comment by thierryvolpiatto** [comment]
Sorry but no.

**Comment by fredbert** [comment]
Too bad. Out of curiosity. How extensive would it be to implement such behaviour ?
I just started to learn coding, but this sounds like a nice task.
