### ISSUE TITLE
helm-attrset: No buffer named *helm*

### ISSUE THREAD

**Issue by mordocai** [emacs-helm/helm#1430]
Using latest melpa version of helm (looks like 20160316.143) and emacs version GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.18.6) of 2016-01-22 on binet, modified by Debian.

I imagine the problem is this commit https://github.com/emacs-helm/helm/commit/8e1400db4dd9668d07aa1c3bee24582382876736 since this just started happening.

Every time I open up a file I get this error.

Helm config:

````


(use-package helm
  :ensure t
  :diminish helm-mode
  :demand t
  :bind (("M-x" . helm-M-x)
         ("C-x b" . helm-mini)
         ("M-y" . helm-show-kill-ring)
         ("C-x C-f" . helm-find-files)
         :map helm-map
              ("<tab>" . helm-execute-persistent-action)
              ("C-i" . helm-execute-persistent-action)
              ("C-z" . helm-select-action))
  :config
  (when (executable-find "curl")
    (setq helm-google-suggest-use-curl-p t))
  (helm-autoresize-mode 1)
  (eval-after-load 'company
  '(progn
     (define-key company-mode-map (kbd "C-:") 'helm-company)
     (define-key company-active-map (kbd "C-:") 'helm-company)))
  (helm-mode 1))

(use-package helm-projectile
  :ensure t)

(use-package helm-company
  :ensure t)

(use-package helm-ag
  :ensure t)
````

From my config here: https://gitlab.com/mordocai/emacs.d/blob/master/packages/helm.el

**Comment by mordocai** [comment]
Confirmed it is the commit linked above causing my issue by removing the new lines of code from my local copy of helm.

**Comment by mordocai** [comment]
Realized my description of the behavior isn't perfectly clear.

I get the message in *messages*:

    helm-attrset: No buffer named *helm* 

In the minibuffer I get:

    No buffer named *helm*

And the screen "flashes" or whatever you call it, signaling an error.

**Comment by thierryvolpiatto** [comment]
Chris Carpenter <notifications@github.com> writes:

> Confirmed it is the commit linked above causing my issue by removing
> the new lines of code from my local copy of helm.

It have been fixed, probably you don't ahve the last version.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Ah! Sorry I didn't push the fix for this done early this morning.
It is why you have the error...
Sorry again.

-- 
Thierry

**Comment by mordocai** [comment]
No problem! Thanks for pushing the fix. Closing in anticipation that it fixes the issue!
