### ISSUE TITLE
Two little details with `helm-source-complex-command-history`

### ISSUE THREAD

**Issue by michael-heerdegen** [emacs-helm/helm#1433]
1.  In very rare cases, `command-history` can contain elements that are multi-line when printed.  Should we add `:multiline t` to the source definition, or is there a better way?

2.  Should `helm-source-complex-command-history` put a re-executed history element to the top of the history?  (I would prefer that, but AFAIK vanilla emacs doesn't do that).  Likewise, should the "Edit and eval" action push the edited input to `read-expression-history`?  I think that would be useful, too.

What's your opinion about these?

Regards,

Michael.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

>  1. In very rare cases, command-history can contain elements that are
>     multi-line when printed. Should we add :multiline t to the source
>     definition, or is there a better way?

Yes, I think :multiline is fine for this.
    
>  2. Should helm-source-complex-command-history put a re-executed
>     history element to the top of the history?

Yes.

>  Likewise, should the "Edit and eval" action push the edited input to
>  read-expression-history?

IMO no.

What if the evaluation of form is cancelled ?
And if modified and fail when executed ?

-- 
Thierry

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> Michael Heerdegen <notifications@github.com> writes:
>
> > 1. In very rare cases, command-history can contain elements that are
> > multi-line when printed. Should we add :multiline t to the source
> > definition, or is there a better way?
>
> Yes, I think :multiline is fine for this.
>
> > 2. Should helm-source-complex-command-history put a re-executed
> > history element to the top of the history?
>
> Yes.

Great.

> > Likewise, should the "Edit and eval" action push the edited input to
> > read-expression-history?
>
> IMO no.

> What if the evaluation of form is cancelled ?
> And if modified and fail when executed ?

Well, we read an expression, and it's only a history (I don't suggest to
add to complex-command-history, to make that clear).  The idea is to
make the input (also) available for further editing and calling via M-:,
especially when executing the modified input fails.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Well, we read an expression, and it's only a history (I don't suggest to
> add to complex-command-history, to make that clear). The idea is to
> make the input (also) available for further editing and calling via M-:,
> especially when executing the modified input fails.

Ok go ahead.

Thanks.

-- 
Thierry

**Comment by michael-heerdegen** [comment]
Hmm, whereby, the "Edit and eval" action uses `edit-and-eval-command` which already automatically adds to `command-history` (unconditionally).  I think I'll leave this as is for consistency - all this stuff then will use `command-history`.

**Comment by michael-heerdegen** [comment]
I hope we are both happy with this change.
