### ISSUE TITLE
Revert latest commit of helm.wiki by mistake

### ISSUE THREAD

**Issue by xuchunyang** [emacs-helm/helm#1435]
I somehow clicked the Revert Changes button on Github while reading the changes, and then I reverted again to fix the first revert: https://github.com/emacs-helm/helm/wiki/FAQ/_history. I am very sorry for the mistake.

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

> I am very sorry for the mistake.

No problems ;-)

-- 
Thierry
