### ISSUE TITLE
helm-M-x shows wrong? keybinding

### ISSUE THREAD

**Issue by Jehops** [emacs-helm/helm#1436]
I make `C-h` behave like backspace and set the keybinding for help to `C-x h` with
```
(define-key key-translation-map (kbd "C-h") (kbd "<DEL>"))
(global-set-key (kbd "C-x h") 'help-command)
```
But, `helm-M-x` still shows `C-h` as the help prefix.  Is this user error or an issue with Helm?

**Comment by michael-heerdegen** [comment]
It's normal, since "C-h" is still bound in the `global-map`, no matter whether you can type it.  You need to unbind that key explicitly, and you need to do that before loading helm.

**Comment by Jehops** [comment]
Thanks.  A `(global-unset-key (kbd "C-h"))` seems to work.
