### ISSUE TITLE
An idea: circumvent `helm-quit-and-find-file` from `helm-map`

### ISSUE THREAD

**Issue by michael-heerdegen** [emacs-helm/helm#1440]
Hi,

we have C-x C-f in `helm-map` bound to `helm-quit-and-find-file`.  This is nice.  However, in a large amount of the cases, I only use that to hit C-f or C-s right afterwards: I just want to search a file with grep that a bookmark points to, or `helm-ff-run-find-sh-command` a directory in the file-cache.

So today, I tried the following:

```
(define-key helm-map
  [(control ?f)]
  (lambda ()
    (interactive)
    (run-with-idle-timer 0 nil #'helm-ff-run-find-sh-command)
    (helm-quit-and-find-file)))

(define-key helm-map
  [(control ?s)]
  (lambda ()
    (interactive)
    (run-with-idle-timer 0 nil #'helm-ff-run-grep)
    (helm-quit-and-find-file)))
```

I think it is quite useful and eases my workflow.  Dunno if it's good enough to include it in Helm.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> I think it is quite useful and eases my workflow. Dunno if it's good
> enough to include it in Helm.

No, at least I would not have this behavior for me.

-- 
Thierry
