### ISSUE TITLE
when helm-mode is enabled, emacs crashes on exit in Windows

### ISSUE THREAD

**Issue by qiangqibing** [emacs-helm/helm#1444]

**Comment by thierryvolpiatto** [comment]
I see no crashes on Windows, thus your bug report is particularly usefulness, what do you want I do with this ?

**Comment by qiangqibing** [comment]
My emacs is compiled with Auctex. When I disabled helm-mode from emacs startup, the emacs can exit successfully. However, at the situation where only helm package is installed, once helm-mode is enabled, emacs crashes on exit in Windows.

Ihave MinGW installed to compile Auctex.

Any hints on how I should debug this?

Thanks a lot!

**Comment by thierryvolpiatto** [comment]
Xu Liang <notifications@github.com> writes:

> My emacs is compiled with Auctex. When I disabled helm-mode from emacs
> startup, the emacs can exit successfully.

What do you mean by "exit successfully" ?
What is exiting ?

> However, at the situation where only helm package is installed, once
> helm-mode is enabled, emacs crashes on exit in Windows.

What's mean "crashes on exit" ?
Be more clear describing exactly what you are doing.

> Any hints on how I should debug this?

Try to start from emacs -Q and install only helm, then start installing
progressively additional packages (auctex etc...) until failure.

-- 
Thierry
