### ISSUE TITLE
helm-grep-truncate-lines seems to have no effect

### ISSUE THREAD

**Issue by vincentjgoh** [emacs-helm/helm#1445]
I've got helm-grep-truncate-lines set to t, but my lines are no longer being truncated. (They used to, but I upgraded to a more recent build.)

I can force the truncation by using C-c >, so truncation WORKS, it's just not auto-truncating the way I expect. I can't remember the version that I had where it was still working, but it was fairly old.

  helm               20160324.836  
  helm-core          20160323.407

**Comment by thierryvolpiatto** [comment]
vincentjgoh <notifications@github.com> writes:

> I've got helm-grep-truncate-lines set to t, but my lines are no longer
> being truncated. (They used to, but I upgraded to a more recent
> build.)

The only thing that have changed is that truncation is disabled when
debugging is turned on, otherwise it is working as expected.

Please try again from emacs-helm.sh.

-- 
Thierry
