### ISSUE TITLE
Request: Auto-name saved grep buffers by default

### ISSUE THREAD

**Issue by vincentjgoh** [emacs-helm/helm#1446]
Current behaviour: with helm-grep-save-buffer-name-no-confirm turned on, new hgrep buffers have a suffix automatically appended if the *hgrep* buffer already exists.

Requested behaviour: all hgrep buffers are named using this scheme. (Perhaps by an extra option on helm-grep-save-buffer-name-no-confirm)

I'd like it so that NO buffers are ever named just *hgrep*. It's not a very useful name.

**Comment by thierryvolpiatto** [comment]
vincentjgoh <notifications@github.com> writes:

> I'd like it so that NO buffers are ever named just hgrep. It's not a very useful name.

Perhaps, but you will have to do with this, looks perfectly fine to me.

-- 
Thierry
