### ISSUE TITLE
`helm-find-files`: Unexpected transformation of regexp

### ISSUE THREAD

**Issue by xiongtx** [emacs-helm/helm#1447]
## Problem 

When using `helm-find-files` and trying to enter a regexp to exclude backup files, which end in a tilde (`~`), as below:

    /foo/bar/ \[^~\]$
	
The minibuffer is unexpectedly transformed into:

    /foo/bar/~\]
	
Upon entering the dollar sign (`$`).

This behavior is strange and unexpected. It is possible to work around it by using exclamation mark (`!`) for negation, e.g.

    /foo/bar/ !~

In fact, the `!` form may even be the "preferred" form for Helm; however, standard Emacs regexps usually work, and are likely *expected* to work by users, and I wonder if this isn't simply one instance of a deeper issue.

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> When using helm-find-files and trying to enter a regexp to exclude
> backup files, which end in a tilde (~), as below:
>
> /foo/bar/ \[^~\]$

Don't escape "[" and "]".

> This behavior is strange and unexpected. It is possible to work around
> it by using exclamation mark (!) for negation, e.g.
>
> /foo/bar/ !~

Yes it is the way to go, you can add more negation if you want, e.g
"/foo/bar/ !html !lisp !something etc...".

-- 
Thierry

**Comment by xiongtx** [comment]
I think the "shrinking" behavior is caused by interaction between the tilde (`~`) and the backslash (`\`), which together are interpreted as a file path starting from the home directory.

Good to know that `!` is the preferred form of negation.
