### ISSUE TITLE
Common functionality in `helm-M-x` and `helm-apropos` for commands

### ISSUE THREAD

**Issue by xiongtx** [emacs-helm/helm#1448]
## Request

It would be nice have access to the same actions in `helm-M-x` as in `helm-apropos`, such as:

- Find function
- Info lookup

I often use `helm-M-x` to discover commands for new packages; once I find a command, I can use persistent action to get its documentation, but I cannot jump to source. I then have to use `helm-apropos` to search for the command again.

Conversely, I often want to execute a command I find through `helm-apropos`, but no action is available to do that. `helm-apropos` also does not show the keybindings of commands next to their names like `helm-M-x` does.

## Suggested Solution

Define a Helm source for Emacs commands that can be used by both `helm-M-x` and `helm-apropos`. This can reduce code duplication and increase consistency.

## Potential Issues

Looking at the `helm-command.el` code, I see that the candidates are populated through `helm-M-x-read-extended-command`, which uses `helm-comp-read` instead of creating a Helm source.

I don't know whether this is because a normal Helm source is insufficient, or the `helm-command.el` code is old, or of some other reason. `helm-comp-read` does not allow an `:action` keyword, so we cannot add actions to `helm-M-x` easily.

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> I often use helm-M-x to discover commands for new packages; once I
> find a command, I can use persistent action to get its documentation,
> but I cannot jump to source.  I then have to use helm-apropos to
> search for the command again.

Sometimes helm users ask me to write a new feature that save them one or
two keystrokes to achieve what they want and would requires me to
rewrite a whole piece of code or more.
So to save 1 or 2 seconds to the user it would take me hours of work for
really a few benefit for the user and zero for me.

Thanks to understand, that I am not paid for helm maintainance and I do
that only on my free time, but your suggestions and bug reports are
always welcome and I appreciate your participation.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
However, I can add a `:actions` keyword to `helm-comp-read` which allow adding more actions to `helm-M-x` without too much work from me (should be easy).
So you could have an action to switch to `helm-apropos` from `helm-M-x` .

**Comment by xiongtx** [comment]
> Sometimes helm users ask me to write a new feature that save them one or two keystrokes to achieve what they want and would requires me to rewrite a whole piece of code or more.
>
>So to save 1 or 2 seconds to the user it would take me hours of work for really a few benefit for the user and zero for me.

We all appreciate the great work you do on Helm, Thierry!

In any case, for me filing an issue doesn't mean "Thierry, do this now!", but is just a record of something I've noticed (a bug, a potential improvement, etc.); others may notice it as well, so having it on the agenda is a good thing.

The best kinds of issues are those that spur discussion about why something is done/not done a certain way. If there's a reason that `helm-M-x` cannot uses a Helm source, but must use (what seems to me to be the more complicated) `helm-completing-read`, that information should be recorded (preferably documented in source).

Regarding implementation, if it is straightforward, we can come up with a plan for others (e.g. myself) to do it. Sometimes this is not a good idea because the code in question is complex enough, or impacts enough other functionality, that only the maintainer has a good idea of how to make the change. 

That may be the case here, I don't know. I do see that you've removed the `:actions` keyword, so I'm guessing this is, in fact, quite complex.

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> The best kinds of issues are those that spur discussion about why
> something is done/not done a certain way. If there's a reason that
> helm-M-x cannot uses a Helm source, but must use (what seems to me to
> be the more complicated) helm-completing-read, that information should
> be recorded (preferably documented in source).

A source can be used for helm-M-x of course.
I wanted initially to have something exiting with a string, no more to
avoid user exiting with a wrong action.
Also helm-M-x is old now, originally it served me as a prototype when I
wrote helm-mode and helm-comp-read, it is why it still use
helm-comp-read.

> Regarding implementation, if it is straightforward, we can come up
> with a plan for others (e.g. myself) to do it. Sometimes this is not a
> good idea because the code in question is complex enough, or impacts
> enough other functionality, that only the maintainer has a good idea
> of how to make the change.

Agreed.

> That may be the case here, I don't know. I do see that you've removed
> the :actions keyword, so I'm guessing this is, in fact, quite complex.

Not so complex, I think that helm-comp-read should return a string and
no more, i.e have as action only identity.
If it returns or may returns something else I guess we will have
problems because users will want a customized action
var and will add there incompatible stuff.

-- 
Thierry
