### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by xiongtx** [emacs-helm/helm#1450]
The [install instructions](https://github.com/emacs-helm/helm/wiki#install) specify getting the files from the Git repo:

> First get the files from the git repo:
>
> The Helm git repo is at: https://github.com/emacs-helm/helm See the Tags section for tarballs for different versions.
>
> ...

The easiest way to install these days should be through `package.el`, right? Should we update the instructions?

**Comment by thierryvolpiatto** [comment]
I have updated wiki at https://github.com/emacs-helm/helm/wiki#install

Thanks.
