### ISSUE TITLE
`helm-open-file-externally` does not work the first time

### ISSUE THREAD

**Issue by xiongtx** [emacs-helm/helm#1451]
## Problem

The first time that `helm-open-file-externally` is run, it returns the external program to be used without actually opening the file.

## Analysis

Starting from `emacs-helm.sh`, evaluating the following on a Fedora system gives:

```emacs-lisp
(helm-open-file-externally "foo/bar/doc.pdf")

;; => ("/usr/bin/xdg-open")
```

Evaluating it a second time opens the file and gives the correct result:

```emacs-lisp
;; => /usr/bin/xdg-open /foo/bar/doc.pdf process...Finished
```

The problem line seems to be:

```emacs-lisp
(helm-run-or-raise program file)
```

Calling this this function the first time results `("/usr/bin/xdg-open")`.

**Update**: the issue seems to be with `helm-external-commands-list`. See [comment below](https://github.com/emacs-helm/helm/issues/1451#issuecomment-202013343).

**Update 2**: the issue the use of a path-qualified command, e.g. `/usr/bin/xdg-open`, vs. a non-qualified command (e.g. `xdg-open`). See [comment below](https://github.com/emacs-helm/helm/issues/1451#issuecomment-202125876).

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> Problem
>
> The first time that helm-open-file-externally is run, it returns the external program to be used without actually opening the file.
>
> Starting from emacs-helm.sh, evaluating the following on a Fedora system gives:
>
> (helm-open-file-externally "foo/bar/doc.pdf")
>
> ;; => ("/usr/bin/xdg-open")

I think it is more a problem with xdg-open itself, which itself need to
choose a program to use by default (xdg-open is not a specialized
program for pdf).

Here how work helm-open-file-externally:

1) It checks for an entry in helm-external-programs-associations, if no
entry it goes to 2).

2) It checks in a .mailcap (home or system wide) what application it
could use, if it finds one there it uses it (your case with xdg-open+pdf).

3) If nothing found in both it prompt you with a list of programs to use
with eventually arguments, if you accept this program (RET) it store
this program in helm-external-programs-associations and this entry will
override .mailcap entry.

Of course you can force the use of another program at any time by using
a prefix arg (I often do this with images, sometimes to view them,
sometimes to edit with gimp etc...)
This is much better than the regular emacs system that force you to
reuse what you have configured in a variable you have to setup manually
again when you want to choose another program.

So if you use this interactively you should not have any problems, I use
this everyday to open files with diverses programs.

But xdg-open may be buggy on some systems and behave oddly, here it is
working as expected with xubuntu+xfce.

-- 
Thierry

**Comment by xiongtx** [comment]
Ahh, I think I figured out the issue.

`helm-run-or-raise` contains the following:

```emacs-lisp
(when (cl-loop for i in helm-external-commands-list thereis (string= real-com i))
  ...)
```

When Helm is first started, `helm-external-commands-list` is nil, so this check is *not* passed. We then go to the part where the command is added to the front of `helm-external-commands-list`:

```emacs-lisp
(setq helm-external-commands-list
            (cons real-com
                  (delete real-com helm-external-commands-list)))
```

Now that the command is there, the second invocation of `helm-run-or-raise` works as expected.

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> Ahh, I think I figured out the issue.
>
> helm-run-or-raise contains the following:
>
> (when (cl-loop for i in helm-external-commands-list thereis (string= real-com i))
>   ...)
>
> When Helm is first started, helm-external-commands-list is nil,

No, when you call helm-open-file-externally it calls
helm-external-commands-list-1 which itself setup
helm-external-commands-list.
This is done _before_ calling helm-run-or-raise.

-- 
Thierry

**Comment by xiongtx** [comment]
Ahh, yes, *there's* the problem.

In `helm-open-file-externally`, we have:

```emacs-lisp
(def-prog       (helm-get-default-program-for-file fname))
(real-prog-name (if (or helm-current-prefix-arg (not def-prog))
					;; Prefix arg or no default program.
					(prog1
						(helm-comp-read
						 "Program: " collection
						 :must-match t
						 :name "Open file Externally"
						 :del-input nil
						 :history helm-external-command-history)
					  ;; Always prompt to set this program as default.
					  (setq def-prog nil))
				  ;; No prefix arg or default program exists.
				  (replace-regexp-in-string " %s\\| '%s'" "" def-prog)))
(program        (concat real-prog-name " %s")))
...
(helm-run-or-raise program file)
```

The problem is that `program` has the value of `/usr/bin/xdg-open`, whereas `helm-external-commands-list-1` populates `helm-external-commands-list` with just `xdg-open`. Therefore, the `string=` check in

```emacs-lisp
(when (cl-loop for i in helm-external-commands-list thereis (string= real-com i))
```

in `helm-run-or-raise` fails. After it fails, however, we add the command to the front of `helm-external-commands-list`, so it succeeds if we try again.

**Comment by xiongtx** [comment]
Confirmed as fixed.
