### ISSUE TITLE
Unable to set source-local delays

### ISSUE THREAD

**Issue by alphapapa** [emacs-helm/helm#1454]
Hi,

As I mentioned at https://github.com/emacs-helm/helm/issues/1400#issuecomment-203490226 I am having a problem with using multiple delayed sources.  As the reporter of that bug described, when I use a `:delayed` other than the default, I get duplicated results, with `:candidates` being called once for every character entered.

When I set both `helm-input-idle-delay` and `helm-idle-delay` to the same value, it works properly.

But despite trying every way I can think of, I can't set those values without overriding the user's global values.  

These all have no effect:

```el
(let ((helm-input-idle-delay 2)
      (helm-idle-delay 2))
    (helm))

(helm :init (lambda ()
              (setq helm-input-idle-delay 2)
              (setq helm-idle-delay 2)))

(helm :before-init-hook (lambda ()
                          (setq helm-input-idle-delay 2)
                          (setq helm-idle-delay 2)))

(helm :after-init-hook (lambda ()
                         (setq helm-input-idle-delay 2)
                         (setq helm-idle-delay 2)))
```

This works, but it also sets the global values, overriding future invocations of Helm:

```el
(helm :source (helm-build-sync-source "name"
                :init (lambda ()
                        (setq helm-input-idle-delay 2)
                        (setq helm-idle-delay 2))))
```

I was able to get it to reset the default values after Helm exits by using the source above with a `:cleanup` function that reset the global values.  However, that requires me to record the original values in my own global variables, which means that if the user customizes them after loading my package, my sources will reset the old values until Emacs is restarted.

So, is there a way that Helm could allow `helm-input-idle-delay` and `helm-idle-delay` to be set for individual sources or individual invocations of `helm`?  That would solve this problem completely, I think.

Thanks for your help.

**Comment by thierryvolpiatto** [comment]
alphapapa <notifications@github.com> writes:

> Hi,
>
> As I mentioned at #1400 (comment) I am having a problem with using
> multiple delayed sources.

As I already told you you are reinventing from scratch or nearly helm
in-buffer method so of course errors are expected...

> As the reporter of that bug described, when I use a :delayed other
> than the default, I get duplicated results, with :candidates being
> called once for every character entered.

I guess this hide a problem in your own code implementation.

> When I set both helm-input-idle-delay and helm-idle-delay to the same value, it works properly.

I made a quick fix, please note (I will improve docstring about this)
that :delayed slot value have to be a number, not a boolean.

Note also that delayed sources are NO more needed nowaday and their usage may
be removed in future.

-- 
Thierry

**Comment by alphapapa** [comment]
Hi Thierry,

Thanks for your reply.

> As I already told you you are reinventing from scratch or nearly helm in-buffer method so of course errors are expected...

You may be right, but if I understand correctly, using the helm-in-buffer method wouldn't be appropriate for what I'm doing, because:

1.  I don't want to copy the buffer I'm searching into a new buffer to find candidates in it.
2.  I'm not matching lines but org-mode nodes, which requires a lot of backtracking.

> I guess this hide a problem in your own code implementation.

I don't think so, because the problem I'm describing is exactly the same as the other bug describes.  I have one source per buffer I'm searching.  When I use `:delayed` without a value, it works correctly.  When I pass it an integer, Helm waits for the delay, and then calls the `:candidates` function one time for every character entered, rather than a single time.  I could use a plain:

```el
:candidates (lambda () ("called"))
```

...and Helm would call it multiple times instead of once.  And as the other bug report noted, this only happens when `:delayed` is called with a number and the source is also `:volatile`.

> Note also that delayed sources are NO more needed nowaday and their usage may be removed in future.

Sorry, I'm confused.  What's the correct way to delay a source from calling its candidates function until the user stops typing?

Thanks for your help.

**Comment by thierryvolpiatto** [comment]
Delayed sources are deprecated since we have introduced the usage of while-no-input in helm some years ago.  I have since then removed usage of it in all helm sources provided with helm.

Delayed was needed at the time to prevent helm updating while user was typing something in minibuffer, at this time updating was kicking in with post-command hook and not with a timer inside minibuffer-setup-hook, well the implementation was different and the results too, often hanging while typing in e.g helm-locate, helm-find-files and some others.

Now I have stopped using this, there is no need to use it anymore, thus the code was quite buggy because I didn't take care of this as I was not using it anymore.
For maintenance, it is also much better for me because it was sometimes a headache to make this working everywhere.

So @alphapapa  for your specific case, you should not need this, if you think you still need this consider modifying your approach for what you want to implement.

Thanks all for your comprehension.

**Comment by thierryvolpiatto** [comment]
Also BTW helm-idle-delay and helm-quick-update have been also removed, for the benefit of user.
helm-idle-delay specially made a lot of confusion for all helm users, now only helm-input-idle-delay is needed.

**Comment by alphapapa** [comment]
Hi Thierry,

Thanks for your work and explanation.  That makes sense.

The reason I would like to have a small delay now is to prevent flickering of the Helm buffer while the user is typing.  This is especially noticeable if the user pauses for a moment and then begins typing again.  For example, in my project, it isn't useful to filter on one or two letters at a time, but on whole words, so filtering as fast as the user can type isn't helpful and results in the flickering.

If a delay could be specified for each Helm invocation, it would solve the problem.  For example, I'd like to have a 50-100ms delay to prevent the flickering.

I'm guessing that setting `helm-input-idle-delay` would fix that now, however I have been unable to set that for individual invocations of Helm.  I've tried several methods, but either it doesn't take effect (like wrapping the `helm` call in a `let`), or it sets the global value, overriding the user's setting for all future Helm sessions (like when setting the variable in `:init`).

I was able to work around that by resetting the variable in `:cleanup`, but that resulted in another problem: if the user customizes `helm-input-idle-delay` after my package is loaded, my package will reset the value that was set when it was loaded.

So, would it be possible to have a way to set `helm-input-idle-delay` in the call to `helm`?  I think this could be useful for many other projects that use Helm, especially for ones that use synchronous sources.

Thanks for all your help.

**Comment by thierryvolpiatto** [comment]
alphapapa <notifications@github.com> writes:

> So, would it be possible to have a way to set helm-input-idle-delay in
> the call to helm? I think this could be useful for many other projects
> that use Helm, especially for ones that use synchronous sources.

I have commited a change so that you can set this locally, e.g

    (helm :sources (helm-build-sync-source "test"
                     :candidates '(aaaaaa baaaaa caaaa dddddd edd fcccc gbaa hbaa))
          :input-idle-delay 3
          :buffer "*helm test*")

However do you know you can suspend update with `C-!` ?

-- 
Thierry

**Comment by alphapapa** [comment]
Thank you, Thierry, that should be perfect!  I really appreciate your taking the time to do that.

> However do you know you can suspend update with `C-!` ?

Well, what I needed way a way to delay `:candidates` from being called until after the user stops typing, so this change you made should do the trick.  :dancer: 

Thanks again, Helm is the best!
