### ISSUE TITLE
helm-locate fails if default-directory doesn't exist

### ISSUE THREAD

**Issue by CyberShadow** [emacs-helm/helm#1457]
To reproduce:

```
M-: (find-file "~/a/b/c/test.txt") RET
M-x helm-locate RET
(type something)
```

This shows no results, or an error:

```
(file-error "Setting current directory" "no such file or directory" "/home/vladimir/a/b/c/")
```

Sorry, I'm not sure if this is a helm bug. Is the working directory important for `locate`?

**Comment by thierryvolpiatto** [comment]
Vladimir Panteleev <notifications@github.com> writes:

> Is the working directory important for locate?

Yes, as soon as you save your file it will work.

-- 
Thierry

**Comment by CyberShadow** [comment]
> Yes, as soon as you save your file it will work.

Yeah, I realize that. Probably should have mentioned that in the bug report. My setup creates buffers with nonexisting auto-generated paths when I create a new frame, so I can start typing away random notes and save them to unique filenames. Not sure if that's not weird enough to warrant fixing something in helm though.

**Comment by michael-heerdegen** [comment]
FWIW, this bug has a longstanding tradition in Emacs.  Try e.g. M-x gnus.

I think the best would be to find a solution for this problem in Emacs.

**Comment by thierryvolpiatto** [comment]
Vladimir Panteleev <notifications@github.com> writes:


> Not sure if that's not weird enough to warrant fixing something in
> helm though.

There is nothing to fix on helm side, as Michael said it is an emacs
bug, try from emacs -Q:

M-: (find-file "~/a/b/c/myfile.txt") RET
M-: default-directory RET

-- 
Thierry

**Comment by CyberShadow** [comment]
> M-: (find-file "~/a/b/c/myfile.txt")  
> RET M-: default-directory RET

Yeah, again, that's not the surprising part. Helm *could* check if `default-directory` exists before spawning processes. But feel free to close this.

**Comment by CyberShadow** [comment]
Hello,

I think this should be reopened.

The situation of having a buffer open for which the directory doesn't yet exist is not at all uncommon.

One way to do this is, which I mentioned above, is to visit a file name with non-existing directory names in its path.

However, this can also happen if the directory of a file visited in Emacs has been deleted externally. This can happen if you open a temporary file, or a file whose lifetime is bound to something Emacs doesn't know (e.g. the file is opened from an archive program, which extracts the file to a temporary location but deletes it when the program exits).

Either way:

It is not unexpected that functions related to the current file fail, for example M-x compile. It would be possible to make it work still, by passing the current directory by handle instead of by path, but that's outside the scope of this bug.

However, in this situation, the failure is with the `locate` invocation, the results of which do not actually depend on the current directory.

Therefore, I would like to affirm that this actually is a bug in helm. Helm should be setting the current directory of `locate` to something that's known to exist, such as `/`.

**Comment by thierryvolpiatto** [comment]
Vladimir Panteleev <notifications@github.com> writes:

> I think this should be reopened.

Should be fixed now, if it is not the case feel free to reopen.

Thanks.

-- 
Thierry

**Comment by CyberShadow** [comment]
It works, thanks!

**Comment by CyberShadow** [comment]
> if it is not the case feel free to reopen.

BTW, it might not be obvious but only those with commit access can reopen issues.

**Comment by thierryvolpiatto** [comment]
Vladimir Panteleev <notifications@github.com> writes:

>     if it is not the case feel free to reopen.
>    
> BTW, it might not be obvious but only those with commit access can reopen issues.

Oh, really ?
Is that new in github ?   I thought it was possible.

-- 
Thierry
