### ISSUE TITLE
"ad-handle-definition: `tramp-read-passwd' got redefined" being logged to messages

### ISSUE THREAD

**Issue by stevenspasbo** [emacs-helm/helm#1459]
It's happening when helm-mode is enabled.

Emacs version: `GNU Emacs 24.5.1 (x86_64-apple-darwin14.5.0, NS apple-appkit-1348.17)`

**Comment by thierryvolpiatto** [comment]
Steven <notifications@github.com> writes:

> It's happening when helm-mode is enabled.

It is a warning about tramp-read-passwd adviced by helm, nothing wrong,
well just a warning, don't worry ;-)

-- 
Thierry

**Comment by stevenspasbo** [comment]
Thanks, I was doing some benchmarking with [esup](https://github.com/jschaf/esup), which kept failing, and I thought it might be related. After more digging it sounds like a bug with the other project.
