### ISSUE TITLE
Helm swallows error message generated by candidates function

### ISSUE THREAD

**Issue by tmalsburg** [emacs-helm/helm#1460]
In [helm-bibtex](https://github.com/tmalsburg/helm-bibtex), my candidates function fails with an error when the BibTeX file supplied by the user is malformed.  Unfortunately, Helm only shows an empty buffer in this case (as if there were no candidates) and the error is not printed in the message buffer.

It would be great if Helm could display the error message, so that users have some information about what might be going on.

**Comment by thierryvolpiatto** [comment]
Titus von der Malsburg <notifications@github.com> writes:

> In helm-bibtex, my candidates function fails with an error when the
> BibTeX file supplied by the user is malformed. Unfortunately, Helm
> only shows an empty buffer in this case (as if there were no
> candidates) and the error is not printed in the message buffer.
>
> It would be great if Helm could display the error message, so that
> users have some information about what might be going on.

Helm is returning an error in this case:

    (helm :sources (helm-build-sync-source "test"
                     :candidates (lambda ()
                                   (mapc 'insert-file-contents
                                         (apply 'append '(("~/tmp/foo.txt" "~/tmp/bar.txt")
                                                          ("~/tmp/test/test1.txt" "~/tmp/test/test2.txt")
                                                          ;; These next two files don't exists.
                                                          ("~/tmp/test2/foo.txt" "~/tmp/test2/bar.txt/"))))))
          :buffer "*helm test*")


=>
Debugger entered--Lisp error: (file-error "Opening input file" "aucun fichier ou dossier de ce type" "/home/thierry/tmp/test2/foo.txt")
  insert-file-contents("~/tmp/test2/foo.txt")


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Thierry Volpiatto <thierry.volpiatto@gmail.com> writes:

> Titus von der Malsburg <notifications@github.com> writes:
>
>> In helm-bibtex, my candidates function fails with an error when the
>> BibTeX file supplied by the user is malformed. Unfortunately, Helm
>> only shows an empty buffer in this case (as if there were no
>> candidates) and the error is not printed in the message buffer.
>>
>> It would be great if Helm could display the error message, so that
>> users have some information about what might be going on.
>
> Helm is returning an error in this case:
>
>     (helm :sources (helm-build-sync-source "test"
>                      :candidates (lambda ()
>                                    (mapc 'insert-file-contents
>                                          (apply 'append '(("~/tmp/foo.txt" "~/tmp/bar.txt")
>                                                           ("~/tmp/test/test1.txt" "~/tmp/test/test2.txt")
>                                                           ;; These next two files don't exists.
>                                                           ("~/tmp/test2/foo.txt" "~/tmp/test2/bar.txt/"))))))
>           :buffer "*helm test*")
>
>
> =>
> Debugger entered--Lisp error: (file-error "Opening input file" "aucun fichier ou dossier de ce type" "/home/thierry/tmp/test2/foo.txt")
>   insert-file-contents("~/tmp/test2/foo.txt")

And if you use your init function which use user-error, the error is
prevented:

(helm :sources (helm-build-sync-source "test"
                 :init (lambda ()
                         (mapc (lambda (file)
                                 (unless (file-exists-p file)
                                   (user-error "BibTeX file %s could not be found." file)))
                               (apply 'append '(("~/tmp/foo.txt" "~/tmp/bar.txt")
                                                      ("~/tmp/test/test1.txt" "~/tmp/test/test2.txt")
                                                      ;; These next two files don't exists.
                                                      ("~/tmp/test2/foo.txt" "~/tmp/test2/bar.txt/")))))
                 :candidates (lambda ()
                               (mapc 'insert-file-contents
                                     (apply 'append '(("~/tmp/foo.txt" "~/tmp/bar.txt")
                                                      ("~/tmp/test/test1.txt" "~/tmp/test/test2.txt")
                                                      ;; These next two files don't exists.
                                                      ("~/tmp/test2/foo.txt" "~/tmp/test2/bar.txt/"))))))
      :buffer "*helm test*")

=> only a message:

user-error: BibTeX file ~/tmp/test2/foo.txt could not be found.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
So it is not helm but you who is preventing helm from popping up error with your init function.
Closing, feel free to reopen if needed.

**Comment by tmalsburg** [comment]
There is a misunderstanding: the problem does not occur when a file is not found.  It occurs when the BibTeX file has a syntax error.  This error arises in the candidates function.  When I call the candidates function directly, I get an error message, but when it is called through helm, there is no error message but just an empty buffer.  I'll try to construct a minimal working example.

**Comment by tmalsburg** [comment]
Here's an example:

``` elisp
(helm :sources (helm-build-sync-source "test"
                 :candidates (lambda () (signal 'scan-error '())))
      :buffer "*helm test*")
```

When I executed this the first time, I got an empty helm-buffer but no error message.  Interestingly, when I executed it again, I did get an error message and back track.  Very strange.

**Comment by thierryvolpiatto** [comment]
Titus von der Malsburg <notifications@github.com> writes:

> Here's an example:
>
> (helm :sources (helm-build-sync-source "test"
>                  :candidates (lambda () (signal 'scan-error '())))
>       :buffer "*helm test*")
>
> When I executed this the first time, I got an empty helm-buffer but no
> error message. Interestingly, when I executed it again, I did get an
> error message and back track. Very strange.

I have an error message at each time with your recipe, did you try from
./emacs-helm.sh ?

> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub*


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Thierry Volpiatto <thierry.volpiatto@gmail.com> writes:

> I have an error message at each time with your recipe, did you try from
> ./emacs-helm.sh ?

Well, I meant a backtrace at each time, sorry.

>> —
>> You are receiving this because you modified the open/close state.
>> Reply to this email directly or view it on GitHub*


-- 
Thierry

**Comment by michael-heerdegen** [comment]
Same here.  With `debug-on-error -> t` of course.

@thierryvolpiatto  I wonder now, however, if it is good to silently ignore errors without indication.  We could generate a pseudo candidate like `*An error occured in this source*` or so, to make this case distinguishable from the "no error, no candidates" case when `debug-on-error -> nil`.

**Comment by tmalsburg** [comment]
In helm-bibtex, I reliably get no error but the code is complex and it's difficult to track down what's causing this problem.  Perhaps, it has something to do with timing?  This could potentially also explain why my example above worked only the first time. 

@michael-heerdegen I like your proposal.  An alternative might be that a helm session isn't even started.  It doesn't make sense to prompt for a search term if the candidate function failed.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Same here. With debug-on-error -> t of course.

debug-on-error is always t when evaling.

> @thierryvolpiatto I wonder now, however, if it is good to silently
> ignore errors without indication. We could generate a pseudo candidate
> like *An error occured in this source* or so,

No, this would defeat code relaying of helm-empty-buffer/source.

> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub*


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Titus von der Malsburg <notifications@github.com> writes:

> Perhaps, it has something to do with timing?

No.

> This could potentially also explain why my example above worked only
> the first time.

This is not related to helm but something else, did you try from
emacs-helm.sh ?

> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub*


-- 
Thierry

**Comment by michael-heerdegen** [comment]
Thanks!

Though, the message for Titus' example looks a bit weird:

"In ‘test’ source: ‘(closure (t) nil (signal ’scan-error ’nil))’ must either be a function, a variable or a list
 (scan-error)"

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> > Same here. With debug-on-error -> t of course.
>
> debug-on-error is always t when evaling.

Not for pp-eval-last-sexp.

> > @thierryvolpiatto I wonder now, however, if it is good to silently
> > ignore errors without indication. We could generate a pseudo candidate
> > like *An error occured in this source* or so,
>
> No, this would defeat code relaying of helm-empty-buffer/source.

Ah, right.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Thanks!
>
> Though, the message for Titus' example looks a bit weird:
>
> "In ‘test’ source: ‘(closure (t) nil (signal ’scan-error ’nil))’ must either be a function, a variable or a list
> (scan-error)"

The only weird part I see is 

‘(closure (t) nil (signal ’scan-error ’nil))’

This could be replaced by "anonymous" in such case but I thought it could be useful
to see the whole closure or lambda or bytecode even if it looks weird,
but I have not a strong opinion on this, if you feel "anonymous" is
enough I am ok with it.

Also of course "must either be a function, a variable or a list" is
something generic that not always reflect the type of error, I have no
better idea for now, if you think you can improve this message feel free
to change it.

-- 
Thierry

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:


> The only weird part I see is 
>
> ‘(closure (t) nil (signal ’scan-error ’nil))’
>
> This could be replaced by "anonymous" in such case but I thought it
> could be useful to see the whole closure or lambda or bytecode even if
> it looks weird, but I have not a strong opinion on this, if you feel
> "anonymous" is enough I am ok with it.

No, I agree it's useful.

> Also of course "must either be a function, a variable or a list" is
> something generic that not always reflect the type of error, I have no
> better idea for now, if you think you can improve this message feel
> free to change it.

Can we avoid that generic part in case of an error (where it makes no
sense at all)?  AFAIK it's only useful when the return value is not of
an appropriate type.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> No, I agree it's useful.

Ok, so let's keep it.

> Can we avoid that generic part in case of an error (where it makes no
> sense at all)? AFAIK it's only useful when the return value is not of
> an appropriate type.

Yes, done, have a try with these wrong functions:

    (defun helm-test-error ()
      (interactive)
      (helm :sources (helm-build-sync-source "test"
                       :candidates (directory-files "/zzzzzzzzzzzzzz"))
            :buffer "*helm test*"))

    (defun helm-test-error1 ()
      (interactive)
      (helm :sources (helm-build-sync-source "test"
                     :candidates "foo")
          :buffer "*helm test*"))


Thanks.
 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub*


-- 
Thierry

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> Yes, done,

Thanks!

 have a try with these wrong functions:
>
> (defun helm-test-error ()
> (interactive)
> (helm :sources (helm-build-sync-source "test"
> :candidates (directory-files "/zzzzzzzzzzzzzz"))
> :buffer "*helm test*"))

In this example, the error is not treated by the code you changed, but
already when building the source - or do I miss something?  I guess you
wanted to use a candidates function?

> (defun helm-test-error1 ()
> (interactive)
> (helm :sources (helm-build-sync-source "test"
> :candidates "foo")
> :buffer "*helm test*"))

That example works as expected.


Two more comments:

1. Can we give the variable "type-error" a better name (since it doesn't
handle only type errors)?  "notify-error" maybe?

2.  For debugging purposes (getting a good backtrace), can we downgrade
the `condition-case' in "helm-get-candidates" to not catch errors at all
when debug-on-error -> t?  It doesn't make sense to re-throw the error
later, that loses the context of the error.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Thierry Volpiatto <notifications@github.com> writes:
>
>> Yes, done,
>
> Thanks!
>
> have a try with these wrong functions:
>>
>> (defun helm-test-error ()
>> (interactive)
>> (helm :sources (helm-build-sync-source "test"
>> :candidates (directory-files "/zzzzzzzzzzzzzz"))
>> :buffer "*helm test*"))
>
> In this example, the error is not treated by the code you changed, but
> already when building the source - or do I miss something? I guess you
> wanted to use a candidates function?

Yes I sent the wrong one sorry (wrap it in a lambda).

>> (defun helm-test-error1 ()
>> (interactive)
>> (helm :sources (helm-build-sync-source "test"
>> :candidates "foo")
>> :buffer "*helm test*"))
>
> That example works as expected.
>
> Two more comments:
>
> 1. Can we give the variable "type-error" a better name (since it doesn't
> handle only type errors)? "notify-error" maybe?

Done.

> 2. For debugging purposes (getting a good backtrace), can we downgrade
> the `condition-case' in "helm-get-candidates" to not catch errors at all
> when debug-on-error -> t? It doesn't make sense to re-throw the error
> later, that loses the context of the error.

Done.

Thanks.

> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub*


-- 
Thierry

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> Done.
> [...]
> Done.

Looks good, thanks.

**Comment by michael-heerdegen** [comment]
Maybe we can moreover improve the generic error message.  E.g.
```
(helm :sources (helm-build-sync-source "test"
                 :candidates (lambda () 1))
      :buffer "*helm test*")
```
says: "In ‘test’ source: ‘(closure (t) nil 1)’ must either be a function, a variable or a list"

I guess we mean something like "either be a list, a variable bound to a list, or a function returning a list".

**Comment by michael-heerdegen** [comment]
Oh, and in the message: ```"In `%s' source: `%s' %s %s"```, I think the last format specifier should be `"%S"`, since `e` is typically not bound to a list.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Oh, and in the message: "In `%s' source: `%s' %s %s", I think the last
> format specifier should be "%S", since e is typically not bound to a
> list.

Thanks, done.

> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub*


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Maybe we can moreover improve the generic error message.

It's ok like this, the message is clear enough, this kind of details is
for a developer which is aware of what the candidates attr should do, 
(doc) not for end user.

> E.g.
>
> (helm :sources (helm-build-sync-source "test"
>                  :candidates (lambda () 1))
>       :buffer "*helm test*")
>
> says: "In ‘test’ source: ‘(closure (t) nil 1)’ must either be a function, a variable or a list"
>
> I guess we mean something like "either be a list, a variable bound to a list, or a function returning a list".
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub*


-- 
Thierry

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> It's ok like this, the message is clear enough, this kind of details
> is for a developer which is aware of what the candidates attr should
> do, (doc) not for end user.

OK, then I'm happy with everything now ;-)

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Thierry Volpiatto <notifications@github.com> writes:
>
>> It's ok like this, the message is clear enough, this kind of details
>> is for a developer which is aware of what the candidates attr should
>> do, (doc) not for end user.
>
> OK, then I'm happy with everything now ;-)

Well if you really think it is important to change the message, you can
of course (I know I am sometimes not enough rigorous).

Thanks.

> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub*


-- 
Thierry

**Comment by tmalsburg** [comment]
Thanks both.  I wasn't able to figure out why I didn't get an error message earlier but after Thierry's commits I do get an error.  That's incredibly useful!

**Comment by michael-heerdegen** [comment]
> Well if you really think it is important to change the message, you
> can of course (I know I am sometimes not enough rigorous).

Ok.  Was what I had suggested correct?: "...either be a list, a variable
bound to a list, or a function returning a list"?  Then I think I'll
make the change to avoid confusion.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Ok. Was what I had suggested correct?: "...either be a list, a variable
> bound to a list, or a function returning a list"?

Yes.

> Then I think I'll make the change to avoid confusion.

Thanks.

> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub*


-- 
Thierry

**Comment by michael-heerdegen** [comment]
Done.

I also fixed the `"%S"` usage: for the empty string we specify when `e -> nil`, this inserted two quotation marks instead of nothing.  I use `"%s"` again and `prin1-to-string` `e` explicitly.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Done.
>
> I also fixed the "%S" usage: for the empty string we specify when e ->
> nil, this inserted two quotation marks instead of nothing. I use "%s"
> again and prin1-to-string e explicitly.


Thanks.

> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub*


-- 
Thierry
