### ISSUE TITLE
 Odd behavior of forward slashes in helm-buffers-list patterns

### ISSUE THREAD

**Issue by CyberShadow** [emacs-helm/helm#1462]
When filtering the results of `helm-buffers-list` or `helm-for-files`, as soon as I type a forward slash, Helm seems to switch from filtering results as expected to showing *all* buffers:

![](http://dump.thecybershadow.net/d752c50030e999e2440939a67088eba1/recorded.gif)

It seems to highlight some letters in the buffers list, but I don't see any logic or pattern behind this behavior.

I'm not sure why this happens. Fuzzy matching is off as far as I can tell. If it is a feature, it seems to be an undocumented one - the documentation for `helm-buffers-list` only mentions handling of slashes appearing at the start of patterns.

I've [asked on emacs.stackexchange.com](http://emacs.stackexchange.com/q/21468/6695), but as I've gotten no answer, posting here in case it might be a bug.

**Comment by thierryvolpiatto** [comment]
Vladimir Panteleev <notifications@github.com> writes:

> When filtering the results of helm-buffers-list or helm-for-files, as
> soon as I type a forward slash, Helm seems to switch from filtering
> results as expected to
> showing all buffers:

A bug, should be fixed, thanks.

-- 
Thierry

**Comment by CyberShadow** [comment]
Thank you, it does indeed appear to be fixed.
