### ISSUE TITLE
helm-eshell-history size

### ISSUE THREAD

**Issue by fm4d** [emacs-helm/helm#1463]
I experience similar behaviour as described in https://github.com/emacs-helm/helm/issues/107 - with every use of helm-eshell-history the size of history is increased by a fixed ammount (128 in my case) which makes it painfully slow very soon.

**Comment by thierryvolpiatto** [comment]
fm4d <notifications@github.com> writes:

> I experience similar behaviour as described in #107 - with every use
> of helm-eshell-history the size of history is increased by a fixed
> ammount (128 in my case) which makes it painfully slow very soon.

Indeed, should be fixed now.

Thanks.

-- 
Thierry
