### ISSUE TITLE
helm-find-file with a url at point

### ISSUE THREAD

**Issue by plantarum** [emacs-helm/helm#1465]
Hi,

Not sure if this is a bug, or I just don't understand how helm-find-files i supposed to work. If point is on a url and I start `helm-find-files`, the url is inserted as the completion target. If I actually want to open a file, there's no obvious way to reject the url and start a regular file search. From reading the online help, it looks like I should be able to jump to the root directory by entering a `/`, or to start completing from home enter /~/. However, this text is appended to the url, which remains part of the completion target.

I can C-a C-k to kill the url, but shouldn't I also be able to use the 'quick pattern expansions' from the help page?

Thanks,

Tyler

**Comment by thierryvolpiatto** [comment]
Tyler Smith <notifications@github.com> writes:

> I can C-a C-k to kill the url,

You can skip the C-a as long as cursor is at eol.

> but shouldn't I also be able to use the 'quick pattern expansions'
> from the help page?

I wondered why I didn't allow this, but I soon I made the modification,
I realized that it created a lot of problems like expanding url to
default-directory among other annoyances.

So i think we can live with this by using e.g "C-k /./" which is very
easy and save me a lot of work for a few benefit.

I will add something explaining this in documentation.

Thanks.

>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub*


-- 
Thierry

**Comment by plantarum** [comment]
Ok, thanks for the explanation!
