### ISSUE TITLE
helm-etags throws timer error

### ISSUE THREAD

**Issue by mbuczko** [emacs-helm/helm#1471]
Hi, I'm getting strange timer problems while trying to narrow list of tags shown by ```helm-etags```:

    Error running timer: (invalid-regexp "Unmatched [ or [^")

It's being thrown with each key press. Helm updated today from melpa.

**Comment by thierryvolpiatto** [comment]
Michał Buczko <notifications@github.com> writes:

> Hi, I'm getting strange timer problems while trying to narrow list of tags shown by helm-etags:
>
> Error running timer: (invalid-regexp "Unmatched [ or [^")
>
> It's being thrown with each key press. Helm updated today from melpa.

Would be nice to have more infos on this (with only this I can do nothing):

What are your helm etags setting ?
What is the last git revision working ?
Is it possible to get the repository from where you ran helm etags ?
Can you reproduce error from ./emacs-helm.sh ?

-- 
Thierry

**Comment by mbuczko** [comment]
I hope it will help to track the problem down:

- etags are not customized at all. default configuration is used.
- helm version from melpa is 20160413.41 so I guess it's the newest git revision available
- I assume TAGS file is crucial thing for helm-tags, isn't it? I can reproduce this problem with TAGS as simple as this one: https://www.dropbox.com/s/8kpdkmjkgwv9ccq/TAGS
- yes, it's perfectly reproducible with emacs-helm.sh (and the attached TAGS)

**Comment by thierryvolpiatto** [comment]
Michał Buczko <notifications@github.com> writes:

> I hope it will help to track the problem down:
>
>   * etags are not customized at all. default configuration is used.
>   * helm version from melpa is 20160413.41 so I guess it's the newest git revision available
>   * I assume TAGS file is crucial thing for helm-tags, isn't it? I can reproduce this problem with TAGS as simple as this one: 
>     https://www.dropbox.com/s/8kpdkmjkgwv9ccq/TAGS
>   * yes, it's perfectly reproducible with emacs-helm.sh (and the attached TAGS)

Great, I should be able to fix the problem with your TAGS file, thanks.
Will do ASAP.

> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub*


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Should work now.

> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub*


-- 
Thierry

**Comment by mbuczko** [comment]
yup, works perfectly now. thanks!
