### ISSUE TITLE
helm-eshell-history with multiple eshells

### ISSUE THREAD

**Issue by fm4d** [emacs-helm/helm#1472]
`helm-eshell-history` behaves strange with multiple eshells, first call to helm-eshell-history will show history from last visited eshell and calls after that the proper history of current eshell.

Steps to reproduce: Create two different eshell instances, write few commands in first, then in second and do `helm-eshell-history` in first and the helm buffer will contain history of the second.

**Comment by thierryvolpiatto** [comment]
fm4d <notifications@github.com> writes:

> helm-eshell-history behaves strange with multiple eshells, first call
> to helm-eshell-history will show history from last visited eshell and
> calls after that the propert history of current eshell.
>
> Steps to reproduce: Create two different eshell instances, write few
> commands in first, then in second and do helm-eshell-history in first
> and the helm buffer will contain history of the second.

Should work now.

Behave like this:

Each new eshell buffer you open starts with the history found in
eshell-history-file-name, then each command you run go to the history of
its buffer (local), when exiting a buffer its history is saved to file.

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub*


-- 
Thierry

**Comment by fm4d** [comment]
Thanks for quick fix, I will try to test it as much as possible, it looks like I am the only one actually using this feature :D (which is awesome btw).

**Comment by fm4d** [comment]
Thanks for quick fix, I will try to test it as much as possible, it looks like I am the only one actually using this feature :D (which is awesome btw).
