### ISSUE TITLE
helm-grep-git-1 with an active region?

### ISSUE THREAD

**Issue by romanoaugusto88** [emacs-helm/helm#1473]
Hi. I'm trying to improve my `helm-grep-do-git-grep` experience, filling the input when there is an active region and tried the following with no success:

```elisp
(defun my/git-grep ()
  (interactive)
  (if (region-active-p)
      (helm-grep-git-1
       (projectile-project-root)
       (buffer-substring-no-properties (region-beginning) (region-end)))
    (helm-grep-git-1 (projectile-project-root) nil)))
```

How can I fix this?
Thx

**Comment by thierryvolpiatto** [comment]
`helm-grep-git-1` is not supporting this (i.e input).
Instead of trying to add the region as input, use `C-w` after launching `helm-grep-do-git-grep` which will be faster than marking a region before launching git-grep.

**Comment by romanoaugusto88** [comment]
I understand. Thx for reply.
But I found some issues using `C-w`. Say I have the following:
```c
int main() {
    return 0;
}
```
and I wanna grep by `int main()`. `C-w` won't fill the parenthesis in this case. Neither the curly bracket, if you want to.

And about speedness, it's not always true. With evil-mode or expand-region I can be faster:
Say I have

```go
len("Hello, sir! Grep me, please. Thank you")
```

To grep the whole quotation above, in evil I would use 3 keystrokes: `vi"`, in expand-region, 2 keystrokes. Against 7 times `C-w` keypressed.

**Comment by thierryvolpiatto** [comment]
Romano Augusto <notifications@github.com> writes:

> I understand. Thx for reply.
> But I found some issues using C-w. Say I have the following:
>
> int main() {
>     return 0;
> }
>
> and I wanna grep by int main(). C-w won't fill the parenthesis in this
> case. Neither the curly bracket, if you want to.

These are not issues C-w is using `forward-word` by default, you can
customize this with `helm-yank-text-at-point-function`.

> And about speedness, it's not always true. With evil-mode or
> expand-region I can be faster:

Sorry I don't know evil nor expand-region.

So to come back to what you asked, you can now do something like this
after updating helm:


    (defun my/git-grep (beg end)
      (interactive "r")
      (helm-grep-git-1
       (projectile-project-root)
       nil
       (and beg end (buffer-substring-no-properties beg end))))

Note that this example is using DEFAULT and not INPUT which is better
IMO, up to you to modify to use INPUT instead (add a nil).

Note also I tested with default-directory as I don't have
`projectile-project-root`.

Also you should use in your function the ALL argument (provided by a
prefix arg), actually your function is grepping only starting at
default-directory, with a prefix arg you could grep the whole repo
(upper if some).

> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub*


-- 
Thierry

**Comment by romanoaugusto88** [comment]
I've tried here, after Melpa's update, but it didn't work. :(
Even when I mark any region, the input is always empty.
Sorry, I didn't get the difference between DEFAULT and INPUT.

**Comment by romanoaugusto88** [comment]
I saw your last commit documenting it, and got the difference now.
I've tested only your code and forgot of mine. :dancer: 
Passing the region as INPUT instead of DEFAULT, works as I was expecting:

```elisp
(defun my/git-grep ()
  (interactive)
  (helm-grep-git-1
   (projectile-project-root)
   nil
   nil
   (if (region-active-p)
       (buffer-substring-no-properties (region-beginning) (region-end))
     nil)))
```

Didn't figure out why your example is broken, even passing the region as default.
BUT, thank you for your time and help!! :+1: :smile:

**Comment by xuchunyang** [comment]
To make the DEFAULT working, it looks like you have to add helm-source-grep to helm-sources-using-default-as-input, e.g.,

    (add-to-list 'helm-sources-using-default-as-input 'helm-source-grep)

Also, you should be able to know the difference between DEFAULT and INPUT after trying both of them.

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

> To make the DEFAULT working, it looks like you have to add
> helm-source-grep to helm-sources-using-default-as-input, e.g.,

Yes, it is the best way to use it but you can also insert it in with `M-n`.

> (add-to-list 'helm-sources-using-default-as-input 'helm-source-grep)
>
> Also, you should be able to know the difference between DEFAULT and INPUT after trying both of them.

If you add it to `helm-sources-using-default-as-input` the advantage is
your prompt still empty and you can start typing immediately something
else if the result is not what you expect.

> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub*


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Romano Augusto <notifications@github.com> writes:

> I saw your last commit documenting it, and got the difference now.
> I've tested only your code and forgot of mine. :da
> Passing the region as INPUT instead of DEFAULT, works as I was expecting:
>
> (defun my/git-grep ()
>   (interactive)
>   (helm-grep-git-1
>    (projectile-project-root)
>    nil
>    nil
>    (if (region-active-p)
>        (buffer-substring-no-properties (region-beginning) (region-end))
>      nil)))

It is more convenient to use the "r" spec of interactive but your code
is ok too.

> Didn't figure out why your example is broken,

It is not broken see previous post.

> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub*


-- 
Thierry
