### ISSUE TITLE
helm-ff-default-directory gets stuck in a non-nil value

### ISSUE THREAD

**Issue by vspinu** [emacs-helm/helm#1474]
I don't have a reproducible example for this but maybe it rings a bell. 

Somtimes `helm-do-grep-ag` suddenly starts opening files in a wrong directory. I tracked it down to to `helm-ff-default-directory`. That variable is commonly nil, but something sets it to global value and gets stuck there. The problem affects `helm-do-grep-ag` but not `helm-do-grep-1`. I am pretty sure this is not my configuration, but it might be some of the helm- extensions that I use. I will report if I could narrow it down.

Any ideas based just on this info?

This is helm `20160416.906`.

**Comment by thierryvolpiatto** [comment]
Vitalie Spinu <notifications@github.com> writes:

> I don't have a reproducible example for this but maybe it rings a bell.
>
> Somtimes helm-do-grep-ag suddenly starts opening files in a wrong
> directory. I tracked it down to to helm-ff-default-directory.

helm-do-grep-ag is not using helm-ff-default-directory at all AFAIK.

> That variable is commonly nil, but something sets it to global value
> and gets stuck there. The problem affects helm-do-grep-ag but not
> helm-do-grep-1. I am pretty sure this is not my configuration,

To be sure try to reproduce from emacs-helm.sh

> but it might be some of the helm- extensions that I use. I will report
> if I could narrow it down.
>
> Any ideas based just on this info?

Perhaps something (in config or external package) is trying to use
wrongly helm-grep-ag from the functions used in helm-files.el and
reserved from an usage from hff ?

Anyway I can't reproduce this, I use helm-grep-ag always either from
helm-do-grep-ag and from hff.

> This is helm 20160416.906.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub*


-- 
Thierry

**Comment by vspinu** [comment]
> helm-do-grep-ag is not using helm-ff-default-directory at all AFAIK.

I set it to nil and everything resumed to normal. So there must be something there.

> Anyway I can't reproduce this,

Neither do I. It happened twice so far but it's extremely hard to pinpoint. Will keep an eye and will be back if it happens again.

Thanks.
