### ISSUE TITLE
helm-find-files inside eshell

### ISSUE THREAD

**Issue by alxest** [emacs-helm/helm#1475]
I am using helm version "20160409.357", emacs version "GNU Emacs 24.3.1"
When I use helm-find-files inside eshell, it tracks current directory without last "/"
For example, when I call "helm-find-files" in "/A/B/", I expect to see list of files inside "/A/B/", but it just shows single directory "/A/B".
I have been using somewhat old version of helm until lately, and its behavior was the former, but it changed to latter after I updated to the forementioned version.
Is this intended behavior?

In the code, inside "helm-find-files" function, "default-input" variable is set with "/A/B".
When I replace "default-input" to "nil", it works as I expected.
~~~
(defun helm-find-files (arg)
  "Preconfigured `helm' for helm implementation of `find-file'.
Called with a prefix arg show history if some.
Don't call it from programs, use `helm-find-files-1' instead.
This is the starting point for nearly all actions you can do on files."
  (interactive "P")
  (let* ((hist            (and arg helm-ff-history (helm-find-files-history)))
         ;; [[[[REPLACED HERE]]]]
         ;; (default-input   (or hist (helm-find-files-initial-input)))
         (default-input   nil)
         (input           (cond ((and (eq major-mode 'org-agenda-mode)
                                      org-directory
                                      (not default-input))
                                 (expand-file-name org-directory))
                                ((and (eq major-mode 'dired-mode) default-input)
                                 (file-name-directory default-input))
                                ((and (not (string= default-input ""))
                                      default-input))
                                (t (expand-file-name (helm-current-directory)))))
         (input-as-presel (null (nth 0 (file-attributes input))))
         (presel          (helm-aif (or hist
                                        (and input-as-presel input)
                                        (buffer-file-name (current-buffer))
                                        (and (eq major-mode 'dired-mode)
                                             default-input))
                              (if helm-ff-transformer-show-only-basename
                                  (helm-basename it) it))))
    (set-text-properties 0 (length input) nil input)
    (helm-find-files-1 input (and presel (null helm-ff-no-preselect)
                                  (concat "^" (regexp-quote presel))))))
~~~

**Comment by thierryvolpiatto** [comment]
YoungJu Song <notifications@github.com> writes:

> I am using helm version "20160409.357".
> When I use helm-find-files inside eshell, it tracks current directory
> without last "/" For example, when I call "helm-find-files" in
> "/A/B/", I expect to see list of files inside "/A/B/", but it just
> shows single directory "/A/B".  I have been using somewhat old version
> of helm until lately, and its behavior was the former, but it changed
> to latter after I updated to the forementioned version.

I can't reproduce.

Perhaps you changed also something else in your config or installed
something else affecting it ?

Please try to reproduce from emacs-helm.sh script.

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub*


-- 
Thierry
