### ISSUE TITLE
quitting with "C-g"

### ISSUE THREAD

**Issue by alxest** [emacs-helm/helm#1476]
I am using helm version "20160409.357", emacs version "GNU Emacs 24.3.1"
When I type "C-g" during "helm-find-files" or etc, it does not exit directly and requires 1-2 more types.
It seems first 1-2 keys are bound to normal "keyboard-quit", and the last one is bound to "helm-keyboard-quit" and then it exits.
Is this normal behavior? I want to quit with one type, what should I do?
Thanks a lot.

**Comment by thierryvolpiatto** [comment]
YoungJu Song <notifications@github.com> writes:

> I am using helm version "20160409.357", emacs version "GNU Emacs
> 24.3.1" When I type "C-g" during "helm-find-files" or etc, it does not
> exit directly and requires 1-2 more types.  It seems first 1-2 keys
> are bound to normal "keyboard-quit", and the last one is bound to
> "helm-keyboard-quit" and then it exits.  Is this normal behavior? I
> want to quit with one type, what should I do?

Sorry but here is the same, can't reproduce.
Perhaps you should update your emacs to 24.5 ?

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub*


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
And also like always, even with 24.3 try from emacs-helm.sh.

Thanks.

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub*


-- 
Thierry

**Comment by xiongtx** [comment]
Information on using `emacs-helm.sh` to report bugs is available on the [Wiki](https://github.com/emacs-helm/helm/wiki/Bugs).

Please raise an issue if the Wiki is unclear or missing information, so other users can benefit.
