### ISSUE TITLE
Getting slot value for Helm sync source

### ISSUE THREAD

**Issue by xiongtx** [emacs-helm/helm#1477]
I'm confused as to why the following does not work:

```emacs-lisp
(slot-value (helm-build-sync-source "Test"
			  :candidates '(1 2 3 4 5))
			'name)
```

The source created above should be an instance of `helm-source-sync`, which is a subclass of `helm-source`. Yet I get the error:

> (wrong-type-argument (or eieio-object-p class-p) ((name . "Test") ...

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> I'm confused as to why the following does not work:
>
> (slot-value (helm-build-sync-source "Test"
>               :candidates '(1 2 3 4 5))
>             'name)

Use assoc.

> The source created above should be an instance of helm-source-sync,
> which is a subclass of helm-source.

It is not, helm-build-sync-source is returning an alist.

    (helm-build-sync-source "Test"
      :candidates '(1 2 3 4 5))

    =>

    ((name . "Test")
     (candidates 1 2 3 4 5)
     (action . identity)
     (filtered-candidate-transformer helm-fuzzy-highlight-matches)
     (match helm-mm-exact-match helm-mm-match)
     (header-line . "C-j: Do Nothing (keeping session)")
     (dont-plug helm-compile-source--multi-match helm-compile-source--persistent-help helm-compile-source--migemo)
     (matchplugin))

> Yet I get the error:
>
>     (wrong-type-argument (or eieio-object-p class-p) ((name . "Test") ...

Read carefully the error message, you see that indeed 
((name . "Test") [...] is not a eieio-object.
 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub*


-- 
Thierry

**Comment by xiongtx** [comment]
OK, but where do the EIEIO objects come into play then? Where do they fit into Helm?

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> OK, but where do the EIEIO objects come into play then?

They are used only temporarily to build source but not kept
(They may be used directly in the future).

> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub*


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> Where do they fit into Helm?

Note also that beside creating the source, they can be used BEFORE
creating the source to modify the eieio instance (the eieio-object)
which is used to build the source, this is done with defmethod
`helm--setup-source` internally and can be done at user level with
`helm-setup-user-source`.

> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub*


-- 
Thierry

**Comment by xiongtx** [comment]
Interesting. So would something like the following be most appropriate?

```emacs-lisp
(defun helm-source-name (source)
  "Name of Helm source (as a string)."
  (cdr (assoc 'name source)))
```

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> Interesting. So would something like the following be most appropriate?
>
> (defun helm-source-name (source)
>   "Name of Helm source (as a string)."
>   (cdr (assoc 'name source)))

Yes, sure, we use generally assoc-default though, but it is the same,
just a detail.
Of course to use this you have to know SOURCE or extract it when you are
inside a helm session, use for this `helm-get-current-source`.
Note that `helm-get-current-source` will return nil if helm-buffer is
empty.

> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub*


-- 
Thierry

**Comment by xiongtx** [comment]
Alright, that answers my question, thanks.
