### ISSUE TITLE
Jump to one source among many

### ISSUE THREAD

**Issue by xiongtx** [emacs-helm/helm#1478]
I'm working on creating a Helm session in which the sources are Clojure namespaces and the candidates are symbols in the namespaces. Thus, the number of sources can be fairly large (dozens, maybe even hundreds?). In this scenario, what is the best way to jump to a particular source?

I know about `helm-next-source` and `helm-previous-source`, and they work fine when the number of sources is small (e.g. for `helm-mini`). When the number of sources is very large, however, they are impractical.

Some options I've considered:

- Include the namespace as part of the candidate (e.g. `clojure.core/reduce` instead of just `reduce`), thereby allowing narrowing.
  - This repeats a lot of information, making the screen look cluttered.
- First, query the user (optionally) for a namespace using `completing-read` or another Helm session.
  - This creates a two-step process in the "wrong order", forcing the user to think of which namespace they want ahead of time (which, in my view, goes against the philosophy of incremental completion).

Ideally, there'd be a key binding in a Helm session that brings up another Helm session with sources' names as candidates; when the user selects a source, it goes back to that source in the previous Helm session.

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> In this scenario, what is the best way to jump to a particular source?

> Ideally, there'd be a key binding in a Helm session that brings up
> another Helm session with sources' names as candidates; when the user
> selects a source, it goes back to that source in the previous Helm
> session.

IIUC what you want to do I see maybe two way to achieve this:

- Use :allow-nest

Have a look at helm-find-files + helm-ff-file-name-history, you can try
it from an helm-find-files session and C-c h.
It is not exactly the same as what you want to do but from this example,
I guess you can achive what you want (use :allow-nest in your second
helm-session).

- Use filter sources

Also what may help is having a look at `helm-multi-files`, don't know if
you already tried it, you can go to one source from other sources and
come back to original sources, it is the same as helm-for-files, but
launch locate only when needed and come back with same binding (C-c p).

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub*


-- 
Thierry

**Comment by xiongtx** [comment]
I think `:allow-nest` may work, but I'm running into some issues.

The steps are as follows:

1. Get first Helm session (`Session 1`) with many sources
2. Bring up second Helm session (`Session 2`) to select source by name
3. Go back to `Session 1`, and go to source that was selected in `Session 2`.

However, the "go to source" part works inconsistently. I *think* it's a timing issue: there is a period between Steps 2 and 3 during which Helm is not "alive", and sometimes the "go to source" is called during this "dead phase".

Here is the function for `Session 1`:

```emacs-lisp
(defun helm-cider-apropos (&optional source)
  "Helm interface to CIDER apropos.

Each Helm source is a Clojure namespace, and candidates are
symbols in the namespace.

Optional arg SOURCE goes to source.

Set the `helm-cider-apropos-follow' variable to true to turn on
`helm-follow-mode' for all sources."
  (interactive)
  (let ((old-key (lookup-key helm-map (read-kbd-macro "C-c n"))))
    (with-helm-temp-hook 'helm-after-initialize-hook
      (define-key helm-map (kbd "C-c n") #'helm-cider-apropos-ns))
    (with-helm-temp-hook 'helm-after-update-hook
      (with-helm-buffer
        (when source
          (helm-goto-source source)
          (helm-next-line))))
    (unwind-protect
        (helm :buffer "*Helm CIDER Apropos*"
              :candidate-number-limit 9999
              :preselect (cider-symbol-at-point t)
              :sources (helm-cider--apropos-sources))
      (define-key helm-map (kbd "C-c n") old-key))))	  
```

And for `Session 2`:

```emacs-lisp
(defun helm-cider--apropos-ns-source (&optional excluded-ns)
  "Helm source of namespaces.

Namespaces in EXCLUDED-NS are excluded.  If not provided,
`helm-cider-apropos-excluded-ns' is used."
  (helm-build-sync-source "Clojure Namespaces"
    :action '(("Search in namespace" . helm-cider-apropos)
              ("Find definition" . (lambda (ns)
                                     (cider-find-ns nil ns)))
              ("Set REPL namespace" . cider-repl-set-ns))
    :candidates (cl-loop for ns in (cider-sync-request:ns-list)
                         unless (helm-cider--excluded-ns-p ns excluded-ns)
                         collect (cider-propertize ns 'ns) into all
                         finally (return (sort all #'string<)))
    :nomark t
    :volatile t))

(defun helm-cider-apropos-ns ()
  "Choose Clojure namespace to call Helm CIDER apropos on."
  (interactive)
  (helm :allow-nest t
        :buffer "*Helm Clojure Namespaces*"
        :candidate-number-limit 9999
        :sources (helm-cider--apropos-ns-source)))
```

The details probably don't matter much; the thing I'm wondering is whether `helm-after-update-hook` is the right place to put the "go to source" logic. `helm-after-initialize-hook` certainly isn't, as I've discovered.

I don't see any sort of `helm-after-sources-loaded-hook`, which is what I (think I) need.

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> I think :allow-nest may work, but I'm running into some issues.
>
> The steps are as follows:
>
>  1. Get first Helm session (Session 1) with many sources
>  2. Bring up second Helm session (Session 2) to select source by name
>  3. Go back to Session 1, and go to source that was selected in Session 2.

When going from 1 to 2 you don't have to launch
with-helm-after-update-hook.
When going from 2 to 1 (3) you HAVE to use with-helm-after-update-hook.
Actually I guess helm is confused because in step 1 you use an
with-helm-after-update-hook which is not consumed, and you try to reuse it in
step 2 without having consumed the first.

> Here is the function for Session 1:
>
> (defun helm-cider-apropos (&optional source)
>   "Helm interface to CIDER apropos.
>
> Each Helm source is a Clojure namespace, and candidates are
> symbols in the namespace.
>
> Optional arg SOURCE goes to source.
>
> Set the `helm-cider-apropos-follow' variable to true to turn on
> `helm-follow-mode' for all sources."
>   (interactive)
>   (let ((old-key (lookup-key helm-map (read-kbd-macro "C-c n"))))
>     (with-helm-temp-hook 'helm-after-initialize-hook
>       (define-key helm-map (kbd "C-c n") #'helm-cider-apropos-ns))
>     (with-helm-temp-hook 'helm-after-update-hook
>       (with-helm-buffer
>         (when source
>           (helm-goto-source source)
>           (helm-next-line))))

Try instead

(when source
  (with-helm-after-update-hook
    (with-helm-buffer
      (helm-goto-source source)
      (helm-next-line))))

But apart this I wonder if your approach is good or perhaps
I misunderstand what you want to do:

>  1. Get first Helm session (Session 1) with many sources
>  2. Bring up second Helm session (Session 2) to select source by name
>  3. Go back to Session 1, and go to source that was selected in Session 2.

Why are you popping up session 1 and then go to session 2 to then come
back to 1 ?

Why don't you start directly from session 2 and switch to session 1 with
only the source you need once you have choosen it ?
You could do that with helm-set-sources and helm-set-source-filter:

Start with this source (SOURCE1):

SOURCE1
source-name1
source-name2
source-name3
etc...

Use a key which will be used to switch to the source you want and to
come back to this initial list of source.
Use this key now to switch say to source-name2:

SOURCE-NAME2
candidate1
candidate2
candidate3
etc...

If you don't find what you want in source-name2 or change your mind, use
the key to switch back to SOURCE1 and select another source-name.

> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub*


-- 
Thierry

**Comment by xiongtx** [comment]
Great, the snippet you provided seems to work well. I was quite certain that `helm-after-update-hook` is the only reasonable hook to use, but it's good to have confirmation.

```emacs-lisp
(when source
  (with-helm-after-update-hook
    (with-helm-buffer
      (helm-goto-source source)
      (helm-next-line))))
```
You're absolutely correct regarding the `Session 1` -> `Session 2` -> `Session 3 (1)`. I was not cleaning up the Helm session properly.

The original idea as that `Session 2` would always start from `Session 1`, but now I think there is no reason for that to be the case. `Session 1` and `Session 2` can invoke each other as equals. The user can choose whether to start with all symbols or to select a namespace first.
