### ISSUE TITLE
"session" source broken in recent versions

### ISSUE THREAD

**Issue by glyph** [emacs-helm/helm#1479]
When using `helm-C-x-b`, I get this:

```
In `Session' source: `#[0 \301\302\303\304""\207 [session-file-alist cl-delete-if-not #[257 \301"\206
\302!\207 [helm-tramp-file-name-regexp string-match file-exists-p] 4 

(fn F)] mapcar car] 5 

(fn)]' 
 (void-variable session-file-alist)
"Beep."
In `Session' source: `#[0 \301\302\303\304""\207 [session-file-alist cl-delete-if-not #[257 \301"\206
\302!\207 [helm-tramp-file-name-regexp string-match file-exists-p] 4 

(fn F)] mapcar car] 5 

(fn)]' 
 (void-variable session-file-alist)
```

**Comment by glyph** [comment]
(helm package version 20160419.635 from melpa)

**Comment by glyph** [comment]
I do not have `emacs-session` installed, which is possibly the problem?

**Comment by glyph** [comment]
`(setq session-file-alist nil)` works around the problem, so perhaps that's what the `defvar` in `helm-files.el` should be doing?

**Comment by thierryvolpiatto** [comment]
Glyph <notifications@github.com> writes:

> When using helm-C-x-b, I get this:

I don't know what helm-C-x-b is.

>  (void-variable session-file-alist)

It just seems you are using helm for session and session is not
installed.

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub*


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Glyph <notifications@github.com> writes:

> I do not have emacs-session installed, which is possibly the problem?

Of course.

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub*


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Glyph <notifications@github.com> writes:

> (setq session-file-alist nil) works around the problem, so perhaps
> that's what the defvar in helm-files.el should be doing?

In last helm versions, we are raising error when the candidate function
fail, it is why you have an error.
The benefit is that you discovered that you are using in your helm-c-x-b
function a source which is unuseful because emacs-session is not
installled.

I could check if the variable is bound and fail silently, but raising an error
is better IMO.

So if you need emacs-session, install it, otherwise just remove the
source from your customized function.

>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub*


-- 
Thierry

**Comment by glyph** [comment]
@thierryvolpiatto -

> I don't know what helm-C-x-b is.

It's a part of helm-cmd-t; I've filed a bug there and linked this one. Perhaps the bug is on their side, but it is the change in helm itself that the error started happening.

**Comment by thierryvolpiatto** [comment]
See #1460

**Comment by thierryvolpiatto** [comment]
>Perhaps the bug is on their side, but it is the change in helm itself that the error started happening.

The error is since a long time here in your side but until now helm was failing silently.
As I said above, we can fail silently like this:

```elisp
(defvar helm-source-session
  (helm-build-sync-source "Session"
    :candidates (lambda ()
                  (when (boundp 'session-file-alist)
                    (cl-delete-if-not (lambda (f)
                                        (or (string-match helm-tramp-file-name-regexp f)
                                            (file-exists-p f)))
                                      (mapcar 'car session-file-alist))))
    :keymap helm-generic-files-map
    :help-message helm-generic-file-help-message
    :action 'helm-type-file-actions)
  "File list from emacs-session.")
```
But you have better time checking if source are needed or not in helm-cmd-t.
