### ISSUE TITLE
helm-files: option to have RET descend into directory

### ISSUE THREAD

**Issue by bmalehorn** [emacs-helm/helm#1480]
In `ido-mode`, `RET` on a file opens it, while `RET` on a directory descends into that directory. In helm, `RET` on a file opens it, `RET` on a directory opens it in dired, and `C-j` on a directory descends into it.

That means I need to alternate between `C-j` and `RET` to open a file every time, which is still awkward after months of use. Worse still, I need to put up with this behavior if I want to use helm for literally anything else.

So, it would be nice if there was an option:

```
    (setq helm-files-open-directories-in-dired t)
```

So you could get the more logical behavior of `RET` opening the folder.

I've tried making the change myself, but it seems helm is structured in a way that assumes `RET` means "I'm done deciding, now give me the result".

**Comment by thierryvolpiatto** [comment]
Brian Malehorn <notifications@github.com> writes:

> In ido-mode, RET on a file opens it, while RET on a directory descends
> into that directory. In helm, RET on a file opens it, RET on a
> directory opens it in dired, and C-j on a directory descends into it.

Yes, and this will not change, ido is ido and helm is helm, sorry but I
wont fix this.

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub*


-- 
Thierry

**Comment by xuchunyang** [comment]
> I've tried making the change myself, but it seems helm is structured in a way that assumes RET means "I'm done deciding, now give me the result".

Hmm, I guess you are right. But `RET` still is a normal key binding so you can bind it to any command you want, for example, to make `RET` in `helm-find-files` has the behaviour that you want:

```elisp
(defun chunyang-helm-maybe-exit-minibuffer ()
  (interactive)
  (if (file-directory-p (helm-get-selection))
      (call-interactively (key-binding "\C-j"))
    (helm-maybe-exit-minibuffer)))

(define-key helm-find-files-map "\r" #'chunyang-helm-maybe-exit-minibuffer)
```
you can also bind this new command to `RET` in `helm-read-file-map` if you want it in other places.

**Comment by bmalehorn** [comment]
@xuchunyang, thanks a lot! That's exactly the functionality I wanted. I just wasn't aware of `helm-get-selection`.
