### ISSUE TITLE
Feature Request: Ability to refresh man pages

### ISSUE THREAD

**Issue by nmaludy** [emacs-helm/helm#1482]
Currently the helm-man-woman completion list is populated on init. If a user installs a new man page after emacs has started there is no way to refresh this list of man pages in the helm-man-woman completion list. For helm-man-woman to recognize the new man page emacs must be restarted.

It would be great if there was a function to refresh the man page list without restarting emacs.

**Comment by xuchunyang** [comment]
Does helm-man-woman with a prefix argument work for you?

**Comment by thierryvolpiatto** [comment]
It does here with a prefix arg.
