### ISSUE TITLE
Missing matches in helm-org-agenda-files-headings

### ISSUE THREAD

**Issue by simonthum** [emacs-helm/helm#1484]
I just noticed that in helm (package version 20151024.2233) some Org headings are being missed.

Some investigation revealed that some headings were wrapped, and the match does not extend beyond that wrapping point. Thus, I can potentially locate the missed heading when matching something close to the beginning, or I can increase the emacs window size beforehand.

The proper fix, I guess, is to match against the full headlines. I didn't update yet but I checked the logs and did not see an obvious fix.

**Comment by thierryvolpiatto** [comment]
simonthum <notifications@github.com> writes:

> I just noticed that in helm (package version 20151024.2233) some Org
> headings are being missed.
>
> Some investigation revealed that some headings were wrapped, and the
> match does not extend beyond that wrapping point. Thus, I can
> potentially locate the missed heading when matching something close to
> the beginning, or I can increase the emacs window size beforehand.
>
> The proper fix, I guess, is to match against the full headlines. I
> didn't update yet but I checked the logs and did not see an obvious
> fix.

First of all update your helm copy.
Then it would be great if you provide a recipe (with possibly a sample
org file) describing exactly what you are doing and what you want to
match so that I can reproduce.

Thanks.

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub*


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Also look at  `helm-org-truncate-lines`, you have perhaps very long headers and you try to match against their end.

**Comment by simonthum** [comment]
Well I just updated, but I'll hardly be able to report back unless you have an idea what might be wrong there:

````
Debugger entered--Lisp error: (void-function helm-file-name-sans-extension)
  helm-file-name-sans-extension("ada-mode.info.bz2")
  helm-get-info-files()
  #[0 "\300 \207" [helm-get-info-files] 1 "\n\n(fn)"]()
  funcall(#[0 "\300 \207" [helm-get-info-files] 1 "\n\n(fn)"])
  eval((funcall (function #[0 "\300 \207" [helm-get-info-files] 1 "\n\n(fn)"])))
  byte-code("\303\304N\211\203
```

**Comment by simonthum** [comment]
Sorry, the bytecode seems to mess up the clipboard.

```
Debugger entered--Lisp error: (void-function helm-file-name-sans-extension)
  helm-file-name-sans-extension("ada-mode.info.bz2")
  helm-get-info-files()
  #[0 "\300 \207" [helm-get-info-files] 1 "\n\n(fn)"]()
  funcall(#[0 "\300 \207" [helm-get-info-files] 1 "\n\n(fn)"])
  eval((funcall (function #[0 "\300 \207" [helm-get-info-files] 1 "\n\n(fn)"])))
  byte-code("\303\304N\211\203
  custom-initialize-reset(helm-default-info-index-list (funcall (function #[0 "\300 \207" [helm-get-info-files] 1 "\n\n(fn)"])))
  custom-declare-variable(helm-default-info-index-list (funcall (function #[0 "\300 \207" [helm-get-info-files] 1 "\n\n(fn)"])) "Info files to search in with `helm-info'." :group helm-info :type (repeat (choice string)) :set helm-info-index-set)
  byte-code("\300\301\302\303\304DD\305\306\307\310\311\312\313&	\207" [custom-declare-variable helm-default-info-index-list funcall function #[0 "\300 \207" [helm-get-info-files] 1 "\n\n(fn)"] "Info files to search in with `helm-info'." :group helm-info :type (repeat (choice string)) :set helm-info-index-set] 10)
  require(helm-info)
  eval-buffer(#<buffer  *load*-303543> nil "/home/simon/.emacs.d/elpa/helm-20160425.958/helm-bookmark.el" nil t)  ; Reading at buffer position 958
  load-with-code-conversion("/home/simon/.emacs.d/elpa/helm-20160425.958/helm-bookmark.el" "/home/simon/.emacs.d/elpa/helm-20160425.958/helm-bookmark.el" nil t)
  require(helm-bookmark)
  eval-buffer(#<buffer  *load*-611182> nil "/home/simon/.emacs.d/elpa/helm-20160425.958/helm-files.el" nil t)  ; Reading at buffer position 1007
  load-with-code-conversion("/home/simon/.emacs.d/elpa/helm-20160425.958/helm-files.el" "/home/simon/.emacs.d/elpa/helm-20160425.958/helm-files.el" nil t)
  require(helm-files)
  eval-buffer(#<buffer  *load*-290870> nil "/home/simon/.emacs.d/elpa/helm-20160425.958/helm-mode.el" nil t)  ; Reading at buffer position 872
  load-with-code-conversion("/home/simon/.emacs.d/elpa/helm-20160425.958/helm-mode.el" "/home/simon/.emacs.d/elpa/helm-20160425.958/helm-mode.el" nil t)
  (helm-mode)
  (progn (helm-mode) (define-key global-map "j" (quote helm-org-agenda-files-headings)))
  (if (require (quote helm-org) nil t) (progn (helm-mode) (define-key global-map "j" (quote helm-org-agenda-files-headings))))
  eval-buffer(#<buffer  *load*-334102> nil "/home/simon/org/scripts/org-mode.el" nil t)  ; Reading at buffer position 415
  load-with-code-conversion("/home/simon/org/scripts/org-mode.el" "/home/simon/org/scripts/org-mode.el" nil nil)
  load("~/org/scripts/org-mode")
  eval-buffer(#<buffer  *load*> nil "/home/simon/.emacs.d/init.el" nil t)  ; Reading at buffer position 575
  load-with-code-conversion("/home/simon/.emacs.d/init.el" "/home/simon/.emacs.d/init.el" t t)
  load("/home/simon/.emacs.d/init" t t)
  #[0 "\205\262
```

**Comment by simonthum** [comment]
Ok, it was a stale helm-core sitting around.

Well, it's OK now because org-helm no longer concatenates headings (toplevel / sublevel / item) but would only show item in this case. I liked this behaviour, and will try to restablish it, but this will bring back long lines.

In any case, I consider it a bug that truncation is the default behaviour. Should one ever want to miss matches late in the headline(s), I'm sure he or she can enable that flag. What really worries me is that the matching depends on UI niceties like truncation, which in turn depends on window width,  a slightly surprising match predictor.

**Comment by thierryvolpiatto** [comment]
simonthum <notifications@github.com> writes:

> Ok, it was a stale helm-core sitting around.
>
> Well, it's OK now because org-helm no longer concatenates headings
> (toplevel / sublevel / item) but would only show item in this case. I
> liked this behaviour, and will try to restablish it, but this will
> bring back long lines.
>
> In any case, I consider it a bug that truncation is the default
> behaviour. Should one ever want to miss matches late in the
> headline(s), I'm sure he or she can enable that flag. What really
> worries me is that the matching depends on UI niceties like
> truncation, which in turn depends on window width, a slightly
> surprising match predictor.

Perhaps.

But consider thinking at why do you have so long headers in your org
files, why some people write their life in the Subject header of an
email etc...

Personally headers in my org files (and lines also) don't exeed 70
columns.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
simonthum <notifications@github.com> writes:

> Ok, it was a stale helm-core sitting around.
>
> Well, it's OK now because org-helm no longer concatenates headings
> (toplevel / sublevel / item) but would only show item in this case. I
> liked this behaviour, and will try to restablish it, but this will
> bring back long lines.
>
> In any case, I consider it a bug that truncation is the default
> behaviour. Should one ever want to miss matches late in the
> headline(s), I'm sure he or she can enable that flag.

You can have truncation and matching the end of a header, we have a
match function for this, this can be demonstrated in a small org buffer
with very long lines.
Match (one of) is done on `helm-real-display`.

> What really worries me is that the matching depends on UI niceties
> like truncation, which in turn depends on window width, a slightly
> surprising match predictor.

Match is _not_ behaving on this.

> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub*


-- 
Thierry

**Comment by simonthum** [comment]
Thierry, I'm not sure what you mean. In the version that had the bug matching must have worked against the (potentially truncated) display string. The question is what is it now - does helm match against the truncated string or the "real" one by default? If it's the "real" one this bug does no longer exist.

My use-case does not depend on long headings (they're typically below 20 chars of text), but that is the problem, in a way. I have tons of not-overly-descriptive headings like "misc" or "resources" but I would like to pinpoint them by matching to the headlines or org-file names that contain them. For that I prefer to see see the containing headings and the Org file, which it seems was the default in the 2015 package (I hope it's still possible). The point is that headings need context, at least in the way I use them.

So it's only the concatenation of 5 level headings that gets messy and does/did not match properly. Feel free to close the bug if this should work now. I haven't gotten to that point in the new version.

**Comment by thierryvolpiatto** [comment]
simonthum <notifications@github.com> writes:

> Thierry, I'm not sure what you mean. In the version that had the bug
> matching must have worked against the (potentially truncated) display
> string. The question is what is it now - does helm match against the
> truncated string or the "real" one by default?

The real one. Sorry for confusion.

> If it's the "real" one this bug does no longer exist.

I think so, I just tried with `helm-org-format-outline-path` of a sample
org file with very long headers and I was able to match end of headers,
have a try.

-- 
Thierry

**Comment by simonthum** [comment]
Hi, I just found those settings and it all works well, apparently. Very well indeed - it's much faster too.

Sorry for the noise! It was all fixed ahead of time.. I get very nervous when something in Org doesn't work predictably, as it grew very important to my daily work flows.
