### ISSUE TITLE
helm make exists buffer(tab) invisible

### ISSUE THREAD

**Issue by muyinliu** [emacs-helm/helm#1485]
Sometimes after using helm-M-x, helm make exists buffer(tab) invisible, like this:
![emacs helm make buffer invisible](https://cloud.githubusercontent.com/assets/3318872/14803912/b4b061d8-0b90-11e6-9c62-4c731195d546.gif)
The buffer(tab) `*scratch*`  is invisible after cancel helm-M-x. I can find it back with helm-buffer-list but it's not convenient.
How to prevent this?
Note: Aquamacs with tabbar.

**Comment by thierryvolpiatto** [comment]
muyinliu <notifications@github.com> writes:

> Sometimes after using helm-M-x, helm make exists buffer(tab)
> invisible, like this: emacs he The buffer(tab) *scra�tch* is invisible
> after cancel helm-M-x. I can find it back with helm-buffer-list but
> it's not convenient.  How to prevent this?

I have no idea, I will try to install tabbar and reproduce, maybe it is
a bug in tabbar, dunno, will see.

> Note: Aquamacs with tabbar.

I think I can try tabbar but I have no way to try aquamacs.

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub*


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Thierry Volpiatto <thierry.volpiatto@gmail.com> writes:

> muyinliu <notifications@github.com> writes:
>
>> Sometimes after using helm-M-x, helm make exists buffer(tab)
>> invisible, like this: emacs he The buffer(tab) *scra�tch* is invisible
>> after cancel helm-M-x. I can find it back with helm-buffer-list but
>> it's not convenient.  How to prevent this?
>
> I have no idea, I will try to install tabbar and reproduce, maybe it is
> a bug in tabbar, dunno, will see.

Seems it is a problem only when switching to slime, i.e when displaying
the slime buffer.
It can happen by switching directly to this buffer without using helm,
so the problem is IMO with slime but not with tabbar or helm, IOW it
seems slime doesn't support tabbar.

>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly or view it on GitHub*


-- 
Thierry

**Comment by muyinliu** [comment]
No, I am sure it is NOT about SLIME:
![emacs helm make buffer invisible2](https://cloud.githubusercontent.com/assets/3318872/14807399/f5b6968e-0bae-11e6-9040-dd9ba12969dd.gif)

**Comment by muyinliu** [comment]
And without helm, buffers work fine, never became invisible suddenly:
![emacs helm make buffer invisible3](https://cloud.githubusercontent.com/assets/3318872/14807560/1c11528c-0bb0-11e6-8232-7bab883d8d32.gif)

**Comment by thierryvolpiatto** [comment]
muyinliu <notifications@github.com> writes:

> No, I am sure it is NOT about SLIME:

Sorry but I can't reproduce this here (GNU Linux).
Please start with a minimal emacs (emacs-helm.sh).

The tabs disappear only when switching to a whole slime buffer (one
window), otherwise tha tabs are always here.

As I said IMO helm is not involved in this.

> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub*


-- 
Thierry

**Comment by muyinliu** [comment]
> The tabs disappear only when switching to a whole slime buffer (one window), otherwise tha tabs are always here.

That's NOT true. [Look at this](https://github.com/emacs-helm/helm/issues/1485#issuecomment-214616995)

**Comment by thierryvolpiatto** [comment]
That's not true on your side, but it is true on mine.
If you don't want to start from emacs-helm.sh and try to debug this on your side, I can do nothing for you, sorry.

To summarize:
I can't replicate your bug, helm+tabbar on a GNU Linux box is perfectly compatible.

**Comment by muyinliu** [comment]
I will try emacs-helm.sh later. Please do wait for my reply. Thank you.
