### ISSUE TITLE
[feature request] enhanced helm-find-file which like ido-find-file.

### ISSUE THREAD

**Issue by zw963** [emacs-helm/helm#1488]
I still not give up ido completely. at least for me, I consider ido-find-file are not equivalent in helm.

for ido-find-file, two functions seem missing in helm. 

When run ido-find-file, will guess current symbol if is a exist file in default directory.(and subdirectory)
    if found, ido will auto complete file name, else just keep the normal behavior.
    we can enable this with: (setq ido-use-filename-at-point 'guess)
    When press C-x C-f, ido will use (ffap-guesser) to find out the exist file.

When run ido-find-file, If string not matched any file in current directory, will search
    subdirectory recursively with some tools like find/locate to try to find out correct
    file name. e.g. current-directory is /foo/, exit a file in /foo/bar/example.el
    when open ido-find-file in /foo/, input exam, waiting half a seconds, ido will
    auto complete the correct file name: /foo/bar/example.el which exist in subdirectory.

Anyone could tell me those two function if implemented in current version helm? (2016/04)
   Thanks.

**Comment by thierryvolpiatto** [comment]
Billy <notifications@github.com> writes:

> When run ido-find-file, will guess current symbol if is a exist file
> in default directory.(and subdirectory) if found, ido will auto
> complete file name, else just keep the normal behavior.  we can enable
> this with: (setq ido-use-filename-at-point 'guess) When press C-x C-f,
> ido will use (ffap-guesser) to find out the exist file.

This annoyance is available with `helm-ff-guess-ffap-filenames`.

> When run ido-find-file, If string not matched any file in current
> directory, will search subdirectory recursively with some tools like
> find/locate to try to find out correct file
> name. e.g. current-directory is /foo/, exit a file in
> /foo/bar/example.el when open ido-find-file in /foo/, input exam,
> waiting half a seconds, ido will auto complete the correct file name:
> /foo/bar/example.el which exist in subdirectory.

I don't know this feature, seems not available by default though my ido
knowledge is very limited (I don't use ido at all).
I don't want such a feature in helm, we have enough tools actually to
find files recursively from helm-find-files.

-- 
Thierry

**Comment by zw963** [comment]
> we have enough tools actually to find files recursively from helm-find-files.

Could you please give e simple example about `find files recursively from helm-find-files` ?

**Comment by thierryvolpiatto** [comment]
Billy <notifications@github.com> writes:

>     we have enough tools actually to find files recursively from helm-find-files.
>    
> Could you please give e simple example about find files recursively from helm-find-files ?

`C-c /`, `C-u C-x C-f`, `C-x C-d`(browse projects).

You can also execute an action on a set of files fetched recursively
with a named extension.

Please read the documentation `C-h m` all this is explained.

> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub*


-- 
Thierry

**Comment by zw963** [comment]
Help me a lot, thank very much.
