### ISSUE TITLE
helm-ff-run-grep* do not work under Windows

### ISSUE THREAD

**Issue by jeeger** [emacs-helm/helm#1489]
I'm running Emacs  on Windows 7, and I've just testet `helm-ff-run-grep-ag`, `helm-ff-run-git-grep` and `helm-ff-run-grep`. All of these functions fail to work correctly (and I'd wager that the rest of the `helm-ff-run` functions don't work either).

Possible reasons could be (I had a look at what helm-ag does, which works correctly with Windows):
 - Newline conversion necessary (helm-ag deletes all "\xd" from output)
 - Color codes not interpreted correctly (helm-ag uses `ag --vim-rep` vs `ag --nogroup --nocolor`)
 - ag under Windows needs folder argument (optional under Linux)

Most of these points only apply to ag, and there might be different problems with tools such as pdfgrep or zgrep.

**Comment by thierryvolpiatto** [comment]
Jan Seeger <notifications@github.com> writes:

> I'm running Emacs on Windows 7, and I've just testet
> helm-ff-run-grep-ag, helm-ff-run-git-grep and helm-ff-run-grep. All of
> these functions fail to work correctly (and I'd wager that the rest of
> the helm-ff-run functions don't work either).
>
> Possible reasons could be (I had a look at what helm-ag does, which works correctly with Windows):

Instead of trying to find what's wrong with helm just look at the
docstring of you diverse helm grep commands.

>   * Newline conversion necessary (helm-ag deletes all "\xd" from
>   output)

helm-ag is not part of helm.

>   * Color codes not interpreted correctly (helm-ag uses ag --vim-rep
>   vs ag --nogroup --nocolor)

Wrong, same as above.

>   * ag under Windows needs folder argument (optional under Linux)

Use pt instead of ag on windows, but if you succeed at installing ag it
should work too.

> Most of these points only apply to ag, and there might be different
> problems with tools such as pdfgrep or zgrep.

All grep commands are working fine for me on Windows7 that run in
virtualbox (I have not tried pdfgrep and zgrep because I don't know how
to install these commands on windoze).

It seems you are trying helm-ag which is not part of helm.

-- 
Thierry

**Comment by jeeger** [comment]
Sorry for not expressing that clearly: I was listing problems that `helm-ag ` (which works) circumvents which, that could be responsible for `helm-ff-run-grep-ag` and such not working. I am in no way implying that `helm-ag` is part of helm proper.

On trying again, `helm-ff-run-grep` works somewhat (i.e. proper candidates are listed), but a lot of garbage is inserted into the helm candidate buffer. I've inserted a screenshot to show what I mean. The other `helm-ff-run-grep-*` functions seem to have the same problem.

Somehow, the standard output of `ag` and `grep` is inserted into the helm buffer, without running thorough the candidate transformer. Could this be a performance problem (running external processes is extremely slow on my computer)?
![emacs-screenshot](https://cloud.githubusercontent.com/assets/3542252/15009838/1b954180-11e9-11e6-8768-f97dd773065c.png)

**Comment by thierryvolpiatto** [comment]
Jan Seeger <notifications@github.com> writes:

> Sorry for not expressing that clearly: I was listing problems that
> helm-ag (which works) circumvents which, that could be responsible for
> helm-ff-run-grep-ag and such not working. I am in no way implying that
> helm-ag is part of helm proper.
>
> On trying again, helm-ff-run-grep works somewhat (i.e. proper
> candidates are listed), but a lot of garbage is inserted into the helm
> candidate buffer. I've inserted a screenshot to show what I mean. The
> other helm-ff-run-grep-* functions seem to have the same problem.
>
> Somehow, the standard output of ag and grep is inserted into the helm
> buffer, without running thorough the candidate transformer. Could this
> be a performance problem (running external processes is extremely slow
> on my computer)?  emacs-sc

The problem is not related to helm but something else, try with a
minimal install, for me here on Windows7 running in virtualbox I can't
reproduce lost of performance, garbage in helm-buffer or whatever.

> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub*


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
And here two screenshot of helm running grep and pt (platinium) using the --color option in case you don't believe me:

![screenshot - 04052016 - 16 09 37](https://cloud.githubusercontent.com/assets/1533939/15016810/30a3787e-1213-11e6-984d-c76932d060a9.png)
![screenshot - 04052016 - 16 11 21](https://cloud.githubusercontent.com/assets/1533939/15016832/3f516fca-1213-11e6-956a-7a47b0f3580e.png)

**Comment by jeeger** [comment]
So, after several hours of tinkering, it appears my compiled version of `emacs` was at fault. I've installed the emacs package from `msys2`, and it appears to work much better, including all the `helm-ff-run*` functions.
Sorry for bugging you, and thanks for being such a responsive maintainer!

**Comment by thierryvolpiatto** [comment]
Jan Seeger <notifications@github.com> writes:

> Sorry for bugging you, and thanks for being such a responsive maintainer!

You are welcome ;-)

> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub*


-- 
Thierry

**Comment by jeeger** [comment]
The reason was a Socks wrapper program called SocksCap64, somehow the preloading messed up the programs being run in Emacs.

**Comment by thierryvolpiatto** [comment]
Jan Seeger <notifications@github.com> writes:

> The reason was a Socks wrapper program called SocksCap64, somehow the
> preloading messed up the programs being run in Emacs.

Thanks, good to know.

-- 
Thierry
