### ISSUE TITLE
Improve helm Org-mode property dialog

### ISSUE THREAD

**Issue by simonthum** [emacs-helm/helm#1491]
In org-mode, when entering a new property value (C-c-x p), I am presented with a list of existing values of that property. There may be valid use cases, but I'm using org-contacts it is not helpful.

I would like to suggest an option to take some properties out of that mechanism, in my case, EMAIL and TEL.

An alternative is to avoid putting values on the list which only occur once, taking that fact as a sign that the  value is unique.

**Comment by thierryvolpiatto** [comment]
I don't know this org command, do you have something different when disabling helm-mode ?
This is an helm-mode command that is helmizing a org command so don't expect more than what you have in org when helm-mode is disabled.

**Comment by simonthum** [comment]
Well, I guess that Org would complete the values mentioned, but plain Org does not encourage completion with the same fervour. I use org's completion seldom enough that I don't know when it's not useful.

I'll check for an Org-mode native way to get what I want. If that fails, can I opt out of helm-mode for that particular org command?

**Comment by simonthum** [comment]
OK, I disabled helm for org-set-property, vanilla is good enough for my purposes and does not over(w)helm me ;)
