### ISSUE TITLE
Opt out from Helm Help's special display behaviour?

### ISSUE THREAD

**Issue by lunaryorn** [emacs-helm/helm#1493]
`helm-help` by means of `helm-help-internal` explicitly calls `delete-other-windows` to try and make its window the only one.  I'm not sure why this is done but in any case in conflicts with custom `display-buffer-alist` rules.  

Is there a way to opt out from this behaviour and tell Helm to display its Help buffer just like a regular buffer and let `display-buffer-alist` take care of the exact display rules?

**Comment by thierryvolpiatto** [comment]
Sebastian Wiesner <notifications@github.com> writes:

> helm-help by means of helm-help-internal explicitly calls
> delete-other-windows to try and make its window the only one. I'm not
> sure why this is done but in any case in conflicts with custom
> display-buffer-alist rules.

I don't see the problem, as this affect only your helm session.
Please describe exactly the problem you have with this.

-- 
Thierry

**Comment by lunaryorn** [comment]
I'm sorry, I should have made myself more clear.  Essentially I'd just like the Helm Help buffer *not* cover the whole frame, but just a part of it, by my own rules.  I just don't want to loose the context I'm using Helm in, i.e. the original buffer, when I need to look up a Helm key.

I tried adding display rules for it, only to discover that helm overrides any of these because it forcibly deletes all other windows, and other than advising `helm-help-internal`—which I'd rather not like to do—I've no choice to make the Help buffer subject to my own special display rules.

Sure it's just the Help buffer, but I actually use it a lot because I haven't memorized many of the less used Helm keys and find myself frequently looking up things.

**Comment by thierryvolpiatto** [comment]
Sebastian Wiesner <notifications@github.com> writes:

> I'm sorry, I should have made myself more clear. Essentially I'd just
> like the Helm Help buffer not cover the whole frame, but just a part
> of it, by my own rules. I just don't want to loose the context I'm
> using Helm in, i.e. the original buffer, when I need to look up a Helm
> key.
>
> I tried adding display rules for it, only to discover that helm
> overrides any of these because it forcibly deletes all other windows,
> and other than advising helm-help-internal—which I'd rather not like
> to do—I've no choice to make the Help buffer subject to my own special
> display rules.

I made a new user var `helm-help-full-frame`, it should fit your needs.

-- 
Thierry

**Comment by michael-heerdegen** [comment]
I didn't read this thread very carefully, but to enable the user to control this via `display-buffer-alist`, we must not use `switch-to-buffer` I think.  The typical alternative is `pop-to-buffer-same-window` which is based on `display-buffer` but quite similar to `switch-to-buffer` in behavior.
