### ISSUE TITLE
enhancement: Allow selecting helm candidate with mouse

### ISSUE THREAD

**Issue by dtreiter** [emacs-helm/helm#1495]
As far as I can tell there's no way to select a helm candidate by clicking on it. What are your thoughts on adding this in?

**Comment by thierryvolpiatto** [comment]
Daniel Reiter <notifications@github.com> writes:

> As far as I can tell there's no way to select a helm candidate by
> clicking on it. What are your thoughts on adding this in?

Hmm, I am not a fan of the mouse usage in emacs...

Implementing this is not too hard, but require work though, however all
the annoyances it will introduce will be a big work to fix.

So if someone can come with a patch implementing this and preventing all
annoyances the mouse usage will generate, I am not against, but I will
not do this work.

-- 
Thierry
