### ISSUE TITLE
Does helm 1.9.5 really require async 1.8?

### ISSUE THREAD

**Issue by spwhitton** [emacs-helm/helm#1496]
Hello,

Does helm 1.9.5 break when used with async versions 1.6 or 1.7?

I ask because your commits bumping the required version in helm*-pkg.el do not seem to have explanations for the bump.

Thanks.

Sean

**Comment by thierryvolpiatto** [comment]
Sean Whitton <notifications@github.com> writes:

> Hello,
>
> Does helm 1.9.5 break when used with async versions 1.6 or 1.7?

No, the improvements of 1.8 are just about dired-async which handle in a
better way errors and provide also a backup fn, but helm needs async
only for compilation.

Note also that when installed from git, i.e not using package.el to
install and using make to compile, async is not needed at all even if
it is better to have it (allow copying/renaming etc... files async from
helm-find-files).

-- 
Thierry

**Comment by spwhitton** [comment]
Thank you for replying so quickly with that information.

If you're interested, I asked because I want to make async a recommendation of the Debian packaging of helm, rather than a dependency.  But I couldn't do that if async 1.6 is incompatible with helm 1.9.5 because if it is a recommendation not a dependency, there is no guarantee that the async package would get upgraded along with helm.  Now that I know that async 1.6 is okay, I'll switch it to a recommendation.
