### ISSUE TITLE
Is it possible to open the helm list over the current buffer

### ISSUE THREAD

**Issue by willmcclellan** [emacs-helm/helm#1497]
One of the nice features of Vim's Unite was the ability to open the candidates list over the current buffer (i.e. don't open a new buffer in horizontal/vertical split). Then selecting any file in the list opens in that same buffer.

Is there any configuration to do something similar with helm? I looked through issues but couldn't see anything clear. Thanks in advance for any help

**Comment by thierryvolpiatto** [comment]
Will McClellan <notifications@github.com> writes:

> Is there any configuration to do something similar with helm?

See `helm-split-window-default-side`.

-- 
Thierry

**Comment by willmcclellan** [comment]
@thierryvolpiatto thanks! When I said 'over' I meant *inside* the currently focused buffer, which it doesn't look like it supported yet. I'm using Spacemacs too which only has config for left/right/top/bottom

**Comment by thierryvolpiatto** [comment]
Will McClellan <notifications@github.com> writes:

> @thierryvolpiatto thanks! When I said 'over' I meant inside the
> currently focused buffer,

I understood.

> which it doesn't look like it supported yet.

It is supported, please read the docstring.

> I'm using Spacemacs too which only has config for
> left/right/top/bottom

I don't know (and don't care) what spacemacs is doing.

-- 
Thierry

**Comment by willmcclellan** [comment]
Sorry, I misunderstood the docs. I see this can be done with:

`helm-split-window-default-side` 

set to 'same. It didn't work for me so I think Spacemacs might be overwriting the config somewhere. I'll ask the question in that repo. Cheers
