### ISSUE TITLE
`(helm-mode 1)` causes ```ad-handle-definition: `tramp-read-passwd' got redefined```

### ISSUE THREAD

**Issue by michaelmhoffman** [emacs-helm/helm#1498]
Using emacs 24.5.2, with Helm 1.9.5 installed, I run `emacs -Q` and then execute the following forms line-by-line in the `*scratch*` buffer:

```emacs-lisp
(package-initialize)
(require 'helm)
(helm-mode 1)
```

Upon executing `(helm-mode 1)` I get the message ```ad-handle-definition: `tramp-read-passwd' got redefined```. `tramp-read-passwd` does not appear to be loaded before `(helm-mode 1)` so Helm appears to be advising and then redefining it.

This was also described in syl20bnr/spacemacs#192 but they silenced the warning.

**Comment by thierryvolpiatto** [comment]
michaelmhoffman <notifications@github.com> writes:

> Using emacs 24.5.2, with Helm 1.9.5 installed, I run emacs -Q and then
> execute the following forms line-by-line in the *scratch* buffer:
>
> (package-initialize) (require 'helm) (helm-mode 1)
>
> Upon executing (helm-mode 1) I get the message ad-handle-definition:
> `tramp-read-passwd' got redefined. tramp-read-passwd does not appear
> to be loaded before (helm-mode 1) so Helm appears to be advising and
> then redefining it.

There is no problem with this warning, forget it.

-- 
Thierry

**Comment by michaelmhoffman** [comment]
The problem is that if one gets used to the habit of ignoring extraneous warnings, one can easily miss warnings that indicate issues that need to be dealt with.

**Comment by xuchunyang** [comment]
Try `(setq ad-redefinition-action 'accept)`

**Comment by michaelmhoffman** [comment]
```emacs-lisp
(let ((ad-redefinition-action 'accept))
  (helm-mode 1))
```

works around the warning. Thanks.
