### ISSUE TITLE
helm-imenu-in-all-buffers not work correct.

### ISSUE THREAD

**Issue by zw963** [emacs-helm/helm#1499]
I found this function is worked only for all buffers which 
belongs to same mode/extension.

In fact, similar behavior is exist in `helm-imenu-anywhere` which belongs to
another package `imenu-anywhere`.

So,  i create this issue, is this behavior is for intention?

anyway, this name `in-all-buffer` confuse me a little.

**Comment by thierryvolpiatto** [comment]
Billy <notifications@github.com> writes:

> I found this function is worked only for all buffers which
> belongs to same mode/extension.

This is the expected behavior.

-- 
Thierry

**Comment by zw963** [comment]
> This is the expected behavior.

OK.  seem like imenu-anywhere is no need anymore.

Any plan to change this name or add a options for global?

**Comment by zw963** [comment]
Several times, i meet the case hope grep `javascripts` functions name in `ruby` buffer.
so I think this function is maybe worth to realize.

And more, I think this function document need to update. 
`"Preconfigured helm for fetching imenu entries of all buffers."` is no use in this case.
I still consider this functions will show `all function define in all buffer`.

**Comment by zw963** [comment]
Cool, i think this function will instead of `helm-imenu-anywhere` totally.

**Comment by thierryvolpiatto** [comment]
> Several times, i meet the case hope grep javascripts functions name in ruby buffer.

You will be soon allowed to associate your javascript mode with your ruby ones, you can already try the assoc_buffers branch.
Use `helm-imenu-all-buffer-assoc` to associate your mode, then you should be able to jump to a function from javascript to a ruby buffer and vice-versa.

**Comment by zw963** [comment]
Thanks for `helm-imenu-all-buffer-assoc` variable, though I think this is some little overkill for this.

For now, I think exist two command,  one only derived buffer, another is all buffer which is opened.
I don't know if latter is hard to implement? 

for all files which included in my project, I could you helm-git-grep, we have so richness help plugins
to archive this.

anyway, i will try this new function after several hours, i will report result here.

**Comment by thierryvolpiatto** [comment]
Billy <notifications@github.com> writes:

> For now, I think exist two command, one only derived buffer, another
> is all buffer which is opened.  I don't know if latter is hard to
> implement?

It is not, the only thing is it is too costly, thus all buffers are not
supported by imenu, so you have to limit the number of searched buffers.
It is what we are doing now, limiting the searched buffers by using only
the derived ones and in bonus using the ones authorized in
`helm-imenu-all-buffer-assoc`.
This allow for example jumping to the definition of the symbol above
from this mail buffer (which is unrelated to emacs-lisp-mode).

> for all files which included in my project, I could you helm-git-grep,

Grep tools are unrelated to this, they are searching OCCURENCES of a
symbol, whereas imenu or etags are searching the DEFINITION of this symbol.

-- 
Thierry

**Comment by zw963** [comment]
Hi, I have test with following config:

```cl
(eval-after-load 'helm-imenu
  '(progn
     (add-to-list 'helm-imenu-all-buffer-assoc  '(ruby-mode . js-mode))
     (add-to-list 'helm-imenu-all-buffer-assoc  '(js-mode . ruby-mode))
     ))
```
It work very well between ruby-mode and js-mode, bidirectional.

**Comment by zw963** [comment]
just for clarify, If I want to binding `rhtml-mode` too. 
what i need is:
```cl
(eval-after-load 'helm-imenu
  '(progn
     (add-to-list 'helm-imenu-all-buffer-assoc  '(ruby-mode . js-mode))
     (add-to-list 'helm-imenu-all-buffer-assoc  '(js-mode . ruby-mode))
     (add-to-list 'helm-imenu-all-buffer-assoc  '(ruby-mode . html-mode))
     (add-to-list 'helm-imenu-all-buffer-assoc  '(html-mode . ruby-mode))
     (add-to-list 'helm-imenu-all-buffer-assoc  '(js-mode . html-mode))
     (add-to-list 'helm-imenu-all-buffer-assoc  '(html-mode . js-mode))
     ))
```

it seem like a little complex.

**Comment by thierryvolpiatto** [comment]
Billy <notifications@github.com> writes:

> Hi, I have test with following config:
>
> (eval-after-load 'helm-imenu
>   '(progn
>      (add-to-list 'helm-imenu-all-buffer-assoc  '(ruby-mode . js-mode))
>      (add-to-list 'helm-imenu-all-buffer-assoc  '(js-mode . ruby-mode))
>      ))

You should only need '(ruby-mode . js-mode) it should work in both sens.

> It work very well between ruby-mode and js-mode, bidirectional.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub*


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Billy <notifications@github.com> writes:

> just for clarify, If I want to binding rhtml-mode too.
> what i need is:
>
> (eval-after-load 'helm-imenu
>   '(progn
>      (add-to-list 'helm-imenu-all-buffer-assoc  '(ruby-mode . js-mode))
>      (add-to-list 'helm-imenu-all-buffer-assoc  '(js-mode . ruby-mode))
>      (add-to-list 'helm-imenu-all-buffer-assoc  '(ruby-mode . html-mode))
>      (add-to-list 'helm-imenu-all-buffer-assoc  '(html-mode . ruby-mode))
>      (add-to-list 'helm-imenu-all-buffer-assoc  '(js-mode . html-mode))
>      (add-to-list 'helm-imenu-all-buffer-assoc  '(html-mode . js-mode))
>      ))

You should only need:

(eval-after-load 'helm-imenu
  '(progn
     (add-to-list 'helm-imenu-all-buffer-assoc  '(ruby-mode . js-mode))
     ;; (add-to-list 'helm-imenu-all-buffer-assoc  '(js-mode . ruby-mode))
     (add-to-list 'helm-imenu-all-buffer-assoc  '(ruby-mode . html-mode))
     ;; (add-to-list 'helm-imenu-all-buffer-assoc  '(html-mode . ruby-mode))
     (add-to-list 'helm-imenu-all-buffer-assoc  '(js-mode . html-mode))
     ;; (add-to-list 'helm-imenu-all-buffer-assoc  '(html-mode . js-mode))
     ))

-- 
Thierry

**Comment by zw963** [comment]
> You should only need '(ruby-mode . js-mode) it should work in both sens.

It worked,  thanks.

**Comment by zw963** [comment]
It worked well in following case too:

1. use previous ruby js, html config.
2. create a js function: named: foo
3. creat a ruby method: named: foo
4. in html file, search foo use helm-imenu.

we got two correct result. Cool! though, no major-mode is displayed in helm buffer list.

Thanks.

**Comment by thierryvolpiatto** [comment]
Billy <notifications@github.com> writes:

> It worked well in following case too:
>
>  1. use previous ruby js, html config.
>  2. create a js function: named: foo
>  3. creat a ruby method: named: foo
>  4. in html file, search foo use helm-imenu.
>
> we got two correct result. Cool! though, no major-mode is displayed in helm buffer list.

Yes but you should see the filename if you use helm-popup-tip-mode.

-- 
Thierry

**Comment by zw963** [comment]
> Yes but you should see the filename if you use helm-popup-tip-mode.

It worked.

**Comment by zw963** [comment]
Hi, I binding `helm-imenu-in-all-buffers` with some hotkey in global-map.
but, seem like this command is not worked well with `org-mode`

following is a example
```
* aaa
* bbb
* ccc
* ddd
```

run `helm-imenu-in-all-buffer`, minibuffer get input, let me input pattern.
but, when input any char, always tips `imenu-indexing-buffers...done`.

in same case, `helm-imenu` is work well for me.

Following is my config:

```cl
(require 'helm-config) ;default use C-x c prefix.
(helm-mode 1)
```

**Comment by thierryvolpiatto** [comment]
Billy <notifications@github.com> writes:

> Hi, I binding helm-imenu-in-all-buffers with some hotkey in global-map.
> but, seem like this command is not worked well with org-mode

It is not working with org, only modes derived from prog-mode.

-- 
Thierry
