### ISSUE TITLE
helm-org-agenda-files-headings lost all the faces

### ISSUE THREAD

**Issue by llcc** [emacs-helm/helm#1500]
As title pointed, when I call the `helm-org-agenda-files-headings`,
 I could not get the headlings properly. Can you fix this?

![image](https://cloud.githubusercontent.com/assets/3996879/15248438/2a5c1afe-1955-11e6-8871-2363cd6c0e34.png)

**Comment by thierryvolpiatto** [comment]
llcc <notifications@github.com> writes:

> As title pointed, when I call the helm-org-agenda-files-headings,
> I could not get the headlings properly. Can you fix this?

Nothing to fix, see customization to have the effect you want.

-- 
Thierry

**Comment by llcc** [comment]
Thanks, I got everything I want.
2016年5月14日(土) 1:48 Thierry Volpiatto <notifications@github.com>:

>
