### ISSUE TITLE
Advanced Keybinding

### ISSUE THREAD

**Issue by der-Daniel** [emacs-helm/helm#1501]
Hi,

I am currently struggling on how to define some keybinding for specific helm actions.

Scenario 1:
I want to have `return` perform `helm-execute-persistent-action` only during `helm-find-files`. I tried to bind it by the following snippet:
`(define-key helm-find-files-map (kbd "<return>") 'helm-execute-persistent-action)`  
but emacs tells me that `helm-find-files-map` is void.

Scenario 2:
I want to change the `C-c o` binding for opening a file in a new window to `C-<return>`. How to I get to know the name for the command. The doc only says `switch to other window`.

Cheers
Daniel

**Comment by xuchunyang** [comment]
> (define-key helm-find-files-map (kbd "<return>") 'helm-execute-persistent-action)

Try

    (with-eval-after-load 'helm-files
      (define-key helm-find-files-map (kbd "<RET>") 'helm-execute-persistent-action))

> How to I get to know the name for the command

Use `C-h k`, it works in helm session as well.

**Comment by der-Daniel** [comment]
Awesome! :) 
Many Thanks
