### ISSUE TITLE
Helm Shell does not respect "history-delete-duplicates"

### ISSUE THREAD

**Issue by eddiepierce** [emacs-helm/helm#1502]
Helm does not remove duplicates when (setq history-delete-duplicates t) in Shell

**Comment by thierryvolpiatto** [comment]
Eddie <notifications@github.com> writes:

> Helm does not remove duplicates when (setq history-delete-duplicates t) in Shell

I don't think this variable is affecting shell history.
Anyway, if it does and you have duplicates it is more an emacs bug than
a helm bug, helm is just helmizing the completion emacs propose.
See perhaps `helm-comint-input-ring` which will provide something better.

-- 
Thierry
