### ISSUE TITLE
helm hangs if typing file path after wait a monent when execute helm-find-files

### ISSUE THREAD

**Issue by zhcosin** [emacs-helm/helm#1504]
Hi, I try to use helm to complete something, but I found a phenomenon when execute helm-find-files, I bind this function to C-x C-f, if I C-x C-f and input file path immediately then it works fine, but if I input the file path wait a moment after C-x C-f, then it hangs..... Dose anyone  encounter this problem?
tips: I use Emacs 24.4 GUI version on win7.

**Comment by thierryvolpiatto** [comment]
Fixed by 5235fe0
