### ISSUE TITLE
Helm hangs after deleting a character

### ISSUE THREAD

**Issue by xificurC** [emacs-helm/helm#1505]
Latest helm seems to have a bug:

```
emacs -Q
M-x (package-initialize)
M-x (require 'helm)
M-x find-files . <backspace> .
```

This hangs for me. Several other people reported an issue with deleting on spacemacs gitter channel. The above snippet shows that it should be a `helm` issue though.

Let me know if you need more information

**Comment by thierryvolpiatto** [comment]
duplicate of #1504

**Comment by xificurC** [comment]
Thanks for the quick fix
