### ISSUE TITLE
how to highlight all the results of helm-occur in the buffer 

### ISSUE THREAD

**Issue by c02y** [emacs-helm/helm#1506]
When I use helm-occur to search a string in the buffer, how can I highlight all the strings in the buffer even after I hit Enter and close the occur window, like setting (setq lazy-highlight-cleanup nil) for isearch?

**Comment by thierryvolpiatto** [comment]
c02y <notifications@github.com> writes:

> When I use helm-occur to search a string in the buffer, how can I
> highlight all the strings in the buffer even after I hit Enter and
> close the occur window, like setting (setq lazy-highlight-cleanup nil)
> for isearch?

This is not implemented in helm-occur and the motivation to do this is
very low...
You can highlight other matches in the lines around current match in
persistent action, which is enough IMO. 

-- 
Thierry

**Comment by c02y** [comment]
How can I highlight other matches in the lines around current match in 
persistent action?

**Comment by thierryvolpiatto** [comment]
c02y <notifications@github.com> writes:

> How can I highlight other matches in the lines around current match in
> persistent action?

Configure the number of lines to highlight around current match with

`helm-highlight-matches-around-point-max-lines`

Default is 15, I use 30.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
![screenshot-18052016-11 57 07](https://cloud.githubusercontent.com/assets/1533939/15354838/cb9cbbec-1cef-11e6-832c-bfea518ad633.png)

**Comment by c02y** [comment]
Never mind, I already use highlight-symbol to highlight all the occurrences 
in the buffer.
