### ISSUE TITLE
Setting `helm-recentf-fuzzy-match` to `t` got different order the recentf list

### ISSUE THREAD

**Issue by Yevgnen** [emacs-helm/helm#1507]
Hi,

I use fuzzy match everywhere in helm, but find that setting `helm-recentf-fuzzy-match` to `t` may break the recentf list order. Is this a feature or bug ?

 For example, find file `~/lstm/models.py` and close, then find file `~/theano/models.py` and close, run `helm-recentf` and type `models`, the first item should be `~/theano/models.py` but got `~/lstm/models.py`.(Notice that before typing anything, the recentf list is shown in expected order)

Also please note that evaluating the `(setq helm-recentf-fuzzy-match nil)` will not fix this immediately unless I restart emacs. Below is the minimum test code. 

    (require 'package)
    
    (setq package-archives '(("marmalade" . "http://marmalade-repo.org/packages/")
                             ("gnu" . "http://elpa.gnu.org/packages/")
                             ("melpa" . "https://melpa.org/packages/")
                             ("org" . "http://orgmode.org/elpa/")))
    
    (package-initialize)
    
    (unless (and (file-exists-p (expand-file-name "elpa/archives/marmalade" user-emacs-directory))
                 (file-exists-p (expand-file-name "elpa/archives/gnu" user-emacs-directory))
                 (file-exists-p (expand-file-name "elpa/archives/melpa" user-emacs-directory))
                 (file-exists-p (expand-file-name "elpa/archives/org" user-emacs-directory)))
      (package-refresh-contents))
    
    (unless (package-installed-p 'use-package)
      (package-refresh-contents)
      (package-install 'use-package))
    
    (use-package helm
      :init
      (setq helm-recentf-fuzzy-match nil))

How can I enjoy the fuzzy matching in `helm-recentf` and meanwhile preserving the `recentf-list` order? Any help will be appreciated !

**Comment by thierryvolpiatto** [comment]
Yevgnen <notifications@github.com> writes:

> I use fuzzy match everywhere in helm, but find that setting
> helm-recentf-fuzzy-match to t may break the recentf list order. Is
> this a feature or bug ?

Well it seems obvious that as soon as you start narrowing with helm or
whatever and with fuzzy matching or not you loose such initial sorting.
So what you are asking is not reasonable IMO.

> Also please note that evaluating the (setq helm-recentf-fuzzy-match
> nil) will not fix this immediately unless I restart emacs.

See Issue #1486.

-- 
Thierry

**Comment by Yevgnen** [comment]
Ok, I redefine it for my own use.

      (defun helm-recentf2-candidates ()
        (loop for index from 0
              for file in recentf-list
              collect (cons file `(:index ,index :file ,file))))
    
      (defun helm-recentf2-transformer (candidates source)
        (-sort (lambda (c1 c2) (< (plist-get (cdr c1) :index) (plist-get (cdr c2) :index))) candidates))
    
      (setq helm-source-recentf2
            (helm-build-sync-source "helm-recentf2"
              :candidates #'helm-recentf2-candidates
              :filtered-candidate-transformer #'helm-recentf2-transformer))
    
      (defun helm-recentf2 ()
        (interactive)
        (helm :sources 'helm-source-recentf2
              :ff-transformer-show-only-basename nil
              :buffer "*helm recentf2*"))
      (bind-key "C-c f" #'helm-recentf2)

And thanks for your links about the second question.

**Comment by thomasjm** [comment]
@thierryvolpiatto I'm running into this same issue, and was wondering if there is a way to improve it.

The way I'd like this to work once you start narrowing (using fuzzy matching or whatever) is to use the order from fuzzy matching as usual, but *break ties* using recency. So in the original example, typing `models` will yield an equally good match to both of the two `models.py` files, but `~/theano/models.py` will come up first due to tie breaking.

Is this something an end-user could do, perhaps by providing a custom sort function? Thanks!

**Comment by thierryvolpiatto** [comment]
Tom McLaughlin <notifications@github.com> writes:

> @thierryvolpiatto I'm running into this same issue, and was wondering if there is a way to improve it.
>
> The way I'd like this to work once you start narrowing (using fuzzy
> matching or whatever) is to use the order from fuzzy matching as
> usual, but break ties using recency.

How do you set `helm-recentf-fuzzy-match`?

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thomasjm** [comment]
I have tried both `nil` and `t`. Although actually, I'm more interested in making this work for helm-buffers than helm-recentf. (If my helm buffers list were sorted the way I described, then I would not need helm-recentf at all.)

**Comment by thierryvolpiatto** [comment]
Tom McLaughlin <notifications@github.com> writes:

> I have tried both nil and t.

No I mean how do you set this? With setq?
If it is the case it won't work, use instead

    (customize-set-variable 'helm-recentf-fuzzy-match t)

> Although actually, I'm more interested in making this work for
> helm-buffers than helm-recentf. (If my helm buffers list were sorted
> the way I described, then I would not need helm-recentf at all.)

I can make this configurable if you want (it is already configurable but
a little tricky), please open an issue.

Thanks.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thomasjm** [comment]
Oh I see. That explains why `setq` wasn't working reliably. 

Regarding the `customize-set-variable` thing, I use [Doom Emacs](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org) and its documentation contains a note saying not to use the customize API with Doom. Not a big deal, but it would be nice to be able to control helm variables without relying on customize.

Just filed the new issue #2339 ! Thanks for the quick responses :)

**Comment by thierryvolpiatto** [comment]
Tom McLaughlin <notifications@github.com> writes:

> Oh I see. That explains why setq wasn't working reliably.
>
> Regarding the customize-set-variable thing, I use Doom Emacs and its documentation contains a note saying not to use the customize API with Doom. Not a big deal, but it
> would be nice to be able to control helm variables without relying on
> customize.

The answer is no, there is no reason we don't use customize which is a
nice feature and the way to specify user variables in Emacs since years,
Doom have to adapt itself, not the contrary.


-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by manuel-uberti** [comment]
@thomasjm if Doom Emacs uses `use-package`, IIRC you can use `:custom` to set `helm-recentf-fuzzy-match` without going through the Customize interface. But I agree with Thierry: it shouldn't be up to Helm to adapt to a specific Emacs configuration.

**Comment by thomasjm** [comment]
It turns out Doom provides a function `setq!` which works properly with `defcustom`-style things.

I don't know the specific reason why Doom doesn't like customize, but it's a really impressive distro that contains a lot of good decisions IMO. A similar example is how they abandon the built-in `package.el` in favor of a more modern purely functional package manager. So maybe they're onto something  ¯\\_(ツ)_/¯. Anyway, thanks for the help!
