### ISSUE TITLE
helm-do-grep-1, helm-grep-ignored-directories not works

### ISSUE THREAD

**Issue by yuandaxing** [emacs-helm/helm#1508]
describe-variable: helm-grep-ignored-directories
("SCCS" "RCS" "CVS" "MCVS" ".svn" ".git" ".hg" ".bzr" "_MTN" "_darcs" "{arch}" ".gvfs" ".git" "*/.git/*" "git" ".git")
but when i run:
(helm-do-grep-1 (list "~/code/skillset/"))
below file is in the result:
/home/ydx/code/skillset/.git/index

describe-variable helm-grep-default-command:
helm-grep-default-command is a variable defined in `helm-grep.el'.
Its value is "grep --color=always -a -d recurse %e -n%cH -e %p %f"
Original value was 
"grep --color=always -a -d skip %e -n%cH -e %p %f"

I notice that helm-grep-in-recurse is true, it will use  helm-grep-ignored-directories
but still not works

**Comment by thierryvolpiatto** [comment]
yuandaxing <notifications@github.com> writes:

> describe-variable: helm-grep-ignored-directories
> ("SCCS" "RCS" "CVS" "MCVS" ".svn" ".git" ".hg" ".bzr" "_MTN" "_darcs"
> "{arch}" ".gvfs" ".git" "/.git/" "git" ".git")

This is not the default value.

> but when i run:
> (helm-do-grep-1 (list "~/code/skillset/"))

This is not recursive so helm-grep-ignored-directories are not passed,
normal.

> below file is in the result:
> /home/ydx/code/skillset/.git/index

If you have this in your result something is wrong, but not with helm,
see below.

> I notice that helm-grep-in-recurse is true

You should not use this directly, use the RECURSE arg of helm-do-grep-1.

> , it will use helm-grep-ignored-directories but still not works

So it is a problem with your helm-grep-ignored-directories settings,
grep is troubled with all the "git" entries you gave, see the man page
of grep.

Here the arguments are passed correctly to command line:

(helm-do-grep-1 '("~/labo/github/helm/"))
=>
** 06:39:31.322393 (helm-grep-init)
 Command line used was:

>>> grep --color=always -d skip --exclude=.\#\* --exclude=\*.o --exclude=\*\~ --exclude=\*.bin --exclude=\*.lbin --exclude=\*.so --exclude=\*.a --exclude=\*.ln --exclude=\*.blg --exclude=\*.bbl --exclude=\*.elc --exclude=\*.lof --exclude=\*.glo --exclude=\*.idx --exclude=\*.lot --exclude=\*.fmt --exclude=\*.tfm --exclude=\*.class --exclude=\*.fas --exclude=\*.lib --exclude=\*.mem --exclude=\*.x86f --exclude=\*.sparcf --exclude=\*.dfsl --exclude=\*.pfsl --exclude=\*.d64fsl --exclude=\*.p64fsl --exclude=\*.lx64fsl --exclude=\*.lx32fsl --exclude=\*.dx64fsl --exclude=\*.dx32fsl --exclude=\*.fx64fsl --exclude=\*.fx32fsl --exclude=\*.sx64fsl --exclude=\*.sx32fsl --exclude=\*.wx64fsl --exclude=\*.wx32fsl --exclude=\*.fasl --exclude=\*.ufsl --exclude=\*.fsl --exclude=\*.dxl --exclude=\*.lo --exclude=\*.la --exclude=\*.gmo --exclude=\*.mo --exclude=\*.toc --exclude=\*.aux --exclude=\*.cp --exclude=\*.fn --exclude=\*.ky --exclude=\*.pg --exclude=\*.tp --exclude=\*.vr --exclude=\*.cps --exclude=\*.fns --exclude=\*.kys --exclude=\*.pgs --exclude=\*.tps --exclude=\*.vrs --exclude=\*.pyc --exclude=\*.pyo -niH -e define [...]

(helm-do-grep-1 '("~/labo/github/helm/") t)
=>
** 06:41:13.632010 (helm-grep-init)
 Command line used was:

>>> grep --color=always -d recurse --include=\*.el --exclude-dir=SCCS --exclude-dir=RCS --exclude-dir=CVS --exclude-dir=MCVS --exclude-dir=.svn --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.bzr --exclude-dir=_MTN --exclude-dir=_darcs --exclude-dir=\{arch\} --exclude-dir=.gvfs -niH -e define /home/thierry/labo/github/helm/ 


-- 
Thierry

**Comment by yuandaxing** [comment]
great thanks.
I want to use "-exclude-dir" and "--exclude" at the same time.
helm's interactive feature is really impressive, and i do not want to use find-grep or something else.
I have trouble with this for weeks,  could you help me?

**Comment by thierryvolpiatto** [comment]
yuandaxing <notifications@github.com> writes:

> I want to use "-exclude-dir" and "--exclude" at the same time.

If you want to do this always use the RECURSIVE arg of helm-do-grep-1 or
in interactive usage, use a prefix arg.
I personally don't use grep as backend but ack-grep, which allow to not
bother about ignored directories and files.
For directory searching I use ag and git-grep.

-- 
Thierry

**Comment by yuandaxing** [comment]
great thanks.
could someone update the code to support 
 I want to use "-exclude-dir" and "--exclude" at the same time.
I think it is a needed feature, is it?

**Comment by thierryvolpiatto** [comment]
yuandaxing <notifications@github.com> writes:

> I want to use "-exclude-dir" and "--exclude" at the same time.
> I think it is a needed feature, is it?

No.

Look, here a repo named "foo" that contain one source file "foo.el" and
a ".git" directory, cursor is "!".

foo .!
foo ..
.git
foo.el

Start grepping NOT recursively, what happens ?

grep will search in all files of "foo" directory, but will not enter the
".git" directory, so no need to give to grep "--exclude-dir=.git" as it
will never recurse into it, what we only need is to notify it is the files
to not search in with "--exclude".

Now start searching recursively.

grep will search all files in "foo" directory but will also recurse in
the ".git" directory unless we notify it not doing so by passing
"--exclude-dir=.git", it is what we are doing.
About excluding files instead of using "--exclude" we notify grep to search only in files
with a specific extension (you should have been prompted for "*.el", "*"
etc...) with the "--include" arg, which is much more accurate and
efficient.

e.g:

** 07:05:13.632010 (helm-grep-init)
 Command line used was:

>>> grep --color=always -d recurse --include=\*.el --exclude-dir=SCCS --exclude-dir=RCS --exclude-dir=CVS --exclude-dir=MCVS --exclude-dir=.svn --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.bzr --exclude-dir=_MTN --exclude-dir=_darcs --exclude-dir=\{arch\} --exclude-dir=.gvfs -niH -e define /home/thierry/labo/github/helm/ 

As I said, if you don't want to have to deal with all this, just use
ack-grep, ag or git-grep, which are more clever than plain grep about
the files to search in or not, they are all supported in helm.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
yuandaxing <notifications@github.com> writes:

> great thanks.
> could someone update the code to support
> I want to use "-exclude-dir" and "--exclude" at the same time.
> I think it is a needed feature, is it?

Also, if you really want to use the both, and not "--include" (which is
more efficient IMO) call helm-do-grep-1 with EXTS specified as an empty
string.
In interactive calls use C-RET to exit prompt with empty string,
helm-grep in this case will use both --exclude and --excluse-dir.

-- 
Thierry

**Comment by yuandaxing** [comment]
yes, it works.
may be not that good. 
thanks for your kindly help.

**Comment by thierryvolpiatto** [comment]
Ok closing now.
