### ISSUE TITLE
Unexpected behavior with `helm-preselect`

### ISSUE THREAD

**Issue by xiongtx** [emacs-helm/helm#1509]
## Problem

I am encountering some unexpected behavior with the `:preselect` keyword for the `helm` command. Consider the example below:

```emacs-lisp
(helm :sources (list (helm-build-sync-source "foo"
                       :candidates '("a" "b" "c"))
                     (helm-build-sync-source "bar"
                       :candidates '(1 2 3)))
      :buffer "*Helm test*"
      :preselect "bar")
```

The selection overlay is moved to `1`, which is unexpected, since none of the candidates in the two sources match `bar`. In the case of no match, I would expect the selection overlay to be placed on the first line of the first source--in this case, on `a`.

Looking at the [source](https://github.com/emacs-helm/helm/blob/master/helm.el#L4288) for `helm-preselect`, it seems that the preselection is done by searching through the Helm buffer. Might this phenomenon be due to the regexp matching the source name?

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> Might this phenomenon be due to the regexp matching the source name?

Yes, should be fixed now.

Thanks.

-- 
Thierry

**Comment by xiongtx** [comment]
Confirmed as fixed.

**Comment by xiongtx** [comment]
I'm going to reopen this issue because `(helm-preselect "" "")` now causes Emacs to hang.

Example:

```emacs-lisp
(progn
  (with-helm-after-update-hook
    (with-helm-buffer
      (let ((helm-force-updating-p t)) 
        (helm-preselect "" ""))))

  (helm :buffer "*Preselect example*"                
        :sources (list (helm-build-sync-source "Source 1"
                         :candidates '(1 2 3))
                       (helm-build-sync-source "Source 2"
                         :candidates '(1 2 3)))))
```

The problem is that the call to `(helm-goto-source "")` in `helm-preselect` moves the selection line to the *last* header line, `"Source 2"`. Then, the `helm-awhile` loop never exists, because `(re-search-forward "" nil t)` never returns `nil`.

This unexpected behavior is due to the implementation of `helm-move--goto-source-fn`. Instead, `(helm-goto-source "")` should not move point at all (I don't think empty string is a valid source name).

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> I'm going to reopen this issue because (helm-preselect "" "") now causes Emacs to hang.

helm-preselect SOURCE arg should not be a string, but a source which is
a list or nil. (typically the SOURCE arg is generated by `helm-get-current-source`).
If your code generate a SOURCE arg which is a string, something is wrong
in your code.

-- 
Thierry

**Comment by xiongtx** [comment]
`helm-goto-source` has the parameter `source-or-name`, so what's wrong with using the source name string?

**Comment by xiongtx** [comment]
At the risk of beating a dead horse, I'm not sure where we left off on the issue of `helm-preselect` with a string source name.

The documentation for `helm-preselect` suggests that this *should* be accepted:

> Argument SOURCE is a valid source name or a source alist

But this is currently broken due to the use of 

```emacs-lisp
    (helm-display-mode-line (or source (helm-get-current-source)))
```

which assumes that `source` is always a list.

If we must use an actual source, we should:

- Change the docstring to remove reference to source name
- Provide a way to get a source from a source name for a current Helm session

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> If we must use an actual source, we should:
>
>   * Change the docstring to remove reference to source name
>   * Provide a way to get a source from a source name for a current Helm session

A simple loop against helm-sources that check egality of name with the
helm-attr 'name of source should do the trick (I use this somewhere in
helm but can't remember where).

-- 
Thierry

**Comment by xiongtx** [comment]
Alright, but `helm-sources` is marked as `[INTERNAL]` (though the lack of a `--` in the name suggests otherwise). Should it be considered an API instead?

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> Alright, but helm-sources is marked as [INTERNAL] (though the lack of
> a -- in the name suggests otherwise). Should it be considered an API
> instead?

No.  It was an API in the first ages of anything and was largely abused
by users, I want to keep it internal.

--
Thierry
