### ISSUE TITLE
`helm-occur` jumps to wrong line for Man pages

### ISSUE THREAD

**Issue by xiongtx** [emacs-helm/helm#1511]
## Problem

Opening a Man page with `man` and searching for a term with `helm-occur` does not jump to the correct line.

For example:

1. Open the `top` man page with `man`
2. Using an appropriate search term (e.g. `number-of-iterations`), we can jump to this (or any previous) line correctly: `-n  :Number-of-iterations limit as:  -n number`
3. But not the following line (or any after): `Specifies the maximum number of iterations, or frames, top should produce before ending`.

If we copy the text in the Man buffer to another buffer, `helm-occur` works fine on the text in that buffer.

**Update**: as noted in a [comment below](https://github.com/emacs-helm/helm/issues/1511#issuecomment-220519708), this is reproducible with `helm-split-window-default-side` set to `same`, but not when it is set to `below`.

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> Problem
>
> Opening a Man page with man and searching for a term with helm-occur does not jump to the correct line.

Can't reproduce, it is working fine here, both in my main emacs and in
.emacs-helm.sh.

> For example:
>
>  1. Open the top man page with man 2. Using an appropriate search term
>  (e.g. number-of-iterations), we can jump to this (or any previous)
>  line correctly: -n :Number-of-iterations limit as: -n number 3. But
>  not the following line (or any after): Specifies the maximum number
>  of iterations, or frames, top should produce before ending.

Working fine with this recipe.

On which system are you ?
Are you using a special version of man ?

-- 
Thierry

**Comment by xiongtx** [comment]
Reproducible with `emacs-helm.sh` when `helm-split-window-default-side` variable is set to `same`. We've run into issues with this setting before in #1441.

I don't understand why this settings is problematic, whereas `below`, the default, works fine. What technical detail is there that makes it an issue?

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> Reproducible with emacs-helm.sh when helm-split-window-default-side
> variable is set to same. We've run into issues with this setting
> before in #1441.

Not able to reproduce in ./emacs-helm.sh with
helm-split-window-default-side == same.

> I don't understand why this settings is problematic, whereas below,
> the default, works fine.
> What technical detail is there that makes it an issue?

I don't understand too why you have this error, we have to find what
differ from what you are doing and what I am doing here as I can't
reproduce your error.
I still think the problem comes from outside of emacs, in the way man
itself is formatting the buffer.

BTW I know what could trigger such error in helm but I fixed it months
ago, are you sure you are using the most recent helm.el file ?

-- 
Thierry

**Comment by xiongtx** [comment]
Yes, I have the latest version of Helm. What version of Emacs are you using? I'm using 24.5.50.1.

I can definitely reproduce the issue with the window side. `same` = bad, `below` = good. If it's a problem with the way that Man formats the buffer, this should not affect it...should it?

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> Yes, I have the latest version of Helm. What version of Emacs are you using? I'm using 24.5.50.1.

GNU Emacs 24.5.1 (x86_64-unknown-linux-gnu, X toolkit) of 2016-04-18 on
dell-14z

> I can definitely reproduce the issue with the window side. same = bad,
> below = good. If it's a problem with the way that Man formats the
> buffer, this should not affect it...should it?

Perhaps it should, I am using man 2.6.7.1 on ubuntu.

> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub*


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> Yes, I have the latest version of Helm. What version of Emacs are you
> using?

Failed to reproduce also on emacs-25.

-- 
Thierry

**Comment by xiongtx** [comment]
I'll close this for now since you cannot reproduce it and it's not a big deal, but I find the issue mystifying.

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> I'll close this for now since you cannot reproduce it and it's not a
> big deal, but I find the issue mystifying.

Yes, I am curious to know why this is happening, let me know if you find
something new.

What "man --version" returning for you ?
What OS are you using ?

-- 
Thierry

**Comment by xiongtx** [comment]
Man 2.6.7.1 on Fedora 21.
