### ISSUE TITLE
Wiki typo:  C-x c b is mentioned as C-x C-b 

### ISSUE THREAD

**Issue by rdotdk** [emacs-helm/helm#1516]
In [Helm Workflow for Files, Directories and Buffers](https://github.com/emacs-helm/helm/wiki#helm-workflow-for-files-directories-and-buffers), it is mentioned as,
``` C-x C-b ```  to switch back to the resumed Helm sources.
It should be,
``` C-x c b ``` to switch back to the resumed Helm sources.

I checked describe key of ``` C-x c b ```, it gives ``` helm-resume```.
P.S : I don't see the markdown file in the doc directory. Is it okay if i directly edit the wiki?

**Comment by thierryvolpiatto** [comment]
rdotdk <notifications@github.com> writes:

> In Helm Workflow for Files, Directories and Buffers, it is mentioned as,
> C-x C-b to switch back to the resumed Helm sources.
> It should be,
> C-x c b to switch back to the resumed Helm sources.

No, C-x C-b switch to the list of resumed sources whereas C-x c b switch
to the last resumed source.

    (define-key map (kbd "C-x b")      'helm-resume-previous-session-after-quit)
    (define-key map (kbd "C-x C-b")    'helm-resume-list-buffers-after-quit)

> I checked describe key of C-x c b, it gives helm-resume.

No this is the global command, see above.

> P.S : I don't see the markdown file in the doc directory. Is it okay if i directly edit the wiki?

Yes.

Thanks.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Thierry Volpiatto <thierry.volpiatto@gmail.com> writes:

> No, C-x C-b switch to the list of resumed sources whereas C-x c b
                                                            ^^^^^^^
I meant                                                     C-x b

Typo, Sorry.


-- 
Thierry

**Comment by rdotdk** [comment]
Oh Okay. Thanks.
