### ISSUE TITLE
Helm autoloads

### ISSUE THREAD

**Issue by tollerm** [emacs-helm/helm#1519]
It seems that autoloads are broken again in Helm. The symptoms are exactly the same as in the issue "Lazy loading of helm broken #802", i.e. helm is loaded when there is the option :defer t in the use-package.

**Comment by thierryvolpiatto** [comment]
tollerm <notifications@github.com> writes:

> It seems that autoloads are broken again in Helm. The symptoms are
> exactly the same as in the issue "Lazy loading of helm broken #802",
> i.e. helm is loaded when there is the option :defer t in the
> use-package.

Since when is this happening ?

Can you provide a simple recipe to configure helm (minimal) with
use-package and :defer ?

Thanks.

-- 
Thierry

**Comment by tollerm** [comment]
After some additional testing it turned out that the package helm-recoll actually triggers loading the helm. The helm-recoll indeed does not respect :defer t and :config options, thus the helm-recoll project seems a more appropriate place for reporting this issue. Sorry for the noise and thank you for your time and consideration.
Best regards, Toller

**Comment by michael-heerdegen** [comment]
What does "helm-recoll does not respect :defer t and :config options" mean?  use-package is a third party package, and no package needs to provide some infrastructure for it.

**Comment by tollerm** [comment]
Indeed, packages do not need to provide anything special for the use-package. However, it is possible that something is wrong with autoloads in the combination helm/helm-recoll that triggers this behaviour. It could be some problem with use-package though. 
Btw it is a snippet from my config file:

(use-package helm-recoll
  :ensure t
  :defer t
  :config
  (helm-recoll-create-source "main" "~/.recoll"))

The function helm-recoll-create-source always triggers loading the helm.

**Comment by michael-heerdegen** [comment]
tollerm <notifications@github.com> writes:

> (use-package helm-recoll
> :ensure t
> :defer t
> :config
> (helm-recoll-create-source "main" "~/.recoll"))
>
> The function helm-recoll-create-source always triggers loading the
> helm.

Actually, it is a macro.

Hmm, this is because of

  (require 'helm-mode)

in the macro's body.  I don't recoll - ehh, recall - why I have put it
there.  Let me think about it.

**Comment by michael-heerdegen** [comment]
Michael Heerdegen <michael_heerdegen@web.de> writes:

> Hmm, this is because of
>
>   (require 'helm-mode)
>
> in the macro's body.  I don't recoll - ehh, recall - why I have put it
> there.  Let me think about it.

Actually it wasn't me.

Ok, please create an issue (terse description is enough) on the
helm-recoll page, so that I don't create unneeded noise here.  Then I
can ask there why this requirement had been put into that macro.

See you there and TIA.

**Comment by michael-heerdegen** [comment]
Closing the issue here for now, we can reopen if necessary.
