### ISSUE TITLE
C-g doesn't work with helm completion

### ISSUE THREAD

**Issue by RaphaelHythloday** [emacs-helm/helm#1522]
Often I need to cancel a command mid-way with C-g. However, instead of closing the completion window, it just corrupts helm-M-x and makes it unusable until I press RET enough times to get it to execute something and clear itself. 

For example, suppose I press C-x C-f:
![screenshot from 2016-05-28 14-36-35](https://cloud.githubusercontent.com/assets/12179121/15637675/efd723f0-25d5-11e6-9822-45eaa67325ef.png)

And then I want to cancel with C-g:
![screenshot from 2016-05-28 14-36-44](https://cloud.githubusercontent.com/assets/12179121/15637679/ff5aed02-25d5-11e6-8427-7bc9b1523288.png)
 
Instead of closing the completion window, it just shows some weird stuff. The only way I've found to get rid of it is to press RET a bunch of times, which opens up a buffer with some weird name. This problem affects all commands, not just C-x C-f.

**Comment by thierryvolpiatto** [comment]
RaphaelHythloday <notifications@github.com> writes:

> Often I need to cancel a command mid-way with C-g. However, instead of
> closing the completion window, it just corrupts helm-M-x and makes it
> unusable until I press RET enough times to get it to execute something
> and clear itself.
>
> For example, suppose I press C-x C-f: screensh

Seems like you are using spacemacs or something similar.
Ask there.

Helm is working fine here.

-- 
Thierry
