### ISSUE TITLE
helm-find-files fails to work after opening a file

### ISSUE THREAD

**Issue by dancollins** [emacs-helm/helm#1524]
Using emacs-helm.sh, I am able to open a file using `helm-find-files` (`C-x C-f`). Once I have a file open, however, I am no longer able to use `helm-find-files` to open a second file. I can still open files using `M-x find-file`.

Here is the error message from `*Messages*`:
```
Helm completion enabled
Loading cc-langs...done
Loading vc-git...done
Symbol's value as variable is void: it
Quit
```
If you can help me obtain more debugging info (such as a line number for the error) than I am happy to try and help.

Note that both `helm-buffers-list` (`C-x b`) and `helm-M-x` (`M-x`) continue to work as normal.

I am using helm-20160529.114

**Comment by dancollins** [comment]
I should note that I am using `emacs-helm.sh` to reproduce this issue.

**Comment by thierryvolpiatto** [comment]
It looks that helm-lib.el is not loaded, that is the helm-core package, are you sure your installation of helm went well ?

**Comment by dancollins** [comment]
Thanks for the idea! I actually upgraded which caused helm to break. Removing the helm packages (I removed all of them, but I probably only needed to remove helm and helm-core) and re-installing fixed the issue.

**Comment by thierryvolpiatto** [comment]
Dan Collins <notifications@github.com> writes:

> Thanks for the idea! I actually upgraded which caused helm to
> break. Removing the helm packages (I removed all of them, but I
> probably only needed to remove helm and helm-core) and re-installing
> fixed the issue.

Use the helm interface to upgrade:

M-x helm-list-elisp-packages

If upgrades are available helm will show them on startup.

Then C-c U to upgrades all packages (you can upgrade individually, see
C-h m for more infos).

> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.*


-- 
Thierry
