### ISSUE TITLE
C-g is throwing really long error when trying to quit any helm windows

### ISSUE THREAD

**Issue by stevenspasbo** [emacs-helm/helm#1525]
I'm running helm-20160530.424 and helm-core-20160530.754.
Screenshot:
<img width="1388" alt="screen shot 2016-05-30 at 11 51 11 am" src="https://cloud.githubusercontent.com/assets/863398/15657971/593adcb6-266b-11e6-90fa-7b8c5884b06f.png">

It's only happening when trying to quit. helm-find-files works fine if I open a file, helm-M-x works fine if I execute a command, and helm-mini works fine if I switch buffers/open recent file. It's only happening when I attempt to quit (`helm-keyboard-quit`).

Looking through my init, it doesn't look like I've added anything that could be conflicting with helm.

**Comment by thierryvolpiatto** [comment]
This is not reproductible, please start from emacs-helm.sh, looks like you are using many external packages.
Are you using Spacemacs ? If it is the case report bug there.
Looks like a duplicate of #1522 .

**Comment by stevenspasbo** [comment]
Not using spacemacs, just spaceconfig and powerline.

I figured it out, it was being caused by enabling `toggle-debug-on-quit`. I'll go ahead and close this, thanks.
