### ISSUE TITLE
helm-run-after-exit doesn't run action when helm buffer is empty

### ISSUE THREAD

**Issue by cosmicexplorer** [emacs-helm/helm#1526]
Starting up on `emacs -Q`, the below code demonstrates what I believe to be a bug. I am trying to run a command on a keypress while helm is alive.

```emacs-lisp
(let ((map (make-sparse-keymap)))
  (set-keymap-parent map helm-map)
  (define-key map (kbd "M-j")
    (lambda ()
      (interactive)
      (helm-run-after-exit
       (lambda ()
         (helm :sources (helm-build-sync-source "wow" :candidates '("a" "b"))
               :buffer "helm")))))
  (helm :sources (helm-build-sync-source "wow"
                   :candidates nil ; helm just quits here
                   ;; :candidates '("a") ; works as expected if used instead
                   )
        :buffer "helm"
        :keymap map))
```

I would expect that by pressing <kbd>M-j</kbd>, I would begin a new helm session, with the candidates `'("a" "b")`. This occurs when the initial list of candidates is not empty; however, when the candidates list is empty, helm just quits and the new helm session initiated with `helm-run-after-exit` works as expected. This is not a new issue and I'm not sure why it's happening.

**Comment by thierryvolpiatto** [comment]
Danny McClanahan <notifications@github.com> writes:

> Starting up on emacs -Q, the below code demonstrates what I believe to
> be a bug. I am trying to run a command on a keypress while helm is
> alive.

I see no bug, please try to learn (if needed) how work this function by
reading in source code the differents example here and there.

Thanks.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Thierry Volpiatto <thierry.volpiatto@gmail.com> writes:

> Danny McClanahan <notifications@github.com> writes:
>
>> Starting up on emacs -Q, the below code demonstrates what I believe to
>> be a bug. I am trying to run a command on a keypress while helm is
>> alive.
>
> I see no bug, please try to learn (if needed) how work this function by
> reading in source code the differents example here and there.

After more investigations, I guess you are right and it should work as
you expect in such case, even if in practice, it is rarely or not needed
to handle such a case.
I will commit a fix for this in a few minutes, it's easy to fix.

Thanks.

-- 
Thierry
