### ISSUE TITLE
helm-mode conflict with ido-everywhere.

### ISSUE THREAD

**Issue by zw963** [emacs-helm/helm#1527]
Fine, I think helm could be instead of ido.
But, in very less case, ido is better choice, and few package only support ido.

when enable ido-everywhere feature and helm-mode.
```cl
(require 'ido)
(ido-mode t)
(ido-everywhere 1)

(require 'helm-config)
(helm-mode 1)
```
first time invoke `C-x v d`,  runs helm-mode-vc-dir.
second time invoke `C-x v d`,  use ido instead of helm.

**Comment by thierryvolpiatto** [comment]
Billy.Zheng <notifications@github.com> writes:

> Fine, I think helm could be instead of ido.
> But, in very less case, ido is better choice, and few package only support ido.
>
> when enable ido-everywhere feature and helm-mode.
>
> (require 'ido)
> (ido-mode t)
> (ido-everywhere 1)
>
> (require 'helm-config)
> (helm-mode 1)

Please stop complicating, if you want ido use ido if you want helm use
helm.

Note that when using helm you can configure conveniently which commands
you want to use with ido, but from the ido side this is not possible.
Use `helm-completing-read-handlers-alist` for this.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Now added to FAQ.
https://github.com/emacs-helm/helm/wiki/FAQ#helm-mode-conflict-with-ido-everywhere
