### ISSUE TITLE
[Feature request] switch from helm-find-files to helm-mini,  vice versa

### ISSUE THREAD

**Issue by zw963** [emacs-helm/helm#1528]
I don't found those function. 

it effect as if `helm-ff-run-browse-project` and `helm-buffers-run-browse-project`, but to `mini-buffer`.

Thanks.

**Comment by zw963** [comment]
What i means is: 

files <=> buffer switch.

it can be `helm-mini-buffer`, or `helm-buffers-list`.

**Comment by thierryvolpiatto** [comment]
Please use `C-x b` and `C-x C-b`.

**Comment by zw963** [comment]
Not work, e.g. 

1. I first run `helm-mini` want to switch to a exist buffer.
2. after input some keyword, i found those buffer not exist.
3. I want to `helm-find-files` right now.

`C-x b` or `C-x C-b` how to do this?

**Comment by zw963** [comment]
Previous problem worked, sorry. `C-x C-f`.

**Comment by zw963** [comment]
But following not worked?

1.  I first run `helm-find-files` to start a new helm session, want to open a new file.
2. after input some keyword, I think this file maybe is opened by emacs
3.  I want to use `helm-mini` as quickly as possible.
4. But, I don't found a way to do this. `C-x b` or `C-x C-b` not work.
    `helm-mini` keybinding not worked too.

Thanks.
4.

**Comment by thierryvolpiatto** [comment]
Billy.Zheng <notifications@github.com> writes:

> Not work, e.g.

No, everything is working, please learn with C-h m how to use
everything.

>  1. I first run helm-mini want to switch to a exist buffer.
>  2. after input some keyword, i found those buffer not exist.
>  3. I want to helm-find-files right now.

So hit now C-x C-f

> C-x b or C-x C-b how to do this?

These are commands to respectively resume to previous session and all resumed
sessions while in helm.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Billy.Zheng <notifications@github.com> writes:

> But following not worked?
>
>  1. I first run helm-find-files to start a new helm session, want to open a new file.
>  2. after input some keyword, I think this file maybe is opened by emacs
>  3. I want to use helm-mini as quickly as possible.
>  4. But, I don't found a way to do this. C-x b or C-x C-b not work. helm-mini keybinding not worked too.

Sorry I understand nothing at what you want to do, please provide a
clear recipe step by step.

-- 
Thierry

**Comment by michael-heerdegen** [comment]
AFAIU he wants to replace the helm-find-files session with a helm-mini session.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> AFAIU he wants to replace the helm-find-files session with a helm-mini session.

Yes, but I don't understand at which moment.
He said he created a file, so once done he is no more in hff session
AFAIU ? So the only thing to do is hitting C-x C-b from the buffer
recently created.

Otherwise from a helm-find-files session, assuming a buffer session have
been opened before, C-x b will allow switching to hff and vice versa.
If the pevious session was something else, he can use C-x C-b to choose
the session.

-- 
Thierry

**Comment by zw963** [comment]
>> AFAIU he wants to replace the helm-find-files session with a helm-mini session.

Yes. This is exactly what i want.

**Comment by zw963** [comment]
@thierryvolpiatto , Sorry for my poor and don't clear english.

>> He said he created a file, so once done he is no more in hff session AFAIU ?
What I want to said is to try open a exist file with `C-x C-f`, But suddenly remember 
this file has been opened previously, I want to switch to `helm-mini` directly.
And in this case, no previous `helm-mini` is exists. How to do this?
I think if we add a command to switch to `helm-mini` or `helm-buffers-list`
from `helm-find-files` directly in any case, maybe a better idea?

I don't know other guys how to use `helm`, But, the mostly useful command
for me is `helm-find-files`, `helm-mini`, `helm-browse-project`, if could quickly
switch from each other is more comfortable for me.  

Thanks.



I create a exact step to reproduce my problem.

**Comment by zw963** [comment]
In fact, I often press wrong keybinding when I working with emacs.
especially when I was thinking ... 

What i want is to switch to a opened buffer, but I maybe `C-x C-f` habitually.
in this case, i hope could switch each other as quickly as possible.
I maybe don't remember what previous session is, so i have to `C-g` to quit
current session, and run `helm-mini` again.

Anyone have this trouble like me?

**Comment by thierryvolpiatto** [comment]
Billy.Zheng <notifications@github.com> writes:

> In fact, I often press wrong keybinding when I working with emacs.
> especially when I was thinking ...
>
> What i want is to switch to a opened buffer, but I maybe C-x C-f
> habitually.

Perhaps change your habit and always start with C-x C-b instead of C-x
C-f ?

> in this case, i hope could switch each other as quickly as possible.
> I maybe don't remember what previous session is, so i have to C-g to quit
> current session, and run helm-mini again.

Assuming you already used a buffers session (helm-mini or whatever) you
will retrieve this session from helm-find-files with C-x C-b.

-- 
Thierry

**Comment by zw963** [comment]
> Perhaps change your habit and always start with C-x C-b instead of C-x C-f ?

Fine,I had try this, though, feel more complex for me...

Just wonder, If add a command like `helm-quit-and-helm-mini` exist technical cause?

Anywhy, we have `helm-quit-and-find-file` `helm-ff-run-browse-project`, `helm-buffer-run-browse-project`,
just missing `helm-quit-and-helm-mini`, right?
(BTW: though, I think `helm-ff-run-browse-project` and `helm-buffer-run-browse-project` shoud be merge
into one command:  `helm-quit-and-browse-project`,  for unification.

Thanks.

**Comment by michael-heerdegen** [comment]
> Anywhy, we have helm-quit-and-find-file helm-ff-run-browse-project,
> helm-buffer-run-browse-project, just missing helm-quit-and-helm-mini,
> right?

In any case it should be easy to define it yourself with means of
`helm-run-after-exit'.

**Comment by zw963** [comment]
> In any case it should be easy to define it yourself with means of `helm-run-after-exit'.

@ thierryvolpiatto, What you think about to add ``helm-quit-and-helm-mini`` ?
I think this is not a bad idea.

**Comment by thierryvolpiatto** [comment]
Billy.Zheng <notifications@github.com> writes:

>     In any case it should be easy to define it yourself with means of `helm-run-after-exit'.
>    
> @ thierryvolpiatto, What you think about to add helm-quit-and-helm-mini ?
> I think this is not a bad idea.

No, as long as we can do it differently, also using just C-g C-x C-b is
fine to me and prevent me a lot of work.

Did you try the workflow proposed ?

1) M-x helm-mini
2) C-x C-f
3) C-x b
4) C-x b
etc...

If C-x b switchs to something else, use C-x C-b to choose the source you
want (helm-mini or helm-find-files).

If all this is not enough a PR is welcome.

-- 
Thierry

**Comment by zw963** [comment]
> Did you try the workflow proposed ? 1) M-x helm-mini 2) C-x C-f 3) C-x b 4) C-x b etc...

I have use this several days. though, I bind it to others keys. thanks.

>  If all this is not enough a PR is welcome.

I try to add a PR [here](https://github.com/emacs-helm/helm/pull/1537)
Please see if enough.
