### ISSUE TITLE
Is it possible to optimize helm load (require) mechanism?

### ISSUE THREAD

**Issue by sickHamm** [emacs-helm/helm#1529]
helm own have 40+ libraries, and more dependend libraries; 
At present helm just require all (maybe)request features；like just use helm-M-x will  load 60+ libraries. Is it possible use `eval-after-load, autoload etc` to defer helm load dependend libraries; optimize load time.
	

---------------------------------------------------------------
```
[helm-command require 10ms]
 ├─[helm-elisp require 20ms]
 │ ╰─[helm-eval require 65ms]
 │   ├─[edebug require 28ms]
 │   ╰─[eldoc require 173ms]
 ├─[helm-mode require 11ms]
 │ ╰─[helm-files require 121ms]
 │   ├─[image-dired require 33ms]
 │   ├─[tramp require 138ms]
 │   │ ╰─[tramp-compat require 15ms]
 │   │   ├─[tramp-loaddefs require 270ms]
 │   │   ├─[trampver require 11ms]
 │   │   ├─[shell require 15ms]
 │   │   │ ╰─[pcomplete require 14ms]
 │   │   ╰─[format-spec require 9ms]
 │   ├─[dired-x require 231ms]
 │   ├─[dired-aux require 53ms]
 │   ├─[ffap require 97ms]
 │   ├─[thingatpt require 35ms]
 │   ├─[helm-buffers require 21ms]
 │   │ ╰─[helm-elscreen require 12ms]
 │   ├─[helm-tags require 15ms]
 │   ├─[helm-bookmark require 89ms]
 │   │ ├─[helm-adaptive require 7ms]
 │   │ ├─[helm-info require 184ms]
 │   │ ╰─[bookmark require 62ms]
 │   │   ╰─[pp require 15ms]
 │   ├─[helm-locate require 12ms]
 │   ├─[helm-grep require 52ms]
 │   │ ╰─[helm-regexp require 15ms]
 │   │   ╰─[helm-plugin require 6ms]
 │   ├─[helm-external require 6ms]
 │   │ ╰─[helm-net require 49ms]
 │   │   ├─[browse-url require 53ms]
 │   │   ├─[xml require 14ms]
 │   │   ╰─[url require 14ms]
 │   │     ├─[url-proxy require 11ms]
 │   │     ├─[url-privacy require 11ms]
 │   │     ├─[url-expand require 12ms]
 │   │     │ ╰─[url-methods require 16ms]
 │   │     ├─[url-history require 18ms]
 │   │     ├─[url-cookie require 19ms]
 │   │     │ ├─[url-domsuf require 13ms]
 │   │     │ ╰─[url-util require 17ms]
 │   │     │   ╰─[url-parse require 15ms]
 │   │     │     ╰─[auth-source require 29ms]
 │   │     │       ├─[gnus-util require 85ms]
 │   │     │       ├─[mm-util require 55ms]
 │   │     │       │ ╰─[mail-prsvr require 13ms]
 │   │     │       ╰─[password-cache require 11ms]
 │   │     ├─[url-vars require 15ms]
 │   │     ╰─[mailcap require 20ms]
 │   ├─[helm-utils require 17ms]
 │   ╰─[helm-types require 94ms]
 ├─[helm-help require 16ms]
 ╰─[helm require 110ms]
   ├─[helm-config require 13ms]
   │ ├─[helm-autoloads load 10ms]
   │ ├─[helm-easymenu require 7ms]
   │ ╰─[async-bytecomp require 7ms]
   │   ╰─[async require 7ms]
   ├─[gv require 19ms]
   ├─[helm-source require 22ms]
   │ ╰─[eieio require 81ms]
   │   ╰─[eieio-core require 27ms]
   ├─[helm-multi-match require 9ms]
   ╰─[helm-lib require 12ms]
     ╰─[dired require 78ms]
```

**Comment by zw963** [comment]
I start emacs as a daemon when I start computer (for a long to restart),
 at this time, all my need package(include helm) is loaded.

anyway, Slow is not a big deal for me, exactly opposite, I hope load 
every things I could load when the first emacs deamon is up.

**Comment by zw963** [comment]
I don't want when I press some hotkey, or open some special mode,
it need several ms to load a package. it not a good experience.

**Comment by sickHamm** [comment]
Yes. It is a program to keep balance.
But some features like`url-proxy, url-cookie, url-*,bookmark,gnus-util,mm-uti` etc, is it  really need by everyone ?  I don't think  I need use this features  at mostly time (or never).
And If there  some special features we request ready at init time  ，we could just  manual `require` at all.

**Comment by sickHamm** [comment]
Because most of emacs library has use autoload file expose extern functions,  so just  needed check  all  requested function in helm is autload object and decide is need  require feature immediately.

--------------------------------------------------------------
```
(auto-require-for-funs 'url
  '(url-hexify-string url-retrieve-synchronously))

(defun auto-require-for-funs (feature funs)
  (if (memq feature features)
      t
    (catch 'break-fun
      (mapc (lambda (fun)
	      (unless (autoloadp (symbol-function fun))
		(require feature)
		(throw 'break-fun fun)))
	    funs))))
```

**Comment by thierryvolpiatto** [comment]
>Is it possible use eval-after-load, autoload etc to defer helm load dependend libraries; optimize load >time.

Helm is already using autoloads, but when calling a helm command (they are all autoloaded) helm may requires more library than what is needed, this may be improved but it is tricky to fix all the requires order.  This is not an urgency though, helm is starting here in 0.5s (loading all in the way).
 
For `eval-after-load` it is a feature that should never be used in sources files, only in user config files,
so no I will not use it.
