### ISSUE TITLE
Duplicated hl-lock entries.

### ISSUE THREAD

**Issue by jacekmigacz** [emacs-helm/helm#1530]
When **unhighlight-regexp** is displayed in helm, every entry is shown twice.

![hi-foo](https://cloud.githubusercontent.com/assets/1120058/15865034/859411dc-2cd9-11e6-9d90-987abbcb8966.png)

**Comment by thierryvolpiatto** [comment]
Jacek Migacz <notifications@github.com> writes:

> When unhighlight-regexp is displayed in helm, every entry is shown twice.

Should fixed now.

Thanks.

-- 
Thierry

**Comment by jacekmigacz** [comment]
Works for me!

Thanks.
