### ISSUE TITLE
What happened to the old helm-ag interface? 

### ISSUE THREAD

**Issue by peterhadlaw** [emacs-helm/helm#1531]
That seemed to have a lot more features, and it was easier to interact. Definitely much faster to use too. Is there a way to enable the old method? 

Thank you in advance.

**Comment by thierryvolpiatto** [comment]
It seems you are referring to the helm-ag package which has never been part of helm.
I guess you have just uninstalled it.
Otherwise nothing have changed in helm about helm-grep ag.
