### ISSUE TITLE
Mouse jumps to the upper-right hand corner of the frame

### ISSUE THREAD

**Issue by Stebalien** [emacs-helm/helm#1538]
If `mouse-autoselect-window` is set, the mouse cursor (i.e., X11 cursor) gets moved to the upper-right hand corner of the frame (GUI) when a helm prompt is closed with ESC. This doesn't happen when the prompt is closed by selecting an action.

**Reproduction guide:**

1. Start Emacs
2. Evaluate `(setq mouse-autoselect-window t)`.
3. Open a helm prompt.
4. Hit ESC.

**Observed behaviour:**

The mouse cursor is moved to the upper-right corner of the frame.

**Expected behaviour:**

My mouse stays where I left it...

Reported downstream at https://github.com/syl20bnr/spacemacs/issues/6138

**Comment by thierryvolpiatto** [comment]
Thanks, should be fixed now.

**Comment by Stebalien** [comment]
Thanks!
