### ISSUE TITLE
helm-map load error on emacs startup

### ISSUE THREAD

**Issue by galactica147** [emacs-helm/helm#1539]
I'm have some trouble getting helm installed and configured in a machine without internet access. 
Following the manual installation instructions, i've added helm and async source files into ~/.emacs.d/ and add them into 'load-path' respectively. But i got errors when starting emacs on the following helm-map setup.

```
(require 'helm-config)
(define-key helm-map (kbd "<tab>") 'helm-execute-persistent-action) ; rebind tab to run persistent action
(define-key helm-map (kbd "C-i") 'helm-execute-persistent-action) ; make TAB works in terminal
(define-key helm-map (kbd "C-z")  'helm-select-action) ; list actions using C-z
```

emacs -nw ~/.emacs --debug-init
```
Debugger entered--Lisp error: (void-variable helm-map) 
(define-key helm-map (kbd "<tab>") (quote helm-execute-persistent-action)) 
eval-buffer(#<buffer  *load*> nil "/home/galactica/.emacs" nil t)  ; Reading at buffer position 5093
load-with-code-conversion("/home/galactica/.emacs" "/home/galactica/.emacs" t t)
```

Anyone has an idea what this happens and how to fix it?
Thanks!

**Comment by thierryvolpiatto** [comment]
What you are looking for is `with-eval-after-load`.

```elisp
(add-to-list 'load-path "~/elisp/helm")
(require 'helm-config)
(with-eval-after-load "helm.el"
  (define-key helm-map (kbd "C-c p") 'ignore))
```

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> What you are looking for is with-eval-after-load.
>
> (add-to-list 'load-path "~/elisp/helm")
> (require 'helm-config)
> (with-eval-after-load "helm.el"
>   (define-key helm-map (kbd "C-c p") 'ignore))

Maybe we could add to

   https://github.com/emacs-helm/helm/wiki#configure

that helm-config doesn't load all of helm and things like that should be
delayed with w-e-a-l or similar.

**Comment by galactica147** [comment]
Hi Thierry, 

Thanks for the suggestion! However it did not work for me -- I didn't see helm activated after rebooting Emacs. Instead if I add 'require helm-mode' ahead of the suggested config, it seems to work. 
i.e., 
```
(require 'helm-mode)
(require 'helm-config)
```

Not sure if this would disable any other helm features yet.

**Comment by thierryvolpiatto** [comment]
galactica147 <notifications@github.com> writes:

> Hi Thierry,
>
> Thanks for the suggestion! However it did not work for me

What did not work ?

> (require 'helm-mode)
> (require 'helm-config)
>
> Not sure if this would disable any other helm features yet.

No but is defeat the purpose of autoloads and the usage of
`with-eval-after-load`...


-- 
Thierry

**Comment by galactica147** [comment]
Hi Thierry,

adding the following didn't work for me, the error was as before on undefined 'helm-map' -- 

```
(add-to-list 'load-path "~/.emacs.d/helm")
 (require 'helm-config)
 (with-eval-after-load "helm.el"
   (define-key helm-map (kbd "C-c p") 'ignore))
```

**Comment by xuchunyang** [comment]
Try `(with-eval-after-load "helm" ...)` or `(with-eval-after-load 'helm ...)` instead

**Comment by thierryvolpiatto** [comment]
galactica147 <notifications@github.com> writes:

> Hi Thierry,
>
> adding the following didn't work for me,

What did not work for you? 
When describing a bug saying "don't work" means nothing useful, please
describe all what you are doing step by step.
Here the snippet below is working as expected.

> the error was as before on undefined 'helm-map' --
>
> (add-to-list 'load-path "~/.emacs.d/helm")
>  (require 'helm-config)
>  (with-eval-after-load "helm.el"
>    (define-key helm-map (kbd "C-c p") 'ignore))
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.*


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Thierry Volpiatto <notifications@github.com> writes:
>
>> What you are looking for is with-eval-after-load.
>>
>> (add-to-list 'load-path "~/elisp/helm")
>> (require 'helm-config)
>> (with-eval-after-load "helm.el"
>> (define-key helm-map (kbd "C-c p") 'ignore))
>
> Maybe we could add to
>
> https://github.com/emacs-helm/helm/wiki#configure
>
> that helm-config doesn't load all of helm and things like that should be
> delayed with w-e-a-l or similar.

Yes sure, go ahead if you want (the wiki is editable).

-- 
Thierry

**Comment by galactica147** [comment]
ok, let me clarify again. this time I started emacs in a clean env WITH internet access by setting HOME to some new dir. The plan is to setup helm there and copy it over to the restricted env. 

In this new .emacs file, after running `make` under `/path/to/new/dir/.emacs.d/helm-src/helm/` as suggested by the installation manual i put the following:

```
(add-to-list 'load-path "/path/to/new/dir/.emacs.d/helm-src/helm/")
(require 'helm-config)
(with-eval-after-load "helm.el"
  (define-key helm-map (kbd "C-c p") 'ignore))

(require 'helm-config)
(define-key helm-map (kbd "<tab>") 'helm-execute-persistent-action) ; rebind tab to run persistent action
(define-key helm-map (kbd "C-i") 'helm-execute-persistent-action) ; make TAB works in terminal
(define-key helm-map (kbd "C-z")  'helm-select-action) ; list actions using C-z
```

As the installation manual suggests, i put async/ under `/path/to/new/dir/.emacs.d/helm-src/` too. 
Then i run emacs and got the following error message:

`Symbol's value as variable is void: helm-map`

let me know if I can clarify further.
Thanks!

**Comment by xuchunyang** [comment]
You need to wrap all `helm-map` in `(with-eval-after-load ...)`, i.e.,

``` elisp
(with-eval-after-load 'helm
  (define-key helm-map (kbd "C-c p") 'ignore)
  (define-key helm-map (kbd "<tab>") 'helm-execute-persistent-action) ; rebind tab to run persistent action
  (define-key helm-map (kbd "C-i") 'helm-execute-persistent-action) ; make TAB works in terminal
  (define-key helm-map (kbd "C-z")  'helm-select-action))
```

**Comment by galactica147** [comment]
Thank you Chunyang! That seems fixed the error! 
-
Jin

**Comment by michael-heerdegen** [comment]
Ahh, with-eval-after-load "helm.el" just doesn't match when you load the compiled file, that's why it didn't work.  "helm" should work exactly the same as 'helm OTOH.
