### ISSUE TITLE
A detail: How to indicate candidate number in the mode-line

### ISSUE THREAD

**Issue by michael-heerdegen** [emacs-helm/helm#1546]
Hi,

we currently use
```
(:eval (format "L%-3d" (helm-candidate-number-at-point)))
```
(see `helm-display-mode-line`).

This is a bit confusing: the number is not a line count but about the number of the currently selected candidate.

I suggest to replace the letter "L" by something better. "C" is probably not better (unclear what it means, and could be misunderstood as "column"); "Cand" is too long.  Just "#" maybe (meaning "number")?

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> I suggest to replace the letter "L" by something better.

I don't think there is something better, at least with only one letter,
also I don't think "L" is confusing, everybody understood that it is
(L)ine number of current source. 

-- 
Thierry
