### ISSUE TITLE
Wrong type argument error with helm-imenu-in-all-buffers

### ISSUE THREAD

**Issue by fniessen** [emacs-helm/helm#1547]
When calling M-x helm-imenu (or M-x helm-imenu-on-all-buffers) on this Java file:

    // ee: package declaration
    package application.helloworld;
    // ee: package declaration
    import java.util.Locale;
    import java.util.MissingResourceException;
    import java.util.ResourceBundle;

    /**
     * HelloWorld.java
     */

    public class HelloWorld
    {
        // be: specific constructor
        public HelloWorld()
        {
            System.out.println("Object HelloWorld created");
        } // end of specific constructor "HelloWorld()"
        // ee: specific constructor

        public static final void main(final String[] args)
        {
            String baseName = "HelloWorld";
            ResourceBundle rb = ResourceBundle.getBundle(baseName);
            String greetings = rb.getString("hello_msg");
            System.out.printf("%s\n", greetings);
        } // end of method "main(String[] args)"
    } // end of class "HelloWorld"

I get:

    Error: (wrong-type-argument symbolp #<overlay from 451 to 502 in listings-ext_exmpl_b.java>)

What could be wrong?

Helm version helm-20160616.217 (from MELPA).
Emacs 24.5.1.

**Comment by thierryvolpiatto** [comment]
From M-x imenu I have an error and with helm I have no error but an empty buffer, what extension are you using for your file?

**Comment by thierryvolpiatto** [comment]
No, sorry I was using a wrong extension for this source code, so when using a *.java extension it is working fine:

![screenshot - 23062016 - 12 57 06](https://cloud.githubusercontent.com/assets/1533939/16300829/3bf1b9ba-3942-11e6-8814-c3ab2f17e283.png)

**Comment by fniessen** [comment]
Happy bisecting, then?  Thanks for looking at it, anyway.
