### ISSUE TITLE
Tab completion not working with `Find File At Point`

### ISSUE THREAD

**Issue by domi91c** [emacs-helm/helm#1549]
When I hit tab to complete a directory name within the `Find File At Point` Helm session, nothing happens. Tab completion works fine in `Find Files` so I'm not sure what the problem is.

**Comment by thierryvolpiatto** [comment]
Dominic Nunes <notifications@github.com> writes:

> When I hit tab to complete a directory name within the Find File At
> Point Helm session, nothing happens. Tab completion works fine in Find
> Files, so I'm not sure what the problem is.

Read
https://github.com/emacs-helm/helm/wiki#helm-completion-vs-emacs-completion
and https://github.com/emacs-helm/helm/wiki#helm-interaction-model.

-- 
Thierry
