### ISSUE TITLE
Start helm is very slowly in some special case.

### ISSUE THREAD

**Issue by zw963** [emacs-helm/helm#1550]
Hi, I found in some special case, use helm(e.g. run helm-mini) is very
slowly for me, following is some description for this.

### 5.  If those four window with a buffer which enable linum-mode, it impact the performance too. though, seem like not so bad than golden-raito.

With all above condition satisfied, when I run `helm-mini`, need to 3 second to popup helm-mini window.

I think this not the problem caused by helm maybe,  just for report here, and want to know anyone else
if encounter same case like me.

Thanks.

**Comment by zw963** [comment]
Just want to report, I switch from `linum-mode` to `nlinum-mode`, performance is better. 

And I create a issue [here](https://github.com/roman/golden-ratio.el/issues/69) for golden-ratio too.

**Comment by thierryvolpiatto** [comment]
Billy.Zheng <notifications@github.com> writes:

> Hi, I found in some special case, use helm(e.g. run helm-mini) is very
> slowly for me, following is some description for this.
>
> 1. config helm as default
>
> 2. setting helm to use popwin, to make helm always popup from bottom

Not needed.

> 3. open four window in current frame. (If only two window, Performance loss is not so bad)
>
> 4. use golden-ratio package, this package heavy
>
>        impact the performance of helm-mini

When set correctly golden-ratio have no impact on helm, but I guess
there is some conflict probably with popwin (I don't use popwin, so I
only guess, not affirm).

(use-package golden-ratio
    ;; :disabled t
    :diminish golden-ratio-mode
    :init
  (progn
    (add-hook 'ediff-before-setup-windows-hook (lambda () (golden-ratio-mode -1)))
    (add-hook 'ediff-quit-hook (lambda () (golden-ratio-mode 1))))
  :config
  (progn
    (defun helm/running-p () helm-alive-p)
    (defun tv/ispell-running-p ()
      (and (boundp 'ispell-choices-buffer)
           (get-buffer ispell-choices-buffer)))
    (setq golden-ratio-inhibit-functions     '(helm/running-p tv/ispell-running-p))
    (setq golden-ratio-exclude-buffer-regexp '("\\`\\*[Hh]elm.*\\*\\'"))
    (setq golden-ratio-exclude-buffer-names  '("*Org Select*"))
    (setq golden-ratio-exclude-modes         '(ediff-mode calendar-mode wget-mode))
    (setq golden-ratio-recenter              t)
    (golden-ratio-mode 1)))

> 5. If those four window with a buffer which enable linum-mode, it impact the performance too.
>
>         though, seem like not so bad than golden-raito.
>
> With all above condition satisfied, when I run helm-mini, need to 3
> second to popup helm-mini window.

And probably any other window unrelated to helm (i.e probably conflict with popwin).

> I think this not the problem caused by helm maybe,

It is not.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Billy.Zheng <notifications@github.com> writes:

> Just want to report, I switch from linum-mode to nlinum-mode,
> performance is better.

Use linum-relative which is supported by helm (it have a special mode to
start in helm) other *linum* packages are badly supported in helm.

-- 
Thierry

**Comment by zw963** [comment]
@thierryvolpiatto , Thanks for your's golden-ratio config, I will test it after a while.



> Use linum-relative which is supported by helm (it have a special mode to start in helm) other *linum* packages are badly supported in helm.

I think my english describe is not accurate ..
Do you think I enable linum-mode in helm-buffer??
What I want to say is:  one emacs frame which with four window opened, those window open buffers which linum-mode is enabled, I does not enable linum-mode globallly. I just enable it in `prog-mode-hook`,  I think all four buffer is linum-mode is enabled, and so, slow down the helm buffer (which opened by popwin as fifth window) 

following is a Picture,  when I press `helm-mini` shortcut, before helm-mini buffer is popup,
exist a considerable delay.

![Screenshot at 2016-06-25 16:21:41.png](http://zw963.github.io/212063027231334.png)

**Comment by zw963** [comment]
> following is a Picture, when I press helm-mini shortcut, before helm-mini buffer is popup,
> exist a considerable delay.

If current frame only one window is opened, popup helm-mini window performance is very well.

With those detail report, do you think linum-relative is still better than linum for helm, anywhy,
I am not enable linum-mode in helm buffer?

**Comment by thierryvolpiatto** [comment]
As I said, it is up to you to find a better configuration, not only for
helm but more generally for your emacs, actually you are additionning
all the features that slow down emacs and its windowing system.

- linum-mode => slow and ineficient
- popwin     => unuseful 

And perhaps other things I am not aware of.

I can't do something for you on helm side, here with a reasonable
configuration, helm popup instantly with four windows open.
(for helm-mini, I have constantly between 80 to 200 buffers open)

-- 
Thierry

**Comment by zw963** [comment]
>> - linum-mode => slow and ineficient

Comment here for someone need a more efficient linum-mode [nlinum-mode](http://elpa.gnu.org/packages/nlinum.html), but found this mode not worked with emacs daemon mode(emacsclient).

Following code make my emacs 24.5.1 start as daemon worked very well with nlinum-mode for now.

```cl
(defun initialize-nlinum (&optional frame)
  (require 'nlinum)
  (add-hook 'prog-mode-hook 'nlinum-mode))
(when (daemonp)
  (add-hook 'window-setup-hook 'initialize-nlinum)
  (defadvice make-frame (around toggle-nlinum-mode compile activate)
  (nlinum-mode -1) ad-do-it (nlinum-mode 1)))
```

**Comment by thierryvolpiatto** [comment]
This have nothing to do with helm, so I am closing now.

**Comment by zw963** [comment]
After some adjust for `golden-raito` and swith to `nlinum-mode`,  Helm is worked much faster than before.
Thanks for help.

**Comment by zw963** [comment]
Although too late, l just want to say: 

1. for emacs 25, `linum-mode` performance is better, i switch back to use it.

2.  the speed is slow mostly because i use `popwin` to pop helm buffer, if not use it, problem is gone.
