### ISSUE TITLE
Error: wrong type of argument integer or marker when executing helm-imenu

### ISSUE THREAD

**Issue by emacsuser123** [emacs-helm/helm#1552]
Hi.

Whenever I execute helm-imenu on my c file, I get the following error:

> In `Imenu' source: `helm-imenu-candidates' 
>  (wrong-type-argument integer-or-marker-p #<overlay from 1446 to 1500 in queue.c>)
> 

However, if I run helm-imenu-anywhere, it executes ok, without any problem.

Below you can find the associated backtrace.

thanks,
-Bob

> Debugger

>  entered--Lisp error: (wrong-type-argument integer-or-marker-p #<overlay from 1446 to 1500 in queue.c>)
>   copy-marker(#<overlay from 1446 to 1500 in queue.c>)
>   helm-imenu--candidates-1(((#("getQr=" 0 6 (helm-imenu-type "Variables")) . #<overlay from 1446 to 1500 in queue.c>) (#("getResponseCode=" 0 16 (helm-imenu-type "Variables")) . #<overlay from 1623 to 1944 in queue.c>) (#("getRedisReplyCode=" 0 18 (helm-imenu-type "Variables")) . #<overlay from 1946 to 2265 in queue.c>) (#("getRedisErrorCode=" 0 18 (helm-imenu-type "Variables")) . #<overlay from 2267 to 2570 in queue.c>)))
>   helm-imenu--candidates-1((("Variables" ("getQr=" . #<overlay from 1446 to 1500 in queue.c>) ("getResponseCode=" . #<overlay from 1623 to 1944 in queue.c>) ("getRedisReplyCode=" . #<overlay from 1946 to 2265 in queue.c>) ("getRedisErrorCode=" . #<overlay from 2267 to 2570 in queue.c>)) ("Functions" ("printHexMemory()" . #<overlay from 513 to 746 in queue.c>) ("printUserIpList()" . #<overlay from 748 to 924 in queue.c>) ("printEvents()" . #<overlay from 926 to 1268 in queue.c>) ("getIpProto()" . #<overlay from 1316 to 1444 in queue.c>) ("getOneQuerySectionLength()" . #<overlay from 2572 to 3191 in queue.c>) ("getTotalQuerySectionLength()" . #<overlay from 3193 to 3558 in queue.c>) ("getOneAnswerSectionDomain()" . #<overlay from 3560 to 5037 in queue.c>) ("release()" . #<overlay from 5039 to 5641 in queue.c>) ("processPkt()" . #<overlay from 7959 to 20093 in queue.c>) ("cb()" . #<overlay from 20095 to 20293 in queue.c>) ("initRestarts()" . #<overlay from 20295 to 21430 in queue.c>) ("init()" . #<overlay from 21432 to 27330 in queue.c>) ("main()" . #<overlay from 27332 to 32714 in queue.c>)) ("Includes" ("stdio.h<>" . #<overlay from 1 to 19 in queue.c>) ("stdlib.h<>" . #<overlay from 20 to 39 in queue.c>) ("errno.h<>" . #<overlay from 40 to 58 in queue.c>) ("unistd.h<>" . #<overlay from 59 to 78 in queue.c>) ("string.h<>" . #<overlay from 79 to 98 in queue.c>) ("sys/param.h<>" . #<overlay from 99 to 121 in queue.c>) ("netinet/in.h<>" . #<overlay from 122 to 145 in queue.c>) ("linux/types.h<>" . #<overlay from 146 to 170 in queue.c>) ("linux/netfilter.h<>" . #<overlay from 171 to 199 in queue.c>) ("arpa/inet.h<>" . #<overlay from 229 to 251 in queue.c>) ("time.h<>" . #<overlay from 252 to 269 in queue.c>) ("pthread.h<>" . #<overlay from 270 to 290 in queue.c>) ("libnetfilter_queue/libnetfilter_queue.h<>" . #<overlay from 292 to 342 in queue.c>) ("hiredis/hiredis.h<>" . #<overlay from 343 to 371 in queue.c>) ("libconfig.h<>" . #<overlay from 372 to 394 in queue.c>) ("queue.h<>" . #<overlay from 396 to 414 in queue.c>))))
>   helm-imenu-candidates()
>   apply(helm-imenu-candidates nil)
>   helm-funcall-with-source(((name . "Imenu") (candidates . helm-imenu-candidates) (keymap keymap (right . helm-execute-persistent-action) (left . helm-maybe-exit-minibuffer) (M-up . helm-imenu-previous-section) (M-down . helm-imenu-next-section) keymap (f13 lambda nil (interactive) (helm-select-nth-action 12)) (f12 lambda nil (interactive) (helm-select-nth-action 11)) (f11 lambda nil (interactive) (helm-select-nth-action 10)) (f10 lambda nil (interactive) (helm-select-nth-action 9)) (f9 lambda nil (interactive) (helm-select-nth-action 8)) (f8 lambda nil (interactive) (helm-select-nth-action 7)) (f7 lambda nil (interactive) (helm-select-nth-action 6)) (f6 lambda nil (interactive) (helm-select-nth-action 5)) (f5 lambda nil (interactive) (helm-select-nth-action 4)) (f4 lambda nil (interactive) (helm-select-nth-action 3)) (f3 lambda nil (interactive) (helm-select-nth-action 2)) (f2 lambda nil (interactive) (helm-select-nth-action 1)) (menu-bar keymap (help-menu keymap (describe keymap (describe-mode . helm-help)))) (help keymap (109 . helm-help)) (f1 lambda nil (interactive) (helm-select-nth-action 0)) (8 keymap (109 . helm-help) (104 . undefined) (8 . undefined) (4 . helm-enable-or-switch-to-debug)) (20 . helm-toggle-resplit-and-swap-windows) (C-tab . undefined) (67108897 . helm-toggle-suspend-update) (3 keymap (57 lambda nil (interactive) (helm-execute-selection-action-at-nth 9)) (56 lambda nil (interactive) (helm-execute-selection-action-at-nth 8)) (55 lambda nil (interactive) (helm-execute-selection-action-at-nth 7)) (54 lambda nil (interactive) (helm-execute-selection-action-at-nth 6)) (53 lambda nil (interactive) (helm-execute-selection-action-at-nth 5)) (52 lambda nil (interactive) (helm-execute-selection-action-at-nth 4)) (51 lambda nil (interactive) (helm-execute-selection-action-at-nth 3)) (50 lambda nil (interactive) (helm-execute-selection-action-at-nth 2)) (49 lambda nil (interactive) (helm-execute-selection-action-at-nth 1)) (63 . helm-help) (62 . helm-toggle-truncate-line) (21 . helm-refresh) (6 . helm-follow-mode) (9 . helm-copy-to-buffer) (11 . helm-kill-selection-and-quit) (25 . helm-yank-selection) (45 . helm-swap-windows)) (67108987 . helm-enlarge-window) (67108989 . helm-narrow-window) (19 . undefined) (18 . undefined) (23 . helm-yank-text-at-point) (24 keymap (57 lambda nil (interactive) (helm-execute-selection-action-at-nth -9)) (56 lambda nil (interactive) (helm-execute-selection-action-at-nth -8)) (55 lambda nil (interactive) (helm-execute-selection-action-at-nth -7)) (54 lambda nil (interactive) (helm-execute-selection-action-at-nth -6)) (53 lambda nil (interactive) (helm-execute-selection-action-at-nth -5)) (52 lambda nil (interactive) (helm-execute-selection-action-at-nth -4)) (51 lambda nil (interactive) (helm-execute-selection-action-at-nth -3)) (50 lambda nil (interactive) (helm-execute-selection-action-at-nth -2)) (49 lambda nil (interactive) (helm-execute-selection-action-at-nth -1)) (2 . helm-resume-list-buffers-after-quit) (98 . helm-resume-previous-session-after-quit) (6 . helm-quit-and-find-file)) (11 . helm-delete-minibuffer-contents) (67108896 . helm-toggle-visible-mark) (0 . helm-toggle-visible-mark) (C-M-up . helm-scroll-other-window-down) (C-M-down . helm-scroll-other-window) (M-prior . helm-scroll-other-window-down) (M-next . helm-scroll-other-window) (12 . helm-recenter-top-bottom-other-window) (15 . helm-next-source) (10 . helm-execute-persistent-action) (26 . helm-execute-persistent-action) (9 . helm-select-action) (13 . helm-maybe-exit-minibuffer) (left . helm-previous-source) (right . helm-next-source) (7 . helm-keyboard-quit) (22 . helm-next-page) ...) (action . helm-imenu-action) (persistent-action . helm-imenu-persistent-action) (persistent-help . "Show this entry") (help-message . helm-imenu-help-message) (candidate-transformer . helm-imenu-transformer) (filtered-candidate-transformer helm-flx-fuzzy-matching-sort helm-fuzzy-highlight-matches) (match helm-mm-exact-match helm-mm-match helm-fuzzy-match) (fuzzy-match) (header-line . "C-j: Show this entry (keeping session)") (dont-plug helm-compile-source--multi-match helm-compile-source--persistent-help helm-compile-source--migemo) (matchplugin)) helm-imenu-candidates)
>   helm-interpret-value(helm-imenu-candidates ((name . "Imenu") (candidates . helm-imenu-candidates) (keymap keymap (right . helm-execute-persistent-action) (left . helm-maybe-exit-minibuffer) (M-up . helm-imenu-previous-section) (M-down . helm-imenu-next-section) keymap (f13 lambda nil (interactive) (helm-select-nth-action 12)) (f12 lambda nil (interactive) (helm-select-nth-action 11)) (f11 lambda nil (interactive) (helm-select-nth-action 10)) (f10 lambda nil (interactive) (helm-select-nth-action 9)) (f9 lambda nil (interactive) (helm-select-nth-action 8)) (f8 lambda nil (interactive) (helm-select-nth-action 7)) (f7 lambda nil (interactive) (helm-select-nth-action 6)) (f6 lambda nil (interactive) (helm-select-nth-action 5)) (f5 lambda nil (interactive) (helm-select-nth-action 4)) (f4 lambda nil (interactive) (helm-select-nth-action 3)) (f3 lambda nil (interactive) (helm-select-nth-action 2)) (f2 lambda nil (interactive) (helm-select-nth-action 1)) (menu-bar keymap (help-menu keymap (describe keymap (describe-mode . helm-help)))) (help keymap (109 . helm-help)) (f1 lambda nil (interactive) (helm-select-nth-action 0)) (8 keymap (109 . helm-help) (104 . undefined) (8 . undefined) (4 . helm-enable-or-switch-to-debug)) (20 . helm-toggle-resplit-and-swap-windows) (C-tab . undefined) (67108897 . helm-toggle-suspend-update) (3 keymap (57 lambda nil (interactive) (helm-execute-selection-action-at-nth 9)) (56 lambda nil (interactive) (helm-execute-selection-action-at-nth 8)) (55 lambda nil (interactive) (helm-execute-selection-action-at-nth 7)) (54 lambda nil (interactive) (helm-execute-selection-action-at-nth 6)) (53 lambda nil (interactive) (helm-execute-selection-action-at-nth 5)) (52 lambda nil (interactive) (helm-execute-selection-action-at-nth 4)) (51 lambda nil (interactive) (helm-execute-selection-action-at-nth 3)) (50 lambda nil (interactive) (helm-execute-selection-action-at-nth 2)) (49 lambda nil (interactive) (helm-execute-selection-action-at-nth 1)) (63 . helm-help) (62 . helm-toggle-truncate-line) (21 . helm-refresh) (6 . helm-follow-mode) (9 . helm-copy-to-buffer) (11 . helm-kill-selection-and-quit) (25 . helm-yank-selection) (45 . helm-swap-windows)) (67108987 . helm-enlarge-window) (67108989 . helm-narrow-window) (19 . undefined) (18 . undefined) (23 . helm-yank-text-at-point) (24 keymap (57 lambda nil (interactive) (helm-execute-selection-action-at-nth -9)) (56 lambda nil (interactive) (helm-execute-selection-action-at-nth -8)) (55 lambda nil (interactive) (helm-execute-selection-action-at-nth -7)) (54 lambda nil (interactive) (helm-execute-selection-action-at-nth -6)) (53 lambda nil (interactive) (helm-execute-selection-action-at-nth -5)) (52 lambda nil (interactive) (helm-execute-selection-action-at-nth -4)) (51 lambda nil (interactive) (helm-execute-selection-action-at-nth -3)) (50 lambda nil (interactive) (helm-execute-selection-action-at-nth -2)) (49 lambda nil (interactive) (helm-execute-selection-action-at-nth -1)) (2 . helm-resume-list-buffers-after-quit) (98 . helm-resume-previous-session-after-quit) (6 . helm-quit-and-find-file)) (11 . helm-delete-minibuffer-contents) (67108896 . helm-toggle-visible-mark) (0 . helm-toggle-visible-mark) (C-M-up . helm-scroll-other-window-down) (C-M-down . helm-scroll-other-window) (M-prior . helm-scroll-other-window-down) (M-next . helm-scroll-other-window) (12 . helm-recenter-top-bottom-other-window) (15 . helm-next-source) (10 . helm-execute-persistent-action) (26 . helm-execute-persistent-action) (9 . helm-select-action) (13 . helm-maybe-exit-minibuffer) (left . helm-previous-source) (right . helm-next-source) (7 . helm-keyboard-quit) (22 . helm-next-page) ...) (action . helm-imenu-action) (persistent-action . helm-imenu-persistent-action) (persistent-help . "Show this entry") (help-message . helm-imenu-help-message) (candidate-transformer . helm-imenu-transformer) (filtered-candidate-transformer helm-flx-fuzzy-matching-sort helm-fuzzy-highlight-matches) (match helm-mm-exact-match helm-mm-match helm-fuzzy-match) (fuzzy-match) (header-line . "C-j: Show this entry (keeping session)") (dont-plug helm-compile-source--multi-match helm-compile-source--persistent-help helm-compile-source--migemo) (matchplugin)))
>   #[0 "\302\203 
>

**Comment by thierryvolpiatto** [comment]
emacsuser123 <notifications@github.com> writes:

> Hi.
>
> Whenever I execute helm-imenu on my c file, I get the following error:
>
>     In Imenu' source:helm-imenu-candidates'
>     (wrong-type-argument integer-or-marker-p #)
>    
> However, if I run helm-imenu-anywhere, it executes ok, without any problem.
>
> Below you can find the associated backtrace.

Thanks, could you provide the c file or a link to it so that I can
reproduce?


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
emacsuser123 <notifications@github.com> writes:

> However, if I run helm-imenu-anywhere

Note that you can use helm-imenu-in-all-buffers and you don't need
external package providing helm-imenu-anywhere.

Also I failed to reproduce your bug with several C files.

-- 
Thierry

**Comment by emacsuser123** [comment]
Hi.

Thanks for the folllowup on this...

I can reproduce the problem even with a minimal c program like the following:

> #include <stdio.h>
> #include <stdlib.h>
> 
> int main(int argc, char **argv) {
> printf("This is a test\n");
> 
> exit 0;
> }
> 
> 

Now I also have problems with helm-imenu-anywhere, and the plain imenu-anywhere.
The function helm-imenu-in-all-buffers also fails.
The only one that goes OK is the plain imenu.
When I execute imenu-anywhere it says that Symbol's values as variable is void: for.
When I execute helm-imenu-anywhere it says: In 'imenu-anywere' source: 'helm-imenu-anywhere-candidates' (void-variable for)
When I execute helm-imenu-in-all-buffers it says: In 'Imenu in all buffers' source: 'helm-imenu-candidate-in-all-buffers' (wrong-type-argument integer-or-marker-p #overlay from 41 to 124 in test.c>)

It is unclear to me what you mean to say when you mention that I don't need external package providing helm-imenu-anywhere.

My init file does:  

> (use-package imenu-anywhere
>    :bind ("C-x c w") . helm-imenu-anywhere)
> 

And, in the use-package helm declaration, I use:

> setq helm-imenu-fuzzy-match  t

Those above are the only helm-imenu related statements.

thanks a lot.
-Bob

**Comment by emacsuser123** [comment]
I think that the "external package" you were referring to was precisely the "imenu-anywhere" package.

OK, I have removed it entirely from my init file, but the problem is still there with helm-imenu and helm-imenu-in-all-buffers.

Not sure what else to do ...

Thanks.
-Bob

**Comment by emacsuser123** [comment]
However, helm-semantic-or-imenu works perfectly.  I suppose it uses the semantic part, which works smoothly.

**Comment by thierryvolpiatto** [comment]
emacsuser123 <notifications@github.com> writes:

> Hi.
>
> Thanks for the folllowup on this...
>
> I can reproduce the problem even with a minimal c program like the following:
>
>     #include
>     #include
>    
>     int main(int argc, char **argv) {
>     printf("This is a test\n");
>    
>     exit 0;
>     }

Unable to reproduce with your sample file.
    
> Now I also have problems with helm-imenu-anywhere, and the plain
> imenu-anywhere.

helm-imenu-anywhere is not part of helm.

> The function helm-imenu-in-all-buffers also fails.

Not here, works as expected, please start from ./emacs-helm.sh.

> It is unclear to me what you mean to say when you mention that I don't
> need external package providing helm-imenu-anywhere.

As said above:
helm-imenu-anywhere is not part of helm.

It seems you have a problem in your helm installation, some of the
errors you see are related to cl-lib not loaded, so please check your
installation and stats with a minimal installation.

-- 
Thierry

**Comment by emacsuser123** [comment]
Thanks.

Using the minimal installation (emacs-helm.sh), both helm-imenu and helm-imenu-in-all-buffers work perfectly.

In regards to my current deployment (not minimal):
I have found a reproducible workflow that could shed some light:

- I do:  rm -rf helm and helm-core package directories.
- I open emacs: helm and helm-core packages get installed again.
- Now, helm-imenu and helm-imenu-in-all-buffers work OK.
- I exit emacs.
- When I restart emacs, now neither helm-imenu nor helm-imenu-in-all-buffers do not work.

Thanks.
-Bob

**Comment by thierryvolpiatto** [comment]
emacsuser123 <notifications@github.com> writes:

> Thanks.
>
> Using the minimal installation (emacs-helm.sh), both helm-imenu and
> helm-imenu-in-all-buffers work perfectly.

Good, now we know it is not an helm bug.

> In regards to my current deployment (not minimal):
> I have found a reproducible workflow that could shed some light:
>
>   * I do: rm -rf helm and helm-core package directories.
>   * I open emacs: helm and helm-core packages get installed again.

I guess because of :ensure t in your use-package snippet.

>   * Now, helm-imenu and helm-imenu-in-all-buffers work OK.

With :ensure use-package install and load your packages.

>   * I exit emacs.
>   * When I restart emacs, now neither helm-imenu nor
>   helm-imenu-in-all-buffers do not work.

And not only these ones I think.
Do you have `(package-initialize)` on top of your .emacs ?

If you don't have this emacs will not be aware of all packages inside
elpa directory.

So depending on what you have in your config, some library are loaded
and others not (not sure but I guess it is helm-core in your case).

-- 
Thierry

**Comment by emacsuser123** [comment]
Hi.

Well, yes, I use use-.package-always-ensure set to true, so that any package loaded by use-package is always installed, if needed.

Yes, I execute package-initialize on top of my emacs init file.

I was just trying to explain that, given that the first time helm/helm-core packages are installed makes the helm-imenu functionality to work perfectly, but not for the subsequent restarts, that gives an idea on where the problem is:  somehow, there must be something done when the package is initially installed or so that is not done on subsequent loads, so that it is different when you install the package and when you do not.
I suspect some of my helm-related packages (helm-ag, helm-gtags, ...) is somehow clashing with helm-core, driving it mad.

I will remove all my helm-related packages, will leave only helm/helm-core and then installed each of the remaining ones one by one, so that I can identify which one is clashing with helm-core.

I will keep you informed.

Thanks  a lot.
-Bob
