### ISSUE TITLE
helm preselect and helm-source-buffers-list with truncation.

### ISSUE THREAD

**Issue by Bad-ptr** [emacs-helm/helm#1555]
Create 2 buffers: one with name `foobar` and another with name `foobaz`.
Then set the helm-buffer-max-length: `(setq helm-buffer-max-length 3)`.

Then there is no way to preselect predictable one of them:
```elisp
(helm :sources helm-mini-default-sources
               :fuzzy-match helm-mode-fuzzy-match
               :buffer "*helm mini*"
               :keymap helm-buffer-map
               :truncate-lines helm-buffers-truncate-lines
               :default "foobaz"
               :preselect (substring "foobaz" 0 (min (string-width "foobaz") (or helm-buffer-max-length 1000)))) ;; without substring it doesn't work or it will preselect element from recentf source
```
Is it possible to do something about it ? (the workaround is to set the helm-buffer-max-length to nil).
Also I think it will be convenient that if the :preselect argument is not given but :default is, then the default should be preselected.

**Comment by thierryvolpiatto** [comment]
Constantin Kulikov <notifications@github.com> writes:

> Is it possible to do something about it ?

No, this is not specific to helm, but more generally to regexp searching
in emacs, i.e (re-search-forward "foobaz") in a buffer containing only
"foo...".

Perhaps I can help if you tell me what you want to do exactly.

-- 
Thierry

**Comment by Bad-ptr** [comment]
> No, this is not specific to helm, but more generally to regexp searching
in emacs, i.e (re-search-forward "foobaz") in a buffer containing only
"foo...".

Ok, maybe the truncation could be done as the `hs-minor-mode` does it for hiding blocks, or like in `prettify-symbols-mode`. How difficult it will be to implement that? Must I try to code it or it will be better to just forget about that minor issue)?

> what you want to do exactly

Nothing special), just want to preselect a buffer and it generally works, but sometimes it preselects a wrong one.

**Comment by thierryvolpiatto** [comment]
Constantin Kulikov <notifications@github.com> writes:

>     No, this is not specific to helm, but more generally to regexp searching
>     in emacs, i.e (re-search-forward "foobaz") in a buffer containing only
>     "foo...".
>    
> Ok, maybe the truncation could be done as the hs-minor-mode does it
> for hiding blocks, or like in prettify-symbols-mode. How difficult it
> will be to implement that?  Must I try to code it or it will be better
> to just forget about that minor issue)?

Please forget it, I don't know how these modes are implemented, we have
something working fine no need to introduce new bugs for fixing
an issue which is not really one, also modifying how buffers are
truncated and the display of details would be a lot of work for a very
small benefit.

> Nothing special), just want to preselect a buffer and it generally
> works, but sometimes it preselects a wrong one.

If you really need to preselect a specific buffer (don't know why one
would want to do this though) you can customize `helm-buffer-details-flag`
and once helm is started with your buffer preselected hit `C-]`.

-- 
Thierry

**Comment by Bad-ptr** [comment]
> I don't know how these modes are implemented

I think they are using overlays or something similar.

> If you really need to preselect a specific buffer (don't know why one would want to do this though)

By default the selection is on the current buffer, but only if it is in the first source. If the current buffer is not in the first source then a buffer from the first source is selected which is not the current one. And I just want to always preselect the current buffer even if it is not in the first source.

Well don't bother too much about that). It is not urgent. I'll take a look if I can do something about it and if I'll find a good solution I will let you know.

**Comment by thierryvolpiatto** [comment]
Constantin Kulikov <notifications@github.com> writes:

> By default the selection is on the current buffer, but only if it is
> in the first source. If the current buffer is not in the first source
> then a buffer from the first source is selected which is not the
> current one. And I just want to always preselect the current buffer
> even if it is not in the first source.

So forget preselection and have a look at ido-make-buffer-list-hook
to override current buffer list (arrange to move current-buffer on top).

-- 
Thierry

**Comment by Bad-ptr** [comment]
I have found that :preselect argument can by a function:
https://github.com/emacs-helm/helm/blob/master/helm.el#L4258
So, I think this issue could be solved like this:
```elisp
(defun my/-helm-mini ()
      (interactive)
      (let* ((cbuf (current-buffer))
             (cbuf-name (buffer-name cbuf))
             helm-candidate-number-limit)
        (or
         (helm :sources helm-mini-default-sources
               :ff-transformer-show-only-basename nil
               :fuzzy-match helm-mode-fuzzy-match
               :buffer "*my helm mini*"
               :keymap helm-buffer-map
               :truncate-lines helm-buffers-truncate-lines
               :default cbuf-name
               :preselect #'(lambda ()
                              (let ((buffer-name-truncated-regexp (helm-buffers--quote-truncated-buffer cbuf))
                                    (beginning-source (helm-get-current-source))
                                    (start (point)) mp)
                                (helm-awhile (re-search-forward buffer-name-truncated-regexp nil t)
                                  (when (helm-pos-header-line-p) (forward-line 1))
                                  (helm-mark-current-line)
                                  (when (eq cbuf (helm-get-selection)) (cl-return (setq mp it))))
                                (goto-char (or mp start))
                                (helm-mark-current-line))))
         (helm-mode--keyboard-quit))))
```
Another issue is that current buffer may be not selected because the buffer position is beyond the `helm-candidate-number-limit` in the list so it needs to be set to nil.

**Comment by thierryvolpiatto** [comment]
>I have found that :preselect argument can by a function:

Indeed, added to docstring.

Closing now.

Thanks.
