### ISSUE TITLE
Trying to implement "helm-completing-read-with-cands-in-buffer-no-move-to-first-cand"

### ISSUE THREAD

**Issue by farva** [emacs-helm/helm#1557]
Basically, I would like to have a **_helm-completing-read_** handler that will act like the helm completion when using "_*helm-mode-dired*_", but not only for file sources.
Narrow candidates, but not choosing any one of them implicitly as the helm buffer updates with my inputs, as opposed to the behavior of **_helm-completing-read-with-cands-in-buffer_**.

I thought it would be a walk in the park, and probably it is, but I'm lost.
If anyone can give me pointers to the right direction, It would really be great.

**Comment by thierryvolpiatto** [comment]
farva <notifications@github.com> writes:

> Basically, I would like to have a helm-completing-read handler that
> will act like the helm completion when using "helm-mode-dired", but
> not only for file sources.

I think you misunderstand how `helm-completing-read-handlers-alist`
works, you have to give it a valid emacs vanilla function as first
element and a specialized helm completion function as second argument or
if you don't add it to this alist with special directives it will reuse
the default helm completions functions proposed by helm-mode.


> Narrow candidates, but not choosing any one of them implicitly as the
> helm buffer updates with my inputs, as opposed to the behavior of
> helm-completing-read-with-cands-in-buffer.

This part is unclear to me I don't understand exactly what you want.

It seems what you want is something more general, where you complete
against lists and not provide completion against a specific function.

So just tell me what you want to complete against so that I can point you in
the right direction (an example).


-- 
Thierry

**Comment by farva** [comment]
@thierryvolpiatto , Thanks for the swift reply.
What I tried is doing the following:
`(add-to-list 'helm-completing-read-handlers-alist
                       '(magit-checkout . helm-completing-read-with-cands-in-buffer)`

This gave me helm completion of the branches' names.
But this is not good enough, in the case I want to checkout a remote branch, so that git will create a local one with the same name, and set it's upstream to the remote branch.
The problem that helm completion by candidates in buffer will expand to "origin/<branch name>" (because this is the only one that exists that completes the branch name) instead of just "<branch name>", and this will put me in detached head mode.

I think the behavior of the `*helm-mode-dired*` (and the helm completion of the destination file-name in `copy-file`, for that matter) is the perfect behavior for this scenario.
The problem is that their implementation if specific for file sources, and I can't see how to mimic it for the general case.

**Comment by thierryvolpiatto** [comment]
farva <notifications@github.com> writes:

> @thierryvolpiatto , Thanks for the swift reply.
> What I tried is doing the following:
> (add-to-list 'helm-completing-read-handlers-alist
> '(magit-checkout . helm-completing-read-with-cands-in-buffer)

You don't need this unless this completion is not fast enough, which I
guess it is not the case (You don't have generally thousand of
branches).

> This gave me helm completion of the branches' names.  But this is not
> good enough, in the case I want to checkout a remote branch, so that
> git will create a local one with the same name, and set it's upstream
> to the remote branch.  The problem that helm completion by candidates
> in buffer will expand to "origin/" (because this is the only one that
> exists that completes the branch name) instead of just "",

Use C-<RET> instead of RET (see mode-line ;-))

Note unrelated to helm:
For checking out a remote branch I use "y" from magit-status and then
just choose the branch and RET.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
farva <notifications@github.com> writes:

> The problem that helm completion by candidates in buffer will expand
> to "origin/" (because this is the only one that exists that completes
> the branch name) instead of just "", and this will put me in detached
> head mode.

Ok I see, I think you are misusing magit, I guess you are hitting "b b"
to checkout your remote branch as a local one, you should instead use "b c" RET
RET (or use the "y" interface and RET).

-- 
Thierry

**Comment by farva** [comment]
> You don't need this unless this completion is not fast enough, which I
> guess it is not the case (You don't have generally thousand of
> branches).

Well darn, it think it is. It is at work, where we actually have thousands of branches in the repo, that I had to add the `with-cands-in-buffer` to the `helm-completing-read-handlers-alist` in order to get completion and narrowing. Trying at home on a private repo shows that the default handler is good enough in narrowing candidates.

> Use C-<RET> instead of RET (see mode-line ;-))

I think i misused the markdown here in github. What I was really trying to write is -

> The problem that helm completion by candidates in buffer will expand to "origin/branch_name" (because this is the only one that exists that completes the branch name) instead of just "branch_name"

> Ok I see, I think you are misusing magit, I guess you are hitting "b b"
> to checkout your remote branch as a local one, you should instead use "b c" RET
> RET (or use the "y" interface and RET).

You are correct, I did use "b b".  "b c" is not exactly what I wanted, since it does not set the _upstream_, but "y" is perfect does this exactly. Thanks!

**Comment by thierryvolpiatto** [comment]
farva <notifications@github.com> writes:

> You are correct, I did use "b b". "b c" is not exactly what I wanted,
> since it does not set the upstream,

Hmm, seems it does here, when I look at the git config the remote is set
to upstream, not local. i.e a git-pull from this newly created branch
would merge from upstream.

> but "y" is perfect does this exactly. Thanks!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.*


-- 
Thierry

**Comment by farva** [comment]
@thierryvolpiatto , thanks for your help!
