### ISSUE TITLE
helm-pattern returns empty

### ISSUE THREAD

**Issue by jagrg** [emacs-helm/helm#1559]
In the example below, I would expect whatever is typed in the selection buffer to be inserted, but it doesn't.

```
(helm :sources (helm-build-sync-source "test"
                 :candidates '(a b c d e)
		 :action (lambda (letter)
			   (insert (or letter helm-pattern))))
      :buffer "*helm test*")
```

**Comment by thierryvolpiatto** [comment]
Jonathan Gregory <notifications@github.com> writes:

> In the example below, I would expect whatever is typed in the selection buffer to be inserted, but it doesn't.
>
> (helm :sources (helm-build-sync-source "test"
>                  :candidates '(a b c d e)
>          :action (lambda (letter)
>                (insert (or letter helm-pattern))))
>       :buffer "*helm test*")

    (helm :sources (helm-build-sync-source "test"
                     :candidates '(a b c d e)
                     :action (lambda (letter)
                               (with-helm-current-buffer
                                 (insert (or letter helm-pattern)))))
          :buffer "*helm test*")

-- 
Thierry

**Comment by jagrg** [comment]
It still returns nil for me, even with `with-helm-current-buffer`.

**Comment by thierryvolpiatto** [comment]
Jonathan Gregory <notifications@github.com> writes:

> It still returns nil for me, even with with-helm-current-buffer.

So I don't know what you want to do.

AFAIU the intention is to insert one candidate in current-buffer no ?
So why do you expect a return value and where ?

-- 
Thierry

**Comment by jagrg** [comment]
1. M-x foo-bar
2. Type "hello"
3. Press return

I want "hello" to be inserted in the current buffer, but it is not.

```
(defun foo-bar ()
  (interactive)
  (helm :sources (helm-build-sync-source "test"
		   :candidates '(a b c d e)
		   :action (lambda (letter)
			     (insert (or letter helm-pattern))))
	:buffer "*helm test*"))
```

**Comment by thierryvolpiatto** [comment]
Jonathan Gregory <notifications@github.com> writes:

>  1. M-x foo-bar
>  2. Type "hello"
>  3. Press return
>
> I want "hello" to be inserted in the current buffer, but it is not.

helm action is extracting the current selection and nothing else, so you
need what is in helm-pattern as part of your candidates.

If you want something that works out of the box, use:

    (defun foo-bar ()
      (interactive)
      (insert (helm-comp-read "test: " '(a b c d e))))

or a plain completing-read with helm-mode enabled.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Jonathan Gregory <notifications@github.com> writes:

>  1. M-x foo-bar
>  2. Type "hello"
>  3. Press return
>
> I want "hello" to be inserted in the current buffer, but it is not.

Another solution is to use a dummy source:

    (helm :sources `(,(helm-build-sync-source "test"
                       :candidates '(a b c d e)
                       :action (lambda (letter)
                                 (with-helm-current-buffer
                                   (insert letter))))
                     ,(helm-build-dummy-source "test2"
                       :action (lambda (letter)
                                 (with-helm-current-buffer
                                   (insert letter)))))
          :buffer "*helm test*")

-- 
Thierry

**Comment by jagrg** [comment]
Perfect. Thanks so much!
