### ISSUE TITLE
helm-attrset: Wrong number of arguments: helm-attrset, 4

### ISSUE THREAD

**Issue by caadar** [emacs-helm/helm#1560]
'C-c a' keys (helm-buffers-toggle-show-hidden-buffers) does not work anymore in 'helm-mini' and 'helm-buffers-list' with 'helm-attrset: Wrong number of arguments: helm-attrset, 4' message.

**Comment by thierryvolpiatto** [comment]
caadar <notifications@github.com> writes:

> C-c a' keys (helm-buffers-toggle-show-hidden-buffers) does not work
> anymore inhelm-mini' and helm-buffers-list' withhelm-attrset: Wrong
> number of arguments: helm-attrset, 4' message.

Fixed, thanks!

-- 
Thierry
