### ISSUE TITLE
Symbol's definition is void: helm-document-attribute

### ISSUE THREAD

**Issue by cphyc** [emacs-helm/helm#1561]
Hi,
I just updated helm to version 20160713.947 from ELPA and I cannot load it anymore using `(helm-mode 1)`, I get the error `Symbol's definition is void: helm-document-attribute`.

**Comment by thierryvolpiatto** [comment]
Corentin Cadiou <notifications@github.com> writes:

> Hi,
> I just updated helm to version 20160713.947 from ELPA and I cannot
> load it anymore using (helm-mode 1), I get the error Symbol's
> definition is void: helm-document-attribute.

This is because you hold somewhere a old version of helm.el(c), please
cleanup your elisp directories, and recompile (or reinstall) helm.

-- 
Thierry

**Comment by KraevRoot** [comment]
go to the .emacs.d/elpa folder and remove all helm folders and restart/start emacs.
