### ISSUE TITLE
Helm version of `apropos-documentation`

### ISSUE THREAD

**Issue by xiongtx** [emacs-helm/helm#1562]
## Problem

It'd be useful to have a Helm version of `apropos-documentation`. 

`helm-apropos` is very useful for looking up Elisp functions, commands, variables, etc., but you must know (or guess) a word in the symbol name. This isn't much to go on if you're looking for something you're not familiar with. Being able to search through docstrings instead would be very useful.

## Concerns

If we want to include symbols of different types (like with `helm-apropos`), we may end up with tens of thousands of symbols. This could be a performance problem.

**Comment by thierryvolpiatto** [comment]
apropos in emacs is something I don't use at all, it is slow and never gives interesting results of what I am searching for, so I am not interested at implementing this, a lost of time IMO.
