### ISSUE TITLE
File error: Cannot open load file, file or directory not found, helm-plugin

### ISSUE THREAD

**Issue by Dickby** [emacs-helm/helm#1565]
since yesterday's update, I get this error message at emacs startup.
helm version: helm-20160715.330
emacs version: GNU Emacs 25.0.95.32
OS: Arch Linux

**Comment by thierryvolpiatto** [comment]
Dickby <notifications@github.com> writes:

> since yesterday's update, I get this error message at emacs startup.

Please reinstall properly your helm files.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
See #1561 #1564

**Comment by Dickby** [comment]
I deleted helm and helm-core packages and reinstalled, but I still get this error, how to reinstall them properly?

**Comment by thierryvolpiatto** [comment]
Dickby <notifications@github.com> writes:

> I deleted helm and helm-core packages and reinstalled, but I still get
> this error, how to reinstall them properly?

You have another helm-package somewhere which is deprecated (or an old helm
file somewhere in your load-path)

Please always start with ./emacs-helm.sh to see if the bug you report is
related to helm itself.

-- 
Thierry

**Comment by Dickby** [comment]
Ok, the problem isn't helm it's helm-dash!
I close this issue.
Thanks
