### ISSUE TITLE
Why doesn't helm-grep-ag just use ag for pattern contains whitespace (but still need grep)?

### ISSUE THREAD

**Issue by xuchunyang** [emacs-helm/helm#1566]
For example, I want to search "defun helm" under the helm project, if I am under shell, I just use `ag 'defun helm'`, but use the same patter in M-x helm-do-grep-ag, the command will be run is: (`ag defun | grep helm`)

```
 Command line used was:

ag --smart-case --line-numbers --nogroup --color-match='0;32'  defun /Users/xcy/Projects/helm/ | grep --perl-regexp --color=always helm
```

it doesn't work for me because grep on Mac is BSD variant and doesn't support `--perl-regexp`. My question is why not just pass the whole pattern to ag?

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

> For example, I want to search "defun helm" under the helm project, if
> I am under shell, I just use ag 'defun helm', but use the same patter
> in M-x helm-do-grep-ag, the command will be run is: (ag defun | grep
> helm)
>
>  Command line used was:
>
> ag --smart-case --line-numbers --nogroup --color-match='0;32' defun
> /Users/xcy/Projects/helm/ | grep --perl-regexp --color=always helm
>
> it doesn't work for me because grep on Mac is BSD variant and doesn't
> support --perl-regexp.

I suggest you install ack-grep, helm will use it if it is installed.

> My question is why not just pass the whole pattern to ag?

IIRC it is not working, anyway it is not needed running a recursive
search twice (or more), only the first call needs to be recursive (ag)
and this output should be piped to a non--recursive grep.

-- 
Thierry

**Comment by xuchunyang** [comment]
I meant treating search pattern literally, for example, search pattern (regexp which is known by ag) "defun helm" means "defun helm" as a whole (10 characters), not a line contains both "defun" and "helm". I guess ag will not do the search twice in this example.

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

> I meant treating search pattern literally, for example, search pattern
> (regexp which is known by ag) "defun helm" means "defun helm" as a
> whole (10 characters), not a line contains both "defun" and "helm". I
> guess ag will not do the search twice in this example.

This would be a regression, if you want to search "defun helm" use this
regexp: "defun\shelm"

-- 
Thierry

**Comment by xuchunyang** [comment]
> This would be a regression, if you want to search "defun helm" use this
> regexp: "defun\shelm"

OK. Thanks for the tip.

**Comment by thierryvolpiatto** [comment]
@xuchunyang I think I was wrong here and AG, PT or RG are perfectly usable through a pipe.
So perhaps we could use `ag... | ag...` instead of  `ag... | ack-grep...` and same for each backend.
Seems it is working fine here, will do some more tests though...
