### ISSUE TITLE
Follow on typing

### ISSUE THREAD

**Issue by quicknir** [emacs-helm/helm#1568]
Right now, it seems like follow mode in helm only launches the persistent action when you press down or up. What would be nice is if the persistent action also launched whenever text was typed in, causing the results to be updated; currently after a query completes the cursor is on the first hit but the buffer has not actually jumped to it, which seems inconsistent. Following on update leads to a nice flow where one uses typing to narrow down results and examines if the desired point has been reached on the buffer, instead of needing the arrow keys at all. I tried doing this on my own for helm-ag via

```
(add-hook 'helm-after-update-hook 'helm-execute-persistent-action)
``` 

However, the perfomance was rather poor. Is it possible to make this more efficiently, either non-intrusively in user code, or perhaps by changing slightly how follow mode works inside helm itself?

**Comment by quicknir** [comment]
One thing I have tried is messing with helm input idle delay. Setting that high enough eliminates the lag, but it also makes the text less responsive. I think a way to solve this would be to provide a hook that runs after update, but with its own, customizable delay. In other words, a hook that runs its functions after update is complete and e.g. 0.2 seconds has gone by, but if another update comes along before that time has expired, then the hook just doesn't run. That way the text feedback can feel fast and smooth, and it can jump to the first hit quite snappily as well.

**Comment by quicknir** [comment]
I currently have it setup with something like this:

```
  (defun delay-exec()
    (cancel-timer my-timer)
    (setq my-timer (run-at-time "0.1 sec" nil 'helm-execute-persistent-action))
    )
```

And then I add this to the after update hook. This works reasonably well. Do you think that's about the best that can be done?

**Comment by thierryvolpiatto** [comment]
quicknir <notifications@github.com> writes:

> Right now, it seems like follow mode in helm only launches the
> persistent action when you press down or up. What would be nice is if
> the persistent action also launched whenever text was typed in,

This was the previous behavior, I may reenable it if I can make it
working smoothly without reenabling issue #1556, I will look to this
ASAP, (not the time right now).

Thanks.

-- 
Thierry

**Comment by quicknir** [comment]
Cool, thanks, I will try it out as soon as the changes hit melpa.
