### ISSUE TITLE
Choose syntax table for `helm-major-mode`

### ISSUE THREAD

**Issue by xiongtx** [emacs-helm/helm#1569]
## Proposal

When creating a new Helm buffer (e.g. through `helm`), it would be useful to be able to choose the buffer's syntax table.

Right now, the syntax table of `helm-major-mode` is that of `fundamental-mode`. This means that characters like `!` are members of the punctuation syntax class instead of symbol syntax class. Trying to match a candidate containing a symbol like `put!` is difficult, because `\_<put!\_>` (with double `\` in a string) does not match.

## Suggested Solution

Add a new keyword parameter to `helm`, `:syntax-table`, that allows the user to specify a syntax table.

## Caveats

The addition of a new `helm` keyword should be sufficient for end users; however, I don't know what internal functions (e.g. `with-helm-buffer`) would need to be changed, or how significant those changes would be.

**Comment by thierryvolpiatto** [comment]
Please provide recipe showing what you are unable to match, as for now I see no reason to add this to helm.

**Comment by xiongtx** [comment]
I was trying to match some Clojure vars/functions/macros I used as candidates in a Helm buffer. It's for the [helm-cider](https://github.com/clojure-emacs/helm-cider) package.

On second thought, this is probably too niche a use case to be worth doing development; I was able to solve the problem another way. I'll close this for now.
