### ISSUE TITLE
could you make helm-files supporting :keep original face after helm-ff-run-toggle-basename 

### ISSUE THREAD

**Issue by jixiuf** [emacs-helm/helm#1570]
when call helm-ff-run-toggle-basename I found the face in original path is lost
could you make it support keep the original face 
this need to 
```
replace (helm-get-selection nil t) with (helm-get-selection nil 'with prop) in 
function helm-ff-toggle-basename
```
and also need change (helm-basename) 
```
(setq fname  #("/ssh:deployer@ip:/boot" 0 22 (face font-lock-warning-face helm-realvalue #("/ssh:deployer@ip:/boot/" 0 22 (face font-lock-warning-face)) helm-cand-num 1)))

(helm-basename fname)
"boot"

```

**Comment by thierryvolpiatto** [comment]
jixiuf <notifications@github.com> writes:

> when call helm-ff-run-toggle-basename I found the face in original
> path is lost

This is not reproductible here.

-- 
Thierry

**Comment by jixiuf** [comment]
before: https://raw.githubusercontent.com/jixiuf/jixiuf.github.com/source/download/s1.png
after  https://raw.githubusercontent.com/jixiuf/jixiuf.github.com/source/download/s1.png
I mean  I write a helm-source ,and want show different faces for file visited by tramp
and when I press Ctrl-] 
the color is lost

**Comment by thierryvolpiatto** [comment]
jixiuf <notifications@github.com> writes:

> before: https://raw.githubusercontent.com/jixiuf/jixiuf.github.com/source/download/s1.png
> after
> https://raw.githubusercontent.com/jixiuf/jixiuf.github.com/source/download/s1.png

Hmm! s1.png == s1.png

> I mean I write a helm-source ,and want show different faces for file
> visited by tramp and when I press Ctrl-] the color is lost

It seems you are writing your own code and something is wrong in this
code, sorry I can't help you without more informations.

-- 
Thierry

**Comment by jixiuf** [comment]
sorry after https://raw.githubusercontent.com/jixiuf/jixiuf.github.com/source/download/s2.png

**Comment by thierryvolpiatto** [comment]
I still don't know what is wrong in your code, my guess is that you are using a candidate-transformer instead of a  filtered one.
Please provide code and/or recipe, screeenshots are not helpfull.

**Comment by jixiuf** [comment]
```
(defvar helm-dired-history-variable nil)
(defvar helm-dired-history-fuzzy-match t)

(defvar helm-dired-history-cleanup-p nil)

(defun helm-dired-history-update()
  "update variable `helm-dired-history-variable'."
  (unless helm-dired-history-cleanup-p
    (setq helm-dired-history-cleanup-p t)
    (let ((tmp-history ))
      (dolist (d helm-dired-history-variable)
        (when (or (file-remote-p d) (file-directory-p d))
          (add-to-list 'tmp-history d t)))
      (setq helm-dired-history-variable tmp-history)))
  (setq helm-dired-history-variable
        (delete-dups (delete (dired-current-directory) helm-dired-history-variable)))
  (let ((dir (dired-current-directory)))
    (when (file-remote-p dir)
      (setq dir (propertize dir 'face 'font-lock-warning-face)))
    (setq helm-dired-history-variable
          (append (list dir) helm-dired-history-variable))))

;;when you open dired buffer ,update `helm-dired-history-variable'.
(add-hook 'dired-after-readin-hook 'helm-dired-history-update)

(defclass helm-dired-history-source (helm-source-sync helm-type-file)
  ((candidates :initform (lambda () helm-dired-history-variable))
   (keymap :initform helm-generic-files-map)
   (help-message :initform helm-generic-file-help-message)))

(defvar helm-source-dired-history
  (helm-make-source "Dired History" 'helm-dired-history-source
    :fuzzy-match helm-dired-history-fuzzy-match))

(defun helm-dired()
  "call `helm' to show dired history and files in current buffers."
  (interactive)
  (require 'helm-dired-history)
  (require 'helm-files)
  (let ((helm-execute-action-at-once-if-one t)
        (helm-quit-if-no-candidate
         (lambda () (message "No history record."))))
    (helm '(helm-source-dired-history ))))

(define-key dired-mode-map "," 'helm-dried)
```

**Comment by jixiuf** [comment]
in the screenshot 
the path "/ssh:deployer@src.najaplsu.com:/home/"  has a face: font-lock-warning-face
after Ctrl-]
it becomes "home" without face

**Comment by thierryvolpiatto** [comment]
jixiuf <notifications@github.com> writes:

>     (when (file-remote-p dir)
>       (setq dir (propertize dir 'face 'font-lock-warning-face)))

Use a filtered-candidate-transformer for this.

-- 
Thierry

**Comment by jixiuf** [comment]
```
(defun helm-dired-history-transform (candidates _source)
  (dolist (c candidates)
    (if (file-remote-p (car c))
        (cons (propertize (car c) 'face 'font-lock-warning-face) (cdr c))
      c)))

(defclass helm-dired-history-source (helm-source-sync helm-type-file)
  ((candidates :initform (lambda () helm-dired-history-variable))
   (keymap :initform helm-generic-files-map)
   (filtered-candidate-transformer :initform helm-dired-history-transform)
   (help-message :initform helm-generic-file-help-message)))
```
I do not know why ,
after I add helm-dried-history-transform
none candidates show 
Is something wrong ?

**Comment by thierryvolpiatto** [comment]
jixiuf <notifications@github.com> writes:

> Is something wrong ?

Yes helm-dried-history-transform is a function and should be quoted.

-- 
Thierry

**Comment by jixiuf** [comment]
thanks fixed .
