### ISSUE TITLE
helm doesn't work with TemplatesMode

### ISSUE THREAD

**Issue by vinurs** [emacs-helm/helm#1572]
when i call helm-find-files, if the file doesn't exist, it can't using templatesMode which can init the new file with predefined formats.
TemplatesMode is `https://www.emacswiki.org/emacs/TemplatesMode`
I checked the helm code found that at last it calls **find-file-at-point** ,  the function works differently in M-x and calling it in elisp code directly. 
Is there a way to achieve my goal ?
hope for your help.

**Comment by thierryvolpiatto** [comment]
vinurs <notifications@github.com> writes:

> when i call helm-find-files, if the file doesn't exist, it can't using
> templatesMode which can init the new file with predefined formats.
> TemplatesMode is https://www.emacswiki.org/emacs/TemplatesMode I
> checked the helm code found that at last it calls find-file-at-point ,
> the function works differently in M-x and calling it in elisp code
> directly.  Is there a way to achieve my goal ?  hope for your help.

I don't know what templatesmode is and the link you provided point to
something else (unsafe?).
Looks like your package is not on melpa too.
I don't trust all what you can find on emacswiki, sorry.
  
-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Ok, I have fixed your link to TemplatesMode (you add inversed the markdown link i.e it should be `[title](url)`).
But consider this package not compatible with helm, I will not work on this to make it working.

**Comment by vinurs** [comment]
@thierryvolpiatto thanks very much
