### ISSUE TITLE
Open file in specific window

### ISSUE THREAD

**Issue by quicknir** [emacs-helm/helm#1573]
I'm trying to enable a keybinding that performs the action: run the default action on selected item in the nth window, and leave helm open. The reason for having this is that it is helpful when wanting to open several files at once. Right now, if I want to have open 3 files in 3 particular windows, I typically have to run 3 helm sessions. This is nice both for opening multiple project files at once with projectile, and for easily arranging your buffers with helm buffers. I cannot figure out how to do this however. I've basically tried things like this:

```
  (defun advice-first-window (orig-fun &rest split-window)
    (select-window-1)
    )

  (defun spacemacs/helm-persistent-action-in-window-1 ()
    (interactive)
    (advice-add 'helm-select-persistent-action-window :around 'advice-first-window)
    ;; (helm-execute-persistent-action)
    ;; (helm-execute-selection-action)
    ;; (helm-log-run-hook 'helm-exit-minibuffer-hook)
    (helm-exit-minibuffer)
    (advice-remove 'helm-select-persistent-action-window 'advice-first-window)
    )
```

As you can see, I've tried various things. The persistent action attempt worked in the sense that the file would get opened in the desired window, but then exiting helm caused the original buffer to return to the window. None of my other attempts worked. Is there a way to do this currently in helm?

For context it may be helpful to know that I'm using spacemacs and it's common to do window related things via the window numbering scheme built into spacemacs, that's where select-window-1 comes from.

**Comment by thierryvolpiatto** [comment]
quicknir <notifications@github.com> writes:

> The reason for having this is that it is helpful when wanting to open
> several files at once.

Mark your files and hit C-u RET.

> For context it may be helpful to know that I'm using spacemacs

I am not a fan of spacemacs and know nothing about it, if things work in
spacemacs, good, otherwise no luck, I will not learn how it works, sorry.

-- 
Thierry

**Comment by quicknir** [comment]
If I use C-u the way you describe, it just creates a bunch of splits. Most of the time I already have windows splits open the way I want and want to open new buffer in existing files. There's no need to learn anything about spacemacs. The question is just whether it's possible to programmatically control in which window things open in helm. Or if there is a way to disable for a persistent action, its removal after helm exits.

**Comment by quicknir** [comment]
Or even: how do i call the default action normally launched by enter, without exiting helm? I looked through and could not figure it out

**Comment by thierryvolpiatto** [comment]
quicknir <notifications@github.com> writes:

> The question is just whether it's possible to programmatically control
> in which window things open in helm.

Not the way you tried.

You will have to mark your candidates and distribute them in differents
windows _once_ exited.
I.e when you press RET you exit helm and your action function takes each
marked candidate and put it in a window.
I guess you will have to loop through helm-marked-candidates and walk-windows.

-- 
Thierry

**Comment by quicknir** [comment]
This is less ideal. How about disabling/modifying the behavior of helm which restores the state of windows? I'm able to control the persistent action window quite handily, the only problem is that helm reverts everything on exit. Can you give me some pointers as to wohere that occurs in the code?

**Comment by thierryvolpiatto** [comment]
quicknir <notifications@github.com> writes:

> This is less ideal. How about disabling/modifying the behavior of helm
> which restores the state of windows?

No, your approach in plain wrong IMO.

> I'm able to control the persistent action window quite handily, the
> only problem is that helm reverts everything on exit.

Of course and it is what is expected.

> Can you give me some pointers as to wohere that occurs in the code?

You will find all in helm.el, BTW don't expect any changes in helm source
code for this (No PR accepted for this).

-- 
Thierry

**Comment by quicknir** [comment]
Can you explain what's wrong about it? Most people find it valuable to have instant feedback; it's easier to ask for buffers to be opened in windows and see what you're doing immediately, rather than to set up a complex series of commands and wait until helm exits to execute them all. For instance, if you make a mistake it's easier to see it right away.

I'd expect it to be in helm.el, I'm asking for a bit of clarification. I've spent about an hour trying to figure this out and sifting through helm.el, a small amount of info from you could probably shorten the amount of time it takes or help make it possible.

I'm not sure why you oppose a PR so strongly for this, since the change on the helm side would at most amount to adding some customization hooks. But that's fine, I'm investigating ways to do this without changing helm.
