### ISSUE TITLE
Unable to compile emacs-helm from source

### ISSUE THREAD

**Issue by svgreatest** [emacs-helm/helm#1574]
I downloaded emacs-helm from the git repository and tried to compile it. Tried multiple
versions ( latest, 1.9.7 and 1.6.7 )

I get this error:

gsrikant:~/.emacs.d/helm# make                                                               
rm -f helm-adaptive.elc helm-apt.elc helm-autoloads.elc helm-bookmark.elc helm-buffers.elc helm-color.elc helm-command.elc helm-config.elc helm-core-pkg.elc helm-dabbrev.elc helm-easymenu.elc helm-elisp-package.elc helm-elisp.elc helm-elscreen.elc helm-eshell.elc helm-eval.elc helm-external.elc helm-files.elc helm-font.elc helm-grep.elc helm-help.elc helm-id-utils.elc helm-imenu.elc helm-info.elc helm-lib.elc helm-locate.elc helm-man.elc helm-misc.elc helm-mode.elc helm-multi-match.elc helm-net.elc helm-org.elc helm-pkg.elc helm-plugin.elc helm-regexp.elc helm-ring.elc helm-semantic.elc helm-source.elc helm-sys.elc helm-tags.elc helm-types.elc helm-utils.elc helm.elc
emacs -Q -batch --eval "(let ((generated-autoload-file (expand-file-name \"helm-autoloads.el\" \".\")) \
(backup-inhibited t)) (update-directory-autoloads \".\"))"
Warning: defvar ignored because generated-autoload-file is let-bound
Generating autoloads for cl-lib.el...
Generating autoloads for cl-lib.el...done
Saving file /u/gsrikant/.emacs.d/helm/helm-autoloads.el...
Wrote /u/gsrikant/.emacs.d/helm/helm-autoloads.el
(No changes need to be saved)
emacs -Q -batch -L . -f batch-byte-compile helm-adaptive.el helm-apt.el helm-autoloads.el helm-bookmark.el helm-buffers.el helm-color.el helm-command.el helm-config.el helm-core-pkg.el helm-dabbrev.el helm-easymenu.el helm-elisp-package.el helm-elisp.el helm-elscreen.el helm-eshell.el helm-eval.el helm-external.el helm-files.el helm-font.el helm-grep.el helm-help.el helm-id-utils.el helm-imenu.el helm-info.el helm-lib.el helm-locate.el helm-man.el helm-misc.el helm-mode.el helm-multi-match.el helm-net.el helm-org.el helm-pkg.el helm-plugin.el helm-regexp.el helm-ring.el helm-semantic.el helm-source.el helm-sys.el helm-tags.el helm-types.el helm-utils.el helm.el

In toplevel form:
helm-adaptive.el:24:1:Error: Wrong type argument: integer-or-marker-p, (format "<f%s>" (1+ n))

In toplevel form:
helm-apt.el:21:1:Error: Wrong type argument: integer-or-marker-p, (format "<f%s>" (1+ n))

In toplevel form:
helm-bookmark.el:21:1:Error: Wrong type argument: integer-or-marker-p, (format "<f%s>" (1+ n))

In toplevel form:
helm-buffers.el:21:1:Error: Wrong type argument: integer-or-marker-p, (format "<f%s>" (1+ n))

In toplevel form:
helm-color.el:20:1:Error: Wrong type argument: integer-or-marker-p, (format "<f%s>" (1+ n))

In toplevel form:
helm-command.el:21:1:Error: Wrong type argument: integer-or-marker-p, (format "<f%s>" (1+ n))
Wrote /u/gsrikant/.emacs.d/helm/helm-config.elc

In toplevel form:
helm-dabbrev.el:20:1:Error: Wrong type argument: integer-or-marker-p, (format "<f%s>" (1+ n))
Wrote /u/gsrikant/.emacs.d/helm/helm-easymenu.elc

In toplevel form:
helm-elisp-package.el:20:1:Error: Wrong type argument: integer-or-marker-p, (format "<f%s>" (1+ n))

In toplevel form:
helm-elisp.el:20:1:Error: Wrong type argument: integer-or-marker-p, (format "<f%s>" (1+ n))

In toplevel form:
helm-elscreen.el:20:1:Error: Wrong type argument: integer-or-marker-p, (format "<f%s>" (1+ n))

In toplevel form:
helm-eshell.el:30:1:Error: Wrong type argument: integer-or-marker-p, (format "<f%s>" (1+ n))

In toplevel form:
helm-eval.el:20:1:Error: Wrong type argument: integer-or-marker-p, (format "<f%s>" (1+ n))

In toplevel form:
helm-external.el:21:1:Error: Wrong type argument: integer-or-marker-p, (format "<f%s>" (1+ n))

In toplevel form:
helm-files.el:21:1:Error: Wrong type argument: integer-or-marker-p, (format "<f%s>" (1+ n))

In toplevel form:
helm-font.el:21:1:Error: Wrong type argument: integer-or-marker-p, (format "<f%s>" (1+ n))

In toplevel form:
helm-grep.el:20:1:Error: Wrong type argument: integer-or-marker-p, (format "<f%s>" (1+ n))

In toplevel form:
helm-help.el:19:1:Error: Wrong type argument: integer-or-marker-p, (format "<f%s>" (1+ n))

In toplevel form:
helm-id-utils.el:20:1:Error: Wrong type argument: integer-or-marker-p, (format "<f%s>" (1+ n))

In toplevel form:
helm-imenu.el:21:1:Error: Wrong type argument: integer-or-marker-p, (format "<f%s>" (1+ n))

In toplevel form:
helm-info.el:21:1:Error: Wrong type argument: integer-or-marker-p, (format "<f%s>" (1+ n))

In end of data:
helm-lib.el:804:1:Warning: the following functions are not known to be
    defined: ansi-color--find-face, ansi-color-apply-sequence
Wrote /u/gsrikant/.emacs.d/helm/helm-lib.elc

In toplevel form:
helm-locate.el:25:1:Error: Wrong type argument: integer-or-marker-p, (format "<f%s>" (1+ n))

In toplevel form:
helm-man.el:21:1:Error: Wrong type argument: integer-or-marker-p, (format "<f%s>" (1+ n))

In toplevel form:
helm-misc.el:20:1:Error: Wrong type argument: integer-or-marker-p, (format "<f%s>" (1+ n))

In toplevel form:
helm-mode.el:21:1:Error: Wrong type argument: integer-or-marker-p, (format "<f%s>" (1+ n))
Wrote /u/gsrikant/.emacs.d/helm/helm-multi-match.elc

In toplevel form:
helm-net.el:21:1:Error: Wrong type argument: integer-or-marker-p, (format "<f%s>" (1+ n))

In toplevel form:
helm-org.el:20:1:Error: Wrong type argument: integer-or-marker-p, (format "<f%s>" (1+ n))

In toplevel form:
helm-plugin.el:21:1:Error: Wrong type argument: integer-or-marker-p, (format "<f%s>" (1+ n))

In toplevel form:
helm-regexp.el:21:1:Error: Wrong type argument: integer-or-marker-p, (format "<f%s>" (1+ n))

In toplevel form:
helm-ring.el:21:1:Error: Wrong type argument: integer-or-marker-p, (format "<f%s>" (1+ n))

In toplevel form:
helm-semantic.el:27:1:Error: Wrong type argument: integer-or-marker-p, (format "<f%s>" (1+ n))
Wrote /u/gsrikant/.emacs.d/helm/helm-source.elc

In toplevel form:
helm-sys.el:21:1:Error: Wrong type argument: integer-or-marker-p, (format "<f%s>" (1+ n))

In toplevel form:
helm-tags.el:21:1:Error: Wrong type argument: integer-or-marker-p, (format "<f%s>" (1+ n))

In toplevel form:
helm-types.el:85:56:Warning: reference to free variable
    `helm-mode-line-string'
helm-types.el:86:37:Warning: reference to free variable
    `helm-generic-files-map'
helm-types.el:115:37:Warning: reference to free variable `helm-bookmark-map'
Wrote /u/gsrikant/.emacs.d/helm/helm-types.elc

In toplevel form:
helm-utils.el:21:1:Error: Wrong type argument: integer-or-marker-p, (format "<f%s>" (1+ n))

In toplevel form:
helm.el:168:1:Error: Wrong type argument: integer-or-marker-p, (format "<f%s>" (1+ n))

When I try emacs-helm.sh with GNU Emacs 24.2.1, I get this error:
Symbol's function defintion is void: cl-defun

**Comment by thierryvolpiatto** [comment]
svgreatest <notifications@github.com> writes:

> I downloaded emacs-helm from the git repository and tried to compile it. Tried multiple
> versions ( latest, 1.9.7 and 1.6.7 )
>
> I get this error:
>
> gsrikant:~/.emacs.d/helm# make
> When I try emacs-helm.sh with GNU Emacs 24.2.1, I get this error:

Without compiling helm directory emacs-helm.sh should not work.

> Symbol's function defintion is void: cl-defun

I guess you have a problem with your emacs installation, after
recompiling your emacs helm should compile fine.

Even better would be you use a recent emacs (24.5 or at least 24.4).

-- 
Thierry

**Comment by xuchunyang** [comment]
https://github.com/emacs-helm/helm#requirements
> Helm requires Emacs-24.3 or later versions.

**Comment by svgreatest** [comment]
Recompiling and using a more recent version of emacs helped. Thanks!
