### ISSUE TITLE
select parent dir when changing to parent dir

### ISSUE THREAD

**Issue by blaenk** [emacs-helm/helm#1575]
I love that I can do `C-l` to go up a directory when completing a path with helm, but I've noticed that if I want to select the parent directory, I still have to navigate with `C-n`/`C-p` to select it at the top of the list. I feel like it would be more intuitive that if we go up a directory with `C-l`, the point should be at the top of the new completion list (which happens to be the parent dir we went up _to_). Instead, the current behavior is that the point is at the entry for the directory which we came _from_.

Example:

1. go to some directory like ~/some/place
2. `M-x cd`
3. `C-l` to go up to ~/some/
4. notice that the entry list is now something like:

    1. ~/.
    2. ~/..
    3. ~/place <-- POINT HERE

In this case I went up the directory so that I could choose ~/some/, so I wish the point were on 1, but instead it's on 3: the directory we came _from_. I imagine the reasoning behind this behavior is that if we want to undo the going-up-a-directory, we can just press ENTER to go back where we were. Personally I never ever need this in all of the time I've ever used helm, and I always do want to use this behavior I desire.

Is there perhaps an option I am missing for this? If not, would you be kind enough to introduce an option to do this? If not, is this something I can create an advice for perhaps?

**Comment by thierryvolpiatto** [comment]
Jorge Israel Peña <notifications@github.com> writes:

> I love that I can do C-l to go up a directory when completing a path
> with helm, but I've noticed that if I want to select the parent
> directory, I still have to navigate with C-n/C-p to select it at the
> top of the list. I feel like it would be more intuitive that if we go
> up a directory with C-l, the point should be at the top of the new
> completion list (which happens to be the parent dir we went up
> to). Instead, the current behavior is that the point is at the entry
> for the directory which we came from.

No, coming back on top would be inconvenient to navigate, when you want
to go to top use instead of `C-l` `../`.

-- 
Thierry
