### ISSUE TITLE
Follow mode and resume bug

### ISSUE THREAD

**Issue by quicknir** [emacs-helm/helm#1577]
With helm-resume, it seems desirable that everything would pickup in the exact same state. Even the cursor position is exactly saved. If you are in follow mode at the time you exit, and then resume, it will show the "HF" indicator, making it seem like you are in follow mode. However, it does not actually jump to the entry the cursor is on, and as soon as you hit up or down, no following occurs either and the HF indicator vanishes. Ideally it should do both of these: as soon as resume is called, it should launch the persistent action on the item the cursor is on, and it should actually stick in HF when up and down arrows are pressed.

**Comment by thierryvolpiatto** [comment]
quicknir <notifications@github.com> writes:

> With helm-resume, it seems desirable that everything would pickup in
> the exact same state. Even the cursor position is exactly saved. If
> you are in follow mode at the time you exit, and then resume, it will
> show the "HF" indicator, making it seem like you are in follow
> mode. However, it does not actually jump to the entry the cursor is
> on, and as soon as you hit up or down, no following occurs either and
> the HF indicator vanishes. Ideally it should do both of these: as soon
> as resume is called, it should launch the persistent action on the
> item the cursor is on, and it should actually stick in HF when up and
> down arrows are pressed.

You are actually describing two problems.
The first is controlled by `helm-follow-mode-persistent` and the second
by `helm-follow-follow-on-update`.
I see no bug in both, just a behavior you dislike.

-- 
Thierry

**Comment by quicknir** [comment]
Well, the fact that it shows HF when it's not actually in follow mode is surely a bug, though not an important one. helm follow mode persistent is a setting with much wider implications, it controls persistence across entirely new helm sessions as well. Is there any chance you would consider changing the resume behavior to remember follow mode, or at least give it a separate persistence setting?

**Comment by thierryvolpiatto** [comment]
I have finally removed `helm-follow-follow-on-update` which is something unsafe (like it was in previous versions).
Helm should follow only on next/previous line.
