### ISSUE TITLE
Documentation helms-source-sync: Fuzzy matching is mentioned but not defined

### ISSUE THREAD

**Issue by tmalsburg** [emacs-helm/helm#1578]
I think it would be good to have at least one sentence saying what fuzzy matching is doing.  For example, I'm getting discontiguous matches in helm-bibtex since I switched to constructing the source with `helm-build-sync-source`.  Is that fuzzy matching?

**Comment by thierryvolpiatto** [comment]
Titus von der Malsburg <notifications@github.com> writes:

> I think it would be good to have at least one sentence saying what
> fuzzy matching is doing. For example, I'm getting discontiguous
> matches in helm-bibtex since I switched to constructing the source
> with helm-build-sync-source. Is that fuzzy matching?

No unless you specified fuzzy-match.

-- 
Thierry

**Comment by tmalsburg** [comment]
In helm-bibtex [I did not specify fuzzy-match](https://github.com/tmalsburg/helm-bibtex/blob/master/helm-bibtex.el#L172) and according to the documentation the default is `nil`, but I still get discontiguous matches.

**Comment by thierryvolpiatto** [comment]
Titus von der Malsburg <notifications@github.com> writes:

> In helm-bibtex I did not specify fuzzy-match and according to the
> documentation the default is nil, but I still get discontiguous
> matches.

I don't know what you mean with discontiguous matches.

I see nothing wrong in your source definition, however I see another
source which is not defined with helm-source.

Please try to debug your sources one by one.

-- 
Thierry

**Comment by tmalsburg** [comment]
Discontiguous matches: I enter "abc" as the search time and get matches like "*a*sjdlfkjsdgjsdg*b*hjgdsjdhgf*c*".  These are almost always false positives.

**Comment by thierryvolpiatto** [comment]
Titus von der Malsburg <notifications@github.com> writes:

> Discontiguous matches: I enter "abc" as the search time and get
> matches like "asjdlfkjsdgjsdgbhjgdsjdhgfc". These are almost always
> false positives.

So you are actually fuzzy matching, don't know why, this is not
reproductible in any other sources or with a simple test source here.

    (helm :sources (helm-build-sync-source "test"
                     :candidates '("abcd" "azbdc" "azertbdfgc" "azertabc" "sdfgabcdfg"))
          :buffer "*helm test*")

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Thierry Volpiatto <thierry.volpiatto@gmail.com> writes:

>     (helm :sources (helm-build-sync-source "test"
>                      :candidates '("abcd" "azbdc" "azertbdfgc" "azertabc" "sdfgabcdfg"))
>           :buffer "*helm test*")

And if you specify :fuzzy-match it works as expected.

-- 
Thierry
