### ISSUE TITLE
All window mode lines are highlighted as being used in a helm session

### ISSUE THREAD

**Issue by fice-t** [emacs-helm/helm#1579]
I think only the current window's mode line should be highlighted as used.

Reproduction:

1. `emacs-helm.sh`
2. Create a few new windows using `C-x 2` and `C-x 3`
3. Start a helm session with `M-x`, `C-h f/v`, etc
4. All mode lines are now highlighted as if they're all being used.

**Comment by thierryvolpiatto** [comment]
fice-t <notifications@github.com> writes:

> I think only the current window's mode line should be highlighted as used.
>
> Reproduction:
>
>  1. emacs-helm.sh
>  2. Create a few new windows using C-x 2 and C-x 3
>  3. Start a helm session with M-x, C-h f/v, etc
>  4. All mode lines are now highlighted as if they're all being used.

I could reproduce this some days ago but after reverting some changes it
is no more reproductible with last helm.
Are you sure you use last helm ?

-- 
Thierry

**Comment by fice-t** [comment]
> Are you sure you use last helm ?

I believe so -- I have a helm-core version of `20160805.711` from MELPA.

**Comment by thierryvolpiatto** [comment]
fice-t <notifications@github.com> writes:

> I think only the current window's mode line should be highlighted as used.

Oh, I understand, the mode-line highlighted is the default mode-line in
other windows, it is normal it is highlighted because I binded
`mode-line-in-non-selected-windows` to nil to prevent bug #1538.

-- 
Thierry

**Comment by fice-t** [comment]
> it is normal it is highlighted because I binded `mode-line-in-non-selected-windows` to nil to prevent bug #1538.

Is it? Looking at the commit (https://github.com/emacs-helm/helm/commit/d53880f23efb5fd822de1c557bca43c87b676f18) for that bug, it looks like that variable wasn't added then.

Seems like it was added in https://github.com/emacs-helm/helm/commit/a6b06f83297c32b1c5d93d532cdd2a60548eaa86.

**Comment by thierryvolpiatto** [comment]
fice-t <notifications@github.com> writes:

>     it is normal it is highlighted because I binded mode-line-in-non-selected-windows to nil to prevent bug #1538.
>    
> Is it? Looking at the commit (d53880f) for that bug, it looks like that variable wasn't added then.
>
> Seems like it was added in a6b06f8.

You are right, my comment was wrongly placed, I have commited a fix,
have a try.

Thanks.

-- 
Thierry

**Comment by fice-t** [comment]
It works, thanks.

**Comment by fice-t** [comment]
I updated to the latest MELPA version and this problem came back.

**Comment by thierryvolpiatto** [comment]
fice-t <notifications@github.com> writes:

> I updated to the latest MELPA version and this problem came back.

Latest melpa doesn't reflet necessary latest git ;-)
 
-- 
Thierry

**Comment by fice-t** [comment]
> Latest melpa doesn't reflet necessary latest git ;-)

Right, though at the moment I believe it does. Sadly the problem is still present. :(

**Comment by thierryvolpiatto** [comment]
fice-t <notifications@github.com> writes:

>     Latest melpa doesn't reflet necessary latest git ;-)
>    
> Right, though at the moment I believe it does. Sadly the problem is still present. :(

Hmm, I misread I thought this was about bug 1613.
I don't know why mode-line-in-non-selected-windows reappear there, maybe
an error during a merge or rebase operation.
Should work again now.
Sorry for inconvenience.

-- 
Thierry

**Comment by fice-t** [comment]
> I don't know why mode-line-in-non-selected-windows reappear there, maybe

Unfortunately it looks like it was removed it to fix #1593. Now that problem is back.

Could you only bind `mode-mode-line-in-non-selected-windows` to `nil` when `helm-follow-mode` is turned on? That would solve both issues at the same time.

**Comment by thierryvolpiatto** [comment]
fice-t <notifications@github.com> writes:

> Unfortunately it looks like it was removed it to fix #1593. Now that problem is back.

Indeed.

> Could you only bind mode-mode-line-in-non-selected-windows to nil when
> helm-follow-mode is turned on? That would solve both issues at the
> same time.

No this will not work, I used another approach by remapping the
mode-line face in persistent action, have a try and let me know if it
fix issue for you.

Thanks.

--
Thierry

**Comment by thierryvolpiatto** [comment]
fice-t <notifications@github.com> writes:

>     I don't know why mode-line-in-non-selected-windows reappear there, maybe
>    
> Unfortunately it looks like it was removed it to fix #1593. Now that problem is back.

After looking at this today and trying several ways to fix this, I think
it's not a bug and not annoying at all.
After all it is normal that the mode-line update with its mode-line face
because helm is indeed making the other buffer current (a very small
amount of time but it does).
So for now I prefer keeping this as it is instead of introducing a new
bug to fix something that is not really a bug.

Thanks.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Finally fixed.
