### ISSUE TITLE
Reverse order?

### ISSUE THREAD

**Issue by therockmandolinist** [emacs-helm/helm#1581]
So, I have seen #362, but since that's very old, I wanted to know if anything has changed or if there's anything new regarding this. 

I think this would be pretty handy, and possibly more popular/useful than given credit in the original issue? I think would especially be a great help for auto-resize mode, where the header line doesn't quite do the trick, in my opinion (it's moving with the top of the helm buffer). I _could_ just not use auto resize mode, but it would be nice if that tradeoff didn't have to exist? (Although I completely understand if it's way too much work to implement – I myself am very, very inexperienced with emacs-lisp so I really wouldn't know)

I apologize for opening a new issue about this, so feel free to just discard this if this is a completely useless topic of discussion.

**Comment by thierryvolpiatto** [comment]
Diego A. Mundo <notifications@github.com> writes:

> So, I have seen #362, but since that's very old, I wanted to know if
> anything has changed there/if there's anything new regarding this.

Nothing have changed, wont fix this.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Note that you can have now a pseudo minibuffer displayed in the header-line, which is maybe what you want, i.e seeing the first results close to where you type.

**Comment by sassanh** [comment]
So that's how helm has only 5 open issues.
