### ISSUE TITLE
Search string not highlighted properly

### ISSUE THREAD

**Issue by d125q** [emacs-helm/helm#1582]
Consider the scenario as depicted on the screenshot:
![1471246579](https://cloud.githubusercontent.com/assets/7765538/17658394/c0d398da-62cb-11e6-837b-4f4f9964daae.png)

I expect the `files` substring to be highlighted also in `helm-find-files` and `helm-multi-files`.  I suppose this has something to do with the keybinding being shown in the Helm buffer.

**Comment by thierryvolpiatto** [comment]
Dario Gjorgjevski <notifications@github.com> writes:

> Consider the scenario as depicted on the screenshot:
> 14712465
>
> I expect the files substring to be highlighted also in helm-find-files
> and helm-multi-files. I suppose this has something to do with the
> keybinding being shown in the Helm buffer.

It is highlighted as expected, (we are speaking of helm-M-x, right?),
please try from emacs-helm.sh, you will see it is working fine. 

-- 
Thierry

**Comment by d125q** [comment]
Here is a screenshot from `emacs-helm.sh`:
![1471257900](https://cloud.githubusercontent.com/assets/7765538/17662492/20855d94-62e6-11e6-80b2-ae9e074a2aec.png)

**Comment by michael-heerdegen** [comment]
Dario Gjorgjevski <notifications@github.com> writes:

> Here is a screenshot from emacs-helm.sh:
> 1471257900

I can reproduce this, looks the same here.

**Comment by d125q** [comment]
Just for reference -- the same search string, but without the `$`:
![1471301991](https://cloud.githubusercontent.com/assets/7765538/17682593/cabd9dec-634c-11e6-98d1-979a76afcc18.png)

**Comment by d125q** [comment]
Another interesting point: why is `helm-for-files` sorted before `helm-find-files` when the `$` anchor is absent, and after when it's present?

**Comment by thierryvolpiatto** [comment]
Dario Gjorgjevski <notifications@github.com> writes:

> Another interesting point: why is helm-for-files sorted before
> helm-find-files when the $ anchor is absent, and after when it's
> present?

Sorry for late reply, this have been fixed.

Thanks.

-- 
Thierry

**Comment by d125q** [comment]
Thank you!
