### ISSUE TITLE
helm-top no sorting by memory and cpu

### ISSUE THREAD

**Issue by tollerm** [emacs-helm/helm#1586]
Helm-top sorting by memory and cpu is broken. For memory, the function helm-top-sort-by-mem refers to wrong column (11 instead of 6), and for cpu function for sorting is not defined.

**Comment by thierryvolpiatto** [comment]
tollerm <notifications@github.com> writes:

> Helm-top sorting by memory and cpu is broken.

They are not with top as backend, I didn't try with ps, but I guess that
if you have configured your command correctly it should work as expected.

> For memory, the function helm-top-sort-by-mem refers to wrong column
> (11 instead of 6),

No the column used by top is column 10 (nth 9) and if you customize
yourself your command with ps, make sure you use the same columns, see
helm-top-command docstring.

> and for cpu function for sorting is not defined.

For top the default is sorting by CPU, so nil is used to sort by CPU.
Don't remember for ps, I have to check.

-- 
Thierry

**Comment by tollerm** [comment]
Dear Thierry,
Thank you for your prompt reply. I am on Arch Linux, use top command. And by default I have only 10 columns with different field order than that used in implementation of helm-top. I briefly looked in documentation and could not find out about default settings for fields in top command. Nevertheless, it is quite easy in top to change the number of fields and their order to match those used in helm-top. After this customization sorting in helm-top works fine. May be it is worthwhile to mention about using correct fields in top on Lunux in documentation of string of helm-top?

**Comment by thierryvolpiatto** [comment]
tollerm <notifications@github.com> writes:

> Dear Thierry, Thank you for your prompt reply. I am on Arch Linux, use
> top command. And by default I have only 10 columns with different
> field order than that used in implementation of helm-top.

I have implemented helm-top based on the top command bundled with ubuntu
based distributions which have 12 columns by default.

> I briefly looked in documentation and could not find out about default
> settings for fields in top command. Nevertheless, it is quite easy in
> top to change the number of fields and their order to match those used
> in helm-top.

Great.

> After this customization sorting in helm-top works fine. May be it is
> worthwhile to mention about using correct fields in top on Lunux in
> documentation of string of helm-top?

Yes I will provide this info in docstring, could you provide your
settings of helm-top-command ?
It will help me a lot to write this docstring.

Thanks.

-- 
Thierry

**Comment by tollerm** [comment]
I've selected in top using 'f' interactive command fields as you specified, i.e. total 12 fields, first two fields are 'PID' and 'USER' and last 4 fields are '%CPU', '%MEM', 'TIME' and 'COMMAND', then used 'W' interactive command to create personal configuration file for top command. Afterwords helm-top worked as expected. It would be probably better do not hardcode columns' number but provide a list variable containing the column numbers corresponding these fields which a user can customize. Even better, search using regex columns' numbers in top output but it is probably to much work .

**Comment by thierryvolpiatto** [comment]
tollerm <notifications@github.com> writes:

> I've selected in top using 'f' interactive command fields as you
> specified, i.e. total 12 fields, first two fields are 'PID' and 'USER'
> and last 4 fields are '%CPU', '%MEM', 'TIME' and 'COMMAND', then used
> 'W' interactive command to create personal configuration file for top
> command. Afterwords helm-top worked as expected.

Thanks, good to know.

> It would be probably better do not hardcode columns' number but
> provide a list variable containing the column numbers corresponding
> these fields which a user can customize.

Hmm, I thing I will opt for an alist, e.g ((pid . 0) .... (proc . 8)
etc... the user can customize.

> Even better, search using regex columns' numbers in top output but it
> is probably to much work .

Hard since it have to work with ps and top.

Thanks.

-- 
Thierry

**Comment by tollerm** [comment]
>
> Hmm, I thing I will opt for an alist, e.g ((pid . 0) .... (proc . 8)
> etc... the user can customize.
>
Perfect. Thank you.
T.
