### ISSUE TITLE
First source header disappears when scrolling down and back up 

### ISSUE THREAD

**Issue by therockmandolinist** [emacs-helm/helm#1587]
I'm getting an issue where when I scroll down, and then back up, I can no longer see the first source header. 

This is with a pretty standard, uncustomized config (I commented out all my own customizations to see if that was the issue):

~~~
      (use-package helm
        :ensure t
        :init
        (require 'helm-config)
        :config
        (use-package helm-descbinds
          ;; To describe keys in a nicer way
          :ensure t)
        (use-package helm-projectile
          ;; To use with projectile
          :ensure t
          :config
          (projectile-global-mode))
        (helm-mode 1)
        (global-set-key (kbd "M-x") 'helm-M-x)
        (global-set-key (kbd "<f1>") 'helm-find-files)
        (global-set-key (kbd "<f2>") 'helm-mini))
~~~

Behavior:
(See key presses on top)
![headererror](https://cloud.githubusercontent.com/assets/9020453/17880287/f91cceea-68ad-11e6-88c9-7c26ae1af94d.gif)

Not sure if this is intended or inevitable, but I guess it would make sense, as you can't place the cursor on the header lines in the first place.

EDIT: The more I think about this, the more I think it's just standard behavior and I just hadn't noticed until now. I'll leave this up just in case anyway...

**Comment by thierryvolpiatto** [comment]
Diego A. Mundo <notifications@github.com> writes:

> I'm getting an issue where when I scroll down, and then back up, I can
> no longer see the first source header.

Can't reproduce.

> This is with a pretty standard, uncustomized config

It is not, please start from emacs-helm.sh.

-- 
Thierry

**Comment by therockmandolinist** [comment]
Sorry, what do you mean by start from emacs-helm.sh? Is there a different way I should be loading helm in my init file?

**Comment by therockmandolinist** [comment]
I think I found the cause of the issue, this line:

`(setq scroll-conservatively 10000)`

which i set up as an attempt for smooth scrolling, wasn't playing nice with helm. Thanks for your feedback.
