### ISSUE TITLE
how to change the font and line spacing in helm buffer?

### ISSUE THREAD

**Issue by yilihong** [emacs-helm/helm#1589]
wonder if that is possible.

1. To have a different font size/family in helm buffer than the global

**Comment by xuchunyang** [comment]
Where does the screen shot come from? is it related to helm?

**Comment by yilihong** [comment]
@xuchunyang Sorry I deleted it and updated the question, I thought it was a helm buffer, but it is C+x a help buffer of Spacemacs.

**Comment by xuchunyang** [comment]
I don't familiar with font. But I do some search and find it is possible to set different font per buffer (according to [this Emacs SE question](http://emacs.stackexchange.com/questions/3038/using-a-different-font-for-each-major-mode) and [this emacs wiki page](https://www.emacswiki.org/emacs/FacesPerBuffer)), you can use something like

```elisp
;; Use variable width font faces in current buffer
(defun my-buffer-face-mode-variable ()
  "Set font to a variable width (proportional) fonts in current buffer"
  (interactive)
  (setq buffer-face-mode-face '(:family "Symbola" :height 100 :width semi-condensed))
  (buffer-face-mode))

(add-hook 'helm-major-mode-hook 'my-buffer-face-mode-variable)
```

You need to pick a font by yourself and if you don't like the line space provided by that font, maybe you can take a look at the `line-spacing` variable.

**Comment by yilihong** [comment]
@xuchunyang  thanks, this is very helpful.
