### ISSUE TITLE
install from melpa seems missing lots of files

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [emacs-helm/helm#1590]
.emacs config
```
(add-to-list 'package-archives '("marmalade" . "https://marmalade-repo.org/packages/"))
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
(add-to-list 'package-archives '("elpa" . "http://tromey.com/elpa/") t)
(add-to-list 'package-archives '("gnu" . "https://elpa.gnu.org/packages/"))
(add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/") t)
```

steps
```
package-install helm
```

my config file
```
(require 'helm)
(require 'helm-config)

(helm-mode 1)

(set-face-attribute 'helm-selection nil
                    :background "blue"
                    :foreground "#e3e32d")

(define-key helm-map (kbd "<tab>") 'helm-execute-persistent-action)
(define-key helm-map (kbd "C-z")  'helm-select-action)

(setq helm-split-window-in-side-p           t
      helm-move-to-line-cycle-in-source     t
      helm-ff-search-library-in-sexp        t
      helm-M-x-fuzzy-match                  t
      helm-buffers-fuzzy-matching           t
      helm-locate-fuzzy-match               t
      helm-recentf-fuzzy-match              t
      helm-scroll-amount                    8
      helm-ff-file-name-history-use-recentf t)

(helm-autoresize-mode 1)
```
result:
![helm](https://cloud.githubusercontent.com/assets/7458713/18030837/08749990-6cfa-11e6-84a1-cff6d532fbaa.png)

![emacs_error](https://cloud.githubusercontent.com/assets/7458713/18030847/6ab3bc80-6cfa-11e6-8130-7cd044c17fdd.png)

the issue occured just from today

**Comment by xuchunyang** [comment]
The latest version of helm on melpa is [20160827.1123](https://melpa.org/#/helm), then I don't understand where does your 20160828.223 come from, any idea?

**Comment by thierryvolpiatto** [comment]
ziyouchutuwenwu <notifications@github.com> writes:

> .emacs config
>

> (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
> (add-to-list 'package-archives '("gnu" . "https://elpa.gnu.org/packages/"))

> steps

(package-initialize)

> package-install helm

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
ziyouchutuwenwu <notifications@github.com> writes:

> result:
> helm    

And also cleanup this directory (remove it), it seems it is helm-core
files with helm-elscreen.el inside which is part of helm package, don't
know how it could get here...!!

Please read also carefully the README file on github about installing helm.

-- 
Thierry

**Comment by ziyouchutuwenwu** [comment]
i find the issue, my package-archives sources are
```
(require 'package)
(add-to-list 'package-archives '("marmalade" . "https://marmalade-repo.org/packages/"))
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
(add-to-list 'package-archives '("elpa" . "http://tromey.com/elpa/") t)
(add-to-list 'package-archives '("gnu" . "https://elpa.gnu.org/packages/"))
(add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/") t)
(add-to-list 'package-archives '("popkit" . "http://elpa.popkit.org/packages/"))
(package-initialize)
```

just remove
```
(add-to-list 'package-archives '("popkit" . "http://elpa.popkit.org/packages/"))
```

@xuchunyang, thanks for reminding me

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

> The latest version of helm on melpa is 20160827.1123, then I don't understand where does your 20160828.223 come from, any idea?

Perhaps the install is coming from one of the other repositories added
in addition of melpa and their timestamp is wrong there with their
packaging too ???

-- 
Thierry

**Comment by xuchunyang** [comment]
> Perhaps the install is coming from one of the other repositories added
> in addition of melpa and their timestamp is wrong there with their
> packaging too ???

That's right. The broken helm package comes from popkit (a fork of melpa). Anyway, this issue is not caused by helm itself.
