### ISSUE TITLE
Exclude `.elc` files from `helm-locate-library`

### ISSUE THREAD

**Issue by xiongtx** [emacs-helm/helm#1592]
## Problem
`helm-locate-library` includes `.elc` files, which seems unnecessary when `.el` files are available. Those who care to look into source code will want the original source, not the compiled bytecode.

## Suggested Solution

Exclude `.elc` files from `helm-locate-library` by modifying `helm-locate-library-scan-list`.

**Comment by thierryvolpiatto** [comment]
Is it ok like this ?

**Comment by xiongtx** [comment]
Yes, the issue is fixed. Thanks!
