### ISSUE TITLE
The mode line flashes when selecting candidates if `helm-follow-mode` is enabled.

### ISSUE THREAD

**Issue by Yevgnen** [emacs-helm/helm#1593]
When moving around a helm buffer (`helm-occur`) with `helm-follow-mode`, the mode line of the origin buffer and helm buffer keep flashing.

![helm](https://cloud.githubusercontent.com/assets/16749790/18222182/16d18e50-71c1-11e6-80a7-c5309be89ee6.gif)

It seems that the focus of the window keep changing all the time ?

Minimum config for reproducing is

    (require 'package)
    
    (setq package-archives '(("marmalade" . "http://marmalade-repo.org/packages/")
                             ("gnu" . "http://elpa.gnu.org/packages/")
                             ("melpa" . "https://melpa.org/packages/")
                             ("org" . "http://orgmode.org/elpa/")))
    
    (package-initialize)
    
    (unless (and (file-exists-p (expand-file-name "elpa/archives/marmalade" user-emacs-directory))
                 (file-exists-p (expand-file-name "elpa/archives/gnu" user-emacs-directory))
                 (file-exists-p (expand-file-name "elpa/archives/melpa" user-emacs-directory))
                 (file-exists-p (expand-file-name "elpa/archives/org" user-emacs-directory)))
      (package-refresh-contents))
    
    (unless (package-installed-p 'use-package)
      (package-refresh-contents)
      (package-install 'use-package))
    
    (setq use-package-verbose t)
    (require 'use-package)
    
    (use-package helm
      :ensure t
      :init
      (setq helm-quick-update t
            helm-move-to-line-cycle-in-source nil
            helm-split-window-default-side 'other
            helm-split-window-in-side-p t
            helm-echo-input-in-header-line nil))

Running an GNU Emacs 25.1.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911)) of 2016-07-25 with the latest elpa version of helm.

Any help will be appreciated! Thanks !

**Comment by xuchunyang** [comment]
I can reproduce.

**Comment by thierryvolpiatto** [comment]
Yevgnen <notifications@github.com> writes:

> When moving around a helm buffer with helm-follow-mode, the mode line of the origin buffer and helm buffer keep flashing.
>
> helm    
>
> It seems that the focus of the window keep changing all the time ?

Of course it is.  When for example used with helm-occur, helm jumps in
other buffer, highlight the line and some regexps around and come back to
helm buffer.
I have commited a fix, seems better now, let me know.

Thanks.

-- 
Thierry

**Comment by xuchunyang** [comment]
> I have commited a fix, seems better now, let me know.

Yes, it is better.  Thanks.
