### ISSUE TITLE
Put the project on site like Gratipay

### ISSUE THREAD

**Issue by xiongtx** [emacs-helm/helm#1594]
## Suggestion
Many popular Emacs projects, like [Orgmode](https://gratipay.com/org-mode/) and [CIDER](https://gratipay.com/cider/), are on [Gratipay](https://gratipay.com/). This allows the maintainers of these projects to receive weekly contributions (instead of alternatives like one-off donations).

Helm could benefit from being on a site like Gratipay and/or others, like Bountysource. Gratipay seems more popular with Emacs projects.

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> Suggestion
>
> Many popular Emacs projects, like Orgmode and CIDER, are on
> Gratipay. This allows the maintainers of these projects to receive
> weekly contributions (instead of alternatives like one-off donations).
>
> Helm could benefit from being on a site like Gratipa and/or others,
> like Bountysource. Gratipay seems more popular with Emacs projects.

Thanks to remind me this, helm was on gratipay, but when the site went
down I removed helm and forget to reinscribe since then.

--
Thierry

**Comment by thierryvolpiatto** [comment]
Done thanks.
