### ISSUE TITLE
Buffer window being scrolled when `helm-follow-mode` is enabled.

### ISSUE THREAD

**Issue by Yevgnen** [emacs-helm/helm#1596]
Sometimes the even the `*helm-*` buffer is smaller the max allowed height, the buffer window will be scrolled when the `*helm-*` pops up. Please see the gif for example.

The minimum reproducing setup is

    (require 'package)
    
    (setq package-archives '(("marmalade" . "http://marmalade-repo.org/packages/")
                             ("gnu" . "http://elpa.gnu.org/packages/")
                             ("melpa" . "https://melpa.org/packages/")
                             ("org" . "http://orgmode.org/elpa/")))
    
    (package-initialize)
    
    (unless (and (file-exists-p (expand-file-name "elpa/archives/marmalade" user-emacs-directory))
                 (file-exists-p (expand-file-name "elpa/archives/gnu" user-emacs-directory))
                 (file-exists-p (expand-file-name "elpa/archives/melpa" user-emacs-directory))
                 (file-exists-p (expand-file-name "elpa/archives/org" user-emacs-directory)))
      (package-refresh-contents))
    
    (unless (package-installed-p 'use-package)
      (package-refresh-contents)
      (package-install 'use-package))
    
    (setq use-package-verbose t)
    (require 'use-package)
    
    (use-package helm
      :ensure t
      :init
      (setq helm-source-names-using-follow '("Occur")
            helm-follow-mode-persistent t))

![o](https://cloud.githubusercontent.com/assets/16749790/18224861/9901fca2-7216-11e6-9d6c-0b6cf1ce2217.gif)

1. Save the above content as `.emacs`.
2. Use emacs open this `.emacs`.
3. `recenter` the line `(require 'package)` to be the first line(default when open the file), put the cursor under the `package`. `M-x` then `helm-occur`, everything is fine.
4. `recenter` the line `(package-initialize)` to be the first line, put the cursor under the `package`. `M-x` then `helm-occur`,  the `.emacs` buffer is scrolled down.

In step 4, if the line `(package-initialize)` is NOT recentered before `helm-occur` this will not happened.

If the `helm-follow-mode` is turn off(removing the `setq` segment, everything seems fine.

What I expected is that, the `*helm-occur*` buffer is small enough(both `recenter`s that line to the first line or not) and should not scroll down the origin buffer. This happens quite often when I use `helm-occur`.

Any help will be appreciated ! Thanks !

**Comment by thierryvolpiatto** [comment]
Yevgnen <notifications@github.com> writes:

>
> What I expected is that, the *helm-occur* buffer is small enough(both
> recenters that line to the first line or not) and should not scroll
> down the origin buffer.

It is not scrolled but recentered, it is not new behavior, it is like
this since a while and no body complained until now.
It is not a bad thing, this allow you to see easily the line highlighted
in the middle of the screen.
If you want to make the helm-buffer smaller on persistent action you can
use `helm-buffers-to-resize-on-pa`.

So I see no bug here.

--
Thierry

**Comment by Yevgnen** [comment]
I like the command panels of sublime and atom which act like a separate window and will not move the buffer window until it can't find the target thing in current visible area.

For me, moving the window up and down too much just a bit annoying. For example I'd like to set the `popwin` window to a suitable height for documents, help buffer and other popup windows to avoid the window moving as less as possible(when the cursor is above the max height of the popup window).

Anyway, thanks for your explanation, and maybe I'll try to get it ? 😐

**Comment by Yevgnen** [comment]
By the way, I think the current behaviour maybe a bit inconsistent when enable `helm-follow-mode` or disabled it ?

**Comment by thierryvolpiatto** [comment]
Yevgnen <notifications@github.com> writes:

> I like the command panels of sublime and atom which act like a separate window and will not move the buffer window until it can't find the target thing in current
> visible area.
>
> For me, moving the window up and down too much just a bit annoying. For example I'd like to set the popwin window to a suitable height for documents, help buffer and
> other popup windows to avoid the window moving as less as possible(when the cursor is above the max height of the popup window).
>
> Anyway, thanks for your explanation, and maybe I'll try to get it ? 😐

Helm is showing all matches around current line, if you keep it on top
you can't see the other matches BEFORE line.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
![capture d ecran_2016-09-03_17-44-02](https://cloud.githubusercontent.com/assets/1533939/18225848/3053d170-71fe-11e6-8b97-15627582908b.png)

**Comment by Yevgnen** [comment]
I know what you mean. But you may like to take a look of `swiper`, it also show all the matches, but locates in the nearest next one, not the first one of the whole buffer

**Comment by thierryvolpiatto** [comment]
Yevgnen <notifications@github.com> writes:

> I know what you mean. But you may like to take a look of swiper, it
> also show all the matches, but locates in the nearest next one, not
> the first one of the whole buffer

I don't know what swiper is doing, but I know that the current helm
behavior is exactly what I want, i.e showing the
`helm-highlight-matches-around-point-max-lines` before and after
highlighted line.

--
Thierry

**Comment by Yevgnen** [comment]
That's quite different from me here. Using the mentioned `.emacs`, when type `highlight` wherever the cursor is, the `*helm-occur*` is located to the first match and the origin buffer is scroll to there too.
![h](https://cloud.githubusercontent.com/assets/16749790/18228159/1ec9a0f4-7273-11e6-92fb-280a7b37f757.gif)

**Comment by thierryvolpiatto** [comment]
Sorry but I don't see what the problem is.
When you start helm-occur, current line with "window" is highlighted and recentered and the other "window" matches before and after are highlighted.
The swiper behavior is NOT what I want, so don't expect a change in this sens, it would be a regression IMO.

**Comment by Yevgnen** [comment]
Isn't the image your provided shown that after `helm-occur`, the cursor keep stopping in the current line ?

**Comment by Yevgnen** [comment]
I mean that `recente`ing the current line is ok though, but why locate to the first candidate ? The image you provided didn't move the current selection to the first candidate.

**Comment by xuchunyang** [comment]
> I mean that recenteing the current line is ok though, but why locate to the first candidate ? The image you provided didn't move the current selection to the first candidate.

I don't know why either, like Thierry, I can't reproduce with my own Emacs setup or `./emacs-helm.sh`.

**Comment by xuchunyang** [comment]
OK, I know how to reproduce now, you need to type the query manually, instead of using the default (some words or symbol around point).

> but why locate to the first candidate ?

I think because it is easy. Pre-selecting nearest matching needs extra work.

**Comment by Yevgnen** [comment]
I type the query manually using the minimum config above, and cannot get 
| i.e showing the
`helm-highlight-matches-around-point-max-lines` before and after
highlighted line.

**Comment by Yevgnen** [comment]
I think I should restate the issue here. 

1. At the beginning, I point out that `helm-occur` 'scrolls' the buffer window as the user start to type.

2. thierryvolpiatto point out that the 'scrolls' in fact is `recenter` and is a feature to help the user see the matches around current line.
> Helm is showing all matches around current line, if you keep it on top
you can't see the other matches BEFORE line.

3. I use the minimum config above, but find that the buffer window in fact is being 'scrolls' to the first match line, at least in my 
`GNU Emacs 25.1.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911)) of 2016-07-25` and `helm 20160903.531`.

So when typing a `helm-occur` query, it seems that the function keeps searching the whole buffer from the **beginning** of the buffer till it finds the first match line, so I can the the window moving up and down quite often.

P.s. While `swiper` will not recenter the window, `helm-swoop` will recenter the window exactly as thierryvolpiatto mentioned. Both of them start the search from **current** line. But `helm-occur` doesn't, as stated in 3.

**Comment by thierryvolpiatto** [comment]
Yevgnen <notifications@github.com> writes:

> Both of them start the search from current line.

It's non sense to search from current line only, why do you assume that
what you are searching is after the current line and not before ?

> But helm-occur doesn't, as stated in 3.

And will never start searching from current line, helm-occur search from
BOB with preselection of the current line if current line match pattern,
which is the case when starting up when helm-occur is in 
helm-sources-using-default-as-input which is the default.

So don't expect a change in the current behavior of helm-occur, I see no
reason to do so.

--
Thierry

**Comment by Yevgnen** [comment]
Sorry, my mistake. I'm not meaning that 'search from current line only', but the cursor stays in the next nearest candidate.
