### ISSUE TITLE
"C-j" to expand candidate fails.

### ISSUE THREAD

**Issue by gujiaxi** [emacs-helm/helm#1597]
## Description

In helm context, pressing `C-j` to expand candidate fails.

## Steps to reproduce (recipe)

- `M-x helm-find-files`.
- Move on to a directory.
- `C-j` to Expand Candidate.

## Backtraces if some (M-x toggle-debug-on-error)

```
Symbol's value as a variable is void: helm-follow-mode
```

## Emacs configs related to Helm

``` lisp
(require 'helm)
(require 'helm-config)
(helm-mode t)
```

## Describe versions of helm, emacs, operating system etc.

- helm-20160903.2135
- GNU Emacs 24.5.1 (i686-pc-mingw32)
- Windows 10

**Comment by thierryvolpiatto** [comment]
Isaac <notifications@github.com> writes:

> Symbol's value as a variable is void: helm-follow-mode

Thanks, it have been fixed, you should have it in next build.

-- 
Thierry
