### ISSUE TITLE
Preselect current heading in `helm-org-in-buffer-headings`

### ISSUE THREAD

**Issue by xiongtx** [emacs-helm/helm#1601]
## Expected behavior

`helm-org-in-buffer-headings` should preselect the current heading so the user has a sense of where they are in the document.

## Actual behavior from emacs-helm.sh if possible

`helm-org-in-buffer-headings` does not preselect the current heading.

## Steps to reproduce (recipe)

Call `helm-org-in-buffer-headings` in an Org document.

## Backtraces if some (M-x toggle-debug-on-error)

N/A

## Describe versions of helm, emacs, operating system etc.

- Helm: 2.1.0
- Emacs: 24.5.50.1
- OS: Fedora 23

**Comment by thierryvolpiatto** [comment]
Done, thanks.

**Comment by thierryvolpiatto** [comment]
Probably we should make this happen only when
helm-org-format-outline-path is nil otherwise people using
helm-org-format-outline-path will complain, also they don't really need
preselection as they can see at which level they are.
Will see.

Actually helm-org-format-outline-path is disabled for in-buffer headings.

-- 
Thierry

**Comment by xiongtx** [comment]
I'm not sure why they would complain; it'd still be useful to see the selection line on the current heading.

`helm-org-format-outline-path` appears to be `nil` by default.

**Comment by thierryvolpiatto** [comment]
But I must let-bound it to make preselection working properly.

Le 12 sept. 2016 08:58, "Tianxiang Xiong" <notifications@github.com> a
écrit :

**Comment by xiongtx** [comment]
Confirmed as fixed.

**Comment by alphapapa** [comment]
> Expected behavior:  helm-org-in-buffer-headings should preselect the current heading so the user has a sense of where they are in the document.

Just to be clear, this is not a bug fix but rather a feature request, right?  Because that is not the behavior I have come to expect.  ;)

**Comment by thierryvolpiatto** [comment]
alphapapa <notifications@github.com> writes:

>     Expected behavior: helm-org-in-buffer-headings should preselect
>     the current heading so the user has a sense of where they are in
>     the document.
>
> Just to be clear, this is not a bug fix but rather a feature request,
> right?

Yes.

> Because that is not the behavior I have come to expect. ;)

Ok, it is easy to make this customizable to have the previous behavior
back and make everybody happy, would it be ok for you like this?

--
Thierry

**Comment by alphapapa** [comment]
> Ok, it is easy to make this customizable to have the previous behavior back and make everybody happy, would it be ok for you like this?

It's kind of you to offer this, Thierry, but for now I suggest leaving it as-is.  I haven't experimented with it yet, so I might actually prefer the new behavior.   :)

Thanks for your tireless work on Helm!

**Comment by thierryvolpiatto** [comment]
alphapapa <notifications@github.com> writes:

>     Ok, it is easy to make this customizable to have the previous
>     behavior back and make everybody happy, would it be ok for you
>     like this?
>
> It's kind of you to offer this, Thierry, but for now I suggest leaving
> it as-is. I haven't experimented with it yet, so I might actually
> prefer the new behavior. :)

Ok let me know (you or nay one else) if you want this to be customized,
it is really easy to do.

> Thanks for your tireless work on Helm!

Thanks.

--
Thierry

**Comment by xiongtx** [comment]
Preselection should be the expected behavior. 

For most things, Helm detects context; if you `helm-find-files` with point on a file path, for example, the Helm buffer opens in that directory.
