### ISSUE TITLE
helm-M-x hides c++-mode

### ISSUE THREAD

**Issue by jemoreira** [emacs-helm/helm#1603]
When I use helm-M-x the command 'c++-mode' is hidden (not showing on the list of possible commands). if I use the standard M-x c++-mode shows normally.

**Comment by syohex** [comment]
You need to input `c\+\+-mode`. Regexp `c++-mode` does not match against `c++-mode`.

**Comment by jemoreira** [comment]
Thank you

**Comment by thierryvolpiatto** [comment]
If you enable fuzzy-matching in helm-M-x, you don't have to escape the special characters:

![capture d ecran_2016-09-13_06-58-48](https://cloud.githubusercontent.com/assets/1533939/18462126/ce07798e-797f-11e6-87f3-ed0b4140aa68.png)
