### ISSUE TITLE
helm-find-files

### ISSUE THREAD

**Issue by jack-ew** [emacs-helm/helm#1605]
## Expected behavior
If I open a directory with `helm-find-files` I will see all the Textfiles

## Actual behavior from emacs-helm.sh if possible
`helm-find-files` don't show all textfiles. In my case there are .mo files

## Steps to reproduce (recipe)
Call `helm-find-files` in a directory with textfiles which ends with .mo

## Backtraces if some (M-x toggle-debug-on-error)
N/A

## Describe versions of helm, emacs, operating system etc.
- helm: 20160911.2202
- emacs: 24.5.1
- OS: archlinux

**Comment by thierryvolpiatto** [comment]
Are you sure you are using ./emacs-helm.sh ?
I can't reproduce.

![capture d ecran_2016-09-13_13-19-25](https://cloud.githubusercontent.com/assets/1533939/18471999/ecf82b4c-79b4-11e6-8f94-7882c168da88.png)

**Comment by thierryvolpiatto** [comment]
I guess you have helm-boring-file-regexp-list excluding *.mo files and
helm-ff-skip-boring-files set to t.

-- 
Thierry

**Comment by jack-ew** [comment]
Thanks for the answer. `helm-ff-skip-boring-files` is set to t and then you can't see *.mo files . Why is *.mo an exclude? For me is it a modelica text file.

**Comment by thierryvolpiatto** [comment]
jack-ew <notifications@github.com> writes:

> Thanks for the answer. helm-ff-skip-boring-files is set to t and then
> you can't see *.mo files . Why is *.mo an exclude?

Dunno, I builded the default list against
`completion-ignored-extensions`, but you can customize it easily with
M-x customize-variable => helm-boring-file-regexp-list

--
Thierry

**Comment by michael-heerdegen** [comment]
jack-ew <notifications@github.com> writes:

> Thanks for the answer. helm-ff-skip-boring-files is set to t and then
> you can't see *.mo files . Why is *.mo an exclude? For me is it a
> modelica text file.

From https://en.wikipedia.org/wiki/.mo:

    .mo can also refer to the file extension of binary files that have
    been compiled from .po files using GNU gettext.
