### ISSUE TITLE
helm-show-kill-ring hangs

### ISSUE THREAD

**Issue by mbuczko** [emacs-helm/helm#1606]
helm 20160913.2108, ```helm-show-kill-ring``` permanently hangs and can be stopped only with ```C-g```.

**Comment by thierryvolpiatto** [comment]
Michał Buczko <notifications@github.com> writes:

> helm 20160913.2108, helm-show-kill-ring permanently hangs and can be
> stopped only with C-g.

Can't reproduce, did you start from ./emacs-helm.sh ?

--
Thierry

**Comment by mbuczko** [comment]
I have just checked with emacs-helm.sh and looks like it's not a problem of helm itself but rather prelude configuration which I use. Sorry for raising a false flag.
