### ISSUE TITLE
Merged results from multiple sources

### ISSUE THREAD

**Issue by theduke** [emacs-helm/helm#1607]
When running 

```elint
(interactive)
(helm :sources '(helm-source-projectile-files-list helm-source-bookmarks)
```

The results are separated in two distinct lists by source.

Is there a feature to show a single list instead, with the type of the result as a column/prefix/postfix?

**Comment by thierryvolpiatto** [comment]
theduke <notifications@github.com> writes:

> When running
>
> (interactive)
> (helm :sources '(helm-source-projectile-files-list helm-source-bookmarks)
>
> The results are separated in two distinct lists by source.
>
> Is there a feature to show a single list instead, with the type of the
> result as a column/prefix/postfix?

No.

--
Thierry

**Comment by xiongtx** [comment]
Being able to combine different sources in a single Helm buffer is a useful feature.

There's no way to automatically combine sources. Even in theory, doing so would be problematic: candidates in a source are subject to the same set of *actions*, e.g. "Open file". How would this work if you combine files with bookmarks?

A few tips to make dealing with multiple sources easier:

- Navigate between sources with `helm-previous-source` and `helm-next-source`
- Show only the candidates in the current source with `helm-show-all-in-this-source-only` and show all candidates in all sources with `helm-display-all-sources`
