### ISSUE TITLE
Suggestion: move documentation into project Org files

### ISSUE THREAD

**Issue by xiongtx** [emacs-helm/helm#1608]
## Expected behavior

Many projects, such as [CIDER](https://github.com/clojure-emacs/cider/tree/master/doc), keep documentation in separate files in a project directory. This keeps things organized and allows documentation to be hosted on sites like [Read the Docs](https://readthedocs.org/).

It would benefit Helm to do the same. In fact, the project already has a `doc` directory, which contains a lone GIF.
## Actual behavior from emacs-helm.sh if possible

Currently, Helm keeps documentation in two (main) places:
- Variables in [helm-help.el](https://github.com/emacs-helm/helm/blob/master/helm-help.el).
- [Project wiki](https://github.com/emacs-helm/helm/wiki)

This has disadvantages due to [duplication](https://en.wikipedia.org/wiki/Single_source_of_truth) and out-of-sync information. It is particularly difficult to keep the wiki up to date, since wiki pages are kept in a repository separate from the project itself.
## Suggested solution
- Bring documentation out of variables and Wiki pages into separate Org files within the project. 
- Reserve Wiki pages for "community" issues, such as [using Helm with Popwin](https://github.com/emacs-helm/helm/wiki/Popwin).

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

>   * Bring documentation out of variables

Did you try M-x helm-documentation ?

>   and Wiki pages into separate Org files within the project.  *
>   Reserve Wiki pages for "community" issues, such as using Helm with
>   Popwin.

Would be nice, but sorry I have not enough time to fix bugs on helm,
provide feature requests etc... and manage documentation.
I already try to make the embeded documentation the best as I can, but
that's the maximum I can do.

-- 
Thierry

**Comment by xiongtx** [comment]
Yes, I know about `helm-documentation`.

> Would be nice, but sorry I have not enough time to fix bugs on helm, provide feature requests etc... and manage documentation.

Yeah, this would probably need to be something done over a long period of time. And it's not just you--others can contribute as well, of course.
