### ISSUE TITLE
describe-face completion and persistent action support

### ISSUE THREAD

**Issue by fice-t** [emacs-helm/helm#1613]
## Expected behavior
`M-x describe-face` works like `describe-function` and `describe-variable`, but with faces.

## Actual behavior from emacs-helm.sh if possible
`describe-face` is not "helmized".

## Steps to reproduce (recipe)
`./emacs-helm.sh`
`M-x descibe-face RET`

## Describe versions of helm, emacs, operating system etc.
* Latest version of helm from MELPA
* Emacs 25.1
* GNU/Linux

**Comment by xiongtx** [comment]
You can use `helm-apropos`, which includes `helm-def-source--emacs-faces` as a source.

**Comment by fice-t** [comment]
Oh, that's really interesting, thanks. Particularly the application of the face onto the face name while searching.

I don't suppose helm could make `describe-face` do the same thing automatically for faces only?

**Comment by xiongtx** [comment]
It can certainly be done, but I personally don't think it's worthwhile.

- You can complete faces with `describe-face` by hitting `TAB`. The faces are not colored, though.
- You can find faces with `helm-apropos` or `helm-colors`. 
  - The latter is useful if you just need to customize a face (as opposed to find it in a source file), because the colors are not hidden by the `helm-match` face.

**Comment by fice-t** [comment]
> You can complete faces with describe-face by hitting TAB. The faces are not colored, though.

Right, but the main feature I was hoping for is to have a helm persistent action that would open up the face's help buffer.

> You can find faces with helm-apropos or helm-colors.

`helm-colors` looks even better, thanks. However, can it be changed/customized to bring up the help buffer for the corresponding face instead of the customize buffer? That way it would be easier to see the face's attributes quickly.

**Comment by xiongtx** [comment]
> the main feature I was hoping for is to have a helm persistent action that would open up the face's help buffer.

`helm-apropos` already does that?

**Comment by fice-t** [comment]
Yes, but it has more than just a face source. It seems like `helm-colors` with that particular persistent action is the best. Is the following method the recommended way to achieve it?

```elisp
(defun my-helm-colors ()
  "Preconfigured `helm' for color."
  (interactive)
  (helm :sources '(helm-source-colors helm-source-describe-face)
        :buffer "*helm colors*"))


(defvar helm-source-describe-face
  (helm-build-in-buffer-source "Describe Face"
    :init 'helm-custom-faces-init
    :get-line 'buffer-substring
    :action '(("Describe"
               . (lambda (line)
                   (describe-face (intern (car (split-string line))))))
              ("Customize"
               . (lambda (line)
                   (customize-face (intern (car (split-string line))))))
              ("Copy name"
               . (lambda (line)
                   (kill-new (car (split-string line " " t)))))))
  "See (info \"(emacs)Faces\")")
```

Also, there appears to be a bug in `helm-colors` and therefore `my-helm-colors`. A 2nd persistent action on the same line does not remove the 1st persistent action like it does in `C-h f`, `C-h v`, or `helm-M-x`.

**Comment by thierryvolpiatto** [comment]
fice-t <notifications@github.com> writes:

>     You can complete faces with describe-face by hitting TAB. The faces are not colored, though.
>
> Right, but the main feature I was hoping for is to have a helm
> persistent action that would open up the face's help buffer.

No, we don't add more than what is provided by emacs vanilla for generic
helmized completions.
describe-variable/function are exceptions because it didn't arm doing
this and was really easy adding this.
Here describe-face is using a completing-read-multiple and helm-mode is
completing against this CRM, so it is not possible adding anyrhing else
here.

--
Thierry

**Comment by thierryvolpiatto** [comment]
fice-t <notifications@github.com> writes:

> Also, there appears to be a bug in helm-colors and therefore
> my-helm-colors. A 2nd persistent action on the same line does not
> remove the 1st persistent action like it does in C-h f, C-h v, or
> helm-M-x.

This have now been fixed, thanks.

--
Thierry

**Comment by fice-t** [comment]
@xiongtx 
Sorry, I didn't notice that you edited your comment.

> If you really want to have faces as a single source, just:

That's great, thanks. I'll close this and use something like that.

@thierryvolpiatto 
Thanks for the fix.

> Here describe-face is using a completing-read-multiple and helm-mode is completing against this CRM, so it is not possible adding anyrhing else here.

Hmm, so CRM can't be supported by helm like regular `completing-read`?

**Comment by xiongtx** [comment]
> Hmm, so CRM can't be supported by helm like regular `completing-read`?

How would that work? If you enter multiple candidates, which would Helm match against?

**Comment by fice-t** [comment]
Perhaps Helm could match the candidate where the point is in the minibuffer using `crm-separator`. For example:

* Blank state/single candidate: The same as in `completing-read`.

* Single candidate+comma (`crm-separator`): Start a new blank match.

* If you move the point back onto the previous candidate, the helm match changes back.

* If you enter a new selection in this state, then the current candidate is updated and the point is moved past the CRM separator.

**Comment by thierryvolpiatto** [comment]
fice-t <notifications@github.com> writes:

> Hmm, so CRM can't be supported by helm like regular completing-read?

No, CRM IS fully supported by helm.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
fice-t <notifications@github.com> writes:

> Perhaps Helm could match the candidate where the point is in the
> minibuffer using crm-separator. For example:
>
>   * Blank state/single candidate: The same as in completing-read.
>
>   * Single candidate+comma (crm-separator): Start a new blank match.
>
>   * If you move the point back onto the previous candidate, the helm
>   match changes back.
>
>   * If you enter a new selection in this state, then the current
>   candidate is updated and the point is moved past the CRM separator.

No, as I said previously generic helm functions are behaving like emacs
vanilla, no more, don't expect a change in this.

Please try to see how CRM works.

For the describe-face case CRM is used to allow user showing several
faces in the same help buffer.

--
Thierry

**Comment by fice-t** [comment]
@thierryvolpiatto Using your fix straight from `emacs-helm.sh` results in:
`Symbol's function definition is void: helm-elisp--persistent-help`

Looks like `helm-elisp.el` isn't required in `helm-color.el`.

**Comment by thierryvolpiatto** [comment]
fice-t <notifications@github.com> writes:

> Looks like helm-elisp.el isn't required in helm-color.el.

Indeed, thanks.

-- 
Thierry

**Comment by fice-t** [comment]
@thierryvolpiatto 
> No, CRM IS fully supported by helm.

For completion; not for persistent action or live preview, it seems.

> No, as I said previously generic helm functions are behaving like emacs vanilla, no more, don't expect a change in this. 

Right, though it would be nice. :)

> Please try to see how CRM works. For the describe-face case CRM is used to allow user showing several faces in the same help buffer.

Indeed, but does that contradict my proposal above? If Helm uses the point position in the minibuffer to determine the "current candidate", then couldn't it work somewhat like regular `completing-read`?

That is,  helm could match whatever candidate the point is currently on, and persistent action should work the same as before.

**Comment by thierryvolpiatto** [comment]
fice-t <notifications@github.com> writes:

> @thierryvolpiatto
>
>     No, CRM IS fully supported by helm.
>
> For completion; not for persistent action or live preview, it seems.
>
>     No, as I said previously generic helm functions are behaving like emacs vanilla, no more, don't expect a change in this.
>
> Right, though it would be nice. :)

No it would not be nice, generic completion should work just as the
original functions no more.

> If Helm uses the point position in the minibuffer to determine the
> "current candidate",

No for CRM helm complete against the candidate at point, that is before
or after the separator.
It is how CRM works.

> That is, helm could match whatever candidate the point is currently
> on, and persistent action should work the same as before.

Sorry but no, I disagree.

--
Thierry

**Comment by fice-t** [comment]
@thierryvolpiatto 
> No it would not be nice, generic completion should work just as the original functions no more.

I don't understand. I would argue that `completing-read` is more generic than `completing-read-multiple`, and yet Helm does more for `completing-read` (live preview in particular).

> No for CRM helm complete against the candidate at point, that is before or after the separator. It is how CRM works.

Yes, and as I understand it my proposal above does the same. So it's not changing how CRM works, but how Helm itself works with CRM.

> Sorry but no, I disagree.

It's not a big deal either way for me since I don't come across CRM that often, but I still think live preview/persistent action for CRM would be nice.

**Comment by thierryvolpiatto** [comment]
fice-t <notifications@github.com> writes:

> I don't understand. I would argue that completing-read is more generic
> than completing-read-multiple,

CRM is not working with completing-read but completion-in-region.

> and yet Helm does more for completing-read (live preview in
> particular).

No, only for symbols because they have a specialized handler.

--
Thierry
