### ISSUE TITLE
helm-find-files realy needs TAB

### ISSUE THREAD

**Issue by liborw** [emacs-helm/helm#1616]
I know that here TAB is almost a rude word, but the helm-find-files is really pain without it. Yes I have read the [1](https://github.com/emacs-helm/helm/wiki#helm-completion-vs-emacs-completion) and [2](https://github.com/emacs-helm/helm/wiki#helm-interaction-model), but this doesn't work for finding files.

To find file in `/foo/bar/readme.txt`  one has to either write full `/foo/bar/` or use right arrow, why not TAB??

**Comment by xiongtx** [comment]
Use `C-j` instead. 

`TAB` is for viewing actions. See the [Helm interaction model](https://github.com/emacs-helm/helm/wiki#helm-interaction-model) for more.

Also consider turning on file name auto-expansion by setting `helm-ff-auto-update-initial-value` to `t`. In `helm-find-files`, toggle it on or off with `C-<backspace>`.

**Comment by liborw** [comment]
Actually, there is no explanation why, there is just that interactivity makes the tab redundant, but it doesn't seems so, if there is different keystroke for the same functionality.

**Comment by thierryvolpiatto** [comment]
TAB is for actions in helm, there is no more explanation needed.
If you are not happy with this, look in the emacs manual how to modify keybindings and modify the use of TAB in helm or more specifically in helm-find-files.

**Comment by mashu** [comment]
Despite all naysayers, I would still suggest giving user an option to use TAB instead of C-j as it is way faster (1 key vs 2 keys placed not so conveniently). Especially that a lot of people will be doing that binding, finding files is one of most often used features so maybe it should be supported out of box as option ?

Regards,
