### ISSUE TITLE
helm-find-1 customize filepattern

### ISSUE THREAD

**Issue by yuandaxing** [emacs-helm/helm#1617]
## Expected behavior
(helm-find-1 directory filepattern)
directory is some directory of my machine, i have hard code it.
filepattern is (thing-at-point 'filename), how to customize it's behavior.

## Actual behavior from emacs-helm.sh if possible
(helm-find-1 dir)

## Describe versions of helm, emacs, operating system etc.
helm version: 20160918.938

**Comment by thierryvolpiatto** [comment]
yuandaxing <notifications@github.com> writes:

> Expected behavior
>
> (helm-find-1 directory filepattern)

No you don't have to use this.
Add instead `helm-source-findutils` to `helm-sources-using-default-as-input`
and use `helm-find`.

-- 
Thierry

**Comment by yuandaxing** [comment]
@thierryvolpiatto , I'm not good at elisp, could you please give some details? 
t

**Comment by thierryvolpiatto** [comment]
yuandaxing <notifications@github.com> writes:

> @thierryvolpiatto , I'm not good at elisp, could you please give some details?

`(add-to-list 'helm-sources-using-default-as-input 'helm-source-findutils)`

and

M-x helm-find


Note: If you don't want to write elisp code at all, use M-x
customize-variable RET helm-sources-using-default-as-input RET
ans add helm-source-findutils.

-- 
Thierry

**Comment by yuandaxing** [comment]
I do as you suggest.
below is the "describe variable helm-sources-using-default-as-input"
(helm-source-findutils helm-source-imenu helm-source-imenu-all helm-source-info-elisp helm-source-etags-select helm-source-man-pages helm-source-occur helm-source-moccur helm-source-grep-ag helm-source-grep-git helm-source-grep)
then 
M-x helm-find,
the string of the filename do not grab as the input.

**Comment by thierryvolpiatto** [comment]
yuandaxing <notifications@github.com> writes:

> the string of the filename do not grab as the input.

Not as input but _default-as-input_; The difference is that your thing-at-point
doesn't appear in minibuffer but is initially computed as default, which
allow you to start writing something in prompt immediately if default is
not what you are interested in.

-- 
Thierry

**Comment by yuandaxing** [comment]
Yes, it works !
helm-find search the word, not the filename.

**Comment by thierryvolpiatto** [comment]
yuandaxing <notifications@github.com> writes:

> Yes, it works !
> helm-find search the word, not the filename.

The default :default is `(thing-at-point 'symbol)`, not word but I can
modify `helm-find-1` to use a :default value of `(thing-at-point
'filename)`.

You can eval this definition of `helm-find-1` to see if it better fit your
needs:

    (defun helm-find-1 (dir)
      (let ((default-directory (file-name-as-directory dir)))
        (helm :sources 'helm-source-findutils
              :buffer "*helm find*"
              :ff-transformer-show-only-basename nil
              :default (thing-at-point 'filename)
              :case-fold-search helm-file-name-case-fold-search)))

See also what M-n does and how to insert word by word with C-w in
minibuffer.
 
-- 
Thierry

**Comment by yuandaxing** [comment]
great, it works!
but i think you should bind helm-findutils-search-full-path to t. because (thing-at-point 'filename) will grab the full path.

**Comment by thierryvolpiatto** [comment]
yuandaxing <notifications@github.com> writes:

> great, it works!
> but i think you should bind helm-findutils-search-full-path to t. because (thing-at-point 'filename) will grab the full path.

Note that if you have a full path at point, you don't need to run find
to reach it, a simple M-x helm-find-files will do the job ;:)


-- 
Thierry

**Comment by yuandaxing** [comment]
got it, thanks.
