### ISSUE TITLE
Smart case sensitivity fails when grepping multiple words

### ISSUE THREAD

**Issue by Nielius** [emacs-helm/helm#1618]
When I use `helm-do-grep-1` with the smart case sensitivity/case-fold-search (i.e., I just use the standard `helm-grep-default-command`, which is `grep --color=always -a -d skip %e -n%cH -e %p %f` and which has the format spec `%c` for smart case sensitivity) *and* multiple words, only the first word has the smart case sensitivity, while the others are always case sensitive. The reason seems to be the following: when I apply helm-do-grep-1 to some files and enter the pattern `foo bar`, the actual command that is executed (according to the helm grep buffer) is:

```grep --color=always -a -d skip --exclude=.\#\* (many more exclude options) -niH -e foo some-file-names-here  | grep --color=always bar```

Clearly, what follows the pipe operator is case sensitive.

## Expected behavior
The expected behavior should be that
`foo bar` is case insensitive, while `foo Bar` or any other pattern with a capital letter is not.

## Actual behavior from emacs-helm.sh if possible
Every word except for the first is matched case sensitively, so that `foo bar` does not match `foo Bar`, while `bar foo` does.

## Steps to reproduce (recipe)
Run `(helm-do-grep-1 "some-file")` and search.

## Describe versions of helm, emacs, operating system etc.
GNU Emacs 26.0.50.2 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2016-10-02
Helm version: 20160929.1313

**Comment by thierryvolpiatto** [comment]
Nielius <notifications@github.com> writes:

> Expected behavior
>
> The expected behavior should be that foo bar is case insensitive,
> while foo Bar or any other pattern with a capital letter is not.

Indeed, thanks for catching this, will fix ASAP.


--
Thierry
