### ISSUE TITLE
how to make helm-imenu save results into a buffer?

### ISSUE THREAD

**Issue by tddsg** [emacs-helm/helm#1619]
## Expected behavior
When using `helm-imenu`, I expect it allows the results to be saved in a buffer, so that I can look at it later without having to call `helm-imenu` again.

This feature is availble in `helm-grep`, `helm-ag` (by pressing `F3` in the helm windows that display the results)

## Actual behavior from emacs-helm.sh if possible

No option to save the results found by `helm-imenu` into a buffer.

## Steps to reproduce (recipe)

`M-x helm-imenu`, type some characters to see the discovered items. There is no option to save the discovered items into a buffer.

## Describe versions of helm, emacs, operating system etc.
`helm-20160926.1203`  on Linux Mint 17.3

**Comment by thierryvolpiatto** [comment]
tddsg <notifications@github.com> writes:

> Expected behavior
>
> When using helm-imenu, I expect it allows the results to be saved in a
> buffer,

Sorry, but no this will not happen, it make sense to save grep results
but not imenu results IMO.

-- 
Thierry

**Comment by tddsg** [comment]
Thank you for the respond! 
I just thought it could be helpful to save the `helm-imenu` result as a reference of source code outline.
