### ISSUE TITLE
`helm-info-*` is blank for some Info files

### ISSUE THREAD

**Issue by xiongtx** [emacs-helm/helm#1620]
## Expected behavior

`helm-info-*` should show index for all Info files.

## Actual behavior from emacs-helm.sh if possible

For some Info files, `helm-info-*` is blank. For example, `helm-info-ert` does not show anything for me.

## Steps to reproduce (recipe)

Start Helm with `ert.info.gz` is in `/usr/local/share/info/`. Other Info files in the same directory, like `eieio.info.gz` and `flymake.info.gz`, show indices when calling their respective `helm-info-*` commands.

## Backtraces if some (M-x toggle-debug-on-error)

N/A

## Describe versions of helm, emacs, operating system etc.

Helm: 2.1.0
Emacs: 25.1.1
OS: Fedora 23

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> helm-info-* should show index for all Info files.

Only if info file have index.  Perhaps we should detect and ignore such
files.

> For some Info files, helm-info-* is blank.

Yes I know, it really depends of the info file (no index), if you take a
file from same place, e.g erc.info.gz, the index is shown.

> For example, helm-info-ert does not show anything for me.

This info file have no index.

--
Thierry

**Comment by xiongtx** [comment]
Is the index something that is generated automatically by the TexInfo tool, or does it have to be manually created (the author has to put index markers into the text, etc.)?

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> Is the index something that is generated automatically by the TexInfo
> tool, or does it have to be manually created (the author has to put
> index markers into the text, etc.)?

I am not an expert of TexInfo, but I think it have to be done manually
by the author.

--
Thierry

**Comment by xiongtx** [comment]
In that case, we can close this issue.
