### ISSUE TITLE
Expansion of refile targets in orgmode

### ISSUE THREAD

**Issue by dinojr** [emacs-helm/helm#1621]
## Expected behavior
When running helm-find-file, C-z (helm-execute-persistent-action)
expands the candidate filename. I'd like to get this behaviour when
using helm to get refile candidates in org-mode.

## Actual behavior from emacs-helm.sh if possible
C-z doesn't do anything.

## Steps to reproduce (recipe)
Type "info Main" in the helm minibuffer when there
is "info.org/Maintenance" among the candidates
C-z should to expand to "info.org/Maintenance/".

## Describe versions of helm, emacs, operating system etc.
helm-20160929.1313 from melpa
GNU Emacs 26.0.50.2 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2016-10-09
Ubuntu 16.04
Org-mode version 8.3.6 (release_8.3.6-1190-g17e73c @ /home/wilk/git-repositories/org-mode/lisp/)

**Comment by thierryvolpiatto** [comment]
Julien Cubizolles <notifications@github.com> writes:

> Steps to reproduce (recipe)
>
> Type "info Main" in the helm minibuffer when there
> is "info.org/Maintenance" among the candidates
> C-z should to expand to "info.org/Maintenance/".

Please provide a full recipe of what you are actually doing, you lost
me, I actually don't know what helm command you are using, if you are
browsing a org directory, the headers of an org buffer and with which
tool, what is "info.org/Maintenance/", a file? a org header? else?

Thanks.

-- 
Thierry

**Comment by dinojr** [comment]
with emacs-helm.sh, in a new buffer

+ M-x org-mode
+ Create three headings
  
  * First Heading
  * Second Heading
  * Third Heading

+ With point on first heading, run M-x org-refile
+ C-z should expand in the minibuffer to the candidate proposed in the org-refile buffer: "First Heading".      It doesn't seem to have any effect.

Sorry about being so unclear in my first post. Thanks for looking into this.

Julien.

**Comment by thierryvolpiatto** [comment]
Julien Cubizolles <notifications@github.com> writes:

> with emacs-helm.sh, in a new buffer
>
>   * M-x org-mode
>   * Create three headings
>
>       + First Heading
>       + Second Heading
>       + Third Heading
>   * With point on first heading, run M-x org-refile
>
>   * C-z should expand in the minibuffer to the candidate proposed in
>   the org-refile buffer: "First Heading". It doesn't seem to have any
>   effect.

Helm is using a generic function for `org-refile` that cannot do more
than the vanilla emacs one, so persistent action cannot be modified
especially for this.
See `helm-org-in-buffer-headings` which have an action that allow
refiling also but can be modified if needed, tell me what's need to be
modified in this case.

Thanks.

--
Thierry

**Comment by dinojr** [comment]
It's much clearer to me now. Running helm-org-agenda-files-headings with helm-org-format-outline-path set to t is very useful. There are two things that could be added:

* another action to expand the candidate in the helm minibuffer, the way C-z does it in helm-find-files when  the candidate is a directory. Right now if you want to create a new heading when refiling (with org-refile-allow-creating-parent-nodes set to t) you have to manually type the whole node structure (with helm-org-format-outline-path set to t) before using helm-org-run-heading-refile

* helm-org-agenda-files-headings could display the name of the file where the heading resides, maybe like: (name-of-org-file)/1st Level heading/2nd Level heading.

Thanks a lot for your help.

**Comment by thierryvolpiatto** [comment]
Julien Cubizolles <notifications@github.com> writes:

> It's much clearer to me now. Running helm-org-agenda-files-headings
> with helm-org-format-outline-path set to t is very useful. There are
> two things that could be added:

Ok, thanks for the feedback.  I will look into all this ASAP.

-- 
Thierry

**Comment by dinojr** [comment]
I'll be sure to test when you have something ready.

**Comment by thierryvolpiatto** [comment]
Julien Cubizolles <notifications@github.com> writes:

> I'll be sure to test when you have something ready.

I have not yet started working on this, but for your second request,
isn't `helm-org-show-filename` doing what you asked for ?

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
And for the first request, perhaps C-c C-y (helm-yank-selection) is good
enough ?

-- 
Thierry

**Comment by dinojr** [comment]
Indeed, both are exactly what I was looking for. I was so used to C-z that I didn't think of helm-yank-selection, and for some reason helm-org-show-filename wasn't showing up with describe-variable.

**Comment by thierryvolpiatto** [comment]
Julien Cubizolles <notifications@github.com> writes:

> Indeed, both are exactly what I was looking for.

Great.

> for some reason helm-org-show-filename wasn't showing up with
> describe-variable.

It showup only when helm-org is loaded (after one call of one of its
autoloaded commands).

Thanks.

--
Thierry

**Comment by sk8ingdom** [comment]
Is there an easy way to make helm-yank-selection the default helm-execute-persistent-action during org-refile? Or at least re-map it during the command?
