### ISSUE TITLE
Moving (renaming) a file into another directory should change `default-directory`

### ISSUE THREAD

**Issue by xiongtx** [emacs-helm/helm#1622]
## Expected behavior

When moving (renaming) a file being visited by a buffer using `helm-find-files` to a different directory, the buffer's `default-directory` should be set to the new directory.

Note that `buffer-file-name` is set correctly to the new directory; `default-directory` certainly should as well.

## Actual behavior from emacs-helm.sh if possible

The buffer's `default-directory` remains the old directory.

## Steps to reproduce (recipe)

1. Create a file in a directory.
   - E.g. `temp.txt` in `~/`.
2. Open the file in a buffer.
2. Use `helm-find-files` to move the file to another directory (e.g. `~/Dropbox/`).
3. Call `helm-find-files` again in the buffer.
   - See that the opened directory is the previous directory (`~/`), not the file's current directory (`~/Dropbox/`)

## Backtraces if some (M-x toggle-debug-on-error)

N/A

## Describe versions of helm, emacs, operating system etc.

- Helm: 2.1.0
- Emacs: 25.1.1
- OS: Fedora 24

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> Expected behavior
>
> When moving (renaming) a file being visited by a buffer using
> helm-find-files to a different directory, the buffer's
> default-directory should be set to the new directory.
>
> Note that buffer-file-name is set correctly to the new directory;
> default-directory certainly should as well.

I agree with you, but I am not sure the emacs developers agree with
this.

> Actual behavior from emacs-helm.sh if possible
>
> The buffer's default-directory remains the old directory.

This is the emacs -Q behavior with M-x rename-file.
However this problem is fixed when using `dired-async-mode`.

--
Thierry

**Comment by xiongtx** [comment]
Ugh...*of course* `rename-file` is a C function. Oh well, thanks for looking into this.
