### ISSUE TITLE
How to visit next file in helm-grep without being on the helm-grep buffer?

### ISSUE THREAD

**Issue by pcompassion** [emacs-helm/helm#1623]
This is a question or feature request.  

Suppose I do helm-grep and save it to a wgrep buffer.
I can visit files by M-n M-p when I'm in the wgrep buffer.

When I need to edit files, (and it happens a lot), here's what I have to do

* visit file 
* edit the file
* go back to the wgrep buffer
* M-n to locate the next file
* enter to visit the file

What I'd like to have is (helm-git-grep lets me do this by binding M-n to `next-error` (I don't know why that works, maybe emacs is recognizing the helm-git-grep's result as error list) (I have split windows where one has the result and one has the file to edit)

* visit file
* edit the file
* M-n to visit the next file

I know I could edit the wgrep buffer directly, but there are many cases where you need to visit the file itself.

I could make a macro "M-n" to do what I want, but wonder if there's a better way.

I think it's used elsewhere and wonder if I'm just not finding the right command to do it with helm-grep

https://www.emacswiki.org/emacs/GrepMode
> Hits from ‘M-x grep’ can be iterated through using `C-x `’. This runs Emacs command ‘next-error’.

**Comment by thierryvolpiatto** [comment]
pcompassion <notifications@github.com> writes:

> This is a question or feature request.
>
> Suppose I do helm-grep and save it to a wgrep buffer.

This is not a wgrep buffer, but a helm-grep-mode buffer.

> What I'd like to have is (helm-git-grep lets me do this by binding M-n
> to next-error

I don't know what helm-git-grep is, but don't expect an implementation
of next-error in helm.

I don't believe next-error is efficient (this have been discussed) in
emacs, except in compile buffer perhaps.
Anyway next-error would bring you to a wrong place as soon as you have
modified your file.

I suggest you change your workflow and use instead helm-resume for such work. 


-- 
Thierry
