### ISSUE TITLE
Add ripgrep

### ISSUE THREAD

**Issue by koterpillar** [emacs-helm/helm#1624]
[Ripgrep](https://github.com/BurntSushi/ripgrep) is a search tool claiming to be faster and more correct WRT Unicode than The Silver Searcher (ag). It would be nice to have it in Helm. The invocation syntax of `rg` is very similar to `ag`; the only difference I've seen is the file type limiting - `--type py` instead of `--python`.

**Comment by xuchunyang** [comment]
You can customize the user option `helm-grep-ag-command`, for example, something like

    (setq helm-grep-ag-command "rg --smart-case --no-heading --line-number %s %s %s")

almost works for me (both `--no-heading` and `--line-number` are required), except colors with `--color=always` doesn't work, it looks like it is because Emacs/Helm can't convert certain escape color code (for example, `simple-io.c:^[[91m^[[1mmain^[(B^[[m (void)`) into Emacs text propertiies, so I didn't add it. And searching on certain file type also is also not supported for the change of the syntax like you said.

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

> You can customize the user option helm-grep-ag-command, for example, something like
>
> (setq helm-grep-ag-command "rg --smart-case --no-heading --line-number %s %s %s")
>
> almost works for me (both --no-heading and --line-number are
> required), except colors with --color=always doesn't work, it looks
> like it is because Emacs/Helm can't convert certain escape color code
> (for example, simple-io.c:^[[91m^[[1mmain^[(B^[[m (void)) into Emacs
> text propertiies, so I didn't add it. And searching on certain file
> type also is also not supported for the change of the syntax like you
> said.

I will look into this as soon as I can checkout and install ripgrep.
So IIUC two things to fix:

- Ansi sequences
- The --type argument to handle instead of the type itself.

Thanks.

--
Thierry

**Comment by thierryvolpiatto** [comment]
See #1625, it is a work in progress, types are now available, didn't work yet on color.

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

> You can customize the user option helm-grep-ag-command, for example, something like
>
> (setq helm-grep-ag-command "rg --smart-case --no-heading --line-number %s %s %s")
>
> almost works for me (both --no-heading and --line-number are
> required), except colors with --color=always doesn't work, it looks
> like it is because Emacs/Helm can't convert certain escape color code
> (for example, simple-io.c:^[[91m^[[1mmain^[(B^[[m (void))

Did you had such ansi sequences as output when specifying --color ?
I have not such output, it seems the --color option have no effect when
used from emacs.

--
Thierry

**Comment by xuchunyang** [comment]
> Did you had such ansi sequences as output when specifying --color ?

Nope

> I have not such output, it seems the --color option have no effect when
> used from emacs.

Same here. It has effect through pipe on the command line.

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

>     Did you had such ansi sequences as output when specifying --color ?
>    
> Nope
>
>     I have not such output, it seems the --color option have no effect when
>     used from emacs.
>    
> Same here.

Hmm, so it is maybe a problem with rg itself which doesn't work well for
--color in some terminals.

I will merge the PR anyway as it is usable like this.
Like in idutils (because this one have no --color option), 
multiple regexps are not highlighted (the first pattern). 

> It has effect through pipe on the command line.

I didn't try, but I tried to bind `process-connection-type` which had no
effect in helm.

Thanks.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
So now the types are available and we have now a workaround for color, anything else ?

**Comment by xuchunyang** [comment]
That workaround works for me. Nice job. I think now we can close the issue.

**Comment by thierryvolpiatto** [comment]
Thanks for your help on this, so I close now.

**Comment by jagrg** [comment]
rg works well in `helm-grep-ag-command`, but how do we use it in `helm-grep-default-command` and `helm-grep-default-recurse-command`?

**Comment by thierryvolpiatto** [comment]
Jonathan Gregory <notifications@github.com> writes:

> rg works well in helm-grep-ag-command, but how do we use it in
> helm-grep-default-command and helm-grep-default-recurse-command?

`helm-grep-ag-command` is a variable, not a command, it is used by M-x
helm-do-grep-ag and from HFF it is bound to `M-g a`.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by jagrg** [comment]
On 12 Jun 2020, Thierry Volpiatto <notifications@github.com> wrote:

> `helm-grep-ag-command` is a variable, not a command, it is used by M-x
> helm-do-grep-ag and from HFF it is bound to `M-g a`.

I know. What I'm asking is how do add rg to the
helm-grep-default-command and helm-grep-default-recurse-command
variables, which by default are set to grep. For example:

1. C-x C-f
2. .org$
3. M-a
4. C-s
5. - \[\ ]

or:

(helm-do-grep-1 org-agenda-files nil 'rg '("*.org") "- \\[\\ ]")

-- 
Jonathan

**Comment by thierryvolpiatto** [comment]
Jonathan Gregory <notifications@github.com> writes:

> On 12 Jun 2020, Thierry Volpiatto <notifications@github.com> wrote:
>
>> `helm-grep-ag-command` is a variable, not a command, it is used by M-x
>> helm-do-grep-ag and from HFF it is bound to `M-g a`.
>
> I know. What I'm asking is how do add rg to the
> helm-grep-default-command and helm-grep-default-recurse-command
> variables, which by default are set to grep. For example:
>
> 1. C-x C-f
> 2. .org$
> 3. M-a
> 4. C-s
> 5. - \[\ ]
>
> or:
>
> (helm-do-grep-1 org-agenda-files nil 'rg '("*.org") "- \\[\\ ]")

No, you can't, helm-grep-default-command and
helm-grep-default-recurse-command are for helm-grep which support grep
and ack-grep, for ag commands which are recursive by default please use
M-g a.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by jagrg** [comment]
On 12 Jun 2020, Thierry Volpiatto <notifications@github.com> wrote:

> No, you can't, helm-grep-default-command and
> helm-grep-default-recurse-command are for helm-grep which support grep
> and ack-grep, for ag commands which are recursive by default please use
> M-g a.

Are you saying there's some limitation to rg that makes GNU grep a
better choice? Can you be more specific. For example, we could grep
marked/selected files only using:

rg 'pattern' file1.el file2.el

or recursively (with C-u C-s):

rg 'pattern'

We can also grep files matching a given file extension:

rg -g '*.el' 'pattern'

WDYT?

-- 
Jonathan

**Comment by thierryvolpiatto** [comment]
Jonathan Gregory <notifications@github.com> writes:

> On 12 Jun 2020, Thierry Volpiatto <notifications@github.com> wrote:
>
>> No, you can't, helm-grep-default-command and
>> helm-grep-default-recurse-command are for helm-grep which support grep
>> and ack-grep, for ag commands which are recursive by default please use
>> M-g a.
>
> Are you saying there's some limitation to rg that makes GNU grep a
> better choice?

No, I am saying use grep or ack-grep for files and rg for recursive search.

> Can you be more specific. For example, we could grep marked/selected
> files only using:

No, this add no extra features, just extra work on my side for no
benefit, please use C-s and C-u C-s with ack or grep and M-g a with rg.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
