### ISSUE TITLE
helm-org-agenda-files-headings unstable on large file

### ISSUE THREAD

**Issue by avkoval** [emacs-helm/helm#1626]
## Expected behavior

I expect helm-org-agenda-files-headings  to show headings OR display an error. 

## Actual behavior from emacs-helm.sh if possible

Usually it works fine after emacs start. But suddenly after some time/calls it stops functioning.
Sometimes it restores working behavior (for example after saving settings to .emacs it almost always restores) but most of time this function is unusable.

## Steps to reproduce (recipe)

I expect it has something to do with the file size: the bigger your org-file[s], the more easily problem gets reproduced. For example: http://scr.ua2web.com/avk/someorg.org.gz

## Describe versions of helm, emacs, operating system etc.

Ubuntu 16.04 emacs 25.1.51 helm started from emacs-helm.sh v2.3.0

**Comment by thierryvolpiatto** [comment]
avkoval <notifications@github.com> writes:

> I expect it has something to do with the file size:

Of course, the buffer is huge (8M and 175817 lines), consider splitting your org files.

--
Thierry

**Comment by avkoval** [comment]
OK, on smaller file this error happens just less frequently. I specifically made the file so big so you can reliably reproduce the bug and fix it. I have much smaller files - a two of them each is around 500kb. But Helm still fails from time to time on them. When I try to call the function helm-org-get-candidates directly, it returns results more-less promptly, in less then 2 seconds usually. Yes, it may be not super fast, but it works. While helm does not - it works randomly. Same happens on large buffers (like trying helm-occur on package-list-packages screen) but since it suddenly works there after a few tries I can live with it. But I can not really understand why helm fails here and not fails for example parsing my firefox bookmarks file, which also takes around 2 seconds, but *always* succeeds - this makes me think that its not about timeout or data size, but its just some nasty bug. I tried to trace this, but can not figure it out myself yet.

**Comment by thierryvolpiatto** [comment]
avkoval <notifications@github.com> writes:

> OK, on smaller file this error happens just less frequently. I
> specifically made the file so big so you can reliably reproduce the
> bug and fix it. I have much smaller files - a two of them each is
> around 500kb. But Helm still fails from time to time on them. When I
> try to call the function helm-org-get-candidates directly, it returns
> results more-less promptly, in less then 2 seconds usually. Yes, it
> may be not super fast, but it works. While helm does not - it works
> randomly. Same happens on large buffers (like trying helm-occur on
> package-list-packages screen) but since it suddenly works there after
> a few tries I can live with it. But I can not really understand why
> helm fails here and not fails for example parsing my firefox bookmarks
> file, which also takes around 2 seconds, but always succeeds - this
> makes me think that its not about timeout or data size, but its just
> some nasty bug. I tried to trace this, but can not figure it out
> myself yet.

Well, this is not reproductible here, and I don't know exactly what you
are doing and on which buffers, with the one you gave me of course helm
is slow, but no more than anything else in emacs (scrolling,
font-locking etc...). Lets use files everybody know (like emacs files)
and try to reproduce from there using helm-occur or whatever.
But my guess is you have something else taking all your ressources, try
to look with top or whatever tool what's going on.
Also without more infos I am unable to tell you more about this.


--
Thierry

**Comment by thierryvolpiatto** [comment]
avkoval <notifications@github.com> writes:

> I have much smaller files - a two of them each is around 500kb.

On files of this size you should have no problems (my biggest org file
is 657k).
Can you reproduce with same files with
`(setq-default bidi-display-reordering nil)` ?

Also is it better on emacs 24.5 ?

Ensure also to have helm well installed (reinstall/recompile).

Also do you have a clip ring manager running ?

--
Thierry

**Comment by avkoval** [comment]
Thank you for hints. I've disabled Parcellite and now I can not reproduce this bug (tried for 15 minutes in various situations on large file as well, no problems found).

So, it looks like its duplicate for https://github.com/emacs-helm/helm/issues/1157

Thank you for prompt and valuable hints. Looks like there is no helm issue here ;-)
