### ISSUE TITLE
Feature Request: sort by date

### ISSUE THREAD

**Issue by xarath** [emacs-helm/helm#1627]
Sometimes, I want to access the last file that was modified and I don't know its name.  It would be very useful if there was an option to sort candidates by date.  A key to toggle this would be nice.  It would go like this:
1. type something at helm prompt to get a list of candidates
2. hit key to re-order by date
3. select desired candidate

Thank you.

**Comment by thierryvolpiatto** [comment]
xarath <notifications@github.com> writes:

> Sometimes, I want to access the last file that was modified 

Did you try from helm-find-files to access the history files with 
`C-c h` ?

Also always from helm-find-files, you can hit `C-c /` which run find and
after a pattern or not, add * followed by a find option (e.g -atime
1, -amin 60 etc...).

--
Thierry

**Comment by xarath** [comment]
Thanks for your reply.  However, C-c h doesn't work because the file I want to visit was modified by another process so it's not in history files.

C-c / could work with helm-find-files but won't work with org-attach-attach to choose a file to attach.

Thans again.

**Comment by thierryvolpiatto** [comment]
xarath <notifications@github.com> writes:

> C-c / could work with helm-find-files but won't work with
> org-attach-attach to choose a file to attach.

org-attach-attach is an emacs command helmized by helm-mode with a
generic function, such commands should not be modified.
They should do no more no less than the original ones apart the helm
completion.

--
Thierry

**Comment by xarath** [comment]
Ok.  I was previously using ido for org-attach-attach with ido-sort-mtime-mode to list the last modified file first.  I guess this is something I'll miss from ido.

Thanks for your help.

**Comment by thierryvolpiatto** [comment]
xarath <notifications@github.com> writes:

> Ok. I was previously using ido for org-attach-attach with
> ido-sort-mtime-mode to list the last modified file first. I guess this
> is something I'll miss from ido.

Add to your config:

(add-to-list 'helm-completing-read-handlers-alist '(org-attach-attach . ido))

--
Thierry

**Comment by xarath** [comment]
Thank you.
