### ISSUE TITLE
`helm-run-or-raise` does not respect relative path

### ISSUE THREAD

**Issue by xiongtx** [emacs-helm/helm#1629]
## Expected behavior

`(helm-run-or-raise "evince" "~/Downloads/foo.pdf")` should open `/home/<user>/Downloads/foo.pdf`, where `<user>` is the username.

## Actual behavior from emacs-helm.sh if possible

An Evince error is shown:

```
Unable to open document “file:///home/<user>/.emacs.d/elpa/helm-20160914.813/~/Downloads/PaymentSummary.pdf”.

Error opening file: No such file or directory
```

Apparently `default-directory` is being prefixed to the relative file path, but it's unclear where that's happening...

## Steps to reproduce (recipe)

See above

## Backtraces if some (M-x toggle-debug-on-error)

N/A

## Describe versions of helm, emacs, operating system etc.

- Helm: 2.1.0
- Emacs: 25.1.1
- OS: Fedora 24

**Comment by thierryvolpiatto** [comment]
Is there a bug in github today ? My messages sent by mail don't appear here.

**Comment by xiongtx** [comment]
Not sure. I only ever use the GitHub in the browser.

**Comment by thierryvolpiatto** [comment]
Ok, thanks.

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> Describe versions of helm, emacs, operating system etc.
>
>   * Helm: 2.1.0

BTW we are at 2.3.0 actually ;-).

Think you can close now.

Thanks.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> Expected behavior
>
> (helm-run-or-raise "evince" "~/Downloads/foo.pdf") should open
> /home/<user>/Downloads/foo.pdf, where <user> is the username.

Note that you should not use this which is used internally by
`helm-open-file-externally`.

Use instead from HFF `C-c x`.

Anyway I fixed it when evaled directly with an abbreviated path.

--
Thierry

**Comment by xiongtx** [comment]
> BTW we are at 2.3.0 actually ;-).

It's hard to keep up with the torrential rate of development ;)!
