### ISSUE TITLE
Tab Completion of Directory Paths

### ISSUE THREAD

**Issue by nordlow** [emacs-helm/helm#1630]
Is there a way to change back behaviour of TAB completion in `helm-find-files` to traditional behaviour that completes directory names when navigating down directory tree.

**Comment by xuchunyang** [comment]
C-j expands candidate, does C-j work for you? If it does, since there is nothing special about TAB as an key, you can bind it to any command, for example, `(define-key helm-find-files-map "\t" 'helm-execute-persistent-action)` to make TAB run C-j's command.

**Comment by nordlow** [comment]
Yep, it does. Now I know. Thanks.

**Comment by nordlow** [comment]
Thanks!
