### ISSUE TITLE
Reverse History I-search

### ISSUE THREAD

**Issue by nordlow** [emacs-helm/helm#1632]
I'm missing the Vanilla Emacs key-binding `C-r` in the minibuffer that does reverse history I-search. Is there a configuration for this?

**Comment by xiongtx** [comment]
You still have `previous-matching-history-element` available through `M-r` in Helm commands excluding `helm-find-files` (where it is bound to `helm-ff-rotate-right-persistent`). Granted, it's not as useful as `C-r` (I forget which command it's bound to...I think `isearch-reverse-minibuffer-exit`?).

If you hit `C-r` using the non-Helm version of `M-x` (`execute-extended-command`) with `helm-mode` on, you actually get nice Helm completion of minibuffer history (`helm-minibuffer-history`).

I don't know if making `helm-minibuffer-history` available for Helm commands would be too challenging or confusing from a technical/UX perspective. You'd have to bring up a different Helm window, then restore the previous one after the user selects a history item.

**Comment by thierryvolpiatto** [comment]
Definitely mail replies don't appear anymore in github, can somebody confirm this or is it just me ?

**Comment by xiongtx** [comment]
:confused:  I don't reply using e-mail, but it does seem that your usual mail replies aren't showing up.

**Comment by thierryvolpiatto** [comment]
They appear but about two days later (they appear now in #1629).
I have submitted an issue here:
https://github.com/isaacs/github/issues/802

**Comment by nordlow** [comment]
Ok, thanks!

Does this mean I can now bind `C-r` to `isearch-backward` in `helm-find-files-map`
 and automatically get the desired behaviour in `helm-find-files`.

What if I want this behaviour in all my helm-enhanced minibuffer interactions? Can I get this behaviour by modifying some common helm mode map?

**Comment by thierryvolpiatto** [comment]
Per Nordlöw <notifications@github.com> writes:

> I'm missing the key-binding C-r in the minibuffer for reverse history
> I-search. Is there a configuration for this?

I am not an expert of isearch, i rarely use it (only in helm help), but
it seems C-r is for reversing the search, isn't it?


--
Thierry

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> commands would be too challenging or confusing from a technical/UX
> perspective. You'd have to bring up a different Helm window, then
> restore the previous one after the user selects a history item.

Done, helm have a special slot called :allow-nest which makes this easy, helm
kill-ring among others uses it.

You can try it with:

(define-key helm-map (kbd "C-r") 'helm-minibuffer-history)

--
Thierry

**Comment by thierryvolpiatto** [comment]
Test if mail reply appear in github.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Per Nordlöw <notifications@github.com> writes:

> Does this mean I can now bind C-r to isearch-backward in
> helm-find-files-map

No, why isearch-backward ?
Now C-r is bound in helm-map, so all your helm commands will have it,
except helm-find-files based commands which use C-r for other purpose.
In helm-find-files, you don't really need this as you have M-p and also
C-c h, but if you really want to have helm-minibuffer-history you can of
course bind it in helm-find-files-map to something else than C-r, or
arrange to bind C-r to something else (C-r in helm-find-files is really
useful, it allow undoing your successive hit on C-l).

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Looks it is now fixed, feel free to reopen.

thanks.
