### ISSUE TITLE
Non-Intrusive Entering of Minibuffer in Helm Mode

### ISSUE THREAD

**Issue by nordlow** [emacs-helm/helm#1636]
Is there a way to make helm **not** restructure by current windows (in my case from multiple windows into a single window) when I enter the minibuffer?

**Comment by xuchunyang** [comment]
I used the following for some time, it might does what you want. However, it breaks some functions of helm such as `C-h m` (`helm-help`) and `helm-autoresize-mode`.

```elisp
(add-to-list 'display-buffer-alist
             '("\\`\\*helm.*\\*\\'"
               (display-buffer-in-side-window)
               (window-height . 0.4)))

(setq helm-display-function 'display-buffer)
```

**Comment by nivekuil** [comment]
I have these settings to make helm split the active window and appear in the bottom half:
```
(setq helm-split-window-in-side-p t)
(setq helm-split-window-default-side 'below)
```

**Comment by nordlow** [comment]
Perfect! Precisely what I was looking for!
