### ISSUE TITLE
helm-M-x displays not all keybindings attached to a command

### ISSUE THREAD

**Issue by triklsbg** [emacs-helm/helm#1637]
![helm_meta_x_20161105](https://cloud.githubusercontent.com/assets/3647083/20032258/a210bcce-a386-11e6-88f0-3feb01efdbe0.png)
The attached screenshot shows the help-buffer for other-window, a command bound to two bindings in this case. The lower window shows the helm-M-x buffer displaying only one binding (C-^) for other-window. 

emacs-version 25.1

**Comment by xiongtx** [comment]
This is the default behavior of [`substitute-command-keys`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Keys-in-Documentation.html), which `helm-M-x-transformer-1` uses to get commands' keybindings.

From the manual:

> If a command has multiple bindings, this function normally uses the first one it finds.

If you want to see all keybindings (and other documentation) for a command, just use persistent action (`C-j`) to bring up the `*Help*` window.
