### ISSUE TITLE
helm-grep speed optimization

### ISSUE THREAD

**Issue by pcompassion** [emacs-helm/helm#1640]
I've been using helm-git-grep (https://github.com/yasuyk/helm-git-grep) 

One thing I miss in helm-git-grep is `grep-find-ignored-directories`.  
So I'm trying `helm-grep`, but the speed is noticeably slower than `helm-git-grep`

I would like to see the best of both world if possible.

**Comment by thierryvolpiatto** [comment]
pcompassion <notifications@github.com> writes:

> I've been using helm-git-grep (https://github.com/yasuyk/helm-git-grep) 
>
> One thing I miss in helm-git-grep is `grep-find-ignored-directories`.  
> So I'm trying `helm-grep`, but the speed is noticeably slower than `helm-git-grep`

Since I have no benchmarks, I can't compare.

Anyway here `helm-grep-do-git-grep` is really fast, and it is the first
time somebody complain about performances for this.

> I would like to see the best of both world if possible. 

If people were contributing to helm instead of reinventing the wheel on
their side, you would have the best of both world...
And we would have less helm redundant packages in Melpa.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Note also that git is doing some caching of repositories it greps, so if
you run twice the same git-grep command on a repo, the second will be
much faster.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Also I see you had modified helm git grep to grep always the whole
directory in #1252, so if the repo you are in is large and one git-grep
is grepping the whole directory and the other only the subdirectory,
this could make a difference.

-- 
Thierry

**Comment by xiongtx** [comment]
> If people were contributing to helm instead of reinventing the wheel on
their side

I was actually under the impression that you wanted to keep Helm's scope limited. Which Helm projects would you like to see folded into Helm itself? Something like [`helm-describe-modes`](https://github.com/emacs-helm/helm-describe-modes)?

**Comment by pcompassion** [comment]
> Since I have no benchmarks, I can't compare.

True! 
I have no idea how to measure the speed. 
If you want me to measure how it compares when performing search on 'emac-helm' , 'emacs' git repository.  
I can provide that.

Thanks for answering the question.

When I move around several git projects, I think the initial caching is reset. Is my founding correct?

**Comment by thierryvolpiatto** [comment]
pcompassion <notifications@github.com> writes:

>> Since I have no benchmarks, I can't compare.
>
> True! 
> I have no idea how to measure the speed. 
> If you want me to measure how it compares when performing search on 'emac-helm' , 'emacs' git repository.  
> I can provide that.

1) open /path/to/emacs/lisp/files.el
2) from this buffer:
M-: (with-helm-time-after-update (helm-git-grep-1 "url-retrieve")) RET
=> for me 0.018...s
M-: (with-helm-time-after-update (helm-grep-git-1 default-directory t nil "url-retrieve"))
=> for me 0.0099...s

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> I was actually under the impression that you wanted to keep Helm's
> scope limited.

Yes, I prefer generally adding fully new features to emacs-helm.
I may move more stuff from helm to emacs-helm in the future.

> Which Helm projects would you like to see folded into Helm itself?

Nothing folded, I just think that there is no need to write a new package
for a missing feature of an already provided helm application.

> Something like
> [`helm-describe-modes`](https://github.com/emacs-helm/helm-describe-modes)?

This is something independent (even though a mode is a command/function
described in helm-apropos).

--
Thierry

**Comment by thierryvolpiatto** [comment]
@pcompassion Note also that I have added in helm-grep mode-line a time measurement.
It differ from non interactive call because of diverse things running in interactive calls (mode-line...).

**Comment by thierryvolpiatto** [comment]
I am closing this as I see no performances issues in helm for git-grep, all the contrary.
The external package helm-git-grep is in addition highlighting with elisp the matches which is slower than
using the native ansi color of git-grep, so I don't see how it would be faster than what we use.
We are using a sentinel than can slow down a bit the resulting buffer to pop up but it is insignificant.
So actually, no we can't say git-grep implementation coming from helm-grep.el is slow.
