### ISSUE TITLE
helm-M-x kill-emacs interaction with i3 window manager

### ISSUE THREAD

**Issue by plantarum** [emacs-helm/helm#1641]
I have come across a very unusual interaction between helm and the i3 window manager. Using `helm-M-x` to invoke `kill-emacs` causes the keyboard input to be ignored until the mouse is used to switch windows. It's probably a very local issue, but since I can reproduce it without fail, I'm reporting it in case anyone else encounters this. 

## Expected behavior

`helm-M-x` -> `kill-emacs`, emacs closes and focus returns to the window manager.

## Actual behavior from emacs-helm.sh if possible

1. Start emacs from a terminal (but a GUI version, not emacs -nw) via `emacs-helm.sh`
2. `helm-M-x` `kill-emacs`
3. Emacs closes, but keyboard is non-responsive
4. If another window is open, or another workspace is in use, after selecting the other window or workspace with the mouse the keyboard will work again.
5. If no other window or workspace is available to be selected by the mouse, the only way to regain the functioning of the keyboard is to switch to another virtual terminal (i.e., Ctrl-Alt-F1) and restart the window manager. 

## Steps to reproduce (recipe)

Sorry, not sure how 'actual behaviour' and 'steps to reproduce' are not the same thing?

## Backtraces if some (M-x toggle-debug-on-error)

NA - no actual error within Emacs, but rather a problem when returning focus to the OS

## Describe versions of helm, emacs, operating system etc.
Emacs 25.1.50.2
Helm 20161113.908
Debian Linux
i3 version 4.13

Things I've tested:
- no problem when using other window managers
- no problem when starting helm via emacs-helm.sh, but calling `kill-emacs` via regular `M-x` instead of `helm-M-x`

Now that I've narrowed down the problem to a reproducible recipe for my system, this is easy enough to avoid. However, if anyone has any ideas *why* this happens, it might help me with some other weird behaviours I'm experiencing with my window manager freezing up.

**Comment by xuchunyang** [comment]
I can't reproduce on Ubuntu with the following steps:

1. Login with i3 and its default config
2. Open terminal and cd to helm directory
3. `./emacs-helm.sh` (it opens a graphic Emacs and input focus goes to that window)
4. `helm-M-x kill-emacs` (it closes Emacs window and input focus goes to the terminal window)

---

- Ubuntu 16.04
- i3 4.11-1 from Ubuntu's official repo
- helm git repo and 20161109.1317
- Emacs 26.0.50.3

**Comment by xuchunyang** [comment]
Does (or can) i3 give any log/debug information about this?

**Comment by thierryvolpiatto** [comment]
Tyler Smith <notifications@github.com> writes:

> I have come across a very unusual interaction between helm and the i3
> window manager. Using `helm-M-x` to invoke `kill-emacs` causes the
> keyboard input to be ignored until the mouse is used to switch
> windows. It's probably a very local issue, but since I can reproduce
> it without fail, I'm reporting it in case anyone else encounters this.
>
> ## Expected behavior
>
> `helm-M-x` -> `kill-emacs`, emacs closes and focus returns to the
> window manager.
>
> ## Actual behavior from emacs-helm.sh if possible
>
> 1. Start emacs from a terminal (but a GUI version, not emacs -nw) via
> `emacs-helm.sh` 2. `helm-M-x` `kill-emacs` 3. Emacs closes, but
> keyboard is non-responsive 4. If another window is open, or another
> workspace is in use, after selecting the other window or workspace
> with the mouse the keyboard will work again.  5. If no other window or
> workspace is available to be selected by the mouse, the only way to
> regain the functioning of the keyboard is to switch to another virtual
> terminal (i.e., Ctrl-Alt-F1) and restart the window manager.
>
> ## Steps to reproduce (recipe)
>
> Sorry, not sure how 'actual behaviour' and 'steps to reproduce' are
> not the same thing?
>
> ## Backtraces if some (M-x toggle-debug-on-error)
>
> NA - no actual error within Emacs, but rather a problem when returning
> focus to the OS
>
> ## Describe versions of helm, emacs, operating system etc.  Emacs
> 25.1.50.2 Helm 20161113.908 Debian Linux i3 version 4.13
>
> Things I've tested: - no problem when using other window managers - no
> problem when starting helm via emacs-helm.sh, but calling `kill-emacs`
> via regular `M-x` instead of `helm-M-x`
>
> Now that I've narrowed down the problem to a reproducible recipe for
> my system, this is easy enough to avoid. However, if anyone has any
> ideas *why* this happens, it might help me with some other weird
> behaviours I'm experiencing with my window manager freezing up.

I have encountered the same problem by building emacs with Lucid, the
focus was lost when quitting emacs as soon as helm have been used once,
and without i3 or helm-M-x to quit emacs.
As soon as I builded emacs with Gtk the bug gone away.
It is an emacs bug, I reported it to emacs at the time.
https://debbugs.gnu.org/cgi/bugreport.cgi?bug=16076

I never been able to produce a useful backtrace with gdb.

--
Thierry

**Comment by plantarum** [comment]
I had been using lucid, but just rebuilt Emacs with gtk instead. The problem persists. Calling `kill-emacs` with helm-M-x and I lose focus of the keyboard. Calling it from regular `execute-extended-command` works as expected, no loss of focus.

Thanks for your suggestions!

**Comment by thierryvolpiatto** [comment]
Tyler Smith <notifications@github.com> writes:

> I had been using lucid, but just rebuilt Emacs with gtk instead. The
> problem persists. Calling kill-emacs with helm-M-x and I lose focus of
> the keyboard. Calling it from regular execute-extended-command works
> as expected, no loss of focus.

I would say that some elisp code that helm is using is causing emacs to
loose focus when exiting.
I think this is not an helm bug but an emacs bug, I am afraid I can do
nothing on the helm side to fix this.

BTW did you try to exit emacs with C-x C-c after using intensively helm ?

And when running emacs from gdb, do you have some backtrace ?

--
Thierry

**Comment by plantarum** [comment]
I don't have any problems with C-x C-c. I'll try running from gdb and see what I can find.

**Comment by errge** [comment]
I have a workaround:

    (add-to-list 'kill-emacs-hook 'iconify-frame t)

**Comment by errge** [comment]
I started working on this, see https://github.com/i3/i3/pull/2839

I have a workaround for the meantime.  Put this in your .emacs:

    (defun x-focus-frame (dummy))

**Comment by errge** [comment]
Sorry, but was not able to get the i3 changeset in, as the i3 guys started playing ICCCM and EWMH standard committee on me without even reading my comments or trying to understand the issue.  They closed the discussion with a final comment that contains total nonsense techwise and also forbid me from ever telling them so. :((

So the second best thing we can do is to put a small one-liner workaround in helm specific to i3.

I tried to put plenty of comments in the changeset, if it needs more explanation, don't hesitate to ask me.

**Comment by errge** [comment]
#1818 fixes this.
