### ISSUE TITLE
helm-etags-fuzzy-match does not male helm-etags-select fuzzy

### ISSUE THREAD

**Issue by cryptomaniac512** [emacs-helm/helm#1642]
In my Emacs configuration I set
```elisp
(setq helm-M-x-fuzzy-match t
      helm-buffers-fuzzy-matching t
      helm-apropos-fuzzy-match t
      helm-semantic-fuzzy-match t
      helm-imenu-fuzzy-match t
      helm-M-x-fuzzy-match t
      helm-locate-fuzzy-match t
      helm-mode-fuzzy-match t
      helm-completion-in-region-fuzzy-match t
      helm-etags-fuzzy-match t)
```
but when I try to search tag via `helm-etags-select` it has no "fuzzy" behavior.

```elisp
M-x describe-variable helm-etags-fuzzy-match RET:

helm-etags-fuzzy-match is a variable defined in ‘helm-tags.el’.
Its value is t
Original value was nil
```

**Comment by thierryvolpiatto** [comment]
CryptoManiac <notifications@github.com> writes:

> In my Emacs configuration I set
> ```elisp
> (setq helm-M-x-fuzzy-match t
>       helm-buffers-fuzzy-matching t
>       helm-apropos-fuzzy-match t
>       helm-semantic-fuzzy-match t
>       helm-imenu-fuzzy-match t
>       helm-M-x-fuzzy-match t
>       helm-locate-fuzzy-match t
>       helm-mode-fuzzy-match t
>       helm-completion-in-region-fuzzy-match t
>       helm-etags-fuzzy-match t)
> ```
> but when I try to search tag via `helm-etags-select` it has no "fuzzy" behavior.

Use M-x customize-variable or 
`(customize-set-variable 'helm-etags-fuzzy-match t)`

-- 
Thierry
