### ISSUE TITLE
Update helm-locate for es (cmdline of Everything) to fit with beta versions of Everything.

### ISSUE THREAD

**Issue by aligua** [emacs-helm/helm#1645]
## Expected behavior

Please refer to below two url for the just-added support from the es.exe(a beta release) that it increases run-counter of a specific file.   
https://www.voidtools.com/forum/viewtopic.php?f=2&t=5813
https://www.voidtools.com/forum/viewtopic.php?f=2&t=5762&p=16376#p16376 
     search for -inc-run-count in this page

So I assume the helm can consider add a second call to es (with es -inc-run-count target-file) after user has a target file selected in helm-for-file

Since this is a change in es beta release, so I am not sure if it is necessary to check for es version before call -inc-run-count, if this is a problem, then it is not necessary to be hurry to add this change in helm

**Comment by thierryvolpiatto** [comment]
Please describe exactly what this change will bring to helm comparing to current behavior, for now I don't understand.
Thanks.

**Comment by aligua** [comment]
hi thierryvolpiatto 
current behavior
after input keywords to find a file from helm-locate (es in windows), the everything "Run History.csv" does not updated with the run-count +1 of the last file.  This results the next time if I input the same keywords, the file will not show at top of the helm-locate session (sorting is according to position of file in "Run History.csv", but es.exe doesn't update it)

expect behavior
the 2nd time with the same keyword input, the target file should be shown in near top of the helm-locate candidates list. This behavior is same with "everthing.exe", as it accumulates the "run-counter" of every file selection and update it into "Run History.csv". And everytime when find a file in everything, the program can refer to this file for result sorting (if user enable the "sort by run count")

The "Run History.csv" file content is like bellow:
Filename,Run Count,Last Run Date
"C:\aligua\stable",122,131238136048720901
"C:\nouse\killme",112,131241899945758565
"C:\aligua\cuizi\work",85,131239218305370017
"C:\aligua\cuizi",35,131230722428423496
"C:\aliguabak\vm_share",34,131229872481532252

The lastest added option of -inc-run-counter of es.exe makes the expected behavior possible, as that optoin inc 1 of the counter in the "Run History.csv" (But does not do file search at all with that option).

So as the bellow example code shown, the expected change is issue a new es.exe command after the file is find by helm-locate in windows.

This expected behavior has some overlap with the helm-recentf-source. But still it can be consider as a enhancement for the helm-locate user experience.

@@ -740,9 +740,13 @@ directory, open this directory."
           (find-alternate-file remote-path))
       (find-file remote-path))))
 
+(defun aligua-helm-find-file (filename)
+  (shell-command (concat "C:\\aligua\\generaltool\\Everything\\es -inc-run-count " (convert-standard-filename filename))))
 (defun helm-find-many-files (_ignore)
   (let ((helm--reading-passwd-or-string t))
-    (mapc 'find-file (helm-marked-candidates))))
+    (mapc 'find-file (helm-marked-candidates))
+    (when (and (equal (cdar (helm-get-current-source)) "Locate") (eq 'windows-nt system-type))
+      (mapc 'aligua-helm-find-file (helm-marked-candidates)))))
 
 (defun helm-read-repeat-string (prompt &optional count)
   "Prompt as many time PROMPT is not empty.

**Comment by thierryvolpiatto** [comment]
Thanks for explanations.

aligua <notifications@github.com> writes:

> So as the bellow example code shown, the expected change is issue a
> new es.exe command after the file is find by helm-locate in windows.

I have added a hook that run in helm-find-many-files, so that you don't
have to modify source code.
Let me know if it is enough for your needs.

--
Thierry

**Comment by aligua** [comment]
it looks good patch to me, thanks for help:)

**Comment by thierryvolpiatto** [comment]
aligua <notifications@github.com> writes:

> it looks good patch to me, thanks for help:)

Perhaps you could provide documented code as PR that can be added to the
hook by users if needed ?

Thanks.

-- 
Thierry

**Comment by aligua** [comment]
Could you explain what PR is the abbrev?
Sounds likes I write a snippet of example code + description for how use this hook interface? yes sure I can do it.

**Comment by thierryvolpiatto** [comment]
aligua <notifications@github.com> writes:

> Could you explain what PR is the abbrev?

Sorry, it means Pull Request.

https://github.com/emacs-helm/helm/pulls

https://help.github.com/articles/about-pull-requests/

https://help.github.com/articles/creating-a-pull-request/

> Sounds likes I write a snippet of example code + description for how
> use this hook interface? yes sure I can do it.

I thought about writing the function that will go into the hook with
full description on what it is and how to use it in docstring.
Also explain which "Everything" version is needed and where to get it.

Thanks.
 
--
Thierry

**Comment by aligua** [comment]
yes, added into my org todo list, will do in this weekend

**Comment by aligua** [comment]
Hi thierryvolpiatto
Below is a description of helm+es configuration, is it too verbose?
I didn't make PR as I don't know where to put this description in. So you decide please :)


;; a config of helm to work with on windows version of locate --- "everything", can be as follow:
(when (eq 'windows-nt system-type)
  ;; the "es" is cmdline interface of "everything", which can officially be downloaded from http://voidtools.com/. However for today as of 2016/12/4, latest beta version (>es 1.1.0.4a) in https://www.voidtools.com/forum/viewtopic.php?f=2&t=5762&p=16376#p16376 is recommented for its run count increment ability, see the bellow instance of helm-find-many-files-after-hook.
  ;; -sort run-count: sort the result from top to down as the frequency of they are selected in history.
  ;; -p, -match-path: Match full path and file name
  ;; -n 50 limit the es to output 50 results
  (setq es-program "C:\\zjl\\generaltool\\Everything\\es")
  (custom-set-variables `(helm-locate-command ,(concat es-program " %s -sort run-count -p -n 50 %s")))

  (defun helm-es-hook ()
    (when (and (equal (cdar (helm-get-current-source)) "Locate") (eq 'windows-nt system-type))
      (mapc (lambda (file) 
	      (shell-command (concat es-program " -inc-run-count " (convert-standard-filename file))))
	    (helm-marked-candidates))))

  ;; helm hook to increase file's run count while it is selected, which then next sort (-sort run-count) rank of this file will be higher. details in https://github.com/emacs-helm/helm/issues/1645  
  (add-hook 'helm-find-many-files-after-hook 'helm-es-hook))

**Comment by thierryvolpiatto** [comment]
aligua <notifications@github.com> writes:

> Hi thierryvolpiatto
> Below is a description of helm+es configuration, is it too verbose?
> I didn't make PR as I don't know where to put this description in. So you decide please :)

We need only the helm-es-hook function (rename it to something like
helm-locate--es-hook), up to the user to add this function to
`helm-find-many-files-after-hook` if needed.

This function should not assume that all Windows users use "es", i.e (eq
'windows-nt system-type).

It should also check if current version of "es" support this feature and
fall back to noop if not (At least check if helm-locate-command refer to
this new option).
  
Thanks.

--
Thierry

**Comment by thierryvolpiatto** [comment]
I have cleaned up the description and code you sent, feel free to correct it if needed and add it to [wiki](https://github.com/emacs-helm/helm/wiki/Locate), no need to make a PR, this have no place in helm actually, thanks.

```elisp
;; A config of helm-locate to work with last beta of Everything,
;; on Windows using last sort capabilities of "es"
;; for recently used files.

;; the "es" is cmdline interface of "everything",
;; which can officially be downloaded from http://voidtools.com/.

;; However for today as of 2016/12/04, latest beta version (>es 1.1.0.4a)
;; in https://www.voidtools.com/forum/viewtopic.php?f=2&t=5762&p=16376#p16376
;; is recommented for its run count increment ability.

;; Here the relevant arguments available with last "es" beta release:

;; -sort run-count: sort the result from top to bottom
;; as the frequency of they are selected in history.

;; -p, -match-path: Match full path and file name

;; -n 50 limit the es to output 50 results

(setq helm-locate-command "es %s -sort run-count -p -n 50 %s")
(defun helm-es-hook ()
  (when (and (equal (assoc-default 'name (helm-get-current-source)) "Locate")
             (string-match "\\`es" helm-locate-command))
    (mapc (lambda (file)
            (call-process "es" nil nil nil
                          "-inc-run-count" (convert-standard-filename file))))
          (helm-marked-candidates))))

;; Helm hook to increase file's run count while it is selected,
;; which then next sort (-sort run-count) rank of this file will be higher.
;; details in #1645
(add-hook 'helm-find-many-files-after-hook 'helm-es-hook)
```

**Comment by thierryvolpiatto** [comment]
Now done, see https://github.com/emacs-helm/helm/wiki/Locate and feel free to correct.

Thanks.

**Comment by aligua** [comment]
I verified the code posted on wiki, found "(helm-marked-candidates)" is ouside of the (mapc ...) , corrected it already. 
Other part of words and code are good on my side :)

**Comment by thierryvolpiatto** [comment]
aligua <notifications@github.com> writes:

> I verified the code posted on wiki, found "(helm-marked-candidates)"
> is ouside of the (mapc ...) , corrected it already.  Other part of
> words and code are good on my side :)

Great, thanks.

--
Thierry
