### ISSUE TITLE
helm-echo-input-in-header-line and % in input

### ISSUE THREAD

**Issue by michael-heerdegen** [emacs-helm/helm#1648]
## Actual behavior from emacs-helm.sh if possible

With ```helm-echo-input-in-header-line -> t```, when the input string contains percent characters, the input echoed in the header-line is incorrect.  Obviously, we must avoid that the input string is interpreted as a mode-line style format string - it has to be used literally.

## Steps to reproduce (recipe)

(setq helm-echo-input-in-header-line t)

Give an input to helm including "%d" for example.

## Describe versions of helm, emacs, operating system etc.

Current Melpa version.

Thanks,

Michael.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> With ```helm-echo-input-in-header-line -> t```, when the input string
> contains percent characters, the input echoed in the header-line is
> incorrect.

Should be fixed now, let me know though, I am generally not using this.

Thanks.

--
Thierry

**Comment by michael-heerdegen** [comment]
Seems to be fine, thanks.  Should I find problems, I'll report back.

**Comment by thierryvolpiatto** [comment]
This change was of course breaking cursor position when moving inside string.

**Comment by michael-heerdegen** [comment]
I'm sorry, it's not yet entirely correct.  When you move the cursor before an "%" occurrence, the cursor is shifted by 1 position in the header-line.

AFAIU you need
```
(cl-loop for c across cont when (eql c ?%) do (cl-incf pos))
```
to loop only up to ```(point)``` instead of the end of the minibuffer.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> I'm sorry, it's not yet entirely correct. When you move the cursor before an "%" occurrence, the cursor is shifted by 1 position in the header-line.
>
> AFAIU you need
>
> (cl-loop for c across cont when (eql c ?%) do (cl-incf pos))
>
> to loop only up to (point) instead of the end of the minibuffer.

Yes, but not enough when cursor is on a "%", should be fixed (I
hope!) now.

Thanks.

-- 
Thierry

**Comment by michael-heerdegen** [comment]
Ok, I think it's fine now.

BTW i think instead of ```(looking-at "%")``` you can use ```(= (char-after) ?%)``` which is equivalent but more effective.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Ok, I think it's fine now.
>
> BTW i think instead of (looking-at "%") you can use (= (char-after)
> ?%) which is equivalent but more effective.

Feel free to make the change.

--
Thierry

**Comment by michael-heerdegen** [comment]
FWIW I had to use "eq" instead of "=" since "char-after" can also return nil (namely at the end of a buffer)).

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> FWIW I had to use "eq" instead of "=" since "char-after" can also
> return nil (namely at the end of a buffer)).

I generally use `eql` for chars and such.


--
Thierry

**Comment by thierryvolpiatto** [comment]
Thierry Volpiatto <thierry.volpiatto@gmail.com> writes:

> I generally use `eql` for chars and such.

e.g

    (eql (current-buffer) (get-buffer "*scratch*"))
    (eql nil 1)
    (= (point) (point-max))
    (= 1.0 1)
    (eq 'foo 'bar)

-- 
Thierry

**Comment by michael-heerdegen** [comment]
Why for chars and buffers?  Isn't it equivalent to `eq' in those cases?

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Why for chars and buffers? Isn't it equivalent to `eq' in those cases?

Yes, but I think it is a better practice to use eql in such cases even
if eq is working too (eq is also working for integers, but it is better
using =) but well this is not very important...

-- 
Thierry

**Comment by xiongtx** [comment]
> The predicate `eql` is the same as `eq`, except that if the arguments are characters or numbers of the same type then their values are compared. Thus `eql` tells whether two objects are *conceptually* the same, whereas `eq` tells whether two objects are *implementationally* identical. It is for this reason that `eql`, not eq, is the default comparison predicate for the sequence functions defined in chapter 14.

From [Common Lisp the Language, 2nd Edition](https://www.cs.cmu.edu/Groups/AI/html/cltl/clm/node74.html). Applies to Emacs Lisp too.

I think the key is that we want *conceptual* equality, not implementation (object) equality.

**Comment by michael-heerdegen** [comment]
> From Common Lisp the Language, 2nd [Edition.]

Thanks.  That's what I expected.

> Applies to Emacs Lisp too.

That's a matter of taste.

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> I think the key is that we want conceptual equality, not implementation (object) equality.

In this case yes, FWIW cl-case for example is using eql to compare chars
among other things.
But I guess everybody is doing as it feel, you can find in emacs source
code char comparison made with eq, eql and =.
For myself I try to use eq for symbols comparison, = for integers, eql
for lisp objects such as markers, windows, buffers, chars etc...
and equal when there is not predictable ways to know of what type the
objects we compare will be.

-- 
Thierry

**Comment by michael-heerdegen** [comment]
I've just changed it in my commit.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> I've just changed it in my commit.

Ok, thanks.

-- 
Thierry
