### ISSUE TITLE
helm-echo-input-in-header-line: broken shadow cursor

### ISSUE THREAD

**Issue by michael-heerdegen** [emacs-helm/helm#1649]
## Expected behavior

The shadow cursor in the header-line echoing the given input reflects the cursor's position in the minibuffer.

## Actual behavior from emacs-helm.sh if possible

The emulated cursor doesn't move.

## Steps to reproduce (recipe)

(setq helm-echo-input-in-header-line t)

Invoke some helm command and move the cursor backwards in the minibuffer (e.g. with backward-char).
## Describe versions of helm, emacs, operating system etc.

Current Melpa version of Helm.

Thanks in advance,

Michael.

**Comment by michael-heerdegen** [comment]
Oops, I had had a quick look at your patch then, but didn't see the mistake either.  Thanks for the fix.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Oops, I had had a quick look at your patch then, but didn't see the
> mistake either. Thanks for the fix.

I have commited a fix for both #1648 and #1649, seems to work fine, feel
free to close #1648 if it works for you too.

Thanks.

--
Thierry
