### ISSUE TITLE
Enhancement: helm-minibuffer-history: add non-match to history variable

### ISSUE THREAD

**Issue by theldoria** [emacs-helm/helm#1650]
## Expected behavior
Using `helm-minibuffer-history` without any matching candidate should provide the option (or default action) to add the minibufer content as candidate. This could be done similar to `helm-find-files` where I can enter a new filename.

See also my [stackexchange question](http://emacs.stackexchange.com/questions/29144/is-there-a-helm-read-from-minibuffer-functionalityl).

## Actual behavior from emacs-helm.sh if possible
The entered string is deleted if no matching content is found.

## Steps to reproduce (recipe)
Run `C-r` and enter string not containedin the current history variable.

## Backtraces if some (M-x toggle-debug-on-error)
N/A

## Describe versions of helm, emacs, operating system etc.
helm-core-20160913.219

**Comment by thierryvolpiatto** [comment]
theldoria <notifications@github.com> writes:

> Expected behavior
>
> Using ``helm-minibuffer-historywithout any matching candidate should
> provide the option (or default action) to add the minibufer content as
> candidate. This could be done similar tohelm-find-files` where I can
> enter a new filename.

This would be the same as writing directly in minibuffer without calling
helm-minibuffer-history, so I don't see how this would help.

--
Thierry

**Comment by theldoria** [comment]
I would help that I would not have to retype everything, if there's no match.

**Comment by thierryvolpiatto** [comment]
theldoria <notifications@github.com> writes:

> I would help that I would not have to retype everything, if there's no match.

Hmm, personally if I run history and nothing match, I write something
else until it match, but well the current behavior was no good anyway,
now the default is not allowing exiting minibuffer when nothing match,
you can customize this with `helm-minibuffer-history-must-match`,
possible value are: nil, t and confirm.

-- 
Thierry

**Comment by yitang** [comment]
Hi, is this feature supported in helm? I tried setting `helm-minibuffer-history-must-match` to nil and :history test-history. when typing a new value that doesn't exist in test-history, helm simply returns nil and doesn't update test-history. 

also ping @xuchunyang

**Comment by thierryvolpiatto** [comment]
Yi Tang <notifications@github.com> writes:

> Hi, is this feature supported in helm? I tried setting
> helm-minibuffer-history-must-match to nil

What do you expect exactly? Start with e.g. `M-:', call
`helm-minibuffer-history` write something (non match is prefixed with ?)
maybe move cursor on the non matching candidate and hit RET, this non
matching candidate is inserted in minibuffer when
`helm-minibuffer-history-must-match` is nil, if it is 'confirm you have
to type RET twice i.e. you have to confirm.
What's wrong with this? 

> and :history test-history.

Why?! and Where?

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by yitang** [comment]
Hi, please below for the code.  


(setq helm-minibuffer-history-must-match nil)
(setq test-list '(a b c d))
(helm :sources (helm-build-in-buffer-source "a"
		 :data test-list
		 )
      :history 'test-list
      )

I tried to type z and was expecting the helm function to return z but it returns nil instead. is it supposed to be return z? sry i'm new to helm... 

on the other hand, the test-list variable got updated so it has an entry z in there.

**Comment by thierryvolpiatto** [comment]
Yi Tang <notifications@github.com> writes:

> Hi, please below for the code.
>
> (setq helm-minibuffer-history-must-match nil)
> (setq test-list '(a b c d))
> (helm :sources (helm-build-in-buffer-source "a"
>                  :data test-list)
>       :history 'test-list)

> I tried to type z and was expecting the helm function to return z but
> it returns nil instead. is it supposed to be return z? sry i'm new to
> helm...

`helm-minibuffer-history-must-match` is affecting only the helm
implementation of minibuffer-history bound by default to C-r in
e.g. `M-:`, so the code above is not affected by this variable.

If you want a must-match mechanism, use `helm-comp-read` instead:

    (helm-comp-read "test: " '(a b c d e) :must-match nil)
    (helm-comp-read "test: " '(a b c d e) :must-match 'confirm)

Or if you really want to use helm directly try this:

    (let ((minibuffer-completion-confirm t))
      (helm :sources (helm-build-in-buffer-source "test"
                       :data '(a b c d e)
                       :must-match t)
            :buffer "*helm test*"))

    (let ((minibuffer-completion-confirm 'confirm))
      (helm :sources (helm-build-in-buffer-source "test"
                       :data '(a b c d e)
                       :must-match t)
            :buffer "*helm test*"))

You can use either `helm-build-in-buffer-source` or
`helm-build-sync-source`, see documentation of `helm-source`,
`helm-source-sync` and `helm-source-in-buffer`.

NOTE: When reading Classes documentation in Emacs always use
helm-apropos which provide an action (helm-describe-class) that format
help properly, otherwise in native Emacs the help for classes is
unreadable.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Note that with helm directly, not helm-comp-read, we must let-bound `minibuffer-completion-confirm` to the desired value, I may modify this behavior to allow using directly the value of `:must-match` slot without having to let-bound `minibuffer-completion-confirm`.

**Comment by yitang** [comment]
just upgraded to 20200517.509 version and it works great! thank you very much. now I'm able to select and update candidates at the same time. it would make my ledger cli posting a lot enjoyable. 

I wasn't aware there are help pages for classes. helm-apropos makes it a lot easier to read helm documentation as there are so many options. 

I noticed there's a function called helm-build-in-file-source, i wonder if there's a way to update candidates in the file instead of in the history variable? 

Thanks again.

**Comment by xuchunyang** [comment]
> I tried to type z and was expecting the helm function to return z but it returns nil instead. is it supposed to be return z? sry i'm new to helm...

Maybe try helm-build-dummy-source?

```el
(helm :sources (list (helm-build-in-buffer-source "a"
                       :data test-list)
                     (helm-build-dummy-source "dummy"))
      :history 'test-list)
```

However, `helm` is usually used a standalone command, and you achieve everything within it, the return value is rarely used. Try stick with `completing-read` if that's possible.
