### ISSUE TITLE
Can helm buffer source sort by display time?

### ISSUE THREAD

**Issue by aligua** [emacs-helm/helm#1651]
## Expected behavior
in Helm buffer source, the more recent buffer displayed, the more buffer is on top of source list.

## Actual behavior from emacs-helm.sh if possible
is not sort as buffer usage history

The suggestion is sorting the buffer list as follow
<pre><code>
(setq helm-result 
      (sort helm-candidates-before-sort (lambda (left right)
					  (> (with-current-buffer (cdr left)
					       (float-time buffer-display-time))
					     (with-current-buffer (cdr right)
					       (float-time buffer-display-time))))))

</code></pre>

**Comment by thierryvolpiatto** [comment]
aligua <notifications@github.com> writes:

> Expected behavior
>
> in Helm buffer source, the more recent buffer displayed, the more buffer is on top of source list.

See issue #1301.

-- 
Thierry
