### ISSUE TITLE
Feature Request: Commonly accessed directories

### ISSUE THREAD

**Issue by sachdevaprash** [emacs-helm/helm#1652]
## Expected behavior
Show commonly accessed directories for quick access. Most useful for saving files from message-mode.

## Actual behavior from emacs-helm.sh if possible
No such "favorite" or "bookmarked" folders.

## Steps to reproduce (recipe)
mu4e-view-save-attachement-single

## Describe versions of helm, emacs, operating system etc.
Helm: 20161209 from MELPA
Emacs: 26.0.50.2
Operating System: Ubuntu 16.04

**Comment by thierryvolpiatto** [comment]
Prashant Sachdeva <notifications@github.com> writes:

> Expected behavior
>
> Show commonly accessed directories for quick access. Most useful for saving files from message-mode.
>
> Actual behavior from emacs-helm.sh if possible
>
> No such "favorite" or "bookmarked" folders.
>
> Steps to reproduce (recipe)
>
> mu4e-view-save-attachement-single
                       ^
                       mu4e-view-save-attachment-single

Helm is using a generic function to helmize `read-file-name` when
`mu4e-view-save-attachment-single` uses it.

This generic function cannot be changed/improved for a particular case
like all other generic functions used by helm-mode.

-- 
Thierry

**Comment by sachdevaprash** [comment]
I see. So the appropriate location to address this would be to provide more helm sources from mu4e then? Along the lines of helm-mini, to include some bookmarked or commonly used folders. Does that sound right?

**Comment by thierryvolpiatto** [comment]
Prashant Sachdeva <notifications@github.com> writes:

> I see. So the appropriate location to address this would be to provide
> more helm sources from mu4e then? Along the lines of helm-mini, to
> include some bookmarked or commonly used folders. Does that sound
> right?

No, we already have this, you have to write another function from mu4e (or
advice the current one) to do what you expect.
You can also write a specialized function and add it to
helm-completing-read-handlers-alist.

--
Thierry

**Comment by thierryvolpiatto** [comment]
TODO Write a specialized fn to add to `helm-completing-read-handler-alist`.

**Comment by sachdevaprash** [comment]
Thanks! I'll consider that for mu4e. I suppose this issue can be closed now!

**Comment by thierryvolpiatto** [comment]
Prashant Sachdeva <notifications@github.com> writes:

> Thanks! I'll consider that for mu4e. I suppose this issue can be closed now!

Something like this should work:

    (defun helm-read-file-name-handler-1 (prompt dir default-filename
                                          mustmatch initial predicate
                                          name buffer)
      (helm-read-file-name
       prompt
       :name name
       :history helm-ff-history
       :buffer buffer
       :default default-filename
       :initial-input (expand-file-name initial dir)
       :alistp nil
       :must-match mustmatch
       :test predicate))

    (add-to-list 'helm-completing-read-handlers-alist '(mu4e-view-save-attachment-single . helm-read-file-name-handler-1))

-- 
Thierry

**Comment by sachdevaprash** [comment]
Works like a charm! Thanks so much for your help. :+1: :smile:
