### ISSUE TITLE
I feel `helm-esh-complete` command should be improved.

### ISSUE THREAD

**Issue by kkatsuyuki** [emacs-helm/helm#1654]
## Current behavior

Recently I began to use `eshell` and as one of the completion functions
I used `helm-esh-complete`. But I think the command is not useful especially when 
the completed path is long. The command complete only the directories at current level, 
so I have to execute `helm-esh-complete` many times if I execute the completion in 
every directory level.

## Ideal

I think the ideal is the completion that can complete the path on current and deeper level 
by executing the command only at once. I want the directory to be completed 
at every level the way `helm-find-files` does.

Would you provide me some ideas?

**Comment by thierryvolpiatto** [comment]
KKatsuyuki <notifications@github.com> writes:

> Current behavior
>
> Recently I began to use eshell and as one of the completion functions
> I used helm-esh-complete. But I think the command is not useful especially when
> the completed path is long. The command complete only the directories at current level,
> so I have to execute helm-esh-complete many times if I execute the completion in
> every directory level.

This is the behavior of completion in all shell buffers.

> Ideal
>
> I think the ideal is the completion that can complete the path on current and deeper level
> by executing the command only at once. I want the directory to be completed
> at every level the way helm-find-files does.
>
> Would you provide me some ideas?

Why not using helm-find-files and then `C-c i` ?

-- 
Thierry

**Comment by kkatsuyuki** [comment]
Sorry, I don't know the useful command `C-c i` that insert the path found in `helm-find-files`. This command seemed to reach my ideal.
