### ISSUE TITLE
Allow globally sorting the candidates in an async source

### ISSUE THREAD

**Issue by PythonNut** [emacs-helm/helm#1657]
A followup from https://github.com/PythonNut/helm-flx/issues/17.

## Problem

Currently it's impossible to use a `:(filtered-)?candidate-transformer` to sort the candidates in an async source, since the transformer is applied to batches of candidates as they arrive, but never all candidates at once. 

## Expected behavior

Ideally, this sorting would be possible, since it allows for significant enhancements to the usability of some helm sources. For example, `helm-locate` with `(setq helm-locate-fuzzy-match t)` is generally not very useful because `locate` returns a vast number of poor quality matches. However, if we are allowed to sort the candidates with `flx` we can usually produce very good matches even with only a few characters.

**Comment by thierryvolpiatto** [comment]
PythonNut <notifications@github.com> writes:

> A followup from PythonNut/helm-flx#17.
>
> Problem
>
> Currently it's impossible to use a :(filtered-)?candidate-transformer
> to sort the candidates in an async source, since the transformer is
> applied to batches of candidates as they arrive, but never all
> candidates at once.

True.

> Expected behavior
>
> Ideally, this sorting would be possible, since it allows for
> significant enhancements to the usability of some helm sources. For
> example, helm-locate with (setq helm-locate-fuzzy-match t) is
> generally not very useful because locate returns a vast number of poor
> quality matches.

Agree, I don't use fuzzy for locate personally, I added it on request.

> However, if we are allowed to sort the candidates with flx we can
> usually produce very good matches even with only a few characters.

I doubt you would be efficient though, you would have to redisplay all
candidates sorted.
I have a branch allowing this actually, but it is slow, the redisplay is
done in sentinel functions.

--
Thierry

**Comment by thierryvolpiatto** [comment]
If you use the redisplay branch, you will find `helm-locate-fuzzy-sort-fn` where you could bind your own sort fn.
Doing this, the sort will be done on the whole list of candidate.

**Comment by PythonNut** [comment]
@thierryvolpiatto it works great, thanks a bunch!

Now, I did run into the following problem:

1. The redisplay may never happen if the number of candidates locate returns is above the `:candidate-number-limit`.
2. Even normally, `locate` may take a long time to terminate, which delays the redisplay.

Right now, a customization like
```emacs
(setq helm-locate-fuzzy-match t
        helm-source-locate
        (helm-make-source "Locate" 'helm-locate-source
          :pattern-transformer 'helm-locate-pattern-transformer
          :candidate-number-limit 1000)
        helm-locate-command "locate %s -e -l 1000 --regex %s")
```
Helps alleviate these two issues, but it's just a fragile hack. 

But when it works, it's fantastic! If you like, you can try this out. I think you'll like it.

```emacs
(require 'helm-flx)
(defun helm-flx-locate-fuzzy-matching-sort (candidates)
  (helm-flx-sort candidates
                 helm-pattern
                 (lambda (cand)
                   (if (consp cand)
                       (car cand)
                     cand))))

(setq helm-locate-fuzzy-sort-fn #'helm-flx-locate-fuzzy-matching-sort)
```

**Comment by thierryvolpiatto** [comment]
PythonNut <notifications@github.com> writes:

> @thierryvolpiatto it works great, thanks a bunch!
>
> Now, I did run into the following problem:
>
>  1. The redisplay may never happen if the number of candidates locate
>  returns is above the :candidate-number-limit.

Good catch, I added a new hook that should fix this issue.

>  2. Even normally, locate may take a long time to terminate, which
>  delays the redisplay.

Hmm, not sure to understand what you mean here, as soon as the limit is
reached, locate process is killed and redisplay happen.

>
> Right now, a customization like
>
> (setq helm-locate-fuzzy-match t
>         helm-source-locate
>         (helm-make-source "Locate" 'helm-locate-source
>           :pattern-transformer 'helm-locate-pattern-transformer
>           :candidate-number-limit 1000)
>         helm-locate-command "locate %s -e -l 1000 --regex %s")

You should not need this now.

>
> Helps alleviate these two issues, but it's just a fragile hack.
>
> But when it works, it's fantastic! If you like, you can try this out. I think you'll like it.

Great, I don't use flx, but I can see the result with helm fuzzy default
settings.

One more issue to fix, helm-redisplay-buffer should not be called when
not using fuzzy (i.e pattern contain one or more space), 
so the test `(when helm-locate-fuzzy-match [...])` is not enough.
Will try to fix this soon.

Thanks.

-- 
Thierry

**Comment by PythonNut** [comment]
@thierryvolpiatto oddly enough, it seems like `helm-locate-fuzzy-sort-fn` is never called in the latest versions. I tried in `emacs -Q` with the latest `helm` from MELPA and a basic function in `helm-locate-fuzzy-match-sort-fn` with `debug-on-entry` set. I had `(setq helm-locate-fuzzy-match t)` and the debugger was never triggered.

**Comment by thierryvolpiatto** [comment]
PythonNut <notifications@github.com> writes:

> @thierryvolpiatto oddly enough, it seems like
> helm-locate-fuzzy-sort-fn is never called in the latest versions. I
> tried in emacs -Q with the latest helm from MELPA and a basic function
> in helm-locate-fuzzy-match-sort-fn with debug-on-entry set. I had
> (setq helm-locate-fuzzy-match t) and the debugger was never triggered.

Hmm, can't reproduce.
Can you try to reproduce with just emacs-helm.sh using default settings
(just turn on fuzzy for locate).

Thanks.

> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.*


--
Thierry

**Comment by PythonNut** [comment]
Huh, I tried it again, then updated MELPA and everything worked. :/ Did you change something recently?

**Comment by thierryvolpiatto** [comment]
PythonNut <notifications@github.com> writes:

> Huh, I tried it again, then updated MELPA and everything worked. :/
> Did you change something recently?

Yes I did many changes around this, perhaps melpa have synchronized on
one of my intermediate commits ?

Among other things I had to rework helm-redisplay-buffer that was not
working properly in multi sources (e.g helm-for-files).

--
Thierry

**Comment by PythonNut** [comment]
@thierryvolpiatto yes, I noticed that as well. It's a welcome fix.

As far as I can tell, everything is working perfectly.

**Comment by thierryvolpiatto** [comment]
PythonNut <notifications@github.com> writes:

> @thierryvolpiatto yes, I noticed that as well. It's a welcome fix.
>
> As far as I can tell, everything is working perfectly.

Great, thanks for testing.

-- 
Thierry
