### ISSUE TITLE
No match highlighting on selected line in `*helm ag*` buffer opened by `helm-do-grep-ag`

### ISSUE THREAD

**Issue by jacg** [emacs-helm/helm#1660]
## Expected behavior

When running `helm-do-grep-ag`, the match should be highlighted with the `helm-grep-match` (or perhaps `helm-match` or some other) face on the selected line in the `*helm ag*` buffer, as can be seen in this output of `helm-ag` where `defun` is highlighted (in red, in this case) on the selected line (350) as well as other lines.

![helm-matching](https://cloud.githubusercontent.com/assets/2570854/21908894/fdde2824-d915-11e6-96e0-89ad7f82df7a.png)

## Actual behavior from emacs-helm.sh if possible

The match (`defun` once again) is *not* highlighted on the selected line (350 in the image below), while it is highlighted on other lines.

![helm-not-matiching](https://cloud.githubusercontent.com/assets/2570854/21908793/9617b5ac-d915-11e6-8730-0a21979c7535.png)

## Steps to reproduce (recipe)

- `./emacs-helm.sh`
- `M-x helm-do-grep-ag`
- `defun`
- `C-n C-n` ...

## Describe versions of helm, emacs, operating system etc.

- Helm cloned from github some minutes ago
- GNU Emacs 24.4.1 (x86_64-pc-linux-gnu, GTK+ Version 3.14.5) of 2015-03-07 on trouble, modified by Debian
- Debian jessie

**Comment by thierryvolpiatto** [comment]
jacg <notifications@github.com> writes:

> The match (defun once again) is not highlighted on the selected line
> (350 in the image below), while it is highlighted on other lines.

It is highlighted, but the selection overlay is hiding the highlighted
match.  This is what is expected, the selection overlay have higher priority.

So there is nothing wrong here.

--
Thierry

**Comment by jacg** [comment]
> It is highlighted, but the selection overlay is hiding the highlighted match. This is what is expected, the selection overlay have higher priority. 

In that case, why does the selection overlay not hide the highlighted match in the case of `helm-ag`? There the match highlighting is visible even on the selected line.

> So there is nothing wrong here.

Hmm, maybe there's nothing wrong from the "here's a technical explanation of what is happening" perspective, but it certainly seems wrong from the UI perspective.

And the fact that, from the UI perspective, the almost identical thing works correctly in `helm-ag`, suggests that it doesn't *have* to be like this.

**Comment by thierryvolpiatto** [comment]
jacg <notifications@github.com> writes:

>     It is highlighted, but the selection overlay is hiding the highlighted match. This is what is expected, the selection overlay have higher priority.
>
> In that case, why does the selection overlay not hide the highlighted
> match in the case of helm-ag?

Just loaded helm-ag and it does, at least here, anyway the
implementation of helm-ag is completely different from what is used here
at helm.  Here we use the original highlighting of the backend by
default (ansi).

> Hmm, maybe there's nothing wrong from the "here's a technical
> explanation of what is happening" perspective, but it certainly seems
> wrong from the UI perspective.

It is not, the selection should have higher priority, if you want to see
the highlighted matches, just hit C-j and you will see them in other buffer.

--
Thierry

**Comment by jacg** [comment]
>> why does the selection overlay not hide the highlighted match in the case of helm-ag?

> Just loaded helm-ag and it does, at least here

Just loaded helm-ag, and it does **not**, at least in a clean install.

Here is my recipe:

1. `cd /tmp`
1. `mkdir helm-test`
1. `cd helm-test`
1. `git clone https://github.com/emacs-helm/helm.git`
1. `https://github.com/syohex/emacs-helm-ag.git`
1. `cd helm`
1. `make`
1. `./emacs-helm.sh &`
1. `M-x helm-do-grep-ag RET defun C-n C-n C-n`
1. Take screenshot `A`
1. `C-g`
1. `M-x load-file RET /tmp/helm-test/emacs-helm-ag/helm-ag.el`
1. `M-x helm-ag RET defun RET C-n C-n C-n`
1. Take screenshot `B`

Here are screenshots `A` and `B` resulting from the above process:

![helm-do-grep-ag](https://cloud.githubusercontent.com/assets/2570854/21925164/7cc51a6a-d97c-11e6-9ef1-491cd9e25549.png)

![helm-ag](https://cloud.githubusercontent.com/assets/2570854/21925167/83f8b1fc-d97c-11e6-8bb8-ac5c5b27bde2.png)

Please observe that on screenshot `B` (unlike on screenshot `A`) the match is highlighted (red foreground) on *all* lines, including the selected one.

This might be explained by the fact that in `B` the match highlight face sets the foreground, while in `A` the match highlight face (whatever it may be) only sets the background, and the background is overwritten by the selection face or overlay.

Which leads us to the question "What is the match highlight face in `helm-do-grep-ag`?" I would have thought that it is `helm-grep-match`, but the fact that (in the test configuration which produced the screenshots) `helm-grep-match` has a red (`#b00000`) foreground (and no other set attributes) while the corresponding screenshot shows the match being highlighted with a black foreground and yellow background, leads me to conclude that `helm-grep-match` is not what we are looking at here.

It also leads me to conclude that the following might be a solution to the problem:

- Identify the face being used to highlight matches in `helm-do-grep-ag` and change its foreground.

>>  it certainly seems wrong from the UI perspective.

> It is not, the selection should have higher priority,

We seem to have fundamentally differing ideas about the meaning of 'should'. You seem to be using technical explanations of why, given the code that currently exists, the observed behaviour occurs. I am talking about *useful* and *desirable* behaviour, which is different from the behaviour we currently have.

I trust that you agree that having the match highlighted on the selected line is more useful than not having it highlighted on the selected line. That is what I mean by 'should'.

>  if you want to see the highlighted matches, just hit C-j and you will see them in other buffer.

That works, but it places glitches in the otherwise smooth workflow. It demotes this particular feature of helm from spectacularly and amazingly awesome to a mere awesome.

Can you identify the black-foreground-yellow-background face that is being used by `helm-do-grep-ag` to highlight matches in screenshot `A`?

If you can help me identify that face, then I can probably arrive at a satisfactory soultion myself.

Many thanks for your work on helm. Every now and then, something comes along that makes the Emacs experience (and thus life) take a *huge* leap forward. Helm is one of those.

**Comment by thierryvolpiatto** [comment]
jacg <notifications@github.com> writes:

> This might be explained by the fact that in B the match highlight face
> sets the foreground, while in A the match highlight face (whatever it
> may be) only sets the background, and the background is overwritten by
> the selection face or overlay.

When helm-match face foreground is red it is highlighted in red,
but when it is black it is highlighted in black and BTW less visible.

> Which leads us to the question "What is the match highlight face in
> helm-do-grep-ag?" I would have thought that it is helm-grep-match, but
> the fact that (in the test configuration which produced the
> screenshots) helm-grep-match has a red (#b00000) foreground (and no
> other set attributes) while the corresponding screenshot shows the
> match being highlighted with a black foreground and yellow background,
> leads me to conclude that helm-grep-match is not what we are looking
> at here.

Highlighting use the same face as the backend use ("--color=always").
helm-grep-match face is used only if you use "--nocolor", so
highlighting is done by helm with elisp (slower).

> It also leads me to conclude that the following might be a solution to
> the problem:
>
>   * Identify the face being used to highlight matches in
>   helm-do-grep-ag and change its foreground.

Use --color-match in your `helm-grep-ag-command`
e.g "--color-match '31;43'" (red on yellow).

> That works, but it places glitches in the otherwise smooth
> workflow. It demotes this particular feature of helm from
> spectacularly and amazingly awesome to a mere awesome.

Sorry I don't understand these two sentences :-)

> Can you identify the black-foreground-yellow-background face that is
> being used by helm-do-grep-ag to highlight matches in screenshot A?

See above, faces are build according to ansi sequence.

> If you can help me identify that face, then I can probably arrive at a
> satisfactory soultion myself.

Using --color-match should fit your needs.

> Many thanks for your work on helm. Every now and then, something comes
> along that makes the Emacs experience (and thus life) take a huge leap
> forward. Helm is one of those.

Thanks.

--
Thierry

**Comment by thierryvolpiatto** [comment]
So to summarize what you probably want is customizing the color used by ag to highlight matches so that you can see them under helm selection, here what to customize to have a yellow background and a red foreground (see https://en.wikipedia.org/wiki/ANSI_escape_code#Colors):

```elisp
(setq helm-grep-ag-command "ag --line-numbers -S --hidden --color --color-match '31;43' --nogroup %s %s %s")
(setq helm-grep-ag-pipe-cmd-switches '("--color-match '31;43'"))
```

**Comment by jacg** [comment]
This recipe works for me.

Many thanks.

**Comment by AtomicNess123** [comment]
> So to summarize what you probably want is customizing the color used by ag to highlight matches so that you can see them under helm selection, here what to customize to have a yellow background and a red foreground (see https://en.wikipedia.org/wiki/ANSI_escape_code#Colors):
> 
> ```emacs-lisp
> (setq helm-grep-ag-command "ag --line-numbers -S --hidden --color --color-match '31;43' --nogroup %s %s %s")
> (setq helm-grep-ag-pipe-cmd-switches '("--color-match '31;43'"))
> ```

Thanks. Do you have to configure too the `helm-ag-base-command` separately?
