### ISSUE TITLE
helm-grep-ignored-directories helm-grep-ignored-files are not working..

### ISSUE THREAD

**Issue by littlehome-eugene** [emacs-helm/helm#1661]
## Expected behavior

When I include 'foo'
helm-grep-ignored-directories

I expect not to see results under 'foo/*/*'

## Actual behavior from emacs-helm.sh if possible

    (defun my-helm-grep-do-git-grep (not-all)
    (interactive "P")
    (helm-grep-git-1 default-directory (null not-all)))

    (global-set-key (kbd "C-c g") 'my-helm-grep-do-git-grep)

When I do my-helm-grep-do-git-grep, I see results from `foo/*`

## Describe versions of helm, emacs, operating system etc.

emacs 25.1.2
helm 2.4.0

ubuntu

**Comment by thierryvolpiatto** [comment]
littlehome-eugene <notifications@github.com> writes:

> Expected behavior
>
> When I include 'foo'
> helm-grep-ignored-directories
>
> I expect not to see results under 'foo//'
>
> Actual behavior from emacs-helm.sh if possible
>
> (defun my-helm-grep-do-git-grep (not-all)
> (interactive "P")
> (helm-grep-git-1 default-directory (null not-all)))
>
> (global-set-key (kbd "C-c g") 'my-helm-grep-do-git-grep)
>
> When I do my-helm-grep-do-git-grep, I see results from foo/*

These variables are used by the helm-grep's using grep as backend, all
other backends are not supporting "--exclude" options and have their own
mechanisms to ignore directories/files, for git you have to configure
your .gitconfig and .gitignore or .gitignore_globals files.


-- 
Thierry

**Comment by littlehome-eugene** [comment]
I would like to feature request to exclude files/directories in git grep.

.gitignore is to decide which files you want to manage in the repository.

There could be non gitignored files that you don't want to search.  

For one, in django project, there's a database migration files, which probably most django developers don't want to in there git-grep.

**Comment by xuchunyang** [comment]
> I would like to feature request to exclude files/directories in git grep.

git-grep doesn't support this outside git, as far as I know.

> .gitignore is to decide which files you want to manage in the repository.

hmm, though you are not wrong, but according to `man gitignore`, `.gitignore` is to "Specifies intentionally untracked files to ignore".

> There could be non gitignored files that you don't want to search.

By default, git-grep(1) doesn't search untracked files (even they are non gitignored). To use the default behavior, try to remove `--no-index --exclude-standard` from the user option `helm-grep-git-grep-command`.

**Comment by thierryvolpiatto** [comment]
littlehome-eugene <notifications@github.com> writes:

> There could be non gitignored files that you don't want to search.

You can add files to ignore to "~/.gitignore_global" file.
For example in the emacs git repo, there is "Changelog" files that I want
to ignore, they are git controled and not in the local ".gitignore"
file, I added "Changelog*" to "~/.gitignore_global" file and when I
git-grep the emacs directory these files are ignored.

> For one, in django project, there's a database migration files, which
> probably most django developers don't want to in there git-grep.

Yes, add it to global file.

--
Thierry

**Comment by emacsun** [comment]
@thierryvolpiatto it works for me. now under the root of the project there are two ignore files: one is .gitignore and the other one is .gitignore_global. Why not just one? this is very abnormal to have two .gitignore files.  :)

**Comment by thierryvolpiatto** [comment]
Eastern Zhang <notifications@github.com> writes:

> @thierryvolpiatto it works for me. now under the root of the project
> there are two ignore files: one is .gitignore and the other one is
> .gitignore_global.

Which project?

A .gitignore file have to be in the project's directory and a
.gitignore_global have to be in the $HOME directory.

> Why not just one? this is very abnormal to have two .gitignore
> files. :)

Yes a .gitignore_global file have nothing to do in a directory project.



--
Thierry

**Comment by pcompassion** [comment]
I finally figured out what it means with my setup I had to add `--exclude-standard --no-index` to `helm-grep-git-grep-command`

git --no-pager grep --exclude-standard --no-index -n%cH --color=always --full-name -e %p -- %f

**Comment by thierryvolpiatto** [comment]
pcompassion <notifications@github.com> writes:

> I finally figured out what it means with my setup I had to add
> --exclude-standard --no-index to helm-grep-git-grep-command

Which is documented in its docstring...

--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
