### ISSUE TITLE
`helm-next-or-previous-line` beginning and end handling

### ISSUE THREAD

**Issue by xiongtx** [emacs-helm/helm#1663]
## Expected behavior

`helm-next-line` and `helm-previous-line`, which both delegate to `helm-next-or-previous-line`, should do nothing if `helm-move-to-line-cycle-in-source` is `nil` and we are at the beginning/end of a source.

## Actual behavior from emacs-helm.sh if possible

When at beginning/end of a source, moving up/down seems to return the current candidate.

This creates a problem when working with [preview buffers](https://groups.google.com/forum/#!topic/emacs-helm/8LNuVa1zsVc). When `helm-follow-mode-p` is `t`, there's no way to distinguish between:

- Being at beginning/end candidate and moving up/down
- Calling persistent action on beginning/end candidate

We need to be able to distinguish between these two events (or eliminate the first event) to have different behavior.

- Being at beginning/end candidate and moving up/down *should not* kill preview buffer.
- Calling persistent action on beginning/end candidate when preview buffer is shown *should* kill preview buffer.

## Steps to reproduce (recipe)

As described above.

## Backtraces if some (M-x toggle-debug-on-error)

N/A

## Describe versions of helm, emacs, operating system etc.

- Helm: 2.4.0
- Emacs: 25.1.1
- OS: Fedora 24

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> Expected behavior
>
> helm-next-line and helm-previous-line, which both delegate to
> helm-next-or-previous-line, should do nothing if
> helm-move-to-line-cycle-in-source is nil and we are at the
> beginning/end of a source.
>
> Actual behavior from emacs-helm.sh if possible
>
> When at beginning/end of a source, moving up/down seems to return the current candidate.
>
> This creates a problem when working with preview buffers. When
> helm-follow-mode-p is t, there's no way to distinguish between:
>
>   * Being at beginning/end candidate and moving up/down
>   * Calling persistent action on beginning/end candidate

I think I understand your concern with what you call preview buffers and
follow-mode.
helm-next/previous-line is a sensible area which needs to be modified
very carefully.
If we modify this we will have a cascade of bugs with follow-mode in
diverses situations, the first coming to mind is follow-mode will not
show anymore first candidate after update.  Try to think at an other
approach with your preview buffers i.e do something when your preview
buffer is alive and visible and do something else when not.
You can also determine if you are in persistent action or not etc...

> We need to be able to distinguish between these two events (or
> eliminate the first event) to have different behavior.

You can determine if you are at first/last candidate with
helm-beginning-of-source-p and helm-end-of-source-p.

--
Thierry

**Comment by xiongtx** [comment]
I'll close this b/c it's not a big deal--just a bit inconvenient that moving up/down at top/bottom entries toggles the preview buffer.
