### ISSUE TITLE
Is there a way to change function colors in C?

### ISSUE THREAD

**Issue by hisnawi** [emacs-helm/helm#1665]
I am trying to change the functions color in emacs (I have helm installed).
I program in C/C++.

Is there a way of doing so?

**Comment by thierryvolpiatto** [comment]
hisnawi <notifications@github.com> writes:

> I am trying to change the functions color in emacs (I have helm installed).
> I program in C/C++.
>
> Is there a way of doing so?

You bug report is not complete, I don't understand what you want.
We provide a template for bug reports, please follow it and describe
exactly what is your problem, otherwise I will close this bug.

Thanks.

-- 
Thierry

**Comment by xiongtx** [comment]
Changing colors involves getting a new [color theme](https://www.emacswiki.org/emacs/ColorThemes). It has nothing to do w/ Helm.

**Comment by hisnawi** [comment]
My sincere apologies. I am new to emacs and just installed the prelude package which includes helm. I see many talk about helm-colors and thought it might be responsible for setting custom face, but now I think this is part of the theme.
please close this bug.
