### ISSUE TITLE
`helm-minibuffer-history` breaks with right arrow

### ISSUE THREAD

**Issue by xiongtx** [emacs-helm/helm#1667]
## Expected behavior

When using `query-replace-regexp` and related functions, `helm-minibuffer-history` should work when selecting candidates of the form `foo → bar`, where `→` is the [Rightwards Arrow](http://www.codetable.net/hex/2192).

## Actual behavior from emacs-helm.sh if possible

Selecting `foo → bar` results in `foo^@bar` being entered into the minibuffer.

## Steps to reproduce (recipe)

1. Call `query-replace-regexp` with `bar` replacing `foo`
2. Call it again and select `foo → bar` from `helm-minibuffer-history` (`C-r` by default).

## Backtraces if some (M-x toggle-debug-on-error)

N/A

## Describe versions of helm, emacs, operating system etc.

- Helm: 2.4.0
- Emacs: 25.1.1
- OS: Fedora 24

**Comment by xuchunyang** [comment]
The actual text is `foo^@bar`, though due to text properties, it displays as `foo → bar`. And `query-replace[-regexp]` does rely on the text properties. However, helm doesn't preserve text properties after completion.

Here is a work-around, which works for me:

```elisp
(define-advice helm-minibuffer-history (:after () add-text-property-back)
  "For `query-replace' and `query-replace-regexp'."
  (when (eq minibuffer-history-variable
            'query-replace-from-to-history)
    (let* ((str (minibuffer-contents))
           (pos (string-match "\0" str)))
      ;; Adapted from `query-replace-read-from'
      (add-text-properties
       pos (1+ pos)
       `(display ,query-replace-from-to-separator separator t)
       str)
      (delete-minibuffer-contents)
      (insert str))))
```

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> Actual behavior from emacs-helm.sh if possible
>
> Selecting foo → bar results in foo^@bar being entered into the minibuffer.

Hmm, could reproduce with emacs-25, works fine with emacs-24.5 though as
the stupid unicode separator have not been added there yet.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

> The actual text is foo^@bar, though due to text properties, it displays as foo → bar. And query-replace[-regexp] does rely on the text properties. However, helm
> doesn't preserve text properties after completion.
>
> Here is a work-around, which works for me:
>
> (define-advice helm-minibuffer-history (:after () add-text-property-back)
>   "For `query-replace' and `query-replace-regexp'."
>   (when (eq minibuffer-history-variable
>             'query-replace-from-to-history)
>     (let* ((str (minibuffer-contents))
>            (pos (string-match "\0" str)))
>       ;; Adapted from `query-replace-read-from'
>       (add-text-properties
>        pos (1+ pos)
>        `(display ,query-replace-from-to-separator separator t)
>        str)
>       (delete-minibuffer-contents)
>       (insert str))))

Thanks for this, helped a lot, however seems
`query-replace-from-to-history` doesn't exists so I finally had to test
with `last-command`, which works fine.

Can't believe they have added such a thing in emacs :-(

-- 
Thierry

**Comment by xiongtx** [comment]
Works like a charm.

I personally like the arrow; it makes it easy to transpose words and change the direction of `query-replace`. Maybe implementation could be better, though.

**Comment by thierryvolpiatto** [comment]
Great thanks, many thanks to @xuchunyang also your advice saved me a lot of time.
