### ISSUE TITLE
Copy paste with middle mouse button in minibuffer should work out of the box

### ISSUE THREAD

**Issue by torgil** [emacs-helm/helm#1669]
## Expected behavior
Emacs should paste selected text into minibuffer

## Actual behavior from emacs-helm.sh if possible
Emacs does nothing

## Steps to reproduce (recipe)
1. install Ubuntu 16.04
2. apt install emacs
3. launch emacs and install helm
4. M-x helm-find-files<return>
5. Select text somewhere with left mouse button 
6. Switch to minibuffer and press middle mouse button 

## Describe versions of helm, emacs, operating system etc.
Ubuntu 16.04
Emacs 24.5.1
Helm 20170119.158

**Comment by thierryvolpiatto** [comment]
torgil <notifications@github.com> writes:

> Expected behavior
>
> Emacs should paste selected text into minibuffer
>
> Actual behavior from emacs-helm.sh if possible
>
> Emacs does nothing
>
> Steps to reproduce (recipe)
>
>  1. install Ubuntu 16.04
>  2. apt install emacs
>  3. launch emacs and install helm
>  4. M-x helm-find-files
>  5. Select text somewhere with left mouse button

Use instead "C-c C-k" (copy display part) or "C-u C-c C-k" (copy real
part).

>  6. Switch to minibuffer and press middle mouse button

Use then C-y or helm-show-kill-ring.

Note: Usage of the mouse in helm is not provided except for help echo's
and scrolling.
I am personally not using the mouse at all in emacs, it is most of the
time disabled...

-- 
Thierry

**Comment by torgil** [comment]
Thank you for swift handling of this issue.

I interpret your response that I either need to branch, look for a branch or look elsewhere for any mouse-integration in Helm.

**Comment by thierryvolpiatto** [comment]
torgil <notifications@github.com> writes:

> Thank you for swift handling of this issue.
>
> I interpret your response that I either need to branch, look for a
> branch or look elsewhere for any mouse-integration in Helm.

Don't expect any mouse integration in helm soon, helm is keyboard oriented
and will stay like this for long time.

Sorry and thanks for your understanding.

--
Thierry

**Comment by michael-heerdegen** [comment]
torgil <notifications@github.com> writes:

> I interpret your response that I either need to branch, look for a
> branch or look elsewhere for any mouse-integration in Helm.

Helm is actively impeding mouse usage. You can get it mostly work again
with

(setq helm-prevent-escaping-from-minibuffer nil)
(define-key helm-map [down-mouse-1] nil)
(define-key helm-map [mouse-1] nil)
(define-key helm-map [mouse-2] nil)


Michael.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> torgil <notifications@github.com> writes:
>
>> I interpret your response that I either need to branch, look for a
>> branch or look elsewhere for any mouse-integration in Helm.
>
> Helm is actively impeding mouse usage. You can get it mostly work again
> with
>
> (setq helm-prevent-escaping-from-minibuffer nil)
> (define-key helm-map [down-mouse-1] nil)
> (define-key helm-map [mouse-1] nil)
> (define-key helm-map [mouse-2] nil)

Don't complain however if you loose focus in your helm-session with such
settings.

-- 
Thierry

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> Don't complain however if you loose focus in your helm-session with
> such settings.

Yes - it's the purpose of this snipped to allow this.  Actually, the
behavior is not different from anything else reading input using a
minibuffer: you can get focus back (to Helm) by simply switching back to
the minibuffer with the ordinary means (clicking on it with the mouse or
C-x o or whatever).  However unlike vanilla Emacs completion, it's not
useful to select the candidates window because you can't do anything
useful here (and the cursor is not visible).

**Comment by torgil** [comment]
Thanks Michael.  These settings will do it for me. My use-case is not really to use mouse with helm but to be able to find files with helm and paste them elsewhere or vice versa (like open a path outputed by some script or web page).

**Comment by thierryvolpiatto** [comment]
torgil <notifications@github.com> writes:

> My use-case is not really to use mouse with helm but to be able to
> find files with helm and paste them elsewhere or vice versa (like open
> a path outputed by some script or web page).

You don't need the mouse to do this, from helm to elswhere it can be
done with `C-c C-k` (perhaps prefixed with C-u) and then `C-y`, and from
elsewhere to helm, just use `C-k` and `C-y`.

--
Thierry

**Comment by freckletonj** [comment]
If i have selected multiple files/dirs with `C-SPC`, is there a way to copy them such that I can yank them all, or perhaps even `yank-rectangle`?
