### ISSUE TITLE
registering a candidate buffer seems to be broken?

### ISSUE THREAD

**Issue by lewang** [emacs-helm/helm#1672]
660740d1  doesn't look right to me.

`helm-candidate-buffer-alist` has to be saved across calls to `helm-candidate-buffer`.

**Comment by thierryvolpiatto** [comment]
Le Wang <notifications@github.com> writes:

> 660740d doesn't look right to me.
>
> helm-candidate-buffer-alist has to be saved across calls to helm-candidate-buffer.

Please develop, using the issue template.

Thanks.

-- 
Thierry

**Comment by lewang** [comment]
Issue fixed in 	d9aaf7b

**Comment by thierryvolpiatto** [comment]
Le Wang <notifications@github.com> writes:

> Issue fixed in d9aaf7b

Perhaps, but I expect more explanations in bug reports and the issue
template to not be ignored.

Thanks.

-- 
Thierry
