### ISSUE TITLE
Helm mode does not modify M-x or C-x C-f

### ISSUE THREAD

**Issue by J3RN** [emacs-helm/helm#1674]
## Expected behavior
Per the README:
> M-x helm-mode to enable helm completion for common Emacs commands (e.g M-x, C-x C-f, etc...).

## Actual behavior from emacs-helm.sh if possible
After initializing Helm via `M-x helm-mode`, the behavior of `M-x` and `C-x C-f` are unchanged. When running `M-x` or `C-x C-f`, Helm disappears from the list of modes only to reappear when the command is finished.

However, `C-x b` *does* use helm without issue.

## Steps to reproduce (recipe)
- Install Helm from MELPA in a clean emacs install (you will need to add MELPA to `'package-archives`, so perhaps it's not a *perfectly* clean emacs install).
- Run `M-x helm-mode` to load Helm
- Run `C-x C-f` or `M-x` and verify that Helm is not used and disappears from mode list.

## Backtraces if some (M-x toggle-debug-on-error)
None

## Describe versions of helm, emacs, operating system etc.
Helm 20170124.2354
GNU Emacs 25.1.1 (x86_64-apple-darwin16.3.0, NS appkit-1504.76 Version 10.12.2 (Build 16C67)) of 2017-01-09
macOS 10.12.2

**Comment by xuchunyang** [comment]
It's done by 1de1701c73b15a86e99ab1c5c53bd0e8659d8ede. Though the README needs to be updated.
