### ISSUE TITLE
company mode taking over helm 

### ISSUE THREAD

**Issue by zeltak** [emacs-helm/helm#1677]
## Expected behavior
in helm buffers company shouldnt takeover TAB, i wonder if i can define TAB to work in helm buffers overriding TAB behavior 

## Steps to reproduce (recipe)
add  the company packages and as in the wiki assign

```(global-set-key [tab] 'tab-indent-or-complete)```

## Describe versions of helm, emacs, operating system etc.
emacs 25.1, arch linux , latest helm from melpa

also see issue initially opned here
https://github.com/company-mode/company-mode/issues/634#issuecomment-275358012

best

Z

**Comment by thierryvolpiatto** [comment]
zeltak <notifications@github.com> writes:

> Expected behavior
>
> in helm buffers company shouldnt takeover TAB, i wonder if i can define TAB to work in helm buffers overriding TAB behavior
>
> Steps to reproduce (recipe)
>
> add the company packages and as in the wiki assign
>
> (global-set-key [tab] 'tab-indent-or-complete)

The vector version of TAB is overriding bindings wrote with `\t` or
`C-i` try instead:

    (global-set-key (kbd "C-i") 'tab-indent-or-complete)

-- 
Thierry

**Comment by zeltak** [comment]
thx @thierryvolpiatto  for the answer

sorry for the silly question, but above you are suggesting to use `Ctrl-i ` instead of tab right?

i rather like the TAB for completion. so i understand its impossible to have both helm and company to share the TAB key? if so can i remap the TAB function in default helm to a new bind?

appreciate the help!

Z

**Comment by thierryvolpiatto** [comment]
zeltak <notifications@github.com> writes:

> thx @thierryvolpiatto for the answer
>
> sorry for the silly question, but above you are suggesting to use
> Ctrl-i instead of tab right?

Yes, C-i is the same key as TAB.
>
> i rather like the TAB for completion.

Yes, no problem, bind your key to C-i and use then TAB, you will see
your command is bound to TAB without overriding TAB inside helm.

> so i understand its impossible to have both helm and company to share
> the TAB key?

No you can of course.


-- 
Thierry

**Comment by zeltak** [comment]
hmmm ahh i see now, thx for the clarifications

unfortunantly, the bind dosent seem to be helping with the use in company when the completion pops up

this is the bind i used
```
(global-set-key (kbd "C-i") 'tab-indent-or-complete)
```

it does bring back the TAB in helm (great!:)) yet i cant get company to use TAB to complete

thx again

Z

**Comment by zeltak** [comment]
ok just to update the issue , i *finally* got it working with this code

```

 (with-eval-after-load 'company
   (define-key company-mode-map (kbd "C-i") #'company-indent-or-complete-common)
 )
```

thx you so much for the help and effort, its much appreciated!

best

Z

**Comment by thierryvolpiatto** [comment]
zeltak <notifications@github.com> writes:

> ok just to update the issue , i finally got it working with this code
>
>  (with-eval-after-load 'company
>    (define-key company-mode-map (kbd "C-i") #'company-indent-or-complete-common)
>  )

As long don't bind this to global-map, I think you can use as well [tab]
or "\t" without overriding over bindings.

Anyway glad you could resolve your problem.


-- 
Thierry
