### ISSUE TITLE
C-x C-s not saving results to a persistent buffer.

### ISSUE THREAD

**Issue by it3ration** [emacs-helm/helm#1678]
## Expected behavior

When I open a helm buffer via helm-do-ag-project-root or similar, then hit C-x C-s and save the results to a buffer, the buffer should be persistent.

## Actual behavior from emacs-helm.sh if possible

When I navigate away from the buffer (aka, switch to another buffer) the buffer is removed and it's not possible to return to it.

## Steps to reproduce (recipe)

M-x helm-do-ag-project-root
...
C-x C-s
C-x b

## Describe versions of helm, emacs, operating system etc.

Latest version from melpa.

**Comment by thierryvolpiatto** [comment]
Kevin Depue <notifications@github.com> writes:

> Expected behavior
>
> When I open a helm buffer via helm-do-ag-project-root or similar, then hit C-x C-s and save the results to a buffer, the buffer should be persistent.
>
> Actual behavior from emacs-helm.sh if possible
>
> When I navigate away from the buffer (aka, switch to another buffer) the buffer is removed and it's not possible to return to it.
>
> Steps to reproduce (recipe)
>
> M-x helm-do-ag-project-root

I have no such command, perhaps coming from another package ?
I can't reproduce with M-x helm-do-grep-ag and C-x C-s, the buffer is
saved as expected, however I see another bug when jumping to candidate
which I will fix soon.

-- 
Thierry

**Comment by xiongtx** [comment]
`helm-do-ag-project-root` is from the [`helm-ag`](https://github.com/syohex/emacs-helm-ag) package.

**Comment by it3ration** [comment]
My apologies, it is in the aforementioned package [helm-ag](https://github.com/syohex/emacs-helm-ag).  However, I swear I've seen it with other commands (that is to say, saving helm results in a buffer, then navigating to another buffer, and when I try to return, the saved buffer is gone).

**Comment by xiongtx** [comment]
The problem is that the buffer is named `*helm ag results*`; buffers with names starting with `*helm` are hidden by `helm-buffers-list`, `helm-mini`, etc. because Helm creates a lot of such buffers and does not want them to pollute the buffers list.

To see this, call `switch-to-buffer` and verify that the `ag` results buffer is there.

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> The problem is that the buffer is named *helm ag results*; buffers
> with names starting with *helm are hidden by helm-buffers-list,
> helm-mini, etc. because Helm creates a lot of such buffers and does
> not want them to pollute the buffers list.

You can see all hidden buffers with `C-c a` (it is a toggle command).

--
Thierry

**Comment by xiongtx** [comment]
> You can see all hidden buffers with `C-c a`

Helm is full of surprises!

**Comment by thierryvolpiatto** [comment]
Kevin Depue <notifications@github.com> writes:

> My apologies, it is in the aforementioned package helm-ag. However, I
> swear I've seen it with other commands (that is to say, saving helm
> results in a buffer, then navigating to another buffer, and when I try
> to return, the saved buffer is gone).

You can save helm buffers only when using grep or derived (git-grep, ag
etc..) and helm-occur/moccur.
This two modes are working as expected and their buffers always visibles
from buffer listing.
You can create several buffers (you are then prompted for a different
name) or overwrite the previous one.

--
Thierry

**Comment by it3ration** [comment]
Hah, I've been a hardcore emacs user for years and even written my own packages, but I wasn't aware of hidden buffers.  Thanks @xiongtx, that works just fine. :)
