### ISSUE TITLE
Wrong type argument: stringp, nil

### ISSUE THREAD

**Issue by michengit** [emacs-helm/helm#1682]
## Expected behavior
without error

## Actual behavior from emacs-helm.sh if possible
Wrong type argument: stringp, nil

## Steps to reproduce (recipe)
Running helm-M-x  on 2.5.1 release today

## Describe versions of helm, emacs, operating system etc.
2.5.1, emacs 25.1.91.1, ubuntu 14

**Comment by thierryvolpiatto** [comment]
michengit <notifications@github.com> writes:

> Actual behavior from emacs-helm.sh if possible
>
> Wrong type argument: stringp, nil

Are you really using emacs-helm.sh ?

> Steps to reproduce (recipe)
>
> Running helm-M-x on 2.5.1 release today

Not reproductible here.

> Backtraces if some (M-x toggle-debug-on-error)

Please backtrace.

> Describe versions of helm, emacs, operating system etc.
>
> 2.5.1, emacs 25.1.91.1, ubuntu 14
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.*


-- 
Thierry

**Comment by michengit** [comment]
Sorry not notice this requirement. No, i am not running emacs-helm.sh. 

One thing is i am always using the latest version on emacs 25.1. Not sure if this is the cause.

here is the trace buffer content:

helm-init-candidates-in-buffer(global ("magit-diff-popup" "gnus-score-mode" "desktop-save-in-desktop-dir" "edebug-Trace-fast-mode" "company-version" "package$
  #[0 "\301\302\303\300!\203^M^@\300 \202^N^@\300\"\207" [#[0 "\306\300\301\304\305$\307^V^P\303\242\310=\204O^@^N^Q\311\230\204O^@\312^N^Q^B\"\204O^@\312\313^$
  apply(#[0 "\301\302\303\300!\203^M^@\300 \202^N^@\300\"\207" [#[0 "\306\300\301\304\305$\307^V^P\303\242\310=\204O^@^N^Q\311\230\204O^@\312^N^Q^B\"\204O^@\31$
  helm-funcall-with-source(((nomark) (name . "Emacs Commands") (init #[0 "\301\302\303\300!\203^M^@\300 \202^N^@\300\"\207" [#[0 "\306\300\301\304\305$\307^V^P$
  helm-funcall-foreach(init)
  helm-initial-setup(nil)
  helm-initialize(noresume nil nil (((nomark) (name . "Emacs Commands History") (candidates . #[0 "\304\302\300\305\303$\211\205^Q^@\306\307\310\301^D\"\"\207"$
  helm-internal((((nomark) (name . "Emacs Commands History") (candidates . #[0 "\304\302\300\305\303$\211\205^Q^@\306\307\310\301^D\"\"\207" [commandp nil ("ev$
  apply(helm-internal ((((nomark) (name . "Emacs Commands History") (candidates . #[0 "\304\302\300\305\303$\211\205^Q^@\306\307\310\301^D\"\"\207" [commandp n$
  helm((((nomark) (name . "Emacs Commands History") (candidates . #[0 "\304\302\300\305\303$\211\205^Q^@\306\307\310\301^D\"\"\207" [commandp nil ("eval-buffer$
  apply(helm ((((nomark) (name . "Emacs Commands History") (candidates . #[0 "\304\302\300\305\303$\211\205^Q^@\306\307\310\301^D\"\"\207" [commandp nil ("eval$
  helm(:sources (((nomark) (name . "Emacs Commands History") (candidates . #[0 "\304\302\300\305\303$\211\205^Q^@\306\307\310\301^D\"\"\207" [commandp nil ("ev$
  helm-comp-read("M-x " [unfill edebug-Trace-fast-mode corral edebug-inside-func company-gtags--annotation helm-swoop-split-direction debpaste debugger-previou$
  helm-M-x-read-extended-command()
  byte-code("^H^Q^H\302 D\207" [current-prefix-arg helm-M-x-prefix-argument helm-M-x-read-extended-command] 2)
  call-interactively(helm-M-x nil nil)
  command-execute(helm-M-x)

**Comment by thierryvolpiatto** [comment]
michengit <notifications@github.com> writes:

> Sorry not notice this requirement. No, i am not running emacs-helm.sh.

So please use it to see if this is reproductible from it.


> One thing is i am always using the latest version on emacs 25.1. Not
> sure if this is the cause.

No I can't reproduce from emacs-25.1 nor emacs-26.
Be sure helm si installed properly (perhaps reinstall it).

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
michengit <notifications@github.com> writes:

> here is the trace buffer content:

How did you get this backtrace ?

Also try to load manually the files helm.el and helm-command.el to avoid
bytecode in BT.

> helm-init-candidates-in-buffer(global ("magit-diff-popup"
> "gnus-score-mode" "desktop-save-in-desktop-dir"
> "edebug-Trace-fast-mode" "company-version" "package$

My guess is you are still using an old helm.el somewhere, please check
your install.

Thanks.

-- 
Thierry

**Comment by michael-heerdegen** [comment]
FWIW I also can't reproduce.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> FWIW I also can't reproduce.

Thanks to confirm, I think this is just a wrong installation problem,
the behavior with 'global buffers haven't changed AFAIK in 2.5.1.

-- 
Thierry

**Comment by michengit** [comment]
You are right. I re-install the entire helm package and it works fine now. Thanks.
