### ISSUE TITLE
Ivy´s ivy-occur in helm

### ISSUE THREAD

**Issue by jtkDvlp** [emacs-helm/helm#1683]
Hi guys,

I am new to helm. And I am wondering if there is are functionality in helm like the from ivy given ivy-occour ?

Thanks

**Comment by xiongtx** [comment]
There's `helm-occur`. 

For future reference, such questions are better suited for the [Emacs StackExchange](http://emacs.stackexchange.com/) or [Helm Google Group](https://groups.google.com/forum/#!forum/emacs-helm).

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> There's helm-occur.

The original and the best ;-)

-- 
Thierry

**Comment by jtkDvlp** [comment]
> For future reference, such questions are better suited for the Emacs StackExchange or Helm Google Group.

Of course, sry.

Thanks for quick feedback. But I think im looking for another function. Helm´s occur searchs the buffer, but ivy´s occur put the current matches into a new buffer and stop completion. See doc:

> (ivy-occur)
> 
> Stop completion and put the current matches into a new buffer.
> 
> The new buffer remembers current action(s).
> 
> While in the *ivy-occur* buffer, selecting a candidate with RET or
> a mouse click will call the appropriate action for that candidate.
> 
> There is no limit on the number of *ivy-occur* buffers.

Or I´m wrong? oO

Thanks

**Comment by thierryvolpiatto** [comment]
JT Knabenschuh <notifications@github.com> writes:

> Thanks for quick feedback. But I think im looking for another
> function. Helm´s occur searchs the buffer, but ivy´s occur put the
> current matches into a new buffer and stop completion.

helm-occur does the both, please try it and get used to it.

>     There is no limit on the number of ivy-occur buffers.

Same here.

--
Thierry
