### ISSUE TITLE
`helm-goto-source` nil vs. empty string

### ISSUE THREAD

**Issue by xiongtx** [emacs-helm/helm#1684]
## Expected behavior

`helm-goto-source` should behave the same when given `nil` or an empty string `""`.

## Actual behavior from emacs-helm.sh if possible

`(helm-goto-source "")` does the right thing. `(helm-goto-source nil)` does not.

## Steps to reproduce (recipe)

Evaluate the following and see that `a` is selected, as expected.

```emacs-lisp
(progn
  (with-helm-after-update-hook
    (with-helm-buffer
      (let ((helm--force-updating-p t))
        (helm-goto-source "")        
        (recenter 1))))
  (helm :sources (list (helm-build-sync-source "ABC"                       
                         :candidates '(a b c))
                       (helm-build-sync-source "DEF"
                         :candidates '(d e f)))
        :buffer "Test"))
```

Changing `(helm-goto-source "")` to `(helm-goto-source nil)` selects `DEF`, the source header line, which is incorrect.  

## Backtraces if some (M-x toggle-debug-on-error)

N/A

## Describe versions of helm, emacs, operating system etc.

- Helm: `20170131.754`
- Emacs: `25.1`
- OS: `Darwin C02RW05YFVH6 15.6.0`

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> Expected behavior
>
> helm-goto-source should behave the same when given nil or an empty string "".

Why not, I am not against this, it is now fixed.
However, I don't really see why you need this, if the selection is stuck
on first source header at startup, perhaps your code have a problem
elsewhere and abusing helm-goto-source in the helm-after-update-hook is
maybe hiding another problem.

Thanks.

-- 
Thierry

**Comment by xiongtx** [comment]
> If the selection is stuck on first source header at startup, perhaps your code have a problem
elsewhere and abusing `helm-goto-source` in the `helm-after-update-hook` is maybe hiding another problem.

My use case involves jumping to a source based on the symbol at point. If there is no symbol, the default should be to go to the first line of the first source. 

Also see comment about making `source-or-name` optional for `helm-goto-source`.

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

>     If the selection is stuck on first source header at startup, perhaps your code have a problem
>     elsewhere and abusing helm-goto-source in the helm-after-update-hook is maybe hiding another problem.
>
> My use case involves jumping to a source based on the symbol at
> point. If there is no symbol, the default should be to go to the first
> line of the first source.

It what helm does by default after updating, so I don't see the need to
use here helm-goto-source.

> Also see comment about making source-or-name optional for helm-goto-source.

Yes of course this can be done also...

--
Thierry
