### ISSUE TITLE
no any keybindings shown with`helm-smex-major-mode-commands`  

### ISSUE THREAD

**Issue by 11111000000** [emacs-helm/helm#1685]
## Expected behavior

`helm-smex-major-mode-commands`  shows suggestions with keys (if available)

## Actual behavior from emacs-helm.sh if possible

`helm-smex-major-mode-commands`  shows suggestions without any keybindings

## Steps to reproduce (recipe)

`<S-M-x>`  (or `<M-x>` `helm-smex-major-mode-commands` `<RET>` )

## Describe versions of helm, emacs, operating system etc.

helm from melpa

**Comment by thierryvolpiatto** [comment]
Peter Kosov <notifications@github.com> writes:

> Expected behavior
>
> helm-smex-major-mode-commands shows suggestions with keys (if available)

helm-smex is not part of helm, please report bug to the relevant place.

Thanks.

-- 
Thierry

**Comment by xiongtx** [comment]
The `helm-smex` repo is [here](https://github.com/ptrv/helm-smex).
