### ISSUE TITLE
Make expand/contract multiline candidates a core feature

### ISSUE THREAD

**Issue by xiongtx** [emacs-helm/helm#1686]
## Expected behavior

Issue #1664 led to the development of a way to limit the number of lines of multiline candidates, and to expand candidates to their full values with a key binding, for `helm-kill-ring`.

This functionality would be useful beyond `helm-kill-ring`. A `:multiline-limit` should be added to `helm-source` that determines how many lines multiline candidates can be before they are truncated.

## Actual behavior from emacs-helm.sh if possible

New feature request.

## Steps to reproduce (recipe)

N/A

## Backtraces if some (M-x toggle-debug-on-error)

N/A

## Describe versions of helm, emacs, operating system etc.

N/A

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> This functionality would be useful beyond helm-kill-ring. A
> :multiline-limit should be added to helm-source that determines how
> many lines multiline candidates can be before they are truncated.

Good idea.

--
Thierry

**Comment by thierryvolpiatto** [comment]
So now `:multiline` slot accept a numeric value, in this case the multiple lines candidate string is truncated to `:multiline` value.

**Comment by xiongtx** [comment]
Nice, I'll try it out soon.
