### ISSUE TITLE
Add a "insert symbol name" action for helm-apropos

### ISSUE THREAD

**Issue by girzel** [emacs-helm/helm#1687]
It would be very nice if helm-apropos (or maybe some other related command) gave us the option to simply insert the symbol name in the current buffer. It might not sound like much, but I think it would be very useful when writing docs and doing support -- saves typing and typos. Just a suggestion!

**Comment by girzel** [comment]
Of course, moments later I found helm-add-action-to-source. I still think it would be generally useful, but I'll do it myself if not.

**Comment by xiongtx** [comment]
Why not make a PR if it'd be useful to others :wink:?

**Comment by thierryvolpiatto** [comment]
girzel <notifications@github.com> writes:

> It would be very nice if helm-apropos (or maybe some other related
> command) gave us the option to simply insert the symbol name in the
> current buffer.

Use `C-c C-i`.

--
Thierry

**Comment by girzel** [comment]
That's great, thank you very much!
