### ISSUE TITLE
conflict with bookmark+ and helm's bmkp-add-tags History

### ISSUE THREAD

**Issue by Dapuva76** [emacs-helm/helm#1688]
## Expected behavior
Adding a tag to a bookmark in the bookmark list of bookmark+

## Actual behavior from emacs-helm.sh if possible
I can't leave the interactive dialogue that asks me for a tag. With helm disabled, an empty line and RET leaves the dialogue and completes the process. With helm enabled, pressing RET on an empty line selects the tag from Helm's bmkp-add-tags history buffer again and again.

## Steps to reproduce (recipe)
Use latest helm and bookmarks+ from melpa. Call up the bookmarks list. Try to add a tag.

## Describe versions of helm, emacs, operating system etc.
Latest version of helm from melpa, emacs 25.1.1, windows 7

**Comment by Dapuva76** [comment]
I also contacted the maintainer of bookmarks+, he told me it sounds like a helm problem, and should get in touch with you

From Drew Adams:
> Bookmark+ does not do anything special to read tags.  It does
> only this, to read each tag:
> 
> (completing-read prompt1 cands nil nil nil 'bmkp-tag-history)
> 
> where CANDS is an alist each of whose element is a singleton
> list of a tag, e.g., (("red") ("blue")...).
> 
> Note that `completing-read is called with nil as its
> REQUIRE-MATCH argument, meaning that completion is lax
> (the tag name you enter need not be an already existing
> tag name).  Dunno whether that bothers Helm, but it is
> standard Emacs.
> 
> Note too that after each tag is read, it is removed from
> the list of completion candidates (so you don't see it
> again as a possible choice).  Dunno whether that bothers
> Helm, but it shouldn't.
>

**Comment by thierryvolpiatto** [comment]
Dapuva76 <notifications@github.com> writes:

> Expected behavior
>
> Adding a tag to a bookmark in the bookmark list of bookmark+
>
> Actual behavior from emacs-helm.sh if possible
>
> I can't leave the interactive dialogue that asks me for a tag. With
> helm disabled, an empty line and RET leaves the dialogue and completes
> the process. With helm enabled, pressing RET on an empty line selects
> the tag from Helm's bmkp-add-tags again and again.

See
https://github.com/emacs-helm/helm/wiki/FAQ#why-cant-i-exit-completing-read-with-an-empty-string

--
Thierry

**Comment by Dapuva76** [comment]
Yes, I've tried that, it says both keybinds are undefined.

**Comment by thierryvolpiatto** [comment]
Eval `(completing-read "test: " '(a b c d))`
C-RET should return "".
I does here, if this recipe is not working, be sure you are using the last helm-version and it is well installed.

Thanks.

**Comment by thierryvolpiatto** [comment]
Dapuva76 <notifications@github.com> writes:

> Yes, I've tried that, it says both keybinds are undefined.

When you hit C-RET, perhaps you are in the history source ?
The keymap was unbound there until now, now it should work from here as
well.

-- 
Thierry

**Comment by Dapuva76** [comment]
> When you hit C-RET, perhaps you are in the history source ? The keymap was unbound there until now, now it should work from here as well.

After I enter the first tag, it automatically highlights an entry in "bmkp-add-tags History". "Now" as in the latest version? I just updated, and same result.

> Eval (completing-read "test: " '(a b c d))
> C-RET should return "".

That works, no problems.

**Comment by thierryvolpiatto** [comment]
Dapuva76 <notifications@github.com> writes:

>     When you hit C-RET, perhaps you are in the history source ? The
>     keymap was unbound there until now, now it should work from here
>     as well.
>
> After I enter the first tag, it automatically highlights an entry in
> "bmkp-add-tags History". "Now" as in the latest version? I just
> updated, and same result.

So I don't know, can you provide a recipe with a completing-read where
you can't exit ?

Also did you try from emacs-helm.sh, and then load only bookmark+ and
try to reproduce ?
 
For now perhaps disable helm for this function with
`helm-completing-read-handlers-alist` to force the use of regular
completing-read.

--
Thierry

**Comment by thierryvolpiatto** [comment]
Dapuva76 <notifications@github.com> writes:

>     Eval (completing-read "test: " '(a b c d))
>     C-RET should return "".
>    
> That works, no problems.

I hardly see though why this is working and the other completing-read in
bmkplus doesn't exit properly.

-- 
Thierry

**Comment by Dapuva76** [comment]
Ok, I just tried the same situation on my Debian VM, where Emacs has a slightly different package setup. Works flawlessly. So it's likely some other package interfering, but I don't know how to debug that. My first thought was "evil", but I've got that on Linux as well, so I really don't know. But thanks a lot for the feedback, I enjoy helm a lot and it is one of my favourite packages.

**Comment by thierryvolpiatto** [comment]
Dapuva76 <notifications@github.com> writes:

> Ok, I just tried the same situation on my Debian VM, where Emacs has a
> slightly different package setup. Works flawlessly.

Great.

> So it's likely some other package interfering, but I don't know how to
> debug that.

Perhaps try to load one by one the packages ?

> My first thought was "evil", but I've got that on Linux as well, so I
> really don't know.

Yes, normally helm is handling other minor maps in addition of its
bindings.

> But thanks a lot for the feedback, I enjoy helm a lot and it is one of
> my favourite packages.

Thanks.

--
Thierry

**Comment by Dapuva76** [comment]
I just did an upgrade from 25.1 to 25.1-2, and did another package upgrade. Now it works. As I said I upgraded yesterday, so unless there was no package released, maybe something in the upgrade process got futzed and I was using an old version.... although I checked, so... I don't know.
