### ISSUE TITLE
Autocompletion in the file selector doesn't work as expected

### ISSUE THREAD

**Issue by minad** [emacs-helm/helm#1689]
This is an issue I am having in spacemacs. See https://github.com/syl20bnr/spacemacs/issues/8285

## Expected behavior

I have two files alpha and beta. Pressing a and tab selects alpha.

In general I would like a similar autocompletion behaviour as in zsh or bash.

## Actual behavior from emacs-helm.sh if possible

I have two files alpha and beta. Pressing ctrl-x f a and tab/enter selects beta. I found this originally in spacemacs but it also happens in pure helm using your emacs-helm.sh script.

## Steps to reproduce (recipe)

I have two files alpha and beta. Pressing ctrl-x f a and tab/enter selects beta. 

## Backtraces if some (M-x toggle-debug-on-error)

No crash.

## Describe versions of helm, emacs, operating system etc.

emacs 24.4.1, spacemacs 0.200.7

**Comment by thierryvolpiatto** [comment]
Daniel Mendler <notifications@github.com> writes:

> This is an issue I am having in spacemacs. See syl20bnr/spacemacs#8285

I don't look at spacemacs issues.

> Expected behavior
>
> I have to files alpha and beta. Pressing a and tab selects alpha.
         ^^
         two

Don't see what TAB is doing here, but indeed entering "a" makes "beta"
appearing in first position because HFF starts fuzzy matching at second
char entered.
I have installed a change in scoring that fix this.

Thanks.

-- 
Thierry

**Comment by minad** [comment]
Thx for your response! Would it also be possible to disable the scoring algorithm (which seems fragile) and just match on prefix? Or is it possible to configure the scoring without touching helm internals?

**Comment by thierryvolpiatto** [comment]
Daniel Mendler <notifications@github.com> writes:

> Thx for your response! Would it also be possible to disable the
> scoring algorithm

No.

> (which seems fragile)

It is not, it is used here since long time now without any problems.

> and just match on prefix? Or is it possible to configure the scoring
> without touching helm internals?

You can just disable `helm-ff-fuzzy-matching`, but well you loose a nice
feature...

--
Thierry

**Comment by minad** [comment]
Ok, thank you! I will try your fix and the fuzzy setting to see what works for me.
