### ISSUE TITLE
Cursor position spaztastic when Helm is enabled

### ISSUE THREAD

**Issue by moxford** [emacs-helm/helm#1691]
## Expected behavior
Cursor should be steady at the point a user expects.

## Actual behavior from emacs-helm.sh if possible
n/a, emacs-heml.sh doesn't work (Symbol's value as variable is void: async-bytecomp-package-mode)

## Steps to reproduce (recipe)
This is the easiest way:  Fire up a clean emacs with nothing but Helm.  Open Helm (helm-M-x) and type "format" into the search.  Note that at the third character (and always the third character) the cursor warps to the beginning of the line.  Backspace will return the cursor to the end of the line, and typing another character (which is, again, the third) will warp it to the beginning.  As you continue to type, note that it's bouncing around horizontally.

Open up M-x normally (without Helm) and note that the issue does not arise and typing is normal.

Interestingly, this does not appear to only happen when Helm is activated, but if Helm is installed then other cursor issues arise (like ctrl-e not making it all the way to the end of the line.)  I have not been able to pin this one down too well, or find a repro case for it.

## Backtraces if some (M-x toggle-debug-on-error)
No errors seen.

## Describe versions of helm, emacs, operating system etc.
OS: OSX El Capitan, 10.11.5
Emacs : 26.0.50.1 (master) compiled from source
Helm: Master (commit fdc277116bcc57917a17838a388d880f7c7ea83b)

**Comment by moxford** [comment]
Further testing with the GUI client (same build) did NOT show the same issue.
Testing in another Terminal window with the same binary did NOT show the same issue.

It appears to be something with the individual terminal as I can repro it 100% there (including the "emacs without Helm works fine."

Closing ... not a Helm bug but something with the Terminal.

**Comment by thierryvolpiatto** [comment]
moxford <notifications@github.com> writes:

> n/a, emacs-heml.sh doesn't work (Symbol's value as variable is void:
> async-bytecomp-package-mode)

It is working fine, please check your helm installation, if you have
installed from git check if your async package is updated (or just
remove it from your load-path if you don't want to use it).

>
> Steps to reproduce (recipe)
>
> This is the easiest way: Fire up a clean emacs with nothing but
> Helm. Open Helm (helm-M-x) and type "format" into the search. Note
> that at the third character (and always the third character) the
> cursor warps to the beginning of the line. Backspace will return the
> cursor to the end of the line, and typing another character (which is,
> again, the third) will warp it to the beginning. As you continue to
> type, note that it's bouncing around horizontally.

Not reproductible.

--
Thierry
