### ISSUE TITLE
Has helm faces to customize match in buffers such as helm-do-grep-ag?

### ISSUE THREAD

**Issue by 0rdy** [emacs-helm/helm#1693]
I'm working on my own theme for Emacs, but I didn't find a face to customize default yellow background match here:
![1487237019](https://cloud.githubusercontent.com/assets/9018005/23015450/8cb60a36-f43b-11e6-8cfd-b803d7a05a02.png)

The face looks like built-in helm-header-line-left-margin, but this face didn't change background in helm-do-grep-ag.

**Comment by xuchunyang** [comment]
AFAIK the color is produced by ag's `--color` (see `helm-grep-ag-command`), thus to use a different color, set it within ag's command line option.

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

> AFAIK the color is produced by ag's --color (see helm-grep-ag-command)

I confirm colors in all grep command are now produced by backends (grep,
git-grep, ag, rg ...) as ansi sequences and then translated.

> , thus to use a different color, set it within ag's command line
> option.

Don't forget to customize also `helm-grep-ag-pipe-cmd-switches` to have
a color option corresponding to the one set in main command line.

-- 
Thierry

**Comment by 0rdy** [comment]
@xuchunyang, @thierryvolpiatto, thanks for the answers.
