### ISSUE TITLE
helm-mode and completing read

### ISSUE THREAD

**Issue by quicknir** [emacs-helm/helm#1694]
It would be nice if `helm-mode`, when used to do completing reads generically, would enable a persistent action that was the same as the regular action (hitting Enter), just leaving helm open. Right now the persistent action in such cases is a no-op. Is there any easy way to do this at the moment?

**Comment by thierryvolpiatto** [comment]
quicknir <notifications@github.com> writes:

> It would be nice if helm-mode, when used to do completing reads
> generically, would enable a persistent action that was the same as the
> regular action (hitting Enter), just leaving helm open. Right now the
> persistent action in such cases is a no-op. Is there any easy way to
> do this at the moment?

This would lead to problems when a command call a function which use
itself a completing-read too, it is why persistent actions are disabled
there.  So no I will not add persistent actions there.

BTW I have added an entry in both FAQ and helm help about helmized functions
by helm-mode which should NOT have additionals features, right after
this commit people start asking for new features there, perhaps I was not
clear enough ?...

--
Thierry
