### ISSUE TITLE
Helm-M-X - Wrong number of arguments ( 3. 3 ), 2

### ISSUE THREAD

**Issue by schvabodka-man** [emacs-helm/helm#1695]
## Expected behavior
Helm M-x opens helm M-x

## Actual behavior from emacs-helm.sh if possible
Wrong number of arguments ( 3. 3 ), 2

## Steps to reproduce (recipe)
Hi! Just a few days ago this error began to appear. After using helm-m-x  few times i just getting Wrong number of arguments ( 3. 3 ), 2, it seems that there are some errors with helm session

## Backtraces if some (M-x toggle-debug-on-error)
I got "trying to run helm without helm session" signal.

## Describe versions of helm, emacs, operating system etc.
Fedora 25
Emacs 25.1
Helm 2.3.4
My init.el - https://github.com/schvabodka-man/Dotfiles/blob/master/.emacs.d/init.el

**Comment by thierryvolpiatto** [comment]
Ivan <notifications@github.com> writes:

> Expected behavior
>
> Helm M-x opens helm M-x
>
> Actual behavior from emacs-helm.sh if possible
>
> Wrong number of arguments ( 3. 3 ), 2

Probably a bad installation of helm, reinstalling completely should
solve your problem.

-- 
Thierry

**Comment by schvabodka-man** [comment]
Nope, i reinstalled it. Still getting this error

**Comment by thierryvolpiatto** [comment]
Ivan <notifications@github.com> writes:

> Nope, i reinstalled it. Still getting this error

It is not reproductible here with emacs-helm.sh and plain emacs, are you
sure you have not an old helm library somewhere ?
Did you restart emacs after upgrading/reinstalling ?

I hardly see what could be wrong here as no changes have been done
recently in this place.

Can you send a backtrace please ?

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Ivan <notifications@github.com> writes:

> Actual behavior from emacs-helm.sh if possible
>
> Wrong number of arguments ( 3. 3 ), 2

Are you sure you are REALLY starting with ./emacs-helm.sh from your helm
directory ?

> Backtraces if some (M-x toggle-debug-on-error)
>
> I got "trying to run helm without helm session" signal.

What does that mean ?

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Also I have upgraded an old helm installation from Melpa without any problems and helm-M-x is working as expected, i.e no errors.

**Comment by schvabodka-man** [comment]
Ok, with emacs-helm.sh it works pretty nice, but there are weird config and i would prefer to use my init.el and have .desktop file that opens emacs nicely and directly, so emacs-helm.sh isn't choice to go for me

**Comment by michael-heerdegen** [comment]
Ivan <notifications@github.com> writes:

> Ok, with emacs-helm.sh it works pretty nice, but there are weird
> config and i would prefer to use my init.el and have .desktop file
> that opens emacs nicely and directly, so emacs-helm.sh isn't choice to
> go for me

Thierry doesn't want to suggest to use helm.sh for your daily work.  But
if everything works fine with that, it is very likely that there is a
problem with your config.  Your config is not part of Helm and out of
our scope, so you'll need to find a recipe for us to be able to
reproduce your problem if you think you've hit a bug in Helm.

**Comment by thierryvolpiatto** [comment]
Ivan <notifications@github.com> writes:

> Ok, with emacs-helm.sh it works pretty nice, but there are weird
> config and i would prefer to use my init.el and have .desktop file
> that opens emacs nicely and directly, so emacs-helm.sh isn't choice to
> go for me

Using here emacs-helm.sh is just for debugging purpose and prove there
is no bug in helm but in your config. I don't tell you to use this
definitely of course.

Try bisecting your init file to find the culprit, I can't do anything on
helm side as there is no helm bug here.

Also enabling the debugger will help to find what is happening, try to
get a backtrace.

Thanks.

--
Thierry

**Comment by sboosali** [comment]
fwiw, I also get an arity error:

    "helm-interpret-value: Wrong number of arguments: (1 . 1), 0"

on `helm-find-file` with both MELPA and MELPA Stable versions (both Helm 3.0, I think) and Emacs 26.

But, a recently a cloned `./helm/emacs-helm.sh` does work (i.e. `helm-M-x`, `helm-find-files`, etc). So, I'll debug my init, maybe we have the same issue? @schvabodka-man, are you wrapping `helm-find-files` in another command, which would strip out the `(interactive "P")`  that passes in a mandatory argument to `(defun helm-find-files (prefixarg) (interactive "P") ...)`? I had thought this was my issue.

or that it might be incorrect transitive dependency, maybe even `helm-core` being a different version from `helm`. but afaict, they're consistent. `C-h f helm-find-files` shows it to be from `~/.emacs.d/elpa/`, as expected.

@thierryvolpiatto there's no `helm-version`, is there? is hyperlinking to the source file from a helm buffer the best way to double-check which `helm` packages are being used?

**Comment by thierryvolpiatto** [comment]
Spiros Boosalis <notifications@github.com> writes:

> @thierryvolpiatto there's no `helm-version`, is there?

No, the reason is that package.el makes its own helm-pkg.el file and
don't keep the original one, this for compatibility with ELPA, I have
proposed to implement this in the past i.e. Using a *pkg.el file for all
packages even the single file package and use it instead of deleting it
and creating a new one and also reading informations from source files.

So the version you use if installed from MELPA is the MELPA version, see
the badges on the helm github page. 

> is hyperlinking to the source file from a helm buffer the best way to
> double-check which `helm` packages are being used?

Not sure to understand what you mean.

-- 
Thierry

**Comment by sboosali** [comment]
Thanks, that makes sense.
