### ISSUE TITLE
helm-create-helm-buffer fails with "Text is read-only"

### ISSUE THREAD

**Issue by Apakollaps** [emacs-helm/helm#1697]
## Expected behavior
When e.g. `helm-show-kill-ring` is executed, the kill ring is displayed.

## Actual behavior from emacs-helm.sh if possible
Sometimes the command fails with the message "Text is read-only".

## Steps to reproduce (recipe)
I haven't found a way to easily reproduce this, even though it happens quite often. It seems to only occur in the `helm-show-*-ring` functions. After it has happened, I haven't found a way to fix it other than restarting emacs. Closing the buffer for the command, e.g. the `helm kill ring` buffer does not help.

I realize that this is not an ideal bug report, but I have found a workaround, and that is to add `(set (make-local-variable 'inhibit-read-only) t)` after the `(set (make-local-variable 'buffer-read-only) nil)` line in the `helm-create-helm-buffer` function.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: nil (rev. c2774bc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(markdown html python helm auto-completion c-c++ better-defaults emacs-lisp gtags gnus org shell-scripts
          (shell :variables shell-default-height 30 shell-default-position 'bottom)
          spell-checking syntax-checking version-control)
```
- System configuration features: XPM JPEG PNG RSVG SOUND DBUS GCONF NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK2 X11

**Comment by thierryvolpiatto** [comment]
Apakollaps <notifications@github.com> writes:

> Expected behavior
>
> When e.g. helm-show-kill-ring is executed, the kill ring is displayed.
>
> Actual behavior from emacs-helm.sh if possible
>
> Sometimes the command fails with the message "Text is read-only".
>
> Steps to reproduce (recipe)
>
> I haven't found a way to easily reproduce this, even though it happens
> quite often. It seems to only occur in the helm-show-*-ring
> functions. After it has happened, I haven't found a way to fix it
> other than restarting emacs. Closing the buffer for the command,
> e.g. the helm kill ring buffer does not help.
>
> I realize that this is not an ideal bug report, but I have found a
> workaround, and that is to add (set (make-local-variable
> 'inhibit-read-only) t) after the (set (make-local-variable
> 'buffer-read-only) nil) line in the helm-create-helm-buffer function.

This is related to issue #1176.
The problem is that making inhibit-read-only local is not the right fix
(IIRC it is what I did initially to fix this bug but it was wrong). I will
try to fix this soon.

Thanks.

--
Thierry

**Comment by thierryvolpiatto** [comment]
Apakollaps <notifications@github.com> writes:

> I haven't found a way to easily reproduce this,

I guess you are copying text with read-only property.

-- 
Thierry

**Comment by Apakollaps** [comment]
Yes, most likely lines including the prompt from a shell buffer is causing the issue. Thanks for the quick reply.

**Comment by thierryvolpiatto** [comment]
Apakollaps <notifications@github.com> writes:

> I haven't found a way to easily reproduce this,

Here's a recipe:

1) Create a buffer "test"
2) M-: (insert (propertize "foo" 'read-only t)) RET
3) C-RET C-RET
4) M-x helm-all-mark-rings
=> Text is read-only error popup and helm is not starting.

Couldn't reproduce from kill-ring though.

I have commited a fix, seems to work fine, can you confirm ?

Thanks.


-- 
Thierry

**Comment by Apakollaps** [comment]
Couldn't reproduce it with your recipe (or by yanking from a shell buffer). This without the fix applied, so I can't confirm the fix. But it looks like basically the same fix, only in two places and a different way, so it should be fine.

(C-RET is undefined for me both in spacemacs and in emacs -Q)

**Comment by thierryvolpiatto** [comment]
Apakollaps <notifications@github.com> writes:

> Couldn't reproduce it with your recipe (or by yanking from a shell buffer). This without the fix applied, so I can't confirm the fix. But it looks like
> basically the same fix, only in two places and a different way, so it should be fine.
>
> (C-RET is undefined for me both in spacemacs and in emacs -Q)

Sorry I meant C-SPC.

-- 
Thierry

**Comment by Apakollaps** [comment]
That's what I tried, weird. Will try again.

**Comment by Apakollaps** [comment]
Followed the recipe exactly, and without the fix applied it still works. Very strange. Anyway, I think the fix is good, so I think we'll have to leave it unconfirmed as of now...

**Comment by thierryvolpiatto** [comment]
Apakollaps <notifications@github.com> writes:

> Followed the recipe exactly, and without the fix applied it still
> works. Very strange. Anyway, I think the fix is good, so I think we'll
> have to leave it unconfirmed as of now...

Ok, I will leave this open in case someone else can reproduce.

Thanks.

--
Thierry

**Comment by Apakollaps** [comment]
The browser window wasn't updated, reopening...

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> I have commited a fix, seems to work fine, can you confirm ?

Wouldn't it be cleaner to remove the read-only property, e.g. in
`helm-global-mark-ring-format-buffer'?  The property shouldn't land in
any Helm buffer at all, this cries for problems we don't foresee.  It
isn't very useful there anyway.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Thierry Volpiatto <notifications@github.com> writes:
>
>> I have commited a fix, seems to work fine, can you confirm ?
>
> Wouldn't it be cleaner to remove the read-only property, e.g. in
> `helm-global-mark-ring-format-buffer'?

Seems the problem doesn't appear only in mark-ring but elsewhere as well
(couldn't reproduce though elsewhere than mark-ring).
This wouldn't arm removing the property in mark-ring though.

I don't see why it is not clean let-binding `inhibit-read-only`.

> The property shouldn't land in any Helm buffer at all,

It is however, at least it can be.

> this cries for problems we don't foresee. It isn't very useful there
> anyway.

What isn't useful and where ?

-- 
Thierry

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> I don't see why it is not clean let-binding `inhibit-read-only`.

It is more sort of a workaround, so you have to keep in mind that this
problem exists when writing future code.  If your solution is what you
think is best, then let's go with that.  I just wanted to mention a
possible alternative.

> > this cries for problems we don't foresee. It isn't very useful there
> > anyway.
>
> What isn't useful and where ?

Read-only parts in candidates and Helm buffers have no use.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Thierry Volpiatto <notifications@github.com> writes:
>
>> I don't see why it is not clean let-binding `inhibit-read-only`.
>
> It is more sort of a workaround, so you have to keep in mind that this
> problem exists when writing future code.

When writing future code the insertion of such text will be always
possible, OTH I hardly see how removing read-only prop in mark-ring will
allow handling future code with read-only property elsewhere.

> If your solution is what you think is best, then let's go with that.

I think it's good yes, at least I have no better idea for now, if you
have some let me know or provide a PR.

> I just wanted to mention a possible alternative.

Your solution is good and I agree with you that we have to remove the
read-only prop in mark-ring but this is not a global solution.

>> > this cries for problems we don't foresee. It isn't very useful there
>> > anyway.
>>
>> What isn't useful and where ?
>
> Read-only parts in candidates and Helm buffers have no use.

For our actual case yes, but like any other properties they could give
a clue on one candidate (I have no example to give, but I imagine it may
happen).

-- 
Thierry

**Comment by Apakollaps** [comment]
It would seem that the fix doesn't solve my original problem. I believe I got the code when updating spacemacs. I have two lines with `remove-text-properties` in `helm-ring.el`. After the update I got the "Text is read only" message again (while running `helm-show-kill-ring`), and the workaround of adding `(set (make-local-variable 'inhibit-read-only) t)` to `helm-create-helm-buffer` fixed it.

**Comment by thierryvolpiatto** [comment]
I still can't reproduce.
I tried inserting text with read-only in some buffer, copy it, and open helm-show-kill-ring, worked as expected.
Please try to reproduce from emacs-helm.sh, spacemacs is not suitable to reproduce bugs.

**Comment by Apakollaps** [comment]
Fair enough, I'll try to do that.

**Comment by Apakollaps** [comment]
I haven't seen this issue since, so from my point of view this fix is confirmed. Thanks a lot!

**Comment by thierryvolpiatto** [comment]
Apakollaps <notifications@github.com> writes:

> I haven't seen this issue since, so from my point of view this fix is confirmed. Thanks a lot!

Thanks to confirm it is fixed.

-- 
Thierry
