### ISSUE TITLE
Can't get fallback source to work, is this a bug or user error?

### ISSUE THREAD

**Issue by cwittern** [emacs-helm/helm#1698]
## Expected behavior

I am trying to create a source with fallback, as described at various places, for example here:
http://wikemacs.org/wiki/How_to_write_helm_extensions#Actions_when_there_is_no_match
So I expect to see a buffer with candidates and a fallback option
## Actual behavior from emacs-helm.sh if possible
Even with emacs-helm.sh, only the helm candidates are shown, no fallback

## Steps to reproduce (recipe)
After emacs starts with emacs-helm.sh, I paste the following in the scratch-buffer and evaluate:

(defun some-action (arg)
  (message-box "%s\n%s"
    (helm-get-selection)
    (helm-marked-candidates)))

(defun default-action (candidate)
  (browse-url
   (format
    "http://www.google.com/search?q=%s" (url-hexify-string helm-pattern))))

(defvar source1 '((name . "HELM")
                  (candidates . (1 2 3 4))
                  (action . (("open" . some-action)))))

(defvar fallback-source '((name . "fallback")
                          (dummy)
                          (action . (("Google" . default-action)))))

(helm :sources '(source1 fallback-source))

## Describe versions of helm, emacs, operating system etc.
ubuntu 16.04
emacs 24.5.1
helm-20170131.2356

**Comment by thierryvolpiatto** [comment]
cwittern <notifications@github.com> writes:

> Expected behavior
>
> I am trying to create a source with fallback, as described at various places, for example here:
> http://wikemacs.org/wiki/How_to_write_helm_extensions#Actions_when_there_is_no_match

This describe the old way of defining sources, it is still possible like
this, but it is much more easier to use the new way to make source, see
https://github.com/emacs-helm/helm/wiki/Developing

Note that if you read the org help embeded with helm (c-h m from helm
session) you will find basic examples and link to wiki.

Here something to start with:

    (defun helm/test-default-action (candidate)
      (browse-url (format
                   "http://www.google.com/search?q=%s"
                   (url-hexify-string candidate))))

    (helm :sources (helm-build-dummy-source "test"
                     :action '(("Google" . helm/test-default-action)))
          :buffer "*helm test*")

-- 
Thierry

**Comment by cwittern** [comment]
Thank you for your suggestion.  I see that this will work. 
I did in fact look at the page you mention, but that page does not mention anything about fallback actions, so I did not realize this is possible.

**Comment by thierryvolpiatto** [comment]
cwittern <notifications@github.com> writes:

> Thank you for your suggestion. I see that this will work.
> I did in fact look at the page you mention, but that page does not
> mention anything about fallback actions, so I did not realize this is
> possible.

I have just updated the wiki with your example, before it was refering
to dummy sources, but without examples, now there is an example.
https://github.com/emacs-helm/helm/wiki/Developing#helm-source-dummy

Thanks.

--
Thierry
