### ISSUE TITLE
Looking to create a small tool using helm

### ISSUE THREAD

**Issue by kovek** [emacs-helm/helm#1699]
Hi helm contributors! Thank you for your work on helm, it's a pretty nice tool. 

I am looking to write a small function that would show me many commands I can run (which would be the helm buffer) in one window, and another window showing the description of the commands. Almost exactly the way helm-M-x already works! 👍  Two nits are that it would be nice to be able to specify what helm does on C-z, and also to run persistent-action automatically when the option is selected. 

Instead of having helm-M-x show me the available elisp commands and their descriptions, I would like to provide my own list of tuples of (:command-name "name" :persistent-action 'show-implementation) .

N/A:
## Expected behavior
An easy way to specify what will persistent-action do

## Actual behavior from emacs-helm.sh if possible
(helm ...) does not allow to specify what persistent-action will do for a selction

## Steps to reproduce (recipe)
M-x helm-M-x, and select an option and hit C-z. What if instead of the description, you could see the implementation of the function? How would you specify this?

## Backtraces if some (M-x toggle-debug-on-error)
N/A

## Describe versions of helm, emacs, operating system etc.
N/A

**Comment by thierryvolpiatto** [comment]
Kevin Galkov <notifications@github.com> writes:

> An easy way to specify what will persistent-action do

The way to specify persistent-action is to use the slot
`:persistent-action ` to specify the function helm will run when using
C-j or C-z. If you don't specify this helm will run the first action of
the action list as persistent action.
But of course you can specify additional persistent actions, of course
they will be bound to other keys than C-j/z.
Here how to do:

    (defun helm-foo-persistent-action ()
      "Bind a new persistent action 'foo-action to foo function.
    foo function is an action function called with one arg candidate."
      (interactive)
      (with-helm-alive-p
        ;; never split means to not split the helm window when executing
        ;; this persistent action. If your source is using full frame you
        ;; will want your helm buffer to split to display a buffer for the
        ;; persistent action (if it needs one to display something).
        (helm-attrset 'foo-action '(foo . never-split))
        (helm-execute-persistent-action 'foo-action)))

Then you bind your new persistent action to something else than C-j/z
and you are done.


--
Thierry

**Comment by thierryvolpiatto** [comment]
I added this to wiki:

https://github.com/emacs-helm/helm/wiki/Developing#writing-persistent-actions

-- 
Thierry
