### ISSUE TITLE
helm-for-files stat()s every local file in recentf

### ISSUE THREAD

**Issue by CyberShadow** [emacs-helm/helm#1701]
It seems that any time `helm-for-files` is invoked, it will invoke `file-attributes` for every file in the current directory and `recentf`. This causes some problems:

- If `recentf-max-saved-items` is large, Helm will still `stat` every item in it every time it is invoked, even if it will show a small subset of them.
- If some files reside on a mounted remote filesystem, the Helm invocation will be slow or even cause Emacs to hang, merely by being invoked, as `file-remote-p` can't tell whether a mounted filesystem is a network one.

Some ways in which this could be improved:

- Highlight file names asynchronously
- Only call `helm-highlight-files` for files that are immediately visible
- Cache the result of `helm-highlight-files` on a per-filename basis in a hashmap

For now, my workaround is to stub out `helm-highlight-files`:

```lisp
(defun helm-highlight-files (files)
  files)
```

This made `helm-for-files` instant again.

**Comment by CyberShadow** [comment]
It doesn't look like it. That one deals with TRAMP, this one deals with local paths.

**Comment by thierryvolpiatto** [comment]
Vladimir Panteleev <notifications@github.com> writes:

> It doesn't look like it. That one deals with TRAMP, this one deals
> with local paths.

Ok, please try the last changes and let me know if it is better
(highlight_files branch).

--
Thierry

**Comment by thierryvolpiatto** [comment]
Vladimir Panteleev <notifications@github.com> writes:

> It seems that any time helm-for-files is invoked, it will invoke file-attributes for every file in the current directory and recentf. This causes some problems:
>
>   * If recentf-max-saved-items is large, Helm will still stat every
>   item in it every time it is invoked, even if it will show a small
>   subset of them.

#1702 should fix this (use a moderate value for helm-candidate-number-limit).

>   * If some files reside on a mounted remote filesystem, the Helm
>   invocation will be slow or even cause Emacs to hang, merely by being
>   invoked, as file-remote-p can't tell whether a mounted filesystem is
>   a network one.

This is a good point and need to be fixed, I guess you are using sshfs,
what is your typical usage of it?

--
Thierry

**Comment by CyberShadow** [comment]
> This is a good point and need to be fixed, I guess you are using sshfs, what is your typical usage of it?

I use sshfs (to remote servers and to my phone) and cifs (to my Windows VM). If I disconnect my phone or my Windows VM hangs, `stat` on files under those paths will hang (in an uninterruptible syscall, so even `pkill -9 emacs` has no effect).

I will try your changes soon, thanks!

**Comment by thierryvolpiatto** [comment]
Adding "Fix Issue" to PR title close automatically issue, fill free to reopen if not fully fixed.

Thanks.
