### ISSUE TITLE
helm selection moving upside down.

### ISSUE THREAD

**Issue by introom** [emacs-helm/helm#1703]
For example, in this screen recording:

https://vimeo.com/207223333

When typing "sp spsp ...", the highlighted line will moving *meaningless*ly.

The desired effect is:
Always the first line stays highlighted.

It seems, *in the end*,  helm will always place the best result as the first line and highlight, the interim moving and highlighting is really disturbing.

**Comment by michael-heerdegen** [comment]
"Shiyao.Ma" <notifications@github.com> writes:

> For example, in this screen recording:
>
> https://vimeo.com/207223333
>
> When typing "sp spsp ...", the highlighted line will moving meaninglessly.

I saw that too, from time to time.  AFAICT this happens only when
"something went wrong".  I don't know what the cause is, however.  Most
of the time, restarting helps.

Do you have a recipe to reproduce this behavior?

**Comment by introom** [comment]
The context of the vimeo video is:

In a linux kernel source directory, invoking helm-gtags, search a tag by typing "sp spsp..." *rather fast*.

It seems to me, as long as you type more quickly than helm can handle, the problem will reproduce.

**Comment by thierryvolpiatto** [comment]
Shiyao.Ma <notifications@github.com> writes:

> For example, in this screen recording:
>
> https://vimeo.com/207223333
>
> When typing "sp spsp ...", the highlighted line will moving meaninglessly.
>
> The desired effect is:
> Always the first line stays highlighted.
>
> It seems, in the end, helm will always place the best result as the
> first line and highlight, the interim moving and highlighting is
> really disturbing.

I don't use helm-gtags and it is not part of helm, but I see it is using
fuzzy-matching which seems broken in etags, do you see the same behavior
with fuzzy disabled ?

--
Thierry

**Comment by thierryvolpiatto** [comment]
Thierry Volpiatto <thierry.volpiatto@gmail.com> writes:

> I don't use helm-gtags and it is not part of helm, but I see it is using
> fuzzy-matching which seems broken in etags,

It is not finally, I was using a very old TAG file, it is working as
expected with both 'all and 'tag for helm-etags-match-part-only and
fuzzy enabled.

-- 
Thierry

**Comment by introom** [comment]
It's about the speed you type vs the amount of calculation helm must handle.

This problem also occurs in helm-projectile, too.

Say, inside the linux kernel source directory, invoke helm-projectile, type *rather, rather* quick the input "sp".  You will notice the moving updown of the highlighted selection.   But be sure to check you are not on a super fast computer or your typing speed is fast enough.

**Comment by thierryvolpiatto** [comment]
Shiyao.Ma <notifications@github.com> writes:

> It's about the speed you type vs the amount of calculation helm must handle.
>
> This problem also occurs in helm-projectile, too.
>
> Say, inside the linux kernel source directory, invoke helm-projectile,
> type rather, rather quick the input "sp". You will notice the moving
> updown of the highlighted selection. But be sure to check you are not
> on a super fast computer or your typing speed is fast enough.

I don't use projectile and helm-projectile.

I guess this is a problem of implementation of these sources.
Perhaps helm-gtags should use other filters or even better be async, and
helm-projectile Hmm, don't know what it tries to do..., maybe try instead
helm-ls-git if you work on git.
Perhaps you have better time to report to their respectives authors as
these packages i.e helm-gtags and helm-projectile are not part of emacs-helm.

--
Thierry

**Comment by introom** [comment]
I don't think this is unrelated to the way helm works, though I do not now about how helm works.

Conceptually, the ultimate selection/highlight of the entry should be an implementation of helm, not the helm plugins.  The plugin only tells helm the whole candidates, and what to select as the best match.  It shouldn't interfere with the rest on how helm highlights/selects the best candidate.

The behavior of moving up and down, thus, is seemingly a logic flaw of helm.   

Regards.

**Comment by thierryvolpiatto** [comment]
Hard to reproduce and make a recipe, but this is reproductible with multiple sources like helm-imenu-all.

**Comment by thierryvolpiatto** [comment]
Can you reproduce with Fix_1703 branch ?

**Comment by introom** [comment]
fix_1703 seems have fixed it.

**Comment by thierryvolpiatto** [comment]
Shiyao.Ma <notifications@github.com> writes:

> fix_1703 seems have fixed it.

Thanks to confirm, merging now.

-- 
Thierry
