### ISSUE TITLE
`helm-imenu-in-all-buffers` should have each buffer as separate source

### ISSUE THREAD

**Issue by xiongtx** [emacs-helm/helm#1705]
## Expected behavior

`helm-imenu-in-all-buffers` should have symbols from each buffer under a separate source, preferably with indication of the buffer's major mode.

## Actual behavior from emacs-helm.sh if possible

All symbols from all buffers are in a single source, with no indication as to where each came from.

E.g. the following symbols came from 3 buffers: 2 `enh-ruby-mode`, 1 `js-mode`. This is not at all clear.

![helm-imenu-same-source](https://cloud.githubusercontent.com/assets/1624090/23698967/52dae84c-03a2-11e7-99a4-f564625f9c14.png)

## Steps to reproduce (recipe)

Call `helm-imenu-in-all-buffers` with multiple buffers in the same major mode.

## Backtraces if some (M-x toggle-debug-on-error)

N/A

## Describe versions of helm, emacs, operating system etc.

- Helm: `2.5.1`
- Emacs: `25.1.1`
- OS: `Fedora 24`

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:


> All symbols from all buffers are in a single source, with no
> indication as to where each came from.
>
> E.g. the following symbols came from 3 buffers: 2 enh-ruby-mode, 1
> js-mode. This is not at all clear.

You can use helm-popup-tip-mode.

--
Thierry

**Comment by thierryvolpiatto** [comment]
![popup-tip-mode](https://cloud.githubusercontent.com/assets/1533939/23702874/7a57fea4-03fd-11e7-9f6a-bb47d18d11d0.png)

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> Expected behavior
>
> helm-imenu-in-all-buffers should have symbols from each buffer under a
> separate source,

This have been addressed now, let me know if you are happy with this.

> preferably with indication of the buffer's major mode.

For this one it is easy to fix now, though I am still unsure how to
present it.

-- 
Thierry

**Comment by xiongtx** [comment]
:+1: LGTM.
