### ISSUE TITLE
`helm-imenu-in-all-buffers` does'nt work with semantic imenu indexes

### ISSUE THREAD

**Issue by muahah** [emacs-helm/helm#1706]
## Expected behavior
`helm-imenu-candidates-in-all-buffers` works everywhere.

## Actual behavior from emacs-helm.sh if possible
With semantic activated, `imenu-create-index-function` is set to `semantic-create-imenu-index` for some mode (python-mode at least).
In this configuration, `helm-imenu-in-all-buffers` throws an error : 
```
In ‘Imenu in all buffers’ source: ‘helm-imenu-candidates-in-all-buffers’ 
 (wrong-type-argument integer-or-marker-p #<overlay from 143 to 2439 in file.py>)
```

## Steps to reproduce (recipe)
- Launch emacs-helm.sh
- Open a python script with `python-mode`
- Activate `semantic-mode`
- Call `helm-imenu-in-all-buffers`

## Backtraces if some (M-x toggle-debug-on-error)
Helm discards the backtrace buffer as soon as I touch a key, but the error happen in `helm-imenu--candidates-1` line 211 : `(setcdr elm (copy-marker (cdr elm))) ; Same as [1].`
The problem being that the cdr of elm is an overlay and is expected to be a marker.

## Proposed solutions
- `helm-imenu--candidates-1` can be enhanced to handle `elm` containing overlays.
- `semantic-create-imenu-index` can be modified to return markers instead of overlays.

## Describe versions of helm, emacs, operating system etc.
OS : Manjaro
emacs : 25.1.1
helm-core : 2.5.3

**Comment by thierryvolpiatto** [comment]
muahah <notifications@github.com> writes:

> In ‘Imenu in all buffers’ source: ‘helm-imenu-candidates-in-all-buffers’
> (wrong-type-argument integer-or-marker-p #<overlay from 143 to 2439 in file.py>)

Should be fixed now, please confirm.

> Helm discards the backtrace buffer as soon as I touch a key,

Many people reported this but I never been able to reproduce it, I am
curious to know what is causing this behavior.

Thanks for the clear bug report.

--
Thierry

**Comment by muahah** [comment]
Nicely working, I close the issue.
Thanks.

Regarding the disappearing backtrace, you were not able to reproduce it with `emacs-helm.sh` in the previous configuration ?

**Comment by thierryvolpiatto** [comment]
muahah <notifications@github.com> writes:

> Regarding the disappearing backtrace, you were not able to reproduce
> it with emacs-helm.sh in the previous configuration ?

Yes.

--
Thierry
