### ISSUE TITLE
`helm-imenu` results are too cluttered

### ISSUE THREAD

**Issue by xiongtx** [emacs-helm/helm#1708]
## Expected behavior

`helm-imenu` candidates like `t1`, `v1`, and `f1` should not be prefixed with `Type`, `Variable`, or `Function` respectively.

Instead, only the symbol names should be displayed:

```
t1
v1
f1
```

They should be differentiated by giving `t1` `Type`'s face, `v1` `Variable`'s face, etc.

## Actual behavior from emacs-helm.sh if possible

`helm-imenu` results are of the form:

```
Type / t1
Variable / v1
Function / f1
```

This clutters up the results and makes regexp matching difficult. For example, using a simple `^` to match against a symbol doesn't work because the candidate begins with `Type`, `Variable`, or `Function`.

## Steps to reproduce (recipe)

Call `helm-imenu`

## Backtraces if some (M-x toggle-debug-on-error)

N/A

## Describe versions of helm, emacs, operating system etc.

- Helm: `2.5.1`
- Emacs: `25.1.50.1`
- OS: `Darwin C02RW05YFVH6 15.6.0`

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> Expected behavior
>
> helm-imenu candidates like t1, v1, and f1 should not be prefixed with
> Type, Variable, or Function respectively.

This is true for elisp but not other languages where hierarchy is
displayed when semantic is enabled, e.g:

Class / Foo / *definition*
Class / Foo / __init__
etc...

-- 
Thierry

**Comment by xiongtx** [comment]
Interesting...I wonder if we can have the best of both worlds.
