### ISSUE TITLE
helm-locate on osx

### ISSUE THREAD

**Issue by mclearc** [emacs-helm/helm#1711]
## Expected behavior
Search using mdfind and helm-locate. I expect helm-locate to update the minibuffer as I type. This is how it works, for example, in spacemacs. 

## Actual behavior from emacs-helm.sh if possible

Using the following configuration, helm-locate works, but there is about a 2 second lag between when the search terms are input and the results show. This lag is only present in helm-locate (not, e.g. in helm-ag or helm-swoop). It is definitely something wrong with my config, as helm-locate works as expected in spacemacs on the same machine. 

## Steps to reproduce (recipe)
Here's my config:

```emacs-lisp
  (use-package helm
    :diminish (helm-mode . "")
    :defer 1
    :init
    (setq helm-locate-fuzzy-match nil
          helm-locate-command "mdfind -interpret -name %s %s")
    :config
    (progn
      ;; Use helm to provide :ls, unless ibuffer is used
      (evil-ex-define-cmd "buffers" 'helm-buffers-list)
      (setq helm-M-x-fuzzy-match t  ;; Use fuzzy match in helm
            helm-apropos-fuzzy-match t
            helm-buffers-fuzzy-matching t
            helm-imenu-fuzzy-match t
            helm-recentf-fuzzy-match t
            helm-prevent-escaping-from-minibuffer t
            helm-bookmark-show-location t
            helm-ff-file-name-history-use-recentf t
            helm-find-files-sort-directories t
            helm-display-header-line nil
            helm-move-to-line-cycle-in-source t
            helm-always-two-windows t                       
            helm-split-window-in-side-p nil
            ;; helm-split-window-default-side 'other
            helm-echo-input-in-header-line t)
      ;;keybindings
      (general-define-key "M-x" 'helm-M-x)
      ;;; helm vim-bindings in buffer ;;
      (define-key helm-map (kbd "C-j") 'helm-next-line)
      (define-key helm-map (kbd "C-k") 'helm-previous-line)
      (define-key helm-map (kbd "C-h") 'helm-next-source)
      (define-key helm-map (kbd "C-S-h") 'describe-key)
      (define-key helm-map (kbd "C-l") (kbd "RET"))
      (general-define-key :keymaps 'helm-map 
        "TAB"  'helm-execute-persistent-action ; rebind tab to do persistent action
        "C-i"    'helm-execute-persistent-action ; make TAB works in terminal
        "C-z"    'helm-select-action ; list actions using C-z
        )
      (setq helm-boring-buffer-regexp-list '("\\*SPEEDBAR" "\\*magit" "\\*Sunshine" "\\*Help" "\\*Shell Command Output" "\\*Flycheck error message" "\\*Compile-Log" "\\` " "\\*helm" "\\*helm-mode" "\\*Echo Area" "\\*Minibuf"))
      (helm-autoresize-mode 1)
      (setq helm-autoresize-max-height 40)
      (setq helm-autoresize-min-height 35)
      (helm-mode 1)
      ))

```

I've done the normal bisecting but haven't gotten anywhere and wondered whether I was missing something obvious.

## Describe versions of helm, emacs, operating system etc.
I'm using OSX Sierra, emacs 25.2.2, and the most recent package of helm.

**Comment by thierryvolpiatto** [comment]
Colin McLear <notifications@github.com> writes:

> Actual behavior from emacs-helm.sh if possible
>
> Using the following configuration, helm-locate works, but there is
> about a 2 second lag between when the search terms are input and the
> results show. This lag is only present in helm-locate (not, e.g. in
> helm-ag or helm-swoop). It is definitely something wrong with my
> config, as helm-locate works as expected in spacemacs on the same
> machine.

So IIUC when using mdfind as locate command and the spacemacs
configuration, you have not the 2s lag and when starting emacs with your
own configuration below the 2s lag is present before helm buffer is
updated, right ?

Try to start from ./emacs-helm.sh and add just this part of your config
from the scratch buffer:

    (setq helm-locate-fuzzy-match nil
          helm-locate-command "mdfind -interpret -name %s %s")

Is it working correctly ?

If yes try now to eval:

    (setq helm-echo-input-in-header-line t)

Try again locate.

If it works try now:

M-x helm-autoresize-mode
(which is not recommended with helm-echo-input-in-header-line).

If it works try then to start evil and see what happen.

Otherwise I see nothing obviously wrong in your config, however I can't
try the mdfind command as I have no access to an OSX machine.

To enable helm-echo-input-in-header-line I use this config:

https://github.com/thierryvolpiatto/emacs-tv-config/blob/master/init-helm-thierry.el#L49

> Steps to reproduce (recipe)
>
> Here's my config:
>
>   (use-package helm
>     :diminish (helm-mode . "")
>     :defer 1
>     :init
>     (setq helm-locate-fuzzy-match nil
>           helm-locate-command "mdfind -interpret -name %s %s")
>     :config
>     (progn
>       ;; Use helm to provide :ls, unless ibuffer is used
>       (evil-ex-define-cmd "buffers" 'helm-buffers-list)
>       (setq helm-M-x-fuzzy-match t  ;; Use fuzzy match in helm
>             helm-apropos-fuzzy-match t
>             helm-buffers-fuzzy-matching t
>             helm-imenu-fuzzy-match t
>             helm-recentf-fuzzy-match t
>             helm-prevent-escaping-from-minibuffer t
>             helm-bookmark-show-location t
>             helm-ff-file-name-history-use-recentf t
>             helm-find-files-sort-directories t
>             helm-display-header-line nil
>             helm-move-to-line-cycle-in-source t
>             helm-always-two-windows t
>             helm-split-window-in-side-p nil
>             ;; helm-split-window-default-side 'other
>             helm-echo-input-in-header-line t)
>       ;;keybindings
>       (general-define-key "M-x" 'helm-M-x)
>       ;;; helm vim-bindings in buffer ;;
>       (define-key helm-map (kbd "C-j") 'helm-next-line)
>       (define-key helm-map (kbd "C-k") 'helm-previous-line)
>       (define-key helm-map (kbd "C-h") 'helm-next-source)
>       (define-key helm-map (kbd "C-S-h") 'describe-key)
>       (define-key helm-map (kbd "C-l") (kbd "RET"))
>       (general-define-key :keymaps 'helm-map
>         "TAB"  'helm-execute-persistent-action ; rebind tab to do persistent action
>         "C-i"    'helm-execute-persistent-action ; make TAB works in terminal
>         "C-z"    'helm-select-action ; list actions using C-z
>         )
>       (setq helm-boring-buffer-regexp-list '("\\*SPEEDBAR" "\\*magit" "\\*Sunshine" "\\*Help" "\\*Shell Command Output" "\\*Flycheck error message" "\\*Compile-Log" "\\` " "\\*helm" "\\*helm-mode" "\\*Echo Area" "\\*Minibuf"))
>       (helm-autoresize-mode 1)
>       (setq helm-autoresize-max-height 40)
>       (setq helm-autoresize-min-height 35)
>       (helm-mode 1)
>       ))
>
> I've done the normal bisecting but haven't gotten anywhere and wondered whether I was missing something obvious.
>
> Describe versions of helm, emacs, operating system etc.
>
> I'm using OSX Sierra, emacs 25.2.2, and the most recent package of helm.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.*


--
Thierry

**Comment by mclearc** [comment]
Thanks very much - emacs-helm.sh is super useful! I finally narrowed it down to an unrelated setting for bash aliases `(setq shell-command-switch "-ic")`, which seems to have been the culprit. Apologies for the noise!
