### ISSUE TITLE
helm-comp-read strips backslashes

### ISSUE THREAD

**Issue by glynnforrest** [emacs-helm/helm#1712]
Thank you for all the work you do with helm!

After updating to a new version of helm, `helm-comp-read` has started to ignore backslashes. I've tried escaping the backslashes, but they are always removed.

## Expected behavior

Backslashes are visible in the helm candidates.

## Actual behavior from emacs-helm.sh if possible

No backslashes are present in the candidates list.

## Steps to reproduce (recipe)

* Start emacs-helm.sh
* Eval ` (helm-comp-read "choose " '("foo" "foo\bar" "foo\\baz" "foo\\\\quo" "foo\\\\\\\\zed"))`

## Backtraces if some (M-x toggle-debug-on-error)

None

## Describe versions of helm, emacs, operating system etc.

Helm: 20170310.2335
Emacs: GNU Emacs 25.1.1 (x86_64-apple-darwin16.1.0) of 2016-10-30
OS: MacOS Sierra

Old versions where it worked correctly:
Helm: 20170127.245
Emacs: Not sure of the version, but 24.*

**Comment by thierryvolpiatto** [comment]
Glynn Forrest <notifications@github.com> writes:

> Thank you for all the work you do with helm!
>
> After updating to a new version of helm, helm-comp-read has started to
> ignore backslashes.

Should be fixed by reverting a5d73ab2, thanks.

--
Thierry

**Comment by glynnforrest** [comment]
Excellent, it's fixed now. Thanks for your quick response!
