### ISSUE TITLE
grep in a dirctory shows duplicate results

### ISSUE THREAD

**Issue by maindoor** [emacs-helm/helm#1714]
## Expected behavior

There are a bunch of el files in a directory. 
name1.el name2.el name3.el, name4.el and a directory called "pkgs" with some 
more el files.
name3.el contains a string say "helm-imenu". 
If I select all the files + dir to grep for "helm-imenu" by first typing in 
by M-a and and then start a grep (C-s). It shows "helm-imenu" in name3.el exactly 10 times.
Expectation is that it should show "helm-imenu" exactly once.

## Steps to reproduce (recipe)
Highlighted in Expected behavior

## Describe versions of helm, emacs, operating system etc.
helm version 20170216.738 installed from melpa
emacs version 24.5.1
Operating System Kubuntu 16.04

helm config:
(require 'helm)
(require 'helm-config)

(setq helm-split-window-in-side-p           t ; open helm buffer inside current window, not occupy whole other window
      helm-move-to-line-cycle-in-source     t ; move to end or beginning of source when reaching top or bottom of source.
      helm-ff-search-library-in-sexp        t ; search for library in `require' and `declare-function' sexp.
      helm-scroll-amount                    8 ; scroll 8 lines other window using M-<next>/M-<prior>
      helm-ff-file-name-history-use-recentf t
      helm-echo-input-in-header-line t
      helm-mode-fuzzy-match        t
      helm-buffers-fuzzy-matching  t
      helm-recentf-fuzzy-match     t
      helm-M-x-fuzzy-match t
      helm-highlight-matches-around-point-max-lines 50)

(setq helm-autoresize-max-height 0)
(setq helm-autoresize-min-height 20)
(helm-autoresize-mode 1)

(helm-mode 1)

**Comment by thierryvolpiatto** [comment]
maindoor <notifications@github.com> writes:

> Expected behavior
>
> There are a bunch of el files in a directory.
> name1.el name2.el name3.el, name4.el and a directory called "pkgs" with some
> more el files.
> name3.el contains a string say "helm-imenu".
> If I select all the files + dir to grep for "helm-imenu" by first typing in
> by M-a and and then start a grep (C-s). It shows "helm-imenu" in name3.el exactly 10 times.
> Expectation is that it should show "helm-imenu" exactly once.

Not reproductible with the exact same recipe from emacs-helm.sh.
(Tried with both grep and ack-grep as backend)

-- 
Thierry

**Comment by maindoor** [comment]
Sorry, I may have missed a crucial step in recreating the issue. The right order to grep is:
M-a -> C-u -> C-s to see the issue.
I am able to recreate the issue with emacs-helm.sh. If you still can't see the issue, let me know,
I will record it using a screencapture utility and upload it somewhere.

**Comment by thierryvolpiatto** [comment]
maindoor <notifications@github.com> writes:

> Sorry, I may have missed a crucial step in recreating the issue. The
> right order to grep is: M-a -> C-u -> C-s to see the issue.  I am able
> to recreate the issue with emacs-helm.sh.

Thanks, could reproduce with this recipe, I made a quick fix (will
probably make something better later).
Should work now.

--
Thierry

**Comment by maindoor** [comment]
works now. Please close this bug.
