### ISSUE TITLE
Having names of all helm-buffer starting with a space?

### ISSUE THREAD

**Issue by xuchunyang** [emacs-helm/helm#1715]
Emacs thinks buffer name starting with a spece is "uninteresting" to the user, can helm follow the convention?

> Buffers that are ephemeral and generally uninteresting to the user
> have names starting with a space, so that the ‘list-buffers’ and
> ‘buffer-menu’ commands don’t mention them (but if such a buffer visits a
> file, it *is* mentioned).

I mainly use helm to swtich between buffers but I still want "Buffers" from the menu bar (or see the following picture) and ibuffer don't show helm's internal buffers out of the box.

![screen shot 2017-03-19 at 2 33 51 pm](https://cloud.githubusercontent.com/assets/4550353/24078806/e0fe53c0-0cb2-11e7-944f-1f554f2445af.png)

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

> Emacs thinks buffer name starting with a spece is "uninteresting" to
> the user, can helm follow the convention?

IIRC this have been already discussed, I don't remember exactly the
details but there was an issue in some places changing this.

>
>     Buffers that are ephemeral and generally uninteresting to the user
>     have names starting with a space, so that the ‘list-buffers’ and
>     ‘buffer-menu’ commands don’t mention them (but if such a buffer visits a
>     file, it is mentioned).
>
> I mainly use helm to swtich between buffers

What about using `C-c a` to see such buffers ?

> but I still want "Buffers" from the menu bar (or see the following
> picture) and ibuffer don't show helm's internal buffers out of the
> box.
>
> screen s
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.*


--
Thierry

**Comment by thierryvolpiatto** [comment]
See Issue #1398

-- 
Thierry

**Comment by xuchunyang** [comment]
> IIRC this have been already discussed, I don't remember exactly the
> details but there was an issue in some places changing this.

I think you described the issue at https://github.com/emacs-helm/helm/issues/1398#issuecomment-188087168. But I installed the following patch (almost the same as your 69bc4ac70c15187adba8f2ce6966c366a3661610) and use helm (such as helm-find-files, helm-M-x, helm-mini, helm-resume and helm-list-elisp-packages-no-fetch) for a few times without noticing any problem. I will report if something is broken.

``` diff
diff --git a/helm.el b/helm.el
index 3a4adfb3..691b6fc1 100644
--- a/helm.el
+++ b/helm.el
@@ -2027,6 +2027,8 @@ ANY-KEYMAP ANY-DEFAULT ANY-HISTORY See `helm'."
                    helm-in-persistent-action
                    helm-quit
                    (helm-buffer (or any-buffer helm-buffer)))
+               (unless (string-match-p "\\` " helm-buffer)
+                 (setq helm-buffer (concat " " helm-buffer)))
                (helm-initialize
                 any-resume any-input any-default any-sources)
                (helm-display-buffer helm-buffer)
```

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

> I think you described the issue at #1398 (comment). But I installed
> the following patch (almost the same as your 69bc4ac) and use helm
> (such as helm-find-files, helm-M-x, helm-mini, helm-resume and
> helm-list-elisp-packages-no-fetch) for a few times without noticing
> any problem. I will report if something is broken.

Hmm, IIRC correctly we had problems doing this, don't remember exactly
what though.
Will see, keep an eye on this...

--
Thierry

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

> diff --git a/helm.el b/helm.el
> index 3a4adfb3..691b6fc1 100644
> --- a/helm.el
> +++ b/helm.el
> @@ -2027,6 +2027,8 @@ ANY-KEYMAP ANY-DEFAULT ANY-HISTORY See `helm'."
>                     helm-in-persistent-action
>                     helm-quit
>                     (helm-buffer (or any-buffer helm-buffer)))
> +               (unless (string-match-p "\\` " helm-buffer)
> +                 (setq helm-buffer (concat " " helm-buffer)))
>                 (helm-initialize
>                  any-resume any-input any-default any-sources)
>                 (helm-display-buffer helm-buffer)

Just tried the patch and we loose text properties in some places like
described in my old comment in #1398, try with M-x
helm-list-elisp-packages and M-I, we loose the orange color and maybe
other important properties elsewhere.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
So it seems that buffers with a leading space in their names, in addition of not being listed and disabling undo are also disabling other features, unfortunately these seem to be undocumented.
AFAICT, at least tabulated-list-mode is not working properly with such buffers or maybe helm use it wrongly ?

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> So it seems that buffers with a leading space in their names, in
> addition of not being listed and disabling undo are also disabling
> other features, unfortunately these seem to be undocumented.  AFAICT,
> at least tabulated-list-mode is not working properly with such buffers
> or maybe helm use it wrongly ?

When I search for "name" in the DEFUN of get-buffer-create, I see
disabling undo as the only implication of the buffer's name starting
with a space.

Of course can arbitrary code look at a buffer's name and do something
special when the name starts with a space char.  But I would not expect
tabulated-list-mode to do something like that.

**Comment by thierryvolpiatto** [comment]
I still think there is in emacs corner cases where buffers prefixed with a spaces are not fully functional, like here for example [difference-between-a-normal-buffer-and-a-space-prefix-buffer-in-emacs](http://stackoverflow.com/questions/18418079/difference-between-a-normal-buffer-and-a-space-prefix-buffer-in-emacs) so I had prefer not using this for helm buffers.
