### ISSUE TITLE
helm find files within curly braces

### ISSUE THREAD

**Issue by DrWaleedAYousef** [emacs-helm/helm#1716]
## Expected behavior
find the file

## Steps to reproduce (recipe)
go with cursor to {/home/AnyFile}; the highlight will not go to AnyFile unless you remove the curly braces or replace them with, e.g., brackets.

**Comment by thierryvolpiatto** [comment]
Waleed Yousef <notifications@github.com> writes:

> go with cursor to {/home/AnyFile}; the highlight will not go to
> AnyFile unless you remove the curly braces or replace them with, e.g.,
> brackets.

Not reproductible.

--
Thierry

**Comment by DrWaleedAYousef** [comment]
So do you mean C-x-f will populate the current directory and go to the file inside the curly braces?

**Comment by thierryvolpiatto** [comment]
Waleed Yousef <notifications@github.com> writes:

> So do you mean C-x-f will populate the current directory and go to the
> file inside the curly braces?

Not the current directory but the file-name-directory of the file which
is inside {}, pressing RET once there will bring you to this file.

--
Thierry

**Comment by DrWaleedAYousef** [comment]
Yes, sorry, I mean the file-name-directory. But unfortunately it does
not work. I will give a clearer example:

going with the cursor to the middle of (/home/wyousef/MyDocuments/)
opens helm buffer at the directory inside the brackets
/home/wyousef/MyDocuments/ and populates 

However, going with the cursor to the middle of
{/home/wyousef/MyDocuments/} opens helm buffer at /home/wyousef

The curly braces always fools helm!

**Comment by thierryvolpiatto** [comment]
Waleed Yousef <notifications@github.com> writes:

> Yes, sorry, I mean the file-name-directory. But unfortunately it does
> not work. I will give a clearer example:
>
> going with the cursor to the middle of (/home/wyousef/MyDocuments/)
> opens helm buffer at the directory inside the brackets
> /home/wyousef/MyDocuments/ and populates
>
> However, going with the cursor to the middle of
> {/home/wyousef/MyDocuments/} opens helm buffer at /home/wyousef
>
> The curly braces always fools helm!

This is not reproductible.

What command are you using exactly ?

Are you using emacs-helm.sh ?


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Also in which mode is the buffer you are starting from ?

**Comment by thierryvolpiatto** [comment]
Also please fill in the bug template, which emacs version you are using ? etc...

**Comment by DrWaleedAYousef** [comment]
The behavior I report occurs within any buffer; for simplicity try even scratch.

The command is helm-find-files. 

GNU Emacs 25.1.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.22.7) of 2017-02-07

I am using Arch linux.

Yes, I tried emacs-helm.sh The same problem occurs. whenever the
file/directory is inside a curly braces and I hit helm-find-files the
helm buffer opens the current directory NOT  the directory inside the
braces unless I put it inside brackets or remove them. I attached two
images explaining what I say; I obtained them after I directly used
emacs-helm.sh

**Comment by thierryvolpiatto** [comment]
Waleed Yousef <notifications@github.com> writes:

> The behavior I report occurs within any buffer; for simplicity try even scratch.
>
> The command is helm-find-files.
>
> GNU Emacs 25.1.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.22.7) of 2017-02-07
>
> I am using Arch linux.
>
> Yes, I tried emacs-helm.sh The same problem occurs. whenever the
> file/directory is inside a curly braces and I hit helm-find-files the
> helm buffer opens the current directory NOT the directory inside the
> braces unless I put it inside brackets or remove them. I attached two
> images explaining what I say; I obtained them after I directly used
> emacs-helm.sh

Thanks, that's more clear.

So I could reproduce the bug with emacs-25, seems it is a bug in ffap,
and of course as helm is using ffap to compute initial input it fails.

In scratch buffer with cursor on {/etc} do M-: (ffap-guesser) RET

With emacs-25   => nil
With emacs-24.5 => "/etc"

Perhaps you should report the bug to upstream.

-- 
Thierry

**Comment by DrWaleedAYousef** [comment]
Thanks so much; what is upstream? Could you send the URL

**Comment by thierryvolpiatto** [comment]
Upstream is emacs-bug, you can report the bug with M-x report-emacs-bug.
In the meaning time you can use:
```elisp
(setq ffap-string-at-point-mode-alist
      (cons '(file "--:\\\\$+<>@-Z_[:alpha:]~*?" "<@" "@>;.,!:")
            (remove (assq 'file ffap-string-at-point-mode-alist)
                    ffap-string-at-point-mode-alist)))
```
to retrieve the emacs-24.5 behavior.

**Comment by thierryvolpiatto** [comment]
Here something more compact and keeping (assoc 'file ..) at the same nth if for some reason it is not the car.

```elisp
(setcdr (assq 'file ffap-string-at-point-mode-alist)
            '("--:\\\\$+<>@-Z_[:alpha:]~*?" "<@" "@>;.,!:"))
```

**Comment by DrWaleedAYousef** [comment]
Thanks so much; although I do not parse what you provided (I am not an
expert in Lisp) it works very well. In addition, I reported the bug to
emacs team.

Thanks so much

**Comment by thierryvolpiatto** [comment]
> although I do not parse what you provided

To make it simple and without entering in the details of `skip-chars-forward/backward`:

Emacs-24.5 is returning  "/etc"  in "{/etc}"  and checking if file exists which is true in this case, whereas Emacs-25 is returning "{/etc}" in "{/etc}" and checking if file exists which is false of course.

Now closing this as fixing this from helm with the code above would be wrong, it has to be fixed in emacs.

Thanks.
