### ISSUE TITLE
helm-autoresize issue

### ISSUE THREAD

**Issue by maindoor** [emacs-helm/helm#1717]
## Expected behavior
This is the setting I have:
(setq helm-autoresize-max-height 40)
(setq helm-autoresize-min-height 0)
(helm-autoresize-mode 1)

The big bold characters that tell me different things under different contexts is messing
up the auto-resize function. 
I am talking about the big "Smex" string (below the "pattern:") that pops up when you
type helm-smex. The same thing shows a directory when I use helm-cscope etc. This 
line is not taken into consideration when I use helm-autoresize-mode. As a consequence
the 40% of the buffer used (see my setting above) has the last line truncated to half a line.
see below:

![image](https://cloud.githubusercontent.com/assets/3489239/24114571/fcc4ee6a-0d5d-11e7-9c76-0ef11cb4c695.png)

Is it possible to remove the big bold "Smex" type strings ? or reduce its size ? It can be bold but just normal size.

## IMPORTANT NOTE:

If you are using a Unix or GNU-Linux system there is no excuses 
to not use `emac-helm.sh` to reproduce your bug in 99% of the cases.

**Comment by thierryvolpiatto** [comment]
maindoor <notifications@github.com> writes:

> Is it possible to remove the big bold "Smex" type strings ? or reduce
> its size ? It can be bold but just normal size.

See https://github.com/emacs-helm/helm/issues/918

--
Thierry

**Comment by maindoor** [comment]
Ok. That configuration works for me too.
