### ISSUE TITLE
`man -l` bug keeps getting rediscovered

### ISSUE THREAD

**Issue by gitfoxi** [emacs-helm/helm#1718]
## Expected behavior
Man pages

## Actual behavior from `emacs-helm.sh` if possible (See note at bottom)
Invoking man -l /usr/share/man/man1/ls.1 in the background
Can’t find the /usr/share/man/man1/ls.1 manpage

## Steps to reproduce (recipe)
On a mac:

helm-man-woman 
ls

## Describe versions of helm, emacs, operating system etc.
OS: darwin
Emacs: 25.1.1
Spacemacs: 0.200.7
Spacemacs branch: lisp-mode-2 (rev. e956e88)
Graphic display: t
Distribution: spacemacs
Editing style: vim
Completion: helm

## This bug has been reported and closed before
#1145  #1035 syl20bnr/spacemacs#8549 

I think a better solution would be either of:

* If darwin, don't use -l
* If `man -l` fails, retry with `man`

## IMPORTANT NOTE:

If you are using a Unix or GNU-Linux system there is no excuses 
to not use `emac-helm.sh` to reproduce your bug in 99% of the cases.

**Comment by thierryvolpiatto** [comment]
Michael Fox <notifications@github.com> writes:

> helm-man-woman
> ls

This is working fine on a GNU Linux box.
I am not using MacOS and helm is not following Spacemacs but I think you
can customize `helm-man-format-switches`.

Let me know if you can't make this working properly from emacs-helm.sh.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Ok I think what you want is helm setting the command by default according to system-type, this is done now.
