### ISSUE TITLE
helm-show-kill-ring doesnt work with osx clipboard 

### ISSUE THREAD

**Issue by lukertty** [emacs-helm/helm#1719]
## Expected behavior

helm-show-kill-ring should also show system clipboard content in OSX.

## Steps to reproduce (recipe)

1. emacs -Q
2. paste these lines to *scratch*
```
(add-to-list 'load-path "~/.emacs.d/elpa/helm-20170320.1242")
(add-to-list 'load-path "~/.emacs.d/elpa/helm-core-20170320.231")
(require 'helm-config)
```
3. eval-buffer
3.5 M-x helm-show-kill-ring (to see what it is)
4. copy something from sublime or chrome...
5. M-x helm-show-kill-ring -> There is nothing! 

However the "s-v" (yank) works well.

![2](https://cloud.githubusercontent.com/assets/11374295/24136966/94a4f4f2-0e4c-11e7-8e28-19fa7589c47e.gif)

## Describe versions of helm, emacs, operating system etc.

1. helm 20170320
2. emacs 25.2.1
3. system OSX 10.11.6

**Comment by thierryvolpiatto** [comment]
lukertty <notifications@github.com> writes:

> Expected behavior
>
> helm-show-kill-ring should also show system clipboard content in OSX.

No, helm-show-kill-ring show only the content of kill-ring and emacs add an
X-selection to kill-ring only once you have yanked this X-selection.

See (info "(elisp) The kill ring")

-- 
Thierry
