### ISSUE TITLE
[feature request]how about make helm-read-file-name support fuzzy match

### ISSUE THREAD

**Issue by jixiuf** [emacs-helm/helm#1720]
## Expected behavior
make helm-read-file-name support  helm-mode-fuzzy-match or support keyword :fuzzy

## Steps to reproduce (recipe)
```
(setq  helm-mode-fuzzy-match t)
(helm-read-file-name "read file:"
                     :initial-input "/fbar"
                     :history '("/tmp/bar" "/tmp/foo" "/tmp/foobar"))
```

**Comment by thierryvolpiatto** [comment]
jixiuf <notifications@github.com> writes:

> Expected behavior
>
> make helm-read-file-name respect helm-mode-fuzzy-match or support keyword :fuzzy

There is no need to use the :fuzzy-match keyword, helm-read-file-name is
implemented like helm-find-files, it is already fuzzy matching.

> Steps to reproduce (recipe)
>
> (setq  helm-mode-fuzzy-match t)
> (helm-read-file-name "read file:"
>                      :initial-input "/fbar"
>                      :history '("/tmp/bar" "/tmp/foo" "/tmp/foobar"))

Perhaps you mean fuzzy matching in history ?

-- 
Thierry

**Comment by zw963** [comment]
I close all my fuzz match function after use a while ...

personal, I don't think fuzz match is as useful as I expect ...

**Comment by jixiuf** [comment]
yes   fuzzy matching in history

**Comment by thierryvolpiatto** [comment]
jixiuf <notifications@github.com> writes:

> yes fuzzy matching in history

Indeed it is more consistent enabling fuzzy in history's of
helm-find-files and helm-read-file-name as they use both fuzzy by
default.

So now fuzzy in hff history is enabled if helm-ff-fuzzy-matching is
enabled and in helm-read-file-name it is enabled by default but you can
disable it with `:fuzzy nil` keyword.

Thanks.

-- 
Thierry

**Comment by jixiuf** [comment]
thanks .
