### ISSUE TITLE
helm autoresize off by 1 issue

### ISSUE THREAD

**Issue by maindoor** [emacs-helm/helm#1722]
## Expected behavior
With helm autoresize set to a min of 0 and a max of 40, the list of search results are off by 1.
Best explained with this picture before with emacs-helm.sh. evaluate the two lines at the bottom
to set the min and max height and enable helm-autoresize-mode (M-x helm-autoreize-mode)
search for a file.

![image](https://cloud.githubusercontent.com/assets/3489239/24313459/19531d74-109a-11e7-80be-f941fe232ba1.png)

As can be seen there are 6 entries in the search results but shows only 5 even though the space
is not anywhere close to 40% of the frame.

What I would expect is to have the buffer expand to show all the 6 entries.

## IMPORTANT NOTE:

If you are using a Unix or GNU-Linux system there is no excuses 
to not use `emac-helm.sh` to reproduce your bug in 99% of the cases.

**Comment by thierryvolpiatto** [comment]
maindoor <notifications@github.com> writes:

> With helm autoresize set to a min of 0 and a max of 40, the list of
> search results are off by 1.

Increase the min number ?

    (helm :sources (helm-build-sync-source "test"
                     :candidates '("foo" "bar" "baz" "bal" "biz" "beer" "bin"))
          :buffer "*helm test*"
          :input "b"
          :autoresize-min-height 10
          :autoresize-max-height 40)

Anyway these settings are not exacts at 1% I think.

If you really want to fix this perhaps change the way the
`fit-window-to-buffer` args are calculated or just try to reproduce with
a dry `fit-window-to-buffer` call and if you succeed report upstream,
but IMO it is not worth an effort for the few benefit it will provide,
you have better time adjusting your settings to your needs.

-- 
Thierry

**Comment by maindoor** [comment]
Fair enough. The new setting works for me.
