### ISSUE TITLE
helm-gm-previous-file, helm-gm-next-file from saved *hgrep* buffer: error "No buffer named *helm*"

### ISSUE THREAD

**Issue by ackalker** [emacs-helm/helm#1723]
## Expected behavior
Point should move to previous file or next file without also signaling an error.

## Actual behavior from `emacs-helm.sh` if possible (See note at bottom)
Point moves to previous or next file but also signals the above mentioned error in the minibuffer.

## Steps to reproduce (recipe)

- In a fresh Git clone of `emacs-helm/helm`, run `make`, then `./emacs-helm.sh`
- Perform a recursive Helm grep search for `helm`, by doing `M-x helm-find-files RET C-u C-s * RET helm`
- Use `F3 RET` to save results in grep buffer `*hgrep*`
- In the `*hgrep*` buffer, try and navigate between files in the grep results using `M-up` or `M-down` (`helm-gm-precedent-file` or `helm-gm-next-file`)

## Backtraces if some (M-x toggle-debug-on-error)

```
Debugger entered--Lisp error: (error "No buffer named *helm*")
  helm-get-current-source()
  helm-follow-execute-persistent-action-maybe()
  helm-goto-next-or-prec-file(1)
  helm-gm-next-file()
  funcall-interactively(helm-gm-next-file)
  call-interactively(helm-gm-next-file nil nil)
  command-execute(helm-gm-next-file)
```

## Describe versions of helm, emacs, operating system etc.

`helm` from fresh Git clone (master @ b4d899388f9adb3c7d40317e0794fb81a53b8596), on Void Linux x86_64, using Emacs 25.1.1 (packaged by Void Linux).

## IMPORTANT NOTE:

If you are using a Unix or GNU-Linux system there is no excuses 
to not use `emac-helm.sh` to reproduce your bug in 99% of the cases.

**Comment by ackalker** [comment]
Thanks for the quick fix!

**Comment by thierryvolpiatto** [comment]
Alain Kalker <notifications@github.com> writes:

> Thanks for the quick fix!

Yes, thanks for the good bug report!

-- 
Thierry
