### ISSUE TITLE
Could cursor blink?

### ISSUE THREAD

**Issue by summer-wu** [emacs-helm/helm#1724]
## Expected behavior
cursor blink in helm-M-x.

## Steps to reproduce (recipe)
```
(blink-cursor-mode 1);effect to normal buffer. Has no effect to  helm-M-x
```
Is there a `helm-blink-cursor-mode` I can use to  turn cursor blink?

## Describe versions of helm, emacs, operating system etc.

+ master(helm-20170322.842)
+ mac os 10.12
+ emacs 25.1

**Comment by thierryvolpiatto** [comment]
summer-wu <notifications@github.com> writes:

> Expected behavior
>
> cursor blink in helm-M-x.
>
> Steps to reproduce (recipe)
>
> (blink-cursor-mode 1);effect to normal buffer. Has no effect to  helm-M-x
>
> Is there a helm-blink-cursor-mode I can use to turn cursor blink?

blink-cursor-mode is disabled by default in emacs-helm.sh otherwise it
is working fine (unfortunately :-)).

-- 
Thierry

**Comment by summer-wu** [comment]
Thank you, @thierryvolpiatto. I'm not using emacs-helm.sh to launch emacs.However now i got the usage of emacs-helm.sh ^_^.

Finally I figure out why.
In Spacemacs,helm use a separate input area which is not minibuffer.
In original helm,helm use minibuffer,minibuffer is controled by blink-cursor-mode.
So, I should open an issue in spacemacs repo.

Original helm,use minibuffer:
![original](https://cloud.githubusercontent.com/assets/2476434/24322486/2738171c-11a0-11e7-85a0-ad0871f9b09e.gif)

Spacemacs use separate area:
![spacemacs](https://cloud.githubusercontent.com/assets/2476434/24322487/27acc738-11a0-11e7-9a64-9bdf1850e6f7.gif)

**Comment by michael-heerdegen** [comment]
summer-wu <notifications@github.com> writes:

> Original helm,use minibuffer:
> original
>
> Spacemacs use separate area:
> spacemacs

Isn't this just the normal helm behavior with
helm-echo-input-in-header-line -> t?

Unless we reimplement blink-cursor-mode for the pseudo cursor in the
header-line, which I think would complicate things too much for a little
benefit, there is no chance to let that cursor blink AFAICT.

**Comment by thierryvolpiatto** [comment]
summer-wu <notifications@github.com> writes:

> In Spacemacs,helm use a separate input area which is not minibuffer.

This is not a spacemacs feature but just a helm configuration as Michael
pointed out.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> summer-wu <notifications@github.com> writes:
>
>> Original helm,use minibuffer:
>> original
>>
>> Spacemacs use separate area:
>> spacemacs
>
> Isn't this just the normal helm behavior with
> helm-echo-input-in-header-line -> t?

Yes I guess spacemacs is just using this configuration.

> Unless we reimplement blink-cursor-mode for the pseudo cursor in the
> header-line, which I think would complicate things too much for a little
> benefit, there is no chance to let that cursor blink AFAICT.

Agreed, would be a lost of time to implement such a mostly unwanted
feature!

-- 
Thierry
