### ISSUE TITLE
`helm-occur` can repeat results 

### ISSUE THREAD

**Issue by xiongtx** [emacs-helm/helm#1725]
## Expected behavior

`helm-occur` should show one result when called with search string `(helm` in a buffer containing the following:

```emacs-lisp
(helm
 :sources 'foo)
```

## Actual behavior from `emacs-helm.sh` if possible (See note at bottom)

Two results for `(helm` are returned. See image below:

![image](https://cloud.githubusercontent.com/assets/1624090/24326304/d0fc3b1c-1168-11e7-8caa-1e7c13946c22.png)

Other strange (possibly related) behaviors:

When there is no space after `helm`, but the search string contains the space (`(helm\ `), the line *after* `(helm` is in the search result.

## Steps to reproduce (recipe)

1. Run `emacs-helm.sh`
2. Put the aforementioned contents in the `*scratch*` buffer
3. Call `helm-occur` with aforementioned search string

## Backtraces if some (M-x toggle-debug-on-error)

N/A

## Describe versions of helm, emacs, operating system etc.

* Helm: `helm-2.5.4`
* Emacs: `25.1.1`
* OS: `Fedora 24`

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> Expected behavior
>
> helm-occur should show one result when called with search string (helm
> in a buffer containing the following:
>
> (helm
>  :sources 'foo)
>
> Actual behavior from emacs-helm.sh if possible (See note at bottom)
>
> Two results for (helm are returned. See image below:

Thanks to catch this, I start figuring what's going on, but it is not
easy to fix, looks like a problem in in-candidate initialization and
possibly multiple match functions, not sure for now, I will work on this
next week but don't expect a quick fix, it's tricky to fix.

--
Thierry

**Comment by thierryvolpiatto** [comment]
Fixed:
- [X] Duplicate candidates with exact matche at first line.
- [  ] Wrong number of line for first empty line matching
- [  ] Match next line when adding a escaped space at end of pattern

**Comment by xiongtx** [comment]
Confirmed as fixed. Can't say I like the hackish code in those commits though 😛 .

**Comment by thierryvolpiatto** [comment]
The only hackish commit is 9ddc867 which have been reverted.

Otherwise we have a bad hack in the candidate-in-buffer implementation that should be fixed one day, but it is not trivial to find something better, see helm/helm.el at master · emacs-helm/helm
https://github.com/emacs-helm/helm/blob/master/helm.el#L4901
This code is causing problems like the ones in this bug.
