### ISSUE TITLE
How do I delete the entire search string?

### ISSUE THREAD

**Issue by zxcvbn97** [emacs-helm/helm#1726]
## Expected behavior

When searching with helm, how do I delete the entire search string?
I tried Ctrl-backspace but it does not work

## IMPORTANT NOTE:

If you are using a Unix or GNU-Linux system there is no excuses 
to not use `emac-helm.sh` to reproduce your bug in 99% of the cases.

**Comment by xiongtx** [comment]
Such questions are better suited for the [Google Group](https://groups.google.com/forum/#!forum/emacs-helm) or [Emacs StackExchange](http://emacs.stackexchange.com/). 

Hitting `C-k` should clear the search string.

**Comment by thierryvolpiatto** [comment]
I have updated the help about the behavior of `C-u C-k`.
While in helm you will find most of your answers with `C-h m`.
