### ISSUE TITLE
Disabling sorting by helm--completion-in-region

### ISSUE THREAD

**Issue by kyleam** [emacs-helm/helm#1735]
Magit uses `crm` to read multiple values.  When we're reading
revisions, we'd like the order of the collection to be preserved when
the items are displayed (https://github.com/magit/magit/pull/3029).

When `helm-mode` is turned on and `completion-in-region-function` is
set to `helm--completion-in-region`, the collection is sorted by
`helm-generic-sort-fn`, losing the order of the original collection.

What method would you recommend for disabling sorting with `crm`?  I
see that binding `helm-completion-in-region-fuzzy-match` to non-nil
will disable the sorting, but I'd guess that turning on fuzzy matching
for the side-effect of disabling sorting is not the right approach.

**Comment by thierryvolpiatto** [comment]
Kyle Meyer <notifications@github.com> writes:

> Magit uses crm to read multiple values. When we're reading
> revisions, we'd like the order of the collection to be preserved when
> the items are displayed (magit/magit#3029).
>
> When helm-mode is turned on and completion-in-region-function is
> set to helm--completion-in-region, the collection is sorted by
> helm-generic-sort-fn, losing the order of the original collection.
>
> What method would you recommend for disabling sorting with crm?

You can use now `helm-completion-in-region-default-sort-fn` with a nil
value.

> I see that binding helm-completion-in-region-fuzzy-match to non-nil
> will disable the sorting,

It will disable the generic sort fn, but not sorting, fuzzy is using its
own sort fn (and must use it).

> but I'd guess that turning on fuzzy matching for the side-effect of
> disabling sorting is not the right approach.

Yes.

-- 
Thierry

**Comment by kyleam** [comment]
> You can use now `helm-completion-in-region-default-sort-fn` with a nil value.

Great.  Thanks!
