### ISSUE TITLE
helm-M-x-read-extended-command: Missing argument in lambda causing error

### ISSUE THREAD

**Issue by alphapapa** [emacs-helm/helm#1736]
I just upgraded all of my Helm packages, and now when I run `helm-M-x-read-extended-command`, I get this error:

```elisp
Wrong number of arguments: (((orig-fuzzy-sort-fn . helm-fuzzy-matching-default-sort-fn) (history) (collection) t) (candidates source) (funcall orig-fuzzy-sort-fn candidates source (quote real))), 3
```

I tracked it down to this: https://github.com/emacs-helm/helm/blob/master/helm-command.el#L200

```elisp
             (helm-fuzzy-sort-fn (lambda (candidates source)
                                   (funcall orig-fuzzy-sort-fn
                                            candidates source 'real)))
```

The lambda only accepts two arguments, which causes the error.  Adding a third, optional argument fixes it, e.g.:

```elisp
             (helm-fuzzy-sort-fn (lambda (candidates source &optional use-real)
                                   (funcall orig-fuzzy-sort-fn
                                            candidates source 'real)))
```

I'm not sure if `'real` should be replaced with `use-real`.

I'm surprised that no one else has encountered this.  Am I the only one using fuzzy matching or sorting here?  Also, I ran blame on the `(lambda ...` line, and it's from a commit from December 2014; how could no one have encountered it by now?

I'm trying to reproduce with `emacs-helm.sh`, but when I press `M-x` in the Emacs instance started by that script, I get another error: `Invalid function: (get-buffer local-bname)`.  I'm also getting that in my normal Emacs config, but while trying to debug that error I encountered this one (which prevents me from using `helm-M-x` normally).

As a possible shortcut, does Helm no longer support Emacs 24.4?  I'm guessing that's the problem, but if so, I guess it should be documented, and the `Package-Requires` should be updated.

Thanks.

**Comment by thierryvolpiatto** [comment]
Are you sure all your helm files have been recompiled with the right emacs version ?
I didn't try with emacs-24.4, I have not such version here, I will try next week perhaps.
Otherwise from here I have no errors, helm-M-x is working fine here with and without fuzzy enabled, I really think this is a problem of compilation of your helm files.

**Comment by alphapapa** [comment]
I'm checking into that now, thanks.  I deleted all the `.elc` files in `elpa/` and it seems to have helped, but now I'm getting other errors, including one with `emacs-helm.sh`, which I'll report in a moment.  I'll close this for now.  Thanks.

**Comment by thierryvolpiatto** [comment]
alphapapa <notifications@github.com> writes:

>              (helm-fuzzy-sort-fn (lambda (candidates source)
>                                    (funcall orig-fuzzy-sort-fn
>                                             candidates source 'real)))
>
> The lambda only accepts two arguments, which causes the error. Adding a third, optional argument fixes it, e.g.:
>
>              (helm-fuzzy-sort-fn (lambda (candidates source &optional use-real)
>                                    (funcall orig-fuzzy-sort-fn
>                                             candidates source 'real)))

I think there is something wrong in this code that may fail if one have
configured helm-fuzzy-sort-fn to something else that accept only 2 args,
is it your case ? IOW do you have somewhere a 
(setq helm-fuzzy-sort-fn 'something_else_that_accepts_only_2_args) ?


Here is the wrong code:

      (let* ((orig-fuzzy-sort-fn helm-fuzzy-sort-fn)
             (helm-fuzzy-sort-fn (lambda (candidates source)
                                   (funcall orig-fuzzy-sort-fn
                                            candidates source 'real)))

We are actually using funcall on orig-fuzzy-sort-fn which is maybe a
function with 2 args only and orig-fuzzy-sort-fn is used nowhere else, I
guess this is a vestige of old code that haven't been cleaned, if it
have worked fine until now, it is by chance only i.e no body have used a
personal helm-fuzzy-sort-fn.

I will correct this ASAP.

Thanks.

-- 
Thierry

**Comment by alphapapa** [comment]
> I think there is something wrong in this code that may fail if one have configured helm-fuzzy-sort-fn to something else that accept only 2 args, is it your case ? IOW do you have somewhere a (setq helm-fuzzy-sort-fn 'something_else_that_accepts_only_2_args) ?

I grepped all of `~/.emacs.d` and all of my `~/src`, but I couldn't find any reference to `helm-fuzzy-sort-fn` except in Helm itself.  I am quite confused.  :)

Thanks for your help.

**Comment by thierryvolpiatto** [comment]
I made a specific sort function for helm-M-x, which is cleaner and less confusing than before.
I close now, feel free to reopen if something not working.

Thanks.
