### ISSUE TITLE
Function to get marked candidates in all sources?

### ISSUE THREAD

**Issue by alphapapa** [emacs-helm/helm#1739]
`(helm-marked-candidates)` only returns candidates in the source that the currently-selected line is in, even if candidates are marked in other sources.

Based on `helm-revive-visible-mark`, I came up with this function that seems to work (I'm only returning the `real` part of the candidate here):

```elisp
(defun helm-org-rifle--get-marked-candidates ()
  "Return list of all marked candidates in Helm.
`helm-marked-candidates' only returns results from the current
source, so we must gather them manually."
  ;; Based on `helm-revive-visible-mark'
  (with-current-buffer helm-buffer
    (save-excursion
      (cl-loop for o in helm-visible-mark-overlays
               collect (overlay-get o 'real)))))
```

Would you accept a PR to add a function to get marked candidates in all sources, or to modify `helm-marked-candidates` to do so?

Also, `helm-mark-all` only works on the current source too.  Would you accept a function that marks all candidates in all sources?

Thanks.

**Comment by thierryvolpiatto** [comment]
alphapapa <notifications@github.com> writes:

> Would you accept a PR to add a function to get marked candidates in
> all sources, or to modify helm-marked-candidates to do so?

A new key for `helm-marked-candidates` would be ok.

Thanks.

--
Thierry

**Comment by thierryvolpiatto** [comment]
You can now use `(helm-marked-candidates :all-sources t)`.

**Comment by alphapapa** [comment]
Thanks, Thierry.  I pushed this commit that modifies helm-mark-all to operate on all sources also.  I think it should work, but I'm not sure if it's how you'd want it done.

**Comment by thierryvolpiatto** [comment]
No, helm-mark-all should not be modified like this.  I will try to modify it next week.

**Comment by thierryvolpiatto** [comment]
I made a quick change that should allow marking in all sources, I will look at this more closely if it's working fine next week.

**Comment by alphapapa** [comment]
Thanks, that looks great.

**Comment by thierryvolpiatto** [comment]
`helm-mark-all` should handle different sources, files etc...
If user mark all sources inadvertently  we have to ensure only marked in current source will be used.
So let this open I will do further work on this later.

**Comment by alphapapa** [comment]
Thanks!
