### ISSUE TITLE
helm open things

### ISSUE THREAD

**Issue by NikolaMandic** [emacs-helm/helm#1744]
question about usability

## Expected behavior
I have 4 windows in emacs
and I select one
then I do some helm
open thing from helm
it goes into window I selected and not where helm wants

## Actual behavior from `emacs-helm.sh` if possible (See note at bottom)

it goes not to the window I selected

is it somehow possible to set it?

**Comment by thierryvolpiatto** [comment]
Никола <notifications@github.com> writes:

> question about usability
>
> Expected behavior
>
> I have 4 windows in emacs
> and I select one
> then I do some helm
> open thing from helm
> it goes into window I selected and not where helm wants

It is the actual behavior from .emacs-helm.sh.

> Actual behavior from emacs-helm.sh if possible (See note at bottom)
>
> it goes not to the window I selected

I can't reproduce, are you sure you are using .emacs-helm.sh?

> is it somehow possible to set it?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.*


-- 
Thierry

**Comment by NikolaMandic** [comment]
thanks. I copy pasted something from emacs-helm.sh and it works now. It was my config specific it seems
