### ISSUE TITLE
How change matching color for command “helm-grep-do-git-grep”?

### ISSUE THREAD

**Issue by alexei28** [emacs-helm/helm#1745]
Windows 7, Emacs 25.1, Helm package.

In my **helm-grep-do-git-grep** the match text is dark red. I  want to change match text color (dark red) to another (e.g. green).
I try to find in **helm-grep-face**,  but not found.
So how I can change this face color?

**Comment by thierryvolpiatto** [comment]
alexei28 <notifications@github.com> writes:

> So how I can change this face color?

Add in [color] section of your ~/.gitconfig:

        [color "grep"]
	match = black yellow

Change black yellow as needed, where black is the foreground and yellow
the background.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by alexei28** [comment]
> Add in [color] section of your ~/.gitconfig:

        [color "grep"]
	match = black yellow


I change my c:\Users\Alex\.gitconfig

Add section **color**

[color "grep"]
	match = black yellow

Restart Emacs, but it NOT help. Command **helm-grep-do-git-grep** - match text is DARK RED (аs before).

**Comment by thierryvolpiatto** [comment]
alexei28 <notifications@github.com> writes:

>     Add in [color] section of your ~/.gitconfig:
>
>     [color "grep"]
> match = black yellow
>
> I change my c:\Users\Alex.gitconfig
>
> Add section color
>
> [color "grep"]
> match = black yellow
>
> Restart Emacs, but it NOT help. Command helm-grep-do-git-grep - match
> text is DARK RED (аs before).

That's mean you have changed your default command line, please read the
documentation of `helm-grep-git-grep-command`. And you don't need to
restart emacs, the color change as soon as you modify settings in .gitconfig.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by thierryvolpiatto** [comment]
Default value of  `helm-grep-git-grep-command`:

![capture d ecran_2017-04-18_12-50-21](https://cloud.githubusercontent.com/assets/1533939/25127477/45614f12-2436-11e7-824c-bf0220badb42.png)

Using yellow as background in .gitconfig:

![capture d ecran_2017-04-18_12-52-45](https://cloud.githubusercontent.com/assets/1533939/25127521/7110d7ae-2436-11e7-82cd-277a0d99ea55.png)

![capture d ecran_2017-04-18_12-51-45](https://cloud.githubusercontent.com/assets/1533939/25127565/96a0e798-2436-11e7-8dd5-116bf3a2a3b9.png)

Now editing .gitconfig to have green as background:

![capture d ecran_2017-04-18_12-53-18](https://cloud.githubusercontent.com/assets/1533939/25127594/ba5605ec-2436-11e7-90c9-b957a7cf922e.png)

![capture d ecran_2017-04-18_12-53-52](https://cloud.githubusercontent.com/assets/1533939/25127603/c43cbef2-2436-11e7-8c3f-89b038d831bb.png)

**Comment by alexei28** [comment]
Sorry. When I change d:\Programs\emacs\ .gitconfig  it's WORK. Thanks.
