### ISSUE TITLE
Select candidates with mouse

### ISSUE THREAD

**Issue by xiongtx** [emacs-helm/helm#1746]
## Expected behavior

In a Helm buffer, it should be possible to move the selection line to a candidate with the mouse (`<mouse-1>`).

## Actual behavior from `emacs-helm.sh` if possible (See note at bottom)

It is not possible to move the selection line to a candidate with `<mouse-1>`.

## Steps to reproduce (recipe)

N/A

## Backtraces if some (M-x toggle-debug-on-error)

N/A

## Describe versions of helm, emacs, operating system etc.

- Helm: `2.5.1`
- Emacs: `25.1.50.1`
- OS: `Darwin C02RW05YFVH6 15.6.0`

**Comment by thierryvolpiatto** [comment]
Here how it will behave:
- If `helm-prevent-mouse` is non-nil, no mouse, same behavior as now.
- `helm-prevent-mouse` is nil:
   - mouse-1 select candidate
   - mouse-2 execute default action
   - mouse-3 popup menu actions

Perhaps in the future we should also track the mouse for automatic selection
but this is much more work.

**Comment by alphapapa** [comment]
This sounds great!

**Comment by xiongtx** [comment]
Cool, though I think it's more common for vars to do something when they're non-nil, so I'd reverse `helm-prevent-mouse` to `helm-allow-mouse` and make it `t` by default.

**Comment by alphapapa** [comment]
That's a good point.  Double-negative options tend to be confusing for some reason.

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> Cool, though I think it's more common for vars to do something when
> they're non-nil, so I'd reverse helm-prevent-mouse to helm-allow-mouse
> and make it t by default.

Yeah, this and some other details I need to fix...

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by thierryvolpiatto** [comment]
I think I handled now all user cases, let me know when something is wrong.
Should also fix related issue: #501 #1495 and #622.

**Comment by thierryvolpiatto** [comment]
Still some issues with help-echo's in async-sources that need to be fixed:

- Duplicates in help-echo when redisplaying (helm-locate).
- help-echo at first candidate is overwritten.

**Comment by alphapapa** [comment]
Is it just me, or is this significant enough to warrant some kind of announcement or news item?  :)

**Comment by thierryvolpiatto** [comment]
alphapapa <notifications@github.com> writes:

> Is it just me, or is this significant enough to warrant some kind of
> announcement or news item? :)

Will add a note in https://github.com/emacs-helm/helm/releases when
releasing next version.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by ferrum-salvator** [comment]
Can I swap mouse2 and mouse3? I haven't owned a mouse with a middle button in 6 years.

**Comment by thierryvolpiatto** [comment]
Anton Shiryaev <notifications@github.com> writes:

> Can I swap mouse2 and mouse3? I haven't owned a mouse with a middle button in 6 years.

Normally, mouse1 + mouse3 == mouse2, IOW press simultenaously your two
mouse button.

-- 
Thierry

**Comment by ferrum-salvator** [comment]
I can't do that either, sadly. So far I've bound it to S-<mouse1>.
