### ISSUE TITLE
Quit hook?

### ISSUE THREAD

**Issue by alphapapa** [emacs-helm/helm#1747]
Hi Thierry,

Would it be possible to add a hook that is run at the end of `helm-keyboard-quit`?  My situation is, when I run a persistent action in `helm-org-rifle`, it creates indirect buffers, and I'd like to clean them up if the user aborts the Helm session.  I guess I might be able to make a cleanup hook that checks `helm-exit-status`, but it would be nice to have a quit hook.  :)

Thanks.

**Comment by thierryvolpiatto** [comment]
alphapapa <notifications@github.com> writes:

> Hi Thierry,
>
> Would it be possible to add a hook that is run at the end of
> helm-keyboard-quit? My situation is, when I run a persistent action in
> helm-org-rifle, it creates indirect buffers, and I'd like to clean
> them up if the user aborts the Helm session. I guess I might be able
> to make a cleanup hook that checks helm-exit-status, but it would be
> nice to have a quit hook. :)

What about something like this:

    (condition-case _err
        (helm :sources my-source <etc...>)
      (quit (delete-my-buffers-or-whatever)))

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by alphapapa** [comment]
Thanks, I didn't know about that pattern.  That should work.
