### ISSUE TITLE
helm-grep-do-git-grep fails to open files on remote machine

### ISSUE THREAD

**Issue by yota9** [emacs-helm/helm#1748]
## Expected behavior
Open selected file

## Actual behavior from `emacs-helm.sh` if possible (See note at bottom)
Enter password for ssh:machine (without user name)

## Steps to reproduce (recipe)
Just connect to remote machine via ssh and do helm-grep-do-git-grep in project. After selecting founded file you would be asked for password for "/ssh:machine:" without user name. 

## Describe versions of helm, emacs, operating system etc.
Ubuntu 16.04; emacs 25.1.1; helm-20161028.559

**Comment by thierryvolpiatto** [comment]
helm-projectile is not part of helm, please report elsewhere.
Thanks.

**Comment by yota9** [comment]
OK, I updeted my report. The problem is with helm-grep and projectile was just based on it :) Thank you!

**Comment by thierryvolpiatto** [comment]
yota9 <notifications@github.com> writes:

> OK, I updeted my report. The problem is with helm-grep and projectile
> was just based on it :) Thank you!

See also https://github.com/emacs-helm/helm/wiki/Grep#tramp

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997
