### ISSUE TITLE
helm-debug-toggle

### ISSUE THREAD

**Issue by yota9** [emacs-helm/helm#1749]
## Expected behavior
Enable and disable debug

## Actual behavior from `emacs-helm.sh` if possible (See note at bottom)
Always prints "debug enabled"

## Steps to reproduce (recipe)
run helm-debug-toggle 2 times

## Describe versions of helm, emacs, operating system etc.
Ubuntu 16.04; emacs 25.1.1; helm-20161028.559

**Comment by thierryvolpiatto** [comment]
yota9 <notifications@github.com> writes:

> Expected behavior
>
> Enable and disable debug
>
> Actual behavior from emacs-helm.sh if possible (See note at bottom)
>
> Always prints "debug enabled"

helm-debug-toggle is now deprecated, you should use `C-h C-d` instead, I
will remove it, thanks to remember me to do it.
You will find an entry in help (C-h m) on how to use this. 

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997
