### ISSUE TITLE
Cannot open load file helm-autoloads

### ISSUE THREAD

**Issue by fedkey** [emacs-helm/helm#1754]
### error message:
Error (el-get): while initializing helm: Cannot open load file: no file or dir not exists, helm-autoloads

I Verified, The document does not exist,

please repair it, when you have free time

Thank you!

**Comment by thierryvolpiatto** [comment]
暮色连城 <notifications@github.com> writes:

> Expected behavior
>
> error message:
>
> Error (el-get): while initializing helm: Cannot open load file: no file or dir not exists, helm-autoloads

If it doesn't exists, it is it haven't been created, up to el-get to run
make or whatever to create the autoload file.

> I Verified, The document does not exist,

If you install with package.el from MELPA or from git+make you will see
the autoload file.
Here the relevant part of make output:

emacs -Q -batch --eval "(let ((generated-autoload-file (expand-file-name \"helm-autoloads.el\" \".\")) \
(backup-inhibited t)) (update-directory-autoloads \".\"))"
Generating autoloads for helm.el...
Generating autoloads for helm.el...done

[...]

Generating autoloads for helm-source.el...done
Generating autoloads for helm-types.el...
Generating autoloads for helm-types.el...done
Saving file /home/thierry/elisp/helm/helm-autoloads.el..


IOW this is a problem with el-get configuration or el-get itself, not
helm, perhaps you should ask at el-get for help (I don't use el-get so I
can't help you more on it).

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997
