### ISSUE TITLE
helm pdf grep on all files in a directory

### ISSUE THREAD

**Issue by bishesh** [emacs-helm/helm#1756]
## Expected behavior
In helm-find-files interface with a base directory selected (.), M-g p should grep all the pdf files existing in . directory 

## Actual behavior from `emacs-helm.sh` if possible (See note at bottom)
The helm-find-files interface simply quits doing no grep.
However if a single pdf file is selected, M-g p does grep and returns results.

## Steps to reproduce (recipe)
1. helm-find-files 
2. Select . directory
3. M-g p

## Describe versions of helm, emacs, operating system etc.
Helm: 20170331.2339
Emacs: 24.5.1

**Comment by thierryvolpiatto** [comment]
Bishesh <notifications@github.com> writes:

> Expected behavior
>
> In helm-find-files interface with a base directory selected (.), M-g p
> should grep all the pdf files existing in . directory
>
> Actual behavior from emacs-helm.sh if possible (See note at bottom)
>
> The helm-find-files interface simply quits doing no grep.
> However if a single pdf file is selected, M-g p does grep and returns results.

It is just not implemented. IIRC when I wrote this the "-r" option of
pdfgrep was not existing. Will write something soon.

Thanks.


--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by thierryvolpiatto** [comment]
For now, just mark your pdf files and launch pdfgrep.

**Comment by bishesh** [comment]
Marking the files and launching pdfgrep is a handy temporary workaround, thanks. But it would be very useful to have the recursive feature implemented, thanks!

**Comment by thierryvolpiatto** [comment]
Bishesh <notifications@github.com> writes:

> Marking the files and launching pdfgrep is a handy temporary
> workaround, thanks. But it would be very useful to have the recursive
> feature implemented, thanks!

Coming soon ;-)

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by thierryvolpiatto** [comment]
It seems ok for me, let me know if it works for you as you expect.

Thanks.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by bishesh** [comment]
Yes, it works! Thank you !!!

**Comment by hisnawi** [comment]
This is just not working for me.
whenever I mark all pdfs with helm-find-files
~/test/

Than I do M-g p to choose helm-ff-run-pdfgrep 
I get:
apply: No such action ‘helm-ff-pdfgrep’ for this source

What am I doing wrong?

**Comment by thierryvolpiatto** [comment]
hisnawi <notifications@github.com> writes:

> This is just not working for me.
> whenever I mark all pdfs with helm-find-files
> ~/test/
>
> Than I do M-g p to choose helm-ff-run-pdfgrep
> I get:
> apply: No such action ‘helm-ff-pdfgrep’ for this source
>
> What am I doing wrong?

Without more infos, I can't help, it is working fine here starting from
emacs-helm.sh, please try to start from here first.
Be sure also to have pdfgrep installed.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by hisnawi** [comment]
@thierryvolpiatto Thanks for your response.
Yes, pdfgrep is installed. I am able to mark a file or a set of pdf files and search in them. But when I mark a directory and  M-g p I get the message: No such action ‘helm-ff-pdfgrep’ for this source

Also sorry for my ignorance but what is emacs-helm-sh?
I am simply using the helm and helm-grep packages in emacs. I am not aware of this script or how to use it.

**Comment by thierryvolpiatto** [comment]
hisnawi <notifications@github.com> writes:

> @thierryvolpiatto Thanks for your response.  Yes, pdfgrep is
> installed. I am able to mark a file or a set of pdf files and search
> in them. But when I mark a directory and M-g p I get the message: No
> such action ‘helm-ff-pdfgrep’ for this source

Should be fixed now.

> Also sorry for my ignorance but what is emacs-helm-sh?

See https://github.com/emacs-helm/helm/wiki#quick-try-with-emacs-helmsh

> I am simply using the helm and helm-grep packages in emacs. I am not aware of this script or how to use it.

helm-grep is not a package in itself, it is part of helm.
You will find emacs-helm.sh in your helm installation directory, cd to
this directory and run ./emacs-helm.sh (you can also make a symlink in
e.g. ~/bin).


-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Note that if you installed from source the symlink is already created in /usr/local/bin as helm.

**Comment by hisnawi** [comment]
Thank you for the fix. I was wondering when this will make it to melpa to pull it into my emacs packages.
