### ISSUE TITLE
show quick-access numbers

### ISSUE THREAD

**Issue by brotzeitmacher** [emacs-helm/helm#1757]
Is there an option to show quick-access numbers like in company ? Thanks.

**Comment by thierryvolpiatto** [comment]
brotzeitmacher <notifications@github.com> writes:

> Is there an option to show quick-access numbers like in company ?

I never used company, so I don't know this.
Maybe what you are looking for is accessing numbered candidates ?
Helm have C-x 1, C-x 2,....,C-x 9 to execute default action on candidate
number <n> BEFORE current candidate and C-c 1, 2 etc... to access
candidate number <n> AFTER current candidate.
However if you have not the candidate number visible, this is not very
useful, so you have to install linum-relative.el and enable it for helm
with M-x helm-linum-relative-mode.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by brotzeitmacher** [comment]
Nice, that's perfect. But I would like to rebind the commands and I can't find the names.

**Comment by thierryvolpiatto** [comment]
brotzeitmacher <notifications@github.com> writes:

> Nice, that's perfect. But I would like to rebind the commands and I can't find the names.

(lambda () (interactive) (helm-execute-selection-action-at-nth n))

See the loop at end of helm-map definition.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by thierryvolpiatto** [comment]
BTW, note that mouse usage is now available in helm.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by thierryvolpiatto** [comment]
You should now be able to use the variables `helm-action-at-nth-positive-prefix-key` and `helm-action-at-nth-negative-prefix-key`.

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> Is it possible to just have the convention that universal prefix (C-u)
> before the positive prefix key applies the negative prefix key?

No, typing e.g C-u -6 <key> would be boring (and nearly as long as
typing C-n * 6 RET).
Typing C-x 6 is much better.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by brotzeitmacher** [comment]
Great. What do you think about adding the possbility to call the commands with prefix argument in order to only select a candidate without executing the default action ?

**Comment by thierryvolpiatto** [comment]
brotzeitmacher <notifications@github.com> writes:

> Great. What do you think about adding the possbility to call the
> commands with prefix argument in order to only select a candidate
> without executing the default action ?

The prefix arg would prevent using it on default action.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by brotzeitmacher** [comment]
Ok. Thanks for your time!
