### ISSUE TITLE
`helm-M-x` should always display prefix arg in mode line

### ISSUE THREAD

**Issue by xiongtx** [emacs-helm/helm#1760]
## Expected behavior

When specifying a prefix arg (e.g. via `universal-argument`) *before* calling `helm-M-x`, the prefix arg should be displayed in the mode line.

## Actual behavior from `emacs-helm.sh` if possible (See note at bottom)

Prefix arg specified *before* calling `helm-M-x` is not shown in mode line. Instead, it is shown as part of the prompt. The same thing should not be found in two places. See images below:

Prefix arg *before* calling `helm-M-x`:

![prefix-before-helm-m-x](https://cloud.githubusercontent.com/assets/1624090/25553150/dcfb8bee-2c60-11e7-9f0f-ed10a215a815.png)

Prefix arg *after* calling `helm-M-x`:

![prefix-after-helm-m-x](https://cloud.githubusercontent.com/assets/1624090/25553151/e32ea186-2c60-11e7-9318-aa4481ec9343.png)

## Steps to reproduce (recipe)

1. Call `universal-argument` (`C-u`)
2. Call `helm-M-x`
3. See that prefix arg is not shown in command line

## Backtraces if some (M-x toggle-debug-on-error)

N/A

## Describe versions of helm, emacs, operating system etc.

- `helm`: `20170324.1617`
- Emacs: `25.1.1`
- OS: `Fedora 24`

**Comment by thierryvolpiatto** [comment]
Tianxiang Xiong <notifications@github.com> writes:

> Expected behavior
>
> When specifying a prefix arg (e.g. via universal-argument) before
> calling helm-M-x, the prefix arg should be displayed in the mode line.

No.

The prefix arg shown in mode-line reflects prefix args called AFTER
calling M-x, the prefix arg called BEFORE M-x should be notified in
prompt like regular M-x. When a prefix arg is specified BEFORE, then the
first prefix arg called AFTER should disable the former (try C-u M-x C-u).
This allow user to change its mind about the initial prefix arg entered,
also if the initial prefix arg is a row prefix arg and user add numeric
prefix arg to it we are wrong, same for the contrary.

IOW we should keep the two interfaces for prefix args independent, and
specifying one in prompt and one in mode-line make this clear.

You will find an issue discussing this.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by xiongtx** [comment]
OK, thanks; didn't think about the cases that would warrant differentiation.
