### ISSUE TITLE
Execute the selected item in the list programmatically 

### ISSUE THREAD

**Issue by fiveNinePlusR** [emacs-helm/helm#1762]
## Expected behavior

I would like to have some kind of way to execute the default action (look up the function/variable/whatever in the documentation) programmatically from outside of the helm function.

Use case is using the superior filtering and aggregated search that helm-apropos provides to programmatically find the documentation for whatever is under the cursor. 

things I have tried:

``` elisp
  (defun my/apropos ()
    (interactive)
    (helm-apropos (thing-at-point 'symbol t))
    (sleep-for 0)
    ;; (with-helm-buffer
    ;; (with-helm-current-buffer
    ;; (with-current-buffer "*helm apropos*"
    (with-current-buffer "*HELM Apropos"
      ;; (evil-ret)
      (message "before minibuffer")

      (helm-execute-selection-action)
      ;; (helm-maybe-exit-minibuffer)
      ;; (insert (kbd "<enter>"))
      (message "helm happened"))
    )
```

## Actual behavior from `emacs-helm.sh` if possible (See note at bottom)

Doesn't seem to have a way.

## Describe versions of helm, emacs, operating system etc.

Emacs 25 on osx

**Comment by thierryvolpiatto** [comment]
fiveNinePlusR <notifications@github.com> writes:

> Expected behavior
>
> I would like to have some kind of way to execute the default action
> (look up the function/variable/whatever in the documentation)
> programmatically from outside of the helm function.
>
> Use case is using the superior filtering and aggregated search that
> helm-apropos provides to programmatically find the documentation for
> whatever is under the cursor.

I don't understand what you want to do exactly, isn't what helm-apropos
does actually, i.e finding the documentation of symbol at point ?

> things I have tried:
>
>   (defun my/apropos ()
>     (interactive)
>     (helm-apropos (thing-at-point 'symbol t))
>     (sleep-for 0)
>     ;; (with-helm-buffer
>     ;; (with-helm-current-buffer
>     ;; (with-current-buffer "*helm apropos*"
>     (with-current-buffer "*HELM Apropos"
>       ;; (evil-ret)
>       (message "before minibuffer")
>
>       (helm-execute-selection-action)
>       ;; (helm-maybe-exit-minibuffer)
>       ;; (insert (kbd "<enter>"))
>       (message "helm happened"))
>     )

When you want to write your own helm commands, don't reuse an existing
one, but `helm` directly e.g

    (helm :sources '(some_apropos_sources) 
          :buffer "*helm my-apropos-or-whatever*"
          etc....)

Oh! but perhaps what you want to do is exiting immediately when symbol
at point is found ?
If so you have to wrap your helm call in a let binding with
`helm-execute-action-at-once-if-one` and to advice temporarily
`helm-apropos-init` to not return default+candidates but only
candidates.

Note that you will loose several functionalities of helm-apropos doing
this.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by fiveNinePlusR** [comment]
> Oh! but perhaps what you want to do is exiting immediately when symbol at point is found ?

Exactly! I still will use helm for more advanced queries but this one I want to bring up the first result found if possible.

So I tried doing what you suggest and I am having a tough time on the advice part. 

Here's what I tried to do and it's being called 5 times each time it's run. The return value seems to be a buffer name that likely holds the candidate results for each of the types of apropos queries. 

``` elisp
  (defun my/apropos ()
    (interactive)
    (let* ((helm-execute-action-at-once-if-one t)
           (helm-apropos (thing-at-point 'symbol t)))
    ))

  (defun trace-apropos (orig-fun &rest args)
    (message "apropos called with args %s" args)
    (let ((res (apply orig-fun args)))
      (message "apropos returned %s" res)
      res))
  (advice-add 'helm-apropos-init :around #'trace-apropos)
```

Output:

``` elisp
apropos called with args (commandp trace-apropos)
apropos returned  *helm candidates:Commands*
apropos called with args (#[257 \300!\205\301!?\205\302!?\205\303!?\207 [fboundp commandp generic-p class-p] 3 

(fn X)] trace-apropos)
apropos returned  *helm candidates:Functions*
apropos called with args (#[257 \300!\207 [class-p] 3 

(fn X)] trace-apropos)
apropos returned  *helm candidates:Classes*
apropos called with args (#[257 \300!\207 [generic-p] 3 

(fn X)] trace-apropos)
apropos returned  *helm candidates:Generic functions*
apropos called with args (#[257 \300!\205
\301!?\207 [boundp keywordp] 3 

(fn X)] trace-apropos)
apropos returned  *helm candidates:Variables*
```

Any advice would be much appreciated!

**Comment by thierryvolpiatto** [comment]
fiveNinePlusR <notifications@github.com> writes:

> Exactly! I still will use helm for more advanced queries but this one
> I want to bring up the first result found if possible.

Try instead something like this:

    (defun my-helm-apropos ()
      (interactive)
      (let ((helm-execute-action-at-once-if-one t))
        (helm :sources
              (mapcar (lambda (func)
                        (funcall func nil))
                      helm-apropos-function-list)
              :history 'helm-apropos-history
              :buffer "*helm apropos*"
              :input (thing-at-point 'symbol))))

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by fiveNinePlusR** [comment]
That actually doesn't work for me as it still just shows the candidates and doesn't perform the default first action. is there a way to hack in something like a `helm-execute-default-action-at-once`

**Comment by thierryvolpiatto** [comment]
fiveNinePlusR <notifications@github.com> writes:

> That actually doesn't work for me as it still just shows the
> candidates and doesn't perform the default first action. is there a
> way to hack in something like a helm-execute-default-action-at-once

It is working, use something like this:

    (concat "\\_<" (thing-at-point 'symbol) "\\_>")
 
Note that you will have variables with same name as functions,
so expect duplicates.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by thierryvolpiatto** [comment]
And don't forget to disable fuzzy for helm-apropos.


-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> It is working, use something like this:
>
> (concat "\\_<" (thing-at-point 'symbol) "\\_>")

You probably want to `regexp-quote' the symbol name.  I recently learned
that the canonical way to construct such a regexp is "regexp-opt":

(regexp-opt (list (thing-at-point 'symbol)) 'symbols)

**Comment by fiveNinePlusR** [comment]
Thanks for the help! It's working now. 👍
