### ISSUE TITLE
helm-do-grep-ag with file type selector failed when helm-adaptive-mode is on.

### ISSUE THREAD

**Issue by gujiaxi** [emacs-helm/helm#1764]
## Expected behavior
File type selector will show up to select for ag/rg.

## Actual behavior from `emacs-helm.sh` if possible (See note at bottom)
When `helm-adaptive-mode` is on, run `helm-do-grep-ag` with type selector will fail with error `"Wrong type argument: lisp, \.\.\."`.

## Steps to reproduce (recipe)
1. My setup for helm.
``` lisp
(use-package helm
  :config
  (require 'helm-config)
  (helm-mode)
  (helm-adaptive-mode t)
  (setq helm-grep-ag-command "rg --color=always --smart-case --no-heading --line-number %s %s %s")
  :bind
  (("C-x g" . helm-do-grep-ag)))
```
2. Start helm-do-grep-ag with type select using `C-u C-x g`.

## Describe versions of helm, emacs, operating system etc.

Emacs: 25.1.1 on MacOS Sierra (`brew cask install emacs`)
Helm: helm-20170503

**Comment by thierryvolpiatto** [comment]
Isaac <notifications@github.com> writes:

> Expected behavior
>
> File type selector will show up to select for ag/rg.
>
> Actual behavior from emacs-helm.sh if possible (See note at bottom)
>
> When helm-adaptive-mode is on, run helm-do-grep-ag with type selector
> will fail with error "Wrong type argument: lisp, \.\.\.".

Not reproductible with my `helm-adaptive-history-file` which is clean.

Seems that your `helm-adaptive-history-file` is corrupted, you should
use M-x helm-reset-adaptive-history and restart emacs.

Be aware that when doing this you loose all your previous adaptative
history, but the benefit will be to restart with something clean.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by gujiaxi** [comment]
@thierryvolpiatto Thanks, it works.
