### ISSUE TITLE
helm-render-source has become very slow

### ISSUE THREAD

**Issue by masutaka** [emacs-helm/helm#1766]
## Behavior

I believe `helm-render-source` has become very slow since 96d671a3fec4b28af49648caefb274708bb75657.

Can you revert this change?

## Steps to reproduce (recipe)

1. Execute emacs in sandbox environment using https://gist.github.com/masutaka/4c2e70bb94e95966aba9b6a00d2868f5

    ```
    $ mkdir ~/.emacs.test.d
    $ curl -o ~/.emacs.test.d/init.el https://gist.githubusercontent.com/masutaka/4c2e70bb94e95966aba9b6a00d2868f5/raw/87e4fe388a20ad545950a9a949376b5b60633cae/init.el
    $ emacs -q -l ~/.emacs.test.d/init.el
    ```

1. Wait until to show `Wrote $HOME/.hatenabookmark` in minibuffer.
1. M-x helm-hatena-bookmark
    * It takes **about 30 second** on my Mac.
1. Eval the following elisp

    ```lisp
    (defun helm-render-source (source matches)
      "Display MATCHES from SOURCE according to its settings."
      (helm-log "Source name = %S" (assoc-default 'name source))
      (when matches
        (helm-insert-header-from-source source)
        (if (not (assq 'multiline source))
            (cl-loop for m in matches
                     for count from 1
                     do (helm-insert-match m 'insert count source))
          (let ((start (point))
                (count 0)
                separate)
            (cl-dolist (match matches)
              (cl-incf count)
              (if separate
                  (helm-insert-candidate-separator)
                (setq separate t))
              (helm-insert-match match 'insert count source))
            (put-text-property start (point) 'helm-multiline t)))))
    ```

1. M-x helm-hatena-bookmark
    * It takes **about 2 second** on my Mac.
1. Remove the sandbox and else
    * `$ rm -rf ~/.emacs.test.d ~/.hatenabookmark`

## Describe versions of helm, emacs, operating system etc.

Emacs: 25.2 on macOS Sierra (brew cask install railwaycat/emacsmacport/emacs-mac-official-icon)
Helm: helm-core-20170503.19

**Comment by thierryvolpiatto** [comment]
Takashi Masuda <notifications@github.com> writes:

> Behavior
>
> I believe helm-render-source has become very slow since 96d671a.
>
> Can you revert this change?

Revert no, but I have modified it, let me know if it is faster.

Thanks.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by masutaka** [comment]
The problem has fixed.

Thanks!!!
