### ISSUE TITLE
Unable to open org-mode attachments

### ISSUE THREAD

**Issue by jocap** [emacs-helm/helm#1767]
## Expected behavior

When I press `C-c C-a o` on an org-mode headline, I should see, in a Helm interface, a list of attachments to open. The function (`org-attach-open`) works without Helm, but not with it.

## Actual behavior from `emacs-helm.sh`

Nothing happens except I get an error message: `(wrong-type-argument characterp` + the name of the first attachment in the list.

This happens using `emacs-helm.sh`.

## Steps to reproduce (recipe)

Go to an org-mode heading containing any number of attachments. Press `C-c C-a o` to invoke `org-attach-open`.

## Backtraces if some (M-x toggle-debug-on-error)

Because of the enormous length of the backtrace, I put it [in a gist here](https://gist.github.com/jocap/32a39be2af3fa3e0e200a939fc780a92).

## Describe versions of helm, emacs, operating system etc.

* Helm is in a directory called `helm-20170425.328` - I assume that's the version?
* GNU Emacs 25.1.2
* Operating system: Ubuntu 16.04.1 LTS

Perhaps this is an issue with org-mode? I don't know. Maybe some Helm update broke the org-mode function. In the meantime I'll have to use `C-c C-a f` and *dired* to open my attachments.

**Comment by thierryvolpiatto** [comment]
John Ankarström <notifications@github.com> writes:

> Expected behavior
>
> When I press C-c C-a o on an org-mode headline, I should see, in a
> Helm interface, a list of attachments to open. The function
> (org-attach-open) works without Helm, but not with it.

It is working fine here.

>   * Helm is in a directory called helm-20170425.328 - I assume that's
>   the version?

Yes that is the Melpa version which is outdated (we are at 20170506.840).

>   * GNU Emacs 25.1.2
>   * Operating system: Ubuntu 16.04.1 LTS
>
> Perhaps this is an issue with org-mode? I don't know. Maybe some Helm
> update broke the org-mode function. In the meantime I'll have to use
> C-c C-a f and dired to open my attachments.

Updating helm should fix your problem.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by jocap** [comment]
@thierryvolpiatto:

Thank you! Of course I should have updated Helm. I'll close the issue :-)
