### ISSUE TITLE
Dired-do-copy  or Shift+c  in dired mode , Wrong type argument: stringp, nil

### ISSUE THREAD

**Issue by chxp** [emacs-helm/helm#1771]
In my emacs24.4.1, the second try to copy file in dired mode (M-x dired-do-copy or Shift+c ) failed as follows, while the first try is ok after open up emacs.

## Steps to reproduce (recipe)
M-x  Dired-do-copy  or Shift+c  in dired mode second try after open emacs,
the first try is ok

## Backtraces if some (M-x toggle-debug-on-error)
mini terminal show "Wrong type argument: stringp, nil"
the backtraces is in the attached file
[qusi1.txt](https://github.com/emacs-helm/helm/files/1003034/qusi1.txt)

## Describe versions of helm, emacs, operating system etc.
My helm is helm-20170513.2252 and helm-core is helm-core-20170514.2238 
Under  emacs24.4.1 in Ubuntu 14.04

**Comment by thierryvolpiatto** [comment]
chxp <notifications@github.com> writes:

> In my emacs24.4.1, the second try to copy file in dired mode (M-x
> dired-do-copy or Shift+c ) failed as follows, while the first try is
> ok after open up emacs.

I hardly see how it would work the first time and not the second, you
are (auto)loading something else than helm between the two calls, helm
nor dired are using read-file-name-internal as I see in your backtrace,
also why is ido involved ?

Please use ./emacs-helm.sh to reproduce your bug.

It is not reproductible here, though I didn't try on 24.4.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by chxp** [comment]
Thanks, I think it it helm conflict with ido mode ?

After I comment all the thing about the ido mode in .emacs , it works well

**Comment by thierryvolpiatto** [comment]
chxp <notifications@github.com> writes:

> Thanks, I think it it helm conflict with ido mode ?

You should use helm-mode and not ido-mode, because helm-mode allow
configuring commands to use ido or whatever, but ido-mode allow using
ido and nothing else.


-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997
