### ISSUE TITLE
helm-recentf file order doesn't change when switching buffers

### ISSUE THREAD

**Issue by mstorus** [emacs-helm/helm#1772]
## Expected behavior
I expected that when switching between buffers, the order of the recent files would change such that the most recently opened buffer would be first, and 2nd most recently opened buffer would be 2nd, and so on

## Actual behavior from `emacs-helm.sh`
After initially opening each file, and then switching between buffers, the order of the recent files doesn't change.

Recording:
![recentf](https://cloud.githubusercontent.com/assets/1182738/26222354/86f92db4-3bce-11e7-84fe-e79b9e7ab9d2.gif)

## Steps to reproduce (recipe)
open `README.md`, then `helm.el`, then `helm-files.el`. Then invoke `helm-recentf` and re-open some recent files. Note that the order of files displayed by `helm-recentf` doesn't change

## Describe versions of helm, emacs, operating system etc.
```
$ emacs --version
GNU Emacs 25.2.1
```

helm version `2.6.1`

Mac OS `10.12.4`

**Comment by thierryvolpiatto** [comment]
Mark Storus <notifications@github.com> writes:

> I expected that when switching between buffers, the order of the
> recent files would change such that the most recently opened buffer
> would be first, and 2nd most recently opened buffer would be 2nd, and
> so on

No, helm is just a front end of recentf end recentf is just registering
in find-file-hook AFAIR (i.e when you visit this file).

So helm is just showing the files in the order given by recentf itself.

Note that if you use both buffers source and recentf (e.g helm-mini),
your recentest buffers should popup on top, so there is no real interest
in filtering recentf files this way.

> After initially opening each file, and then switching between buffers,
> the order of the recent files doesn't change.

Buffers are one thing and files another.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by mstorus** [comment]
Thanks. Using `helm-mini` is a good solution for me
