### ISSUE TITLE
Hide leading stars in helm-source-org-headings-for-files

### ISSUE THREAD

**Issue by jagrg** [emacs-helm/helm#1775]
If org-hide-leading-stars is t, or org-indent-mode is on, I think it would make sense to also hide the first N-1 stars in the helm-org buffer. This is what I tried:

```
(defun helm-source-org-headings-for-files (filenames &optional parents)
  (helm-make-source "Org Headings" 'helm-org-headings-class
    :filtered-candidate-transformer 'helm-org-hide-leading-stars
    :parents parents
    :candidates filenames))

(defun helm-org-hide-leading-stars (candidates _source)
  (cl-loop for i in candidates
	   collect
	   (cons
	    (when (string-match "^\\(\\**\\)\\(\\* \\)\\(.*\n?\\)" (car i))
	      (replace-match "\\1\\2\\3" nil nil (car i)))
	    (cdr i))))
```

Now:

1. Open an Org buffer with a few subtrees.
2. M-x org-indent-mode
3. Set helm-org-headings-fontify to t
3. M-x helm-org-in-buffer-headings

The problem is it only works with helm-org-headings-fontify set to t. How can we do the same with helm-org-headings-fontify set to nil?

**Comment by jagrg** [comment]
I think I found a solution. Would you accept a PR?

```
(defun helm-org-hide-leading-stars (candidates _source)
  (cl-loop for i in candidates
	   collect
	   (cons
	    (if helm-org-headings-fontify
		(when (string-match "^\\(\\**\\)\\(\\* \\)\\(.*\n?\\)" (car i))
		  (replace-match "\\1\\2\\3" nil nil (car i)))
	      (when (string-match "^\\(\\**\\)\\(\\* \\)\\(.*\n?\\)" (car i))
		(let ((foreground (org-find-invisible-foreground)))
		  (if foreground
		      (concat
		       (propertize (replace-match "\\1" nil nil (car i))
				   'font-lock-face `(:foreground ,foreground))
		       (replace-match "\\2\\3" nil nil (car i)))
		    (replace-match "\\1\\2\\3" nil nil (car i))))))
	    (cdr i))))
```

**Comment by thierryvolpiatto** [comment]
Jonathan Gregory <notifications@github.com> writes:

> I think I found a solution. Would you accept a PR?

I have not a strong opinion on this as my org usage is quite basic (I
never heard about org-indent-mode before), so if you think this is a
good addition and it is not breaking what we had before, yes I accept a
PR.

Thanks.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by thierryvolpiatto** [comment]
@jagrg Can we close this issue or do you still have some work pending on it ?

**Comment by jagrg** [comment]
Yes. That was all. Thanks!

**Comment by thierryvolpiatto** [comment]
Jonathan Gregory <notifications@github.com> writes:

> Yes. That was all. Thanks!

Great, thanks for your work!

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997
