### ISSUE TITLE
mac os emacs el-get cant install helm

### ISSUE THREAD

**Issue by Leviathans** [emacs-helm/helm#1776]
‘helm-mode-line-string’
helm-types.el:87:37:Warning: reference to free variable
    ‘helm-generic-files-map’
helm-types.el:116:37:Warning: reference to free variable ‘helm-bookmark-map’

In end of data:
helm-types.el:282:1:Warning: the following functions are not known to be
    defined: helm-ediff-marked-buffers, helm-make-type

In toplevel form:
helm-utils.el:21:1:Error: Cannot open load file: No such file or directory, async

In toplevel form:
helm.el:32:1:Error: Cannot open load file: No such file or directory, async
make: *** [batch-compile] Error 1

**Comment by thierryvolpiatto** [comment]
This is a problem with el-get itself, not helm which is actually
installing correcly from git and from Melpa.
I am not using el-get, so I can't help you, you should ask about your
problem on el-get list.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by federkasten** [comment]
FYI here is my fork of el-get recipe for helm 2.7.0,

```elisp
(:name helm-2.7.0
       :description "Emacs incremental completion and narrowing framework"
       :type github
       :pkgname "emacs-helm/helm"
       :autoloads "helm-autoloads"
       :build (("sed" "-i" "s/elpa/el-get/g" "Makefile")
               ("sed" "-i" "s/async-\[.0-9\]*/emacs-async/g" "Makefile")
               ("make"))
       :depends (emacs-async)
       :checkout "bdc6711656954562ed721545ac22ee3a507110a3"
       :build/darwin `(("sed" "-i" ".old" "s/elpa/el-get/g" "Makefile")
                       ("sed" "-i" ".old" "s/async-\[.0-9\]*/emacs-async/g" "Makefile")
                       ("make" ,(format "EMACS_COMMAND=%s" el-get-emacs)))
       ;; Windows probably doesn't have make available so we fake it.
       :build/windows-nt
       (let ((generated-autoload-file (expand-file-name "helm-autoloads.el")) \
             (backup-inhibited t))
         (update-directory-autoloads default-directory)
         nil)
       :features "helm-config"
       :post-init (helm-mode))
```

I have tested on linux and macOS.

Latest Makefile requires `async` installed via elpa. (b133fb3e)
So you need to apply some patches into Makefile to build on el-get.

**Comment by federkasten** [comment]
I submitted a PR to el-get <https://github.com/dimitri/el-get/pull/2535>. It will be merged soon.

**Comment by rohni** [comment]
@federkasten Thanks very much for this, I edited my recipe, and it works a charm.
