### ISSUE TITLE
helm's completing-read emulation doesn't respect require-match = nil

### ISSUE THREAD

**Issue by dwang20151005** [emacs-helm/helm#1782]
How do I get the helm emulation of `completing-read` to input a value which is
not among the candidates?

I vaguely recall that helm used to do this.  There was always a candidate which was `[?]FOO` where `FOO` was exactly the pattern I had typed so far.  Am I mis-remembering?

## Expected behavior

In `emacs-helm.sh`, I type this into the scratch buffer:

    (progn
      (helm-mode -1)
      (completing-read "prompt: " '("foo" "bar" "baz")))

    (progn
      (helm-mode 1)
      (completing-read "prompt: " '("foo" "bar" "baz")))

Note that this means the `require-match` parameter is `nil`.

I eval each `progn` with `C-x C-e` and then type `f o RET`, expecting to get the
same value either way (`fo`).

## Actual behavior from `emacs-helm.sh` if possible (See note at bottom)

In fact, the value is different.

Without helm, I get `fo` as the completion.

With helm, I can only select the `foo` candidate.

## Steps to reproduce (recipe)

See above.

## Backtraces if some (M-x toggle-debug-on-error)

No backtrace.

## Describe versions of helm, emacs, operating system etc.

elpa helm-20170604.21

GNU Emacs 25.1.2 (x86_64-unknown-linux-gnu, X toolkit, Xaw scroll bars) of 2016-09-20

Linux igm-qws-u12112a 2.6.32-696.1.1.el6.x86_64 #1 SMP Tue Apr 11 17:13:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

## IMPORTANT NOTE:

If you are using a Unix or GNU-Linux system there is no excuses 
to not use `emacs-helm.sh` to reproduce your bug in 99% of the cases.

**Comment by thierryvolpiatto** [comment]
Should be fixed now, thanks.

**Comment by dwang20151005** [comment]
Thanks!
