### ISSUE TITLE
Eshell completion fails when PATH contains a non-readable folder

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#1785]
Completing any command will fail if PATH contains a non-readable folder.

## Steps to reproduce (recipe)

```
chmod -r <folder-in-your-path>
```
Then with the recommanded setup:
```
(add-hook
 'eshell-mode-hook
 (lambda ()
   (eshell-cmpl-initialize)
   (define-key eshell-mode-map [remap eshell-pcomplete] 'helm-esh-pcomplete)
   (define-key eshell-mode-map (kbd "C-r") 'helm-eshell-history)))
```
Run eshell and press `<TAB>`.

## Backtraces if some (M-x toggle-debug-on-error)

```
Debugger entered--Lisp error: (file-error "Opening directory" "Permission denied" "/home/ambrevar/personal/hackpool")
  file-name-all-completions("l" "/home/ambrevar/personal/hackpool/")
  eshell-complete-commands-list()
  #[0 "\300 \207" [eshell-complete-commands-list] 1]()
  pcomplete--here(#[0 "\300 \207" [eshell-complete-commands-list] 1] nil nil nil)
  #[0 "\300\301\302\211\211$\207" [pcomplete--here #[0 "\300 \207" [eshell-complete-commands-list] 1] nil] 5]()
  pcomplete-completions()
  helm-esh-get-candidates()
  apply(helm-esh-get-candidates nil)
  helm-funcall-with-source(((name . "Eshell completions") (init lambda nil (setq pcomplete-current-completions nil pcomplete-last-completion-raw nil) (remove-hook (quote minibuffer-setup-hook) (quote eshell-mode))) (candidates . helm-esh-get-candidates) (keymap keymap (escape . helm-keyboard-quit) (2 . helm-previous-page) (6 . helm-next-page) (f13 lambda nil (interactive) (helm-select-nth-action 12)) (f12 lambda nil (interactive) (helm-select-nth-action 11)) (f11 lambda nil (interactive) (helm-select-nth-action 10)) (f10 lambda nil (interactive) (helm-select-nth-action 9)) (f9 lambda nil (interactive) (helm-select-nth-action 8)) (f8 lambda nil (interactive) (helm-select-nth-action 7)) (f7 lambda nil (interactive) (helm-select-nth-action 6)) (f6 lambda nil (interactive) (helm-select-nth-action 5)) (f5 lambda nil (interactive) (helm-select-nth-action 4)) (f4 lambda nil (interactive) (helm-select-nth-action 3)) (f3 lambda nil (interactive) (helm-select-nth-action 2)) (f2 lambda nil (interactive) (helm-select-nth-action 1)) (menu-bar keymap (help-menu keymap (describe keymap (describe-mode . helm-help)))) (help keymap (109 . helm-help)) (23 . #[0 "\306\307\310\311\312\305!\313\"\314$\216\315\302!\210\316\304!\317\211\211\301=\203'
```

## Describe versions of helm, emacs, operating system etc.

Helm: master.
Emacs 25.2
OS: Arch Linux.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Completing any command will fail if PATH contains a non-readable
> folder.

Of course, this the expected behavior.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by Ambrevar** [comment]
Why? Completion can still work from the other members of PATH. A warning would be enough.

I am working on a site with ill-managed systems where the administrators removed the read rights of some folders in the PATH. Whatever the reason, I don't want this to prevent `helm-esh-pcomplete` from working.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Why? Completion can still work from the other members of PATH. A
> warning would be enough.
>
> I am working on a site with ill-managed systems where the
> administrators removed the read rights of some folders in the
> PATH. Whatever the reason, I don't want this to prevent
> helm-esh-pcomplete from working.

Sorry but not sure to understand.
You mean that you cant complete a directory when this one contains a
non-readable subdirectory ?

1) mkdir -p ~/tmp/test/test2/test3
2) sudo chmod a-r ~/tmp/test/test2/test3
3) from eshell I can complete with TAB tmp/, test/, test2/ but not test3/.

Which is correct.

I can send a message when trying to complete on test3/, e.g
"No completion for test/test2/test3" 

Is it what you want ?

Thanks.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by Ambrevar** [comment]
No, I did not mean completing files/paths, I meant the _command_ itself, i.e. the first word.
Press `<TAB>` directly at the empty prompt or _on the first word of the prompt_.
```
em<TAB>
```
will fail to complete to `emacs`.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> No, I did not mean completing files/paths, I meant the command itself, i.e. the first word.
> Press <TAB> directly at the empty prompt or on the first word of the prompt.
>
> em<TAB>
>
> will fail to complete to emacs.

Hmm, try to reproduce from emacs -Q without helm, only M-x eshell and
TAB on something, if you have the same problem, it is an emacs bug.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by Ambrevar** [comment]
My bad, you are right. I'll report this.

**Comment by Ambrevar** [comment]
Reported here: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=27300
