### ISSUE TITLE
Show kmacro name in `helm-execute-kmacro`

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#1786]
Emacs' kmacros can be named with `kmacro-name-last-macro`. It would be nice to display that name along the command in `helm-execute-kmacro`.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Emacs' kmacros can be named with kmacro-name-last-macro. It would be
> nice to display that name along the command in helm-execute-kmacro.

There is no way actually in emacs to make the relation with a macro (a
vector) with its symbol-name given previously with
kmacro-name-last-macro, at least reliabily.
IOW it would be complex to implement this for the few benefit it provides.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by Ambrevar** [comment]
Looks like you are right, the current definition of `kmacro-name-last-macro` does not seem to allow that.
It would be possible to advice the function to store the name in a global list, but I guess that's beyond the scope of Helm.
