### ISSUE TITLE
helm-top: Make sorting dynamic

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#1795]
## Expected behavior

Pressing `M-P` and `M-M` should sort by CPU and memory respectively.

## Actual behavior

It does not. The reason is that my `top` columns do not match `helm-top-sort-colums-alist`.
I had to change its value from

	((com . 11) (mem . 9) (cpu . 8) (user . 1))

to

	((com . 11) (mem . 7) (cpu . 6) (user . 1))

My `top` comes from procps-ng 3.3.12-1 (Arch Linux).

I understand that the column order will (probably?) change from OS to OS.
Is there a more reliable way to implement that though?

If not, I suggest you add some document to `C-h m` and to the docstring of `helm-top`.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Expected behavior
>
> Pressing M-P and M-M should sort by CPU and memory respectively.
>
> Actual behavior
>
> It does not. The reason is that my top columns do not match helm-top-sort-colums-alist.
> I had to change its value from
>
> ((com . 11) (mem . 9) (cpu . 8) (user . 1))
>
> to
>
> ((com . 11) (mem . 7) (cpu . 6) (user . 1))
>
> My top comes from procps-ng 3.3.12-1 (Arch Linux).
>
> I understand that the column order will (probably?) change from OS to OS.
> Is there a more reliable way to implement that though?

No, there is too much difference with diverses versions provided, on
MacOs, top is just not usable and people are using `ps`.

> If not, I suggest you add some document to C-h m and to the docstring of helm-top.

Isn't it enough documented in `helm-top-command` docstring ?

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by Ambrevar** [comment]
You are right, I completely forgot that one.
