### ISSUE TITLE
helm-ff: Open marked files externally

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#1796]
With `helm-find-files` pressing `C-c C-x` will not open all marked files but only one file.

It would be nice to be able to one program over a sequence of files. Many programs support this, e.g. `mpv $*` for a playlist, or `sxiv $*` for a slideshow.

We can associate the program with the extension of the first selected file. The user is responsible for the rest of the selection.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> With helm-find-files pressing C-c C-x will not open all marked files
> but only one file.
>
> It would be nice to be able to one program over a sequence of
> files. Many programs support this,

Many also are not supporting this, so it is better to not allow marked.


> e.g. mpv $* for a playlist, or sxiv $* for a slideshow.

I suggest you make eshell aliases for such commands, and use then M-!
on your marked files from helm-find-files (It is documented in hff).

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by Ambrevar** [comment]
This is the same reasoning as helm-top #1794: Leave the choice to the user. There is no point in restricting it.

Besides, if a program does not support multiple files it will simply use the first one, which is the current behaviour.

**Comment by thierryvolpiatto** [comment]
Sorry, but I disagree on this one for the reasons specified above, closing now.
