### ISSUE TITLE
Size of eshell completion buffer

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#1797]
When the Eshell prompt is at the bottom, the `helm-esh-pcomplete' window is only about 4 lines high when displaying at the bottom.

Is there a way to configure that? I could not find it in the source code, I might have missed it.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> When the Eshell prompt is at the bottom, the `helm-esh-pcomplete' window is only about 4 lines high when displaying at the bottom.
>
> Is there a way to configure that?

See `helm-show-completion-use-special-display`.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by Ambrevar** [comment]
That was it, thanks!
