### ISSUE TITLE
helm-occur does not immediately pop up the helm buffer when on two heading stars or more

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#1798]
## Expected behavior

Switch to org-mode, create a header-2 or deeper, e.g.
```
** header
```
Move point to one of the `*` and run `helm-occur`. The occur window should appear immediately.

## Actual behavior from `emacs-helm.sh`

The window only appears on first key press.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Expected behavior
>
> Switch to org-mode, create a header-2 or deeper, e.g.
>
> ** header
>
> Move point to one of the * and run helm-occur. The occur window should appear immediately.
>
> Actual behavior from emacs-helm.sh
>
> The window only appears on first key press.

Should be fixed now, thanks.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997
