### ISSUE TITLE
Allow for creating directories when renaming in helm-ff

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#1799]
With helm-ff we can create directories while browsing by appending a `/` to the query and pressing `RET`.

However, this behaviour is no longer available once we have selected some files for renaming with `M-R`. It forces the user to ensure the destination folder exists before selecting the files for renaming.
It would be nice to have the same behaviour as for normal browsing.

**Comment by thierryvolpiatto** [comment]
Done, thanks.
