### ISSUE TITLE
emacs-helm.sh fails in Emacs: eval-buffer: Cannot open load file: No such file or directory, async

### ISSUE THREAD

**Issue by alphapapa** [emacs-helm/helm#1800]
## Expected behavior

`./emacs-helm.sh` used to work, launching Emacs and loading Helm, etc.

## Actual behavior from `emacs-helm.sh` if possible (See note at bottom)

Now it starts Emacs and this error is displayed in the minibuffer:

> eval-buffer: Cannot open load file: No such file or directory, async

## Steps to reproduce (recipe)

Checkout `master`.
Run `./emacs-helm.sh`

## Describe versions of helm, emacs, operating system etc.

Emacs 25.1.1 on Ubuntu 14.04
`async` 1.9.2 is installed in `~/emacs.d/elpa/async-20170610.2241`.

**Comment by thierryvolpiatto** [comment]
I finally could reproduce by uninstalling emacs-async and installing it from melpa.

**Comment by thierryvolpiatto** [comment]
Should work now.

**Comment by alphapapa** [comment]
I see, thanks.  I was running the script from `~/src/helm`, which I thought was the intended way.
