### ISSUE TITLE
helm-locate outputs incorrect Chinese characters while using es.exe to locate files with Chinese names

### ISSUE THREAD

**Issue by gnocil** [emacs-helm/helm#1801]
## Expected behavior
I use es-1.1.0.6a to helm-locate files. All the mini-buffers generated by helm can display Chinese characters correctly using UTF-8 except the one generated by helm-locate.

I use UTF-8 as the default encoding format both in file editing environment and shell environment. 

## Describe versions of helm, emacs, operating system etc.
helm 20170506.840 
emacs 25.2
OS win7-x64

## IMPORTANT NOTE:

If you are using a Unix or GNU-Linux system there is no excuses 
to not use `emacs-helm.sh` to reproduce your bug in 99% of the cases.

**Comment by thierryvolpiatto** [comment]
gnocil <notifications@github.com> writes:

> Expected behavior
>
> I use es-1.1.0.6a to helm-locate files. All the mini-buffers generated
> by helm can display Chinese characters correctly using UTF-8 except
> the one generated by helm-locate.

Did you try the es command line from a terminal to see if the output is
correct ?

I doubt it is the helm fault, my guess is that everything either needs
to be configured properly (is there a UTF-8 option somewhere?) or has a
bug.

Unfortunately, I can't test myself as I have not anymore a Windows box.

> I use UTF-8 as the default encoding format both in file editing
> environment and shell environment.

But is "Everything" configured to use UTF-8 ?

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by aligua** [comment]
reporter, try if this help? (btw, I just a passer, happened to see the question in google search result so comeby to leave a word...)
(set-language-environment 'Chinese-GBK)
    (setenv "LANG" "zh_CN.GBK")
    (prefer-coding-system 'utf-8-unix)

**Comment by gnocil** [comment]
![_20170703190133](https://user-images.githubusercontent.com/7325448/27790195-0f19443c-6022-11e7-83a1-dd5f297c2dcc.png)

it doesn't work

**Comment by gnocil** [comment]
![_20170703190133](https://user-images.githubusercontent.com/7325448/27790246-4b04c908-6022-11e7-92c0-43d41ed58af8.png)

It doesn't work.

**Comment by thierryvolpiatto** [comment]
Can you try same `es` command line from an emacs shell buffer (shell or eshell) instead of DOS console?

Thanks.

**Comment by gnocil** [comment]
![default](https://user-images.githubusercontent.com/7325448/27790741-6b32b878-6024-11e7-8ebf-f40f91193b16.PNG)

**Comment by thierryvolpiatto** [comment]
gnocil <notifications@github.com> writes:

> default 

Ok we know now the problem is not specific to helm, but more generally
to emacs configuration.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by thierryvolpiatto** [comment]
Do you have the same output from emacs -Q (always in (e)shell) ?

**Comment by gnocil** [comment]
![image](https://user-images.githubusercontent.com/7325448/27791260-bdb6f5c6-6026-11e7-8213-8661d54d3997.png)

**Comment by thierryvolpiatto** [comment]
Here we are, something in your .emacs is wrong.
What value of `shell-file-name` are you using in .emacs ?

**Comment by gnocil** [comment]
shell-file-name is a variable defined in ‘C source code’.
Its value is
"D:/emacs-25.2/libexec/emacs/25.2/x86_64-w64-mingw32/cmdproxy.exe"
Original value was 
"C:/msys64/home/Kel/repo/emacs/nt/cmdproxy.exe"

**Comment by thierryvolpiatto** [comment]
So it is something else.

**Comment by gnocil** [comment]
Emacs gives the same value when I run it under -Q, so why and how to solve this problem?

**Comment by gnocil** [comment]
I didn't change the value and I'm sure it's the default value when emacs was installed.

**Comment by thierryvolpiatto** [comment]
I meant it is not `shell-file-name` which is causing the problem but something else in your config or a third party package which is modifying something wrongly.

**Comment by thierryvolpiatto** [comment]
Try also to see what is different from emacs -Q and your current emacs by running M-x `describe-coding-system` from one of the shell buffers.

**Comment by gnocil** [comment]
Thanks! I will take a try.

祝好！

李西聪


2017-07-03 20:56 GMT+08:00 Thierry Volpiatto <notifications@github.com>:

**Comment by aligua** [comment]
gnocil,
Just keep dichotomy (二分法) commenting your own configuration then you should be able to locate the wrong configuration.
And for my suggested configuration above, have you tried eval them all in same order as I posted?

**Comment by alphapapa** [comment]
This package may help you bisect your init file to find the problem:

https://github.com/Malabarba/elisp-bug-hunter

The `bug-hunter-init-file` command is very good.

**Comment by aligua** [comment]
seems nice

alphapapa <notifications@github.com>于2017年7月12日 周三下午3:09写道：

**Comment by damon98xp** [comment]
Here is  workaround works for me, for using 65001 code page

(defun my/helm-locate-wrap-cmd (orig-fun &rest args)
  "Run helm-locate command under cmd.exe with UTF-8 codepage."
  (let ((helm-locate-command
         (format "cmd.exe /c chcp 65001>nul & %s" helm-locate-command))
        (default-process-coding-system '(utf-8-dos . utf-8-dos)))
    (apply orig-fun args)))

(with-eval-after-load 'helm-locate
  (advice-add 'helm-locate-init :around #'my/helm-locate-wrap-cmd))

;; To undo:
;; (advice-remove 'helm-locate-init #'my/helm-locate-wrap-cmd)
