### ISSUE TITLE
filter buffer makes emacsclient not responding

### ISSUE THREAD

**Issue by Juanchen1190** [emacs-helm/helm#1802]
## Expected behavior
When I input `**` with mistakes during filter buffer, I want delete one of the `*`, but the emacsclient is not responding.

## Steps to reproduce (recipe)
1. Using emacs demon and emacsclient to run emacs. 
2. `C-x b` invoke helm-mini
3.  input two asterisk(*)

## Describe versions of helm, emacs, operating system etc.
helm-20170612.2141
emacs-25.2
macos 10.12.4

**Comment by thierryvolpiatto** [comment]
Juanchen <notifications@github.com> writes:

> Expected behavior
>
> When I input ** with mistakes during filter buffer, I want delete one of the *, but the emacsclient is not responding.
>
> Actual behavior from emacs-helm.sh if possible (See note at bottom)
>
> Steps to reproduce (recipe)
>
>  1. Using emacs demon and emacsclient to run emacs.
>  2. C-x b invoke helm-mini
>  3. input two asterisk(*)

Can't reproduce.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by thierryvolpiatto** [comment]
Juanchen <notifications@github.com> writes:

> Expected behavior
>
> When I input ** with mistakes during filter buffer, I want delete one
> of the *, but the emacsclient is not responding.
>
> Actual behavior from emacs-helm.sh if possible (See note at bottom)

You can try from emacs-helm.sh from the helm directory with:

./emacs-helm.sh --daemon
emacsclient -c

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by Juanchen1190** [comment]
I tried emacs-helm.sh, but no useful information appeared.

Here is some information that I know, hope it can help you:

1. I can't reproduce this issue in Ubuntu, it seems it only appears in mac os.
2. When the error appears, the emacs server is frozen, any input is not responding(include C-g). I need to kill the Emacs server process with the activity monitor. And the activity monitor shows that emacs takes more than 90% CPU. Is the server waiting something to finish?
3. When I input *c* ,  it runs properly. But when I delete the 'c' and left two asterisks in the minibuffer, it was frozen.

**Comment by thierryvolpiatto** [comment]
Juanchen <notifications@github.com> writes:

> I tried emacs-helm.sh, but no useful information appeared.
>
> Here is some information that I know, hope it can help you:

Doesn't help much as I use Ubuntu (LinuxMint) and I can't reproduce bug.
I would like to know which source is hanging emacs, could you try to
reproduce bug separately for each source individually:

Take the list of sources used by helm-mini (helm-mini-default-sources)
and run helm on each of these sources (replace source1 with the relevant
source)


    (helm :sources 'source1 ;; from helm-mini-default-sources
          :buffer "*helm test source1")

Also are you using different versions of emacs or the same version on
each OS ?

BTW can you can get a helm-debug buffer?

Create a directory of your choice, e.g "/home/you/helm-debug"

(setq helm-debug-root-directory "/home/you/helm-debug")

M-x helm-mini RET C-h C-d

Try to reproduce the bug

You should have now in the directory a subdirectory (dated) containing
the relevant debug buffer.

Thanks.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by Juanchen1190** [comment]
I follow these steps, but the helm-debug directory is empty. 
I found an another information:
I comment the body of the `helm-funcall-with-source` and I can input two * in the minibuffer, so I write `source-name`, `functions` and `args` to a file. 

Hope this file can give you some information.

[helm.log.zip](https://github.com/emacs-helm/helm/files/1108916/helm.log.zip)

**Comment by thierryvolpiatto** [comment]
Juanchen <notifications@github.com> writes:

> I follow these steps, but the helm-debug directory is empty.

Probably you fail to follow the steps, helm-debug have no bug actually,
nevermind.


> I found an another information: I comment the body of the
> helm-funcall-with-source and I can input two * in the minibuffer, so I
> write source-name, functions and args to a file.

Sorry I don't understand what you are doing here.

> Hope this file can give you some information.

No, it is of no help.

I asked you in previous post to tell me in which source the bug happen,
without this information I can do nothing.

Thanks.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by Juanchen1190** [comment]
The bug happens in `helm-source-recentf` and `helm-source-buffer-not-found`.

These are no log file when the bug happens. Here are some logs and pictures in  
 ` 'helm-source-buffers-list ` source, which behaves properly but differently to Ubuntu.

[helm-debug-20170629.zip](https://github.com/emacs-helm/helm/files/1110754/helm-debug-20170629.zip)

**Comment by thierryvolpiatto** [comment]
Juanchen <notifications@github.com> writes:

> The bug happens in helm-source-recentf and helm-source-buffer-not-found.

Hmm, I will have a look to recentf but I really think it is more a bug
with the emacs you use on MacOS than a helm bug, otherwise it would be
reproductible on both platforms.
Be sure it is not recentf that hang emacs when you start recentf-mode.
 
> These are no log file when the bug happens. Here are some logs and pictures in
> 'helm-source-buffers-list source, which behaves properly but differently to Ubuntu.
>
> helm-debug-20170629.zip

I am unable to open these files, looks pure garbage, also I don't like
having to unzip such attached files, please provide your screenshots with
the github issues interface.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by Juanchen1190** [comment]
Here are my screenshots:
Note that when input two asterisk, the Buffers is empty:

<img width="770" alt="1_asterisk" src="https://user-images.githubusercontent.com/12491689/27671811-4a4ea300-5cc9-11e7-93f5-0baca1e079b7.png">

![2_asterisks](https://user-images.githubusercontent.com/12491689/27671810-4a4cea92-5cc9-11e7-9c8a-32a5439f7a0c.png)

![3_asterisks](https://user-images.githubusercontent.com/12491689/27671812-4a540ab6-5cc9-11e7-8e4d-6c4795223d57.png)

And here is the log file:
[20170629-102753.txt](https://github.com/emacs-helm/helm/files/1110913/20170629-102753.txt)

**Comment by thierryvolpiatto** [comment]
You said that the source that is hanging emacs is the recentf source, or the create new buffer source, and you show me screenshots and debug log of buffers source ??
Please try to debug recentf only source if it is the one that hang emacs.
Thanks.

**Comment by thierryvolpiatto** [comment]
Also can you reproduce the bug when using a normal emacs session (no daemon).

**Comment by Juanchen1190** [comment]
It didn't appear in a normal emacs session.
I said that when debug recentf only source or the create new buffer source, there is no debug log.
Why I give you screenshots and debug log of buffers source is that It looks different to a normal emacs session, and looks different to a Ubuntu daemon emacs session. 
A normal emacs session and a Ubuntu daemon emacs session behaviors same when input two asterisks.

And here is the screenshot when the bug happened, I think it is not special.
![image](https://user-images.githubusercontent.com/12491689/27717142-d1d6e7cc-5d75-11e7-9e71-77ef095632b2.png)

**Comment by thierryvolpiatto** [comment]
Juanchen <notifications@github.com> writes:

> It didn't appear in a normal emacs session.  I said that when debug
> recentf only source or the create new buffer source, there is no debug
> log.  Why I give you screenshots and debug log of buffers source is
> that It looks different to a normal emacs session, and looks different
> to a Ubuntu daemon emacs session.  A normal emacs session and a Ubuntu
> daemon emacs session behaviors same when input two asterisks.

I think there is nothing to do on the helm side for this, the bug IMO is
related to the emacs MacOs version you are using; The best you have to
do is trying to launch emacs inside GDB and have a good backtrace from
there when emacs crash or when you have to kill it and submit the bug to
emacs.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by thierryvolpiatto** [comment]
Juanchen <notifications@github.com> writes:

> It didn't appear in a normal emacs session.

I notice now, looking at screenshot that you are not using a standard
cursor, you have changed the value of cursor-type (emacs-helm.sh is not
changing this), this is maybe not supported by emacs running in terminal
(daemon) and perhaps also when used in addition with your locale or
something else ?
If it is the case perhaps you can reproduce the bug in a normal emacs
session but running in a tty ?

Don't know, was just a thought.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by thierryvolpiatto** [comment]
One thing I notice also:

with emacs 24.5 entering "******" in the prompt take 95% CPU and returns
to normal immediately whereas in emacs 25.2 it takes 100% CPU and stays
at 100% if I don't delete the "*" in minibuffer, so perhaps it is
related to emacs-25.2 which is known to be unstable on MacOs.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by thierryvolpiatto** [comment]
I have commited a fix that's try to workaround the fact that emacs
doesn't send an invalid-regexp error on repeated "*" or "?" (i.e you should
be able to reproduce your bug with "???????????" as well), please try it
and see if it prevent emacs taking 100% CPU when entering more than 1
"*" or "?".

Thanks.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by Juanchen1190** [comment]
Yes, the Emacs runs nicely when repeated "*".
I reproduce this bug with "??", "*?", "?*", but it doesn't matter, I never use them.

Thanks a lot.

**Comment by thierryvolpiatto** [comment]
Juanchen <notifications@github.com> writes:

> Yes, the Emacs runs nicely when repeated "".
> I reproduce this bug with "??", "?", "?*",

Thanks, I have blacklisted them as well, though that doesn't prevent
their usage when embedded inside pattern.

The problem is that emacs doesn't return invalid-regexp error on such
regexps.

Also there is no reason emacs hang forever with MacOs and not Linux.
Maybe we missed something about MacOs ?  Unfortunately I have no access
to such system.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997
