### ISSUE TITLE
helm-esh-pcomplete does not escape properly

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#1803]
## Expected behavior

Run in eshell:
$ touch 'File(with)special&chars'
$ ls Fil<TAB>

With <TAB> bound to `helm-esh-pcomplete` like documentation suggests.

## Actual behavior from `emacs-helm.sh`

The line is completed to

	$ ls 'File(with)special&chars'

instead of

	$ ls 'File\(with\)special\&chars'

There might be more characters than just those 3, I haven't investigated.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> The line is completed to
>
> $ ls 'File(with)special&chars'
>
> instead of
>
> $ ls 'File\(with\)special\&chars'

Indeed, should be fixed now.

Thanks.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by Ambrevar** [comment]
Perfect!

**Comment by Ambrevar** [comment]
Sorry, this is actually not correct. It least in one case: completing a token starting with `~` will escape it while it should remain unescaped to mean `$HOME`. `eshell-pcomplete` does that correctly.
