### ISSUE TITLE
helm-ff-switch-to-eshell cannot switch to numbered eshell sessions 

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#1804]
## Steps to reproduce

- Start two eshell sessions, go to the second one (`*eshell*<2>` by defaylt).
- Call `helm-find-files`, change directory and press `M-e`.

## Expected behaviour

Back to `*eshell*<2>`, we should be in the folder selected by helm-ff.

## Actual behaviour

We are brought back to `*eshell*`, in the selected folder.

I think it would be much more intuitive and useful to change folder in the last used eshell session.

In the current state we cannot use helm-ff to change directory in eshell sessions >1.

Besides, if you kill `*eshell*` and stick to `*eshell*<2>`, `helm-find-files`+`M-e` will create a new `*eshell*` and change dir there, which is rather disturbing.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I think it would be much more intuitive and useful to change folder in
> the last used eshell session.

Even better is providing completion on eshell buffers when more than
one.
Alternatively you can now use a numeric prefix arg if you know the
eshell number you want to switch to (or create a new one if you want
with a pref arg > to last eshell buffer num).

Have a try and let me know if new behavior fit your needs.

Thanks.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by Ambrevar** [comment]
Nice! It's a great idea and it works well!

As a bonus, it'd be nice to get the last eshell session the selection default :)

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Nice! It's a great idea and it works well!
>
> As a bonus, it'd be nice to get the last eshell session the selection default :)

Yes, it's because I was sorting, no sorting should give you the buffer
list in the right order.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by Ambrevar** [comment]
Indeed. Thanks!
