### ISSUE TITLE
helm-core-20170630.19.tar.gz is missing from melpa

### ISSUE THREAD

**Issue by thraxil** [emacs-helm/helm#1805]
## Steps to reproduce (recipe)

* Go to http://melpa.org/#/helm-core
* click 'Download' button
* get a 404 on http://melpa.org/packages/helm-core-20170630.19.tar

doing a package install from within emacs also hits this problem.

**Comment by xuchunyang** [comment]
The button points to https://melpa.org/packages/helm-core-20170701.629.tar right now. Try refresh the webpage in your web browser and `M-x package-refresh-contents` in your Emacs.

Unfortunately, Melpa doesn't keep old versions of packages, thus users of Melpa are supposed to `M-x package-refresh-contents` every time before installing a package.

**Comment by thraxil** [comment]
Cool. Thanks.
