### ISSUE TITLE
[Question/Suggestion] Create File / truncate-line / recentf path for helm-for-files

### ISSUE THREAD

**Issue by frankie8518** [emacs-helm/helm#1807]
Note: Personally, I like `helm-for-files` more than `helm-find-file`s and `helm-mini`, so..
## Expected behavior

1. Can we have "create file" like `helm-find-file` in `helm-for-files`?

2. Can we have truncate line in `helm-for-files` in buffer list source just like `helm-mini`? (Because I set default side right)

3.  I think it might be more clean and readable to many people if we could print out just `~/.....` in recentf source when candidates it's under home directory instead of absolute path.

4. It's a surprise to me that I can press `C-x C-s` to save a buffer, and I haven't find any page describe this, so I would like to know more action to buffer/file not mentioned in action menu, any suggestion?

**Comment by thierryvolpiatto** [comment]
frankie8518 <notifications@github.com> writes:

> Note: Personally, I like helm-for-files more than helm-find-files and helm-mini, so..

However helm-find-files is much more powerful than helm-for-files and
helm-multi-files, all my efforts are concentred on the development of
helm-find-files...

> Expected behavior
>
>  1. Can we have "create file" like helm-find-file in helm-for-files?

Just hit C-x C-f from helm-for-files and create your file or directory.

>  2. Can we have truncate line in helm-for-files in buffer list source
>  just like helm-mini? (Because I set default side right)

Done.

>  3. I think it might be more clean and readable to many people if we
>     could print out just ~/..... in recentf source when candidates
>     it's under home directory instead of absolute path.

You can toggle the ABS view.

For the helm buffers commands, they are all mentioned in help (see
mode-line).

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by frankie8518** [comment]
1. For trucate line in`helm-for-files`, it seems that only `helm-20170704` is available now. So I try to add the source code directly and eval it, but the effect disappears after restarting Emacs. Anything I can do?

2. > You can toggle the ABS view.

Sorry, I just can't find what or where can I do this. Could you explain more about this?

**Comment by thierryvolpiatto** [comment]
frankie8518 <notifications@github.com> writes:

>  1. For trucate line inhelm-for-files, it seems that only helm-20170704 is available now. So I try to add the source code directly and eval it, but the
>     effect disappears after restarting Emacs. Anything I can do?

Wait until the Melpa build finish (https://melpa.org/#/).
    
>  2.
>         You can toggle the ABS view.
>        
> Sorry, I just can't find what or where can I do this. Could you explain more about this?

If you look at your mode-line, you will see "C-h m:Help", use it widely.
For the answer it is `C-]`.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by frankie8518** [comment]
Sorry for not reading help carefully. And I find two things not mentioned in help or customized group. 
1. When I press `C-]` it leave with only file name, can we have a quote behind file name to show which directory it is?
2. Can we set hide information default?

**Comment by thierryvolpiatto** [comment]
frankie8518 <notifications@github.com> writes:

> Sorry for not reading help carefully. And I find two things not mentioned in help or customized group.
>
>  1. When I press C-] it leave with only file name, can we have a quote
>  behind file name to show which directory it is?

Now whole path is shown abbreviated and basename, well only basename as
before.

>  2. Can we set hide information default?

What is "information default" ?

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by thierryvolpiatto** [comment]
As a side note, you have in `helm-find-files` a much better history (load and save quickly at start and stop of emacs among other things) than `recentf` (I have personally disabled completely recentf), available with `C-c h` in addition of the directory history available from `M-p`.

**Comment by frankie8518** [comment]
Umm... Sorry for my poor comprehension of English..

> Now whole path is shown abbreviated and basename, well only basename as before.

Is that mean I can see abbreviated file path every time when starting a helm buffer relating to files, after updating?

> What is "information default" ?

Sorry, set "hide-information" default.
Anyway, what I would like to have is to set abbreviated path default.

**Comment by frankie8518** [comment]
Additionally, I want share some opinions about search a file or a directory.
1. I think it's wonderful for me to just type file name which I want to access, and skip complicated structure of directory, It's a kind of abstraction, I thought. And it may help people to focus on what he want to do with that file without spending energy on how to get to it.
2. I like `helm-for-files-preferred-list` , it just like lego and I can put source I prefered into one piece.
Just personal opinion, for your reference.
And I also try to press `C-c h` and `M-p` int `helm-for-files`, it's cool and useful. I think my work flow can't be without these. Appreciate for your great works.

**Comment by thierryvolpiatto** [comment]
frankie8518 <notifications@github.com> writes:

> Anyway, what I would like to have is to set abbreviated path default.

It is now the default and when you hit C-] it goes to basename.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by thierryvolpiatto** [comment]
frankie8518 <notifications@github.com> writes:

> Additionally, I want share some opinions about search a file or a directory.
>
>  1. I think it's wonderful for me to just type file name which I want
>     to access, and skip complicated structure of directory, It's a
>     kind of abstraction, I thought.  And it may help people to focus
>     on what he want to do with that file without spending energy on
>     how to get to it.  2. I like helm-for-files-preferred-list , it
>     just like lego and I can put source I prefered into one piece.
>     Just personal opinion, for your reference.  And I also try to
>     press C-c h and M-p int helm-for-files, it's cool and useful. I
                              ^^^^^^^^^^^^^^
                              helm-find-files (just for not confusing other readers ;-))
>     think my work flow can't be without these. Appreciate for your
>     great works.

Thanks.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997
