### ISSUE TITLE
Impossible to add magnet links with transmission.el?

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#1808]
## Expected behavior

Pressing 'a' in the transmission window prompts for a torrent file or a magnet link.
When `helm-mode` is on, the helm prompt takes over.

If the user wants to add a magnet link, he/she has to clear the prompt first and then paste the link.

## Actual behavior

The following message is returned:

> invalid or corrupt torrent file

## Steps to reproduce (recipe)

- M-x helm-mode
- M-x transmission
- `a`
- `C-k` to clear the helm prompt
- Copy the magnet link.
- (Back to the transmission buffer) `C-y RET`

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Expected behavior
>
> Pressing 'a' in the transmission window prompts for a torrent file or a magnet link.
> When helm-mode is on, the helm prompt takes over.

I am not sure to understand (I don't use transmission.el).
I just downloaded the code and found this function:

    (defun transmission-read-strings (prompt &optional collection)
      "Read strings until an input is blank, with optional completion.
    PROMPT and COLLECTION are the same as in `completing-read'.
    Returns a list of non-blank inputs."
      (let (res entry)
        (catch :finished
          (while t
            (setq entry (if (not collection) (read-string prompt)
                          (completing-read prompt collection nil)))
            (if (and (not (string-empty-p entry))
                     (not (string-blank-p entry)))
                (progn (push entry res)
                       (setq collection (delete entry collection)))
              (throw :finished (nreverse res)))))))


AFAICT it is working fine with helm:
    (transmission-read-strings "test: " '("foo.torrent" "bar.torrent" "baz.torrent"))
Choose e.g "bar.torrent" with RET then hit C-RET to exit.

I didn't try to load the whole transmission.el library and really try to
add a torrent file, but I guess it would work similarly.

Let me know if I missed something.

Thanks.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by Ambrevar** [comment]
Torrent files work fine, magnet links don't. Try adding this:
```
magnet:?xt=urn:btih:88928d3ca7f5d71e39037279c1ee787a80de6ea0&dn=archlinux-2017.07.01-x86_64.iso&tr=udp://tracker.archlinux.org:6969&tr=http://tracker.archlinux.org:6969/announce
```

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Torrent files work fine, magnet links don't. Try adding this:
>
> magnet:?xt=urn:btih:88928d3ca7f5d71e39037279c1ee787a80de6ea0&dn=archlinux-2017.07.01-x86_64.iso&tr=udp://tracker.archlinux.org:6969&tr=http://tracker.archlinux.org:6969/announce

Sorry but as I said I don't use transmission.el.
I tried installing it but it failed immediately so I can't try what you
suggest.

So please try to make the effort of debugging a bit this so what we know
what transmission.el function is triggered.

Thanks.

PS: When you know which is the function you add magnet with, you can
disable helm on it with `helm-completing-read-handlers-alist`.

e.g 
    (add-to-list 'helm-completing-read-handlers-alist '(transmission-? . nil))

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by thierryvolpiatto** [comment]
Despite the lack of informations, I guess that transmission.el function you use is `transmission-add` which uses `read-file-name` both for reading a string or a filename, which is pretty unclear, but why not.
I still unsure of what you expect but I have modified `*-read-file-name` so that it returns exactly what it find in minibuffer, HTH.

**Comment by Ambrevar** [comment]
I don't have access to transmission.el at the moment.

You said transmission.el failed on startup. Make sure you've got the transmission program installed and that you've started `transmission-daemon`.

Your fix looks about right in the case of transmission.el, but will this have side-effects? Why was helm calling `expand-file-name` in the first place?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I don't have access to transmission.el at the moment.
>
> You said transmission.el failed on startup. Make sure you've got the
> transmission program installed and that you've started
> transmission-daemon.

They are installed but seems they are not configured correctly and I
don't want to bother about this.

> Your fix looks about right in the case of transmission.el, but will
> this have side-effects?

I think it is safe, I will make more tests before next release anyway.


> Why was helm calling expand-file-name in the first place?

IIRC it is vestige of code that was needed when I haven't already
implemented :default.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by Ambrevar** [comment]
It works! Thank you for the update.
Feel free to close it if you have no further questions.

**Comment by thierryvolpiatto** [comment]
Oops, I have added reference to two commits related to #1809 here by error, closing now.

Thanks.

**Comment by tidux** [comment]
This behavior has returned in Helm as of 20171202.133.

**Comment by thierryvolpiatto** [comment]
I tried to yank a magnet link in the prompt of `transimission-read-strings` and it worked, did I miss something? (be sure to use C-RET to exit the minibuffer)

```elisp
(defun transmission-read-strings (prompt &optional collection)
  "Read strings until an input is blank, with optional completion.
PROMPT and COLLECTION are the same as in `completing-read'.
Returns a list of non-blank inputs."
  (let (res entry)
    (catch :finished
      (while t
        (setq entry (if (not collection)
                        (read-string prompt)
                      (completing-read prompt collection nil)))
        (if (and (not (string-empty-p entry)) (not (string-blank-p entry)))
            (progn (push entry res) (setq collection (delete entry collection)))
          (throw :finished (nreverse res)))))))
(transmission-read-strings "test: " '("foo.torrent" "bar.torrent" "baz.torrent"))
```
