### ISSUE TITLE
helm-find-files does not automatically select files starting with `[`

### ISSUE THREAD

**Issue by dakrone** [emacs-helm/helm#1809]
## Expected behavior
When I invoke `helm-find-files` (`C-x C-f`) from dired with the point on a file name, I expect that file to be already highlighted in the helm buffer.

## Actual behavior from `emacs-helm.sh` if possible (See note at bottom)
(See reproduction steps)

## Steps to reproduce (recipe)
First, create some test  files:

```sh
$ mkdir test && cd test
$ touch a
$ touch b
$ touch "[c]"
```

- Next, open the "test" directory in `dired`.
- Place the line on the `a` file
- Hit `C-x C-f`, notice the "a" file is highlighted
- Place the line on the `b` file
- Hit `C-x C-f`, notice the "b" file is highlighted
- Place the line on the `[c]` file
- Hit `C-x C-f`, instead of "[c]" being highlighted, the `.` file (current working directory) is highlighted

Here's a screenshot of what's highlighted instead:

![screenshot_2017-07-07_11-00-19](https://user-images.githubusercontent.com/19060/27968255-847423da-6303-11e7-8a6b-0542465ae673.png)

This definitely slows down what I usually use `helm-find-files` for from dired, which is to hit `C-x C-f C-c C-x` to open the current file at point in an external program.

## Describe versions of helm, emacs, operating system etc.
Emacs 25.2, Fedora 25

**Comment by thierryvolpiatto** [comment]
Lee Hinman <notifications@github.com> writes:

> Expected behavior
>
> When I invoke helm-find-files (C-x C-f) from dired with the point on a
> file name, I expect that file to be already highlighted in the helm
> buffer.

This should work wit `helm-ff-guess-ffap-filenames` non-nil.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by dakrone** [comment]
> This should work wit `helm-ff-guess-ffap-filenames` non-nil.

Hmm.. I set `helm-ff-guess-ffap-filenames` to `t` and I am still seeing the original (non-selecting) behavior.

**Comment by thierryvolpiatto** [comment]
Lee Hinman <notifications@github.com> writes:

>     This should work wit helm-ff-guess-ffap-filenames non-nil.
>
> Hmm.. I set helm-ff-guess-ffap-filenames to t and I am still seeing
> the original (non-selecting) behavior.

Indeed when `helm-ff-guess-ffap-filenames` is non-nil ffap use
`ffap-dired` which is not working, so let's use directly
`dired-get-filename`.
The problem is now the file corresponding to the current line in dired
buffer will be preselected even when point is outside the filename e.g
at bob, but is it really a problem ?
As a non dired user, I am not sure what is the best for now (it is easy
to change if needed) let me know what you think.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by thierryvolpiatto** [comment]
When point is on e.g 2014, file is anyway preselected

![capture d ecran_2017-07-08_07-39-03](https://user-images.githubusercontent.com/1533939/27982927-ef0c9bf2-63b0-11e7-8c48-56f9f6cc478c.png)

**Comment by thierryvolpiatto** [comment]
Should be fixed now, however see comments above.
The two commit related to this are referenced by error in issue #1808 , sorry.

**Comment by dakrone** [comment]
This is fixed now, thank you!
