### ISSUE TITLE
How to set case insenstive when using helm functions such as helm-find-files?

### ISSUE THREAD

**Issue by c02y** [emacs-helm/helm#1811]
## Expected behavior
After setting case insensitive in helm, when I'm using helm functions such as `helm-find-files`, helm should find `New` if I type `New` or `new` or 'NEw'.

## Actual behavior from `emacs-helm.sh` if possible (See note at bottom)
The same behavior as I said, it is smart case sensitive.

## Steps to reproduce (recipe)
For example, there is a file or directory named `New` in my home directory, and I use M-x helm-find-files to find it, and I typed `new`, OK, helm can find it, but if I typed `NEW` of `NEw`, helm will not find it. 

After googling and searching in this project, it seems `helm-case-fold-search` variable controls the case stuff when searching, so `helm-case-fold-search` is `smart` by default, but I set

    (setq helm-case-fold-search nil)
    (setq case-fold-search nil)

to make helm case insensitive, it does not work at all, it is still smart case sensitive.

## Backtraces if some (M-x toggle-debug-on-error)
No info.

## Describe versions of helm, emacs, operating system etc.

- GNU Emacs 25.2.1 (i686-pc-linux-gnu, GTK+ Version 2.20.1)
- helm-20170529.2236, but this happens a long time ago.
- CentOS6.5 32bit

**Comment by thierryvolpiatto** [comment]
c02y <notifications@github.com> writes:

> Expected behavior
>
> After setting case insensitive in helm, when I'm using helm functions
> such as helm-find-files.helm will find New item if I type New or new
> or 'NEw'.
>
> Actual behavior from emacs-helm.sh if possible (See note at bottom)
>
> The same behavior as I said, it is smart case sensitive.
>
> Steps to reproduce (recipe)
>
> For example, there is a file or directory named New in my home
> directory, and I use M-x helm-find-files to find it, and I typed new,
> OK, helm can find it, but if I typed NEW of NEw, helm will not find
> it.
>
> After googling and searching in this project, it seems
> helm-case-fold-search variable controls the case stuff when searching,
> so helm-case-fold-search is smart by default, but I set
>
> (setq helm-case-fold-search nil)

For files it is controled by `helm-file-name-case-fold-search`.

> (setq case-fold-search nil)

Why are you setting this globally, it is unrelated to helm IOW you don't
need this.

> to make helm case insensitive, it does not work at all, it is still
> smart case sensitive.

`helm-file-name-case-fold-search` use `helm-case-fold-search` as default
value, but if you modify only `helm-case-fold-search`
`helm-file-name-case-fold-search` value will stay on the old value of
`helm-case-fold-search`.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by c02y** [comment]
>> (setq case-fold-search nil)

> Why are you setting this globally, it is unrelated to helm IOW you don't need this.

Since the document of `helm-case-fold-search` says:

    Use nil or t to turn off smart behavior and use ‘case-fold-search’ behavior.

and the document of `case-fold-search` says:

    Non-nil if searches and matches should ignore case.

But it seems i made wrong configuration, it should be 
    
    (setq case-fold-search t)

which is default instead nil. I just test them, not really use them in my init.el

Anyway, after I use this:

    (setq helm-file-name-case-fold-search t)

I got what I expected.

Thanks.

**Comment by thierryvolpiatto** [comment]
Yes (i.e use the value you need as described in `case-fold-search`)
For other readers, I suggest to not do this and keep the default value which is `smart` for a better experience.
