### ISSUE TITLE
It seems (add-to-list 'helm-completing-read-handlers-alist '(execute-extended-command . ido)) no working ?

### ISSUE THREAD

**Issue by chxp** [emacs-helm/helm#1812]
## Expected behavior
M-x command using ido completion

## Actual behavior 
still using helm completion

## Detailed
I have add (add-to-list 'helm-completing-read-handlers-alist '(execute-extended-command . ido)) in my .emacs

Besides, (add-to-list 'helm-completing-read-handlers-alist '(find-files . ido)) works well

my .emacs about helm is here:

    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    ;;;;;;helm
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    (require 'helm)
    (require 'helm-config)
    
    (define-key helm-map (kbd "C-i") 'helm-execute-persistent-action) ; make TAB works in terminal
    (define-key helm-map (kbd "C-z")  'helm-select-action) ; list actions using C-z
    
    (helm-mode 1)
    
    ;; using ido elsewhere
    (add-to-list 'helm-completing-read-handlers-alist '(execute-extended-command . ido))
    (add-to-list 'helm-completing-read-handlers-alist '(find-files . ido))

## Describe versions of helm, emacs, operating system etc.
helm 20170709.1054 helm-core 20170701.629
emacs24.5.1
under ubuntu 16.04

## Other:
I donnot why my custom-variable of helm-completing-read-handlers-alist have two Symbol of execute-extended-command, one is ido , the other one is nil

as following shows:
![2017-07-11 11-12-55](https://user-images.githubusercontent.com/14882692/28049475-3a373fd0-662a-11e7-9e50-b3548d849e3d.png)

**Comment by thierryvolpiatto** [comment]
See https://github.com/emacs-helm/helm/wiki/FAQ#why-after-enabling-helm-mode-m-x-and-c-x-c-f-are-not-helmized

**Comment by chxp** [comment]
After C-h b , I find  M-x  execute-extended-command is binding to smex (a enhacement of ido). However it still using helm when using M-x

I want use ido mode  when M-x instead of helm

**Comment by thierryvolpiatto** [comment]
chenxp <notifications@github.com> writes:

> After C-h b , I find M-x execute-extended-command is binding to smex
> (a enhacement of ido). However it still using helm when using M-x

I guess helm is helmizing smex.

> I want use ido mode when M-x instead of helm

So bind M-x to `execute-extended-command` and `execute-extended-command`
will use ido as you have specified in `helm-completing-read-handlers-alist`.

I can't give you any advice about smex as I don't know how it works.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by chxp** [comment]
I forget a detail.

When I type M-x em  it shows:

![screenshot_20170712_134046](https://user-images.githubusercontent.com/14882692/28103366-f35d74ec-6707-11e7-815d-6ecbd2c0b727.png)

When I type TAB, it will using helm:

![screenshot_20170712_134127](https://user-images.githubusercontent.com/14882692/28103402-184f60da-6708-11e7-96d1-e66d7cf4193d.png)

But I want still using ido ? or disabled helm?

The .emacs file with:

    (define-key helm-map (kbd "<tab>") 'helm-execute-persistent-action) ; rebind tab to do persistent action

seems no working...

**Comment by thierryvolpiatto** [comment]
The command bound to TAB is not `helm-execute-persistent-action` here (You are not in helm here but in ido) but the `minibuffer-complete` command.

**Comment by chxp** [comment]
So how to close the minibuffer-complete (it is helm-mode-minibuffer-complete, not ido minibuffer-complete?) just when M-x execute-extended-command...

And if no answer, just close the issue. I just a little diffcult to be accustomed to helm when using M-x (For that some times Helm cannot find all M-x el-get-install packages, but I forget which package).

**Comment by thierryvolpiatto** [comment]
chenxp <notifications@github.com> writes:

> So how to close the minibuffer-complete (it is
> helm-mode-minibuffer-complete, not ido minibuffer-complete?) just when
> M-x execute-extended-command...

Here, if I:

1) Configure helm-completing-read-handlers-alist with
execute-extended-command => ido.

2) Bind execute-extended-command to M-x

    (global-set-key (kbd "M-x") 'execute-extended-command)
3) M-x
type helm and hit TAB, completion is displayed in a completion buffer,
not helm.

So the question is why do you endup with helm completion for TAB from
this ido prompt ?

Did you try from emacs-helm.sh ?

> And if no answer, just close the issue. I just a little diffcult to be
> accustomed to helm when using M-x

I you use helm-M-x for M-x you will have no problems.

> (For that some times Helm cannot find all M-x el-get-install packages,
> but I forget which package).

No, helm is using all symbols from obarray that are commands (commandp)
so I don't see how it could miss symbols unless these symbols are not
already loaded for some reasons (no autoloads), in this case these
symbols will not be available with ido or whatever.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by chxp** [comment]
I forget that I usually type more content in ido to avoid the minibufer or using Ctrl-s to cycle and select command in the minitermial. I just think the command of M-x is not very large, no need to open up a new minibuffer (show in minitermial?)...

After try, yeah,  helm-M-x works well in emacs-helm.sh, and convenient for no need to type extra TAB (so the same short of ido, in ido just M-x command-partial C-s). 

 A new to helm, some habit have not turn to helm manner. Thanks for nice answer and advice.

**Comment by thierryvolpiatto** [comment]
Ok thanks, I am closing now, for more questions on helm usage feel free to ask on our mailing list at https://groups.google.com/group/emacs-helm?hl=en
