### ISSUE TITLE
helm-ff : unable to open a file with colons in the name

### ISSUE THREAD

**Issue by nmaludy** [emacs-helm/helm#1817]
## Expected behavior
helm-ff should open the file select.

## Actual behavior from `emacs-helm.sh` if possible (See note at bottom)
The file is not opened, helm closes its window and emacs returns the buffer prior to helm-ff being invoked

## Steps to reproduce (recipe)
```
# in terminal
echo "hello world" > /tmp/file\:\:name\:\:with\:\:colons.txt
```
```
# in emacs
C-x C-f /tmp/file::name::with::colons.txt
```

## Backtraces if some (M-x toggle-debug-on-error)
<none>

## Describe versions of helm, emacs, operating system etc.
```
$ emacs --version
GNU Emacs 25.2.1
Copyright (C) 2017 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```
```
helm MELPA 20170622.126
```
```
$ cat /etc/redhat-release 
CentOS Linux release 7.3.1611 (Core)
```

## IMPORTANT NOTE:

If you are using a Unix or GNU-Linux system there is no excuses 
to not use `emacs-helm.sh` to reproduce your bug in 99% of the cases.

**Comment by thierryvolpiatto** [comment]
nmaludy <notifications@github.com> writes:

> Expected behavior
>
> helm-ff should open the file select.
>
> Actual behavior from emacs-helm.sh if possible (See note at bottom)
>
> The file is not opened, helm closes its window and emacs returns the buffer prior to helm-ff being invoked
>
> Steps to reproduce (recipe)
>
> echo "hello world" > /tmp/file::name::with::colons.txt
> C-x C-f /tmp/file::name::with::colons.txt

It's not the colons that create the bug but "file:" which is matched by
`ffap-url-regexp` which we relay on.

I am looking into this.

Thanks.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by thierryvolpiatto** [comment]
Should work now.

Thanks to have catched this.

BTW This should also affect `find-file-at-point` (not tried) but if true this is an emacs bug.

**Comment by nmaludy** [comment]
@thierryvolpiatto I confirmed this works! It also fixed the same problem for files prefixed with `profile::`

Thank you VERY much for the quick response and quick fix!

Going to close this now.
