### ISSUE TITLE
Dired rename fails on second attempt to rename a file

### ISSUE THREAD

**Issue by alamaison** [emacs-helm/helm#1819]
## Expected behavior

Pressing `R` in a dired buffer should allow me to rename files without limit.

## Actual behavior from `emacs-helm.sh` if possible (See note at bottom)

The first rename succeeds.  Subsequent renames of any file in the same dired buffer fails.  I can't reproduce it with emacs-helm.sh but can with my normal init file.

## Steps to reproduce (recipe)

- Open a dired buffer to a non-empty directory.
- Press `R` to rename a file.
- Enter new filename.
- Press `Enter` to rename file.
- Observe file renamed.
- Press `R` again to rename a file again.
- Observe error

## Backtraces if some (M-x toggle-debug-on-error)

Backtrace attached as file because it contains binary for some reason, which Github doesn't like

[backtrace.txt](https://github.com/emacs-helm/helm/files/1166059/backtrace.txt)

## Describe versions of helm, emacs, operating system etc.

- helm-core          20170717.600 from MELPA
- GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9)
-  of 2016-04-17 on lgw01-04, modified by Debian
- Linux 4.4.0-81-generic #104-Ubuntu SMP Wed Jun 14 08:17:06 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by thierryvolpiatto** [comment]
Alexander Lamaison <notifications@github.com> writes:

> Actual behavior from emacs-helm.sh if possible (See note at bottom)
>
> The first rename succeeds. Subsequent renames of any file in the same
> dired buffer fails.

I hardly see why it would fail on subsequent calls if first call success.

> I can't reproduce it with emacs-helm.sh but can with my normal init
> file.

So it is a bug in your init file or in one of the package you load from
your init file, but not a helm bug.

I can't reproduce this bug.

Start by commenting all your init.el and uncomment slowly while
restarting emacs and trying to reproduce, once you can reproduce, you
will know the last uncommented block is the culprit.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by alamaison** [comment]
Good idea.  So it seems to be something about using `ido` and `helm` together.  In particular, `ido` with `(setq ido-everywhere t)`.  Are they incompatible?

**Comment by thierryvolpiatto** [comment]
Alexander Lamaison <notifications@github.com> writes:

> Good idea. So it seems to be something about using ido and helm
> together. In particular, ido with (setq ido-everywhere t). Are they
> incompatible?

Like this yes.

When helm-mode is enabled, helm allows you to use ido where you want to
use ido, otherwise helm completion is used.

So instead of turning on ido, setup
`helm-completing-read-handlers-alist` to enable ido where you want to
use it.

OTH.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by alamaison** [comment]
Thanks.  Not a bug then
