### ISSUE TITLE
helm-read-file-name and default-directory

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#1820]
## Expected behavior

`helm-read-file-name` should start in `default-directory`.

## Actual behavior from `emacs-helm.sh` if possible (See note at bottom)

It does not and I'm always puzzled at how it decides which starting directory to pick.
It might be the one of the last visited file.

## Steps to reproduce (recipe)

- Browse a file at location `/foo`.
- Start `eshell` and go to `/bar`. See that `default-directory` is now `/bar`.
- Run `helm-find-files` and go to `/quux`, copy `quux.txt` (default: `M-C`).

The copy will spawn a `helm-read-file-name` started somewhere that might not be `default-directory` (here `/bar`).
I am not sure but it might well be `/foo`, the folder of the last visited file.

## Describe versions of helm, emacs, operating system etc.

- Latest Helm from MELPA.
- Emacs 25.2
- Gentoo

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Expected behavior
>
> helm-read-file-name should start in default-directory.
>
> Actual behavior from emacs-helm.sh if possible (See note at bottom)
>
> It does not and I'm always puzzled at how it decides which starting directory to pick.
> It might be the one of the last visited file.
>
> Steps to reproduce (recipe)
>
>   * Browse a file at location /foo.
>   * Start eshell and go to /bar. See that default-directory is now /bar.
>   * Run helm-find-files and go to /quux, copy quux.txt (default: M-C).
>
> The copy will spawn a helm-read-file-name started somewhere that might
> not be default-directory (here /bar).

This is due to `helm-dwim-target-directory`.

> I am not sure but it might well be /foo, the folder of the last
> visited file.

I guess you have to windows in 3) step:

- One showing the eshell buffer at /bar
- One showing some file at /foo

When you start helm-find-files from the eshell buffer (at /bar) the
default directory to copy will be /foo (dwim-target-directory).
But if you start with only the eshell buffer it will be /bar.
See `helm-dwim-target-directory` docstring.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by Ambrevar** [comment]
That's exactly that.  Now I understand the mechanics it feels much more
usable! :)

Question: when there is more than 2 windows, which one is the other
window?  `other-window`?

If so, with many windows and when the last window switch was done a
while back, it is not obvious to remember which one is the "other
window".

Another thought: Take the scenario where I have several windows open for
random reasons, and I decide to move some files in a subfolder of their
current location.  I fire up `helm-find-files`, find the files
`/foo/bar/baz/.../qux/quux` folder and select some files.  Then I hit
`M-R`.  If I have kept the window configuration with the other window
`helm-dwim-target-directory` will probably not do what I mean, that is,
it will start `helm-read-file-name' in some random folder and I have to
find `/foo/bar/baz/.../qux/quux` again.  Annoying.

Is it possible to turn that feature off on-the-fly?

What is the intended workflow?  If I don't want the aforementioned
annoyance to arise, I can:

- Keep only one window.  If I want to keep the window configuration, I
  have to save it to a register and restore it afterwards.  Or use some
  workspace package.  A bit cumbersome.

- Move to my destination first with eshell (or dired or whatever).  Then
  go to another window _only once_ and fire up `helm-find-files`.

I think all this should be documented.  There is no reference to
`helm-dwim-target-directory' in the documentation of `helm-read-file-name'.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> That's exactly that. Now I understand the mechanics it feels much more
> usable! :)
>
> Question: when there is more than 2 windows, which one is the other
> window? `other-window`?

IIRC `next-window`

> If so, with many windows and when the last window switch was done a
> while back, it is not obvious to remember which one is the "other
> window".
>
> Another thought: Take the scenario where I have several windows open for
> random reasons, and I decide to move some files in a subfolder of their
> current location. I fire up `helm-find-files`, find the files
> `/foo/bar/baz/.../qux/quux` folder and select some files. Then I hit
> `M-R`. If I have kept the window configuration with the other window
> `helm-dwim-target-directory` will probably not do what I mean, that is,
> it will start `helm-read-file-name' in some random folder and I have to
> find `/foo/bar/baz/.../qux/quux` again. Annoying.
>
> Is it possible to turn that feature off on-the-fly?

Not actually but I can do it, I personally don't like this much, the
original motivation to enable this was to provide `dired-dwim-target`
feature.

> What is the intended workflow?

I generally find my previous destinations when copying from
helm-find-files with C-o which switch to the directory history.

> If I don't want the aforementioned annoyance to arise, I can:
>
> - Keep only one window. If I want to keep the window configuration, I
> have to save it to a register and restore it afterwards. Or use some
> workspace package. A bit cumbersome.
>
> - Move to my destination first with eshell (or dired or whatever). Then
> go to another window _only once_ and fire up `helm-find-files`.
>
> I think all this should be documented. There is no reference to
> `helm-dwim-target-directory' in the documentation of `helm-read-file-name'.

Indeed yes should be documented.

Will make this optional as well.


-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Another thought: Take the scenario where I have several windows open for
> random reasons, and I decide to move some files in a subfolder of their
> current location.

What about in this case having completion on all the default-directory
belonging to each window:

    (defun helm-dwim-target-directory ()
      "Return value of `default-directory' of buffer in other window.
    If there is only one window return the value of currently visited directory
    if found in `helm-ff-history' or fallback to `default-directory'
    of current buffer."
      (with-helm-current-buffer
        (let* ((wins (remove (get-buffer-window helm-marked-buffer-name)
                             (window-list)))
               (num-windows (length wins)))
          (expand-file-name
           (if (> num-windows 1)
               (helm-comp-read "Default directory: "
                               (mapcar (lambda (w) 
                                         (with-selected-window w
                                           default-directory))
                                       wins))
             default-directory)
           ;; Using the car of *ff-history allow
           ;; staying in the directory visited instead of current.
           (or (car-safe helm-ff-history) default-directory)))))

Probably it needs some improvements but that's give you an idea...

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by thierryvolpiatto** [comment]
See #1821

**Comment by Ambrevar** [comment]
> I generally find my previous destinations when copying from
> helm-find-files with C-o which switch to the directory history.

In my example with `/foo/bar/baz/.../qux/quux` where I want to copy in a subdir, you won't find `/foo/bar/baz/.../qux/quux` if no buffer had ever been opened at that location.

**Comment by Ambrevar** [comment]
But staying in the directory where the action was performed is what `(setq helm-dwim-target nil)` does, so problem solved!

**Comment by Ambrevar** [comment]
All good, thanks for the this new feature!
