### ISSUE TITLE
Async file operations (copy, rename) and fine-grained control

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#1823]
This is a general question and while not directly related to Helm, it would make `helm-find-files` a much more powerful file manager:

Can we have fine-grained control over the copy/rename operations?  Such as displaying progress, queueing / parallelizing operations, pausing, etc.

I don't even know if there exists a generic commandline tool for doing that.

I've raised the question there with a workflow example: https://bbs.archlinux.org/viewtopic.php?pid=1727873#p1727873.

If there is no such thing, I could go back to work and implement it I guess.

At the moment file operations from Helm (or Dired for that matters) block Emacs.
It would be awesome to have Helm file operations bound to such a tool.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> At the moment file operations from Helm (or Dired for that matters) block Emacs.

Try M-x dired-async-mode

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by Ambrevar** [comment]
But beside running in the background, can you get the progress, pause/resume, queue, etc.?
All this could be implemented within Emacs obviously, but I don't think it would fit: solving the problem in CLI would be much more generic and could be used by Emacs too. (That would supersede dired-async.)

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> But beside running in the background, can you get the progress,
> pause/resume, queue, etc.?

- Progress bar => yes/no, you have a notification that a job is running in
  mode-line and it disappear sending a finish message (always in
  mode-line) when done.

- Pause/resume => no, I don't see the need as long as emacs is not
  blocked while copying, thus I never heard of this feature in any
  copy/rename tool.

- Queue => yes, you can send as many jobs you want they are notified in
  mode-line and you are notified when one finish.

The best is you try dired-async, I use it always and I am very happy
with this (I can copy one or more 2G files while doing something else in emacs)

One recent bug though I have not yet fixed with emacs-26 (works fine up
to 25.2):

https://github.com/jwiegley/emacs-async/issues/80

This bug is unrelated to helm.

 
> All this could be implemented within Emacs obviously, but I don't
> think it would fit: solving the problem in CLI would be much more
> generic and could be used by Emacs too. (That would supersede
> dired-async.)

I have no idea of what could be done here for know (please enlight me ;-))

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by Ambrevar** [comment]
- Progress bar (it does not have to be a bar): some way of monitoring the good progress of the copy and some ETA. Useful in many scenarios: Can I expect to shutdown the machine before going to bed? :)

- Pause/resume: this is useful when you have a big copy in the background but you want to run something else that is both more urgent and resource-demanding.  Then you can pause the copy, run the urgent job, then resume the copy.  Scenarios are plenty.

- Queue: Wait, does dired-async actually _queue_ the operations, that is, run them one after the other?

> I have no idea of what could be done here for know (please enlight me ;-))

I don't think there is anything to be done on Helm's side, I was merely asking if you had heard of such a tool, or if you had a similar workflow for file operations.

I'll keep on investigating for existing products, and if nothing shows up I'll develop my tool.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

>   * Progress bar (it does not have to be a bar): some way of
>     monitoring the good progress of the copy and some ETA. Useful in
>     many scenarios: Can I expect to shutdown the machine before going
>     to bed? :)

Yes I understood, What I explained is that there is no progress bar but
you always know a job is running or is finish (when you see nothing in
mode-line that's mean everything have finished).

If you try to copy a big file you will see it's quite handy, but it is
not a progress bar (I would love having a real progress bar in emacs).

>   * Pause/resume: this is useful when you have a big copy in the
>     background but you want to run something else that is both more
>     urgent and resource-demanding. Then you can pause the copy, run
>     the urgent job, then resume the copy. Scenarios are plenty.

Yes I agree it could be useful but I am not aware of any tool providing
this feature.

>   * Queue: Wait, does dired-async actually queue the operations, that
>   is, run them one after the other?

Yes, try to launch the copy of say three large files (e.g large .avi)
one after the other i.e don't mark three files and launch copy but do
copy file1, copy file2, copy file3, you will have three jobs queued.

>     I have no idea of what could be done here for know (please enlight me ;-))
>
> I don't think there is anything to be done on Helm's side, I was
> merely asking if you had heard of such a tool, or if you had a similar
> workflow for file operations.
>
> I'll keep on investigating for existing products, and if nothing shows
> up I'll develop my tool.

Would be cool, let me know about your progress on this.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by Ambrevar** [comment]
> Yes, try to launch the copy of say three large files (e.g large .avi)
> one after the other i.e don't mark three files and launch copy but do
> copy file1, copy file2, copy file3, you will have three jobs queued.

That's awesome.  Is this documented anywhere?  Either I missed this or
it should be way more advertised.

**Comment by thierryvolpiatto** [comment]
Here successive copy of two videos:

![capture d ecran_2017-08-01_20-55-50](https://user-images.githubusercontent.com/1533939/28841914-0c2194b4-76fc-11e7-8769-a9a7844a4c6d.png)

When first job finished you are notified in mode-line and then the mode line update with 
`[1 Async job(s) running]`.

**Comment by Ambrevar** [comment]
I've seen that, but it does not say they are _queued_: they could be just as well running in parallel, like two `cp` would do in a shell.

**Comment by thierryvolpiatto** [comment]
They are running in parallel each one using a separate emacs instance.
When I say  _queued_ I mean that each emacs instance is registered and the number of instances is always notified in mode-line as "job", when one finish mode-line is updated, but the second can finish before the first.
I think you mean by _queuing_ the second job should start only when the first have finished.
If so, I don't see why you would want to do this as it will take longer to finish, I don't see the advantage.

Perhaps we could continue this discussion in async, I am closing this now as it is not directly related to helm (the copy/rename async code is in dired-async).

Thanks.

**Comment by Ambrevar** [comment]
I'll work on it when I have time.  I'll report to the async repo then.

As a last note, parallel copying is _not_ necessarily faster, it could actually slow down the process more or less dramatically in case the same device is used for the different copies and the device is serial-oriented, like HDDs are.  SSDs are much better at that.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I'll work on it when I have time. I'll report to the async repo then.
>
> As a last note, parallel copying is not necessarily faster, it could
> actually slow down the process more or less dramatically in case the
> same device is used for the different copies and the device is
> serial-oriented, like HDDs are. SSDs are much better at that.

Good to know, thanks.

My workflow is generally copying from HDD => USB disk, at least for big
files.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997
