### ISSUE TITLE
An option to show the directory name in git grep ?

### ISSUE THREAD

**Issue by azer** [emacs-helm/helm#1825]
Hey there,

I like how helm is trimming the filename, but I have one thought. Can we show the folder name of a file, too ? 

For example, if you search your emacs config directory, you may end up seeing a lot of `config.el` mentioning same keyword. If you got a lot of folders with same name (e.g spacemacs) it's impossible to figure out which config.el is which by looking at them.

For example, instead of seeing;

`
config.el: 
config.el
config.el
` 

It could be better to see;

`
org-mode/config.el
js2-mode/config.el
go-mode/config.el
`

**Comment by xuchunyang** [comment]
Try user option `helm-grep-file-path-style`, e.g.,

    (setq helm-grep-file-path-style 'relative)

**Comment by azer** [comment]
@xuchunyang yay! exactly what I was looking for :)

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

> Try user option helm-grep-file-path-style, e.g.,
>
> (setq helm-grep-file-path-style 'relative)

`helm-popup-tip-mode` may help too.


-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997
