### ISSUE TITLE
"search by directory name" ignore dired buffers

### ISSUE THREAD

**Issue by rvelseg** [emacs-helm/helm#1826]
I want to kill a bunch of buffers based on a common path. Then, it would be good to filter candidates, mark them, and kill them using M-D.

When I try to do it, using "search by directory name" all the dired buffers are discarded. I believe removing dired buffers was chosen for some reason, if this is the case, how can I use helm to kill all the buffers (incuding dired buffers) under some directory?

## Expected behavior
Use "/" to filter candidates not discarding dired buffers.

## Actual behavior from `emacs-helm.sh` if possible (See note at bottom)
dired buffers are discarded as soon as "/" is written in pattern

## Steps to reproduce (recipe)
Open some buffers, some of them corresponding to files, some other corresponding to directories containing these files. Then, list buffers with `C-x C-b`, and write "/" in the pattern.

## Backtraces if some (M-x toggle-debug-on-error)
no errors here

## Describe versions of helm, emacs, operating system etc.
debian jessie, emacs 24.4.1, helm 20170731.1225 from melpa, 

## IMPORTANT NOTE:

If you are using a Unix or GNU-Linux system there is no excuses 
to not use `emacs-helm.sh` to reproduce your bug in 99% of the cases.

I did

**Comment by thierryvolpiatto** [comment]
Roberto Velasco Segura <notifications@github.com> writes:

> I want to kill a bunch of buffers based on a common path. Then, it would be good to filter candidates, mark them, and kill them using M-D.
>
> When I try to do it, using "search by directory name" all the dired buffers are discarded. I believe removing dired buffers was chosen for some reason, if this is the
> case, how can I use helm to kill all the buffers (incuding dired buffers) under some directory?
>
> Expected behavior
>
> Use "/" to filter candidates not discarding dired buffers.

This filter is filtering buffer-file-name under a directory but not the
directories themself, use instead "*dired foo" to filter all dired
buffers matching "foo".


-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by rvelseg** [comment]
Thanks 😄

**Comment by rvelseg** [comment]
Thanks again. However, this doesn't solve completely the problem, "*dired foo" keeps buffers having "foo" in the directory name, but not in the name of the upper level directories.

**Comment by thierryvolpiatto** [comment]
Roberto Velasco Segura <notifications@github.com> writes:

> Thanks again. However, this doesn't solve completely the problem,
> "*dired foo" keeps buffers having "foo" in the directory name, but not
> in the name of the upper level directories.

Sorry, I rarely use dired, but yes that make sense, so now you should be
able to do "*dired /foo" or "/foo *dired"

Thanks.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by rvelseg** [comment]
Wow, thanks, it is working like a charm 😃
