### ISSUE TITLE
Shell-escaped file name insertion

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#1827]
I find myself calling `helm-find-files` very frequently to look for a file and insert its path (`C-c i`) in the current buffer.  It's extremely useful for Eshell in particular to insert filename arguments.

Until I meet a file that needs escaping.  Then I have to shell-escape the arguments manually.
It is trivial to add a "Insert shell-escaped file path" action.  Would you consider it?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I find myself calling helm-find-files very frequently to look for a
> file and insert its path (C-c i) in the current buffer. It's extremely
> useful for Eshell in particular to insert filename arguments.
>
> Until I meet a file that needs escaping. Then I have to shell-escape
> the arguments manually.  It is trivial to add a "Insert shell-escaped
> file path" action. Would you consider it?

Instead of adding a new action, what about detecting shell buffers and
escaping inserted strings inconditionally in those buffers ?

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by Ambrevar** [comment]
What would those be? Shell, Eshell, term, ansi-term... What-about sh-mode?
I like the idea though, so I sense a call for a defcustom mode list!

**Comment by Ambrevar** [comment]
While we are at it, I always found "Complete at point" to be a confusing title for something that should rather be "Insert file path".

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> What would those be? Shell, Eshell, term, ansi-term...

`(eshell-mode shell-mode term-mode)` covers all I think.

> What-about sh-mode?

AFAIK you don't need escaped strings in `sh-mode`.

> I like the idea though, so I sense a call for a defcustom mode list!

I try to avoid adding defcustom's if possible, if the hard-coded list
above covers all, probably it is not needed to add a defcustom for this
(assuming that users want their filenames always quoted in such
buffers).
So will see, if really needed we will add one otherwise stay like this
for now.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by Ambrevar** [comment]
> AFAIK you don't need escaped strings in `sh-mode`.

Why not? Shell scripts follow the same syntax as shell prompts, don't
they?

I.e. a copy on a prompt:

	cp ~/file\ with\ escapes foo

is written the same in a shell script:

	cp ~/file\ with\ escapes foo

I understand that defcustom increase the size of the API, but in that
case it seems impossible to predict which mode the user-will use
(there are also third-party shell modes like `rc-mode` and `fish-mode`).

The user could also want to _remove_ the auto-escaping functionality, or
even write wrappers that do it _conditionally_.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

>> AFAIK you don't need escaped strings in `sh-mode`.
>
> Why not? Shell scripts follow the same syntax as shell prompts, don't
> they?

In good style no.

> I.e. a copy on a prompt:
>
> cp ~/file\ with\ escapes foo
>
> is written the same in a shell script:
>
> cp ~/file\ with\ escapes foo

I would write cp "~/file with escape" "foo"

> I understand that defcustom increase the size of the API, but in that
> case it seems impossible to predict which mode the user-will use
> (there are also third-party shell modes like `rc-mode` and `fish-mode`).

Ah! was not aware of these third party mode, so ok that make sense.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by Ambrevar** [comment]
For the record, Bourne-like shells won't expand the ~ between double-quotes, so `cp "~/file with escape"` won't work, it's either `cp "$HOME/file with escape"` or `cp ~/file\ with\ escapes foo`.

That being said you are right, it can't think of a proper use-case for sh-mode.  Same for `rc-mode` or `fish-mode`.  Besides adding support for third-party modes makes little sense if those modes have a different escaping syntax.

I would go either for:
- no user configuration and we stick to what you've commited;
- a defcustom function that takes the file path as parameter and returns whatever the user wants (identity, escaped, etc.).

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> For the record, Bourne-like shells won't expand the ~ between
> double-quotes, so cp "~/file with escape" won't work, it's either cp
> "$HOME/file with escape" or cp ~/ file\ with\ escapes foo.

Yes you are right, I just wanted to point out that filenames are
generally double quoted but neither escaped.

> I would go either for:
>
>   * no user configuration and we stick to what you've commited;
>   * a defcustom function that takes the file path as parameter and returns whatever the user wants (identity, escaped, etc.).

We have now added `helm-modes-using-escaped-strings`. 

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by Ambrevar** [comment]
Alright, works fine by me, thanks!
