### ISSUE TITLE
Dynamic candidate-number-limit?

### ISSUE THREAD

**Issue by alphapapa** [emacs-helm/helm#1831]
Hi Thierry,

Would it be possible to make the `candidate-number-limit` dynamic?  i.e. if it's a symbol instead of an integer, use the symbol's value?

The reason I would like this is that I have a source that I want to call in two different commands, and in one command I want the source to show no more than 10 candidates, but in the other command I want to see a much larger number.  As far as I can tell, the limit is set when the source is defined, so since I set it in a `defvar` in the package (so users can use it in their own commands), changes to the variable that sets the limit don't take effect unless the `defvar` is redefined:

```el
(defvar helm-source-org-recent-headings
    (helm-build-sync-source " Recent Org headings"
      :candidates (lambda () org-recent-headings-list)
      :candidate-number-limit org-recent-headings-candidate-number-limit
      :candidate-transformer 'org-recent-headings--truncate-candidates
      :keymap org-recent-headings-helm-map
      :action (helm-make-actions
               "Show entry (default function)" 'org-recent-headings--show-entry-default
               "Show entry in real buffer" 'org-recent-headings--show-entry-direct
               "Show entry in indirect buffer" 'org-recent-headings--show-entry-indirect
               "Remove entry" 'org-recent-headings--remove-entries
               "Bookmark heading" 'org-recent-headings--bookmark-entry))
    "Helm source for `org-recent-headings'.")
```

If I could set `:candidate-number-limit 'org-recent-headings-candidate-number-limit`, and have Helm access the value of that symbol every time the source is used, it would solve this problem.

Thanks.

**Comment by thierryvolpiatto** [comment]
alphapapa <notifications@github.com> writes:

> Hi Thierry,
>
> Would it be possible to make the candidate-number-limit dynamic?
> i.e. if it's a symbol instead of an integer, use the symbol's value?

Done.  Thanks.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by alphapapa** [comment]
Thank you!  I appreciate that you are so responsive to your users!
