### ISSUE TITLE
Getting text properties from candidate

### ISSUE THREAD

**Issue by alphapapa** [emacs-helm/helm#1835]
Hi Thierry,

I'm trying to make a command similar to `helm-swoop`.  I was going to use `helm-build-in-file-source`, but there are two problems with that:

1.  It only works for file-backed buffers, so e.g. it doesn't work for the scratch buffer.
2.  It only shows the contents of the file on-disk, so if the file is open in a dirty buffer, it doesn't show the contents of the buffer.

So I tried to make a class that works for any buffer, copying from `helm-source-in-file`:

```el
(defclass ap/helm-source-from-buffer-contents (helm-source-in-buffer)
  ((init :initform (lambda ()
                     (let ((buffer (helm-attr 'candidates-file))
                           (count 1))
                       (with-current-buffer (helm-candidate-buffer 'global)
                         (insert-buffer-contents buffer)
                         (goto-char (point-min))
                         (while (not (eobp))
                           (add-text-properties
                            (point-at-bol) (point-at-eol)
                            `(helm-linum ,count))
                           (cl-incf count)
                           (forward-line 1))))))
   (get-line :initform #'buffer-substring)
   (candidates-file
    :initarg :candidates-file
    :initform nil
    :custom string
    :documentation
    "  A filename.
  Each line number of FILE is accessible with helm-linum property
  from candidate display part."))

  "The contents of the FILE will be used as candidates in buffer.")
```

Then I use this function to insert the contents of the buffer, since there is no native function for buffer contents, like there is for files with `insert-file-contents`:
```el
(cl-defun insert-buffer-contents (buffer &key (get-contents-fn #'buffer-string))
  (let ((contents (with-current-buffer buffer
                    (funcall get-contents-fn))))
    (insert contents)))
```

Then I copied `helm-build-in-buffer-source`:
```el
(defmacro helm-build-from-buffer-source (name buffer &rest args)
  "Build a helm source with NAME name using `candidates-in-files' method.
Arg BUFFER is a buffer, the contents of this buffer will be
used as candidates in buffer.
Args ARGS are keywords provided by `helm-source-in-file'."
  (declare (indent 1))
  `(helm-make-source ,name 'ap/helm-source-from-buffer-contents
     :candidates-file ,buffer ,@args))
```

Then I have a function to go to the candidate's line using the `helm-linum` property:
```el
(defun goto-helm-linum-property (c)
  (goto-line (get-text-property 0 'helm-linum c)))
```

Finally I call `helm` with the source:

```el
(helm :sources (helm-build-from-buffer-source
                     "testing" (current-buffer)
                     :action (helm-make-actions
                              "Go to line" #'goto-helm-linum-property)))
```

And it works great, except for one thing: `goto-helm-linum-property` receives strings without properties.  I have verified that the in-buffer source buffer does have the `helm-linum` properties set, but the string received by `goto-helm-linum-property` has no properties.

As best I can figure out, this is because `helm-get-selection` is being called with `force-display-part` not set to `'withprop`, so it's calling `buffer-substring-no-properties`.  

But I can't figure out how to fix this.  There doesn't seem to be a way to change this in the source classes.  I thought that the `:get-line` attribute was for this, because the docstring says:

```
Slot: get-line    default = (quote buffer-substring-no-properties)
A function like ‘buffer-substring-no-properties’ or ‘buffer-substring’.
  This function converts point of line-beginning and point of line-end,
  which represents a candidate computed by ‘helm-candidates-in-buffer’.
  By default, ‘helm-candidates-in-buffer’ uses
  ‘buffer-substring-no-properties’.
```
But when I set this to a lambda that prints a debug message, I can see that it is called for every line in the buffer when I run the Helm command, not when I execute an action on a candidate.  So I guess this is only for getting lines from the source buffer into the candidates buffer, not for getting lines from the candidates buffer to the action function.  (This is pretty confusing; the docs should probably be adjusted.)

Finally I found the `helm-get-selection` function, but I grepped through all the Helm source files, and I can't find any example of how to change the call to this in a source, to call it with `'withprop`.

I am stumped.  I would appreciate any help.  :)

Thanks.

**Comment by alphapapa** [comment]
Ok, as usual, as soon as I write out a detailed explanation, a possible solution occurs to me, and it works:
```el
(helm :sources (helm-build-from-buffer-source
                     (buffer-file-name (current-buffer)) (current-buffer)
                     :action (helm-make-actions
                              "Go to line" (lambda (&rest args)
                                             (goto-helm-linum-property
                                              (helm-get-selection nil 'withprop))))))
```
I see that I have to get the selection in the action function myself with `helm-get-selection`.

This works, of course, but it seems awkward.  If I could just set a keyword arg to set the selection function, or just pass `'withprop` to it, I could use the candidate directly in the action function instead of having to call `helm-get-selection` manually.

So I guess I have a few suggestions and questions here:

1.  The docstring for the `:get-line` attribute needs clarification.  As read, it sounds like it changes what function is used to retrieve the candidate for the action function, but it actually seems to load candidates into the behind-the-scenes Helm buffer.
2.  I don't understand why `:get-line` is even relevant when I'm retrieving and inserting contents in the `:init` function.  Is `:get-line` being called here unnecessarily?  I can see from my testing that it's called for every line when I initialize the Helm command.
3.  It would be nice if there were an attribute on the sources to change the `helm-get-selection` call to get text with properties, etc.  This would avoid having to make another call to `helm-get-selection`, which makes the arguments to the action function useless.
4.  It seems like there's a need for a `helm-from-buffer-contents` source to go with the `helm-source-in-file` source.  Or maybe there could be one source that works for either a filename or a buffer.  Preferably it should work on a buffer if there is already one open for the filename given.  Having a source like this would make it much simpler to make many generally useful Helm sources that work with buffer contents.  So maybe it could be called `helm-source-with-buffer-or-file-contents`.

Thanks for your help.  Even though I feel confused by Helm sometimes, I couldn't do any of this without it, and I really am thankful for it.

**Comment by thierryvolpiatto** [comment]
alphapapa <notifications@github.com> writes:

> Hi Thierry,
>
> I'm trying to make a command similar to helm-swoop.

You don't need to reinvent the wheel, helm-(m)occur is able to behave
exactly like helm-swoop and even better.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by thierryvolpiatto** [comment]
alphapapa <notifications@github.com> writes:

> So I guess I have a few suggestions and questions here:
>
>  1. The docstring for the :get-line attribute needs clarification. As
>     read, it sounds like it changes what function is used to retrieve
>     the candidate for the action function, but it actually seems to
>     load candidates into the behind-the-scenes Helm buffer.

Think at what buffer-substring / buffer-substring-no-properties do.

When a line match in candidate buffer it is extracted with the get-line
fn, so if you use buffer-substring you will be able to get props from
this line, see how helm-occur is written as example.

>  2. I don't understand why :get-line is even relevant when I'm retrieving and inserting contents in the :init function. Is :get-line being called here
>     unnecessarily?

No, I think you are confusing the helm-candidate-buffer and the
helm-buffer, there is only raw data in the candidate-buffer and the data
is formated according to get-line fn if some and inserted in the
helm-buffer.

>  I can see from my testing that it's called for every line when I
>  initialize the Helm command.

Yes,

helm-candidate-buffer                helm-buffer
          v            get-line fn       v
       raw data                       transformed data
                                      by get-line fn


Note that to ease the write of init functions, you can use the :data slot.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by alphapapa** [comment]
Hi Thierry,

> You don't need to reinvent the wheel, helm-(m)occur is able to behave exactly like helm-swoop and even better.

Well, almost.  :)  There are a few advantages helm-swoop has:

1.  It shows candidates when the helm-pattern is empty.
2.  It doesn't show the filename when looking at the contents of a single buffer.

I would like to make this configurable, however, since `helm-moccur-get-line` gets the line number by getting fields from the candidate string divided by `:`, it means the line number must be displayed.  I am trying to use the `helm-linum` text-property to avoid displaying the line numbers and filename.

> Think at what buffer-substring / buffer-substring-no-properties do.

Yes, that is the problem: helm-get-selection is calling buffer-substring-no-properties, so the action function receives a string without properties.

> When a line match in candidate buffer it is extracted with the get-line fn, so if you use buffer-substring you will be able to get props from this line, see how helm-occur is written as example.

I'm sorry, I don't understand: I specifically set `:get-line #'buffer-substring`, but the action function received a string without any properties.  As best I can determine, this is because `helm-get-selection` is being called with force-display-part not set to 'withprop, so it's calling buffer-substring-no-properties, and so the action function gets a string without properties.

> Note that to ease the write of init functions, you can use the :data slot.

Yes, I've tried different combinations of `:data` and `:init`, but I haven't been able to determine the "correct" way to use these to simply dump the contents of a buffer into a Helm source buffer.  Do you mean that I should use `:data` instead of `:init`?

Thanks for your help.

**Comment by thierryvolpiatto** [comment]
alphapapa <notifications@github.com> writes:

> Yes, that is the problem: helm-get-selection is calling
> buffer-substring-no-properties, so the action function receives a
> string without properties.

See helm-get-selection docstring, what you want is

    (helm-get-selection nil 'withprop)

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by alphapapa** [comment]
Yes, but how do I set that in a source or command with a keyword?  That would allow me to avoid having to call helm-get-selection in the action function.

**Comment by thierryvolpiatto** [comment]
alphapapa <notifications@github.com> writes:

> Hi Thierry,
>
>     You don't need to reinvent the wheel, helm-(m)occur is able to behave exactly like helm-swoop and even better.
>    
> Well, almost. :) There are a few advantages helm-swoop has:

Note that helm-swoop is not implemented correctly, several parts of its
code are not helm compliant and not running at all in helm, its
implementation is also slower than the helm-occur one (sync vs in-buffer).

>  1. It shows candidates when the helm-pattern is empty.

    (defmethod helm-setup-user-source ((source helm-source-multi-occur))
      (setf (slot-value source 'requires-pattern) 0))

Note that's pretty unuseful apart slowing down helm on large buffers.

>  2. It doesn't show the filename when looking at the contents of a single buffer.

Use `helm-popup-tip-mode`.

>     When a line match in candidate buffer it is extracted with the get-line fn, so if you use buffer-substring you will be able to get props from this line, see how
>     helm-occur is written as example.
>    
> I'm sorry, I don't understand: I specifically set :get-line #'buffer-substring, but the action function received a string without any properties. As best I can
> determine, this is because helm-get-selection is being called with force-display-part not set to 'withprop, so it's calling buffer-substring-no-properties, and so the
> action function gets a string without properties.

Yes, I meant when you use :get-line #'buffer-substring the props will be
present in helm-buffer, but you have to extract them explicitely with
the 'withprop flag in your action.

>     Note that to ease the write of init functions, you can use the :data slot.
>    
> Yes, I've tried different combinations of :data and :init, but I haven't been able to determine the "correct" way to use these to simply dump the contents of a buffer
> into a Helm source buffer.

    (helm :sources (helm-build-in-buffer-source "test"
                     :data (with-helm-current-buffer (buffer-string)))
          :buffer "*helm test*")

You can also wrap your data in a lambda.

> Do you mean that I should use :data instead of :init?

:data is just a shortcut that prepare an :init function for you, most of
the time it is enough, but for more complex :init fns you will have to
use :init. See how a source using :data expand.

Also in your :init functions you can use helm-init-candidates-in-buffer
which avoid the with-current-buffer dance.

HTH.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by alphapapa** [comment]
> Note that helm-swoop is not implemented correctly, several parts of its code are not helm compliant and not running at all in helm, its implementation is also slower than the helm-occur one (sync vs in-buffer).

Right, that's why I want to make a version that makes use of in-buffer sources, etc.  :)  Most of the time it works well enough, but sometimes the speed is an issue.

> (defmethod helm-setup-user-source ((source helm-source-multi-occur))
      (setf (slot-value source 'requires-pattern) 0))

> Note that's pretty unuseful apart slowing down helm on large buffers.

Thanks, that is what I was looking for, but I don't know EIEIO yet, so I wouldn't have discovered that.  :)

> >   2. It doesn't show the filename when looking at the contents of a single buffer.
> Use `helm-popup-tip-mode`.

Actually, I meant that as a positive thing.  When I'm looking at the contents of a single buffer, I don't want to display the filename, but helm-occur shows the filename and line numbers.

> Yes, I meant when you use :get-line #'buffer-substring the props will be present in helm-buffer, but you have to extract them explicitely with the 'withprop flag in your action.

Thanks, that is what confused me.  Could we update the docstring for :get-line to clarify this?  As read, it sounds like :get-line retrieves the candidate from helm-buffer and passes it to the action, so I spent some time trying to figure out why I couldn't get text properties in the action function when I set :get-line to #'buffer-substring.  I was barking up the wrong tree for a while.

> (helm :sources (helm-build-in-buffer-source "test"
                     :data (with-helm-current-buffer (buffer-string)))
          :buffer "*helm test*")

Thanks, this is very helpful.

> :data is just a shortcut that prepare an :init function for you, most of
the time it is enough, but for more complex :init fns you will have to
use :init. See how a source using :data expand.

Thanks.

> Also in your :init functions you can use helm-init-candidates-in-buffer
which avoid the with-current-buffer dance.

Aha, thanks.

> HTH.

It does, very much, thanks for your patience.

**Comment by thierryvolpiatto** [comment]
alphapapa <notifications@github.com> writes:

>     Note that helm-swoop is not implemented correctly, several parts of its code are not helm compliant and not running at all in helm, its implementation
>     is also slower than the helm-occur one (sync vs in-buffer).
>
> Right, that's why I want to make a version that makes use of in-buffer
> sources,

IMO a waste of time to reimplement all, I suggest you tweak the helm
occur class as needed or rewrite your own class inheriting from helm
occur class if you want something different than helm-occur.

> Actually, I meant that as a positive thing. When I'm looking at the
> contents of a single buffer, I don't want to display the filename, but
> helm-occur shows the filename and line numbers.

I guess this could be easily implemented in helm-occur, using a display
property + an invisible face.


>
>
>     Yes, I meant when you use :get-line #'buffer-substring the props will be present in helm-buffer, but you have to extract them explicitely with the
>     'withprop flag in your action.
>
> Thanks, that is what confused me. Could we update the docstring for
> :get-line to clarify this?

Yes I will if that help.

>
> It does, very much, thanks for your patience.

Youre welcome.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by thierryvolpiatto** [comment]
I have clarified the docstring of `:get-line`, closing now.

Thanks.

**Comment by thierryvolpiatto** [comment]
Update (see https://github.com/emacs-helm/helm/wiki/Developing#pre-filtering-lines-in-a-buffer)

Now the `:data` slot accept a buffer, for instance:

```elisp
(helm :sources (helm-build-in-buffer-source "test"
                 :data (current-buffer))
      :buffer "*helm test*")
```

**Comment by alphapapa** [comment]
Hey Thierry,

That's awesome!  That makes it so simple to make new sources based on the contents of a buffer!  Brilliant!  Thanks!  :)

**Comment by thierryvolpiatto** [comment]
Update: helm-occur is not showing buffer name (default but configurable).

**Comment by alphapapa** [comment]
Thanks, Thierry, that sounds great.  Maybe I won't need my custom source anymore.
