### ISSUE TITLE
Is there a way to change the layout of candidates/prompt in helm?

### ISSUE THREAD

**Issue by rgrinberg** [emacs-helm/helm#1837]
Currently helm works  by putting the prompt above the candidates list, but I'd like the order of these windows to be reserved. I want to see the candidates above the prompt. I looked for such an option in `customize` but couldn't find anything relevant. Is there an option for this, or this layout isn't possible yet?

**Comment by thierryvolpiatto** [comment]
Rudi Grinberg <notifications@github.com> writes:

> Currently helm works by putting the prompt above the candidates list,

No it doesn't, at least by default.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by rgrinberg** [comment]
Hmm, I see. It must be my spacemacs installation. What's the setting to change this?

**Comment by thierryvolpiatto** [comment]
Rudi Grinberg <notifications@github.com> writes:

> Hmm, I see. It must be my spacemacs installation. What's the setting to change this?

See `helm-echo-input-in-header-line`.
I guess the minibuffer is also hidden, so remove
`helm-hide-minibuffer-maybe` from `helm-minibuffer-set-up-hook`.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by thierryvolpiatto** [comment]
Closing now, don't hesitate to ask if you still have problems disabling this.

Thanks.
