### ISSUE TITLE
Collection function argument to helm-comp-read is always sent an empty string

### ISSUE THREAD

**Issue by fice-t** [emacs-helm/helm#1838]
## Expected behavior
A function `collection` argument to `helm-comp-read` should be sent the current input/pattern as the first argument.

## Actual behavior from `emacs-helm.sh` if possible
The first argument is always the empty string, regardless of the input.

## Steps to reproduce (recipe)
```elisp
(defun what (s _p _t)
  (let ((inhibit-message t))
    (message "string received: %s" s))
  '(one two three))

(helm-comp-read "hello: " #'what)
```
No matter what you type as input, the message is always `"string-received: "`.

## Describe versions of helm, emacs, operating system etc.
Latest helm from MELPA, `emacs 26.0.50 (6ac60c53)`, GNU/Linux

**Comment by thierryvolpiatto** [comment]
Indeed, until now I never used the string parameter because we access such information through `helm-pattern`.  It is set by default to empty string.
Why do you need to access this value ?

**Comment by thierryvolpiatto** [comment]
Also, such value could be accessed only when using a sync sources, which calls its candidates fn at each time pattern changes, otherwise with in-buffer source (completing-read default) this value will not be available as the function is called only once at startup.
We could pass also `helm-pattern` value to the init function of in-buffer but it should be always an empty string to ensure all the candidates are fetched; It should be the case most of the time as helm-pattern is not computed at init time and default to empty string, but to be safe and make the code clear I guess the input parameter should be explicitly empty string.

**Comment by fice-t** [comment]
I'm currently in the process of making a proposal to extend/modularize Emacs's `completing-read-multiple`, which I plan on posting to the `emacs-devel` mailing list in the near future (I'm planning on CC'ing the maintainers of the popular completion frameworks).

As part of the process, I looked for some areas where things could be improved, and one such place I found was completing `key=value` pairs (from reading #1161).

One prerequisite, I believe, is to have a dynamic collection that is updated every time the input/pattern changes. This allows for either key or value completion depending on the context of the input. However, the `collection` procedure has to be aware of the whole input.

I'm not familiar with the internals of Helm, but what would be the issue with the following diff? If I apply it, then it does what I would expect.

```diff
--- /home/alex/.emacs.d/elpa/helm-20170812.952/helm-mode.el
+++ #<buffer helm-mode.el>
@@ -479,7 +479,7 @@ helm-comp-read
            (get-candidates
             (lambda ()
               (let ((cands (helm-comp-read-get-candidates
-                            collection test sort alistp)))
+                            collection test sort alistp helm-pattern)))
                 (helm-cr-default default cands))))
            (history-get-candidates
             (lambda ()

Diff finished.  Sun Aug 13 23:18:48 2017
```
Here's an example that works with the above proposed diff applied:

```elisp
(defvar test-table '(("key" . ("value1" "value2"))
                     ("other" . ("other1" "other2"))))
(defun key-val (s &optional _p _t)
  (let* ((end (string-match "=" s))
         (sub (substring s nil end)))
    (if end
        (mapcar (lambda (c) (concat sub "=" c))
                (cdr (assoc sub test-table)))
      (mapcar #'car test-table))))

(helm-comp-read "hello: " #'key-val)
```

If you type `key=` or `other=`, then you get the completions for the respective values.

FWIW, Ivy supports this behaviour (sending the current input to `collection`):

```elisp
(ivy-read "hello: " #'key-val
          :dynamic-collection t)
```

**Comment by thierryvolpiatto** [comment]
fice-t <notifications@github.com> writes:

> I'm currently in the process of making a proposal to extend/modularize
> Emacs's completing-read-multiple,

`completing-read-multiple` is handled by `completion-in-region`,
`helm-comp-read` is not involved with it.

> I'm not familiar with the internals of Helm, but what would be the
> issue with the following diff? If I apply it, then it does what I
> would expect.

I have commited something similar few minutes ago see commit 9fd57601.
However as I specified in previous post, this will work with
`helm-comp-read` used without :candidates-in-buffer slot otherwise it
will never be called, and we now use by default :candidates-in-buffer
for `completing-read`.
IOW helm-comp-read will work but not completing-read.

> Here's an example that works with the above proposed diff applied:
>
> (defvar test-table '(("key" . ("value1" "value2"))
>                      ("other" . ("other1" "other2"))))
> (defun key-val (s &optional _p _t)
>   (let* ((end (string-match "=" s))
>          (sub (substring s nil end)))
>     (if end
>         (mapcar (lambda (c) (concat sub "=" c))
>                 (cdr (assoc sub test-table)))
>       (mapcar #'car test-table))))
>
> (helm-comp-read "hello: " #'key-val)
>
> If you type key= or other=, then you get the completions for the respective values.

You example is failing with emacs-24.5, but with your key-val fn
modified like this it works:(probably substring is supporting a FROM
argument as nil in emacs-26 ?)

    (defun key-val (s &optional _p _t)
      (let* ((end (string-match "[=]\\'" s))
             (sub (and end (substring s 0 end))))
        (if end
            (mapcar (lambda (c) (concat sub "=" c))
                    (cdr (assoc sub test-table)))
          (mapcar #'car test-table))))

> FWIW, Ivy supports this behaviour (sending the current input to collection):
>
> (ivy-read "hello: " #'key-val
>           :dynamic-collection t)

I guess this is because ivy collect and search its candidates from list
(or function returning lists) but have no concept of candidates storage
in buffer (I just suppose as I know nothing of ivy).

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by fice-t** [comment]
> `completing-read-multiple` is handled by `completion-in-region`, `helm-comp-read` is not involved with it.

I believe that's at least part of the problem that I have with it. I actually have working prototypes of what I'd like for both Helm and Ivy. I'd like to discuss this further on the `emacs-devel` mailing list only after I either figure out how to nicely implement `key=value` support or give up trying.

> I have commited something similar few minutes ago see commit 9fd5760. However as I specified in previous post, this will work with `helm-comp-read` used without :candidates-in-buffer slot otherwise it will never be called, and we now use by default :candidates-in-buffer for `completing-read`. IOW helm-comp-read will work but not completing-read.

Thanks, that works for me. Although, why does the Helm version of `completing-read` always use `:candidates-in-buffer`? Perhaps there should be another argument to add to Emacs's `completing-read` that would tell the `completing-read-function` to use dynamic collections...

>You example is failing with emacs-24.5, but with your key-val fn modified like this it works:(probably substring is supporting a FROM argument as nil in emacs-26 ?)

Yeah, I was just testing it on Emacs 26, where `substring` has an optional FROM argument. Sorry for any confusion (I don't really use Emacs 24 anymore).

**Comment by thierryvolpiatto** [comment]
fice-t <notifications@github.com> writes:

> Thanks, that works for me. Although, why does the Helm version of
> completing-read always use :candidates-in-buffer?

It is much faster and suitable for completing-read 99% of the time, but
if you want to use a sync function for some reason, you can use
completing-read with a special handler added to
`helm-completing-read-handlers-alist`.

e.g (find-file-at-point . helm-completing-read-sync-default-handler)

find-file-at-point is using dynamic collection so for such special case
I have just to give it a sync handler.

> Perhaps there should be another argument to add to Emacs's
> completing-read that would tell the completing-read-function to use
> dynamic collections...

See above how to use dynamic lists as collection for a specific
function.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by fice-t** [comment]
> you can use completing-read with a special handler added to `helm-completing-read-handlers-alist`.

Thanks.

> See above how to use dynamic lists as collection for a specific function.

That's good for Helm, but my particular issue in this case is that I'm concerned with a generic completion interface that 3rd-party packages can use. That means that the package shouldn't have to worry about any specific functions/variables of Helm or any other completion framework. So I believe 3rd-party packages should have some way of specifying that _any_ completion framework should always call the `candidates` procedure whenever the input changes.

**Comment by thierryvolpiatto** [comment]
fice-t <notifications@github.com> writes:

> So I believe 3rd-party packages should have some way of specifying
> that any completion framework should always call the candidates
> procedure whenever the input changes.

I have added a new var that allow setting this globally instead of
specifically for each function, see
`helm-completing-read-dynamic-complete`.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997
