### ISSUE TITLE
Is it possible "helm-occur" to show text dynamically ("on fly")

### ISSUE THREAD

**Issue by lmdic** [emacs-helm/helm#1843]
Windows 10, Emacs 25.1.
I open **helm-occur** and enter text "dalvik". 
Then I open console and start some process that show in console many times text "dalvik".
But in buffer **helm occur** nothing show. 
But if close buffer **helm occur** and start again "helm-occur" , enter text "dalvik" then in buffer **helm occur** success show text "dalvik".
Question: Is it possible to show text in buffer *helm-occur" dynamically("on fly")?

**Comment by thierryvolpiatto** [comment]
lmdic <notifications@github.com> writes:

> Windows 10, Emacs 25.1.
> I open helm-occur and enter text "dalvik".
> Then I open console and start some process that show in console many times text "dalvik".
> But in buffer helm occur nothing show.
> But if close buffer helm occur and start again "helm-occur" , enter text "dalvik" then in buffer helm occur success show text "dalvik".
> Question: Is it possible to show text in buffer *helm-occur" dynamicaly ("on fly")?

1) Open console start process showing dalvik
2) M-x helm-occur (you should have some results)
3) C-x C-s
4) there is some more output in your console
5) go to the *hmoccur* buffer (should be in other window)
6) type "g" to refresh buffer

Otherwise no it can't be done automatically.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by thierryvolpiatto** [comment]
lmdic <notifications@github.com> writes:

> Windows 10, Emacs 25.1.
> I open helm-occur and enter text "dalvik".
> Then I open console and start some process that show in console many times text "dalvik".
> But in buffer helm occur nothing show.

At this point, you can just hit `C-c C-u` to force update in
helm-buffer.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by lmdic** [comment]
`C-c C-u` - this work only if in buffer "helm-occur" before has some text. If before no text, then `C-c C-u` not update.

**Comment by thierryvolpiatto** [comment]
lmdic <notifications@github.com> writes:

> C-c C-u - this work only if in buffer "helm-occur" before has some
> text. If before no text, then C-c C-u not update.

Note that helm-occur have not been designed to monitor the output of
processes, (and will not) I am just trying here to propose a workaround.

Why don't you start your process in the shell buffer and start
helm-occur when the output starts arriving in shell buffer ?
Then you only have to C-c C-u for update it, a saved buffer will do
also (you will have to update it with "g" this time).

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by thierryvolpiatto** [comment]
I am not sure to understand exactly what you want to do, but IIUC you
want to monitor the output of a process, and specially the line matching
a specific string. If so I think helm-occur is not the right tool to
use, using for example two tmux panel outside of emacs would be much
more efficient:

One panel running your process redirected to a file.
A second panel running "tailf your_file.log | grep foo".

Was just a thought HTH.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by thierryvolpiatto** [comment]
lmdic <notifications@github.com> writes:

> C-c C-u - this work only if in buffer "helm-occur" before has some
> text.

Should be fixed now.

Thanks.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997
