### ISSUE TITLE
helm-semantic-or-imenu fails to use semantic in emacs-lisp files

### ISSUE THREAD

**Issue by oracleyue** [emacs-helm/helm#1845]
## Expected behavior
Semantic fails to offer tags in **elisp** for *helm-semantic-or-imenu* (*Imenu* is used instead, as explained in your comments); however, it works well for C++ files, as shown in following figures. I guess it should be due to my configuration problems, since the demo in [helm-tudo](https://tuhdo.github.io/helm-intro.html) shows semantic works for elisp files. I want to use semantic instead of imenu to parse elisp files.

![screenshot from 2017-08-31 00-07-04](https://user-images.githubusercontent.com/5046605/29897475-54e11958-8de1-11e7-9aae-a028fdba0d3d.png)
![screenshot from 2017-08-31 00-07-27](https://user-images.githubusercontent.com/5046605/29897476-56b0229c-8de1-11e7-924d-665ec72fb270.png)

## Requests
Could you confirm whether semantic works in *helm-semantic-or-imenu* for elisp files or not? If yes, could you briefly check wether the following configurations have problems? Did I miss some essential settings for working with elisp? (I was trying to use minimal features of CEDET, so probably I forgot to turn something?)

### Configurations

```emacs-lisp
(setq helm-semantic-fuzzy-match t
      helm-imenu-fuzzy-match    t)
(semantic-mode 1) ;; enable necessary CEDET backend
(with-eval-after-load 'helm-semantic      ;; default: c, python, elisp
  (push '(c++-mode . semantic-format-tag-summarize) helm-semantic-display-style))
;; setting GNU /global/ for /semantic-symref/
(setq semantic-symref-tool 'global)
```

## Actual behavior from `emacs-helm.sh` if possible (See note at bottom)
   (and Steps to reproduce (recipe))

Run `emacs-helm.sh` and evaluate the above configurations in `*scratch*`. Then open any *.el file, run `C-x c i`, show results offered by Imenu; open any *.h or *cpp files, run `C-x c i`, show results offered by Semantic.

## Describe versions of helm, emacs, operating system etc.

*helm*  : 20170817.2240
*emacs* : 25.2.1 (linux) and 25.1.1 (osx)
*Linux* : Arch Linux 4.12.8-2
*OSX*   : Sierra

## IMPORTANT NOTE:

If you are using a Unix or GNU-Linux system there is no excuses
to not use `emacs-helm.sh` to reproduce your bug in 99% of the cases.

**Comment by thierryvolpiatto** [comment]
Zuogong Yue <notifications@github.com> writes:

> Could you confirm whether semantic works in helm-semantic-or-imenu for
> elisp files or not?

AFAIK yes it works, however some cl functions will not be recognized you
need a patched "/lisp/cedet/semantic/bovine/el.el" file.

> Did I miss some essential settings for working with elisp?

Yes:

    (when (fboundp 'semantic-default-elisp-setup)
       (semantic-default-elisp-setup))

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Here the patch I use (submitted to emacs long time ago and never had answer as always): 

```diff
diff --git a/lisp/cedet/semantic/bovine/el.el b/lisp/cedet/semantic/bovine/el.el
index ba6b05d7600..bf1adad8a6a 100644
--- a/lisp/cedet/semantic/bovine/el.el
+++ b/lisp/cedet/semantic/bovine/el.el
@@ -1,6 +1,6 @@
 ;;; semantic/bovine/el.el --- Semantic details for Emacs Lisp
 
-;; Copyright (C) 1999-2005, 2007-2017 Free Software Foundation, Inc.
+;; Copyright (C) 1999-2005, 2007-2014 Free Software Foundation, Inc.
 
 ;; Author: Eric M. Ludlam <zappo@gnu.org>
 
@@ -149,10 +149,8 @@ compound strings."
 	 (nth 1 form))
 	(t nil)))
 
-(defcustom semantic-elisp-store-documentation-in-tag nil
-  "When non-nil, store documentation strings in the created tags."
-  :type 'boolean
-  :group 'semantic)
+(defvar semantic-elisp-store-documentation-in-tag nil
+  "*When non-nil, store documentation strings in the created tags.")
 
 (defun semantic-elisp-do-doc (str)
   "Return STR as a documentation string IF they are enabled."
@@ -245,9 +243,12 @@ Return a bovination list to use."
 			 (eq (car form) 'define-overloadable-function))
        ))
   defun
+  cl-defun
   defun*
   defsubst
+  cl-defsubst
   defmacro
+  cl-defmacro
   define-overload ;; @todo - remove after cleaning up semantic.
   define-overloadable-function
   )
@@ -392,6 +393,7 @@ Return a bovination list to use."
          (cons nil nil)
          )))
   defstruct
+  cl-defstruct
   )
 
 (semantic-elisp-setup-form-parser
@@ -610,7 +612,7 @@ Returns non-nil it is not possible to go up a context."
   (let ((last-up (semantic-up-context-default)))
   (while
       (and (not (looking-at
-		 "(\\(let\\*?\\|def\\(un\\|method\\|generic\\|\
+		 "(\\(let\\*?\\|cl-defun\\|def\\(un\\|method\\|generic\\|\
 define-mode-overload\\)\
 \\|with-slots\\)"))
 	   (not last-up))
@@ -702,7 +704,7 @@ of `let' or `let*', grab those variable names."
 	  ;; Snart args...
 	  (up-list -1)
 	  (forward-char 1)
-	  (forward-word-strictly 1)
+	  (forward-word 1)
 	  (skip-chars-forward "* \t\n")
 	  (let ((arglst (read (buffer-substring-no-properties
 			       (point)

```

**Comment by thierryvolpiatto** [comment]
Forget to mention that you have to add `semantic-default-elisp-setup` to `semantic-mode-hook` before starting `semantic-mode`.

**Comment by oracleyue** [comment]
@thierryvolpiatto Impressive! Thanks a lot for your prompt reply!! Problem solved!
