### ISSUE TITLE
Switching buffers

### ISSUE THREAD

**Issue by bradprob** [emacs-helm/helm#1846]
Since the last helm update when I try switch between my buffers I am getting this error:
helm-highlight-buffers: Symbol’s value as variable is void: dired-buffers

This is the help output for my key binding:

C-x b runs the command helm-mini (found in global-map), which is an
interactive autoloaded compiled Lisp function in ‘helm-buffers.el’.
It is bound to C-x b.
(helm-mini)
Preconfigured ‘helm’ lightweight version (buffer -> recentf).

**Comment by thierryvolpiatto** [comment]
bradprob <notifications@github.com> writes:

> Since the last helm update when I try switch between my buffers I am getting this error:
> helm-highlight-buffers: Symbol’s value as variable is void: dired-buffers

Thanks, should be fixed now.

-- 
Thierry

**Comment by bradprob** [comment]
It is indeed solved! Thaks

**Comment by bladealslayer** [comment]
@bradprob `(require 'dired)` seems to be missing also from some fns in `helm-buffers.el`. At least calls to [helm-buffer--details](https://github.com/emacs-helm/helm/blob/master/helm-buffers.el#L335) fail for me under some conditions.

**Comment by hotpxl** [comment]
Same here. Found calls to `helm-buffer--details` breaking. I'll try to catch a traceback next time it happens.

**Comment by thierryvolpiatto** [comment]
Should be fixed again.

Thanks.
