### ISSUE TITLE
Recursive grep not working - Symbol’s function definition is void: helm-adaptive-sort

### ISSUE THREAD

**Issue by zombiegonsdude** [emacs-helm/helm#1850]
## Expected behavior
Recursive grep on selected folder with C-u C-s from within find files

## Actual behavior from `emacs-helm.sh` if possible (See note at bottom)
find files exits with the following error.
"Symbol’s function definition is void: helm-adaptive-sort"

## Steps to reproduce (recipe)
- C-x C-f helm-find-files
- highlight directory
- C-u C-s

## Describe versions of helm, emacs, operating system etc.
20170909.613 from melpa

## IMPORTANT NOTE:

If you are using a Unix or GNU-Linux system there is no excuses 
to not use `emacs-helm.sh` to reproduce your bug in 99% of the cases.

**Comment by thierryvolpiatto** [comment]
Zombiegons <notifications@github.com> writes:

> Expected behavior
>
> Recursive grep on selected folder with C-u C-s from within find files
>
> Actual behavior from emacs-helm.sh if possible (See note at bottom)
>
> find files exits with the following error.
> "Symbol’s function definition is void: helm-adaptive-sort"

Should be fixed now.

Thanks for the report.

-- 
Thierry

**Comment by zombiegonsdude** [comment]
Quick question, unrelated to the actual bug. I wanted to include a backtrace with the report, but was unable to properly copy the buffer. I was using the emacs-helm.sh to run the session. Is there a proper way of copying a stack trace from that buffer? I couldn't find any info in the actual emacs docs about doign this.
