### ISSUE TITLE
keep dot directories on top in helm files buffer

### ISSUE THREAD

**Issue by CeleritasCelery** [emacs-helm/helm#1853]
I am sure this has been asked before, but I can't seem to find it anywhere. Is there a way to sort the "dot" directories (`.` and `..`) so that they are always on top of the buffer? The sorting order for all the rest of the files and directories are fine. I just want `.` and `..` to stay on top. 

Note: using Spacemacs if that is relevant.

**Comment by thierryvolpiatto** [comment]
CeleritasCelery <notifications@github.com> writes:

> I am sure this has been asked before, but I can't seem to find it
> anywhere. Is there a way to sort the "dot" directories (. and ..) so
> that they are always on top of the buffer? The sorting order for all
> the rest of the files and directories are fine. I just want . and
> .. to stay on top.

If you are asking for helm-find-files, dotted directories are always on
top.

> Note: using Spacemacs if that is relevant.

Please don't use spacemacs for reporting bugs, spacemacs is so hacked
that bug reports with spacemacs enabled are irrelevants.

--
Thierry

**Comment by CeleritasCelery** [comment]
the buffer is `*Helm file completions*`. And it is only the first directory. If I move up a directory the dot files are on top. I will have to see if this is spacemacs related.

**Comment by thierryvolpiatto** [comment]
CeleritasCelery <notifications@github.com> writes:

> the buffer is *Helm file completions*. And it is only the first
> directory. If I move up a directory the dot files are on top.

This is helm-read-file-name, and as helm-find-files dotted files are
always on top.

> I will have to see if this is spacemacs related.

Please reproduce your bugs with emacs-helm.sh.

--
Thierry

**Comment by CeleritasCelery** [comment]
I tried it with stock helm and the dot directories are always on top. Sounds like a Spacemacs problem.
