### ISSUE TITLE
emacs-helm.sh and non-standard ELPA dirs

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#1854]
I like to have my `package-user-dir` set to `~/.cache/emacs/elpa`.  Starting `emacs-helm.sh` generates the following error:

> package-activate-1: Unable to activate package ‘helm’.
> Required package ‘async-1.9.2’ is unavailable

I see that there is a provision for that case:
```
(unless (file-equal-p package-user-dir "~/.emacs.d/elpa")
  (add-to-list 'package-directory-list (directory-file-name
                                        (file-name-directory
                                         (directory-file-name default-directory)))))
```
but I don't quite understand the intention.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I like to have my package-user-dir set to ~/.cache/emacs/elpa. Starting emacs-helm.sh generates the following error:
>
>     package-activate-1: Unable to activate package ‘helm’.
>     Required package ‘async-1.9.2’ is unavailable
>    
> I see that there is a provision for that case:

Isn't it fixing your package-user-dir setting ?

> (unless (file-equal-p package-user-dir "~/.emacs.d/elpa")
>   (add-to-list 'package-directory-list (directory-file-name
>                                         (file-name-directory
>                                          (directory-file-name default-directory)))))
>
> but I don't quite understand the intention.

I see I added a comment:

    ;; User is maybe using a non standard `package-user-dir'.
    ;; Don't modify `package-user-dir' but `package-directory-list'
    ;; because user is perhaps starting helm from a non elpa installation.

The code above should add in your case ~/.cache/emacs/elpa to
package-directory-list:

    (let ((default-directory "~/.cache/emacs/elpa/helm-2222-12-12/"))
      (directory-file-name
       (file-name-directory
        (directory-file-name default-directory))))
    =>"~/.cache/emacs/elpa"

-- 
Thierry

**Comment by Ambrevar** [comment]
Where am I supposed to start the script from?
From the `package-directory-list` provision, it seems that I should start it from `~/.cache/emacs/elpa` so that it can find `async` there.  From your last example, you are implying that `default-directory` (i.e. my pwd?) should be `~/.cache/emacs/elpa/helm-2222-12-12/` but I don't understand how it's supposed to find `async` from there.

Either way, it always fails.  Am I missing something?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Where am I supposed to start the script from?

From the helm directory.

> From the package-directory-list provision, it seems that I should
> start it from ~/.cache/emacs/elpa so that it can find async
> there. From your last example, you are implying that default-directory
> (i.e. my pwd?) should be ~/.cache/emacs/elpa/helm-2222-12-12/ but I
> don't understand how it's supposed to find async from there.

When you start from ~/.cache/emacs/elpa/helm-2222-12-12/ the lisp
snippet in helm-cfg.el will deduce that helm is installed in
~/.cache/emacs/elpa/ and add this directory to package-directory-list
then package.el should find all the packages contained in this directory
and load them.

> Either way, it always fails. Am I missing something?

So when you cd to ~/.cache/emacs/elpa/helm-2222-12-12/ and use
./emacs-helm.sh it fails ?

If so it is a bug and we should fix it (it may be also an emacs bug with
package-directory-list, don't know yet).

--
Thierry

**Comment by Ambrevar** [comment]
Yes, it fails.  To be honest I am not sure how it was supposed to work.  Could you try to reproduce?  That might enlighten us.

**Comment by Ambrevar** [comment]
Err... I just tried another time and it works.  :/
Please leave this issue open until I can try on my other machines, then I'll confirm whether there is an actual issue or not.

**Comment by Ambrevar** [comment]
Can't reproduce, closing thins.
