### ISSUE TITLE
Possible issue with helm--remap-mouse-mode-map never being reset

### ISSUE THREAD

**Issue by rswgnu** [emacs-helm/helm#1856]
The body of the helm--remap-mouse-mode minor-mode contains this:

 (unless helm-alive-p
    (setq helm--remap-mouse-mode-map nil))

And the only other place that helm--remap-mouse-mode-map is set is in its defvar as far as I can see.  So once this map is set to nil by the minor mode, there is nothing in the minor mode to later re-establish its value; it can't be used again when the minor mode is re-enabled.  The purpose of this map is to disable all global mouse keys, so sometimes when using helm they will all be disabled and sometimes they will not be, which could lead to inconsistent behavior.  The fix would be to have the minor mode reset the mode-map's value when needed.

I will see if I can fix this with other changes I am making if you just verify that it is indeed an issue.  I understand that helm overrides this map with specific text property bindings in places but that does not affect other buffer locations without such properties.

**Comment by thierryvolpiatto** [comment]
Robert Weiner <notifications@github.com> writes:

> The body of the helm--remap-mouse-mode minor-mode contains this:
>
> (unless helm-alive-p
> (setq helm--remap-mouse-mode-map nil))
>
> And the only other place that helm--remap-mouse-mode-map is set is in
> its defvar as far as I can see. So once this map is set to nil by the
> minor mode, there is nothing in the minor mode to later re-establish
> its value; it can't be used again when the minor mode is
> re-enabled. The purpose of this map is to disable all global mouse
> keys, so sometimes when using helm they will all be disabled and
> sometimes they will not be, which could lead to inconsistent
> behavior. The fix would be to have the minor mode reset the mode-map's
> value when needed.
>
> I will see if I can fix this with other changes I am making if you
> just verify that it is indeed an issue. I understand that helm
> overrides this map with specific text property bindings in places but
> that does not affect other buffer locations without such properties.

See my last post in issue #1857, there is no need to implement ways to
use helm buffers (bindings, mouse or whatever) when helm is not alive.

--
Thierry

**Comment by rswgnu** [comment]
On Tue, Sep 12, 2017 at 11:59 PM, Thierry Volpiatto <
notifications@github.com> wrote:

>
> See my last post in issue #1857, there is no need to implement ways to
> use helm buffers (bindings, mouse or whatever) when helm is not alive.
>

​See my last answer for the rationale.

Bob

**Comment by rswgnu** [comment]
I have adapted to using helm buffers only when they are active, though another useful feature of global mouse button support is that a global mouse button when clicked in an inactive helm completion buffer can resume it and make it active again; then further mouse clicks can activate items for a seamless experience from the mouse.
