### ISSUE TITLE
Feature Request: Make all/most helm key bindings work in the helm completion buffer

### ISSUE THREAD

**Issue by rswgnu** [emacs-helm/helm#1857]
Now that there is mouse support and point might move from the minibuffer window to the helm completion buffer, it would be very useful to still be able to use helm keys, especially the movement keys when in the completion buffer.  When an execute action command is issued, the associated function could return to the minibuffer and continue the action as things do now.

**Comment by thierryvolpiatto** [comment]
Robert Weiner <notifications@github.com> writes:

> Now that there is mouse support and point might move from the
> minibuffer window to the helm completion buffer, it would be very
> useful to still be able to use helm keys, especially the movement keys
> when in the completion buffer. When an execute action command is
> issued, the associated function could return to the minibuffer and
> continue the action as things do now.

It seems you want absolutely to use dead helm buffers, why don't you use
helm-resume for this purpose ?

--
Thierry

**Comment by rswgnu** [comment]
>
> It seems you want absolutely to use dead helm buffers, why don't you use
> helm-resume for this purpose ?
>

​Because whenever I have a helm buffer on screen (maybe I have several for
developmental purposes or for use as pinned menus), I want to be able to
use my mouse buttons consistently to either select the default action for
any helm candidate or see what its default action is.  Often this might be
when helm is not running and I don't want to go back to the keyboard to
start it up.  Plus, resume only restarts the last helm, not one I might
have left around an hour ago.

Again, I think helm is incredibly useful but with a few modifications will
expand its utility, reach and usability even further.

Bob

**Comment by thierryvolpiatto** [comment]
Robert Weiner <notifications@github.com> writes:

>>
>> It seems you want absolutely to use dead helm buffers, why don't you use
>> helm-resume for this purpose ?
>>
>
> ​Because whenever I have a helm buffer on screen (maybe I have several for
> developmental purposes or for use as pinned menus), I want to be able to
> use my mouse buttons consistently to either select the default action for
> any helm candidate or see what its default action is. Often this might be
> when helm is not running and I don't want to go back to the keyboard to
> start it up.

Again I don't understand why you insist to reuse dead helm buffers when
it is so easy (and more powerful) to resume them.

> Plus, resume only restarts the last helm, not one I might have left
> around an hour ago.

No, helm-resume allow resuming any resumable session, by cycling or with
helm completion (see helm help, it is fully documented).

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Also note that helm-resume is usable from lisp to switch to a particular buffer by passing it a buffer as argument, e.g `(helm-resume "*helm find files*")`.

**Comment by rswgnu** [comment]
On Wed, Sep 13, 2017 at 1:25 PM, Thierry Volpiatto <notifications@github.com
> wrote:

> Also note that helm-resume is usable from lisp to switch to a particular
> buffer by passing it a buffer as argument, e.g (helm-resume "*helm find
> files*").
>
​Got it.  Thanks for all the pointers.  This is probably what I need.  I
was trying to avoid having the minibuffer active and helm grabbing the
keystrokes but I can probably work with this as long as I am able to
override the local mouse buttons.  I will work with helm-resume and see how
that works.

**Comment by thierryvolpiatto** [comment]
Robert Weiner <notifications@github.com> writes:

> On Wed, Sep 13, 2017 at 1:25 PM, Thierry Volpiatto <notifications@github.com
>> wrote:
>
>> Also note that helm-resume is usable from lisp to switch to a particular
>> buffer by passing it a buffer as argument, e.g (helm-resume "*helm find
>> files*").
>>
> ​Got it. Thanks for all the pointers. This is probably what I need. I
> was trying to avoid having the minibuffer active and helm grabbing the
> keystrokes but I can probably work with this as long as I am able to
> override the local mouse buttons.

If you use helm-resume to switch to your helm buffers, you probably don't
need anymore to disable helm bindings (AFAIU).

> I will work with helm-resume and see how that works.

Thanks.

-- 
Thierry

**Comment by rswgnu** [comment]
On Wed, Sep 13, 2017 at 2:54 PM, Thierry Volpiatto <notifications@github.com
> wrote:

>
> > I will work with helm-resume and see how that works.
>

​After a helm-resume and selection of a candidate item, how can I emulate
the C-j and RET key presses in Lisp code (to invoke an action)?  I have
tried the following but it does not work the same as manual key presses:

(setq unread-command-events (listify-key-sequence (kbd "C-j")))
or
(setq unread-command-events (listify-key-sequence (kbd "RET")))

Calling the commands bound to these keys interactively doesn't seem to work
either, it just pops me out of the helm prompt.
I am testing with helm-info.

Bob

**Comment by rswgnu** [comment]
I just happened upon this snippet from 2 years ago and it seems to work.
It shows there is some interest in this.

https://www.reddit.com/r/emacs/comments/376won/select_helm_candidate_by_using_mouse_click/

​Bob
​

**Comment by thierryvolpiatto** [comment]
Robert Weiner <notifications@github.com> writes:

> I just happened upon this snippet from 2 years ago and it seems to work.
> It shows there is some interest in this.
>
> https://www.reddit.com/r/emacs/comments/376won/select_helm_candidate_by_using_mouse_click/

AFAIK I have already implemented mouse usage in helm, so why are you
pointing on this?

-- 
Thierry

**Comment by rswgnu** [comment]
On Thu, Sep 14, 2017 at 12:19 AM, Thierry Volpiatto <
notifications@github.com> wrote:


> AFAIK I have already implemented mouse usage in helm, so why are you
> pointing on this?


​Because it shows a working command that can be bound to a global mouse key
(but doesn't yet override local bindings).

Maybe a solution is just to extract the text-property mouse bindings for
Helm and make them a minor mode with a normal keymap (putting the
conditional logic into the bound commands themselves).  Then a user could
change both the mouse buttons bound and the commands they are bound to,
however desired.  That would then largely remove the need and desire for
global buttons.  What do you think of that?

I have some code that shadows the text property keymap and utilizes current
global mouse bindings when in helm mode but it needs some testing; it uses
a new minor-mode keymap.  I think changing the text property mouse bindings
to a minor mode map would be a cleaner solution as the context-sensitive
nature of these bindings is not that great and could be tested dynamically
on each press, I would think.

Bob

**Comment by thierryvolpiatto** [comment]
Closing because this is still related to usage of inactive helm buffers.
