### ISSUE TITLE
Feature Request: Need a way to quickly see main helm package commands

### ISSUE THREAD

**Issue by rswgnu** [emacs-helm/helm#1858]
There are many helm related packages that use helm-<package-name> as the main way to invoke the package.  But the 'helm-' namespace is filled with many other commands, so when you type 'M-x helm-', you see a lengthy list of commands.  It is difficult to find just the main entry points for each package, e.g. M-x helm-info.

I propose a simple new naming standard be added for such commands (the old names can remain as well), maybe with the prefix 'hlm-' so that one could quickly see and invoke just the main entry point commands.

Or an alternative would be a helm command that used helm itself to list all the available main commands and then invoked the selected one.  Maybe call it helm-commands or helm-package-commands.

**Comment by thierryvolpiatto** [comment]
Robert Weiner <notifications@github.com> writes:

> There are many helm related packages and many of them use helm-s as
> the main way to invoke the package. But the helm- namespace is filled
> with many other commands so when you type 'M-x helm-', you typically
> see a very long list of commands. It is then near impossible to just
> find the main entry points for each package, e.g. M-x helm-info.

Use helm-M-x instead of standard execute-extended-command, then you can
use fuzzy:

    (setq helm-M-x-fuzzy-match t)

Then just type hlminfo or hinfo

Or if you use multi match you can type "helm info"

> I propose a simple new naming standard be adopted for such commands,
> maybe with the prefix 'hlm-' so that one could quickly see and invoke
> just the main entry point commands.

No, I think you just need to get used of helm completion which is much
powerful than standard emacs completion.

> Or an alternative would be a helm command that used helm itself to
> list all the available main commands and then invoked the selected
> one. Maybe call it helm-commands or helm-package-commands.

It is helm-M-x

--
Thierry

**Comment by rswgnu** [comment]
On Tue, Sep 12, 2017 at 11:52 PM, Thierry Volpiatto <
notifications@github.com> wrote:

>
> Robert Weiner <notifications@github.com> writes:
>
> > There are many helm related packages and many of them use helm-s as
> > the main way to invoke the package. But the helm- namespace is filled
> > with many other commands so when you type 'M-x helm-', you typically
> > see a very long list of commands. It is then near impossible to just
> > find the main entry points for each package, e.g. M-x helm-info.
>
> Use helm-M-x instead of standard execute-extended-command, then you can
> use fuzzy:
>
> (setq helm-M-x-fuzzy-match t)
>
> Then just type hlminfo or hinfo
>
> Or if you use multi match you can type "helm info"
>

​Thank you for that pointer.  I tried it out and it is good if you know
what you are looking for so you can narrow down the search quickly since it
still initially shows many commands.  It didn't seem to list all autoloaded
helm package (or module) entry points, just the ones I had used previously
from history.

Part of my point was that a user might install six new helm packages for
trial later and then a week later be ready to test them out but he doesn't
remember which ones they were so he has to search his package list and then
figure out the command names for each package.  Helm could easily focus his
attention by having a single command that lists these entry points only
through some convention established for helm.  That would be so much
simpler and more helpful in that context.  It is just an idea I would like
you to consider a bit more.

Bob

**Comment by thierryvolpiatto** [comment]
Sorry but I still don't understand how this would be helpful.

**Comment by rswgnu** [comment]
Just do a M-x helm- or helm-M-x and try to find all the autoloaded helm
command/entry points you have available on your system.  You can't, so
there is no convenient way for helm users (including extension packages) to
find what commands to try out.  They have to spend lots of time reviewing
documentation or examining code before they can experiment.  And this
effort is repeated by every user.
My point was, with a little code, the situation could be improved greatly.

Bob

**Comment by thierryvolpiatto** [comment]
Robert Weiner <notifications@github.com> writes:

> Just do a M-x helm- or helm-M-x and try to find all the autoloaded helm
> command/entry points you have available on your system. You can't,

Not autoloaded commands but many helm interative commands, the one that
have a 'helm-only property.

> so there is no convenient way for helm users

There is, try M-x helm-apropos.

-- 
Thierry

**Comment by rswgnu** [comment]
On Sat, Sep 23, 2017 at 11:41 AM, Thierry Volpiatto <
notifications@github.com> wrote:

>
> Robert Weiner <notifications@github.com> writes:
>
> > Just do a M-x helm- or helm-M-x and try to find all the autoloaded helm
> > command/entry points you have available on your system. You can't,
>
> Not autoloaded commands but many helm interative commands, the one that
> have a 'helm-only property.


{M-x ​helm-M-x RET helm-} is a start at showing key entry points but for me
it produces 65 matches.  Instead of just the helm-only property, you could
make a helm-entry property and then have a command that justs lists (and
maybe shows a one line help next to) each command.  That would be a great
way to get people to explore more facets of helm.

For me, now that I have dived into it a bit, the Hyperbole menu I developed
is sufficient as this gateway for now for me.

​
> ​​
>
> ​​
> > so there is no convenient way for helm users
> ​​
>
> ​​
> There is, try M-x helm-apropos.


​I got over 100 matches when I tried that and typed in 'helm'.  It's like
pointing someone to a large office building and saying, "I'll meet you in
the office.  I just pointed you to it."  Now helm is better than this
because it has documentation which explains a bunch of the entry points but
I am thinking of something that lets someone download the helm package and
go directly to trying out its main features interactively.  You put a lot
of effort into minimizing keystrokes and making users efficient once they
know their way around helm but why not make it more inviting when they are
first trying it out and have not yet studied its features and are still
trying to decide whether to integrate it into their toolset or not?

Bob




​

**Comment by thierryvolpiatto** [comment]
I don't understand what you want here, you can have all the helm commands with helm-apropos, perhaps some packages are not loaded yet, if you don't remember which packages you have installed through Melpa, use M-x helm-list-elisp-packages-no-fetch (C-x c @) and look at the installed packages with `M-I`, you will have then all the helm packages installed and know which prefix to use e.g `helm-foo-`.
Feel free to open a new issue once what you want is clear, for now I don't understand what you want.
Thanks.
