### ISSUE TITLE
Make Helm help behaviour more standard

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#1859]
Now that I'm editing Helm's documentation, I find it particularly annoying not to be able to keep the help window open (the one raised by `C-h m`) while resuming my Emacs activities, i.e. editing the documentation.

Why this strange setup in the first place?  Wouldn't it be simpler to fire up a read-only `outline-mode` / `org-mode` buffer?
Why the special bindings?  I'm an Evil user, the binding context-switch is somewhat disturbing and it's very non-Emacs-ish to have bindings that are _not configurable_.

What do you think?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Now that I'm editing Helm's documentation, I find it particularly
> annoying not to be able to keep the help window open (the one raised
> by C-h m) while resuming my Emacs activities, i.e. editing the
> documentation.
>
> Why this strange setup in the first place? Wouldn't it be simpler to
> fire up a read-only outline-mode / org-mode buffer?

Doing this would loose your helm session, the point is to be able to
read the documentation without quitting helm.

> Why the special bindings?

Because we are using a loop reading events, so these events have to be
configured specially for the loop (i.e they are not regular bindings
with a map).

> I'm an Evil user, the binding context-switch is somewhat disturbing
> and it's very non-Emacs-ish to have bindings that are not
> configurable.

Perhaps, but at this point helm is not "emacs-ish" at all, providing a
help system which is not conventional because helm have its own loop
waiting for events.

> What do you think?

Implementing a new helm system with keymap would not be trivial, perhaps
it would be better to provide a way to configure the actual bindings
like here:

https://github.com/thierryvolpiatto/zop-to-char/blob/master/zop-to-char.el#L63


--
Thierry

**Comment by Ambrevar** [comment]
OK, I did not think of that.

Is it possible to display the documentation independently though?  E.g. something like `M-x helm-help-buffer` and shows a normal read-only buffer.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> OK, I did not think of that.
>
> Is it possible to display the documentation independently though?
> E.g. something like M-x helm-help-buffer and shows a normal read-only
> buffer.

M-x helm-documentation

Will not be read only though.

>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.*


--
Thierry

**Comment by Ambrevar** [comment]
This is great!  Can't believe I missed that.  Is is referenced anywhere?

Isn't it possible to make it read-only by default?
Also I see that Helm generates the `helm-doc.org` file in `.emacs.d`.  Why not simply using a buffer without creating a file?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> This is great! Can't believe I missed that. Is is referenced anywhere?

AFAIK no, and the only reference I see is in documentation is this:

    M-x helm-help		Shows this generic Helm help.

which is wrong, I will fix this soon.
 
> Isn't it possible to make it read-only by default?

Sure but see below.

> Also I see that Helm generates the helm-doc.org file in .emacs.d. Why
> not simply using a buffer without creating a file?

Just to allow one editing the buffer and adding personal notes.

--
Thierry

**Comment by Ambrevar** [comment]
It is also referenced in the wiki's FAQ.

Alright for the notes, but what happens when the documentation gets updated?  Is it overwritten?  Merged?  Ignored?  Sounds like you are trying to do something impossible here.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> It is also referenced in the wiki's FAQ.
>
> Alright for the notes, but what happens when the documentation gets
> updated? Is it overwritten?

It is overwritten as soon as you call the command with C-u.
There is no way actually to merge the new upstream changes unless
maintaining the file with VCS.

> Merged? Ignored? Sounds like you are trying to do something impossible
> here.

I try nothing, I just let the possibility to people to edit the file and
do what they want with it, but maybe I am wrong and it is better to make
it readonly and update it automatically?

--
Thierry

**Comment by Ambrevar** [comment]
Yes, I would say so: a documentation that does not update without a `C-u` will confuse unwary users.

Documentation's first and foremost goal is to be straightforward to use: the user should not have to learn _how to_ fire up the documentation.  It's devil circle.

**Comment by thierryvolpiatto** [comment]
Now helm-documentation is displayed in a read-only buffer with view-mode enabled.

**Comment by Ambrevar** [comment]
Looks good to me, thanks!

**Comment by thierryvolpiatto** [comment]
Ok, thanks, so I am closing this one.
