### ISSUE TITLE
Suggestion about "new issue" text: explain `emacs-helm.sh`

### ISSUE THREAD

**Issue by zck** [emacs-helm/helm#1867]
In the text that's displayed when creating a new issue, the second header is as follows:

> Actual behavior from `emacs-helm.sh` if possible (See note at bottom)

So we have to look at the note at the bottom of the page. It reads:

> IMPORTANT NOTE:
>
>If you are using a Unix or GNU-Linux system there is no excuses 
to not use `emacs-helm.sh` to reproduce your bug in 99% of the cases.

I think this text could be more helpful, especially to people who have never heard of `emacs-helm.sh` before. Although I don't think you mean to, this message comes across as a bit passive-aggressive.

So there are two things I want to do in a rewrite:

1. Explain what `emacs-helm.sh` *is*.
2. Explain how to use it.

The first one should probably be done in the issue text, to provide context to people and be less aggressive. The second could be done elsewhere, and linked to.

Here's my proposal for the first text:

> If you're on a Linux or Mac, please use `emacs-helm.sh` to reproduce a bug before reporting it. `emacs-helm.sh` is a way to start Emacs preconfigured only with Helm. Instructions for reproducing bugs with it can be found \<here\>.

"\<here\>" at the end of that line would link out to the complete instructions.

And my proposal for the complete `emacs-helm.sh` instructions, to be on a separate page and linked to:

>`emacs-helm.sh` is a way to start Emacs preconfigured only with Helm. It's designed to be used to reproduce bugs in a way that ensures the bug is in Helm, and not elsewhere. To start up an Emacs instance with it, follow these instructions:
>
>1. Clone the helm git repository and `cd` into it.
>2. Run `make`.
>3. Run `./emacs-helm.sh`.
>4. Reproduce your bug.

I'm not 100% sure this is complete, having never used `emacs-helm.sh` before, but it seems like those are the complete steps required. My hope is to make bug reporting both easier for the reporter (they won't be confused as to how to submit a high-quality bug report), and more useful to the Helm maintainers (more bug reports will include reproducible instructions from `emacs-helm.sh`).

**Comment by thierryvolpiatto** [comment]
zck <notifications@github.com> writes:

>     If you're on a Linux or Mac, please use emacs-helm.sh to reproduce
>     a bug before reporting it. emacs-helm.sh is a way to start Emacs
>     preconfigured only with Helm.  Instructions for reproducing bugs
>     with it can be found <here>.
>
> "<here>" at the end of that line would link out to the complete instructions.

AFAIK links are not working in issue forms.

> And my proposal for the complete emacs-helm.sh instructions, to be on
> a separate page and linked to:
>
>     emacs-helm.sh is a way to start Emacs preconfigured only with
>     Helm. It's designed to be used to reproduce bugs in a way that
>     ensures the bug is in Helm, and not elsewhere. To start up an
>     Emacs instance with it, follow these instructions:
>
>      1. Clone the helm git repository and cd into it.
>      2. Run make.
>      3. Run ./emacs-helm.sh.
>      4. Reproduce your bug.

This will confuse most people that are using Melpa to install helm i.e
"Why do I need to install Git and clone the helm repository to report a
bug"

> I'm not 100% sure this is complete, having never used emacs-helm.sh
> before, but it seems like those are the complete steps required. My
> hope is to make bug reporting both easier for the reporter (they won't
> be confused as to how to submit a high-quality bug report), and more
> useful to the Helm maintainers (more bug reports will include
> reproducible instructions from emacs-helm.sh).

Thanks, PR welcomed.

--
Thierry

**Comment by zck** [comment]
> AFAIK links are not working in issue forms.

That's true. However, I think that even if users had to copy and paste a link, that would be better than not describing how to use emacs-helm.sh.

> This will confuse most people that are using Melpa to install helm i.e "Why do I need to install Git and clone the helm repository to report a bug"

Yes, this is confusing! But it is my current understanding of how to use emacs-helm.sh. How should it be used?

**Comment by thierryvolpiatto** [comment]
zck <notifications@github.com> writes:

>     AFAIK links are not working in issue forms.
>
> That's true. However, I think that even if users had to copy and paste
> a link, that would be better than not describing how to use
> emacs-helm.sh.

I don't think a link is needed, only specifying to cd to helm directory
and run the script is enough, see below.

>     This will confuse most people that are using Melpa to install helm i.e "Why do I need to install Git and clone the helm repository to report a bug"
>
> Yes, this is confusing! But it is my current understanding of how to use emacs-helm.sh. How should it be used?

cd /helm/directory
./emacs-helm.sh -h

All option available in emacs are usable e.g "-nw"

doesn't matter if the helm directory have been installed by git or package.el.

NOTE: A symlink from the helm directory to somewhere in your PATH is
also working, however as the helm directory name chnage always when
installing from Melpa (e.g helm-2222-12-22) your symlink will be invalid
at each update.

--
Thierry

**Comment by Ambrevar** [comment]
Some typos / rephrasing over your latest changes:
```
## Expected behavior


## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)


## Steps to reproduce (recipe)


## Backtraces if any (`M-x toggle-debug-on-error`)


## Describe versions of Helm, Emacs, operating system, etc.


## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):


## IMPORTANT NOTE

Helm provides a script named `emacs-helm.sh` which runs Helm in a neutral
environment: no other packages and only minimal settings.

When possible, use it to reproduce your Helm issue to ensure no other package is
interfering.

To run it, simply switch to the directory where Helm is installed and call `./emacs-helm.sh`.

Thanks.
```

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Some typos / rephrasing over your latest changes:

Thanks, merged.

-- 
Thierry
