### ISSUE TITLE
search query ending with a dollar sign doesn't find files where the query matches earlier in the filename too.

### ISSUE THREAD

**Issue by zck** [emacs-helm/helm#1868]
## Steps to reproduce

1. create a file `txt.txt` in some directory, and in that same directory a file `other.txt`.
2. `./emacs-helm.sh`
3. type `C-x C-f` and navigate to that directory.
4. type `txt`. You should see both files in the `*helm find files*` buffer.
5. Add a `$` to the prompt, so the entire search is for `txt$`.

## Expected behavior

Any file that ends in `txt` shows up in the `*helm find files*` buffer. That is, both `txt.txt` and `other.txt` should be found.

## Actual behavior from `emacs-helm.sh` if possible (See note at bottom)

Only `other.txt` shows up in the `*helm find files*` buffer.

## Describe versions of helm, emacs, operating system etc.

Helm commit bb5e11c82783bd65b67c95207e0f9ecd3d0ac57a (from September 16).
Emacs commit 1c382c096b8b7d1fa995e6131b887d9128085c68 (from mid-August)
OS: Ubuntu 16.04.3

**Comment by thierryvolpiatto** [comment]
zck <notifications@github.com> writes:

> Steps to reproduce
>
>  1. create a file txt.txt in some directory, and in that same directory a file other.txt.
>  2. ./emacs-helm.sh
>  3. type C-x C-f and navigate to that directory.
>  4. type txt. You should see both files in the *helm find files* buffer.
>  5. Add a $ to the prompt, so the entire search is for txt$.

helm-find-files is fuzzy matching, so when you give it "txt$", the
pattern is transformed like this:

** 05:56:18.443238 (helm-find-files-get-candidates)
 Pattern="/home/thierry/tmp/test1/[^t]*t[^x]*x[^t]*t$"

If you want to start regexp matching, you have to use multi match by
using a space (" txt$") and helm will use this as pattern:

** 05:59:59.383672 (helm-find-files-get-candidates)
 Pattern="/home/thierry/tmp/test1/ txt$"

and even if HFF was only matching on regexp, the regexp you give is
wrong: "/home/you/txt$" will never match "/home/you/txt.txt"

So just remember that as soon you want to use a regexp you have to enter
a space to tell to HFF "stop fuzzy matching, use now multi regexp
matching".


-- 
Thierry
