### ISSUE TITLE
helm-buffer-run-kill-persistent should not prompt before killing

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#1869]
`helm-buffer-run-kill-persistent` prompts a confirmation before killing each buffer.  It makes it very inconvenient, not to say unusable.

I think it should behave like the non-persistent command: only prompt for confirmation when buffer has unsaved changes.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> helm-buffer-run-kill-persistent prompts a confirmation before killing
> each buffer. It makes it very inconvenient, not to say unusable.
>
> I think it should behave like the non-persistent command: only prompt
> for confirmation when buffer has unsaved changes.

Done.

Thanks.

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.*


--
Thierry

**Comment by Ambrevar** [comment]
Thank you.
