### ISSUE TITLE
Bug: (helm-alive-p) returns nil when helm-action-buffer is visible and in use

### ISSUE THREAD

**Issue by rswgnu** [emacs-helm/helm#1873]
Shouldn't the second line of the body of (helm-alive-p) be:

     (get-buffer-window (helm-buffer-get) 'visible)

so it accounts for both helm-buffer and helm-action-buffer usage?

**Comment by thierryvolpiatto** [comment]
Robert Weiner <notifications@github.com> writes:

> Shouldn't the second line of the body of (helm-alive-p) be:
>
>  (get-buffer-window (helm-buffer-get) 'visible)
>
> so it accounts for both helm-buffer and helm-action-buffer usage?

Yes, fixed via cc15f73.

Thanks.

-- 
Thierry
