### ISSUE TITLE
Infinite street fields with bbdb-create

### ISSUE THREAD

**Issue by Postroutine** [emacs-helm/helm#1876]
## Expected behavior

Be able to create contact with BBDB

## Actual behavior from `emacs-helm.sh` if possible (See note at bottom)

When BBDB ask for the "street line 1", it continue to ask for "street line 2", "street line3", etc.
Without helm, don't have this problem.

## Steps to reproduce (recipe)

With Helm, call "bbdb-create" and try to create a contact.

## Describe versions of helm, emacs, operating system etc.

GNU Emacs 25.3.1
Helm 20170724.2137 (melpa)
BBDB 20170129.2224 (melpa)

**Comment by thierryvolpiatto** [comment]
Postroutine <notifications@github.com> writes:

> Expected behavior
>
> Be able to create contact with BBDB
>
> Actual behavior from emacs-helm.sh if possible (See note at bottom)
>
> When BBDB ask for the "street line 1", it continue to ask for "street line 2", "street line3", etc.
> Without helm, don't have this problem.

Read

https://github.com/emacs-helm/helm/wiki/FAQ#why-cant-i-exit-completing-read-with-an-empty-string


-- 
Thierry

**Comment by Postroutine** [comment]
Thanks Thierry.

Why completion help is display on mode-line and not in completion buffer?

**Comment by thierryvolpiatto** [comment]
Postroutine <notifications@github.com> writes:

> Thanks Thierry.
>
> Why completion help is display on mode-line and not in completion
> buffer?

Basic commands are briefly described in mode-line, you should see
something like "C/M-RET:Empty".
I will add an entry for completing-read's and read-file-name's about
this.

Thanks.

--
Thierry

**Comment by Postroutine** [comment]
When BBDB ask for "street line 1", If I use the C-RET or M-RET, BBDB stop after asking for city.

I don't have this problem if I disable helm-mode.

**Comment by thierryvolpiatto** [comment]
Postroutine <notifications@github.com> writes:

> When BBDB ask for "street line 1", If I use the C-RETor M-RET, BBDB stop after asking for city.

Sorry but I am not using bbdb, so I don't understand what you mean I
will install it as soon as possible and see what's going on.

> I don't have this problem if I disable helm-mode.

You can disable helm-mode only for this if needed with
helm-completing-read-handlers-alist.


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Postroutine <notifications@github.com> writes:

> When BBDB ask for "street line 1", If I use the C-RETor M-RET, BBDB
> stop after asking for city.

Just tried, you have to press C-RET to exit the helm completion
interfaces, "street line 1" is just a simple read-string, just press RET
when done.
So I don't think there is a bug here.

I am not a fan of bbdb myself, I use addressbook-bookmark.el, but if you
like bbdb, you should try helm-bbdb which provide helm native functions
instead of generic helm functions when you use directly bbdb.

-- 
Thierry

**Comment by Postroutine** [comment]
This is what happend for me:
- I start `bbdb-create`
- Respond to questions untile BBDB ask for "street line 1"
- I hit C-RET
- BBDB ask for city of the contact I record
- I press RET
- BBDB quit

**Comment by thierryvolpiatto** [comment]
Postroutine <notifications@github.com> writes:

> This is what happend for me:
>
>   * I start bbdb-create
>   * Respond to questions untile BBDB ask for "street line 1"
>   * Ihit C-RET
>   * BBDB ask for city of the contact I record
>   * I press RET
>   * BBDB quit

Just hit RET when you have NO helm completion and C-RET when you have a
helm buffer completion.
I just tried and I can confirm it works the same with and without
helm-mode enabled.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Note tha if you create contact from [helm-bbdb](https://github.com/emacs-helm/helm-bbdb) you don't have to press C-RET, just hit RET on the fake candidate:

![capture d ecran_2017-09-23_11-14-41](https://user-images.githubusercontent.com/1533939/30771858-d9307bf0-a050-11e7-80f3-f71a30b1a65c.png)

**Comment by thierryvolpiatto** [comment]
But if you started from M-x bbdb-create you have the helmized completing-read and there you have to type C-RET:

![capture d ecran_2017-09-23_11-19-57](https://user-images.githubusercontent.com/1533939/30771882-61c0e8ec-a051-11e7-84b7-1c0231c47f9b.png)

**Comment by thierryvolpiatto** [comment]
But when prompted with a simple `read-string` (always from bbdb-create) just hit RET:

![capture d ecran_2017-09-23_11-23-31](https://user-images.githubusercontent.com/1533939/30771900-ce35fdd2-a051-11e7-92bf-01858fcc131c.png)

**Comment by thierryvolpiatto** [comment]
Hope that help
