### ISSUE TITLE
Feature Request: Provide helm-grep command for immediate directory grepping

### ISSUE THREAD

**Issue by rswgnu** [emacs-helm/helm#1877]
Presently, to use helm's grep capability, one must invoke {M-x helm-find-files RET} and then use {M-g s}.  I think there should be an additional command that immediately invokes helm grep on the current directory, as it would speed up things and be much simpler to learn.

If there is a simple way to code a function to do this with existing helm primitives, please show it.  I have tried the following but it does not work.  -- Thanks, Bob

```
(defun helm-grep ()
  "Use helm to grep over the current directory; with prefix argument, recurse into subdirectories."
  (interactive)
  (require 'helm-files)
  (helm-find-files-1 default-directory)
  (sit-for 0.2)
  ;; Prefix arg makes grep recurse subdirectories
  (let ((helm-current-prefix-arg (or current-prefix-arg '(4))))
    (call-interactively #'helm-ff-run-grep))))
```

**Comment by thierryvolpiatto** [comment]
Robert Weiner <notifications@github.com> writes:

> Presently, to use helm's grep capability, one must invoke {M-x
> helm-find-files RET} and then use {M-g s}. I think there should be an
> additional command that immediately invokes helm grep on the current
> directory, as it would speed up things and be much simpler to learn.

Please use M-g a from helm-find-files (be sure to have installed AG or
similar) and from current buffer use helm-do-grep-ag, in the directories
handled by git you can use git grep as well (M-g g).

--
Thierry

**Comment by rswgnu** [comment]
On Thu, Sep 21, 2017 at 3:21 PM, Thierry Volpiatto <notifications@github.com
> wrote:

>
> Robert Weiner <notifications@github.com> writes:
>
> Please use M-g a from helm-find-files (be sure to have installed AG or
> similar) and from current buffer use helm-do-grep-ag, in the directories
> handled by git you can use git grep as well (M-g g).
>

​Why not just add a command like helm-do-grep-ag but for normal grep and
call it helm-grep for ease of use?  It should be mostly the same, right?

This must be a common desire, to have helm support for grep from a direct
command, without the need to install another significant package.

Bob

**Comment by thierryvolpiatto** [comment]
Robert Weiner <notifications@github.com> writes:

> On Thu, Sep 21, 2017 at 3:21 PM, Thierry Volpiatto <notifications@github.com
>> wrote:
>
>>
>> Robert Weiner <notifications@github.com> writes:
>>
>> Please use M-g a from helm-find-files (be sure to have installed AG or
>> similar) and from current buffer use helm-do-grep-ag, in the directories
>> handled by git you can use git grep as well (M-g g).
>>
>
> ​Why not just add a command like helm-do-grep-ag but for normal grep and
> call it helm-grep for ease of use? It should be mostly the same, right?

See
https://github.com/emacs-helm/helm/wiki/FAQ#what-happened-to-the-grep-and-multi-occur-commands

> This must be a common desire, to have helm support for grep from a direct
> command, without the need to install another significant package.

Nowaday, everybody is using AG or RG which are much faster and clever than grep. 

-- 
Thierry

**Comment by rswgnu** [comment]
On Fri, Sep 22, 2017 at 12:06 AM, Thierry Volpiatto <
notifications@github.com> wrote:

>
> Robert Weiner <notifications@github.com> writes:
>
> > ​Why not just add a command like helm-do-grep-ag but for normal grep and
> > call it helm-grep for ease of use? It should be mostly the same, right?
>
> See
> https://github.com/emacs-helm/helm/wiki/FAQ#what-happened-
> to-the-grep-and-multi-occur-commands


​Ok, I see that you don't feel grep and occur commands should not be
top-level helm commands but only used after selecting some targets within a
helm session.

Could you just tell us how to send keyboard events programmatically to a
helm session (sample code), so we can invoke whatever helm actions we want
upon startup?  This would be useful in all sorts of contexts.

Thanks,

Bob

**Comment by thierryvolpiatto** [comment]
Robert Weiner <notifications@github.com> writes:

> Could you just tell us how to send keyboard events programmatically to a
> helm session (sample code), so we can invoke whatever helm actions we want
> upon startup?

This is not implemented.

The reason is that it would not be reliable because you have no idea of which
candidate will popup even more with an async process constantly
updating.  The only usage I see for this is for debugging or writing tests
with a small list of candidates you know in advance, a preselected
candidate and a predefined action.  I plan to implement such a thing for
tests but not soon.

If you want to create an interactive command for grep based on
`default-directory` you have to use directly `helm-do-grep-1`.

e.g

    (helm-do-grep-1 default-directory t 'grep '("*.el") "defun")

-- 
Thierry

**Comment by rswgnu** [comment]
On Fri, Sep 22, 2017 at 10:17 AM, Thierry Volpiatto <
notifications@github.com> wrote:

>
> Robert Weiner <notifications@github.com> writes:
>
> > Could you just tell us how to send keyboard events programmatically to a
> > helm session (sample code), so we can invoke whatever helm actions we
> want
> > upon startup?
>
> This is not implemented.
>
> The reason is that it would not be reliable because you have no idea of
> which
> candidate will popup even more with an async process constantly
> updating.


How is it different when a program provides the keystrokes than a user
except that it may occur faster?

​​
> The only usage I see for this is for debugging or writing tests
> ​​
> with a small list of candidates you know in advance, a preselected
> ​​
> candidate and a predefined action. I plan to implement such a thing for
> ​​
> tests but not soon.
>

Thoughts that come to mind: providing a complex, predefined pattern at
startup; getting helm into a particular mode before choosing candidates,
e.g. as you noted, using default directory rather than being prompted for a
directory.

​​
>
> ​​
> If you want to create an interactive command for grep based on
> ​​
> `default-directory` you have to use directly `helm-do-grep-1`.
> ​​
>
> ​​
> e.g
> ​​
>
> ​​
> (helm-do-grep-1 default-directory t 'grep '("*.el") "defun")


​Thanks.  I tried that in a directory with many .el files but could not get
any candidates to appear, just a blank helm buffer no matter what I typed.

You can see that a new user who is used to Emacs {M-x grep RET} and wants
to use helm to do a grep could never figure that out.  My goal is to help
you see some of the needs from that perspective and draw out more of the
great helm capabilities to a broader set of easier-to-use top-level
commands, so the out-of-the-box experience gets even better than it is now.

Bob

**Comment by rswgnu** [comment]
On Fri, Sep 22, 2017 at 10:33 AM, Robert Weiner <rsw@gnu.org> wrote:

> ​C​
>> reate an interactive command for grep based on
>> ​​
>> `default-directory` you have to use directly `helm-do-grep-1`.
>> ​​
>>
>> ​​
>> e.g
>> ​​
>>
>> ​​
>> (helm-do-grep-1 default-directory t 'grep '("*.el") "defun")
>
>
> ​Thanks.  I tried that in a directory with many .el files but could not
> get any candidates to appear, just a blank helm buffer no matter what I
> typed.
>

​The problem in my local test is that the helm variable,
helm-ff-default-directory, is already non-nil before this is invoked ​and
the code then replaces the default-directory argument provided instead with
the value of helm-ff-default-directory; grep is then invoked in the wrong
directory.  Somehow, it needs to either recognize the default-directory
from which it is called, have an additional parameter for default-directory
or be able to recognize when a directory is given within the TARGETS
argument.

Or rather than all that, look at the simple calling convention of the
built-in Emacs (grep args) command and replicate that with a wrapper
command, helm-grep that looks similar and doesn't need to have the breadth
of parameters of helm-do-grep-1.

Bob

**Comment by rswgnu** [comment]
>
> ​​
>>> (helm-do-grep-1 default-directory t 'grep '("*.el") "defun")
>>
>>
​The first argument must be a list:

​​
(helm-do-grep-1 (list default-directory) t 'grep '("*.el") "defun")

That will then work if you add the following two lines to helm-do-grep-1
after the (unless helm-ff-default-directory...) sexp:

    (when (and (= (length targets) 1) (file-directory-p (car targets)))
      (setq helm-ff-default-directory (car targets)))

as a temporary fix.

Bob

**Comment by rswgnu** [comment]
And this command works without modifying helm-do-grep-1:

(defun helm-rgrep-here ()
  "Performs a recursive grep within the current directory using helm."
  (interactive)
  (require 'helm-files) ; This requires helm-grep and defines
helm-ff-default-directory.
  (setq helm-ff-default-directory default-directory)
  (helm-do-grep-1 (list default-directory) t 'grep))

Bob

​​

**Comment by thierryvolpiatto** [comment]
Robert Weiner <notifications@github.com> writes:

> ​The first argument must be a list:

Robert, please just look at how I have implemented `helm-grep-git-1`,
what you need should be mostly the same, I don't remember the detail of
how arguments are used here and there.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Robert Weiner <notifications@github.com> writes:

> (setq helm-ff-default-directory (car targets)))

And don't setq this.

-- 
Thierry

**Comment by rswgnu** [comment]
On Fri, Sep 22, 2017 at 12:07 PM, Thierry Volpiatto <
notifications@github.com> wrote:

>
> Robert Weiner <notifications@github.com> writes:
>
> > (setq helm-ff-default-directory (car targets)))
>

> And don't setq this.


​Why not?  Those lines go in helm-do-grep-1 which already has a setq of
helm-ff-default-directory.

If I use this value before calling helm-do-grep-1, I could do that in a
(let) so that its value is not permanently set outside of helm.

Bob
​

**Comment by thierryvolpiatto** [comment]
I think you have now all ingredients to make your own grep command, I again suggest you use AG which is different from grep.
The reason that I don't want to provide the grep command you are asking for is that it is inneficient compared to the existing alternatives, just keep using simple grep (or ack-grep) for grepping single or marked files.
Closing now.

**Comment by rswgnu** [comment]
On Sat, Sep 23, 2017 at 3:18 AM, Thierry Volpiatto <notifications@github.com
> wrote:

> I think you have now all ingredients to make your own grep command,
>
​Yes, thanks.​

> I again suggest you use AG which is different from grep.
>
​Grep is more than fast enough for all the directory spaces I search.  It
is locate that could use some speedup on a Mac (so I use mdfind in many
cases).​


> The reason that I don't want to provide the grep command you are asking
> for is that it is inneficient compared to the existing alternatives, just
> keep using simple grep (or ack-grep) for grepping single or marked files.
> Closing now.
>
​Fine.
​
Bob

**Comment by thierryvolpiatto** [comment]
Robert Weiner <notifications@github.com> writes:

> ​Grep is more than fast enough for all the directory spaces I search.

It is not that grep is slow, it is that it is not clever as AG/PT or RG are,
the result is that in most cases AG and particularly RG are about ten
times faster than grep, see their documentation.
Even ack-grep which is slower technically than Grep give you the results
you want faster than grep.

I personally don't use grep anymore, apart some times on command line
and in scripts.

-- 
Thierry

**Comment by rswgnu** [comment]
spaces I search.
> 
> It is not that grep is slow, it is that it is not clever as AG/PT or RG are,
> the result is that in most cases AG and particularly RG are about ten
> times faster than grep, see their documentation.
> Even ack-grep which is slower technically than Grep give you the results
> you want faster than grep.

Good to know.  Thanks.

Bob
