### ISSUE TITLE
Error (void-variable tramp-methods) by helm-minibuffer-history in find-file

### ISSUE THREAD

**Issue by iquiw** [emacs-helm/helm#1879]
## Expected behavior

No error happens and selected file is in minibuffer.

## Steps to reproduce (recipe)

1. Run `emacs-helm.sh`.
2. <kbd>M-x find-fine</kbd>
3. Select any file or directory.
4. <kbd>M-x find-fine</kbd>
5. <kbd>C-r</kbd>
6. Select history by <kbd>RET</kbd>

## Backtraces if some (M-x toggle-debug-on-error)

```
Debugger entered--Lisp error: (void-variable tramp-methods)
  helm-ff--get-tramp-methods()
  helm-ff-set-pattern("~/work/helm/")
  helm-ff--invalid-tramp-name-p("~/work/helm/")
  helm-ff-before-action-hook-fn()
  run-hooks(helm-before-action-hook)
  helm-log-run-hook(helm-before-action-hook)
  helm-execute-selection-action()
```

## Describe versions of helm, emacs, operating system etc.

* helm (b0be214cf64526c686ae823da4709d647b59a2ad)
* emacs-25.3 on Void Linux (NetBSD as well)

**Comment by thierryvolpiatto** [comment]
Iku Iwasa <notifications@github.com> writes:

> Expected behavior
>
> No error happens and selected file is in minibuffer.
>
> Actual behavior from emacs-helm.sh if possible (See note at bottom)
>
> Steps to reproduce (recipe)
>
>  1. Run emacs-helm.sh.
>  2. M-x find-fine
>  3. Select any file or directory.
>  4. M-x find-fine
>  5. C-r
>  6. Select history by RET
>
> Backtraces if some (M-x toggle-debug-on-error)
>
> Debugger entered--Lisp error: (void-variable tramp-methods)

Should work now, thanks.

-- 
Thierry

**Comment by iquiw** [comment]
Thank you!
