### ISSUE TITLE
helm-find-files-eshell-command-on-file does not display aliases in candidate buffer when $1 is quoted

### ISSUE THREAD

**Issue by vibrys** [emacs-helm/helm#1881]
## Expected behavior
I've added following eshell alias to run gdb through M-! action:
```
alias gud gud-gdb "gdb --fullname $1"
```

when M-! action is chosen for file, "gud" should be present on candidates' list.

When I force to write "gud" command gud-gdb will run of course.

```
M-: (eshell-read-aliases-list)
(("gud" "gud-gdb \"gdb --fullname $1\""))
```

Note: defining following alias does not work with gud-gdb function:
```
alias gud gud-gdb gdb --fullname $1
```

Immediate reason for the issue seems to be "\\(\\$1\\|\\$\\*\\)$" regexp within ```helm-find-files-eshell-command-on-file-1```

## Actual behavior from `emacs-helm.sh` if possible (See note at bottom)
"gud" is not present on candidates' list.

## Steps to reproduce (recipe)
- run ./emacs-helm.sh
- M-x eshell
- alias gud gud-gdb "gdb --fullname $1"
- M-x helm-find-files: choose some file
- visit actions menu
- choose M-!

## Describe versions of helm, emacs, operating system etc.
emacs 25.3.1
helm: 161c90f

## IMPORTANT NOTE:

Helm is providing a script named `emacs-helm.sh` which allows running Helm
in a neutral environment with only helm installed with minimal settings.
When possible it is important to use it to reproduce your helm bugs 
to ensure no other package is interfering.
To run it, just cd to the directory where helm is installed and call ./emacs-helm.sh.

Thanks.

**Comment by thierryvolpiatto** [comment]
Mat Vibrys <notifications@github.com> writes:

> Immediate reason for the issue seems to be "\(\$1\|\$\*\)$" regexp
> within helm-find-files-eshell-command-on-file-1

Indeed, should be fixed now, let me know.

Thanks.

--
Thierry

**Comment by vibrys** [comment]
it works now. Thank You for fix.
