### ISSUE TITLE
Bug with helm open file in new update

### ISSUE THREAD

**Issue by schvabodka-man** [emacs-helm/helm#1882]
## Expected behavior
Helm find file simply open list with file

## Actual behavior 
I'm getting 
`helm-ff-save-history: Symbol’s value as variable is void: helm--completing-file-name`
if i'll open helm find file. BUT if i open helm-m-x(or ant other helm func) first and then use helm find file everything works ok 
## Steps to reproduce (recipe)
Start emacs
Use helm find file

## Backtraces if some (M-x toggle-debug-on-error)
`helm-ff-save-history: Symbol’s value as variable is void: helm--completing-file-name`

## Describe versions of helm, emacs, operating system etc.
Fedora, emacs 25, latest helm from melpa.The fact is that when i'm using helm from melpa-stable everything is flawless and there are no bug

**Comment by thierryvolpiatto** [comment]
Ivan <notifications@github.com> writes:

> Steps to reproduce (recipe)
>
> Start emacs
> Use helm find file

This is not enough, I don't know how you started emacs and configured helm.

> Fedora, emacs 25, latest helm from melpa.

Are you sure you are using the last?
The bug looks similar at #1880 that have been fixed by commit 161c90ff.

--
Thierry

**Comment by thierryvolpiatto** [comment]
Also see #1867 about emacs-helm.sh
