### ISSUE TITLE
helm-world-time fails when display-time-world is not run first

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#1884]
## Expected behavior

Display world time.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

Error is returned, see backtrace.

## Steps to reproduce (recipe)

Start Emacs and run `helm-world-time`.
If you run `display-time-world`, then `helm-world-time` works.

## Backtraces if any (`M-x toggle-debug-on-error`)
```
(void-variable display-time-world-list)
  #[0 ...
  #[0 ...
  apply(#[0 ...
  helm-funcall-with-source(((name . "Time World List") (init #[0 ...
  helm-funcall-foreach(init)
  helm-initial-setup(nil)
  helm-initialize(nil nil nil helm-source-time-world)
  helm-internal(helm-source-time-world nil nil nil nil "*helm world time*" nil nil nil)
  apply(helm-internal (helm-source-time-world nil nil nil nil "*helm world time*" nil nil nil))
  helm(helm-source-time-world nil nil nil nil "*helm world time*" nil nil nil)
  apply(helm (helm-source-time-world nil nil nil nil "*helm world time*" nil nil nil))
  helm(:sources helm-source-time-world :buffer "*helm world time*")
  helm-other-buffer(helm-source-time-world "*helm world time*")
  helm-world-time()
  funcall-interactively(helm-world-time)
  call-interactively(helm-world-time record nil)
  command-execute(helm-world-time record)
  helm-M-x(nil #("helm-world-time" 0 15 (match-part "helm-world-time")))
  funcall-interactively(helm-M-x nil #("helm-world-time" 0 15 (match-part "helm-world-time")))
  call-interactively(helm-M-x nil nil)
  command-execute(helm-M-x)
```

## Describe versions of Helm, Emacs, operating system, etc.

- Emacs 25.2
- Helm: master

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):

Yes.

## IMPORTANT NOTE

Helm provides a script named `emacs-helm.sh` which runs Helm in a neutral
environment: no other packages and only minimal settings.

When possible, use it to reproduce your Helm issue to ensure no other package is
interfering.

To run it, simply switch to the directory where Helm is installed and call `./emacs-helm.sh`.

Thanks.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> (void-variable display-time-world-list)

Should be fixed now.

Thanks.

-- 
Thierry

**Comment by Ambrevar** [comment]
Thanks!
