### ISSUE TITLE
find-library should prefer `foobar` over `foobar-pkg`, `foobar-autoloads`, and `foobar.elc`

### ISSUE THREAD

**Issue by glasser** [emacs-helm/helm#1885]
## Expected behavior

I have a package `popup` installed from Melpa. I type type `M-x find-library` followed by `popu` and hit RET.

I would like this to open the library `popup`.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

(This happens with emacs-helm.sh, which is why I chose `popup` for this example.)

It opens the library `popup-autoloads`.

(It works OK if I type out the full `popup` so it's an exact match, but not if I've only typed part of it.)

## Steps to reproduce (recipe)

`M-x find-library popu RET`

## Backtraces if any (`M-x toggle-debug-on-error`)

N/A

## Describe versions of Helm, Emacs, operating system, etc.

helm-20170926.310 from melpa.

## Commentary

I assume this is because find-library uses completing-read and helm has no special support for it.  But it seems like a nice opportunity for helm to have a slightly better version.  I'd be happy to add this support (to helm itself or some other package) if somebody pointed me at an example of a similar simple command given a bit of helm augmentation — there's a lot going on in helm :)

**Comment by thierryvolpiatto** [comment]
Helm use a generic function to helmize the completing-read used by find-library, see https://github.com/emacs-helm/helm/wiki/FAQ#can-you-modify-the-emacs-vanilla-helmized-command-to-behave-differently
If you really want to make it working like you want, you have to write a new function and bind it to find-library in helm-completing-read-handlers-alist but you have better time using a native helm command like helm-locate-library.

**Comment by glasser** [comment]
OK, I should probably figure out how to add helm functions then!

I would prefer something like find-library over helm-locate-library because find-library always finds me the current version of the library that Emacs would load, whereas h-l-l might send me to a different version that's later on the load list.

**Comment by thierryvolpiatto** [comment]
David Glasser <notifications@github.com> writes:

> OK, I should probably figure out how to add helm functions then!
>
> I would prefer something like find-library over helm-locate-library
> because find-library always finds me the current version of the
> library that Emacs would load, whereas h-l-l might send me to a
> different version that's later on the load list.

You have to understand that helm for such emacs commands is using a
generic function to helmize the completing-read.  This generic function
is more or less completing correctly in most cases, but of course is not
perfect everywhere.

For example what you want here is a clever sorting of candidates to make
"popup" emerging on top, but sorting is maybe not wanted as some other
completing-read are providing a COLLECTION already sorted specifically
for their candidates.

When using fuzzy matching though your candidates will be sorted (see
helm-mode-fuzzy-match) but you may have problems elsewhere (i.e fuzzy
matching not adapted to certain types of candidates).

--
Thierry
