### ISSUE TITLE
Is it possible to remove specific items from 'helm-comint-input-ring)?

### ISSUE THREAD

**Issue by lmdic** [emacs-helm/helm#1886]
Window 10, Emacs 25.1 package: helm

```
;; Shell commands history
(define-key shell-mode-map (kbd "C-c C-l") 'helm-comint-input-ring)
```
OK. It's work fine.

But after some time this list becomes large. So I want to:

1. Remove specific item from list
2. Clear all list

Is it possible?

**Comment by thierryvolpiatto** [comment]
lmdic <notifications@github.com> writes:

> Window 10, Emacs 25.1 package: helm
>
> ;; Shell commands history
> (define-key shell-mode-map (kbd "C-c C-l") 'helm-comint-input-ring)
>
> OK. It's work fine.
>
> But after some time this list becomes large. So I want to:
>
>  1. Remove specific item from list
>  2. Clear all list
>
> Is it possible?

Helm is just displaying the contents of `comint-input-ring`, I guess you
can modify it, but you have better time to set `comint-input-ring-size`
to a lower value (default is 500).

-- 
Thierry
