### ISSUE TITLE
display-buffer-reuse-frames unwanted behaviour

### ISSUE THREAD

**Issue by Pitometsu** [emacs-helm/helm#1887]
Hello, I have such configuration.

```elisp
(setq display-buffer-reuse-frames t)

(setq popwin:reuse-window (quote current))
(setq popwin:special-display-config
   (quote
    (...
     ("^\\*helm.*\\*$" :regexp t)
     (help-mode)
     (completion-list-mode :noselect t)
     (compilation-mode :noselect t)
     ...
```

To reuse exist buffers like compilation in other frames.

And I use https://github.com/m2ym/popwin-el/issues/139 for `helm` buffers placement.
However, when I use few frames, I expect to see `*Helm*` buffer in `popwin` in current frame, not in exist one.

It works like that not for all `helm` buffers,
here steps to reproduce:

`F1 v` **=>** appears **`*helm-mode-describe-variable*`** buffer in `popwin`
`foc in RET` **=>** show **`*Help*`** buffer in `popwin` for `focus-in-hook` variable
`C-x 5 o` **=>** switch to other frame
`F1 v` **=>** *EXPECT* to see **`*helm-mode-describe-variable*`** in current frame
 . . . *BUT ACTUALLY* see **`*helm-mode-describe-variable*`** on previous frame.

**Comment by Pitometsu** [comment]
```
GNU Emacs 25.2.1 (x86_64-apple-darwin16.4.0, NS appkit-1504.81 Version 10.12.3 (Build 16D30)) of 2017-06-22
```
```
$ git -C ~/.emacs.d/el-get/popwin/ log -1
commit 95dea14c60019d6cccf9a3b33e0dec4e1f22c304 (grafted, HEAD -> master, tag: v1.0.0, origin/master, origin/HEAD)
Author: Tomohiro Matsuyama <m2ym.pub@gmail.com>
Date:   Sun Mar 15 22:00:07 2015 +0900

    Version 1.0.0
```
```
$ git -C ~/.emacs.d/el-get/helm/ log -1
commit 8d0ef8f7ba56a78d7c1292d3db65f993518b8a78 (grafted, HEAD -> master, origin/master, origin/HEAD)
Author: Thierry Volpiatto <thierry.volpiatto@gmail.com>
Date:   Thu Jun 22 22:55:31 2017 +0200

    Try to prevent read-only candidates (#1755).

    * helm.el (helm-insert-match): Do it.
```

**Comment by thierryvolpiatto** [comment]
Please follow the template included to fill in your issue.
Try to reproduce your issue from emacs-helm.sh without any external
library installed, popwin included.

Thanks.

-- 
Thierry
