### ISSUE TITLE
`helm-buffers` input hangs in follow-mode with EXWM

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#1889]
With `helm-buffers` and `helm-follow-mode` on, after going up/down over the buffers a few times
the input hangs.  To resume activity, I've got to click on the non-Helm buffer then `other-window` to the minibuffer to stop Helm.

There is no CPU hog or anything.

It seems to only happen when Emacs is run as EXWM.

Sorry for the lack of details, sadly I do not know in which direction to investigate.  The issue could be specific to the combination of EXWM and Helm.

**Comment by Ambrevar** [comment]
I've tried with a barebone config:
```
(require 'helm-config)
(require 'exwm)
```
I start EXWM from `.xinitrc`:
```
	emacs --daemon -f exwm-enable
	exec emacsclient -c
```
The issue seems to occur only when at least one EXWM buffer is present.  I've tried with different X programs.
I think an EXWM buffer has to be hovered once at least before it triggers the issue.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> With helm-buffers and helm-follow-mode on, after going up/down over the buffers a few times
> the input hangs. To resume activity, I've got to click on the non-Helm buffer then other-window to the minibuffer to stop Helm.
>
> There is no CPU hog or anything.
>
> It seems to only happen when Emacs is run as EXWM.
>
> Sorry for the lack of details, sadly I do not know in which direction
> to investigate. The issue could be specific to the combination of EXWM
> and Helm.

I think you are refering to https://github.com/ch11ng/exwm, right?
I see also https://github.com/tumashu/exwm-x?

For now I have no ideas on how to install and use this to reproduce.
I guess it is more a problem with EXWM which may give focus to another
window or something like this.
Perhaps helm window should be excluded from the windows handled by EXWM,
maybe EXWM have a variable for configuring this?

>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.*


-- 
Thierry

**Comment by Ambrevar** [comment]
Yes, https://github.com/ch11ng/exwm.
It's very straightforward to install: it's available for ELPA.
Add the 2 lines I suggested to your `.xinitrc` and run `startx`.

You are right, there might be a race condition in the window selection and input gets lost in the process.

**Comment by Ambrevar** [comment]
Update: if I filter out EXWM windows with `*!exwm`, then the issue does not occur.
Interestingly, if I filter out all non-EXWM window with `*exwm`, the issue does not occur either!

So the problem lies in the mix of both.  I've managed to narrow down the recipe:

- When I hover from a non-EXWM buffer to a non-EXWM buffer, it's fine.
- When I hover from a non-EXWM buffer to an EXWM buffer, it's fine.
- When I hover from an EXWM buffer to an EXWM buffer, it's fine.
- However, as soon as I hover from an EXWM buffer to a non-EXWM buffer, it's the cursor gets lost.

I have to click on another buffer to regain control.

I think this might have to do with the fact that EXWM buffers have no cursor position.  What do you think?

**Comment by Ambrevar** [comment]
Besides, this might be related to #1891 and point/marker positions.

**Comment by Ambrevar** [comment]
With the workaround of #1891, this issue is still here: that was quite expected considering this has probably nothing to do with the mark-ring.  Since the original cause of the issue #1891 might still be unknown, those two bugs might still be related.

**Comment by Ambrevar** [comment]
Note that this problem is no longer relevant when separating Emacs buffers from EXWM buffers with Helm-EXWM.

**Comment by Ambrevar** [comment]
It seems that this problem is gone with recent versions of Helm / EXWM.  Closing.

**Comment by moritzschaefer** [comment]
not for me :/
