### ISSUE TITLE
helm autocompletion of tags in org mode does not work

### ISSUE THREAD

**Issue by ikosmidis** [emacs-helm/helm#1890]
## Expected behavior
C-c C-c on a heading in org mode would give helm-like autocompletion of tags

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
*Org tags* buffer appears. Pressing TAB opens the *helm-mode-org-set-tags* buffer with "Tag:" in the minibuffer but helm does not load the available tags in the org file (i.e. there are no selections to choose from really)

## Steps to reproduce (recipe)
Create a test.org file with 
```
#+TAGS: test1(a) test2(b)  

* test
```

and hit C-c C-c on the line of test

## Describe versions of Helm, Emacs, operating system, etc.
helm-20171002.2119
GNU Emacs 24.5.1
Ubuntu 16.04-3

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):
yes

**Comment by thierryvolpiatto** [comment]
Ioannis Kosmidis <notifications@github.com> writes:

> Expected behavior
>
> C-c C-c on a heading in org mode would give helm-like autocompletion of tags
>
> Actual behavior (from emacs-helm.sh if possible, see note at the bottom)
>
> Org tags buffer appears. Pressing TAB opens the helm-mode-org-set-tags
> buffer with "Tag:" in the minibuffer but helm does not load the
> available tags in the org file 

It is not helm that "does not load the available tags" but org itself.

> (i.e. there are no selections to choose from really)
>
> Steps to reproduce (recipe)
>
> Create a test.org file with
> `
> #+TAGS: test1(a) test2(b)
>
>   * test

Please try without helm enabled, here I have no tags as well with your recipe.
OTOH completion on tags is working fine in all my org buffers (I use it
daily).

--
Thierry

**Comment by ikosmidis** [comment]
Thanks for the speedy response. 

I think I've figured out what's the reason for the behaviour. If at least one of the tags is set for [fast tag selection](http://orgmode.org/guide/Setting-tags.html#Setting-tags), then `org-set-tags` takes over and the `*Org tags*` buffer comes up for fast selection. Everything works as expected if 

```
#+TAGS: test1 test2

* test
```

Is this documented anywhere already? Perhaps fast tag selection should be ignored by default if helm is enabled to ensure that current sets of tags with fast tag selection work? 

Best wishes and thanks for the great software,
Ioannis

**Comment by thierryvolpiatto** [comment]
Ioannis Kosmidis <notifications@github.com> writes:

> Thanks for the speedy response.
>
> I think I've figured out what's the reason for the behaviour. If at
> least one of the tags is set for fast tag selection,

Indeed, forgot about this.

> then org-set-tags takes over and the *Org tags* buffer comes up for
> fast selection. Everything works as expected if
>
> #+TAGS: test1 test2
>
> * test
>
> Is this documented anywhere already?

I don't think so, should be added somewhere if not.

> Perhaps fast tag selection should be ignored by default if helm is
> enabled to ensure that current sets of tags with fast tag selection
> work?

Hmm, no that would be too invasive, perhaps some users want to use "fast
tag selection" and have helm enabled at the same time.

Please let this bug report open as a reminder so that I can document
this somewhere.

Thanks.

--
Thierry

**Comment by thierryvolpiatto** [comment]
Added docstring and an entry in [FAQ](https://github.com/emacs-helm/helm/wiki/FAQ#org-tag-completion-is-not-working).
