### ISSUE TITLE
source helm-source-recentf appears only after manual M-x helm-recentf

### ISSUE THREAD

**Issue by bravosierrasierra** [emacs-helm/helm#1892]
Hello! Thanks for your awesome solution!

After update i found bug/feature: helm-source-recentf initially should be populated at emacs startup. Old versions dont have this problem, at least before 10 august 2017. My lovely solution from http://kitchingroup.cheme.cmu.edu/blog/2015/02/04/Helm-at-the-Emacs/ not worked with error "undefined variable helm-source-recentf" after emacs startup. Source helm-source-recentf appears only after manual call M-x helm-recentf.

**Comment by thierryvolpiatto** [comment]
If you want the source to be loaded, you have to require helm-for-files.el
