### ISSUE TITLE
Helm Grep Mode: helm-grep-mode-jump-other-window

### ISSUE THREAD

**Issue by zalky** [emacs-helm/helm#1893]
Just want to say thanks for all the hard work, helm makes emacs so much better!

## Expected behavior

Until recently, when opening candidates in helm-grep, `helm-grep-mode-jump-other-window` would open the candidate in another _existing_ window.

## Actual behavior

Since I upgraded to 2.8.5, `helm-grep-mode-jump-other-window` splits the current window when opening a candidate, rather than opening in another _existing_ window. Neither splitting the current window vertically or horizontally is useful as the resulting windows are generally too small to do anything. This also doesn't seem to match the "open in other window" functionality in other helm modes, like helm-find-files, where candidates are generally opened in another _existing_ window.

I've looked through the source and I don't think I see a configuration var to change this behaviour. Am I missing something?

## Steps to reproduce (recipe)

Load candidates in helm-grep, `C-o` on a candidate.

## Backtraces if any (`M-x toggle-debug-on-error`)

None

## Describe versions of Helm, Emacs, operating system, etc.

Helm versions: 2.8.5 from melpa-stable, as well as helm-20171009.221 from melpa
Emacs version: 25.2.1
OS: Mac OS Sierra

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):

No, I could not get `emacs-helm.sh` to work. It loads emacs but without helm.

**Comment by thierryvolpiatto** [comment]
zalky <notifications@github.com> writes:

> Since I upgraded to 2.8.5, helm-grep-mode-jump-other-window splits the
> current window when opening a candidate, rather than opening in
> another existing window.

Indeed, in 2.8.5 I fixed this for helm-moccur, but not for grep, in last
helm it is not fixed for both, should be done now, have a try.

> Helm versions: 2.8.5 from melpa-stable, as well as helm-20171009.221 from melpa
> Emacs version: 25.2.1
> OS: Mac OS Sierra
>
> Are you using emacs-helm.sh to reproduce this bug (yes/no):
>
> No, I could not get emacs-helm.sh to work. It loads emacs but without helm.

Use emacs-helm.sh -P <emacs executable name> (IIRC I heard on Mac OS the
emacs name is not emacs but somting else).

-- 
Thierry

**Comment by zalky** [comment]
@thierryvolpiatto , hi apologies for the delayed response. But I can confirm that this is fixed in the latest `melpa` build.

Thanks again for all the hard work on some incredible software!
