### ISSUE TITLE
helm-mini has large startup delay after opening some files (cpp?)

### ISSUE THREAD

**Issue by hrehfeld** [emacs-helm/helm#1894]
## Expected behavior
helm-mini should be instant

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
3-5s delay before opening window

## Steps to reproduce (recipe)
no idea, that's what I'm trying to find out
## profiler:

```
- command-execute                                                2007  84%
 - call-interactively                                            2007  84%
  - byte-code                                                    1643  68%
   - helm-M-x-read-extended-command                              1643  68%
    - helm-comp-read                                             1643  68%
     - helm                                                      1637  68%
      - apply                                                    1637  68%
       - helm                                                    1637  68%
        - apply                                                  1637  68%
         - helm-internal                                         1637  68%
          - helm-read-pattern-maybe                              1552  65%
           - read-from-minibuffer                                1512  63%
            - timer-event-handler                                1357  56%
             - apply                                             1357  56%
              - #<lambda 0x11072bc6>                              318  13%
               - when                                             318  13%
                - if                                              318  13%
                 - progn                                          318  13%
                  - with-current-buffer                           318  13%
                   - save-current-buffer                          318  13%
                    - mode-icons-set-minor-mode-icon                318  13%
                     - mode-icons-get-icon-spec                   303  12%
                      - mode-icons-supported-p                    297  12%
                       - mode-icons--get-font-xpm-file                168   7%
                          mode-icons-get-icon-file                158   6%
                         mode-icons-supported-font-p                 13   0%
                       + mode-icons--ext-available-p                  6   0%
              + #<lambda 0x170075c6>                              315  13%
              + #<lambda 0x11072bc6>                              280  11%
              + #<lambda 0x170075c6>                              221   9%
              + #<compiled 0x940929>                              206   8%
            + command-execute                                      62   2%
            + redisplay_internal (C function)                      11   0%
              minibuffer-inactive-mode                              4   0%
           + helm-update                                           30   1%
          + helm-initialize                                        68   2%
          + #<compiled 0x931b0f>                                   14   0%
          + select-window                                           3   0%
     + helm-make-source                                             6   0%
  + funcall-interactively                                         364  15%
+ ...                                                             332  13%
+ timer-event-handler                                              38   1%
+ redisplay_internal (C function)                                   7   0%

```

## enabled minor modes in c++
```
Enabled minor modes: Abbrev Anzu Async-Bytecomp-Package
Auto-Composition Auto-Compression Auto-Encryption Cmake-Project
Column-Number Company Company-Quickhelp Company-Quickhelp-Local
Csv-Field-Index Desktop-Save Diff-Auto-Refine Dired-Omit Dtrt-Indent
Electric-Indent File-Name-Shadow Flycheck-Pos-Tip Font-Lock
Global-Anzu Global-Auto-Revert Global-Company Global-Eldoc
Global-Flycheck Global-Font-Lock Global-Git-Commit Global-Subword Helm
Helm-Autoresize Highlight-Symbol Irony Jabber-Activity Line-Number
Magit-Auto-Revert Mouse-Wheel Override-Global Projectile Pyvenv
Save-Place Savehist Shell-Dirtrack Show-Paren Smart-Tabs Subword
Tooltip Tracking Which-Function Window-Numbering
```

## helm-mini-default-sources

```
helm-mini-default-sources is a variable defined in ‘helm-buffers.el’.
Its value is
(helm-source-buffers-list helm-source-files-in-current-dir helm-source-file-name-history helm-source-buffer-not-found)

Original value was 
(helm-source-buffers-list helm-source-recentf helm-source-buffer-not-found)
```

## Describe versions of Helm, Emacs, operating system, etc.
Archlinux
GNU Emacs 25.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.19) of 2017-09-16
helm-20170723.2339

## Request
This suddenly starts to happen, I suspect after opening c++ files. I guess it's some mode interfering... How can I find out what causes the slowdown?

**Comment by hrehfeld** [comment]
https://github.com/hrehfeld/.emacs.d here's my current .emacs.d

**Comment by hrehfeld** [comment]
Updating all packages, esp. helm to helm-20171010.2317 doesn't fix the problem.

**Comment by hrehfeld** [comment]
The problems seems to be with this source:
```
helm-source-file-name-history
```
If I remove it, helm-mini is not slow anymore.

**Comment by thierryvolpiatto** [comment]
Hauke Rehfeld <notifications@github.com> writes:

> The problems seems to be with this source:
>
> helm-source-file-name-history
>
> If I remove it, helm-mini is not slow anymore.

I guess the problem is not from helm but from your history file that contain
something long to load.

It is not reproductible here, helm is starting fast.

-- 
Thierry

**Comment by hrehfeld** [comment]
Thank you, I will try to investigate more when I have time.

**Comment by Ambrevar** [comment]
@hrehfeld: Any update?

**Comment by gongzhitaao** [comment]
I had a similar problem.  My problem is related to `dired-x` package. I noticed you have `dired-omit` mode enabled.  And I saw you load `dired-x` in your init file, could you please try Emacs without loading `dired-x`?

**Comment by lmdic** [comment]
I also have this problem. And I Don not know how reproduce it.Sometime I need to wait 30 SECONDS to show buffers in helm-mini.

**Comment by hrehfeld** [comment]
Problem still persists with `20180826.515`

(Sorry for the long update)

**Comment by Ambrevar** [comment]
@hrehfeld , @lmdic , @gongzhitaao : Could you post recipes or minimal configurations?
There is very little information as of now on how to reproduce.

Are you people using `dired-x`?  Is it with C++ files?

**Comment by lmdic** [comment]
I describe my approach to test here: https://github.com/emacs-helm/helm/issues/2089

**Comment by ReneFroger** [comment]
Comment out half of your configuration. You can use M-x comment-region to comment out the region of selected text, or with Evil commenter (see emacs.zeef.com). (You can uncomment the region using C-u with the same command. (For convenience, you can bind comment-region to a key.)

Start Emacs. Did you see the same problem?
If yes, then the problem is not caused by the part you commented out.
If no, then it is.

For the problematic part: Comment out the other part and half of the problematic part. Then see if the problem arises. Repeat #2 and #3, over and over. It doesn't take long: 1/2, 3/4, 7/8, 15/16, 31/32, 63/64, 127/128, 255/256, 511/512, 1023/1024,...

It doesn't matter how big your init file is or how much other code it loads (if the problem is in other code then repeat the same process on that file, etc.).

**Comment by hrehfeld** [comment]
> Are you people using `dired-x`? Is it with C++ files?
Yes, I do, but it also happened when disabling that particular use-package call.

**Comment by hrehfeld** [comment]
> It doesn't matter how big your init file is or how much other code it loads (if the problem is in other code then repeat the same process on that file, etc.).

It does not work if your config depends on stuff loaded earlier. And restructuring a large config so that you have `require`s everywhere is not a small task (I went through that process), so this is not as simple as it sounds.

**Comment by barrkel** [comment]
I'm seeing the issue too. `global-linum-mode` seems to be a culprit for me - lots of post-text rendering hooks call into linum code in my profile.

**Comment by zw963** [comment]
Does you settings gc-cons-threshold to one large value consider [gc-optimization](https://github.com/lewang/flx#gc-optimization)?

e.g.

```el
(setq gc-cons-threshold 20000000)
```

If you does, emacs-mini will very slow in somecase, i have to change to `10000000`, 
but it seem like still slow, i plan to change this threshold to a more low value today..

**Comment by barrkel** [comment]
My `gc-cons-threshold` is `20000000`. However, the profile indicated 1% of time was spent in GC. After turning off global-linum-mode it became almost instantaneous. I replaced linum with nlinum.

**Comment by lmdic** [comment]
> My `gc-cons-threshold` is `20000000`. However, the profile indicated 1% of time was spent in GC. After turning off global-linum-mode it became almost instantaneous. I replaced linum with nlinum.

I replace HELM by IDO mode + SMEX.
And now no more slow reaction. All is very fast!

**Comment by Ambrevar** [comment]
About linum:

- Consider switching to Emacs 26 and use display-line-number-mode, it's an order of magnitude faster so it will probably fix your issue.

- If for some reason you cannot use Emacs 26, you can simply disable linum-mode in Helm, for instance `(add-hook 'helm-mode-hook 'linum-mode)` (untested).

**Comment by thierryvolpiatto** [comment]
lmdic <notifications@github.com> writes:

>     My gc-cons-threshold is 20000000. However, the profile indicated 1% of time was spent in GC. After turning off global-linum-mode it became almost
>     instantaneous. I replaced linum with nlinum.
>    
> I replace HELM by IDO mode + SMEX.
> And now no more slow reaction. All is very fast!

emacs -Q is very fast too...
Sorry couldn't resist.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
> If for some reason you cannot use Emacs 26, you can simply disable linum-mode in Helm, for instance (add-hook 'helm-mode-hook 'linum-mode) (untested).

Note that this will do nothing apart enabling maybe linum-mode in all helmized buffers.

**Comment by zw963** [comment]
@thierryvolpiatto ,  maybe we should  handle to set `(display-line-numbers-mode -1)` in helm if someone add 
`(global-display-line-numbers-mode)` config for emacs 26.

**Comment by thierryvolpiatto** [comment]
Billy.Zheng <notifications@github.com> writes:

> @thierryvolpiatto , maybe we should handle to set (display-line-numbers-mode -1) in helm if someone add
> (global-display-line-numbers-mode) config for emacs 26.

I don't think so, looks this mode unlike linum is fast enough and works
fine as linum-relative.el (https://github.com/coldnew/linum-relative).
I.e. C-x <n> and C-c <n> are working fine with it.

-- 
Thierry

**Comment by zw963** [comment]
```
By default, linum-relative use linum-mode as backend, since linum-mode is based on emacs-lisp, you may have performance issue on large file.

Since linum-relative 0.6, if you also use emacs version 26.1 or above, you can setup linum-relative-backend to make linum-relative-mode use display-line-number-mode as backend, which is implement in C so the performance is really nice.
```

https://github.com/coldnew/linum-relative#backends, @thierryvolpiatto

**Comment by thierryvolpiatto** [comment]
Billy.Zheng <notifications@github.com> writes:

> since linum-mode is based on emacs-lisp, you may have performance issue on large file.
>
> Since linum-relative 0.6, if you also use emacs version 26.1 or above,
> you can setup linum-relative-backend to make linum-relative-mode use
> display-line-number-mode as backend, which is implement in C so the
> performance is really nice.

You can use directly `global-display-line-numbers-mode` without the need
of linum-relative.el, it is supported by helm.

> https://github.com/coldnew/linum-relative#backends, @thierryvolpiatto
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.*


--
Thierry

**Comment by zw963** [comment]
Thank you.
