### ISSUE TITLE
Make marking candidates customizable

### ISSUE THREAD

**Issue by narendraj9** [emacs-helm/helm#1895]
My use case is to be able to do a helm-occur on all helm candidates. I use `helm-do-grep-ag` for this. The source that is used has `nomark` set and doesn't allow marking candidates and hence it's difficult for me to get a hold of all candidates and do a `muti-occur` on them. 

It think that whether marking should be allowed in a specific source or not should be left to the use of the source.

**Comment by thierryvolpiatto** [comment]
Narendra Joshi <notifications@github.com> writes:

> My use case is to be able to do a helm-occur on all helm candidates. I
> use helm-do-grep-ag for this.

Why do you want to run helm-occur on *-grep-ag candidates???

> The source that is used

Which source ?

helm-moccur is meant to be used with buffers...

-- 
Thierry

**Comment by narendraj9** [comment]
I want to search for a language's identifiers in candidate files only. 

The source is `helm-grep-ag-source`built from class `helm-grep-ag-class`

**Comment by thierryvolpiatto** [comment]
Narendra Joshi <notifications@github.com> writes:

> I want to search for a language's identifiers in candidate files only.
>
> The source is helm-grep-ag-sourcebuilt from class helm-grep-ag-class

Sorry but I still don't understand what you want to do with helm-moccur.

-- 
Thierry

**Comment by narendraj9** [comment]
Let's say I do a `helm-do-grep-ag' and search for `models.db.mongo` (which can be a namespace). Now I have helm candidates that have this string somewhere in their text. I want to now perform searches only on these files.

Sorry, if it is still unclear.

**Comment by thierryvolpiatto** [comment]
Narendra Joshi <notifications@github.com> writes:

> Let's say I do a helm-do-grep-ag' and search formodels.db.mongo`
> (which can be a namespace). Now I have helm candidates that have this
> string somewhere in their text.  I want to now perform searches only
> on these files.

Ok, so you want to set :nomark to nil, right?

If so you can add this to init file:

    (defmethod helm-setup-user-source ((source helm-grep-ag-class))
      (setf (slot-value source 'nomark) nil))

Then after restarting emacs (or rebuilding the source) you should be
able to mark candidates.

NOTE:
You can also do what you want with buffers by using the "@" filter, then
mark the resulting buffers and start helm-moccur.

--
Thierry

**Comment by narendraj9** [comment]
@thierryvolpiatto Thanks a lot! :) It works like a charm and is cleaner! :)

I couldn't understand what you meant by "@" filter. Can you please elaborate? :)

**Comment by thierryvolpiatto** [comment]
Narendra Joshi <notifications@github.com> writes:

> @thierryvolpiatto Thanks a lot! :) It works like a charm and is cleaner! :)
>
> I couldn't understand what you meant by "@" filter. Can you please elaborate? :)

From helm-mini or helm-buffers-list, you can use "@foo" to narrow down the
list to buffers containing "foo", then mark these buffers and hit C-s to
launch helm-moccur on these buffers.


-- 
Thierry
