### ISSUE TITLE
Unexpected argument: stringp, nil with bookmark+

### ISSUE THREAD

**Issue by Gastove** [emacs-helm/helm#1896]
I'm attempting to use `bmkp-url-target-set`, from `bookmark+`. It's throwing inside helm. If I do an `emacs -Q` and load nothing but `bookmark+`, the command works totally normally -- it only errors if Helm is also loaded.  It errors whether or not `helm-bookmark` has been required.

## Expected behavior

`M-x bmkp-url-target-set` should prompt for the URL, then a name for the bookmark, and create a bookmark in my configured bookmark file.

## Actual behavior

`Unexpected argument: stringp, nil` is messaged and the command exits.

## Steps to reproduce (recipe)

1. Install `bookmark+` and helm (latest from Elpa).
2. Open a fresh scratch buffer
3. `M-x bmkp-url-target-set`

## Backtraces if any (`M-x toggle-debug-on-error`)

The stack trace is astonishingly long; let me know if the full trace is useful:

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-name-as-directory(nil)
  helm-comp-read-get-candidates(ffap-read-file-or-url-internal nil nil nil "")
```

## Describe versions of Helm, Emacs, operating system, etc.
- Emacs 25.3.1
- helm-20171010-2317
- macOS 10.12.6

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):
No. This error seems to be in an interaction with another package, though I have used `emacs -Q` to verify that this problem only occurs once helm is loaded.

**Comment by thierryvolpiatto** [comment]
Ross Donaldson <notifications@github.com> writes:

> M-x bmkp-url-target-set should prompt for the URL, then a name for the
> bookmark, and create a bookmark in my configured bookmark file.

I guess bmkp is using a completing-read and the collection is empty
because it is a single url. Disable helm for this with something like:

    (add-to-list 'helm-completing-read-handlers-alist '(bmkp-url-target-set . nil))


--
Thierry
