### ISSUE TITLE
helm-cycle-resume fails: helm-iter-sub-next-circular: Invalid function: helm-position

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#1897]
## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

`helm-cycle-resume` and `helm-run-cycle-resume` fail with the following error

```
helm-cycle-resume fails: helm-iter-sub-next-circular: Invalid function: helm-position
```

## Steps to reproduce (recipe)

- `M-x helm-buffers-list`
- `C-c n`

## Describe versions of Helm, Emacs, operating system, etc.

- Helm: Melpa / master
- Gentoo
- Emacs 25.2

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Actual behavior (from emacs-helm.sh if possible, see note at the bottom)
>
> helm-cycle-resume and helm-run-cycle-resume fail with the following error
>
> helm-cycle-resume fails: helm-iter-sub-next-circular: Invalid function: helm-position

Not reproductible, try to recompile helm (verify you don't have old helm
files somewhere in load-path).

-- 
Thierry

**Comment by Ambrevar** [comment]
I can't reproduce on a different machine, however I cannot make it work, either `C-c n` does not do anything or it "resumes" an empty session.  I've never used it before, so maybe I'm doing it wrong.  How is it supposed to work?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I can't reproduce on a different machine, however I cannot make it
> work, either C-c n does not do anything or it "resumes" an empty
> session. I've never used it before, so maybe I'm doing it wrong. How
> is it supposed to work?

Of course you need to have opened more than one session to be able to
cycle, otherwise it does nothing indeed staying on same session.

Once you have many sessions to resume, you hit first `C-c n` and quickly
after `n` repeatedly until you see the name of the session you want to
resume in minibuffer.

--
Thierry

**Comment by Ambrevar** [comment]
OK, I think I've spotted one bug:
- Start with `emacs-helm.sh`.
- Call `helm-find-files`, enter a pattern, press RET.
- Do it again with another pattern.
- Call `helm-find-files` and press `C-c n`: nothing happens.
- Call `helm-buffers-list` and press `C-c n`: this time it works.

Restart `emacs-helm.sh` and repeat by swapping `helm-find-files` and `helm-buffers-list` in the procedure.

My conclusion: `C-c n` only works if at least 2 different Helm session types have been called.

I have another issue on my personal config, could be my fault, still investigating.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> OK, I think I've spotted one bug:
>
>   * Start with emacs-helm.sh.
>   * Call helm-find-files, enter a pattern, press RET.
>   * Do it again with another pattern.
>   * Call helm-find-files and press C-c n: nothing happens.
>   * Call helm-buffers-list and press C-c n: this time it works.
>
> Restart emacs-helm.sh and repeat by swapping helm-find-files and helm-buffers-list in the procedure.
>
> My conclusion: C-c n only works if at least 2 different Helm session
> types have been called.

Of course :-) what do you expect with only one session?
It is not a bug.

-- 
Thierry

**Comment by Ambrevar** [comment]
So you can't cycle through _different_ helm-find-files sessions?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> So you can't cycle through different helm-find-files sessions?

No, helm-resume is reusing the last helm-buffer.
OTOH you can bookmark your hff sessions with C-x r m and retrieve them
with C-x r b.

-- 
Thierry

**Comment by Ambrevar** [comment]
OK, makes sense now. I'll investigate the original issue I have on my setup.

**Comment by Ambrevar** [comment]
News from the front:

- I cannot reproduce the original post issue when using the git checkout.
- I can reproduce however when using Helm installed from MELPA.

Recipe:

- `emacs -Q`
- `(require 'package)`
- `(add-to-list 'package-archives '("melpa" . "http://melpa.milkbox.net/packages/"))`
- `(package-refresh-contents)`
- `(package-install 'helm)`
- `C-x c C-x C-f foo`
- `C-x c C-x C-b bar`
- `C-x c C-x C-f C-c n`

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> News from the front:
>
>   * I cannot reproduce the original post issue when using the git checkout.
>   * I can reproduce however when using Helm installed from MELPA.

Try to uninstall helm-core and helm and reinstall helm and be sure you
have not disabled async compilation in your config.

-- 
Thierry

**Comment by Ambrevar** [comment]
Err... My repice installs Helm from scratch (including, I suppose, async compilation) through MELPA.  Or am I misunderstanding you?

**Comment by thierryvolpiatto** [comment]
Have you uninstalled previous helm installations, particularly helm-core?
With your recipe you are installing helm which install helm-core, but if it finds helm-core is already installed, it installs and compile only helm.
So you have to recompile helm-core, for this use M-x helm-list-elisp-packages-no-fetch and choose the recompile action.

**Comment by thierryvolpiatto** [comment]
Ok I could reproduce, should be fixed now.

Thanks.

**Comment by Ambrevar** [comment]
Fixed, thanks!
