### ISSUE TITLE
Make helm-ff `C-c i` work on multiple candidates

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#1899]
## Steps to reproduce (recipe)

- `M-x helm-find-files`
- Select some candidates.
- `C-c i`

## Expected behavior

All selected candidates get inserted at point in current buffer.

## Actual behavior

Only current candidate gets inserted.

## Describe versions of Helm, Emacs, operating system, etc.

Helm: master

**Comment by Ambrevar** [comment]
Somehow I was sure this used to work.  But maybe I'm being mistaken for Eshell completion which can insert several completions at once (I mostly use `C-c i` in Eshell).

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Somehow I was sure this used to work.

Use `C-c C-i` and not `C-c i` which is a different thing (it is
completing).

-- 
Thierry

**Comment by Ambrevar** [comment]
Problem is, `C-c C-i` does not espace it's arguments plus it prints over multiple lines.
`helm-esh-pcomplete` can complete several candidates.  See also
https://github.com/emacs-helm/helm/issues/1827.

**Comment by Ambrevar** [comment]
Perfect, thanks!
