### ISSUE TITLE
How delete all selected buffer from helm-mini by one command?

### ISSUE THREAD

**Issue by lmdic** [emacs-helm/helm#1900]
1. Open helm using `helm-mini`
2. Scroll through the list and mark 10 buffers I want to delete with `C-Spc`
3. Press  `C-c d (helm-buffer-run-kill-persistent)` to delete all selected buffer.

OK. It's work.
But the problem is that it ask me every time (in this example 10 times) before delete buffer.

How delete all selected buffer by one command?

**Comment by Ambrevar** [comment]
It does not ask for confirmation in my case, but I believe this issue was fixed recently:
https://github.com/emacs-helm/helm/issues/1869
Update Helm and see if this is gone.

**Comment by thierryvolpiatto** [comment]
lmdic <notifications@github.com> writes:

> How delete all selected buffer by one command?

M-D

You will find this info in the helm help (C-h m).

-- 
Thierry

**Comment by lmdic** [comment]
`M-D` - close `helm-mini` buffer. But I wan't to be close.

**Comment by lmdic** [comment]
I update all my helm packages

```
  helm               20170729.2124 
  helm-core          20170727.1245
  helm-descbinds     20160916.713 
  helm-ls-git        20170727.1238
```


But the problem is not gone.
`C-c d (helm-buffer-run-kill-persistent)` - ask my EVERY time before delete every buffer

**Comment by Ambrevar** [comment]
20170729.2124? Does not seem up-to-date.  How do you update your packages?

**Comment by lmdic** [comment]
after updte helm to version 

```
helm               20171016.2245 
helm-core          20171018.2151 
helm-descbinds     20160916.713  
helm-ls-git        20170727.1238 
```

the problem is GONE!!!
Thanks.

**Comment by Cumol** [comment]
This is still happening, btw. 

helm 20200128.1832
