### ISSUE TITLE
Fail to complete to shortest when too many candidates share the same prefix

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#1901]
## Expected behavior

`C-h f hel` should return "helm" near the beginning as I type.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

"helm" it's does not appear in the list until I finish typing "helm", at which
time it finally appears on top, but that defeats the whole purpose of
completion.

`helm-M-x` suffers from the same issue.

I think this has to do with the number of entries.  For instance if you use
vanilla Org-mode, then `C-h f org-agend` works alright.
If you install org-contrib-plus which adds tons of `org-agenda-` prefixed commands, then the same issue arises.

## Steps to reproduce (recipe)

`C-h f hel`: no "helm" there.
`C-h f helm`: there it is!

## Describe versions of Helm, Emacs, operating system, etc.

Emacs 25.2
Helm: MELPA

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Expected behavior
>
> C-h f hel should return "helm" near the beginning as I type.

It does if "helm" is in the list of candidates to sort, which may not be
the case if your helm-candidate-number-limit is too low (for me it
starts appearing with a limit of 400, not below).

-- 
Thierry

**Comment by Ambrevar** [comment]
So if I understand correctly, `describe-function` looks up the first `helm-candidate-number-limit` randomly (in which case "helm" might not be part of the list), then sorts the list?

**Comment by Ambrevar** [comment]
So there is now way of fixing this?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> So there is now way of fixing this?

Apart increasing helm-candidate-number-limit, no.

    (helm-position "helm" (all-completions "hel" obarray 'functionp)
    :test 'equal)

-- 
Thierry

**Comment by Ambrevar** [comment]
Hmm, a pity.  Alright, closing.
