### ISSUE TITLE
Cannot get helm execute action at once to work

### ISSUE THREAD

**Issue by quicknir** [emacs-helm/helm#1903]
## Expected behavior

Expecting helm to immediately jump to a file, because it's the only hit.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

It doesn't.

## Steps to reproduce (recipe)

I have code like this:

```
(defun worse-faster-projectile-files-input (input)
  (interactive)
  (let ((default-directory (projectile-project-root))
        (helm-execute-action-at-once-if-one t))
    (helm :sources 'worse-helm-source-projectile-files-list
          :buffer "*helm worse files*"
          :input input)))
```
I'd expect if this function is called with `input` such that only one file matches, it would jump to that file. The only thing I can think of, is that maybe helm-execute-action-at-once is not supported for async sources? My source is asynchronous. In that case is there any way to get the same behavior?

## Describe versions of Helm, Emacs, operating system, etc.
Emacs 25.1, rhel 6, helm 20170514

**Comment by thierryvolpiatto** [comment]
Sorry for late reply.
This is not working for async sources, but perhaps you can check if you have only one candidate in a sentinel function and exit to this candidate from there ?

**Comment by quicknir** [comment]
Thanks for the response! I'll give it a shot.
