### ISSUE TITLE
Suggestion: helm-clean-list

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#1906]
I think it would be a good idea if Helm could remove selected candidates from lists like

- the mark ring,
- the `helm-*-history' variables,

and probably a few more.

A sort of powerful, manual cleanup.  Or "how to keep the history tailored to your needs".
For instance, sometimes I run useless commands in Eshell and I don't want them to "pollute" my history; I could confuse useless commands for useful commands if they look alike.

The problem: Helm history commands and `helm-show-kill-ring` do not have multiple selection turned on as it would not make sense to recall several elements of a history.

Two suggestions:

1. Enable multiple selection never the less.  The "default" action will work on the selected candidate while the "remove" action will work on the marked candidates.

2. Add a special helm command that prompts for a variable to clean up and then list its content ready to be filtered+deleted.
That command would have to take into account that some variables are lists while others are rings.

Side note: just noticed that `helm-find-file-history` allows for multiple candidate selection.  Bug?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I think it would be a good idea if Helm could remove selected candidates from lists like
>
>   * the mark ring,
>   * the `helm-*-history' variables,
>
> and probably a few more.
>
> A sort of powerful, manual cleanup. Or "how to keep the history tailored to your needs".
> For instance, sometimes I run useless commands in Eshell and I don't want them to "pollute" my history; I could confuse useless commands for useful commands if they
> look alike.
>
> The problem: Helm history commands and helm-show-kill-ring do not have
> multiple selection turned on as it would not make sense to recall
> several elements of a history.

helm-show-kill-ring allow deleting many entries at once, perhaps you
mean mark-ring ?


> Two suggestions:
>
>  1. Enable multiple selection never the less. The "default" action
>  will work on the selected candidate while the "remove" action will
>  work on the marked candidates.

It's what helm-show-kill-ring does, so you want this for mark-ring ?

>  2. Add a special helm command that prompts for a variable to clean up
>     and then list its content ready to be filtered+deleted.  That
>     command would have to take into account that some variables are
>     lists while others are rings.

Why not adding this as action to helm-apropos ?

> Side note: just noticed that helm-find-file-history allows for
> multiple candidate selection. Bug?

Yes forgot to add :nomark, but the action works only on selection.

--
Thierry

**Comment by Ambrevar** [comment]
> helm-show-kill-ring allow deleting many entries at once, perhaps you mean mark-ring ?

Sorry, I mixed up the two, and yes, helm-show-kill-ring is already OK.
On second thought I don't think it makes much sense for the mark ring.

> Why not adding this as action to helm-apropos ?

Indeed, I think it's a good idea.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

>     helm-show-kill-ring allow deleting many entries at once, perhaps you mean mark-ring ?
>    
> Sorry, I mixed up the two, and yes, helm-show-kill-ring is already OK.
> On second thought I don't think it makes much sense for the mark ring.

Me too.

>
>     Why not adding this as action to helm-apropos ?
>    
> Indeed, I think it's a good idea.

Something like this should work:

    (defun helm-apropos-clean-variable (candidate)
      (let* ((sym   (intern-soft candidate))
             (cands (symbol-value sym))
             (mkds  (helm-comp-read "Delete entry: " cands :marked-candidates t)))
        (cl-loop for elm in mkds do (set sym (setq cands (delete elm cands))))))


-- 
Thierry

**Comment by Ambrevar** [comment]
I haven't tried, but wouldn't that work only for lists?
What about other rings?  Say the `kmacro-ring`.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I haven't tried, but wouldn't that work only for lists?

Yes, unless the ring is implemented with list like kill-ring, otherwise
the function should check with ring-p and and handle sequence as a ring.
 
> What about other rings? Say the kmacro-ring.

There is a command for kmacro in helm-ring, we could add an action to it.


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
For history, try this patch:

```diff
diff --git a/helm-elisp.el b/helm-elisp.el
index 5e744ce1..93d3ddd9 100644
--- a/helm-elisp.el
+++ b/helm-elisp.el
@@ -507,6 +507,15 @@ Filename completion happen if string start after or between a double quote."
       candidates
       (sort candidates #'helm-generic-sort-fn)))
 
+(defun helm-apropos-clean-history-variable (candidate)
+  (let* ((sym   (intern-soft candidate))
+         (cands (symbol-value sym))
+         (mkds  (and (listp cands)
+                     (helm-comp-read "Delete entry: "
+                                     cands :marked-candidates t))))
+    (cl-assert (listp mkds) nil "Variable value is not a list")
+    (cl-loop for elm in mkds do (set sym (setq cands (delete elm cands)))))))
+
 (defun helm-def-source--emacs-variables (&optional default)
   (helm-build-in-buffer-source "Variables"
     :init (lambda ()
@@ -527,19 +536,21 @@ Filename completion happen if string start after or between a double quote."
     :action-transformer
     (lambda (actions candidate)
       (let ((sym (helm-symbolify candidate)))
-        (if (custom-variable-p sym)
-            (append
-             actions
-             (let ((standard-value (eval (car (get sym 'standard-value)))))
-               (unless (equal standard-value (symbol-value sym))
-                 `(("Reset Variable to default value" .
-                    ,(lambda (candidate)
-                       (let ((sym (helm-symbolify candidate)))
-                         (set sym standard-value)))))))
-             '(("Customize variable" .
-                (lambda (candidate)
-                  (customize-option (helm-symbolify candidate))))))
-          actions)))))
+        (cond ((custom-variable-p sym)
+               (append
+                actions
+                (let ((standard-value (eval (car (get sym 'standard-value)))))
+                  (unless (equal standard-value (symbol-value sym))
+                    `(("Reset Variable to default value" .
+                                                         ,(lambda (candidate)
+                                                            (let ((sym (helm-symbolify candidate)))
+                                                              (set sym standard-value)))))))
+                '(("Customize variable" .
+                   (lambda (candidate)
+                     (customize-option (helm-symbolify candidate)))))))
+              ((string-match-p "history" candidate)
+               (append actions '(("Clean variable" . helm-apropos-clean-history-variable))))
+              (t actions))))))
 
 (defun helm-def-source--emacs-faces (&optional default)
   "Create `helm' source for faces to be displayed with
```

**Comment by thierryvolpiatto** [comment]
Perhaps add a specialized function for rings when ring is detected with ring-p.

**Comment by Ambrevar** [comment]
> There is a command for kmacro in helm-ring, we could add an action to it.

By the way, `helm-execute-kmacro` also allows for multiple selection.  Which is good if we want to add a "delete" action.  Presently it is not used however as only the current candidate is executed.

Actually that would be an _awesome_ feature to run multiple kmacros in the order they are selected.
It would be neat to add a transformer to display the index of the execution order for all selected candidates.
What do you think?

**Comment by Ambrevar** [comment]
About your patch: looks good to me.

**Comment by Ambrevar** [comment]
I can't seem to be able to clean `eshell-history-ring`.  Note that it's a local variable in my case.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I can't seem to be able to clean eshell-history-ring. Note that it's a
> local variable in my case.

This is not yet implemented:

(ring-p eshell-history-ring) => t

The clean action works only on list for now, I haven't yet added the clean
ring action (unsure what to do for now):


    (defun helm-apropos-clean-ring (candidate)
      (let* ((sym   (intern-soft candidate))
             (cands (and (ring-p sym) (ring-elements sym)))
             (mkds  (and cands (helm-comp-read "Delete entry: "
                                               cands :marked-candidates t))))
        (when mkds
          (cl-loop for elm in mkds do (ring-remove sym (helm-position elm cands))))))


-- 
Thierry

**Comment by Ambrevar** [comment]
I haven't tried your code but does it cause any issue?  It looks good to me.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I haven't tried your code

Me too :)

> but does it cause any issue? It looks good to me.

Don't know yet what to do:

1) Have two function, one for rings one for lists, when ring-p make the
ring function popup, when matching history and it is a list make appear
the other function for list.
2) Have only one function (merge the two function) that popup when
"ring-p or (and match history listp history)"


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Thierry Volpiatto <thievol05@zoho.eu> writes:

> Pierre Neidhardt <notifications@github.com> writes:
>
>> I haven't tried your code
>
> Me too :)
>
>> but does it cause any issue? It looks good to me.
>
> Don't know yet what to do:
>
> 1) Have two function, one for rings one for lists, when ring-p make the
> ring function popup, when matching history and it is a list make appear
> the other function for list.
> 2) Have only one function (merge the two function) that popup when
> "ring-p or (and match history listp history)"

Finally opted for 1) which is easier to read and debug.

-- 
Thierry

**Comment by Ambrevar** [comment]
Well, since there probably only ever will be lists and rings to clean, that code won't expand, so there is little need for a specially smart design.  So I think both 1 and 2 are fine.

**Comment by Ambrevar** [comment]
Just tested: looks good to me.  Thanks.

**Comment by Ambrevar** [comment]
What about my comment on the kmacros?  Or do you want to tackle this in another issue?
I really the idea of chaining macros, that would be one of the things that make Helm so special :)

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> What about my comment on the kmacros? Or do you want to tackle this in
> another issue?

Yes, another issue.

> I really the idea of chaining macros, that would be one of the things
> that make Helm so special :)

Will not be trivial to implement.

-- 
Thierry

**Comment by Ambrevar** [comment]
See #1913.
