### ISSUE TITLE
Help with writing new helm-exwm source

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#1907]
I'm working on a helm-exwm source that would be similar to helm-buffers except it would be exclusive to EXWM buffers.
I'm facing a few puzzling issues, so maybe you can help.

``` elisp
(defvar helm-exwm-browser-map
  (let ((map (make-sparse-keymap)))
    (set-keymap-parent map helm-map)
    (define-key map (kbd "C-c o")     'helm-buffer-switch-other-window)
    (define-key map (kbd "C-c C-o")   'helm-buffer-switch-other-frame)
    (define-key map (kbd "M-D")       'helm-buffer-run-kill-buffers)
    ;; (define-key map (kbd "C-c d")     'helm-buffer-run-kill-persistent)
    (define-key map (kbd "C-c d")     'helm-exwm-buffer-run-kill-persistent)
    map)
  "Keymap for browser source in Helm.")

;; This fails to be persistent, nothing is run after kill-buffer.
(defun helm-exwm-buffer-run-kill-persistent ()
  "Kill buffer without quitting helm."
  (interactive)
  (message "before")
  (kill-buffer (car (helm-marked-candidates)))
  (message "after"))
(put 'helm-exwm-buffer-run-kill-persistent 'helm-only t)

(defun helm-exwm-browser-buffers ()
  "Preconfigured `helm' to list browser buffers."
  (interactive)
  (helm :sources
        (helm-build-sync-source "helm-exwm browser buffers"
          :candidates
          (let ((bufs (delq nil (mapcar
                                 (lambda (buf)
                                   (if (with-current-buffer buf
                                         (and (eq major-mode 'exwm-mode)
                                              (string= (downcase exwm-class-name) (file-name-nondirectory browse-url-generic-program))))
                                       (buffer-name buf)
                                     nil))
                                 (buffer-list)))))
            (when bufs
              ;; Move first buffer (current) to last position.
              (setcdr (last bufs) (list (pop bufs))))
            bufs)
          :action '(("Switch to browser buffer(s)" . helm-buffer-switch-buffers)
                    ("Switch to browser buffer(s) in other window `C-c o'" . helm-buffer-switch-buffers-other-window)
                    ("Switch to browser buffer in other frame `C-c C-o'" . switch-to-buffer-other-frame)
                    ("Kill browser buffer(s)" . helm-kill-marked-buffers))
          ;; When follow-mode is on, the persistent-action allows for multiple candidate selection.
          :persistent-action 'helm-buffers-list-persistent-action
          ;; :update 'helm-exwm-update
          :keymap helm-exwm-browser-map)
        :buffer "*helm-exwm browser*"))

(exwm-input-set-key (kbd "s-w") #'helm-exwm-browser-buffers)
```

In the above example, the "kill buffer" persistent action is not persistent.
In fact, the call to `kill-buffer` in `helm-exwm-buffer-run-kill-persistent` seems to abort the function and close the Helm session.
It is to be noted that there seem to be an issue with the value returned by `kill-buffer` for EXWM buffers:
https://github.com/ch11ng/exwm/issues/322

I'm not sure why this terminates the function.  The following function kills all EXWM buffers as expected:

```
(defun helm-exwm-kill-all ()
  (dolist (b (buffer-list))
    (with-current-buffer b
      (when (eq major-mode 'exwm-mode)
        (message "helm-exwm: Killing %s..." b)
        (kill-buffer b)
        (message "helm-exwm: Killed.")))))
```

The documentation of `kill-buffer` shows that

> Any processes that have this buffer as the ‘process-buffer’ are killed
> with SIGHUP.  This function calls ‘replace-buffer-in-windows’ for
> cleaning up all windows currently displaying the buffer to be killed.

----------

Side question: How do you run Edebug over helm-related functions?  My problem is that the Edebug messages are instantly covered by the Helm prompt, so I cannot read them.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> ;; This fails to be persistent, nothing is run after kill-buffer.
> (defun helm-exwm-buffer-run-kill-persistent ()

See `helm-buffer-run-kill-persistent` as example.

> Side question: How do you run Edebug over helm-related functions? My
> problem is that the Edebug messages are instantly covered by the Helm
> prompt, so I cannot read them.

Yes helm is hard to debug with edebug, you can read the messages
afterward in the *messages* buffer.

You can use helm-log messages in your code if that help.
See the helm help about debugging.

--
Thierry

**Comment by Ambrevar** [comment]
> See `helm-buffer-run-kill-persistent` as example.

You misunderstood.  See my code above, `helm-buffer-run-kill-persistent` is commented because I tried using it and got the same issue, that is, the helm buffer disappears.

I tried reproducing with the shortest possible function, i.e.:

```
(defun helm-exwm-buffer-run-kill-persistent ()
  "Kill buffer without quitting helm."
  (interactive)
  (message "before")
  (kill-buffer (car (helm-marked-candidates)))
  (message "after"))
(put 'helm-exwm-buffer-run-kill-persistent 'helm-only t)
```

`"after"` is never messaged.  The function fails to complete until the end, and yet there is no error.  Strange, isn't it?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

>     See helm-buffer-run-kill-persistent as example.
>    
> You misunderstood. See my code above, helm-buffer-run-kill-persistent is commented because I tried using it and got the same issue, that is, the helm buffer
> disappears.
>
> I tried reproducing with the shortest possible function, i.e.:
>
> (defun helm-exwm-buffer-run-kill-persistent ()
>   "Kill buffer without quitting helm."
>   (interactive)
>   (message "before")
>   (kill-buffer (car (helm-marked-candidates)))
>   (message "after"))
> (put 'helm-exwm-buffer-run-kill-persistent 'helm-only t)
>
> "after" is never messaged. The function fails to complete until the end, and yet there is no error. Strange, isn't it?

There is nothing strange, when you hit C-c d (is it C-c d ?) helm
doesn't know that helm-exwm-buffer-run-kill-persistent is a persistent
action, how would it know ?
Helm is using it just as if it were a normal action.
C-j OTH should work as expected as it finds in source a
persistent-action attribute bound to your function.
If you want to bind your PA to another key than C-j, you have to use

    (with-helm-alive-p
        (helm-attrset 'foo-action '(foo . never-split))
        (helm-execute-persistent-action 'foo-action))

-- 
Thierry

**Comment by Ambrevar** [comment]
Sorry, I forgot to include that part of the code in the issue (but I did use it)
```
  (with-helm-alive-p
    (helm-attrset 'kill-action '(helm-buffers-persistent-kill . never-split))
    (helm-execute-persistent-action 'kill-action)))
```

Regardless, that's not the issue: it does not work as it terminates whenever `kill-buffer` is called.  The `(message "after")` is never run.

**Comment by Ambrevar** [comment]
Correction: that's the full code
```
;;; This fails to be persistent, nothing is run after kill-buffer.
(defun helm-exwm-buffer-run-kill-persistent ()
  "Kill buffer without quitting helm."
  (interactive)
  (with-helm-alive-p
    (helm-attrset 'kill-action '(helm-exwm-buffers-persistent-kill . never-split))
    (helm-execute-persistent-action 'kill-action)))
(put 'helm-exwm-buffer-run-kill-persistent 'helm-only t)

(defun helm-exwm-buffers-persistent-kill ()
  "Kill buffer without quitting helm."
  (interactive)
  (message "before")
  (kill-buffer (car (helm-marked-candidates)))
  (message "after"))
```

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Sorry, I forgot to include that part of the code in the issue (but I did use it)
>
>   (with-helm-alive-p
>     (helm-attrset 'kill-action '(helm-buffers-persistent-kill . never-split))
>     (helm-execute-persistent-action 'kill-action)))
>
> Regardless, that's not the issue: it does not work as it terminates
> whenever kill-buffer is called. The (message "after") is never run.

Are you sure the message is not hidden by a (message nil) somewhere ?
Look in *messages* buffer to be sure there is no "after" somewhere.

-- 
Thierry

**Comment by Ambrevar** [comment]
That's not it either: I ran the code through Edebug: the function calling (kill-buffer <exwm-buffer>) terminates right at that call, and the rest of the function is never run.

**Comment by Ambrevar** [comment]
Sorry, I've just realized that `helm-buffers-list` suffer from the same issue: it cannot kill EXWM buffers persistently.  So this has nothing to do with my source.

**Comment by Ambrevar** [comment]
I'm more or less done with my new `helm-exwm` package: https://github.com/Ambrevar/dotfiles/blob/master/.emacs.d/lisp/package-helm-exwm.el

Beside current issue and issue #1911, it works pretty neatly.
I'd like to publish the package.  Would you consider hosting it on github.com/emacs-helm or should I just release it independently?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I'm more or less done with my new helm-exwm package: https://github.com/Ambrevar/dotfiles/blob/master/.emacs.d/lisp/package-helm-exwm.el
>
> Beside current issue and issue #1911, it works pretty neatly.  I'd
> like to publish the package. Would you consider hosting it on
> github.com/emacs-helm

No problems, I think I gave you the right to add your package there, let
me know if you can't.

Thanks.

--
Thierry

**Comment by Ambrevar** [comment]
I'm not sure I can create a github.com/emacs-helm/helm-exwm repository.  Aren't I supposed to be in https://github.com/orgs/emacs-helm/people or is this unrelated?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I'm not sure I can create a github.com/emacs-helm/helm-exwm
> repository. Aren't I supposed to be in
> https://github.com/orgs/emacs-helm/people or is this unrelated?

You are right, I added you to people, so you should now be able to create
new repositories, let me know if you still not have the rights.

-- 
Thierry

**Comment by Ambrevar** [comment]
Good, thank you very much!

**Comment by Ambrevar** [comment]
I'd like to let the user customize `helm-mini` sources so that one source contains all Emacs buffers but EXWM's and another contains only EXWM's buffers.

My package contains a "EXWM buffer source".
I'd like to create a source of all buffers like `helm-source-buffers` with all EXWM buffers filtered out.
Is it possible to do this without rewriting a new `helm-source-buffers`?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I'd like to let the user customize helm-mini sources so that one
> source contains all Emacs buffers but EXWM's and another contains only
> EXWM's buffers.
>
> My package contains a "EXWM buffer source".
> I'd like to create a source of all buffers like helm-source-buffers with all EXWM buffers filtered out.
> Is it possible to do this without rewriting a new helm-source-buffers?

Use (let-bind) helm-boring-buffer-regexp-list ?

--
Thierry

**Comment by Ambrevar** [comment]
But that does not work per-source, does it?
Can I define a new source that is just `helm-source-buffers` with a let-bound `helm-boring-buffer-regexp-list`?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> But that does not work per-source, does it?

No, you are right, what you can do is define a new function to get your
buffers and add it in your source with :buffer-list slot like we do in helm-ls-git:

    (defun helm-ls-git-build-buffers-source ()
      "Build `helm-source-ls-git-buffers'.

    Do nothing when `helm-source-ls-git-buffers' is not member of
    `helm-ls-git-default-sources'."
      (and (memq 'helm-source-ls-git-buffers helm-ls-git-default-sources)
           (helm-make-source "Buffers in git project" 'helm-source-buffers
             :header-name #'helm-ls-git-header-name
             :buffer-list (lambda () (helm-browse-project-get-buffers
                                      (helm-ls-git-root-dir)))
             :keymap helm-ls-git-buffer-map)))


-- 
Thierry

**Comment by Ambrevar** [comment]
That's perfect.  Alright, helm-exwm inbound then! :)

**Comment by Ambrevar** [comment]
Actually there is an issue: it seems that using several sources at once which all set `:buffer-list` will create a conflict.  In my case, my "non-EXWM-buffers" source seems to override the normal buffer list so that EXWM buffers are remove from both sources.

**Comment by Ambrevar** [comment]
Seems perfect, thanks!

**Comment by Ambrevar** [comment]
I've commited the new project and opened specific issues, so I'm closing this one.
