### ISSUE TITLE
Broken helm-sys::helm-top CPU sorting (and defcustom typo)

### ISSUE THREAD

**Issue by ahungry** [emacs-helm/helm#1909]
## Expected behavior

Set up the defcustom for helm-sys helm-top columns properly, and see CPU and MEM sorting work.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

CPU was not sorting at all with the default helm top command in helm-sys, as the CPU running function was setting the CPU sort to null (git log mentioned a ps sort fix was the reason that line was committed originally).

When setting the defcustom, also noticed incorrect spelling of colum for the variable, despite being called column throughout various spots in the doc strings.

Fixed in PR #1908

**Comment by thierryvolpiatto** [comment]
Matthew Carter <notifications@github.com> writes:

> Expected behavior
>
> Set up the defcustom for helm-sys helm-top columns properly

If sorting is not working perhaps you modified wrongly
helm-top-sort-colums-alist ?

> , and see CPU and MEM sorting work.

AFAICT sorting both by CPU and MEM is working fine from emacs-helm.sh,
can you explain what is going wrong from emacs-helm.sh (recipe).

Thanks.

> Actual behavior (from emacs-helm.sh if possible, see note at the bottom)
>
> CPU was not sorting at all with the default helm top command in
> helm-sys, as the CPU running function was setting the CPU sort to null
> (git log mentioned a ps sort fix was the reason that line was
> committed originally).

Top is sorting by CPU by default so there is no need to have a sort
command when using CPU sorting, no need to sort what is already sorted.

> When setting the defcustom, also noticed incorrect spelling of colum
> for the variable, despite being called column throughout various spots
> in the doc strings.

Thanks for the spelling fix.

>
> Fixed in PR #1908

With this fix sorting with `ps` would not work, at least by default.

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.*


--
Thierry

**Comment by ahungry** [comment]
Top does not always sort by CPU by default.  On a fresh Arch Linux install, top sorts by PID, *not* by CPU.

That is a user setting, and not implied by how the rest of the package operates (it could just as easily default to sorting by MEM).

I do not understand why the CPU sort function must be null for the ps sort to work either - if the user is relying on ps to sort, perhaps ps should set the 'top' command to something other than the default (so it misses the clause that forces the CPU sort to be null).

**Comment by ahungry** [comment]
Also, fwiw, on a fresh docker alpine image, top does not sort by CPU there either (it sorts by PID), and the CLI flags given in the helm-sys file do not force a CPU sort by default either.

Have you tested under any GNU/Linux dist or just OSX?

**Comment by ahungry** [comment]
CentOS 6+ tested and confirmed, no CPU default sort.

Was this working for any GNU/Linux users in the past?  Because the failure seems consistent on all the 3 OSes (I'll test Ubuntu tomorrow).

**Comment by ahungry** [comment]
Recipe for failure:

Any GNU/Linux distribution:

./emacs-helm.sh
M-x helm-top
M-P 

No sorted CPU (even when accounting for column misalignment).

Behavior with the update I have added = sorted CPU.

**Comment by thierryvolpiatto** [comment]
Matthew Carter <notifications@github.com> writes:

> Also, fwiw, on a fresh docker alpine image, top does not sort by CPU there either (it sorts by PID), and the CLI flags given in the helm-sys file do not force a CPU
> sort by default either.
>
> Have you tested under any GNU/Linux dist or just OSX?

I use ubuntu 14.04 and sorting is done by default by CPU.

> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.*


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Matthew Carter <notifications@github.com> writes:

> Top does not always sort by CPU by default. On a fresh Arch Linux install, top sorts by PID, not by CPU.

Ok, so that's mean there is different top versions around and we indeed
need to use a specific sort function.

> That is a user setting, and not implied by how the rest of the package
> operates (it could just as easily default to sorting by MEM).
>
> I do not understand why the CPU sort function must be null for the ps
> sort to work either

All the contrary it have to be set.

--
Thierry

**Comment by Ambrevar** [comment]
See #1586 for more details.  I have had sorting issues so far but I never took time to investigate.
Latest commits seem to do it though.
