### ISSUE TITLE
Helm buffers not truncated properly when helm-buffers-end-truncated-string is changed

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#1910]
## Expected behavior

`(setq helm-buffers-end-truncated-string "…")`: truncated buffers should display two characters more and the size column should stay at the some spot.

Conversely,

`(setq helm-buffers-end-truncated-string "......")`: truncated buffers should display 3 characters less and the size column should stay at the some spot.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

The truncated name remains the same regardless of the `helm-buffers-end-truncated-string` value while the size column gets moved.

I think `helm-buffer-max-length` is meant to define the total width the of truncated buffer name, suffix included.

## Steps to reproduce (recipe)

- `(setq helm-buffers-end-truncated-string "…")`
- `M-x helm-buffers-list`

## Describe versions of Helm, Emacs, operating system, etc.

- GNU Emacs 25.2.2 (x86_64-unknown-linux-gnu, GTK+ Version 3.10.8) of 2017-06-28
- Helm: MELPA

**Comment by Ambrevar** [comment]
c99c2c6 mis-aligns the columns when the truncation string is more than 1 character.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> c99c2c6 mis-aligns the columns when the truncation string is more than 1 character.

Can you develop? everything is aligned properly here, I tried with "..."
and "......", recipe please and perhaps screenshot.

Thanks.


-- 
Thierry

**Comment by Ambrevar** [comment]
Recipe:

- `emacs-helm.sh`
- `C-x C-f`: open file with more than 20 characters in its name
- `C-x C-b`: OK
- `(setq helm-buffers-end-truncated-string "…....")`
- `C-x C-b`: size, mode and path of the file are not aligned with those of the message buffer and the scratch buffer.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Recipe:
>
>   * emacs-helm.sh
>   * C-x C-f: open file with more than 20 characters in its name
>   * C-x C-b: OK
>   * (setq helm-buffers-end-truncated-string "…....")
>   * C-x C-b: size, mode and path of the file are not aligned with those of the message buffer and the scratch buffer.

Of course, you are mixing unicode strings and ascii strings, why one
would want to do this (I mean for such a simple thing as a separator).

> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.*


-- 
Thierry

**Comment by Ambrevar** [comment]
No, this is not the issue: "aaaaa" as a separator will do the same.
Note that if I set the separator _before_ loading helm, it's fine.  If I change afterwards the alignment goes awry.

It's convenient to use unicode in separators because you can use symbols that are easily distringuished from filenames and that make sense as a separator.
Also … is 2 characters shorter than `...`.  This can make a difference on small screen where real estate is precious!

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> No, this is not the issue: "aaaaa" as a separator will do the same.
> Note that if I set the separator before loading helm, it's fine. If I
> change afterwards the alignment goes awry.

Sorry but I can't reproduce, I can modify as I want separator and stay
always aligned properly.

>
> It's convenient to use unicode in separators because you can use
> symbols that are easily distringuished from filenames and that make
> sense as a separator.  Also … is 2 characters shorter than .... This
> can make a difference on small screen where real estate is precious!

Yes I have nothing against unicode strings, but why do you mix unicode
string with ascii string?

There is no reliable ways to measure the length of such strings.

--
Thierry

**Comment by thierryvolpiatto** [comment]
More I think at it more I think it is not needed to modify this so I have reverted for now.
You can get exactly what you want by setting `n` characters less `helm-buffer-max-length` where `n` is the length of your separator.

**Comment by Ambrevar** [comment]
> Yes I have nothing against unicode strings, but why do you mix unicode string with ascii string?

Sorry, that does not make sense to me.  A unicode string can contain ASCII characters.
The length of unicode strings is computed the same way, with or without ASCII characters: the algorithm is so that it support variable width characters, the width varying between 1 and... 4 or 6, don't remember.

```
(string-width "…")
1
(string-width "…a")
2
```

**Comment by thierryvolpiatto** [comment]
Let restart from start:

What you want is when `(setq helm-buffers-end-truncated-string "…")`  and  "…" is a unicode string of length 1 (not 3) you can see 2 more characters in the buffer name part, right ?
The only thing you have to do in this case with original code is increasing `helm-buffer-max-length` by 2. You will have what you want and I have nothing to do. Is it ok for you ?

**Comment by Ambrevar** [comment]
Of course I can do that.  I filed this issue because this is not very elegant: the user should not have to do some column calculation just to change the separators.

I would send a PR but I'm very busy these days, so maybe later.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Of course I can do that. I filed this issue because this is not very
> elegant: the user should not have to do some column calculation just
> to change the separators.

There is no calculation to do, the user changes the separator to "…" then
he sees that he can now increase the value of `helm-buffer-max-length`
just by looking at the display of buffers list.

> I would send a PR but I'm very busy these days, so maybe later.

I am reluctant to modify this because it already have caused many
problems of aligment (and lot of work to fix it) with people using emacs
with Japanese/Chinese characters.

--
Thierry
