### ISSUE TITLE
Helm-find-files freeze at startup

### ISSUE THREAD

**Issue by erik-helmers** [emacs-helm/helm#1912]
Hi !
I have a weird bug.. I really don't understand, tried installing from source, MELPA, etc...

## Expected behavior
First helm-find-files call should be instant or fast (< 5 seconds) 

## Actual behavior
First helm-find-files call make emacs freeze for  up to two minutes then opens.
After that i can call again helm-find-files without problems or delay.

## Steps to reproduce (recipe)
Simply C-x C-f with helm.

## Backtraces if any 
None

## Describe versions of Helm, Emacs, operating system, etc.
Helm 20171104.2211, Emacs 24.5.1, Ubuntu 16.04.. 
## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):
Yes and it does the same weird behavior.

**Comment by thierryvolpiatto** [comment]
Erik Helmers <notifications@github.com> writes:

> Hi !
> I have a weird bug.. I really don't understand, tried installing from source, MELPA, etc...
>
> Expected behavior
>
> First helm-find-files call should be instant or fast (< 5 seconds)
>
> Actual behavior
>
> First helm-find-files call make emacs freeze for up to two minutes then opens.
> After that i can call again helm-find-files without problems or delay.

See
https://github.com/emacs-helm/helm/wiki/FAQ#why-helm-mode-is-so-long-to-startup

-- 
Thierry

**Comment by erik-helmers** [comment]
OK sorry, I didn't see that FAQ answer... I'll search about it. Thanks anyway !
