### ISSUE TITLE
Suggestion: Execute multiple kmacros in sequence

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#1913]
`helm-kmacros` supports multiple candidates by mistake: Helm actually ignores it.

This gave me the idea that we could make use of this feature to exectute all the selected macro candidates in sequence (possibly in the order they were selected if Helm supports that).

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> helm-kmacros supports multiple candidates by mistake: Helm actually ignores it.

Note that when you are allowed to mark candidates in a helm buffer, that
doesn't mean forcibly you can do something on marked candidates, this
depend on the action(s) if it uses (helm-marked-candidates) or
candidate.

> This gave me the idea that we could make use of this feature to
> exectute all the selected macro candidates in sequence (possibly in
> the order they were selected if Helm supports that).

Making an action that execute all marked kmacro at once would not be
really useful as kmacro have to be repeated n times, that's their
purpose, so executing same action a second time would require restarting
helm and remarking all candidates in same order etc..

What would be useful is an action that create a new kmacro compiling all
marked candidates, this new macro would be pushed on top of ring to be
reused with f4 (or helm + PA).

Note that actually you can execute kmacros with persistent action
allowing you to change kmacro after each hit of C-j.

--
Thierry

**Comment by Ambrevar** [comment]
> What would be useful is an action that create a new kmacro compiling all
> marked candidates, this new macro would be pushed on top of ring to be
> reused with f4 (or helm + PA).

Indeed.

> Note that actually you can execute kmacros with persistent action
> allowing you to change kmacro after each hit of C-j.

I did not know that, thanks for the tip!

**Comment by Ambrevar** [comment]
Works great, thanks!
