### ISSUE TITLE
Cannot kill EXWM buffers persistently

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#1914]
## Expected behavior

`C-c d` on an EXWM buffer should kill the buffer while keep the Helm session open.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

The buffer gets killed and the Helm session terminates.

## Steps to reproduce (recipe)

- Install EXWM.
- Start any X program.
- Start `helm-buffers-list`.
- `C-c d` on the EXWM buffer.

## Describe versions of Helm, Emacs, operating system, etc.

Emacs: 25.3
Helm: MELPA
EXWM: 0.15

**Comment by Ambrevar** [comment]
I've experimented with the following:

Killing buffers out of Helm works properly.  The function terminates:

```
(defun helm-exwm-kill-all ()
  (dolist (b (buffer-list))
    (with-current-buffer b
      (when (eq major-mode 'exwm-mode)
        (message "helm-exwm: Killing %s..." b)
        (kill-buffer b)
        (message "helm-exwm: Killed.")))))
```

Within helm, the function does not terminate: the "after" message never prints.

```
(defun helm-exwm-buffer-run-kill-persistent ()
  "Kill buffer without quitting helm."
  (with-helm-alive-p
    (helm-attrset 'kill-action '(helm-exwm-buffers-persistent-kill . never-split))
    (helm-execute-persistent-action 'kill-action)))
(put 'helm-exwm-buffer-run-kill-persistent 'helm-only t)

(defun helm-exwm-buffers-persistent-kill ()
  "Kill buffer without quitting helm."
  (message "before")
  (kill-buffer (car (helm-marked-candidates)))
  (message "after"))
```

**Comment by thierryvolpiatto** [comment]
Did you try `kill-buffer-and-window` instead of `kill-buffer` for these specific buffers?
I don't think there is a problem specifically with helm, but with `kill-buffer` for these specific windows.

**Comment by Ambrevar** [comment]
I tried with `kill-buffer-and-window`: Same result, Helm terminates and "after" is never printed.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I tried with kill-buffer-and-window: Same result, Helm terminates and
> "after" is never printed.

Ok, and what happen if instead of calling kill-buffer directly, you use:

    (let ((kill-buffer-query-functions nil))
       (kill-buffer buf))


--
Thierry

**Comment by Ambrevar** [comment]
`kill-buffer-query-functions` contains `process-kill-buffer-query-function`.

Your trick seems to work, but it wrecks the Helm state in such a spectacular way it becomes unusable.
I'll investigate more.  In the mean time, do you have any idea what's happening?

**Comment by Ambrevar** [comment]
I see the "after" message, however after that most commands fail, anything from buffer switching to windowing.

The `*Messages*` buffer contains repetitions of

```
Selecting deleted buffer
Error in post-command-hook (helm--update-header-line): (error "No buffer named *helm*")
Error in post-command-hook (helm--maybe-update-keymap): (error "No buffer named *helm*")
...

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> kill-buffer-query-functions contains process-kill-buffer-query-function.
>
> Your trick seems to work, but it wrecks the Helm state in such a spectacular way it becomes unusable.
> I'll investigate more. In the mean time, do you have any idea what's happening?

I haven't installed exwm (it would be difficult to use on my system) but
I looked at the code and saw that
`exwm-manage--kill-buffer-query-function` is in
`kill-buffer-query-functions`, I guess the problem comes from it.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I see the "after" message, however after that most commands fail, anything from buffer switching to windowing.
>
> The *Messages* buffer contains repetitions of
>
> Selecting deleted buffer
> Error in post-command-hook (helm--update-header-line): (error "No buffer named *helm*")
> Error in post-command-hook (helm--maybe-update-keymap): (error "No buffer named *helm*")
> ...

Have a look at `exwm-manage--unmanage-window` definition, particularly
this piece of code:

      (let ((kill-buffer-func
             (lambda (buffer)
               (with-current-buffer buffer
                 (let ((kill-buffer-query-functions nil)
                       (floating exwm--floating-frame))
                   (kill-buffer)
                   (when floating
                     (select-window
                      (frame-selected-window exwm-workspace--current))))))))
        (if (not (active-minibuffer-window))
            ;; Kill the buffer as usual.
            (funcall kill-buffer-func buffer)
          ;; This can happen when this buffer was requested to be killed
          ;; from the minibuffer (e.g. with `ido-kill-buffer-at-head').
          ;; We have to exit the minibuffer first or there'll be a
          ;; "selecting deleted buffer" error.
          (run-with-idle-timer 0 nil kill-buffer-func buffer)
          (exit-minibuffer))))))

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
This looks related to exwm more than Helm, can we close this?
Thanks.

**Comment by Ambrevar** [comment]
I'll take some time to re-investigate the issue soon, I'll let you know.

**Comment by Ambrevar** [comment]
I've raised the issue on EXWM issue tracker.  Let's see what @ch11ng thinks.
