### ISSUE TITLE
Make emacs a super search center like the Alfred on macos

### ISSUE THREAD

**Issue by netjune** [emacs-helm/helm#1916]
As a system app launcher, searching bookmarks of web browser and open the result in web browser, ...
Helm seems be able to do this. Is there a plan for this?

**Comment by thierryvolpiatto** [comment]
netjune <notifications@github.com> writes:

> As a system app launcher, searching bookmarks of web browser and open the result in web browser, ...
> It seems that helm can do this. Is there a plan for this?

helm-firefox?


-- 
Thierry

**Comment by netjune** [comment]
> helm-firefox?
More than this. You can define many action modules(launch app, search bookmark, search file, google it, bing it, lookup dict for it, open it as file/directory...). Every module can process your input content, giving you the result or bring you to the final place(like the search result page in web browser).

You can set the default modules and fallback modules. You can give eveny module a keyword and use the keyword to activate the module you want.

**Comment by thierryvolpiatto** [comment]
Well, looks similar to helm, what you call modules are sources in helm and you can use several sources at once.  Note that I have no access to macos so perhaps I missed something?

**Comment by netjune** [comment]
Yes, similar concept. Alfred has better user experience(Beautiful GUI, icon, big font) and some convenient features(define keyword for action module , press shift key to preview the result of a module).

It's website: https://www.alfredapp.com/

I like the following flow:
1. input "email ", then the candidates are your contacts
2. move cursor to the one you want to send mail to, and then continue to input " this is the mail title" and press enter key
3.  Your favorite mail app will be opened. And now you just need to fill the mail body, then send it.

**Comment by thierryvolpiatto** [comment]
Helm have about everything you describe, but the UI is different, well it is emacs, so I don't see what we could do.
