### ISSUE TITLE
More simple pattern for filter buffers

### ISSUE THREAD

**Issue by lmdic** [emacs-helm/helm#1918]
Windows 10, Emacs 25.1, package helm

If I want in `helm-mini` to show all buffers with extension `*.log` AND`*.txt` I use the next pattern:

`^.*.txt\|.*.log`

or more accurately

`^.*\.\(txt\|log\)`

OK. It's work.
But the problem is this is difficult pattern for remember for me. Is it possible to use more simple pattern? Something like this:

`.log|.txt`

?

**Comment by thierryvolpiatto** [comment]
lmdic <notifications@github.com> writes:

> Windwos 10, Emacs 25.1, package helm
>
> If I want in helm-mini to show all buffers with extenstion *.log and *.txt I use the next pattern:
>
> ^.*.txt\|.*.log
>
> or more accurately
>
> ^.*\.\(txt\|log\)
>
> The problem is this is difficult pattern for remember for me. Is it possible to use more simple pattern? Something like this:
>
> .log|.txt

You have better time using mode instead of extensions, Try *txt,fun

-- 
Thierry

**Comment by lmdic** [comment]
Not help. Can you have some example?

**Comment by thierryvolpiatto** [comment]
At prompt enter `*text,fun` (sorry I wrote txt in previous example).

**Comment by thierryvolpiatto** [comment]
See C-h m for more infos on how to use filters for buffers.
