### ISSUE TITLE
write-file fail to copy to a directory under emacs-26+

### ISSUE THREAD

**Issue by thierryvolpiatto** [emacs-helm/helm#1920]
## Expected behavior

Use write-file to copy current-buffer as a file to a directory.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

In helm-mode, write-file can't be used to copy a file to another
directory with the same name. When visiting file.org, invoking
write-file and selecting ~/directory/ in the completing buffer gives
"File ''~/directory/.' exists; overwrite ?" Of course that's not what I want.

## Steps to reproduce (recipe)
Ensure helm-mode is enabled
M-x write-file
choose a directory as destination

## Describe versions of Helm, Emacs, operating system, etc.

This bug is reproductible only under emacs-26+ versions.

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):

Yes.
## IMPORTANT NOTE

Helm provides a script named `emacs-helm.sh` which runs Helm in a neutral
environment: no other packages and only minimal settings.

When possible, use it to reproduce your Helm issue to ensure no other package is
interfering.

To run it, simply switch to the directory where Helm is installed and call `./emacs-helm.sh`.

Thanks.

**Comment by thierryvolpiatto** [comment]
See https://groups.google.com/forum/#!topic/emacs-helm/PCUvfRPiduI

**Comment by dinojr** [comment]
This problem is fixed by commit https://github.com/emacs-helm/helm/commit/c8bfb714d85716761f90edbc94510c5466e1d2b0

**Comment by thierryvolpiatto** [comment]
Great, thanks to confirm closing now.
