### ISSUE TITLE
enhancement: helm-calendar

### ISSUE THREAD

**Issue by it3ration** [emacs-helm/helm#1921]
This is a feature request, and perhaps I can take a stab at it, I'll have to increase my elisp-fu.

It'd be nice to be able to explore the calendar through helm and trigger actions when you narrow down to a day(s). For example, maybe in org-journal mode (a package for journaling), you could go M-x helm-calendar, and then type like:

`year SPACE month SPACE day`

Hitting tab would let you trigger various actions based on the day (like create a new journal entry). Perhaps there could be ways to narrow to certain date(s) via keywords like `today`.

It seems I can't attach labels by default, but this would be an `enhancement` obviously.

Thanks for your consideration, I love `helm`, it's my favorite emacs package. :)

**Comment by thierryvolpiatto** [comment]
Kevin Depue <notifications@github.com> writes:

> This is a feature request, and perhaps I can take a stab at it, I'll
> have to increase my elisp-fu.
>
> It'd be nice to be able to explore the calendar through helm and
> trigger actions when you narrow down to a day(s). For example, maybe
> in org-journal mode (a package for journaling), you could go M-x
> helm-calendar, and then type like:

I just downloaded org-journal and had a quick look at the code.
It seems it uses read-string's to let user input a date, looks a better
approach would be to use completing-read's to provide completion of its
files and strings.
This would be a better approach (patching org-journal) than making a
full new helm IMO.
 
> year SPACE month SPACE day

Too long to type, better have a binding in calendar or org agenda.

> Hitting tab would let you trigger various actions based on the day
> (like create a new journal entry).

Creating a new file (<date>.org) yes, adding an entry is more difficult
i.e. where should we add the entry?

Anyway this should be implemented by a dummy source, not an action. 

Thanks.

--
Thierry

**Comment by it3ration** [comment]
Thanks for looking into this, I need to familiarize myself better with `M-x calendar`. What do you mean by adding an entry?

**Comment by thierryvolpiatto** [comment]
Kevin Depue <notifications@github.com> writes:

> Thanks for looking into this, I need to familiarize myself better with
> M-x calendar. What do you mean by adding an entry?

A heading in the <date>.org file.

--
Thierry

**Comment by it3ration** [comment]
Oh I see - let me close this issue for now and do some research, I'll rtfm a bit and get back to you. :)
