### ISSUE TITLE
Enable multiple marking with numeric prefix

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#1923]
I was working on [evil-helm](https://github.com/jojojames/evil-collection/blob/master/evil-helm.el) when I got struck by some random enlightenment: what about making `C-SPC` and `S-SPC` support a numeric prefix argument to select multiple elements at once?  That would especially make sense with relative-line-numbers.

I've done it for evil-helm, it's very easy, so I guess it could easily be merged upstream.  What do you think?

**Comment by Ambrevar** [comment]
Thanks! And what about supporting negative arguments to mark upward?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Thanks! And what about supporting negative arguments to mark upward?

Done, thanks.

-- 
Thierry

**Comment by Ambrevar** [comment]
Works like a charm!
