### ISSUE TITLE
Delete files from recentf in helm-mini breaks after narrowing

### ISSUE THREAD

**Issue by vkz** [emacs-helm/helm#1924]
`M-x helm-mini`
Type in pattern to narrow candidates. Assume it narrows to a bunch of files from recentf.
Mark some of theme.
`Delete file(s) from recentf`

## Expected behavior
marked files should no longer appear in recentf

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
files apper under recentf in helm-mini

## Steps to reproduce (recipe)
as described above. 

NOTE: Works correctly if you don't narrow candidates with pattern, instead switch to recentf source in helm-mini with `C-o`, mark files there, then delete from recentf.

## Describe versions of Helm, Emacs, operating system, etc.
GNU Emacs 25.3.1 (x86_64-apple-darwin17.2.0, NS appkit-1561.10 Version 10.13.1 (Build 17B48)) of 2017-11-12

helm-20171124.102 from melpa

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):
yes

## IMPORTANT NOTE

Helm provides a script named `emacs-helm.sh` which runs Helm in a neutral
environment: no other packages and only minimal settings.

When possible, use it to reproduce your Helm issue to ensure no other package is
interfering.

To run it, simply switch to the directory where Helm is installed and call `./emacs-helm.sh`.

Thanks.

**Comment by thierryvolpiatto** [comment]
Vladilen Kozin <notifications@github.com> writes:

> M-x helm-mini
> Type in pattern to narrow candidates. Assume it narrows to a bunch of files from recentf.
> Mark some of theme.
> Delete file(s) from recentf
>
> Expected behavior
>
> marked files should no longer appear in recentf
>
> Actual behavior (from emacs-helm.sh if possible, see note at the bottom)
>
> files apper under recentf in helm-mini
>
> Steps to reproduce (recipe)
>
> as described above.
>
> NOTE: Works correctly if you don't narrow candidates with pattern, instead switch to recentf source in helm-mini with C-o, mark files there, then delete from recentf.

Could not reproduce, from main emacs and emacs-helm.sh.

-- 
Thierry

**Comment by vkz** [comment]
I just reproduced it with both
a) emacs-helm.sh
b) wipe .emacs.d completely, fresh .emacs.d/init.el with only package-install helm

hm, not sure what else I can try. You definitely narrowed to fewer files in `helm-recentf` then `Delete files from recentf` not `Delete files`?

Thanks

**Comment by thierryvolpiatto** [comment]
Vladilen Kozin <notifications@github.com> writes:

> I just reproduced it with both
> a) emacs-helm.sh
> b) wipe .emacs.d completely, fresh .emacs.d/init.el with only package-install helm
>
> hm, not sure what else I can try. You definitely narrowed to fewer
> files in helm-recentf then Delete files from recentf not Delete files?

I don't use recentf so I tried with a new recentf file, opened some
files, then narrow down to their names and delete them, then when I
restart helm the files are no more present.

Let me know if I missed something to reproduce.

Thanks.

--
Thierry

**Comment by xuchunyang** [comment]
> hm, not sure what else I can try. You definitely narrowed to fewer files in helm-recentf then Delete files from recentf not Delete files?

It looks like `(setq recentf-list (delq file recentf-list))` is the cause, it only works when the candidates is not narrowed because how `eq` works.

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

>     hm, not sure what else I can try. You definitely narrowed to fewer
>     files in helm-recentf then Delete files from recentf not Delete
>     files?
>
> It looks like (setq recentf-list (delq file recentf-list)) is the
> cause, it only works when the candidates is not narrowed because how
> eq works.

Thanks, make sense, still don't know why I couldn't reproduce though.

--
Thierry
