### ISSUE TITLE
Multiple persistent actions

### ISSUE THREAD

**Issue by student-sx** [emacs-helm/helm#1926]
I know that I can define multiple actions for a helm source and select the action via f1,f2,etc. 

However it seems to be only possible to have one persistent action, i.e. without leaving the helm session and that it works with follow mode. 

I think it would be a nice feature to allow multiple persistent actions such that the user can list and choose inside a running helm session the persistent action. That action is used for example in follow mode until the user selects another persistent action. 

There should be also a variable which configures if helm remembers the persistent action from the last session or resets it to the first persistent action on the list.

**Comment by thierryvolpiatto** [comment]
Sorry for late reply, I will look into this as soon as possible.

**Comment by dustinlacewell** [comment]
Darn, This never came to fruition.

**Comment by thierryvolpiatto** [comment]
The problem on this issue is how to decide which action is suitable to be a persistent action, few sources have more than one action suitable for persistence.

**Comment by dustinlacewell** [comment]
FWIW, I just overstepped this whole issue, and am using a key bound to a Hydra, allowing for as many actions, persistent or not, as needed.
