### ISSUE TITLE
[helm-xref] add `xref-find-references` to `xref-prompt-for-identifier`

### ISSUE THREAD

**Issue by MaskRay** [emacs-helm/helm#1928]
## Expected behavior

`xref-find-references` reads the identifier at point, instead of reading it from the minibuffer.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

`xref-find-references` prompts for the identifier to look up.

This is because `xref-find-references` is not in `xref-prompt-for-identifier`.

## Steps to reproduce (recipe)

Call `xref-find-references` at an identifier.

**Comment by thierryvolpiatto** [comment]
Please report helm-xref bugs to https://github.com/brotzeit/helm-xref


-- 
Thierry
