### ISSUE TITLE
a file hide and show between helm buffer show and hide

### ISSUE THREAD

**Issue by chenpoyang** [emacs-helm/helm#1929]
two files are open in emacs:
<pre>
emacs windows:
---------------
|fileone|filetwo|
---------------
</pre>
and several files in buffer, cursor in fileone, filetwo hide and show while switch file using helm(C-x b).
that means, after (C-x b), filetwo hide:
<pre>
emacs window with mini buffer
--------
|fileone |
--------
|helm    |<----choosing buffer file.(mini buffer)
--------
</pre>
after finush choosing buffer file. filetwo show:
<pre>
emacs windows:
---------------
|fileone|filetwo|
---------------
</pre>

is there any method to prevent the temporary hide of filetwo while (C-x b), and show:
<pre>
emacs window:
---------------
|fileone|filetwo|
---------------
|helm     buffer|
-----------------
</pre>

**Comment by thierryvolpiatto** [comment]
Peck Chen <notifications@github.com> writes:

> is there any method to prevent the temporary hide of filetwo while (C-x b), and show:
>
> | fileone | filetwo |
> | | |
>
> | helm buffer |

Not sure to understand, but isn't `helm-split-window-inside-p` what you
want ?

-- 
Thierry

**Comment by chenpoyang** [comment]
two files open in emacs, while open helm buffer, one file hide. after helm buffer close, the file show.
<a href="https://github.com/chenpoyang/config/tree/master/images">show the issues</a>

**Comment by chenpoyang** [comment]
it works:<a href="https://emacs.stackexchange.com/questions/14253/how-to-stop-helm-deleting-vertical-split-when-opening-helm-buffer">stop helm deleting vertical split when opening helm buffer</a>
<pre>
(setq helm-display-function #'pop-to-buffer)

(setq shackle-rules '(("\\`\\*helm.*?\\*\\'" :regexp t :align t :ratio 0.46)))
(shackle-mode)
</pre>

**Comment by thierryvolpiatto** [comment]
Peck Chen <notifications@github.com> writes:

> it works:stop helm deleting vertical split when opening helm buffer

Bad.

> (setq helm-display-function #'pop-to-buffer)

Bad.

You will find several helm variables to configure how helm split, you
have better time using them.

-- 
Thierry
