### ISSUE TITLE
`helm`'s :truncate-lines is not documented

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#1930]
Unless I'm mistaken of course :)

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Unless I'm mistaken of course :)

See `helm` doctring "Other keywords" section.

-- 
Thierry

**Comment by Ambrevar** [comment]
Indeed.  Hmmm... Any way to make this more apparant?  If not, forget it and feel free to close this issue.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Indeed. Hmmm... Any way to make this more apparant?

No unless making it a slot to be added in source.

-- 
Thierry
