### ISSUE TITLE
Add command+bindings to toggle-fullscreen

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#1931]
We have a few bindings to change window position or to enlarge/shrink the helm buffer, but no binding/command to go "fullscreen" (that is, only one window), a bit like `helm-top` does it.

I think it would be a very nice feature to have for many helm sessions which have very long lines.
I'm thinking of my current work with `helm-system-packages` in particular.

**Comment by thierryvolpiatto** [comment]
Not so easy, we have to allow persistent actions to split window when toggling to one window and to prevent them to split when coming back to a splitted view.

**Comment by Ambrevar** [comment]
Excellent, thanks for this!

As a side note: I did not receive notifications until you closed this issue.  So I could not really answer to your "fixed_wait_confirm" since I did not notice the changes.  Are my GitHub settings wrong?  If it's a GitHub limitation, then you should post a message on the thread to ask for testing.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Excellent, thanks for this!
>
> As a side note: I did not receive notifications until you closed this issue. So I could not really answer to your "fixed_wait_confirm" since I did not
> notice the changes. Are my GitHub settings wrong? 

Hmm, no I don't think so, we have had such issue one year ago or so,
sometimes for some reasons it takes a while before github sent
notifications by email.

> If it's a GitHub limitation, then you should post a message on the
> thread to ask for testing.

Which thread ? This one ?

Note I am sending this by email, not from the web interface.

-- 
Thierry

**Comment by Ambrevar** [comment]
I meant that when you add a label or you reference an issue from a commit, the people who subscribed to the issue don't receive a notification.  I think this is a limitation from GitHub.

In this case, you implemented the feature 6 days ago but I did not notice until now (when you closed the issue) because the fact that you only referenced/labeled this issue did not send me any notification.

To work around this, I suggest that everytime you fix an issue and wait for confirmation, you comment on the issue so that the original poster receives a notification.

(By the way sending by e-mail is fine.)

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I meant that when you add a label or you reference an issue from a
> commit, the people who subscribed to the issue don't receive a
> notification. I think this is a limitation from GitHub.
>
> In this case, you implemented the feature 6 days ago but I did not
> notice until now (when you closed the issue) because the fact that you
> only referenced/labeled this issue did not send me any notification.
>
> To work around this, I suggest that everytime you fix an issue and
> wait for confirmation, you comment on the issue so that the original
> poster receives a notification.

Indeed the label is not enough, I have to send a message, what I do
generally (like "Fixed, please confirm"), I forgot this time, sorry.

--
Thierry
