### ISSUE TITLE
helm-show-kill-ring disregards the selection

### ISSUE THREAD

**Issue by mgoldenbe** [emacs-helm/helm#1934]
When I select entries (with `C-<SPACE>`) in `helm-show-kill-ring` and press either `Enter` or `F1`, it disregards the selection and yanks the entry currently under cursor. I would expect it to apply the _yank_ action to all the selected entries... 

Versions: Emacs 24.5.1 (minimal configuration), helm-20150626.731

**Comment by thierryvolpiatto** [comment]
mgoldenbe <notifications@github.com> writes:

> When I select entries (with C-<SPACE>) in helm-show-kill-ring and press either Enter or F1, it disregards the selection and yanks the entry currently under cursor. I
> would expect it to apply the yank action to all the selected entries...

f3 does this.

-- 
Thierry

**Comment by mgoldenbe** [comment]
There is no such action. In which version did it appear?

**Comment by mgoldenbe** [comment]
F3 forms a string with new lines between the entries. It then yanks that string in a single invocation of yank. I would like to simply apply the default action (i.e. yank) to each of the selected entries. 

**Background**. In my case, I collect BibTeX keys in the kill ring and then I would like to yank them all (one at a time) to get a multi-paper citation. I have advised yank-insert to handle the yanking of BibTeX entries intelligently.

**Comment by thierryvolpiatto** [comment]
mgoldenbe <notifications@github.com> writes:

> F3 forms a string with new lines between the entries. It then yanks
> that string in a single invocation of yank. I would like to simply
> apply the default action (i.e.  yank) to each of the selected entries.

You mean sequentially ?  In this case which separator would be used to
separate entries, a space is ok for single line entries but not for
multilines entries.
With what you propose, no separator is used between entries, which may
be fine for your specific usage but not in most cases e.g. yanking two
functions with several lines.

--
Thierry

**Comment by mgoldenbe** [comment]
I propose to leave F3 as is, but to make F1 not ignore the selection (why would a user select something if he wants it to be ignored?), but rather apply its action to each candidate in the simplest possible manner. The work of the users who are used to the existing functionality will not be affected.

**Comment by thierryvolpiatto** [comment]
mgoldenbe <notifications@github.com> writes:

> I propose to leave F3 as is, but to make F1 not ignore the selection
> (why would a user select something if he wants it to be ignored?), but
> rather apply its action to each candidate in the simplest possible
> manner.

This is the point, what is "a simplest possible manner", do we yank like
in f3 with a newline as separator (in this case f3 and f1 could be
merged)? 
with a space ? with no separator ?

Note also that the last candidate used will be pushed to kill ring, it
it what we want or push the concated candidates as a single string on
top of ring (like f3 does)?

--
Thierry

**Comment by mgoldenbe** [comment]
How about a configurable separator, e.g. `(setq helm-show-kill-ring-separator "\n")` for F1? Then some people can choose to make it a space and I can make it an empty string for my purposes. You can also offer F3, whereby the user would be prompted for a separator for one-time usage.

**Comment by mgoldenbe** [comment]
I have advised `helm-kill-ring-action-yank` for my purposes, so if you feel that the proposed changed is not justified, that is fine with me.

Here is my code:

```
(defun my-kill-ring-action-yank(_orig_fun _string)
  "My version of helm-kill-ring-action-yank."
  (dolist (c (helm-marked-candidates) nil)
    (insert-for-yank c)))

(advice-add 'helm-kill-ring-action-yank
	    :around 'my-kill-ring-action-yank)
```

**Comment by thierryvolpiatto** [comment]
mgoldenbe <notifications@github.com> writes:

> I have advised helm-kill-ring-action-yank for my purposes, so if you feel that the proposed changed is not justified, that is fine with me.
>
> Here is my code:
>
> (defun my-kill-ring-action-yank(_orig_fun _string)
>   "My version of helm-kill-ring-action-yank."
>   (dolist (c (helm-marked-candidates) nil)
>     (insert-for-yank c)))
>
> (advice-add 'helm-kill-ring-action-yank
>             :around 'my-kill-ring-action-yank)

Thanks, but your code is not handling prefix arg and yank-pop, will not
work properly when yanking in active minibuffer, is not pushing to kill-ring etc...

-- 
Thierry

**Comment by mgoldenbe** [comment]
Ah, you are right. Then how about this:

```
(defun my-kill-ring-action-yank(orig_fun _string)
  "My version of helm-kill-ring-action-yank."
  (dolist (c (helm-marked-candidates) nil)
    (funcall orig_fun c)))

(advice-add 'helm-kill-ring-action-yank
	    :around 'my-kill-ring-action-yank)
```

**Comment by xuchunyang** [comment]
You can simply custom the user option `helm-kill-ring-actions`, the first one is the default action, i.e., can be run via RET or F1. For example, I have the following in my init.el for a long time (so long that I mistakenly thought it is the default):

```el
(add-to-list
 'helm-kill-ring-actions
 '("Yank(s)" .
   (lambda (_candidate)
     (helm-kill-ring-action
      (mapconcat #'identity (helm-marked-candidates) "\n")))))
```

**Comment by mgoldenbe** [comment]
Is there anything wrong with the advise? If not, how is your suggestion simpler?

**Comment by xuchunyang** [comment]
It's a user option, so it is supposed to be change by user.

**Comment by thierryvolpiatto** [comment]
I made the default action handling marked and I have removed the append action (f3).
The default separator is still "\n" but you can specify a different one with `C-u C-u`, you will be prompted for a separator.

**Comment by mgoldenbe** [comment]
It would be nice to make the separator a variable which the user can set
and not need to use C-u C-u each time...

On Thu, Dec 21, 2017 at 3:45 PM, Thierry Volpiatto <notifications@github.com

**Comment by thierryvolpiatto** [comment]
mgoldenbe <notifications@github.com> writes:

> It would be nice to make the separator a variable which the user can set
> and not need to use C-u C-u each time...

I didn't make it a variable yet because there is no way AFAIK from a
read-string to enter a newline as separator, and the newline is the
separator you will use in most cases.

-- 
Thierry

**Comment by mgoldenbe** [comment]
I did not mean `read-string`. I meant simply defining a customizable
variable:

`(defcustom helm-show-kill-ring-separator "\n")`

On Thu, Dec 21, 2017 at 9:55 PM, Thierry Volpiatto <notifications@github.com
> wrote:

>

**Comment by thierryvolpiatto** [comment]
mgoldenbe <notifications@github.com> writes:

> I did not mean `read-string`. I meant simply defining a customizable
> variable:
>
> `(defcustom helm-show-kill-ring-separator "\n")`

You didn't understand the point, with a variable, if you do 
(setq helm-show-kill-ring-separator ""), there is no way from
`read-string` to set the separator to "\n" (apart setq) so I prefer
hardcoding the default to "\n" until I find a solution.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Oh! I got it, to insert a newline in a `read-string` prompt, we have to use `C-q C-j` I was trying `C-q RET`, so yes now I can introduce your variable.
