### ISSUE TITLE
duplicate menu while pase php file wiile calling helm-semantic-or-imenu 

### ISSUE THREAD

**Issue by chenpoyang** [emacs-helm/helm#1935]
i have php file open, and use helm-semantic-or-imenu to lookup the function i define.
the menu is dumplicate like this:

<pre>
Pubilc Methods / index
Public Methods / db
Public Methods / hello
Public Methods / list
Public Methods / read
Public Methods / post
All Methods / index
All Methods / db
All Methods / hello
All Methods / list
All Methods / read
All Methods / post
</pre>
and no issue while open lisp file , C/C++ file etc. i don't know if it is a bug?

**Comment by thierryvolpiatto** [comment]
Peck Chen <notifications@github.com> writes:

> i have php file open, and use helm-semantic-or-imenu to lookup the function i define.
> the menu is dumplicate like this:
>
> Pubilc Methods / index
> Public Methods / db
> Public Methods / hello
> Public Methods / list
> Public Methods / read
> Public Methods / post
> All Methods / index
> All Methods / db
> All Methods / hello
> All Methods / list
> All Methods / read
> All Methods / post
> and no issue while open lisp file , C/C++ file etc. i don't know if it is a bug?

I guess it is the behavior of semantic to show this for PHP?

Helm is showing all as it is not really duplicates.

Note I don't know if semantic-mode is enabled, and I don't know many
other things as you didn't follow the report-bug template...

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Looks like it is the behavior of semantic to show "Public Methods" and "All Methods" even if the both share same objects, closing.
