### ISSUE TITLE
Helm error makes a lot of functions invalid

### ISSUE THREAD

**Issue by stardiviner** [emacs-helm/helm#1937]
## Steps to reproduce (recipe)

When I try to check out a function docstring with package `helpful`.
Then suddendly it popup an error in echo-area, then `helpful` display the buffer, but then when I try `[M-x]`, `[C-x b]`, `[M-:]`, none of them works.

## Backtraces if any (`M-x toggle-debug-on-error`)

I tried toggle-debug-on-error, but only got `Selecting deleted buffer` in echo-area.
Maybe my emacs respond my key hitting is a little of slow. Because I have many packages installed. Performance issue. Then some popup buffers like `which-key` or info or other else, they popup then closed, but Helm still treat them exist. For example, I hit `[C-h]`, found wrong then hit `[C-g]` to cancel, `which-key` popup not done. Then I hit `[C-c]` again. so Emacs always display message "Selecting deleted buffer". (This is just my guess)

## Describe versions of Helm, Emacs, operating system, etc.

I'm using MELPA version Helm. and Emacs from master branch source code compiled.

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):

no

**Comment by thierryvolpiatto** [comment]
stardiviner <notifications@github.com> writes:

> Expected behavior
>
> Steps to reproduce (recipe)
>
> When I try to check out a function docstring with package helpful.

It seems `helpful` is an external package not part of helm, you should
report bug to its author.

> Then suddendly it popup an error in echo-area,

Which error?

> then helpful display the buffer, but then when I try [M-x], [C-x b],
> [M-:], none of them works.
>
> Backtraces if any (M-x toggle-debug-on-error)
>
> I tried toggle-debug-on-error, but only got Selecting deleted buffer in echo-area.

The only piece of code I see in helpful source code that could trigger
helm is this (I had a quick look, perhaps there is something else)):

    (defun helpful--read-symbol (prompt predicate)
      (let ((sym-here (symbol-at-point)))
        (read (completing-read prompt obarray
                               predicate t nil nil
                               (when (funcall predicate sym-here)
                                 (symbol-name sym-here))))))

And this piece of code is working fine with helm-mode enabled.

> Describe versions of Helm, Emacs, operating system, etc.
>
> I'm using MELPA version Helm. and Emacs from master branch source code compiled.
>
> Are you using emacs-helm.sh to reproduce this bug (yes/no):

Please answer here, if no try anyway to load and use helpful from there
otherwise it is not possible to debug as there is too much packages that
may be involved.

> IMPORTANT NOTE
>
> Helm provides a script named emacs-helm.sh which runs Helm in a neutral
> environment: no other packages and only minimal settings.
>
> When possible, use it to reproduce your Helm issue to ensure no other package is
> interfering.
>
> To run it, simply switch to the directory where Helm is installed and call ./emacs-helm.sh.
>
> Thanks.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.*


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Just installed helpful and couldn't reproduce your bug here from emacs-25.3.

**Comment by stardiviner** [comment]
Thanks, normally it can't be triggered. I got it because of my quick hitting [C-g]. I got same error in Ivy too. So this must be a bug in `helpful`. I will report bug at there. Thanks for your help and provide a quick look. Really.
I will try to dig deeper.
