### ISSUE TITLE
`helm-find-files` responds slowly

### ISSUE THREAD

**Issue by twlz0ne** [emacs-helm/helm#1939]
![test-helm-find-files-1](https://user-images.githubusercontent.com/2653486/34418769-ba7e2f0a-ec3a-11e7-85fe-0fcc1279a1bf.png)

![test-helm-find-files-3](https://user-images.githubusercontent.com/2653486/34418777-c577e7de-ec3a-11e7-878e-2c77277da1cc.png)

### Expected Behavior

`helm-find-files` responds quickly.

### Actual Behavior

`helm-find-files` responds slowly.

### Steps to reproduce the behavior

```sh
$ mkdir helm-test-files && cd helm-test-files/
$ printf '%04d\n' {1..1000} | xargs touch
$ /path/to/emacs -nw -Q -l /path/to/test-helm-find-files.el
```

### Environment

- MacBook Pro (13-inch, Early 2011) 2.3 GHz Intel Core i5
- macOS 10.11.6
- Emacs 25/26/27
- helm-20171227.2150, helm-core-20171227.2227/
- test-helm-find-files.el

```elisp
;;; Date: 2017-12-28_23.12.21
;;; Usage:
;; $ mkdir helm-test-files && cd helm-test-files/
;; $ printf '%04d\n' {1..1000} | xargs touch
;; $ /path/to/emacs -nw -Q -l /path/to/test-helm-find-files.el
(toggle-debug-on-error)

(setq package-user-dir
      (concat
       user-emacs-directory
       (format "elpa--%s/%s" (file-name-base load-file-name) emacs-version)))

(setq package-archives
      '(("gnu"   . "https://elpa.gnu.org/packages/")
        ("melpa" . "https://melpa.org/packages/")))

(package-initialize)

(defun require-packages (&rest packages)
  (dolist (pkg packages)
    (unless (package-installed-p pkg)
      (package-refresh-contents)
      (package-install pkg))
    (require pkg)))

(require-packages
 'helm
 )

;; ------------------------------------------------------------------

(add-hook 'after-init-hook
          (lambda ()
            (switch-to-buffer "*scratch*")
              (insert "\
(let ((begin-time (current-time)))
  (defun after-helm-update (&rest arg)
    (message
     (format
      \"Completed in %.3fs, press `C-g' to invoke `profiler-report'\"
      (- (float-time (current-time)) (float-time begin-time)))))

  (advice-add 'helm-update :after 'after-helm-update)

  (profiler-start 'cpu)
  (helm-find-files-1 \"~/helm-test-files/\")
  (profiler-report)

  (advice-remove 'helm-update 'after-helm-update))")
              (require 'helm-config)
              (helm-mode 1)
              (setq helm-ff-skip-boring-files t)
              (setq-default helm-boring-file-regexp-list
                            (append '("\\.DS_Store$"
                                      "\\.svn$"
                                      "\\.svn-base$"
                                      "\\.swp$") helm-boring-file-regexp-list))
              (eval-buffer)))

(run-hooks 'after-init-hook)
;;; test-helm-find-files.el ends here
```

**Comment by thierryvolpiatto** [comment]
twlz0ne <notifications@github.com> writes:

> Actual Behavior
>
> helm-find-files responds slowly.

Please start from emacs-helm.sh.

Here it is fast enough:

     (length (directory-files "/usr/bin"))
     =>2333
     (with-helm-time-after-update
         (helm-find-files-1 "/usr/bin/"))
     =>0.2508530616760254

IOW helm-find-files open in 0.25 seconds on a directory containing 2333
files.

-- 
Thierry

**Comment by twlz0ne** [comment]
@thierryvolpiatto thanks for your reply.

Now I know that there is `with-helm-time-after-update`，it does consume less time. I also find that `hlem-update` only executes once in this macro, but four times in my case:

```elisp
(let ((begin-time (current-time)))
  (defun my/helm-after-update-hook ()
    (message
     "Completed in %.3fs, press `C-g' to exit\""
     (- (float-time (current-time)) (float-time begin-time))))

  (add-hook 'helm-after-update-hook 'my/helm-after-update-hook)
  (helm-find-files-1 "~/helm-test-files/")
  (remove-hook 'helm-after-update-hook 'my/helm-after-update-hook))
```

In buffer `*Messages*`:

```
Completed in 1.354s, press ‘C-g’ to exit"
Completed in 1.357s, press ‘C-g’ to exit"
Completed in 2.871s, press ‘C-g’ to exit"
Completed in 2.874s, press ‘C-g’ to exit"
```

The time consuming close to the actual experience when i press <kbd>M-x helm-find-files RET ~/helm-find-files RET</kbd>.
 
At the same time, I found a strange phenomenon, if i visit `(helm-find-files-1 "/usr/bin/")` in my case, the `helm-update` alson executes once!

Test environment：

- MacBook Pro (13-inch, Early 2011) 2.3 GHz Intel Core i5 -- macOS 10.11.6
- Bandwagonhost Basic VPS 1x Intel Xeon -- Ubuntu 15.10 x86_64

**Comment by xuchunyang** [comment]
Turn on `helm-ff-skip-boring-files` makes `helm-find-files-1` 3x slower according the following test (the value of `helm-boring-file-regexp-list` is unchanged by me)

```
(cd "/usr/share/man/man3/")
     => "/usr/share/man/man3/"

(length (directory-files "./"))
     => 10188

(with-helm-time-after-update
 (helm-find-files-1 "./"))
     => 0.9875431060791016

helm-ff-skip-boring-files
     => nil

(setq helm-ff-skip-boring-files t)
     => t

(with-helm-time-after-update
 (helm-find-files-1 "./"))
     => 2.988765001296997
```

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

> Turn on helm-ff-skip-boring-files makes helm-find-files-1 3x slower

Yes this is a known problem that have been already discussed and I
didn't find yet a good solution.

When you turn on helm-ff-skip-boring-files, the filter function check
each file if it match one of helm-boring-file-regexp-list member by
looping in this list (See `helm-ff-boring-file-p` and
`helm-ff-filter-candidate-one-by-one`).

Probably filtering should be done at source (`directory-files`) with one
big regexp (`regexp-opt`), I will look into this ASAP.

Thanks.

--
Thierry

**Comment by thierryvolpiatto** [comment]
Should be faster now when `helm-ff-skip-boring-files` is enabled.
Let me know.

**Comment by thierryvolpiatto** [comment]
Perhaps I should also fix `helm-boring-file-regexp-list` with a set function so that it update its value when user change value of `completion-ignored-extensions`.

**Comment by twlz0ne** [comment]
There are problems:

1. `helm-ff-skip-boring-files`
2. tildle (`~`) path

`with-helm-time-after-update` does not trigger the problem 2.

Here's my latest test code:

```elisp
(defun test-helm-find-files (path)
  (setq abs-path (expand-file-name path))
  (setq begin-time (current-time))
  (setq time-elapsed nil)

  (defun after-helm-update (&rest arg)
    (setq time-elapsed (- (float-time (current-time)) (float-time begin-time))))

  (defun after-helm-check-new-input (&rest arg)
    (when (and helm-input (string= abs-path helm-input)
               ;; quit when "~/path/" changed to "$HOME/path/"
               (keyboard-quit))))

  (advice-add 'helm-update :after 'after-helm-update)
  (advice-add 'helm-check-new-input :after 'after-helm-check-new-input)

  (helm-find-files-1 path)

  (advice-remove 'helm-check-new-input 'after-helm-check-new-input)
  (advice-remove 'helm-update 'after-helm-update)

  (message "%fs" time-elapsed))
  
;; -----------------------------------------------------------------------------

(setq helm-ff-skip-boring-files t)
(test-helm-find-files "~/helm-test-files/")
(test-helm-find-files (concat (getenv "HOME") "/helm-test-files/"))
;; => 3.725301s
;; => 1.095013s

(setq helm-ff-skip-boring-files nil)
(test-helm-find-files "~/helm-test-files/")
(test-helm-find-files (concat (getenv "HOME") "/helm-test-files/"))
;; => 0.874272s
;; => 0.203923s
```

**Comment by thierryvolpiatto** [comment]
twlz0ne <notifications@github.com> writes:

> There are problems:
>
>  1. helm-ff-skip-boring-files
>  2. tildle (~) path
>
> with-helm-time-after-update does not trigger the problem 2.

Can you elaborate on what the problem 2 is ?


-- 
Thierry

**Comment by twlz0ne** [comment]
It seems that `helm-update` is repeated multiple times when expanding `~/path/` to `$HOME/path/`:

```
Minibufer:
+--------------------------------------+
| Find files or URL: ~/path/           |
+--------------------------------------+
                        |
                        | auto expand
Minibufer:              v
+--------------------------------------+
| Find files or URL: /Users/john/path/ |
+--------------------------------------+
                        |
                        v
                        (helm-update)
```

You can check the elapsed time by `with-helm-time-after-update` or my function `test-helm-find-files`:

```elisp
(test-helm-find-files "~/helm-test-files")
(test-helm-find-files (concat (getenv "HOME")"~/helm-test-files"))
```

Sometimes the result of `with-helm-time-after-update` is not obvious, perhaps because it blocks the helm window.

**Comment by thierryvolpiatto** [comment]
twlz0ne <notifications@github.com> writes:

> It seems that helm-update is repeated multiple times when expanding
> ~/path/ to $HOME/path/:

You are right, this is because helm-find-files-1 had to resolve the
abbreviated path, but helm-find-files was passing an expanded path
though so that helm-find-files-1 was called only once when calling
helm-find-files. This is fixed now.

Thanks.


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Let me know if commit 7d409c3 speed up things (it does here).

Thanks.

**Comment by twlz0ne** [comment]
I ran the test case 2*2*2*10 times, looks good:

```
---------- helm-ff-skip-boring-files: t ----------

---------- test-helm-find-files ------------
---------- tilde path    ---------- abs path
1.170824s                0.216788s
0.252416s                0.207559s
0.523519s                0.199659s
0.222499s                0.208972s
0.219739s                0.223185s
0.210761s                0.219708s
0.204793s                0.206167s
0.207042s                0.206797s
0.214907s                0.212732s
0.199888s                0.209409s

---------- with-helm-time-after-update -----
---------- tilde path    ---------- abs path
0.5402209758758545       0.219588041305542
0.3060309886932373       0.20665812492370605
0.21102404594421387      0.2197279930114746
0.2222590446472168       0.22104096412658691
0.20591115951538086      0.20322203636169434
0.20905303955078125      0.2213881015777588
0.20642805099487305      0.2037050724029541
0.20421385765075684      0.23666906356811523
0.21342015266418457      0.2147960662841797
0.20875096321105957      0.20853018760681152


---------- helm-ff-skip-boring-files: nil ----------

---------- test-helm-find-files ------------
---------- tilde path    ---------- abs path
0.205116s                0.192909s
0.163355s                0.178346s
0.205504s                0.189230s
0.176239s                0.168304s
0.225796s                0.222723s
0.175254s                0.170961s
0.192809s                0.208375s
0.163416s                0.168702s
0.199099s                0.196743s
0.169077s                0.173579s

---------- with-helm-time-after-update -----
---------- tilde path    ---------- abs path
0.20480990409851074      0.20491385459899902
0.16686391830444336      0.1731419563293457
0.27303099632263184      0.1945359706878662
0.19437193870544434      0.17540502548217773
0.20816898345947266      0.20311689376831055
0.18001508712768555      0.16961288452148438
0.21509504318237305      0.2030620574951172
0.5678269863128662       0.17865681648254395
0.24296307563781738      0.19345307350158691
0.18035888671875         0.16851186752319336
```

The full script is here https://gist.github.com/twlz0ne/b01ad4f4f726d9f98b7245d4a6abcfac

**Comment by thierryvolpiatto** [comment]
twlz0ne <notifications@github.com> writes:

> I ran the test case 222*10 times, looks good:

Great, thanks!

-- 
Thierry

**Comment by twlz0ne** [comment]
@thierryvolpiatto

There is still a little delay in the actual operation, Especially for the first time. I also tested [ivy](https://github.com/abo-abo/swiper) in the same environment, helm still have room for improvement:

```
[0/10] 0.203100
[1/10] 0.020301
[2/10] 0.066867
[3/10] 0.025738
[4/10] 0.061565
[5/10] 0.051574
[6/10] 0.023039
[7/10] 0.054084
[8/10] 0.019610
[9/10] 0.050505
```

Full script: https://gist.github.com/twlz0ne/9eb9672b10c469230dd85aa987f3d565

**Comment by thierryvolpiatto** [comment]
twlz0ne <notifications@github.com> writes:

> @thierryvolpiatto
>
> There is still a little delay in the actual operation, Especially for
> the first time. I also tested ivy in the same environment, helm still
> have room for improvement:

Your tests are not meaningful, the conditions are not the same.

--
Thierry
