### ISSUE TITLE
what's the helm facility of search in current buffer and modify it in place

### ISSUE THREAD

**Issue by introom** [emacs-helm/helm#1941]
Hi,

I feel this functionality should exist in helm, but haven't found it.

Search in a buffer, and modify the matched text in place.

What's the corresponding helm interface?

Helm-occur indeed shows the result, but doesn't support modification.

**Comment by xuchunyang** [comment]
> Helm-occur indeed shows the result, but doesn't support modification.

You can type `C-x C-s` (`helm-moccur-run-save-buffer`) which is defined on `helm-moccur-map`, then use wgrep.el to edit the result. You can learn more about this by type `C-h m` (`helm-help`) while running `helm-occur`.

For helm-grep, use the same keybindings `C-x C-s` (`helm-grep-run-save-buffer`).

**Comment by introom** [comment]
cool. thanks.
