### ISSUE TITLE
completing-read in helm mode does not remember old history for defvar-local

### ISSUE THREAD

**Issue by HuStmpHrrr** [emacs-helm/helm#1942]
## Expected behavior
completing-read should remember all the old history for defvar-local.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
it does not.

## Steps to reproduce (recipe)
1. run following code
```
(defvar-local history1 nil)
(defun test-func1 (arg)
  (interactive
   (list (completing-read "func1 :" nil nil nil
                          ""
                          'history1)))
  '())

(defvar history2 nil)
(defun test-func2 (arg)
  (interactive
   (list (completing-read "func2 :" nil nil nil
                          ""
                          'history2
                          )))
  '())
```
2. turn on helm mode.
3. calling `test-func1` and `test-func2` multiple times. 
4. we should see that history of `test-func1` does not accumulate like one of `test-func2` does.

## Backtraces if any (`M-x toggle-debug-on-error`)
there isn't explicit error.

## Describe versions of Helm, Emacs, operating system, etc.
helm version: 20180101.14
emacs verison: 25.3.1

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):
yes

**Comment by thierryvolpiatto** [comment]
Jason Hu <notifications@github.com> writes:

> Expected behavior
>
> completing-read should remember all the old history for defvar-local.

No, it doesn't even with helm-mode disabled, you can also have a look at
your history file after restarting emacs, you will see that the history1
is recorded but not set like history2.
This make sense, a local variable as history var for completing-read
have no utility, it should be global.
When you specify a symbol as history argument for completing-read you
can be sure that this history will belong always to this same function
so no need to make it local.

-- 
Thierry
