### ISSUE TITLE
possible to hide some results from a command invoked by helm

### ISSUE THREAD

**Issue by introom** [emacs-helm/helm#1943]
for example, the result of find-library is completed by helm.  however, its results contains entries whose name ends in ".elc", and I'd like to hide them.

**Comment by thierryvolpiatto** [comment]
Shiyao.Ma <notifications@github.com> writes:

> for example, the result of find-library is completed by helm. however,
> its results contains entries whose name ends in ".elc", and I'd like
> to hide them.

No, this is a helmized vanilla command, the results are the same as what
you have without helm.

--
Thierry

**Comment by introom** [comment]
helm buffer has boring buffers, and helm find file has boring file list.  however, they are based on per-helm command.

i wonder if there is, *globally*, a boring list that will be filtered through the helm interface.

**Comment by thierryvolpiatto** [comment]
Shiyao.Ma <notifications@github.com> writes:

> helm buffer has boring buffers, and helm find file has boring file
> list. however, they are based on per-helm command.
>
> i wonder if there is, globally, a boring list that will be filtered
> through the helm interface.

No, helm provides completion on to many different and unrelated things.

--
Thierry
