### ISSUE TITLE
helm-M-x with several windows split

### ISSUE THREAD

**Issue by tomasorti** [emacs-helm/helm#1944]
Hi.
I have a doubt regarding this behavior of helm.

If an Emacs frame is split in two or more windows and the command `helm-M-x` is used, only the window that has the cursor active is kept. The other window (or windows) are hidden to show the helm buffer.

Can that be changed or it is just the way helm works?

Best Regards.

**Comment by thierryvolpiatto** [comment]
nephewtom <notifications@github.com> writes:

> Hi.
> I have a doubt regarding this behavior of helm.
>
> If an Emacs frame is split in two or more windows and the command
> helm-M-x is used, only the window that has the cursor active is
> kept. The other window (or windows) are hidden to show the helm
> buffer.
>
> Can that be changed or it is just the way helm works?

Of course this can be changed, apparently you are using
`helm-always-two-windows`, perhaps what you want is
`helm-split-window-inside-p` ? Or even better display the helm-buffer in a
separate frame ?  For this customize `helm-commands-using-frame`.

--
Thierry

**Comment by thierryvolpiatto** [comment]
![capture d ecran_2018-01-15_13-32-03](https://user-images.githubusercontent.com/1533939/34942633-a2a27352-f9f8-11e7-972f-b38798467024.png)

**Comment by thierryvolpiatto** [comment]
![capture d ecran_2018-01-15_13-37-53](https://user-images.githubusercontent.com/1533939/34942833-5a5c0e54-f9f9-11e7-8630-55f9b9ab8f9d.png)

**Comment by thierryvolpiatto** [comment]
Otherwise the default behavior is to display helm-buffer in the next-window below or at right of your current buffer:

![capture d ecran_2018-01-15_13-41-35](https://user-images.githubusercontent.com/1533939/34942994-01e36370-f9fa-11e7-8d33-620f77b0e61d.png)

**Comment by tomasorti** [comment]
Oh, thanks for you quick reply!
It seems I inadvertently had `helm-split-window-in-side-p` set to nil in my config.

Anyway, I will have a look at those customize options.
Best regards!
