### ISSUE TITLE
org files are not listed in helm-recentf

### ISSUE THREAD

**Issue by takaxp** [emacs-helm/helm#1947]
## Expected behavior

org files shall be listed in helm-recentf buffer if `recentf-list` has such files. But if you use the source codes in HEAD, they will not be listed.

## Steps to reproduce (recipe)

1. visit an org file (or create hoge.or / hoge.o)
2. check `recentf-list` value if the org file is listed
3. call helm-recentf
4. check the org file is NOT listed in helm-recentf buffer

## Describe versions of Helm, Emacs, operating system, etc.

- Emacs 26.0.90 and 25.3
- helm-20180114.2330 (from MELPA)
- MacOS X 10.11.6

Additional information:
If you use helm 2.8.7, this will not happen. Also if you remove "\\\\.o" from `helm-boring-file-regexp-list`, this will not happen too. I doubt that there is something wrong in `helm-files.el`.

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):

no

**Comment by thierryvolpiatto** [comment]
Takaaki ISHIKAWA <notifications@github.com> writes:

> Expected behavior
>
> org files shall be listed in helm-recentf buffer if recentf-list has
> such files. But if you use the source codes in HEAD, they will not be
> listed.

I don't see why they would not be listed.

>
> Steps to reproduce (recipe)
>
>  1. visit an org file (or create hoge.or / hoge.o)
>  2. check recentf-list value if the org file is listed
>  3. call helm-recentf
>  4. check the org file is NOT listed

Of course, hoge.o and hoge.or are not org files and are hidden by
helm-boring-file-regexp-list.

Use the proper extension for org files which is "*.org" and not "*.o" or
whatever or if you really want to use incorrect file extensions, modify
accordingly boring regexp list.

--
Thierry

**Comment by takaxp** [comment]
Hi Thierry,

When I tried other files can be listed in helm-recentf buffer, other extensions are not listed in helm-recentf buffer too, such as "hoge.al" and "hoge.alg". So this issue is not limited to *.org files and it's definition of file extensions.

I walked through the commits between version 2.8.7 and HEAD. Then I found some optimisations were applied to `helm-boring-file-regexp-list` in helm-files.el. I can see some changes on the algorithm for regexp of word ending by `$`.

Note - I confirmed other users in Japanese community fece this issue too.

Best,
Takaaki

**Comment by thierryvolpiatto** [comment]
Indeed I could reproduce, should be fixed now let me know.
If you modify helm-boring-regexp-list be sure to use customize and not setq.

Thanks.

**Comment by takaxp** [comment]
Hi Thierry,

Many thanks to you for the quick reactions.
I just confirmed the latest codes works fine for me and a user(@niku) who faced the same issue.

Best regards,
Takaaki

**Comment by niku** [comment]
Yeah, I confirm it.
Thank you for fixing quickly 👍

**Comment by OskarSigvardsson** [comment]
I noticed this problem too (not being able to see org files in recentf), so I searched around and found this thread. I just updated helm to fix it, and now it wont even open helm-mini, it gives the message "Symbol's value as variable is void: helm-boring-file-regexp-list".

**Comment by takaxp** [comment]
Hi OskarSigvardsson,

It was actually happened in my environment too. So I just re-installed helm and helm-core. Finally, the error message was disappeared.

Best,
Takaaki

**Comment by OskarSigvardsson** [comment]
Ok, I'll try that. I tried running `emacs -Q` and installing only helm and nothing else, and it happened then as well.

**Comment by thierryvolpiatto** [comment]
OskarSigvardsson <notifications@github.com> writes:

> I noticed this problem too (not being able to see org files in
> recentf), so I searched around and found this thread. I just updated
> helm to fix it, and now it wont even open helm-mini, it gives the
> message "Symbol's value as variable is void:
> helm-boring-file-regexp-list".

`helm-boring-file-regexp-list` is now part of helm-core, so if you don't
reinstall helm-core as well helm won't find the variable.

--
Thierry

**Comment by OskarSigvardsson** [comment]
Ah! I see. Thank you so much for your help!
