### ISSUE TITLE
How to hide persistent-help ?

### ISSUE THREAD

**Issue by honmaple** [emacs-helm/helm#1948]
![_2018-01-17_10-45-43](https://user-images.githubusercontent.com/12235570/35023319-11bbc734-fb75-11e7-88e2-c3f9582351cd.png)

After latest update, the second place appear but it's disappeared before. How can I hide it ?

version:
```
helm-20180114.2330
helm-core-20180116.425
```

**Comment by thierryvolpiatto** [comment]
Please use the template to fill up bugs and please use emacs-helm.sh.
Indeed you have the header-line info showing up in  minibuffer when header-line is used as minibuffer, what's the problem?

**Comment by thierryvolpiatto** [comment]
honmaple <notifications@github.com> writes:

> _2018-01
>
> After latest update, the second place appear but it's disappeared before. How can I hide it ?

(setq helm-display-header-line nil)


-- 
Thierry
