### ISSUE TITLE
Sticky Helm frame

### ISSUE THREAD

**Issue by tuhdo** [emacs-helm/helm#1951]
I frequently display `grep/ag` results in a large frame, side by side to my main Emacs frame. However, I constantly have to use the OS's window manager shortcuts to move Helm frame to the left of my screen, to align both frames side by side.

It would be nice if I can have a command to "stick" Helm frame to the current position on my screen. That means, from then on, whenever I run a Helm command, the frame appears at that fixed position until I run the command to toggle it off and return back to the original behavior.

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> I frequently display grep/ag results in a large frame, side by side to
> my main Emacs frame. However, I constantly have to use the OS's window
> manager shortcuts to move Helm frame to the left of my screen, to
> align both frames side by side.
>
> It would be nice if I can have a command to "stick" Helm frame to the
> current position on my screen. That means, from then on, whenever I
> run a Helm command, the frame appears at that fixed position until I
> run the command to toggle it off and return back to the original
> behavior.

1) Frame popup at point.

2) Move frame where needed with mouse or whatever.

3) Quit or exit helm.

4) Restart helm, frame popup at point.

5) Use "C-c &" (we can discuss about this particular binding) to move
frame where it was in 2)

Is that ok?

--
Thierry

**Comment by tuhdo** [comment]
Well, it would be better if I don't have to exit Helm, but save its position. The next time invoking Helm, it simply appears where it was last time. 

This is the same as you suggested, with a slight change in saving order. About the key binding, how about `C-t`? It is used for Helm window, but since this is Helm frame, it could be reused.

**Comment by tuhdo** [comment]
It should be saved, not be restored. You can think of it as `helm-resume` but for frame. Yes, something like `helm-frame-resume`.

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> Well, it would be better if I don't have to exit Helm, but save its
> position. The next time invoking Helm,

That's mean that you exited/quitted helm in first place ;-)

> it simply appears where it was last time.

It is what is does now, have a try.

--
Thierry

**Comment by tuhdo** [comment]
> That's mean that you exited/quitted helm in first place ;-)

But when quitting, Helm should remember the frame position and the next command I run, it should restore to the previous position. Currently, when I run a Helm command, it appears at default position, then I have to press key to restore the old position again. This does not improve from my original use case, where I must use the OS key to move frame to the left/right to make it side by side.

I think, you can add this feature for `helm-resume`. Not only the frame position is restored, but the previous buffer content too. 

You can also keep the current implemented key binding, so it covers all cases. I find it useful for arbitrary positions.



> It is what is does now, have a try.

When I first try it, this error occurs:

> helm-restore-last-frame-position: Wrong type argument: integerp, nil [2 times]

The next time, it runs well, so I cannot give you a trace.

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

>     That's mean that you exited/quitted helm in first place ;-)
>
> But when quitting, Helm should remember the frame position 

It does.

> and the next command I run, it should restore to the previous
> position.

Agreed, but it is not what you asked initially ;-)

> Currently, when I run a Helm command, it appears at default position,
> then I have to press key to restore the old position again.

It is what you asked initially (or I misunderstand what you wanted?)

> This does not improve from my original use case, where I must use the
> OS key to move frame to the left/right to make it side by side.
>
> I think, you can add this feature for helm-resume.

Yes perhaps it is the best to do.

>     It is what is does now, have a try.
>
> When I first try it, this error occurs:
>
>     helm-restore-last-frame-position: Wrong type argument: integerp, nil [2 times]
>
> The next time, it runs well, so I cannot give you a trace.

No problem I already know what happened, will fix soon.

Thanks.

--
Thierry

**Comment by thierryvolpiatto** [comment]
Now resuming is restoring last frame position.

**Comment by thierryvolpiatto** [comment]
"C-c &" have been removed.
