### ISSUE TITLE
pop-up frame should be given input focus

### ISSUE THREAD

**Issue by hexmode** [emacs-helm/helm#1952]
`helm-display-buffer-pupup-frame` is great, but the old frame still has focus.  `select-frame-set-input-focus` should be used to give the new frame input focus.

**Comment by tumashu** [comment]
In my opinion, this feature  helm should use child-frame which is a feature of emacs 26,  this mean
use main frame's minibuffer as input minibuffer, while show results in a child-frame of main frame.

**Comment by tumashu** [comment]
I am testing  child-frame as company cand menu, helm's this feature has similar need: https://github.com/tumashu/company-childframe

**Comment by thierryvolpiatto** [comment]
tumashu <notifications@github.com> writes:

> In my opinion, this feature helm should use child-frame which is a feature of emacs 26, this mean
> use main frame's minibuffer as input minibuffer, while show results in a child-frame of main frame.

We have to support emacs-25.3...

-- 
Thierry
