### ISSUE TITLE
helm-find-files async build file list

### ISSUE THREAD

**Issue by CeleritasCelery** [emacs-helm/helm#1954]
I noticed that helm takes advantage of `emacs-async` to copy/move files asynchronously. Another great use of background processes would be in fetching the list of files. There are two use cases where this would be really useful. 
1) When using `helm-find-files` in large directories the UI is blocked for several seconds while the file list is retrieved and displayed. Even if all the user wants to do it move up a directory they still have to wait. 
2) When using TRAMP with `helm-find-files` The UI is blocked once the hostname is completed (e.g. once the user types `/ssh:hostname:`) and TRAMP connects. This blocks the user from pasting a path into the helm buffer until after the candidates are fetched. 

If files and directories were fetched asynchronously, it would allow the user to quickly execute actions when they don't actually care about the file list. If the user wanted to see the file list, they could wait. 

I do not know the scope of this change, and it seems like a worthwhile addition only if it could be done easily. If it is a low impact change I could try and implement it.

**Comment by thierryvolpiatto** [comment]
Troy Hinckley <notifications@github.com> writes:

> I do not know the scope of this change, and it seems like a worthwhile
> addition only if it could be done easily.

It isn't easy, I already tried.
You can have something working more or less easily, but there is dozen
or corner cases where it becomes complicated to make it working.
Also it is not much faster.
The implementation I did was with an async source using ls (also it is
not portable). Of course other approches are possible...

See:

https://gist.github.com/thierryvolpiatto/a0e1121cd9340ac9fcf86865e974c019

Not fully working, but perhaps a good start.

-- 
Thierry

**Comment by CeleritasCelery** [comment]
> It isn't easy, I already tried.

Why am I not surprised 😉 

> Also it is not much faster.

speed is not so much a concern as blocking the UI





> I did was with an async source using ls (also it is not portable).

Does `emacs-async` allow you to make a sub process out of elisp? Though I am sure you already tried that.

**Comment by thierryvolpiatto** [comment]
Troy Hinckley <notifications@github.com> writes:

> speed is not so much a concern as blocking the UI

You can now disable the preselection when going up one level with
`helm-ff-up-one-level-preselect` and reduce the
`helm-ff-candidate-number-limit` value.

It have nothing to do with computing candidates async but would help
navigating across large directories, at the cost of loosing preselection
and having only few candidates displayed.

> Does emacs-async allow you to make a sub process out of elisp?

It does a sub process but there is no filter process where we can handle
the output, so no it is not really helpful.

-- 
Thierry

**Comment by CeleritasCelery** [comment]
> You can now disable the preselection when going up one level with
`helm-ff-up-one-level-preselect` and reduce the
`helm-ff-candidate-number-limit` value.

your suggestions solutions works great for me! Thanks
