### ISSUE TITLE
helm prevents operation of c-xref-project-new (or c-xref-project-new does not to comply to elisp standard that helm requires)

### ISSUE THREAD

**Issue by thoni56** [emacs-helm/helm#1955]
## Expected behavior
`helm` and `c-xrefactory`should not interfere with each other

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

`Wrong type argument : stringp, nil` when executing `c-xref-project-new`

## Steps to reproduce (recipe)

  - Install [c-xrefactory](https://github.com/thoni56/c-xrefactory) (`el-get-install` `c-xrefactory`)
  - Run `c-xref-project-new`either from prompt or from C-xref menu

## Backtraces if any (`M-x toggle-debug-on-error`)

[backtrace.txt](https://github.com/emacs-helm/helm/files/1664778/backtrace.txt)

## Describe versions of Helm, Emacs, operating system, etc.

Emacs 25.3.1 on Darwin 13.4.0, MacOS 10.13.2. Helm version is unknown (don't know how to find it), but installed using `el-get`.

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):

No.

I'm not sure which package is "at fault", so I need help in figuring that out. Thanks.

## IMPORTANT NOTE

Helm provides a script named `emacs-helm.sh` which runs Helm in a neutral
environment: no other packages and only minimal settings.

When possible, use it to reproduce your Helm issue to ensure no other package is
interfering.

To run it, simply switch to the directory where Helm is installed and call `./emacs-helm.sh`.

Thanks.

**Comment by thierryvolpiatto** [comment]
This is not the helm fault, according the backtrace, your package is
using a `completing-read` with a function as collection which itself
handle filenames without binding `minibuffer-completing-file-name` and
this function is apparently in some cases returning an empty input ("").

So your c-xref package can fix the problem by either binding
`minibuffer-completing-file-name` or better using a `read-file-name` to
get completion on its files.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Thomas Nilefalk <notifications@github.com> writes:

> If someone could help out with a PR for this in c-xrefactory I'd
> appreciate this immensely. There are only six occurrences of
> completing-readin the project.

I don't use this package and I haven't installed it, just downloaded the
code and read it so I don't know if this patch fix your problem, have a
try.

Here is the patch fully not tested:

diff --git a/env/emacs/c-xref.el b/env/emacs/c-xref.el
index 3be818f..d8fb362 100644
--- a/env/emacs/c-xref.el
+++ b/env/emacs/c-xref.el
@@ -4888,13 +4888,15 @@ the part of .c-xrefrc file describing this project will be deleted.
 ))
 
 (defun c-xref-read-jpath-from-minibuffer (prompt default)
-  (let ((res))
+  (let ((res)
+        (minibuffer-completing-file-name t))
     (setq res (completing-read prompt 'c-xref-java-path-completionfun nil nil default))
     res
 ))
 
 (defun c-xref-read-jpath-from-minibuffer-xx (prompt)
-  (let ((res) (ini))
+  (let ((minibuffer-completing-file-name t)
+        res ini)
     (if (eq c-xref-platform 'windows)
         (setq ini "c:\\")
       (setq ini "/")

--
Thierry

**Comment by thoni56** [comment]
Thanks for trying to help! But that did not make any difference. Can you explain what the code was aimed to do? Then I perhaps have a chance at some progress here.

As far as I understand elisp, it is adding a local variable named `minibuffer-completing-file-name` and setting it to true. Where is that variable used? Is `completing-read` picking that up somehow? I could google anything about such a variable, and the docs on `completing-read` that I found does not mention it either. Of course, I could be completely off here.

**Comment by thierryvolpiatto** [comment]
Thomas Nilefalk <notifications@github.com> writes:

> Thanks for trying to help! But that did not make any difference.

So you have to fix your `c-xref-java-path-completionfun` function, but I
guess this have to be reimplemented from start, as I already said, using
a completing-read to provide completion on filenames is not the thing to
do, you have better time using read-file-name.

> Can you explain what the code was aimed to do?

minibuffer-completing-file-name is just a flag to say to completion
functions we are trying to complete filenames (helm among other emacs
functions is using it).

-- 
Thierry
