### ISSUE TITLE
[Feature] When a different Helm command runs, frame position and size should be reset

### ISSUE THREAD

**Issue by tuhdo** [emacs-helm/helm#1956]
Currently, when reusing frame for a new Helm command, the previous size is kept. The previous size is changed when I move Helm frame around. This is a problem because the Helm frame can be as large as the original frame, and can consume half of the screen.

My solution is that when a Helm command is different than previous command, size and position should be reset to the default. When a Helm command is not different, e.g. I run the same `helm-do-grep` command, it should appear using previous frame parameters.

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> Currently, when reusing frame for a new Helm command, the previous
> size is kept. The previous size is changed when I move Helm frame
> around. This is a problem because the Helm frame can be as large as
> the original frame, and can consume half of the screen.

Now when you resume you will have the same frame but when you start a
new command the frame is resized.

> My solution is that when a Helm command is different than previous
> command, size and position should be reset to the default. When a Helm
> command is not different, e.g. I run the same helm-do-grep command, it
> should appear using previous frame parameters.

No if you want to do a grep command with same frame as before, just
resume it, if you start a new helm command, grep or other helm will
reinitialize frame.

--
Thierry

**Comment by tuhdo** [comment]
The default parameters should be restored before displaying the frame. Currently, the frame appears big for an instant before returning to the original size.

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> The default parameters should be restored before displaying the
> frame. Currently, the frame appears big for an instant before
> returning to the original size.

Because you use helm-display-buffer-reuse-frame.

--
Thierry

**Comment by tuhdo** [comment]
> Because you use helm-display-buffer-reuse-frame.

You can set the frame size while the frame is invisible and it appears that way when visible. All frame parameters should be set before visible.

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

>     Because you use helm-display-buffer-reuse-frame.
>    
> You can set the frame size while the frame is invisible and it appears
> that way when visible. All frame parameters should be set before
> visible.

In theory, but in practice no, for example in our case if you do so you
lose minibuffer (tested on 25.3 and 27.0.50).
Perhaps I am missing something, dunno.
Will see if I can find a solution to this problem.

It is a shame that emacs-27 is so slow to display frames otherwise you
could use helm-display-buffer-reuse-frame == nil (and I could drop the
code that reuse frame which is a pain), hope it will be fixed
some days.

-- 
Thierry
