### ISSUE TITLE
Question: Can we mark multiple candidates with the mouse?

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#1957]
I could be missing something, but I cannot find how to do it :/
With `(setq helm-allow-mouse t)`, I can only select one candidate.

**Comment by Ambrevar** [comment]
As a reminder, I think the related issue is https://github.com/emacs-helm/helm/issues/1746.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I could be missing something, but I cannot find how to do it :/
> With (setq helm-allow-mouse t), I can only select one candidate.

You can have only one selection, with or without mouse, I guess what you want to
know is that if you can mark many candidates at once with mouse, the
answer if no.

-- 
Thierry

**Comment by Ambrevar** [comment]
OK, but why not?

Something like C-mouse-1 to mark multiple candidates (equivalent to C-space) and S-mouse-1 to mark all candidates in the region would be fairly familiar to most people used to Cocoa/GTK/Qt, etc.  What do you think?

I'm working on an experimental [stand-alone for Helm System Pakcages](https://github.com/emacs-helm/helm-system-packages/tree/master/stand-alone) which aims at being as straightforward as possible to non-Emacs users.

If you don't want to add those additional mouse binding to Helm, could you guide me on how to do add them locally?  Thanks!

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> OK, but why not?

Because I will have to make it and I have no motivation for implementing
it ;-).

-- 
Thierry

**Comment by Ambrevar** [comment]
If you don't mind, leave this open, I might work on it at some point.
