### ISSUE TITLE
How to call helm-find-files-1 with a specific action done?

### ISSUE THREAD

**Issue by moyotar** [emacs-helm/helm#1958]
Due to the bad performance of `helm-projectile-find-file` in project with more than 10 thousands files, I want to write a function to find file faster through `helm-projectile-find-file-1` and `helm-ff-run-find-sh-command`. But I'm new for `elisp` so that I don't know how to call `helm-find-files-1` with `helm-ff-run-find-sh-command` done. 

> (defun my-projectile-find-file ()                                                                                                                        
      (interactive)                                                                                                                                          
      ;; I try (helm-ff-run-find-sh-command) here and get failure. T_T                                                                                       
     (helm-find-files-1 (projectile-project-root))                                                                                                          
     ;; failure again here. T_T                                                                                                                             
     )

**Comment by thierryvolpiatto** [comment]
moyotar <notifications@github.com> writes:

> Due to the bad performance of helm-projectile-find-file in project
> with more than 10 thousands files,

If your project is under git, install `helm-ls-git` and use `M-x
helm-browse-project` (C-x C-d) from any buffer of your project or `C-x C-d`
(same) from `helm-find-files` (navigate to your project).

An alternative is using `helm-locate` with a locale Db file to your
project, for this use `C-u C-x C-f` from `helm-find-files` or `C-u
helm-locate` from any buffer of your project.

If you want to browse files of several projects at once, use `M-x
helm-projects-find-files` after setting up variable `helm-locate-project-list`.
c
-- 
Thierry

**Comment by moyotar** [comment]
@thierryvolpiatto Thanks. It's good to use `C-u helm-locate`. But the `locate.db` will not update automatically. What'more, I found no way to update it.

**Comment by thierryvolpiatto** [comment]
moyotar <notifications@github.com> writes:

> @thierryvolpiatto Thanks. It's good to use C-u helm-locate. But the
> locate.db will not update automatically. What'more, I found no way to
> update it.

C-u C-u ;-)

-- 
Thierry

**Comment by moyotar** [comment]
Thanks a lot!
