### ISSUE TITLE
Bind helm-unmark-all to M-u?

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#1959]
Presently, `M-a` is bound to `helm-mark-all`, `M-m` to `helm-toggle-all-marks` while `M-U` is bound to `helm-unmark-all`.
The uppercase is a bit inconsistent here.

Things get worse with the display filters used by helm-system-packages (originally your bindings): `M-I` for installed packages, `M-D` for dependencies, etc.
Then `M-U` cannot be used for uninstalled packages.

In my opinion it would be more consistent to leave the generic marking commands to lowercase bindings and the display filters to uppercase bindings.  What do you think?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Presently, M-a is bound to helm-mark-all, M-m to helm-toggle-all-marks while M-U is bound to helm-unmark-all.
> The uppercase is a bit inconsistent here.

M-u => upcase-word

> Things get worse with the display filters used by helm-system-packages
> (originally your bindings): M-I for installed packages, M-D for
> dependencies, etc.  Then M-U cannot be used for uninstalled packages.

So use something else?

> In my opinion it would be more consistent to leave the generic marking
> commands to lowercase bindings and the display filters to uppercase
> bindings. What do you think?

Only when possible, yes, otherwise like for M-u it is not possible.

--
Thierry

**Comment by Ambrevar** [comment]
Duh, forgot about that!

OK, then I'll use `M-N` for *N*on-installed packages.
