### ISSUE TITLE
Automatically act on all marked candidates?

### ISSUE THREAD

**Issue by girzel** [emacs-helm/helm#1961]
Is there any way to define a source, using just the alist format, but have the action functions always act on all marked candidates automatically? Right now (unless I'm missing something), the action functions have the signature: `(defun my-action (candidate))` and only receive the candidate under point. If I want to check the marked candidates, I have to discard that argument and act on the return value of `helm-marked-candidates`. What I'd like is to have the action functions always receive the results of `helm-marked-candidates` as their argument.

Is this possible right now?

**Comment by thierryvolpiatto** [comment]
Eric Abrahamsen <notifications@github.com> writes:

> Is there any way to define a source, using just the alist format,

First of all, this is not recommended, prefer using helm-build-<xx>
macros or with a class and helm-make-source.

> What I'd like is to have the action functions always receive the
> results of helm-marked-candidates as their argument.

Why? What's the problem with

    (lambda (_candidate) (let ((mkds (helm-marked-candidates))) ...))

> Is this possible right now?

No, though helm-comp-read is able to return a list instead of a single
candidate:

    (helm-comp-read "test: " '(a b c d e) :marked-candidates t)

but in this case you have to use a single action on this return value.

--
Thierry

**Comment by girzel** [comment]
I'm trying to write a package to go in Elpa, that uses helm but doesn't "Package-Require" it, since it doesn't work to declare  a dependency from Elpa to Melpa. For a bit I thought I might be able to write code that could be used to make a helm command, but not actually call any helm functions, but I've given up and am just going to use `declare-function` to protect the helm functions.

In other words, please ignore this!

**Comment by thierryvolpiatto** [comment]
Eric Abrahamsen <notifications@github.com> writes:

> I'm trying to write a package to go in Elpa, that uses helm but
> doesn't "Package-Require" it, since it doesn't work to declare a
> dependency from Elpa to Melpa.

Note that Melpa support dependencies from Elpa... so you have better
time to put your packages in Melpa instead of Elpa for this and many
other reasons.

--
Thierry
