### ISSUE TITLE
Helm-locate fails on local db with spaces

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#1962]
`C-u M-x helm-locate` fails when the path to the database contains a space:

```
* Exit with code 1, no result found, command line was:

 locate -d /run/media/ambrevar/complete current/locate.db -i -e -A --regex movies locate: can not stat () `/run/media/ambrevar/complete': No such file or directory
 ```

The following fix works:

```diff
(defun helm-locate-with-db (&optional db initial-input default)
  "Run locate -d DB.
If DB is not given or nil use locate without -d option.
Argument DB can be given as a string or list of db files.
Argument INITIAL-INPUT is a string to use as initial-input.
See also `helm-locate'."
  (require 'helm-files)
  (when (and db (stringp db)) (setq db (list db)))
  (helm-locate-set-command)
  (let ((helm-locate-command
         (if db
             (replace-regexp-in-string
              "locate"
              (format (if helm-locate-fuzzy-match
-                         "locate -b -d %s" "locate -d %s")
+                         "locate -b -d '%s'" "locate -d '%s'")
```

I tried using `shell-quote-argument` to no avail.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> C-u M-x helm-locate fails when the path to the database contains a space:
>
> * Exit with code 1, no result found, command line was:
>
>  locate -d /run/media/ambrevar/complete current/locate.db -i -e -A --regex movies locate: can not stat () `/run/media/ambrevar/complete': No such file or directory
>
> The following fix works:

Thanks, fixed the db creation as well.

-- 
Thierry

**Comment by Ambrevar** [comment]
@makp: I'm also working on a wrapper around `helm-locate-with-db` to work with a set of databases.  I'm curious about your implementation.  Do you mind sharing? :)

**Comment by makp** [comment]
@Ambrevar Not at all! Here is what I use:
```
(defun mk/locate-with-helm (&optional arg)
  (interactive "p")
  (cond
   ((equal arg 1)  (helm-locate-with-db (expand-file-name "locate-1.db" "~/elisp"))) 
   ((equal arg 4)  (helm-locate-with-db (expand-file-name "locate-2.db" "~/elisp")))
   ((equal arg 16) (helm-locate-with-db (expand-file-name "locate-3.db" "~/elisp")))))

(global-set-key (kbd " ") 'mk/locate-with-helm)
```
I use a cron job to generate different locate databases which are placed in the folder `~/elisp/`. And, as you can see above, I use a prefix argument to select my desired db (that way I only have to use one keybinding for my multiple databases).

**Comment by Ambrevar** [comment]
Oh, I see, that's a very different use case :)

Here is what I do: I store one local database in `~/.cache/locatedb` for `/` (so that I can udpate the db without admin priviledges),
plus one db per non-root drive, which are usually mounted in `/media` or `/run/media/<login>`.

``` elisp
(defun helm-locate-create-or-update-db (db root &optional update)
  "See `helm-locate-meta'."
  (let ((was-missing (not (file-exists-p db))))
    (when (or update was-missing)
      (if (= (shell-command
              (funcall helm-locate-create-db-function
                       db
                       root))
             0)
          (message "locatedb file `%s' %s" db (if was-missing "created" "updated"))
        (error "Failed to %s locatedb file `%s'" db (if was-missing "create" "update"))))))

(defun helm-locate-meta (&optional update)
  "Like `helm-locate' but also use the databases found in /media and /run/media.
With prefix argument, UPDATE the databases."
  (interactive "P")
  (let ((user-db (expand-file-name "~/.cache/locate.db")))
    (helm-locate-create-or-update-db user-db "/" update)
    (helm-locate-with-db
     (mapconcat 'identity
                (append (list user-db)
                        (mapc
                         (lambda (db)
                           (helm-locate-create-or-update-db db (file-name-directory db) update))
                         (apply 'append (mapcar
                                         (lambda (root) (file-expand-wildcards (concat root "/*/locate.db")))
                                         (list (concat "/run/media/" (user-login-name)) "/media")))))
                ":")
     nil (thing-at-point 'filename))))
```

`helm-locate-meta` effectively becomes a universal finder: it finds everything on all drives, and whenever I suspect some the databases might be out of date, I use a prefix argument.

I wonder however if it couldn't be made simpler with the existing code from `helm-locate`.  @thierryvolpiatto?

**Comment by makp** [comment]
@Ambrevar: Yes, my use case is much simpler :) I like the idea of using locate to find any file on my computer though. Thanks for sharing your wrapper!

**Comment by thierryvolpiatto** [comment]
Makmiller Pedroso <notifications@github.com> writes:

> It seems that this change will prevent users from using "~" to specify the path to the locate database file using helm-locate-with-db (at least, that's what happened
> with me). However, I understand that this is not a big deal because
> someone might simply use expand-file-name to specify the path for the
> locate db file.

You should now be able to pass abbreviated file names to
helm-locate-with-db.

Thanks.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
For using more than one locale DB at the same time, see: `helm-locate-project-list` and `helm-projects-find-files`.

**Comment by Ambrevar** [comment]
@thierryvolpiatto Yes, `helm-projects-find-files` would do exactly that but for one thing: specifying a root directory (`-U`) different from the parent directory of the database.

Apparently the following does not work:

```
> touch /locatedb
> chmod 666 /locatedb
> updatedb -l 0 -o /locatedb -U /
/usr/bin/updatedb: can not open a temporary file for `/locatedb'
```

Thus I must store the locatedb in a folder where my user account has write permissions, that is, a folder different from `/`.
Then `helm-projects-find-files` will run update the db with the wrong root.

Or am I missing something?
