### ISSUE TITLE
Please make helm-boring-file-regexp-list support non-suffix patterns

### ISSUE THREAD

**Issue by rrthomas** [emacs-helm/helm#1963]
At present (I'm using helm-2.8.8), the docstring for this variable says:

> The directory names should end with "/?" e.g. "\.git/?" and the
> file names should end with "$" e.g. "\.o$".

Indeed, if I try to add a pattern that does not end with `$`, it does not work. What is less obvious is that I cannot add a pattern anchored at the other end, with `^`. So for example, if I want to exclude files named `.bak.*`, then I can't write `^\.bak\.`.

It seems the closest I can get is to write: `/\.bak\..*$`. If this is the best we can do, it would be nice to document it; otherwise, perhaps it could be fixed? My understanding is that this list is meant to match only the basename, not the full path, so allowing patterns to be written more naturally (using the `^` anchor, and omitting the `$` anchor) should not break anything.

**Comment by thierryvolpiatto** [comment]
Reuben Thomas <notifications@github.com> writes:

> At present (I'm using helm-2.8.8), the docstring for this variable says:
>
>     The directory names should end with "/?" e.g. ".git/?" and the
>     file names should end with "$" e.g. ".o$".
>
> Indeed, if I try to add a pattern that does not end with $, it does not work. What is less obvious is that I cannot add a pattern anchored at the other end, with ^.
> So for example, if I want to exclude files named .bak.*, then I can't write ^\.bak\..
>
> It seems the closest I can get is to write: /\.bak\..*$. If this is
> the best we can do, it would be nice to document it; otherwise,
> perhaps it could be fixed? My understanding is that this list is meant
> to match only the basename, not the full path,

Not necessarily, this is because it is tricky to fix (without loosing
performances).
For helm-find-files, we match indeed the basename with a regexp
concatening all boring regexps, but for e.g. locate the filenames are
absolute and for the directories we can't match at end, e.g.

/foo/bar/.git/config

where .git is an unwanted directory.

> so allowing patterns to be written more naturally (using the ^ anchor,
> and omitting the $ anchor) should not break anything.

Will work for one but not the other.

Will look in the next days what I can do.

--
Thierry

**Comment by thierryvolpiatto** [comment]
Reuben Thomas <notifications@github.com> writes:

> At present (I'm using helm-2.8.8), the docstring for this variable says:
>
>     The directory names should end with "/?" e.g. ".git/?" and the
>     file names should end with "$" e.g. ".o$".
>
> Indeed, if I try to add a pattern that does not end with $, it does
> not work. What is less obvious is that I cannot add a pattern anchored
> at the other end, with ^.  So for example, if I want to exclude files
> named .bak.*, then I can't write ^\.bak\..

As another example, ^/.bak/.. would not match in locate filenames with
something like /foo/bar/.bak.else this is why the prefix should not be
added.

So for your use case using "\\.bak\\..*$" is working fine here for both
HFF and locate.

Note that you have to use customize when modifying
helm-boring-file-regexp-list (customize-set-variable or friend).

--
Thierry

**Comment by rrthomas** [comment]
Thanks very much for the explanation. Documenting that some uses of the list match the entire string would help users (or at least me!) understand the patterns have to take, and why. You could say explicitly that the pattern matches the entire path, and that this is needed for some commands, including locate. In fact, that might be just as good a solution! An example for a file prefix, such as the one I give, might also help.

**Comment by thierryvolpiatto** [comment]
Reuben Thomas <notifications@github.com> writes:

> Thanks very much for the explanation. Documenting that some uses of
the list match the entire string would help users (or at least me!)
understand the patterns have > to take, and why. You could say
explicitly that the pattern matches the entire path, and that this is
needed for some commands, including locate. In fact, that might > be
just as good a solution! An example for a file prefix, such as the one I
give, might also help.

Would this be ok?

    These regexps doesn't match forcibly the extension of file but also the
    whole filename, so if one want for example to ignore all files
    prefixed by \".bak.\", \"\\.bak\\..*$\" can be used as regexp.

Thanks.

--
Thierry

**Comment by rrthomas** [comment]
Thanks, that looks good. I would just tweak the English:

> These regexps may be used to match the entire path, not just the file name, so for example to ignore files with a prefix ".bak.", use "\\.bak\\..*$" as the regexp.

**Comment by thierryvolpiatto** [comment]
Reuben Thomas <notifications@github.com> writes:

> Thanks, that looks good. I would just tweak the English:
>
>     These regexps may be used to match the entire path, not just the
>     file name, so for example to ignore files with a prefix ".bak.",
>     use "\.bak\..*$" as the regexp.

Thanks for english correction ;-) Merged.

-- 
Thierry
