### ISSUE TITLE
Take in helm-swoop as a part of helm

### ISSUE THREAD

**Issue by HuStmpHrrr** [emacs-helm/helm#1966]
It's a feature request.

It turns out that helm-swoop has a high chance to be in a state of no longer maintained. However, helm-swoop is a really nice tool, and in many helm introductions, helm-swoop is mentioned to be a very typical tool for helm.

After a recent update from helm, helm-swoop side broke for a few days, and up until now the patch has not been merged yet to the master branch, nor published to melpa. Considering the essential importance of helm-swoop, do you think it's OK to take in helm-swoop as a part of helm, so that it can be up to date?

Also refer to this issue: https://github.com/ShingoFukuyama/helm-swoop/issues/123

**Comment by thierryvolpiatto** [comment]
Jason Hu <notifications@github.com> writes:

> It's a feature request.
>
> It turns out that helm-swoop has a high chance to be in a state of no
> longer maintained. However, helm-swoop is a really nice tool, and in
> many helm introductions, helm-swoop is mentioned to be a very typical
> tool for helm.

Implementation of helm-swoop is terrible, we have helm-occur and helm-moccur
which do more or less the same, are faster and well implemented.

So no thanks I don't want to take over helm-swoop.

--
Thierry

**Comment by HuStmpHrrr** [comment]
OK, since you don't like it, we can close this issue now.
