### ISSUE TITLE
Save helm find files result to buffer

### ISSUE THREAD

**Issue by CeleritasCelery** [emacs-helm/helm#1969]
Is there a way to save the current candidates from a `helm-find-files` session to a buffer? If I have used the pattern matching to show just the files that I want, it would be create to save those off to a buffer to be manipulated, saved, or emailed. I looked through the docs, look at the key map, asked on gitter, and googled it but could find nothing. Is this supported?

**Comment by thierryvolpiatto** [comment]
Troy Hinckley <notifications@github.com> writes:

> Is there a way to save the current candidates from a helm-find-files
> session to a buffer? If I have used the pattern matching to show just
> the files that I want, it would be create to save those off to a
> buffer to be manipulated, saved, or emailed. I looked through the
> docs, look at the key map, asked on gitter, and googled it but could
> find nothing. Is this supported?

No because we have dired, so no need to reinvent the wheel.
So you can exit helm-find-files in dired, you can also open a dired
buffer with only marked  candidates (wdired) with (C-u) C-x C-q.

--
Thierry

**Comment by Ambrevar** [comment]
Also try `helm-copy-to-buffer` (default to `C-c TAB`).

**Comment by CeleritasCelery** [comment]
@Ambrevar that is exactly what I was looking for! Thanks!

**Comment by Ambrevar** [comment]
Note that it works in all Helm sessions.  Very handy when looking up variables, functions and such.
One of Helm's many badass features... :)
