### ISSUE TITLE
helm-execute-kmacro error: wrong-type-argument characterp

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#1970]
I sometimes get an error when I try to concat macros:

```
Debugger entered--Lisp error: (wrong-type-argument characterp 67108923)
  mapconcat(identity ([67108923 98 105 97 109 98 114 101 118 97 114 47 escape 7] "l") "")
  (setq last-kbd-macro (mapconcat (quote identity) (let* ((--cl-var-- mkd) (km nil) (--cl-var-- nil)) (while (consp --cl-var--) (setq km (car --cl-var--)) (setq --cl-var-- (cons (car km) --cl-var--)) (setq --cl-var-- (cdr --cl-var--))) (nreverse --cl-var--)) ""))
  (progn (kmacro-push-ring) (setq last-kbd-macro (mapconcat (quote identity) (let* ((--cl-var-- mkd) (km nil) (--cl-var-- nil)) (while (consp --cl-var--) (setq km (car --cl-var--)) (setq --cl-var-- (cons (car km) --cl-var--)) (setq --cl-var-- (cdr --cl-var--))) (nreverse --cl-var--)) "")))
  (if (cdr mkd) (progn (kmacro-push-ring) (setq last-kbd-macro (mapconcat (quote identity) (let* ((--cl-var-- mkd) (km nil) (--cl-var-- nil)) (while (consp --cl-var--) (setq km (car --cl-var--)) (setq --cl-var-- (cons ... --cl-var--)) (setq --cl-var-- (cdr --cl-var--))) (nreverse --cl-var--)) ""))))
  (let ((mkd (helm-marked-candidates))) (if (cdr mkd) (progn (kmacro-push-ring) (setq last-kbd-macro (mapconcat (quote identity) (let* ((--cl-var-- mkd) (km nil) (--cl-var-- nil)) (while (consp --cl-var--) (setq km ...) (setq --cl-var-- ...) (setq --cl-var-- ...)) (nreverse --cl-var--)) "")))))
  helm-kbd-macro-concat-macros(([66 105 escape 67108923 105 97 109 98 114 101 118 97 114 47 7 escape] 0 "%d"))
	...
```

I haven't investigated, but from the look of the backtrack it seems that when the macro contains a modifiers, its internal representation is a vector and not a string.
I suppose concatenating vectors instead of strings should fix it.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I sometimes get an error when I try to concat macros:

Eval this and let me know if it works:

    (defun helm-kbd-macro-concat-macros (_candidate)
      (let ((mkd (helm-marked-candidates)))
        (when (cdr mkd)
          (kmacro-push-ring)
          (setq last-kbd-macro
                (mapconcat 'key-description
                           (cl-loop for km in mkd
                                    collect (car km))
                           "")))))

> Debugger entered--Lisp error: (wrong-type-argument characterp 67108923)
>   mapconcat(identity ([67108923 98 105 97 109 98 114 101 118 97 114 47 escape 7] "l") "")

Normally it should, as 

(mapconcat 'key-description 
           '([67108923 98 105 97 109 98 114 101 118 97 114 47 escape 7]
           "l") 
           "")

=> "C-; b i a m b r e v a r / <escape> C-gl" 

-- 
Thierry

**Comment by Ambrevar** [comment]
I does not fail but the resulting macros has all its spaces replaced by
SPC.

So instead of inserting "ambrevar", the resulting macros inserts "a m b
r e v a r".

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I does not fail but the resulting macros has all its spaces replaced by
> SPC.
>
> So instead of inserting "ambrevar", the resulting macros inserts "a m b
> r e v a r".

I don't understand:

1) hit <f3> (runs the command kmacro-start-macro-or-insert-counter)
2) write ambrevar
3) hit <f4> (runs the command kmacro-end-or-call-macro)
4) M-x helm-execute-kmacro
5) hit RET ambrevar with no spaces is entered at point

What is wrong with this?
Did I miss something ?

Oh maybe the recipe above doesn't generate a vector entry ?
Can you give me a recipe to reproduce a vector entry ?

Thanks.

-- 
Thierry

**Comment by Ambrevar** [comment]
The spaces appear _after_ concatenation (with your last fix).

Recipe:

- <f3>
- foo
- <f4>
- <f3>
- bar
- <f4>
- M-x helm-execute-kmacro (everything is in order)
- C-SPC C-SPC (to select "foo" and "bar")
- <f2>
- M-x helm-execute-kmacro (the newly created entry is "b SPC a SPC r f SPC o SPC o")

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I does not fail but the resulting macros has all its spaces replaced by
> SPC.
>
> So instead of inserting "ambrevar", the resulting macros inserts "a m b
> r e v a r".

Ok I think I understand what is happening, can you try with:

    (defun helm-kbd-macro-concat-macros (_candidate)
      (let ((mkd (helm-marked-candidates)))
        (when (cdr mkd)
          (kmacro-push-ring)
          (setq last-kbd-macro
                (mapconcat 'identity
                           (cl-loop for km in mkd
                                    if (vectorp km)
                                    append (cl-loop for k across km collect
                                                    (key-description (vector k)))
                                    into result
                                    else collect (car km) into result)
                           "")))))
-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Oops, forget to return result in the cl-loop above, I have commited a new fix now, have a try.

**Comment by Ambrevar** [comment]
Seems to be working now, thanks!
