### ISSUE TITLE
Buffer ID column is too wide in helm-buffers-list

### ISSUE THREAD

**Issue by angrybacon** [emacs-helm/helm#1972]
## Expected Behavior

When setting ` helm-buffer-max-length` to `nil`, the first column when using `helm-buffers-list`, buffer ID, should be separated from the second column, buffer size, by a smaller gap. Much like the 2-spaces gap found between the columns for buffer size and buffer major mode, as well as the columns for buffer major mode and buffer path.

## Actual Behavior

<kbd>C-x b</kbd>

![image](https://user-images.githubusercontent.com/5608624/36546651-3dc198fc-17ec-11e8-97a2-587988d8554c.png)

<kbd>C-x b</kbd> `somelongbufferidsomelongbufferid` <kbd>RET</kbd> <kbd>C-x b</kbd>

![image](https://user-images.githubusercontent.com/5608624/36546749-80b8e796-17ec-11e8-9621-2d222b5cae3a.png)

## Steps to reproduce

```elisp
(setq package-load-list '((async t) (helm t) (helm-core t) (popup t)))
(package-initialize)
(require 'helm-config)
(helm-mode)
(setq-default
 helm-always-two-windows t
 helm-buffer-max-length nil
 helm-split-window-default-side 'left)
(define-key global-map [remap switch-to-buffer] 'helm-buffers-list)
```

## Versions

- Windows 10
- GNU Emacs 25.3.1 (x86_64-w64-mingw32) of 2017-09-12
- `elpa/async-20180119.533/`
- `elpa/helm-20180221.555/`
- `elpa/helm-core-20180221.731/`
- `elpa/popup-20160709.729/`

**Comment by thierryvolpiatto** [comment]
Mathieu Marques <notifications@github.com> writes:

> Expected Behavior
>
> When setting helm-buffer-max-length to nil, the first column when
> using helm-buffers-list, buffer ID, should be separated from the
> second column, buffer size, by a smaller gap. Much like the 2-spaces
> gap found between the columns for buffer size and buffer major mode,
> as well as the columns for buffer major mode and buffer path.

Ok, I made the same separator for all columns, indeed this one was a tab
instead of two spaces, thus I made a new user var
`helm-buffers-column-separator` for this you can customize.

Thanks.

--
Thierry

**Comment by angrybacon** [comment]
I didn't notice at first but it's actually explained in the code, size is formatted to account for 7 characters.

Thanks for the reactiveness :-)
