### ISSUE TITLE
Feature request: visit (open) multiple marked files from `helm-filtered-bookmarks`

### ISSUE THREAD

**Issue by ackalker** [emacs-helm/helm#1974]
## Expected behavior
- It would be nice to be able to visit (open) multiple marked files from within `helm-filtered-bookmarks`.
## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
- Currently, only the last marked file is visited.
## Steps to reproduce (recipe)
- Make sure bookmarks contain some files (I visited each file then used `C-x r m RET` to bookmark it)
- Run `helm-filtered-bookmarks` (which in my case is bound to `C-x r b`)
- Make sure some files are listed in the source section `Bookmark Files&Directories`
- Filter the results by typing some text (I typed `init` to filter my bookmarks to just my init files)
- Mark some files in the filtered results by moving selection and pressing `C-SPC`
- Press `RET`
## Describe versions of Helm, Emacs, operating system, etc.
Helm: 20180227.411 (installed from MELPA)
Emacs: GNU Emacs 25.3.1
OS: Void Linux (x86_64, glibc)

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):
no

EDIT: Updated steps to reproduce.

**Comment by ackalker** [comment]
I guess that this request could perhaps be generalized to: Act on each marked entry in `helm-filtered-bookmarks`. Any comments are welcome.

**Comment by thierryvolpiatto** [comment]
Alain Kalker <notifications@github.com> writes:

> I guess that this request could perhaps be generalized to: Act on each
> marked entry in helm-filtered-bookmarks. Any comments are welcome.

Not all sources support jumping to multiple candidates, and each
category of bookmark behave differently according to the handler they
use, this is why you can't open many candidates at once. Distinction
could be make for source allowed to jump to more than one candidates but
I am not sure it is worth the effort comparing to the little benefit it
offers.

--
Thierry

**Comment by ackalker** [comment]
@thierryvolpiatto Thanks for the explanation, sorry for my late reply.
