### ISSUE TITLE
Helm autoresize is broken/changed in v2.9.0 

### ISSUE THREAD

**Issue by furkanusta** [emacs-helm/helm#1975]
## Expected behavior
![screenshot from 2018-02-28 20-39-07](https://user-images.githubusercontent.com/10398862/36803170-e6e6ecd6-1cc7-11e8-9e33-9e2398a59909.png)

Open helm-find-files (above) and go one directory up (below image). This works in v2.8.9

![screenshot from 2018-02-28 20-39-26](https://user-images.githubusercontent.com/10398862/36803147-dc0dab24-1cc7-11e8-832f-079f24acd09c.png)

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
This one is in v2.9.0

![screenshot from 2018-02-28 20-39-10](https://user-images.githubusercontent.com/10398862/36803162-e306c406-1cc7-11e8-9313-4cf063a80c9c.png)

## Steps to reproduce (recipe)
(helm-autoresize-mode 1)

## Describe versions of Helm, Emacs, operating system, etc.

Helm v2.9.0
Emacs 25.3.1
Fedora 27

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):
Yes

**Comment by furkanusta** [comment]
I've checked the commits  between 2.8.9 and 2.9.0 and the culprit is a5e9a7b7277ecc30fba608a711ac55925e860453 and it looks like it is implemented as a fix for another user's problem #1973 .

**Comment by thierryvolpiatto** [comment]
Furkan <notifications@github.com> writes:

> I've checked the commits between 2.8.9 and 2.9.0 and the culprit is
> a5e9a7b and it looks like it is implemented as a fix for another
> user's problem #1973 .

Thanks, should work now.

--
Thierry

**Comment by furkanusta** [comment]
Yes, works as expected. Thanks for the quick fix
