### ISSUE TITLE
Note: helm + posframe, may be some one like it :-)

### ISSUE THREAD

**Issue by tumashu** [emacs-helm/helm#1980]
A simple exwmple, maybe it is useful to someone, 
Note: the below code need newest posframe :-)

```
(require 'posframe)

(setq helm-display-function #'helm-posframe-display)

(defvar helm-posframe-buffer nil)

(defun helm-posframe-display (buffer &optional _resume)
  (setq helm-posframe-buffer buffer)
  (posframe-show
   buffer
   :poshandler #'posframe-poshandler-frame-bottom-left-corner
   :width (+ (window-width) 2)
   :height helm-display-buffer-height
   :respect-header-line t))

(defun helm-posframe-cleanup ()
  (posframe-hide helm-posframe-buffer))

(add-hook 'helm-cleanup-hook #'helm-posframe-cleanup)

```

**Comment by thierryvolpiatto** [comment]
tumashu <notifications@github.com> writes:

> A simple exwmple, maybe it is useful to someone,
> Note: the below code need newest posframe :-)

We already support helm in frame since 2.8.8

https://github.com/emacs-helm/helm/releases/tag/v2.8.8

https://github.com/emacs-helm/helm/wiki/frame

-- 
Thierry

**Comment by tumashu** [comment]
For user, they may be different :-). I will close this note :-)

**Comment by thierryvolpiatto** [comment]
Thanks anyway for posframe, looks cool (but seems it is working only on 26+ ?).

**Comment by tumashu** [comment]
yes
