### ISSUE TITLE
helm mini buffer delete disorder

### ISSUE THREAD

**Issue by ambjlon** [emacs-helm/helm#1982]
When delete in mini buffer, the characters disorder below:
![image](https://user-images.githubusercontent.com/4489822/37188620-15513f44-238b-11e8-9c80-b4684d330a37.png)

**Comment by thierryvolpiatto** [comment]
Chen Jianglong <notifications@github.com> writes:

> image   

Sorry but I don't know what you are doing, how you are deleting
characters in minibuffer etc...
Also you didn't fill the bug report template, please do it.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Also it seems you are not using a minimal emacs (emacs-helm.sh) so I am closing this, feel free to reopen a real bug report explaining clearly what you are doing to reproduce the bug.
Thanks.

**Comment by ambjlon** [comment]
![image](https://user-images.githubusercontent.com/4489822/38081243-239d9ce6-3376-11e8-9249-88747b8c8d98.png)
