### ISSUE TITLE
New popup when more than 2 buffers

### ISSUE THREAD

**Issue by Cmdv** [emacs-helm/helm#1983]
This feature would of been nice if it was an opt in rather than now having to opt out 😄 
Might only be Spacemacs related:

## Expected behavior
Pop-up to be a single buffer not a reflection of current workspace.
## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
![screen shot 2018-03-09 at 08 33 12](https://user-images.githubusercontent.com/3036557/37198063-e2814b7e-2374-11e8-8acc-8ac160200f39.png)

## Steps to reproduce (recipe)
open more than two buffers then search project or file.
## Describe versions of Helm, Emacs, operating system, etc.
Spacemacs develop branch
## IMPORTANT NOTE

Helm provides a script named `emacs-helm.sh` which runs Helm in a neutral
environment: no other packages and only minimal settings.

When possible, use it to reproduce your Helm issue to ensure no other package is
interfering.

To run it, simply switch to the directory where Helm is installed and call `./emacs-helm.sh`.

Thanks.

**Comment by hynek** [comment]
I’ve found that it’s on purpose: https://github.com/emacs-helm/helm/commit/221b6ad8351c9529a1755b830bd8c4fbf1838e90

The fix is to `(setq helm-use-frame-when-more-than-two-windows nil)`.

Personally, I don’t mind the popup which seems to be close to the cursor, but it’s completely useless because it’s a small frame with at lest 3 windows so everything is cut off. :)

**Comment by thierryvolpiatto** [comment]
Changed default to nil. Note that the crap you see is only related to Spacemacs.

**Comment by Cmdv** [comment]
cool thank you @thierryvolpiatto 
though that Spacemacs would be the culprit for the messy looking frame 😢

**Comment by hynek** [comment]
For the record and Google: the inherit thing can be fixed using `(setq persp-init-new-frame-behaviour-override nil)`
