### ISSUE TITLE
Is these codes reasonable?

### ISSUE THREAD

**Issue by netjune** [emacs-helm/helm#1985]
In the file helm-imenu.el, in the following fuction:

```
(defun helm-imenu-transformer (candidates)
  (cl-loop for (k . v) in candidates
        for types = (or (helm-imenu--get-prop k)
                        (list "Function" k))
        for bufname = (buffer-name
                       (pcase v
                         ((pred overlayp) (overlay-buffer v))
                         ((or (pred markerp) (pred integerp))
                          (marker-buffer v))))
        for disp1 = (mapconcat
                     (lambda (x)
                       (propertize
                        x 'face
                        (cl-loop for (p . f) in helm-imenu-type-faces
                                 when (string-match p x)
                                 return f)))
                     types helm-imenu-delimiter)
        for disp = (propertize disp1 'help-echo bufname)
        collect
        (cons disp (cons k v))))
```

Should the 'types' be mapconcat-ed? There are two elements in 'types': the first one is type, the second is symbol name. Why the symbol name be matched with helm-imenu-type-faces?

In elisp, define a var like this:
`(defvar Variables nil)`

Then the var (with name Variables) will be highlighted as type. Is this intended?

**Comment by thierryvolpiatto** [comment]
netjune <notifications@github.com> writes:

> In the file helm-imenu.el, in the following fuction:
>
> (defun helm-imenu-transformer (candidates)

[...]

>
> Should the 'types' be mapconcat-ed? There are two elements in 'types':
> the first one is type, the second is symbol name. Why the symbol name
> be matched with helm-imenu-type-faces?

The second element is not a symbol, it is a symbol-name i.e. a string.
For variables, types helm-imenu--get-prop returns something like this:

(#1="Variables" #("helm-imenu-map" 0 14 (helm-imenu-type #1#)))

whereas for function it returns nil and we fallback to ("Function"
"foo"), doing something like this (simplified):

(mapconcat (lambda (x) (propertize x 'face 'default)) '("Function" "foo") " / ")
=> #("Function / foo" 0 8
  (face default)
  11 14
  (face default))

This example returns 'default face for both but indeed only "Function"
gets the appropriate face in the real code.

> In elisp, define a var like this:
> (defvar Variables nil)
>
> Then the var (with name Variables) will be highlighted as type. Is this intended?

I don't understand what you are asking for here, what is Variables?

--
Thierry

**Comment by netjune** [comment]
>  (mapconcat (lambda (x) (propertize x 'face 'default)) '("Function" "foo") " / ")
> => #("Function / foo" 0 8 (face default) 11 14 (face default)) 
>
> This example returns 'default face for both but indeed only "Function" gets the appropriate face in the real code.

If there is a function whose name is "Function", then the the value of 'types' will be '("Function" "Function"), and he two strings will both get the font-lock-function-name-face face. Is this intended? 
What I expect is that the second element(the symbol name string) always has the default face(not 
font-lock-function-name-face or font-lock-variable-name-face).

**Comment by thierryvolpiatto** [comment]
netjune <notifications@github.com> writes:

>     (mapconcat (lambda (x) (propertize x 'face 'default)) '("Function" "foo") " / ")
>     => #("Function / foo" 0 8 (face default) 11 14 (face default))
>
>     This example returns 'default face for both but indeed only "Function" gets the appropriate face in the real code.
>
> If there is a function whose name is "Function", then the the value of
> 'types' will be '("Function" "Function"), and he two strings will both
> get the font-lock-function-name-face face. Is this intended?

No, but probably this will highlight that naming a function "Function"
is a bad idea :-)

--
Thierry

**Comment by netjune** [comment]
> No, but probably this will highlight that naming a function "Function" is a bad idea :-)
Yes, but here helm does some unused thing which may cause problem(not only Function). It is not a good idea.

If the value of 'types' is as the above, then only the car of 'types' need regexp-match, which save half of regexp-match work.

**Comment by thierryvolpiatto** [comment]
netjune <notifications@github.com> writes:

> If the value of 'types' is as the above, then only the car of 'types'
> need regexp-match, which save half of regexp-match work.

Yes but it is not always the case, types may be longer like 
    '(type1 type2 type3 ... symbol-name).

--
Thierry

**Comment by thierryvolpiatto** [comment]
I think all have been explained here closing now.
