### ISSUE TITLE
Allow for more customizations in `helm--set-header-line`

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#1987]
Some people would like to change how `helm--set-header-line` behaves.

I've implemented a hack that taylors it for Evil, but we run into issues:
https://github.com/emacs-evil/evil-collection/issues/101.

```
(defun evil-collection-helm--set-header-line (&optional update)
  "Like `helm--set-header-line' with some Evil-specific tweaks.
- The cursor changes when in Evil insert state.
- Visual selection is highlighted."
  (with-selected-window (minibuffer-window)
    (let* ((beg (save-excursion (vertical-motion 0 (helm-window)) (point)))
           (end (save-excursion (end-of-visual-line) (point)))
           ;; The visual line where the cursor is.
           (cont (buffer-substring beg end))
           (pref (propertize
                  " "
                  'display (if (string-match-p (regexp-opt `(,helm--prompt
                                                             ,helm--action-prompt))
                                               cont)
                               `(space :width ,helm-header-line-space-before-prompt)
                             (propertize
                              "->"
                              'face 'helm-header-line-left-margin))))
           (pos (- (point) beg)))
      ;; Increment pos each time we find a "%" up to current-pos (#1648).
      (cl-loop for c across (buffer-substring-no-properties beg (point))
               when (eql c ?%) do (cl-incf pos))
      ;; Increment pos when cursor is on a "%" to make it visible in header-line
      ;; i.e "%%|" and not "%|%" (#1649).
      (when (eql (char-after) ?%) (setq pos (1+ pos)))
      (setq cont (replace-regexp-in-string "%" "%%" cont))
      (let ((state evil-state)
            (region-active (region-active-p))
            (m (mark t)))
        (with-helm-buffer
          (setq header-line-format (concat pref cont " "))
          (when region-active
            (setq m (- m beg))
            ;; Increment pos to handle the space before prompt (i.e `pref').
            (put-text-property (1+  (min m pos))  (+ 2 (max m pos))
                               'face
                               (list :background (face-background 'region))
                               header-line-format))
          (put-text-property
           ;; Increment pos to handle the space before prompt (i.e `pref').
           (+ 1 pos) (+ 2 pos)
           'face
           (if (eq state 'insert)
               'underline
             ;; Don't just use 'cursor, this can hide the current character.
             (list :inverse-video t
                   :foreground (face-background 'cursor)
                   :background (face-background 'default)))
           header-line-format)
          (when update (force-mode-line-update)))))))

```

The main tweaks are the cursor change depending on the Evil state and the display of the region in visual state.

It's not very pretty to override the entire function.  @thierryvolpiatto: Can you think of a neater way to customize it?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Some people would like to change how helm--set-header-line behaves.

[...]


>            (if (eq state 'insert)
>                'underline
>              ;; Don't just use 'cursor, this can hide the current character.
>              (list :inverse-video t
>                    :foreground (face-background 'cursor)
>                    :background (face-background 'default)))
>            header-line-format)

Make this a customizable function and call it with funcall.

-- 
Thierry

**Comment by Ambrevar** [comment]
But is it possible to make this change in Helm itself?

Also note the let bindings I had to set before.  Not sure how to make that customizable.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> But is it possible to make this change in Helm itself?

It have to be done in helm itself.

> Also note the let bindings I had to set before.

You don't need it, use directly the global evil flag in the customizable
function.

1) (defcustom helm-var 'helm-default-func ...)
2) Use (funcall helm-var) in helm--set-header-line.
3) Define a new function for your package and bind helm-var to it and
you are done.

-- 
Thierry

**Comment by Ambrevar** [comment]
There might be a misunderstanding: I'm asking if we can make this change
to the official `helm--set-header-line` function, that is, in this repository.
Something Evil-agnostic, obviously.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> There might be a misunderstanding: I'm asking if we can make this change
> to the official `helm--set-header-line` function, that is, in this repository.
> Something Evil-agnostic, obviously.

Yes, I understood, I will do it soon.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Done.
Now you can set `helm-default-cursor-face-function` to your own function.

**Comment by thierryvolpiatto** [comment]
Note: Now you have a variable, perhaps a better approach is to use `add-function` when changing mode, this will reduce even more duplicated code.

**Comment by Ambrevar** [comment]
Thank you, but I'm afraid your change is not generic enough.

```
      (let ((state evil-state)
            (region-active (region-active-p))
            (m (mark t)))
```

Those variables are set _before_ `with-helm-buffer`.  Unless I'm mistaken, your current approach makes the original buffer inaccessible from the callback.
My suggestion is to pass the original buffer as a parameter to the callback.

Furthermore, it's not the cursor that must be customizable but the whole prompt:

```
          (when region-active
            (setq m (- m beg))
            ;; Increment pos to handle the space before prompt (i.e `pref').
            (put-text-property (1+  (min m pos))  (+ 2 (max m pos))
                               'face
                               (list :background (face-background 'region))
                               header-line-format))
```

I suggest to rename `helm-default-cursor-face-function` to, say, `helm-prompt-face-function` and move
```
        put-text-property
         ;; Increment pos to handle the space before prompt (i.e `pref').
         (+ 1 pos) (+ 2 pos)
         'face
```

inside the callback.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Thank you, but I'm afraid your change is not generic enough.
>
>       (let ((state evil-state)
>             (region-active (region-active-p))
>             (m (mark t)))
>
> Those variables are set before with-helm-buffer. Unless I'm mistaken,
> your current approach makes the original buffer inaccessible from the
> callback.  My suggestion is to pass the original buffer as a parameter
> to the callback.

Well, up to you to check for those variable value in the right buffer
with appropriate functions:

(let ((state (with-helm-current-buffer evil-staz)))
   (if state == foo do this else do that))


--
Thierry

**Comment by Ambrevar** [comment]
OK, I did not know about `with-helm-current-buffer`.  First point solved!

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Furthermore, it's not the cursor that must be customizable but the whole prompt:
>
>           (when region-active
>             (setq m (- m beg))
>             ;; Increment pos to handle the space before prompt (i.e `pref').
>             (put-text-property (1+  (min m pos))  (+ 2 (max m pos))
>                                'face
>                                (list :background (face-background 'region))
>                                header-line-format))
>
> I suggest to rename helm-default-cursor-face-function to, say, helm-prompt-face-function and move
>
>         put-text-property
>          ;; Increment pos to handle the space before prompt (i.e `pref').
>          (+ 1 pos) (+ 2 pos)
>          'face
>
> inside the callback.

I suggest you make a PR for this as you know better than me what you
need exactly.

-- 
Thierry

**Comment by Ambrevar** [comment]
Will do.

I'm now realizing that all this does not solve the initial issue that was raised on Evil Collection issue tracker: evil-collection-helm.el won't compile if helm is not installed because of the helm-specific macros I've used.
With `with-helm-current-buffer`, the issue would remain.  What's your suggestion for this?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Will do.
>
> I'm now realizing that all this does not solve the initial issue that was raised on Evil Collection issue tracker: evil-collection-helm.el won't compile if helm is
> not installed because of the helm-specific macros I've used.
> With with-helm-current-buffer, the issue would remain. What's your suggestion for this?

(with-current-buffer helm-current-buffer...)

or

(eval-when-compile (require 'helm))

-- 
Thierry

**Comment by Ambrevar** [comment]
> (with-current-buffer helm-current-buffer...)

OK.

> (eval-when-compile (require 'helm))

Wouldn't that fail when helm is not installed?

**Comment by Ambrevar** [comment]
See PR #1995.
