### ISSUE TITLE
org-agenda disappears from helm-M-x results for "org agenda" after 1 use

### ISSUE THREAD

**Issue by CyberShadow** [emacs-helm/helm#1988]
## Steps to reproduce (recipe)

1. Run `emacs-helm.sh`
2. `M-x`, type `org agenda`, hit `RET`
3. Hit `q`
4. `M-x helm-M-x`
5. `M-x`, type `org agenda`

## Expected behavior

`org-agenda` is at the top of the suggestions, like in step 2.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

`org-agenda` is not in the list of suggestions.

## Describe versions of Helm, Emacs, operating system, etc.

helm-20180312, Emacs 25.3.1

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):

Yes.

**Comment by thierryvolpiatto** [comment]
Vladimir Panteleev <notifications@github.com> writes:

> Steps to reproduce (recipe)
>
>  1. Run emacs-helm.sh
>  2. M-x, type org agenda, hit RET
>  3. Hit q
>  4. M-x helm-M-x
>  5. M-x, type org agenda
>
> Expected behavior
>
> org-agenda is at the top of the suggestions, like in step 2.
>
> Actual behavior (from emacs-helm.sh if possible, see note at the bottom)
>
> org-agenda is not in the list of suggestions.

This is because after loading org-agenda, a lot of commands prefixed
with org-agenda pop up (then sorting is done on the
candidate-number-limit candidates so org-agenda is not found).

Use "org agenda$", "agenda$" or "org agenda" and hit C-M a.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Vladimir Panteleev <notifications@github.com> writes:

> Thanks for the explanation, but there is still an UX problem.
>
> Why is helm-candidate-number-limit applied before sorting, instead of after?

For the obvious reason that you can sort only once you have a set of
candidates, not before.
What could be done is sorting all candidates once computed and then displaying
candidate-number-limit candidates, but this would have no sense to use
candidate-number-limit at all, the purpose beeing to limit the
computation of candidates (which is costly) to candidate-number-limit.

-- 
Thierry
