### ISSUE TITLE
helm and ff-find-file-other conflict

### ISSUE THREAD

**Issue by tangxinfa** [emacs-helm/helm#1989]
## Expected behavior

In "/tmp/monitor.hpp" file buffer, `M-o` created "/tmp/monitor.cpp"

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

In "/tmp/monitor.hpp" file buffer, `M-o` created "/tmp/monitor.cpp/"

## Steps to reproduce (recipe)

ff-find-other-file call `read-directory-name` to select the directory to create
a file, the following code snippet show the bug:

`(read-directory-name
  (format "Find or create %s in: " "monitor.cpp")
  default-directory "monitor.cpp" nil)`

When echo area prompt `Find or create monitor.cpp in: /tmp/`, just press ENTER,
With helm, evaluated to: `"/tmp/monitor.cpp/"`
Without helm, evaluated to: `"monitor.cpp"`

## Describe versions of Helm, Emacs, operating system, etc.

Helm: 20180124.58
Emacs: 25.3.1
OS: Arch Linux

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):

no

## IMPORTANT NOTE

Helm provides a script named `emacs-helm.sh` which runs Helm in a neutral
environment: no other packages and only minimal settings.

When possible, use it to reproduce your Helm issue to ensure no other package is
interfering.

To run it, simply switch to the directory where Helm is installed and call `./emacs-helm.sh`.

Thanks.

**Comment by thierryvolpiatto** [comment]
tangxinfa <notifications@github.com> writes:

> Expected behavior
>
> In "/tmp/monitor.hpp" file buffer, M-o created "/tmp/monitor.cpp"
>
> Actual behavior (from emacs-helm.sh if possible, see note at the bottom)
>
> In "/tmp/monitor.hpp" file buffer, M-o created "/tmp/monitor.cpp/"
>
> Steps to reproduce (recipe)
>
> ff-find-other-file call read-directory-name to select the directory to create
> a file, the following code snippet show the bug:
>
> (read-directory-name (format "Find or create %s in: " "monitor.cpp") default-directory "monitor.cpp" nil)
>
> When echo area prompt Find or create monitor.cpp in: /tmp/, just press ENTER,
> With helm, evaluated to: "/tmp/monitor.cpp/"
> Without helm, evaluated to: "monitor.cpp"

This is a bug in `ff-find-the-other-file` which use wrongly the
arguments of `read-directory-name`:

    (read-directory-name (format "Find or create %s in: " "monitor.cpp") "/tmp/" "monitor.cpp" nil)

where the 3th argument of `read-directory-name` (DEFAULT-DIRNAME) is a filename instead of
being a directory name.
Helm is expecting a correct usage of the `read-file-name` or
`read-directory-name` arguments when building its generic function to
provide helm completion.

It works by chance outside of helm-mode because you exit minibuffer with
an empty string.

To work around this bug from helm, you can exit minibuffer with empty
string as well with C-RET or forcing the use of vanilla emacs by adding
`ff-find-other-file` to `helm-completing-read-handlers-alist`:

    (add-to-list 'helm-completing-read-handlers-alist '(ff-find-other-file . nil))

I can do nothing on the helm side to fix this bug.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
This bug have been introduced by this commit:

7e27ce9cdb691909a33667d5e2b186d23bb7c9c4
Author:     Antoine Levitt <antoine.levitt@gmail.com>
AuthorDate: Sat Mar 5 16:56:00 2011 -0500
Commit:     Chong Yidong <cyd@stupidchicken.com>
CommitDate: Sat Mar 5 16:56:00 2011 -0500

**Comment by thierryvolpiatto** [comment]
`read-file-name` have been replaced by `read-directory-name` without changing the relevant arguments.

**Comment by thierryvolpiatto** [comment]
So emacs should use:

```elisp
(expand-file-name
   default-name
   (read-directory-name
    (format "Find or create %s in: " default-name)
     default-directory nil))
```
instead of

``` elisp
(expand-file-name
    (read-directory-name
    (format "Find or create %s in: " default-name)
     default-directory default-name nil))
```

**Comment by tangxinfa** [comment]
> forcing the use of vanilla emacs by adding `ff-find-other-file` to `helm-completing-read-handlers-alist`: 
>    (add-to-list 'helm-completing-read-handlers-alist '(ff-find-other-file . nil))
-------------------
It works, thanks!
