### ISSUE TITLE
helm-esh-pcomplete leaves an extra space when no completion found

### ISSUE THREAD

**Issue by lepieru** [emacs-helm/helm#1990]
## Expected behavior

- Given I complete a command into Eshell (with `TAB` or `C-i`)
- When the completion is not found
- Then `No completion of my-unknown-command` is printed in the minibuffer.

## Actual behavior (from `emacs-helm.sh`)

- Given I complete a command into Eshell (with `TAB` or `C-i`)
- When the completion is not found
- Then `No completion of my-unknown-command` is printed in the minibuffer *and a space is added after the command I just typed*

Example:
- I type "lscd" in an Eshell
- I complete
- Then I have "lscd " (note the space after `lscd`)

## Steps to reproduce (recipe)

You should set `helm-esh-pcomplete` for Eshell first:

```emacs-lisp
(define-key eshell-mode-map [remap eshell-pcomplete] 'helm-esh-pcomplete)
```

Then run an Eshell, type an unknown command and hit `TAB` or `C-i`.

## Describe versions of Helm, Emacs, operating system, etc.

Helm: 20180314.934
Emacs: GNU Emacs 25.2.2

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):

Yes.

**Comment by thierryvolpiatto** [comment]
Pierre Le Gall <notifications@github.com> writes:

> Expected behavior
>
>   * Given I complete a command into Eshell (with TAB or C-i)
>   * When the completion is not found
>   * Then No completion of my-unknown-command is printed in the minibuffer.
>
> Actual behavior (from emacs-helm.sh)
>
>   * Given I complete a command into Eshell (with TAB or C-i)
>   * When the completion is not found
>   * Then No completion of my-unknown-command is printed in the minibuffer and a space is added after the command I just typed
>
> Example:
>
>   * I type "lscd" in an Eshell
>   * I complete
>   * Then I have "lscd " (note the space after lscd)

Fixed, thanks!

-- 
Thierry

**Comment by lepieru** [comment]
Thanks @thierryvolpiatto :+1:
