### ISSUE TITLE
Allow helm buffers to be saved as text.

### ISSUE THREAD

**Issue by it3ration** [emacs-helm/helm#1991]
Hello, avid `helm` user here (actually supported you on Patreon for awhile). :)

I often run commands like `helm-apropos` and narrow the list of candidates. I don't think it's currently possible to copy the entire contents of a helm buffer as text. I know there is `helm-copy-to-buffer`, but this isn't sufficient in buffers like `helm-apropos` where only one candidate can be selected. I'd like to be able to copy the entire contents of any `helm` buffer as text for further processing. It may also be nice to have another command that generates a temporary buffer with the copied content.

Thanks for all your stellar work!

**Comment by thierryvolpiatto** [comment]
Kevin Depue <notifications@github.com> writes:

> Hello, avid helm user here (actually supported you on Patreon for awhile). :)

Thanks!

> I often run commands like helm-apropos and narrow the list of
> candidates. I don't think it's currently possible to copy the entire
> contents of a helm buffer as text.  I know there is
> helm-copy-to-buffer, but this isn't sufficient in buffers like
> helm-apropos where only one candidate can be selected. I'd like to be
> able to copy the entire contents of any helm buffer as text for
> further processing. It may also be nice to have another command that
> generates a temporary buffer with the copied content.

You already have the buffer but it is hidden, you can see it with M-x
helm-buffers-list (or helm-mini) and hit `C-c a` to show hidden buffers.
Once in the buffer you can do what you want like in any other buffer,
but keep in mind that if you edit the buffer or change point and/or
mark, it will be no more usable for resuming, you will have to restart
again the whole helm session to renew the buffer (e.g. helm-apropos).
Let me know if that's enough for your use case or you need something
else.

--
Thierry

**Comment by thierryvolpiatto** [comment]
Thierry Volpiatto <thievol05@zoho.eu> writes:
 
> Once in the buffer you can do what you want like in any other buffer,
> but keep in mind that if you edit the buffer or change point and/or
> mark, it will be no more usable for resuming, you will have to restart
> again the whole helm session to renew the buffer (e.g. helm-apropos).

This is no more true since today! Fixed.

-- 
Thierry

**Comment by it3ration** [comment]
This will work! Thanks so much. :)
