### ISSUE TITLE
helm-imenu display orgmode title as "Function /  Test level 1 title(only 1 level)"

### ISSUE THREAD

**Issue by netjune** [emacs-helm/helm#1997]
The section has only 1 level.

Function seems be the default type added by helm-imenu. But it is not a function!

**Comment by thierryvolpiatto** [comment]
netjune <notifications@github.com> writes:

> The section has only 1 level.
>
> Function seems be the default type added by helm-imenu. But it is not a function!

I commited a change to fix this, but note that this should be fixed
upstream instead of here, i.e. give a type to first top level header as
for other headers.

-- 
Thierry

**Comment by netjune** [comment]
Another problem: 
In go-mode, the possible types are: type, func, which doesn't match types in helm-imenu and can't be highlighted as type.

**Comment by thierryvolpiatto** [comment]
netjune <notifications@github.com> writes:

> Another problem: In go-mode, the possible types are: type, func, which
> doesn't match types in helm-imenu and can't be highlighted as type.

Types are not highlighted in other languages like python and this is not
a problem. Also you can customize helm-imenu-type-faces.

--
Thierry
