### ISSUE TITLE
Helm reveals GPG passphrase for authinfo.gpg 

### ISSUE THREAD

**Issue by vbuzin** [emacs-helm/helm#2000]
The same problem as in #718. The only difference is that I have a GPG key encrypted authinfo file which is used by ange-ftp. Here's my configuration:

```lisp
(setq auth-sources "~/.secrets/authinfo.gpg")
(setq ange-ftp-netrc-filename auth-sources)
(setq epa-pinentry-mode 'loopback)
```

Steps to reproduce:

1. Generate a GPG key if you don't have one already
2. Create an entry in the authinfo.gpg file and encrypt the file with the key
3. Try to access a file on the server
4. You'll be asked for the passphrase which will be revealed when typed

**Comment by thierryvolpiatto** [comment]
Can you be more precise, specially on 4) ?

This looks like a bug with usage of `epa-pinentry-mode == loopback`, seems there is many problems with this so that it have been removed from emacs AFAIU, see the many discussions on emacs-devel about this.
I don't think I can fix this on helm side.

**Comment by vbuzin** [comment]
It seems that having `(setq epa-pinentry-mode 'loopback)` is the right way to go when you use Emacs - GnuPG integration. Furthermore this particular variable was introduced in emacs >= 25.1 which means this approach is hardly obsolete. With this setting Emacs will use mini buffer as the interface for entering the passphrase  when access to gpg-encrypted files is required.

**Comment by thierryvolpiatto** [comment]
Viacheslav Buzin <notifications@github.com> writes:

> It seems that having (setq epa-pinentry-mode 'loopback) is the right
> way to go when you use Emacs - GnuPG integration.

Not anymore it seems AFAIU the discussion on emacs-devel.
The safest way IMO is to use a graphical pinentry which DTRT, the
epa-pinentry-mode == loopback seems just pure hack I wouldn't trust.


> Furthermore this particular variable was introduced in emacs >= 25.1
> which means this approach is hardly obsolete. With this setting Emacs
> will use mini buffer as the interface for entering the passphrase when
> access to gpg-encrypted files is required.

I know what does epa-pinentry-mode == loopback, what I want to know is
detailed information on what happen on your machine specially in step 4)
of your recipe.
More specifically, would be great to know if
`epg-passphrase-callback-function` is called in step 4).
If so I could advice it to fix this bug.

--
Thierry

**Comment by vbuzin** [comment]
`epg-passphrase-callback-function` seems to be obsolete, `epa-passphrase-callback-function` is called instead.

**Comment by thierryvolpiatto** [comment]
Viacheslav Buzin <notifications@github.com> writes:

> epg-passphrase-callback-function seems to be obsolete,
> epa-passphrase-callback-function is called instead.

Yes thanks, but is it called in your use case ? (Use C-u C-M x on the
definition of function and then try do your ftp connection, if the
debugger kick in it is the function is used)
Also you didn't answer on what happen EXACTLY in 4)

--
Thierry

**Comment by thierryvolpiatto** [comment]
I propose this blindly as I don't know what is happening in what you described as 4) step in your recipe:
Is evaling the code below fix your issue?

``` emacs-lisp
(advice-add 'epa-passphrase-callback-function
            :around #'helm--advice-tramp-read-passwd)
```

**Comment by vbuzin** [comment]
I already confirmed that `epa-passphrase-callback-function` is called by using `debug-on-entry`. I also tried advising the function as in #718. So the following code does the trick.

```lisp
(defadvice epa-passphrase-callback-function (around disable-helm-update activate)
  ;; Suspend update when prompting for a ange password.
  (setq helm-suspend-update-flag t)
  (setq overriding-terminal-local-map nil)
  (setq helm--reading-passwd-or-string t)
  (unwind-protect
       ad-do-it
    (setq helm--reading-passwd-or-string nil)
    (setq helm-suspend-update-flag nil)))
```

Don't really understand your question regarding step 4. When you enter the passphrase it goes into the helm buffer as you type it.

**Comment by thierryvolpiatto** [comment]
Viacheslav Buzin <notifications@github.com> writes:

> I already confirmed that epa-passphrase-callback-function is called by
> using debug-on-entry. I also tried advising the function as in
> #718. So the following code does the trick.

> (defadvice epa-passphrase-callback-function (around disable-helm-update activate)
>   ;; Suspend update when prompting for a ange password.
>   (setq helm-suspend-update-flag t)
>   (setq overriding-terminal-local-map nil)
>   (setq helm--reading-passwd-or-string t)
>   (unwind-protect
>        ad-do-it
>     (setq helm--reading-passwd-or-string nil)
>     (setq helm-suspend-update-flag nil)))

Great, thanks, it is the same code I sent in previous post, I will add
it in helm tomorrow.

> Don't really understand your question regarding step 4. When you enter
> the passphrase it goes into the helm buffer as you type it.

Thanks, that's all what I wanted to know.

--
Thierry

**Comment by thierryvolpiatto** [comment]
Can you confirm last helm fix your problem?
Thanks.

**Comment by vbuzin** [comment]
The problem is fixed. Thanks!

**Comment by thierryvolpiatto** [comment]
Great, thanks.
