### ISSUE TITLE
helm-flx-fuzzy-highlighter wrong-type-argument stringp nil

### ISSUE THREAD

**Issue by simendsjo** [emacs-helm/helm#2001]
## Expected behavior
help-projectile opens project

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
Error is raised

## Steps to reproduce (recipe)
`helm-projectile-switch-project` then select project

## Backtraces if any (`M-x toggle-debug-on-error`)

![capture](https://user-images.githubusercontent.com/351519/37755895-90dd0ad2-2da7-11e8-9076-27dbcc282078.PNG)

## Describe versions of Helm, Emacs, operating system, etc.
- GNU Emacs 25.3.1 (x86_64-w64-mingw32) of 2017-09-12
- Spacemacs v.0.300.0 (develop branch commit 0fa3658cd8e283825dcd0a54ce1579dec55eb568)
- `helm-info-version` gives `helm-M-x: Wrong type argument: stringp, nil`
- Windows 10 v1709 (OS Build 16299.309)

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):
no
Couldn't get it working. Edited the script to find the correct emacs binary, but I get "No such file or directory, helm" when launching.

## IMPORTANT NOTE

Helm provides a script named `emacs-helm.sh` which runs Helm in a neutral
environment: no other packages and only minimal settings.

When possible, use it to reproduce your Helm issue to ensure no other package is
interfering.

To run it, simply switch to the directory where Helm is installed and call `./emacs-helm.sh`.

Thanks.

**Comment by simendsjo** [comment]
I've tried clearing all caches I've found, including elpa and redownloaded everything.

**Comment by simendsjo** [comment]
I also get the same error calling `helm-projectile-find-file`.. And probably a lot more

**Comment by simendsjo** [comment]
I should note that I got the same issue on GNU/Linux

**Comment by thierryvolpiatto** [comment]
simendsjo <notifications@github.com> writes:

> Expected behavior
>
> help-projectile opens project
>
> Actual behavior (from emacs-helm.sh if possible, see note at the bottom)
>
> Error is raised
>
> Steps to reproduce (recipe)
>
> helm-projectile-switch-project then select project

This is not part of Helm please report bug to helm-projectile.

> Backtraces if any (M-x toggle-debug-on-error)
>
> capture 
>
> Describe versions of Helm, Emacs, operating system, etc.
>
>   * GNU Emacs 25.3.1 (x86_64-w64-mingw32) of 2017-09-12
>   * Spacemacs v.0.300.0 (develop branch commit 0fa3658cd8e283825dcd0a54ce1579dec55eb568)
>   * helm-info-version gives helm-M-x: Wrong type argument: stringp, nil
>   * Windows 10 v1709 (OS Build 16299.309)
>
> Are you using emacs-helm.sh to reproduce this bug (yes/no):
>
> no
> Couldn't get it working. Edited the script to find the correct emacs binary, but I get "No such file or directory, helm" when launching.

You can't run a shell script on Windoze...

-- 
Thierry

**Comment by simendsjo** [comment]
> You can't run a shell script on Windoze...

I'm using msys to survive.

**Comment by thierryvolpiatto** [comment]
simendsjo <notifications@github.com> writes:

>     You can't run a shell script on Windoze...
>    
> I'm using msys to survive.

I don't know msys, but if it can run scripts, be sure to run the script
from the helm directory with ./emacs-helm.sh.
If your emacs binary is not "emacs", use 
./emacs-helm.sh -P /path/to/your/emacs.

-- 
Thierry

**Comment by simendsjo** [comment]
Hmm. Is there a known problem opening emacs-helm on Spacemacs? I get `byte-code: Cannot open load file: No such file or directory, helm`

**Comment by simendsjo** [comment]
Spacmacs has a complex folder structure, which is why I thought it might be related.

```sh
$ pwd
/home/simendsjo/.emacs.d/elpa/25.3/develop/helm-20180321.116
$ ./emacs-helm.sh
# Emacs starts, and I get the error that it cannot find helm
```

**Comment by thierryvolpiatto** [comment]
Try `./emacs-helm.sh --debug-init` to see if you have more infos on what's going on, I guess it is package.el which is confused by the uncommon setting of the elpa directory.

**Comment by simendsjo** [comment]
`--debug-init` doesn't give any additional info at all for what I can see.
