### ISSUE TITLE
Melpa update breakes helm-org-rifle

### ISSUE THREAD

**Issue by adam52** [emacs-helm/helm#2007]
I did an Upgrade recently, of all my packages on Melpa. Now when I run `helm-org-rifle` I am prompted for a "PATTERN:" (which I key in) and I can then select a result in the indirect buffer. 

However, when I hit `[enter]` to complete the selection, I receive an error message:

    Wrong number of arguments: (1 . 1), 0

Any ideas?

Thanks,
-Adam

**Comment by thierryvolpiatto** [comment]
adam52 <notifications@github.com> writes:

> I did an Upgrade recently, of all my packages on Melpa. Now when I run helm-org-rifle I am prompted for a "PATTERN:" (which I key in) and I can then select a result
> in the indirect buffer.
>
> However, when I hit [enter] to complete the selection, I receive an error message:
>
> Wrong number of arguments: (1 . 1), 0
>
> Any ideas?

Not until you send a backtrace (M-x toggle-debug-on-error).

Thanks.

-- 
Thierry

**Comment by adam52** [comment]
Here you go!

[backtrace.txt](https://github.com/emacs-helm/helm/files/1857111/backtrace.txt)

**Comment by thierryvolpiatto** [comment]
@alphapapa It seems you are using `helm-get-sources` somewhere, (in cleanup-hook) but the signature of this function have changed, it takes one argument SOURCES which is a list of sources, I think you don't need it anymore by using directly local variable `helm-sources`.

**Comment by thierryvolpiatto** [comment]
adam52 <notifications@github.com> writes:

> Here you go!
>
> backtrace.txt

Thanks!


-- 
Thierry

**Comment by adam52** [comment]
Ah! You fixed it!!

Here is the original code for the cleanup-hook, found in `helm-org-rifle.el`.

      (helm-cleanup-hook (lambda ()
                           ;; Close new buffers if enabled
                           (when helm-org-rifle-close-unopened-file-buffers
                             (if (= 0 helm-exit-status)
                                 ;; Candidate selected; close other new buffers
                                 (let ((candidate-source (helm-attr 'name (helm-get-current-source))))
                                   (dolist (source (helm-get-sources))
                                     (unless (or (equal (helm-attr 'name source)
                                                        candidate-source)
                                                 (not (helm-attr 'new-buffer source)))
                                       (kill-buffer (helm-attr 'buffer source)))))
                               ;; No candidates; close all new buffers
                               (dolist (source (helm-get-sources))
                                 (when (helm-attr 'new-buffer source)
                                   (kill-buffer (helm-attr 'buffer source))))))))))

and here is the revised code, taking your suggestions:

      (helm-cleanup-hook (lambda ()
                           ;; Close new buffers if enabled
                           (when helm-org-rifle-close-unopened-file-buffers
                             (if (= 0 helm-exit-status)
                                 ;; Candidate selected; close other new buffers
                                 (let ((candidate-source (helm-attr 'name (helm-get-current-source))))
                                   (dolist (source helm-sources)
                                     (unless (or (equal (helm-attr 'name source)
                                                        candidate-source)
                                                 (not (helm-attr 'new-buffer source)))
                                       (kill-buffer (helm-attr 'buffer source)))))
                               ;; No candidates; close all new buffers
                               (dolist (source helm-sources)
                                 (when (helm-attr 'new-buffer source)
                                   (kill-buffer (helm-attr 'buffer source))))))))))

Thanks Thierry!!!
