### ISSUE TITLE
helm ignore start with `.git` file. eg `.gitignore`, and `.gitconfig`

### ISSUE THREAD

**Issue by ncaq** [emacs-helm/helm#2009]
## Expected behavior

If I input `.git` to `helm-locate`, helm display `.gitignore`, and `.gitconfig`.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

helm ignore `.gitignore` and `.gitconfig`.

## Steps to reproduce (recipe)

1. startup `emacs-helm.sh`
2. <kbd>M-x</kbd>
3. `helm-locate`
4. input `\.git`

## Describe versions of Helm, Emacs, operating system, etc.

* helm-20180326.109
* GNU Emacs 25.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.26) of 2018-03-09
* Linux 4.14.24-gentoo
* mlocate 0.26

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):

yes

## IMPORTANT NOTE

Helm provides a script named `emacs-helm.sh` which runs Helm in a neutral
environment: no other packages and only minimal settings.

When possible, use it to reproduce your Helm issue to ensure no other package is
interfering.

To run it, simply switch to the directory where Helm is installed and call `./emacs-helm.sh`.

Thanks.

**Comment by thierryvolpiatto** [comment]
ncaq <notifications@github.com> writes:

> Expected behavior
>
> If I input .git to helm-locate, helm display .gitignore, and .gitconfig.
>
> Actual behavior (from emacs-helm.sh if possible, see note at the bottom)
>
> helm ignore .gitignore and .gitconfig.

Use "\\.git/" and "\\.git$" in helm-boring-file-regexp-list instead of
just "\\.git/?".

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
I have updated `helm-boring-file-regexp-list` docstring.
Thanks.
