### ISSUE TITLE
Cleanup function ignored

### ISSUE THREAD

**Issue by michael-heerdegen** [emacs-helm/helm#2010]
Hello,

since some time, a source of mine doesn't run its "cleanup" function any more.  It seems that the cleanup feature is not working in general.  Here is a recipe for emacs-helm.sh:

```
(defclass helm-test-source (helm-source-sync)
  ((candidates :initform (list "a" "b"))
   (cleanup :initform (lambda () (message "Cleanup!")))))

(helm :sources (helm-make-source "Test" 'helm-test-source))
```

No message appears after exiting the session, but AFAIU there should be one.

FWIW, there are these lines in "helm-cleanup":

```
    ;; Be sure we call this from helm-buffer.
    (helm-funcall-foreach 'cleanup)
```

but AFAICT after calling "bury-buffer" (that's done some lines before that) the "helm-buffer" is not current any more - at least here for me (Emacs master branch), and the list of sources can only be gotten locally from the "helm-buffer".

TIA, Michael.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> but AFAICT after calling "bury-buffer" (that's done some lines before
> that) the "helm-buffer" is not current any more - at least here for me
> (Emacs master branch), and the list of sources can only be gotten
> locally from the "helm-buffer".

Thanks to catch this, should work now.

I have sanitized usage of helm-sources that is now always local to
helm-buffer. It was working before (by chance) because of global value
staying around when quitting/exiting.

--
Thierry

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> Thanks to catch this, should work now.

Thanks!
