### ISSUE TITLE
Wrong-type-argument stringp nil in `Find files` source

### ISSUE THREAD

**Issue by dangom** [emacs-helm/helm#2013]
## Expected behavior
Run `helm-find-files` and it opens a helm window for file browsing.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
Not from emacs-helm.sh, as it complained no helm directory found.

Emacs complains :

> In ‘Find Files’ source: ‘helm-find-files-get-candidates’ 
>  (wrong-type-argument stringp nil)

## Steps to reproduce (recipe)

1. Open the scratch buffer
2. type `file:`
3. Place point immediately after the `:`
4. Run  `helm-find-files`

## Describe versions of Helm, Emacs, operating system, etc.

Helm from MELPA 20180331.2328 (why is there no helm-version variable?)
emacs-version is a variable defined in ‘C source code’.
Its value is "25.3.1"
MacOS 10.12.6

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):
NO, as it tells me "Cannot open load file: No such file or directory, helm"

## IMPORTANT NOTE

Helm provides a script named `emacs-helm.sh` which runs Helm in a neutral
environment: no other packages and only minimal settings.

When possible, use it to reproduce your Helm issue to ensure no other package is
interfering.

To run it, simply switch to the directory where Helm is installed and call `./emacs-helm.sh`.

Thanks.

**Comment by thierryvolpiatto** [comment]
Daniel Gomez <notifications@github.com> writes:

> Not from emacs-helm.sh, as it complained no helm directory found.

On macOS use the "-P" option to specify path:
./emacs-helm.sh -P /path/to/emacs

>
> Emacs complains :
>
>     In ‘Find Files’ source: ‘helm-find-files-get-candidates’
>     (wrong-type-argument stringp nil)

Thanks to catch this I can reproduce, to fix this use:

(add-to-list 'ffap-url-unwrap-remote "file")

This is again an issue with ffap.

I have committed a fix to not fail badly when ffap-url-unwrap-remote is
not set as above.

Thanks.
    

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
See also related issue #1716
