### ISSUE TITLE
Type error in helm-esh-get-candidates

### ISSUE THREAD

**Issue by jabranham** [emacs-helm/helm#2014]
## Expected behavior

```
M-x eshell
su
M-x helm-esh-pcomplete
```
I'd expect to be presented with a helm buffer of completions starting with "su"

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
```
In ‘Eshell completions’ source: ‘helm-esh-get-candidates’ 
 (wrong-type-argument stringp nil)
```

## Steps to reproduce (recipe)
```
./emacs-helm.sh
M-x eshell
su
M-x helm-esh-pcomplete
```

## Backtraces if any (`M-x toggle-debug-on-error`)
[debug.txt](https://github.com/emacs-helm/helm/files/1877866/debug.txt)

It's large, so I've attached it as a file.

## Describe versions of Helm, Emacs, operating system, etc.

helm bf58ccde0df420a314623d777b3f5e7363081223
Emacs 26.0.91 (GNU Emacs 26.0.91 (build 1, x86_64-pc-linux-gnu, X toolkit, Xaw3d scroll bars) of 2018-03-27)
Linux

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):
yes

**Comment by thierryvolpiatto** [comment]
Alex Branham <notifications@github.com> writes:

> Expected behavior
>
> M-x eshell
> su
> M-x helm-esh-pcomplete
>
> I'd expect to be presented with a helm buffer of completions starting with "su"
>
> Actual behavior (from emacs-helm.sh if possible, see note at the bottom)
>
> In ‘Eshell completions’ source: ‘helm-esh-get-candidates’ 
>  (wrong-type-argument stringp nil)
>
> Steps to reproduce (recipe)
>
> ./emacs-helm.sh
> M-x eshell
> su
> M-x helm-esh-pcomplete

Couldn't reproduce from ./emacs-helm.sh and my current emacs, tried with
emacs-25 and emacs-27 (master), didn't try with emacs-26 though.


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
According to your backtrace, it seems pcomplete didn't set its `pcomplete-stub` var to a string but to nil hence the `all-completions` error.
I could fix this by using something like `(or pcomplete-stub "")` but this will hide the problem pcomplete have with this emacs.

**Comment by thierryvolpiatto** [comment]
I diffed both pcomplete.el versions from Emacs-26 and 27 and didn't see significant changes.
Perhaps try to recompile both your emacs (make bootstrap) and helm.
If you are building helm from sources, you can use `make && sudo make install` and then use `helm` instead of `./emacs-helm.sh`.

**Comment by thierryvolpiatto** [comment]
![capture d ecran_2018-04-05_07-55-54](https://user-images.githubusercontent.com/1533939/38349351-e9a38c90-38a6-11e8-9131-891e697ce93d.png)

**Comment by jabranham** [comment]
Thanks for all the info. I recompiled emacs and helm and can't reproduce the issue anymore. I'll close this issue and reopen it if it pops up again later.
