### ISSUE TITLE
`helm-comp-read` does not receive backslashes as input

### ISSUE THREAD

**Issue by HuStmpHrrr** [emacs-helm/helm#2015]
## Expected behavior
it should recover input with slashes(possibly turn `\\` into `\`)

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
all backslashes are stripped

## Steps to reproduce (recipe)
1. (helm-comp-read "choose" nil)
2. type as many `\\\\\\\\\\` as you want. note that there is no input after `[?]`

note that it's very similar to #1712 but it's not the same bug.

## Describe versions of Helm, Emacs, operating system, etc.
helm version 0406
emacs 25.2.2
Ubuntu 17.10

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):
no, however, when I disable helm mode and try the same interactive function, I was able to input backslash.

**Comment by thierryvolpiatto** [comment]
Jason Hu <notifications@github.com> writes:

> Expected behavior
>
> it should recover input with slashes(possibly turn \\ into \)
>
> Actual behavior (from emacs-helm.sh if possible, see note at the bottom)
>
> all backslashes are stripped
>
> Steps to reproduce (recipe)
>
>  1. (helm-comp-read "choose" nil)
>  2. type as many \\\\\\\\\\ as you want. note that there is no input after [?]

Should be fixed now:

(helm-comp-read "choose: " nil) => \\\\ => "\\\\\\\\"

(helm-comp-read "choose: " nil :must-match t) => \\\\ => [No match]
Can't exit, must quit wit C-g

(helm-comp-read "choose: " nil :must-match 'confirm) => \\\\ => [confirm]
Second hit exit with "\\\\\\\\"

Same behavior with `completing-read`:

(completing-read "choose: " nil) => \\\\ => "\\\\\\\\"

(completing-read "choose: " nil nil t) => \\\\ => [No match]
Can't exit, must quit wit C-g

(completing-read "choose: " nil nil 'confirm) => \\\\ => [confirm]
Second hit exit with "\\\\\\\\"

Thanks.

-- 
Thierry

**Comment by HuStmpHrrr** [comment]
@thierryvolpiatto  thank you. do you mean by fixed in master? could you please point out what was the reason so that i can partially apply the change before the next release.

**Comment by HuStmpHrrr** [comment]
i see, you have done another release. thank you very much.
