### ISSUE TITLE
Edebug is broken for helm with emacs-25+ 

### ISSUE THREAD

**Issue by thierryvolpiatto** [emacs-helm/helm#2016]
When you want to use edebug with helm functions, and function run while helm is active edebug switch back to helm buffer and don't allow anymore stepping in function.
Workaround: Switch to emacs-24, recompile helm and edebug your function from emacs-24.

**Comment by thierryvolpiatto** [comment]
Probably edebug is broken as well for all functions switching to a minibuffer completion.

**Comment by thierryvolpiatto** [comment]
Even worst edebug crashes emacs after first C-g when stepping...

**Comment by mooseyboots** [comment]
i still have this issue on 27.1, damn it makes hacking around on helm impossible, all those `cl-loops` of mystery. did you ever find a work around?

**Comment by thierryvolpiatto** [comment]
mooseyboots ***@***.***> writes:

> i still have this issue on 27.1, damn it makes hacking around on helm
> impossible, all those cl-loops of mystery. did you ever find a work
> around?

No, unless the function you Edebug runs before the helm loop, Edebug is
not working with Helm.


-- 
Thierry
