### ISSUE TITLE
Helm does not use the helm-grep-match face properly.

### ISSUE THREAD

**Issue by it3ration** [emacs-helm/helm#2020]
## Expected behavior

When running a command such as `helm-grep-do-git-grep`, `helm` should use the `helm-grep-match` face to highlight any matches.

## Actual behavior

All of the other `helm-grep-.*` faces work except for the `helm-grep-match` face. If you do a `describe-face` in the `*helm-git-grep*` buffer, the face for matches is actually set to `bold`.

## Steps to reproduce (recipe)

Set the `helm-grep-match` face to something and then run `helm-grep-do-git-grep` and type something to trigger some matches. The `helm-grep-match` face will not be used.

Looks like other people have run into this issue [here](https://stackoverflow.com/questions/43425309/emacs-how-change-matching-color-for-command-helm-grep-do-git-grep).

## Describe versions of Helm, Emacs, operating system, etc.

```
helm-20180407.452
GNU Emacs 25.3.1 (x86_64-apple-darwin16.7.0) of 2017-09-12
macOS High Sierra
```

**Comment by it3ration** [comment]
Ah that's very unfortunate, `git`'s ansi colors are extremely limited. You can only choose from about 8 of them I think. Curious why the other faces work (aka, things like `helm-grep-file`). Aren't they also using the ansi colors?

**Comment by it3ration** [comment]
Hey, thanks for responding.

> Which is enough IMO.

No comment. :)

> There is no helm-grep-file command in helm.

I'm not talking about a command, I'm talking about the `helm-grep-file` face defined in `helm-grep.el`. All of the following faces work for me (the only one that doesn't is `helm-grep-match` and I think I understand why):

```
helm-grep-cmd-line
helm-grep-file
helm-grep-finish
helm-grep-lineno
```

Cheers, -it3ration

**Comment by thierryvolpiatto** [comment]
Kevin Depue <notifications@github.com> writes:

> I'm not talking about a command, I'm talking about the helm-grep-file
> face defined in helm-grep.el.

This one is active indeed even when using --color, ansi color is used
only for matches.

-- 
Thierry

**Comment by it3ration** [comment]
Ok thanks, I'll close the issue. :)
