### ISSUE TITLE
delete disorderly in minibuffer

### ISSUE THREAD

**Issue by ambjlon** [emacs-helm/helm#2022]
When delete in minibuffer(using command: helm-find-files), the display is in wild disorder as below:
![2018-03-30 10 49 55](https://user-images.githubusercontent.com/4489822/38908680-f24a9ee0-42f3-11e8-9715-d8861b794e2c.gif)

**Comment by thierryvolpiatto** [comment]
This is not emacs-helm.sh, please try to reproduce from emacs-helm.sh, this bug is not reproductible.

**Comment by thierryvolpiatto** [comment]
This issue is the same as you reported in #1982 and is not better, closing.
