### ISSUE TITLE
recursive helm-ff-run-grep fails to work as expected when using ack

### ISSUE THREAD

**Issue by oracleyue** [emacs-helm/helm#2023]
## Expected behavior

As described in your wiki (https://github.com/emacs-helm/helm/wiki/Grep):

> By default, the extension of the file at point is used when the cursor is on a file name. If the cursor is at root of a directory, all the file name extensions found in the directory and not matching the variable grep-find-ignored-files are inserted into the prompt.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

If using `grep` (set `helm-grep-default-recurse-command`), it behaves as expected, shown as the following figure.
However, when I use `ack`, it always pop up the list of all extensions that the default ackrc defines. It ignores the feature as expected, shown as the figure.

Could you check if you can repeat this issue?
I guess it's the setting of `helm` or `ack` (`.ackrc`)? How could I make helm recursive grep using `ack` work as expected? Many thanks!

<img width="586" alt="screen shot 2018-04-20 at 12 04 16" src="https://user-images.githubusercontent.com/5046605/39045475-4c0b6c66-4493-11e8-98b3-bfccf825d9cb.png">
<img width="581" alt="screen shot 2018-04-20 at 12 03 42" src="https://user-images.githubusercontent.com/5046605/39045891-9129e876-4494-11e8-9b8d-d7805d7876d9.png">

## Steps to reproduce (recipe)

Run the `emacs-helm.sh` and in the *scratch*, run 
```
(setq helm-grep-default-command
      "ack-grep -Hn --color --smart-case --no-group %e %p %f"
      helm-grep-default-recurse-command
      "ack-grep -H --color --smart-case --no-group %e %p %f")
```
(I use `ack` instead of `ack-grep` due the platform of OS X, which is installed by `brew install ack`).

Then go to any folder with text files, `C-x C-f`, placing the cursor on a regular text file (e.g. "a.tex"), then `C-u C-s` to run the recursive grep, see if it prompt `*.tex` or a long list of extensions.

## Describe versions of Helm, Emacs, operating system, etc.

- Helm: 2017.0903.117
- Helm-core: 2017.0902.2335
- Emacs: 25.3.1
- OS: OS X 10.12.6

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):
yes

## IMPORTANT NOTE

Helm provides a script named `emacs-helm.sh` which runs Helm in a neutral
environment: no other packages and only minimal settings.

When possible, use it to reproduce your Helm issue to ensure no other package is
interfering.

To run it, simply switch to the directory where Helm is installed and call `./emacs-helm.sh`.

Thanks.

**Comment by thierryvolpiatto** [comment]
Because ack doesn't work like grep, it is using types whereas grep use "--include"  option. All is working as expected.
Just hit RET on the type you are expecting and then type your pattern.
If you want more types add them to your .ackrc file.

**Comment by thierryvolpiatto** [comment]
Note that for recursive search you should use instead AG which is much more efficient specially with ripgrep.  Once you have installed a backend (rg, ag or pt) setup the command line with `helm-grep-ag-command` and use M-g a from helm-find-files or M-x helm-do-grep-ag from current-buffer.

**Comment by oracleyue** [comment]
@thierryvolpiatto All right. So it is due to the different mechanism of `ack`. Helm doesn't make `*helm ack-types*` behaves like `*helm grep exts*` that only lists the extension of the file where the current cursor. Am I right?

Thanks! Yes, I also install `ag`, and try it. So many choices, I am trying figure out which one to use.

**Comment by oracleyue** [comment]
@thierryvolpiatto Thanks! Yes, your suggest is great.
