### ISSUE TITLE
Proper way to avoid a (mostly harmless) error when using helm-find-file with file-name-handler-alist

### ISSUE THREAD

**Issue by sbroberg** [emacs-helm/helm#2025]
I do a lot of work with sqlite files, and I decided it would be cool to, when opening one, to have it automatically go into iSQL mode instead of presenting me with a buffer filled with the contents of the binary file.

I wanted this to be universal (working with C-x C-f, as well as find-file-at-point, etc.), so I did it by invoking iSQL in the file handler, followed by deleting the buffer to the actual sqlite file immediately after, this way:
```
    (defun sqlite-handler (operation &rest args)
      "An open hook that will invoke iSQL when opening sqlite files."
      (let ((sql-database (car args)))
        (kill-buffer nil)
        (sql-sqlite sql-database)
        (sql-set-sqli-buffer-generally)
        )
      )
    
    (put 'sqlite-handler 'operations '(insert-file-contents))
    
    (add-to-list 'file-name-handler-alist
                 '("\\.sqlite\\|\\.db\\'" . sqlite-handler))
```    
Problem is, since I'm using helm-find-files as my replacement for normal C-x C-f, I've noticed that whenever this code runs, I get this message afterwards:
```
    find-file-noselect-1: Wrong type argument: arrayp, nil
```
This is happening because helm-find-files still wants to do stuff with the buffer after my hook has run, but the buffer no longer exists due to my killing it:
```
    Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
      file-truename(nil)
      find-file-noselect-1(#<killed buffer> "~/Downloads/test.db" nil nil "~/Downloads/test.db" (95296428 16777222))
      find-file-noselect("/Users/sbroberg/Downloads/test.db" nil nil nil)
      find-file("/Users/sbroberg/Downloads/test.db")
      helm-find-file-or-marked("/Users/sbroberg/Downloads/test.db")
      helm-execute-selection-action-1()
      helm-execute-selection-action()
      helm-internal(helm-source-find-files "/Users/sbroberg/" "Find files or url: " nil nil "*helm find files*" nil "/Users/sbroberg/Command:" nil)
      apply(helm-internal (helm-source-find-files "/Users/sbroberg/" "Find files or url: " nil nil "*helm find files*" nil "/Users/sbroberg/Command:" nil))
      helm(helm-source-find-files "/Users/sbroberg/" "Find files or url: " nil nil "*helm find files*" nil "/Users/sbroberg/Command:" nil)
      apply(helm (helm-source-find-files "/Users/sbroberg/" "Find files or url: " nil nil "*helm find files*" nil "/Users/sbroberg/Command:" nil))
      helm(:sources helm-source-find-files :input "/Users/sbroberg/" :case-fold-search t :preselect nil :ff-transformer-show-only-basename t :default "/Users/sbroberg/Command:" :prompt "Find files or url: " :buffer "*helm find files*")
      helm-find-files-1("/Users/sbroberg/" nil)
      helm-find-files(nil)
      funcall-interactively(helm-find-files nil)
      call-interactively(helm-find-files nil nil)
      command-execute(helm-find-files)
```
Everything works as it should, other than the fact that my sqlite file never appears in my recent files list, since this failure above is apparently where helm-find-files is trying to resolve the truename of the file in order to add it to recent files.

Is there a better way I should be writing my hook so as to interact with helm more gracefully?

**Comment by thierryvolpiatto** [comment]
sbroberg <notifications@github.com> writes:

> Problem is, since I'm using helm-find-files as my replacement for
> normal C-x C-f, I've noticed that whenever this code runs, I get this
> message afterwards: find-file-noselect-1: Wrong type argument: arrayp,
> nil

Looks like you would have the same problem running emacs vanilla
"find-file", did you try with M-x find-file instead of M-x
helm-find-files ?

If you experiment the same problem you have to fix your code above, I am
afraid that there is nothing to do on helm side.  Let me know.

> This is happening because helm-find-files still wants to do stuff with
> the buffer after my hook has run,

It is not helm-find-files but find-file-noselect that does something with
the buffer-file-name.

--
Thierry

**Comment by sbroberg** [comment]
You're right - this isn't related to helm.
