### ISSUE TITLE
Get helm-find-files-map for locate?

### ISSUE THREAD

**Issue by girzel** [emacs-helm/helm#2026]
I understand that `helm-find-files-map` is separate from `helm-generic-files-map`, and probably for good reason, but I'd really like to have more of the `helm-find-files-map` actions available for the locate interface, in particular `helm-ff-mail-attach-files'.

I'm trying to decide which find-file command to use as my "regular find-file interface": `helm-find-files`, `helm-for-files`, and `helm-multi-files`. This last seems like the right one, since I like its "locate toggle" behavior, but after I've found files with locate, I can't attach them to messages!

**Comment by thierryvolpiatto** [comment]
Eric Abrahamsen <notifications@github.com> writes:

> I understand that helm-find-files-map is separate from
> helm-generic-files-map, and probably for good reason, but I'd really
> like to have more of the helm-find-files-map actions available for the
> locate interface, in particular `helm-ff-mail-attach-files'.
>
> I'm trying to decide which find-file command to use as my "regular
> find-file interface": helm-find-files, helm-for-files, and
> helm-multi-files.

helm-find-files is the more powerful interface for finding files... 

> This last seems like the right one, since I like its "locate toggle"
> behavior,

From helm-find-files see C-x C-f, C-u C-x C-f, C-u C-u C-x C-f for
locate and C-c / for find, see also how to find directories recursively
with e.g. "/home/you/..gnus/".
See C-h m from helm-find-files for more infos.

> but after I've found files with locate, I can't attach them to
> messages!

Ok, I have added this action, note that you can customize
`helm-type-file-actions` and add any key to `helm-generic-files-map` if
needed.
Also you can switch at any time to helm-find-files with C-x C-f and take
advantage of its actions.

For helm-find-files, see how you can add context actions here:

https://github.com/thierryvolpiatto/emacs-tv-config/blob/master/init-helm.el#L315

--
Thierry

**Comment by thierryvolpiatto** [comment]
Eric Abrahamsen <notifications@github.com> writes:

>> https://github.com/thierryvolpiatto/emacs-tv-config/blob/master/init-helm.el#L315
>
> That's really helpful, thank you -- if you don't mind, I'll edit the
> helm wiki in a bit and add that in.

Of course, thanks.


-- 
Thierry

**Comment by girzel** [comment]
Done!
