### ISSUE TITLE
How to use smart case temporarily  when using helm-occur

### ISSUE THREAD

**Issue by c02y** [emacs-helm/helm#2029]
I set `(setq helm-case-fold-search t)` in my init.el, so when I search "Abc", it will search "abc" and "Abc" or "ABC", but I need exact "Abc", so this means sometimes I need smart or not smart temporarily.

Is it able to smart search in `helm-occur` session temporarily? "temporarily" means when I am `helm-occur`, I can use another key (defined in `helm-moccur-map`) to toggle the variable to `smart`, after done `helm-occur`, it will be back to `(setq helm-case-fold-search t)`.

**Comment by thierryvolpiatto** [comment]
c02y <notifications@github.com> writes:

> I set (setq helm-case-fold-search t) in my init.el, so when I search "Abc", it will search "abc" and "Abc" or "ABC", but I need exact "Abc", so this means sometimes I
> need smart or not smart temporarily.
>
> Is it able to smart search in helm-occur session temporarily?

No.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
c02y <notifications@github.com> writes:

> I set (setq helm-case-fold-search t) in my init.el, so when I search "Abc", it will search "abc" and "Abc" or "ABC", but I need exact "Abc", so this means sometimes I
> need smart or not smart temporarily.

If you set helm-case-fold-search to 'smart, you will have what you ask.

-- 
Thierry
