### ISSUE TITLE
Max helm-window height

### ISSUE THREAD

**Issue by ghost** [emacs-helm/helm#203]
Often, when I have a tall frame and two windows side by side, helm chooses one of these, which means the helm choices are at the top of my frame and my minibuffer is all the way at the bottom. I really want to give helm a maximum height, like 7 lines or something, and have it always be a small window from the minibuffer to just 7 lines above it. I imagine this isn't hard, maybe it has something to do with `helm-show-completion-display-function`, but the source is very confusing to me so I can't reliably hack on it myself to get this behavior as I want.

**Comment by zw963** [comment]
Does this function implement yet?

popwin seem like not worked with me.

I just like this:

```
 +---+---+----------------+
 |   | B | C                    |
 | A +---+------------------+
 |   |   D                       |
 +---+---+--------------------+
 |     helm always here.   |
 +------------------------------+
```

**Comment by zw963** [comment]
here is a solution, Thanks.
https://www.reddit.com/r/emacs/comments/33qj0p/make_helm_window_always_at_the_bottom_using/
