### ISSUE TITLE
Helm TRAMP show directories

### ISSUE THREAD

**Issue by CeleritasCelery** [emacs-helm/helm#2030]
First off, thanks for this awesome package. The more I look into the code the more I realize what has gone into this.

I was looking at using helm via tramp, and everything works well, except for the the fact that there is no way to distinguish between directories and files. I looked into `helm-ff-tramp-not-fancy` and as you warned, disabling that makes tramp incredibly slow. I tried to update `helm-ff-filter-candidate-one-by-one` to only check `file-directory-p` when using tramp and it worked. Problem is that is now almost as slow as getting the file attributes and applying the face properties. 

Is there a way to distinguish files from directories when using helm with tramp without taking a large performance penalty?

**Comment by thierryvolpiatto** [comment]
Troy Hinckley <notifications@github.com> writes:

> First off, thanks for this awesome package. The more I look into the
> code the more I realize what has gone into this.

Thanks.

>
> I was looking at using helm via tramp, and everything works well,
> except for the the fact that there is no way to distinguish between
> directories and files. I looked into helm-ff-tramp-not-fancy and as
> you warned, disabling that makes tramp incredibly slow. I tried to
> update helm-ff-filter-candidate-one-by-one to only check
> file-directory-p when using tramp and it worked. Problem is that is
> now almost as slow as getting the file attributes and applying the
> face properties.

The problem are predicates, they are incredibly slow under tramp,
especially file-directory-p, I use file-attributes which is faster and
needs to be called only once, but it still too slow.

> Is there a way to distinguish files from directories when using helm
> with tramp without taking a large performance penalty?

Yes with file-name-all-completions, directories end with "/".
Of course there is no ways to guess if file is a symlink, an executable
file etc... without using again a predicate.

Try this patch:

diff --git a/helm-files.el b/helm-files.el
index 14474e8..7b4170a 100644
--- a/helm-files.el
+++ b/helm-files.el
@@ -2274,6 +2274,16 @@ purpose."
                        (list path))
                      (helm-ff-directory-files basedir t))))))
 
+(defun helm-list-directory (directory)
+  (cl-loop for f in (sort (file-name-all-completions "" directory)
+                          'string-lessp)
+           unless (or (member f '("./" "../"))
+                      (char-equal (aref f (1- (length f))) ?:))
+           if (and (helm--dir-name-p f)
+                   (helm--dir-file-name f directory))
+           collect (propertize it 'helm-ff-dir t)
+           else collect (expand-file-name f directory)))
+
 (defun helm-ff-directory-files (directory &optional full)
   "List contents of DIRECTORY.
 Argument FULL mean absolute path.
@@ -2284,8 +2294,7 @@ systems."
                    (expand-file-name directory)))
   (let* (file-error
          (ls   (condition-case err
-                   (directory-files
-                    directory full directory-files-no-dot-files-regexp)
+                   (helm-list-directory directory)
                  ;; Handle file-error from here for Windows
                  ;; because predicates like `file-readable-p' and friends
                  ;; seem broken on emacs for Windows systems (always returns t).
@@ -2619,7 +2628,9 @@ Return candidates prefixed with basename of `helm-input' first."
               (if (helm-dir-is-dot file)
                   file
                 (cons (or (helm-ff--get-host-from-tramp-invalid-fname file)
-                          basename)
+                          (if (get-text-property 1 'helm-ff-dir file)
+                              (propertize basename 'face 'helm-ff-directory)
+                            basename))
                       file))
             file)
         ;; Now highlight.


--
Thierry

**Comment by thierryvolpiatto** [comment]
See #2031

**Comment by thierryvolpiatto** [comment]
Looks fast enough to be usable, merged.

**Comment by CeleritasCelery** [comment]
Thanks! This is a huge improvement.
