### ISSUE TITLE
Display relative path of recenf in helm-recentf

### ISSUE THREAD

**Issue by azzamsa** [emacs-helm/helm#2033]
I use Emacs for presentation. Most of the time I need to access recentf. Since the screen became smaller in presentation (connected with projector). Reading long wrapped line of absolute path in recentf is a pain.

I want to ask if helm-recentf can parse recentf-list to relative path. e.g
~/foo/bar/baz/file.txt to ~/f/b/baz/file.txt

Thank you.

**Comment by kohnish** [comment]
basename is different from relative path. helm doesn't have an option but to print either the full path or the file name.

**Comment by thierryvolpiatto** [comment]
kohnish ***@***.***> writes:

> basename is different from relative path. helm doesn't have an option
> but to print either the full path or the file name.

No, helm-recentf is printing the abbreviated path of filename or the
basename, which is different.  Why would you want to print the relative path and
against which directory?

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.*Message ID: ***@***.***>

-- 
Thierry

**Comment by kohnish** [comment]
Sorry, I was talking about helm-find, despite the issue description.  

I have `find-program` set to the following shell script to support fuzzy recursively from project root with fzf and rg, so I don't need parent paths from the project root. For now I can patch `helm-findutils-transformer` to simply do nothing at abspath resolution.

```
#!/bin/bash
rg --files " |fzf --filter "${!#//\*/}" | head -n 50
```

**Comment by thierryvolpiatto** [comment]
kohnish ***@***.***> writes:

> Sorry, I was talking about helm-find, despite the issue description.

Ok, I just installed a new user var `helm-find-show-full-path-fn`,
customize it to your need.

-- 
Thierry

**Comment by kohnish** [comment]
It works splendidly with `(setopt helm-find-show-full-path-fn #'file-relative-name)`
Thanks you so much @thierryvolpiatto .
