### ISSUE TITLE
Feature request : make `helm-marked-candidates` returns properties

### ISSUE THREAD

**Issue by montag451** [emacs-helm/helm#2034]
`helm-get-selection` have an argument `force-display-part` which let you retrieve the selected candidate with its properties, it would be nice if `helm-marked-candidates` could do the same. I'm currently developing a helm source which attach metadata to candidates using text properties and I miss this feature.

**Comment by thierryvolpiatto** [comment]
montag451 <notifications@github.com> writes:

> helm-get-selection have an argument force-display-part which let you
> retrieve the selected candidate with its properties, it would be nice
> if helm-marked-candidates could do the same. I'm currently developing
> a helm source which attach metadata to candidates using text
> properties and I miss this feature.

I suggest you store your properties in the real part of candidates
instead of the display (if they are needed in the display put properties
in both), your candidate would looks like this:

    (DISPLAY . (propertize REAL 'metadata metadata))

--
Thierry

**Comment by montag451** [comment]
Yes it's what I was doing before but as I switched to `helm-source-in-buffer` it's not possible anymore (correct me if I'm wrong)

**Comment by thierryvolpiatto** [comment]
montag451 <notifications@github.com> writes:

> Yes it's what I was doing before but as I switched to
> helm-source-in-buffer it's not possible anymore (correct me if I'm
> wrong)

Use get-line attribute.

-- 
Thierry

**Comment by montag451** [comment]
> Use get-line attribute.

I'm already using it (I set it to `buffer-substring`) but if I'm not mistaken it is only used to extract line from `helm-candidate-buffer` to `helm-buffer` so it doesn't help in my case since `helm-marked-candidates` use `helm-get-selection` which removes properties by default.

**Comment by thierryvolpiatto** [comment]
Now you can use `:marked-with-props` slot when building your source:

```elisp
(cl-loop for c in (helm :sources (helm-build-in-buffer-source "test"
                                   :data '("foo" "bar" "baz")
                                   :marked-with-props 'withprop
                                   :candidate-transformer
                                   (lambda (candidates)
                                     (cl-loop for c in candidates
                                              for count from 1
                                              collect
                                              (propertize c 'data (format "%s%s" c count))))
                                   :action (lambda (c) (helm-marked-candidates)))
                        :buffer "*helm test*")
         collect (get-text-property 1 'data c))
;;=> ("foo1" "bar2" "baz3")

(cl-loop for c in (helm :sources (helm-build-in-buffer-source "test"
                                   :data '("foo" "bar" "baz")
                                   ;; :marked-with-props 'withprop
                                   :candidate-transformer
                                   (lambda (candidates)
                                     (cl-loop for c in candidates
                                              for count from 1
                                              collect
                                              (propertize c 'data (format "%s%s" c count))))
                                   :action (lambda (c) (helm-marked-candidates)))
                        :buffer "*helm test*")
         collect (get-text-property 1 'data c))
;;=> (nil nil nil)
```

**Comment by montag451** [comment]
Nice! Thank you!
