### ISSUE TITLE
Helm uses existing buffer instead of minibuffer expanding from bottom

### ISSUE THREAD

**Issue by l7ssha** [emacs-helm/helm#2035]
Hello, I didnt find answer in google (or just I'm ad at searching). In my environment helm to provide completions use existing buffer and dont create minibuffer expanding from bottom - I dont want this behaviour.
![image](https://user-images.githubusercontent.com/23033957/39890001-c88195fc-5499-11e8-85b0-839487e91a57.png)

EDIT: It works like that only when there are open 2+ buffer at once. Like neotree and clojure repl

Latest emacs, latest helm, config: [init.el](https://github.com/l7ssha/dotfiles/blob/master/emacs/init.el)
Arch Linux, 4.16.5-1-ARCH, Openbox WM

**Comment by thierryvolpiatto** [comment]
Szymon Uglis <notifications@github.com> writes:

> Hello, I didnt find answer in google (or just I'm ad at searching). In
> my environment helm to provide completions use existing buffer and
> dont create minibuffer expanding from bottom - I dont want this
> behaviour.

Helm doesn't display its candidates in minibuffer and will never do
this, you will find several variables to display helm candidates in
different windows or in separate frame.

--
Thierry

**Comment by l7ssha** [comment]
I've used wrong words. I want all time this behavior. Completion displayed in expanded from bottom buffer.
![image](https://user-images.githubusercontent.com/23033957/39908056-975048d6-54ec-11e8-9ffd-a5387c68d1a8.png)

**Comment by thierryvolpiatto** [comment]
Szymon Uglis <notifications@github.com> writes:

> I've used wrong words. I want all time this behavior. Completion displayed in expanded from bottom buffer.

See `helm-always-two-windows` or `helm-split-window-inside-p`.

-- 
Thierry

**Comment by cweiske** [comment]
For those ending up here from a search engine: The solution is at https://github.com/emacs-helm/helm/issues/2039#issuecomment-390103697
