### ISSUE TITLE
Open dired on a helm find file selection

### ISSUE THREAD

**Issue by EyalIO** [emacs-helm/helm#2043]
There seems to be no reasonable way to use helm-find-file to open a dired on a selected directory.

When the cursor is on a directory, there is no key that opens that directory in dired.

Pressing <return> to navigate into that directory, shows `.` and `..` entries. Opening dir-ed there still opens dired on the parent directory.

The only ways I found are:

* `<c-d>` and then another `<return>`: leaking an extra dired buffer I don't need.
* `<return> <down> <down> <c-d>`: very inconvenient.

**Comment by thierryvolpiatto** [comment]
EyalIO <notifications@github.com> writes:

> There seems to be no reasonable way to use helm-find-file to open a
> dired on a selected directory.

Wrong.

-- 
Thierry
