### ISSUE TITLE
. and .. entries in helm-find-file are not useful

### ISSUE THREAD

**Issue by EyalIO** [emacs-helm/helm#2044]
There should be a way to filter them out to avoid needing an extra 2 <down> presses to navigate away from them.

They don't serve any useful function from a UI perspective.

**Comment by thierryvolpiatto** [comment]
EyalIO <notifications@github.com> writes:

> There should be a way to filter them out to avoid needing an extra 2 presses to navigate away from them.
>
> They don't serve any useful function from a UI perspective.

This is your point of view, not mine, if I keep them it is for good
reasons.

Same comment as for #2045 for your bug report.

-- 
Thierry

**Comment by EyalIO** [comment]
What is the purpose of those 2 entries?
They require more keypresses to navigate, and don't apparently offer any UI functionality that would not exist without them just as efficiently.

**Comment by thierryvolpiatto** [comment]
This have been discussed several times.
