### ISSUE TITLE
Helm should allow seeing all the "boring" selections when only they remain

### ISSUE THREAD

**Issue by EyalIO** [emacs-helm/helm#2045]
e.g: When trying to navigate to the `*Messages*` buffer, you have to type out its full name.

It's fine that this buffer is filtered out of the completion list normally. But once *all* buffers are filtered out, it's much more useful to stop filtering out, allowing reaching even "hidden" or "boring" buffers.

**Comment by thierryvolpiatto** [comment]
Your bug report is not understandable, please follow the template like
everybody to fill in your bug report, describing step by step what you
are doing and what is wrong.

Thanks.

EyalIO <notifications@github.com> writes:

> e.g: When trying to navigate to the *Messages* buffer, you have to type out its full name.

Wrong.

--
Thierry
