### ISSUE TITLE
helm ignore eshell-directory-name

### ISSUE THREAD

**Issue by azzamsa** [emacs-helm/helm#2046]
## Expected behavior

Read `history` file from `.emacs.d/savefile/eshell/`

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

still check `history` file from `.emacs.d/eshell/`

## Steps to reproduce (recipe)

``` elisp
(use-package eshell
  :demand t
  :config
  (require 'helm-eshell)
  (setq eshell-directory-name
        (expand-file-name "eshell" azzamsa-savefile-dir))
  ;; very strange!. can't use `:bind' for eshell-mode-map
  (add-hook 'eshell-mode-hook
            #'(lambda ()
                (define-key eshell-mode-map (kbd "C-c C-l")
                  'helm-eshell-history))))
```

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):

Probably it's not a bug. I saw prelude using this behavior successfully.
I think it I miss something. But can't figure it out.

I treid to move,

``` elisp
  (setq eshell-directory-name
        (expand-file-name "eshell" azzamsa-savefile-dir))
```
outside use-package definition, trying to put inside `:init` but no luck.

Thanks for Helm.

**Comment by thierryvolpiatto** [comment]
azzamsa <notifications@github.com> writes:

> I treid to move,
>
>   (setq eshell-directory-name
>         (expand-file-name "eshell" azzamsa-savefile-dir))
>
> outside use-package definition, trying to put inside :init but no luck.

Yes, try to move it to :init instead of :config
Are you sure "azzamsa-savefile-dir" is known at this point of your emacs
initialization?
Anyway there is perhaps a bug in emacs, because:

(eval-after-load "eshell.el" (setq eshell-directory-name (expand-file-name "eshell" "~/tmp")))
works, but
(with-eval-after-load "eshell.el" (setq eshell-directory-name (expand-file-name "eshell" "~/tmp")))

And perhaps use-package is using with-eval-after-load internally (which
is the recommended way)?

Anyway, it is not a helm bug.

See my eshell config if that help:
https://github.com/thierryvolpiatto/emacs-tv-config/blob/master/init.el#L1529

-- 
Thierry

**Comment by azzamsa** [comment]
> Are you sure "azzamsa-savefile-dir" is known at this point of your emacs initialization?

Yes. I use this for recentf, savehist, etc

>  And perhaps use-package is using with-eval-after-load internally (which is the recommended way)?

For other packages. :init and :config works fine. :init loaded before package and :config after package loaded.

I tried to set the value after emacs-init hook. But it also doesn't work.

> Anyway, it is not a helm bug.

Oh sorry for that. I thought it was helm has hardcoded/uchanged value of eshell dir. And lookup eshell files default way.

[prelude](https://github.com/bbatsov/prelude/blob/007ae88ed29f950a37aff17d658b956bea7b0b92/core/prelude-editor.el#L352) successfully using this. Maybe I need time to figure it out.

Thank you for the hint. :)

**Comment by azzamsa** [comment]
By the way. this is the error message.

```
custom-initialize-reset: In ‘Eshell history’ source: ‘(lambda nil (with-helm-current-buffer (cl-loop for c from 0 to (ring-length eshell-history-ring) collect (eshell-get-history c))))’ 
 (error "Accessing an empty ring")
```

**Comment by azzamsa** [comment]
### problem solved

It turns out that `eshell-history-file-name` doesn't change. It's still pointing to default directory.

It solved using

``` elisp
(defconst azzamsa-savefile-dir (expand-file-name "savefile" user-emacs-directory))
(defconst azzamsa-eshell-dir (expand-file-name "eshell" azzamsa-savefile-dir))
```

``` elisp
(setq eshell-history-file-name
        (expand-file-name "history" azzamsa-eshell-dir))
```

[eshell history](https://www.gnu.org/software/emacs/manual/html_node/eshell/History.html)`
