### ISSUE TITLE
Feature Request: Show not matching results

### ISSUE THREAD

**Issue by Compro-Prasad** [emacs-helm/helm#2047]
This is a feature like `grep -v`. This has its use cases. If it is already there then how to enable it?

**Comment by thierryvolpiatto** [comment]
Compro Prasad <notifications@github.com> writes:

> This is a feature like grep -v. This has its use cases. If it is
> already there then how to enable it?

When candidates are fetched, there is not actually a feature like grep
-v to invert results to non matching, but you can negate your regexps
with "!".

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
![capture d ecran_2018-05-29_09-31-31](https://user-images.githubusercontent.com/1533939/40644440-89b0a578-6323-11e8-8dc6-ae2a12dd1002.png)

**Comment by Compro-Prasad** [comment]
Cool! Thanks!
