### ISSUE TITLE
helm-mini slow when executed from large buffers

### ISSUE THREAD

**Issue by sewkokot** [emacs-helm/helm#2048]
## Expected behavior
After C-x b (helm-mini) helm should give helm-mini buffer at the same time no matter what the buffer we are in at the time of executing the helm-mini command.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
When the current buffer is large e.g. 700k there need to wait 5 seconds to get the initial *helm-mini* buffer. 

## Steps to reproduce (recipe)
1. Visit a large buffer
2. M-x helm-mini
3. waiting for the *helm-mini* buffer

## The output of M-x profiler-report

```
- command-execute                                               10836  87%
 - call-interactively                                           10836  87%
  - funcall-interactively                                       10836  87%
   - helm-mini                                                   8235  66%
    - apply                                                      8235  66%
     - helm-mini--use-full-frame                                 8235  66%
      - let                                                      8235  66%
       - apply                                                   8235  66%
        - #<lambda 0x346592f5a074af90>                           8235  66%
         - helm                                                  8235  66%
          - apply                                                8226  66%
           - helm                                                8226  66%
            - apply                                              8226  66%
             - helm-internal                                     8221  66%
              - helm-initialize                                  7504  60%
               - helm-initial-setup                              7504  60%
                - helm-funcall-foreach                           7500  60%
                 - helm-funcall-with-source                      7500  60%
                  - apply                                        7500  60%
                   - helm-buffers-list--init                     7500  60%
                    - let                                        7500  60%
                     - let*                                      7500  60%
                      - while                                    7494  60%
                       - let*                                    7494  60%
                        - length                                 7494  60%
                         - save-current-buffer                   7490  60%
                          - if                                   7490  60%
                           - format-mode-line                    7490  60%
                            - eval                               7490  60%
                             - save-excursion                    7474  60%
                              - let                              7474  60%
                               - while                           7470  60%
                                - when                           7426  59%
                                 - if                            7418  59%
                                  - condition-case               7398  59%
                                   - dired-get-filename               7394  59%
                                    - let                        7338  59%
                                     - save-excursion               7338  59%
                                      - if                       7334  59%
                                       - setq                    7334  59%
                                        - dired-move-to-filename                     7314  59%
                                         + error                                       20   0%
```

## Describe versions of Helm, Emacs, operating system, etc.
emacs 26.1
helm from melpa: helm-20180527.2241
debian sid

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):
no

**Comment by Giedriusj1** [comment]
I think I managed to hit the same bug.

After binary chopping my .emacs file I found out that the slowness only occurs if I have dired+ enabled.

Without dired+ running helm-mini from display-packages buffer is instant, whereas with with dired+ it takes around 3-5 seconds.

I'm using emacs 26.1 and helm 20180607 form melpa on Fedora machine.

You can see my emacs config at https://github.com/Giedriusj1/emacs-config/blob/master/emacs.org (please note that I've currently disabled dired+ due to this slowness issue).

**Comment by thierryvolpiatto** [comment]
Giedrius <notifications@github.com> writes:

> Without dired+ running helm-mini from display-packages buffer is
> instant, whereas with with dired+ it takes around 3-5 seconds.

That's mean there is a problem with dired+, sorry I can do nothing on
the helm side.

--
Thierry

**Comment by Giedriusj1** [comment]
No worries Thierry, I can easily live without dired+ :)

**Comment by thierryvolpiatto** [comment]
Giedrius <notifications@github.com> writes:

> No worries Thierry, I can easily live without dired+ :)

As I most of the time use helm-find-files I rarely use dired but when I
use it I use this configuration:
https://notabug.org/thievol/emacs-config/src/master/dired-extension.el

HTH.

-- 
Thierry

**Comment by Giedriusj1** [comment]
TBH, I'm not a big dired user either. I think I've only used dired+ to give me a bit more colorful output. 

I might steal your dired-extension to do that. Thanks!

**Comment by sewkokot** [comment]
@Giedriusj1, thank you for narrowing down the issue to dired+.el. From my profiler-report it seems that dired+ redefines dired-get-filename function which in turn uses the slowing-down dired-move-to-filename function. I will file a bug to the author of dired+.
