### ISSUE TITLE
Helm has problems with dedicated windows

### ISSUE THREAD

**Issue by ermingol23** [emacs-helm/helm#2050]
## Expected behavior
With Emacs in a single frame and within the frame there are two windows where one of the windows is dedicated to a specific buffer. When calling helm-find-files Helm is able to cope with this siutation when for instance previewing a file and not cause any "Error running timer: (wrong-type-argument window-live-p nil)" or "Wrong-type-argument: window-live-p nil" in the minibuffer when editing file path.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
I do not get the problem as Emacs starts with a single frame with a single non-dedicated window. However if I split the initial *scratch* buffer in two (e.g. C-x 3), make one of the windows dedicated (evaluating (set-window-dedicated nil t) in *scratch* buffer) and switch to the other buffer I can reproduce the problem.

## Steps to reproduce (recipe)
1) After Emacs has started (assuming you just get the *scratch* buffer) split window in two, e.g. C-x 3

2) In the right window evaluate (set-window-dedicated-p nil t) to make that window dedicated

3) Switch to the other buffer, e.g. C-x o

4) Call helm-find-files, C-x C-f

5) Type random file name (which does not exist), e.g. "foo"

5) Press C-j twice; you will get "Wrong-type-argument: window-live-p nil" in mini-buffer

6) Press Left cursor key within minibuffer; you will get "Wrong-type-argument: window-live-p nil" in minibuffer

Note: The situation has improved slightly between 2.9.0 and 2.9.4. In 2.9.0 you would not even get a preview window of the file which you do get in 2.9.0.

On the other hand if the initial buffer is split in 3 buffers the problem seems to be gone. What happens is that the preview and *helm find files* buffers are shown in separate buffers so both are visible at the sime time.

## Backtraces if any (`M-x toggle-debug-on-error`)
No backtraces are produced.

## Describe versions of Helm, Emacs, operating system, etc.
Helm 2.9.4, Emacs 25.2, CentOS 6, x86 hardware.

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):
Yes, after following the steps to reproduce the problem. One difference is that I get also "Error running timer: (wrong-type-argument window-live-p nil)" in the minibuffer when pressing delete within the minibuffer.

## IMPORTANT NOTE

Helm provides a script named `emacs-helm.sh` which runs Helm in a neutral
environment: no other packages and only minimal settings.

When possible, use it to reproduce your Helm issue to ensure no other package is
interfering.

To run it, simply switch to the directory where Helm is installed and call `./emacs-helm.sh`.

Thanks.

**Comment by thierryvolpiatto** [comment]
Thanks to catch this.

ermingol23 <notifications@github.com> writes:

> Expected behavior
>
> With Emacs in a single frame and within the frame there are two
> windows where one of the windows is dedicated to a specific
> buffer. When calling helm-find-files Helm is able to cope with this
> siutation when for instance previewing a file and not cause any "Error
> running timer: (wrong-type-argument window-live-p nil)" or
> "Wrong-type-argument: window-live-p nil" in the minibuffer when
> editing file path.

Should work now, let me know.

The problem with this situation is that when helm starts, there is one
window for helm and the other window which is dedicated, so when PA
starts the only window available it find is the helm-window itself and
takes it place leaving helm in a bad situation with no more helm-window.
The only way to fix this is splitting the dedicated window to leave one
room for PA.
The downside is that once you run PA your dedicated window will be
splitted until you quit helm.

> Steps to reproduce (recipe)
>
>  1. After Emacs has started (assuming you just get the scratch buffer) split window in two, e.g. C-x 3
>
>  2. In the right window evaluate (set-window-dedicated-p nil t) to make that window dedicated
>
>  3. Switch to the other buffer, e.g. C-x o
>
>  4. Call helm-find-files, C-x C-f
>
>  5. Type random file name (which does not exist), e.g. "foo"
>
>  6. Press C-j twice; you will get "Wrong-type-argument: window-live-p nil" in mini-buffer
>
>  7. Press Left cursor key within minibuffer; you will get "Wrong-type-argument: window-live-p nil" in minibuffer

Thanks for the good report and the recipe as well.


--
Thierry

**Comment by ermingol23** [comment]
> Should work now, let me know.

Thank you for extremely fast response! I'll try it out tomorrow and let you know what I think of it.


> The only way to fix this is splitting the dedicated
> window to leave one room for PA. The downside
> is that once you run PA your dedicated window
> will be splitted until you quit helm.

Question: Why can't you split the Helm window instead of the dedicated window? Or just ignore the dedicated window and behave in the same way as if you just had a single window (that is fall back to reusing the same window as the Helm buffer uses)? In this way you get consistent behavior for the two cases

1) Single Emacs frame with single window.

2) Single Emacs frame with two windows where one of them is dedicated.

If you ignore all dedicated windows when trying to locate a suitable window to (re)use you will also be able to handle the case when there are multiple dedicated windows and a single non-dedicated window. And from a users point of view there is no perceptual difference between the two cases. Principle of least surprise. 😁

I really do not like the idea of permanently splitting the dedicated window and would like to avoid that situation. For me a dedicated window is more or less "Hands off! Don't touch!" for other libraries/modules than the one who created the window.

In this case the dedicated window is actually just 23 characters wide (holds a "mini map" of current buffer). Thus it is extremely ill situated to hold anything else, and splitting it does not improve the situation (apart from getting rid of the error message).

**Comment by thierryvolpiatto** [comment]
Fixed as well with diff in helm-ls-git.
https://github.com/emacs-helm/helm-ls-git/commit/ceeac5c89a3db7868ff94e5ac272bc1cd9262aa0

**Comment by ermingol23** [comment]
I have now tried latest (commit 8a421fc) on master together with helm.el found on branch PA_window_with_dedicated_win and I can confirm that the error message is no longer and that the preview appears in a temporary split dedicated window.

**Comment by thierryvolpiatto** [comment]
ermingol23 <notifications@github.com> writes:

> I have now tried latest (commit 8a421fc) on master together with
> helm.el found on branch PA_window_with_dedicated_win and I can confirm
> that the error message is no longer and that the preview appears in a
> temporary split dedicated window.

Great! Thanks.

--
Thierry
