### ISSUE TITLE
helm-imenu-in-all-buffers error

### ISSUE THREAD

**Issue by blaenk** [emacs-helm/helm#2052]
## Expected behavior

`M-x helm-imenu-in-all-buffers` to work.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

It never comes up and an error is printed.

## Steps to reproduce (recipe)

`M-x helm-imenu-in-all-buffers`

## Backtraces if any (`M-x toggle-debug-on-error`)

```
Debugger entered--Lisp error: (error "No buffer named *helm imenu all*")
  helm-funcall-foreach(init nil)
  helm-initial-setup(("\\_<\\_>" nil) nil)
  helm-initialize(nil nil ("\\_<\\_>" nil) nil)
  helm-internal(nil nil nil nil nil "*helm imenu all*" nil ("\\_<\\_>" nil) nil)
  apply(helm-internal (nil nil nil nil nil "*helm imenu all*" nil ("\\_<\\_>" nil) nil))
  helm(nil nil nil nil nil "*helm imenu all*" nil ("\\_<\\_>" nil) nil)
  apply(helm (nil nil nil nil nil "*helm imenu all*" nil ("\\_<\\_>" nil) nil))
  helm(:sources nil :default ("\\_<\\_>" nil) :preselect nil :buffer "*helm imenu all*")
  helm-imenu-in-all-buffers()
  funcall-interactively(helm-imenu-in-all-buffers)
  call-interactively(helm-imenu-in-all-buffers record nil)
  command-execute(helm-imenu-in-all-buffers record)
  helm-M-x(nil #("helm-imenu-in-all-buffers" 0 25 (match-part "helm-imenu-in-all-buffers")))
  funcall-interactively(helm-M-x nil #("helm-imenu-in-all-buffers" 0 25 (match-part "helm-imenu-in-all-buffers")))
  call-interactively(helm-M-x nil nil)
  command-execute(helm-M-x)
```

## Describe versions of Helm, Emacs, operating system, etc.

GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-06-02

helm-20180602.2115
helm-core-20180602.851

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):

When I run with `emacs-helm.sh` it does work! :)

I tried it in a project with only emacs-lisp files were open and it worked, so I'm thinking it has something to do with the fact that I'm in a typescript project with [tide](https://github.com/ananthakumaran/tide) and [typescript-mode](https://github.com/ananthakumaran/typescript.el)? Individual `helm-imenu` works perfectly fine.

I'm happy to investigate further but I'm wondering if you have any clues at all based on the backtrace which you may better understand than me.

## IMPORTANT NOTE

Helm provides a script named `emacs-helm.sh` which runs Helm in a neutral
environment: no other packages and only minimal settings.

When possible, use it to reproduce your Helm issue to ensure no other package is
interfering.

To run it, simply switch to the directory where Helm is installed and call `./emacs-helm.sh`.

Thanks.

**Comment by thierryvolpiatto** [comment]
Jorge Israel Peña <notifications@github.com> writes:

> Are you using emacs-helm.sh to reproduce this bug (yes/no):
>
> When I run with emacs-helm.sh it does work! :)

What is the mode running in the buffer from where you are calling
h*imenu?

> I'm curious if you have any suggestions/leads to investigate based on the backtrace?

No, apart helm-funcall-foreach is called with no sources which is not
normal.

> I noticed when I ran M-x helm-imenu-in-all-buffers again with the
> cursor on the end of the emacs-version string, I got this backtrace:
>
> Debugger entered--Lisp error: (error "No buffer named *helm imenu all*")
>   helm-funcall-foreach(init nil)

> I then tried it when emacs-lisp files were open and it worked, so I'm
> thinking it has something to do with the fact that I'm in a typescript
> project with tide and typescript-mode?

Perhaps yes. When it is working with emacs-helm.sh and not in your main
emacs, that's generally there is a mode interfering somewhere.

> Individual helm-imenu works perfectly fine.

In same buffer?

> I'm happy to investigate further but I'm wondering if you have any
> clues at all based on the backtrace which you may better understand
> than me.

No, for now I don't know why it fail, I use this always when developing
helm and noticed no failures.

--
Thierry

**Comment by blaenk** [comment]
The mode was `typescript-mode` with `tide` (further typescript features) also running.

I investigated some more by looking through their source, and only tide seems to have anything regarding imenu. Basically it has a custom `imenu-create-index-function`:

https://github.com/ananthakumaran/tide/blob/fa5a594fd68bd1cff303b60cccc0a703cad50d07/tide.el#L1797-L1799

https://github.com/ananthakumaran/tide/blob/fa5a594fd68bd1cff303b60cccc0a703cad50d07/tide.el#L1581-L1613

I did notice that there's a `tide-imenu-flatten` option that's off by default. I set it to `t` and now `helm-imenu-in-all-buffers` doesn't crash. The problem now is that it's empty, even though an individual buffer's `helm-imenu` works perfectly with `tide-imenu-flatten` set or not.

I'll update if I find anything else, but I'd be happy to hear if you have any theories, ideas, or suggestions.

**Comment by blaenk** [comment]
I stepped through `helm-imenu-candidates-in-all-buffers` and noticed that `(derived-mode-p 'prog-mode)` was evaluating to `nil`. I investigated and found this:

https://github.com/ananthakumaran/typescript.el/blob/7a5c74d88e3c5513cc4431a837003736f905a75e/typescript-mode.el#L2588-L2593

It seems like this is causing `typescript-mode` to not register as a mode deriving from `prog-mode`.

I'm going to open an issue there to see what they think.

**Comment by blaenk** [comment]
Opened an issue there, but I'm also curious if the `prog-mode` check is really necessary? For example, I use `markdown-mode`'s imenu a lot to jump to a markdown buffer's particular heading and I don't imagine that it derives from prog-mode, in fact it derives from text-mode which I don't imagine derives from prog-mode either:

https://github.com/jrblevin/markdown-mode/blob/master/markdown-mode.el#L9424

And yet it would be very nice to be able to use `helm-imenu-in-all-buffers`.

Is there a chance we could remove the check or something to allow it to work in these buffers?

**Comment by thierryvolpiatto** [comment]
Jorge Israel Peña <notifications@github.com> writes:

> Opened an issue there, but I'm also curious if the prog-mode check is
> really necessary?

Yes we have to skip buffers where imenu is not handled like text-mode
etc... for sake of performance.
However you are right that some mode derived from text-mode are imenu
compatible like MD, I have added for this a new user variable where you
can add extra modes:

    (setq helm-imenu-extra-modes '(markdown-mode))

Also hopefully I could reproduce your error when trying imenu all in
markdown-mode, should now be fixed.

Thanks.

-- 
Thierry

**Comment by blaenk** [comment]
Thanks!

I think I'll close this now as the issue does seem to be with typescript-mode and its developers are now aware of it.
