### ISSUE TITLE
helm-delete-file always bypasses trash (Mac OS 10.12.6)

### ISSUE THREAD

**Issue by cmccloud** [emacs-helm/helm#2053]
I'm assuming this isn't intentional behavior - I looked through the issue tracker and didn't see any mention of it in the past, so it was hard to know. 

## Expected behavior
Calling `helm-ff-run-delete-file` from `helm-find-files` should respect  value of `delete-by-moving-to-trash`
## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
`helm-delete-file` bypasses trash in all cases. Expected behavior is observed when the function is altered to pass the optional trash argument to `delete-directory` and `delete-file`. 

```elisp
(defun helm-delete-file (file &optional error-if-dot-file-p synchro)
  "Delete the given file after querying the user.
Ask to kill buffers associated with that file, too."
  (require 'dired)
  (cl-block nil
    (when (and error-if-dot-file-p
               (helm-ff-dot-file-p file))
      (error "Error: Cannot operate on `.' or `..'"))
    (let ((buffers (helm-file-buffers file))
          (helm--reading-passwd-or-string t))
      (cond ((and (not (file-symlink-p file))
                  (file-directory-p file)
                  (directory-files file t dired-re-no-dot))
             ;; Synchro means persistent deletion from HFF.
             (if synchro
                 (when (y-or-n-p (format "Recursive delete of `%s'? "
                                         (abbreviate-file-name file)))
                   (delete-directory file 'recursive t))
               ;; Avoid using dired-delete-file really annoying in
               ;; emacs-26 but allows using ! (instead of all) to not
               ;; confirm anymore for recursive deletion of
               ;; directory. This is not persistent for all session
               ;; like emacs-26 does with dired-delete-file (think it
               ;; is a bug).
               (if (eq helm-ff-allow-recursive-deletes 'always)
                   (delete-directory file 'recursive t)
                 (pcase (helm-read-answer (format "Recursive delete of `%s'? [y,n,!,q]"
                                                 (abbreviate-file-name file))
                                         '("y" "n" "!" "q"))
                   ("y" (delete-directory file 'recursive t))
                   ("!" (setq helm-ff-allow-recursive-deletes 'always)
                         (delete-directory file 'recursive t))
                   ("n" (cl-return 'skip))
                   ("q" (throw 'helm-abort-delete-file
                           (message "Abort file deletion")))))))
            ((and (not (file-symlink-p file))
                  (file-directory-p file))
             (delete-directory file nil t))
            (t (delete-file file t)))
      (when buffers
        (cl-dolist (buf buffers)
          (when (y-or-n-p (format "Kill buffer %s, too? " buf))
            (kill-buffer buf)))))))
```
## Steps to reproduce (recipe)
Given how the function is called, I would expect to see the same behavior on another OS as well, but here is the recipe for on Mac. 

From emacs-helm.sh =>

(customize-set-variable 'delete-by-moving-to-trash t)
(load "/Users/Macnube/.emacs.d/elpa/osx-trash-20160520.600/osx-trash.el")
(osx-trash-setup)

## Describe versions of Helm, Emacs, operating system, etc.
Emacs: 27.0.50
Helm: helm-20180602.851
OS: Mac OS Sierra 10.12.6

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):
Yes

**Comment by thierryvolpiatto** [comment]
Christopher McCloud <notifications@github.com> writes:

> I'm assuming this isn't intentional behavior

No, I have modified helm-delete-file to not use dired-delete-file and I
forget to use the TRASH argument in delete-file/directory calls.
Sorry, should work now.

Thanks.

-- 
Thierry

**Comment by cmccloud** [comment]
No problem at all, thank you for both the quick response and all the work you put into helm, it really shows and I enjoy using it tremendously. 

Take care.
