### ISSUE TITLE
Question about helm-grep-do-git-grep and regexps.

### ISSUE THREAD

**Issue by it3ration** [emacs-helm/helm#2060]
Hey @thierryvolpiatto,

I've been using `helm-grep-do-git-grep` and it's nice and fast. Is there some way to use regular expressions as I would in `helm-occur`? I've tried setting `helm-grep-git-grep-command` to the following but things still don't seem to work:

`(setq helm-grep-git-grep-command "git --no-pager grep -n%cH --color=always --exclude-standard --no-index --full-name --basic-regexp -e %p -- %f")`

I also noticed that when I tried to use a regexp with `helm-grep-do-git-grep` that it seems to split up my regexp in weird ways, chaining the actual calls to both `git grep` and `grep`. For example, typing the following:

`class\ Foo Bar`

results in the following command:

`git --no-pager grep -nH --color=always --exclude-standard --no-index --full-name -e class\\s-Foo --   | grep --color=always  Bar`

I would have expected this to result in two regexps fed to `git grep`, namely, `class\ Foo` and `Bar`.

Thanks in advance, just hoping to figure this out as regexps are essential to my workflow.

Best, -it3ration

**Comment by thierryvolpiatto** [comment]
Kevin Depue <notifications@github.com> writes:

> Hey @thierryvolpiatto,
>
> I've been using helm-grep-do-git-grep and it's nice and fast. Is there
> some way to use regular expressions as I would in helm-occur?

Not exactly, some regexps are specific to emacs e.g. \_>

> I've tried setting helm-grep-git-grep-command to the following but
> things still don't seem to work:
>
> (setq helm-grep-git-grep-command "git --no-pager grep -n%cH --color=always --exclude-standard --no-index --full-name --basic-regexp -e %p -- %f")

"--basic-regexp" is the default IIRC so this is the same as default command.

> I also noticed that when I tried to use a regexp with helm-grep-do-git-grep that it seems to split up my regexp in weird ways, chaining the actual calls to
> both git grep and grep. For example, typing the following:
>
> class\ Foo Bar

Try "Class\sFoo Bar" instead.

-- 
Thierry

**Comment by it3ration** [comment]
Hey thanks for the response. Is there any way to use Emacs-style regexps? (aka, `\ ` instead of `\s`)?

Cheers, -it3ration

**Comment by thierryvolpiatto** [comment]
Kevin Depue <notifications@github.com> writes:

> Hey thanks for the response. Is there any way to use Emacs-style
> regexps? (aka, \ instead of \s)?

No because matching is done by the backend (git-grep) and not helm.
Same for helm-do-grep-ag, you have to use this time PCRE regexp which is
something even different (different from posix and emacs-lisp regexp styles).

--
Thierry

**Comment by it3ration** [comment]
Is it possible to change the regular expression family used by specifying one of the following command line options to `git grep`?

```
[-E | --extended-regexp] 
[-G | --basic-regexp]
[-P | --perl-regexp]
```

It seems that the regex you type into `helm` is being preprocessed before getting to `git grep`. That would explain why `class\ Foo Bar` is translated to the command:

`git --no-pager grep -nH --color=always --exclude-standard --no-index --full-name -e class\\s-Foo -- | grep --color=always Bar`

Is there some way to disable this behaviour so I can use Emacs-style regular expressions?

Cheers, -it3ration

**Comment by thierryvolpiatto** [comment]
Kevin Depue <notifications@github.com> writes:

> Is it possible to change the regular expression family used by specifying one of the following command line options to git grep?
>
> [-E | --extended-regexp]
> [-G | --basic-regexp]
> [-P | --perl-regexp]

No I don't want to enter in these details, a lot of work for few
benefit.

> It seems that the regex you type into helm is being preprocessed
> before getting to git grep. That would explain why class\ Foo Bar is
> translated to the

Yes indeed, I have commited a change that allow typing an escaped space
in grep and ag.

Thanks.

--
Thierry

**Comment by it3ration** [comment]
Ok thanks! -it3ration
