### ISSUE TITLE
helm-find-files no longer prompts to make missing directories

### ISSUE THREAD

**Issue by daewok** [emacs-helm/helm#2061]
## Expected behavior

helm-find-files prompts to make missing directories when opening a file in a folder that does not exist.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

There is no prompt to make missing directories. Instead, the file is found or created in the current directory.

## Steps to reproduce (recipe)

cd helm
./emacs-helm.sh
C-x C-f /tmp/nonexistent-folder/emacs-helm.sh

The emacs-helm.sh script is opened in the new buffer instead of making a new folder and file.

## Describe versions of Helm, Emacs, operating system, etc.
Helm - Current master (40cd9fd39b)
Emacs - 26.1
OS - Gentoo

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):

yes

**Comment by daewok** [comment]
Bisecting suggests that 72b6ff330 introduced this behavior.

**Comment by thierryvolpiatto** [comment]
daewok <notifications@github.com> writes:

> Bisecting suggests that 72b6ff3 introduced this behavior.

Thanks, I have reverted this change.

-- 
Thierry
