### ISSUE TITLE
helm-latex-math-candidates doesn't traverse the whole "Math" menu

### ISSUE THREAD

**Issue by scaramouche1** [emacs-helm/helm#2062]
The "Math" menu in AucTeX (whose content is stored in the variable `LaTeX-math-menu`) has some nested folders.  For example, the entry "AMS" has subfolders "Hebrew" , "Greek lowercase", ...).

Currently, `helm-insert-latex-math` does not display the items in these subfolders.  I think the solution is to fix `helm-latex-math-candidates` so that it traverses `LaTeX-math-menu` recursively.  I have been searching for a simple way of accomplishing this (using the seq or dash libraries) but haven't found one.

**Comment by thierryvolpiatto** [comment]
scaramouche1 <notifications@github.com> writes:

> The "Math" menu in AucTeX (whose content is stored in the variable
> LaTeX-math-menu) has some nested folders. For example, the entry "AMS"
> has subfolders "Hebrew" , "Greek lowercase", ...).
>
> Currently, helm-insert-latex-math does not display the items in these
> subfolders. I think the solution is to fix helm-latex-math-candidates
> so that it traverses LaTeX-math-menu recursively. I have been
> searching for a simple way of accomplishing this (using the seq or
> dash libraries) but haven't found one.

I don't use Auctex actually so I have no idea of how looks the
LaTeX-math-menu structure, perhaps you can send it here?
Anyway, we don't need seq and/or dash to loop in such a list.

--
Thierry

**Comment by thierryvolpiatto** [comment]
scaramouche1 <notifications@github.com> writes:

> Below I'm including a screenshot showing the recursive structure of
> LaTeX-math-menu.

Thanks but this doesn't help, please attach the value of `LaTeX-math-menu`.

-- 
Thierry

**Comment by scaramouche1** [comment]
I'm attaching the content of `LaTeX-math-menu` (output of C-h v).  You'll see, for example, that the subsubfolder `AMS > Hebrew` starts in line 292.

I believe that the problem is that the following function (in `helm-misc.el`) only collects the symbols in the first level of folders in `LaTeX-math-menu`, while it should recursively traverse it.

    (defun helm-latex-math-candidates ()
      "Collect candidates for latex math completion."
      (cl-loop for i in (cddr LaTeX-math-menu)
            for elm = (cl-loop for s in i when (vectorp s)
                            collect (cons (aref s 0) (aref s 1)))
            append elm))
 
[LaTeX-math-menu.txt](https://github.com/emacs-helm/helm/files/2172800/LaTeX-math-menu.txt)

**Comment by scaramouche1** [comment]
(seems I closed the issue by mistake)

**Comment by thierryvolpiatto** [comment]
Thanks for the list.
Is something like this working for you (i.e. do you have all candidates listed?):

```elisp

(defun helm-latex--math-collect (seq)
  (cl-loop for s in seq when (vectorp s)
           collect (cons (aref s 0) (aref s 1))))

(defun helm-latex-math-candidates ()
  "Collect candidates for latex math completion."
  (cl-loop for i in LaTeX-math-menu
           append (cond ((vectorp i)
                         (list (cons (aref i 0) (aref i 1))))
                        ((listp i)
                         (cl-loop for s in (assoc-default (car i) LaTeX-math-menu)
                                  collect (cond ((listp s)
                                                 (helm-latex--math-collect s))
                                                ((vectorp s)
                                                 (cons (aref s 0) (aref s 1)))))))))
```

**Comment by thierryvolpiatto** [comment]
Sorry, I forget one level, use this one instead:

```elisp
(defun helm-latex--math-collect (seq)
  (cl-loop for s in seq when (vectorp s)
           collect (cons (aref s 0) (aref s 1))))

(defun helm-latex-math-candidates ()
  "Collect candidates for latex math completion."
  (cl-loop for i in LaTeX-math-menu
           nconc (cond ((vectorp i)
                        (list (cons (aref i 0) (aref i 1))))
                       ((listp i)
                        (cl-loop for s in (assoc-default (car i) LaTeX-math-menu)
                                 nconc (cond ((listp s)
                                               (helm-latex--math-collect s))
                                              ((vectorp s)
                                               (list (cons (aref s 0) (aref s 1))))))))))
```

**Comment by thierryvolpiatto** [comment]
```elisp
(setq LaTeX-math-menu '("Math"
                        ["foo" val0 t]
                        ("bar"
                         ["baz" val1 t])
                        ("aze"
                         ["zer" val2 t])
                        ("AMS"
                         ("rec"
                          ["fer" val3 t])
                         ("rty"
                          ["der" val4 t]))))
(helm-latex-math-candidates)
;; =>
(("foo" . val0)
 ("baz" . val1)
 ("zer" . val2)
 ("fer" . val3)
 ("der" . val4))
```

**Comment by scaramouche1** [comment]
Many thanks.  That works!

The code you wrote motivated me to write my own version:

    (defun helm-latex-math-candidates ()
      (defun helm-latex--math-collect (L)
        (if (vectorp L)
            (list (cons (aref L 0) (aref L 1)))
          (loop for a in L appending (helm-latex--math-collect a))))
      (helm-latex--math-collect LaTeX-math-menu))

The main benefit of this new code is that it works with arbitrary nesting levels (not just two), so if  AucTeX starts using an even deeper menu structure, it will continue to work.  Feel free to include the one you like the most in `helm-misc.el`.  Many thanks!

**Comment by thierryvolpiatto** [comment]
scaramouche1 <notifications@github.com> writes:

> Many thanks. That works!
>
> The code you wrote motivated me to write my own version:
>
> (defun helm-latex-math-candidates ()
>   (defun helm-latex--math-collect (L)
>     (if (vectorp L)
>         (list (cons (aref L 0) (aref L 1)))
>       (loop for a in L appending (helm-latex--math-collect a))))
>   (helm-latex--math-collect LaTeX-math-menu))
>
> The main benefit of this new code is that it works with arbitrary
> nesting levels (not just two), so if AucTeX starts using an even
> deeper menu structure, it will continue to work. Feel free to include
> the one you like the most in helm-misc.el. Many thanks!

Yes, very good, I will use a slightly modified version though:

(defun helm-latex-math-candidates ()
  (cl-labels ((helm-latex--math-collect (L)
                (cond ((vectorp L)
                       (list (cons (aref L 0) (aref L 1))))
                      ((listp L)
                       (cl-loop for a in L append
                                (helm-latex--math-collect a))))))
    (helm-latex--math-collect LaTeX-math-menu)))

Thanks.

--
Thierry
