### ISSUE TITLE
helm-grep-do-git-grep breaks if submodule.recurse = true in git config

### ISSUE THREAD

**Issue by andrmuel** [emacs-helm/helm#2066]
## Expected behavior

helm-grep-do-git-grep still works and actually recurses through submodules (as git grep will)

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

helm-grep-do-git-grep no longer works at all

## Steps to reproduce (recipe)

Just do (in the shell):
> git config --global --add submodule.recurse true

## Backtraces if any (`M-x toggle-debug-on-error`)

It is caused by one of the flags in `helm-grep-git-grep-command`, I think by `--no-index`.

## Describe versions of Helm, Emacs, operating system, etc.

Emacs 26.1, helm-core 2.9.8

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):

no

## IMPORTANT NOTE

Helm provides a script named `emacs-helm.sh` which runs Helm in a neutral
environment: no other packages and only minimal settings.

When possible, use it to reproduce your Helm issue to ensure no other package is
interfering.

To run it, simply switch to the directory where Helm is installed and call `./emacs-helm.sh`.
If necessary you can specify emacs executable path on command line with "-P" option.

Thanks.

**Comment by thierryvolpiatto** [comment]
Andreas Müller <notifications@github.com> writes:

> It is caused by one of the flags in `helm-grep-git-grep-command`, I think by `--no-index`.

Please try to test your `helm-grep-git-grep-command` in a terminal with
your settings and modify it until it works, when done use this value
with `helm-grep-git-grep-command`.

Thanks.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Andreas Müller <notifications@github.com> writes:

> Helllo Thierry
>
> It works when I remove --exclude-standard and --no-index (--no-index is not supported with --recurse-submodules and --exclude-standard is only useful with
> --no-index).

Yes, --exclude-standard and --no-index are documented (in addition of
git-grep doc of course) in helm-grep-git-grep-command docstring, there
is no problem to remove them.
Perhaps we can remove these args in default?

> So I get git --no-pager grep -n%cH --color=always --full-name -e %p --
> %f for my helm-grep-git-grep-command.
>
> Another option is to add --no-recurse-submodules; this will overwrite the setting from the config file. Of course that also prevents grepping through
> submodules.
>
> A solution might be to use the current value of helm-grep-git-grep-command as default and remove --exclude-standard and --no-index if the configuration
> submodule.recurse is active.

Hmm, don't know how to get programatically this information, is there a
git command (git-config ?) that do this?

Thanks.

-- 
Thierry

**Comment by andrmuel** [comment]
Thierry Volpiatto wrote:
> 
> Yes, --exclude-standard and --no-index are documented (in addition of
> git-grep doc of course) in helm-grep-git-grep-command docstring, there
> is no problem to remove them.
> Perhaps we can remove these args in default?

For me personally that would be fine, but I don't know what the
expectation of the average user would be ...


> Hmm, don't know how to get programatically this information, is there a
> git command (git-config ?) that do this?

Yes, `git config --get submodule.recurse` will return either true or
false.

Thanks, Andreas

**Comment by thierryvolpiatto** [comment]
Andreas Müller <notifications@github.com> writes:

> Thierry Volpiatto wrote:
>>
>> Yes, --exclude-standard and --no-index are documented (in addition of
>> git-grep doc of course) in helm-grep-git-grep-command docstring, there
>> is no problem to remove them.
>> Perhaps we can remove these args in default?
>
> For me personally that would be fine, but I don't know what the
> expectation of the average user would be ...

Seems reasonable as default value, let's use this.

>> Hmm, don't know how to get programatically this information, is there a
>> git command (git-config ?) that do this?
>
> Yes, `git config --get submodule.recurse` will return either true or
> false.

Nice, thanks, but I think it is better to let's user configure the
helm-grep-git-grep-command themselves.

Thanks.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Andreas Müller <notifications@github.com> writes:

> Ok, if you change the default, there will be no more problem if the user
> sets submodule.recurse, so sounds sensible to me.

Done, thanks.

-- 
Thierry
