### ISSUE TITLE
`helm-source-info-elisp` is not defined. 

### ISSUE THREAD

**Issue by vspinu** [emacs-helm/helm#2068]
## Expected behavior

`helm-info-at-point` displays candidates. 

## Actual behavior

`M-x helm-info-at-point` throws `helm-source-info-elisp` is not defined. 

## Backtraces if any (`M-x toggle-debug-on-error`)

```el
Debugger entered--Lisp error: (void-variable helm-source-info-elisp)
  #[257 "\211<\203\207\211J\207" [] 2 "\n\n(fn SOURCE)"](helm-source-info-elisp)
  mapcar(#[257 "\211<\203\207\211J\207" [] 2 "\n\n(fn SOURCE)"] (helm-source-info-elisp helm-source-info-cl helm-source-info-eieio helm-source-info-pages helm-source-info-gnus))
  helm-get-sources((helm-source-info-elisp helm-source-info-cl helm-source-info-eieio helm-source-info-pages helm-source-info-gnus))
  helm-initialize(nil nil nil (helm-source-info-elisp helm-source-info-cl helm-source-info-eieio helm-source-info-pages helm-source-info-gnus))
  helm-internal((helm-source-info-elisp helm-source-info-cl helm-source-info-eieio helm-source-info-pages helm-source-info-gnus) nil nil nil nil "*helm info*" nil nil nil)
  apply(helm-internal ((helm-source-info-elisp helm-source-info-cl helm-source-info-eieio helm-source-info-pages helm-source-info-gnus) nil nil nil nil "*helm info*" nil nil nil))
  helm((helm-source-info-elisp helm-source-info-cl helm-source-info-eieio helm-source-info-pages helm-source-info-gnus) nil nil nil nil "*helm info*" nil nil nil)
  apply(helm ((helm-source-info-elisp helm-source-info-cl helm-source-info-eieio helm-source-info-pages helm-source-info-gnus) nil nil nil nil "*helm info*" nil nil nil))
  helm(:sources (helm-source-info-elisp helm-source-info-cl helm-source-info-eieio helm-source-info-pages helm-source-info-gnus) :buffer "*helm info*")
  helm-info-at-point()
```

## Describe versions of Helm, Emacs, operating system, etc.

Emacs 25.2.2 with helm helm-20180719.1206 from MELPA.

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):

No. I am getting "No such file or directory helm" because there is no "helm" in MELPA instalation.

**Comment by thierryvolpiatto** [comment]
Vitalie Spinu <notifications@github.com> writes:

> This is clearly emacs 25 issues. I just compiled emacs 27 and with the
> same MELPA sources compiled on emacs 25 it works just fine.

Check your info directories (Info-directory-list) installation for
emacs-25, if helm doesn't find the relevant info files, the source is
not created.
The source is created here for me with emacs-25.

For emacs-helm.sh, it is AFAIK bundled with MELPA, and it is working
fine, please read documentation on how to run it, basically it is
./emacs-helm.sh from the helm directory, use -P to specify emacs path if
needed.

-- 
Thierry

**Comment by vspinu** [comment]
> if helm doesn't find the relevant info files, the source is not created.

Hmm. This is prcisely what happened. On default ubuntu 18.04 Info-directory-list doesn't contain info files. One need to install `emacs25-common-non-dfsg` to get those.  How about an initialization warning for clarity or a fallback source which would throw a descriptive error?

> For emacs-helm.sh, it is AFAIK bundled with MELPA, and it is working fine.

Well, not for me, but I no longer need it now:)

Thanks for the quick help!

**Comment by thierryvolpiatto** [comment]
Vitalie Spinu <notifications@github.com> writes:

>     if helm doesn't find the relevant info files, the source is not created.
>    
> Hmm. This is prcisely what happened. On default ubuntu 18.04 Info-directory-list doesn't contain info files. One need to install emacs25-common-non-dfsg to
> get those. How about an initialization warning for clarity or a
> fallback source which would throw a descriptive error?

Will see what I can do.

>
>
>     For emacs-helm.sh, it is AFAIK bundled with MELPA, and it is working fine.
>    
> Well, not for me,

Are you sure? I never heard it is not installed by MELPA, here the
recipe:

https://github.com/melpa/melpa/blob/master/recipes/helm

If you don't have it, it is a problem with MELPA and you should report
it there.

Thanks.

-- 
Thierry

**Comment by vspinu** [comment]
> Are you sure? I never heard it is not installed by MELPA, here the
recipe:

The file is executable file is there but it doesn't work throwing ""No such file or directory helm"". It's almost surely has something to do with the populating load-path. I will check it up.
