### ISSUE TITLE
`helm-list-emacs-process` leaves tabulated list header in other buffer

### ISSUE THREAD

**Issue by jwinder** [emacs-helm/helm#2069]
## Expected behavior

`helm-list-emacs-process` should not affect original buffer.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

After finishing with `helm-list-emacs-process`, and extra border or header is left at the top of the original buffer.

## Steps to reproduce (recipe)

From `emacs-helm.sh`, run `helm-list-emacs-process`. Then finish an action on a process or cancel out of the mini-buffer. An extra border or header is left at the top of the original buffer.

I've found that this behavior is due to `tabulated-list-init-header` which is called by `list-processes--refresh` in the init of `helm-list-emacs-process`. Therefore, calling `tabulated-list-init-header` results in the same issue.

I've found a temporary fix for this is to move the init function (not sure if there's a better solution):

```elisp
(setq helm-source-emacs-process
  (helm-build-sync-source "Emacs Process"
    :candidates (lambda ()
                  (list-processes--refresh)
                  (mapcar #'process-name (process-list)))
    :persistent-action (lambda (elm)
                         (delete-process (get-process elm))
                         (helm-delete-current-selection))
    :persistent-help "Kill Process"
    :action (helm-make-actions "Kill Process"
                               (lambda (_elm)
                                 (cl-loop for p in (helm-marked-candidates)
                                          do (delete-process (get-process p)))))))
```

## Describe versions of Helm, Emacs, operating system, etc.

macOS 10.13.6. Not sure if this behavior happens on linux.
Emacs 26.1
Both helm 2.9.8 and master

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):

yes

## IMPORTANT NOTE

Helm provides a script named `emacs-helm.sh` which runs Helm in a neutral
environment: no other packages and only minimal settings.

When possible, use it to reproduce your Helm issue to ensure no other package is
interfering.

To run it, simply switch to the directory where Helm is installed and call `./emacs-helm.sh`.
If necessary you can specify emacs executable path on command line with "-P" option.

Thanks.

**Comment by thierryvolpiatto** [comment]
Joe Winder <notifications@github.com> writes:

> ## Expected behavior
>
> `helm-list-emacs-process` should not affect original buffer.
>
> ## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
>
> After finishing with `helm-list-emacs-process`, and extra border or header is left at the top of the original buffer.
>
> ## Steps to reproduce (recipe)
>
> From `emacs-helm.sh`, run `helm-list-emacs-process`. Then finish an
> action on a process or cancel out of the mini-buffer. An extra border
> or header is left at the top of the original buffer.

I can't reproduce, what do you mean by "finish an action on a process"?
and which process so that I can reproduce, also what do you mean by
"cancel out of the minibuffer"? C-g?

Thanks.



> I've found that this behavior is due to `tabulated-list-init-header`
> which is called by `list-processes--refresh` in the init

Is wrapping the call of `list-processes--refresh` inside a
`save-selected-window` fixes your problem?


-- 
Thierry

**Comment by jwinder** [comment]
> I can't reproduce, what do you mean by "finish an action on a process"?
and which process so that I can reproduce, also what do you mean by
"cancel out of the minibuffer"? C-g?

Sorry for the confusion. From the `*helm process*` buffer, I meant exit it somehow, either by killing a listed process or by exiting the buffer with `C-g`.

I attempted to reproduce this in an ubuntu container, but I was having an issue installing emacs 26.1 on ubuntu. I'll keep trying, but I'm wondering if this is a macOS only issue. It didn't happen in emacs 25 on mac.

Anyway, I did a little more digging. It looks like `list-processes--refresh` invokes `tabulated-list-init-header` which leaves `header-line-format` set to `" "` locally in original buffer. Its original value is nil.

I've been able to verify that `(setq header-line-format " ")` makes the empty header appear and then `(setq header-line-format nil)` causes it to go away. I think this is the underlying problem. For some reason, `list-processes--refresh` is affecting `header-line-format`.

`save-selected-window` and `save-window-excursion` don't help; however, `with-temp-buffer` fixes the problem for me:

```elisp
(defvar helm-source-emacs-process
  (helm-build-sync-source "Emacs Process"
    :init (with-temp-buffer (list-processes--refresh))
    :candidates (lambda () (mapcar #'process-name (process-list)))
    :persistent-action (lambda (elm)
                         (delete-process (get-process elm))
                         (helm-delete-current-selection))
    :persistent-help "Kill Process"
    :action (helm-make-actions "Kill Process"
                               (lambda (_elm)
                                 (cl-loop for p in (helm-marked-candidates)
                                          do (delete-process (get-process p)))))))
```

Does this seem reasonable to PR? It's probably a little nicer than something like:

```elisp
:init (lambda ()
         (list-processes--refresh)
         (setq-local header-line-format nil))
```

**Comment by thierryvolpiatto** [comment]
Joe Winder <notifications@github.com> writes:

> Does this seem reasonable to PR? It's probably a little nicer than something like:
>
> ```elisp
> :init (lambda ()
>          (list-processes--refresh)
>          (setq-local header-line-format nil))
> ```

What about

    (lambda ()
      (let (tabulated-list-use-header-line)
        (list-processes--refresh)))

Don't know if tabulated-list-use-header-line is available in emacs-25
though.

-- 
Thierry

**Comment by jwinder** [comment]
That fixes my problem:

```elisp
:init (lambda ()
        (let (tabulated-list-use-header-line)
          (list-processes--refresh)))
```

I had a look at tabulated-list.el, and tabulated-list-use-header-line was introduced 6 years ago. I don't think this would be a problem for emacs 25.

**Comment by thierryvolpiatto** [comment]
Joe Winder <notifications@github.com> writes:

> That fixes my problem:
>
> :init (lambda ()
>         (let (tabulated-list-use-header-line)
>           (list-processes--refresh)))
>
> I had a look at tabulated-list.el, and tabulated-list-use-header-line
> was introduced 6 years ago. I don't think this would be a problem for
> emacs 25.

Good, thanks for the PR!

-- 
Thierry
