### ISSUE TITLE
helm-eshell-history opens a new frame

### ISSUE THREAD

**Issue by petercheng00** [emacs-helm/helm#2072]
## Expected behavior
In prior versions, helm-eshell-history opened a small buffer in the bottom of the active frame, as with other helm actions

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
A small separate frame pops up containing the eshell history contents

## Steps to reproduce (recipe)
M-x eshell
M-x helm-eshell-history

## Describe versions of Helm, Emacs, operating system, etc.
helm - 20180728.1656
emacs - 27.0.50
os - ubuntu 18.04

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):
reproduced with emacs-helm.sh from master version of this repo as of right now

**Comment by thierryvolpiatto** [comment]
Peter Cheng <notifications@github.com> writes:

> ## Expected behavior
> In prior versions, helm-eshell-history opened a small buffer in the bottom of the active frame, as with other helm actions
>
> ## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
> A small separate frame pops up containing the eshell history contents

This is now the default for graphic sessions, if you don't want this
customize helm-show-completion-display-function.

-- 
Thierry

**Comment by petercheng00** [comment]
Thanks!
