### ISSUE TITLE
offer auto completion of environment variables 

### ISSUE THREAD

**Issue by CeleritasCelery** [emacs-helm/helm#2073]
Currently helm will substitute environment variables after I type `/`. So I can just type `$REMOTE_PROJECT_DIRECTORY/` and I can go to that directory. However it offers no completion for the environment variables, which can make typing them out every single time slow. Would it be possible to offer completion of environment variables similar to what helm already does for tramp remote hosts (e.g. after I type `/ssh:` helm will offer completion for the hosts that tramp knows about)? Helm could trigger off of `$` followed by some other non-whitespace character (to distinguish from a regex pattern "end"). 

An added plus would be to display the current value as well, to provide more information during filtering.

**Comment by thierryvolpiatto** [comment]
Troy Hinckley <notifications@github.com> writes:

> Currently helm will substitute environment variables after I type
> `/`. So I can just type `$REMOTE_PROJECT_DIRECTORY/` and I can go to
> that directory. However it offers no completion for the environment
> variables, which can make typing them out every single time
> slow. Would it be possible to offer completion of environment
> variables similar to what helm already does for tramp remote hosts
> (e.g. after I type `/ssh:` helm will offer completion for the hosts
> that tramp knows about)? Helm could trigger off of `$` followed by
> some other non-whitespace character (to distinguish from a regex
> pattern "end").

At this stage of helm development I don't want to add such new
features.

I suggest another approach which is IMO more efficient than storing the
path of directories you visit often in ENV vars, it is using bookmarks.
From helm-find-files you can type at any moment C-x r m which save your
current directory in bookmarks, and always from helm-find-files you can
hit at any moment C-x r b to jump to those bookmarks, of course you can
start as well by M-x helm-filtered-bookmarks.

HTH.

--
Thierry

**Comment by thierryvolpiatto** [comment]
![capture d ecran_2018-08-01_09-35-49](https://user-images.githubusercontent.com/1533939/43507820-65701ae0-956e-11e8-9a2e-4135407f27be.png)

**Comment by CeleritasCelery** [comment]
> I suggest another approach which is IMO more efficient than storing the
path of directories you visit often in ENV vars, it is using bookmarks.

That honestly solves the majority of my use cases. I had not considered that. The only scenario where that would not work is when an environment variable is updated regularly to point to different paths, as is the case with some variables set by my work's login shell. But that is uncommon enough to not bother with.
