### ISSUE TITLE
Helm buffer-switching does not filter properly.

### ISSUE THREAD

**Issue by zck** [emacs-helm/helm#2076]
## Steps to reproduce (recipe)
`./emacs-helm.sh`
(in Emacs) `C-x b`
Note that there are three buffers to switch to: `*Messages*`, `*helm-mode-switch-to-buffer*`, and `*scratch*`. Note that all three of these buffers have an `s` in them.
Then type `s`

## Expected behavior
The list of buffers has all three candidates in it, because each buffer name has an `s`.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
 The list of buffers is filtered to only `*Messages*`.
Note that similar behavior occurs on other letters; pressing `a` should have both `*Messages*` and `*scratch*`, but only has `*Messages*` in it.

## Describe versions of Helm, Emacs, operating system, etc.

helm-20180805.611 installed from Melpa.
Emacs 26.0.50 built from git
Ubuntu 16.04

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):

yes!

**Comment by thierryvolpiatto** [comment]
zck <notifications@github.com> writes:

> ## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
>  The list of buffers is filtered to only `*Messages*`.
> Note that similar behavior occurs on other letters; pressing `a`
>  should have both `*Messages*` and `*scratch*`, but only has
>  `*Messages*` in it.

I have commited a fix for this, note you have better time to use
helm-mini or helm-buffers-list for listing your buffers.

Thanks.

-- 
Thierry

**Comment by zck** [comment]
Thanks for fixing it!

I don't really like either `helm-mini` or `helm-buffers-list` for switching buffers. I'm happy to take this conversation elsewhere, but is there the ability to configure helm-buffers-list or helm-mini (I'm not sure of the differences at the moment) to do this:

1. Don't show either the buffer size or major mode in the buffer.
2. Show the entire name of the buffer.

Thanks!

**Comment by thierryvolpiatto** [comment]
zck <notifications@github.com> writes:

> Thanks for fixing it!
>
> I don't really like either helm-mini or helm-buffers-list for
> switching buffers. I'm happy to take this conversation elsewhere,

If you don't like something in helm-buffers-list just open a new issue
to explain what you don't like, thanks.

> but is there the ability to configure helm-buffers-list or helm-mini
> (I'm not sure of the differences at the moment) to do this:
>
>  1. Don't show either the buffer size or major mode in the buffer.

Customize `helm-buffer-details-flag`.
  
>  2. Show the entire name of the buffer.

Customize `helm-buffer-max-length`, perhaps customizing only
`helm-buffer-details-flag` is enough don't remember, at least when you
toggle the details view the whole buffer name is shown.

-- 
Thierry
