### ISSUE TITLE
How to add a custom action to a helm-source?

### ISSUE THREAD

**Issue by student-sx** [emacs-helm/helm#2078]
How can I add a custom action to an existing helm-source? In particular I want to add an action to a recoll source. Here is what  I tried and as comment, what doesn't work:

```
;; Define custom action:

(defun test-action (candidate)
(message (format "Filename: %s" (helm-get-selection)))
)

(helm-recoll-create-source "main" "~/.recoll")

;; 1. approach:

(helm-add-action-to-source "Test 1" 'test-action helm-source-recoll-main 0)

;; Action doesn't show up with first approach

;; 2. approach


;; (defmethod helm-setup-user-source ((source helm-source-recoll-main))
;;   (let ((actions (slot-value source 'action)))
;;     (set-slot-value source 'action
;; 		    ("Test 2" . 'test-action))))

;; Error Unknown specializer helm-source-recoll-main with second method


;; Test:
(helm :sources 'helm-source-recoll-main)


;; Test action with custom source works:

;; (defvar helm-source-test
;;   (helm-build-async-source "helm-source-test"
;;     :candidates-process
;;     (lambda ()
;;       (start-process "echo" nil "recoll" "-q" "-t" helm-pattern))
;;     :action '( 
;; 	      ("test" . test-action)
;; 	      )
;;     )
;;   )

;; (helm :sources 'helm-source-test)
```

My versions: helm-core: 20180712.837, helm-recoll: 20160731.921

**Comment by thierryvolpiatto** [comment]
Please report to helm-recoll directly, thanks.

**Comment by student-sx** [comment]
So you would say that my code should work in principle and that it is just a helm-recoll bug?

**Comment by student-sx** [comment]
Moved it to: https://github.com/emacs-helm/helm-recoll/issues/15

**Comment by thierryvolpiatto** [comment]
student-sx <notifications@github.com> writes:

> So you would say that my code should work in principle and that it is just a helm-recoll bug?

Not necessarily a bug, but for some reasons the source (or the class) may not be
created when your code run. I don't know enough helm-recoll code to
explain what is going wrong, Michael the maintainer will explain you
better what's wrong. 

-- 
Thierry
