### ISSUE TITLE
To bind the key C-M-SPC, use [?\C-\M- ], not [C-M-SPC]

### ISSUE THREAD

**Issue by bingoUV** [emacs-helm/helm#2082]
## Expected behavior
While using helm functionality for the first time after helm installation / upgrade  - e.g. helm-buffers, or helm-find : helm search criteria entry window should open.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

Actually no helm selection window appears, but emacs gives this error in minibuffer : 

> To bind the key C-M-SPC, use [?\C-\M- ], not [C-M-SPC]

I need to replace \<C-M-SPC\> with C-M-SPC in helm-buffers.el, and 
\<M-RET\> with M-RET in helm-files.el and helm-mode.el. Then recompile these el files, and then helm works fine.

I see this problem in multiple updates (possibly all) in last 2 months.

## Steps to reproduce (recipe)
Install helm from melpa in July / Aug 2018, and run M-x helm-buffers
## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):
no

## IMPORTANT NOTE

Helm provides a script named `emacs-helm.sh` which runs Helm in a neutral
environment: no other packages and only minimal settings.

When possible, use it to reproduce your Helm issue to ensure no other package is
interfering.

To run it, simply switch to the directory where Helm is installed and call `./emacs-helm.sh`.
If necessary you can specify emacs executable path on command line with "-P" option.

Thanks.

**Comment by thierryvolpiatto** [comment]
Sorry but I don't understand what's your problem is, please start
emacs-helm.sh and explain clearly what's happening.

Thanks.

-- 
Thierry

**Comment by bingoUV** [comment]
1. emacs-helm.sh starts
2. there is a completely blank Emacs window : white in color.
3. in the minibuffer, this same error message is displayed : To bind the key C-M-SPC, use [?\C-\M- ], not [C-M-SPC]
4. if i click the mouse, or press a key, the mini buffer message vanishes. But C-x C-f does not use helm's version of find files. M-x is also not helm's version.
5. If i apply the patch to change key binding in helm's .el files as stated above, this problem goes away. Helm works normally after applying that patch.

**Comment by thierryvolpiatto** [comment]
Side note:

Please provide all the informations asked in issue template when submitting a bug report.
(Like the emacs and helm versions as asked by @xuchunyang )
Thanks.

**Comment by thierryvolpiatto** [comment]
BTW:

```elisp
(kbd "<C-M-SPC>")
;; =>[201326624]
(kbd "C-M-SPC")
;; =>[201326624]
```

**Comment by bingoUV** [comment]
After I fix the .el files, emacs-helm.sh looks like your screenshot. Otherwise it is completely blank, except for mini buffer.

Emacs version 27.05 , compiled from source
I have this problem in 2 systems : one is Redhat enterprise Linux 6 and one is Redhat enterprise Linux 7.

I'll upload screenshot , currently facing problem of getting blank screenshots due to running within Virtualbox VM.

**Comment by thierryvolpiatto** [comment]
Klozuht <notifications@github.com> writes:

> After I fix the .el files, emacs-helm.sh looks like your screenshot. Otherwise it is completely blank, except for mini buffer.
>
> Emacs version 27.05 , compiled from source

I think it is more a problem with your emacs installation, try to
rebuild your emacs with make bootstrap, restart emacs, recompile your
helm files, and restart emacs again.

Here it is not reproductible with emacs-24.5/25.3/26.1/27

The bindings you are modifying in helm source code are here since
emacs-24.1 IIRC and we never had such problem.

-- 
Thierry

**Comment by bingoUV** [comment]
Ok. BTW Compiling emacs again from the latest code at https://github.com/emacs-mirror does not fix this problem. I would follow up with emacs development. My observations below. I filed this issue so that others who may not be comfortable editing helm .el code after every update would not face this problem. I have been editing it for some months now. And probably the inconsistent usage of \< and \> in defining some keybindings is itself a code consistency issue which might discourage contribution - and could also lead to even more inconsistency as new contributors would have no consistent code pattern to follow.

In my emacs, when *scratch* buffer is open, if I do M-x eval for
`(kbd "<C-M-SPC>")`
I get
>  [C-M-SPC]

Same when doing C-x C-e on (kbd "<C-M-SPC>")  in *scratch* 

If I do M-x eval for 
`(kbd "C-M-SPC")`
I get
> [201326624]

In eshell, strangely, they have the same output : 

> ~ $ (kbd "C-M-SPC")                                                                                                                                                                      
> [201326624]                                                                                                                                                                              
> ~ $ (kbd "\<C-M-SPC\>")                                                                                                                                                                    
> [201326624]                                                                                                                                                                              


And even more strangely, while other buffers are open , M-x eval also gives the same output 

>  [201326624]

for both the forms. In scratch buffer , even after this, M-x eval still behaves in its earlier ways of giving "[C-M-SPC]" for `(kbd "<C-M-SPC>")`

**Comment by thierryvolpiatto** [comment]
I have recompiled helm with emacs-27 and still can't reproduce your issue, thus as I mentioned earlier,
`(kbd "C-M-SPC")` is evaling to `[201326624]` and `(kbd "<C-M-SPC>")` also, this in emacs -Q and with emacs-helm.sh.  So why do you have this problem on your emacs ?
Did you recompile your emacs with "make bootstrap" ?
Also what make you think helm provide inconsistent bindings ?
If "<C-M-SPC>" is inconsistent why is it working fine since years across many different emacs version and it is just failing now and just for you ?
Though I could accept a PR modifying all "<C-M-SPC>" to "C-M-SPC" (they are the same) but you will still have a problem unsolved with your emacs.

**Comment by bingoUV** [comment]
> If "" is inconsistent why is it working ...
Because inconsistent does not mean non-working : https://www.dictionary.com/browse/inconsistent?s=t

> but you will still have a problem unsolved with your emacs
Which is why I said I would take it up with Emacs development.
