### ISSUE TITLE
helm history ignored if helm-find-files-ignore-thing-at-point is t

### ISSUE THREAD

**Issue by CeleritasCelery** [emacs-helm/helm#2087]
## Expected behavior
Calling `helm-find-files` with a single prefix argument will open a `helm-find-files-history` filter to start helm from a previously visited directory. 

## Actual behavior
If `helm-find-files-ignore-thing-at-point` is not `nil`, the selection from `helm-find-files-history` will be ignored and helm will always start in the `default-directory`. 

## Steps to reproduce (recipe)
`(setq helm-find-files-ignore-thing-at-point t)`
call `helm-find-files` with a prefix argument. 
select a directory.
observe that helm ignores selection. 

## Describe versions of Helm, Emacs, operating system, etc.

Latest helm, Emacs 26.1

## Are you using `emacs-helm.sh` to reproduce this bug:

no

**Comment by alphapapa** [comment]
> Are you using emacs-helm.sh to reproduce this bug:
> no

Why not?  :)

**Comment by CeleritasCelery** [comment]
I can never get that thing script to work. I honestly tried, but after fussing with it for 20 minutes I just gave up.

**Comment by thierryvolpiatto** [comment]
Try this patch:

```diff
diff --git a/helm-files.el b/helm-files.el
index 48cf808..f4faa33 100644
--- a/helm-files.el
+++ b/helm-files.el
@@ -4389,7 +4389,8 @@ This is the starting point for nearly all actions you can do on files."
   (let* ((hist            (and arg helm-ff-history (helm-find-files-history nil)))
          (smart-input     (or hist (helm-find-files-initial-input)))
          (default-input   (expand-file-name (helm-current-directory)))
-         (input           (cond (helm-find-files-ignore-thing-at-point
+         (input           (cond ((and (null hist)
+                                      helm-find-files-ignore-thing-at-point)
                                  default-input)
                                 ((and (eq major-mode 'org-agenda-mode)
                                       org-directory

```

**Comment by thierryvolpiatto** [comment]
Running emacs-helm.sh is pretty easy:

1) cd to the helm directory

2) run ./emacs-helm.sh -h 
Usage: helm [-P} Emacs path [-h} help [--] EMACS ARGS

3) As you can see you may need to specify the emacs binary path with "-P" (IIRC Macos user need to specify it)

Note: if you have installed helm from sources with make && sudo make install, you don't need to cd to helm directory and the script is symlinked to "helm" in "/usr/local/bin" so you just run "helm".
If you are on Windows ignore this, the script is not working.

**Comment by CeleritasCelery** [comment]
When I try to run make to generate the autoloads for helm it gives the following error.
```
In toplevel form:
helm-adaptive.el:24:1:Error: Cannot open load file: No such file or directory, async
```
But its looks like your fix addressed the problem with the helm history. Thanks.

**Comment by thierryvolpiatto** [comment]
```
In toplevel form:
helm-adaptive.el:24:1:Error: Cannot open load file: No such file or directory, async
```
For this see https://github.com/emacs-helm/helm/wiki#from-source

The best for installing helm from source is to also install async from source with `make && sudo make install`
