### ISSUE TITLE
How to remap helm-ff-run-complete-fn-at-point and helm-kill-selection-and-quit

### ISSUE THREAD

**Issue by DrWaleedAYousef** [emacs-helm/helm#2092]
## Expected behavior
It is just a matter of convenience to have consistency between the keybinding of `helm-kill-selection-and-quit` and  `helm-ff-run-complete-fn-at-point`. The first gives the displayed/real name without/with prefix. However, the latter does the opposite. How can I change the keybindings? Sorry, for the trivial question.

## IMPORTANT NOTE

Helm provides a script named `emacs-helm.sh` which runs Helm in a neutral
environment: no other packages and only minimal settings.

When possible, use it to reproduce your Helm issue to ensure no other package is
interfering.

To run it, simply switch to the directory where Helm is installed and call `./emacs-helm.sh`.
If necessary you can specify emacs executable path on command line with "-P" option.

Thanks.

**Comment by ReneFroger** [comment]
Your question is not clear enough, so we have no clear idea how we could help you. Perhaps [this answer](https://emacs.stackexchange.com/questions/20072/helm-mode-change-default-keybinding-for-helm-find-files-down-one-level) will help your further.

This issue could be considered as closed.

**Comment by DrWaleedAYousef** [comment]
Ok, thanks so much. Then, I need more help regarding this:

The function `helm-ff-run-complete-fn-at-point` that is bound to `C-c i` (after `helm-find-files`), what are the two functions bound to the prefix versions: `C-u C-c i` and `C-u C-u C-c i`.

Also, the function `helm-kill-selection-and-quit` that is bound to `C-c C-k`  (after `helm-find-files`), what is the function that is bound to the prefix version `C-u C-c C-k`, and what is the function that kills the abbreviated name (not the real name nor the displayed name)?

Thanks so much.

**Comment by thierryvolpiatto** [comment]
Waleed Yousef <notifications@github.com> writes:

> Ok, thanks so much. Then, I need more help regarding this:
>
> The function helm-ff-run-complete-fn-at-point that is bound to C-c i (after helm-find-files), what are the two functions bound to the prefix versions: C-u
> C-c i and C-u C-u C-c i.
>
> Also, the function helm-kill-selection-and-quit that is bound to C-c C-k (after helm-find-files), what is the function that is bound to the prefix version
> C-u C-c C-k, and what is the function that kills the abbreviated name (not the real name nor the displayed name)?

The two functions are different, helm-ff-run-complete-fn-at-point is a
function specific to helm-find-files which belong to helm-find-files-map
while helm-kill-selection-and-quit is a function bound in helm-map and
is used in all helm sources, it kill the display or real value depending
the prefix arg.

So one function is specialized for files while the other is generic and
is used everywhere, it is why they behave differently.

HTH.


-- 
Thierry

**Comment by DrWaleedAYousef** [comment]
Ok, I will try to be clearer. The `helm-kill-selection-and-quit` kills the displayed value and is bound to `C-c C-k` and its prefix version kills the real value and is bound to `C-u C-c C-k`. I need the following:

- killing real value be bound to `C-c k`
- killing the displayed value be bound to `C-u C-c k'

How can I do this?

**Comment by DrWaleedAYousef** [comment]
I think there is a misunderstanding; I will re-ask in a clearer way. Now
there is some THING bind to C-u C-x C-k, I just need to bind/re-bind this
THING to something else, e.g., C-x C-k C-y. It does not matter if this new
key binding works instead of or parallel to the original key binding.

**Comment by thierryvolpiatto** [comment]
Waleed Yousef <notifications@github.com> writes:

> I think there is a misunderstanding; I will re-ask in a clearer way. Now
> there is some THING bind to C-u C-x C-k,

No, there is nothing bound to C-u C-x C-k but something bound to C-x C-k
and it happens that this "something", IOW this function is implemented
to accept a prefix arg, so binding this function to any other key will
not change your problem, what you have to do here is to write another
function doing the same thing as actual one but behaving differently
when you give it a pref arg.

-- 
Thierry

**Comment by DrWaleedAYousef** [comment]
I mean C-u followed by any valid binding not necessary C-x C-k. Can this be
done?

**Comment by thierryvolpiatto** [comment]
No as explained above you can change the behavior of a prefix key only by modifying the initial code itself.  If you are really annoyed by this, advice `helm-kill-selection-and-quit` (override) so that it does the contrary of what it does actually with prefix arg by modifying  `(format "%s" (helm-get-selection nil (not arg)))` to `(format "%s" (helm-get-selection nil arg))`.
