### ISSUE TITLE
helm-comint-input-ring and helm-eshell-input fuzzy matching?

### ISSUE THREAD

**Issue by ChoppinBlockParty** [emacs-helm/helm#2093]
Seems like I have enabled a fuzzy matching everywhere with following

      helm-mode-fuzzy-match                 t ; everything will be fuzzy
      helm-completion-in-region-fuzzy-match t

Did I? Why `helm-comint-input-ring` and `helm-eshell-input` history are not using fuzzy matching?

**Comment by thierryvolpiatto** [comment]
Yuki <notifications@github.com> writes:

> Seems like I have enabled a fuzzy matching everywhere with following
>
>   helm-mode-fuzzy-match                 t ; everything will be fuzzy
>   helm-completion-in-region-fuzzy-match t
>
> Did I?

No, only in generic functions.

> Why helm-comint-input-ring and helm-eshell-input history are not using
> fuzzy matching?

From any helm session type C-h m and read about helm native functions
and helm generic functions (Helm functions vs helmized Emacs functions).

The both sources you are asking have no fuzzy match enabled, you can
enable it by adding to these sources the fuzzy-matching attribute, the
first is a helm source while the second is a class, see
https://github.com/emacs-helm/helm/wiki/FAQ#why-is-a-customizable-helm-source-nil
to know how to do.

-- 
Thierry

**Comment by ChoppinBlockParty** [comment]
Thank you. Seems like I am yet too newbie for this. It need some time to understand this.

**Comment by CeleritasCelery** [comment]
you should be able to do something like this after `helm-misc` and `helm-eshell` are loaded
```lisp
(setq helm-source-comint-input-ring
  (helm-build-sync-source "Comint history"
    :fuzzy-match t
    :candidates (lambda ()
                  (with-helm-current-buffer
                    (ring-elements comint-input-ring)))
    :action 'helm-comint-input-ring-action))
```
```lisp
(defclass helm-eshell-history-source (helm-source-sync)
  ((init :initform
         (lambda ()
           ;; Same comment as in `helm-source-esh'.
           (remove-hook 'minibuffer-setup-hook 'eshell-mode)))
   (candidates
    :initform
    (lambda ()
      (with-helm-current-buffer
        (cl-loop for c from 0 to (ring-length eshell-history-ring)
                 collect (eshell-get-history c)))))
   (nomark :initform t)
   (multiline :initform t)
   (fuzzy-match :initform t)
   (keymap :initform helm-eshell-history-map)
   (candidate-number-limit :initform 9999)
   (action :initform (lambda (candidate)
                       (eshell-kill-input)
                       (insert candidate))))
  "Helm class to define source for Eshell history.")
```

**Comment by thierryvolpiatto** [comment]
So instead of redefining all, use:

``` elisp
(helm-attrset 'fuzzy-match t helm-source-comint-input-ring)

(defmethod helm-setup-user-source ((source helm-eshell-history-source))
  (setf (slot-value 'fuzzy-match) t))
```
Ensure the files are loaded with `with-eval-after-load` or whatever.
HTH, thanks.
