### ISSUE TITLE
How hide helm buffers in *Buffer-List*? 

### ISSUE THREAD

**Issue by lmdic** [emacs-helm/helm#2096]
windows 10, emacs 26.1, helm 3.0

Here my buffer list:

![buffers](https://user-images.githubusercontent.com/303539/45433101-1f484a80-b6b4-11e8-8ebf-1a61cf228c35.png)

How I can hide all **helm** buffers? I'm don't want to Emacs to show them in `Buffer List` ?

**Comment by thierryvolpiatto** [comment]
This is unrelated to Helm.
