### ISSUE TITLE
How can I insert the filename only without complete path?

### ISSUE THREAD

**Issue by student-sx** [emacs-helm/helm#2098]
I often use `C-c i` to insert a complete path of a candidate from a helm session (something like `/path/to/foo.pdf`). Is it also possible just to insert the filename itself without the complete path (in my example just `foo.pdf`)? How can it be done?

**Comment by xuchunyang** [comment]
One alternative solution is `C-c C-k` (that is `helm-kill-selection-and-quit`), it will copy `foo.pdf` to the kill-ring, so you can paste with `C-y` (`yank`).

You can also try the following and use `C-c C-i` (that is, `helm-copy-to-buffer`)

```el
(define-advice helm-copy-to-buffer (:override (real-p) GH2098)
  "Paste current selection to `helm-current-buffer' and exit Helm.
With prefix argument, paste current selection's real value."
  (interactive "P")
  (with-helm-alive-p
    (helm-run-after-exit
     (lambda (candidate)
       (with-helm-current-buffer
         (insert (format "%s" candidate))))
     (helm-get-selection nil (not real-p)))))

;; Uninstall the advice
;; (advice-remove 'helm-copy-to-buffer #'helm-copy-to-buffer@GH2098)
```

I don't know about `C-c i`, I guess that's `helm-ff-run-complete-fn-at-point`, it seems it works only under `C-x C-f` (`helm-find-files`). While `helm-copy-to-buffer` works in all helm sessions.

**Comment by thierryvolpiatto** [comment]
From helm-find-files you can now do `C-u C-u C-u C-c i`.
Closing now.
