### ISSUE TITLE
helm header line does not correctly reflect input

### ISSUE THREAD

**Issue by CeleritasCelery** [emacs-helm/helm#2100]
## Expected behavior
When `helm-echo-input-in-header-line` is `t`, the minibuffer input will be echoed in the header line. 

## Actual behavior
If you use `C-S-!` to suspend updating, the header line will only reflect characters added, not characters deleted.

## Steps to reproduce
- suspend updating with `C-S-!`
- type `foobar` 
- press backspace 3 times

notice that the minibuffer will show `foo` but the header line will show `foobar`.
Once you insert another character, the header line will get back in sync.

## Describe versions of Helm, Emacs, operating system, etc.
Latest Helm
Emacs 26

## Are you using `emacs-helm.sh` to reproduce this bug:
yes

**Comment by thierryvolpiatto** [comment]
This happen only in helm-find-files, right?

**Comment by CeleritasCelery** [comment]
correct. Thanks for the quick fix. That worked.
