### ISSUE TITLE
Helm-m-x fails with "Symbol's value as variable is void: helm-compile-source-functions"

### ISSUE THREAD

**Issue by TyOverby** [emacs-helm/helm#2103]
My emacs helm config looks like this:

```
(require 'helm-config)
(helm-mode 1)
(global-set-key (kbd "M-x" "'helm-M-x))
```

Other helm functions (like completion-at-point, or list-buffers) appear to work, but helm-m-x fails with the error  

```
byte-code: Symbol’s value as variable is void: helm-compile-source-functions
```

**Comment by TyOverby** [comment]
trying to run `helm-mini` runs into the same "Symbol's value as variable is void: helm-compile-source-functions" error.

**Comment by thierryvolpiatto** [comment]
Ty Overby <notifications@github.com> writes:

> My emacs helm config looks like this:
>
> (require 'helm-config)
> (helm-mode 1)
> (global-set-key (kbd "M-x" "'helm-M-x))
>
> Other helm functions (like completion-at-point, or list-buffers) appear to work, but helm-m-x fails with the error
>
> byte-code: Symbol’s value as variable is void: helm-compile-source-functions

It seems you are using deprecated helm libraries, reinstall helm with
last version and your problem should disapear.
FYI helm-compile-source-functions is deprecated IIRC since 3 years or
more.

-- 
Thierry

**Comment by TyOverby** [comment]
It looks like some weird configuration issues were causing me to load two versions of helm, one of them was indeed very old.  

Thanks for the hint, I solved my problem by keeping the older version from loading.
