### ISSUE TITLE
complete common part

### ISSUE THREAD

**Issue by joaocortes** [emacs-helm/helm#2105]
## Expected behavior
When every entry has some common part that isn t typed already, `helm` should complete the common part.

Example:

Assume I type `a`, and every entry that helm prompts starts by `abc`,
`abc-d`
`abc-e`
`abc-f`
`abc-g`

It would be nice if helm completed `bc-` automatically
## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
Its necessary to type the common part

## Describe versions of Helm, Emacs, operating system, etc.
`emacs` 25.1, `fedora` 26

**Comment by thierryvolpiatto** [comment]
You don't need to type "bc" Enter a space and "d" or "e" etc...
