### ISSUE TITLE
<RET> in helm-mini should should have the option to open a new buffer in the previously selected window

### ISSUE THREAD

**Issue by kuwze** [emacs-helm/helm#2107]
## Expected behavior

Hitting `<RET> ` (`helm-maybe-exit-minibuffer`) in helm-mini and it using the previously selected window to display the newly opened buffer. Reasonably expect the selected buffer to take up it's new residence in that previously selected glorious large window.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

To sadly open the buffer with some magical split-window I cannot find in the source code.

## Steps to reproduce (recipe)

Open two buffers vertically, with one being much thinner than the other. Then open helm-mini, open a file and watch it split your wonderfully large buffer in half.

## Backtraces if any (`M-x toggle-debug-on-error`)

N/A

## Describe versions of Helm, Emacs, operating system, etc.

Helm:  helm-20181027.1222
Emacs: GNU Emacs 26.1
OS: Ubuntu 18.04

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):

no

## IMPORTANT NOTE

Helm provides a script named `emacs-helm.sh` which runs Helm in a neutral
environment: no other packages and only minimal settings.

When possible, use it to reproduce your Helm issue to ensure no other package is
interfering.

To run it, simply switch to the directory where Helm is installed and call `./emacs-helm.sh`.
If necessary you can specify emacs executable path on command line with "-P" option.

Thanks.

**Comment by thierryvolpiatto** [comment]
kuwze <notifications@github.com> writes:

> ## Expected behavior
>
> Hitting <RET> (helm-maybe-exit-minibuffer) in helm-mini and it using
> the previously selected window to display the newly opened
> buffer. Reasonably expect the selected buffer to take up it's new
> residence in that previously selected glorious large window.

This is the actual behavior.

> ## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
>
> To sadly open the buffer with some magical split-window I cannot find in the source code.

Please use emacs-helm.sh.

> ## Steps to reproduce (recipe)
>
> Open two buffers vertically, with one being much thinner than the
> other. Then open helm-mini, open a file and watch it split your
> wonderfully large buffer in half.

Cannot reproduce.

> ## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):
>
> no

Please do it.

--
Thierry

**Comment by kuwze** [comment]
Okay, sorry. But what is the command for selecting a window to display? I looked for display-window, select-window, and split-window-*. I think I can figure this out for myself, since obviously it isn't a problem most people are having with your excellent package.

Thanks again for working on Helm!

Sorry for writing a sarcastic bug report.

**Comment by thierryvolpiatto** [comment]
kuwze <notifications@github.com> writes:

> Okay, sorry. But what is the command for selecting a window to
> display?

Well there is not AFAIK command to select a particular window in Emacs,
instead you have command to switch to a buffer (which is displayed in a
window).  You can try for example C-x 4 b
(switch-to-buffer-other-window), you will have a helm completion (if
helm-mode is enabled) on buffers to switch to this choosen buffer in
other-window.
When used with helm-mini, when you press RET your buffer is displayed in
the window you were when starting helm, but you can switch to the
other-window by using C-c o (if no other window the current window is
splitted). With a prefix arg (with RET and C-c o) the split is done
horizontally.
other-window is determined by window-list (order).

Not sure to understand exactly what you are asking for, but hope that
helps.

--
Thierry
