### ISSUE TITLE
When minibuffer and header line are exchanged, can move point over minibuffer prompt

### ISSUE THREAD

**Issue by d125q** [emacs-helm/helm#2108]
## Expected behavior

I expect that exchanging the minibuffer and the header line preserves the property of not being able to move point over the minibuffer prompt.

## Actual behavior

I can move point over minibuffer prompt.

## Steps to reproduce (recipe)

1. `M-x` to call `helm-M-x`
2. `C-c %` to call `helm-exchange-minibuffer-and-header-line`
3. `C-b` a few times to move point backwards

## Backtraces if any (`M-x toggle-debug-on-error`)

None.

## Describe versions of Helm, Emacs, operating system, etc.

Emacs built from latest sources, Helm from MELPA.

## Are you using `emacs-helm.sh` to reproduce this bug:

Yes.

**Comment by thierryvolpiatto** [comment]
Dario Gjorgjevski <notifications@github.com> writes:

> Expected behavior
>
> I expect that exchanging the minibuffer and the header line preserves the property of not being able to move point over the minibuffer prompt.
>
> Actual behavior
>
> I can move point over minibuffer prompt.

What you are describing is not a bug, C-b CAN move cursor over the
prompt even in a minibuffer while C-a is stopping at end of prompt,
however I see a bug when moving back with C-b, the cursor is moving only
one char backward and then jump to BOL, this have been introduced by
26fc137073c5ba8a5795053617018ede0f1c58a9, you can workaround it for now
with (setq helm-display-header-line nil), I will fix this as soon as
possible.

Thanks.

--
Thierry

**Comment by d125q** [comment]
Thank you @thierryvolpiatto!
