### ISSUE TITLE
helm-ucs does not match unicode hex values

### ISSUE THREAD

**Issue by rocha** [emacs-helm/helm#2112]
## Expected behavior

- Start `helm-ucs`
- Type a unicode code point hex value, for example `2192`.
- See the code point `RIGHTWARDS ARROW` matched in the helm buffer.
- Press `Enter`
- See `→` inserted into the current buffer.

## Actual behavior 
No matches in the helm buffer. Also tried `#x2192` and `x2192`

Note that `insert-char` followed by `2182` does not show the code point, but inserts the correct character after hitting `Enter`.

## Describe versions of Helm, Emacs, operating system, etc.
```
helm-20181029.623
GNU Emacs 26.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.30)
Ubuntu 18.04.01 LST
```

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no): 
yes

**Comment by thierryvolpiatto** [comment]
We are actually matching only the last part of candidate, in your case "RIGHT ARROW".
If you want to match against the whole line we can modify the source like this:

```elisp
(defvar helm-source-ucs
  (helm-build-in-buffer-source "UCS names"
    :data #'helm-ucs-init
    :get-line #'buffer-substring
    :help-message 'helm-ucs-help-message
    ;; :match-part (lambda (candidate) (cadr (split-string candidate ":")))
    :filtered-candidate-transformer
    (lambda (candidates _source) (sort candidates #'helm-generic-sort-fn))
    :action helm-ucs-actions
    :persistent-action (lambda (candidate)
                         (helm-ucs-insert-char candidate)
                         (helm-force-update))
    :keymap helm-ucs-map)
  "Source for collecting `ucs-names' math symbols.")
```

**Comment by thierryvolpiatto** [comment]
Have a try with this definition of helm-source-ucs, you will see you match 2192.
If there is no objection of other helm-ucs users and you prefer this behavior I can merge this change.

**Comment by rocha** [comment]
@thierryvolpiatto perfect! thank you!i

**Comment by thierryvolpiatto** [comment]
Ok, I commited the change.
Thanks, closing now.
