### ISSUE TITLE
helm-occur: No such action ‘helm-moccur-save-results’ for this source when saving a helm-occur buffer

### ISSUE THREAD

**Issue by dinojr** [emacs-helm/helm#2114]
## Expected behavior
C-x C-s in a helm-occur buffer used to create a buffer with the matches from helm-occur
## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
Error message: 
`No such action ‘helm-moccur-save-results’ for this source`

## Describe versions of Helm, Emacs, operating system, etc.
helm-20181113.923 from elpa
## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):
yes

**Comment by thierryvolpiatto** [comment]
Julien Cubizolles <notifications@github.com> writes:

> Expected behavior
>
> C-x C-s in a helm-occur buffer used to create a buffer with the matches from helm-occur
>
> Actual behavior (from emacs-helm.sh if possible, see note at the bottom)
>
> Error message:
> No such action ‘helm-moccur-save-results’ for this source

I have added this error message to detect missing actions (actions
available from keybinding but not in menu), looks it works fine :-).
I have now added the missing action, should work now.

Thanks.

-- 
Thierry

**Comment by dinojr** [comment]
It's fixed, thanks a lot.
