### ISSUE TITLE
[Warning] - Helm-mode enabled (Ido is incompatible with Helm-mode, disabling it)

### ISSUE THREAD

**Issue by jcs090218** [emacs-helm/helm#2116]
## Expected behavior
No warning on starting up Emacs.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
This is the warning showing when starting the Emacs.

: Helm-mode enabled (Ido is incompatible with Helm-mode, disabling it)

## Describe versions of Helm, Emacs, operating system, etc.
20181125.1747

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):
No, I think the warning log give enough information. I just wondering why is this happening after install version 20181125.1747. Is it is normal? Do I have to disable IDO in order to run helm because I never had this issue before...

**Comment by thierryvolpiatto** [comment]
Jen-Chieh Shen <notifications@github.com> writes:

> Expected behavior
>
> No warning on starting up Emacs.
>
> Actual behavior (from emacs-helm.sh if possible, see note at the bottom)
>
> This is the warning showing when starting the Emacs.
>
> : Helm-mode enabled (Ido is incompatible with Helm-mode, disabling it)

If you have the warning, that's mean you are enabling ido-mode BEFORE
enabling helm-mode, remove the call to ido-mode or ido-everywhere in
your init file and the warning will disapear.
See issue #2085.

> Are you using emacs-helm.sh to reproduce this bug (yes/no):
>
> No,

Please always use emacs-helm.sh before reporting bugs.

> I think the warning log give enough information. I just wondering why
> is this happening after install version 20181125.1747. Is it is
> normal?

Yes.

> Do I have to disable IDO in order to run helm because I never had this
> issue before...

Yes, ido is incompatible with helm but helm is compatible with ido, see
issue #2085.

-- 
Thierry

**Comment by jcs090218** [comment]
Okay, great! I just want to make sure this is normal after version `20181125.1747`. By commenting out the `(ido-mode t)`, it all goes back to normal. Thank you!

**Comment by thierryvolpiatto** [comment]
Jen-Chieh Shen <notifications@github.com> writes:



> By commenting out the (ido-mode t), it all goes back to normal.

Good, if you want some commands use ido, add this command to
helm-completing-read-handlers-alist, e.g.

(add-to-list 'helm-completing-read-handlers-alist '(find-file . ido))

Thanks.

-- 
Thierry

**Comment by bk322** [comment]
I've the same issue with `ido-read-file-name`. Adding it in a similar way, `(add-to-list 'helm-completing-read-handlers-alist '(ido-read-file-name . ido))` does not work. What do I do?

**Comment by bk322** [comment]
I have a ton of codes, which I wrote way back when which happen to use `ido-read-file-name`. I've long forgotten all about it, but grown accustomed to my custom scripts.

**Comment by thierryvolpiatto** [comment]
You can do this easily with one of the helm*grep command + wgrep.
