### ISSUE TITLE
Possibility to preselect entry for helm-show-kill-ring

### ISSUE THREAD

**Issue by nimag42** [emacs-helm/helm#2117]
Hi,
It would be nice if we could have an optional parameter for helm-show-kill-ring to preselect an entry.

In my before-helm workflow I would do a lot C-y M-y Enter to paste 2nd newest entry in kill-ring,
And now that I have bound M-y to helm-show-kill-ring, I'm forced to do M-y twice to have the second newest. 

So I have redefined it: 
```
(defun my-helm-show-kill-ring ()
    "Like `helm-show-kill-ring' but preselect the second newest."
    (interactive)
    (setq helm-kill-ring--truncated-flag nil)
    (let ((enable-recursive-minibuffers t))
      (helm :sources helm-source-kill-ring
	    :preselect (current-kill 1 t)
	    :buffer "*helm kill ring*"
	    :resume 'noresume
	    :allow-nest t)))
```

But maybe It could be useful to have an optional param, what do you think about it?

**Comment by thierryvolpiatto** [comment]
Jacquin Théo <notifications@github.com> writes:

> Hi,
> It would be nice if we could have an optional parameter for helm-show-kill-ring to preselect an entry.
>
> In my before-helm workflow I would do a lot C-y M-y Enter to paste 2nd newest entry in kill-ring,
> And now that I have bound M-y to helm-show-kill-ring, I'm force to do M-y twice to have the second newest.

Make sense, though it is better to use the cdr of kill-ring in this case
instead of a preselection.
I have installed a change doing this in master, have a look.

Thanks.

-- 
Thierry

**Comment by nimag42** [comment]
That's a nice solution! Thanks a lot
