### ISSUE TITLE
Helm + neotree on spacemacs: unable to use Tab to switch to selected directory

### ISSUE THREAD

**Issue by phoe** [emacs-helm/helm#2120]
## Expected behavior

When using neotree in spacemacs, I used to be able to use Tab to navigate to folders inside helm. Now that functionality is broken.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

Error: `split-window: Cannot split side window or parent of side window`

## Steps to reproduce (recipe)

Download current spacemacs
`SPC f t` to open neotree
Select a directory
Hit `Tab`

## Backtraces if any (`M-x toggle-debug-on-error`)

I cannot copypaste the contents of `*Backtrace*` buffer because I cannot select text from it while the lower window is open, and once I close that window, the contents of that window disappear. The best I can give is a screenshot of my Emacs showing the backtrace.

![](https://user-images.githubusercontent.com/15045546/50385771-35b26900-06db-11e9-9626-cca94eafcdab.png)

## Describe versions of Helm, Emacs, operating system, etc.

Spacemacs 0.200 stable

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):

no

## Other things

Discussed on the spacemacs issue tracker: https://github.com/syl20bnr/spacemacs/issues/11368

**Comment by thierryvolpiatto** [comment]
Please report bugs starting from emacs-helm.sh, and not spacemacs.
Thanks.

**Comment by phoe** [comment]
I have run emacs with `emacs-helm.sh` but neotree is now not loaded. 
The package is downloaded at `~/.emacs.d/elpa/neotree-20180616.1603`
What steps are required to load neotree in this case?

**Comment by phoe** [comment]
I just noticed that the Tab button works just fine unless neotree is open. After I open and then close it, tab button works normally.

**Comment by thierryvolpiatto** [comment]
Michał Herda <notifications@github.com> writes:

> I have run emacs with emacs-helm.sh but neotree is now not loaded.
> The package is downloaded at ~/.emacs.d/elpa/neotree-20180616.1603
> What steps are required to load neotree in this case?

(load-file "/path/to/neotree.el")
M-x neotree

> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.*


-- 
Thierry

**Comment by sdwolfz** [comment]
Thanks for pointing that out @thierryvolpiatto, we do have something like that: https://github.com/syl20bnr/spacemacs/blob/c7a103a772d808101d7635ec10f292ab9202d9ee/layers/%2Bspacemacs/spacemacs-completion/funcs.el#L108.

I'll take a look at what that code does and see if I can come up with a solution.

**Comment by phoe** [comment]
@thierryvolpiatto It's weird - when I run spacemacs, `helm-default-display-buffer-functions` evaluates to `nil` in IELM. The issue nonetheless persists.

**Comment by phoe** [comment]
The error message described in https://github.com/emacs-helm/helm/issues/2115 is the same as this one though.

**Comment by sdwolfz** [comment]
@phoe If you comment out this line: https://github.com/syl20bnr/spacemacs/blob/c7a103a772d808101d7635ec10f292ab9202d9ee/layers/+spacemacs/spacemacs-completion/packages.el#L29 the problem goes away.

But helm will no longer open in a side window on the lower side, takin up the entire frame width, it will instead split the current window.

**Comment by sdwolfz** [comment]
@phoe @thierryvolpiatto This issue can be closed as the problem lies in Spacemacs entirely. Thank you for investigating!

**Comment by phoe** [comment]
@sdwolfz This is a decent workaround - at least the tab button works. Thanks!

**Comment by phoe** [comment]
Closing as per @sdwolfz request.
