### ISSUE TITLE
The `helm-find` results include `Permission denied` errors

### ISSUE THREAD

**Issue by ntc2** [emacs-helm/helm#2121]
## Expected behavior

When I run `helm-find` in a directory where I don't have permissions to read all of the directories, I expect to only see the files that `find` found, not also `find`'s stderr output with a bunch of "Permission denied" errors.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

I see a bunch of "Permission denied" errors along with the files `find` found, e.g. when running `helm-find` in `/tmp`:

```
/tmp/find: ‘/tmp/pulse-PKdhtXMmr18n’: Permission denied
/tmp/find: ‘/tmp/vmware-root’: Permission denied
/tmp/find: ‘/tmp/systemd-private-065cd41716b94ebca88d3472c06d4f13-rtkit-daemon.service-EcXduD’: Permission denied
/tmp/find: ‘/tmp/systemd-private-065cd41716b94ebca88d3472c06d4f13-colord.service-kQ8K8Q’: Permission denied
/tmp/tmux-1001-copycat
/tmp/tmux-1001
```

## Steps to reproduce (recipe)

```sh
/home/conathan/.emacs.d/.cask/25.3/elpa/helm-20181029.623/emacs-helm.sh
# Type `C-u C-x c /` to start `helm-find`.
# Type `/tmp RET` to run `find /tmp`.
# Type `mission` and see the permission errors.
```

## Backtraces if any (`M-x toggle-debug-on-error`)

None.

## Describe versions of Helm, Emacs, operating system, etc.

Ubuntu 16.04.
Emacs 25.3.
Helm elpa/helm-20181029.623.

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):

Yes.

**Comment by thierryvolpiatto** [comment]
This is same as the find command output and IMO it is what is expected, I would not want for myself to have those entries hidden.

**Comment by ntc2** [comment]
Ok, well then can you suggest a workaround? Would you accept a patch that
adds a flag to suppress this error output?

**Comment by thierryvolpiatto** [comment]
Try something like `* -perm u+rwx -prune`

**Comment by ntc2** [comment]
That doesn't work for me. The `find` command I want to run is
```
find <paths> -type d ! \( -readable -executable \) -prune -o <search patterns> -print
```
but adding
```
* -type d ! \( -readable -executable \) -prune
```
to my `helm-find` search doesn't work (in particular, `helm-find` searches for the "d" in `-type d`!?).

Would you consider a PR that added a `helm-findutils-additional-find-args` variable whose contents would be added to the `find` command generated by `helm-find`? Then I could set this variable to
`"-type d ! \( -readable -exectuble \) -prune"`.

**Comment by ntc2** [comment]
Or even more user friendly, but less flexible, a `helm-findutils-suppress-permission-denied-errors` variable that when set to `t` added `-type d ! \( -readable -executable \) -prune` to the `find` args?

**Comment by thierryvolpiatto** [comment]
Nathan Collins <notifications@github.com> writes:

> That doesn't work for me. The find command I want to run is
>
> find <paths> -type d ! \( -readable -executable \) -prune -o <search patterns> -print
>
> but adding
>
> * -type d ! \( -readable -executable \) -prune

Seems emacs doesn't support these parenthesis.

> to my helm-find search doesn't work (in particular, helm-find searches for the "d" in -type d!?).

<search pattern> * -type d ! -readable ! -executable -prune

does work.

> Would you consider a PR that added a helm-findutils-additional-find-args variable whose contents would be added to the find command generated by helm-find?
> Then I could set this variable to
> "-type d ! \( -readable -exectuble \) -prune".

No, thanks, I don't want to add complexity here, the find command is
globally working fine for most use cases, this is too much specific.

-- 
Thierry

**Comment by ntc2** [comment]
Weird, the `<search pattern> * -type d ! -readable ! -executable -prune` doesn't work over here:

![helm-find](https://user-images.githubusercontent.com/16421/50455268-c4083400-0901-11e9-9f17-195af9b996ee.png)

(Using `emacs-helm.sh` with `helm-20181222.848`).

Note that `d` is still part of the search pattern, apparently.

Also, `! -executable ! -readable` is not the same as `! \( -executable -readable \)`, and the difference matters. The correct translation is `\( ! -executable -o ! -readable \)`, and if we can't use parens I'm not sure how to expand that. I tried

```
<search patterns> * -type d ! -readable -prune -o -type d ! -executable -prune
```

but that just prints all of the pruned directories :/

**Comment by thierryvolpiatto** [comment]
Is this a real problem to have "permission denied" for some files in your display (IMO it is a good information).  IOW can we close this?
Thanks.

**Comment by ntc2** [comment]
Yes, I think it's a real problem. The errors appear first and obscure the
list of files.

But it's your project, and you've said you don't want this issue fixed, so
yes, you should probably close the issue.

**Comment by thierryvolpiatto** [comment]
Ok, you should now prevents find errors in helm-buffer with `helm-find-noerrors`.

**Comment by thierryvolpiatto** [comment]
HTH, closing now.
