### ISSUE TITLE
Feature request: Add ff-transformer-abbreviate-file-name

### ISSUE THREAD

**Issue by azzamsa** [emacs-helm/helm#2125]
It's nice to have `helm-ff-run-toggle-basename` and `helm-toggle-truncate-line`.

But sometimes:

1) we have some/ridiculously/long/directory/tree/which/is/too/deep/to/be/shown/helm.org
2) we want to see them not only by its basename. 
3) Some people love 'summarizing the path style' rather than the ex-two. e.g fish path, powerline, etc.

So rather than toggle to base name or truncate the line. The filename will be:

```
some/ridiculously/long/directory/tree/which/is/too/deep/to/be/shown/helm.org
~/s/r/l/d/t/w/is/too/deep/to/be/shown/helm.org
```

Something like [Eshell - Summarising the path](https://www.emacswiki.org/emacs/EshellPrompt#toc4)

So in this code we will have:

``` elisp
(defun helm-recentf ()
  "Preconfigured `helm' for `recentf'."
  (interactive)
  (helm :sources 'helm-source-recentf
        :ff-transformer-show-only-basename nil
        :ff-transformer-abbreviate-file-name t
:buffer "*helm recentf*"))
```

` ff-transformer-abbreviate-file-name` is just an example. Indeed the variable name is up to you :)

Thank you for helm

**Comment by thierryvolpiatto** [comment]
I don't believe this feature would help much, as long as we don't toggle to full path we have only basename shown, just a brief C-] can show the full path and a second back to basename.
I think it is enough, thus adding this to hff would reduce its performance for a small benefit IMHO.
Thanks.

**Comment by azzamsa** [comment]
For anyone get the same problem. You can use:

- `C-c >` ([helm-toggle-truncate-line](https://github.com/emacs-helm/helm/blob/a1791980f9ddca1989c65a67e6997bdde481dc27/helm.el#L236)) to truncate lines
- and `C-]` ([helm-ff-run-toggle-basename](https://github.com/emacs-helm/helm/blob/f0f174138f6f3198a6b970fd29e7caa94236e3bc/helm-types.el#L43)) to toggle the list to the basename only

[source](https://emacs.stackexchange.com/a/48824/11777)
