### ISSUE TITLE
Copy directory from dired tramp FTP using dired-dwim-target causes error

### ISSUE THREAD

**Issue by cjohansson** [emacs-helm/helm#2128]
## Expected behavior

Directory is copied to local machine without any issue

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

Error is thrown
```Debugger entered--Lisp error: (wrong-number-of-arguments (8 . 8) 10)
  helm-read-file-name-handler-1("Copy evolve to:...
```

## Steps to reproduce (recipe)

1. Use `(setq dired-dwim-target t)` and `(helm-mode 1)`
2. Open a dired buffer on a FTP host, locate a directory
3. Open another dired buffer with your local machine, have both open using split frame
4. Copy a directory from FTP by pressing C, error should appear
5. Verify it works it you disable `helm-mode` (by pressing `M-x helm-mode`)

## Describe versions of Helm, Emacs, operating system, etc.

GNU Emacs 27.0.50 (build 2, x86_64-apple-darwin18.2.0, NS appkit-1671.20 Version 10.14.2 (Build 18C54))
 of 2018-12-09
helm-20181117.731

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):

No not yet

## IMPORTANT NOTE

Helm provides a script named `emacs-helm.sh` which runs Helm in a neutral
environment: no other packages and only minimal settings.

When possible, use it to reproduce your Helm issue to ensure no other package is
interfering.

To run it, simply switch to the directory where Helm is installed and call `./emacs-helm.sh`.
If necessary you can specify emacs executable path on command line with "-P" option.

Thanks.

**Comment by thierryvolpiatto** [comment]
I think I know what's you are doing.  AFAIK `dired-dwim-target` set the directory in other window as destination but NOT the directory which is in other frame, so perhaps you are pressing RET while the destination set is the same as your initial directory?

**Comment by cjohansson** [comment]
I’ll do more thorough testing today and use ’emacs-helm.sh’

**Comment by cjohansson** [comment]
I tried to reproduce this error today but can't, the error seems to be fixed where ever it came from
