### ISSUE TITLE
helm-comint-input-ring: Use multiple lines (also with helm-slime?)

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#2131]
## Expected behavior

- `M-x shell`
- echo foo \ RET bar RET
- M-x helm-comint-input-ring
- RET

The above should insert
```
echo foo \
bar
```
at the last prompt.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
It only inserts `bar` (the last _line_ in the history).

## Note

helm-eshell-history has proper multi-line support.  I guess we could just do the same for helm-comint-input-ring.

Interestingly, helm-slime-repl-history does not have multi-line support but still inserts the whole bunch of lines when selecting a single line.  I haven't looked into the code yet.

I can send a patch for helm-comint-input-ring if you think helm-eshell-history is the right approach.
I'll backport the fix to helm-slime afterwards.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Expected behavior
>
>   * M-x shell
>   * echo foo \ RET bar RET

Sorry but I don't understand what you are doing here, what echo is
expected to send here?

-- 
Thierry

**Comment by Ambrevar** [comment]
The `\` in most shells is used to escape the line breaks to allow for multi-line commands.
The above example would look like this in Bash:

```
$ echo foo \
> bar
foo bar
```

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> The \ in most shells is used to escape the line breaks to allow for multi-line commands.
> The above example would look like this in Bash:
>
> $ echo foo \
>> bar
> foo bar

Ok, just wanted to be sure.
So helm have nothing to do with this, it is a shell bug, try to use
arrow up key in shell.

> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.*


-- 
Thierry

**Comment by Ambrevar** [comment]
Hmm... indeed :(

Bad example then.  What about geiser?
```
(display
 'ok)
```
won't work properly.
Do we need something like helm-slime's `helm-slime-repl-history`?
Shouldn't we use a multiline source?

**Comment by Ambrevar** [comment]
See #2132 for a fix.  I've also fixed it in Helm-SLIME, it's great!

**Comment by Ambrevar** [comment]
Fixed by #2135 .

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Fixed by #2135 .

Seems the multiline stuff disapeared during the merge i.e. commit
57ea1d4, not sure it is wanted.

> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.*


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Let me know, I can merge it again if needed.

**Comment by Ambrevar** [comment]
Thanks for spotting this.  Yes, please do, it's important otherwise the comint history Helm is far less usable (in Geiser, SLIME, etc.).

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Thanks for spotting this. Yes, please do, it's important otherwise the comint history Helm is far less usable (in Geiser, SLIME, etc.).

Done.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Done.
