### ISSUE TITLE
helm-semantic-or-imenu can not show function which signature is not one line

### ISSUE THREAD

**Issue by rongyi** [emacs-helm/helm#2139]
## Expected behavior
See function in the output of this command
## Steps to reproduce (recipe)
golang function 
`
func NewProxier(ipt utiliptables.Interface,
	ipvs utilipvs.Interface,
	ipset utilipset.Interface,
	sysctl utilsysctl.Interface,
	exec utilexec.Interface,
	syncPeriod time.Duration,
	minSyncPeriod time.Duration,
	excludeCIDRs []string,
	masqueradeAll bool,
	masqueradeBit int,
	clusterCIDR string,
	hostname string,
	nodeIP net.IP,
	recorder record.EventRecorder,
	healthzServer healthcheck.HealthzUpdater,
	scheduler string,
	nodePortAddresses []string,
) (*Proxier, error) {
}
`
when in this buffer I hit M-x helm-semantic-or-imenu I do not find this function to show up.
## Describe versions of Helm, Emacs, operating system, etc.
helm-core 3.0
emacs linux 26.1
## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):
No
## IMPORTANT NOTE

Helm provides a script named `emacs-helm.sh` which runs Helm in a neutral
environment: no other packages and only minimal settings.

When possible, use it to reproduce your Helm issue to ensure no other package is
interfering.

To run it, simply switch to the directory where Helm is installed and call `./emacs-helm.sh`.
If necessary you can specify emacs executable path on command line with "-P" option.

Thanks.

I googled and find this https://emacs.stackexchange.com/questions/30797/imenu-is-missing-multi-line-golang-function-signatures

**Comment by thierryvolpiatto** [comment]
I guess you are using a mode for handling Golang buffers; This mode is
in charge of providing a imenu function usable by imenu in Emacs, first
verify imenu is working with this mode enabled.
And please start with emacs-helm.sh describing all the steps you do
(enabling go-mode, opening the file etc...)
I will definitely stop accepting bugreport not using emacs-helm.sh
or starting from a minimal configuration.

荣怡 <notifications@github.com> writes:

> Expected behavior
>
> See function in the output of this command
>
> Actual behavior (from emacs-helm.sh if possible, see note at the bottom)
>
> Steps to reproduce (recipe)
>
> golang function
> func NewProxier(ipt utiliptables.Interface, ipvs utilipvs.Interface, ipset utilipset.Interface, sysctl utilsysctl.Interface, exec utilexec.Interface,
> syncPeriod time.Duration, minSyncPeriod time.Duration, excludeCIDRs []string, masqueradeAll bool, masqueradeBit int, clusterCIDR string, hostname string,
> nodeIP net.IP, recorder record.EventRecorder, healthzServer healthcheck.HealthzUpdater, scheduler string, nodePortAddresses []string, ) (*Proxier, error) {
> }
> when in this buffer I hit M-x helm-semantic-or-imenu I do not find this function to show up.
>
> Backtraces if any (M-x toggle-debug-on-error)
>
> Describe versions of Helm, Emacs, operating system, etc.
>
> helm-core 3.0
> emacs linux 26.1
>
> Are you using emacs-helm.sh to reproduce this bug (yes/no):
>
> No
>
> IMPORTANT NOTE
>
> Helm provides a script named emacs-helm.sh which runs Helm in a neutral
> environment: no other packages and only minimal settings.
>
> When possible, use it to reproduce your Helm issue to ensure no other package is
> interfering.
>
> To run it, simply switch to the directory where Helm is installed and call ./emacs-helm.sh.
> If necessary you can specify emacs executable path on command line with "-P" option.
>
> Thanks.
>
> I googled and find this https://emacs.stackexchange.com/questions/30797/imenu-is-missing-multi-line-golang-function-signatures
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.*


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
So, what I did here:
1) install go-mode from Melpa
2) start emacs -Q
3) M-x package-initialize
4) Open a go file with your code pasted in it
5) Add as well a function with a one line signature
6) M-x imenu

Only the function with a one line signature is shown, not the other, so this is a bug in go-mode, please report bug there.

Thanks.

**Comment by thierryvolpiatto** [comment]
If you modify `imenu-generic-expression` like this in go-mode .el, it is working. 
```elisp

(setq imenu-generic-expression
        '(("type" "^type *\\([^ \t\n\r\f]*\\)" 1)
          ("func" "^func *\\(.*\\)" 1)))
```
