### ISSUE TITLE
Create buffer in new window / frame

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#2140]
`helm-source-buffer-not-found` has only one action.
It'd be nice if it had actions mirroring helm-buffers to spawn the new buffer in a new window/frame.

It would also be nice to have the same bindings, i.e. `C-c o` and `C-c C-o`.

Thoughts?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Thoughts?

Done.

Thanks.

-- 
Thierry

**Comment by Ambrevar** [comment]
Thanks!
