### ISSUE TITLE
 No such action ‘helm-find-files-other-window’ for this source when run 

### ISSUE THREAD

**Issue by zw963** [emacs-helm/helm#2141]
## Steps to reproduce (recipe)

1. run **helm-browser-project**

2. C-c C-o, run **helm-ff-run-switch-other-window**

3. Get above error message

BTW: if C-c C-o from helm-find-files, it work.

## Describe versions of Helm, Emacs, operating system, etc.

Helm newest master: 1050b765, Emacs 26.1 Arch Linux.

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):
Yes

Thanks

**Comment by thierryvolpiatto** [comment]
Billy.Zheng <notifications@github.com> writes:

> Steps to reproduce (recipe)
>
>  1. run helm-browser-project

I think you mean helm-browse-project?
    
>  2. C-c C-o, run helm-ff-run-switch-other-window

If you are running emacs-helm.sh, at this point helm-ls-git should not
be loaded and the only source you have is a buffer list under this
directory. In this source, C-c C-o is bound to
`helm-buffer-switch-other-frame` and C-c o is bound to
`helm-buffer-switch-other-window`.
    
>  3. Get above error message

It is not reproductible here.

Please provide a backtrace from emacs-helm.sh.

Thanks.
    
-- 
Thierry

**Comment by zw963** [comment]
> I think you mean helm-browse-project?

Yes.

> If you are running emacs-helm.sh, at this point helm-ls-git should not be loaded and the only source you have is a buffer list under this directory. In this source, C-c C-o is bound to `helm-buffer-switch-other-frame` and C-c o is bound to `helm-buffer-switch-other-window`.

Sorry for confusing, yes, i am place helm-ls-git into git repo, it loaded unexpected.
I thought this issue is about **helm-ls-git**, in this case,  **C-c o** is binding to **helm-find-files-other-window**,  **C-c C-o** is binding to **find-file-other-frame**, above two binding all not working.

But, when move down to select in buffer-list, all binding bind well like you say, and work well.

So, should i create a new issue to "helm-ls-git" ??

Thanks

**Comment by thierryvolpiatto** [comment]
Billy.Zheng <notifications@github.com> writes:

>     I think you mean helm-browse-project?
>    
> Yes.
>
>     If you are running emacs-helm.sh, at this point helm-ls-git should not be loaded and the only source you have is a buffer list under this directory. In
>     this source, C-c C-o is bound to helm-buffer-switch-other-frame and C-c o is bound to helm-buffer-switch-other-window.
>    
> Sorry for confusing, yes, i am place helm-ls-git into git repo, it loaded unexpected.
> I thought this issue is about helm-ls-git, in this case, C-c o is binding to helm-find-files-other-window, C-c C-o is binding to find-file-other-frame,
> above two binding all not working.
>
> But, when move down to select in buffer-list, all binding bind well like you say, and work well.
>
> So, should i create a new issue to "helm-ls-git" ??

From emacs-helm.sh, if I do

    (add-to-list 'load-path "/path/to/helm-ls-git/directory")

Then call helm-browse-project from a buffer or helm-find-files (C-x
C-d), then hit C-c o or C-c C-o it works as expected without error.

So it is not a helm-ls-git issue and not a helm-browse-project issue
which is soft requiring helm-ls-git properly.

So here's a recipe that works fine here:

1) start emacs-helm.sh
2) In scratch buffer evaluate 
    (add-to-list 'load-path "~/elisp/helm-extensions")
and
    (find-file "/path/to/any/file/under/git/repo/yourfile")
3) From the yourfile buffer M-x helm-browse-project
4) C-c o or C-c C-o from the git ls file source

-- 
Thierry
