### ISSUE TITLE
[org-mode] helm-org-in-buffer-headings incorrect tree expansion

### ISSUE THREAD

**Issue by grigorievich** [emacs-helm/helm#2142]
## Steps to reproduce (recipe)

- `M-x org-mode`

- paste the following text:
  
```
* (1) Uppers
** (2) Downers
   screamers, laughers
** (3) ...and also a quart of tequila
   a quart of rum, a case of Budweiser, 
** (4) a pint of raw ether and two dozen amyls.
```

- collapse the whole tree

- `M-x helm-org-in-buffer-headings`

- In the list, choose (2) Downers

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

Observe ellipsis:

```
* (1) Uppers
** (2) Downers
   screamers, laughers
...
```

## Expected behavior

```
* (1) Uppers
** (2) Downers
   screamers, laughers
** (3) ...and also a quart of tequila
** (4) a pint of raw ether and two dozen amyls.
```

## Describe versions of Helm, Emacs, operating system, etc.

helm-20190316.805
GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.7) of 2019-03-17
Org mode version 9.1.9 (release_9.1.9-65-g5e4542 @ /usr/share/emacs/26.1/lisp/org/)

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):

yes

**Comment by thierryvolpiatto** [comment]
I can't reproduce, and also the expected behavior is what the screenshot below shows.
![Capture d’écran_2019-03-25_07-37-24](https://user-images.githubusercontent.com/1533939/54899748-235dec00-4ed1-11e9-8208-707df9410e8d.png)

**Comment by thierryvolpiatto** [comment]
Oh! I see it is when you execute the action you want the full context of your org buffer, but this is due to org itself, not helm, see documentation of `org-show-context` and `org-show-context-detail` for more informations, in short use `C-c-C-r` to show more context if what you have is not enough after jumping to an heading from org.

**Comment by thierryvolpiatto** [comment]
Or if you want always the same behavior configure `org-show-context-detail`.
something like `(setq org-show-context-detail '((default . tree)))` should do what you want.

**Comment by grigorievich** [comment]
@thierryvolpiatto 

> org-show-context and org-show-context-detail for more informations, 

Thanks, that explains it.

> in short use C-c-C-r to show more context if what you have is not enough after jumping to an heading from org.

Yeah, that's what I have to do now: press tab twice to expand.

> `(setq org-show-context-detail '((default . tree)))`

That helps [though better use `(setf (alist-get 'default org-show-context-detail) 'tree)`].

It's not a full fix unfortunately (I have tried with all other values other than 'tree).

Consider the following example. I am using canonical here:

```
canonical      show current headline, its direct ancestors along with
               their entries and children; if point is not located on
               the headline, also show current entry and all children
```

```
* (1) Uppers
** (2) Downers
   screamers
*** laughers
    ...and also a quart of tequila
** (3) a quart of rum,
   a case of Budweiser,
** (4) a pint of raw ether and two dozen amyls.
```

If I choose `(1) Uppers`, I get:

```
* (1) Uppers
...
```

And if I choose `(2) Downers`, I get:

```
* (1) Uppers
** (2) Downers
   screamers
...
** (3) a quart of rum,
** (4) a pint of raw ether and two dozen amyls.
```

Where are my laughers? Expected:

```
* (1) Uppers
** (2) Downers
   screamers
*** laughers...
** (3) a quart of rum,
** (4) a pint of raw ether and two dozen amyls.
```

While better than what I had before, surely, these can't be satisfactory. It probably warrants a bug report / feature request to org-mode.

But some questions first.

(1) Is 'default the proper thing to use?
there is: agenda, org-goto, occur-tree, tags-tree, link-search, mark-goto, bookmark-jump, isearch, default
Does helm use any of these?

(2) As a temporary fix, I want to run `(lambda () (interactive) (org-cycle) (org-cycle))` after selecting a headline. Org-cycling two times does what I want.
Is there an appropriate hook or a function to advise?

**Comment by thierryvolpiatto** [comment]
I am not an org expert, so I can't help you more about org variables usage, sorry.
And no, helm do nothing special in its call of  `org-show-context`.

**Comment by grigorievich** [comment]
@thierryvolpiatto Alright, I see. Thanks!
