### ISSUE TITLE
Collapse on unique helm candidate

### ISSUE THREAD

**Issue by dakrone** [emacs-helm/helm#2144]
This is a feature request, let's say you have a big file and use something like helm-swoop (though helm-occur and pretty much any helm command would work):

![collapse](https://user-images.githubusercontent.com/19060/54958046-1b766a00-4f1a-11e9-971b-0eab09e4269a.png)

It'd be really cool if helm could collapse on all *unique* values for its candidates, so instead of

```
1:  candidate1
2:  candidate3
3:  candidate1
4:  candidate2
7:  candidate2
123:  candidate2
125:  candidate2
234:  candidate2
453:  candidate2
500:  candidate2
```

It would collapse into:

```
1:  candidate2 (7 matches)
2:  candidate1 (2 matches)
3:  candidate3 (1 match)
```

Thanks for all your work on helm!

(I know helm is in bugfix only mode, but this is a feature request for if/when helm development resumes)

**Comment by thierryvolpiatto** [comment]
Lee Hinman <notifications@github.com> writes:

> This is a feature request, let's say you have a big file and use
> something like helm-swoop (though helm-occur and pretty much any helm
> command would work):

You should use helm-occur instead of helm-swoop...

> collapse
>
> It'd be really cool if helm could collapse on all unique values for its candidates, so instead of
>
> 1:  candidate1
> 2:  candidate3
> 3:  candidate1
> 4:  candidate2
> 7:  candidate2
> 123:  candidate2
> 125:  candidate2
> 234:  candidate2
> 453:  candidate2
> 500:  candidate2
>
> It would collapse into:
>
> 1:  candidate2 (7 matches)
> 2:  candidate1 (2 matches)
> 3:  candidate3 (1 match)

If doing something like this, how would you execute any action on say
"234: candidate2"?
How would you even know it exists?

Thanks.

--
Thierry

**Comment by dakrone** [comment]
> If doing something like this, how would you execute any action on say "234: candidate2"? How would you even know it exists?

Perhaps the action once the candidates are collapse could be "search for 'candidate2'" to highlight those candidates in the buffer.

I tend to use helm in this way as in interactive discovery tool, reading large files (log files, json files) to get an overview of information, rather than actually performing any action on them.

**Comment by dakrone** [comment]
> You should use helm-occur instead of helm-swoop...

I use both, they have different performance behaviors, so in files with lots of lines (for example the one I'm looking at has 43,300 lines) `helm-swoop` can complete interactive searches that `helm-occur` takes ~10-15 seconds to complete

**Comment by thierryvolpiatto** [comment]
Lee Hinman <notifications@github.com> writes:

>     You should use helm-occur instead of helm-swoop...
>
> I use both, they have different performance behaviors, so in files
> with lots of lines (for example the one I'm looking at has 43,300
> lines) helm-swoop can complete interactive searches that helm-occur
> takes ~10-15 seconds to complete

Really? I am really interested by this, normally helm-occur should be
faster than helm-swoop, any chance to get the file to make some test and
try to fix this in helm-occur?

Thanks.

--
Thierry

**Comment by thierryvolpiatto** [comment]
I created a separate issue for helm-occur slowness.
Indeed I tried with a 6.2Mo buffer and occur, swoop and helm-occur are unusable, too slow, helm-occur being the slowest.
I am actually fixing this in new_occur branch, you can have a try, results are popping up after a few seconds (nearly instant) where the fastest other implementations take at least 30/40s.
Many features are missing but will come soon.
HTH.

**Comment by dakrone** [comment]
> Really? I am really interested by this, normally helm-occur should be faster than helm-swoop, any chance to get the file to make some test and try to fix this in helm-occur?

I'm not sure if it makes any difference, but I do `(setq helm-swoop-speed-or-color nil)` to attempt to make helm-swoop faster (since helm-occur keeps colors).

As for the file, here's a gzipped copy: [tasks.json.gz](https://github.com/emacs-helm/helm/files/3019045/tasks.json.gz)

I tested this with the new `helm-occur` (using `./emacs-helm.sh` from the `new_occur` branch), I searched for `action"` and timed how long it took for the results to show, it was 9.55 seconds with `helm-occur` and around ~1 second (too fast for me to time with a stopwatch) with `helm-swoop` (I opened `helm-swoop.el` in the Emacs from `./emacs-helm.sh` and did `eval-buffer` to make it available there, so both were using the default configuration).

Perhaps it's that `helm-occur` supports all the faces while searching and `helm-swoop` does not? However, I tried putting the buffer into `fundamental-mode` and got the same results (helm-occur about 10x slower than helm-swoop)

EDIT: I just noticed in the branch that it wasn't `helm-occur` that was rewritten, it was `helm-mini-occur`. When I test with `helm-mini-occur`, searching is as fast as helm-swoop.

**Comment by thierryvolpiatto** [comment]
Lee Hinman <notifications@github.com> writes:

> As for the file, here's a gzipped copy: tasks.json.gz

Thanks.

> I tested this with the new helm-occur (using ./emacs-helm.sh from the new_occur branch), I searched for action" and timed how long it took for the results
> to show, it was 9.55 seconds with helm-occur and around ~1 second (too fast for me to time with a stopwatch) with helm-swoop (I opened helm-swoop.el in the
> Emacs from ./emacs-helm.sh and did eval-buffer to make it available there, so both were using the default configuration).
>
> Perhaps it's that helm-occur supports all the faces while searching
> and helm-swoop does not?

No the big bottleneck is with the get-line function that use for each
line line-number-at-pos which is highly costly.

> However, I tried putting the buffer into fundamental-mode and got the
> same results (helm-occur about 10x slower than helm-swoop)


> EDIT: I just noticed in the branch that it wasn't helm-occur that was
> rewritten, it was helm-mini-occur.

Yes it is just a temporary name, it should become again helm-occur when
it will be ready to merge.

> When I test with helm-mini-occur, searching is as fast as helm-swoop.

Yes, with a larger file it makes a difference, helm-mini-occur become
much faster than helm-swoop.

Thanks to test all this.

--
Thierry

**Comment by dakrone** [comment]
> No the big bottleneck is with the get-line function that use for each line line-number-at-pos which is highly costly.

Interesting, is that something I could turn off? I took a cursory glance through the helm variables but didn't see any that looked like they were related.

**Comment by thierryvolpiatto** [comment]
Lee Hinman <notifications@github.com> writes:

>     No the big bottleneck is with the get-line function that use for each line line-number-at-pos which is highly costly.
>    
> Interesting, is that something I could turn off?

No, this is used internally, you will have to wait the new helm-occur
version aka helm-mini-occur for now.

> I took a cursory glance through the helm variables but didn't see any
> that looked like they were related.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.*


-- 
Thierry

**Comment by dakrone** [comment]
Okay thanks, I will wait for the new `helm-occur`.

In the meantime, since there is already an issue for the new `helm-occur` (#2146) do you want to keep this open to discuss unique candidate collapsing?

**Comment by thierryvolpiatto** [comment]
Lee Hinman <notifications@github.com> writes:

> Okay thanks, I will wait for the new helm-occur.
>
> In the meantime, since there is already an issue for the new
> helm-occur (#2146) do you want to keep this open to discuss unique
> candidate collapsing?

Well keep it open for now but I am not sure this feature will be
reliable especially with large buffer (I am afraid it will reduce performances
largely).

Thanks.

> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.*


--
Thierry

**Comment by thierryvolpiatto** [comment]
Closing now, this would alter largely performances doing such a computation (we do this when backing up files with same name from several directories e.g. backup from HFF all ".md" files in all subdirectories using "**.md" and it is not very fast but as it is a one shot operation it is usable).
Thanks to show me the slowness of old helm-occur!
