### ISSUE TITLE
helm-do-grep-ag uses thing at point as input, but without displaying it in the minibuffer

### ISSUE THREAD

**Issue by kaofelix** [emacs-helm/helm#2145]
## Expected behavior

`helm-do-grep-ag` should open with the thing at point displaying in the minibuffer prompt as the default input. Alternatively I would have a way to disable it and it wouldn't show any results at first. 

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

Helm shows results for the thing at point but the prompt in the mini buffer is empty, like in the screenshot:

<img width="692" alt="Screen Shot 2019-03-27 at 15 45 34" src="https://user-images.githubusercontent.com/223625/55085693-640f5e00-50a7-11e9-8a9a-2985643e05ee.png">

## Steps to reproduce (recipe)

1. I start emacs-helm.sh
2. I run `M-x helm-do-grep-ag` with point over a word, e.g. 'context' as in the screenshot above
3. A helm buffer opens with results for the word `context`, but the `pattern: ` prompt at the minibuffer is empty

## Describe versions of Helm, Emacs, operating system, etc.

Emacs 26.1 on macOS 10.13.6

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):

Yes

**Comment by thierryvolpiatto** [comment]
Kao Félix <notifications@github.com> writes:

> Expected behavior
>
> helm-do-grep-ag should open with the thing at point displaying in the
> minibuffer prompt as the default input.

No, because it is not :input but :default which is used, it is much better
because it allows you to type in anything else if thing-at-point is not
what you want.

> Alternatively I would have a way to disable it and it wouldn't show
> any results at first.

You can disable this by customizing
`helm-sources-using-default-as-input`.

-- 
Thierry

**Comment by kaofelix** [comment]
Ok, I think I get it. I guess I didn't really understand what :default meant for helm. So :default is meant to build an initial candidate list *without* using the query term as the initial input. Did I understand this right?

> You can disable this by customizing
> `helm-sources-using-default-as-input`.

Now I get the meaning of this variable too, I was confused on what exactly it would do at first. 

> it is much better because it allows you to type in anything else if thing-at-point is not
> what you want.

I understand where you're coming from and how people would prefer this behaviour, but often I look for thing-at-point and then I want to narrow the results down by typing extra words. Then I need to retype thing-at-point if I want to keep the same result set as before and further filter it. To me it would feel a lot more natural to have thing-at-point filled in at the prompt and in the cases I don't need it I would delete-word-backwards and type my new search. The existing behaviour was counter intuitive enough to me to genuinely think this was a bug, but I might be alone in this.

Is there a straightforward way to get pre filled input on `helm-grep-do-ag`? I could replace `helm-grep-ag-1` to have an :input keyword to the helm call in there, but if there's an easier way to make it behave like this from the "outside", maybe with a let around a `helm-do-grep-ag` call?

**Comment by thierryvolpiatto** [comment]
Kao Félix <notifications@github.com> writes:

> Ok, I think I get it. I guess I didn't really understand what :default meant for helm. So :default is meant to build an initial candidate list without using
> the query term as the initial input. Did I understand this right?
>
>     You can disable this by customizing
>     helm-sources-using-default-as-input.
>
> Now I get the meaning of this variable too, I was confused on what exactly it would do at first.
>
>     it is much better because it allows you to type in anything else if thing-at-point is not
>     what you want.
>
> I understand where you're coming from and how people would prefer this
> behaviour, but often I look for thing-at-point and then I want to
> narrow the results down by typing extra words. Then I need to retype
> thing-at-point

No, you don't have to retype thing-at-point, just use M-n as in emacs
vanilla completing-read and friends.

> if I want to keep the same result set as before and further filter
> it. To me it would feel a lot more natural to have thing-at-point
> filled in at the prompt and in the cases I don't need it I would
> delete-word-backwards and type my new search. The existing behaviour
> was counter intuitive enough to me to genuinely think this was a bug,
> but I might be alone in this.
>
> Is there a straightforward way to get pre filled input on helm-grep-do-ag? I could replace helm-grep-ag-1 to have an :input keyword to the helm call in
> there, but if there's an easier way to make it behave like this from the "outside", maybe with a let around a helm-do-grep-ag call?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.*


--
Thierry

**Comment by kaofelix** [comment]
> just use M-n as in emacs vanilla completing-read and friends.

I knew about M-p and M-n to navigate history and C-w in isearch to add stuff from point, but I was oblivious to the fact that minibuffer history could have defaults available beyond the past history. Thanks for the tip and clarifications! I'm closing the issue since it's not really a bug after all and just a misconception on my part.
