### ISSUE TITLE
Fix helm-(m)occur performances in large buffers

### ISSUE THREAD

**Issue by thierryvolpiatto** [emacs-helm/helm#2146]
Related to issue #2144.
Started writing a new helm-occur, see branch new_occur.

**Comment by thierryvolpiatto** [comment]
The new helm-occur is now in helm-occur.el, it is mostly functional except the save results, edit results etc... stuff.
This new helm-occur have been tested in a 6.2Mo buffer with good results (popup in few seconds whereas other alternatives takes ages to popup in such buffer).
Should be ready soon!

**Comment by thierryvolpiatto** [comment]
* TODO
 [X] Save results for further editing with wgrep
 [X] Add the mode for editing
 [X] Add switch OF and OW actions
 [X] Add keymap
 [X] Add history
 [X] Prevent marking
 [X] Migemo
 [X] Add group attr
 [] Write revert buffer action for saved buffer
 [] Autoupdate on resume
 [] Add the from isearch functions
 [] Prefix all with helm-occur instead of helm-mini-occur
 [] Remove old code from helm-regexp when all done
 [] Provide patch to emacs-wgrep for this (fix names before)

**Comment by thierryvolpiatto** [comment]
I have now merged new helm-occur in master, test as much as possible and let me know if there if you find bugs.
Thanks.
Note: Running helm-occur from isearch have not yet been merged, coming soon.

**Comment by thierryvolpiatto** [comment]
Note also that wgrep is now broken for Helm until I provide a patch to wgrep, here the patch for those that can't wait:

```diff
diff --git a/wgrep-helm.el b/wgrep-helm.el
index 0ee8384..8ea014f 100644
--- a/wgrep-helm.el
+++ b/wgrep-helm.el
@@ -71,10 +71,15 @@
              (dispname (match-string 1))
              (namelen (length dispname)))
         (let* ((value (get-text-property (point) 'helm-realvalue))
-               (data  (helm-grep-split-line value))
+               (data  (when (eq major-mode 'helm-grep-mode)
+                        (helm-grep-split-line value)))
                (fn    (or (get-text-property (point) 'buffer-name)
                           (get-text-property (point) 'helm-grep-fname)))
-               (line  (string-to-number (nth 1 data)))
+               (line  (if data
+                          (string-to-number (nth 1 data))
+                        ;; Real value of candidate is now the line
+                        ;; number in helm-occur.
+                        value))
                (fprop (wgrep-construct-filename-property fn)))
           (put-text-property start end 'wgrep-line-filename fn)
           (put-text-property start end 'wgrep-line-number line)
@@ -85,12 +90,13 @@
 (add-hook 'helm-grep-mode-hook 'wgrep-helm-setup)
 
 ;;;###autoload
-(add-hook 'helm-moccur-mode-hook 'wgrep-helm-setup)
+(add-hook 'helm-occur-mode-hook 'wgrep-helm-setup)
 
 ;; For `unload-feature'
 (defun wgrep-helm-unload-function ()
   (remove-hook 'helm-grep-mode-hook 'wgrep-helm-setup)
-  (remove-hook 'helm-moccur-mode-hook 'wgrep-helm-setup))
+  (remove-hook 'helm-moccur-mode-hook 'wgrep-helm-setup)
+  (remove-hook 'helm-occur-mode-hook 'wgrep-helm-setup))
 
 (provide 'wgrep-helm)
 
```

**Comment by thierryvolpiatto** [comment]
Here the performances we have for now:

```elisp
;; New helm-occur (cursor on defun in test-helm-occur.el 6.5Mo)
(with-helm-time-after-update (helm-occur))
;; 2.67
;; Old helm-occur (Helm version 3.1)
;; 367.91
;; Helm-swoop
(with-helm-time-after-update (helm-swoop :$query "defun"))
;; 2.54
;; Occur
(benchmark-run-compiled 1 (occur "defun"))
;; 4.55
```
As you can see we have similar performance as helm-swoop, thought helm-swoop have once the buffer popup very bad navigation performance (C-n C-p).
The small difference with helm-swoop is due probably to extra properties (face, help-echo) added when computing candidates.

**Comment by thierryvolpiatto** [comment]
A PR have been submitted to emacs-wgrep:
https://github.com/mhayashi1120/Emacs-wgrep/pull/57
So as soon it is merged wgrep should work again with new helm-occur.

**Comment by thierryvolpiatto** [comment]
Update: I have optimized a bit more how to get candidates (now using helm-source-in-buffer).
```elisp
;; New helm-occur with in-buffer method
(with-helm-time-after-update (helm-occur))
;; =>1.437676191329956
```

**Comment by cmccloud** [comment]
I'm getting unusually high memory usage when using the `save-buffer` action from `helm-occur` when there are a large number of results. It took my computer about 20 seconds to display the buffer - although I can get that down significantly if I disable garbage collection. For comparison, `occur` is able to display the results buffer in about a second with the same query, without the memory issue. I'm on emacs 27.0.50

Steps to reproduce:
From emacs-helm.sh
Run helm-occur on helm.el with 'helm' as the query
F4 to call the 'Save buffer' action


```
CPU Profiler Report
- ...                                                           13006  78%
   Automatic GC                                                 13006  78%
- command-execute                                                3484  21%
 - call-interactively                                            3484  21%
  - funcall-interactively                                        3425  20%
   - helm-M-x                                                    3425  20%
    - command-execute                                            3425  20%
     - call-interactively                                        3425  20%
      - funcall-interactively                                    3425  20%
       - helm-occur                                              3422  20%
        - helm                                                   3422  20%
         - apply                                                 3422  20%
          - helm                                                 3422  20%
           - apply                                               3422  20%
            - helm-internal                                      3422  20%
             - helm-execute-selection-action                     3308  20%
              - helm-execute-selection-action-1                  3308  20%
               + helm-occur-save-results                           21   0%
             + helm-read-pattern-maybe                            112   0%
             + #<compiled 0x1583a911a549>                           2   0%
       + profiler-report                                            2   0%
         profiler-start                                             1   0%
  + byte-code                                                      59   0%
+ redisplay_internal (C function)                                   4   0%
  tooltip-show-help                                                 1   0%
+ timer-event-handler                                               1   0%
```

```
Memory Profiler Report
- command-execute                                       7,379,226,857  99%
 - call-interactively                                   7,379,226,857  99%
  - funcall-interactively                               7,321,034,816  99%
   - helm-M-x                                           7,321,033,720  99%
    - command-execute                                   7,321,033,720  99%
     - call-interactively                               7,321,033,720  99%
      - funcall-interactively                           7,321,033,688  99%
       - helm-occur                                     7,316,964,978  99%
        - helm                                          7,316,962,692  99%
         - apply                                        7,316,961,668  99%
          - helm                                        7,316,961,668  99%
           - apply                                      7,316,961,668  99%
            - helm-internal                             7,316,961,668  99%
             - helm-execute-selection-action            7,281,303,456  98%
              - helm-execute-selection-action-1         7,281,302,312  98%
               + helm-occur-save-results                   18,197,684   0%
              + helm-log-run-hook                               1,144   0%
             + helm-read-pattern-maybe                     24,998,548   0%
             + helm-initialize                             10,430,436   0%
             + helm-display-buffer                            227,530   0%
             + helm--remap-mouse-mode                           1,056   0%
             + #<compiled 0x1583a911a549>                         642   0%
           helm-parse-keys                                      1,024   0%
        + thing-at-point                                        2,202   0%
       + profiler-report                                    4,063,162   0%
       + profiler-start                                         5,548   0%
   + handle-focus-out                                           1,056   0%
   + mouse-drag-region                                             40   0%
  + byte-code                                              58,192,041   0%
+ redisplay_internal (C function)                             428,707   0%
+ tooltip-show-help                                             2,392   0%
  mouse-fixup-help-message                                      1,152   0%
+ mouse--click-1-maybe-follows-link                             1,104   0%
+ timer-event-handler                                           1,056   0%
+ eldoc-schedule-timer                                             16   0%
  ...                                                               0   0%

```

**Comment by thierryvolpiatto** [comment]
Christopher McCloud <notifications@github.com> writes:

> I'm getting unusually high memory usage when using the save-buffer
> action from helm-occur when there are a large number of results. It
> took my computer about 20 seconds to display the buffer - although I
> can get that down significantly if I disable garbage collection. For
> comparison, occur is able to display the results buffer in about a
> second with the same query, without the memory issue. I'm on emacs
> 27.0.50

Thanks for the report, will try to fix this ASAP.


--
Thierry

**Comment by thierryvolpiatto** [comment]
Done, saving is instant now.  Seems all working fine after this change (revert-buffer, wgrep), let me know if something not working.
Thanks.

**Comment by cmccloud** [comment]
I'm seeing instant saves here as well.
Thanks and much appreciated.

**Comment by c02y** [comment]
Question:
~~~
[X] Add the mode for editing
~~~
Does it means I can edit the helm-occur buffer directly like `helm-swoop`? If it is so, how can do that?

**Comment by thierryvolpiatto** [comment]
c02y <notifications@github.com> writes:

> Question:
>
> [X] Add the mode for editing
>
> Does it means I can edit the helm-occur buffer directly like helm-swoop? If it is so, how can do that?

C-x C-s then M-x wgrep-change-to-wgrep-mode (of course you need wgrep
installed).

Note that when you are in a helm-occur session (and any other helm
session) you can hit C-h m to have all this explained ;-)


-- 
Thierry

**Comment by dvzubarev** [comment]
It would be convenient to open edit buffer with C-e keybinding like with helm-swoop. Is it possible?

**Comment by thierryvolpiatto** [comment]
dvzubarev <notifications@github.com> writes:

> It would be convenient to open edit buffer with C-e keybinding like
> with helm-swoop. Is it possible?

Saving results is bound actually to C-x C-s which is `helm-occur-run-save-buffer`,
you can bind this command to C-e in `helm-occur-map` if you want, but
keep in mind you will loose C-e (move-end-of-line) which is useful.

But maybe I am misunderstanding your request as I never used helm-swoop
edit command.
With helm-occur, the saved buffer is not dedicated to a particular
buffer as it can contain the results of more than one buffer, perhaps it
is what you were asking for?

--
Thierry

**Comment by dvzubarev** [comment]
I mean you don't need to `M-x wgrep-change-to-wgrep-mode` with helm-swoop. You just press C-c C-e (forgot about C-c prefix) and you are in the edit buffer. With helm-occur you need to do two actions as you wrote: `C-x C-s` then `M-x wgrep-change-to-wgrep-mode`.

**Comment by thierryvolpiatto** [comment]
dvzubarev <notifications@github.com> writes:

> I mean you don't need to M-x wgrep-change-to-wgrep-mode with
> helm-swoop. You just press C-c C-e (forgot about C-c prefix) and you
> are in the edit buffer. With helm-occur you need to do two actions as
> you wrote: C-x C-s then M-x wgrep-change-to-wgrep-mode.

Yes, because the saved buffer could be used just for further navigation,
so it is up to the user to turn on the edit mode, it is bound to `C-c
C-p`, see `wgrep-enable-key` to change this (I use C-x C-q).
Perhaps to enable this automatically after using C-x C-s you can use the
`helm-occur-mode-hook`, something like:

    (add-hook 'helm-occur-mode-hook 'wgrep-change-to-wgrep-mode)

Fully not tested! Let me know if it works, I will add this to helm-occur
documentation.

Thanks.

> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.*


--
Thierry

**Comment by thierryvolpiatto** [comment]
If it works with the hook, probably I will have to kill local variables when overwriting an already existing *hmocur* buffer, let me know.
Probably a bug can be produced by trying to edit a buffer with wgrep, then overwrite this buffer with a new search and try to reedit as well with wgrep.
A fix for this (if the bug exists dunno) would be adding a call to `kill-all-local-variables` after erasing buffer.

**Comment by thierryvolpiatto** [comment]
Probably you need also to add the hook at the end as wgrep need to setup buffer before:

```elisp
 (add-hook 'helm-occur-mode-hook 'wgrep-change-to-wgrep-mode t)
```
Notice the APPEND argument of `add-hook` is used here.

**Comment by thierryvolpiatto** [comment]
I have added a call to kill-all-local-variables when saving buffer.
