### ISSUE TITLE
Helm makes assumptions about `ls` and availability of `-Q` switch

### ISSUE THREAD

**Issue by fengshaun** [emacs-helm/helm#2147]
using `helm-find-files` with tramp from linux client connecting to freebsd fails to list directories. Looking at tramp's trace, I see an error which complains that the `-Q` option in freebsd's `ls` doesn't exist which I confirmed on the machine.

The offending line is https://github.com/emacs-helm/helm/blob/master/helm-files.el#L2554 which assumes `-Q` exists on target platform.

I assume other BSDs are affected, although I haven't tested. I haven't looked into if there's a way to do without this switch, but hope there is.

At this point, I have started using `helm-list-dir-lisp` to work around the issue.

**Comment by thierryvolpiatto** [comment]
fengshaun <notifications@github.com> writes:

> using helm-find-files with tramp from linux client connecting to
> freebsd fails to list directories. Looking at tramp's trace, I see an
> error which complains that the -Q option in freebsd's ls doesn't exist
> which I confirmed on the machine.

Thanks for the info, didn't know ls FREEBSD version didn't have -Q.
In this case customize `helm-list-directory-function` so that it use
`helm-list-dir-lisp`, I will try later to fix the defcustom so that it
use `helm-list-dir-lisp` for FREEBSD.

Thanks.

--
Thierry

**Comment by thierryvolpiatto** [comment]
After reading https://www.unix.com/man-page/FreeBSD/1/ls/ I am afraid this LS version is incompatible with what we want to do here, in addition of -Q missing, their -F option provides incompatible flags as well.

**Comment by fengshaun** [comment]
Unfortunately, I don't think this is something that can be solved easily without compromise. Even running emacs+helm on a linux machine with gnu ls, connecting through tramp to different platforms (in my case, freebsd) can invoke the issue. So, adding a cl-case for freebsd isn't going to do anything. The real problem is here:

```
(defcustom helm-list-directory-function
  (cl-case system-type
    (gnu/linux #'helm-list-dir-external)
    (berkeley-unix #'helm-list-dir-external)
    (windows-nt #'helm-list-dir-lisp)
    (t #'helm-list-dir-lisp))
  "The function used in `helm-find-files' to list remote directories.
Actually helm provides two functions to do this: `helm-list-dir-lisp'
and `helm-list-dir-external'.
Using `helm-list-dir-external' will provides a similar display to what
provided with local files i.e. colorized symlinks, executables files
etc... whereas using `helm-list-dir-lisp' will allow colorizing only
directories but is more portable.
NOTE that `helm-list-dir-external' needs ls and awk as dependencies."
  :type 'function
:group 'helm-files)
```

The only way around this issue is to figure out the remote system type before deciding which directory listing function to use, but that would add quite a bit of delay for every connection. Connection information could be cached, though, adding a whole lot of complexity for little gain. There doesn't look to be a perfect solution, or even a better one than the current implementation.

I'm happy with `helm-list-dir-lisp` and it's working well. I've resolved to use it everywhere as I work on different platforms. I thought I would bring this to attention just in case someone else has a solution.

And thanks for `helm`, it's the best package I've used and it's life-changing! :)

**Comment by thierryvolpiatto** [comment]
fengshaun <notifications@github.com> writes:

> Unfortunately, I don't think this is something that can be solved
> easily without compromise. Even running emacs+helm on a linux machine
> with gnu ls, connecting through tramp to different platforms (in my
> case, freebsd) can invoke the issue. So, adding a cl-case for freebsd
> isn't going to do anything.

You are right, ls run on the remote end, I made an assomption that the
other platforms you connect to are the same than yours but it is stupid.

> The only way around this issue is to figure out the remote system type
> before deciding which directory listing function to use, but that
> would add quite a bit of delay for every connection. Connection
> information could be cached, though, adding a whole lot of complexity
> for little gain.

Yes I don't want to enter in such complexity.

> There doesn't look to be a perfect solution, or even a better one than
> the current implementation.

Perhaps what I can do is using helm-list-dir-lisp as default and update
the docstring.

> I'm happy with helm-list-dir-lisp and it's working well. I've resolved
> to use it everywhere as I work on different platforms. I thought I
> would bring this to attention just in case someone else has a
> solution.

Great, thanks.

> And thanks for helm, it's the best package I've used and it's life-changing! :)

Glad to know you are happy with Helm!

--
Thierry

**Comment by fengshaun** [comment]
Having `helm-list-dir-lisp` as default and noting it in docs would fix this issue. Thanks.
