### ISSUE TITLE
[Feature Request] helm-buffers display issue

### ISSUE THREAD

**Issue by zw963** [emacs-helm/helm#2148]
Though use `helm-mini` day and day, but some issue about `helm-buffer` keep confused me.

1. **ignore specified mode buffer** (Or match on another column instead of name, e.g. i want to ignore  all `dired-mode` buffer, or ignore based on `mode name column`.

![image](https://user-images.githubusercontent.com/549126/55278866-cc329e00-534c-11e9-9caf-27d7a90c7afa.png)

2. **Limit buffer candidate to only 10 or less,** 
    the reason i expect like this is when i open 'helm-mini',
    helm pop window all filled with buffer candidate,  i even
    could not see any buffer i just close one minute ago.
    All i have to to do is, 'C-n C-n ....', until `Recentf` is show.
    Or, is there any way like helm show `recentf` before helm-buffer?
    (I know i can input something to narrow result, but,  in many case,
    i even don't remember any filter keyword ......)

Thanks.

**Comment by thierryvolpiatto** [comment]
Show all buffers but lisp buffers:
![Capture d’écran_2019-03-30_20-09-37](https://user-images.githubusercontent.com/1533939/55280594-03db1f00-5328-11e9-8a80-82ed1009a2c7.png)

**Comment by thierryvolpiatto** [comment]
You don't need to limit candidates to show next source, just use C-o to switch to next source.
Also what you can do is going backward (C-p or arrow up) if you have enabled `helm-move-to-line-cycle-in-source`.

HTH.

**Comment by zw963** [comment]
> Show all buffers but lisp buffers:

Sorry, not working for me.

I am used to using `dired + helm` to start work, for my situation, often follow 
case is happen. (many Dired buffer), i don't expect see any Dired buffer
in `helm-mini`, but no take effect.

![image](https://user-images.githubusercontent.com/549126/55284223-8f929100-53a4-11e9-8ffc-c067cb39568c.png)

**Comment by zw963** [comment]
> You don't need to limit candidates to show next source, just use C-o to switch to next source.

It working, thanks.

> Also what you can do is going backward (C-p or arrow up) if you have enabled helm-move-to-line-cycle-in-source.

This not working, when enable, it only cycle in current source, when `C-p`, will switch to last item of helm-recentf. 

BTW: I change helm-mini source order to recentf first.

```sh
(setq helm-mini-default-sources
      '(
       helm-source-recentf
       helm-source-buffers-list
       helm-source-buffer-not-found))
```

**Comment by thierryvolpiatto** [comment]
Billy.Zheng <notifications@github.com> writes:

>     You don't need to limit candidates to show next source, just use C-o to switch to next source.
>    
> It working, thanks.
>
>     Also what you can do is going backward (C-p or arrow up) if you have enabled helm-move-to-line-cycle-in-source.
>    
> This not working, when enable, it only cycle in current source, when C-p, will switch to last item of helm-recentf.

Yes, it is what is does cycling in current source, but when you are at
the bottom of your current source, you can see the first items of next
source.

> BTW: I change helm-mini source order to recentf first.
>
> (setq helm-mini-default-sources
>       '(
>        helm-source-recentf
>        helm-source-buffers-list
>        helm-source-buffer-not-found))
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.*


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Billy.Zheng <notifications@github.com> writes:

>     Show all buffers but lisp buffers:
>    
> Sorry, not working for me.
>
> I am used to using dired + helm to start work, for my situation, often follow
> case is happen. (many Dired buffer), i don't expect see any Dired buffer
> in helm-mini, but no take effect.
>
> image   

Of course you are upcasing dired, use "*!dired" instead, you are
matching a major-mode called dired-mode.

> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.*


-- 
Thierry

**Comment by zw963** [comment]
> Of course you are upcasing dired, use "*!dired" instead, you are matching a major-mode called dired-mode.

It worked!, thanks!

is there any way to make `*!dired` can added automatically?

**Comment by zw963** [comment]
Still have one question ....

is there any way to make *!dired can added automatically? @thierryvolpiatto 

Thanks

**Comment by thierryvolpiatto** [comment]
Billy.Zheng <notifications@github.com> writes:

> Still have one question ....
>
> is there any way to make *!dired can added automatically? @thierryvolpiatto

No, you have to enter such pattern manually.

-- 
Thierry

**Comment by zw963** [comment]
> Still have one question ....
> 
> is there any way to make *!dired can added automatically? @thierryvolpiatto
> 
> Thanks

Finally, i resolve this issue use a new way, only keep open one dired buffer. please see following answer.
https://emacs.stackexchange.com/a/1041/11748
