### ISSUE TITLE
Helm browse urls?

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#2149]
Is it possible to have sort of a Helm-occur but only for all URLs in the buffer?
That'd be useful in Org documents, email thread, etc.

Actions would be browse-url and eww for instance.
Thoughts?

**Comment by thierryvolpiatto** [comment]
You can go to any url with helm-occur and hit C-x C-f on url.
 
Pierre Neidhardt <notifications@github.com> writes:

> Is it possible to have sort of a Helm-occur but only for all URLs in the buffer?
> That'd be useful in Org documents, email thread, etc.
>
> Actions would be browse-url and eww for instance.
> Thoughts?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.*


-- 
Thierry

**Comment by Ambrevar** [comment]
Of course, but I'm talking about something that requires less key
presses.

For now, we must do:

- M-x helm-occur
- Insert "https?://"
- Select
- C-x C-f

I'd like:

- M-x helm-occur-urls
- Select
- RET

Makes sense?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Of course, but I'm talking about something that requires less key
> presses.
>
> For now, we must do:
>
> - M-x helm-occur
> - Insert "https?://"
> - Select
> - C-x C-f
>
> I'd like:
>
> - M-x helm-occur-urls
> - Select
> - RET
>
> Makes sense?

We would have to write another source just to save typing http in
minibuffer, what about adding an action transformer to helm-occur, try this:

    (defun helm-occur-extract-urls-from-line (line)
      (with-temp-buffer
        (save-excursion
          (insert "\n" line))
        (cl-loop while (re-search-forward "\\(https?\\|ftp\\)://[^ >]*" nil t)
          collect (match-string 0))))

    (defun helm-occur-browse-urls (_candidate)
      (let ((urls (helm-occur-extract-urls-from-line (helm-get-selection nil t))))
        (browse-url (helm-comp-read "Url: " urls :exec-when-only-one t))))

    (defun helm-occur-action-transformer (actions _candidate)
      (cond ((string-match "\\(https?\\|ftp\\)://[^ >]*" (helm-get-selection nil t))
             (helm-append-at-nth actions '(("Browse urls in line" . helm-occur-browse-urls)) 1))
            (t actions)))

    (defmethod helm-setup-user-source ((source helm-moccur-class))
      (setf (slot-value source 'action-transformer) 'helm-occur-action-transformer))

Eval the code above, then run helm-occur, type http in minibuffer and
type f2 on a line containing one or more url.

-- 
Thierry

**Comment by Ambrevar** [comment]
Is helm-moccur-class recent?  Doesn't seem to be defined on Helm 3.1.

That said, a URL is not always as simple as writing "http" or "ftp".
Those two examples alone show that it's not very practical to list all
"http" or "ftp", it's quite a lot of characters to type.

Coincidentally, this was recently pushed to Notmuch:

```elisp
(defmacro notmuch-show--with-currently-shown-message (&rest body)
  "Evaluate BODY with display restricted to the currently shown
message."
  `(save-excursion
     (save-restriction
      (let ((extent (notmuch-show-message-extent)))
	(narrow-to-region (car extent) (cdr extent))
	,@body))))

(defun notmuch-show--gather-urls ()
  "Gather any URLs in the current message."
  (notmuch-show--with-currently-shown-message
   (let (urls)
     (goto-char (point-min))
     (while (re-search-forward goto-address-url-regexp (point-max) t)
       (push (match-string-no-properties 0) urls))
     (reverse urls))))

(defun notmuch-show-browse-urls ()
  "Offer to browse any URLs in the current message."
  (interactive)
  (let ((urls (notmuch-show--gather-urls)))
    (if urls
	(browse-url (completing-read "Browse URL: " (cdr urls) nil nil (car urls)))
      (message "No URLs found."))))
```

Notice they use `goto-address-url-regexp`.

I understand that a helm-occur that is specialized for URLs might be
shortsighted.  What we really want here, I think, is a class slot that
acts as an input pre-filter.

Then the solution would be as simple as
the snippet you provided except that `helm-occur-extract-urls-from-line'
could be replaced to pre-filter the URLs.

Thoughts?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Is helm-moccur-class recent?

Yes, helm-occur have been rewrited.

> Doesn't seem to be defined on Helm 3.1.
>
> That said, a URL is not always as simple as writing "http" or "ftp".
> Those two examples alone show that it's not very practical to list all
> "http" or "ftp", it's quite a lot of characters to type.

This is just and example I wrote in few minutes just to show how it
would behave as an action in helm-occur.

> Coincidentally, this was recently pushed to Notmuch:
> Notice they use `goto-address-url-regexp`.

Yes, maybe this regexp can be reused, I don't know what it match
exactly, I have to look if it could be compatible.

> I understand that a helm-occur that is specialized for URLs might be
> shortsighted. What we really want here, I think, is a class slot that
> acts as an input pre-filter.

Don't know what you mean by "input pre-filter".

> Then the solution would be as simple as
> the snippet you provided except that `helm-occur-extract-urls-from-line'
> could be replaced to pre-filter the URLs.

Don't understand this sorry.

> Thoughts?

I still think that a specialized helm-occur for urls is a lot of effort
for finally avoid typing few characters at prompt.
I think it is better to type a regexp matching a url and then execute
the specialized action on this url. Note that you can have the url at
point with M-n without having to type it completely (you have also C-w
to yank word at point).

> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.*


-- 
Thierry

**Comment by Ambrevar** [comment]
Sorry for the confusing suggestion, allow me to clarify:

I suggest we add a class slot that can be used to filter the possible
candidates _on invokation_.  For helm-occur, this filter would be empty.
If the user defines `helm-my-occur` with "\<https?://" in the filter
slot, then the custom occur session will only display the corresponding
URIs, on top of which the user can keep searching like a regular helm-occur.

This "pre-filter" slot would make it possible to extent any Helm class
in a new way: it allows to "pre-narrow down the results."

The pre-filter could be a predicate or, for convenience, a regexp.

Makes sense?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Sorry for the confusing suggestion, allow me to clarify:
>
> I suggest we add a class slot that can be used to filter the possible
> candidates _on invokation_.

No need to have a class slot here, what you only need is a helm
invocation with :input https?, so a new command just for urls with the
corresponding action.

> For helm-occur, this filter would be empty.  If the user defines
> `helm-my-occur` with "\<https?://" in the filter slot, then the custom
> occur session will only display the corresponding URIs, on top of
> which the user can keep searching like a regular helm-occur.
>
> This "pre-filter" slot would make it possible to extent any Helm class
> in a new way: it allows to "pre-narrow down the results."
>
> The pre-filter could be a predicate or, for convenience, a regexp.
>
> Makes sense?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.*


-- 
Thierry

**Comment by Ambrevar** [comment]
I think you are right, setting `:input` is good enough.  Thanks!
