### ISSUE TITLE
How to disable follow in helm-occur?

### ISSUE THREAD

**Issue by c02y** [emacs-helm/helm#2152]
## Expected behavior and Actual behavior

Since `helm-occur` is rewritten, when I scroll my point my helm-occur buffer, the point in my buffer gets updated(the default behavior like helm-swoop), the `C-j` command is not working any more, since it is the default behavior now.

I'm not asking to delete the `C-j`, since when I use emacs in terminal, and when I use helm-occur to scroll my point, my screen got flashes somehow, and it has bad performance in big files, since most of time I just want to jump to line from a result in helm-occur instead of viewing all the context when scrolling.

How to make the default behavior disabled, and when I want to view the context of the point, I can just use `C-j` to `Go to Line (Keep session)` , which is the old behavior of `helm-occur`

 
## Describe versions of Helm, Emacs, operating system, etc.
helm-20190412.1025
GNU Emacs 26.1 (build 1, x86_64-suse-linux-gnu, GTK+ Version 3.24.4)

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):
yes

![cj](https://user-images.githubusercontent.com/2135996/56039766-9b4c6300-5d67-11e9-93d9-f9e3dd936d43.png)

**Comment by thierryvolpiatto** [comment]
Add this to init file:

``` elisp
(defmethod helm-setup-user-source ((source helm-moccur-class))
  (setf (slot-value source 'follow) -1))
```
See https://github.com/emacs-helm/helm/wiki/FAQ#why-is-a-customizable-helm-source-nil

**Comment by c02y** [comment]
Thanks
