### ISSUE TITLE
Shorter filenames should be sorted before/above longer filenames

### ISSUE THREAD

**Issue by Davidj361** [emacs-helm/helm#2153]
## Expected behavior
C-x C-f
Search: ".em"
`.emacs` should be first since that's the shortest filename compared to `.emacs-custom.el`
Reason is because you can easily wildcard and add part of the longer filename to filter for it such as: 
".em cu"

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
C-x C-f
Search: ".em"
`.emacs-custom.el` is before/above `.emacs`
This is happening possibly due to regex greediness.

## Steps to reproduce (recipe)
Have a `.emacs` and `.emacs-custom.el` file in the same directory, and C-x C-f into that directory then search: ".em"

## Backtraces if any (`M-x toggle-debug-on-error`)
Not needed?

## Describe versions of Helm, Emacs, operating system, etc.
Emacs 26.2-1
Helm 20190421.1727

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):
Yes

## Extra
Check these out for reference. The issue is likely regex greediness related.
https://vi.stackexchange.com/questions/308/regex-that-prefers-shorter-matches-within-a-match-this-is-more-involved-than-n

https://github.com/emacs-helm/helm/issues/236

Code dealing with greediness maybe?
https://github.com/emacs-jp/helm-c-yasnippet/blob/master/helm-c-yasnippet.el

**Comment by thierryvolpiatto** [comment]
Should work now.

Thanks.
