### ISSUE TITLE
creating new files with helm-find-files with existing path at point

### ISSUE THREAD

**Issue by tpapp** [emacs-helm/helm#2154]
## Expected behavior

This may not be a bug, but a feature request, or perhaps I am using helm wrong. I [asked on stackexchange](https://emacs.stackexchange.com/questions/49011/create-new-file-helm-find-file-with-ffap) and then decided to open an issue.

When `helm-find-files` is used while the point is on a filename, it is offered as a choice *if the file exists*. However, if the path does not exist, I have to retype everything to *create* a new file.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

When `helm-find-files` is invoked with the point over a path that does not exist, the directory is offered in the `*helm-find-files*` buffer.

## Steps to reproduce (recipe)

1. start with `emacs-helm.sh`,
2. in `*scratch*`, write eg `/tmp/x.txt` (assuming there is no such file),
3. <kbd>C-x C-f</kbd>
4. note `/tmp/` in the minibuffer. the issue is having to retype `x.txt`.

## Backtraces if any (`M-x toggle-debug-on-error`)

not applicable

## Describe versions of Helm, Emacs, operating system, etc.

Emacs 26.2, helm-20190421.1727 (MELPA), Ubuntu 19.04 disco.

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):

Yes.

**Comment by thierryvolpiatto** [comment]
You can now configure `helm-ff-allow-non-existing-file-at-point`.
Thanks.

**Comment by tpapp** [comment]
This fixes the issue for me, thanks.
