### ISSUE TITLE
wish: helm-ucs should use persistent cache file

### ISSUE THREAD

**Issue by GregorZattler** [emacs-helm/helm#2156]
## Expected behavior
Since collecting the characters is really slow on first use I would expect this collection to be saved to a cache file in order to speed up helm-ucs in future emacs sessions.
## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
helm-ucs is slow every first usage after emacs restart.
## Steps to reproduce (recipe)
1. start emacs
2. do helm-ucs (slow)
3. do helm-ucs again (fast)
4. exit emacs
5. start emacs again
6. do helm-ucs (slow again)
## Describe versions of Helm, Emacs, operating system, etc.
helm from elpa:
elpa-27.0/helm-20190424.1443

on

GNU Emacs 27.0.50 (build 5, x86_64-pc-linux-gnu, GTK+ Version 3.22.11) of 2019-04-28
## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):
no

Thanks for helm, Gregor

**Comment by thierryvolpiatto** [comment]
GregorZattler <notifications@github.com> writes:

> Expected behavior
>
> Since collecting the characters is really slow on first use I would
> expect this collection to be saved to a cache file in order to speed
> up helm-ucs in future emacs sessions.

Helm have a cache for this, it is `helm-ucs--names`, you can save it for
future emacs sessions like any other variables with psession or desktop
(slower).  For psession it is:

    (add-to-list 'psession-object-to-save-alist '(helm-ucs--names . "helm-ucs--names.el"))

Of course if you add new fonts to your system, you may want to refresh
the cache by using a prefix arg, the new cache will be saved by psession
when quitting emacs.
Also note that you will loose fontifications (colors).

--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by GregorZattler** [comment]
Hi Thierry,
* Thierry Volpiatto <notifications@github.com> [2019-04-29; 22:56]:
> GregorZattler <notifications@github.com> writes:

>> Since collecting the characters is really slow on first use I would
>> expect this collection to be saved to a cache file in order to speed
>> up helm-ucs in future emacs sessions.
>
> Helm have a cache for this, it is `helm-ucs--names`, you can save it for
> future emacs sessions like any other variables with psession or desktop
> (slower).  For psession it is:
>
>     (add-to-list 'psession-object-to-save-alist '(helm-ucs--names . "helm-ucs--names.el"))

Thanks, I will try this.  I don't want a full session management, though.

> Of course if you add new fonts to your system, you may want to refresh
> the cache by using a prefix arg, the new cache will be saved by psession
> when quitting emacs.

Sure.

> Also note that you will loose fontifications (colors).

Thanks again.

Ciao; Gregor
--
 -... --- .-. . -.. ..--.. ...-.-
