### ISSUE TITLE
helm-pass empty candidates list

### ISSUE THREAD

**Issue by avkoval** [emacs-helm/helm#2157]
## Expected behavior

M-x helm-pass to list of all candiates

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

helm-pass - Empty list
running (password-store-list) in *scratch* buffer with C-e returns list if candidates
so it seems its something in the helm itself

C-c C-u does not seems to affect anything
To me it looks like empty value is cached forever or smth else like this

## Steps to reproduce (recipe)

No specific way. The bug is unstable.

## Describe versions of Helm, Emacs, operating system, etc.

Latest emacs GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.7) of 2019-03-25
Latest helm helm-20190424.1443

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):

no because I can't stable reproduce it even with emacs, and when emacs is started fresh, there are no issue

## IMPORTANT NOTE

Helm provides a script named `emacs-helm.sh` which runs Helm in a neutral
environment: no other packages and only minimal settings.

When possible, use it to reproduce your Helm issue to ensure no other package is
interfering.

To run it, simply switch to the directory where Helm is installed and call `./emacs-helm.sh`.
If necessary you can specify emacs executable path on command line with "-P" option.

Thanks.

**Comment by thierryvolpiatto** [comment]
avkoval <notifications@github.com> writes:

> Expected behavior
>
> M-x helm-pass to list of all candiates

Sorry but I don't know what is helm-pass, it is not part of helm.
You should report to helm-pass or the package it belong to.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by avkoval** [comment]
OK but can you give some advice ? Because helm-pass is a package which does mostly this:
```
(defvar helm-pass-source-pass
  (helm-build-sync-source "Password File"
    :candidates #'password-store-list
    :action helm-pass-actions))
```

and it rely on external packages anyway (password-store), so I mean that helm-pass is a kind of proxy here, relaying on both helm and password-store packages.

How in general I can debug the helm? I mean, I see in this case that candidates list renders well, but then the final list is empty. I've experienced that kind of problems with using clipboard managers, but now with copyq it seems to be neutral, so problem is somewhere else

But you may be right, since its only happens with helm-pass I can try to contact author, if you don't have any other suggestions I will close this issue

**Comment by thierryvolpiatto** [comment]
avkoval <notifications@github.com> writes:

> OK but can you give some advice ? Because helm-pass is a package which does mostly this:
>
> (defvar helm-pass-source-pass
>   (helm-build-sync-source "Password File"
>     :candidates #'password-store-list
>     :action helm-pass-actions))

If you have an empty buffer with such a source, the culprit is
`password-store-list`, the :candidates function, if this function
produces something useful for helm, helm will display it.
What is this function producing if it works?
A list of strings?
An alist?
Else?

> and it rely on external packages anyway (password-store), so I mean that helm-pass is a kind of proxy here, relaying on both helm and password-store
> packages.
>
> How in general I can debug the helm?

Try C-h m from any helm session and see "Debugging helm".

> I mean, I see in this case that candidates list renders well,

You mean the :candidates function?

> I've experienced that kind of problems with using clipboard managers,
> but now with copyq it seems to be neutral, so problem is somewhere
> else

Sorry but you lost me here with "Clipboard managers" (which clipboard
managers?) and copyq (what is copyq?)

> But you may be right, since its only happens with helm-pass I can try
> to contact author,

Yes, @ambrevar will explain better than me what's going wrong here as I
am not using pass.

> if you don't have any other suggestions I will close this issue

Please do.

--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by Ambrevar** [comment]
Answered in the dedicated project.  This can be closed.

**Comment by thierryvolpiatto** [comment]
Thanks closing.
