### ISSUE TITLE
How to return to previous helm function?

### ISSUE THREAD

**Issue by 717g301github** [emacs-helm/helm#2161]
## Expected behavior

I wish to see example on how to return to previous helm function. Let us say I am using helm-show-kill-ring and I do for example command M-D to delete the item list.

I am expecting to return back to helm-show-kill-ring list.

This I am giving only as example, I wish to make my own functions where I can return back to previous helm function after doing some of actions.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

helm function exists, back to buffer basically, instead that I return back to previous helm list.

**Comment by thierryvolpiatto** [comment]
717g301github <notifications@github.com> writes:

> Expected behavior
>
> I wish to see example on how to return to previous helm function. Let
> us say I am using helm-show-kill-ring and I do for example command M-D
> to delete the item list.
>
> I am expecting to return back to helm-show-kill-ring list.

Most helm sessions are resumable with M-x helm-resume, this one is not,
however if you don't want to exit session after deleting an item, you
can use its persistent delete action (`C-c d`) instead of `M-D`.
Oh I see I forget to document this in helm kill-ring documentation,
doing it right now.

>
> This I am giving only as example, I wish to make my own functions
> where I can return back to previous helm function after doing some of
> actions.

M-x helm-resume

Note that the display of previous session may be wrong if some
candidates have been deleted (or added) by previous action or by other
external process, in that case you may have to hit `C-c C-u` to refresh
the display.

Always use `C-h m` while in an helm session to read documentation relative
to the command you are using.

> Actual behavior (from emacs-helm.sh if possible, see note at the bottom)
>
> helm function exists, back to buffer basically, instead that I return back to previous helm list.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.*


--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by 717g301github** [comment]
I am trying to make a new command. Here is one example below. If helm command is expanded from wrs/items-list then such item is edited within function rcd/edit-entries -- and what I am trying to understand is how to implement that I can go back to the previous choice, for example to repeat wrs/top command again from sub-helm with rcd/edit-entries. 

Function below is just hypothetical, I cannot helm-resume from function, that is just a concept.

```
(defun wrs/top (area)
  (interactive "nArea ID: ")
  (let* ((sql (format "SELECT pages_id, pages_title, 'page', pages_priority AS priority, pages_notinmenu FROM pages WHERE pages_area = %s AND pages_categories IS NULL UNION ALL SELECT categories_id, categories_name, 'category', categories_priority, categories_notinmenu AS priority FROM categories WHERE categories_parent IS NULL and categories_area = %s ORDER BY priority DESC" area area))
	 (choice (wrs/items-list (concat "WRS Top Items for Area " (number-to-string area)) sql))
	 (type (cadr choice))
	 (id (car choice)))
    (cond ((string= type "page") (rcd/edit-entries "pages" id))
	  ((string= type "category") (rcd/edit-entries "categories" id))))
  (helm-resume))
```

**Comment by thierryvolpiatto** [comment]
717g301github <notifications@github.com> writes:

> I am trying to make a new command. Here is one example below. If helm
> command is expanded from wrs/items-list then such item is edited
> within function rcd/edit-entries -- and what I am trying to understand
> is how to implement that I can go back to the previous choice, for
> example to repeat wrs/top command again from sub-helm with
> rcd/edit-entries.

I am not sure what you want to do exactly, but AFAIU you can't use
helm-resume to achieve what you want to do.
Also I don't know what are the rcd/* functions and wrs/* also, so I
can't tell much.

--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by 717g301github** [comment]
Let me try to explain better. I am using helm to make various choices .It is like entering one category deeper by choice. How do I make it to enter one category higher? One category back?

If helm selection A gives choice to enter new helm-selections C, D, E, once I am inside of D, how do I come back to A?

I know that I can come back to A with helm-resume. But is there way with the key or Function keys maybe? How do you recommend?

**Comment by thierryvolpiatto** [comment]
717g301github <notifications@github.com> writes:

> Let me try to explain better. I am using helm to make various choices .It is like entering one category deeper by choice. How do I make it to enter one category higher? One category back?
>
> If helm selection A gives choice to enter new helm-selections C, D, E, once I am inside of D, how do I come back to A?
>
> I know that I can come back to A with helm-resume. But is there way with the key or Function keys maybe? How do you recommend?

For example:

1) M-x helm-find-files => and navigate somewhere
2) M-g a
3) Enter some pattern to have some rg/ag results
4) C-x b
5) you are now back in 1)

Use C-x C-b instead in 4) to choose your helm session.

See the helm documentation for more infos on this, the node is "Resume
previous session from current Helm session".

HTH.
 
-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by 717g301github** [comment]
Thank you, those are reference that I need. I am grateful for helm, excellent piece of software. I understand your difficulties with development. Be sure that I will be paying my donation to you next month. I will let you know it was from this identity.

**Comment by thierryvolpiatto** [comment]
717g301github <notifications@github.com> writes:

> Thank you, those are reference that I need.

Glad it helped :-)

> I am grateful for helm, excellent piece of software. I understand your
> difficulties with development. Be sure that I will be paying my
> donation to you next month. I will let you know it was from this
> identity.

Thanks.

--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
