### ISSUE TITLE
helm-grep: support for google/codesearch

### ISSUE THREAD

**Issue by myk3v** [emacs-helm/helm#2162]
## Expected behavior

Support for [google/codesearch](https://github.com/google/codesearch) as backend for helm-grep.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

Currently, helm-grep supports a range of common search utilities
- ripgrep
- ag
- GNU grep
- Zgrep
- Pdfgrep
- git grep

Because codesearch is a fairly common utility with integration in some editors and IDEs, it would be great if it also would make the list of supported backends.

**Comment by thierryvolpiatto** [comment]
As long as the backend have switches to provide a line like "filename:linum:line contents" it is easy to write a command with a new backend, but don't expect me to write one actually specially with google code.
Thanks.
