### ISSUE TITLE
Buffers created by helm persistent action replace the current buffer instead of other candidates

### ISSUE THREAD

**Issue by achinhorn** [emacs-helm/helm#2169]
## Expected behavior
The original buffer helm is called from should always remain visible, or at worst be preferred last from available windows.

Use-case:
Leverage persistent actions & helm session management to ad-hoc/quickly lookup various documentation that relates to the buffer I am using. That help is best contextualized via having the buffer I'm working on actually remain visible when possible.
## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
Run `~/path/to/emacs-helm.sh`
`F11` `C-x 3` `C-x 3` `C-x +` (standard 3 column, single frame config)
In any window, `C-x b` `messages` `RET` or some other buffer.
Ensure `*Messages*` window focused
`M-x` `C-j` on any command
Observe that you can no longer see the buffer you began in when there is a third column that is being completely unused

Why the buffer switch: you won't notice this bug if there are duplicate windows of the buffer you are calling from.
## Backtraces if any (`M-x toggle-debug-on-error`)
helm-debug-log shows current-buffer is called, which doesn't really make sense to me that it would use this buffer vs some other candidate window (eg like choosing 'unrecent or 'other window)
## Describe versions of Helm, Emacs, operating system, etc.
Latest 20190703.1516 from MELPA. Emacs 26.2, Fedora 30
## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):
Yes.

**Comment by achinhorn** [comment]
One thing I was wanting to do was leverage helm using an entire window by default and fit a max 3 column, max 2 (maybe 3) row window layout, potentially finding a way to sandbox helm to always use the same vertical space (eg spawn persistent action window below helm-buffer's window). Is this an outer space task I should give up now on? Is there a supplemental package or elisp area I am missing?

Ultimately I'm just looking for the best usage model, better alternatives are appreciated...

**Comment by thierryvolpiatto** [comment]
Not sure to understand exactly what you want, but maybe using `helm-split-window-inside-p` is what you want.
