### ISSUE TITLE
-n, --namespace does not work in v3.0.0-alpha.1

### ISSUE THREAD

**Issue by stevebail** [emacs-helm/helm#2171]
## Expected behavior
Helm v3.0.0-alpha.1 supports namespaces for releases.
A new -n, --namespace flag has been added to commands (e.g. helm install) allowing the user to create the namespace and allocate the release to it.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
A new -n, --namespace flag has not impact on the request.
The user must first create the namespace and change to current active context in order to install the release in the appropriate namespace

## Steps to reproduce (recipe)
$ kubens
alpha <- active namespace
default
kube-node-lease
kube-public
kube-system
$ helm list
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART
my-chart-1      alpha           1               2019-07-08 14:29:08.479577508 +0000 UTC deployed        my-chart-0.1.0
$ helm list --all-namespaces
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART
my-chart-1      alpha           1               2019-07-08 14:29:08.479577508 +0000 UTC deployed        my-chart-0.1.0
my-chart-1      default         1               2019-07-08 14:22:52.204105662 +0000 UTC deployed        my-chart-0.1.0
$ helm install my-chart-1 my-chart-0.1.0.tgz -n beta
Error: cannot re-use a name that is still in use

## Describe versions of Helm, Emacs, operating system, etc.
v3.0.0-alpha-1

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):
no

## IMPORTANT NOTE

Helm provides a script named `emacs-helm.sh` which runs Helm in a neutral
environment: no other packages and only minimal settings.

When possible, use it to reproduce your Helm issue to ensure no other package is
interfering.

To run it, simply switch to the directory where Helm is installed and call `./emacs-helm.sh`.
If necessary you can specify emacs executable path on command line with "-P" option.

Thanks.

**Comment by thierryvolpiatto** [comment]
stevebail <notifications@github.com> writes:

> Expected behavior
>
> Helm v3.0.0-alpha.1 supports namespaces for releases.
> A new -n, --namespace flag has been added to commands (e.g. helm install) allowing the user to create the namespace and allocate the release to it.
>
> Actual behavior (from emacs-helm.sh if possible, see note at the bottom)
>
> A new -n, --namespace flag has not impact on the request.
> The user must first create the namespace and change to current active context in order to install the release in the appropriate namespace

I have no idea what you are speaking about, are you sure you are
speaking of Helm the Emacs extension?

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
