### ISSUE TITLE
Strange behavior of helm-buffers-truncate-lines

### ISSUE THREAD

**Issue by azzamsa** [emacs-helm/helm#2172]
## Expected behavior

helm-mini will truncate long lines automatically when the value of `helm-buffers-truncate-lines` is `t`

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

helm-mini didn't truncate the long lines automatically, I need to type `C-c >` manually every time.

## Steps to reproduce (recipe)

- evaluate `(setq helm-buffers-truncate-lines t)`
- visit files with the long path (to make helm-mini truncate the lines)
- call helm-mini

## Describe versions of Helm, Emacs, operating system, etc.

- OS: Debian GNU/Linux 9.9 (stretch) x86_64
- Kernel: 4.9.0-9-amd64
- WM: i3              
- GNU Emacs 26.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.11) of 2018-05-29

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):

yes

I use both my [emacs helm config](https://gist.github.com/azzamsa/29186826abaf80d001581da471f6eed7#file-aza-helm-el-L35) and emacs-helm.sh, both of them have the same result.

Thanks.

**Comment by thierryvolpiatto** [comment]
Still can't reproduce with emacs-helm.sh.
![Capture du 2019-07-14 17-15-25](https://user-images.githubusercontent.com/1533939/61185556-1a994d80-a65b-11e9-8dc2-7dd0aa429f97.png)
![Capture du 2019-07-14 17-15-52](https://user-images.githubusercontent.com/1533939/61185563-1ff69800-a65b-11e9-90f7-869b2263b348.png)

**Comment by thierryvolpiatto** [comment]
As you can see with default setting line is truncated after hitting C-], the first screenshot show the display with additional infos where the buffer name is truncated as well.
My guess is you have some global setting of truncate-lines or helm-truncate-lines set somewhere.
Did I miss something to reproduce?

**Comment by azzamsa** [comment]
What I want is `C-c >` behavior which is [helm-toggle-truncate-line](https://github.com/emacs-helm/helm/blob/a1791980f9ddca1989c65a67e6997bdde481dc27/helm.el#L236) and not `C-]` ([helm-ff-run-toggle-basename](https://github.com/emacs-helm/helm/blob/f0f174138f6f3198a6b970fd29e7caa94236e3bc/helm-types.el#L43)) to toggle the list to the basename only.


the screenshot you've shown is the right behavior of `C-] (helm-ff-run-toggle-basename)`, cause we can see the info detail in the middle disappeared and all the buffer name toggled into their appropriate base name. What I want is `C-c > (helm-toggle-truncate-line)` which will *truncate* the line, not toggled them into base name.

The behavior is shown below:

1. I've evaluated `(setq helm-buffers-truncate-lines t)`, but look at the green mark, those lines is not truncated automatically after I called helm-mini

![helm-mini-not](https://user-images.githubusercontent.com/17734314/61251587-18331280-a785-11e9-8e9a-9ca7eb85264c.png)

2. I need to type `C-c >` manually (every time) to turn them into this:

![helm-mini-yes](https://user-images.githubusercontent.com/17734314/61251616-31d45a00-a785-11e9-9f38-d09865007fad.png)

---

Those are the behavior of `C-c >`, but this is the behavior of `C-]` which is not what I want:

![helm-mini-drop](https://user-images.githubusercontent.com/17734314/61251661-529caf80-a785-11e9-9739-418894f6774c.png)

**Comment by thierryvolpiatto** [comment]
You are misunderstanding what `truncate-lines` is, in screenshot 1), lines are truncated, but in 2) they are not.  So the behavior of `helm-buffers-truncate-lines` is indeed correct.
See docstring of `truncate-lines` for more infos.

**Comment by azzamsa** [comment]
Oh my bad. It's reversed in my mind.

Now I use `(setq helm-buffers-truncate-lines nil)`. This is what I want since a few months ago.

Thank you for answering patiently. Thank you for your effort that you put into Helm.
