### ISSUE TITLE
helm-find-files cannot go to next folder by using arrow left

### ISSUE THREAD

**Issue by ccqpein** [emacs-helm/helm#2175]
## Expected behavior
After call helm-fild-files function, when mini-buffer cusor move to folder, arrow left usually go into that folder. 
## Actual behavior 
Give me warning `(End of buffer)`

**Comment by thierryvolpiatto** [comment]
ccQpein <notifications@github.com> writes:

> Expected behavior
>
> After call helm-fild-files function, when mini-buffer cusor move to folder, arrow left usually go into that folder.

Not anymore, the default is now left-char and right-char as in Emacs
vanilla.
You can retrieve the previous behavior with:

(define-key helm-map (kbd "<left>") 'helm-previous-source)
(define-key helm-map (kbd "<right>") 'helm-next-source)

And for helm-find-files:

(customize-set-variable 'helm-ff-lynx-style-map t)

For helm-imenu

(customize-set-variable 'helm-imenu-lynx-style-map t)

For semantic

(customize-set-variable 'helm-semantic-lynx-style-map t)

For helm-occur

(customize-set-variable 'helm-occur-use-ioccur-style-keys t)


Hope that help.

Sorry for inconveniency.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by ccqpein** [comment]
Thanks @thierryvolpiatto , no need to sorry. I add `(customize-set-variable 'helm-ff-lynx-style-map t)` and `helm-find-file` behavior back to old time.

**Comment by Deanseo** [comment]
With all due respect, may I know what the motivation was to have this breaking change? 
I mean I was happy with the *previous behavior* with no problem.

**Comment by thierryvolpiatto** [comment]
Because many people asked to have more default bindings behaving like in Emacs.
I was happy too with previous behavior, you can retrieve it as described above, you have also an entry in Helm documentation and also an entry in FAQ in helm wiki.

**Comment by root42** [comment]
I find the new behavior very irritating. Is there an equivalent key to do the same thing in the new version? I tried C-j but that fails in shell completion for example.

**Comment by thierryvolpiatto** [comment]
root42 <notifications@github.com> writes:

> I find the new behavior very irritating. Is there an equivalent key to
> do the same thing in the new version? I tried C-j but that fails in
> shell completion for example.

If you use C-h m, it is documented, it is here as well:

https://github.com/emacs-helm/helm/wiki/FAQ#arrow-keys-behavior-have-changed

> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.*


--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by root42** [comment]
Well, I read the documentation, but still: I added all settings to get the old behavior back, but navigation in shell completion still does not work as it did before. And C-j does not work either. Shall I file a bug report for that?

**Comment by thierryvolpiatto** [comment]
root42 <notifications@github.com> writes:

> Well, I read the documentation, but still: I added all settings to get
> the old behavior back, but navigation in shell completion still does
> not work as it did before.  And C-j does not work either. Shall I file
> a bug report for that?

No there is nothing to report here, if you follow the instructions of
wiki you have the same behavior as before, still don't know what is
wrong in shell completion, please explain exactly what is the problem, I
guess it is trivial to fix.

Fo C-j in helm-find-files, it working fine from emacs-helm.sh, same for
C-l.

--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
