### ISSUE TITLE
Sole action: identity for helm-M-x commands, can you confirm?

### ISSUE THREAD

**Issue by nerton** [emacs-helm/helm#2176]
## Expected behavior

more actions for commands than only identity

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

only one action, identity for commands

## Steps to reproduce (recipe)

start helm-M-x, press tab  on a command

## Backtraces if any (`M-x toggle-debug-on-error`)

no error

## Describe versions of Helm, Emacs, operating system, etc.

emacs 26.1, windows

helm:

(add-to-list 'load-path "c:/me/emacs/.emacs.d/elpa/helm-20190717.550" )
(add-to-list 'load-path "c:/me/emacs/.emacs.d/elpa/helm-core-20190602.626/" )
(add-to-list 'load-path "c:/me/emacs/.emacs.d/elpa/async-20190503.656" )

(require 'helm-config)

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):

No, because it does not work on windows, but I ran emacs with -Q and used the latest packages installed by package.el:

(add-to-list 'load-path "c:/me/emacs/.emacs.d/elpa/helm-20190717.550" )
(add-to-list 'load-path "c:/me/emacs/.emacs.d/elpa/helm-core-20190602.626/" )
(add-to-list 'load-path "c:/me/emacs/.emacs.d/elpa/async-20190503.656" )

(require 'helm-config)

## IMPORTANT NOTE

Helm provides a script named `emacs-helm.sh` which runs Helm in a neutral
environment: no other packages and only minimal settings.

When possible, use it to reproduce your Helm issue to ensure no other package is
interfering.

To run it, simply switch to the directory where Helm is installed and call `./emacs-helm.sh`.
If necessary you can specify emacs executable path on command line with "-P" option.

Thanks.

**Comment by thierryvolpiatto** [comment]
nerton <notifications@github.com> writes:

> Expected behavior
>
> more actions for commands than only identity

Nope, no more commands for this, the only command we have to run is
`command-execute`, and `describe-command` as persistent-action.

> Actual behavior (from emacs-helm.sh if possible, see note at the bottom)
>
> only one action, identity for commands

Yes and I confirm.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by nerton** [comment]
Ah, I thought it was a bug, because I expected more actions there. E.g. I often find commands with M-x and then want to copy the command name in my notes. Or lookup the elisp source code of a command, so I'd like a jump to source action. These could be useful additions,

**Comment by thierryvolpiatto** [comment]
nerton <notifications@github.com> writes:

> Ah, I thought it was a bug, because I expected more actions
> there. E.g. I often find commands with M-x and then want to copy the
> command name in my notes.

C-x C-k

> Or lookup the elisp source code of a command, so I'd like a jump to
> source action. These could be useful additions,

For this use helm-apropos.

--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by nerton** [comment]
> C-x C-k

Thanks. BTW,  I checked helm types and saw such action names:

>    "Describe command" 
>    "Add command to kill ring" 
>    "Go to command's definition" 

Such commands could all be there for helm-M-x too. Helm is about user friendliness and easy discoverability, so it wouldn't hurt to have these also in the M-x actions list.

> For this use helm-apropos.

Yes, I can use helm-apropos for this, but I like helm, because when I select something then it offers the appropriate actions. If I started helm-M-x and already selected a command and it occurs to me check its definition then should I terminate M-x, go to apropos and look up the command again? Why? Isn't it more user friendly to have all the function commands which are applicable to commands right there in helm-M-x?

**Comment by thierryvolpiatto** [comment]
nerton <notifications@github.com> writes:

>     C-x C-k
>
> Thanks. BTW, I checked helm types and saw such action names:
>
>     "Describe command"
>     "Add command to kill ring"

Use C-c C-k, it is available everywhere in Helm.

>     "Go to command's definition"

The type command is not used anymore and is just here for backward
compatibility.

> Such commands could all be there for helm-M-x too.

No, not with current implementation.

> Helm is about user friendliness and easy discoverability, so it
> wouldn't hurt to have these also in the M-x actions list.
>
>     For this use helm-apropos.
>
> Yes, I can use helm-apropos for this, but I like helm, because when I
> select something then it offers the appropriate actions. If I started
> helm-M-x and already selected a command and it occurs to me check its
> definition then should I terminate M-x, go to apropos and look up the
> command again? Why? Isn't it more user friendly to have all the
> function commands which are applicable to commands right there in
> helm-M-x?

Perhaps, but for this I would have to rewrite helm-M-x and I don't have
the time and motivation for this.
I added two new user vars that may help showing function definitions in
helm-M-x (will affect helm-apropos and others as well),

    (setq helm-describe-variable-function 'helpful-variable
          helm-describe-function-function 'helpful-callable)

(you need helpful package for this).

https://github.com/Wilfred/helpful


--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by nerton** [comment]
> Use C-c C-k, it is available everywhere in Helm.

OK, but you see actions list is like a menu in GUI programs. Menus are about discoverabilty. If you don't know how to invoke a function then you dig through the menu. And the hotkey is listed beside the menu item, so if I use it frequently then I can learn its hotkey. If one, like me, uses copying only occasionally then one may not remember C-c C-k and that's why copying should be listed on every action list, because if I don't remember the key then I can just tab and find/search the copy action (and optimally its hotkey is shown beside it, so I can learn it if using it frequently).

> The type command is not used anymore and is just here for backward compatibility.

That's too bad. Command are functions too, so every action available for functions should be available for commands too, so they can be accessed easily. Commands could simply inherit functions' actions.

> I added two new user vars that may help showing function definitions in helm-M-x (will affect helm-apropos and others as well), 

Thank you, though I think actions should be mainly defined from types and if you know the actual item is a function, then function actions should always be available for any source which shows functions.

Anyway, thanks for the new vars. I'll check them out. Closing this.

**Comment by thierryvolpiatto** [comment]
nerton <notifications@github.com> writes:

>     Use C-c C-k, it is available everywhere in Helm.
>
> OK, but you see actions list is like a menu in GUI programs. Menus are
> about discoverabilty. If you don't know how to invoke a function then
> you dig through the menu.  And the hotkey is listed beside the menu
> item, so if I use it frequently then I can learn its hotkey. If one,
> like me, uses copying only occasionally then one may not remember C-c
> C-k and that's why copying should be listed on every action list,
> because if I don't remember the key then I can just tab and
> find/search the copy action (and optimally its hotkey is shown beside
> it, so I can learn it if using it frequently).

Helm have an embeded documentation that nobody reads... C-c C-k is
mentionned there among other things.

--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by nerton** [comment]
> Helm have an embeded documentation that nobody reads... C-c C-k is mentionned there among other things.

That's true for other programs as well,people don't read the help, that's why programs have menus, for easy discoverability, so the users can quickly find what they want without reading the documentation. This is the user friendly way.

In the C-c C-k case what does the user think? I want to copy this item, helm has actions, so it's completely natural in helm to press tab and expect to see the copy candidate as one of the actions there. And it could also show the C-c C-k shortcut beside it, so the user can learn it if he/she uses it often.

This is the paradigm GUI programs use for decades and this is a great way for feature discovery and shortcut memorization.

**Comment by nerton** [comment]
Practically every common action which can be performed with a hotkey, should also be listed among the actions, so the user can acess them via the action list as well if he haven't memorized the shortcut yet and it helps with memorization too.
