### ISSUE TITLE
helm-mini cursor right/left no longer moving between groups?

### ISSUE THREAD

**Issue by dsyzling** [emacs-helm/helm#2177]
## Expected behavior
Previous versions of helm-mini I used to be able to navigate between groups using the arrow keys - left/right - i.e. to jump to Recent files.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
Having updated to the most recent version cursor left/right appears to move the cursor within the text I'm using to complete the buffer name rather than jump between groups. 

## Describe versions of Helm, Emacs, operating system, etc.
helm-core is 20190715.1034, Emacs 26.2 Build 1 2019-04-12 on Arch Linux.
helm-20190717.550

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):
I did try and test this but without a recent file list couldn't reproduce my normal behaviour.

**Comment by thierryvolpiatto** [comment]
See https://github.com/emacs-helm/helm/wiki/FAQ#arrow-keys-behavior-have-changed, issue #2175 and https://github.com/emacs-helm/helm/releases/tag/v3.3.

**Comment by dsyzling** [comment]
Thanks for the response - and apologies for next checking the FAQs and recent updates.
