### ISSUE TITLE
Why helm lacks support of multiple async source?

### ISSUE THREAD

**Issue by cireu** [emacs-helm/helm#2178]
I found multiple async source sometimes useful for me. But helm has weird behavior when handling multiple async source according to https://github.com/emacs-helm/helm/blob/master/helm-source.el#L714.

I' interesting what's the main issue on handling multiple async source?

**Comment by thierryvolpiatto** [comment]
Zhu Zihao <notifications@github.com> writes:

> I found multiple async source sometimes useful for me. But helm has weird behavior when handling multiple async source according to 
> https://github.com/emacs-helm/helm/blob/master/helm-source.el#L714.
>
> I' interesting what's the main issue on handling multiple async source?

One process-buffer for one or more processes that finish in
unpredictable order.
This lead to candidates ending up in the wrong sources, mouse overlays
in wrong places etc...

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by cireu** [comment]
Thanks for your answer!
