### ISSUE TITLE
Helm-find-file + TRAMP in home dir: No selection possible

### ISSUE THREAD

**Issue by tinloaf** [emacs-helm/helm#2179]
## Expected behavior

`helm-find-files` should behave as always when using TRAMP.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

After typing `/ssh:someserver.com:`, TRAMP connects to the remote server, and Helm shows my remote home directory. However typing any character removes *all* possible selections. The only way of selecting anything is with the arrow keys. Once I selected any folder in my home directory (using the arrow keys), selection works as it should. 

I made a video of the behavior I see, which you can find here: https://cloud.tinloaf.de/s/Zq6wy9n5RbyHWWj

The emacs in the video is not started via `emacs-helm.sh`, however I just now verified that the behavior is exactly the same if I start it via `emacs-helm.sh`.

## Steps to reproduce (recipe)

1. `M-x helm-find-files RET`
2. select some server you can SSH into and type `/ssh:someserver.com:`
3. Wait for your home directory to be listed
4. Type any character to select a file / directory

## Backtraces if any (`M-x toggle-debug-on-error`)

None

## Describe versions of Helm, Emacs, operating system, etc.

I'm running helm `20190730.451` from MELPA. I also have `helm-projectile` installed. Looking at my `elpa` folder, a package named `helm-core` also seems to be installed. I'm running Emacs v. 26.2 on Ubuntu 18.04. 

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):
Yes, I've used `emacs-helm.sh` from `~/.emacs.d/elpa/helm-20190730.451`.

**Comment by thierryvolpiatto** [comment]
Lukas Barth <notifications@github.com> writes:

> Steps to reproduce (recipe)
>
>  1. M-x helm-find-files RET
>  2. select some server you can SSH into and type /ssh:someserver.com:

You can hit C-j twice on someserver.com insted of manually entering the
":".
 
>  3. Wait for your home directory to be listed

At this point you have to expand to your home directory with C-j.

>  4. Type any character to select a file / directory

And then here it will work as expected.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tinloaf** [comment]
Okay - that hits a different bug(?): If I hit `C-j` (or the right arrow, for that matter) during `helm-find-file`, I get the message `End of buffer`. This happens regardless of where the current highlight is - file or directory.

This changed after I upgraded all my MELPA packages earlier today (to make sure the "bug" I originally reported wasn't fixed already). Before the update, I used `helm-20190424.1443`, which did not have this behavior.

**Comment by tinloaf** [comment]
Okay, correction: `C-j` seems to have started working again, but the right arrow (which I so far always used…) still gives me `End of buffer`. However, I can just start using `C-j`. Thanks for the help!

**Comment by thierryvolpiatto** [comment]
Lukas Barth <notifications@github.com> writes:

> Okay, correction: C-j seems to have started working again, but the
> right arrow (which I so far always used…) still gives me End of
> buffer. However, I can just start using C-j. Thanks for the help!

https://github.com/emacs-helm/helm/wiki/FAQ#arrow-keys-behavior-have-changed

--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tinloaf** [comment]
Thank you!
