### ISSUE TITLE
helm doesn't work with :bind-keymap from use-package/bind-key

### ISSUE THREAD

**Issue by alfons4966** [emacs-helm/helm#2181]
## Expected behavior

If you run Emacs with the included init-file, and you attempt:

M-x: describe-personal-keybindings 

(or any other M-x command that includes a 'r') I expect it to succeed (i.e. see a *Personal Keybindings* window).

[init.el.gz](https://github.com/emacs-helm/helm/files/3453141/init.el.gz)

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

However, if you try M-x: describe-personal-keybindings, you get a:

Error: Trying to run helm within a running helm session.

error when you type in the 'r' of desc**r**. Reason: 'r' is mapped to helm-occur.  

## Steps to reproduce (recipe)

Run Emacs with an empty .emacs.d directory apart from the included init-file, and try:

M-x: describe-personal-keybindings 

## Backtraces if any (`M-x toggle-debug-on-error`)

helm.el:3165 set helm-alive-p to t
helm.el:2445 Error: Trying to run helm within a running helm session
helm.el:3598 set helm-alive-p to nil

## Describe versions of Helm, Emacs, operating system, etc.

master branch of 2019-07-31
GNU Emacs 26.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2019-06-26

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):

No. This error occurs when you run helm combined with use-package/bind-key. I must admit that I am not convinced that helm is to blame. However, the simplest solution would be if, instead of the error in line 2445, helm just returns. (I might do that as well.)

## IMPORTANT NOTE

Helm provides a script named `emacs-helm.sh` which runs Helm in a neutral
environment: no other packages and only minimal settings.

When possible, use it to reproduce your Helm issue to ensure no other package is
interfering.

To run it, simply switch to the directory where Helm is installed and call `./emacs-helm.sh`.
If necessary you can specify emacs executable path on command line with "-P" option.

Thanks.

**Comment by thierryvolpiatto** [comment]
https://github.com/emacs-helm/helm/wiki#configure

**Comment by thierryvolpiatto** [comment]
```elisp
(use-package helm

  :bind-keymap
  ("C-c h" . helm-map)
  :bind
  (("M-x" . helm-M-x)
  :map helm-map
  ("r" . helm-occur)))
```
In this config, helm-M-x doesn't belong to `helm` package but `helm-command` package, `helm-occur` is a global command and also doesn't belong to `helm` package but `helm-occur` package and finally `helm-map` is not a global map, so if you want to bind e.g. helm-M-x to `C-c h M-x` you have to do it in global-map not `helm-map` i.e. setting a prefix key on helm-map will have for effect to prefix all helm keybindings (the ones used in a helm session) with `C-c h`.

Note that what `(require 'helm-config)` does is principally loading the autoload file which is very fast.

HTH.

**Comment by thierryvolpiatto** [comment]
If you want a prefix key for global commands, use `helm-command-prefix-key`.
