### ISSUE TITLE
Hiding empty lines between sources

### ISSUE THREAD

**Issue by nerton** [emacs-helm/helm#2182]
Is there an option to hide the empty lines between sources? It would be useful for making the display of some helm commands more compact.

**Comment by thierryvolpiatto** [comment]
nerton <notifications@github.com> writes:

> Is there an option to hide the empty lines between sources? It would
> be useful for making the display of some helm commands more compact.

No, and the space is needed.

--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by nerton** [comment]
> No, and the space is needed.

Could we then have at least a separate face for those empty lines like helm-empty-line-between-sources-face? Then I could set the height of that face to 0.1 to hide those lines. 

I have to set emacs fonts large, so my eyes don't get tired so quickly when staring at the screen long, and because of this I can display less information in an emacs window than other people. That's why it's  important for me to hide those empty lines, so I can display more actual information on the screen with bigger fonts. Thanks.

**Comment by nerton** [comment]
Thank you! Closing this.
