### ISSUE TITLE
Command is called "org-set-tags-command" - not "org-set-tags"

### ISSUE THREAD

**Issue by NathanNeff** [emacs-helm/helm#2183]
Hello,

When using org-mode 9.2 and higher, set-tags was broken.  It was displaying the 
set of tags correctly when a heading had no tags.  However, if a heading had 1+ tags
already, then Helm was not displaying the list of available tags.

I think I found the issue (it's quite simple).  The org-set-tags function is not called by
org-mode when pressing C-c C-q.  The function is called "org-set-tags-command".

I modified  my helm-completing-read-handlers-alist and added an entry
(org-set-tags-command . helm-org-completing-read-tags) and this fixed the problem.

https://github.com/emacs-helm/helm/blob/dde90de5c5408e22503f23ed0310f3277f4f6014/helm-mode.el#L45

**Comment by NathanNeff** [comment]
Hmm, after looking a bit further, the old emacs versions also called "org-set-tags-command" when pressing C-c C-q.  

org-set-tags-command calls org-set-tags.  So, why does this fix work?

` (org-set-tags-command . helm-org-completing-read-tags) `

I don't know enough about the magic of Helm to know why this fix works (being
that org versions 9.1.x and 9.2.x both call `org-set-tags-command` which calls
`org-set-tags`.

The definitions of `org-set-tags-command` and `org-set-tags`  changed quite a bit
from org 9.1.x to Org 9.2.x.  One difference that I notice is that the old version of 
`org-set-tags` [1]  was an (interactive) function and the new version of `org-set-tags` is
not [2].

Any ideas?

[1] 9.1.14 https://code.orgmode.org/bzg/org-mode/src/release_9.1.14/lisp/org.el#L14883
[2] 9.2.5 https://code.orgmode.org/bzg/org-mode/src/master/lisp/org.el#L12334

**Comment by NathanNeff** [comment]
Possibly related issues:
https://github.com/emacs-helm/helm/issues/1890
https://github.com/emacs-helm/helm/issues/2063

**Comment by alphapapa** [comment]
Hi Nathan,

If you would, please file this bug on the new https://github.com/emacs-helm/helm-org repo so I can work on it there.

**Comment by NathanNeff** [comment]
Done
