### ISSUE TITLE
org-set-tags and org-capture - move to helm-org.el?

### ISSUE THREAD

**Issue by NathanNeff** [emacs-helm/helm#2184]
Hello, I noticed that helm-org.el was recently moved out of the
helm package.  Should these entries also be moved out of helm?

https://github.com/emacs-helm/helm/blob/dde90de5c5408e22503f23ed0310f3277f4f6014/helm-mode.el#L45

**Comment by thierryvolpiatto** [comment]
Nathan Neff <notifications@github.com> writes:

> Hello, I noticed that helm-org.el was recently moved out of the
> helm package. Should these entries also be moved out of helm?
>
> https://github.com/emacs-helm/helm/blob/dde90de5c5408e22503f23ed0310f3277f4f6014/helm-mode.el#L45

Yes, and some others, done.

Thanks.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
