### ISSUE TITLE
Emacs and window manager freeze during helm-M-x call

### ISSUE THREAD

**Issue by zmorrissey** [emacs-helm/helm#2186]
Hello,

Thank you for your work on the `helm` package. After recently upgrading my Emacs packages, I have been having a recurring issue when calling `helm-M-x` that I have been having difficulty diagnosing.

Previously, calling `helm-M-x` would return near instant updates to the mini-buffer window, however now it seems to randomly freeze at times after typing a few characters, and often will also cause my window manager (LXDE + OpenBox) to momentarily freeze as well, until I repeatedly press C-g to attempt to quit `helm-M-x`. 

Oddly, from what I have seen it only seems to affect the `helm-M-x` call, and not any other helm functions (e.g. `helm-find-files`, `helm-buffers-list`, etc.). Furthermore, I do not receive any warnings, messages, or traceback errors from Emacs when I do the `helm-M-x` call.

Running a minimal Emacs with `emacs-helm.sh` seems to work as expected, so I suspect a package conflict in my configuration, but unfortunately without any apparent error messages I'm not sure where to begin looking to help resolve this issue.

Any help or suggestions would be greatly appreciated, thank you.

## Expected behavior
Calls to `helm-M-x` normally update the buffer near instantaneously without error.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
After calling `helm-M-x` and typing a few characters, Emacs will freeze and sometimes cause the window manager to freeze as well until `C-g` is repeatedly called. However, Emacs appears to freeze somewhat randomly and `helm-M-x` will appear to work normally for a while and then it will happen again. Restarting Emacs does not seem to change the behavior.

## Steps to reproduce (recipe)
`helm-M-x`, begin typing into minibuffer

## Backtraces if any (`M-x toggle-debug-on-error`)
No backtraces produced.

## Describe versions of Helm, Emacs, operating system, etc.
- OS: Ubuntu 16.04 xenial
- DE: LXDE
- WM: OpenBox
- Emacs 25.3.2
- Helm 20190813.1417

Other `helm`-related packages installed:
- `helm-bibtex-2019-07-08.909`
- `helm-core-20190809.1008`
- `helm-dictionary-20160817.2033`
- `helm-projectile-20190731.1538`
- `helm-swoop-20190813.1234`

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):
Running `emacs-helm.sh -P emacs25` seems to work as expected, no freezing issues.

## IMPORTANT NOTE

Helm provides a script named `emacs-helm.sh` which runs Helm in a neutral
environment: no other packages and only minimal settings.

When possible, use it to reproduce your Helm issue to ensure no other package is
interfering.

To run it, simply switch to the directory where Helm is installed and call `./emacs-helm.sh`.

If necessary you can specify emacs executable path on command line with "-P" option.

Thanks.

**Comment by thierryvolpiatto** [comment]
zmorrissey <notifications@github.com> writes:

> Any help or suggestions would be greatly appreciated, thank you.

I suggest you comment all your init file (except helm) and then start
commenting out package by package until you can repeat the bug, then you
will know that the last uncommented is the culprit.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
