### ISSUE TITLE
xref-find-definitions at start of buffer with "// something" generates error with helm-mode

### ISSUE THREAD

**Issue by bgoodr** [emacs-helm/helm#2188]
## Expected behavior

Using M-. when helm-mode is active on a C++ buffer should work in all cases without generating helm-specific errors, even if point is not on a symbol, at the start of a buffer that has "// something in it.

If only "//" is at the start of the buffer, and point is on the very first "/", no error is produced.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

See this error:

    Aborting an helm session running in background
    custom-initialize-reset: In ‘xref-find-definitions’ source: ‘#[0 GARBAGE_BYTES_REMOVED_HERE [test.C enable-recursive-minibuffers t visit-tags-table-buffer complete-with-action tags-completion-table] 8

    (fn STRING PRED ACTION)] nil  nil nil helm-comp-read-get-candidates  helm-cr-default] 6]’
     (user-error "No recursive edit is in progress")

## Steps to reproduce (recipe)

This is the most minimally complete verifiable example showing what I'm seeing:
    
    #!/bin/bash

    rm -rf helm_bug_test_dir
    mkdir -p helm_bug_test_dir
    cd helm_bug_test_dir/
    
    elisp_test_file=test.el
    
    cat > $elisp_test_file <<EOF
    (progn
      (setq user-emacs-directory "$(pwd)/.emacs.d.tempdir.for.bug.report/")
      (let ((package 'helm))
        (require 'package)
        (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
        (package-initialize)
        (when (not package-archive-contents)
          (package-refresh-contents))
        (unless (package-installed-p package)
          (package-install package)))
      (helm-mode 1)
      (find-file "test.C"))
    EOF
    
    # This works:
    # echo '//' > test.C
    
    # This gives the error:
    echo '// something' > test.C
    
    emacs -Q --load $elisp_test_file
    

Run the above script.

Then, without moving point from the beginning of the buffer, type: M-.

See this error:

    Aborting an helm session running in background
    custom-initialize-reset: In ‘xref-find-definitions’ source: ‘#[0 GARBAGE_BYTES_REMOVED_HERE [test.C enable-recursive-minibuffers t visit-tags-table-buffer complete-with-action tags-completion-table] 8

    (fn STRING PRED ACTION)] nil  nil nil helm-comp-read-get-candidates  helm-cr-default] 6]’
     (user-error "No recursive edit is in progress")

## Describe versions of Helm, Emacs, operating system, etc.

Emacs Version:

GNU Emacs 25.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.14.13) of 2018-05-26

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no): No

I rolled my own shell script to install helm from melpa into a standalone .emacs.d directory, generate a small .C file, and run M-. from that.

**Comment by thierryvolpiatto** [comment]
Brent Goodrick <notifications@github.com> writes:


> Are you using emacs-helm.sh to reproduce this bug (yes/no): No
>
> I rolled my own shell script to install helm from melpa into a standalone .emacs.d directory, generate a small .C file, and run M-. from that.

No need to complicate with a script, here the steps to reproduce:

1) Start emacs-helm.sh.
2) Write a new file test.c somewhere with \\ something as content.
3) Hit M-. which run xref-find-definitions and you have the error.

For now add xref-find-definitions to helm-completing-read-handlers-alist
or bind `M-.` to `helm-etags-select` (it is what I do).

Don't expect a fix for this sooner, as I am not a xref user, and not
much time to fix such issue, probably the best is adding
xref-find-definitions to helm-completing-read-handlers-alist by default. 

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Seems:

`(add-to-list 'helm-completing-read-handlers-alist '(xref-find-definitions . helm-completing-read-default-find-tag))`

is fixing this issue.

**Comment by thierryvolpiatto** [comment]
Added by default.

**Comment by thierryvolpiatto** [comment]
Added `xref-find-references` as well.

**Comment by bgoodr** [comment]
Thank you!
