### ISSUE TITLE
`helm-occur` doesn't usually search properly with newline characters

### ISSUE THREAD

**Issue by leungbk** [emacs-helm/helm#2189]
## Expected behavior
`helm-occur` should match newline characters consistently.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
Doesn't generally match.

## Steps to reproduce (recipe)
With a buffer containing the text
```
apple = red
  banana = yellow
```

do `helm-occur` and enter `red\C-q\C-j  banana`. This currently fails to match the text "red\n  banana".

Isearch successfully matches "red\n  b" with the above search input.

## Backtraces if any (`M-x toggle-debug-on-error`)
NA

## Describe versions of Helm, Emacs, operating system, etc.
Helm 3.3, Emacs 26.2.

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):
Yes

## IMPORTANT NOTE

Helm provides a script named `emacs-helm.sh` which runs Helm in a neutral
environment: no other packages and only minimal settings.

When possible, use it to reproduce your Helm issue to ensure no other package is
interfering.

To run it, simply switch to the directory where Helm is installed and call `./emacs-helm.sh`.
If necessary you can specify emacs executable path on command line with "-P" option.

Thanks.

**Comment by thierryvolpiatto** [comment]
Brian Leung <notifications@github.com> writes:

> Expected behavior
>
> helm-occur should match newline characters consistently.

No helm-occur is a line by line tool (like grep).

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by leungbk** [comment]
Using `M-x occur` for the example file I posted also handles the newlines correctly. So I suppose I always have that option.
