### ISSUE TITLE
helm buffer source conflicts with helm-locate-library source

### ISSUE THREAD

**Issue by cireu** [emacs-helm/helm#2191]
## Expected behavior

Type magic symbol `@` `*` or any capital character can search buffers.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

Nothing was updated, but if you type a space first(like `<space>*lisp-mode` but not `*lisp-mode` directly), they can work as usual.

## Steps to reproduce (recipe)

Run this script with raw Emacs and `M-x walle-helm-mini`

```elisp
(require 'helm-buffers)
(require 'helm-elisp)

(defun walle-helm--enh-mini-create-source ()
  (unless helm-source-buffers-list
    (setq helm-source-buffers-list
          (helm-make-source "Buffers" 'helm-source-buffers)))

  `(
    ;; Buffers Recentf Bookmarks
    helm-source-buffers-list
    ;; Elisp library
    ,(helm-build-in-buffer-source "Elisp libraries (Scan)"
       :data #'helm-locate-library-scan-list
       :fuzzy-match helm-locate-library-fuzzy-match
       :keymap helm-generic-files-map
       :search (unless helm-locate-library-fuzzy-match
                 (lambda (regexp)
                   (re-search-forward
                    (if helm-ff-transformer-show-only-basename
                        (replace-regexp-in-string
                         "\\`\\^" "" regexp)
                      regexp)
                    nil t)))
       :match-part (lambda (candidate)
                     (if helm-ff-transformer-show-only-basename
                         (helm-basename candidate) candidate))
       :filter-one-by-one (lambda (c)
                            (if helm-ff-transformer-show-only-basename
                                (cons (helm-basename c) c) c))
       :action (helm-actions-from-type-file))))

(defun walle-helm-mini ()
  (interactive)
  (helm :sources (walle-helm--enh-mini-create-source)
        :buffer "*helm walle enh mini*"
        :ff-transformer-show-only-basename nil
        :truncate-lines helm-buffers-truncate-lines))
```

## Backtraces if any (`M-x toggle-debug-on-error`)

No

## Describe versions of Helm, Emacs, operating system, etc.

OS: Archlinux
Emacs: 27.0.5
Helm: https://github.com/emacs-helm/helm/commit/49d56c19aa00843d086527b7e7fe02058a37061f

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):

No, but `emacs -Q` with only async and helm loaded.

**Comment by thierryvolpiatto** [comment]
Sorry, but what do expect from me to do here ?

**Comment by cireu** [comment]
I just want to know why these two sources conflict, in fact `helm-source-buffer-list` cam work well with many sync source, but helm-locate-library. Is it a bug?

**Comment by thierryvolpiatto** [comment]
Zhu Zihao <notifications@github.com> writes:

> I just want to know why these two sources conflict, in fact
> helm-source-buffer-list cam work well with many sync source, but
> helm-locate-library. Is it a bug?

Don't know for now, I just noticed that if you disable
`helm-locate-library-fuzzy-match` it is working as expected.
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.*


--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by cireu** [comment]
thanks! I' ll use this work around.

**Comment by thierryvolpiatto** [comment]
Seems to be a bug, when entering in minibuffer e.g. *lisp the first source should succeed and the second fail (with invalid regexp) and not be displayed.
Will look into this ASAP.

**Comment by thierryvolpiatto** [comment]
Here what is happening, when you enter e.g. *lisp the fuzzy matching search function doesn't understand "*lisp" and try to fuzzy match it, as soon as you enter a space, the fuzzy fn give up and buffer filtering start working again.
It is still unclear why the second source doesn't fail completely letting the first one (buffers) making its job.  I will investigate more on this.

**Comment by thierryvolpiatto** [comment]
So entering "*lisp " works but entering "*lisp" doesn't.

**Comment by thierryvolpiatto** [comment]
@cireu Should work now.

Thanks.

**Comment by cireu** [comment]
Thanks for your work :+1:
