### ISSUE TITLE
Remove empty lines/spaces from helm-buffer.

### ISSUE THREAD

**Issue by jcs090218** [emacs-helm/helm#2192]
This isn't the bug, is just an enhancement suggestion. 

#### Description
Currently if I pressed up key in `helm` buffer, the window scroll to the center of the current `helm-buffer`. Can you make so the buffer at the bottom does not have that much of the empty space at the bottom? (After the last valid selection)

#### Current behavior
Extra lines at the bottom.
![no-ep](https://user-images.githubusercontent.com/8685505/63661355-cf8f6000-c7ec-11e9-895b-46ba19500af9.gif)

#### Expect behavior
No extra lines shown.
![ep](https://user-images.githubusercontent.com/8685505/63661371-de761280-c7ec-11e9-9d68-8f4ad6c19b1d.gif)

**Comment by thierryvolpiatto** [comment]
Jen-Chieh Shen <notifications@github.com> writes:

> This isn't the bug, is just an enhancement suggestion.
>
> Description
>
> Currently if I pressed up key in helm buffer, the window scroll to the
> center of the current helm-buffer. Can you make so the buffer at the
> bottom does not have that much of the empty space at the bottom?
> (After the last valid selection)

Use `helm-autoresize-mode`.


--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by jcs090218** [comment]
> Use `helm-autoresize-mode`.

I did!

**Comment by jcs090218** [comment]
@thierryvolpiatto Ping! What do you think about this?

**Comment by thierryvolpiatto** [comment]
Jen-Chieh Shen <notifications@github.com> writes:

> @thierryvolpiatto Ping! What do you think about this?

It is not a problem of buffer but window resizing.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by jcs090218** [comment]
As I know, window resizing occurs when the number of candidates displayed are smaller than the window’s height? The situation here is when I hit up, it goes to the last selection but with the buffer is centered. Hence there are empt lines at the bottom, and in this case candidates are higher when the window’s height so resizing wouldn’t be triggered.

**Comment by thierryvolpiatto** [comment]
Sorry but I don't understand what is the problem, with `helm-autoresize-mode` the window is resized to the exact content of buffer. Seems that in you examples above you are not using `helm-autoresize-mode`.

**Comment by awkr** [comment]
I support @jcs090218 's idea, which is more space compact and no need to show the useless empty line.
@thierryvolpiatto `helm-autoresize-mode` is a good idea but not for this issue. Let's say an example:
I enabled `helm-autoresize-mode`, simply open `helm-M-x`, and keep press `C-v` till the end of the candidates, U will see that the last line is in the middle of helm window not at the bottom.

![image](https://user-images.githubusercontent.com/1202134/90329870-bc1b6d00-dfda-11ea-9f90-4842da802dfc.png)
