### ISSUE TITLE
feature request: helm-wikipedia insert as org link.

### ISSUE THREAD

**Issue by dangom** [emacs-helm/helm#2193]
Not a bug.

Similar to `helm-find-files`, it'd be nice if `helm-wikipedia` would also allow inserting the candidate as an org link with `C-c @` or copying the link to the kill-ring.

**Comment by thierryvolpiatto** [comment]
Daniel Gomez <notifications@github.com> writes:

> Not a bug.
>
> Similar to helm-find-files, it'd be nice if helm-wikipedia would also
> allow inserting the candidate as an org link with C-c @ or copying the
> link to the kill-ring.

helm-wikipedia is no more part of helm, could you report this to

https://github.com/emacs-helm/helm-wikipedia

We haven't submitted yet to Melpa, but we will add it soon.
I would like to extract the git history from helm repo and merge it with
new repo though, didn't have the time, I will probably do all this end
of september.
@alphapapa is also maintaining this repo.

Thanks.

--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by dangom** [comment]
Reporting at helm-wikipedia.
