### ISSUE TITLE
Does an overlay display function exist/is it planned?

### ISSUE THREAD

**Issue by jjzmajic** [emacs-helm/helm#2194]
I use helm as my completion frontend, and something like this would be ideal: https://www.reddit.com/r/emacs/comments/57fnar/ivy_completion_at_point_in_an_overlay/

Are there any plans to implement it?

**Comment by thierryvolpiatto** [comment]
jjzmajic <notifications@github.com> writes:

> I use helm as my completion frontend, and something like this would be
> ideal:
> https://www.reddit.com/r/emacs/comments/57fnar/ivy_completion_at_point_in_an_overlay/

Note that most of what you find in ivy have been copied from Helm.

> Are there any plans to implement it?

It already exists but it is not used in generic completion.

For example try M-x helm-lisp-completion-at-point.

--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by jjzmajic** [comment]
I use that function in my config, I was just wondering if it was something I could set a variable to, like `display-buffer-in-side-window`. This overlay is nice, but mostly cosmetic. In the video above, other candidates appear in the overlay as well, so your eyes do not have to dart back and forth. 

If it's not implemented, I'll hack something together. Just wondering if I was missing something obvious.

**Comment by thierryvolpiatto** [comment]
Not sure to understand what you want.
Helm use the macro `with-helm-show-completion` to do this.
