### ISSUE TITLE
[Feature] - Hook runs after the buffer is ready.

### ISSUE THREAD

**Issue by jcs090218** [emacs-helm/helm#2196]
Run hook after helm buffer is ready.

**Comment by thierryvolpiatto** [comment]
Jen-Chieh Shen <notifications@github.com> writes:

> Run hook after helm buffer is ready.

helm-after-initialize-hook

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
