### ISSUE TITLE
helm-kill-ring-action-yank should insert after point in evil mode

### ISSUE THREAD

**Issue by codygman** [emacs-helm/helm#2197]
## Expected behavior
In evil mode, calling `helm-show-kill-ring` in normal mode and then hitting enter should insert *after* the point.

This behavior could just be specific to my workflow, but I always call `helm-show-kill-ring` from normal mode and always want a space inserted and to paste starting there.

In org mode for instance I'll be at this point:

```
* thing1 
* |
```

Then whatever I select is inserted at the cursor and I need it to be inserted after.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
In evil mode, calling `helm-show-kill-ring` in normal mode and then hitting enter inserts at the point.

## Steps to reproduce (recipe)
1. Open buffer with org-mode and evil-mode active
2. paste these contents in buffer, then go back to normal mode with `ESC`
```
* foo
```
2. `C-RET` creates a new org heading
3. move up to foo and place normal mode cursor on `f` then type `yw` to yank word.
4. move back down to new heading and go to end of line with `$` which will be one character in front of the asterisk followed by one space.
5. `M-x helm-show-kill-ring`, `RET`, and observe that your contents now looks like:

```
* foo
*foo 
```

instead of the desired:
```
* foo
* foo 
```

This is what `evil-paste-after` does, so perhaps helm core can't support evil here? Or maybe if evil exists it could specify to use `evil-paste-after`? Not sure if that is an acceptable solution.

## Describe versions of Helm, Emacs, operating system, etc.
helm: 65edabd2cf985eb25d8e4251e6d1626937597d9f (3.3?)
27.0.50
nixos: NixOS 19.09pre190978.8d1510abfb5

**Comment by thierryvolpiatto** [comment]
Cody Goodman <notifications@github.com> writes:

> Expected behavior
>
> In evil mode, calling helm-show-kill-ring in normal mode and then hitting enter should insert after the point.
>
> This behavior could just be specific to my workflow, but I always call helm-show-kill-ring from normal mode and always want a space inserted and to paste starting
> there.
>
> In org mode for instance I'll be at this point:
>
> * thing1 
> * |
>
> Then whatever I select is inserted at the cursor and I need it to be inserted after.
>
> Actual behavior (from emacs-helm.sh if possible, see note at the bottom)
>
> In evil mode, calling helm-show-kill-ring in normal mode and then hitting enter inserts at the point.
>
> Steps to reproduce (recipe)
>
>  1. Open buffer with org-mode and evil-mode active
>  2. paste these contents in buffer, then go back to normal mode with ESC
>
> * foo
>
>  2. C-RET creates a new org heading
>  3. move up to foo and place normal mode cursor on f then type yw to yank word.
>  4. move back down to new heading and go to end of line with $ which will be one character in front of the asterisk followed by one space.
>  5. M-x helm-show-kill-ring, RET, and observe that your contents now looks like:
>
> * foo
> *foo 

I guess this is a problem with Evil, don't expect any change here as it is
working as expected with emacs-helm.sh.
Also I am not using evil and even if I install it I don't know how it works.
You should report this to Evil.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by niwtr** [comment]
Try this:

```emacs-lisp
;;  a magic patch that allows to insert the kill ring history AFTER the point.
(defun patch-fix-helm-kill-ring-action-yank (old-fn &rest arg)
  (interactive)
  (save-excursion
    (evil-save-state
      (evil-insert-state)
      (evil-append 1)
      (apply old-fn arg)
      (sit-for 0.001))))
(advice-add 'helm-kill-ring-action-yank :around #'patch-fix-helm-kill-ring-action-yank)
```
