### ISSUE TITLE
Disable helm-move-to-line-cycle-in-source when there are multiple sources?

### ISSUE THREAD

**Issue by netjune** [emacs-helm/helm#2198]
I set helm-move-to-line-cycle-in-source to t. It works well when there is only one source.
But when there are multiple sources, I can't move to next source with C-n. 

I can move to next source with C-o, but it's not convenient than C-n.

Can the cycling be across the candidates of all sources?

**Comment by thierryvolpiatto** [comment]
To go to end of last source, use M->.

**Comment by netjune** [comment]
OK. Thanks.
