### ISSUE TITLE
use .gitignore in `helm-find-files`

### ISSUE THREAD

**Issue by vzaliva** [emacs-helm/helm#2201]
This is a feature request.

It would be great if `helm-find-files` would take into account `.gitignore` and show only relevant (not ignored) files. For example, like `helm-ag` does.

**Comment by vzaliva** [comment]
I am no elisp expert, but I found a quick and dirty way to do this as follows:

```
(defun is-git-ignored (file)
  (zerop (call-process "git" nil nil nil "check-ignore" "-q" file)))

(defun helm-ff-boring-file-p (file)
  ;; Prevent user doing silly thing like
  ;; adding the dotted files to boring regexps (#924).
  (and (not (string-match "\\.$" file))
       (or (string-match  helm-ff--boring-regexp file)
           (is-git-ignored file))))
```

The first function is new, and the second is patched one from `helm-files.el`.

Maybe there is a more elegant way to do so. I do not mind preparing proper patch if this approach makes sense. Probably need a config variable to enable this functionality.

**Comment by thierryvolpiatto** [comment]
Vadim Zaliva <notifications@github.com> writes:

> I am no elisp expert, but I found a quick and dirty way to do this as follows:
>
> (defun is-git-ignored (file)
>   (zerop (call-process "git" nil nil nil "check-ignore" "-q" file)))

Yes, using git to check this is the way to go, it is much faster than
using elisp.

> (defun helm-ff-boring-file-p (file)
>   ;; Prevent user doing silly thing like
>   ;; adding the dotted files to boring regexps (#924).
>   (and (not (string-match "\\.$" file))
>        (or (string-match  helm-ff--boring-regexp file)
>            (is-git-ignored file))))
>
> The first function is new, and the second is patched one from helm-files.el.
>
> Maybe there is a more elegant way to do so. I do not mind preparing
> proper patch if this approach makes sense. Probably need a config
> variable to enable this functionality.

This approach force user to use `helm-ff-skip-boring-files` to be able to
check git ignored files, I have installed a change that allows one to
use one or the other or both.
So now you can use `helm-ff-skip-boring-files` and/or
`helm-ff-skip-git-ignored-files`.
Note that such settings slow down helm-find-files.

Thanks.

--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Note also that this checking is not done on remote files for performance reasons.

**Comment by vzaliva** [comment]
I just tested this and it works nicely. Thanks!
