### ISSUE TITLE
 How can I make force helm to behave more like Ivy and not take the entire screen for completions?

### ISSUE THREAD

**Issue by mrbig033** [emacs-helm/helm#2202]
I wish for Helm to be less intrusive, occupying a section of the below screen instead of the entire frame. I tried several configurations that, as you can see below:

``` emacs-lisp
(use-package helm
  :ensure t
  :config
  (set-face-attribute 'helm-source-header nil :height 0.1)
  (setq helm-help-full-frame nil
        helm-popup-frame t
        helm-display-header-line nil
        helm-display-buffer-default-height 30
        helm-autoresize-max-height 30
        helm-autoresize-min-height 30
        helm-split-window-state 'horizontal
        helm-split-window-default-side 'below
        helm-split-window-in-side-p t
        helm-window-prefer-horizontal-split t)
  (helm-autoresize-mode +1)
  (helm-mode +1))
```

I also tried these `(helm-autoresize-mode -1)` if that's an issue, with no effect. Every time I run `helm-org-rifle` or a similar command, it takes the entire screen and I cannot see my current buffer anymore. How can I change that?

**Comment by thierryvolpiatto** [comment]
mrbig033 <notifications@github.com> writes:

> I wish for Helm to be less intrusive, occupying a section of the below screen instead of the entire frame, like Ivy does. I tried several configurations, as you can
> see below:
>
> (use-package helm
>   :ensure t
>   :config
>   (set-face-attribute 'helm-source-header nil :height 0.1)
>   (setq helm-help-full-frame nil
>         helm-popup-frame t

Please use only user variables unless you know what you are doing.

>         helm-display-header-line nil
>         helm-display-buffer-default-height 30
>         helm-autoresize-max-height 30
>         helm-autoresize-min-height 30
>         helm-split-window-state 'horizontal

Same.

>   
>         helm-split-window-default-side 'below
>   helm-split-window-in-side-p t helm-window-prefer-horizontal-split t)
>   (helm-autoresize-mode +1) (helm-mode +1))
>
> I also tried these (helm-autoresize-mode -1) if that's an issue, with
> no effect. Every time I run helm-org-rifle or a similar command,

What is similar command?
Most sources in helm are displayed by default in a split-window layout
unless you modify this.
For helm-org-rifle, I guess @alphapapa its developer have forced the use
of full-frame.

> it takes the entire screen and I cannot see my current buffer
> anymore. How can I change that?

For *org-rifle, better is to ask on its github issue page, for Helm I
suggest you start from emacs-helm.sh and see if most common sources
display as you wish and progressively change the configuration window if
needed. I suggest you use `helm-always-two-windows` (like emacs-helm.sh)
to start with.

Note also that Helm allows using frames which allows seeing all your
windows while in Helm...

--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by mrbig033** [comment]
Thank you very much for answering.

I just removed all my configurations and restarted Emacs from scratch. Helm occupies the entire frame for `helm-M-x`, `org-rifle` and `helm-find-files`. I also tried the suggested option `(setq helm-always-two-windows 't)`. It had no effect.

These are my current configurations, but I'd like to stress that I also tested it with no configuration whatsoever:

    (use-package helm
      :ensure t
      :config
      (set-face-attribute 'helm-source-header nil :height 0.1)
      (setq helm-help-full-frame nil
            helm-popup-frame t
            helm-display-header-line nil
            helm-display-buffer-default-height 30
            helm-autoresize-max-height 30
            helm-autoresize-min-height 30
            helm-split-window-state 'horizontal
            helm-split-window-default-side 'below
            helm-split-window-in-side-p t
            helm-split-window-inside-p nil
            helm-window-prefer-horizontal-split t
            helm-always-two-windows 't)

      (helm-split-window-default-fn 'below)

      (defun my/helm-org-in-buffer-headings ()
        (interactive)
        (widen)
        (helm-org-in-buffer-headings)
        (org-narrow-to-subtree))

      (helm-autoresize-mode +1)
      (helm-mode +1))

**Comment by thierryvolpiatto** [comment]
mrbig033 <notifications@github.com> writes:

> Thank you very much for answering.
>
> I just removed all my configurations and restarted Emacs from
> scratch. Helm occupies the entire frame for helm-M-x, org-rifle and
> helm-find-files.

If helm use full frame with helm-M-x and helm-find-files I guess you are
not really restarting from scratch i.e. emacs -Q or emacs-helm.sh.
Please when you report a bug always start with emacs-helm.sh if
possible (as specified in the issue template among other things),
otherwise with emacs -Q, then install only helm with default settings.

--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Here a screenshot of Helm started from emacs-helm.sh:
![Capture d’écran_2019-09-21_10-05-00](https://user-images.githubusercontent.com/1533939/65370284-57835100-dc57-11e9-8317-e8939ef0e4f4.png)

**Comment by thierryvolpiatto** [comment]
Also as I said in previous post use only user variables in your config.

**Comment by mrbig033** [comment]
> Also as I said in previous post use only user variables in your config.

I don't know what "user variables" mean. Regardless, I also tried with no configuration whatsoever (therefore with no customized variable, "user" or not"), and the behavior was not changed. I'm very sorry for my ignorance, but I'm doing my best here. Any help is appreciated.

**Comment by mrbig033** [comment]
> If helm use full frame with helm-M-x and helm-find-files I guess you are not really restarting from scratch i.e. emacs -Q or emacs-helm.sh.

I did fully killed every single Emacs process on my system and restarted from scratch.

If I use `emacs -Q` it will not see any of my configurations, including the presence of the Helm package. How am I supposed to use it for testing?

**Comment by thierryvolpiatto** [comment]
mrbig033 <notifications@github.com> writes:

>     Also as I said in previous post use only user variables in your config.
>
> I don't know what "user variables" mean. Regardless, I also tried with
> no configuration whatsoever (therefore with no customized variable,
> "user" or not"), and the behavior was not changed. I'm very sorry for
> my ignorance, but I'm doing my best here. Any help is appreciated.

I know nothing about your system, your emacs version, how did you install
helm etc... If you followed the template to report I could help, for now
I have not enough infos.

--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by mrbig033** [comment]
You know what? Forget it. If such a basic function requires such an involved debugging process, I'd rather go back to Ivy. Sorry for wasting your time.
