### ISSUE TITLE
no trailing '/' in helm-find-files prompt when invoked from org agenda buffer

### ISSUE THREAD

**Issue by CognDiss** [emacs-helm/helm#2203]
## Expected behavior
to consistently have trailing '/' on directory name in initial prompt from helm-find-files.  It is normally present (eg: prompt of "/Users/tbennett/" ), but is missing when invoked from the "*Org Agenda*" buffer.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
helm-find-files from agenda buffer produces a prompt string of "/Users/tbennett/org" -- no trailing '/'

## Steps to reproduce (recipe)
   $ EMACS=/Applications/MacPorts/Emacs.app/Contents/MacOS/Emacs  ./emacs-helm.sh --load-packages org-agenda
   ESC-x org-agenda RET
   a
   C-x C-f

## Describe versions of Helm, Emacs, operating system, etc.
emacs 26.3,  osx 10.13.6

## IMPORTANT NOTE

Helm provides a script named `emacs-helm.sh` which runs Helm in a neutral
environment: no other packages and only minimal settings.

When possible, use it to reproduce your Helm issue to ensure no other package is
interfering.

To run it, simply switch to the directory where Helm is installed and call `./emacs-helm.sh`.
If necessary you can specify emacs executable path on command line with "-P" option.

Thanks.

**Comment by thierryvolpiatto** [comment]
CognDiss <notifications@github.com> writes:

> Expected behavior
>
> to consistently have trailing '/' on directory name in initial prompt
> from helm-find-files. It is normally present (eg: prompt of
> "/Users/tbennett/" ), but is missing when invoked from the "Org
> Agenda" buffer.

Indeed, fixed.

> $ EMACS=/Applications/MacPorts/Emacs.app/Contents/MacOS/Emacs ./emacs-helm.sh --load-packages org-agenda
> ESC-x org-agenda RET

Glad you used emacs-helm.sh to report your bug.
Note that you don't need to specify EMACS=, you can use instead the -P
or --path option, e.g.

./emacs-helm.sh --path /Applications/MacPorts/Emacs.app/Contents/MacOS/Emacs  --load-packages org-agenda

see emacs-helm.sh -h

the --load-packages option actually only load packages installed via
elpa/melpa i.e. package that are in package-user-dir (generally
~/.emacs.d/elpa), org-agenda is anyway autoloaded by emacs.

Thanks.

--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by CognDiss** [comment]
On Thu, Oct 3, 2019 at 2:17 AM Thierry Volpiatto <notifications@github.com>
wrote:

>
> Indeed, fixed.
>

thanks!

>
> Glad you used emacs-helm.sh to report your bug.
>

emacs-helm.sh worked nicely for this problem and I think its use is a very
reasonable request on your part.

--tony
