### ISSUE TITLE
Recursive dependencies when installing.

### ISSUE THREAD

**Issue by jcs090218** [emacs-helm/helm#2204]
I think `helm` require `helm-org` and `helm-org` require `helm`. It leads me encountering `max-lisp-eval-depth` because of the two separated packages are requiring each other. Now I'm not able to either install or upgrade `helm`.

**Comment by ev-ermakov** [comment]
I have the same trouble.

**Comment by ratnesh1729** [comment]
I have the same trouble now.

**Comment by ratnesh1729** [comment]
Anyone knows a quick fix or workaround ? I am stuck with my emacs not loading. .

**Comment by jcs090218** [comment]
You can’t fix this unless you have your config backup.

**Comment by thierryvolpiatto** [comment]
Et voilà, exactly what I feared, reverting now.

**Comment by jcs090218** [comment]
Do this repo have the CI testing? I will recommend to add one so you will know the error immediately after you pushed the commit.

**Comment by thierryvolpiatto** [comment]
Related to issue #2185, fixed, thanks to all.

**Comment by ratnesh1729** [comment]
probably take a couple of hours for melpa to accept this new git change ?

**Comment by ev-ermakov** [comment]
@ratnesh1729
It looks like it works fine now.

**Comment by ratnesh1729** [comment]
Yes! works fine again now.

**Comment by jcs090218** [comment]
I think the issue is resolved! Close this issue for now.
