### ISSUE TITLE
Bind `/` to switch folder in helm-find-files

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#2210]
I know a couple of users (especially newcomers) like to have `/` enter a subfolder in helm-find-files.  Indeed, `/` never matches anything, so it would make sense to switch to the selected candidate if it's a folder.

Thoughts?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I know a couple of users (especially newcomers) like to have / enter a
> subfolder in helm-find-files. Indeed, / never matches anything, so it
> would make sense to switch to the selected candidate if it's a folder.
>
> Thoughts?

It is what it already does.

--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by Ambrevar** [comment]
There could be a misunderstanding. I tried with `emacs -q`L

- `M-x helm-find-files`
- Go to a folder with "abc" as subfolder.
- `ab`
- Select "abc" subfolder.
- `/`

**Expected behaviour:**

You should now be inside the "abc" subfolder.

**Current behaviour:**

`ab/` is at the prompt and Helm displays 0 candidates.

**Comment by Ambrevar** [comment]
What about this:

- `//`: Go to `/`.
- `[^/]/`: descend select subdirectory.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> What about this:
>
> - `//`: Go to `/`.
> - `[^/]/`: descend select subdirectory.

No, actually this is bound to C-j, RET and maybe to <right> so it is
enough, it is clean as it is, I don't want to enter in such hack to have
an Nieme keybindinding for the same thing, please don't insist.

> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.*


-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by Ambrevar** [comment]
No problem!
