### ISSUE TITLE
Improper escaping in completing-read

### ISSUE THREAD

**Issue by zeebu** [emacs-helm/helm#2214]
## Steps to reproduce (recipe)
[M-:] 
(completing-read "test: " nil nil nil "foo.bar")

## Expected behavior
completing-read to display and return unescaped strings (i.e. "foo.bar.baz")

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
completing-read displays "foo\.bar" and returns "foo\\.bar.baz"

## Backtraces if any (`M-x toggle-debug-on-error`)
N/A

## Describe versions of Helm, Emacs, operating system, etc.
helm-20191023.1610
GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, X toolkit, Xaw scroll bars) of 2019-01-15

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no): 
yes

## Are you using Spacemacs? (yes/no): 
no

Thanks.

**Comment by thierryvolpiatto** [comment]
zeebu <notifications@github.com> writes:

> Steps to reproduce (recipe)
>
> [M-:]
> (completing-read "test: " nil nil nil "foo.bar")
>
> Expected behavior
>
> completing-read to display and return unescaped strings (i.e. "foo.bar.baz")
>
> Actual behavior (from emacs-helm.sh if possible, see note at the bottom)
>
> completing-read displays "foo.bar" and returns "foo\.bar.baz"

Should be fixed, perhaps there is a corner case where we needed to quote
this, don't remember, will see if we have a problem with this.

Thanks.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
