### ISSUE TITLE
Handle confusing or unpredictable switch-to-*buffer behavior called from Helm-M-x

### ISSUE THREAD

**Issue by achinhorn** [emacs-helm/helm#2216]
The `switch-to*buffer` commands are commonly invoked from the minibuffer via M-x technically after the buffer has been created by helm. It's reasonable to expect helm should be doing something to exclude the state it created when it was called. The built-in already includes a case for handling the minibuffer, and the implications aren't very clear in regard to Helm's minibuffer.

It's clear `helm-M-x` should not consider any of it's created state in the context of the selected command in the general case, with exception of allowing universal args to pass to the invoked command. This would ensure numerous possible edge-cases are solved for. A fair bit of handling is in `switch-to-prev-buffer` whose source doesn't fit on my screen, but it doesn't seem to protect helm users. (emacs 27)

## Actual behavior
Calling `switch-to-prev-buffer` via `helm-M-x` oddly managed to switch... to the candidates buffer, which didn't exist prior to pressing M-x to call the command. (My cursor was placed in the helm candidates buffer.) Additionally, I could not get back to the minibuffer, but could switch to it using `helm-mini` in a regular window.

Also oddly, I ran into the following errors the first two times I invoked the `switch-to-prev-buffer`, but which I can't seem to repro (from Message buffer)
```
Error during redisplay: (eval (with-helm-buffer (helm-show-candidate-number (car-safe helm-mode-line-string)))) signaled (error "No buffer named *helm*") [3 times]
user-error: No undo information in this buffer
Quit [7 times]
#<buffer *Messages*>
#<buffer *helm mini*>Error during redisplay: (eval (with-helm-buffer (helm-show-candidate-number (car-safe helm-mode-line-string)))) signaled (error "No buffer named *helm*")
```

## Steps to reproduce (recipe)
`M-x switch-to-prev-buffer RET`

I know that `helm-mini` or `helm-buffers-list` are good and useful, I do not know that `Helm-M-x` will change the returned result of `switch-to-prev-buffer` command from what it normally would do using plain M-x. I now fear any function which involves minibuffer, buffer, and window handling will now be broken when called from helm.

Would love someone smarter than me to explain what is going on and set my expectations for invoking commands using helm.

**Comment by thierryvolpiatto** [comment]
achinhorn <notifications@github.com> writes:

> Actual behavior
>
> Calling switch-to-prev-buffer via helm-M-x oddly managed to
> switch... to the candidates buffer, which didn't exist prior to
> pressing M-x to call the command. (My cursor was placed in the helm
> candidates buffer.) Additionally, I could not get back to teh
> minibuffer.

Can't reproduce.  Please use emacs-helm.sh to reproduce your bugs.

--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
