### ISSUE TITLE
Broken link on the homepage at github.io

### ISSUE THREAD

**Issue by fgeorges** [emacs-helm/helm#2217]
The Helm homepage at https://emacs-helm.github.io/helm/ reads:

> The full configuration I (the helm maintainer) use is [here](https://github.com/thierryvolpiatto/emacs-tv-config/blob/master/init-helm-thierry.el).

But the link is broken.  I guess the correct one is: https://github.com/thierryvolpiatto/emacs-tv-config/blob/master/init-helm.el instead.

**Comment by thierryvolpiatto** [comment]
Think we made the same change nearly at the same time, thanks.
But for some reasons the commit doesn't apply (or maybe I have to clean firefox cache?)
Here the commit https://github.com/emacs-helm/helm/commit/66d50cd8cae731e9f24fe7f13b2ae4621c8f0ea1

**Comment by fgeorges** [comment]
Same here.  I used Insomnia (a REST/HTTP client) to GET the page, and the link is still the old one.  So I'd say it's not the cache.

I am afraid I do not know the GitHub publishing mechanism enough to help here.

**Comment by thierryvolpiatto** [comment]
Finally the changes came in, not sure how... But well it's done.
Thanks, closing now.
