### ISSUE TITLE
Error when running org-refile with non-matching multi match expression

### ISSUE THREAD

**Issue by hperrey** [emacs-helm/helm#2219]
I am using a minimal org file with just two headers. When running org-refile on one of these subtrees, helm offers those two as potential targets. I now enter a non-matching multi match expression (e.g. "asfd") and press space.

## Expected behavior
The list of suggested targets should be empty and further search terms should not produce any output or errors.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
The moment I press space after the first search term, the following error appears in the minibuffer:
`Error running timer: (error "In ‘org-refile’ source: ..........`
This line continues for a long time. Full backtrace can be found below. 
Due to this line being so long (even more so if one has a lot of targets!), switching to the message buffer slows down Emacs significantly.

Using git bisect I could find the commit introducing this behavior a couple of days ago: 070adab3a18def6f9a602cad98ba9197e106606f

Previous ones give the expected behavior.

## Steps to reproduce (recipe)
Start Emacs, create a small org-file with a couple of headers, run org-refile, enter "asdfs" and space.

## Backtraces if any (`M-x toggle-debug-on-error`)
[backtrace](https://gist.github.com/hperrey/f10442f87189145dba21ed839b5208ed)

## Describe versions of Helm, Emacs, operating system, etc.
I ran Emacs 26.3 on OSX 10.15 with a minimal Spacemacs config (latest devel, removing my user config); emacs-helm.sh gave errors about "async" not being found.

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):
no, got a lot of `Error: Cannot open load file: No such file or directory, async`

## Are you using Spacemacs? (yes/no):
yes

Thanks for the continuous development of such a marvelous package! :)

**Comment by thierryvolpiatto** [comment]
Hanno Perrey <notifications@github.com> writes:

> Expected behavior
>
> The list of suggested targets should be empty and further search terms should not produce any output or errors.

Should work as expected now, thanks.

> Are you using emacs-helm.sh to reproduce this bug? (yes/no):
>
> no, got a lot of Error: Cannot open load file: No such file or directory, async

Where is async installed?
What is the value of `package-user-dir`? (It is ~/.emacs.d/elpa on most
emacs installations)

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by hperrey** [comment]
Seems to work fine now, thanks for the quick fix! :D 

I am using spacemacs' devel branch which puts packages in `.emacs.d/elpa/develop` with a folder structure with release date included; async resides in `async-20191030.2138`.

Thanks again for the help!
