### ISSUE TITLE
implement intelligent tab completion

### ISSUE THREAD

**Issue by steckerhalter** [emacs-helm/helm#222]
I'm using helm now for quite a while and I really like it. but one thing bugs me. when I narrow down a list and there are multiple results that can't be much slimmed down by "fuzzy" matching I always need to scroll through the list to get to the right entry.

now the only thing TAB does is to bring up a list with possible commands. I think any other key could do this too. TAB instead should trigger an intelligent completion mechanism.

for example if I know how something **starts** I would like to be able to type some letters of the first word. helm shows me the usual fuzzy matched results. but when I press TAB Helm narrows down the list to the things that start with the letters I entered. or if there is only one occurence, give me the chance to press enter immedately. I think this would make many operations much faster as you could pick the completion that fits the operation.

or maybe there are even better ways to do it?

**Comment by mkeen** [comment]
I don't accept this. Tab completion is the norm in every application I use daily. If I start typing `/dire`, I expect for that to complete to `/directory` when I hit tab. Why wouldn't it? Currently to achieve this behavior in helm I can press the right arrow key. It's very inconvenient.

**Comment by thierryvolpiatto** [comment]
Mike Keen <notifications@github.com> writes:

> I don't accept this. Tab completion is the norm in every application I
> use daily. If I start typing /dire, I expect for that to complete to
> /directory when I hit tab.  Why wouldn't it? Currently to achieve this
> behavior in helm I can press the right arrow key. It's very
> inconvenient.

Please read the helm wiki and the @tudho tutorial (link in README) to
learn what helm is for, what it is doing, and how to use it.

Thanks.

-- 
Thierry

**Comment by lukemaurer** [comment]
Workaround: #1630
