### ISSUE TITLE
Corrupted gud buffer after using helm completion

### ISSUE THREAD

**Issue by aidermoi** [emacs-helm/helm#2220]
## Expected behavior
Before pulling new helm version from Melpa, helm can be used normally for emacs's gdb command completion. For example, cd command can be completed using helm TAB completion.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
After hitting TAB and selecting an option and hitting RET, the *gud* buffer's line is showing:
(gdb) complete file ...
with the command awaiting for completion disappeared, and there was no completion happening.

## Steps to reproduce (recipe)
1. Start up gdb by M-x gdb
2. Type any partial command (cd /home/) and hit TAB.
3. Select the completion (/home/myname) and hit RET.
Now, the partial command disappeared and the command line becomes:
(gdb) complete file /home/myname/home/

## Backtraces if any (`M-x toggle-debug-on-error`)
N/A

## Describe versions of Helm, Emacs, operating system, etc.
I am using Emacs-26.3, gdb-8.2, helm-20191108.726(Melpa). Redhat6.7

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):
yes

## Are you using Spacemacs? (yes/no):
no

**Comment by thierryvolpiatto** [comment]
aidermoi <notifications@github.com> writes:

> Expected behavior
>
> Before pulling new helm version from Melpa, helm can be used normally for emacs's gdb command completion. For example, cd command can be completed using helm TAB completion.
>
> Actual behavior (from emacs-helm.sh if possible, see note at the bottom)
>
> After hitting TAB and selecting an option and hitting RET, the gud buffer's line is showing:
> (gdb) complete file ...
> with the command awaiting for completion disappeared, and there was no completion happening.
>
> Steps to reproduce (recipe)
>
>  1. Start up gdb by M-x gdb
>  2. Type any partial command (cd /home/) and hit TAB.
>  3. Select the completion (/home/myname) and hit RET.
>     Now, the partial command disappeared and the command line becomes:
>     (gdb) complete file /home/myname/home/

Hmm, this looks like an emacs bug as the same is reproductible without
helm-mode, gdb for some reason insert "complete file" which modify start
and end and the completion is inserted at an unexpected place, gdb
should work just as shell-mode works.

Thanks for the recipe.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Seems related to #2165 will see what I can do.
For now you can perhaps disable helm completion in gdb by adding it to `helm-completing-read-handlers-alist`

```elisp
(add-to-list 'helm-completing-read-handlers-alist '(gbd))
```
but unfortunately it is not much better with helm disabled.

**Comment by thierryvolpiatto** [comment]
Definitely an emacs bug, completion is unreliable even in emacs -Q without helm, cursor is jumping at unexpected position at any time during completion.

**Comment by aidermoi** [comment]
My experience with emacs -Q seems normal.
It did jump to the beginning for the buffer couple of times for me, but I don't know how to reproduce it consistently. Otherwise, the completion itself is performing as expected.
The reported issue comes up only after I did my package updates.
The last helm version from Melpa worked normally for me (helm-20191021.625)
The problematic version for me was the version from November.
Not sure what exactly changed between these 2 versions.

**Comment by thierryvolpiatto** [comment]
Here is the problem:
https://debbugs.gnu.org/cgi/bugreport.cgi?bug=18282

and see comment in gud.el:

    ;; FIXME: `gud-gdb-run-command-fetch-lines' has some nasty side-effects on
    ;; the buffer (via `gud-delete-prompt-marker'): it removes the prompt and
    ;; then re-adds it later, thus messing up markers and overlays along the
    ;; way (bug#18282).
    ;; We use an "insert-before" marker for `start', since it's typically right
    ;; after the prompt, which works around the problem, but is a hack (and
    ;; comes with other downsides, e.g. if completion adds text at `start').

**Comment by thierryvolpiatto** [comment]
I added gud-mode to helm-completion-styles-alist to workaround the problem.
