### ISSUE TITLE
helm-completing-read-default-2 seems no refer helm-mode-reverse-history

### ISSUE THREAD

**Issue by elim** [emacs-helm/helm#2223]
## Expected behavior

If the `helm-mode-reverse-history` is non-nil, it should be displayed a history source after a current source.

<https://github.com/emacs-helm/helm/blob/cb0a297bfd20fce9dfe0f16785e5426d386dd7e9/helm-mode.el#L141-L144>

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

It displayed a current source after a history source.

## Steps to reproduce (recipe)

Evaluate this in the neutral environment (by `emacs-helm.sh`).

```elisp
(let*
    ((prompt "")
     (collection (list 'a 'b 'c))
     (predicate nil)
     (require-match nil)
     (initial-input nil)
     (histvar (list 'd 'e 'f))
     (hist 'histvar)
     (def nil)
     (inherit-input-method nil))

  (completing-read prompt collection predicate require-match initial-input hist def inherit-input-method))
```

![image](https://user-images.githubusercontent.com/7157/68633131-0e070200-0534-11ea-8200-c29cd6fc56e5.png)

## Backtraces if any (`M-x toggle-debug-on-error`)

No error happened.

## Describe versions of Helm, Emacs, operating system, etc.

* helm-20191110.1920

* Emacs 26.3

    GNU Emacs 26.3 (build 1, x86_64-apple-darwin19.0.0, NS appkit-1894.00 Version 10.15 (Build 19A602)) of 2019-10-23

* macOS Catalina 10.15.1 (19B88)

    Darwin Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):

yes

## Are you using Spacemacs? (yes/no):

no

* * *

Probably, it `helm-completing-read-default-2` related problem.

The `helm-completing-read-default-2` was introduced at 070adab3a18def6f9a602cad98ba9197e106606f.

And `completing-read` finally uses `helm-completing-read-default-2` instead `helm-completing-read-default-1`.

The `helm-completing-read-default-1` uses `helm-mode-reverse-history` but `helm-completing-read-default-2` is not.

**Comment by thierryvolpiatto** [comment]
Takeru Naito <notifications@github.com> writes:

> Expected behavior
>
> If the helm-mode-reverse-history is non-nil, it should be displayed a history source after a current source.

Added, thanks.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by elim** [comment]
I received version 20191112.634 from the melpa, confirmed it contains 24c74bc modification. It so works very fine!

Thanks!
