### ISSUE TITLE
New Helm: Fish completion

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#2225]
I'd like to move https://gitlab.com/ambrevar/helm-fish-completion to the emacs-helm organization if that's OK.
@thierryvolpiatto ?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I'd like to move https://gitlab.com/ambrevar/helm-fish-completion to the emacs-helm organization if that's OK.
> @thierryvolpiatto ?

No problem, go ahead ;-)

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by Ambrevar** [comment]
Done, thanks!

**Comment by Ambrevar** [comment]
MELPA submission here: https://github.com/melpa/melpa/pull/6544
