### ISSUE TITLE
Make helm-eshell a bit more modular

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#2227]
Helm-eshell has a few functions that are too big and it could help to split them in smaller chunks.  In particular for helm-fish-completion.

In particular, here is what I'd like to have:

- helm-esh-pcomplete: Move `(helm :sources (helm-make-source "Eshell completions" 'helm-esh-source...)` to a defvar or a defun.
- Move the source of the above helm to a variable.
- Move the `:input` value of the above helm to a separate function.
- helm-esh-source: Move the value of `filtered-candidate-transformer` to a separate function.

With the above, I could in particular add `helm-fish-completion`'s source to the above helm, it would fit nicely.

Thoughts?

**Comment by Ambrevar** [comment]
Side question: why does `helm-esh-source` have `nohighlight t`?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Helm-eshell has a few functions that are too big and it could help to split them in smaller chunks. In particular for helm-fish-completion.
>
> In particular, here is what I'd like to have:
>
>   • helm-esh-pcomplete: Move (helm :sources (helm-make-source "Eshell completions" 'helm-esh-source...) to a defvar or a defun.
>   • Move the source of the above helm to a variable.
>   • Move the :input value of the above helm to a separate function.
>   • helm-esh-source: Move the value of filtered-candidate-transformer to a separate function.
>
> With the above, I could in particular add helm-fish-completion's source to the above helm, it would fit nicely.
>
> Thoughts?

Most of helm-eshell will become obsolete once emacs-27 will be released,
so no need to invest too much time in it.

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.*


-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by Ambrevar** [comment]
Out of curiosity, what's new in Emacs 27?

My suggestions take 5 minutes to implement.  If I send a patch, would
you like to merge it?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Out of curiosity, what's new in Emacs 27?

Tab is bound to completion-at-point in emacs-27.

> My suggestions take 5 minutes to implement. If I send a patch, would
> you like to merge it?

Yes if you want, let's see your patch.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by Ambrevar** [comment]
Merged.
