### ISSUE TITLE
Readme.md is broken

### ISSUE THREAD

**Issue by pcr910303** [emacs-helm/helm#2229]
## Expected behavior
Readme should display as formatted text in GitHub.
![image](https://user-images.githubusercontent.com/37990858/68994584-ea431380-08c7-11ea-8438-d3ee21ab142d.png)

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
![image](https://user-images.githubusercontent.com/37990858/68994353-6daf3580-08c5-11ea-9e59-5d7f2da4d5c1.png)

## Steps to reproduce (recipe)
* Navigate to [emacs-helm/helm](https://github.com/emacs-helm/helm)
* view README.md

## Backtraces if any (`M-x toggle-debug-on-error`)
None.

## Describe versions of Helm, Emacs, operating system, etc.
Not applicable.

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):
no

## Are you using Spacemacs? (yes/no):
no

**Comment by thierryvolpiatto** [comment]
Should be fixed now, thanks!
