### ISSUE TITLE
Remove candidates from helm-projects-history

### ISSUE THREAD

**Issue by manuel-uberti** [emacs-helm/helm#2232]
This is not a bug report, but more of a question.

Is there a way to remove a candidate from `helm-projects-history`?

I'm talking about a manual action on a specific candidate, a sort of `helm-buffer-run-kill-persistent`.

Probably an automatic cache invalidation (e.g., a process which will update the history checking if the projects in there still exist) would be better, but just the possibility to remove a project from the history would be enough.

**Comment by thierryvolpiatto** [comment]
Manuel Uberti <notifications@github.com> writes:

> This is not a bug report, but more of a question.
>
> Is there a way to remove a candidate from helm-projects-history?

No, like all the history variables, but if you don't use anymore a
project, it will move slowly at end of stack while you use other
projects, so you should not worry about this.
I personally use bookmarks for my projects, you can set such a bookmark
when visiting its directory with helm-find-files (once in the directory
hit C-x r m).

> I'm talking about a manual action on a specific candidate, a sort of helm-buffer-run-kill-persistent.

Yes, I see. If you really want to emove a project, you can do
(setq helm-projects-history (delete "my_project" helm-projects-history))

> Probably an automatic cache invalidation (e.g., a process which will
> update the history checking if the projects in there still exist)
> would be better,

Yes, I can do that.

> but just the possibility to remove a project from the history is
> enough.


--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by manuel-uberti** [comment]
Fantastic, thank you for the tip! 

I came up with this:
```emacs-lisp
(defun mu-helm-browse-project-history-cleanup ()
  "Remove non-existing projects from `helm-browse-project-history'."
  (interactive)
  (dolist (project helm-browse-project-history)
    (when (not (file-directory-p project))
      (setq helm-browse-project-history (delete project helm-browse-project-history)))))
```
Adding it to `kill-emacs-hook` does the rest.

**Comment by thierryvolpiatto** [comment]
Manuel Uberti <notifications@github.com> writes:

> Fantastic, thank you for the tip!
>
> I came up with this:
>
> (defun mu-helm-browse-project-history-cleanup ()
>   "Remove non-existing projects from `helm-browse-project-history'."
>   (interactive)
>   (dolist (project helm-browse-project-history)
>     (when (not (file-directory-p project))
>       (setq helm-browse-project-history (delete project helm-browse-project-history)))))

Be careful at remote projects, your loop may trigger a remote
connection.
 
> Adding it to kill-emacs-hook does the rest.

Good.

> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.*


-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by manuel-uberti** [comment]
Interesting, thanks. I'll add a check for that too.
