### ISSUE TITLE
Tildes in path break C-x C-f

### ISSUE THREAD

**Issue by japanoise** [emacs-helm/helm#2233]
## Expected behavior

1. In a directory with ~s in it, press `C-x C-f`
2. Helm comes up, I can browse for files

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

Enters an infinite loop, hanging Emacs for a minute or so until it overflows

## Steps to reproduce (recipe)

1. `mkdir -p $HOME/\~test/some/nested/directories`
2. `C-x C-f` and try to navigate into the nested directories
3. cd into `$HOME/\~test/some/nested/directories`
4. touch a file
5. open file with emacsclient
6. `C-x C-f`

## Describe versions of Helm, Emacs, operating system, etc.

Helm latest from MELPA, Emacs 26.3 but also occurs on 25.2.2, under Ubuntu.

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):

No.

## Are you using Spacemacs? (yes/no):

No.

**Comment by thierryvolpiatto** [comment]
chameleon <notifications@github.com> writes:

> Expected behavior
>
>  1. In a directory with ~s in it, press C-x C-f
>  2. Helm comes up, I can browse for files

No AFAIK you can't browse such files in helm, dired, whatever emacs, vim, and
even ls command line from any terminal (even tty's).

See 
https://stackoverflow.com/questions/26126141/path-with-a-folder-named-tilde-cant-be-recognized-by-load-file-in-emacs.

I am not surprized that this crash emacs.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
This is a problem with `substitute-in-file-name`, I committed a fix for this, but well try to avoid using such directory names.
Thanks.

**Comment by japanoise** [comment]
Thanks for quick turnaround and solution.
