### ISSUE TITLE
Helm path completion is broken when using `evil` with `helm-completion-style` set to `helm-fuzzy`

### ISSUE THREAD

**Issue by kiennq** [emacs-helm/helm#2234]
## Expected behavior
Type `:e ~/` and press `tab` should show all file under `~`

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
`[No matches]` is shown.

## Steps to reproduce (recipe)
- Install `evil` package, turn `evil-mode` on
- Customize `helm-completion-style` to `helm-fuzzy`
- Type `:e ~/`, the command is equivalent to `find-files`
- Press `tab`

## Describe versions of Helm, Emacs, operating system, etc.
Helm version: `helm-20191124.640`
Emacs: GNU Emacs 27.0.50 (build 1, i686-w64-mingw32) of 2019-11-12
OS: Windows 10

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):
No

## Are you using Spacemacs? (yes/no):
No

## Notes
In `helm--completion-in-region`, we should probably change
``` elisp
:initial-input
(cond ((and file-comp-p
            (not (string-match "/\\'" input)))
       (concat (helm-mode--completion-in-region-initial-input
                (if (memq helm-completion-style '(helm helm-fuzzy))
                    (helm-basename input)
                  input))
               init-space-suffix))
      ((string-match "/\\'" input) input)
      ((or (null require-match)
           (stringp require-match))
       (helm-mode--completion-in-region-initial-input input))
      (t (concat (helm-mode--completion-in-region-initial-input input)
                 init-space-suffix)))
``` 
to 
``` elisp
:initial-input
(cond ((and file-comp-p
            (not (string-match "/\\'" input)))
       (concat (helm-mode--completion-in-region-initial-input
                (if (memq helm-completion-style '(helm helm-fuzzy))
                    (helm-basename input)
                  input))
               init-space-suffix))
      ((string-match "/\\'" input)
       (unless (memq helm-completion-style '(helm helm-fuzzy))
         input))
      ((or (null require-match)
           (stringp require-match))
       (helm-mode--completion-in-region-initial-input input))
      (t (concat (helm-mode--completion-in-region-initial-input input)
                 init-space-suffix)))
```

**Comment by thierryvolpiatto** [comment]
kiennq <notifications@github.com> writes:

> Expected behavior
>
> Type :e ~/ and press tab should show all file under ~
>
> Actual behavior (from emacs-helm.sh if possible, see note at the bottom)
>
> [No matches] is shown.
>
> Steps to reproduce (recipe)
>
>   • Install evil package, turn evil-mode on

No, please provide a bugreport under emacs-helm.sh, I wont install evil.

>   
>   • Customize helm-completion-style to helm-fuzzy • Type :e ~/, the
>   command is equivalent to find-files • Press tab

This doesn't help, how would you want I fix a bug if I don't know what
is :e?

> Backtraces if any (M-x toggle-debug-on-error)
>
> Describe versions of Helm, Emacs, operating system, etc.
>
> Helm version: helm-20191124.640
> Emacs: GNU Emacs 27.0.50 (build 1, i686-w64-mingw32) of 2019-11-12

If you are using emacs-27, you should try instead

(setq helm-completion-style 'emacs)
(setq completion-styles '(flex))
 
> OS: Windows 10
>
> Are you using emacs-helm.sh to reproduce this bug? (yes/no):
>
> No

If you are on Windows, indeed you can't use shell script unless you have
a bash shell, use instead a minimal configuration.

(require 'helm-config)
(helm-mode 1)

should be enough.

> Notes

> :initial-input
> (cond ((and file-comp-p
>             (not (string-match "/\\'" input)))
>        (concat (helm-mode--completion-in-region-initial-input
>                 (if (memq helm-completion-style '(helm helm-fuzzy))
>                     (helm-basename input)
>                   input))
>                init-space-suffix))
>       ((string-match "/\\'" input)
>        (unless (memq helm-completion-style '(helm helm-fuzzy))
>          input))

Why?


-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by kiennq** [comment]
The problem is initial input is set **twice** for `helm-fuzzy`.
That makes whenever `helm--completion-in-region` run with `~/` with `helm-fuzzy`, it will says that there's no match.
In previous block
```elisp
 (concat (helm-mode--completion-in-region-initial-input
                 (if (memq helm-completion-style '(helm helm-fuzzy))
                     (helm-basename input)
                   input))
                init-space-suffix))
```
The `helm-completion-style` already being checked, why the next block with 
``` elisp
((string-match "/\\'" input)
```
the completion style is not checked?

I indeed can just switch to `emacs` completion style in emacs 27, however I think the `helm-fuzzy` still being supported for now? Especially since emacs 27 is still in preview.

I have other machines that run the stable Emacs 26, and don't want to loose the fuzzy match in helm in that.

**Comment by thierryvolpiatto** [comment]
kiennq <notifications@github.com> writes:

> The problem is initial input is set twice for helm-fuzzy.
> That makes whenever helm--completion-in-region run with ~/ with helm-fuzzy, it will says that there's no match.
> In previous block
>
>  (concat (helm-mode--completion-in-region-initial-input
>                  (if (memq helm-completion-style '(helm helm-fuzzy))
>                      (helm-basename input)
>                    input))
>                 init-space-suffix))
>
> The helm-completion-style already being checked, why the next block with
>
> ((string-match "/\\'" input)
>
> the completion style is not checked?

Make sense, I see also that on version 3.5.0 I made it returning nil.

> I indeed can just switch to emacs completion style in emacs 27,
> however I think the helm-fuzzy still being supported for now?
> Especially since emacs 27 is still in preview.

Yes both helm and helm-fuzzy are still supported.

> I have other machines that run the stable Emacs 26, and don't want to
> loose the fuzzy match in helm in that.

You will see that on emacs-26 a new style called helm-flex appear when
you enable helm-mode, so you can have the same behavior as emacs-27 in
emacs-26 when using helm-completion-style==emacs, just set
completion-styles to '(helm-flex).

> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.*


--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by kiennq** [comment]
I see, so I do have work-around of adding `helm-flex`. Thank you so much for your help

**Comment by thierryvolpiatto** [comment]
kiennq <notifications@github.com> writes:

> I see, so I do have work-around of adding helm-flex.

See https://github.com/thierryvolpiatto/emacs-tv-config/blob/master/init-helm.el#L12

> Thank you so much for your help

You're welcome.

> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.*


-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
