### ISSUE TITLE
Help with writing interactive tests for helm

### ISSUE THREAD

**Issue by codygman** [emacs-helm/helm#2236]
My workflow is heavily dependent upon helm and it's vital for me to ensure certain parts of that workflow work the same across machines. As such, I'm trying to right behavior tests for helm. My best attempt so far as mentioned in DarwinAwardWinner/with-simulated-input#5.

I mention here as well as there both for extra helm-specific help and in case others search the helm issues for this in the future.

`with-simulated-input` let's you do this and it works great:

```elisp
(string-equal "john"
                (with-simulated-input "g RET" (ido-completing-read "Prompt: " '("jane" "john"))))
```

I try doing the equivalent? for helm like this:

```elisp
  (defun email-helm-example ()
    (helm :sources `((name . "Simple helm names example")
                     (candidates . ,(list "jane" "john"))
                     (action . (lambda (candidate) (helm-marked-candidates))))))

  (string-equal "john" (with-simulated-input '((wsi-simulate-idle-time 5 t) "jo" (wsi-simulate-idle-time 5 t) "RET") (car (email-helm-example))))
```

I get what I believe is a with-simulated-input specific error when I do this when run from within emacs, but when run from emacs -batch I also get `Display not ready` which I think is the source of the issue.

Here is a minimal self-contained reproduction of the above:

```
(require 'package)
(setq package-enable-at-startup nil)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
(package-initialize)

;; Bootstrap `use-package'
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(use-package with-simulated-input :ensure t)
(use-package helm :ensure t :config (helm-mode 1))
(require 'with-simulated-input)

(defun email-helm-example ()
  (helm :sources `((name . "Simple helm names example")
                   (candidates . ,(list "jane" "john"))
                   (action . (lambda (candidate) (helm-marked-candidates))))))

(setq helm-exit-idle-delay 0)
(string-equal "john" (with-simulated-input '((wsi-simulate-idle-time 2 t) "jo" (wsi-simulate-idle-time 2 t) "RET") (car (email-helm-example))))
```

Assuming your filename is the same, that can be run with:

```
HOME=/tmp emacs -Q -batch --load /tmp/minimal-repro-helm-simulated-input-testing.el
```

For me this returns:

```
[cody@nixos:~/source/my-emacs-everywhere]$ HOME=/tmp emacs -Q -batch --load /tmp/minimal-repro-helm-simulated-input-testing.el
[Display not ready]

After 0 kbd macro iterations: Reached end of simulated input while evaluating body
```

I expect it to simply return "t" since the resulting string should be "john" rather than an error.

**Comment by codygman** [comment]
A solution was found by @darwinawardwinner:

> I took a wild guess and found the solution: you need to simulate multiple idle times, presumably because one idle timer from Helm is adding another idle timer. The following should work:
> 
> ```emacs-lisp
> (string-equal
>  "john"
>  (with-simulated-input
>      '("jo"
>        (wsi-simulate-idle-time 500)
>        (wsi-simulate-idle-time 500)
>        "RET")
>    (car (helm :sources
> 	      `((name . "Simple helm names example")
> 		(candidates . ,(list "jane" "john"))
> 		(action . (lambda (candidate) (helm-marked-candidates))))))))
> ```
 https://github.com/DarwinAwardWinner/with-simulated-input/issues/5#issuecomment-559237024

They are also looking into how to generally make with-simulated-input work with helm tests. I'll update back here unless they do first so a solution is known and recorded.

**Comment by thierryvolpiatto** [comment]
Cody Goodman <notifications@github.com> writes:

> A solution was found by @DarwinAwardWinner:
>
>     I took a wild guess and found the solution: you need to simulate multiple idle times, presumably because one idle timer from Helm is adding another idle timer.
>     The following should work:
>    
>     (string-equal
>      "john"
>      (with-simulated-input
>          '("jo"
>            (wsi-simulate-idle-time 500)
>            (wsi-simulate-idle-time 500)
>            "RET")
>        (car (helm :sources
>                   `((name . "Simple helm names example")
>                     (candidates . ,(list "jane" "john"))
>                     (action . (lambda (candidate) (helm-marked-candidates))))))))

Please write your sources like this:

(helm :sources (helm-build-sync-source "test"
                 :candidates '(a b c d e))
      :buffer "*helm test*")

Seems that this works as well:

(string-equal
 "john"
 (with-simulated-input
     '("jo"
       (wsi-simulate-idle-time 0.5)
       "RET")
   (completing-read "Prompt: " '("jane" "john"))))
     
NOTE: Have helm-mode enabled to have completing-read helmized.

> DarwinAwardWinner/with-simulated-input#5 (comment)
>
> They are also looking into how to generally make with-simulated-input
> work with helm tests.

Great.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
This without WSI works as well:

```elisp
(string= "john"
         (helm :sources (helm-build-sync-source "test"
                          :candidates '("jane" "john"))
               :execute-action-at-once-if-one t
               :input "jo"
               :buffer "*helm test*"))
```

**Comment by DarwinAwardWinner** [comment]
Actually it turns out my guess was wrong. See this comment for more info: https://github.com/DarwinAwardWinner/with-simulated-input/issues/5#issuecomment-559252025

This behavior is weird, but ultimately not disruptive as long as you don't have a simulated idle time before any simulated input in your test.

**Comment by codygman** [comment]
Thank you @thierryvolpiatto and @DarwinAwardWinner !
