### ISSUE TITLE
helm completion in gdb is broken again.

### ISSUE THREAD

**Issue by aidermoi** [emacs-helm/helm#2237]
## Expected behavior
helm completion in gdb buffer gives a list of completion commands.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
Whenever helm-completion is invoked, Error message "Wrong type argument: listp, helm" appeared.
It was working in a one week earlier version that I've tried.
Previously, I have filed another maybe related issue #2220 

## Steps to reproduce (recipe)
Start up gdb by M-x gdb
Type any partial command (cd /home/) and hit TAB.

## Backtraces if any (`M-x toggle-debug-on-error`)
`Debugger entered--Lisp error: (wrong-type-argument listp helm)
  helm--completion-in-region(#<marker (moves after insertion) at 795 in *gud*> 801 #f(compiled-function (string pred action) #<bytecode 0xcb088d>) nil)
  apply(helm--completion-in-region (#<marker (moves after insertion) at 795 in *gud*> 801 #f(compiled-function (string pred action) #<bytecode 0xcb088d>) nil))
  #f(advice-wrapper :override completion--in-region helm--completion-in-region)(#<marker (moves after insertion) at 795 in *gud*> 801 #f(compiled-function (string pred action) #<bytecode 0xcb088d>) nil)
  completion-in-region(#<marker (moves after insertion) at 795 in *gud*> 801 #f(compiled-function (string pred action) #<bytecode 0xcb088d>) nil)
  completion-at-point()
  funcall-interactively(completion-at-point)
  call-interactively(completion-at-point nil nil)
  command-execute(completion-at-point)`
## Describe versions of Helm, Emacs, operating system, etc.
helm-20191127.455
## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):
yes
## Are you using Spacemacs? (yes/no):
no

**Comment by thierryvolpiatto** [comment]
aidermoi <notifications@github.com> writes:

> Whenever helm-completion is invoked, Error message "Wrong type
> argument: listp, helm" appeared.

Should be fixed now, thanks.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
