### ISSUE TITLE
helm-M-x cannot find specific command

### ISSUE THREAD

**Issue by ccqpein** [emacs-helm/helm#2242]
## Expected behavior
helm should show `slime` when `slime-mode` enable
## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
It doesn't show `slime` command in the commands list
## Steps to reproduce (recipe)
Open any common lisp file, make sure slime-mode enable, type `M-x` and `slime`
## Describe versions of Helm, Emacs, operating system, etc.
helm: helm-20191201.633
emacs: 27.0.50
OS: macOS Cataline
## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):
No
## Are you using Spacemacs? (yes/no):
No

**Comment by ccqpein** [comment]
See also issue: https://github.com/slime/slime/issues/539

**Comment by thierryvolpiatto** [comment]
ccQpein <notifications@github.com> writes:

>
> Open any common lisp file, make sure slime-mode enable, type M-x and slime

Slime is not installed here actually, but it doesn't matter, hlem-M-x
should match anything as long as the symbol exists.  Now helm-M-x is
using completion-styles, and probably they are not configured on your
emacs, only helm is used, so you have to type "slime " instead of
"slime" or enable flex matching:

    (setq completion-styles '(flex)) ; emacs-27
    (setq completion-styles '(helm-flex)) ; emacs-26

See helm documentation about this (pushing to master just now).

--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
I have now installed slime to be sure to reproduce the exact same problem.
Anyway, even without any flex style installed, I can match "slime" without adding any space.
So it is not reproductible here on emacs-26. Will try now on emacs-27.

**Comment by thierryvolpiatto** [comment]
And on emacs-27 helm-M-x shows slime as well, not reproductible.
However, note that slime doesn't load properly as it does on emacs-26.
On emacs-26 after installing slime, and restarting emacs, slime load without the need of any configuration whereas on emacs-27 you have to load it explicitely, perhaps it is the reason why you don't see it? Not the helm fault anyway.

**Comment by ccqpein** [comment]
After restart emacs, I can find `slime` in welcome page too, however, when I go to some lisp files and then the `slime` disappears.

I am compiling emacs and try to reinstall slime and helm to figure out what's the problem.

**Comment by ccqpein** [comment]
I think you are right @thierryvolpiatto , I change my configuration from "assuming slime mode enable auto" to "load it with use-package" and then, I can find `slime` command in `helm-M-x`. 

Thanks a lot. I think you can close this issue.
