### ISSUE TITLE
Skip .. and . in helm-find-files

### ISSUE THREAD

**Issue by grigorievich** [emacs-helm/helm#2244]
When entering a directory with helm-find-files, the selection/point focuses on the first entry, which is the current directory, the second entry being the previous directory. This stands in the way and is inefficient, especially when employing the good old arrows for previous and next source functions. Is there a way to automatically place the selection on the third position of the list?

Tried this

`(defadvice helm-ff-RET (after my/helm-ff-advice-on-RET activate) (helm-next-line 2))`

but it didn't work. Is there some other function to advice?

**Comment by manuel-uberti** [comment]
Not entirely related, but couldn't you just type what you're looking for and let Helm narrow down the candidates for you instead of browsing them with the arrow keys?

 I always start by narrowing down the candidate list the ones closer to what I am looking for, so `.` and `..` are basically avoided anyway.

**Comment by grigorievich** [comment]
@manuel-uberti For some reason I find it easier to manually scroll if I see a seeked file nearby. Maybe a bad habit, but couldn't rid of it so far.

**Comment by thierryvolpiatto** [comment]
grigorievich <notifications@github.com> writes:

> When entering a directory with helm-find-files, the selection/point
> focuses on the first entry, which is the current directory, the second
> entry being the previous directory. This stands in the way and is
> inefficient, especially when employing the good old arrows for
> previous and next source functions. Is there a way to automatically
> place the selection on the third position of the list?

No, and I will not modify this, it have been several times discussed and
I still think we use the correct behavior.
Thanks for your understanding.

--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
