### ISSUE TITLE
Emacs History Commands missing.

### ISSUE THREAD

**Issue by jcs090218** [emacs-helm/helm#2246]
Something wrong on `Dec 9, 2019` commits. Emacs History Commands no longer appear in the window.

**Comment by thierryvolpiatto** [comment]
Still providing bad bug reports, closing.

**Comment by jcs090218** [comment]
It's okay, I guess i will switch to ivy or something else instead. Thanks!

**Comment by thierryvolpiatto** [comment]
Jen-Chieh Shen <notifications@github.com> writes:

> It's okay, I guess i will switch to ivy or something else instead. Thanks!

Great.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
