### ISSUE TITLE
list of buffers in helm switch to buffer window not sorted well

### ISSUE THREAD

**Issue by mmilenko** [emacs-helm/helm#2247]
## Expected behavior
switch-to-buffer or switch-to-buffer-other-window used to bring up a *helm-mode-switch-to-buffer* buffer with the list of buffers sorted in the most recently visited order.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
Now only the first buffer in the list is the most recently visited buffer, the rest are alphabetically sorted, with buffers I don't care about like, `  *Echo Area 0*` and other buffers starting with ` *` at the top.

## Steps to reproduce (recipe)
Call switch-to-buffer or switch-to-buffer-other-window

## Backtraces if any (`M-x toggle-debug-on-error`)
none

## Describe versions of Helm, Emacs, operating system, etc.
helm-20191209.1849, emacs-26.3, Linux

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):
yes

## Are you using Spacemacs? (yes/no):
no

## IMPORTANT NOTE

Helm provides a script named `emacs-helm.sh` which runs Helm in a neutral
environment: no other packages and only minimal settings.

When possible, use it to reproduce your Helm issue to ensure no other package is
interfering.

To run it, simply switch to the directory where Helm is installed and call `./emacs-helm.sh`.
If necessary you can specify emacs executable path on command line with "-P" option.

Thanks.

**Comment by mmilenko** [comment]
Thanks for diagnosing this. I know I'm just one person but this really breaks my flow. Now when I'm switching between several buffers I'm working in, I have to for each switch expend mental effort to remember what the buffer is called and start typing it, instead of just doing C-n a few times.

Helm absolutely rocks btw.

**Comment by mmilenko** [comment]
Oops, hadn't realized that was the fix, I need more coffee. Thanks a bunch!

**Comment by thierryvolpiatto** [comment]
Miodrag Milenkovic <notifications@github.com> writes:

> Oops, hadn't realized that was the fix, I need more coffee. Thanks a bunch!

Sorry didn't make an explicit reply, only a commit.

BTW for managing your buffers consider using helm-buffers-list or helm-mini.

Thanks.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by mmilenko** [comment]
Good tip, thanks.
