### ISSUE TITLE
Helm modify `current-prefix-arg` when calling `completing-read`

### ISSUE THREAD

**Issue by kiennq** [emacs-helm/helm#2250]
## Expected behavior
Helm should not modify `current-prefix-arg`

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
Helm modified `current-prefix-arg` to `nil`

## Steps to reproduce (recipe)
Evaluate this function
``` elisp
(defun test2 ()
  (interactive)
  (completing-read "Chose: " `(a b c) nil t)
  (message "%s - %s" current-prefix-arg helm-current-prefix-arg))
```

with `helm-mode` enabled, run `C-u M-x test2 <Enter> a <Enter>`.

Expectation is that `(4) - (4)` should be printed out.
Actually `nil - nil` is printed.

With `helm-mode` disabled, the issue is not repro'd.

Helm has somehow modified the `current-prefix-arg`.
This behavior broken all the code that interactively reading some thing using `completing-read` and then later using `current-prefix-arg` to do some actions with the inputted value.

## Describe versions of Helm, Emacs, operating system, etc.
helm-20191211.1514
emacs27.0.50 (build 1, i686-w64-mingw32) of 2019-11-12
Windows 10

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):
no

## Are you using Spacemacs? (yes/no):
no

**Comment by thierryvolpiatto** [comment]
kiennq <notifications@github.com> writes:

> Expected behavior
>
> Helm should not modify current-prefix-arg

It doesn't, the behavior is correct, see below.

> Actual behavior (from emacs-helm.sh if possible, see note at the bottom)
>
> Helm modified current-prefix-arg to nil
>
> Steps to reproduce (recipe)
>
> Evaluate this function
>
> (defun test2 ()
>   (interactive)
>   (completing-read "Chose: " `(a b c) nil t)
>   (message "%s - %s" current-prefix-arg helm-current-prefix-arg))
>
> with helm-mode enabled, run C-u M-x test2 <Enter> a <Enter>.
>
> Expectation is that (4) - (4) should be printed out.

No once completing read exit, your prefix arg is consumed.
Try:

(defun test2 ()
  (interactive)
  (message "%s - %s" current-prefix-arg helm-current-prefix-arg)
  (completing-read "Chose: " `(a b c) nil t))

With C-u M-x you should have:

(4) - nil

and with M-x test2 C-u RET RET

(4) - (4)

> Actually nil - nil is printed.

Yes, normal.


-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by kiennq** [comment]
> No once completing read exit, your prefix arg is consumed.

Is it expected that `completing-read` consume `current-prefix-arg`?
With `helm-mode` disabled, the `current-prefix-arg` is not consumed.


> Expectation is that `(4) - (4)` should be printed out.

I'm wrong about this, the expectation should be `(4) - nil` with my test function.

**Comment by thierryvolpiatto** [comment]
kiennq <notifications@github.com> writes:

>     No once completing read exit, your prefix arg is consumed.
>    
> Is it expected that completing-read consume current-prefix-arg?
> With helm-mode disabled, the current-prefix-arg is not consumed.
>
>     Expectation is that (4) - (4) should be printed out.
>    
> I'm wrong about this, the expectation should be (4) - nil with my test function.

Yes, you are right, helm-3.5 is returning "(4) - nil", I found what's
wrong with new helm-M-x, should be fixed soon.

Thanks.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Fixed now. Thanks, closing now.
