### ISSUE TITLE
helm-locate passes string with space to helm-locate-command

### ISSUE THREAD

**Issue by e4z9** [emacs-helm/helm#2252]
As a test set
`(setq helm-locate-fuzzy-match nil)`
`(setq helm-locate-command "echo \\\"%2$s\\\"")`

The output when typing `thequery` in helm-locate is
`"thequery "`
with a space at the end inside the quotes. That space is unexpected and prevents constructing more complex queries for helm-locate-command.

My usecase is mdfind on macOS: The often used command `mdfind -name %2$s` has the disadvantage that -name only matches words within file names. I.e. `mdfind -name locate` does find `helm-locate.el`, but `mdfind -name ocate` does _not_ find `helm-locate.el`.

A solution would be to use `mdfind "kMDItemFSName = '*%2$s*'c"`, but setting this as the helm-locate-command fails because of the space that helm-locate adds within the query string (resulting in `'*ocate *'` instead of `'*ocate*'`).

**Comment by thierryvolpiatto** [comment]
Eike <notifications@github.com> writes:

> As a test set
> (setq helm-locate-fuzzy-match nil)
> (setq helm-locate-command "echo \\\"%2$s\\\"")
>
> The output when typing thequery in helm-locate is
> "thequery "

I have commited a fix, let me know if this is ok for you.
Thanks.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by e4z9** [comment]
Thanks, works!
