### ISSUE TITLE
helm-M-x results are not properly sorted

### ISSUE THREAD

**Issue by nigredo-tori** [emacs-helm/helm#2253]
## Expected behavior

The results that exactly match the pattern should be displayed at the top of the list when doing `helm-M-x`. Looks like this was broken in one of the recent updates.

## Actual behavior

The results don't seem to be sorted in any recognizable way.

## Steps to reproduce (recipe)

0. Start with `emacs-helm.sh`.
1. Do `M-x`.
2. Type in `helm-info`.
3. Observe that the actual `helm-info` command is somewhere in the middle of the list.

## Describe versions of Helm, Emacs, operating system, etc.

- GNU Emacs 27.0.50 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2019-06-05
- Helm-20191217.1347
- Ubuntu 19.04

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):

Yes.

## Are you using Spacemacs? (yes/no):

No.

**Comment by thierryvolpiatto** [comment]
nigredo-tori <notifications@github.com> writes:

>  3. Observe that the actual helm-info command is somewhere in the middle of the list.

I can't reproduce, it is always on top, I tried from emacs-helm.sh from
emacs-27 and emacs-26.3, I tried also with different completion-styles
and helm-info is always on top.

> Describe versions of Helm, Emacs, operating system, etc.
>
>   • GNU Emacs 27.0.50 (build 2, x86_64-pc-linux-gnu, GTK+ Version
>   3.22.30) of 2019-06-05

Perhaps try with emacs-26 or with a fresh emacs-27 yours is from june.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Oh! yes this is it, your emacs-27 doesn't have the adjust-metadata property, so no sort at all is done.
Helm expect either emacs-26 and in this case sorting is done differently, or a recent emacs-27 and in this case a sorting function is used according to what found in metadata.

**Comment by thierryvolpiatto** [comment]
Here the test:
https://github.com/emacs-helm/helm/blob/master/helm-command.el#L213
and here the bit of code missing for you:
https://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/minibuffer.el#n949

**Comment by nigredo-tori** [comment]
Thank you. Turns out I was using a stale Emacs snapshot from before I upgraded my system. The source for it got lost, so the package was not properly upgrading. Reinstalling Emacs via Snap (edge, 27.0.50-5aab1e8) fixed the issue for me.
