### ISSUE TITLE
eieio-class-slots does not exist on Emacs 24.5.1

### ISSUE THREAD

**Issue by lechten** [emacs-helm/helm#2254]
## Expected behavior
Function `helm--create-source` works on Emacs 24.5. (The [homepage lists 24.4 as requirement](https://emacs-helm.github.io/helm/#requirements).)

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
When function `helm--create-source` is used, I get the error message: `Symbol's function definition is void: eieio-class-slots`

This [commit](https://github.com/emacs-helm/helm/commit/85544499ae4653f0abd1a3c0a0e78d084ea65d70) seems to be the culprit.

## Steps to reproduce (recipe)
Start Emacs 24.5.1, try to locate `eieio-class-slots`, which does not exist.

**Comment by thierryvolpiatto** [comment]
Jens Lechtenbörger <notifications@github.com> writes:

> Start Emacs 24.5.1, try to locate eieio-class-slots, which does not exist.

Thanks, I reverted this commit.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by lechten** [comment]
Many thanks for the quick fix!
