### ISSUE TITLE
`helm-M-x` don't use custom fuzzy sort fn when using `helm-fuzzy` completion style.

### ISSUE THREAD

**Issue by cireu** [emacs-helm/helm#2255]
## Expected behavior

Custom sort fn be called
## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

Helm use default sort fn instead
## Steps to reproduce (recipe)

1. `emacs -Q` and load `helm`
2. Eval
```elisp
(setq helm-fuzzy-sort-fn (lambda (&rest args)
                           (prog1 (apply #'helm-generic-sort-fn args)
                             (message "Called!"))))
(setq helm-completion-style 'helm-fuzzy)
```
3. Run `helm-M-x` type some chars to match
## Describe versions of Helm, Emacs, operating system, etc.
OS: Arch Emacs: 27, Helm: https://github.com/emacs-helm/helm/commit/2e5193dd9b7f64cb6c071f16fabc3e5e6f1998a6
## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):

no
## Are you using Spacemacs? (yes/no):

no
## IMPORTANT NOTE

Helm provides a script named `emacs-helm.sh` which runs Helm in a neutral
environment: no other packages and only minimal settings.

When possible, use it to reproduce your Helm issue to ensure no other package is
interfering.

To run it, simply switch to the directory where Helm is installed and call `./emacs-helm.sh`.
If necessary you can specify emacs executable path on command line with "-P" option.

Thanks.

**Comment by thierryvolpiatto** [comment]
Zhu Zihao <notifications@github.com> writes:

> Expected behavior
>
> Custom sort fn be called
>
> Actual behavior (from emacs-helm.sh if possible, see note at the bottom)
>
> Helm use default sort fn instead

Yes, what is expected.

> Steps to reproduce (recipe)
>
>  1. emacs -Q and load helm
>  2. Eval
>
> (setq helm-fuzzy-sort-fn (lambda (&rest args)
>                            (prog1 (apply #'helm-generic-sort-fn args)
>                              (message "Called!"))))

> (setq helm-completion-style 'helm-fuzzy)
>
>  3. Run helm-M-x type some chars to match

helm-M-x doesn't use helm-fuzzy-sort-fn.
Please do M-x C-h m.
 
> OS: Arch Emacs: 27

Please which emacs version?

> , Helm: 2e5193d

Can't find this commit, please update.

> Are you using emacs-helm.sh to reproduce this bug? (yes/no):

Why?

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by cireu** [comment]
> Why?

IIUC `emacs-helm.sh` just a batch file to do things such as "emacs -Q, load async, load-helm, and bind some helm functions" sequentially, right? I prefer to do it manually. So I answer it with no out of respect for the fact.

> Yes, what is expected.

The question is I have a [library](https://github.com/rustify-emacs/fuz.el) which allow user to use extra fuzzy scoring algo for better fuzzy matching result. This plugin use variable `helm-fuzzy-sort-fn` to achieve its goal. But now it doesn't work for `helm-M-x`

I just read the new version of `helm-M-x` implementation and found that it source has `match-dynamic` slot. So the fuzzy match mechanism was delegated to Emacs `completion-style` setting, right?

> Can't find this commit, please update.

Aka current master branch :D

> Please which emacs version?

Precisely, https://github.com/emacs-mirror/emacs/commit/0bc00cda3cb6e765b0e1f0105edf75425bce13c9

**Comment by thierryvolpiatto** [comment]
Zhu Zihao <notifications@github.com> writes:

> I just read the new version of helm-M-x implementation and found that
> it source has match-dynamic slot. So the fuzzy match mechanism was
> delegated to Emacs completion-style setting, right?

Right, see M-x C-h m.

--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Zhu Zihao <notifications@github.com> writes:

>     Why?
>
> IIUC emacs-helm.sh just a batch file to do things such as "emacs -Q,
> load async, load-helm, and bind some helm functions" sequentially,
> right? I prefer to do it manually. So I answer it with no out of
> respect for the fact.

Fair enough, but when you answer no, I assume you are using your full
emacs install.

> The question is I have a library which allow user to use extra fuzzy
> scoring algo for better fuzzy matching result. This plugin use
> variable helm-fuzzy-sort-fn to achieve its goal. But now it doesn't
> work for helm-M-x

Seems you are involved in the development of this library, what you can
do is writing a style called helm-fuz or whatever, see in helm-mode.el
or in minibuffer.el how styles are implemented.

--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
