### ISSUE TITLE
Please stop reporting about helm-M-x before reading documentation

### ISSUE THREAD

**Issue by thierryvolpiatto** [emacs-helm/helm#2256]

**Comment by deusmax** [comment]
Hi Thierry,

Is there any other documentation, you would like us to read, besides these: ?

1. https://emacs-helm.github.io/helm/#configuration
2. https://github.com/emacs-helm/helm/wiki#preconfigured-helm-commands

Just upgraded to helm-20200105.1648 and my helm-M-x stopped working, so I would like to report/open a issue. 
Just briefly here, my helm is misbehaving:
1. the list of commands is not sorted
2. currently with my helm-completion-style is 'helm', will not find the command I'm looking for (ex: gnus, magit-status-here). Need to set helm-completion-style to 'emacs' to find the commands.
3. function helm-call-interactively is not defined. Going into helm-misc.el and running the defun.

**Comment by thierryvolpiatto** [comment]
deusmax <notifications@github.com> writes:

> Hi Thierry,
>
> Is there any other documentation, you would like us to read, besides these: ?

M-x C-h m

>  1. https://emacs-helm.github.io/helm/#configuration
>  2. https://github.com/emacs-helm/helm/wiki#preconfigured-helm-commands
>
> Just upgraded to helm-20200105.1648 and my helm-M-x stopped working, so I would like to report/open a issue.
> Just briefly here, my helm is misbehaving:
>
>  1. the list of commands is not sorted

See https://github.com/emacs-helm/helm/issues/2253

>  2. currently with my helm-completion-style is 'helm', will not find the command I'm looking for (ex: gnus, magit-status-here). Need to set helm-completion-style to
>     'emacs' to find the commands.

Related to 1.

>  
>  3. function helm-call-interactively is not defined. Going into
>  helm-misc.el and running the defun.

My guess:
This happen because you have a bad helm installation, probably old .elc
somewhere or something like that.
helm-call-interactively is used nowhere AFAIK.

--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
With helm-completion-style==helm, maybe there is a problem, please report a bug about this.
Thanks.

**Comment by thierryvolpiatto** [comment]
(2) should be fixed, but be sure to read link in (1) which affect sorting as well.

**Comment by deusmax** [comment]
the helm-call-interactively issue was as customization for helm-type-command-actions.(1st action from an older version). After removing and cleaning up the helm related customizations and updating to helm-20200107.1518,  things seem to work normally.
Except for the candidates list items are not sorted, but that is another issue (#2253).
My helm-completion-style==helm, seems to be behaving. If I see something, I will open an issue.

Thanks Thierry!

**Comment by thierryvolpiatto** [comment]
deusmax <notifications@github.com> writes:

> the helm-call-interactively issue was as customization for helm-type-command-actions.(1st action from an older version). After removing and cleaning up the helm
> related customizations and updating to helm-20200107.1518, things seem to work normally.
> Except for the candidates list items are not sorted, but that is
> another issue (#2253).

Yes, for emacs-27+, you need an up to date version.

> 
> My helm-completion-style==helm, seems to be behaving.

It doesn't, helm-completion-style doesn't affect helm-dynamic-completion
(used by helm-M-x).

> If I see something, I will open an issue.

Thanks.


-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
