### ISSUE TITLE
Disable helm for completion-at-point commands.

### ISSUE THREAD

**Issue by ngleb** [emacs-helm/helm#2257]
## Expected behavior
helm should not replace completion-at-point command. Before there was an option that allowed to disable helm for completion-at-point command. The option was removed and now it is suggested to modify `helm-completing-read-handlers-alist`. I tried using it for `completion-at-point` command but it doesn't work.

Is is possible to replicate the old option `helm-mode-handle-completion-in-region` with `helm-completing-read-handlers-alist`?

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
helm replaces completion-at-point command
## Steps to reproduce (recipe)
execute completion-at-point command and helm completion is shown.
## Describe versions of Helm, Emacs, operating system, etc.
emacs-27 (from git)
## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):
yes, not possible because it disables ledger-mode, which invokoes completion-at-point command (via C-M-i.
## Are you using Spacemacs? (yes/no):
no

**Comment by thierryvolpiatto** [comment]
Gleb Nemshilov <notifications@github.com> writes:

> Expected behavior
>
> helm should not replace completion-at-point command.

Ok, reenabled.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
