### ISSUE TITLE
Directory Completion in *shell* behaves different when starting with a "." (e.g. `cd dir1/` vs `cd ./dir1/`)

### ISSUE THREAD

**Issue by Ket3r** [emacs-helm/helm#2261]
For the bug I expect that the following directories exist:
./dir1/
./dir1/subdir1/
./dir1/subdir2/

## Expected behavior
Helm should show the same completion for using `completion-at-point` (_tab_) after typing:
`cd dir1/`
or
`cd ./dir1/`
in the shell.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
When _tab_ is pressed after typing 
`cd dir1/` 
helm completes to:
`cd dir1/dir1/`
When _tab_ is pressed after typing
`cd ./dir1/`
helm works like expected. It shows subdir1 and subdir2 as completion candidates and inserts the selected one.
When disabling helm `completion-at-point` works like expected for `cd dir1/` and `cd ./dir1/`.

## Steps to reproduce (recipe)
`./emacs-helm.sh`
`M-x shell`
`mkdir test`
`cd test/`
`mkdir dir1`
`mkdir dir1/subdir1`
`mkdir dir1/subdir2`
type `cd` 
press _tab_
shell line looks like this: `cd dir1/`
press _tab_
shell line looks like this: `cd dir1/dir1/`

## Describe versions of Helm, Emacs, operating system, etc.
Windows 10 Microsoft Windows [Version 10.0.17763.914]
Emacs running on WSL version 1 Ubuntu 18.04.3 LTS
Emacs Version: GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu) of 2019-11-20
Helm Packages:
helm-lsp: 20191102.1312
helm: 20191209.1849
helm-core: 20191209.1442
helm-rg: 20190130.1734

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):
yes
## Are you using Spacemacs? (yes/no):
no

**Comment by thierryvolpiatto** [comment]
Ket3r <notifications@github.com> writes:

> For the bug I expect that the following directories exist:
> ./dir1/
> ./dir1/subdir1/
> ./dir1/subdir2/
>
> Expected behavior
>
> Helm should show the same completion for using completion-at-point (tab) after typing:
> cd dir1/
> or
> cd ./dir1/
> in the shell.
>
> Actual behavior (from emacs-helm.sh if possible, see note at the bottom)
>
> When tab is pressed after typing
> cd dir1/
> helm completes to:
> cd dir1/dir1/
> When tab is pressed after typing
> cd ./dir1/
> helm works like expected. It shows subdir1 and subdir2 as completion candidates and inserts the selected one.
> When disabling helm completion-at-point works like expected for cd dir1/ and cd ./dir1/.

Thanks for the recipe, I could reproduce.
Probably something wrong with the helm completion style, however if you
use helm-flex as completion style, this is working as expected.
I can't figure out what's wrong for now, so as a workaround, use the
above style e.g. 

    (setq completion-styles '(helm-fuzzy)) 

or add this to your init file:

    (add-to-list 'helm-completion-styles-alist '(shell-mode . helm))

Thanks.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Also, can't reproduce on my working emacs where bash-completion package is installed.

**Comment by Ket3r** [comment]
Setting the `helm-completion-styles` to either `helm` or `helm-fuzzy` brings the expected behavior. If I set it back to the default value `emacs` the unexpected behavior is back.

For now I added your suggest line 
`(add-to-list 'helm-completion-styles-alist '(shell-mode . helm-fuzzy))`
to my init file so I can keep using helm. 

Thank you :)

**Comment by manuel-uberti** [comment]
I cannot reproduce it either.

![Screenshot from 2020-01-02 17-40-29](https://user-images.githubusercontent.com/8199224/71679087-096a0780-2d87-11ea-90e8-84c6a1268bbe.png)

I am using GNU Emacs 28.0.50 (commit `d36adb544d984b91c70f6194da01344e4b2b6fc9`), with `helm-completion-style` set to `emacs`.

**Comment by thierryvolpiatto** [comment]
Manuel Uberti <notifications@github.com> writes:

> I cannot reproduce it either.
>
> Screensh
>
> I am using GNU Emacs 28.0.50 (commit d36adb544d984b91c70f6194da01344e4b2b6fc9), with helm-completion-style set to emacs.

Perhaps you are using flex in completion-styles?
helm completion style is working perfectly when used with flex (or helm-flex for
emacs-26 users) but fails when used alone (try to set completion-styles
to nil).
When using bash-completion package, completion in shell-mode is working
fine with any style.
Eshell suffer from the same problem.

I added eshell-mode and shell-mode to helm-completion-styles-alist
waiting a better fix.
If you want to use completion-styles in these two modes, remove their
entries in helm-completion-styles-alist and use flex or helm-flex as
completion-styles, see my configuration here:
https://github.com/thierryvolpiatto/emacs-tv-config/blob/master/init-helm.el#L12


> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.*


-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by manuel-uberti** [comment]
Awesome, thank you.

**Comment by Ket3r** [comment]
How do I switch to `helm-flex`? Switching to the `helm-flex` completion style is not possible for me in emacs26. It shows me the following options in the picture.

![image](https://user-images.githubusercontent.com/50021447/71720427-feb08080-2e21-11ea-8f9c-a0036200dc8c.png)

However the the variable `completion-styles-alist` that specifies the available styles for `completion-styles` is this list that contains `helm-flex`:
`((helm-flex helm-flex-completion-try-completion helm-flex-completion-all-completions "helm flex completion style.
Provide flex matching for emacs-26.") (helm helm-completion-try-completion helm-completion-all-completions "helm multi completion style.") (emacs21 completion-emacs21-try-completion completion-emacs21-all-completions "Simple prefix-based completion.
I.e. when completing \"foo_bar\" (where _ is the position of point),
it will consider all completions candidates matching the glob
pattern \"foobar*\".") (emacs22 completion-emacs22-try-completion completion-emacs22-all-completions "Prefix completion that only operates on the text before point.
I.e. when completing \"foo_bar\" (where _ is the position of point),
it will consider all completions candidates matching the glob
pattern \"foo*\" and will add back \"bar\" to the end of it.") (basic completion-basic-try-completion completion-basic-all-completions "Completion of the prefix before point and the suffix after point.
I.e. when completing \"foo_bar\" (where _ is the position of point),
it will consider all completions candidates matching the glob
pattern \"foo*bar*\".") (partial-completion completion-pcm-try-completion completion-pcm-all-completions "Completion of multiple words, each one taken as a prefix.
I.e. when completing \"l-co_h\" (where _ is the position of point),
it will consider all completions candidates matching the glob
pattern \"l*-co*h*\".
Furthermore, for completions that are done step by step in subfields,
the method is applied to all the preceding fields that do not yet match.
E.g. C-x C-f /u/mo/s TAB could complete to /usr/monnier/src.
Additionally the user can use the char \"*\" as a glob pattern.") (substring completion-substring-try-completion completion-substring-all-completions "Completion of the string taken as a substring.
I.e. when completing \"foo_bar\" (where _ is the position of point),
it will consider all completions candidates matching the glob
pattern \"*foo*bar*\".") (initials completion-initials-try-completion completion-initials-all-completions "Completion of acronyms and initialisms.
E.g. can complete M-x lch to list-command-history
and C-x C-f ~/sew to ~/src/emacs/work."))` 

Why does it not show the option to set `completion-styles` to `helm-flex` can this be an emacs issue or is this helm related?

**Comment by thierryvolpiatto** [comment]
Because `completion-styles` value is evaluated in minibuffer.el after `completion-styles-alist` which is a `defconst`.  Probably the situation will be better when emacs-27 will be released, for now we have to do with that.  See in Helm the documentation of  `completion-styles` which try to clarify this.

BTW the bug should be now fixed in fix_#2261 branch, I will merge after testing in other things than shell, at least is is working fine now with shell and eshell in emacs-28.

**Comment by thierryvolpiatto** [comment]
Should be fixed now.

**Comment by Ket3r** [comment]
Yes I can confirm. Updated my helm package to 20200107.1518 and now completion works as expected.

Thank you :)
