### ISSUE TITLE
Performance issues with ggtags-mode

### ISSUE THREAD

**Issue by valschneider** [emacs-helm/helm#2262]
Hi,

I have `ggtags-mode` and `helm-mode` enabled for C files and it's really handy, especially considering I have to wade through the Linux kernel. One thing I do quite often is to call

```
ggtags-find-tag-dwim (M-.)
```

on an empty line, then start typing stuff (e.g. `M-.` `kzalloc` to look for kzalloc related stuff). Populating the candidates list is nigh instantaneous on my home setup, and takes over 10 seconds on my workstation.

## Expected behavior

My home setup has an older version of helm which doesn't seem to suffer from performance issues. Profiling a quick search of `kzalloc` gives me:

```
 - helm-internal                                          825  73%
 - helm-read-pattern-maybe                               506  45%
  + read-from-minibuffer                                 440  39%
  - helm-update                                           54   4%
   - helm--collect-matches                                39   3%
    + helm-compute-matches                                39   3%
```

## Actual behavior

Doing the same on my workstation, I can type stuff alright, but the helm candidates list remains empty and if I hit enter it just closes (I would get [Display not ready] in the minibuffer on helm 3.3). I do get some results eventually but that's after > 10s. Profiling the same request gave me this:

```
 - helm-compute-matches                       14314  87%                                                                                                                                                     
 - helm-match-from-candidates                 9447  58%                                                                                                                                                     
  + helm-mm-match                             2500  15%                                                                                                                                                     
    helm-set-case-fold-search                    4   0%                                                                                                                                                     
 - helm-get-cached-candidates                 3390  20%                                                                                                                                                     
  + helm-get-candidates                       3390  20%                                                                                                                                                     
 + helm-process-filtered-candidate-transformer                 60   0%
```

Completely enudecated guess here: It feels like instead of interrupting the search when I'm inserting more characters, every prefix of the search ends up being searched ("k", "kz", "kza"...).

## Steps to reproduce (recipe)

Open a C file in a big project (e.g. Linux)
Enable ggtags-mode
Enable helm-mode
Type `M-. kzalloc`
Wait a few seconds for the results to appear

I've tried this out on a completely stripped down Emacs, just had to run this in org-mode:
```
#+BEGIN_SRC elisp
(require 'package)
(let* ((no-ssl (and (memq system-type '(windows-nt ms-dos))
                    (not (gnutls-available-p))))
       (proto (if no-ssl "http" "https")))
  (when no-ssl
    (warn "\
Your version of Emacs does not support SSL connections,
which is unsafe because it allows man-in-the-middle attacks.
There are two things you can do about this warning:
1. Install an Emacs version that does support SSL and be safe.
2. Remove this warning from your init file so you won't see it again."))
  ;; Comment/uncomment these two lines to enable/disable MELPA and MELPA Stable as desired
  (add-to-list 'package-archives (cons "melpa" (concat proto "://melpa.org/packages/")) t)
  ;;(add-to-list 'package-archives (cons "melpa-stable" (concat proto "://stable.melpa.org/packages/")) t)
  (when (< emacs-major-version 24)
    ;; For important compatibility libraries like cl-lib
    (add-to-list 'package-archives (cons "gnu" (concat proto "://elpa.gnu.org/packages/")))))
(package-initialize)
#+END_SRC
```
Installed ggtags (), helm (), and reproduced the same perf hit.

## Describe versions of Helm, Emacs, operating system, etc.

Issue reproduced with helm 3.6.0, emacs 26.2, Ubuntu 16.04.

Issue not present on helm 2.9.6, emacs 25.2.2, Ubuntu 18.04

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):
No

## Are you using Spacemacs? (yes/no):
No

**Comment by thierryvolpiatto** [comment]
Valentin Schneider <notifications@github.com> writes:

> Steps to reproduce (recipe)
>
> Open a C file in a big project (e.g. Linux)
> Enable ggtags-mode
> Enable helm-mode
> Type M-. kzalloc
> Wait a few seconds for the results to appear

To what M-. is bound?

You have to found what you are calling and bound it to another handler
in helm-completing-read-handlers-alist. 

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by valschneider** [comment]
> Valentin Schneider <notifications@github.com> writes:
> Steps to reproduce (recipe) Open a C file in a big project (e.g. Linux) Enable ggtags-mode Enable helm-mode Type M-. kzalloc Wait a few seconds for the results to appear
> To what M-. is bound? You have to found what you are calling and bound it to another handler in helm-completing-read-handlers-alist.

That would be the default binding for `ggtags-find-tag-dwim`. I'll give your suggestion a shot.

**Comment by thierryvolpiatto** [comment]
Ok, try to bind it to `helm-completing-read-default-find-tag` or `helm-completing-read-inbuffer-default-handler`.
If it have no effect we will have to find the toplevel function called in `ggtags-find-tag-dwim` and use it in 
`helm-completing-read-handlers-alist` instead of `ggtags-find-tag-dwim`, let me know.
What you can do also is use a specialized helm package for global and bind `M-.` to its command, see
https://github.com/syohex/emacs-helm-gtags

**Comment by valschneider** [comment]
> Ok, try to bind it to `helm-completing-read-default-find-tag` or `helm-completing-read-inbuffer-default-handler`.
> If it have no effect we will have to find the toplevel function called in `ggtags-find-tag-dwim` and use it in
> `helm-completing-read-handlers-alist` instead of `ggtags-find-tag-dwim`, let me know.
> What you can do also is use a specialized helm package for global and bind `M-.` to its command, see
> https://github.com/syohex/emacs-helm-gtags

**Comment by valschneider** [comment]
Hm so `ggtags-find-tag-dwim` isn't what I would call a simple function, but digging through the thing I ended up in `ggtags-read-tag` which seems to be what is being called in my use case. Looking into it, it seems to be calling a simple `completing-read`, which is already taken care of by helm.

The plot thickens a bit; I went and tried this out on another workstation I have at hand and the issue isn't there actually:

architecture: arm64 (previous workstation was x86)
distro: Ubuntu 19.04
helm: 3.6.0 (so same as other one)
emacs: 26.3 (.1 higher than the other one)

And, while trying out random stuff on my x86 workstation (the one with the issue), it turns out that hitting the spacebar immediately updates the candidates list. So for instance I can invoke `ggtags-find-tag-dwim`, enter `sched_domain` and wait for a good while,  but if I type `sched_domain ` instead the results are here immediately. I would have put the blame on `helm-input-idle-delay`, but it seems I have the default value of 0.01.

**Comment by thierryvolpiatto** [comment]
Valentin Schneider <notifications@github.com> writes:

> Hm so ggtags-find-tag-dwim isn't what I would call a simple function, but digging through the thing I ended up in ggtags-read-tag which seems to be what is being
> called in my use case. Looking into it, it seems to be calling a simple completing-read, which is already taken care of by helm.
>
> The plot thickens a bit; I went and tried this out on another workstation I have at hand and the issue isn't there actually:
>
> architecture: arm64 (previous workstation was x86)
> distro: Ubuntu 19.04
> helm: 3.6.0 (so same as other one)
> emacs: 26.3 (.1 higher than the other one)
>
> And, while trying out random stuff on my x86 workstation (the one with
> the issue), it turns out that hitting the spacebar immediately updates
> the candidates list. So for instance I can invoke
> ggtags-find-tag-dwim, enter sched_domain and wait for a good while,
> but if I type sched_domain instead the results are here immediately. I
> would have put the blame on helm-input-idle-delay, but it seems I have
> the default value of 0.01.

Not sure to understand what you are doing here.

Did you try

    (add-to-list 'helm-completing-read-handlers-alist '(ggtags-read-tag . helm-completing-read-default-find-tag))

or
    
    (add-to-list 'helm-completing-read-handlers-alist '(ggtags-read-tag . helm-completing-read-inbuffer-default-handler))


--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
So no, I tried on emacs/src with alloc.c buffer current and the one you have to bind is `ggtags-find-tag-dwim`:

`(add-to-list 'helm-completing-read-handlers-alist '(ggtags-find-tag-dwim . helm-completing-read-default-find-tag))`

is working fine and also

`(add-to-list 'helm-completing-read-handlers-alist '(ggtags-find-tag-dwim . helm-completing-read-inbuffer-default-handler))`

**Comment by thierryvolpiatto** [comment]
Let me know the one you use I will add it by default to helm.

Thanks.

**Comment by valschneider** [comment]
> So no, I tried on emacs/src with alloc.c buffer current and the one you have to bind is `ggtags-find-tag-dwim`:
> 
> `(add-to-list 'helm-completing-read-handlers-alist '(ggtags-find-tag-dwim . helm-completing-read-default-find-tag))`
> 
> is working fine and also
> 
> `(add-to-list 'helm-completing-read-handlers-alist '(ggtags-find-tag-dwim . helm-completing-read-inbuffer-default-handler))`

Yes indeed! Didn't see much of a difference with `ggtags-read-tag`, but it is indeed much better with `ggtags-find-tag-dwim`! Both behave fine, I didn't see any obvious "winner". Thanks a ton for giving it a shot!

**Comment by thierryvolpiatto** [comment]
Valentin Schneider <notifications@github.com> writes:

> Yes indeed! Didn't see much of a difference with ggtags-read-tag, but
> it is indeed much better with ggtags-find-tag-dwim! Both behave fine,
> I didn't see any obvious "winner". Thanks a ton for giving it a shot!

Great! I added it as default to `helm-completing-read-handlers-alist`.

Thanks.

--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
