### ISSUE TITLE
helm-org-in-buffer-headings shows incomplete result

### ISSUE THREAD

**Issue by introom** [emacs-helm/helm#2264]
For a give file example.org, http://dpaste.com/1VPQZGR

Typing orange only shows the following entries, with those under apple missing.

![image](https://user-images.githubusercontent.com/669045/72358420-83a37000-3727-11ea-9208-b9586122b914.png)

**Comment by thierryvolpiatto** [comment]
Shiyao.Ma <notifications@github.com> writes:

> For a give file example.org, http://dpaste.com/1VPQZGR
>
> Typing orange only shows the following entries, with those under apple missing.

Hmm, of course the other entries o1, o2 etc.. doesn't match "orange",
what do you expect?

> image   
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.*


-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by introom** [comment]
I expect the output be:
orange
orange/o1
orange/o2
apple/orange
apple/orange/o1
apple/orange/o2

those from apple are missing.

**Comment by thierryvolpiatto** [comment]
Shiyao.Ma <notifications@github.com> writes:

> I expect the output be:
> orange
> orange/o1
> orange/o2
> apple/orange
> apple/orange/o1
> apple/orange/o2
>
> those from apple are missing.

Hmm, can't guess you are using `helm-org-format-outline-path`...
It is a bug in helm-mode, it should be fixed now by 1ecefa38.

Please send bugreport about helm-org to helm-org, not here.

Thanks.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by introom** [comment]
confirm fixed. thanks.
