### ISSUE TITLE
when i using helm-multi-occur-1 function, helm will create a lot of same buffer.

### ISSUE THREAD

**Issue by doneself** [emacs-helm/helm#2266]
when i using helm-multi-occur-1 function, helm will create a lot of same buffer.

If some org-mode buffers contain chinese chars, I use helm-multi-occur-1 function ,helm will create some annoy buffers.
like this：

```
 *helm candidates:HO [新增数据库记录.org]*新增数据库记录.org
 *helm candidates:HO [新增数据库记录.org]*新增数据库记录.org
 *helm candidates:HO [新增数据库记录.org]*新增数据库记录.org
 *helm candidates:HO [新增数据库记录.org]*新增数据库记录.org
 *helm candidates:HO [新增数据库记录.org]*新增数据库记录.org
```

**Comment by manuel-uberti** [comment]
Could you provide a minimal recipe to reproduce the issue, preferably starting from `emacs-helm.sh` if you can, or at least from `emacs -Q`?

**Comment by doneself** [comment]
> Could you provide a minimal recipe to reproduce the issue, preferably starting from `emacs-helm.sh` if you can, or at least from `emacs -Q`?

I copy someone the code:
```
(defun helm-search-text-in-all-buffers()
  (interactive)
  (require 'cl)
  (require 'helm-occur)
  (unless (region-active-p)
	(helm-multi-occur-1 (cl-delete-if (lambda (buffer) (find (aref (buffer-name buffer) 0) " *")) (buffer-list))))
  (when (region-active-p)
	(helm-multi-occur-1
	 (cl-delete-if (lambda (buffer) (find (aref (buffer-name buffer) 0) " *")) (buffer-list))
	 (buffer-substring-no-properties (region-beginning) (region-end)))))
```

**Comment by doneself** [comment]
> > Could you provide a minimal recipe to reproduce the issue, preferably starting from `emacs-helm.sh` if you can, or at least from `emacs -Q`?
> 
> sorry，I don't know much about elisp and emacs ，i only use org to take notes。

This is my first time to use this function.

**Comment by doneself** [comment]
> Could you provide a minimal recipe to reproduce the issue, preferably starting from `emacs-helm.sh` if you can, or at least from `emacs -Q`?
my buffer list

```
EntityHelper.cs
SiteEntity.cs
MrCMSAppRegistrationContext.cs
my-package-setting.el
*Help*
*Messages*
20200117_1106_新增数据库记录_抵押类等类别ftp和相对路径.org
1145_My_Emacs_pyim_setting.el
笔记字典.txt
mulu.txt
1700_test_org.org
 *helm candidates:HO [20200117_1106_新增数据库记录_抵押类等类别ftp和相对路径.org]*20200117_1106_新增数据库记录_抵押类等类别ftp和相对路径.org
 *helm candidates:HO [1145_My_Emacs_pyim_setting.el]*20200117_1106_新增数据库记录_抵押类等类别ftp和相对路径.org
 *helm candidates:HO [MrCMSAppRegistrationContext.cs]*20200117_1106_新增数据库记录_抵押类等类别ftp和相对路径.org
 *helm candidates:HO [EntityHelper.cs]*20200117_1106_新增数据库记录_抵押类等类别ftp和相对路径.org
 *helm candidates:HO [SiteEntity.cs]*20200117_1106_新增数据库记录_抵押类等类别ftp和相对路径.org
 *helm candidates:HO [笔记字典.txt]*20200117_1106_新增数据库记录_抵押类等类别ftp和相对路径.org
 *helm candidates:HO [mulu.txt]*20200117_1106_新增数据库记录_抵押类等类别ftp和相对路径.org
 *helm candidates:HO [1700_test_org.org]*20200117_1106_新增数据库记录_抵押类等类别ftp和相对路径.org
 *helm candidates:HO [20200121]*20200117_1106_新增数据库记录_抵押类等类别ftp和相对路径.org
 *helm candidates:HO [20200117_1106_新增数据库记录_抵押类等类别ftp和相对路径.org]**Youdao Dictionary*
*scratch*
*Youdao Dictionary*
```

**Comment by manuel-uberti** [comment]
What Emacs version are you using? How did you install Helm? How did you activate it? Could you share how you set it up in your Emacs configuration?

**Comment by manuel-uberti** [comment]
There is an issue template you should fill out to give the maintainer relevant information about your system and the bug you are experiencing.

**Comment by doneself** [comment]
> There is an issue template you should fill out to give the maintainer relevant information about your system and the bug you are experiencing.

I'm using windows 10 and emacs 26.3. I will try  only install helm in my emacs to see if it is my configuration problem,later.

**Comment by thierryvolpiatto** [comment]
doneself <notifications@github.com> writes:

> when i using helm-multi-occur-1 function, helm will create a lot of same buffer.
>
> If some org-mode buffers contain chinese chars, I use helm-multi-occur-1 function ,helm will create some annoy buffers.
> like this：
>
>  *helm candidates:HO [新增数据库记录.org]*新增数据库记录.org
>  *helm candidates:HO [新增数据库记录.org]*新增数据库记录.org
>  *helm candidates:HO [新增数据库记录.org]*新增数据库记录.org
>  *helm candidates:HO [新增数据库记录.org]*新增数据库记录.org
>  *helm candidates:HO [新增数据库记录.org]*新增数据库记录.org

It seems you are calling helm-occur from the same buffer 
i.e. "新增数据库记录.org", so I don't see why you have duplicated
buffers. Why are you using `helm-multi-occur-1` specially if you have no
elisp knowledge?

The only case where we have several buffers for same search is when you
are calling helm-occur from different places (I just commited a fix to
avoid this).

Here a recipe:

1) Create a buffer "新增数据库记录.org"
2) Add some headings e.g. "* foo" etc...
3) Switch to *scratch* buffer
4) M-x helm-mini
5) C-s on buffer "新增数据库记录.org" and type foo
6) C-g M-x helm-mini C-c a C-]

You should see only one buffer
" *helm candidates:HO [新增数据库记录.org]*"

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
