### ISSUE TITLE
How can i hide the buffer in helm buffer list?

### ISSUE THREAD

**Issue by doneself** [emacs-helm/helm#2268]
hello,i only install helm in eamcs yesterday,and i can not hide the *helm candidates:HO buffer. i use helm-boring-buffer-regexp-list,but it seen not work.

```
(setq helm-boring-buffer-regexp-list
      (append helm-boring-buffer-regexp-list
	      (list (rx "*everything")
		    (rx "*Ibuffer")
		    (rx "*GNU Emacs")
			(rx "*helm")
		    )))
```

my buffer list
```
ArchiveService.cs
MidController.cs
20200120_0852_住房证明数据分页打印.org
*Messages*
 *helm candidates:HO [20200117_1106_新增数据库记录_抵押类等类别ftp和相对路径.org]*
 *helm candidates:HO [本周工作报告01-19~01-23.txt]*
 *helm candidates:HO [sjk数据库地址备忘.org]*
 *helm candidates:HO [按类别归档leibie]*
20200117_1106_新增数据库记录_抵押类等类别ftp和相对路径.org
Documents
```

**Comment by thierryvolpiatto** [comment]
doneself <notifications@github.com> writes:

> hello,i only install helm in eamcs yesterday,and i can not hide the
> *helm candidates:HO buffer.

Use M-x helm-buffers-list or M-x helm-mini and not C-x b aka M-x switch-to-buffer.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by doneself** [comment]
> doneself <notifications@github.com> writes:
> hello,i only install helm in eamcs yesterday,and i can not hide the *helm candidates:HO buffer.
> Use M-x helm-buffers-list or M-x helm-mini and not C-x b aka M-x switch-to-buffer.
> […](#)
> -- Thierry Get my Gnupg key: gpg --keyserver pgp.mit.edu --recv-keys 59F29997

I tried "helm-mini".It can hide some buffer like "*helm M-x*","*helm-mini*" etc.
But can not hide ` *helm candidates:HO [sjk数据库地址备忘.org]*` buffer. Buffer name start with a whitespace.

**Comment by thierryvolpiatto** [comment]
doneself <notifications@github.com> writes:

>     doneself notifications@github.com writes:
>     hello,i only install helm in eamcs yesterday,and i can not hide the *helm candidates:HO buffer.
>     Use M-x helm-buffers-list or M-x helm-mini and not C-x b aka M-x switch-to-buffer.
>     …
>     -- Thierry Get my Gnupg key: gpg --keyserver pgp.mit.edu --recv-keys 59F29997
>    
> I tried "helm-mini".It can hide some buffer like "helm M-x","helm-mini" etc.
> But can not hide *helm candidates:HO [sjk数据库地址备忘.org]* buffer. Buffer name start with a whitespace.

Could reproduce, for some reasons the regexp "\\<\\>" matches
" *helm candidates:HO [sjk数据库地址备忘.org]*" but not e.g. 
" *helm candidates:HO [helm-mode.el]*".
Using "\\`\\'" fixes the issue.

Should be fixed now.

Thanks.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by doneself** [comment]
> doneself <notifications@github.com> writes:
> doneself ***@***.*** writes: hello,i only install helm in eamcs yesterday,and i can not hide the *helm candidates:HO buffer. Use M-x helm-buffers-list or M-x helm-mini and not C-x b aka M-x switch-to-buffer. … -- Thierry Get my Gnupg key: gpg --keyserver pgp.mit.edu --recv-keys 59F29997 I tried "helm-mini".It can hide some buffer like "helm M-x","helm-mini" etc. But can not hide *helm candidates:HO [sjk数据库地址备忘.org]* buffer. Buffer name start with a whitespace.
> Could reproduce, for some reasons the regexp "\\<\\>" matches " *helm candidates:HO [sjk数据库地址备忘.org]*" but not e.g. " *helm candidates:HO [helm-mode.el]*". Using "\\`\\'" fixes the issue. Should be fixed now. Thanks.
> […](#)
> -- Thierry Get my Gnupg key: gpg --keyserver pgp.mit.edu --recv-keys 59F29997

It mean set the helm-boring-buffer-regexp-list value like this?
```
(setq helm-boring-buffer-regexp-list '("\\` " "\\`\\*helm" "\\`\\*Echo Area" "\\`\\*Minibuf" "\\`\\'"))
```
