### ISSUE TITLE
Emacs gets minimized if Helm is used in a posframe

### ISSUE THREAD

**Issue by snyball** [emacs-helm/helm#2269]
## Expected behavior
The helm window should close, and focus should return to the main Emacs window.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
The main Emacs window becomes minimized.

## Steps to reproduce (recipe)
https://github.com/tumashu/posframe/tree/bb1393383d512d7358549c99f95b45e7d56d7d2c
https://github.com/tumashu/helm-posframe

Further information in this Doom-emacs bug report: https://github.com/hlissner/doom-emacs/issues/2397

1. Set up Helm to start up in a posframe/childframe
2. Fire up a Helm posframe (M-x for example)
3. Either select something, or abort the Helm session
4. When the helm posframe window disappears, the main Emacs window gets minimized.

The closest I've been able to narrow this down, is that it happens after `(abort-recursive-edit)` runs.

I'm posting this here as I've tried using previous versions of both `posframe` and Emacs, which means the bug _might_ have been introduced in Helm itself (and I'm unfortunately at my wits end with this.)

## Backtraces if any (`M-x toggle-debug-on-error`)
Not applicable.

## Describe versions of Helm, Emacs, operating system, etc.

I've reproduced this bug on Ubuntu 19.04, Ubuntu 18.04, with Emacs 26.3 and Emacs 27/28 (from git.)

Using the latest version of Helm from MELPA as of 2020-01-22.

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):
No, not applicable.

## Are you using Spacemacs? (yes/no):
No.

**Comment by snyball** [comment]
Closing this as I've verified that rolling back Helm does not resolve the issue.

**Comment by thierryvolpiatto** [comment]
Sorry but I will not fix this, looks like a problem with posframe, helm provides a convenient way for using frames why not using this instead?

**Comment by snyball** [comment]
@thierryvolpiatto Yeah, which is why I've clearly closed it.

It's been resolved anyway: https://github.com/hlissner/doom-emacs/issues/2397
