### ISSUE TITLE
Helm savehist-mode "Wrong type argument: listp, t" error

### ISSUE THREAD

**Issue by kadircancetin** [emacs-helm/helm#2273]
## Expected behavior
Save helm-M-x-input-history and other history vars to 'history' and kill emacs.

## Actual behavior
Can't kill the emacs and raise `savehist-autosave: Wrong type argument: listp, t`

## Steps to reproduce (recipe)
1) Clean emacs, just this init.el
```
(require 'package)
(let* ((no-ssl (and (memq system-type '(windows-nt ms-dos))
                    (not (gnutls-available-p))))
       (proto (if no-ssl "http" "https")))
  (add-to-list 'package-archives (cons "melpa" (concat proto "://melpa.org/packages/")) t)
  (when (< emacs-major-version 24)
    (add-to-list 'package-archives (cons "gnu" (concat proto "://elpa.gnu.org/packages/")))))
(package-initialize)
(add-to-list 'package-archives
             '("melpa-stable" . "https://stable.melpa.org/packages/") t)



(unless (package-installed-p 'helm)
  (package-refresh-contents)
  (package-install 'helm))



(savehist-mode 1)
(global-set-key (kbd "M-x") 'helm-M-x)
(require 'helm-config)
(setq   helm-M-x-always-save-history          t
	helm-echo-input-in-header-line        t
	helm-M-x-input-history                t
	helm-display-function                 'pop-to-buffer)



```
2) M-x and create some history.
3) Close emacs. (C-x C-c)

## Backtraces if any (`M-x toggle-debug-on-error`)
```
Debugger entered--Lisp error: (wrong-type-argument listp t)
  savehist-save(t)
  savehist-autosave()
  kill-emacs()
  save-buffers-kill-emacs(nil)
  save-buffers-kill-terminal(nil)
  funcall-interactively(save-buffers-kill-terminal nil)
  call-interactively(save-buffers-kill-terminal nil nil)
  command-execute(save-buffers-kill-terminal)

```
## Describe versions of Helm, Emacs, operating system, etc.
emacs: 26.3 and 27.0.5
OS: linux, archlinux
helm: helm-20200124.1937

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):
no

## Are you using Spacemacs? (yes/no):
no

**Comment by thierryvolpiatto** [comment]
Kadir Can Çetin <notifications@github.com> writes:

> Expected behavior
>
> Save helm-M-x-input-history and other history vars to 'history' and kill emacs.
>
> Actual behavior
>
> Can't kill the emacs and raise savehist-autosave: Wrong type argument: listp, t

Of course, you set helm-M-x-input-history to t in your config!!!
Never touch the history variables!

> (setq  
>  helm-M-x-always-save-history          t
>  helm-echo-input-in-header-line        t
>  helm-M-x-input-history                t

NO.

>  helm-display-function                 'pop-to-buffer

Unrelated but NO also.

>  )
>
>  2. M-x and create some history.
>  3. Close emacs. (C-x C-c)
>
> Backtraces if any (M-x toggle-debug-on-error)
>
> Debugger entered--Lisp error: (wrong-type-argument listp t)

Of course.


-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
So there is no bug here, just a wrong configuration, could be avoided using emacs-helm.sh to reproduce the bug.
