### ISSUE TITLE
Please add support for using "-" for tramp-default-method in helm-find-files

### ISSUE THREAD

**Issue by laurynas-biveinis** [emacs-helm/helm#2275]
**Is your feature request related to a problem? Please describe.**
Without Helm, `M-x find-files` can use "-" pseudo-method as a Tramp access method to make it use `tramp-default-method`, i.e. `//-:hostname:path` would be identical to `//scpx:hostname:path` if `tramp-default-method` is set to "scpx". With `helm-find-files`, I am required to spell out "scpx", it would be nice if "-" were supported too.

**Describe the solution you'd like**
Make `helm-find-files` recognize "-" as a Tramp access method and expand it to `tramp-default-method`, like find-files does.

**Describe alternatives you've considered**
The obvious workaround is to type "scpx" or other access method instead of "-" myself, ignoring tramp-default-method.

**Additional context**
In Tramp URLs, "-" is supported under Tramp default syntax (i.e. not the simplified one).
https://www.gnu.org/software/emacs/manual/html_node/tramp/Default-Method.html
https://www.gnu.org/software/emacs/manual/html_node/tramp/File-name-syntax.html#File-name-syntax

**Comment by thierryvolpiatto** [comment]
Laurynas Biveinis <notifications@github.com> writes:

> Make helm-find-files recognize "-" as a Tramp access method and expand
> it to tramp-default-method, like find-files does.

I have pushed a branch implementing this, but I have no ssh server to
test against from where I am actually, so it is fully untested, let me
know if it works for you.

Thanks.

--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by laurynas-biveinis** [comment]
Thank you - I should be able to test this tomorrow and will update

**Comment by laurynas-biveinis** [comment]
@thierryvolpiatto , I have tested the patch by applying it on the top of 3.6.0 release (not the HEAD - I hope that's good enough) and confirm that "-" now works and expands to tramp-default-method. I did not see any regressions in using "scpx" neither. Thank you!

**Comment by thierryvolpiatto** [comment]
Laurynas Biveinis <notifications@github.com> writes:

> @thierryvolpiatto , I have tested the patch by applying it on the top
> of 3.6.0 release (not the HEAD - I hope that's good enough) and
> confirm that "-" now works and expands to tramp-default-method. I did
> not see any regressions in using "scpx" neither. Thank you!

Thanks for testing, will merge soon.

--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Have been merged, thanks.
