### ISSUE TITLE
helm-split-window-default-side 'other not respecting dedicated windows

### ISSUE THREAD

**Issue by Jefftree** [emacs-helm/helm#2276]
## Expected/actual behavior

helm opens in dedicated windows when `helm-split-window-default-side` is set to 'other. Dedicated windows are respected when the variable is set to any other value left, right, above, below. 

I noticed that helm uses `other-windows-for-scrolling` when retrieving the window when `helm-split-window-default-side` is set to 'other. `other-windows-for-scrolling` does not seem to filter out dedicated windows.

Not sure if this is a bug for helm or upstream.

## Steps to reproduce (recipe)

My configurations:

```
(setq helm-split-window-inside-p nil)
(setq helm-split-window-default-side 'other)
```

Start emacs and split to two windows. Set one to a dedicated window (`(set-window-dedicated-p (selected-window) t)`)

Invoke helm in the other window. The expected behavior is that helm opens in the same window it was invoked due to one of the windows being set as a dedicated window. (This is the behavior observed when setting `helm-split-window-default-side`  to left, right, above, below.) However, it ends up being opened within the dedicated window.

**Comment by thierryvolpiatto** [comment]
Jeffrey Ying <notifications@github.com> writes:

> Expected/actual behavior
>
> helm opens in dedicated windows when helm-split-window-default-side is set to 'other. Dedicated windows are respected when the variable is set to any other value left,
> right, above, below.
>
> I noticed that helm uses other-windows-for-scrolling when retrieving
> the window when helm-split-window-default-side is set to
> 'other. other-windows-for-scrolling does not seem to filter out
> dedicated windows.

Should be fixed now, thanks.

--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
