### ISSUE TITLE
helm assumes ~/.emacs.d as config folder (emacs 27 supports XDG_CONFIG_HOME)

### ISSUE THREAD

**Issue by benjaminor** [emacs-helm/helm#2278]
Starting with emacs 27 (https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=4118297ae2fab4886b20d193ba511a229637aea3), emacs supports having the emacs config folder in XDG_CONFIG_HOME.

## Expected behavior

helm should respect that the emacs config folder could be in XDG_CONFIG_HOME by relying on `user-emacs-directory` instead of hard-coding ~/.emacs.d

## Actual behavior

helm assumes the config folder is in ~/.emacs.d in three different files (helm-adaptive.el, helm-x-files.el, emacs-helm.sh).

## Suggestion

This could be fixed quite fast by replacing the hardcoded `.emacs.d` with `user-emacs-directory`. Do you want to me to open a merge request where I implement these changes?

Thanks a lot for the work on helm! I don't know what I would do without it.

**Comment by thierryvolpiatto** [comment]
Benjamin Orthen <notifications@github.com> writes:

> Do you want to me to open a merge request where I implement these
> changes?

Yes please.

Thanks to catch this.

--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
