### ISSUE TITLE
helm-list-elisp-packages wants to upgrade and delete too much by default

### ISSUE THREAD

**Issue by obar** [emacs-helm/helm#2280]
## Expected behavior
Running `helm-list-elisp-packages` should be something like running `package-list-packages`. Nothing should be marked to delete or install by default (or at least with optional configuration for that behavior), no prompt asking y/n for deleting packages.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
From `emacs-helm.sh`, first thing that happens is a prompt asking if I really want to delete all packages.

In normal operation I believe this is a prompt asking to delete any package not in `package-selected-packages`, including those installed other ways.

After that, it shows the filtered view for upgradable packages (that's OK, docs explain M-A to view all), but with every package that can be upgraded marked for installation.

## Steps to reproduce (recipe)
`M-x helm-list-elisp-packages`

## Backtraces if any (`M-x toggle-debug-on-error`)
n/a

## Describe versions of Helm, Emacs, operating system, etc.
emacs 26.2 with helm-20200128.1831, Ubuntu

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):
yes

## Are you using Spacemacs? (yes/no):
no

**Comment by thierryvolpiatto** [comment]
Ori <notifications@github.com> writes:

> Expected behavior
>
> Running helm-list-elisp-packages should be something like running
> package-list-packages. Nothing should be marked to delete or install
> by default (or at least with optional configuration for that
> behavior), no prompt asking y/n for deleting packages.

You can say no, if you don't want to delete packages.

> Actual behavior (from emacs-helm.sh if possible, see note at the bottom)
>
> From emacs-helm.sh, first thing that happens is a prompt asking if I really want to delete all packages.

All packages? If it asks to delete all packages it is you did something
wrong (e.g. modifying manually package-selected-packages).

> In normal operation I believe this is a prompt asking to delete any
> package not in package-selected-packages, including those installed
> other ways.

If you delete selected package A with dependencies B and C, helm will
ask you if you want to delete packages B and C if they are not used
elsewhere.

So I wonder what is the problem with this as long as you can say yes or
no.

--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by obar** [comment]
> All packages? 

Yes, `emacs-helm.sh` doesn't have my package list.

What about all of the packages that can be upgraded being marked for installation?

**Comment by obar** [comment]
I just made a backup of my `.emacs.d` and tried installing a package using `helm-list-elisp-packages`. I used the "Install packages" action and all of those packages marked with I for install and U for upgrade available were actually unchanged. Not what I expected given the UI state (so these are not marked for install?) but it is what I would want.

Is there any way to change the defaults of this command, ie not asking about package removal and not pre-filter the list to upgrades?

**Comment by thierryvolpiatto** [comment]
Ori <notifications@github.com> writes:

> I just made a backup of my .emacs.d and tried installing a package using helm-list-elisp-packages. I used the "Install packages" action and all of those packages marked
> with I for install and U for upgrade available were actually unchanged. Not what I expected given the UI state (so these are not marked for install?) but it is what I
> would want.
>
> Is there any way to change the defaults of this command, ie not asking
> about package removal and not pre-filter the list to upgrades?

It is now the default.

The problem was you started from emacs-helm.sh and
package-selected-packages is not populated when running from emacs -q.
It is now handled, please try starting from emacs-helm.sh and run
helm-list-elisp-packages or helm-list-elisp-packages-no-fetch, when
hitting M-I, you should see now your installed package marked with "S"
(unless they are dependencies).

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by obar** [comment]
That's great, thank you very much! What I mean about the other part (optional pre-filtering the list) might be easier to explain with code. [This is what I mean](https://github.com/obar/helm/commit/d31378f8a1894fd46ad65acdd7091eb5a0a544e9).

If it's reasonable I can submit a pull request, or perhaps do you think this should use `helm-el-package-initial-filter` differently? That's the variable I initially thought was being ignored as I have it set to the default, all, and obviously that is only followed if `helm-el-package--upgrades` is `nil`.

**Comment by thierryvolpiatto** [comment]
Ori <notifications@github.com> writes:

> That's great, thank you very much! What I mean about the other part
> (optional pre-filtering the list) might be easier to explain with
> code. This is what I mean.
>
> If it's reasonable I can submit a pull request,

Yes, please.

Thanks for looking into this.

--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by obar** [comment]
Thanks for all your help Thierry!
