### ISSUE TITLE
Symbol's value as variable is void: helm-take-first-elements on Emacs 24.5.1

### ISSUE THREAD

**Issue by lechten** [emacs-helm/helm#2282]
## Expected behavior
Can `require 'helm`

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
An error is shown: Symbol's value as variable is void: helm-take-first-elements

## Steps to reproduce (recipe)
emacs -Q, then:

```
(package-initialize)
(setq debug-on-error t)
(require 'helm)
```
## Backtraces if any (`M-x toggle-debug-on-error`)
```
Debugger entered--Lisp error: (void-variable helm-take-first-elements)
  byte-code("\303^H\302 !\304\nG        V\203^U^@\305\n\306     #\202^V^@\n$\210\307^H\310      !\311\nG        V\203F^@\31$
  require(helm-lib)
  eval-buffer(#<buffer  *load*> nil "/root/.emacs.d/elpa/helm-core-20200302.638/helm.el" nil t)  ; Reading at buffer positi$
  load-with-code-conversion("/root/.emacs.d/elpa/helm-core-20200302.638/helm.el" "/root/.emacs.d/elpa/helm-core-20200302.63$
  require(helm)
  eval((require (quote helm)) nil)
  eval-last-sexp-1(nil)
  eval-last-sexp(nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```

## Describe versions of Helm, Emacs, operating system, etc.
helm-20200227.923, helm-core-20200302.638, Emacs 24.5.1, Debian 9

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):
yes

## Are you using Spacemacs? (yes/no):
no

**Comment by lechten** [comment]
I forgot: A newer Emacs tells me this about `cl-defgeneric`: Probably introduced at or before Emacs version 25.1.
Helm [should](https://emacs-helm.github.io/helm/#requirements) work with 24.4.

**Comment by manuel-uberti** [comment]
Do you have the chance to try with a more recent Emacs version? 26.3 has been out for a while, for instance.

**Comment by lechten** [comment]
Normally, I'm on a recent Emacs version, where Helm works. 
I maintain a package, though, which I advertise as "working with 24.4" (where Helm gets pulled in as dependency from a third package that I really need). Also, my Docker images  use Debian 9 which has Emacs 24.5...

**Comment by thierryvolpiatto** [comment]
Jens Lechtenbörger <notifications@github.com> writes:

> Normally, I'm on a recent Emacs version, where Helm works.  I maintain
> a package, though, which I advertise as "working with 24.4" (where
> Helm gets pulled in as dependency from a third package that I really
> need). Also, my Docker images use Debian 9 which has Emacs 24.5...

I reverted the change (sadly), note that I will soon (next version) make
25.1 as requirement as 24+ series are really deprecated versions now.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by lechten** [comment]
Thank you for both, the change and the advance notification!
