### ISSUE TITLE
Helm-gtags result highlighting is very slow

### ISSUE THREAD

**Issue by sakopzon** [emacs-helm/helm#2284]
**Is your feature request related to a problem? Please describe.**
I am working remotely with a very slow network (also heavy loaded due to the Corona). Using Putty to connect and running emacs in the terminal mode. The auto-changing colors of the gtags-find-tag result make the connection stuck for 2-5 seconds. It is more then annoying.

**Describe the solution you'd like**
I want it to be configurable (searched in all faces customization, helm, gtags etc... and didn't find how to disable this highlighting)

**Comment by sakopzon** [comment]
seems like helm is using very large amount of colors which change from one to another. I removed my 256-color configuration and now it works much faster. Still it is very annoying that I have to use ugly colors for helm-gtags to run well...

**Comment by thierryvolpiatto** [comment]
Please give a recipe of what you are doing (and using) exactly, see also issue #2262.

**Comment by sakopzon** [comment]
(setq helm-gtags-pulse-at-cursor nil) fixed the issue
