### ISSUE TITLE
Is it possible to pass string  to Helm?

### ISSUE THREAD

**Issue by introom** [emacs-helm/helm#2285]
For example, I want to define a custom function which invokes Helm-M-x with a default input string "cider-test" ?

**Comment by manuel-uberti** [comment]
Following the guidelines at [Developing](https://github.com/emacs-helm/helm/wiki/Developing), this is how I'd pass a default input string to a custom command:
```emacs-lisp
(helm :sources (helm-build-sync-source "test"
                 :candidates '("cider-connect" "cider-test" "cider-do-something"))
      :input "cider-test"
      :buffer "*my helm test*")
```

**Comment by manuel-uberti** [comment]
To answer the question about `cider-test`, I'd probably to something like this:
```emacs-lisp
(helm :sources (helm-make-source "Emacs Commands" 'helm-M-x-class
                 :candidates (helm-dynamic-completion obarray #'commandp nil nil t))
      :input "cider-test"
      :buffer "*my helm test*")
```

**Comment by introom** [comment]
Thanks.  That solves the problem.

**Comment by thierryvolpiatto** [comment]
Sorry for late reply.

Manuel Uberti <notifications@github.com> writes:

> To answer the question about cider-test, I'd probably to something like this:
>
> (helm :sources (helm-make-source "Emacs Commands" 'helm-M-x-class
>                  :candidates (helm-dynamic-completion obarray #'commandp nil nil t))
>       :input "cider-test"
>       :buffer "*my helm test*")

Yes this exactly what is needed, I would add a sort function in the
`helm-dynamic-completion` call if you use an emacs version < 27 e.g. emacs-26.
See `helm-M-x-read-extended-command` code.

Thanks.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
