### ISSUE TITLE
helm-find-files is unusably slow over tramp with ssh

### ISSUE THREAD

**Issue by gnzlbg** [emacs-helm/helm#2286]
## Expected behavior

Actually be able to at least "find files" without having 10seconds of lag.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

helm-find-files takes a long time to find directories when the name matches perfectly (>10s), if I try to move multiple directories at once, it never finds the path. It is unusably slow, e.g., 30s-5min(I gave up) to display the files in a directory. A normal ssh connection and doing an `ls` is instantaneous.

## Steps to reproduce (recipe)

Use `helm-find-files`, go to a remote host, e.g., `/ssh:username@hostname:` and that already takes too long. Try to then move to your home, e.g., by adding a `~/` so that you get `/ssh:username@hostname:~/`, that takes from 10-30 seconds, try to find a directory or file called `foo` by just typing `fo`, e.g., `/ssh:username@hostname:~/fo`, that never terminates, not even after 5 minutes. Going to the directory ~/ instead and using dired, I can open `foo` without issues.

## Backtraces if any (`M-x toggle-debug-on-error`)

I don't see any errors.

## Describe versions of Helm, Emacs, operating system, etc.

I can reproduce with: Emacs 26.3, MacOSX. Emacs 27 MacOSX, Emacs 26.3 Ubuntu, Emacs 27 Ubuntu.

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no): 

no, when using `emacs-helm.sh` the command `helm-find-files` does not exist.

## Are you using Spacemacs? (yes/no):

yes

**Comment by manuel-uberti** [comment]
Are you sure `helm-find-files` isn't available from `emacs-helm.sh`? I just cloned `helm` respository, and I see it:
![Screenshot from 2020-04-03 10-34-03](https://user-images.githubusercontent.com/8199224/78340633-b9bdf680-7596-11ea-85e0-7689b0e6242f.png)

**Comment by thierryvolpiatto** [comment]
gnzlbg <notifications@github.com> writes:

> Expected behavior
>
> Actually be able to at least "find files" without having 10seconds of lag.

This depend on your ssh connection.

> Actual behavior (from emacs-helm.sh if possible, see note at the bottom)
>
> helm-find-files takes a long time to find directories when the name
> matches perfectly (>10s),

Not reproductible on a reasonably fast enough ssh connection.

> if I try to move multiple directories at once, it never finds the
> path. It is unusably slow, e.g., 30s-5min(I gave up) to display the
> files in a directory. A normal ssh connection and doing an ls is
> instantaneous.

When copying/moving use scp and not ssh.

>
> Steps to reproduce (recipe)
>
> Use helm-find-files, go to a remote host, e.g.,
> /ssh:username@hostname: and that already takes too long. Try to then
> move to your home, e.g., by adding a ~/ so that you get
> /ssh:username@hostname:~/,

Using ~/ added at end of pattern, you end up in your local directory,
not the remote one.


> that takes from 10-30 seconds, try to find a directory or file called
> foo by just typing fo, e.g., /ssh:username@hostname:~/fo, that never
> terminates, not even after 5 minutes. Going to the directory ~/
> instead and using dired, I can open foo without issues.
>
> Backtraces if any (M-x toggle-debug-on-error)
>
> I don't see any errors.
>
> Describe versions of Helm, Emacs, operating system, etc.
>
> I can reproduce with: Emacs 26.3, MacOSX. Emacs 27 MacOSX, Emacs 26.3 Ubuntu, Emacs 27 Ubuntu.
>
> Are you using emacs-helm.sh to reproduce this bug? (yes/no): no, when
> using emacs-helm.sh the command helm-find-files does not exist.

No helm-find-files is by default bound to C-x C-f in helm.sh.

> Are you using Spacemacs? (yes/no): yes

Probably this is your problem, I can't accept bug reports made from
Spacemacs which heavily modify helm, please try to reproduce your bug
from emacs-helm.sh.

Thanks.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by manuel-uberti** [comment]
FWIW, another thing I can think of is the shell prompt on the remote machine. 

If I try what @gnzlbg says on a remote machine with Fish shell and a custom prompt Tramp hangs. IIRC, this is a known-problem. 

However, this has nothing to do with Helm, since it happens with regular `find-files` on `emacs -Q` for me.

**Comment by thierryvolpiatto** [comment]
Manuel Uberti <notifications@github.com> writes:

> FWIW, another thing I can think of is the shell prompt on the remote machine.
>
> If I try what @gnzlbg says on a remote machine with Fish shell and a
> custom prompt Tramp hangs. IIRC, this is a known-problem.

That's good to know, thanks for this.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Also see `helm-list-directory-function` .
