### ISSUE TITLE
Would like C-backspace to behave as default in helm-find-files

### ISSUE THREAD

**Issue by inkybutton** [emacs-helm/helm#2289]
**Is your feature request related to a problem? Please describe.**
Hi there, thanks for making Helm! I just started using Spacemacs which includes Helm. I really like it so far, the auto-complete function is great!
When I use C-x C-f to find files, I have muscle memory to use C-backspace to move up the directory. C-backspace deletes a word in a normal text buffer as well as the default find file minibuffer. However, when I press it in helm-find-files, it seems to toggle the auto expansion option. I don't understand why it is remapped to that.
* It is a key combo I use very often in Emacs in writing code, text and general operations, so having to unlearn and relearn (and only relearn it in this context) seems counter-intuitive. As a new user, I find it breaks my mental model of how Emacs works, and adds an extra barrier for me to get used to Helm. 
* I learned that there is a C-l option for going up the directory. But I think it's good to keep C-backspace for deleting a word, so we can have redundant affordances and people with different backgrounds can get used to the system quickly.
* By my reading of [helm-files.el](https://github.com/emacs-helm/helm/blob/master/helm-files.el) the toggle function seems to be mapped to C-backspace as well as C-c DEL. It seems like changing the C-backspace combo back to normal would still leave C-c DEL as an affordance for toggling auto expansion mode.
* I think toggling auto expansion mode isn't something one would use very often - I may be wrong, it seems like a functionality that only needs to be set once. It seems like it may be better to keep C-backspace mapped to a common function (deleting a word).

**Describe the solution you'd like**
I think it would be good to have the C-backspace key combo mapped to deleting a word, or at least have an option for it to be mapped to deleting a word.

**Describe alternatives you've considered**
As above!

**Additional context**

Thanks for reading, I'd be glad to hear what you think.
Noel.

**Comment by thierryvolpiatto** [comment]
Noel <notifications@github.com> writes:

> Is your feature request related to a problem? Please describe.
> Hi there, thanks for making Helm! I just started using Spacemacs which includes Helm. I really like it so far, the auto-complete function is great!
> When I use C-x C-f to find files, I have muscle memory to use C-backspace to move up the directory. C-backspace deletes a word in a normal text buffer as well as the
> default find file minibuffer. However, when I press it in helm-find-files, it seems to toggle the auto expansion option. I don't understand why it is remapped to that.
>
>   • It is a key combo I use very often in Emacs in writing code, text and general operations, so having to unlearn and relearn (and only relearn it in this context) seems
>     counter-intuitive. As a new user, I find it breaks my mental model
>     of how Emacs works, and an extra barrier for me to get used to
>     Helm.

First of all, remember you can modify keybindings in helm in the same
way as you do in emacs, I will add an entry in documentation, because it
is not the first time people ask for how to modify keybindings in helm.

>   
>   • I learned that there is a C-l option for going up the
>   directory. But I think it's good to keep C-backspace for deleting a
>   word, so we can have redundant affordances and people with different
>   backgrounds can get used to the system quickly.



>   • By my reading of helm-files.el

For some reason most Spacemacs users are not aware of C-h m and have to
go into source code to get infos about helm.

>   the toggle function seems to be mapped to C-backspace as well as C-c
>   DEL. It seems like changing the C-backspace combo back to normal
>   would still leave C-c DEL an affordance for toggling auto expansion
>   mode.

C-c DEL is not as convenient as C-backspace.

>   • I think toggling auto expansion mode isn't something one would use
>   very often - I may be wrong, it seems like a functionality that only
>   needs to be set once. It seems like it may be better to keep
>   C-backspace mapped to a common function (deleting a word).

You are wrong, it is useful mostly for people using
`helm-ff-auto-update-initial-value`.

> Describe the solution you'd like I think it would be good to have the
> C-backspace key combo mapped to deleting a word, or at least have an
> option for it to be mapped to deleting a word.

No, this would add an unuseful option as you can configure this with
define-key.

    (define-key helm-find-files-map (kbd "C-<backspace>") nil)

Hope that help.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by inkybutton** [comment]
Well, I think that's a pretty rude comment that didn't address what I raised regarding the default behaviour. But thanks for taking the time to write it anyway. I wish this project the best.
