### ISSUE TITLE
Performance of helm-M-x degrades when savehist-mode is turned on

### ISSUE THREAD

**Issue by gcv** [emacs-helm/helm#2290]
## Expected behavior

`helm-M-x` narrowing is near-instant.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

`helm-M-x` narrowing is near-instant in a sandbox Emacs and Helm, but slows when there's a large number of large history variables (which naturally happens over time with savehist-mode turned on and large history sizes). Typing `eval-buffer` quickly stutters after the `e`.

## Steps to reproduce (recipe)

Put a large number of commands into `extended-command-history`.

## Describe versions of Helm, Emacs, operating system, etc.

Emacs 26.3, Mac 10.14.6, Helm 3.6.0. I think older versions of Helm did not slow down.

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):

no

## Are you using Spacemacs? (yes/no):

no

**Comment by thierryvolpiatto** [comment]
gcv <notifications@github.com> writes:

> helm-M-x narrowing is near-instant in a sandbox Emacs and Helm, but
> slows when there's a large number of large history variables (which
> naturally happens over time with savehist-mode turned on and large
> history sizes).

Thanks to catch this.
I was just appending commands to `extended-command-history` without
honouring `history-length`, it is why you have accumulated such a large
history for M-x.
It is now fixed, when you will use again helm-M-x it will save your last
command and delete the tail of extended-command-history after
history-length value (I use 100 here).
You can check this by evaluating (length extended-command-history)
before and after using helm-M-x.

Thanks.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by gcv** [comment]
Looks good, thanks for the quick fix!
