### ISSUE TITLE
Duplicate entries in Emacs Commands history

### ISSUE THREAD

**Issue by manuel-uberti** [emacs-helm/helm#2291]
## Expected behavior

No matter how many times I call a command, I expect to see one entry for it in `Emacs Commands history` (`helm-M-x`)

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

![Screenshot from 2020-04-16 16-32-53](https://user-images.githubusercontent.com/8199224/79469153-19d58380-8000-11ea-8687-bac9d77e52b3.png)

## Steps to reproduce (recipe)

From `emacs-helm.sh`:
- Turn on `helm-mode`
- Run `helm-M-x`
- Type `dired` and hit <kbd>RET</kbd>
- Kill the dired buffer
- Run `helm-M-x`
- Type `dired` and hit <kbd>RET</kbd>
- Kill the dired buffer
- `helm-M-x`
- Type `dired`

## Describe versions of Helm, Emacs, operating system, etc.

- Helm version: `commit 7936b49e48d76417a93b4e6dd73c3c69f90d3a11`
- System details:
```
GNU Emacs 28.0.50 (build 1, x86_64-debian-linux-gnu, GTK+ Version 3.22.30, cairo version 1.15.10)
 of 2020-04-16

Repository revision: d5a7df8c02f04102d50a5cd2290262f59f2b1415
Configured using:
--host=x86_64-debian-linux-gnu --with-modules --with-imagemagick --with-harfbuzz host_alias=x86_64-debian-linux-gnu
```

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):

Yes

## Are you using Spacemacs? (yes/no):

No

**Comment by thierryvolpiatto** [comment]
Manuel Uberti <notifications@github.com> writes:

> Expected behavior
>
> No matter how many times I call a command, I expect to see one entry for it in Emacs Commands history (helm-M-x)

This is due to recent changes in commit 811af84 where we use
now `add-to-history`.
Set `history-delete-duplicates` to remove dups.
Set `history-length` to limit history length.

See Issue #2290.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by manuel-uberti** [comment]
Awesome, setting those two fixes it for me. Thank you!
