### ISSUE TITLE
Helm actions buffer initially empty when helm is displayed in child frame without minibuffer

### ISSUE THREAD

**Issue by Alexander-Miller** [emacs-helm/helm#2292]
## Expected behavior

Calling `helm-select-action` should display the available action for the current source.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

The actions buffer appears empty, but typing input reveals and highlights the actions as expected, only the initial state is visually incorrect.

## Steps to reproduce (recipe)

 - Eval
```Elisp
(defun show-helm-child-frame (buffer-name &rest _)
  (let ((buffer (get-buffer buffer-name)))
    (setq helm--buffer-in-new-frame-p t)
    (select-window
     (display-buffer-in-child-frame
      buffer
      `((child-frame-parameters
         .
         ((left . 100)
          (top  . 100)
          (height . 10)
          (width . 50)
          (minibuffer . nil))))))
    (delete-other-windows)
    (select-frame-set-input-focus (selected-frame) t)
    (selected-window)))

(setf helm-display-function #'show-helm-child-frame)
```

 - Call a helm command like `helm-mini`.
 - Press TAB
 - Actions buffers looks empty

I have encountered this in the context of my own private package that makes packages like helm and helpful use a child-frame: https://github.com/Alexander-Miller/framey. So far my workaround has been to simply force an update: `(advice-add 'helm-select-action :after #'helm-force-update)`. If you agree with that solution I can create a PR.

## Describe versions of Helm, Emacs, operating system, etc.

Version 3.6.1, commit 4121e0a7c428a3e008b8f61aef02f0b5b5ce371f
Emacs 26.3, Linux Antergos

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):

I was getting errors with emacs-helm.sh about not finding other packages, probably because I use the straight package manager which installs packages in a different location than what helm expects. The reproduction recipe was run under `emacs -q`.

## Are you using Spacemacs? (yes/no):

No.

**Comment by thierryvolpiatto** [comment]
Alexander-Miller <notifications@github.com> writes:

> Expected behavior
>
> Calling helm-select-action should display the available action for the
> current source.

Please try to look at `helm-display-buffer-in-own-frame`.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by Alexander-Miller** [comment]
`helm-display-buffer-in-own-frame` is not affected because the frame it creates has a minibuffer: https://github.com/emacs-helm/helm/blob/master/helm.el#L3219. If you change that line to `nil` it exhibits the same behavior.

**Comment by thierryvolpiatto** [comment]
Alexander-Miller <notifications@github.com> writes:

> helm-display-buffer-in-own-frame is not affected because the frame it
> creates has a minibuffer:
> https://github.com/emacs-helm/helm/blob/master/helm.el#L3219. If you
> change that line to nil it exhibits the same behavior.

So I guess you found the problem, you need a minibuffer in your frame.
Or use what's helm propose to display helm session inside a frame.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by Alexander-Miller** [comment]
> you need a minibuffer in your frame.

The point is that I shouldn't. If a child frame has no minibuffer on its
own it falls back to using the minibuffer of its parent. As does helm
with this setup. The problem is that it does not update the actions
buffer when it is first switched to, unless a non-delegated minibuffer
is present, and there is no reason these 2 things should be related like
this.

Now I understand that this problem is incredibly obscure, that I am most
likely the only one affected, that helm is on low-maintenance mode and
that a proper fix is probably all sorts of complicated, so if you think
this is not worth the effort (especially since I do have a simple
workaround as it is) please say so explicitly instead of deflecting that
I'm not doing it right.

**Comment by thierryvolpiatto** [comment]
Alexander-Miller <notifications@github.com> writes:

>> you need a minibuffer in your frame.
>
> The point is that I shouldn't. If a child frame has no minibuffer on its
> own it falls back to using the minibuffer of its parent. As does helm
> with this setup. The problem is that it does not update the actions
> buffer when it is first switched to, unless a non-delegated minibuffer
> is present, and there is no reason these 2 things should be related like
> this.
>
> Now I understand that this problem is incredibly obscure, that I am most
> likely the only one affected, that helm is on low-maintenance mode and
> that a proper fix is probably all sorts of complicated, so if you think
> this is not worth the effort (especially since I do have a simple
> workaround as it is) please say so explicitly instead of deflecting that
> I'm not doing it right.

So if it is what you are asking, yes, I won't fix this and I am not
interested in child-frames for helm.
I am now going to close this issue.

> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.*


-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
