### ISSUE TITLE
helm-find-files initial current directory desynced on TRAMP 

### ISSUE THREAD

**Issue by laurynas-biveinis** [emacs-helm/helm#2294]
## Expected behavior

helm-find-files is able to complete in remote $HOME right after establishing connection

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

Upon opening TRAMP connection, remote $HOME contents are listed as completion candidates. But performing any narrowing action or selecting a completion candidate results in "[?] foo" as if remote files are not there.

A workaround is to type "/" or C-l, then the candidate list and ability to navigate start working again

## Steps to reproduce (recipe)

C-x C-f
Type "/scpx:server:"

## Describe versions of Helm, Emacs, operating system, etc.

Helm 3.6.1, Emacs 26.3, host OS macOS 10.15.4, remote OS Ubuntu 18.04.4

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):

The current emacs-helm.sh failed for me to load helm.el due to some load-path mixup. Thus for logging the bug I used helm-minimal.el as of 2020-01-20.

## Are you using Spacemacs? (yes/no):

No

**Comment by thierryvolpiatto** [comment]
Laurynas Biveinis <notifications@github.com> writes:

> Expected behavior
>
> helm-find-files is able to complete in remote $HOME right after establishing connection
>
> Actual behavior (from emacs-helm.sh if possible, see note at the bottom)
>
> Upon opening TRAMP connection, remote $HOME contents are listed as
> completion candidates. But performing any narrowing action or
> selecting a completion candidate results in "[?] foo" as if remote
> files are not there.

Try C-x C-f and C-h m you will find some hints to use helm ff with
tramp.
For a quick answer use C-j on top directory after first connection.


-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by laurynas-biveinis** [comment]
Thank you, I am sorry for missing this in the manual
