### ISSUE TITLE
the option to disable URL at point with helm-find-files

### ISSUE THREAD

**Issue by hisnawi** [emacs-helm/helm#2295]
I looked in the code but couldn't find a way to disable pointing to a URL when executing helm-find-files on top of a URL link.

**Comment by thierryvolpiatto** [comment]
hisnawi <notifications@github.com> writes:

> I looked in the code but couldn't find a way to disable pointing to a URL when executing helm-find-files on top of a URL link.

From helm-find-files C-h c (See in mode-line).

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by hisnawi** [comment]
this solves it:
`          (setq helm-ff-guess-ffap-urls             nil)`
