### ISSUE TITLE
helm-completion-in-region--insert-result assumes too much about crm-separator

### ISSUE THREAD

**Issue by akater** [emacs-helm/helm#2298]
## Expected behavior

Always insert a separator corresponding to `crm-separator` when completing multiple candidates.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

Comma is always inserted in the first completion round in multiple candidates completion.

## Steps to reproduce (recipe)

```
emacs-helm.sh
```

```
M-: (require 'crm) RET
```

Type:

```lisp
(let ((crm-separator "|"))
  (completing-read-multiple "Keyword (or KWD1|KWD2|...): "
    (mapcar #'list '("TODO" "DONE")) nil nil))
```
Press `C-x C-e`.

Press `TAB`.

Press `C-SPC C-SPC RET`.

Observe TODO,DONE in minibuffer.

Press `|`.

Press `TAB`.

Press `C-SPC C-SPC RET`.

Observe TODO,DONE|TODO|DONE in minibuffer.

## Describe versions of Helm, Emacs, operating system, etc.

Helm 20200427
Emacs 28.0.50

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):

Yes.

## Are you using Spacemacs? (yes/no):

No.

**Comment by thierryvolpiatto** [comment]
Should work now.

Should work with the two tests below and also with org-tag.

```elisp
(let ((crm-separator "|"))
  (completing-read-multiple "Keyword (or KWD1|KWD2|...): "
    (mapcar #'list '("TODO" "DONE")) nil nil))

(completing-read-multiple "Keyword (or KWD1|KWD2|...): "
    (mapcar #'list '("TODO" "DONE")))
```

Thanks.

**Comment by akater** [comment]
I don't see any update besides `helm-core` which had no effect on this.

**Comment by thierryvolpiatto** [comment]
akater <notifications@github.com> writes:

> I don't see any update besides helm-core which had no effect on this.

Oops! Forget to push, sorry, now done.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by akater** [comment]
Great, thank you.

Initially I considered a similar solution. My thoughts:

- it is unfortunate that string patterns are strings themselves and hence we can't distinguish;

- `crm` should likely expose separator (the string) on its own in its interface

**Comment by akater** [comment]
One last thing: may I also suggest (an equivalent of)
```diff
--- a/helm-mode.el
+++ b/helm-mode.el
@@ -1873,7 +1873,7 @@
              (when (looking-back crm-separator (1- (point)))
                (setq sep (match-string 0))))
            (funcall completion-list-insert-choice-function
-                    beg end (mapconcat 'identity result sep))))
+                    beg end (mapconcat 'identity (nconc result '("")) sep))))
         (t nil)))
 
 (defun helm-mode--in-file-completion-p ()
```

to spare user from typing the separator in manually?

I even think I saw Helm doing this somewhere.

**Comment by thierryvolpiatto** [comment]
akater <notifications@github.com> writes:

> One last thing: may I also suggest (an equivalent of)
>
> --- a/helm-mode.el
> +++ b/helm-mode.el
> @@ -1873,7 +1873,7 @@
>               (when (looking-back crm-separator (1- (point)))
>                 (setq sep (match-string 0))))
>             (funcall completion-list-insert-choice-function
> -                    beg end (mapconcat 'identity result sep))))
> +                    beg end (mapconcat 'identity (nconc result '("")) sep))))
>          (t nil)))
>  
>  (defun helm-mode--in-file-completion-p ()
>
> to spare user from typing the separator in manually?

No objection, can you make a PR.

Thanks.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
