### ISSUE TITLE
More consistent behaviour w.r.t. completing-read-multiple and completing-read

### ISSUE THREAD

**Issue by akater** [emacs-helm/helm#2299]
**Is your feature request related to a problem? Please describe.**
I want to replace one call to `completing-read` in `org-mode` with a call to `completing-read-multiple`. However, this would lead to the following change in UX for users who use helm and org: completion candidates wouldn't appear immediately anymore; the user would have to hit `TAB` for them to appear.

**Describe the solution you'd like**
It would be better if candidates appeared immediately when selecting multiple candidates, like they do now when selecting a single candidate. In general, this would be more consistent fol Helm.

**Additional context**
We [duscussed this](https://github.com/emacs-helm/helm-org/issues/12#issuecomment-592580957) with @thierryvolpiatto He suggested it was `crm` issue. However, `crm` is consistent in the sense that neither `completing-read` nor `completing-read-multiple` make candidates list appear immediately.

**Comment by thierryvolpiatto** [comment]
akater <notifications@github.com> writes:

> It would be better if candidates appeared immediately when selecting
> multiple candidates, like they do now when selecting a single
> candidate. In general, this would be more consistent fol Helm.

No, see below.

> Additional context We duscussed this with @thierryvolpiatto He
> suggested it was crm issue. However, crm is consistent in the sense
> that neither completing-read nor completing-read-multiple make
> candidates list appear immediately.

Yes but the behavior of completing-read is to exit minibuffer with a candidate
(choosen) as value whereas CRM behavior is to insert a choosen candidate
in the minibuffer, imagine what would happen if you where inserting the
candidate in this same helm minibuffer, so no the behavior here should
not be changed.


-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by akater** [comment]
I don't get it but I trust your expertise; hopefully will revisit later. Thank you.
