### ISSUE TITLE
Change shortcut to go to root / when navigating  with helm-find-files

### ISSUE THREAD

**Issue by hisnawi** [emacs-helm/helm#2300]
Is it possible when doing helm-find-files to change the shortcut that goes to / instead of one / make it two /?

Sometimes when navigating directories I hit / by mistake which takes me to root directory /
However, I found that Ivy deals with this situation better that you need to type // to go to root, which is safer approach.

**Comment by thierryvolpiatto** [comment]
hisnawi <notifications@github.com> writes:

> Is it possible when doing helm-find-files to change the shortcut that
> goes to / instead of one / make it two /?

No, only one is better, hitting twice is an annoyance.

> Sometimes when navigating directories I hit / by mistake which takes
> me to root directory /

Use undo.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by manuel-uberti** [comment]
Sorry for hijacking this issue, @thierryvolpiatto, but what do you think about hitting only `~` instead of `~/` to go to `$HOME`?

**Comment by thierryvolpiatto** [comment]
Manuel Uberti <notifications@github.com> writes:

> Sorry for hijacking this issue, @thierryvolpiatto, but what do you
> think about hitting only ~ instead of ~/ to go to $HOME?

No, too much work and many bugs would be introduced, noth worth the
effort for the small benefice it would give (same for "///").

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
