### ISSUE TITLE
Case distinction bug

### ISSUE THREAD

**Issue by TBombadil** [emacs-helm/helm#2301]
Helm behaviour w.r.t. perfect matches and lower/upper case is unexpected.
**Expected behavior:** Prefer perfect match.
**Actual behavior:**  Prefer capital case.
## Steps to reproduce (recipe)
Run emacs-helm.sh.
Create buffers `test` and `Test`.
Then try to select to move to `test`.
In detail:
1. Start emacs.
2. `C-x C-b test ENTER`
3. `C-x C-b Test ENTER`
4. `C-x C-b *scratch* ENTER`
5. `C-x C-b test`
  Now helm will suggest `Test`, not `test` as first candidate.
  Expected behaviour: Prefer perfect match `test`

This bug is particularly annoying in LaTeX code, where (short) lowercase and uppercase macros are commonly used, and helm prefers upper case, which usually yields the wrong one.

### Somewhat off-topic question
Is there a binding which allows to insert a string as is? (Say `C-ENTER`. I did not see something in the help buffer.)
This would not solve the bugs, but provide a way to circumvent them if the whole thing was typed anyway.
In some situations, I find myself often picking the [?] option, which feels unnecessarily inefficient.

## Describe versions of Helm, Emacs, operating system, etc.
Tested on 26.3. Several debian-based OSs. Any version of helm tested, e.g. helm-20200429.

**Comment by thierryvolpiatto** [comment]
TBombadil <notifications@github.com> writes:

> Helm behaviour w.r.t. perfect matches and lower/upper case is unexpected.
> Expected behavior: Prefer perfect match.
> Actual behavior: Prefer capital case.
>
> Steps to reproduce (recipe)
>
> Run emacs-helm.sh.
> Create buffers test and Test.
> Then try to select to move to test.
> In detail:
>
>  1. Start emacs.
>  2. C-x C-b test ENTER
>  3. C-x C-b Test ENTER
>  4. C-x C-b *scratch* ENTER
>  5. C-x C-b test
>     Now helm will suggest Test, not test as first candidate.
>     Expected behaviour: Prefer perfect match test
>
> This bug is particularly annoying in LaTeX code, where (short)
> lowercase and uppercase macros are commonly used, and helm prefers
> upper case, which usually yields the wrong one.

This is not a bug, Capital letters appear always first unless you write
a sorting function that do the contrary, I see no reasons to do this,
having both "Test" and "test" appear and "Test" comes first is perfectly
fine.  That say you can change case-fold-search in helm by customizing
`helm-case-fold-search`, when you type "test", you will have only "test"
and when you type "Test" you will have only "Test".

> Somewhat off-topic question
>
> Is there a binding which allows to insert a string as is?

What do you mean by "a string as is"?

> (Say C-ENTER. I did not see something in the help buffer.)  This would
> not solve the bugs,

Which bugs?

> but provide a way to circumvent them if the whole thing was typed
> anyway.  In some situations, I find myself often picking the [?]
> option,

???

> which feels unnecessarily inefficient.

???

Don't understand this sorry, please elaborate.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Also if you use `helm-buffers-fuzzy-matching`, you will have a better sort fn and indeed, "test" will appear first.

**Comment by thierryvolpiatto** [comment]
I removed the old sort fn and use inconditionally the fuzzy one which works for both.

**Comment by TBombadil** [comment]
Thanks for the very quick fix! It now works as expected for buffers.
Strangely, for TeX-insert-macro, `Ref` is still before `ref`.
I tried `(setq helm-mode-fuzzy-match t)`, but no change.
I see that it's deprecated, and also tried `(setq completion-styles '(helm-flex))`, but no change either.

I don't know the right terminology, so by "insert string as is" I meant, the following:
In completion interfaces, e.g. helm-find-files, if I want to use whatever string `str` I entered (the "string as is"), I navigate to `[?] str` via C-p (assuming, there are still some matches.)
For example, using helm-find-files to create a new file `test` and a file `testing` already exists.
I was wondering if it is possible to bind the `[?]` choice to a key.
With LaTeX completion, this happens due to unrecognised macros. This happens a lot, so saving one C-p accumulates.

**Comment by thierryvolpiatto** [comment]
TBombadil <notifications@github.com> writes:

> Thanks for the very quick fix! It now works as expected for buffers.
> Strangely, for TeX-insert-macro, Ref is still before ref.
> I tried (setq helm-mode-fuzzy-match t), but no change.
> I see that it's deprecated, and also tried (setq completion-styles '(helm-flex)), but no change either.
>
> I don't know the right terminology, so by "insert string as is" I
> meant, the following: In completion interfaces, e.g. helm-find-files,
> if I want to use whatever string str I entered (the "string as is"), I
> navigate to [?] str via C-p (assuming, there are still some matches.)
> For example, using helm-find-files to create a new file test and a
> file testing already exists.

You can now customize `helm-ff-move-to-first-real-candidate` to always
be on first candidate.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Sorry, ignore previous post, I had to revert last changes because it breaks the logic of `helm-ff-update-when-only-one-matched` when this user var is nil.
Will see what I can do.
