### ISSUE TITLE
Enhancement: helm-source-names-using-follow equivalent without helm-follow-mode-persistent

### ISSUE THREAD

**Issue by chasecaleb** [emacs-helm/helm#2304]
**Is your feature request related to a problem? Please describe.**
As someone who does not want to use Emacs' custom, I want an equivalent to `helm-source-names-using-follow` that works without having to enable `helm-follow-mode-persistent`. I'll spare the tangent on why I don't use custom, but I know I'm far from the only one who avoids it.

**Describe the solution you'd like**
Either respect `helm-source-names-using-follow` all of the time, or provide an equivalent way of doing the same.

**Describe alternatives you've considered**
* Adding `(setq helm-follow-mode-persistent t)`, but I do not want custom to make changes anywhere (even to a separate custom file).
* Setting `follow` on helm sources programmatically, such as how I deal with it for helm-exwm. However this is more complicated than it should be and of course only works when I invoke my wrapper function.
    ```
    ;; This is assigned to a keybind
    (defun cc/helm-exwm-follow (&optional filter)
        "Like `helm-exwm', but with follow set."
        (let ((source (helm-exwm-build-source filter)))
          (helm-attrset 'follow 1 source)
          (helm :sources source :buffer "*helm-exwm*")))
    ```

**Comment by thierryvolpiatto** [comment]
Caleb Chase <notifications@github.com> writes:

> Is your feature request related to a problem? Please describe.
> As someone who does not want to use Emacs' custom,

Sorry, but I am not going to work on something because you don't like
custom, custom is a wonderful feature and I use it.


-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
