### ISSUE TITLE
Helm-M-x emacs command history shows duplicate entries

### ISSUE THREAD

**Issue by andersjohansson** [emacs-helm/helm#2305]
## Expected behavior
The "Emacs command history" source in `helm-M-x` shows only one match for each command. At least this has been the behaviour for me up until some recent changes in helm.

## Actual behavior
The "Emacs command history" source in `helm-M-x` shows several matches (all entries in `extended-command-history`.
![Skärmbild från 2020-05-07 18-53-00](https://user-images.githubusercontent.com/846411/81323323-7ffc7600-9095-11ea-85ed-5a9385d05549.png)

## Steps to reproduce (recipe)
Run emacs, install helm, run some commands with `helm-M-x`.
## Describe versions of Helm, Emacs, operating system, etc.

helm-20200506.729 from melpa
GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.10) of 2019-08-29
Linux 5.4.36-1-lts x86_64 GNU/Linux

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):
No. I used [emacs-sandbox](https://github.com/alphapapa/alpha-org/blob/master/emacs-sandbox.sh), called like this: `emacs-sandbox -d .emacs.d-helm-test/ -i helm -O`
This basically runs emacs -Q and installs helm (and dependencies) from melpa.

I found it difficult to use `emacs-helm.sh` since I don’t normally use `package.el` (but rather [straight.el](https://github.com/raxod502/straight.el)) as package manager.

**Comment by manuel-uberti** [comment]
Could it something similar to https://github.com/emacs-helm/helm/issues/2291

**Comment by thierryvolpiatto** [comment]
Manuel Uberti <notifications@github.com> writes:

> Could it be something similar to #2291

Yes, perhaps some old helm-command.elc ...?

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.*


-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Anders Johansson <notifications@github.com> writes:

> The "Emacs command history" source in helm-M-x shows several matches (all entries in extended-command-history.

helm-M-x obey now to history variables, did you set
history-delete-duplicates as described in #2291?

or perhaps a old elc file somewhere?

> I found it difficult to use emacs-helm.sh since I don’t normally use
> package.el (but rather straight.el) as package manager.

Yes, you are not the first to report dificulties with straight.el, I
don't know how to fix it though, did you try with

EMACSLOADPATH="/path/to/emacs-async:" ./emacs-helm.sh

Where straight.el is installing packages?

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by manuel-uberti** [comment]
> Where straight.el is installing packages?

See: [What does this look like on disk?](https://github.com/raxod502/straight.el#what-does-this-look-like-on-disk)

**Comment by thierryvolpiatto** [comment]
Manuel Uberti <notifications@github.com> writes:

>     Where straight.el is installing packages?
>    
> See: What does this look like on disk?

Thanks for the link ;-)

> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.*


-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by andersjohansson** [comment]
> helm-M-x obey now to history variables, did you set history-delete-duplicates as described in #2291? or perhaps a old elc file somewhere?

Oh, of course. My `history-delete-duplicates` was nil. This is not a bug, just changed helm behaviour (to the better it could be argued). Sorry for the noise and for missing #2291 (and thanks for helm!).

> Yes, you are not the first to report dificulties with straight.el, I
don't know how to fix it though, did you try with
> EMACSLOADPATH="/path/to/emacs-async:" ./emacs-helm.sh

This seems to work! Will use it if I need to debug helm in the future.
In more detail:
```sh
cd ~/.emacs.d/straight/repos/helm
make
EMACSLOADPATH="../emacs-async:" ./emacs-helm.sh 
```
