### ISSUE TITLE
helm-grep-action does not include user name in tramp sessions

### ISSUE THREAD

**Issue by ronievron** [emacs-helm/helm#2307]
The current code constructs the tramp-prefix using the method and host only, leaving out the user name.
The line in question is
(tramp-prefix (concat "/" tramp-method ":" tramp-host ":"))
Rather than extract the various components and then put them back together, it's possible to call file-remote-p with nil to get the entire prefix.
Please see proposed change below.

Thanks,

Roni

diff --git a/helm-grep.el b/helm-grep.el
index 43b491e3..2ede3743 100644
--- a/helm-grep.el
+++ b/helm-grep.el
@@ -617,13 +617,14 @@ WHERE can be one of other-window, other-frame."
                                        helm-buffer)
                                  (get-text-property (point-at-bol) 'helm-grep-fname))
                                (car split)))
-         (tramp-method (file-remote-p (or helm-ff-default-directory
-                                          default-directory) 'method))
-         (tramp-host   (file-remote-p (or helm-ff-default-directory
-                                          default-directory) 'host))
-         (tramp-prefix (concat "/" tramp-method ":" tramp-host ":"))
-         (fname        (if tramp-host
-                           (concat tramp-prefix loc-fname) loc-fname)))
+         (tramp-fname (file-remote-p (or helm-ff-default-directory
+                                          default-directory) nil))
+         (fname        (if tramp-fname
+                           (concat tramp-fname loc-fname) loc-fname)))
+
+    
+    (helm-log "helm-grep-action fname: %s" fname )
+
     (cl-case where
       (other-window (helm-window-show-buffers
                      (list (find-file-noselect fname)) t))

**Comment by thierryvolpiatto** [comment]
ronievron <notifications@github.com> writes:

> Please see proposed change below.

Your patch is unreadable, can you please format it properly?

Thanks.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
I guess what you want is something like this:

```elisp
diff --git a/helm-grep.el b/helm-grep.el
index 43b491e3..b5c54c17 100644
--- a/helm-grep.el
+++ b/helm-grep.el
@@ -618,10 +618,19 @@ WHERE can be one of other-window, other-frame."
                                  (get-text-property (point-at-bol) 'helm-grep-fname))
                                (car split)))
          (tramp-method (file-remote-p (or helm-ff-default-directory
-                                          default-directory) 'method))
+                                          default-directory)
+                                      'method))
          (tramp-host   (file-remote-p (or helm-ff-default-directory
-                                          default-directory) 'host))
-         (tramp-prefix (concat "/" tramp-method ":" tramp-host ":"))
+                                          default-directory)
+                                      'host))
+         (tramp-user   (file-remote-p (or helm-ff-default-directory
+                                          default-directory)
+                                      'user))
+         (tramp-prefix (concat "/" tramp-method ":"
+                               (if tramp-user
+                                   (format "%s@%s" tramp-user tramp-host)
+                                 tramp-host)
+                               ":"))
          (fname        (if tramp-host
                            (concat tramp-prefix loc-fname) loc-fname)))
     (cl-case where
```

**Comment by ronievron** [comment]
Sorry about the format.  
Your patch will work, but here's my version which is simpler.

diff --git a/helm-grep.el b/helm-grep.el
index 43b491e3..2ede3743 100644
--- a/helm-grep.el
+++ b/helm-grep.el
@@ -617,13 +617,14 @@ WHERE can be one of other-window, other-frame."
                                        helm-buffer)
                                  (get-text-property (point-at-bol) 'helm-grep-fname))
                                (car split)))
-         (tramp-method (file-remote-p (or helm-ff-default-directory
-                                          default-directory) 'method))
-         (tramp-host   (file-remote-p (or helm-ff-default-directory
-                                          default-directory) 'host))
-         (tramp-prefix (concat "/" tramp-method ":" tramp-host ":"))
-         (fname        (if tramp-host
-                           (concat tramp-prefix loc-fname) loc-fname)))
+         (tramp-fname (file-remote-p (or helm-ff-default-directory
+                                          default-directory) nil))
+         (fname        (if tramp-fname
+                           (concat tramp-fname loc-fname) loc-fname)))
+
+    
+    (helm-log "helm-grep-action fname: %s" fname )
+
     (cl-case where
       (other-window (helm-window-show-buffers
                      (list (find-file-noselect fname)) t))

**Comment by ronievron** [comment]
Sorry about the format.  Your patch will work, but my version is a bit simpler.

```
diff --git a/helm-grep.el b/helm-grep.el
index 43b491e3..2ede3743 100644
--- a/helm-grep.el
+++ b/helm-grep.el
@@ -617,13 +617,14 @@ WHERE can be one of other-window, other-frame."
                                        helm-buffer)
                                  (get-text-property (point-at-bol) 'helm-grep-fname))
                                (car split)))
-         (tramp-method (file-remote-p (or helm-ff-default-directory
-                                          default-directory) 'method))
-         (tramp-host   (file-remote-p (or helm-ff-default-directory
-                                          default-directory) 'host))
-         (tramp-prefix (concat "/" tramp-method ":" tramp-host ":"))
-         (fname        (if tramp-host
-                           (concat tramp-prefix loc-fname) loc-fname)))
+         (tramp-fname (file-remote-p (or helm-ff-default-directory
+                                          default-directory) nil))
+         (fname        (if tramp-fname
+                           (concat tramp-fname loc-fname) loc-fname)))
+
+    
+    (helm-log "helm-grep-action fname: %s" fname )
+
     (cl-case where
       (other-window (helm-window-show-buffers
                      (list (find-file-noselect fname)) t))

```

**Comment by thierryvolpiatto** [comment]
ronievron <notifications@github.com> writes:

> Sorry about the format. Your patch will work, but my version is a bit
> simpler.

Thanks, merged.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
