### ISSUE TITLE
helm-boring-directory-p does not return when used with a Windows path format

### ISSUE THREAD

**Issue by Grandmaster3000** [emacs-helm/helm#2308]
## Steps to reproduce (recipe)
```elisp
(helm-boring-directory-p "c:/Windows" '("32$"))`
```

It seems that the exit condition in helm-boring-directory-p is never met due to the Windows path format. This does not exit the path traversal on Windows:
```elisp
(when (string= it "/") (cl-return nil))
```

Because of this behaviour the recursive search functionality in a helm-find-file session with the Everything backend es.exe does not work, e.g:

```elisp
(let ((helm-locate-recursive-dirs-command "es -path \"%s\" -r %s"))
  (make-directory "D:/tmp/foo/bar" t)
  (helm-find-files-recursive-dirs "D:/tmp/foo" "bar"))
```

My current fix for the mentioned exit condition looks like this:
```elisp
(when (or (string= it "/")
              (and (eq system-type 'windows-nt)
                   (eq (length it) 3)))
      (cl-return nil))
```

I am using the latest helm version 20200510.1345.
And by the way. Great work. Love the package. Write me, if you need some testing on Windows!

**Comment by thierryvolpiatto** [comment]
Grandmaster3000 <notifications@github.com> writes:

> Steps to reproduce (recipe)
>
> (helm-boring-directory-p "c:/Windows" '("32$"))

Isn't `(helm-boring-directory-p "c:/Windows32" '("32$"))` you want to
test?
Or perhaps `(expand-file-name "c:/Windows")` is expanding to
"c:/Windows32"?

Sorry, I have no Windows box to test against and my Windows knowledge is
limited.

>
> It seems that the exit condition in helm-boring-directory-p is never
> met due to the Windows path format. This does not exit the path
> traversal on Windows: (when (string= it "/") (cl-return nil))

Yes, make sense, looks wrong.

> My current fix for the mentioned exit condition looks like this:
> (when (or (string= it "/") (and (eq system-type 'windows-nt) (eq (length it) 3))) (cl-return nil))

Isn't `(when (string-match "\\`[A-Za-z]?:?/\\'" it)...` better?
Is it working for you?

> I am using the latest helm version 20200510.1345.  And by the
> way. Great work. Love the package. Write me, if you need some testing
> on Windows!

Thanks.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by Grandmaster3000** [comment]
Thanks for the fast response and your right:

```elisp
(when (string-match "\\`[A-Za-z]?:?/\\'" it) (cl-return nil))
```

... is better, because it is shorter and faster as well.

One additional thought so: the above regex matches Windows style pathnames
with /slashes/. But also backslashes are valid on Windows:

"C:/" same as "C:\\"

With this in mind it would be even better to include the backslashes to be even
more flexible in terms of possible backends on Windows:
```elisp
(when (string-match "\\`[A-Za-z]?:?[/\\]\\'" it)  (cl-return nil))
```

Both solutions are working fine for me.

**Comment by thierryvolpiatto** [comment]
Grandmaster3000 <notifications@github.com> writes:

> Thanks for the fast response and your right:
>
> (when (string-match "\\`[A-Za-z]?:?/\\'" it) (cl-return nil))
>
> ... is better, because it is shorter and faster as well.
>
> One additional thought so: the above regex matches Windows style pathnames
> with /slashes/. But also backslashes are valid on Windows:
>
> "C:/" same as "C:\"
>
> With this in mind it would be even better to include the backslashes to be even
> more flexible in terms of possible backends on Windows:
>
> (when (string-match "\\`[A-Za-z]?:?[/\\]\\'" it)  (cl-return nil))

I am not sure this could happen as inside emacs only slashes are used on
Windows IIRC (correct me if wrong).

> Both solutions are working fine for me.

Ok, so let's try the regexp without backslashes, if you encounter a
problem with this let me know, we will see what we can do.

Thanks!

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by Grandmaster3000** [comment]
Works like a charm. Thank you.
