### ISSUE TITLE
Empty candidates list in helm-find-files when typing quickly, remote path

### ISSUE THREAD

**Issue by obar** [emacs-helm/helm#2309]
## Expected behavior

Using `helm-find-files` for a remote path with tramp should work as if local.

## Actual behavior (from `emacs-helm.sh`)

If typing quickly (faster than the helm selections are filtered), multiple tramp commands are run and some seem to fail. Seems to apply to both ssh and scp.

## Steps to reproduce (recipe)

1. Starting with `emacs-helm.sh`, `(setq tramp-verbose 6)`
2. Type `C-x C-f /ssh:$REMOTE:/`. The root directory is now listed as options.
3. Typing faster than helm updates candidate list: `ww`
4. It should complete for `www` path which exists in root, but instead a blank list of completions is shown. Some tramp calls have failed, see the backtraces section for debug info from this operation.
5. Backspace so input is now `/ssh:$REMOTE:/w`, and candidates list now shows `www` and `swapfile` as completions.

## Possible solutions?

I have played with some ssh options like ControlMaster and could not address the issue that way. `tramp-connection-min-time-diff` also doesn't seem to affect the results.

I don't know how the internals compare with `counsel-find-file`, but using that for the same operation feels the same for a remote path as a local path regardless of typing speed.

From reading through past github issues and posts I've read suggestions of increasing `helm-input-idle-delay` which adds some latency for all operations, but does make it harder for this to happen. Is this the best fix, and if so what's the difference that `counsel-find-file` leverages?

Is there some other setting I've missed? Perhaps something to do with tramp or error handling there?

## Backtraces if any (`M-x toggle-debug-on-error`)
From watching the `*tramp/ssh $REMOTE*` buffer while performing the above, it's clear that at the failing step a directory listing is returned with unrelated lines appended below, which aren't there if typing slowly:

```
...
/ssh:$REMOTE:/"usr"/
/ssh:$REMOTE:/"var"/
/ssh:$REMOTE:/"vmlinux"@
/ssh:$REMOTE:/"vmlinux.old"@
/ssh:$REMOTE:/"www"/
tramp_exit_status 0
///832ce6935d5af6e8b4bed3804b9f7a17#$
```

The whole operation's output in the `*debug tramp/ssh $REMOTE*` buffer:

```
10:50:23.259576 tramp-file-name-handler (5) # Non-essential received in operation (file-attributes /ssh:$REMOTE: integer)
10:50:23.259696 tramp-get-test-command (5) # Finding a suitable  test  command
10:50:23.259736 tramp-file-name-handler (5) # Non-essential received in operation (file-readable-p /ssh:$REMOTE:)
10:50:30.620014 tramp-send-command (6) # test -d / 2>/dev/null; echo tramp_exit_status $?
10:50:30.702846 tramp-wait-for-regexp (6) #
tramp_exit_status 0
///832ce6935d5af6e8b4bed3804b9f7a17#$
10:50:30.705369 tramp-do-file-attributes-with-stat (5) # file attributes with stat: /
10:50:30.705774 tramp-send-command (6) # ( (test -e / || test -h /) && (env QUOTING_STYLE=locale \stat -c '((/////%N/////) %h /////%U///// /////%G///// %Xe0 %Ye0 %Ze0 %se0 /////%A///// t %ie0 -1)' / | sed -e 's/"/\\"/g' -e 's/\/\/\/\/\//"/g') || echo nil) 2>/dev/null; echo tramp_exit_status $?
10:50:30.806445 tramp-wait-for-regexp (6) #
((" / ") 23 "root" "root" 1589618497e0 1588228455e0 1588228455e0 4096e0 "drwxr-xr-x" t 2e0 -1)
tramp_exit_status 0
///832ce6935d5af6e8b4bed3804b9f7a17#$
10:50:33.837691 tramp-send-command (6) # test -d /w 2>/dev/null; echo tramp_exit_status $?
10:50:33.923192 tramp-wait-for-regexp (6) #
tramp_exit_status 1
///832ce6935d5af6e8b4bed3804b9f7a17#$
10:50:33.960399 tramp-send-command (6) # test -e /w 2>/dev/null; echo tramp_exit_status $?
10:50:34.013797 tramp-wait-for-regexp (6) #
tramp_exit_status 1
///832ce6935d5af6e8b4bed3804b9f7a17#$
10:50:34.039582 tramp-send-command (6) # test -d /ww 2>/dev/null; echo tramp_exit_status $?
10:50:34.046996 tramp-wait-for-regexp (6) #
tramp_exit_status 1
///832ce6935d5af6e8b4bed3804b9f7a17#$
10:50:47.241789 tramp-send-command (6) # test -d /w 2>/dev/null; echo tramp_exit_status $?
10:50:47.324709 tramp-wait-for-regexp (6) #
tramp_exit_status 1
///832ce6935d5af6e8b4bed3804b9f7a17#$
10:51:17.375524 tramp-send-command (6) # test -d / 2>/dev/null; echo tramp_exit_status $?
10:51:17.460838 tramp-wait-for-regexp (6) #
tramp_exit_status 0
///832ce6935d5af6e8b4bed3804b9f7a17#$
```

## Describe versions of Helm, Emacs, operating system, etc.

helm 20200515.715 with tramp 2.4.3.4 on Emacs 26.2, Ubuntu 18.10.

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):

Yes

## Are you using Spacemacs? (yes/no):

No

**Comment by thierryvolpiatto** [comment]
Ori <notifications@github.com> writes:

> Expected behavior
>
> Using helm-find-files for a remote path with tramp should work as if local.

> Possible solutions?

> I don't know how the internals compare with counsel-find-file, but
> using that for the same operation feels the same for a remote path as
> a local path regardless of typing speed.

I don't know how counsel-find-file works, but I guess it is using a lazy
update with a simple function using directory-files.
Helm is using by default a fast function but that function works only if
both end are using a GNU ls version, see `helm-list-directory-function`.

> From reading through past github issues and posts I've read
> suggestions of increasing helm-input-idle-delay which adds some
> latency for all operations, but does make it harder for this to
> happen.

It may as tramp don't like repeated call in a short delay.
Try for example to type C-! before typing your "www" and then type again
C-!.

> Is this the best fix, and if so what's the difference that
> counsel-find-file leverages?

As I say I don't know counsel, but last time I checked, it was handling
only directories and files, helm is trying to show symlinks, executables
etc... which takes much more ressources.

> Is there some other setting I've missed?

Perhaps try to customize `helm-list-directory-function`?

> Perhaps something to do with tramp or error handling there?

No, tramp is slow, don't think you can do much here.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by obar** [comment]
> Perhaps try to customize `helm-list-directory-function`?

Both ends are using GNU ls, I did try the other approach but with no luck.

> It may as tramp don't like repeated call in a short delay.

Yes that is the root of it. It seems that the tramp buffer has 'spilling over' from one call into the second, is that a correct assessment based on what I see (first code block of the Backtraces section of the bug report)? Perhaps this is a Tramp issue, or if it's expected behavior could those additional lines at the end be ignored by Helm in some way?

**Comment by thierryvolpiatto** [comment]
Ori <notifications@github.com> writes:

>     Perhaps try to customize helm-list-directory-function?
>    
> Both ends are using GNU ls, I did try the other approach but with no luck.
>
>     It may as tramp don't like repeated call in a short delay.
>    
> Yes that is the root of it.

See `helm-process-deferred-sentinel-hook` comments and
`tramp-connection-min-time-diff` docstring.
Perhaps nowaday we could let-bind `tramp-connection-min-time-diff` to a
lower value (or a customizable value).

> It seems that the tramp buffer has 'spilling over' from one call into
> the second, is that a correct assessment based on what I see (first
> code block of the Backtraces section of the bug report)?

Sorry I couldn't find what mean 'spilling over', could you change your
wording to some more basic english (sorry for my bad english).

> Perhaps this is a Tramp issue, or if it's expected behavior could
> those additional lines at the end be ignored by Helm in some way?

What do you mean by additional lines ?
Perhaps you mean limiting the number of candidates ?
See `helm-ff-candidate-number-limit` and
`helm-ff-up-one-level-preselect`.
Perhaps we could make `helm-ff-up-one-level-preselect` nil when working
remote (configurable)?

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by obar** [comment]
>> It seems that the tramp buffer has 'spilling over' from one call into the second, is that a correct assessment based on what I see (first code block of the Backtraces section of the bug report)?
> Sorry I couldn't find what mean 'spilling over', could you change your wording to some more basic english (sorry for my bad english).

Je suis désolé :) Your English is perfect but that was poor wording on my part.

I can see changes by having the `*tramp/ssh $REMOTE*` buffer open while in `helm-find-files`. Normally this is a directory listing. When helm is blank because of too many tramp commands in a short span of time, that buffer has the same directory listing *and* 2 extra lines at the end:

```
...
/ssh:$REMOTE:/"usr"/
/ssh:$REMOTE:/"var"/
/ssh:$REMOTE:/"vmlinux"@
/ssh:$REMOTE:/"vmlinux.old"@
/ssh:$REMOTE:/"www"/
tramp_exit_status 0                      <<< Extra line
///832ce6935d5af6e8b4bed3804b9f7a17#$    <<< Extra line
```

If the extra lines could be ignored, would the helm listing work?

**Comment by gahag** [comment]
+1, I'm affected by this issue too, and it is annoying. I'm having the impression that helm runs the remote `ls` every time we type something. Maybe it would be better if the ls output was cached?

**Comment by thierryvolpiatto** [comment]
gahag <notifications@github.com> writes:

> +1, I'm affected by this issue too, and it is annoying. I'm having the
> impression that helm runs the remote ls every time we type
> something. Maybe it would be better if the ls output was cached?

I just pushed a old local branch rebased, have a try and let me know, it
is HFF_cache.
Note that you may want to C-c C-u when you want to refresh the list of
current directory. Also the cache is cleared after each HFF session.
Note also that you will suffer from the same problem at first visit of a
directory, but subsequent filtering will immediately benefit from the
cache.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by gahag** [comment]
That sounds great! I'll check it by monday. Thanks for your work on this.

**Comment by thierryvolpiatto** [comment]
Merged to master.

**Comment by gahag** [comment]
Works like a charm. Thank you for your amazing work on Helm.

**Comment by thierryvolpiatto** [comment]
gahag <notifications@github.com> writes:

> Works like a charm. Thank you for your amazing work on Helm.

Thanks for the feedback, I have just added a little mode that refresh
the cache (when helm-ff-keep-cached-candidates is non nil) of previous
session when emacs is idle.
To test: 
1) (setq helm-ff-keep-cached-candidates t) 
2) M-x helm-ff-cache-mode RET
3) launch helm-find-files, navigate to some directories and quit.
4) Open a shell and touch a file say foo.txt in one of those
directories.
5) after being idle a few seconds, start back HFF, you should see your
touched file :-).

Warning! Experimental!

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by obar** [comment]
Thanks for the patch Thierry! This does a lot towards fixing the bug for me. I can still type quickly to get tramp failing due to command collisions (`test -d` and `test -e` being called as I type), but the candidates are still shown so it doesn't seem to be a problem.

Sometimes by switching into a directory with `C-j` too soon after typing, that tramp collision occurs and the candidates list is empty (and this time, stays empty due to the cache). `C-c C-u` does not always fix it. At that point only candidate is `[?] valid-dir`, with the minibuffer showing `/ssh:$REMOTE:/path-to/valid-dir/`. If I start typing a file I know to exist in valid-dir, then it does work. Or, if I hit `TAB TAB` (viewing the actions and then returning to where I was), and *then* `C-c C-u`, it refreshes.

These collisions and the problems in helm seem to still be related to recovering from errors in tramp, which is not the fault of helm. There are still the extra lines in a tramp buffer which I suspect could be ignored... though I don't know where that ignoring should happen.

All that said, it's not hard to wait a moment once the completion is there, before entering the directory, and then there is no problem. Overall, helm-find-files is much smoother with this patch. Thanks again :)

**Comment by thierryvolpiatto** [comment]
Ori <notifications@github.com> writes:

> Thanks for the patch Thierry! This does a lot towards fixing the bug for me. I can still type quickly to get tramp failing due to command collisions (test -d and test -e
> being called as I type), but the candidates are still shown so it doesn't seem to be a problem.
>
> Sometimes by switching into a directory with C-j too soon after typing, that tramp collision occurs and the candidates list is empty (and this time, stays empty due to the
> cache). C-c C-u does not always fix it. At that point only candidate is [?] valid-dir, with the minibuffer showing /ssh:$REMOTE:/path-to/valid-dir/. If I start typing a
> file I know to exist in valid-dir, then it does work. Or, if I hit TAB TAB (viewing the actions and then returning to where I was), and then C-c C-u, it refreshes.
>
> These collisions and the problems in helm seem to still be related to recovering from errors in tramp, which is not the fault of helm. There are still the extra lines in a
> tramp buffer which I suspect could be ignored... though I don't know where that ignoring should happen.
>
> All that said, it's not hard to wait a moment once the completion is
> there, before entering the directory, and then there is no
> problem. Overall, helm-find-files is much smoother with this
> patch. Thanks again :)

Thanks for the feedback, yes it is not perfect, but it is now better,
however we do what we can with tramp which is slow whatever we do in
helm.
If you work a lot with remote machines, have a try to sshfs which is
much better (you navigate with HFF just like on your local sys).

Thanks.


-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
