### ISSUE TITLE
Fuzzy finding stops with hyphens on helmM-x

### ISSUE THREAD

**Issue by juacq97** [emacs-helm/helm#2310]
## Expected behavior
When I type on Helm-M-x, helm should match both sides of a string separated by a hyphen. Example: `evalbu` should match `eval-buff`

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
Helm only match text before or after a hyphen, but not both sides. Example: `evalbu` match nothing (the buffer is blank)

## Steps to reproduce (recipe)
```lisp
(use-package helm
  :ensure t
  :bind (
	 ("M-x" . helm-M-x)
	 ("C-x C-f" . helm-find-files)
	 ("C-x b" . helm-buffers-list))
  :config
  (helm-mode 1))
(setq helm-mode-fuzzy-match t)
(setq helm-M-x-always-save-history t)
(setq helm-completion-in-region-fuzzy-match t)
```

Run `helm-M-x` and type

## Describe versions of Helm, Emacs, operating system, etc.
- Emacs 26.3
- Helm 20200517.509
- Arch Linux

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no): 
Yes

## Are you using Spacemacs? (yes/no): 
No, just vanilla emacs and my config file

**Comment by thierryvolpiatto** [comment]
Juan Adrián Castro Quintana <notifications@github.com> writes:

> Expected behavior
>
> When I type on Helm-M-x, helm should match both sides of a string
> separated by a hyphen. Example: evalbu should match eval-buff

You have to use a flex completion-style:

    (use-package helm-mode
      :init
      (add-hook 'helm-mode-hook
                (lambda ()
                  (setq completion-styles
                        (cond ((assq 'helm-flex completion-styles-alist)
                               '(helm-flex))
                              ((assq 'flex completion-styles-alist)
                               '(flex))))))
      :config
      (helm-mode 1))

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
![Capture d’écran_2020-05-19_06-09-04](https://user-images.githubusercontent.com/1533939/82283994-331f7600-9998-11ea-834b-023ec6e054e4.png)

**Comment by thierryvolpiatto** [comment]
Also don't use `(use-package helm)`.
See https://github.com/emacs-helm/helm/wiki#configure
