### ISSUE TITLE
helm-buffers-list broken with emacs-master (emacs-28)

### ISSUE THREAD

**Issue by thierryvolpiatto** [emacs-helm/helm#2311]
## Expected behavior

No error when listing hidden buffers.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

See https://github.com/emacs-helm/helm-ls-git/issues/58

**Comment by manuel-uberti** [comment]
Just to confirm here too: you commit fixed it for me.

**Comment by innerout** [comment]
I can confirm this is fixed with the latest commit.

**Comment by thierryvolpiatto** [comment]
Thanks both to confirm, closing now.
