### ISSUE TITLE
Helm M-x UI freezes/stutters when typing quickly

### ISSUE THREAD

**Issue by wilkystyle** [emacs-helm/helm#2312]
## Expected behavior
Characters appear in the minibuffer for `helm-M-x` as soon as I type them, results appear without blocking minibuffer input.

## Actual behavior
After upgrading all my packages for the first time in a while, I noticed the following: When typing quickly, the Helm UI will pause and stutter before the remaining text and results appear. (I explain additional troubleshooting/debugging steps at the end)

## Steps to reproduce (recipe)
1. Engage `helm-M-x`
2. Type a word (e.g. `shell`) very quickly in the minibuffer.
3. Observe that the UI pauses after the first letter or two, then displays the remaining characters typed in the minibuffer as well as the filtered results.

## Backtraces if any (`M-x toggle-debug-on-error`)
N/A

### Operating System
MacOS Catalina 10.15.4

### Emacs
GNU Emacs 28.0.50 (build 1, x86_64-apple-darwin19.3.0, NS appkit-1894.30 Version 10.15.3 (Build 19D76)) of 2020-02-25 (`emacs-plus` package installed via Homebrew)

### Helm
From `master` branch, commits in-use detailed in **Troubleshooting/debugging** section below.

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):
No

## Are you using Spacemacs? (yes/no):
No

## Troubleshooting/debugging
I started by trimming down my `init.el` to only include a basic Helm installation via [use-package](https://github.com/jwiegley/use-package):

```lisp
(use-package helm
  :bind (("M-x" . helm-M-x))
  :config
  (helm-mode 1))
```

I then used `git bisect` with a known "good" commit in order to narrow down where the issue appeared for me:

* [05d70ff](https://github.com/emacs-helm/helm/commit/05d70ff116a696f5c18e5ad569573d8936ff01da) is the last "good" commit—where the minibuffer and Helm UI are fast and responsive.
* The very next commit, [1ecefa3](https://github.com/emacs-helm/helm/commit/1ecefa3840aa5bdd8d4959d2c4efd3ea0e433f64), is where the problem appears (and is present all the way to the latest commit on `master`)

## Examples

The previous "good" behavior, up until commit `05d70ff1` (notice how the letters s-h-e-l-l appear as they are typed, and the results filter in real-time):

![helm-at-05d70ff1](https://user-images.githubusercontent.com/1310533/83307650-335b1500-a1d3-11ea-9704-d46ae8c19dc4.gif)

The "bad" behavior, on commit `1ecefa38` (notice how `s` appears, the UI pauses, then `hell` appears along with the filtered results):

![helm-at-1ecefa3](https://user-images.githubusercontent.com/1310533/83307770-669da400-a1d3-11ea-87ba-b7f4e5e8cb2f.gif)

**Comment by thierryvolpiatto** [comment]
Mike Wilkerson <notifications@github.com> writes:

> Expected behavior
>
> Characters appear in the minibuffer for helm-M-x as soon as I type them, results appear without blocking minibuffer input.
>
> Actual behavior
>
> After upgrading all my packages for the first time in a while, I
> noticed the following: When typing quickly, the Helm UI will pause and
> stutter before the remaining text and results appear. (I explain
> additional troubleshooting/debugging steps at the end)

I couldn't reproduce from emacs-helm.sh (tried on emacs-26.3 and on
emacs-28), please try from emacs-helm.sh (use -P option to specify emacs
path).  See
https://github.com/emacs-helm/helm/wiki#quick-try-with-emacs-helmsh

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by wilkystyle** [comment]
Thanks for the speedy response and efforts to reproduce!

I just tried with `emacs-helm.sh`, and the problem is still present. When you tried with emacs-26.3 and emacs-28, was that on MacOS? So far I've been able to reproduce across a 2018 MacBook Pro, a 2020 MacBook Air, and a friend confirmed the same on his 2014 retina MacBook Pro.

The common denominator so far seems to be MacOS + GUI emacs, installed via Homebrew (`brew install emacs-plus`).

**Comment by thierryvolpiatto** [comment]
Mike Wilkerson <notifications@github.com> writes:

> Thanks for the speedy response and efforts to reproduce!
>
> I just tried with emacs-helm.sh, and the problem is still
> present. When you tried with emacs-26.3 and emacs-28, was that on
> MacOS?

No, I use a LinuxMint box on a Lenovo with a ryzen5 proc.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by manuel-uberti** [comment]
FWIW, I am using a 3-year old Dell XPS 13 with Ubuntu 20.04 LTS and I cannot reproduce this.

**Comment by wilkystyle** [comment]
I think this must have something to do specifically with the way Emacs is rendered in the GUI on MacOS. I've tried the `emacs-plus` and `emacs-mac` (tweaked version with alleged performance improvements) versions of GUI Emacs, and can replicate the issue in both. However, when I switch to terminal emacs in MacOS Helm is _lightning fast_—faster than GUI Emacs on the "good" commit (`05d70ff`) from my original report.

**Comment by thierryvolpiatto** [comment]
Mike Wilkerson <notifications@github.com> writes:

> I think this must have something to do specifically with the way Emacs
> is rendered in the GUI on MacOS. I've tried the emacs-plus and
> emacs-mac (tweaked version with alleged performance improvements)
> versions of GUI Emacs, and can replicate the issue in both. However,
> when I switch to terminal emacs in MacOS Helm is lightning fast
> —faster than GUI Emacs on the "good" commit (05d70ff) from my original
> report.

Thanks for these informations, good to know there is different Emacs
versions available on MacOs, unfortunately I can't help you, I never
used MacOs, perhaps somebody on this list have some experience with Mac
and can help?

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by wilkystyle** [comment]
Sounds good—appreciate your efforts all the same! Perhaps someone else will stumble across this and find it helpful. In the meantime, I can pin my Helm version to `05d70ff` as a workaround.

**Comment by BlueSpaceCanary** [comment]
I've stumbled on a (mabye?) related issue, though ironically it only appears when *not* using the GUI. I'm seeing flickering & stuttering across the entire frame while scrolling through `helm-occur` matches with follow enabled, but only when using `emacs -nw` or `emacsclient -t`. 

I reproduced on multiple OSes (MacOS and Linux), with my own config and with emacs-helm.sh, locally and over ssh, and with different terminal emulators. It's consistent on 26.3, but doesn't seem to happen at all on 27.1. I haven't had a chance to try emacs 28 yet, but I will update if I have the time to do that. It didn't seem to line up with the git bisect posted above but it's late and I haven't tested that thoroughly yet either.

I did run the profiler, but there wasn't really anything enlightening in it that I could see. I don't have time tonight but I can grab a more thorough pair of traces on on 26.3 vs 27.1 later this week if it'd be helpful

**Comment by BlueSpaceCanary** [comment]
I didn't really see an issue on emacs28, but attached are elp and native profiler outputs for 26 and 27 doing the same operations: open test file, turn off helm-mode, set up profiling with `C-c M-x` to avoid `helm-m-x` contaminating results, start helm-occur, type "load", hit `C-n` 20 times about twice a second, then `C-p` 10 times at roughly the same rate, then `RET`, then get profiler results, again avoiding `helm-m-x`. These weren't generated with emacs-helm.sh, but the only other thing that shows up at all that I saw was a few samples in doom-modeline. If I missed something I can try to grab some profiles through that as well

[26-CPU-Profiler-Report.txt](https://github.com/emacs-helm/helm/files/5204555/26-CPU-Profiler-Report.txt)
[27-CPU-Profiler-Report.txt](https://github.com/emacs-helm/helm/files/5204557/27-CPU-Profiler-Report.txt)
[27-ELP-Results.txt](https://github.com/emacs-helm/helm/files/5204558/27-ELP-Results.txt)
[26-ELP-Results.txt](https://github.com/emacs-helm/helm/files/5204559/26-ELP-Results.txt)

**Comment by sstepashka** [comment]
I have the same problem. I also tried to use native compilation and it made things only worse (helm-M-x perform really bad). I compared it to counsel-M-x and it flies. I can actually reproduce it even in terminal (iTerm2) but in GUI it's worse.

**Comment by sstepashka** [comment]
[elp.txt](https://github.com/emacs-helm/helm/files/6408784/elp.txt)

**Comment by thierryvolpiatto** [comment]
Dmitry Kuragin ***@***.***> writes:

> [[PGP Encrypted Part:OK]] I have the same problem. I also tried to use
> native compilation and it made things only worse (helm-M-x perform
> really bad). I compared it to counsel-M-x and it flies. I can actually
> reproduce it even in terminal (iTerm2) but in GUI it's worse.

I can't reproduce here, helm-M-x is instant when I type.
This on emacs-27.1, 27.2, 28.0.50 with and without native-compile.

The problem is maybe related to while-no-input we are using in helm and
the events occuring on your system.

What is the value of `while-no-input-ignore-events`?
If you are using emacs-28, two more events are usable now, see C-h n.

Are you using a clipboard manager?

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Also don't use preconfigured Emacs to reproduce e.g. spacemacs or doom.

**Comment by sstepashka** [comment]
while-no-input-ignore-events:
```
Its value is
(focus-in focus-out help-echo iconify-frame make-frame-visible selection-request)
```

```
This file is about changes in Emacs version 28.
```

I do not use any clipboard manager. Seems like, it's somehow related to Mac OS and Emacs relationships. 

In Terminal, I can type w/o any interruption, but results update really with large delay. Where, in GUI, version typing is interrupted.

Do you have any suggestion how can I debug it? I tried t reduce number of elements in `obarray` y by keeping only `commandp`, but seems like it's not really related to the number of elements and the issues is somewhere in rendering.

I reproduced the issue with minimal configuration like:
```
(package-initialize)

(require 'helm)
(helm-mode 1)

(define-key global-map [remap execute-extended-command] 'helm-M-x)
(define-key global-map [remap find-file] 'helm-find-files)
```

and emacs -Q -l test.el

**Comment by thierryvolpiatto** [comment]
Dmitry Kuragin ***@***.***> writes:

> [[PGP Encrypted Part:OK]]
> while-no-input-ignore-events:
>
> Its value is
> (focus-in focus-out help-echo iconify-frame make-frame-visible selection-request)
>
> This file is about changes in Emacs version 28.
>
> I do not use any clipboard manager. Seems like, it's somehow related to Mac OS and Emacs relationships.
>
> In Terminal, I can type w/o any interruption, but results update
> really with large delay. Where, in GUI, version typing is interrupted.

So it is slow in terminal and in GUI it freeze, right?

What about helm-apropos? Do you have similar issue?

> Do you have any suggestion how can I debug it?

Can you try with helm-M-x-use-completion-styles set to nil?


-- 
Thierry

**Comment by sstepashka** [comment]
It freezes for both (Terminal and GUI). It's the same in `helm-apropos` (slightly faster, but still very slow).

I tried `(setq helm-M-x-use-completion-styles nil`. It didn't help.

**Comment by thierryvolpiatto** [comment]
Dmitry Kuragin ***@***.***> writes:

> It freezes for both (Terminal and GUI). It's the same in helm-apropos (slightly faster, but still very slow).
>
> I tried (setq helm-M-x-use-completion-styles nil. It didn't help.

So I am afraid it is specific to your platform and I cannot do much for
this.

-- 
Thierry

**Comment by sstepashka** [comment]
I have little benchmark:
```
(defun my--test-function ()
  (helm-match-from-candidates
 (all-completions "" (cl-remove-if-not #'commandp obarray))
 '(helm-fuzzy-match)
 nil
 50
 (helm-build-sync-source "Code Search"
   :candidates (all-completions "" (cl-remove-if-not #'commandp obarray))
   :action nil
   :candidate-number-limit 50
   )))

(benchmark-run 10 (my--test-function))
```

on stable (27.2 from emacsformacos.org) it took 0.086294
on the buggy (native compilation from master) it took 0.743127

I will try to investigate more.

**Comment by sstepashka** [comment]
Basically it has nothing todo with helm: 
```
(defun my--all-completions-test-function ()
  (completion-all-completions "kill" obarray #'symbolp 0))

(benchmark-run 20 (my--all-completions-test-function))
```

**Comment by sstepashka** [comment]
Could this guy be a problem https://github.com/emacs-mirror/emacs/commit/0ce2f591ff9acd8cfb0944d0de95723e7db0d6f0?

**Comment by sstepashka** [comment]
The issue is gone with on older commit: https://github.com/emacs-mirror/emacs/commit/6b2d017ead856c244a0b5c5a162254094877bc54

**Comment by sstepashka** [comment]
Sorry, but actually it started to work better when I disable native compilation for helm by
```
(add-to-list 'comp-deferred-compilation-deny-list "helm")
```

**Comment by sstepashka** [comment]
@thierryvolpiatto TIL: You must run the same version of emacs you used to compile helm. Here's what happen (I assume):

I update the emacs to use native compilation, but I didn't clean up old "etc" files. Emacs started to do native compilation on top of outdated .elc files and the result was very slow (but it worked). When I checked out the git repo and used `make` to compile it was OK, then I opened emacs (of course not the one I just compiled from master with native compilation) it triggered native compilation for the outdated .elc again. 

The problem with MacOS is when we build new `Emacs.app`, it's not being integrated into environment and default (system wide) emacs might be not the same we have right now.

**Comment by thierryvolpiatto** [comment]
Dmitry Kuragin ***@***.***> writes:

> [[PGP Encrypted Part:OK]]
> @thierryvolpiatto TIL: You must run the same version of emacs you used to compile helm. Here's what happen (I assume):
>
> I update the emacs to use native compilation, but I didn't clean up
> old "etc" files. Emacs started to do native compilation on top of
> outdated .elc files and the result was very slow (but it worked). When
> I checked out the git repo and used make to compile it was OK, then I
> opened emacs (of course not the one I just compiled from master with
> native compilation) it triggered native compilation for the outdated
> .elc again.

Yes, it is generally better to compile with the same emacs, seems it is
specially true with native compile.
Normally without native compile emacs works (most of the time) with
compiled files compiled with an emacs below the one you use but not the
contrary. e.g. compiled files under 27.2 work with 28.0.50 but not the
contrary. But now it seems we must (re)compile all with native comp.

> The problem with MacOS is when we build new Emacs.app, it's not being
> integrated into environment and default (system wide) emacs might be
> not the same we have right now.

Glad you found what's wrong with MacOS.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Here a record with emacs 28 native compiled on LinuxMint:

![Peek 05-05-2021 07-37](https://user-images.githubusercontent.com/1533939/117100927-542dd200-ad75-11eb-875b-1b45d753e0ae.gif)

As you can see helm works fine in this environment.
Please compile helm as described above by @sstepashka and do not use preconfigured emacs (e.g. spacemacs or doom).

**Comment by bard** [comment]
I uninstalled and reinstalled `helm` and `helm-core`, to make sure they would be compiled with the same version of Emacs I'm using, as per https://github.com/emacs-helm/helm/issues/2312#issuecomment-831698867. Problem persisted.

Then I disabled native compilation for Helm, as per https://github.com/emacs-helm/helm/issues/2312#issuecomment-831425044, and removed the corresponding `*.eln` file from `eln-cache` just in case. Problem persisted.

(Problem in this case being not only UI stutter, but extra input, as per https://github.com/emacs-helm/helm/issues/2411.)

Using Arch Linux.

**Comment by Chaformbintrano** [comment]
I removed eln-cache, added helm to the deny list and it didn't help.

**Comment by thierryvolpiatto** [comment]
Chaformbintrano ***@***.***> writes:

> [[PGP Encrypted Part:OK]]
> I removed eln-cache, added helm to the deny list and it didn't help.

This is not the problem, I use here native-compile with helm without any
problems, it runs full speed, for helm-M-x and else, I guess the problem
is outside helm, maybe platform related, at least many people with MacOs
complain about this.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Massimiliano Mirra ***@***.***> writes:

> [[PGP Encrypted Part:OK]] If the platform were the culprit, wouldn't
> it affect all Helm sessions, since the platform doesn't change between
> one invocation and the next?

You lost me here, do you mean the bug appear only in some helm sessions?

> At least in my case, and as reported in #2411, Helm doesn't simply "freeze/stutter when typing quickly".
>
>   • It freezes/stutters significantly, plus it produces spurious input, when typing quickly and the list of candidates is very long (e.g. M-x describe-function)
>   • It freezes/stutters slightly, but without spurious input, when the list is shorter (e.g. helm-M-x)
>   • It neither freezes/stutters nor produces spurious input when the list is short (e.g. helm-multi-files)

My guess is something is interfering with emacs, see issue #1157.


-- 
Thierry

**Comment by bard** [comment]
> Yes if you want.

Well, it appears to be a bug, and it appears not to be tracked elsewhere, I'd imagine those would be reasons to keep it open, but it's up to you really.

**Comment by thierryvolpiatto** [comment]
Massimiliano Mirra ***@***.***> writes:

> [[PGP Encrypted Part:OK]]
>     Yes if you want.
>    
> Well, it appears to be a bug, and it appears not to be tracked
> elsewhere,

I still think your bug is not much different from this one, also IMHO it
is not an helm bug but a bug affecting some emacs functions
(while-no-input among others IMO), but if you still think it is something
different please reopen your initial bug.

Also, try to see what external program may affect emacs on your system,
try to see also if you can reproduce with a stable emacs
e.g. emacs-27.2.

Thanks. 

-- 
Thierry

**Comment by bard** [comment]
Ok, sounds good. I can't reopen the issue though, GitHub only allows non-collaborators to reopen issues that they themselves closed.

**Comment by thierryvolpiatto** [comment]
Massimiliano Mirra ***@***.***> writes:

> Ok, sounds good. I can't reopen the issue though, GitHub only allows
> non-collaborators to reopen issues that they themselves closed.

Done.


-- 
Thierry

**Comment by Chaformbintrano** [comment]
@thierryvolpiatto 
>I guess the problem is outside helm, maybe platform related, at least many people with MacOs complain about this.
I use GNU/Linux

**Comment by 2e0byo** [comment]
I had this bug or something very like it when I moved to nativecomp yesterday.  In addition to helm stuttering as described here, text entry in LSP-mode buffers was painfully slow.

On Arch, moving from `emacs-native-comp-get-enhanced` to `emacs-git` and manually setting `JIT=YES` and `AOT=YES` entirely cured it.

I have a lot of work to do and a blazingly fast Emacs to do it in, but I will try to bisect this properly in a week or so when I have time.  However if this is the bug everyone else is seeing I *think* it's related to pgtk.  And if so it's definitely not a helm bug, although it was most noticeable in helm.

**Comment by thierryvolpiatto** [comment]
2e0byo ***@***.***> writes:

> I had this bug or something very like it when I moved to nativecomp yesterday. In addition to helm stuttering as described here, text entry in LSP-mode buffers was painfully slow.
>
> On Arch, moving from emacs-native-comp-get-enhanced to emacs-git and manually setting JIT=YES and AOT=YES entirely cured it.
>
> I have a lot of work to do and a blazingly fast Emacs to do it in, but I will try to bisect this properly in a week or so when I have time. However if this is the bug everyone else is
> seeing I think it's related to pgtk. And if so it's definitely not a helm bug, although it was most noticeable in helm.

Thanks to look into this.

-- 
Thierry

**Comment by Chaformbintrano** [comment]
@2e0byo Thanks a million! I installed an Emacs without pgtk and the problems went away!

**Comment by 2e0byo** [comment]
hurrah!  Mine has been blissfully fast since I did.

**Comment by MattMicheletti** [comment]
I am having essentially the same issue on Emacs for macOS (Railwaycat port - Emacs 27.2). Helm is lags for several seconds no matter what I use / do (switch buffer, find files, describe function, or anything with Helm). For example, with a directory with only 20 files (and 1 is cpp) ... just typing ".cpp" for find files ... Helm takes 2 ~ 3 seconds to respond and filter the list. Helm works _flawlessly_ on Windows (even in a VM).

I am not sure what the issue is (Emacs or Helm) and I do not know much about the internal workings of Emacs (I am relatively new to Emacs) and AFAIK, the railwaycat Emacs port is the _best_ port of Emacs for macOS.

@2e0byo Do you use the same port? Did the steps you took solve the problem on macOS with that port?

@thierryvolpiatto First off, thank you so much for developing Helm! It's really wonderful. It looks like, based on the discussion above, that you don't have a Mac computer to test Helm with. Is it possible that I could buy a Mac Mini to send to you for you to debug Helm on?

Thanks,
Matt M.

**Comment by thierryvolpiatto** [comment]
Matt Micheletti ***@***.***> writes:

> I am not sure what the issue is (Emacs or Helm)

I guess an unknow event specific to MacOS is interfering with Emacs,
perhaps with the `while-no-input` mechanism Helm is using to allow typing
fast but I can't be sure of course.

I introduced the variable `while-no-input-ignore-events` to handle such
events (we had the same problem at the time with selection-request event
triggered by clipboard managers like parcellite) originally only some
events were hardcoded in C emacs function.

So what need to be found is the culprit event and circumvent it,
possibly (hopefully) by adding it to `while-no-input-ignore-events` or
if it is not enough creating another mechanism specific to MacOS, this
would happen in Emacs core (C), not Helm.

> and I do not know much about the internal workings of Emacs (I am
> relatively new to Emacs) and AFAIK, the railwaycat Emacs port is the
> best port of Emacs for macOS.

As said above, I don't think the Emacs MacOS port is involved.

> @thierryvolpiatto First off, thank you so much for developing Helm!
> It's really wonderful.

Thanks.

> It looks like, based on the discussion above, that you don't have a
> Mac computer to test Helm with. Is it possible that I could buy a Mac
> Mini to send to you for you to debug Helm on?

Thanks, but I don't want you to spend so much for a problem I am unsure
to solve, but you can make a donation for Helm development of course
;-).


-- 
Thierry

**Comment by 2e0byo** [comment]
> @2e0byo Do you use the same port? Did the steps you took solve the problem on macOS with that port?
Sadly not!  I'm on arch.  I had an intuition that the puregtk code was interacting badly, and switching from a pgtk build has fixed it for a few of us. But that's with native-compilation (and thus emacs 28).  I have not had time to bisect and confirm this and am currently on holiday, but I'll try to chase it down for completeness' sake in a couple of weeks.

**Comment by MattMicheletti** [comment]
> Matt Micheletti ***@***.***> writes:
> I am not sure what the issue is (Emacs or Helm) ...

@thierryvolpiatto Thanks for the quick response. I actually figured out the issue _I_ was experiencing. It looks like flyspell-mode was causing the severe lag and stuttering I was experiencing. When I first set it up I accidentally hooked it into _every_ mode so that was the reason. Consequently it does not look like it was related to this issue (there is still some initial lag (less than 2 seconds) with `helm-M-x` for the first search ... at least in my testing) but at least I can now _use_ Helm (the lag was _so_ bad I almost gave up on Helm). Anyways, thanks again for the ideas / thoughts, it was actually very helpful! :)

@2e0byo Awesome! Thank you. I am sure many people appreciate it. Enjoy your holiday :)

**Comment by thierryvolpiatto** [comment]
Matt Micheletti ***@***.***> writes:

>     Matt Micheletti @.***> writes:
>     I am not sure what the issue is (Emacs or Helm) ...
>    
> @thierryvolpiatto Thanks for the quick response. I actually figured
> out the issue I was experiencing. It looks like flyspell-mode was
> causing the severe lag and stuttering I was experiencing. When I first
> set it up I accidentally hooked it into every mode so that was the
> reason. Consequently it does not look like it was related to this
> issue (there is still some initial lag (less than 2 seconds) with
> helm-M-x for the first search ... at least in my testing) but at least
> I can now use Helm (the lag was so bad I almost gave up on
> Helm). Anyways, thanks again for the ideas / thoughts, it was actually
> very helpful! :)

Glad you found what's wrong, thanks for Helm ;-)


-- 
Thierry
