### ISSUE TITLE
recenter helm-display-buffer-in-own-frame

### ISSUE THREAD

**Issue by dangom** [emacs-helm/helm#2315]
**Is your feature request related to a problem? Please describe.**
Not a real problem, but I couldn't find a solution for it in the docs or in other issues.
 I'm always frustrated when I have point near the border of my screen and I call M-x, and the new frame is barely visible.

**Describe the solution you'd like**
When point is close to the border of the frame, move the starting position of the new helm frame such that it displays completely.

**Describe alternatives you've considered**
I considered just using helm's defaults, i.e., windows and not frames.

**Additional context**
In the screenshot below, note how the new frame is hidden by the end of the screen.
<img width="738" alt="image" src="https://user-images.githubusercontent.com/7881842/83582500-33d81080-a531-11ea-8567-4fcd63f6145a.png">

**Comment by thierryvolpiatto** [comment]
Daniel Gomez <notifications@github.com> writes:

> Is your feature request related to a problem? Please describe.
> Not a real problem, but I couldn't find a solution for it in the docs or in other issues.
> I'm always frustrated when I have point near the border of my screen and I call M-x, and the new frame is barely visible.
>
> Describe the solution you'd like
> When point is close to the border of the frame, move the starting position of the new helm frame such that it displays completely.
>
> Describe alternatives you've considered
> I considered just using helm's defaults, i.e., windows and not frames.
>
> Additional context
> In the screenshot below, note how the new frame is hidden by the end of the screen.
> image                                                              


Hmm, I can't reproduce this, when I am at the border of the frame the
new frame is displayed differently so that it is always visible. So is
it a problem with emacs itself or with your window manager settings ?

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.*


-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by dangom** [comment]
Thank you for your reply. The frame is visible, but not if the monitor comes to an end.

Emacs frame in the middle of the monitor
![image](https://user-images.githubusercontent.com/7881842/83599142-f5efe200-a55a-11ea-8735-bee96a8eff83.png)

Emacs frame close to monitor limit:
![image](https://user-images.githubusercontent.com/7881842/83599160-056f2b00-a55b-11ea-97ac-bddbed0ca1a6.png)

**Comment by thierryvolpiatto** [comment]
Still can't reproduce:
![Capture d’écran_2020-06-03_16-24-57](https://user-images.githubusercontent.com/1533939/83649678-c0c5ad00-a5b7-11ea-9037-ed47cf37276c.png)

**Comment by dangom** [comment]
Alright I'll close this issue because it must be related to my config, or being on a Mac. Thanks for your time and for sharing Helm with us - for now I'll revert back to using windows instead of frames.
