### ISSUE TITLE
helm-M-x errors when command not found in command history 

### ISSUE THREAD

**Issue by ksafford** [emacs-helm/helm#2316]
## Expected behavior
When calling helm-M-x with `M-x` and typing a command, I expect matching commands to be listed and the best match to be highlighted, even if that command is not in the Emacs Command History.

## Actual behavior 

When calling helm-M-x with ` M-x` and typing in a function name, once the string being entered
diverges from something in the command history completions do not work, even
though possible functions are listed under the "Emacs Commands" section,
attempts to complete the string cease and the following error appears in the
minibuffer:

![Screen Shot 2020-06-03 at 3 42 45 PM](https://user-images.githubusercontent.com/1257916/83687194-09c63300-a5b1-11ea-9b0b-7b858aa43fc4.png)

The full error is:

```
Error running timer: (error "In ‘Emacs Commands history’ source: ‘#[0 \\306\\307\\304\\305\"��\\310��\\303\\242\\311=\\312\\313\\314\\315\\316\\300\\302\\303��$\\317\"\\320\\321%\\322\\310���\\301$*\\207 [(org-display-inline-images org-mode org-superstar-restart org-mode org-superstar-mode customize-group find-variable elisp-index-search org-display-inline-images org-mode org-superstar-mode org-bullets-mode json-mode wttrin replace-string blacken-buffer eglot org-present org-gcal-sync org-gcal-fetch org-gcal-sync org-gcal-fetch deft eglot pyvenv-workon org-display-inline-images wttrin replace-string iedit-mode zetteldeft-follow-link replace-string iedit-mode spacemacs/recompile-elpa zetteldeft-follow-link org-toggle-link-display smartparens-mode org-gcal-fetch customize-group indent-region org-gcal-sync org-gcal-fetch paredit-mode org-narrow-to-subtree narrow-to-defun iedit-mode narrow-to-defun paredit-mode which-key-show-full-keymap zetteldeft-set-classic-keybindings zetteldeft-follow-link zetteldeft-insert-list-links zetteldeft-new-file-and-link zetteldeft-follow-link zetteldeft-insert-list-links zetteldeft-new-file zetteldeft-tag-buffer zetteldeft-new-file iedit-mode diredfl-mode package-install eglot-reconnect visual-line-mode customize-variable org-property-action wttrin toggle-word-wrap visual-line-mode org-agenda-toggle-deadlines wttrin hungry-delete-forward hungry-delete-mode package-install replace-string eglot-reconnect flymake-goto-next-error visual-line-mode yank-rectangle kill-rectangle writeroom-mode ispell-word ispell-buffer make-directory iedit-mode blacken-buffer pyvenv-workon company-mode json-mode paredit-mode insert-char kevin-home-mode highlight-indentation-mode recover-file customize-group bash-completion-reset-all which-key-show-major-mode bash-completion-reset spacemacs/toggle-spelling-checking-off upcase-char upcase-region sbt-hydra smartparens-mode org-beamer-export-to-pdf term eshell describe-face org-display-inline-images package-list-packages paredit-close-bracket eglot-find-implementation customize-variable vc-mode-line nyan-mode flymake-start eyebrowse-mode nyan-stop-music nyan-start-music flymake-show-diagnostics-buffer flymake-mode flycheck-mode flycheck-verify-checker flycheck-verify-setup recover-this-file all-the-icons-dired-mode all-the-icons-install-fonts org-superstar-restart org-superstar-mode org-bullets-mode paredit-forward-slurp-sexp er/expand-region insert-arrow-up corral-braces-backward corral-braces-forward corral-single-quotes-forward corral-single-quotes-backward sphinx-doc scheme-mode lsp-ui-mode org-babel-expand-src-block-maybe spacemacs/auto-yasnippet-expand yas-describe-tables sbt-run-previous-command sbt-start sbt-command sbt-mode csv-mode shell customize-face blacken-mode describe-font toggle-word-wrap list-packages describe-variable toggle-debug-on-error eglot pytest-all apropos-variable linum-mode which-key-show-full-major-mode spacemacs/toggle-mode-line-major-mode lsp-mode lsp-describe-session eglot-shutdown eglot-rename untabify flycheck-display-error-at-point python-shell-send-file cfw:refresh-calendar-buffer cfw:open-calendar-buffer cfw:show-details-command spacemacs/recompile-elpa cycle-spacing magit-status magit magit-checkout magit-branch focus-mode insert-org-header ace-jump-word-mode delete-trailing-whitespace enlarge-window all-the-icons-insert iconify-frame find-face-definition spaceline-all-the-icons-theme undo-fu-only-undo query-replace python-pytest-popup describe-key magit-pull-from-upstream magit-push magit-commit magit-stage magit-dispatch flycheck-buffer importmagic-mode flymake-disabled-backends lsp-workspace-restart flymake-reporting-backends flymake-stop-all-syntax-checks lsp-python-ms-update-server flycheck-describe-checker flycheck-disable-checker tags-reset-tags-tables ensime ensime-mode ensime-sbt-do-ensime-config clipboard-kill-region lsp-python-ms-setup lsp-treemacs-symbols python-mode live-py-mode clipboard-yank count-words org-cycle-list-bullet magit-reset-hard magit-blame toggle-truncate-lines ensime-reload magit-visit-ref nginx-mode scala-mode smerge-ediff treemacs sql-mode helm-do-ag list-buffers js-mode helm-ag undo-tree-undo profiler-report profiler-start magit-rebase py-isort-buffer anaconda-mode butterfly setenv revert-buffer dockerfile-mode helm-projectile-grep server-start artist-mode origami-recursively-toggle-node turn-on-undo-tree-mode dotspacemacs/sync-configuration-layers forward-whitespace spacemacs/error-transient-state/nil magit-show-commit iedit-rectangle-mode font-show-log) #[257 \\300\\301�!!\\207 [commandp intern-soft] 4 
```

## Steps to reproduce (recipe)

`helm-M-x` and then begin typing a command that is not in the command history.

## Backtraces if any (`M-x toggle-debug-on-error`)

![Screen Shot 2020-06-03 at 4 21 20 PM](https://user-images.githubusercontent.com/1257916/83690412-4d6f6b80-a5b6-11ea-9b84-b33976b6759a.png)

Sorry for the screenshot of the backtrace, but for whatever reason, I cannot save or yank the backtrace buffer. Seems to be a Spacemacs bug.

## Describe versions of Helm, Emacs, operating system, etc.
OS: darwin
Emacs: 27.0.50
Spacemacs: 0.300.0
Spacemacs branch: develop (rev. 015303a)
Graphic display: t
Distribution: spacemacs
helm: 20200602.485

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):

no. I was unable to start an emacs session with emacs-helm.sh. I get the error: cannot open load file: no such file or directory, helm-config when attempting to use the script.

## Are you using Spacemacs? (yes/no):

yes

**Comment by manuel-uberti** [comment]
I am not able to reproduce this. 

re `emacs-helm.sh`: did you ran `make` in the `helm` repository before running the script?

**Comment by thierryvolpiatto** [comment]
Kevin Safford <notifications@github.com> writes:

> Expected behavior
>
> When calling helm-M-x with M-x and typing a command, I expect matching
> commands to be listed and the best match to be highlighted, even if
> that command is not in the Emacs Command History.
>
> Actual behavior
>
> When calling helm-M-x with M-x and typing in a function name, once the string being entered
> diverges from something in the command history completions do not work, even
> though possible functions are listed under the "Emacs Commands" section,
> attempts to complete the string cease and the following error appears in the
> minibuffer:

Can't reproduce, helm-M-x is working correctly here.

> Screen S
>
> Steps to reproduce (recipe)
>
> Backtraces if any (M-x toggle-debug-on-error)
>
> Describe versions of Helm, Emacs, operating system, etc.
>
> OS: darwin
> Emacs: 27.0.50
> Spacemacs: 0.300.0
> Spacemacs branch: develop (rev. 015303a)
> Graphic display: t
> Distribution: spacemacs
> helm: 20200602.485
>
> Are you using emacs-helm.sh to reproduce this bug? (yes/no):
>
> no. I was unable to start an emacs session with emacs-helm.sh. I get
> the error: cannot open load file: no such file or directory,
> helm-config when attempting to use the script.

That's mean your helm installation is not correct.

> Are you using Spacemacs? (yes/no):
>
> yes

Can't help you with Spacemacs enabled.


-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by ksafford** [comment]
@manuel-uberti Thanks for the response. Running make fails with lots of 

    helm-adaptive.el:24:1:Error: Cannot open load file: No such file or directory, async

**Comment by thierryvolpiatto** [comment]
Kevin Safford <notifications@github.com> writes:

> @manuel-uberti Thanks for the response. Running make fails with lots of
>
> helm-adaptive.el:24:1:Error: Cannot open load file: No such file or directory, async

Please read the install section on helm wiki.
I run the helm make file before each commit and more without errors...

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by ksafford** [comment]
I'll close this as I have confirmed the issue isn't in helm. Thanks.
