### ISSUE TITLE
Helm-find-files: Also allow switching to M-x shell

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#2317]
**Is your feature request related to a problem? Please describe.**
I use `M-e` (Switch to Eshell) all the time from Helm-find-files.  I'd like to use it for M-x shell too.

**Describe the solution you'd like**

```elisp
(defun helm-ff--shell-interactive-buffer-p (buffer)
  (with-current-buffer buffer
    (and (eq major-mode 'shell-mode)
         (save-excursion
           (goto-char (point-min))
           (comint-next-prompt 1)
           (null (eql (point) (point-min)))))))

(defun helm-ff-switch-to-shell (_candidate)
  "Like `helm-ff-switch-to-eshell' but for `M-x shell'.

With a numeric prefix arg switch to numbered shell buffer, if no
prefix arg provided and more than one shell buffer exists, provide
completions on those buffers.  If only one shell buffer exists,
switch to this one, if no shell buffer exists or if the numeric
prefix arg shell buffer doesn't exists, create it and switch to it."
  (let ((cd-shell
         (lambda ()
           (goto-char (point-max))
           (comint-delete-input)
           (insert (format "cd %s"
                           (shell-quote-argument
                            (if (tramp-tramp-file-p helm-ff-default-directory)
                                (tramp-file-name-localname
                                 (tramp-dissect-file-name helm-ff-default-directory))
                              helm-ff-default-directory))))
           (comint-send-input)))
        (bufs (cl-loop for b in (mapcar 'buffer-name (buffer-list))
                       when (helm-ff--shell-interactive-buffer-p b)
                       collect b)))
    (helm-aif (and (null helm-current-prefix-arg)
                   (if (cdr bufs)
                       (helm-comp-read "Switch to shell buffer: " bufs
                                       :must-match t)
                     (car bufs)))
        (switch-to-buffer it)
      (shell))
    ;; TODO: Can we check if a process is currently running within the running shell?
    (funcall cd-shell)))
```

Then `M-e` could be bound to a function that dispatches between `helm-ff-switch-to-shell` and `helm-ff-switch-to-eshell` depending on the major-mode of the underlying buffer.

**Comment by manuel-uberti** [comment]
I'd love this, since I only use `M-x shell`. 

Right now I have a custom action for `helm-ls-git`, but it would be great to have a quick key binding for `helm-find-files` as well.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Is your feature request related to a problem? Please describe.  I use
> M-e (Switch to Eshell) all the time from Helm-find-files. I'd like to
> use it for M-x shell too.

Ok, we can make this addition.

> Then M-e could be bound to a function that dispatches between
> helm-ff-switch-to-shell and helm-ff-switch-to-eshell depending on the
> major-mode of the underlying buffer.

I don't understand this, why is it better for a particular mode to use
shell-mode or eshell-mode, i.e. what are the criterions for a particular
mode over the other?

Thanks.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

>     ;; TODO: Can we check if a process is currently running within the running shell?

Yes (something like this):

    (when (eq 'run (process-status (get-buffer-process (current-buffer))))
      (funcall cd-shell)))

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by Ambrevar** [comment]
I got the above code wrong.

We need to change the predicate to match Eshell or M-x shell.
In other word,

(or (helm-ff--shell-interactive-buffer-p buffer)
    (or (helm-ff--eshell-interactive-buffer-p buffer))

A few more things:

- cd-shell must be specialized to work in either Eshell or M-x shell
  (I've provided a working sample).

- The (E)shell creation expression cannot guess whether it should be
  Eshell or M-x shell.  I suggest we introduce a defcustom so that the
  user can choose which one they prefer.

Untested code:

```elisp
(defun helm-ff--shell-interactive-buffer-p (buffer)
  (with-current-buffer buffer
    (or
     (and (eq major-mode 'shell-mode)
          (save-excursion
            (goto-char (point-min))
            (comint-next-prompt 1)
            (null (eql (point) (point-min)))))
     (and (eq major-mode 'eshell-mode)
          (save-excursion
            (goto-char (point-min))
            (eshell-next-prompt 1)
            (null (eql (point) (point-min))))))))

(defun helm-ff-switch-to-shell (_candidate)
  "Switch to Eshell or M-x shell and cd to `helm-ff-default-directory'.
Set your prefered shell mode in `helm-ff-prefer-eshell'.

With a numeric prefix arg switch to numbered shell buffer, if no
prefix arg provided and more than one shell buffer exists, provide
completions on those buffers.  If only one shell buffer exists,
switch to this one, if no shell buffer exists or if the numeric
prefix arg shell buffer doesn't exists, create it and switch to it."
  (let ((cd-eshell (lambda ()
                     (eshell/cd helm-ff-default-directory)
                     (eshell-reset)))
        (cd-shell
         (lambda ()
           (goto-char (point-max))
           (comint-delete-input)
           (insert (format "cd %s"
                           (shell-quote-argument
                            (if (tramp-tramp-file-p helm-ff-default-directory)
                                (tramp-file-name-localname
                                 (tramp-dissect-file-name helm-ff-default-directory))
                              helm-ff-default-directory))))
           (comint-send-input)))
        (bufs (cl-loop for b in (mapcar 'buffer-name (buffer-list))
                       when (helm-ff--shell-interactive-buffer-p b)
                       collect b)))
    (helm-aif (and (null helm-current-prefix-arg)
                   (if (cdr bufs)
                       (helm-comp-read "Switch to shell buffer: " bufs
                                       :must-match t)
                     (car bufs)))
        (switch-to-buffer it)
      (if helm-ff-prefer-eshell
          (eshell helm-current-prefix-arg)
        (shell)))
    (if (eq major-mode 'eshell-mode)
        (unless (get-buffer-process (current-buffer))
          (funcall cd-eshell))
      ;; TODO: Can we check if a process is currently running within the running shell?
      (funcall cd-shell))))

```

**Comment by Ambrevar** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> Yes (something like this):
>
>     (when (eq 'run (process-status (get-buffer-process (current-buffer))))
>       (funcall cd-shell)))

The (eq ...) always returns `t' in M-x shell.  This is because
process-status return the status of the shell process (e.g. Bash), not
of the command executed by the shell.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I got the above code wrong.
>
> We need to change the predicate to match Eshell or M-x shell.

Yes, should not be too hard.

> A few more things:
>
> - cd-shell must be specialized to work in either Eshell or M-x shell
> (I've provided a working sample).

Yes.

> - The (E)shell creation expression cannot guess whether it should be
> Eshell or M-x shell. I suggest we introduce a defcustom so that the
> user can choose which one they prefer.

All this is not a problem, we just have to write the code, what I asked
is why you need for some modes eshell and others shell, I had the
impression you wanted to select either eshell or shell depending on the
mode, I was asking what was the criterions to use one or the other.
But maybe I misundertand, in this case yes we need a user var to choose
the shell to use when hitting M-e.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by Ambrevar** [comment]
Should I send a pull request or is the above code snippet enough?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Should I send a pull request or is the above code snippet enough?

A PR is always better.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I got the above code wrong.
>
> We need to change the predicate to match Eshell or M-x shell.
> In other word,
>
> (or (helm-ff--shell-interactive-buffer-p buffer)
> (or (helm-ff--eshell-interactive-buffer-p buffer))

Something like this avoid repetition in your code (not tested):

    (defun helm-ff--shell-interactive-buffer-p (buffer &optional mode)
      (with-current-buffer buffer
        (when (eq major-mode (or mode 'eshell-mode))
          (let ((next-prompt-fn (cl-case major-mode
                                  (shell-mode #'comint-next-prompt)
                                  (eshell-mode #'eshell-next-prompt))))
            (save-excursion
              (goto-char (point-min))
              (funcall next-prompt-fn 1)
              (null (eql (point) (point-min))))))))

> A few more things:
>
> - cd-shell must be specialized to work in either Eshell or M-x shell
> (I've provided a working sample).
> (defun helm-ff-switch-to-shell (_candidate)

Will look into this one tomorrow.

Thanks.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
This after finish for today :-)
IIUC:

```elisp
(if (tramp-tramp-file-p helm-ff-default-directory)
    (tramp-file-name-localname
     (tramp-dissect-file-name helm-ff-default-directory))
  helm-ff-default-directory)
;; ==
(helm-aif (file-remote-p helm-ff-default-directory 'localname)
    it
  helm-ff-default-directory)
```

**Comment by thierryvolpiatto** [comment]
Here what I came up with:

```elisp
(defvar helm-ff-prefered-shell-mode 'eshell-mode)
(defun helm-ff--shell-interactive-buffer-p (buffer &optional mode)
  (with-current-buffer buffer
    (when (eq major-mode (or mode 'eshell-mode))
      (let ((next-prompt-fn (cl-case major-mode
                              (shell-mode #'comint-next-prompt)
                              (eshell-mode #'eshell-next-prompt))))
        (save-excursion
          (goto-char (point-min))
          (funcall next-prompt-fn 1)
          (null (eql (point) (point-min))))))))

(defun helm-ff-switch-to-shell (_candidate)
  "Switch to Eshell or M-x shell and cd to `helm-ff-default-directory'.
Set your prefered shell mode in `helm-ff-prefered-shell'.

With a numeric prefix arg switch to numbered shell buffer, if no
prefix arg provided and more than one shell buffer exists, provide
completions on those buffers. If only one shell buffer exists,
switch to this one, if no shell buffer exists or if the numeric
prefix arg shell buffer doesn't exists, create it and switch to it."
  (let ((cd-eshell (lambda ()
                     (eshell/cd helm-ff-default-directory)
                     (eshell-reset)))
        (cd-shell
         (lambda ()
           (goto-char (point-max))
           (comint-delete-input)
           (insert (format "cd %s"
                           (shell-quote-argument
                            (or (file-remote-p
                                 helm-ff-default-directory 'localname)
                                helm-ff-default-directory))))
           (comint-send-input)))
        (bufs (cl-loop for b in (mapcar 'buffer-name (buffer-list))
                       when (helm-ff--shell-interactive-buffer-p
                             b helm-ff-prefered-shell-mode)
                       collect b)))
    (helm-aif (if (cdr bufs)
                  (helm-comp-read "Switch to shell buffer: " bufs
                                  :must-match t)
                (car bufs))
        (switch-to-buffer it)
      (if (eq helm-ff-prefered-shell-mode 'eshell-mode)
          (eshell helm-current-prefix-arg)
        (shell (helm-aif (and helm-current-prefix-arg
                              (prefix-numeric-value helm-current-prefix-arg))
                   (format "*shell<%s>" it)))))
    (helm-aif (and (eq helm-ff-prefered-shell-mode 'shell-mode)
                   (get-buffer-process (current-buffer)))
      (accept-process-output it))
    (if (eq major-mode 'eshell-mode)
        (unless (get-buffer-process (current-buffer))
          (funcall cd-eshell))
      ;; TODO: Can we check if a process is currently running within the running shell?
      (funcall cd-shell))))
```

**Comment by thierryvolpiatto** [comment]
Needs a defcustom for `helm-ff-prefered-shell-mode`, and probably polishing the code, otherwise it works, didn't find a real solution yet for your last comment.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Thierry Volpiatto <notifications@github.com> writes:
>
>> Yes (something like this):
>>
>> (when (eq 'run (process-status (get-buffer-process (current-buffer))))
>> (funcall cd-shell)))
>
> The (eq ...) always returns `t' in M-x shell. This is because
> process-status return the status of the shell process (e.g. Bash), not
> of the command executed by the shell.

So maybe something like this:

    (defun helm-ff-shell-alive-p ()
      (save-excursion
        (comint-goto-process-mark)
        (or (null comint-last-prompt)
            (not (eql (point)
                      (marker-position (cdr comint-last-prompt)))))))

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
I pushed some new changes, let me know if something wrong.
Thanks.

**Comment by manuel-uberti** [comment]
Just tested it for `shell-mode` and it works for me. Thank you!

**Comment by manuel-uberti** [comment]
One minor nitpick: `helm-ff-prefered-shell-mode` should be `helm-ff-preferred-shell-mode`. :)

**Comment by Ambrevar** [comment]
Looking good to me, beside the "prefered" typo :)
Thanks a lot!

**Comment by thierryvolpiatto** [comment]
Manuel Uberti <notifications@github.com> writes:

> One minor nitpick: helm-ff-prefered-shell-mode should be helm-ff-preferred-shell-mode. :)

Thanks! Fixed.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
