### ISSUE TITLE
navigating back and forth, in folders, in mini-buffer

### ISSUE THREAD

**Issue by DrWaleedAYousef** [emacs-helm/helm#2318]
## Expected behavior

When pressing left / right arrow key in the main buffers the crusor should move left or right.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

It calls helm-find. I need this behaviour only in the mini buffer to navigate through directories.

## Steps to reproduce (recipe)
```
(use-package helm
  :init
  (global-unset-key (kbd "C-x c"))
  (global-set-key   (kbd "C-c h") 'helm-command-prefix)
  (global-set-key   (kbd "C-x b") 'helm-mini)
  (global-set-key   (kbd "C-c h o") 'helm-occur)
  (global-set-key   (kbd "C-x C-f") 'helm-find-files)
  (global-set-key   (kbd "M-y") 'helm-show-kill-ring)
  (setq helm-mode-fuzzy-match t
	helm-completion-in-region-fuzzy-match t
	helm-locate-fuzzy-match t
	helm-M-x-fuzzy-match t
	helm-recentf-fuzzy-match t
	recentf-max-menu-items 100
	recentf-max-saved-items 100
	helm-split-window-inside-p t)
  :bind ( ("M-x"	.	helm-M-x	)
	  ("<left>" . helm-find-files-up-one-level)
	  ("<right>" . helm-execute-persistent-action)
	  )
  :config
  (require 'helm-config)
  (helm-mode 1)
  (helm-autoresize-mode t)
  )
```
## Describe versions of Helm, Emacs, operating system, etc.

GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20) of 2020-05-19

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):

no

## Are you using Spacemacs? (yes/no):

no

## IMPORTANT NOTE

Helm provides a script named `emacs-helm.sh` which runs Helm in a neutral
environment: no other packages and only minimal settings.

When possible, use it to reproduce your Helm issue to ensure no other package is
interfering.

To run it, simply switch to the directory where Helm is installed and call `./emacs-helm.sh`.
If necessary you can specify emacs executable path on command line with "-P" option.

Thanks.

**Comment by manuel-uberti** [comment]
I get the behaviour I think you want from `emacs-helm.sh`. Could you try to reproduce your issue from there?

**Comment by manuel-uberti** [comment]
Another thing: check the value of `helm-ff-lynx-style-map`. It should be `t` by default, but you can customize to `t` if it isn't and get the desired behaviour.

**Comment by DrWaleedAYousef** [comment]
@DrWaleedAYousef I think I found the problem. It seems to be an old bug in `helm` that did not use the left/right arrow keys to navigate in the mini buffer. This is why I put the lines 
```
	  ("<left>" . helm-find-files-up-one-level)
	  ("<right>" . helm-execute-persistent-action)

``

Now, I just removed them. Everything works well. When I use `helm-find` I cant navigate through directories using the left/arrow keys as a default behaviour in helm without any settings.

**Comment by manuel-uberti** [comment]
Good, I think you can safely close this issue then. :)
