### ISSUE TITLE
Maybe regression on cmd producing ANSI color?

### ISSUE THREAD

**Issue by braineo** [emacs-helm/helm#2320]
Thank you for your effort maintaining helm.
Maybe I need change something on my side but I could not figure out what should be changed. It will be great to have some hint from you.

I am using `ripgrep` to search with `helm-rg`, it was working until I updated `helm`

I did a bisect and it pointed out this `Fix grep highlighting without ansi ` is the first commit breaks the function. And since the command generated by `helm-rg` is 

```
rg --smart-case --color=ansi --colors=match:fd:red <pattern>
```
I wonder how should I adopt the change on my side.

## Expected behavior
helm shows candidates in helm buffer

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
no result showing in helm buffer

## Steps to reproduce (recipe)
Since I'm using helm-rg, skip this part

## Backtraces if any (`M-x toggle-debug-on-error`)
[backtrace.log](https://github.com/emacs-helm/helm/files/4750355/backtrace.log)

## Describe versions of Helm, Emacs, operating system, etc.
Helm master, emacs 27.0.5, Debian 9

I did a bisect and get following result

```
4071dca 2020-05-31 09:45 +0200 Thierry Volpiatto       o [HEAD] [refs/bisect/bad] Fix grep highlighting without ansi (#2313)
6500dc4 2020-05-31 07:53 +0200 Thierry Volpiatto       o [refs/bisect/good-6500dc4e6b433f90844e6008fd992c1d96a17548] Update AG command docstring and help (#231
91f89aa 2020-05-30 11:20 +0200 Thierry Volpiatto       o Prefer cl-loop for parsing buffers
9101738 2020-05-30 07:56 +0200 Thierry Volpiatto       o Remove all ido-virtual broken stuff
f7fa3a9 2020-05-30 06:51 +0200 Thierry Volpiatto       o [refs/bisect/good-f7fa3a9e0ef1f69c42e0c513d02c9f76ea9a4344] Get rid of ido for listing buffers (#2311)
0ee299e 2020-05-29 07:57 +0200 Thierry Volpiatto       o Fix initial minibuffer-completion-confirm value
16e4794 2020-05-28 09:53 +0200 Thierry Volpiatto       o Use bold face for class slots in help
b95e9a6 2020-05-26 09:58 +0200 Thierry Volpiatto       o Allow passing minibuffer-completion-confirm value
4ff354e 2020-05-17 17:10 +0200 Thierry Volpiatto       o Update version number in helm.el
a751fa7 2020-05-17 08:36 +0200 Thierry Volpiatto       o Update template
41242fa 2020-05-17 07:09 +0200 Thierry Volpiatto       o [refs/bisect/good-41242faebb5c16c23fe7e831d4bb2cb3294e074d] <v3.6.2> Update pkg file and drop support
```

```
4071dca7f80b590a9d089ff790fb54224fad110d is the first bad commit
commit 4071dca7f80b590a9d089ff790fb54224fad110d
Author: Thierry Volpiatto <thierry.volpiatto@gmail.com>
Date:   Sun May 31 09:45:37 2020 +0200

    Fix grep highlighting without ansi (#2313)
    
    We need to transform pcre regexp to elisp when needed.
    
    * helm-grep.el (helm-grep-mode--use-pcre): New local flag.
    (helm-grep-save-results-1): Use it.
    (helm-grep-mode--sentinel): Maybe use pcre.
    (helm-grep-class): Use now a FCT.
    (helm-grep--filter-candidate-1): Take one more arg PCRE.
    (helm-grep-filter-one-by-one): Same.
    (helm-grep-fc-transformer): New use it now for grep and ag.
    (helm-grep-highlight-match): Use pcre regexp when pcre arg is specified.
    (helm-grep-ag-class): Use now a FCT.
    * helm-occur.el (helm-occur-filter-one-by-one): Fix arg no more used.

:100644 100644 c6262988ddb349fa81f2f30d99dadbc200439c86 97470e4b7914c8b261862a308930c0dbec10b58b M	helm-grep.el
:100644 100644 fbf81c2e2a00dbe7fc3509485e12b9cb08f7255a 24a6a3a906afe01b2929e4ec3d761ccb0c258010 M	helm-occur.el
```

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):
yes

## Are you using Spacemacs? (yes/no):
NO

## IMPORTANT NOTE

Helm provides a script named `emacs-helm.sh` which runs Helm in a neutral
environment: no other packages and only minimal settings.

When possible, use it to reproduce your Helm issue to ensure no other package is
interfering.

To run it, simply switch to the directory where Helm is installed and call `./emacs-helm.sh`.
If necessary you can specify emacs executable path on command line with "-P" option.

Thanks.

**Comment by thierryvolpiatto** [comment]
braineo <notifications@github.com> writes:

> Thank you for your effort maintaining helm.
> Maybe I need change something on my side but I could not figure out what should be changed. It will be great to have some hint from you.
>
> I am using ripgrep to search with helm-rg, it was working until I updated helm
>
> I did a bisect and it pointed out this Fix grep highlighting without ansi is the first commit breaks the function. And since the command generated by helm-rg is
>
> rg --smart-case --color=ansi --colors=match:fd:red <pattern>

I have no idea what's wrong, this looks a bug in helm-rg, perhaps it
needs to stick with new helm code?
At least our implementation here is working fine (i.e. helm-do-grep-ag
with helm-grep-ag-command using rg).

Here my settings:

        helm-grep-ag-command
        "rg --color=always --colors 'match:bg:yellow' --colors 'match:fg:black' --smart-case --no-heading --line-number %s %s %s"

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by manuel-uberti** [comment]
I am using a different `helm-grep-ag-command` from the one reported above by Thierry and I can't reproduce the problem. 

Note that I'm not using `helm-rg` either, so it's probably best to report this problem there?

**Comment by braineo** [comment]
@thierryvolpiatto @manuel-uberti 

Thanks for getting back.

Interestingly, I retried 

* `helm-grep-ag-command` -- working
* `helm-ag` (using rg) --working
* `helm-projectile-ag` (using ag) -- working
* `helm-projectile-ag` (using rg) -- not working while used to be working

I agree that other packages should keep up with new helm code, while I could not see what interface has changed...
