### ISSUE TITLE
Buffer selector

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#2321]
**Is your feature request related to a problem? Please describe.**

A pattern I find myself using over and over again is that of a "buffer
selector".  Think a shell buffer selector, your favourite REPL buffer selector,
email buffers, org buffers, eww buffers...

**Describe the solution you'd like**

A higher-order function or a macro the defines a command that does the following:

- First time it's called, it create the buffer (e.g. shell buffer)
- When called again and the current buffer is not of the correspinding major
  more (here shell-mode), switch to the corresponding buffer.
- When called and the current buffer _is_ of the corresponding major mode,
  show a Helm of all buffers of this type + a source to create a new buffer of
  this type.
  
The function / macro would take the following arguments:

- name
- predicate to match buffers
- buffer creation function

**Describe alternatives you've considered**
I have a quick 'n' dirty implementation but I'd be happy to rewrite it properly
and send a patch. 

Let me know if you are interested :)

**Comment by Ambrevar** [comment]
Would you mind that I host a separate package on github.com/emacs-helm/helm-selectors then?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Would you mind that I host a separate package on
> github.com/emacs-helm/helm-selectors then?

No problem.


-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by Ambrevar** [comment]
Done: https://github.com/emacs-helm/helm-selector

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Done: https://github.com/emacs-helm/helm-selector

Thanks.

NOTE: You can avoid using seq easily with simpler lisp code that doesn't
require the reader to learn seq, e.g.

    (helm-aand (file-name-extension name) 
               (downcase it) 
               (member it '("org" "gpg"))

vs

    (and name
         (file-name-extension name)
         (seq-find
          (lambda (ext)
            (string= (downcase (file-name-extension name))
                     ext))
          ;; Org files have a .gpg extension when GPG-encrypted.
          '("org" "gpg")))

As a benefit you don't have to require seq.

Same comment for seq-filter.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by Ambrevar** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> NOTE: You can avoid using seq easily with simpler lisp code that doesn't
> require the reader to learn seq, e.g.
>
>     (helm-aand (file-name-extension name) 
>                (downcase it) 
>                (member it '("org" "gpg"))

Good catch!  I'm not a fan of anaphoric macros so I'd rather use
`and-let*` here.

> Same comment for seq-filter.

Which higher-order function to you recommend instead?

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

>> Same comment for seq-filter.
>
> Which higher-order function to you recommend instead?

(cl-loop for ELM in SEQ when PREDICATE return ELM)

Think it is what seq does.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by Ambrevar** [comment]
> (cl-loop for ELM in SEQ when PREDICATE return ELM)

I prefer the functional programming approach.  In particular, it allows
for chaining higher-order functions and makes debugging easier.

I could use `cl-remove-if` to avoid depending on `seq`.

**Comment by Ambrevar** [comment]
Done.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

>> (cl-loop for ELM in SEQ when PREDICATE return ELM)

You see as I don't know seq functions I confused seq-find and seq-filter.

> I prefer the functional programming approach. In particular, it allows
> for chaining higher-order functions and makes debugging easier.
>
> I could use `cl-remove-if` to avoid depending on `seq`.

Be careful they have not the same meaning:

    (let ((lst '(1 2 3 4 5 6 7 8 9 10)))
      (cl-remove-if 'cl-evenp lst))
    =>(1 3 5 7 9)


    (let ((lst '(1 2 3 4 5 6 7 8 9 10)))
      (seq-filter 'cl-evenp lst))
    =>(2 4 6 8 10)

    (let ((lst '(1 2 3 4 5 6 7 8 9 10)))
      (cl-remove-if-not 'cl-evenp lst))
    =>(2 4 6 8 10)

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by Ambrevar** [comment]
The exact equivalent is indeed `cl-remove-if-not`.  Thanks!

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

>> (cl-loop for ELM in SEQ when PREDICATE return ELM)
>
> I prefer the functional programming approach.

Me too, what make you think using cl-loop is not a functional
programming approach?

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by Ambrevar** [comment]
Thierry Volpiatto <notifications@github.com> writes:

>> I prefer the functional programming approach.
>
> Me too, what make you think using cl-loop is not a functional
> programming approach?

In this context, the functional programming style prefers to abstract
control structures as functions, instead of the ALGOL-style for/while
blocks.

cl-loop is similar to the latter with an embedded language that enables
the user to describe the control structure, but it does not abstract it
away as a function.

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Thierry Volpiatto <notifications@github.com> writes:
>
>>> I prefer the functional programming approach.
>>
>> Me too, what make you think using cl-loop is not a functional
>> programming approach?
>
> In this context, the functional programming style prefers to abstract
> control structures as functions, instead of the ALGOL-style for/while
> blocks.
>
> cl-loop is similar to the latter with an embedded language that enables
> the user to describe the control structure, but it does not abstract it
> away as a function.

Yes of course, cl-loop is a lower level function as seq* but you can
also make your own function using this tool i.e. cl-loop.
Note that you can also teach seq to use cl-loop:

    (cl-defmethod seq-filter (predicate (sequence sequence))
      (cl-loop for elm in sequence
               when (funcall predicate elm)
               collect (cons elm "I am using cl-loop")))

Now when you run seq-filter on a sequence, it will use cl-loop :-)

Try

    (let ((lst '(1 2 3 4 5 6 7 8 9 10)))
      (seq-filter 'cl-evenp lst))


-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
