### ISSUE TITLE
duplicate candidate hits 

### ISSUE THREAD

**Issue by sjLambda** [emacs-helm/helm#2322]
Don't know if this is a bug or a misconf; see attached screenshot
![helmdups](https://user-images.githubusercontent.com/15698764/84778893-7a4d5680-af98-11ea-9a07-4299b01c7f67.png)
## Expected behavior
no duplicates of the same command

## Describe versions of Helm, Emacs, operating system, etc.
helm: Version: 3.6.2
emacs:  GNU Emacs 28.0.50 (x86_64-apple-darwin15.6.0, NS appkit-1404.47 Version 10.11.6 (Build 15G22010))
mac osx: ProductVersion:	10.11.6 BuildVersion:	15G22010

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):
no because magit is not loaded in the barebones version of emacs-helm.sh

## Are you using Spacemacs? (yes/no):
no

**Comment by manuel-uberti** [comment]
> ## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):
> 
> no because magit is not loaded in the barebones version of emacs-helm.sh

Does it happen only with `magit-status`?

You may want to check out https://github.com/emacs-helm/helm/issues/2291
See in particular Thierry's comment: https://github.com/emacs-helm/helm/issues/2291#issuecomment-615037764

**Comment by thierryvolpiatto** [comment]
See #2305

**Comment by sjLambda** [comment]
thanks, yes #2305,   

`(setq` history-delete-duplicates `t)` 

solved it. Closed.
