### ISSUE TITLE
Helm issued errors: helm-match-from-candidates in source `Find Files': args-out-of-range (0 0)

### ISSUE THREAD

**Issue by douglasdavis** [emacs-helm/helm#2330]
Helm is still usable, but an error message is reported.

## Expected behavior
```emacs-lisp
(setq helm-ff-skip-boring-files t)
```
<kbd>C-x C-f</kbd> <kbd>~/.....</kbd> (find starting from home dir) without an error message

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

```emacs-lisp
(setq helm-ff-skip-boring-files t)
```
<kbd>C-x C-f</kbd> <kbd>~/.....</kbd> with an error message:

```
Helm issued errors: helm-match-from-candidates in source `Find Files': args-out-of-range (0 0)
```

## Steps to reproduce (recipe)

Using `emacs-helm.sh` just execute the s-exp `(setq helm-ff-skip-boring-files t)` and run <kbd>C-x C-f</kbd> and start with tilde (trying to start from home directory)

## Backtraces if any (`M-x toggle-debug-on-error`)

![Screenshot from 2020-06-24 12-30-26](https://user-images.githubusercontent.com/3202090/85595178-998e5880-b616-11ea-9bf3-5482fe6aac47.png)

## Describe versions of Helm, Emacs, operating system, etc.

Emacs 28.0.50, helm-20200624.737 from MELPA

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):

Yes

## Are you using Spacemacs? (yes/no):

No (Vanilla GNU Emacs)

**Comment by thierryvolpiatto** [comment]
Doug Davis <notifications@github.com> writes:

> Expected behavior
>
> (setq helm-ff-skip-boring-files t)
>
> C-x C-f ~/..... without an error message
>
> Actual behavior (from emacs-helm.sh if possible, see note at the bottom)
>
> (setq helm-ff-skip-boring-files t)
>
> C-x C-f ~/..... with an error message:
>
> Helm issued errors: helm-match-from-candidates in source `Find Files': args-out-of-range (0 0) [3 times]

Fixed, I may fix it differently tomorrow though.

Thanks.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by douglasdavis** [comment]
Thanks!

**Comment by banzr** [comment]
I'm using spacemacs 0.300.0 on emacs 26.3 with helm commit 0e7779, which is currently hosted on mepla labeled 20200731.649 and I am experiencing the same issue. 

I am also running on macOS 10.15.6 and the error does not occur until I navigate to my Documents folder.

May you please reopen this ticket?

**Comment by thierryvolpiatto** [comment]
Try to reproduce the error WITHOUT spacemacs with emacs-helm.sh, then if you still experiment the error turn on debug on error and send the relevant backtrace, I will then reopen issue.
Thanks.
