### ISSUE TITLE
helm-multiline-transformer does not support (DISPLAY . REAL) format candidates

### ISSUE THREAD

**Issue by f279801** [emacs-helm/helm#2334]
## Expected behavior
`helm` should behave correctly.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
Wrong type argument: char-or-string-p, ("d1" . "r1")

## Steps to reproduce (recipe)
`(helm :sources
   (helm-build-sync-source "test"
     :candidates '(("d1" . "r1") ("d2" . "r2"))
     :multiline 2)
     :buffer "*helm multiline test*")`

## Backtraces if any (`M-x toggle-debug-on-error`)

> Debugger entered--Lisp error: (wrong-type-argument char-or-string-p ("d1" . "r1"))
  helm--multiline-get-truncated-candidate(("d1" . "r1") 2)
  helm-multiline-transformer((("d1" . "r1") ("d2" . "r2")) ((name . "test") (candidates ("d1" . "r1") ("d2" . "r2")) (keymap keymap (26 . helm-select-action) (tab . helm-execute-persistent-action) (f13 lambda nil (interactive) (helm-select-nth-action 12)) (f12 lambda ni$
  apply(helm-multiline-transformer ((("d1" . "r1") ("d2" . "r2")) ((name . "test") (candidates ("d1" . "r1") ("d2" . "r2")) (keymap keymap (26 . helm-select-action) (tab . helm-execute-persistent-action) (f13 lambda nil (interactive) (helm-select-nth-action 12)) (f12 la$
  helm-apply-functions-from-source(((name . "test") (candidates ("d1" . "r1") ("d2" . "r2")) (keymap keymap (26 . helm-select-action) (tab . helm-execute-persistent-action) (f13 lambda nil (interactive) (helm-select-nth-action 12)) (f12 lambda nil (interactive) (helm-se$
  helm-process-filtered-candidate-transformer((("d1" . "r1") ("d2" . "r2")) ((name . "test") (candidates ("d1" . "r1") ("d2" . "r2")) (keymap keymap (26 . helm-select-action) (tab . helm-execute-persistent-action) (f13 lambda nil (interactive) (helm-select-nth-action 12$
  helm-compute-matches(((name . "test") (candidates ("d1" . "r1") ("d2" . "r2")) (keymap keymap (26 . helm-select-action) (tab . helm-execute-persistent-action) (f13 lambda nil (interactive) (helm-select-nth-action 12)) (f12 lambda nil (interactive) (helm-select-nth-act$
  helm--collect-matches((((name . "test") (candidates ("d1" . "r1") ("d2" . "r2")) (keymap keymap (26 . helm-select-action) (tab . helm-execute-persistent-action) (f13 lambda nil (interactive) (helm-select-nth-action 12)) (f12 lambda nil (interactive) (helm-select-nth-a$
  helm-update(nil)
  helm-read-pattern-maybe(nil nil nil nil nil nil nil)
  helm-internal(((name . "test") (candidates ("d1" . "r1") ("d2" . "r2")) (keymap keymap (26 . helm-select-action) (tab . helm-execute-persistent-action) (f13 lambda nil (interactive) (helm-select-nth-action 12)) (f12 lambda nil (interactive) (helm-select-nth-action 11)$
  apply(helm-internal (((name . "test") (candidates ("d1" . "r1") ("d2" . "r2")) (keymap keymap (26 . helm-select-action) (tab . helm-execute-persistent-action) (f13 lambda nil (interactive) (helm-select-nth-action 12)) (f12 lambda nil (interactive) (helm-select-nth-act$
  helm(((name . "test") (candidates ("d1" . "r1") ("d2" . "r2")) (keymap keymap (26 . helm-select-action) (tab . helm-execute-persistent-action) (f13 lambda nil (interactive) (helm-select-nth-action 12)) (f12 lambda nil (interactive) (helm-select-nth-action 11)) (f11 la$
  apply(helm (((name . "test") (candidates ("d1" . "r1") ("d2" . "r2")) (keymap keymap (26 . helm-select-action) (tab . helm-execute-persistent-action) (f13 lambda nil (interactive) (helm-select-nth-action 12)) (f12 lambda nil (interactive) (helm-select-nth-action 11)) $
  helm(:sources ((name . "test") (candidates ("d1" . "r1") ("d2" . "r2")) (keymap keymap (26 . helm-select-action) (tab . helm-execute-persistent-action) (f13 lambda nil (interactive) (helm-select-nth-action 12)) (f12 lambda nil (interactive) (helm-select-nth-action 11)$
  eval((helm :sources (helm-build-sync-source "test" :candidates (quote (("d1" . "r1") ("d2" . "r2"))) :multiline 2) :buffer "*helm multiline test*"))
  eshell-exec-lisp(eshell-print eshell-error (helm :sources (helm-build-sync-source "test" :candidates (quote (("d1" . "r1") ("d2" . "r2"))) :multiline 2) :buffer "*helm multiline test*") nil t)
  eshell-lisp-command((helm :sources (helm-build-sync-source "test" :candidates (quote (("d1" . "r1") ("d2" . "r2"))) :multiline 2) :buffer "*helm multiline test*"))
  eval((eshell-lisp-command (quote (helm :sources (helm-build-sync-source "test" :candidates (quote (("d1" . "r1") ("d2" . "r2"))) :multiline 2) :buffer "*helm multiline test*"))))
  eshell-do-eval((eshell-lisp-command (quote (helm :sources (helm-build-sync-source "test" :candidates (quote (("d1" . "r1") ("d2" . "r2"))) :multiline 2) :buffer "*helm multiline test*"))) nil)
  eshell-do-eval((prog1 (eshell-lisp-command (quote (helm :sources (helm-build-sync-source "test" :candidates (quote (... ...)) :multiline 2) :buffer "*helm multiline test*"))) (run-hooks (quote eshell-this-command-hook))) nil)
  (condition-case err (eshell-do-eval (quote (prog1 (eshell-lisp-command (quote (helm :sources (helm-build-sync-source "test" :candidates ... :multiline 2) :buffer "*helm multiline test*"))) (run-hooks (quote eshell-this-command-hook)))) nil) ((debug error) (run-hooks ($
  eval((condition-case err (eshell-do-eval (quote (prog1 (eshell-lisp-command (quote (helm :sources ... :buffer "*helm multiline test*"))) (run-hooks (quote eshell-this-command-hook)))) nil) ((debug error) (run-hooks (quote eshell-this-command-hook)) (eshell-errorn (err$
  eshell-do-eval((condition-case err (eshell-do-eval (quote (prog1 (eshell-lisp-command (quote (helm :sources ... :buffer "*helm multiline test*"))) (run-hooks (quote eshell-this-command-hook)))) nil) ((debug error) (run-hooks (quote eshell-this-command-hook)) (eshell-e$
  (let ((eshell-this-command-hook (quote (ignore)))) (eshell-do-eval (quote (condition-case err (eshell-do-eval (quote (prog1 (eshell-lisp-command ...) (run-hooks ...))) nil) ((debug error) (run-hooks (quote eshell-this-command-hook)) (eshell-errorn (error-message-strin$
  eval((let ((eshell-this-command-hook (quote (ignore)))) (eshell-do-eval (quote (condition-case err (eshell-do-eval (quote (prog1 ... ...)) nil) ((debug error) (run-hooks (quote eshell-this-command-hook)) (eshell-errorn (error-message-string err)) (eshell-close-handles$
  eshell-do-eval((let ((eshell-this-command-hook (quote (ignore)))) (eshell-do-eval (quote (condition-case err (eshell-do-eval (quote (prog1 ... ...)) nil) ((debug error) (run-hooks (quote eshell-this-command-hook)) (eshell-errorn (error-message-string err)) (eshell-clo$
  eshell-do-eval((progn (let ((eshell-this-command-hook (quote (ignore)))) (eshell-do-eval (quote (condition-case err (eshell-do-eval (quote ...) nil) ((debug error) (run-hooks ...) (eshell-errorn ...) (eshell-close-handles 1)))) nil))) nil)
  (catch (quote top-level) (eshell-do-eval (quote (progn (let ((eshell-this-command-hook (quote ...))) (eshell-do-eval (quote (condition-case err ... ...)) nil)))) nil))
  eval((catch (quote top-level) (eshell-do-eval (quote (progn (let ((eshell-this-command-hook ...)) (eshell-do-eval (quote ...) nil)))) nil)))
  eshell-do-eval((catch (quote top-level) (eshell-do-eval (quote (progn (let ((eshell-this-command-hook ...)) (eshell-do-eval (quote ...) nil)))) nil)) nil)
  eshell-do-eval((progn (quote nil) (catch (quote top-level) (eshell-do-eval (quote (progn (let (...) (eshell-do-eval ... nil)))) nil)) (run-hooks (quote eshell-post-command-hook))) nil)
  (let ((eshell-current-handles (quote [nil (t . 1) (t . 1)])) eshell-current-subjob-p) (eshell-do-eval (quote (progn (quote nil) (catch (quote top-level) (eshell-do-eval (quote (progn ...)) nil)) (run-hooks (quote eshell-post-command-hook)))) nil))
  eval((let ((eshell-current-handles (quote [nil (t . 1) (t . 1)])) eshell-current-subjob-p) (eshell-do-eval (quote (progn (quote nil) (catch (quote top-level) (eshell-do-eval (quote ...) nil)) (run-hooks (quote eshell-post-command-hook)))) nil)))
  eshell-do-eval((let ((eshell-current-handles (quote [nil (t . 1) (t . 1)])) eshell-current-subjob-p) (eshell-do-eval (quote (progn (quote nil) (catch (quote top-level) (eshell-do-eval (quote ...) nil)) (run-hooks (quote eshell-post-command-hook)))) nil)))
  eshell-resume-eval()
  eshell-eval-command((let ((eshell-current-handles (quote [nil (t . 1) (t . 1)])) eshell-current-subjob-p) (eshell-do-eval (quote (progn (quote nil) (catch (quote top-level) (eshell-do-eval (quote ...) nil)) (run-hooks (quote eshell-post-command-hook)))) nil)) "(helm :$
  eshell-send-input(nil)
  funcall-interactively(eshell-send-input nil)
  call-interactively(eshell-send-input nil nil)
  command-execute(eshell-send-input)

## Describe versions of Helm, Emacs, operating system, etc.
helm-core-20200703.1245
Emacs 26.3

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):
no

## Are you using Spacemacs? (yes/no):
no

**Comment by thierryvolpiatto** [comment]
Tai Dinh <notifications@github.com> writes:

> Expected behavior
>
> helm should behave correctly.
>
> Actual behavior (from emacs-helm.sh if possible, see note at the bottom)
>
> Wrong type argument: char-or-string-p, ("d1" . "r1")

Thanks to catch this, should work now.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by f279801** [comment]
Beautiful!
Verified +1
