### ISSUE TITLE
Display .desktop icons in helm-run-external-command

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#2337]
**Is your feature request related to a problem? Please describe.**
Wouldn't it be neat to display icons for applications that have a .desktop file?
While mostly cosmetic, this also has the benefit to allow EXWM users to test if their .desktop icons are working properly (useful if you are an application packager).

**Describe the solution you'd like**
Similarly to helm-emms, display applications icons left of their name in helm-run-external-command.

**Comment by manuel-uberti** [comment]
Don't know if this is related (I don't use it), but some icons can be already displayed with [helm-icons](https://github.com/yyoncho/helm-icons).

**Comment by thierryvolpiatto** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Is your feature request related to a problem? Please describe.
> Wouldn't it be neat to display icons for applications that have a
> .desktop file?  While mostly cosmetic, this also has the benefit to
> allow EXWM users to test if their .desktop icons are working properly
> (useful if you are an application packager).

A pain to implement, i.e. where are the .desktop files? freedesktop
specification? Windows? MAc? etc...

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by Ambrevar** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> A pain to implement, i.e. where are the .desktop files? freedesktop
> specification? Windows? MAc? etc...

The freedesktop specification give us easy access to the icons.  I don't
think it's hard to implement.

About Windows and macOS, I don't know if it's doable, but that's OK
since the icons only display if they are available, it would not disturb
anything else.

**Comment by andersjohansson** [comment]
I did some work on using desktop-files and icons here:
https://gitlab.com/andersjohansson/helm-launcher
(This is some work-in-progress attempt at creating an emacs and helm-based application and file-launcher like Gnome Do, Synapse etc.)

> The freedesktop specification give us easy access to the icons.  I don't think it's hard to implement.

Perhaps, but not trivial either. I ended up cheating and using some python code for getting icons from gi. This works on gnome (and perhaps other gtk-based environments?) but it isn't very portable.

Implementing this would also mean searching for `Exec` lines matching the collected external commands in desktop files. Not entirely trivial either.

**Comment by Ambrevar** [comment]
> But that lookup isn’t that trivial, since icons need not be specified with a path but can be specified as: "emacs" or "preferences-desktop" (an “iconstring” in the specification). A icon should then be chosen from the current theme, and if that is not found fallbacks are used. That is, we would need to implement everything under "Icon lookup" here in elisp: https://freedesktop.org/wiki/Specifications/icon-theme-spec/.

I didn't know that, thanks for clarifying this point.  Well, maybe we
don't need to support the more advanced lookups and stick to finding the
file.  After all, it's just a cosmetic option and if we miss some icons
it's probably not so bad.
