### ISSUE TITLE
Be able to break ties in fuzzy matching using recentness (in helm-buffers etc.)

### ISSUE THREAD

**Issue by thomasjm** [emacs-helm/helm#2339]
**Is your feature request related to a problem? Please describe.**
The problem is that when you use fuzzy search narrowing in helm, it forgets about any previously existing sort orders (such as by recentness). This was first discussed in #1507 in the context of helm-recentf.

**Describe the solution you'd like**
It would be nice if it was possible to ensure that when two candidates have an equal score according to the fuzzy search function, ties are broken by recentness. (Or perhaps by whatever sort order you use before narrowing begins.) I'm not sure exactly how this would work but some kind of fully user-configurable narrowing function would be nice.

**Describe alternatives you've considered**
None

**Additional context**
@thierryvolpiatto indicated he had a solution in mind on #1507, so I'm just filing this issue to track.

**Comment by thierryvolpiatto** [comment]
Tom McLaughlin <notifications@github.com> writes:

> Is your feature request related to a problem? Please describe.
> The problem is that when you use fuzzy search narrowing in helm, it forgets about any previously existing sort orders (such as by recentness). This was first discussed in 
> #1507 in the context of helm-recentf.
>
> Describe the solution you'd like
> It would be nice if it was possible to ensure that when two candidates
> have an equal score according to the fuzzy search function, ties are
> broken by recentness.

Done for buffers, see `helm-buffers-sort-fn`.

Thanks to report.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thomasjm** [comment]
Thanks @thierryvolpiatto ! I'm trying this out now and it seems to be working well. I'll just experiment a bit longer and then close this issue.

**Comment by thomasjm** [comment]
I think this is working, so going to hit close. Thanks again!
