### ISSUE TITLE
Customise how shell buffer is displayed

### ISSUE THREAD

**Issue by lionel-** [emacs-helm/helm#2350]
**Is your feature request related to a problem? Please describe.**
I always use shells in the right window of a 2-split configuration.

For some reason this used to work with `<f2>` in helm-find-files, whether a shell buffer was open or not. It stopped working after updating the Emacs packages, but I can't figure out why.

**Describe the solution you'd like**
`helm-ff-switch-to-shell` uses `switch-to-buffer` when the shell buffer already exists. This prevents it from being opened in a dedicated window.

I believe this patch would allow users to customise how shell buffers are opened:

```diff
--- a/helm-files.el
+++ b/helm-files.el
@@ -1562,7 +1562,9 @@ prefix arg shell buffer doesn't exists, create it and switch to it."
                        (helm-comp-read "Switch to shell buffer: " bufs
                                        :must-match t)
                      (car bufs)))
-        (switch-to-buffer it)
+        (if-let ((window (display-buffer it)))
+            (select-window window)
+          (switch-to-buffer it))
       (cl-case helm-ff-preferred-shell-mode
         (eshell-mode
          (eshell helm-current-prefix-arg))
```

**Describe alternatives you've considered**

Temporarily setting the current window as dedicated works for me because switch-to-buffer then delegates to pop-to-buffer, but that doesn't seem the right solution:

```elisp
(advice-add #'helm-ff-switch-to-shell :around #'my-around-dedicated-window)

(defun my-around-dedicated-window (fn &rest args)
  (let ((win (selected-window))
        (old (window-dedicated-p)))
    (unwind-protect
        (progn
          (set-window-dedicated-p win t)
          (apply fn args))
      (set-window-dedicated-p win old))))
```

**Comment by thierryvolpiatto** [comment]
Lionel Henry <notifications@github.com> writes:

> Is your feature request related to a problem? Please describe.
> I always use shells in the right window of a 2-split configuration.

Ok, if you split in two vertical windows and you start helm from the
right window, your shell will be displayed in the right window.

> For some reason this used to work with <f2> in helm-find-files,

F2 never switch to shell, perhaps you have another configuration?

> whether a shell buffer was open or not. It stopped working after
> updating the Emacs packages, but I can't figure out why.

Please describe what was working and what is no more working.

From where do you start helm? right window? left window?
Where is the shell now once you switch to it?

Also please start from emacs-helm.sh so that we use same configuration,
same bindings etc...

> Describe the solution you'd like helm-ff-switch-to-shell uses
> switch-to-buffer when the shell buffer already exists. This prevents
> it from being opened in a dedicated window.

I am confused now, where is the dedicated window and to what is it
dedicated.

> I believe this patch would allow users to customise how shell buffers are opened:
>
> --- a/helm-files.el
> +++ b/helm-files.el
> @@ -1562,7 +1562,9 @@ prefix arg shell buffer doesn't exists, create it and switch to it."
>                         (helm-comp-read "Switch to shell buffer: " bufs
>                                         :must-match t)
>                       (car bufs)))
> -        (switch-to-buffer it)
> +        (if-let ((window (display-buffer it)))
> +            (select-window window)
> +          (switch-to-buffer it))
>        (cl-case helm-ff-preferred-shell-mode
>          (eshell-mode
>           (eshell helm-current-prefix-arg))
>
> Describe alternatives you've considered
>
> Temporary setting the current window as dedicated works, but that doesn't seem the right solution:

So you want to have a dedicated buffer for shell?
Do you have a particular reason to do that?
Note you don't have to advice helm for this you can use
`special-display-regexps`.

> (advice-add #'helm-ff-switch-to-shell :around #'my-around-dedicated-window)
>
> (defun my-around-dedicated-window (fn &rest args)
>   (let ((win (selected-window))
>         (old (window-dedicated-p)))
>     (unwind-protect
>         (progn
>           (set-window-dedicated-p win t)
>           (apply fn args))
>       (set-window-dedicated-p win old))))
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.*


-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by lionel-** [comment]
> Ok, if you split in two vertical windows and you start helm from the
right window, your shell will be displayed in the right window.

Right but I need it to open in the right window even when I browse files from the left window (which is common in my workflow since this window contains buffers for source files). This happens when the eshell buffer doesn't exist yet because I've configured `display-buffer-alist` to always open eshell in the right window. However if the eshell buffer already exists, helm-ff calls `switch-to-buffer` which always open in the current window.


> Please describe what was working and what is no more working.

Previously the shell would open in the right window even when helm-ff was running from the left window. This doesn't really matter because I don't understand how it worked before. The bottom line is that `helm-ff-switch-to-shell` uses `switch-to-buffer` which is meant to open in the current window. This doesn't allow configuration without using advices.

> Note you don't have to advice helm for this you can use
`special-display-regexps`.

This variable is obsolete in favour of `display-buffer-alist`. `switch-to-buffer` doesn't consult this variable though. The proposed patch makes it possible to consult it.

**Comment by thierryvolpiatto** [comment]
Lionel Henry <notifications@github.com> writes:

> Previously the shell would open in the right window even when helm-ff
> was running from the left window. This doesn't really matter because I
> don't understand how it worked before. The bottom line is that
> helm-ff-switch-to-shell uses switch-to-buffer which is meant to open
> in the current window. This doesn't allow configuration without using
> advices.

Thanks for explaining.

> The proposed patch makes it possible to consult it.

Thanks for the patch, applied with modification to not use if-let.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by lionel-** [comment]
Thanks!

**Comment by lionel-** [comment]
Sorry I should have mentioned I'm not very familiar with how display-buffer is used. Looking more into it, I think we could improve the patch.

#### Handling frames

It seems using `pop-to-buffer` instead of `display-buffer` might be more appropriate. This is a wrapper around `display-buffer` but with some additional logic for selecting windows and frames. From the docstring:

```
If a suitable window is found, select that window.  If it is not
on the selected frame, raise that window's frame and give it
input focus.
```

I imagine having shells in their own frames on a different monitor is a common setting, so that seems important. `pop-to-buffer` doesn't fall back to `switch-to-buffer` when no window is displayed, which is different from my patch, but that's probably the right behaviour actually. This would only be the case if the buffer was explicitly prevented from being displayed by the user IIUC.

So, a simpler and probably more correct patch would be to replace `switch-to-buffer` by `pop-to-buffer`.


#### Preserving the existing default behaviour

The previous default behaviour was to open in the same window. If we use `pop-to-buffer` or `display-buffer`, the default behaviour, as controlled by `display-buffer-fallback-action`, is to reuse a window that already displays the buffer, or pop it up to a new frame or window. This is a behaviour change.

If you'd like to avoid this default behaviour change, you can specify a default action that will have priority over `display-buffer-fallback-action` but will be overridden by the user configuration in `display-buffer-alist`.

For these reasons, I suggest to use:

```elisp
;; Display in same window by default to preserve the historical behaviour
(pop-to-buffer it '(display-buffer-same-window))
```

**Comment by thierryvolpiatto** [comment]
Lionel Henry <notifications@github.com> writes:

> So, a simpler and probably more correct patch would be to replace switch-to-buffer by pop-to-buffer.
>
> Preserving the existing default behaviour
>
> The previous default behaviour was to open in the same window. If we
> use pop-to-buffer or display-buffer, the default behaviour, as
> controlled by display-buffer-fallback-action, is to reuse a window
> that already displays the buffer, or pop it up to a new frame or
> window. This is a behaviour change.
>
> If you'd like to avoid this default behaviour change, you can specify
> a default action that will have priority over
> display-buffer-fallback-action but will be overridden by the user
> configuration in display-buffer-alist.
>
> For these reasons, I suggest to use:
>
> ;; Display in same window by default to preserve the historical behaviour
> (pop-to-buffer it '(display-buffer-same-window))

Make sense, applied, thanks.
PS: If you want to do more changes please make a PR.

> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.*


-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
