### ISSUE TITLE
C-r broken in repeat-complex-command

### ISSUE THREAD

**Issue by michael-heerdegen** [emacs-helm/helm#2351]
Hi,

I'm using up-to-date Helm from Melpa with an Emacs master built.

Recipe: M-x repeat-complex-command C-r

Instead of showing the history, an error is raised:

Wrong type argument: stringp, (repeat-complex-command 1)
string= ""

The reason is that in `helm-minibuffer-history` the elements of the `minibuffer-history-variable` are tested for string= "", but in this case, the elements are the elements of `command-history` and these are not strings.

TIA,

Michael.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Hi,

Hi Michael,

> I'm using up-to-date Helm from Melpa with an Emacs master built.
>
> Recipe: M-x repeat-complex-command C-r
>
> Instead of showing the history, an error is raised:
>
> Wrong type argument: stringp, (repeat-complex-command 1)
> string= ""
>
> The reason is that in helm-minibuffer-history the elements of the
> minibuffer-history-variable are tested for string= "", but in this
> case, the elements are the elements of command-history and these are
> not strings.

Testing now with equal.

Thanks!

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> Hi Michael,

Hi Thierry!

> Testing now with equal.

Yip, fixed - thanks!
