### ISSUE TITLE
Add variable to disable appending crm-separator?

### ISSUE THREAD

**Issue by kyleam** [emacs-helm/helm#2353]
With 21261899, `helm-completion-in-region--insert-result` appends a separator.  I understand why that'd be useful behavior for typical `completing-read-multiple` calls, but it leads to undesirable behavior for `magit-completing-read-multiple`.

As an example, magit reads a diff range with a separator of "\\.\\.\\.?", allowing the user to enter, say, "a" or "a..b" or "a...b".  (They could technically go farther, entering "a..b..c", though that of course isn't a valid git range.)  Anyway, as of 21261899, selecting "a" will result in "a," (trailing comma) in the prompt, leading to git-diff being incorrectly called with "a,".

Note that "," is the separator that `helm-completion-in-region--insert-result` falls back to when it can't find the separator based on `crm-separator` matching previous input.  Even if a valid separator was determined, though, appending it to the completion would lead to an undesirable result in this context ("a.." instead of "a").  Unlike `completing-read-multiple`, `magit-completing-read-multiple` does not split the result on the `crm-separator`, since the particular form of the separator is a meaningful part of the range.

Would you be open to adding a defvar that we can bind to disable this behavior?

**Comment by thierryvolpiatto** [comment]
Kyle Meyer <notifications@github.com> writes:

> With 2126189, helm-completion-in-region--insert-result appends a separator. I understand why that'd be useful behavior for typical completing-read-multiple calls, but it
> leads to undesirable behavior for magit-completing-read-multiple.
>
> As an example, magit reads a diff range with a separator of "\.\.\.?", allowing the user to enter, say, "a" or "a..b" or "a...b". (They could technically go farther,
> entering "a..b..c", though that of course isn't a valid git range.) Anyway, as of 2126189, selecting "a" will result in "a," (trailing comma) in the prompt, leading to
> git-diff being incorrectly called with "a,".
>
> Note that "," is the separator that helm-completion-in-region--insert-result falls back to when it can't find the separator based on crm-separator matching previous input.
> Even if a valid separator was determined, though, appending it to the completion would lead to an undesirable result in this context ("a.." instead of "a"). Unlike
> completing-read-multiple, magit-completing-read-multiple does not split the result on the crm-separator, since the particular form of the separator is a meaningful part of
> the range.
>
> Would you be open to adding a defvar that we can bind to disable this behavior?

Yes, but for now I don't understand how to use this, I tried even with
helm-mode disabled but I have only completion on other branches and
tags, I expected completion on revisions but maybe I misunderstand how
it works, didn't find much help in documentation.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Still don't understand how to use magit diff range, what I see is after each completion helm append "," which is wrong obviously, I don't unserstand why magit use a regexp as separator i.e. `"\\.\\.\\.?"` @tarsius ?
What I can do is making a variable for "," default separator instead of harcoding it, like this @tarsius can let bind it in its magit fn:

``` diff
diff --git a/helm-mode.el b/helm-mode.el
index 62179fca..7544eb99 100644
--- a/helm-mode.el
+++ b/helm-mode.el
@@ -1854,6 +1854,8 @@ Can be used for `completion-in-region-function' by advicing it with an
         (advice-remove 'lisp--local-variables
                        #'helm-mode--advice-lisp--local-variables)))))
 
+(defvar helm-crm-default-separator ","
+  "Default separator for `completing-read-multiple'.")
 (defun helm-completion-in-region--insert-result (result start point end base-size)
   (cond ((stringp result)
          (choose-completion-string
@@ -1876,7 +1878,7 @@ Can be used for `completion-in-region-function' by advicing it with an
                          ;; it matches or default to "," if no match.
                          (eq (length crm-separator) 1)
                          crm-separator)
-                        ",")))
+                        helm-crm-default-separator)))
            ;; Try to find a default separator. If `crm-separator' is a
            ;; regexp use the string the regexp is matching.
            (save-excursion
```
Would that help?

**Comment by thierryvolpiatto** [comment]
Finally after reading both git-diff man page and magit code, I could understand what this tool is for and how to use it.
I think the installed patch fixes the problem once the new variable is used in `magit-completing-read-multiple`.

``` diff
diff --git a/lisp/magit-utils.el b/lisp/magit-utils.el
index d221b57a..addd472f 100644
--- a/lisp/magit-utils.el
+++ b/lisp/magit-utils.el
@@ -523,6 +523,7 @@ into a list."
          (minibuffer-completion-table #'crm--collection-fn)
          (minibuffer-completion-confirm t)
          (helm-completion-in-region-default-sort-fn nil)
+         (helm-crm-default-separator nil)
          (input
           (cl-letf (((symbol-function 'completion-pcm--all-completions)
                      #'magit-completion-pcm--all-completions))
```

**Comment by kyleam** [comment]
Thanks for the replies.  It seems you worked through your earlier questions, so I'll skip over those.

>  What I can do is making a variable for "," default separator instead of harcoding it
> [...]
> Would that help?

In the case of `magit-read-range`, it's equivalent to not appending the separator, so yes, it resolves the issue.

There's a similar case in `magit-log-read-revs` that isn't solved with the current implementation.  `magit-log-read-revs` uses a more complicated value for `crm-separator`: "\\(\\.\\.\\.?\\|[, ]\\)".  That regexp has a space, so the "find default separator" logic in `helm-completion-in-region--insert-result` ends up setting `sep` to a space based on matching the trailing space in the prompt.

Two fixes (both maybe worthwhile on their own) come to mind:

  * Is "find default separator" the logic off-by-one in that it considers the first character of the prompt?  If this match didn't happen, `magit-log-read-revs` would use `helm-crm-default-separator => nil` and work as intended, from Magit's point of view at least.

  * If `helm-crm-default-separator` is specified, it seems the "find default separator" logic isn't necessary.  The default value for the variable could be set to some symbol (`auto`?) and then any other values could be taken as is.

**Comment by thierryvolpiatto** [comment]
Kyle Meyer <notifications@github.com> writes:

> Two fixes (both maybe worthwhile on their own) come to mind:
>
>   • Is "find default separator" the logic off-by-one in that it
>   considers the first character of the prompt? If this match didn't
>   happen, magit-log-read-revs would use helm-crm-default-separator =>
>   nil and work as intended, from Magit's point of view at least.
>    
>   • If helm-crm-default-separator is specified, it seems the "find
>   default separator" logic isn't necessary. The default value for the
>   variable could be set to some symbol (auto?) and then any other
>   values could be taken as is.

Now when SEP is not a string i.e. fallback to helm-crm-default-separator
which is nil in our case, the default separator is not searched, so it
should work as expected. I tried with "l o" from magit-status.

For the magit side:
It is up to the user to enter separators, perhaps it would be
good to specify (in prompt?) the possible separators i.e. "..", "...", "," or
" " and document them somewhere else?

I know now we can use this separators because I entered in this issue,
but before I had no ideas on what to use for either diff range of
log rev.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by kyleam** [comment]
> so it should work as expected

Works as expected on my end.  Thank you.

> For the magit side: It is up to the user to enter separators, perhaps it would be good to specify (in prompt?) the possible separators i.e. "..", "...", "," or " " and document them somewhere else?

Hmm, `magit-log-read-revs` tries to indicate the "," separator in its prompt: "Log rev,s: ".  A space behaves the same as comma, so that's covered too.  Perhaps that's too cryptic, but I don't have any better ideas of how to do it without taking up too much space.

That still leaves the diff separators (".." and "...") for `magit-log-read-revs`.  I can't think of a clear and concise way to indicate those in the prompt, but this behavior should certainly be documented.  I'll take a closer look and try to fill in any gaps.

**Comment by thierryvolpiatto** [comment]
Kyle Meyer <notifications@github.com> writes:

>     so it should work as expected
>    
> Works as expected on my end. Thank you.

Good thanks to confirm.

>     For the magit side: It is up to the user to enter separators,
>     perhaps it would be good to specify (in prompt?) the possible
>     separators i.e. "..", "...", "," or " " and document them
>     somewhere else?
>    
> Hmm, magit-log-read-revs tries to indicate the "," separator in its
> prompt: "Log rev,s: ". A space behaves the same as comma, so that's
> covered too. Perhaps that's too cryptic,

Yes, I understand it now you tell me, before I was thinking of something
like rev plural, but perhaps english speakers don't make same error.

> but I don't have any better ideas of how to do it without taking up
> too much space.

But wait, doesn't Log rev support ".." and "..." as well?

> That still leaves the diff separators (".." and "...") for
> magit-log-read-revs. I can't think of a clear and concise way to
> indicate those in the prompt, but this behavior should certainly be
> documented. I'll take a closer look and try to fill in any gaps.

Perhaps in the magit-popup buffer? (not sure if it is still magit-popup).

Thanks.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by kyleam** [comment]
>> Hmm, magit-log-read-revs tries to indicate the "," separator in its prompt: "Log rev,s: ". A space behaves the same as comma, so that's covered too. Perhaps that's too cryptic,
>
> Yes, I understand it now you tell me, before I was thinking of something like rev plural, but perhaps english speakers don't make same error.
>
>> but I don't have any better ideas of how to do it without taking up too much space.
>
> But wait, doesn't Log rev support ".." and "..." as well?

It does.  Sorry for not presenting it clearly.  I was taking the separators in turn; the ".." and "..." come in the next sentence...

>> That still leaves the diff separators (".." and "...") for magit-log-read-revs.

... but I meant to say "range separator" instead of "diff separator" here, since the "..." and ".." ranges are used in both log and diff.  (Confusingly, ranges mean something quite different to diff-related git commands than they do to log-related ones.)

>> I can't think of a clear and concise way to indicate those in the prompt, but this behavior should certainly be documented. I'll take a closer look and try to fill in any gaps.

> Perhaps in the magit-popup buffer?

Perhaps, though I think if something is short and clear enough to put there, it'd probably work just as well in the prompt, closer to where the actual completion happens.

> (not sure if it is still magit-popup).

magit-popup has been replaced by transient now.
