### ISSUE TITLE
Unexpected highlight when executing helm-imenu-persistent-action

### ISSUE THREAD

**Issue by twlz0ne** [emacs-helm/helm#2354]
![Screenshot_2020-08-01_at_2.05.54_AM--helm-imenu-persistent-action|640x417](https://emacs-china.org/uploads/default/original/2X/e/e2af511c105136c75eeb03c8188b8c30caaa3ef6.png)

## Expected behavior

Don't highlight the symbol at point when executing `helm-imenu-persistent-action`.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

The symbol at point is highlighted.

## Steps to reproduce (recipe)

1. Create an empty buffer named **test.el**, and enable emacs-lisp-mode.
2. Paste following code into **test.el**:

``` elisp
(defun foo () nil)

(defun bar () nil)

(defun qux () nil)

(save-excursion
  (goto-char (point-min))
  (forward-char 1) ;; goto the first ‘defun’
  (minibuffer-with-setup-hook
      (lambda ()
        (execute-kbd-macro (kbd "C-j"))) ;; persistent action
    (helm-imenu)))
```

3. Press `C-x e` to eval the last form.

## Describe versions of Helm, Emacs, operating system, etc.

- helm-20200728.1222/
- Emacs 28.0.50
- macOS 10.12.6

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no): NO

There is an error on my computer:

``` sh
⋊> [~/r/emacs-helm] ./emacs-helm.sh
find: -printf: unknown primary or operator
```

So I created my own minimal test script.

<details>
<summary>test-helm.el</summary>

``` elisp
;;; Usage: /path/to/emacs -nw -Q -l /path/to/test-helm-imenu-persistent-action.el
;;; Date: 2020-07-31_11.56.40
(toggle-debug-on-error)

(add-to-list 'load-path (expand-file-name "~/repos/emacs-async"))
(add-to-list 'load-path (expand-file-name "~/repos/emacs-helm"))

;; ------------------------------------------------------------------

(require 'helm)
(require 'helm-config)

(add-hook 'after-init-hook
          (lambda ()
            (helm-mode 1)

            (switch-to-buffer "*.el")
            (emacs-lisp-mode)
            (insert "\
(defun foo () nil)

(defun bar () nil)

(defun qux () nil)

;; test helm-imenu")
            
            ;; Reproduce steps:
            (save-excursion
              (goto-char (point-min))
              (forward-char 1) ;; goto to the first ‘defun’
              (minibuffer-with-setup-hook
                  (lambda ()
                    (execute-kbd-macro (kbd "C-j"))) ;; persistent action
                (helm-imenu)))))

(run-hooks 'after-init-hook)
;;; test-helm-imenu-persistent-action.el ends here
```
</details>

## Are you using Spacemacs? (yes/no): NO

**Comment by thierryvolpiatto** [comment]
twlz0ne <notifications@github.com> writes:

> Screensh
>
> Expected behavior
>
> Don't highlight the symbol at point when executing helm-imenu-persistent-action.

Why?

> Actual behavior (from emacs-helm.sh if possible, see note at the bottom)
>
> The symbol at point is highlighted.

Of course it is highlighted, what's the problem?

> Steps to reproduce (recipe)
>
>  1. Create an empty buffer named test.el, and enable emacs-lisp-mode.
>  2. Paste following code into test.el:
>
> (defun foo () nil)
>
> (defun bar () nil)
>
> (defun qux () nil)
>
> (save-excursion
>   (goto-char (point-min))
>   (forward-char 1) ;; goto the first ‘defun’
>   (minibuffer-with-setup-hook
>       (lambda ()
>         (execute-kbd-macro (kbd "C-j"))) ;; persistent action
>     (helm-imenu)))

Why do you need this?

> ⋊> [~/r/emacs-helm] ./emacs-helm.sh
> find: -printf: unknown primary or operator

Probably MacOs is using a crap find version.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by twlz0ne** [comment]
> Of course it is highlighted, what's the problem?

I haven't typed anything yet, and these highlights make me confused.

 And there is a highlight (`helm-match-item`) on the image in the comments, where it will never be highlighted as `helm-selection-line`.

I think the `helm-match-item` should appear on the line that is highlighted as `helm-selection-line`.

In my opinion, the following highlighting is more reasonable:

![Screenshot_2020-08-01_at_8_06_51_PM--helm-imen-persistent-action--expected-highlight](https://user-images.githubusercontent.com/2653486/89101525-248f1980-d433-11ea-9aa1-42de1fdcc7de.png)

**Comment by thierryvolpiatto** [comment]
Seems reasonable indeed, but that makes me discover another bug, will try to fix ASAP. Thanks.

**Comment by thierryvolpiatto** [comment]
Now you can customize `helm-imenu-highlight-matches-around-point-max-lines` which default to 0, which mean highlight only in the matched line (like in your screenshot above).
Also fixed a bug where matched items were highlighted beyond `helm-highlight-matches-around-point-max-lines`.

**Comment by twlz0ne** [comment]
I think there are still some issues.

- Step 1. Move point at `defun`, invoke `helm-imenu`, Press `C-j` (helm-input => `"\_<defun\_>"`):

![1_C-c-i_C-j](https://user-images.githubusercontent.com/2653486/89119387-cde01900-d4e0-11ea-940e-26e55c606204.png)

- Step 2. Type "foo", Press `C-j` (helm-input => `"foo"`)

![2_typing-foo_C-j](https://user-images.githubusercontent.com/2653486/89119398-e05a5280-d4e0-11ea-83c3-aefbff037a22.png)

- Step 3. Delete "foo", Press `C-j` (helm-input => `""`)

![3_remove-foo_C-j](https://user-images.githubusercontent.com/2653486/89119400-e4867000-d4e0-11ea-8914-4d9061af9a08.png)

Why does `helm-input` have a value (`"\_<defun\_>"`) at step 1, but not at step 3?

**Comment by thierryvolpiatto** [comment]
twlz0ne <notifications@github.com> writes:

> Why does helm-input have a value ("\_<defun\_>") at step 1, but not at step 3?

Because helm display its candidates according to default only at first
call, once you start typing in, the pattern becomes what you type and no
more default, when you delete what you have typed the pattern become
what you have typed, that is and empty string.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by twlz0ne** [comment]
I see where the default come from:

https://github.com/emacs-helm/helm/blob/f683ba14a2a9d6a76e124ec6fda406debd3a4834/helm-imenu.el#L330

I doubt if the default is necessary.

Imagine this. The user can call `helm-imenu` from anywhere, most of the time he/she probably doesn't care about the symbol under the cursor.

**Comment by thierryvolpiatto** [comment]
twlz0ne <notifications@github.com> writes:

> I see where the default come from:
>
> https://github.com/emacs-helm/helm/blob/f683ba14a2a9d6a76e124ec6fda406debd3a4834/helm-imenu.el#L330
>
> I doubt if the default is necessary.

Of course it is necessary, it allows you to jump to symbol at point!
See `helm-imenu-execute-action-at-once-if-one`.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Consider a file containing this:
```elisp
(defun foo ())

(defun bar ())

(defun baz ()
  (foo))
```
Move your cursor on the symbol foo in the function baz and call helm-imenu, you will see helm-imenu jump to the foo definition.

**Comment by twlz0ne** [comment]
If  the `helm-imenu--execute-action-at-once-p` executed success, the `helm-imenu` window will not appear, and the highlighting of `foo` is meaningless.

If there is no `(defun foo ())` in the file, the `helm-imenu--execute-action-at-once-p` has nowhere to jump, then why highlight the `foo`?

**Comment by thierryvolpiatto** [comment]
twlz0ne <notifications@github.com> writes:

> If the helm-imenu--execute-action-at-once-p executed success, the helm-imenu window will not appear, and the highlighting of foo is meaningless.
>
> If there is no (defun foo ()) in the file, the helm-imenu--execute-action-at-once-p has nowhere to jump, then why highlight the foo?

I agree it is not very useful, in my workflow I never hit this problem
because unless I want to jump to a specific symbol, I do a C-a before
calling helm-imenu so that I have preselection on the name of current
definition, so apart by accident where I forget to hit C-a I have no
symbol highlighted (it is why I never noticed this bug even if I use a
lot helm-imenu).
But yes perhaps we could completely remove this highlighting in helm-imenu
even if it doesn't harm, OTOH the same code serve for helm-occur/grep, I
will see what I can do when I find time.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Done.
