### ISSUE TITLE
Candidate list is sometimes not updated or updated with old input pattern

### ISSUE THREAD

**Issue by yantar92** [emacs-helm/helm#2359]
## Expected behavior

Normally `helm-M-x` and generic helm completion should update the candidate list as I type.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

From time to time (more often when there is high CPU load or when the candidate search takes long time), I get an empty candidate list or candidate list frozen in outdated state (not in sync with the current input pattern). I managed to capture some of the behavior in the video: [helm.mkv.tar.gz](https://github.com/emacs-helm/helm/files/5046755/helm.mkv.tar.gz)

## Steps to reproduce (recipe)

I cannot reliably reproduce this with built-in helm commands. It just happen from time to time.

## Describe versions of Helm, Emacs, operating system, etc.

Helm master (85061a39).
GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0) of 2020-08-04
Gentoo (Linux yantar92-laptop 5.7.6-gentoo)

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):

No. I cannot reproduce the bug reliably + `emacs-helm.sh` does not run on my system.

## Are you using Spacemacs? (yes/no):

no

**Comment by thierryvolpiatto** [comment]
yantar92 <notifications@github.com> writes:

> Expected behavior
>
> Normally helm-M-x and generic helm completion should update the candidate list as I type.
>
> Actual behavior (from emacs-helm.sh if possible, see note at the bottom)
>
> From time to time (more often when there is high CPU load or when the
> candidate search takes long time), I get an empty candidate list or
> candidate list frozen in outdated state (not in sync with the current
> input pattern). I managed to capture some of the behavior in the
> video: helm.mkv.tar.gz

You are asking for helm-M-x and generic completion but your video is about something else not
part of Helm.
I cannot reproduce such a behavior with any of the helm commands I use.

> Describe versions of Helm, Emacs, operating system, etc.
>
> Helm master (85061a3).

If you have installed helm from sources with "make && sudo make install"
emacs-helm.sh is symlinked to "/usr/local/bin/helm", so running helm from any place
should work fine.

> GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0) of 2020-08-04
> Gentoo (Linux yantar92-laptop 5.7.6-gentoo)
>
> Are you using emacs-helm.sh to reproduce this bug? (yes/no):
>
> No. I cannot reproduce the bug reliably + emacs-helm.sh does not run on my system.

Please try to reproduce from emacs-helm.sh with commands bundled with
helm (helm-M-x, HFF etc...), it works fine on any Linux
box, no reasons to not use it.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by yantar92** [comment]
> You are asking for helm-M-x and generic completion but your video is about something else not
part of Helm.
> I cannot reproduce such a behavior with any of the helm commands I use.

In the video I use two commands: `helpful-variable` and `helm-M-x` -> `debug-on-entry`. Both commands call `completing-read` internally, thus delegating to helm completion. 

However, I observe the same problem with pretty much any helm command from time to time. Video is just illustrating what is happening.

What is worse, the behavior on video does not happen most of time and I cannot reproduce it reliably. It is just that I was lucky to record the video this time.

> If you have installed helm from sources with "make && sudo make install"
emacs-helm.sh is symlinked to "/usr/local/bin/helm", so running helm from any place
should work fine.

Unfortunately, running `make` in helm source yields 

```
In toplevel form:
helm.el:35:1: Error: Cannot open load file: No such file or directory, async
make: *** [Makefile:69: batch-compile] Error 1
```

**Comment by thierryvolpiatto** [comment]
yantar92 <notifications@github.com> writes:

>     You are asking for helm-M-x and generic completion but your video is about something else not
>     part of Helm.
>     I cannot reproduce such a behavior with any of the helm commands I use.
>    
> In the video I use two commands: helpful-variable and helm-M-x -> debug-on-entry. Both commands call completing-read internally, thus delegating to helm completion.
>
> However, I observe the same problem with pretty much any helm command from time to time. Video is just illustrating what is happening.
>
> What is worse, the behavior on video does not happen most of time and I cannot reproduce it reliably. It is just that I was lucky to record the video this time.
>
>     If you have installed helm from sources with "make && sudo make install"
>     emacs-helm.sh is symlinked to "/usr/local/bin/helm", so running helm from any place
>     should work fine.
>    
> Unfortunately, running make in helm source yields
>
> In toplevel form:
> helm.el:35:1: Error: Cannot open load file: No such file or directory, async
> make: *** [Makefile:69: batch-compile] Error 1

Look at the wiki on how to install helm.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by yantar92** [comment]
> Look at the wiki on how to install helm.

Thanks. I will try it. I guess it may be a good idea to add a link to wiki to the bug report template.

**Comment by yantar92** [comment]
I managed to make `emacs-helm.sh` working, but the issue is not reproduceable. I am not able to reproduce it on my config reliably. No doubt it did not appear so easily in `emacs-helm.sh`. 

If anyone have any clues what may be happening, let me know. I will keep trying to reproduce the problem myself, but the above video is the best I managed to get so far.
