### ISSUE TITLE
Space appended to completion when :annotation-function returns string

### ISSUE THREAD

**Issue by non-Jedi** [emacs-helm/helm#2360]
## Expected behavior

The first argument that `:exit-function` receives should be the un-annotated string that is being completed-to.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

At least part of the the value returned from `:annotation-function` is appended to the completion name when its passed to `:exit-function`. The annotation also appears to be included in the final in-buffer completion.

The docstring for `completion-extra-properties` says:

>The function must accept one argument, a completion string,
>and return either nil or a string which is to be displayed
>next to the completion (but which is not part of the
>completion).

## Steps to reproduce (recipe)

```elisp
(defun my-capf ()
  (list (line-beginning-position) (point) '("foo" "foobar")
        :annotation-function (lambda (_) " ")
        :exit-function (lambda (string _status)
                         (message ":exit-function string: %s, length: %d"
                                  string (length string)))))

(setq completion-at-point-functions (list 'my-capf))
```

The message when completing "foo" should be `:exit-function string: foo, length: 3`; instead it is `:exit-function string: foo , length: 4`. "foo" should be inserted into the buffer by itself; instead a space is inserted after "foo".

## Describe versions of Helm, Emacs, operating system, etc.

Helm master, Emacs 26.3, Linux

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):

Yes

## Are you using Spacemacs? (yes/no):

No

**Comment by non-Jedi** [comment]
Actually the space gets appended to the completion result if `:annotation-function` returns *any* string. The value returned by `:annotation-function` seems to be irrelevant for this bug:

```elisp
(defun my-capf ()
  (list (line-beginning-position) (point) '("foo" "foobar")
	:annotation-function (lambda (_) "")
        :exit-function (lambda (string _status)
                         (message ":exit-function string: %s, length: %d" string (length string)))))

(setq completion-at-point-functions (list 'my-capf))
```

The above shows the same output of `:exit-function string: foo , length: 4`.

**Comment by thierryvolpiatto** [comment]
Adam B <notifications@github.com> writes:

> Actually the space gets appended to the completion result if :annotation-function returns any string. The value returned by :annotation-function seems to be irrelevant for
> this bug:
>
> (defun my-capf ()
>   (list (line-beginning-position) (point) '("foo" "foobar")
>         :annotation-function (lambda (_) "")
>         :exit-function (lambda (string _status)
>                          (message ":exit-function string: %s, length: %d" string (length string)))))
>
> (setq completion-at-point-functions (list 'my-capf))
>
> The above shows the same output of :exit-function string: foo , length: 4.

The space at end is added to display annotation in a display property
added to this space (not by helm, but by minibuffer.el).

I fixed this but at insertion only, that's mean the recipe above will
still return :length 4, this to preserve properties that may be needed
by the :exit-function, up to you to modify this in your :exit-function
if needed.
Let me know if this is correct for you.

Thanks.

-- 
Thierry
