### ISSUE TITLE
helm-find-files doesn't show candidates

### ISSUE THREAD

**Issue by offbyone** [emacs-helm/helm#2362]
## Expected behavior

Using spacemacs, I expect helm-find-files to show file and directory candidates

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

What I get is an empty set of candidates/completions, no matter which directory I am in. Notably, though, `helm-projectile-find-file` works just fine and finds files within a project.

## Steps to reproduce (recipe)

In literally any directory, invoke `helm-find-files` (I originally noted the issue via `spacemacs/helm-find-files` but I can confirm that directly invoking `helm-find-files` also has the same result)

## Backtraces if any (`M-x toggle-debug-on-error`)

N/A. There's nothing of note in `*Messages*` either.

## Describe versions of Helm, Emacs, operating system, etc.

`GNU Emacs 28.0.50 (build 1, x86_64-apple-darwin19.3.0, NS appkit-1894.30 Version 10.15.3 (Build 19D76)) of 2020-03-21`

helm-files version: elpa, 20200813.627

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no): 

no, since it's tied into spacemacs. Also, when I tried it:

```
For information about GNU Emacs and the GNU system, type C-h C-a.
byte-code: Cannot open load file: No such file or directory, helm
Making completion list...
```

So, that isn't working. I tried several variations, including attempting to reference my binary with `-P` to no avail.

## Are you using Spacemacs? (yes/no):

yes

## IMPORTANT NOTE

Helm provides a script named `emacs-helm.sh` which runs Helm in a neutral
environment: no other packages and only minimal settings.

When possible, use it to reproduce your Helm issue to ensure no other package is
interfering.

To run it, simply switch to the directory where Helm is installed and call `./emacs-helm.sh`.
If necessary you can specify emacs executable path on command line with "-P" option.

Thanks.

**Comment by offbyone** [comment]
Note: I recognize that this verges on an "it doesn't work" bug report, and I'm sorry; I literally haven't the foggiest idea where to look for error messages that might be the cause of this. If there's a way to turn on extended debugging here, I will happily jump through the hoops, because otherwise I'm stuck with `ivy` and I really miss Helm here.

**Comment by manuel-uberti** [comment]
Could you try cloning the Helm git repo, running `make` and then run `./emacs-helm.sh`?

**Comment by offbyone** [comment]
The compilation process spits out a lot of these:

```
In toplevel form:
helm-external.el:21:1: Error: Cannot open load file: No such file or directory, async
```

And `*Messages*` contains this:

```
For information about GNU Emacs and the GNU system, type C-h C-a.
eval-buffer: Cannot open load file: No such file or directory, async
```

(Note that I don't see that error in spacemacs' load screen at all)

**Comment by offbyone** [comment]
This also occurs on my work machine, which is subtly different:

``
GNU Emacs 28.0.50 (build 1, x86_64-apple-darwin18.7.0, NS appkit-1671.60 Version 10.14.6 (Build 18G3020)) of 2020-03-18
Helm version 20200803.937
```

**Comment by manuel-uberti** [comment]
On my Ubuntu 20.04, this is what I get:
```
manuel@hathaway:~/code/helm$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working tree clean
manuel@hathaway:~/code/helm$ make
rm -f helm-adaptive.elc helm-autoloads.elc helm-bookmark.elc helm-buffers.elc helm-color.elc helm-comint.elc helm-command.elc helm-config.elc helm-core-pkg.elc helm-dabbrev.elc helm-easymenu.elc helm-elisp-package.elc helm-elisp.elc helm-eshell.elc helm-eval.elc helm-external.elc helm-files.elc helm-find.elc helm-font.elc helm-for-files.elc helm-global-bindings.elc helm-grep.elc helm-help.elc helm-id-utils.elc helm-imenu.elc helm-info.elc helm-lib.elc helm-locate.elc helm-man.elc helm-misc.elc helm-mode.elc helm-multi-match.elc helm-net.elc helm-occur.elc helm-pkg.elc helm-regexp.elc helm-ring.elc helm-semantic.elc helm-shell.elc helm-source.elc helm-sys.elc helm-tags.elc helm-types.elc helm-utils.elc helm-x-files.elc helm.elc
emacs -q -batch --eval "(progn (setq generated-autoload-file (expand-file-name \"helm-autoloads.el\" \".\")) \
(setq backup-inhibited t) (update-directory-autoloads \".\"))"
  INFO     Scraping files for helm-autoloads.el... 
  INFO     Scraping files for helm-autoloads.el...done
emacs -q -batch -L . -L /home/manuel/.emacs.d/elpa/async-1.9.3 -L /home/manuel/.emacs.d/straight/build/async -f batch-byte-compile helm-adaptive.el helm-autoloads.el helm-bookmark.el helm-buffers.el helm-color.el helm-comint.el helm-command.el helm-config.el helm-core-pkg.el helm-dabbrev.el helm-easymenu.el helm-elisp-package.el helm-elisp.el helm-eshell.el helm-eval.el helm-external.el helm-files.el helm-find.el helm-font.el helm-for-files.el helm-global-bindings.el helm-grep.el helm-help.el helm-id-utils.el helm-imenu.el helm-info.el helm-lib.el helm-locate.el helm-man.el helm-misc.el helm-mode.el helm-multi-match.el helm-net.el helm-occur.el helm-pkg.el helm-regexp.el helm-ring.el helm-semantic.el helm-shell.el helm-source.el helm-sys.el helm-tags.el helm-types.el helm-utils.el helm-x-files.el helm.el
```
Then, after `./emacs-helm.sh` I see this in `*Messages*`:
```
For information about GNU Emacs and the GNU system, type C-h C-a.
Source file ‘/home/manuel/.emacs.d/straight/build/async/async-bytecomp.el’ newer than byte-compiled file; using older file
```

Note that I don't use Spacemacs, but I do use `straight.el` instead of regular `package.el`. I can't see what is going on on your side, unfortunately.

**Comment by offbyone** [comment]
That's the problem... neither can I. I tried edebug-stepping into the helm methods, but got lost somewhere around the sources invocation; I don't know where the actual source is, since I tried to edebug what I thought was it, but it wasn't called in the course of finding files.

**Comment by thierryvolpiatto** [comment]
Chris Rose <notifications@github.com> writes:

> Expected behavior
>
> Using spacemacs, I expect helm-find-files to show file and directory candidates

Please don't use Spacemacs for reporting bugs, we are going to loose our
time. Start with a clean install of async and helm (no Spacemacs) and
run emacs-helm.sh, if all is working fine there the bug is coming from
Spacemacs and/or one of the many packages used by spacemacs or one of
the modification Spacemacs did to helm.

To install helm see:

https://github.com/emacs-helm/helm/wiki#install

-- 
Thierry

**Comment by jr0cket** [comment]
Recent issues with Spacemacs and helm may be resolved by deleting all helm packages from `.emacs.d/elpa/` directory and restarting Emacs.

**Comment by offbyone** [comment]
@jr0cket I just tried that:

```
rm -rf ~/.emacs.d/elpa/*/*/helm*
```

Restarting emacs installed a lot of helm, but `helm-find-files` (and the spacemacs wrappers) do not find any values still.

**Comment by thierryvolpiatto** [comment]
As long as you continue installing and running helm with Spacemacs, we will not be able to solve your issue, only you can find what is wrong, we are not on your machine.
So for a clean install, uninstall all helm packages, git clone async package and install it with make && sudo make install, then do the same with helm. Once done, use `(require 'helm-config)` then M-x helm-find-files.
I don't say to install with package and melpa because I guess the core of your problem is a mess in the elpa installation with the too many packages installed by Spacemacs.

**Comment by thierryvolpiatto** [comment]
Note: Start with `emacs -q` not `-Q` to ensure your helm and async packages are known in load-path otherwise with -Q, you will need to add them to load-path manually.

Also note that when installing with make and make install, you can run from a shell `helm` directly without any config.

All of this is notified in helm wiki...

**Comment by offbyone** [comment]
Given that beyond "Spacemacs + Helm" my customizations are zero on this, I don't feel like I have a set of knobs to twiddle that you couldn't, as well, and you actually know how/where Helm's results are populated and I don't.  If you'd do me the courtesy of telling me how/where I can do my own debugging, instead of just repeating "you use spacemacs, so we won't help you", I'd be happy to take a stab at it myself. I'm not going to change my whole init framework, so having some idea of how to troubleshoot this and fix it would be great. I'm willing to try do the diagnostic legwork.

While it's your project, and I get that you don't personally use spacemacs... not gonna lie, your approach here is pretty hostile. I'd be interested in a guess as to how much of helm's userbase is using it via Spacemacs' default use of it too. My guess is "a fair amount" given that you've apparently got a "if you use our project this common way, we're going to ignore you" question in your issue template. So... good, I guess?

**Comment by offbyone** [comment]
So, FWIW, I stripped out my .emacs and went to a bare emacs. Installed `async` from ELPA (the make install approach from source failed) and then installed helm from source, and the issue does not appear.

I'm not sure how this set of steps helped anyone though; now I know that a configuration that I don't use nor intend to use works fine... but since that's not what I'll be running, it's not really providing me any value. How would you propose that I go forward, in a practical and useful way?

**Comment by thierryvolpiatto** [comment]
Chris Rose <notifications@github.com> writes:

> So, FWIW, I stripped out my .emacs and went to a bare emacs. Installed
> async from ELPA (the make install approach from source failed) and
> then installed helm from source, and the issue does not appear.
>
> I'm not sure how this set of steps helped anyone though; now I know
> that a configuration that I don't use nor intend to use works
> fine... but since that's not what I'll be running, it's not really
> providing me any value. How would you propose that I go forward, in a
> practical and useful way?

Now you know that your bug doesn't come from helm code but elsewhere.
Spacemacs is modifying Helm and and install hundred of packages,
probably it comes from either modifications done by Spacemacs or one
package that clash with Helm, how can I know?..


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Chris Rose <notifications@github.com> writes:

> Given that beyond "Spacemacs + Helm" my customizations are zero on
> this, I don't feel like I have a set of knobs to twiddle that you
> couldn't, as well, and you actually know how/where Helm's results are
> populated and I don't. If you'd do me the courtesy of telling me
> how/where I can do my own debugging,

I don't know.

> instead of just repeating "you use spacemacs, so we won't help you",
> I'd be happy to take a stab at it myself. I'm not going to change my
> whole init framework,

So you want me to install Spacemacs and debug Spacemacs, no way.

> so having some idea of how to troubleshoot this and fix it would be
> great.

If I could I tell you but I don't know.

> I'm willing to try do the diagnostic legwork.
>
> While it's your project, and I get that you don't personally use
> spacemacs... not gonna lie, your approach here is pretty hostile.

Sorry but I preserve myself, I don't want to spend my days debugging
Spacemacs, my part is to debug Helm that's all.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
So if Helm is working with a minimal config, I guess I can close this bug report.

Thanks.
