### ISSUE TITLE
minibuffer-local-must-match-filename-map: void-variable in emacs28

### ISSUE THREAD

**Issue by sewkokot** [emacs-helm/helm#2363]
The recent emacs built from git removes obsolete
`minibuffer-local-must-match-filename-map` variable. 

Deleting line 31 from `helm-global-bindings.el`:
```
minibuffer-local-must-match-filename-map; Older emacsen
```

solves the problem.

**Comment by daviderestivo** [comment]
@sewkokot Thanks for the tip ...

**Comment by thierryvolpiatto** [comment]
Seweryn Kokot <notifications@github.com> writes:

> The recent emacs built from git removes obsolete
> minibuffer-local-must-match-filename-map variable.
>
> Deleting line 31 from helm-global-bindings.el:
>
> minibuffer-local-must-match-filename-map; Older emacsen
>
> solves the problem.

Thanks, fixed by PR #2364.

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.*


-- 
Thierry
