### ISSUE TITLE
helm-get-candidates has error "Candidates function ... should run a process"

### ISSUE THREAD

**Issue by yamatakau08** [emacs-helm/helm#2367]
## Steps to reproduce (recipe)
1. M-x helm-do-ag
2. select the directory
3. input the arguments of helm-do-ag  "--depth=0"
    While input --depth=0,  the following error occurs.
```Error running timer: (error "Candidates function ‘#[0 \\301 \\210\\302\\300!\\207 [~/ helm-ag--do-ag-set-command helm-ag--do-ag-candidate-process] 2]’ should run a process")```

## Backtraces if any (`M-x toggle-debug-on-error`)
![image](https://user-images.githubusercontent.com/13044987/90364713-83919700-e09f-11ea-8722-1aefc948fe65.png)

note:
other helm-ag works fine.

## Describe versions of Helm, Emacs, operating system, etc.
helm-20200816.1406 installed from melpa
(emacs-version)
=> "GNU Emacs 28.0.50 (build 1, x86_64-w64-mingw32)
 of 2020-07-06"
system-type
=> Windows

helm-20200816.160 installed frome melpa
(emacs-version) 
=> "27.1"
system-type
=> darwin
**also have the same error.**

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):
no

## Are you using Spacemacs? (yes/no):
no

**Comment by manuel-uberti** [comment]
Could you please try reproducing the problem with `emacs-helm.sh`?

**Comment by thierryvolpiatto** [comment]
yamatakau08 <notifications@github.com> writes:

>  1. M-x helm-do-ag

There is no such command in helm.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
And looking at the backtrace, the source is build with functions that are not part of helm, closing.
Please reopen a bug starting with native helm command and as @manuel-uberti said from emacs-helm.sh.

**Comment by yamatakau08** [comment]
I assumed the root cause is in helm package itself.
But I understand this issue board is for helm package and native command of it.
Sorry for unfit issue posting.

**Comment by thierryvolpiatto** [comment]
yamatakau08 <notifications@github.com> writes:

> I assumed the root cause is in helm package itself.

No, it is not, if you have such error, it is you are using an async
source with a candidate-process function which is not returning a
process. But I can't help as I don't know most of the functions you are using.

> But I understand this issue board is for helm package and native command of it.
> Sorry for unfit issue posting.

No problem.

-- 
Thierry
