### ISSUE TITLE
helm-do-grep-ag can't show search results on Windows

### ISSUE THREAD

**Issue by shenhai-ran** [emacs-helm/helm#2370]
## Expected behavior
`helm-do-grep-ag` should show searched text in files

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
`helm-do-grep-ag` shows 0 results even there is from command line

## Steps to reproduce (recipe)
I have a fold called _C:/helm-ag-test_ with a file _helm-ag-test_, and only content is _helm-ag-test_.
When open this file with Emacs and `M-x helm-do-grep-ag`, search pattern for _helm_, it shows
![helm_ag_no_results](https://user-images.githubusercontent.com/8853417/90896423-e5b20b00-e3c3-11ea-8e4b-94315ae2a067.png)
While if I search _hh_ of curse nothing found, but ag response that.
![helm_ag_no_found](https://user-images.githubusercontent.com/8853417/90896264-9f5cac00-e3c3-11ea-90df-5f407ecf7bbf.png)

Search on command line with ag gives what it should be....
![ag_cmd_helm](https://user-images.githubusercontent.com/8853417/90896469-00847f80-e3c4-11ea-83b9-9dda518844d7.png)

## Describe versions of Helm, Emacs, operating system, etc.
 
- Helm version: 20200820.1936
- Emacs version: 26.3
- Windows 10 version: 1809
- Ag version: 2.1.0 +jit +lzma +zlib

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):
Yes
## Are you using Spacemacs? (yes/no):
No

**Comment by shenhai-ran** [comment]
> Why "hh"? If content of file is "helm-ag-test", what do you expect with "hh"?
> Yes but your pattern is "helm".

Sorry that I made it was not clear. What I meant was that if I search for "helm" I expect to get something and I did get the result from command line. But `helm-do-grep-ag` doesn't show any results.

I included search results for "hh" to illustrate that it seems that even though `helm-do-grep-ag` gives no result, "hh" was due to ag couldn't find any, while for "helm" ag could find results but is not shown by `helm-do-grep-ag`

Hope it is better this time...

> Describe versions of Helm, Emacs, operating system, etc. • Helm version: 20200820.1936 • Emacs version: 26.3 • Windows 10 version: 1809 • Ag version: 2.1.0 +jit +lzma +zlib Are you using emacs-helm.sh to reproduce this bug? (yes/no): Yes
> Are you sure? On Windows?

Well no, I used Msys2 .... so not on Windows

**Comment by thierryvolpiatto** [comment]
Could not reproduce.

**Comment by xiongtx** [comment]
I am also having this problem. It seems to have something to do w/ [this bit](https://github.com/emacs-helm/helm/blob/08e95dbfa12d7c47ec43cd81f06e8f2205d7f72f/helm.el#L5129-L5133) of code.

First I noticed a need to split on `"^M\n"` instead of `"\n"` b/c the output is like:

```
^[[1;33m1^[[0m^[[K:^[[30;43mvar^[[0m^[[K scriptFile = new DzFile(getScriptFileName());^M
^[[1;33m6^[[0m^[[K:  ^[[30;43mvar^[[0m^[[K nodes = getNodesNotParented(isClothing);^M
^[[1;33m1^[[0m^[[K:^[[30;43mvar^[[0m^[[K scriptFile = new DzFile(getScriptFileName());^M
...
```

Then something seems to happen in `helm-transform-candidates` to render the candidates empty. I haven't had the time to investigate further.
