### ISSUE TITLE
Helm issued errors: helm-match-from-candidates in source `Find Files': args-out-of-range (0 0) [2 times] error

### ISSUE THREAD

**Issue by student-sx** [emacs-helm/helm#2371]
After upgrading helm `helm-find-files` doesn't work anymore on my home directory (see below). Is there any workaround until this is fixed?

## Expected behavior

Opens candidate list from find files

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

Error message: 
```
Helm issued errors: helm-match-from-candidates in source `Find Files': args-out-of-range (0 0) [2 times]
```
## Steps to reproduce (recipe)

`M-x helm-find-files` on my home directory  (other dirs' work)

## Backtraces if any (`M-x toggle-debug-on-error`)
```
Debugger entered--Lisp error: (error "The mark is not set now, so there is no region")
  region-beginning()
  #f(compiled-function (method) #<bytecode 0x3ab945>)(nil)
  copy-region-as-kill(nil 29 1)
  kill-ring-save(nil 29 1)
  funcall-interactively(kill-ring-save nil 29 1)
  call-interactively(kill-ring-save nil nil)
  command-execute(kill-ring-save)
  read-from-minibuffer(#("Find files or url: " 0 19 (face helm-minibuffer-prompt)) "/home/myuser/" (keymap (f13 lambda nil (interactive) (helm-select-nth-action 12)) (f12 lambda nil (interactive) (helm-select-nth-action 11)) (f11 lambda nil (interactive) (helm-select-nth-action 10)) (f10 lambda nil (interactive) (helm-select-nth-action 9)) (f9 lambda nil (interactive) (helm-select-nth-action 8)) (f8 lambda nil (interactive) (helm-select-nth-action 7)) (f7 lambda nil (interactive) (helm-select-nth-action 6)) (f6 lambda nil (interactive) (helm-select-nth-action 5)) (f5 lambda nil (interactive) (helm-select-nth-action 4)) (f4 lambda nil (interactive) (helm-select-nth-action 3)) (f3 lambda nil (interactive) (helm-select-nth-action 2)) (f2 lambda nil (interactive) (helm-select-nth-action 1)) (menu-bar keymap (help-menu keymap (describe keymap (describe-mode . helm-help)))) (help keymap (109 . helm-help)) (23 . #f(compiled-function () (interactive nil) #<bytecode 0x16c147d>)) (f1 lambda nil (interactive) (helm-select-nth-action 0)) (8 keymap (109 . helm-help) (104 . undefined) (8 . undefined) (99 . helm-customize-group) (4 . helm-enable-or-switch-to-debug)) (20 . helm-toggle-resplit-and-swap-windows) (C-tab . undefined) (67108897 . helm-toggle-suspend-update) (3 keymap (57 . helm-execute-selection-action-at-nth-+9) (56 . helm-execute-selection-action-at-nth-+8) (55 . helm-execute-selection-action-at-nth-+7) (54 . helm-execute-selection-action-at-nth-+6) (53 . helm-execute-selection-action-at-nth-+5) (52 . helm-execute-selection-action-at-nth-+4) (51 . helm-execute-selection-action-at-nth-+3) (50 . helm-execute-selection-action-at-nth-+2) (49 . helm-execute-selection-action-at-nth-+1) (63 . helm-help) (110 . #f(compiled-function () (interactive nil) #<bytecode 0x16c1429>)) (108 . helm-display-line-numbers-mode) (62 . helm-toggle-truncate-line) (21 . helm-refresh) (6 . helm-follow-mode) (9 . helm-copy-to-buffer) (11 . helm-kill-selection-and-quit) (25 . helm-yank-selection) (37 . helm-exchange-minibuffer-and-header-line) (95 . helm-toggle-full-frame) (45 . helm-swap-windows)) (67108987 . helm-enlarge-window) (67108989 . helm-narrow-window) (19 . undefined) (24 keymap (57 . helm-execute-selection-action-at-nth-+9) (56 . helm-execute-selection-action-at-nth-+8) (55 . helm-execute-selection-action-at-nth-+7) (54 . helm-execute-selection-action-at-nth-+6) (53 . helm-execute-selection-action-at-nth-+5) (52 . helm-execute-selection-action-at-nth-+4) (51 . helm-execute-selection-action-at-nth-+3) (50 . helm-execute-selection-action-at-nth-+2) (49 . helm-execute-selection-action-at-nth-+1) (2 . helm-resume-list-buffers-after-quit) (98 . helm-resume-previous-session-after-quit) (6 . helm-quit-and-find-file)) (11 . helm-delete-minibuffer-contents) (67108896 . helm-toggle-visible-mark-forward) (0 . helm-toggle-visible-mark) (C-M-up . helm-scroll-other-window-down) (C-M-down . helm-scroll-other-window) (M-prior . helm-scroll-other-window-down) (M-next . helm-scroll-other-window) (12 . helm-recenter-top-bottom-other-window) (left . helm-previous-source) (right . helm-next-source) (15 . helm-next-source) (10 . helm-execute-persistent-action) (9 . helm-select-action) (13 . helm-maybe-exit-minibuffer) (7 . helm-keyboard-quit) (22 . helm-next-page) (27 keymap (110 . next-history-element) (112 . previous-history-element) (115 . undefined) (5 . helm-display-all-sources) (1 . helm-show-all-candidates-in-source) (85 . helm-unmark-all) (97 . helm-mark-all) (109 . helm-toggle-all-marks) (41 . helm-next-visible-mark) (40 . helm-prev-visible-mark) (91) (32 . helm-toggle-visible-mark-backward) (33554454 . helm-scroll-other-window-down) (25 . helm-scroll-other-window-down) (22 . helm-scroll-other-window) (12 . helm-reposition-window-other-window) (111 . helm-previous-source) (62 . helm-end-of-buffer) (60 . helm-beginning-of-buffer) (118 . helm-previous-page)) (next . helm-next-page) (prior . helm-previous-page) (C-up . helm-follow-action-backward) (C-down . helm-follow-action-forward) (16 . helm-previous-line) (14 . helm-next-line) (up . helm-previous-line) ...) nil nil nil t)
  helm-read-pattern-maybe("Find files or url: " "/home/myuser/" nil nil nil nil nil)
  helm-internal(helm-source-find-files "/home/myuser/" "Find files or url: " nil nil "*helm find files*" nil nil nil)
  apply(helm-internal (helm-source-find-files "/home/myuser/" "Find files or url: " nil nil "*helm find files*" nil nil nil))
  helm(helm-source-find-files "/home/myuser/" "Find files or url: " nil nil "*helm find files*" nil nil nil)
  apply(helm (helm-source-find-files "/home/myuser/" "Find files or url: " nil nil "*helm find files*" nil nil nil))
  helm(:sources helm-source-find-files :input "/home/myuser/" :case-fold-search smart :preselect nil :ff-transformer-show-only-basename t :default nil :prompt "Find files or url: " :buffer "*helm find files*")
  helm-find-files-1("/home/myuser/" nil)
  helm-find-files(nil)
  funcall-interactively(helm-find-files nil)
  call-interactively(helm-find-files record nil)
  command-execute(helm-find-files record)
  execute-extended-command(nil "helm-find-files" "helm-find-files")
  funcall-interactively(execute-extended-command nil "helm-find-files" "helm-find-files")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

## Describe versions of Helm, Emacs, operating system, etc.

Helm Version: 20200823.1516
Emacs Version: 26.3
OS: Ubuntu 20.04.1 LTS

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):

Results in same error message.

## Are you using Spacemacs? (yes/no):

no

**Comment by thierryvolpiatto** [comment]
student-sx <notifications@github.com> writes:

> After upgrading helm helm-find-files doesn't work anymore on my home
> directory (see below). Is there any workaround until this is fixed?

helm-find-files is working properly, I can't reproduce any bug either
from my main Emacs (27) or from emacs-helm.sh.
The error is coming from the command kill-ring-save called with no
region active, see your backtrace.
So why kill-ring-save is called at the same time of helm-find-files?
Anyway it can't be in emacs-helm.sh.

> Error message: Helm issued errors: helm-match-from-candidates in source `Find Files': args-out-of-range (0 0) [2 times]
>
> Steps to reproduce (recipe)
>
> M-x helm-find-files on my home directory (other dirs' work)
>
> Backtraces if any (M-x toggle-debug-on-error)
>
> Debugger entered--Lisp error: (error "The mark is not set now, so there is no region")
> region-beginning()
> #f(compiled-function (method) #<bytecode 0x3ab945>)(nil)
> copy-region-as-kill(nil 29 1)
> kill-ring-save(nil 29 1)
> funcall-interactively(kill-ring-save nil 29 1)
> call-interactively(kill-ring-save nil nil)
> command-execute(kill-ring-save)

Why is this called? This is not coming from helm AFAIK.

> Describe versions of Helm, Emacs, operating system, etc.
>
> Helm Version: 20200823.1516
> Emacs Version: 26.3
> OS: Ubuntu 20.04.1 LTS
>
> Are you using emacs-helm.sh to reproduce this bug? (yes/no):
>
> Results in same error message.

Can't reproduce.

-- 
Thierry

**Comment by manuel-uberti** [comment]
I am not able to reproduce this, neither from my configuration nor from `emacs-helm.sh`.

Could you try cloning the Helm repository and using `emacs-helm.sh` from there?

**Comment by student-sx** [comment]
I cloned the helm repository and tried `emacs-helm.sh` from there. I get the same error message (but wasn't able to copy the backtrace; it appears on a window when the error occurs, but if I click on it, it disappears. If I then quit `helm-find-files` and switch to the `*Backtrace*` buffer, is is empty.

**Comment by student-sx** [comment]
It seems to occur the first time in commit 570a76a641c792c06e6cb40e3a39a4da8f7c9302, does this help to isolate the problem?

**Comment by manuel-uberti** [comment]
Could you try creating a new user with an empty home directory and starting `emacs-helm.sh` from there? Just to rule out the possibility that something in your current home directory is actually interfering.

**Comment by student-sx** [comment]
Hm, I tried it, but `make` did throw an error about a missing `async` package. Then I installed it via package manager and tried make again. Now it seemed to work, but after starting `emacs-helm.sh` it complains "Cannot open load file: No such file or directory, async".

**Comment by student-sx** [comment]
I cloned helm into another (already existing and heavily used) home/user. In this home directory (lets call it `/home/myuser2`) it didn't occur, but if I try (as `myuser2`) to find a file from `myuser` (I granded permissions for `myuser2` to see files from `myuser` before), the error occurs again. So there seems to be something special in `myuser`'s home directory which doesn't work well with `helm-find-files` since commit https://github.com/emacs-helm/helm/commit/5608bf57de38cb97e6518c7d6f282ccf36fc3214

**Comment by thierryvolpiatto** [comment]
student-sx <notifications@github.com> writes:

> I cloned helm into another (already existing and heavily used)
> home/user. In this home directory (lets call it /home/myuser2) it
> didn't occur, but if I try (as myuser2) to find a file from myuser (I
> granded permissions for myuser2 to see files from myuser before), the
> error occurs again. So there seems to be something special in myuser's
> home directory which doesn't work well with helm-find-files since
> commit 5608bf5

commit 5608bf5 have nothing to do with your problem.
Your error comes from something trying to kill a region, why? I don't
know, nothing is trying to do something like this in helm-find-files.
What are you doing exactly apart (after) M-x helm-find-files?


-- 
Thierry

**Comment by student-sx** [comment]
Problem solved: I have found a symlink in my home directory pointing to a non existing network drive. Removing the link solved the problem.

**Comment by manuel-uberti** [comment]
@student-sx can this be closed then?
