### ISSUE TITLE
Mode-line error when starting helm from a helm buffer

### ISSUE THREAD

**Issue by nunowallenstein** [emacs-helm/helm#2377]
I get this same bug when i try to change the buffer with Mouse 1 at the title of the buffer in the lower left part of the buffer. 
When i for example, find a file (C-x C-f) and change the buffer with the mouse 1, i end up in a buffer called \***helm find files**\* and i cannot switch to other buffers this way, after encountering this buffer. This also happens every time i encounter a \***helm buffer**\* this way,  preventing me from switching buffer using mouse 1. On the buffer \***Messages**\* these kind of error messages occur. How can i fix them?

```
Error during redisplay: (eval (with-helm-buffer (helm-show-candidate-number (car-safe helm-mode-line-string)))) signaled (error "No buffer named *helm*") [11 times]
helm-display-mode-line: Wrong type argument: stringp, ("File(s)" "\\<helm-map>\\[helm-help]:Help \\[helm-select-action]:Act \\[helm-maybe-exit-minibuffer]/f1/f2/f-n:NthAct \\[helm-toggle-suspend-update]:Tog.suspend \\[helm-customize-group]:Conf")Error during redisplay: (eval (with-helm-buffer (helm-show-candidate-number (car-safe helm-mode-line-string)))) signaled (error "No buffer named *helm*")
Error during redisplay: (eval (with-helm-buffer (helm-show-candidate-number (car-safe helm-mode-line-string)))) signaled (error "No buffer named *helm*") [9 times]
auto trimmed 0 chars
helm-display-mode-line: Wrong type argument: stringp, ("File(s)" "\\<helm-map>\\[helm-help]:Help \\[helm-select-action]:Act \\[helm-maybe-exit-minibuffer]/f1/f2/f-n:NthAct \\[helm-toggle-suspend-update]:Tog.suspend \\[helm-customize-group]:Conf") [2 times]
next-line: End of buffer
Quit
QuitError during redisplay: (eval (with-helm-buffer (helm-show-candidate-number (car-safe helm-mode-line-string)))) signaled (error "No buffer named *helm*")
Error during redisplay: (eval (with-helm-buffer (helm-show-candidate-number (car-safe helm-mode-line-string)))) signaled (error "No buffer named *helm*")

```
I have tried to fix the helm.el file like the commit mentioned but i noticed the fix was already in place.

_Originally posted by @nunowallenstein in https://github.com/emacs-helm/helm/issues/1517#issuecomment-685963914_

**Comment by thierryvolpiatto** [comment]
Should work now, thanks to report.

**Comment by nunowallenstein** [comment]
Thanks a lot! Just updated the package and it's now working properly! Keep on the good work!
