### ISSUE TITLE
Helm ignores the value of use-file-dialog overriding the dialogues unconditionally

### ISSUE THREAD

**Issue by yantar92** [emacs-helm/helm#2381]
## Expected behavior

When `use-file-dialog` is non-nil (by default), clicking "Open file..." from menu or toolbar is using system dialogue. 
This option is designed for new users unfamiliar with Emacs and this default is expected to be the same when helm is installed and helm-mode is activated.

I understand that replacing `read-file-name` is explained in `helm-mode` docstring. However, not honoring `use-file-dialog`   and `use-dialog-box` may be extremely confusing for new Emacs users trying to understand Emacs and use Helm.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

Opening file does not spawn OS' file-chooser dialogue, but raises helm interface instead.

## Steps to reproduce (recipe)

1. emacs -Q
2. Load helm
3. (helm-mode +1)
4. File->Open menu

## IMPORTANT NOTE

Helm provides a script named `emacs-helm.sh` which runs Helm in a neutral
environment: no other packages and only minimal settings.

When possible, use it to reproduce your Helm issue to ensure no other package is
interfering.

To run it, simply switch to the directory where Helm is installed and call `./emacs-helm.sh`.
If necessary you can specify emacs executable path on command line with "-P" option.

Thanks.

**Comment by manuel-uberti** [comment]
This is an interesting suggestion. I've never used the system file dialogs in Emacs, and do not intend to give up the power of `helm-find-files` for a mouse-driven UI, but it's true that newcomers may expect a dialog to open a file.

**Comment by yantar92** [comment]
I found this issue during ongoing discussion about making it easier for newcomers to use Emacs: https://lists.gnu.org/archive/html/emacs-devel/2020-09/msg00234.html

**Comment by yantar92** [comment]
> I've never used the system file dialogs in Emacs, and do not intend to give up the power of helm-find-files for a mouse-driven UI, but it's true that newcomers may expect a dialog to open a file.

Most of long-term users do not use mouse-driven UI (including me), as I know. That's why I suggest to not override Emacs attempts to be more [new] user-friendly, as it is done by helm now. 

By default, this `use-file-dialog` option does not affect `find-file` called via `C-x C-f` - only from menu or toolbar. I believe that similar behavior would be good to have in helm.

**Comment by thierryvolpiatto** [comment]
yantar92 <notifications@github.com> writes:

> Expected behavior
>
> When use-file-dialog is non-nil (by default), clicking "Open file..."
> from menu or toolbar is using system dialogue.

I made a PR fixing this, not fully tested, have a try.

Thanks.


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
In the same idea some months ago I also made mouse-3 opening helm menu but it seems nobody noticed it :-(

**Comment by yantar92** [comment]
> I made a PR fixing this, not fully tested, have a try.

Works for me (emacs master).

> In the same idea some months ago I also made mouse-3 opening helm menu but it seems nobody noticed it :-(

Probably, users interested in mouse navigatoin are simply not aware about github...

**Comment by thierryvolpiatto** [comment]
yantar92 <notifications@github.com> writes:

>     I made a PR fixing this, not fully tested, have a try.
>    
> Works for me (emacs master).

Thanks to confirm.  Merged.

>     In the same idea some months ago I also made mouse-3 opening helm menu but it seems nobody noticed it :-(
>    
> Probably, users interested in mouse navigatoin are simply not aware about github...

Probably yes.

> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.*


-- 
Thierry
