### ISSUE TITLE
 Symbol’s value as variable is void: \213

### ISSUE THREAD

**Issue by sjLambda** [emacs-helm/helm#2385]
## Expected behavior
helm interface with list of files, and no error msg in the mini buffer

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
C-x C-b does not open the helm interface with list of files but shows this error in mini buffer:

load-with-code-conversion: Symbol’s value as variable is void: \213

## Steps to reproduce (recipe)
C-x C-b
or
M-x helm-for-files

## Backtraces if any (`M-x toggle-debug-on-error`)
Does not catch this error, here's a transcript

ELISP> (toggle-debug-on-error)
nil
ELISP> (helm-for-files)
*** Eval error ***  Symbol’s value as variable is void: 
ELISP> (setq eval-expression-debug-on-error t)
t
ELISP> (helm-for-files)
*** Eval error ***  Symbol’s value as variable is void: \213
ELISP> 

I also deleted recentf files to exclude any malformed file names there.

## Describe versions of Helm, Emacs, operating system, etc.
Helm version: 3.6.2
Emacs version: 27.1 on mac os catalina
also tested with 
Emacs version: GNU Emacs 28.0.50 build from latest trunk

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):
No, this bug is not shown or displayed.

emacs-helm.sh does not catch or trap this error. See the ielm transcript above for an alternate. 

## Are you using Spacemacs? (yes/no):
no

## IMPORTANT NOTE

Helm provides a script named `emacs-helm.sh` which runs Helm in a neutral
environment: no other packages and only minimal settings.

When possible, use it to reproduce your Helm issue to ensure no other package is
interfering.

To run it, simply switch to the directory where Helm is installed and call `./emacs-helm.sh`.
If necessary you can specify emacs executable path on command line with "-P" option.

Thanks.

**Comment by thierryvolpiatto** [comment]
Lambda Coder <notifications@github.com> writes:

> Are you using emacs-helm.sh to reproduce this bug? (yes/no):
>
> No, this bug is not shown or displayed

That's the point.

-- 
Thierry

**Comment by sjLambda** [comment]
What's the point again? You don't know how to make helm work with the rest of the emacs eco system? Or you don't care?

**Comment by yantar92** [comment]
> What's the point again? You don't know how to make helm work with the rest of the emacs eco system? Or you don't care?

Most of time, it just means that we don't know how to make helm work with your config. If you find a specific part of your config causing helm to fail, feel free to post it. Otherwise, we will simply not be able to find the cause - there is nearly infinite number of package combinations. We cannot test all possibilities.

**Comment by michael-heerdegen** [comment]
yantar92 <notifications@github.com> writes:

> We cannot test all possibilities.

And a backtrace might help.

**Comment by thierryvolpiatto** [comment]
@sjLambda Please don't be aggressive, if you want help from here for your problem follow the rules.
If you can't reproduce the bug in a minimal environment it means it is not a Helm bug, that's all, is it difficult to understand?

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> @sjLambda Please don't be aggressive, if you want help from here for
> your problem follow the rules.  If you can't reproduce the bug in a
> minimal environment it means it is not a Helm bug, that's all, is it
> difficult to understand?

But Thierry, this really sounds subliminally aggressive to me as well.

**Comment by sjLambda** [comment]
> @sjLambda Please don't be aggressive, if you want help from here for your problem follow the rules.
> If you can't reproduce the bug in a minimal environment it means it is not a Helm bug, that's all, is it difficult to understand?

I think you were the one who's aggressive. I noticed this many times before. So let this be a warning.

As for the issue at hand, what you overlooked is that I tried to trigger a backtrace but to no avail. I did that after I ran the shell script, which did not trigger an error. In other words, this is a class of problem that is happening outside the confines of back-tracing or toggling debug on error. So my question was how to solve or look for the real culprit?

If you don't know the answer, staying silent is an option too. I wasn't expecting a smart-alec response, especially to someone like me who's helped you clean helm documentation files in the past. 

I'm not offended by your aggressiveness but your brushing off the problem itself.

**Comment by yantar92** [comment]
> So my question was how to solve or look for the real culprit?

It looks for me like the issue is with your config (otherwise, you would be able to reproduce on clean Emacs). The best we can suggest considering the lack of debug info is that you can bisect your config.

**Comment by sjLambda** [comment]
> bisect your config.

yes indeed since there's no way around it

**Comment by yantar92** [comment]
> yes indeed since there's no way around it

FYI: https://github.com/Malabarba/elisp-bug-hunter can automate
bisecting process.

**Comment by sjLambda** [comment]
Oh yes, thanks for reminding that Malabarba package.
