### ISSUE TITLE
C-g or C-] does not exit helm's C-h m

### ISSUE THREAD

**Issue by winny-** [emacs-helm/helm#2387]
Thank you for helm it's amazing!  I'm not sure if this is a bug, but it certainly is a usability issue.

## Expected behavior

Type `C-g` (`keyboard-quit`) or `C-]` (`abort-recursive-edit`) closes `helm-help` when it's opened as a modal window from the helm minibuffer.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

Nothing happens.  Not even the terminal/desktop bell rings/beeps when one types `C-g` with nothing left to quit and `C-]` with no recursive edits to abort.

Instead one has to type `q`, which is not a standard "emacs convention" like `keyboard-quit` or `abort-recursive-edit`.

## Steps to reproduce (recipe)

1. fire up emacs with helm
2. run `helm-M-x` (e.g. `M-x`)
3. type `C-h m`
4. try to back out of the "modal" buffers like one would back out of other modal buffers -- e.g. `C-g` or `C-]`.  Note no beeps.
5. Wait a moment, and realize the minibuffer is showing help information for this very special mode on how to quit it.

## Describe versions of Helm, Emacs, operating system, etc.
```
GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, X toolkit, Xaw3d scroll bars) of 2020-08-30
```

```
LSB Version:    n/a
Distributor ID: Gentoo
Description:    Gentoo Base System release 2.7
Release:        2.7
Codename:       n/a
```

```
helm-20200808.430
```

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):
**yes**

## Are you using Spacemacs? (yes/no):
**no**

## IMPORTANT NOTE

Helm provides a script named `emacs-helm.sh` which runs Helm in a neutral
environment: no other packages and only minimal settings.

When possible, use it to reproduce your Helm issue to ensure no other package is
interfering.

To run it, simply switch to the directory where Helm is installed and call `./emacs-helm.sh`.
If necessary you can specify emacs executable path on command line with "-P" option.

Thanks.

**Comment by thierryvolpiatto** [comment]
`C-g` was the way to exit help long time ago, since then, most users have asked for `q` and I have enabled `q` to exit help, I will not change now after all these years of using `q`.
Thanks.

**Comment by thierryvolpiatto** [comment]
See bug #808, also helm help bindings are now configurable through `helm-help-hkmap`.
