### ISSUE TITLE
Future of Helm and new maintainer?

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#2389]
Since @thierryvolpiatto seems to have retired from Helm development (thank you again for the tireless years of development <3), I suppose we need a plan for Helm and its future.

Should Helm be forked?  Should maintainance be handed over?
Is anyone feeling fit for the job? :)

Alternatively, Helm extensions could be added to https://github.com/emacs-helm (I have write access there).

Thoughts, anyone?

**Comment by alphapapa** [comment]
I don't know if he's retired.  I see quite a few recent commits by him: https://github.com/emacs-helm/helm/commits/master  Sometimes people just need a break from staring at code all the time.  I think that, if Thierry were ready to turn over Helm to someone else, he would say so.  Let's not be presumptuous.  :)

**Comment by Ambrevar** [comment]
Sure thing, well, since the discussion is happening here, Thierry will chime in if he feels the need to :)

**Comment by michael-heerdegen** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Sure thing, well, since the discussion is happening here, Thierry will
> chime in if he feels the need to :)

That would not really fit into what I would consider a break.  I would
want that people don't rely on me to chime in.

Michael.

**Comment by Ambrevar** [comment]
This discussion is public, and if Thierry is pushing commits on this repo
then he probably witnessed this issue as well.

**Comment by michael-heerdegen** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> This discussion is public, and if Thierry is pushing commits on this
> repo then he probably witnessed this issue as well.

Of course.

I only think that doesn't mean he wants to decide anything about this
now, and we shouldn't push him to.

Michael.

**Comment by Ambrevar** [comment]
Let's not then! :)

Let's simply get the discussion started for a couple of weeks, we'll see
where this leads us!

**Comment by alphapapa** [comment]
I trust Thierry.  He's faithfully developed and maintained this package for years, and I'm sure that if he wants to retire from it someday, he'll ensure a smooth transition to new stewardship at the proper time.  Having yet another, public, "What about Helm's future?" discussion doesn't help anything, and if I were him, I'd feel pressured by it, even if it's not the intention.  So I encourage you to just close this issue and let Helm and Thierry be.

**Comment by Ambrevar** [comment]
Sorry, I was not aware that this had been discussed before.  Do you have a link?

Given that Thierry had posted about his (possible?) retirement months ago (https://github.com/emacs-helm/helm/issues/2386) in which nothing was mentioned about Helm's future.
I felt that enough time had passed that we started a discussion.  No harm in discussing.

I believe it's a good thing to discuss openly, regardless of the time frame (again, no pressure! :p), so if anyone wants to chime in, feel free to bring up this discussion again, anytime from now :)
