### ISSUE TITLE
Helm behaviour for org-match-sparse-tree should be similar to helm-find-files

### ISSUE THREAD

**Issue by vr00m** [emacs-helm/helm#2395]
**Is your feature request related to a problem? Please describe.**

As illustrated in the image, helm's behaviour for `org-match-sparse-tree` needs to be more nuanced.

The input being asked here is not just tags, it is an argument having its own DSL , and multiple functionalities folded into one string. So, when the user types in input which does not match any of the tags simply, then the completion system should discard the tags suggestions completely, and use the input string as is.

I have the same issue with org-agenda-set-tags. For new tags, so many times I've mistakenly entered the wrong tags because helm 'helpfully' guessed that the new different tag/text that I entered manually, should actually be replaced by some pre-existing tag.

**Describe the solution you'd like**
One usually expects to just type the text one wants and hit enter. Here, helm interferes in the workflow by making you check and be sure that your text-input hasn't been auto-completed to a completely different thing.

**Describe alternatives you've  considered**
I've searched for some helm setting to change this behaviour, but unable to find it. There really should be a one point setting for this.

**Additional context**
[Some discussion here.](https://github.com/syl20bnr/spacemacs/issues/13624)
 #13624

![helm autocomplete](https://user-images.githubusercontent.com/306456/113446017-97f08d00-93ff-11eb-80e8-5ec2563a0b13.png)

**Comment by thierryvolpiatto** [comment]
Mohammed Sami ***@***.***> writes:

> I've searched for some helm setting to change this behaviour, but
> unable to find it. There really should be a one point setting for
> this.

Problem is that a global var to control this like HFF has would affect
all completing-read's, not only org-match-sparse-tree, this because it
is a generic helm function used by helm-mode and not a native helm
function which is used here (See "Helm functions vs helmized Emacs
functions" section in helm documentation).
I can add easily a new global var, but it will affect whole
completing-read's...

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
This is a generic completing-read, if one want to fix this he has to write a new handler for org-match-sparse-tree and use it with helm-completing-read-handler-alist.
Closing now.
