### ISSUE TITLE
helm-find-files cannot list directory members (culprit was located)

### ISSUE THREAD

**Issue by abgruszecki** [emacs-helm/helm#2400]
## Expected behavior

helm-find-files can list members of a directory.

## Actual behavior

I get an error: `Helm issued errors: helm-match-from-candidates in source `Find Files': args-out-of-range (0 0) [2 times]`

The error appears to be caused by file with a name that contains "file-error" as substring. I replicated it with `multi-file-error.check`, `multi-file-error`, and `file-error`, and with no smaller file name.

The error happens in `helm-match-from-candidates`, on the following line:
```
                          for prop-part = (get-text-property 0 'match-part target)
```

The problem is that `target` is `nil`. I debugged the problem and it appears that on the line above, `(helm-get-attr 'match-on-real source)` is `t`, but both `(cdr-safe c)` and `(get-text-property 0 'helm-realvalue disp)` are nil. The source is an instance of `helm-source-ffiles` (`helm-source-find-files`, I think).

A makeshift fix is to replace the `for target` with:
```
                          for target = (if (helm-get-attr 'match-on-real source)
                                           (or (cdr-safe c)
                                               (get-text-property 0 'helm-realvalue disp)
                                               disp)
                                         disp)
```

But I'm not sure if that's the best thing to do.

## Reproducing

Call `helm-find-files` in a directory that has a file named `file-error`. I couldn't run `./emacs-helm.sh`, but I ran an unconfigured Emacs, installed `helm` from MELPA, and I could reproduce the issue.

**Comment by thierryvolpiatto** [comment]
Thanks for reporting this. 

Could reproduce and find what happened, see commit 6cbb30e0 in devel
branch, will merge soon.

Aleksander Boruch-Gruszecki ***@***.***> writes:

> A makeshift fix is to replace the for target with:
>
>                           for target = (if (helm-get-attr 'match-on-real source)
>                                            (or (cdr-safe c)
>                                                (get-text-property 0 'helm-realvalue disp)
>                                                disp)

Thanks I added this change which doesn't harm and make code stronger,
but it is not enough to fix the bug which comes from the transformer
that matched on "file-error" to handle the file-error message maybe
printed in helm-buffer.

-- 
Thierry

**Comment by abgruszecki** [comment]
Great, thanks a lot for the quick turnaround!
