### ISSUE TITLE
Is there an intro to helm API?

### ISSUE THREAD

**Issue by AkselAllas** [emacs-helm/helm#2406]
Is there somewhere, where I can get more info on this?

![image](https://user-images.githubusercontent.com/26136082/115871232-f4682a80-a448-11eb-839f-332eaf3b7765.png)

**Comment by thierryvolpiatto** [comment]
Aksel Allas ***@***.***> writes:

> Is there somewhere, where I can get more info on this?

https://github.com/emacs-helm/helm/wiki/Developing

And now the org file is distributed with helm in doc/ directory.

You can as well use make info and make install-info to install manuals
in info format (still in development).

-- 
Thierry

**Comment by rnchzn** [comment]
Here are some links for the same question on https://stackoverflow.com/questions/20041498/where-to-find-emacs-helm-documentation

- As far as writing new extensions for helm I would recommend the 16 minute video that accompanies this: https://github.com/krisajenkins/helm-spotify

---

A very good tutorial was written by John Kitchin: http://wikemacs.org/wiki/How_to_write_helm_extensions

(first of the three original post blogs: http://kitchingroup.cheme.cmu.edu/blog/2015/01/24/Anatomy-of-a-helm-source/)

He introduces:

-     the simplest kind of helm interface with a fixed set of candidates
-     A simple dynamic set of candidates
-     A simple fixed set of candidates from a list of cons cells.
-     Candidates and one action
-     More than one action
-     Handling multiple selections
-     Actions when there is no match

**Comment by AkselAllas** [comment]
Thank you very much for the material! I learned a lot!
