### ISSUE TITLE
[Question] How to quit *Helm Help*?

### ISSUE THREAD

**Issue by sstepashka** [emacs-helm/helm#2413]
## Expected behavior
`C-g` or `ESC ESC ESC` exit the help. Seems like only "q" works, but it required me few tried to find it...

## Actual behavior (from `emacs-helm.sh` if possible, see note above)
`C-g` or `ESC ESC ESC`, `C-o`, `C-x C-c` do not work.

## Steps to reproduce (recipe)
`M-x C-h m`

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):
yes

**Comment by thierryvolpiatto** [comment]
Dmitry Kuragin ***@***.***> writes:

> Expected behavior
>
> C-g or ESC ESC ESC exit the help. Seems like only "q" works, but it
> required me few tried to find it...

It is notified in the prompt in minibuffer.
At first only C-g was working to exit help, then I have been asked to
disable C-g and enable "q", so I did and now we have "q" ;-).
Related to #2387 and #808.

-- 
Thierry
