### ISSUE TITLE
helm-ff-move-to-first-real-candidate is not effective on helm-mode

### ISSUE THREAD

**Issue by kkatsuyuki** [emacs-helm/helm#2415]
When I use helm-completion with helm-mode (ex. dired-do-copy on a dired-mode buffer with helm-mode on), an incomplete input is selected instead of first real candidate. Therefore, I have to move select to the first candidate. How do I change to select the candidate without moving cursol?

helm-mode.el
```
(cl-defun helm-read-file-name
      :
  (mapc (lambda (hook)
          (add-hook 'helm-after-update-hook hook))
        '(helm-ff-move-to-first-real-candidate
          helm-ff-update-when-only-one-matched
          helm-ff-auto-expand-to-home-or-root))
     :
```

`helm-read-file-name` uses `helm-ff-move-to-first-real-candidate`, but it seems that `helm-ff-move-to-first-real-candidate` is not working.

Can you help me to fix it? Thank you!

**Comment by thierryvolpiatto** [comment]
KKatsuyuki ***@***.***> writes:

> [[PGP Encrypted Part:OK]]
> When I use helm-completion with helm-mode (ex. dired-do-copy on a dired-mode buffer with helm-mode on), an incomplete input is selected instead of first real candidate. Therefore, I have
> to move select to the first candidate. How do I change to select the candidate without moving cursol?

Dired commands are not allowed to move to first real candidate see bug
#910, use `helm-ff-goto-first-real-dired-exceptions` to modify this for
your needs. Even better use helm-find-files insead of dired ;-)


-- 
Thierry

**Comment by kkatsuyuki** [comment]
Thank you! I can select first real candidate in dired-do-copy, dired-do-rename using `helm-ff-goto-first-real-dired-exceptions`.
