### ISSUE TITLE
Repeated error messages on inotify-less systems

### ISSUE THREAD

**Issue by akater** [emacs-helm/helm#2422]
Hopefully, this doesn't need an elaborate formulaic report.  I don't have inotify support, or any equivalent thereof, on some systems, and there, helm had become extremely noisy and distracting some 7 months ago.  I'm now using a patched version which alleviates this, the patch is trivial but I'm not sure it's a proper solution so I'm not making it a PR.  The patch is in the default branch in my fork: https://github.com/akater/helm/tree/silent-no-notify

**Comment by thierryvolpiatto** [comment]
akater ***@***.***> writes:

> Hopefully, this doesn't need an elaborate formulaic report. I don't
> have inotify support, or any equivalent thereof, on some systems,

What are those systems?  Nowaday most systems have a notify support.

> and there, helm had become extremely noisy and distracting some 7
> months ago.

Yes Helm is now taking advantage of file-notify.
What do you mean by noisy and distracting? The error messages from
file-notify-add-watch?

> I'm now using a patched version which alleviates this, the patch is
> trivial but I'm not sure it's a proper solution so I'm not making it a
> PR. The patch is in the default branch in my fork:
> https://github.com/akater/helm/tree/silent-no-notify

Thanks, unfortunately you will have to manually update your directories
(C-c C-u) with such patch.

-- 
Thierry

**Comment by akater** [comment]
> What are those systems? Nowaday most systems have a notify support.

My Emacs is compiled without inotify support.  I just never ensured inotify is supported in my kernel build, and I generally have configuration flags disabled by default.  Regardless, as long as Emacs offers the “no notifications” configuration option, it should be taken into account.

> What do you mean by noisy and distracting? The error messages from
> file-notify-add-watch?

Yes.

Anyway, with the new defcustom, everything is fine.  Thank you.
