### ISSUE TITLE
helm completing-read emulation aborts when using unmatched value with `require-match` nil

### ISSUE THREAD

**Issue by wwade** [emacs-helm/helm#2423]
With reference to #1782, the fix appears to be in place, but I'm still seeing the problem as described below.

## Expected behavior
For this `completing-read`:
```(completing-read "prompt: " '("foo" "bar" "baz"))```

If I enter something outside the list, e.g. `*`, I would expect it to be returned from `completing-read`. With helm disabled, this is the case.

## Actual behavior (from `emacs-helm.sh` if possible, see note above)
In `emacs-helm.sh`, it seems to abort / exit somewhere without returning any value. If I enter `* M-RET` it returns nil.

## Steps to reproduce (recipe)

In `emacs-helm.sh` scratch buffer:

```elisp
(progn
  (helm-mode -1)
  (message "helm-mode %s debug-on-error %s" helm-mode debug-on-error)
  (message "out: %s" (completing-read "prompt: " '("foo" "bar" "baz"))))

(progn
  (helm-mode 1)
  (message "helm-mode %s debug-on-error %s" helm-mode debug-on-error)
  (message "out: %s" (completing-read "prompt: " '("foo" "bar" "baz"))))

(message "finished")
```

1. `eval-buffer`
2. (setq debug-on-error t)
2. `* RET * RET` -- from `view-lossage`:
```
 * [self-insert-command]
 <return> [exit-minibuffer]
 * [self-insert-command]
 <return> [helm-maybe-exit-minibuffer]
```

Output in `*Messages*`:
```
helm-mode nil debug-on-error t
out: *
helm-mode t debug-on-error t
```

Note that at this point, we see neither the `out: ` after the helm `completing-read`, nor the final `"finished"`.

## Backtraces if any (`M-x toggle-debug-on-error`)
None

## Describe versions of Helm, Emacs, operating system, etc.
- Helm:   20210525.659
- OS: Ubuntu 20.04.2 LTS
- Emacs: GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.14) of 2020-03-26, modified by Debian

Helm version detail:
```
helm is an installed package.

     Status: Installed in ‘helm-20210525.659/’ (unsigned). Delete
    Version: 20210525.659
     Commit: 3fa68fb13a031a45f21556c99c58eb51f32aec8b
    Summary: Helm is an Emacs incremental and narrowing framework
   Requires: emacs-25.1, async-1.9.4, popup-0.5.3, helm-core-3.7.1
   Homepage: https://github.com/emacs-helm/helm
```
```
helm-core is a dependency package.

     Status: Installed in ‘helm-core-20210522.1148/’ (unsigned).
    Version: 20210522.1148
     Commit: 3fa68fb13a031a45f21556c99c58eb51f32aec8b
    Summary: Development files for Helm
   Requires: emacs-25.1, async-1.9.4
Required by: helm-20210525.659
```

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):
Yes

**Comment by thierryvolpiatto** [comment]
wwade ***@***.***> writes:

> With reference to #1782, the fix appears to be in place, but I'm still seeing the problem as described below.
>
> Expected behavior
>
> For this completing-read:
> (completing-read "prompt: " '("foo" "bar" "baz"))
>
> If I enter something outside the list, e.g. *,

This is specific to "*" and maybe others like "?" see Bug#1802, I
reverted this to allow "*" as #1802 should be fixed elsewhere both in
emacs and helm.

> I would expect it to be returned from completing-read.

Should work now.

Thanks.

-- 
Thierry

**Comment by wwade** [comment]
Ah, great, thanks for the help!

**Comment by wwade** [comment]
I confirmed that commit a49591b5a56e22c86476b798f7b63ba8527f498a does fix the issue.
