### ISSUE TITLE
multiline candidates truncated when helm-completion-style set to 'helm

### ISSUE THREAD

**Issue by progfolio** [emacs-helm/helm#2428]
Hi, Thierry.
I've run into this problem once before, and I'm not sure if it's by design or a bug:

## Expected behavior
`completing-read` shows multiline candidates when helm is enabled.

## Actual behavior (from `emacs-helm.sh` if possible, see note above)
Candidate strings are truncated at the new line.

## Steps to reproduce (recipe)

Git bisect points to 052afb3e1bb8fb7cd76fac9aaef232af9a84ba86:

> helm-completion-style now default to 'helm

Setting `helm-completion-style` to `emacs` fixes the issue, but I was unsure if this was a limitation similar to dropping text-properties mentioned in #2378.
I was able to reproduce the issue with the following in a clean Emacs environment (no init.el) with only helm installed and activated:

```emacs-lisp
    (let ((candidates (mapcar (lambda (s) (concat (propertize s 'face 'bold) "\n" s))
                              '("one" "two" "three"))))
      (customize-set-variable 'helm-completion-style (nth 0 '(helm emacs)))
      (completing-read "test: " candidates))
```

Switching `helm-completion-style` should demonstrate the two different behaviors.

Apologies  if this runs afoul of #2256, but is the truncation of a candidate after a newline expected?
If so, I'd be willing to submit a pull to the documentation of the variable to clarify that (and the text property limitation).

## Describe versions of Helm, Emacs, operating system, etc.

-   `Emacs version`: GNU Emacs 28.0.50 (build 1, x86<sub>64</sub>-pc-linux-gnu, X toolkit, cairo version 1.17.4, Xaw3d scroll bars) of 2021-06-29
-   `Helm version`: v3.8.0 (master eaf5b01f9c0c70dca2f665b1da1b7a461dc1d112)
-   `OS`: `Linux arch 5.12.13-arch1-2 #1 SMP PREEMPT Fri, 25 Jun 2021 22:56:51 +0000 x86<sub>64</sub> GNU/Linux`

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):

No, I used `straight-bug-report` which installs/activates helm in a clean environment.

**Comment by thierryvolpiatto** [comment]
Hi Nicholas.

Nicholas Vollmer ***@***.***> writes:

> Hi, Thierry.
> I've run into this problem once before, and I'm not sure if it's by design or a bug:

By design.
When helm-completion-style is set to helm (or helm-fuzzy), helm-mode is
using for completing-read a default handler which is using
helm-source-in-buffer, because of this candidates are split to newline
when inserted in the matching buffer.
This is a limitation of candidates-in-buffer implementation. Try this
two below:

    (let ((candidates (mapcar (lambda (s) (concat (propertize s 'face 'bold) "\n" s))
                                  '("one" "two" "three"))))
      (helm-comp-read "test: " candidates :candidates-in-buffer t))
      
    (let ((candidates (mapcar (lambda (s) (concat (propertize s 'face 'bold) "\n" s))
                                  '("one" "two" "three"))))
      (helm-comp-read "test: " candidates))

Helm-mode use this by default for completing-read because it is much
faster.
However, if you really need your candidates with a newline in a specific
command, you can pass this command to
helm-completing-read-handlers-alist and use
helm-completing-read-sync-default-handler as handler for this command.

    (defun helm-mode/test-sync-handler ()
      (interactive)
      (let ((candidates (mapcar (lambda (s) (concat (propertize s 'face 'bold) "\n" s))
                                '("one" "two" "three"))))
        (completing-read "test: " candidates)))
      
    (add-to-list 'helm-completing-read-handlers-alist '(helm-mode/test-sync-handler . helm-completing-read-sync-default-handler))


> No, I used straight-bug-report which installs/activates helm in a clean environment.

Interesting, I didn't know this feature.


-- 
Thierry

**Comment by progfolio** [comment]
Thanks for the clarification! That makes perfect sense now.
