### ISSUE TITLE
Visible Mark Prefix shifts candidates on selection

### ISSUE THREAD

**Issue by akater** [emacs-helm/helm#2430]
Marks on margins shift the whole list of candidates (at least in console Emacs), when they appear. This is quite distracting. Keeps happening even if I set `helm-visible-mark-prefix` to `""`.

## Reproducing with `emacs-helm.sh`
`(setq helm-visible-mark-prefix "")`
`C-x C-f`
`C-SPC`

## Expected behavior
Filenames stay in place when selected

## Actual behavior
Filenames are shifted one char to the right

## Describe versions of Helm, Emacs, operating system, etc.
Emacs 27.2, Helm master `93a8963c4ee84a0d58da93bb61a20b9dff1eaa1e`, Gentoo

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):
Yes

**Comment by thierryvolpiatto** [comment]
akater ***@***.***> writes:

> Marks on margins shift the whole list of candidates (at least in
> console Emacs), when they appear. This is quite distracting. Keeps
> happening even if I set helm-visible-mark-prefix to "".

Should work now, have a try.

-- 
Thierry

**Comment by akater** [comment]
It does, thank you!
