### ISSUE TITLE
helm depends on while-no-input-ignore-events which is no available in emacs 25.2.2

### ISSUE THREAD

**Issue by vapniks** [emacs-helm/helm#2433]
`while-no-input-ignore-events` is used in `helm--maybe-load-tramp-preview` and `helm--maybe-use-while-no-input`, but is not available in emacs 25.2.2
This means `helm-minibuffer-history` throws an error.

**Comment by thierryvolpiatto** [comment]
vapniks ***@***.***> writes:

> while-no-input-ignore-events is used in helm--maybe-load-tramp-preview
> and helm--maybe-use-while-no-input, but is not available in emacs
> 25.2.2 This means helm-minibuffer-history throws an error.

I don't understand why you have an error, while-no-input-ignore-events
is let bounded, if it is not defined, it should work just like any (non
global) var not defined with defvar, that is it should do nothing apart
a warning at compile time. 
Also why do you have only an error in helm-minibuffer-history?
Could you provide a backtrace?
Also what is Emacs version 25.2.2 ?

Thanks.

NB Please follow report bug template when filling bugs.

-- 
Thierry

**Comment by vapniks** [comment]
Look at line 2809 & 4687 in [helm.el](https://github.com/emacs-helm/helm/blob/60db46905443c87f324440202bd0735d57c5c201/helm.el), the let binding is just a cons of the old value with `dbus-event`:
```
  (let ((while-no-input-ignore-events
         (cons 'dbus-event while-no-input-ignore-events)))
``` 
So if it's not already defined you'll get an error. 
I don't think a backtrace is necessary (and it's rather long), it's pretty obvious what the problem is, and can easily be fixed using `boundp` to test if its already defined.

When I do `M-x emacs-version` I get: 
```
GNU Emacs 25.2.2 (x86_64-pc-linux-gnu, GTK+ Version 3.22.21) of 2017-09-22, modified by Debian
```

**Comment by thierryvolpiatto** [comment]
vapniks ***@***.***> writes:

> Look at line 2809 & 4687 in helm.el, the let binding is just a cons of the old value with dbus-event:
>
>   (let ((while-no-input-ignore-events
>          (cons 'dbus-event while-no-input-ignore-events)))

Ah yes there is a cons, so yes we need a test when consing, will fix
soon.

Thanks.

-- 
Thierry
