### ISSUE TITLE
Specify an action to be applied for all visible candidates

### ISSUE THREAD

**Issue by milochadam** [emacs-helm/helm#2434]
I would like to have an action specified like this:
```elisp
(defun custom/helm-search-action (candidate)
    (helm-mark-all)
    (helm-do-ag (projectile-project-root) (helm-marked-candidates)))
```
`(helm-mark-all)` is not possible to use in this context though. 

How can I achieve given that I want to avoid pressing `M-a` simply because I always want to work on all visible candidates (I would prior filter out some of the candidates when working with helm-projectile)?

**Comment by thierryvolpiatto** [comment]
This is not possible, mark all your candidates after narrowing and then run your action on this set of candidates.

**Comment by milochadam** [comment]
I found a workaround by binding this function to a key instead of using helm actions:
```elisp
(defun chom/helm-search-in-selected-files ()
    (interactive)
    (helm-mark-all)
    (with-helm-alive-p
      (helm-run-after-exit (lambda ()
                             (helm-do-ag (projectile-project-root) (helm-marked-candidates))))))
```
