### ISSUE TITLE
Completion of relative Tramp filenames does not work in HFF

### ISSUE THREAD

**Issue by d125q** [emacs-helm/helm#2435]
## Expected behavior

I want to be able to complete relative Tramp filenames in HFF.
For example, typing
```
/sudo:localhost:.bash_history
```
should give me the `.bash_history` file in the home directory of `root` (assuming the file exists, of course; it usually does).

## Actual behavior (from `emacs-helm.sh` if possible, see note above)

```
/sudo:localhost:.bash_history
```

does not give any results.

```
/sudo:localhost:~/.bash_history
```

gives the `.bash_history` file as expected.

Neither `find-file` nor `ido-find-file` exhibit this behavior.
The Tramp method is irrelevant, all of them seem to be having the issue.

## Steps to reproduce (recipe)

1. Open HFF
2. Type `/sudo:localhost:` and, if prompted, enter your password
3. Helm will show a list of files in the home directory of `root`; in my case, I see `.bash_history` among others
4. Keep typing and end up with `/sudo:localhost:.bash_history` — Helm does not show any results even though `.bash_history` should be there!

On the other hand, typing `/sudo:localhost:~/.bash_history` makes everything work as expected.

## Describe versions of Helm, Emacs, operating system, etc.

- `helm` is `20210714.1600`, `helm-core` is `20210716.1933`
- Emacs is `GNU Emacs 28.0.50 (build 1, x86_64-apple-darwin20.5.0, NS appkit-2022.50 Version 11.4 (Build 20F71)) of 2021-07-21` built from commit `bb2d1252e6da6202ebf7015ad9615b31fe993fdc` with native compilation
- OS is macOS Big Sur Version 11.4

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):

✅

**Comment by thierryvolpiatto** [comment]
Dario Gjorgjevski ***@***.***> writes:

> [[PGP Encrypted Part:OK]]
> Expected behavior
>
> I want to be able to complete relative Tramp filenames in HFF.
> For example, typing
>
> /sudo:localhost:.bash_history
>
> should give me the .bash_history file in the home directory of root (assuming the file exists, of course; it usually does).
>
> Actual behavior (from emacs-helm.sh if possible, see note above)
>
> /sudo:localhost:.bash_history
>
> does not give any results.

This happen at first connection, then this should not happen.
Please hit C-j after "/sudo:localhost:", this will expand to
"/sudo:localhost:/" and you will be able to type whatever you want after
this, on next calls C-j will expand to "~/" ("/root").
  
> /sudo:localhost:~/.bash_history
>
> gives the .bash_history file as expected.
>
> Neither find-file nor ido-find-file exhibit this behavior.

HFF is not Ido nor find-file, don't expect any changes to this behavior.

Thanks.

-- 
Thierry

**Comment by d125q** [comment]
Thank you; glad to know it's intended behavior.
