### ISSUE TITLE
Cursor type changes when using helm completion

### ISSUE THREAD

**Issue by mihem** [emacs-helm/helm#2436]
![helm_cursor_2](https://user-images.githubusercontent.com/46907494/128150161-197e03f4-8e4e-4c3f-bd1f-a2040aa08316.gif)

## Expected behavior
cursor-type remains vertical bar when performing completion with helm
The box cannot be changed back to a vertical bar. Only reverting the buffer revert the cursor-type to vertical

## Actual behavior (from `emacs-helm.sh`)
cursor-type changes to box when helm does autocompletion
this only occurs when the completion is unique (see gif)

## Steps to reproduce (recipe)
in terminal ./emacs-helm.sh
change cursor type to vertical bar (M-x describe-variable  cursor-type)
M-x emacs-lisp-mode
type "confirm-kill-em" M-x completion-at-point

## Backtraces if any (`M-x toggle-debug-on-error`)
none

## Describe versions of Helm, Emacs, operating system, etc.
arch linux 5.13.7
emacs 27.2-1
helm-20210729.1510

## Are you using `emacs-helm.sh` to reproduce this bug?
yes
this bug does not occur when disabling helm

This is just a really minor bug but somewhat annoying.
@thierryvolpiatto btw: Thanks for this best emacs package ever created :)

**Comment by thierryvolpiatto** [comment]
mihem ***@***.***> writes:

> cursor-type remains vertical bar when performing completion with helm

Should work now, thanks.

-- 
Thierry

**Comment by mihem** [comment]
Thanks for the super fast answer, works as expected now.
