### ISSUE TITLE
helm--ansi-color-apply has issue on master version of emacs. 

### ISSUE THREAD

**Issue by ccqpein** [emacs-helm/helm#2448]
### What happened?

Error message: `helm--ansi-color-apply: Symbol's function definition is void: ansi-color--find-face`

I guess it from [here](https://github.com/emacs-helm/helm/blob/b2bd8a2a938030c70e7da84bd49cadcc095ec2b9/helm-lib.el#L28).

Because this function is renamed. Check [this commit](https://github.com/emacs-mirror/emacs/commit/21dcb9830a46a6ed2c613e496b91f611ba7f6a27#diff-8af82071a7b4b41bb9cba2b44f38b4fa0bca8508924910b328e25dba5a213c3b) out

Btw, I compile my emacs by myself. So it is the 29 version on the master branch.

### How to reproduce?

I just run `helm-do-grep-ag` when my cursor on the word I want to search.

### Helm Version

Master branch

### Emacs Version

Emacs-28.0.50

### OS

MacOSX

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by thierryvolpiatto** [comment]
ccQpein ***@***.***> writes:

> What happened?
>
> Error message: helm--ansi-color-apply: Symbol's function definition is void: ansi-color--find-face
>
> I guess it from here.
>
> Because this function is renamed. Check this commit out

Thanks to report this, assuming nowaday `ansi-color-apply` is working
properly lets use it and advice it with `helm--ansi-color-apply` only
for emacs < 26.

-- 
Thierry
