### ISSUE TITLE
helm-run-external-command not working in latest version

### ISSUE THREAD

**Issue by xl666** [emacs-helm/helm#2449]
### What happened?

In latest version 20211017.752 on Melpa the functions: helm-run-external-command and helm-run-or-raise stop working, giving the following message:
if: Wrong type argument: stringp, nil

Previous version do not have this problem.

### How to reproduce?

Interactively call helm-run-external-command selecting a command to run

### Helm Version

Last from Melpa

### Emacs Version

Emacs-28.0.50

### OS

GNU/Linux

### Relevant backtrace (if possible)

```text
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  expand-file-name(nil)
  (if (eq system-type 'windows-nt) (helm-w32-prepare-filename file) (expand-file-name file))
  (shell-quote-argument (if (eq system-type 'windows-nt) (helm-w32-prepare-filename file) (expand-file-name file)))
  (let* ((real-com (replace-regexp-in-string "(" "" (car (split-string exe)))) (proc-name (if file (concat real-com " " file) real-com)) (file-arg (shell-quote-argument (if (eq system-type 'windows-nt) (helm-w32-prepare-filename file) (expand-file-name file)))) process-connection-type proc) (if (get-process proc-name) (if helm-raise-command (shell-command (format helm-raise-command real-com)) (error "Error: %s is already running" real-com)) (if (member real-com helm-external-commands-list) (progn (message "Starting %s..." real-com) (if file (cond ((string-match "%s &)\\'" exe) (call-process-shell-command ...)) (t (setq proc ...))) (setq proc (start-process-shell-command proc-name nil exe))) (if proc (progn (set-process-sentinel proc #'...))))) (setq helm-external-commands-list (cons real-com (delete real-com helm-external-commands-list)))))
  helm-run-or-raise("dolphin")
  helm-run-external-command("dolphin")
  funcall-interactively(helm-run-external-command "dolphin")
  command-execute(helm-run-external-command)
```

### Minimal configuration

- [x] I agree using a minimal configuration

**Comment by thierryvolpiatto** [comment]
xl666 ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
> What happened?
>
> In latest version 20211017.752 on Melpa the functions: helm-run-external-command and helm-run-or-raise stop working, giving the following message:
> if: Wrong type argument: stringp, nil

Should be fixed by edd28b87.

Thanks.

-- 
Thierry
