### ISSUE TITLE
Some warning when do native compile on emacs 28.0.60. 

### ISSUE THREAD

**Issue by zw963** [emacs-helm/helm#2452]
### What happened?

Some warn when do native compile on emacs 28.0.60

Warning (comp): helm-buffers.el:295:48: Warning: ‘helm-attr’ is an obsolete function (as of 3.7.0); use ‘helm-get-attr’ instead.

Warning (comp): helm.el:6887:47: Warning: ‘special-display-buffer-names’ is an obsolete variable (as of 24.3); use ‘display-buffer-alist’ instead.

Warning (comp): helm.el:6887:23: Warning: ‘special-display-regexps’ is an obsolete variable (as of 24.3); use ‘display-buffer-alist’ instead.

Warning (comp): helm-sys.el:158:14: Warning: ‘focus-in-hook’ is an obsolete variable (as of 27.1); after-focus-change-function

Warning (comp): helm-sys.el:184:30: Warning: ‘focus-in-hook’ is an obsolete variable (as of 27.1); after-focus-change-function

Warning (comp): helm-net.el:274:7: Warning: ‘browse-url-gnome-moz-program’ is an obsolete variable (as of 25.1).

Warning (comp): helm-net.el:276:7: Warning: ‘browse-url-galeon-program’ is an obsolete variable (as of 25.1).

Warning (comp): helm-net.el:277:7: Warning: ‘browse-url-netscape-program’ is an obsolete variable (as of 25.1).

Warning (comp): helm-files.el:4225:45: Warning: ‘mm-default-file-encoding’ is an obsolete function (as of future); use ‘mm-default-file-type’ instead.

Warning (comp): helm-eshell.el:144:37: Warning: ‘pcomplete-suffix-list’ is an obsolete variable (as of 24.1).

Warning (comp): helm.el:6886:23: Warning: ‘display-buffer-function’ is an obsolete variable (as of 24.3); use ‘display-buffer-alist’ instead.

Warning (comp): helm-utils.el:90:1: Warning: custom-declare-variable `helm-buffers-to-resize-on-pa' docstring wider than 80 characters

Warning (comp): helm-utils.el:105:1: Warning: custom-declare-variable `helm-html-decode-entities-function' docstring wider than 80 characters

Warning (comp): helm-tags.el:124:8: Warning: docstring wider than 80 characters

Warning (comp): helm-sys.el:63:1: Warning: custom-declare-variable `helm-top-sort-columns-alist' docstring wider than 80 characters

Warning (comp): helm-ring.el:497:8: Warning: docstring wider than 80 characters

Warning (comp): helm-occur.el:127:1: Warning: custom-declare-variable `helm-occur-keep-closest-position' docstring wider than 80 characters

Warning (comp): helm-mode.el:262:1: Warning: custom-declare-variable `helm-completion-style' docstring wider than 80 characters

Warning (comp): helm-mode.el:551:11: Warning: docstring wider than 80 characters

Warning (comp): helm-mode.el:1244:11: Warning: docstring wider than 80 characters

Warning (comp): helm-lib.el:1087:8: Warning: docstring wider than 80 characters

Warning (comp): helm-lib.el:1268:8: Warning: docstring wider than 80 characters

Warning (comp): helm-lib.el:1680:8: Warning: docstring wider than 80 characters

Warning (comp): helm-imenu.el:346:8: Warning: docstring wider than 80 characters

Warning (comp): helm-grep.el:49:1: Warning: custom-declare-variable `helm-grep-default-command' docstring wider than 80 characters

Warning (comp): helm-adaptive.el:66:1: Warning: defvar `helm-adaptive-history' docstring wider than 80 characters

### How to reproduce?

(normal-top-level-add-subdirs-to-load-path)

;; 下面的脚本用来生成 eln 的
(native-compile-async "~/Dropbox/common/.emacs.d/plugins" 'recursively)
(while (or comp-files-queue
           (> (comp-async-runnings) 0))
  (sleep-for 1))

### Helm Version

Master branch

### Emacs Version

Emacs-28.0.50

### OS

GNU/Linux

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by thierryvolpiatto** [comment]
Most warnings have been fixed, other are not important. Thanks.
