### ISSUE TITLE
`(require 'helm-adaptive)` missing from helm-files.el ?

### ISSUE THREAD

**Issue by mandarm** [emacs-helm/helm#2455]
### What happened?

I run `helm-find-files`, select some files, choose to run eshell-command on the selected files, reply with y to the first question, and then get the error on the second line.

    No eshell aliases found, run eshell-command without alias anyway? (y or n) y
    apply: Symbol’s function definition is void: helm-adaptive-sort

Line 1512 of `helm-files.el` references `helm-adaptive-sort`, but there is no `(require 'helm-adaptive)` at the beginning of the file.

I added the `require` to my `eval-after-load "helm-mode"`, and the problem went away.

### How to reproduce?

Works with emacs -Q as above + `(package-initialize)` so that I have access to helm. Also works with emacs-helm.sh.

### Helm Version

Last from Melpa

### Emacs Version

Emacs-27.1

### OS

GNU/Linux

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by thierryvolpiatto** [comment]
Mandar Mitra ***@***.***> writes:

> What happened?
>
> I run helm-find-files, select some files, choose to run eshell-command
> on the selected files, reply with y to the first question, and then
> get the error on the second line.
>
> No eshell aliases found, run eshell-command without alias anyway? (y or n) y
> apply: Symbol’s function definition is void: helm-adaptive-sort

Should be fixed now, thanks!

-- 
Thierry
