### ISSUE TITLE
Helm partially activates itself without user input

### ISSUE THREAD

**Issue by kbauer** [emacs-helm/helm#2457]
### What happened?

Something installed `helm` as a dependency. Afterwards, I suddenly had the helm-version of history search, without wanting it, and without enabling it.

### How to reproduce?

1. Run `emacs -Q`
2. Install `helm` to a temporary package directory

       M-x load-library RET package RET
       M-: (setq package-user-dir (make-temp-name "/tmp/package.helm.test.")) RET
       M-: (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/")) RET
       M-x list-packages RET
       M-x package-install RET helm RET

3. Test `find-file`'s history search

       M-: (setq file-name-history (list "~/.emacs" "~/../you/.emacs" "/work/.emacs")) RET
       C-x C-f C-r .emacs

Best practice suggests that just loading a package should not change the behavior of Emacs. However, after helm is installed, `helm-global-bindings.el` installs its `C-r` hotkey into all minibuffer keymaps.

When helm is installed unexpectedly as a dependency, this is confusing.

### Helm Version

Last from Melpa

### Emacs Version

Emacs-27.2

### OS

GNU/Linux

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by progfolio** [comment]
I was unable to reproduce this with just helm installed in a clean environment.

> Something installed helm as a dependency

What installed helm as a dependency? Is it possible that the package relying on helm has set things up as you describe?

**Comment by kbauer** [comment]
I just rechecked on a different system (Windows 10, using Emacs 27.1) and get the same result, running the procedure as described above. Note that I am setting up a completely clean environment before installing helm (currently result in version `20211108.1546`).

Insofar, no, it can't be the package that installed helm originally. While I don't know which it was, the difference should not affect the clean environment.

**Comment by thierryvolpiatto** [comment]
Until now nobody complained about this (probably because most users know what packages they install).  What I could do is bind this to nil, but most helm users will then complain about it, so I suggest you bind this to nil:

```elisp
(customize-set-variable 'helm-minibuffer-history-key nil)
```
Thanks.

**Comment by kbauer** [comment]
Just for reference: Helm seems to have been installed as a dependency of `org-ref`.

As long as a package manager is involved, most users will *not* know, exactly what packages are installed as dependency. It is just an unusual case, that helm has been affected in this case.

**Comment by progfolio** [comment]
> As long as a package manager is involved, most users will not know, exactly what packages are installed as dependency

Straight.el has commands to list dependencies. Not sure if there is anything equivalent for package.el
