### ISSUE TITLE
helm-mark-ring-default-action may delete from wrong mark ring (fix attached)

### ISSUE THREAD

**Issue by jocap** [emacs-helm/helm#2460]
### What happened?

Looking at the source code of `helm-mark-ring-default-action`, I see that it tries to delete buffer-less marks in `mark-ring`. The problem is that the same function is used for `helm-global-mark-ring`.

I have not encountered this bug in practice, but it seems clear to me that it is a bug, unless buffer-less marks can only appear in `mark-ring' and not in `global-mark-ring` for some reason of which I'm not yet aware.

I've included my fix below.

```
diff -u --label /home/john/.emacs.d/elpa/helm-20211013.727/helm-ring.el --label \#\<buffer\ helm-ring.el\> /home/john/.emacs.d/elpa/helm-20211013.727/helm-ring.el /tmp/buffer-content-XIjIzs
--- /home/john/.emacs.d/elpa/helm-20211013.727/helm-ring.el
+++ #<buffer helm-ring.el>
@@ -312,6 +312,22 @@
       (setq mark-ring (delete target mark-ring))
       (error "Marker points to no buffer"))))
 
+(defun helm-global-mark-ring-default-action (candidate)
+  (let ((target (copy-marker candidate)))
+    (helm-aif (marker-buffer candidate)
+        (progn
+          (switch-to-buffer it)
+          (helm-log-run-hook 'helm-goto-line-before-hook)
+          (helm-match-line-cleanup)
+          (with-helm-current-buffer
+            (unless helm-yank-point (setq helm-yank-point (point))))
+          (helm-goto-char target)
+          (helm-highlight-current-line))
+      ;; marker points to no buffer, no need to dereference it, just
+      ;; delete it.
+      (setq global-mark-ring (delete target global-mark-ring))
+      (error "Marker points to no buffer"))))
+
 (defvar helm-source-mark-ring
   (helm-build-sync-source "mark-ring"
     :candidates #'helm-mark-ring-get-candidates
@@ -323,7 +339,7 @@
 (defvar helm-source-global-mark-ring
   (helm-build-sync-source "global-mark-ring"
     :candidates #'helm-global-mark-ring-get-candidates
-    :action '(("Goto line" . helm-mark-ring-default-action))
+    :action '(("Goto line" . helm-global-mark-ring-default-action))
     :persistent-help "Show this line"
     :group 'helm-ring))
 

Diff finished.  Tue Nov 23 16:40:31 2021
```

### How to reproduce?

-

### Helm Version

Last from Melpa

### Emacs Version

Emacs-27.1

### OS

Other

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by thierryvolpiatto** [comment]
John ***@***.***> writes:

> What happened?
>
> Looking at the source code of helm-mark-ring-default-action, I see
> that it tries to delete buffer-less marks in mark-ring. The problem is
> that the same function is used for helm-global-mark-ring.
>
> I have not encountered this bug in practice, but it seems clear to me
> that it is a bug, unless buffer-less marks can only appear in
> mark-ring' and not in global-mark-ring` for some reason of which I'm
> not yet aware.

Yes, looking at `helm-global-mark-ring-get-candidates` code, they can't
appear in global-mark-ring source as marker-buffer is checked:

    [...]
    (cl-loop for marker in marks
             for mb = (marker-buffer marker)
             for gm = (unless (or (string-match "^ " (format "%s" mb))
                                  (null mb)) <<<<<<<<< it is checked here.
                        (helm-global-mark-ring-format-buffer marker))
             when (and gm (not (assoc gm recip)))
             collect (cons gm marker) into recip
    [...]

So we should not have problem with this unless I missed something.
But thanks for looking at this ;-).

-- 
Thierry

**Comment by jocap** [comment]
Thierry Volpiatto wrote:
> Yes, looking at `helm-global-mark-ring-get-candidates` code, they can't
> appear in global-mark-ring source as marker-buffer is checked:

Ah, okay! Thanks for the info! And for helm :-)

--
John
