### ISSUE TITLE
helm-M-x to insert symbol name 

### ISSUE THREAD

**Issue by flintforge** [emacs-helm/helm#2462]
### Suggestion

What about using `helm-M-x `to insert selected symbol name ?

### Description

We look into the vast catalog of functions available to program, look for their documentation, read their code, call them interactively and at some point insert their name. Completions frameworks works for a specific mode, but one may be typing elisp when not in elisp-mode (say, in org-mode). This is where I find helm-M-x useful. There are certainly other ways to do so - and I may have miss something else - but I found this way very convenient and short to implement. The F-1 to 9 keys are already bound in helm-M-x (when their not also bound on X) and the 5 last are related to debugging.  To rank this one in the priority list, I would say I goes between the 3rd and 5th place. What do you think ? Personal customization or larger scope ?

### Solutions

``` elisp
(defcustom helm-type-function-actions
  (helm-make-actions
   "Describe function"  ... "Find function" ... etc.
   "Insert function name" '(lambda(func) (insert (symbol-name func)))
```

**Comment by thierryvolpiatto** [comment]
flintforge ***@***.***> writes:

> Suggestion
>
> What about using helm-M-x to insert selected symbol name ?

You can use C-c C-i for this.

-- 
Thierry

**Comment by flintforge** [comment]
Many thanks Thierry. I guess I got confused by the meaning of "marked candidate" and hadn't tried hard enough.
