### ISSUE TITLE
browse-url-galeon-program removed from master

### ISSUE THREAD

**Issue by michael-heerdegen** [emacs-helm/helm#2466]
### What happened?

Loading "helm-net" fails.

### How to reproduce?

Load helm-net.

The removed variable is referenced in the definition of `helm-browse-url-default-browser-alist'.  Oh, they also removed `browse-url-netscape-program` - you may check what exactly has to be done.  TIA - Michael.

### Helm Version

Last from Melpa

### Emacs Version

Emacs-28.0.50

### OS

GNU/Linux

### Relevant backtrace (if possible)

```text
Should be clear.
```

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by michael-heerdegen** [comment]
I could not select 29.0.50 from the Emacs version list btw.  Maybe you can just add "master"?

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen ***@***.***> writes:

> The removed variable is referenced in the definition of
> helm-browse-url-default-browser-alist'. Oh, they also removed
> browse-url-netscape-program`

Should be fixed, not tested on emacs-28/29 though.

Thanks.

-- 
Thierry

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto ***@***.***> writes:

> Should be fixed, not tested on emacs-28/29 though.

I can confirm that it's fixed on 29, too.

Thanks, Michael.
