### ISSUE TITLE
commit e419f5452 :  helm-find-files no longer shows as candidate a URL or path if inside a code block

### ISSUE THREAD

**Issue by rdiaz02** [emacs-helm/helm#2469]
### What happened?

I think the changes introduced on 2021-12-22, in commit e419f5452d9e81588de5f4a28b07fbe6e79e651a , "Allow matching library at toplevel when point is not in first line of" change the former behavior of `helm-find-files` so that now URLs or paths will not be shown as candidates if they are inside some some blocks of code and `helm-ff-search-library-in-sexp` is true.

*What happens*
If point is on a URL or a path, `helm-find-files` will not show the URL or path as candidate to open, but will show the library as candidate.

*What did I expect to happen*
If point is on a URL or path, `helm-find-files` will show as candidate the URL or path. This was the behavior with version 3.8.0 of helm. And I think this is desirable behavior: if point is on a URL or path, we probably want to open that URL or path (not the toplevel library).

### How to reproduce?

Start emacs with `emacs -Q`. Then evaluate these lines in the scratch buffer

```
;; URL1:  https://github.com/emacs-helm/helm

(require 'package)

;; URL 2:  https://github.com/emacs-helm/helm

(package-initialize)

(setq helm-ff-search-library-in-sexp t)

(use-package helm
  :preface  (require 'helm-config)
  :bind (
	 ;; URL 3:  https://github.com/emacs-helm/helm
         ;; some path:   /tmp
	 ("C-x C-f"	.	helm-find-files)
	 )
  )
```

After evaluating the code, using `helm-find-files` on URL 1 (anywhere in the URL itself) will show, as candidate, the URL. However, placing point on URL 2 and using `helm-find-files` will offer as candidate the file `package.el[.gz]`  (`lisp/emacs-lisp/package.el.gz`) and placing point on URL 3 will offer as candidate `helm.el` (`somewhere/elpa/helm-core-20211202.1641/helm.el`).

Similarly, if point is somewhere on `/tmp` , the candidate shown by `helm-find-files` is  `helm.el` (not `/tmp`). 

If we `(setq helm-ff-search-library-in-sexp nil)` then, when point is at the URL or path, the candidate is the URL or path.

 

### Helm Version

Last from Melpa

### Emacs Version

Emacs-28.0.50

### OS

GNU/Linux

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by thierryvolpiatto** [comment]
Ramon Diaz-Uriarte ***@***.***> writes:

> What happened?
>
> I think the changes introduced on 2021-12-22, in commit e419f54 ,
> "Allow matching library at toplevel when point is not in first line
> of" change the former behavior of helm-find-files so that now URLs
> will not be shown as candidates if they are inside some some blocks of
> code and helm-ff-search-library-in-sexp is true.

I have reverted this commit, let me know if it works now as expected.

Thanks.

-- 
Thierry

**Comment by rdiaz02** [comment]
Yes, it does work as expected. Thank you very much!! I guess we can close this issue.
