### ISSUE TITLE
helm-mode-org-insert-link doesn't show newly created files

### ISSUE THREAD

**Issue by nyc-tinker** [emacs-helm/helm#2473]
### What happened?

org-insert-link (which activates helm-mode-org-insert-link) doesn't show newly created files.  If one were to save a new file (while emacs is already running), one cannot create a link to the file using helm-mode-org-insert-link.  The newly created file does not appear in the list of candidates.

File does show up in dired mode.

Note that shutting down emacs and restarting resolves this issue.  Any workaround?

### How to reproduce?

- Open emacs with helm
- Save a new file in a location
- Try to insert a link to the newly created file in emacs

### Helm Version

Master branch

### Emacs Version

Emacs-27.1

### OS

GNU/Linux

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by thierryvolpiatto** [comment]
nyc_tinker ***@***.***> writes:

> What happened?
>
> org-insert-link (which activates helm-mode-org-insert-link) doesn't
> show newly created files. If one were to save a new file (while emacs
> is already running), one cannot create a link to the file using
> helm-mode-org-insert-link. The newly created file does not appear in
> the list of candidates.
>
> Note that shutting down emacs and restarting resolves this issue. Any workaround?
>
> How to reproduce?
>
>   • Open emacs with helm
>   • Save a new file in a location
>   • Try to insert a link to the newly created file in emacs

Your recipe is vague, here what I did from emacs-helm.sh:

1) Create and save ~/tmp/test.txt with foo as first line contents.
2) Create a new org file ~/tmp/test.org.
3) insert a * test header in this file
4) M-x org-insert-link
- Choose "file:" (first prompt) and RET
- Choose the new created ~/tmp/test.txt (second prompt)

So as you can see I can't reproduce, did I miss something?

-- 
Thierry

**Comment by nyc-tinker** [comment]
You are correct - running emacs-helm.sh fails to replicate the issue, so it must be another package that is conflicting with this.  I will investigate further if I can find the conflict.

**Comment by nyc-tinker** [comment]
After some investigation, it appears this is a pretty nuanced issue that may only be relevant in a WSL2 / Debian setup, which is what my setup is.  

When I save a file in Windows (for example, foo.jpg), in a given directory, helm does not see the file.  I have replicated this issue using the emacs-helm.sh script.

However, in what I would consider a workaround is to then access the disk on the Debian side (i.e. if `touch bar.txt` is executed).  When `touch bar.txt` is executed, helm can see the image file `foo.jpg` created in the previous step.

What is odd is that this only seems to affect helm, as accessing the directory via Dired shows the file with no problems without needing to access the disk on the Debian side first.

**Comment by thierryvolpiatto** [comment]
nyc_tinker ***@***.***> writes:

> After some investigation, it appears this is a pretty nuanced issue
> that may only be relevant in a WSL2 / Debian setup, which is what my
> setup is.
>
> When I save a file in Windows (for example, foo.jpg), in a given
> directory, helm does not see the file. I have replicated this issue
> using the emacs-helm.sh script.

Helm FF is caching files of each directory and watching each directory
visisted (once cached) with notify library, when you are using Windows
to create, delete, move etc... Debian (notify) is not aware of this and
vice versa.

> However, in what I would consider a workaround is to then access the
> disk on the Debian side (i.e. if touch bar.txt is executed). When
> touch bar.txt is executed, helm can see the image file foo.jpg created
> in the previous step.

Yes because the cache is created again, I suggest to do only C-c C-u
instead to refresh the cache.

> What is odd is that this only seems to affect helm, as accessing the
> directory via Dired shows the file with no problems without needing to
> access the disk on the Debian side first.

Dired is not caching directory contents, well the cache is the buffer if
you keep it and you should have the same problem in an existing dired
buffer until you hit "g".

-- 
Thierry

**Comment by nyc-tinker** [comment]
Thank you!
