### ISSUE TITLE
helm-grep fails with patterns starting with a hyphen

### ISSUE THREAD

**Issue by x-yuri** [emacs-helm/helm#2475]
### What happened?

When I try to search files e.g. for `\) ->` it finds nothing and in the log I can see:

```
 Command line used was:

>>> rg --color=always --smart-case --no-heading --line-number  -- \\\) /home/yuri/.emacs.d/elpa/helm-20211223.2045/ | rg -N -S --color=always  -\>
...
 output-string = "error: Found argument '->' which wasn't expected, or isn't valid in this context

USAGE:
...
```

The reason is supposedly [here][a] (no `--`).

[a]: https://github.com/emacs-helm/helm/blob/v3.8.2/helm-grep.el#L1537

### How to reproduce?

* `M-:` `(setq helm-grep-ag-command "rg --color=always --smart-case --no-heading --line-number %s -- %s %s")` `RET`
* `C-x C-f`
* `M-g a`
* `C-h C-d`
* `\) ->`
* `C-g`
* `M-x` `helm-debug-open-last-log` `RET`

### Helm Version

Last from Melpa

### Emacs Version

Emacs-27.2

### OS

GNU/Linux

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by thierryvolpiatto** [comment]
x-yuri ***@***.***> writes:

> What happened?
>
> When I try to search files e.g. for \) -> it finds nothing and in the log I can see:

Use something like this: "\)\s[->]"

-- 
Thierry

**Comment by x-yuri** [comment]
In the end I used `\)\ ->`, but this (with `\) ->`) sounds like a bug.

**Comment by thierryvolpiatto** [comment]
x-yuri ***@***.***> writes:

> In the end I used \)\ ->, but this (with \) ->) sounds like a bug.

No, helm interpret your space as a multi search.


-- 
Thierry

**Comment by x-yuri** [comment]
That's okay if it does, but it could add `--` to the command line:

```
rg ... \\\) /some/path/ | rg ... -\>
```

See? It (`rg`) runs into `->` and thinks it's an option, when in fact it is an argument (a pattern).

I can make it work with one pattern:

```
(setq helm-grep-ag-command "rg ... %s -- %s %s")
```

but I can't affect the [second command][a].

[a]: https://github.com/emacs-helm/helm/blob/v3.8.2/helm-grep.el#L1537

**Comment by thierryvolpiatto** [comment]
x-yuri ***@***.***> writes:

> That's okay if it does, but it could add -- to the command line:
>
> rg ... \\\) /some/path/ | rg ... -\>
>
> See? It (rg) runs into -> and thinks it's an option, when in fact it is an argument (a pattern).
>
> I can make it work with one pattern:
>
> (setq helm-grep-ag-command "rg ... %s -- %s %s")
>
> but I can't affect the second command.

Try with `helm-grep-ag-pipe-cmd-switches`.

-- 
Thierry

**Comment by x-yuri** [comment]
You also might want to update the commands here:

https://github.com/emacs-helm/helm/blob/cd4add6fae1d9acf8904d93f2f32e37c0737b03d/helm-grep.el#L1471-L1476

And possibly in other parts.

**Comment by thierryvolpiatto** [comment]
x-yuri ***@***.***> writes:

> You also might want to update the commands here:
>
> https://github.com/emacs-helm/helm/blob/cd4add6fae1d9acf8904d93f2f32e37c0737b03d/helm-grep.el#L1471-L1476

Right, thanks.


-- 
Thierry
