### ISSUE TITLE
Is it possible not turn on async-bytecomp-package-mode automatically?

### ISSUE THREAD

**Issue by ShuguangSun** [emacs-helm/helm#2479]
### Suggestion

Don't turn on async-bytecomp-package-mode automatically

### Description

https://lists.gnu.org/archive/html/bug-gnu-emacs/2022-02/msg00003.html
A new mechanism for compilation warning positions has been merged into Emacs recently, and it will lead to some issue for packge install or update.
```
error in process sentinel: async-when-done: Invalid read syntax: "#<"
error in process sentinel: Invalid read syntax: "#<"
```

### Solutions

Make it a user option to turn on or not the `async-bytecomp-package-mode`

**Comment by thierryvolpiatto** [comment]
ShuguangSun ***@***.***> writes:

> Suggestion
>
> Don't turn on async-bytecomp-package-mode automatically

This is not an option, using async-bytecomp saved me dozen of bugreports
since years now, if there is a problem with it, I prefer trying to fix
it.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
I think this have been fixed in emacs, closing.
