### ISSUE TITLE
Helm on nongnu does not handle dependencies

### ISSUE THREAD

**Issue by stshine** [emacs-helm/helm#2480]
### What happened?

When installing helm from the nongnu elpa, packages that helm depends on is not installed.

### How to reproduce?

Add nongnu repository to `package-archives`.
List packages by `M-x list-packages`.
Select `helm` from nongnu and install.
Package `helm-core`, `async`, `popup` is not installed.

### Helm Version

Last from Melpa

### Emacs Version

Emacs-27.2

### OS

Windows

### Relevant backtrace (if possible)

```text
;; This is copied from "~/.emacs.d/elpa/archives/nongnu/archive-contents".
;; The dependecy variable is nil.

 (helm .
       [(3 6 2)
	nil "Emacs incremental and narrowing framework" tar
	((:url . "https://github.com/emacs-helm/helm")
	 (:maintainer "Thierry Volpiatto" . "thierry.volpiatto@gmail.com")
	 (:authors
	  ("Thierry Volpiatto" . "thierry.volpiatto@gmail.com"))
	 (:commit . "4ff354efb6b24044fd38b725b61d470bd5423265"))])
```

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by thierryvolpiatto** [comment]
stshine ***@***.***> writes:

> What happened?
>
> When installing helm from the nongnu elpa, packages that helm depends on is not installed.
>
> How to reproduce?
>
> Add nongnu repository to package-archives.
> List packages by M-x list-packages.
> Select helm from nongnu and install.
> Package helm-core,

I guess the problem comes from here, ELPA doesn't support the concept of
having two different packages coming from the same git repository
i.e. helm-core and helm.
I even didn't know Helm was already available on NonGNU Elpa!

> async, popup is not installed.

For these two no ideas what's wrong.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
It seems I am wrong as I see Nongnu Elpa provides helm-core and helm packages so I have no ideas what's wrong, may be you should report this on Emacs bug or devel.

**Comment by stshine** [comment]
I'll have a try, then.
Althrough I am really not sure where the bug should go...

**Comment by thierryvolpiatto** [comment]
Also they are using version 3.6.2 which is deprecated! Why 3.6.2 no ideas!

**Comment by thierryvolpiatto** [comment]
I have just tagged a new version 3.8.3 which is now the latest.

**Comment by thierryvolpiatto** [comment]
Oh I see, they read the version from helm.el headers which was not up to date (3.6.2) and use the corresponding tag.

**Comment by stshine** [comment]
I have sent an email to bug-gnu-emacs mailing list. Still I don't know if I have succeed or not...

**Comment by thierryvolpiatto** [comment]
I updated *.pkg.el files as well and created a new tag.

**Comment by stshine** [comment]
The Emacs bug I submitted is https://debbugs.gnu.org/cgi/bugreport.cgi?bug=53805

**Comment by mgsloan** [comment]
Fix here this seems to have broken use with straight.el + use-package.  I opened #2481 in order to not distract from the main topic here.

**Comment by stshine** [comment]
Helm on NonGNU works fine now.
Thank you!

**Comment by stshine** [comment]
Oh, one regression: Call `(describe-package 'helm)` results error:
(wrong-type-argument char-or-string-p nil)

I guess this is cause by lacking of Commentary section in helm.el.

**Comment by thierryvolpiatto** [comment]
stshine ***@***.***> writes:

> Oh, one regression: Call (describe-package 'helm) results error:
> (wrong-type-argument char-or-string-p nil)
>
> I guess this is cause by lacking of Commentary section in helm.el.

Done! Thanks.

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.
> You are receiving this because you commented.*Message ID: ***@***.***>


-- 
Thierry
