### ISSUE TITLE
Allow Pre-Marking/Pre-Select of Multiple Candidates (e.g. as a slot in the main `helm` API or through some auxiliary API)

### ISSUE THREAD

**Issue by MattMicheletti** [emacs-helm/helm#2485]
### Suggestion

Is it possible to some how pre-mark the candidates that Helm displays? Perhaps, could the `:preselect` slot be enhanced to allow for a list of candidates to mark on initialization?

### Description

Essentially, specified candidates would have the `*` marker already next to them once Helm initializes and displays. Simplifying repetitive invocations and allowing for more user-centric Helm buffers whereby users can just immediately proceed with their desired action(s) / just press enter.

### Solutions

I have tried using the `:after-init-hook` slot of the `:sources` slot but it does not seem to be at the right timing to properly execute any Helm methods (e.g. `helm-mark-all`) because `with-helm-alive-p` determines that Helm is not active (I am using Helm in it's own frame, similar to your own configuration Thierry). There is probably a better way to accomplish this or a more appropriate API, hook, or slot than what I seem to be using.

Thanks for any help, suggestions, ideas, etc. :)

**Comment by thierryvolpiatto** [comment]
Matt Micheletti ***@***.***> writes:

> Suggestion
>
> Is it possible to some how pre-mark the candidates that Helm displays?
> Perhaps, could the :preselect slot be enhanced to allow for a list of
> candidates to mark on initialization?

You have to wait helm finish updating before marking all, something like
this:

    (defun helm/test-mark-all-at-init ()
      (with-helm-after-update-hook (helm-mark-all))
      (helm :sources (helm-build-sync-source "test" :candidates '(a b c d e f))
            :buffer "*helm test*"))

-- 
Thierry

**Comment by MattMicheletti** [comment]
> 

Thanks @thierryvolpiatto! That worked perfectly. I was able to adapt the `helm-mark-all` method for my needs. Thanks again :)
