### ISSUE TITLE
Make helm support wgrep multi-file editing feature if available.

### ISSUE THREAD

**Issue by zw963** [emacs-helm/helm#2491]
### Suggestion

Following is some hack for help-grep.el. (sorry, i remove some code which i don't know how to use it, but it works for me)

```diff
diff --git a/helm-grep.el b/helm-grep.el
index d212afe9..da61a7eb 100644
--- a/helm-grep.el
+++ b/helm-grep.el
@@ -823,18 +823,6 @@ If N is positive go forward otherwise go backward."
          (pattern (with-helm-buffer helm-input-local))
          (src (helm-get-current-source))
          (src-name (assoc-default 'name src)))
-    (when (get-buffer buf)
-      (if helm-grep-save-buffer-name-no-confirm
-          (setq new-buf  (format "*hgrep|%s|-%s" pattern
-                                 (format-time-string "%H-%M-%S*")))
-        (setq new-buf (helm-read-string "GrepBufferName: " buf))
-        (cl-loop for b in (helm-buffer-list)
-                 when (and (string= new-buf b)
-                           (not (y-or-n-p
-                                 (format "Buffer `%s' already exists overwrite? "
-                                         new-buf))))
-                 do (setq new-buf (helm-read-string "GrepBufferName: " "*hgrep "))))
-      (setq buf new-buf))
     (with-current-buffer (get-buffer-create buf)
       (setq default-directory (or helm-ff-default-directory
                                   (helm-default-directory)
@@ -863,7 +851,9 @@ If N is positive go forward otherwise go backward."
             (define-key map [mouse-2] 'helm-grep-mode-mouse-jump)
             (define-key map [mouse-3] 'ignore)
             (forward-line 1))))
-      (helm-grep-mode))
+      (helm-grep-mode)
+      (if (fboundp 'wgrep-change-to-wgrep-mode)
+          (wgrep-change-to-wgrep-mode)))
     (pop-to-buffer buf)
     (message "Helm %s Results saved in `%s' buffer" src-name buf)))
```

Now, when we run `helm-grep-do-git-grep`, then pressing `F3` to select the action `Save results in grep buffer`.
We can editing it directly use [wgrep](https://github.com/mhayashi1120/Emacs-wgrep)

Thanks

### Description

support wgrep 

### Solutions

support wgrep.

**Comment by thierryvolpiatto** [comment]
We already support wgrep.

**Comment by zw963** [comment]
I always use F3 (the third action) for use it after apply above hack, so, what is the prefer way to use wgrep?

Thank you.

**Comment by thierryvolpiatto** [comment]
"Billy.Zheng" ***@***.***> writes:

> I always use F3 (the third action) for use it after apply above hack, so, what is the prefer way to use wgrep?

C-x C-s to save grep/ag/rg buffer, then M-x wgrep-change-to-wgrep-mode
(don't remember what is the default binding (perhaps C-c p, not sure), I
use here C-x C-Q).
Then you can edit your buffer, use iedit, query-replace etc... hit C-x
C-s when done.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
"Billy.Zheng" ***@***.***> writes:

>     C-x C-s to save grep/ag/rg buffer, then M-x wgrep-change-to-wgrep-mode (don't remember what is the default binding (perhaps C-c p, not sure), I use here C-x C-Q). Then you can edit
>     your buffer, use iedit, query-replace etc... hit C-x C-s when done.
>
> Yes, that exactly what i have done on this issue, wgrep official
> hotkey is: C-c C-p, what i proposed is, we don't need pressing this
> key anyway, because the only usage which i know when entrying
> grep/ag/rg buffer is, replace use wgrep, maybe we can add one more
> options, make C-c C-p can be running automatically when save
> grep/ag/rg buffer?

Ok, you can achieve this with:

    (add-hook 'helm-grep-mode-hook 'wgrep-change-to-wgrep-mode)

-- 
Thierry

**Comment by zw963** [comment]
> (add-hook 'helm-grep-mode-hook 'wgrep-change-to-wgrep-mode)

Hi, thank you for your answer, i try it, but it seem like not same as code above, with following difference:

1. as you can see, i delete the code which confirm override grep buffer, it more conveniently.
2.  more important, only add above hook, behavior not same. e.g. following is some explain with some screens

1) when i editing, it should be highlight the entry line, but add hook is not.
![image](https://user-images.githubusercontent.com/549126/161198766-3fd39534-2a7f-4c81-b578-41ddfd6ec2cf.png)

2)  After C-c C-k to discard changes, i can pressing `q` to exit this buffer, but hook is not.

so, i guess this hook is hook `wgrep-changes-to-wgrep-mode` into different place cause this issue, i test on 04f5cdba

**Comment by thierryvolpiatto** [comment]
Oops! sorry, try instead:

`(add-hook 'helm-grep-mode-hook 'wgrep-change-to-wgrep-mode 100)`
