### ISSUE TITLE
Support for Emacs 28.1 completions-detailed parameter

### ISSUE THREAD

**Issue by Horrih** [emacs-helm/helm#2496]
### Suggestion

Emacs 28.1 has introduced the completions-detailed parameter, which enables a more detailed view in the completion system.
I have looked for a bit but can't seem to find an equivalent in helm for the moment (except C-j on every line one after the other)

### Description

When completions-detailed parameter is not nil, display the beginning of the description of the symbol/function/command/apropos on the side.

I use helm all the time, thank you very much for your work !
This would be really a game changer for me, i spend a lot of time in helm-M-x and helm-apropos to play with the packages I learn, and 90% of the time a short description would helm me pick without needing the detailed view.

### Solutions

An example of nice looking interface would be the [ivy-rich equivalent](https://github.com/Yevgnen/ivy-rich/blob/master/screenshots.org) which displays that in a second column.

Of course, I guess it will impact negatively performance so it should be opt-in (as is the completions-detailed variable in emacs 28.1).

**Comment by thierryvolpiatto** [comment]
> I get the performance argument, even if I believe some tricks could help mitigate this issue, e.g loading the descriptions after a delay or on a keypress, and only for the currently displayed results.

Implemented for *M-x, it is not enabled by default as I found this distracting, you can toggle this with `C-]`.
Thanks.

**Comment by Horrih** [comment]
Thank you so much !!
It looks amazing and I did not notice a drop in performance, great job.
I will leave it on on my side :)

The only issue I see is if you leave it off, two trailing whitespaces have been added by the commit. It looks ugly if show-trailing-whitespace is set to true
I just created a [PR with a fix proposal ](https://github.com/emacs-helm/helm/pull/2500) to address this specific issue.

**Comment by vonHabsi** [comment]
Is something like this available for Emacs 27?

I just asked a question about it [on reddit](https://www.reddit.com/r/emacs/comments/v9quds/can_mx_be_made_to_display_the_docstrings_of_the/) and none of the solutions used `helm`.

Recently I've been writing lots of functions with function names along the lines of `object-verb` and they can be so similar and confusing and that is why are needed.

There are something you never really think of until the need hits you. Right now the reason I still prefer `helm-M-x` is the way it separates the recently used functions from the rest, but I think given my needs I can probably do without it.

I'll be upgrading to Emacs 28.1 soon so this new feature might make me stick with helm for longer. You should consider it in all applicable parts of helm.

With increasingl powerful computers the performance overhead may be less important, and even with a performance hit the results come up faster than most people can work out exactly which one they need.

**Comment by thierryvolpiatto** [comment]
Frank Church ***@***.***> writes:

> Is something like this available for Emacs 27?

Yes it is working on 27 as well just hit C-] from helm-M-x.
It is documented in helm-M-x, just hit C-h m as always.

It is not implemented with the completions-detailed parameter and will
not as it is terribly slow, IOW no completions-detailed parameter
implementation planned for completion-at-point and other generic
functions like describe-variable etc...

I have not yet enabled it in helm-apropos because by default
helm-apropos uses a small frame and there is no place for such long
lines, but I may make a switch allowing using it when not displayed in frame.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
helm-M-x with short doc enabled:
![Capture d’écran_2022-06-14_07-12-25](https://user-images.githubusercontent.com/1533939/173498308-3f7122b0-b79c-4c1f-8994-b1bb57919dcd.png)

**Comment by vonHabsi** [comment]
Which function does helm bind `C-]` to?

Mine is bound to another function.

**Comment by thierryvolpiatto** [comment]
Frank Church ***@***.***> writes:

> Which function does helm bind C-] to?

helm-M-x-toggle-short-doc

> Mine is bound to another function.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you modified the open/close state.*Message ID: ***@***.***>


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
I finally find a compromise, by providing `completions-detailed` parameter only for the `emacs` `helm-completion-style` so if one use:
```elisp
(setq helm-completion-style 'emacs
      completions-detailed t)
```
details will be displayed with C-h f/v/o etc... though it is quite slow as expected, but usable.

Also short doc like in helm-M-x are now available in helm-apropos, to turn it on:

```elisp
(setq helm-apropos-show-short-doc t
      helm-commands-using-frame
      (remove 'helm-apropos helm-commands-using-frame))
```

**Comment by thierryvolpiatto** [comment]
![Capture d’écran_2022-06-16_11-53-17](https://user-images.githubusercontent.com/1533939/174044937-d7de157d-ae56-476e-be63-9716e6e7b835.png)
![Capture d’écran_2022-06-16_11-53-53](https://user-images.githubusercontent.com/1533939/174044958-49b8e332-01ce-42d7-9f2c-27d6829b2eb7.png)
