### ISSUE TITLE
Protect system processes calls

### ISSUE THREAD

**Issue by albinus** [emacs-helm/helm#2497]
### What happened?

With the upcoming Emacs 29, system process functions like `list-system-processes` and `process-attributes` work on the remote host when default-directory is remote. In order to avoid this, wrap the respective code by

```
(let ((default-directory temporary-file-directory))
  ...)

```

### How to reproduce?

See above

### Helm Version

Master branch

### Emacs Version

Emacs-28/29

### OS

GNU/Linux

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by thierryvolpiatto** [comment]
Hello Michael,

albinus ***@***.***> writes:

> What happened?
>
> With the upcoming Emacs 29, system process functions like
> list-system-processes and process-attributes work on the remote host
> when default-directory is remote. In order to avoid this, wrap the
> respective code by
>
> (let ((default-directory temporary-file-directory))
>   ...)

I am not sure to understand where you want these changes to happen.
Also how do you deal with this for compatibility with previous Emacs versions?

Thanks.

-- 
Thierry

**Comment by albinus** [comment]
> Hello Michael, 

Hi Thierry,

> I am not sure to understand where you want these changes to happen.

I've searched the (Non)GNU ELPA repositories for uses of `list-system-processes` and `process-attributes`, and there are

```
packages/helm-core/helm-lib.el
1078:   (cl-loop with process-list = (list-system-processes)
1080:         for process = (assoc-default 'comm (process-attributes pid))
packages/helm/helm-lib.el
1078:   (cl-loop with process-list = (list-system-processes)
1080:         for process = (assoc-default 'comm (process-attributes pid))
```

>  Also how do you deal with this for compatibility with previous Emacs versions? Thanks.

The code snippet I have shown guarantees backward compatibility, because `default-directory` is not remote.

> -- Thierry

Best regards, Michael.

**Comment by thierryvolpiatto** [comment]
Done, thanks.

**Comment by thierryvolpiatto** [comment]
albinus ***@***.***> writes:

>     Hello Michael,
>    
> Hi Thierry,
>
>     I am not sure to understand where you want these changes to happen.
>    
> I've searched the (Non)GNU ELPA repositories for uses of
> list-system-processes and process-attributes,

Ok, I thought there were something else because you said "like
list-system-processes and process-attributes".

> The code snippet I have shown guarantees backward compatibility, because default-directory is not remote.

Yes of course!

Applied, will be merged in master soon.

Thanks.

-- 
Thierry
