### ISSUE TITLE
Error: Trying to run helm within a running helm session.

### ISSUE THREAD

**Issue by zylthinking** [emacs-helm/helm#2499]
### What happened?

open futex with WoMan in space emacs report: Error: Trying to run helm within a running helm session.
others such as open/epoll_ctl... etc are OK

and in shell, man futex, and man open/epoll_ctl ... etc are all OK

### How to reproduce?

1. emacs version is 28.1
2. bind M-k to Woman in evil normal/insert/motion modes
3. in evil insert mode, M-k to wake up Woman
4. input futex and press enter
5. helm reports Error: Trying to run helm within a running helm session.

### Helm Version

Melpa or NonGnuElpa

### Emacs Version

Emacs-28/29

### OS

GNU/Linux

### Relevant backtrace (if possible)

```text
I don't know which version the helm is, it is downloaded from spacemacs automatically
```

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by thierryvolpiatto** [comment]
You agree using a minimal version, but it seems you don't.
Helm is not supporting Spacemacs, please try to provide a bug report starting from emacs-helm.sh.
Thanks.
