### ISSUE TITLE
Sort by kind, name, descendent order

### ISSUE THREAD

**Issue by AtomicNess123** [emacs-helm/helm#2501]
### Suggestion

It would be great to be able to sort directories grouping first all subdirectories first and then allowing to sort in descending order. I have tried to find elsewhere how to do this but it doesn't seem to be possible.

### Description

Using a switch to allow kind sort.

### Solutions

Investigating at the moment :)

**Comment by thierryvolpiatto** [comment]
Name of Mine ***@***.***> writes:

> Suggestion
>
> It would be great to be able to sort directories grouping first all
> subdirectories first and then allowing to sort in descending order. I
> have tried to find elsewhere how to do this but it doesn't seem to be
> possible.

You have a serie of sort commands in HFF (S-<f1>..<f6>).

Note that of course all these commands have effect only when displaying
the whole directory, not when filtering its contents.

-- 
Thierry
