### ISSUE TITLE
Donation links are missing 

### ISSUE THREAD

**Issue by ReneFroger** [emacs-helm/helm#2505]
Helm is mainly maintained by only one person, Thierry Volpiatto, which is already a huge task on itself.
Earlier on Helm's readme and Helm's wiki page, there was a link to Paetron which enables people to donate. Since Paetron made it a mess with their billing, agreements and security, the links to the Emacs Helm's Paetron donation page gets removed.

As far I'm aware, Thierry uses liberapay. But I don't see any reference to it on Emacs Helm readme and Emacs Helm Wikipage or documentation. I think a lot of people would love to help with a financial donation, but they are not aware of the possibility to do.

Would it be desirable if I could add links about the possibility to donate to Thierry Volpiatto on both Helm's readme and wiki?

**Comment by thierryvolpiatto** [comment]
The links are on the right side of the Readme page on Github but not on the Home page indeed, I will add the links soon (even if donations for Helm tend to zero nowaday :-1: ( ).

**Comment by ReneFroger** [comment]
Please do! I would love to help, but my Elisp knowledge is somewhat limited. 

I know only that there were many recurring contributors on Patreon for Emacs Helm, until you switched to Liberapay which caused a loss of recurring donations I suspect?

**Comment by brotzeit** [comment]
> I know only that there were many recurring contributors on Patreon for Emacs Helm, until you switched to Liberapay which caused a loss of recurring donations I suspect?

I didn't even realize.

**Comment by thierryvolpiatto** [comment]
ReneFroger ***@***.***> writes:

> Please do! I would love to help, but my Elisp knowledge is somewhat limited.

The links have been added, thanks for your support!

> I know only that there were many recurring contributors on Patreon for
> Emacs Helm, until you switched to Liberapay which caused a loss of
> recurring donations I suspect?

Definitely. 

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.*Message ID: ***@***.***>


-- 
Thierry

**Comment by ReneFroger** [comment]
@thierryvolpiatto I think this issue should be opened.

I would to set up a fundraiser again because Helm needs more support. A lot of damage was done when you kept switching from donation processing websites. Why would you do that? That's the fastest way to lose recurring donations :disappointed: 
By the way, I noticed Libera pay keeps reminding me to donate to Helm. Is there no payment website which makes you to donate to Helm recurring?

**Comment by thierryvolpiatto** [comment]
ReneFroger ***@***.***> writes:

> @thierryvolpiatto I think this issue should be opened.
>
> I would to set up a fundraiser again because Helm needs more
> support.

It's a long time I didn't look into this, so I am not aware of what is
good actually for that.
I am not sure also (even if I continue improving and maintaining) there
is much interest in Helm nowaday as what we had before. 

> A lot of damage was done when you kept switching from donation
> processing websites.
> Why would you do that? That's the fastest way to lose recurring
> donations 😞

Agree, that's was an error at the time to leave Patreon.

> 
> By the way, I noticed Libera pay keeps reminding me to donate to
> Helm. Is there no payment website which makes you to donate to Helm
> recurring?

The only ways actually to contribute are Paypal and Libera, Libera
interface is pretty unclear of who donate, how much etc... Anyway there
is really few contributors nowaday for Helm (3 on Libera I think and on
paypal nearly nothing).


-- 
Thierry

**Comment by ReneFroger** [comment]
I will address this soon. But could you pinpoint me where the donation links are added? I couldn't find any mention of it in the readme file. Thanks in advance!

**Comment by thierryvolpiatto** [comment]
ReneFroger ***@***.***> writes:

> I will address this soon.

Thanks!

> But could you pinpoint me where the donation links are added?


They are on the right of the home page
(https://github.com/emacs-helm/helm), under "Sponsor this project".

> I couldn't find any mention of it in the readme file.

Yes, they are no more in README file, I used the "Sponsor" github
feature to add them.
I also added the links here https://emacs-helm.github.io/helm/


-- 
Thierry

**Comment by ReneFroger** [comment]
I updated the readme because the donation links are _really_ difficult to find which doesn't help your case much.  Could you merge/review the proposed changes? Then I would like to set up a fundraiser.

**Comment by patrickaroo** [comment]
I just want to say that I am sorry that the donations are so low. I am working on improving my scene and when I do I will contribute. I absolutely love and rely on Helm.

**Comment by thierryvolpiatto** [comment]
patrickaroo ***@***.***> writes:

> I just want to say that I am sorry that the donations are so low. I am
> working on improving my scene and when I do I will contribute. I
> absolutely love and rely on Helm.

Thank you very much.

I will reenable a Patreon link ASAP, I removed all links to PayPal
because this company is so bad (account blocked, ask for factures for
each donations etc...) and as Liberapay uses Paypal, I removed as well,
so actually there is no way for donations in Helm.

>
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.*Message ID: ***@***.***>


-- 
Thierry

**Comment by capfredf** [comment]
I would like to support helm. Can you use GitHub sponsorship?

**Comment by thierryvolpiatto** [comment]
Fred Fu ***@***.***> writes:

> I would like to support helm.

Thanks.

> Can you use GitHub sponsorship?

No, but I will add a Patreon link soon.

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.*Message ID: ***@***.***>


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Patreon links has been added.

**Comment by ReneFroger** [comment]
Where can I find the donation links in the Emacs github repository?

**Comment by thierryvolpiatto** [comment]
ReneFroger ***@***.***> writes:

> Where can I find the donation links in the Emacs github repository?

On the right column of the README page under "Sponsor this project".

Thanks.

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you modified the open/close state.*Message ID: ***@***.***>

-- 
Thierry

**Comment by ReneFroger** [comment]
https://old.reddit.com/r/emacs/comments/18hfso2/emacs_helm_is_maintained_by_one_maintaner_for_11/?

**Comment by thierryvolpiatto** [comment]
ReneFroger ***@***.***> writes:

> https://old.reddit.com/r/emacs/comments/18hfso2/emacs_helm_is_maintained_by_one_maintaner_for_11/?

Thanks.
Problem is also (las comment confirm it) I failed to explain what Helm
is and does, most people think about "completion only" whereas Helm provide
much more than this, so they don't understand why the Helm package is
bigger than others.  The consult or vertico (not sure which one is it)
package(s) don't provide the half of what Helm does.

-- 
Thierry

**Comment by karbiv** [comment]
Other option is missing - "**_one-of payments_**" like buymeacoffee . com

On Mar 14~18 2024 github announced buymeacoffee support.
https://www.buymeacoffee.com/warengonzaga/enable-buy-me-coffee-github-project
