### ISSUE TITLE
Sort bookmarks, most visited first in helm-bookmarks

### ISSUE THREAD

**Issue by TimotheeMathieu** [emacs-helm/helm#2507]
### Suggestion

I want to have the most used bookmark listed first to gain time when searching for bookmarks that I use everyday.

### Description

From what I understood, this should be doable with helm-adaptive and helm-bookmarks but I think it is not implemented yet. 

### Solutions

The alternative is not to use helm and use bookmarks+ instead that support this type of sorting, but helm is much more efficient IMHO for a fast access to bookmarks.

**Comment by thierryvolpiatto** [comment]
Hmm replying by email seems broken, nothing appear here anymore, don't know if it is mu4e or github itself.
Anyway, the solution is to use `helm-filtered-bookmarks`.

![helm-bookmarks](https://user-images.githubusercontent.com/1533939/167284181-85a1035e-1995-451a-bf62-f376463174d5.gif)

**Comment by TimotheeMathieu** [comment]
Thanks for the answer but I don't see how I an use `helm-filtered-bookmarks` to sort bookmark by usage frequency. I beleived it was `helm-filtered-bookmarks` was just a way to categorized several sources for the bookmarks. Are you saying that we can specify a source that gets sorted by usage frequency ? I did not find how to do this.

**Comment by thierryvolpiatto** [comment]
TimotheeMathieu ***@***.***> writes:

> Thanks for the answer but I don't see how I an use
> helm-filtered-bookmarks to sort bookmark by usage frequency. I
> beleived it was helm-filtered-bookmarks was just a way to categorized
> several sources for the bookmarks. Are you saying that we can specify
> a source that gets sorted by usage frequency ? I did not find how to
> do this.

No, by using helm-adaptive your most recent bookmarks are going on top,
and when filtering with a given pattern the recentest used with this
pattern will popup on top.


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
You have first to start using your bookmarks and you will see on next usage they will popup on top.
If you never used helm-filtered-bookmarks your bookmarks are not sorted by usage frequency.
Also this differ from bookmark+ which add a usage frequency flag inside the bookmark itself, helm doesn't modify the bookmark.

**Comment by TimotheeMathieu** [comment]
You are right, it works. Thank you.
