### ISSUE TITLE
Make a new command from helm--completion-in-region that works similar to helm-lisp-completion-at-point

### ISSUE THREAD

**Issue by BooAA** [emacs-helm/helm#2510]
### Suggestion

`helm--completion-in-region` is now an advice around `completion-in-region`. Most of the time I just use the built-in tab completion, sometimes I need advanced searching than I want helm. So it will be great we have a separate command (maybe just call `helm-completion-in-region`) that works similar to `helm-lisp-completion-at-point`, so we can have the benefits from both world (the simple tab completion and powerful helm version).

### Description

Make a new command called `helm-completion-in-region` (instead of an advice around `completion-in-region`), that use `completion-at-point-function` as source and display the candidates in an overlay/child-frame just like `helm-lisp-completion-at-point`.

### Solutions

None

**Comment by thierryvolpiatto** [comment]
Liangjie Lee ***@***.***> writes:

> Suggestion
>
> helm--completion-in-region is now an advice around
> completion-in-region.

It is an advice for compatibility with other packages.

> Most of the time I just use the built-in tab completion, sometimes I
> need advanced searching than I want helm. So it will be great we have
> a separate command (maybe just call helm-completion-in-region) that
> works similar to helm-lisp-completion-at-point, so we can have the
> benefits from both world (the simple tab completion and powerful helm
> version).

Sorry but this is not possible, completion-in-region covers dozen of
different situations, if you want a specialized helm in certain
circonstances, I suggest using a specialized function for this, helm
provide many commands and sources that may fit your needs.

-- 
Thierry

**Comment by BooAA** [comment]
Understand, thanks.
