### ISSUE TITLE
C-x is hardcoded, but should use keymaps like ctl-x-map

### ISSUE THREAD

**Issue by teika-kazura** [emacs-helm/helm#2514]
Hi. In helm, many files hardcode the prefix key C-x. If you bind
something to C-x, helm initialization fails. (Users can bind any to
C-x; then you have to bind ctl-x-map to some other key. )

BUT helm has been there for years, and such complaint seems
extremely rare (only mine?) Feel free to close it as wontfix.
I'll respect your decision.
\# I recently updated helm from 1.5.6, having been too lazy for a
\# decade. ;-)

How to reproduce it:

$ emacs -Q -l foo.el

The content of foo.el:

    (setq debug-on-error t)
    (push "<path to helm>" load-path)
    (push "<path to async>" load-path)
    (push "<path to popup>" load-path)
    (global-set-key "\C-x" 'fill-paragraph) ;; or whatever
    (require 'helm)
In fact, if you don't set (setq debug-on-error t), emacs starts
without an error, and only a complaint message is shown in the minibuffer
(and \*Messages\*.)

I'm not sure of the "right" way to fix this. At the very least,
you can define "helm-xxx-ctl-x-map" for each keymap defined by helm,
but that seems to be too demanding. Solutions will not be so
straightforward since there are also other prefix keymaps, for C-h,
C-c, etc. (See the section "prefix keymaps" in the emacs manual.)

Thank you very much for developing helm.
Best regards.

**Comment by teika-kazura** [comment]
Sorry, this bug report should be marked as "unconfirmed". The true problem was edebug.el.

**Comment by teika-kazura** [comment]
(Sorry for posting several times. I closed this issue a few hours ago, but let me reopen.)

**Comment by teika-kazura** [comment]
Thanks for your kind reply. This time I get hit in helm-global-bindings.el:

> Debugger entered--Lisp error: (error "Key sequence C-x c starts with non-prefix key C-x")
> define-key((keymap ...
> #^^[3 0 set-mark-comma...
> (progn (define-key (current-global-map) (read-kbd-macro key) 'helm-command-prefix))
> (if key (progn (define-key (current-global-map) (read-kbd-macro key) 'helm-command-prefix)))
> (closure (t) (var key) (if (and (boundp var)...
> custom-initialize-reset(helm-command-prefix-key (funcall ...
> custom-declare-variable(helm-command-prefix-key (funcall ...
> eval-buffer(#<buffer  *load*-396643> nil 
> load-with-code-conversion(...
> require(helm-global-bindings nil t)

Thanks Thierry Volpiatto. IIRC it was "anything" when you took over the development of this project. :)

**Comment by thierryvolpiatto** [comment]
teika ***@***.***> writes:

> Thanks for your kind reply. This time I get hit in helm-global-bindings.el:
>
>     Debugger entered--Lisp error: (error "Key sequence C-x c starts with non-prefix key C-x")
>     define-key((keymap ...
>     #^^[3 0 set-mark-comma...
>     (progn (define-key (current-global-map) (read-kbd-macro key) 'helm-command-prefix))
>     (if key (progn (define-key (current-global-map) (read-kbd-macro key) 'helm-command-prefix)))
>     (closure (t) (var key) (if (and (boundp var)...
>     custom-initialize-reset(helm-command-prefix-key (funcall ...
>     custom-declare-variable(helm-command-prefix-key (funcall ...
>     eval-buffer(#<buffer load-396643> nil
>     load-with-code-conversion(...
>     require(helm-global-bindings nil t)

Did you update? I made a similar fix than what Lars did upstream.
    
> Thanks Thierry Volpiatto. IIRC it was "anything" when you took over the development of this project. :)
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.*Message ID: ***@***.***>


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
AFAIU if one add something like `(global-set-key "\C-x" 'fill-paragraph)` at beginning of its init file, this affect only the global map, so the fix I did in helm-global-bindings similar to what have been done in Emacs-29 should be enough.
Anyway, as it is not usual to do this and probably not recommended, I will not try to fix this further.

**Comment by teika-kazura** [comment]
I tested both vanilla emacs-28 and patched edebug.el, but the above patched doesn't work for both.

Ok, I close this issue. Let me express my gratitude again.
Best wishes.

**Comment by thierryvolpiatto** [comment]
teika ***@***.***> writes:

> I tested both vanilla emacs-28 and patched edebug.el, but the above
> patched doesn't work for both.

Out of curiosity, could you send the backtrace with again a precise
recipe of what you are doing, use the last helm from master and do not apply
any patch (to have a backtrace use emacs --debug-init), use of course
the patched edebug.el to avoid this error.

Thanks.

-- 
Thierry

**Comment by teika-kazura** [comment]
Glad to help. But --debug-init doesn't emit a backtrace, so I fell back to `(setq debug-on-error t)'. (And I used helm-3.8.5, assuming that's ok.)

Here's init.el:

> (setq debug-on-error t)
> (push "/tmp/helm-3.8.5" load-path)
> (push "/usr/share/emacs/site-lisp/popup/" load-path)
> (push "/usr/share/emacs/site-lisp/async/" load-path)
> (global-set-key "\C-x" 'fill-paragraph) ;; or whatever
> (require 'helm)

And I ran
$ emacs -Q -l init.el

(emacs-version) =>:
GNU Emacs 28.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.29, cairo version 1.16.0) of 2022-05-22

Backtrace is attached:
[Bactrace.txt](https://github.com/emacs-helm/helm/files/8790171/Bactrace.txt)

**Comment by thierryvolpiatto** [comment]
teika ***@***.***> writes:

> Glad to help. But --debug-init doesn't emit a backtrace, so I fell
> back to `(setq debug-on-error t)'. (And I used helm-3.8.5, assuming
> that's ok.)

Ah I understand, you didn't update to last helm from master, hence the
error in the attached backtrace, please update to last helm from master,
it should be fixed there (b28378b7).

Thanks.

-- 
Thierry

**Comment by teika-kazura** [comment]
Yeah, that commit fixed the problem. Thank you for your endurance!

Regards.

**Comment by teika-kazura** [comment]
FYI: Permettez mon français horrible.

> I made a similar fix **than** what Lars did upstream.

Je me suis demandé que vous vouliez dire avec ce "than", mais après avoir essayé le HEAD, je crois qu'il correspond à « que ». Vous savez, on dit « même que », mais en anglais c'est "same as". (En tout cas similaire à = similar to. :)

Je vous remercie, en fait tout vous doivent remercier, de votre travail, long, profond, vraiment diligent et très très respectable, pour Emacs. A bientôt.

**Comment by thierryvolpiatto** [comment]
teika ***@***.***> writes:

> FYI: Permettez mon français horrible.
>
>     I made a similar fix than what Lars did upstream.
>    
> Je me suis demandé que vous vouliez dire avec ce "than", mais après
> avoir essayé le HEAD, je crois qu'il correspond à « que ». Vous savez,
> on dit « même que », mais en anglais c'est "same as". (En tout cas
> similaire à = similar to. :)

Ah d'accord, je m'en rappellerai, merci.

> Je vous remercie, en fait tout vous doivent remercier, de votre
> travail, long, profond, vraiment diligent et très très respectable,
> pour Emacs. A bientôt.

Merci.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
teika ***@***.***> writes:

> Yeah, that commit fixed the problem. Thank you for your endurance!

:-) Great, thanks.

> Regards.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.*Message ID: ***@***.***>


-- 
Thierry
