### ISSUE TITLE
Minimal install with straight fails with "Invalid function"

### ISSUE THREAD

**Issue by gcantieni** [emacs-helm/helm#2517]
### What happened?

A minimal install with straight bootstrap code and `(require 'helm)` fails with:
`Invalid function: (binding (car (where-is-internal (quote Control-X-prefix) (list global-map))))`.
I am not sure how using straight factors in, other than that I think it is cloning from the github page instead of melpa.

### How to reproduce?

Config:
```
;; Taken from straight github page
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

;; Install helm
(straight-use-package 'helm)
(require 'helm)
```

### Helm Version

Melpa or NonGnuElpa

### Emacs Version

Emacs-26.3

### OS

Windows

### Relevant backtrace (if possible)

```text
Debugger entered--Lisp error: (invalid-function (binding (car (where-is-internal (quote Control-X-prefix) (list global-map)))))
  (binding (car (where-is-internal (quote Control-X-prefix) (list global-map))))()
  #f(compiled-function () #<bytecode 0x1d46fcd>)()
  funcall(#f(compiled-function () #<bytecode 0x1d46fcd>))
  eval((funcall (function #f(compiled-function () #<bytecode 0x1d46fcd>))))
  custom-initialize-reset(helm-command-prefix-key (funcall (function #f(compiled-function () #<bytecode 0x1d46fcd>))))
  custom-declare-variable(helm-command-prefix-key (funcall (function #f(compiled-function () #<bytecode 0x1d46fcd>))) "The key `helm-command-prefix' is bound to in the global map." :type (choice (string :tag "Key") (const :tag "no binding")) :group helm-config :set #f(compiled-function (var key) #<bytecode 0x1d46fe9>))
  byte-code("\300\301\302\303\304DD\305\306\307\310\311\312\313&\011\207" [custom-declare-variable helm-command-prefix-key funcall function #f(compiled-function () #<bytecode 0x1d46fcd>) "The key `helm-command-prefix' is bound to in the global map." :type (choice (string :tag "Key") (const :tag "no binding")) :group helm-config :set #f(compiled-function (var key) #<bytecode 0x1d46fe9>)] 10)
  require(helm-global-bindings nil t)
  eval-buffer(#<buffer  *load*-752912> nil "c:/Users/gcantieni/AppData/Roaming/.emacs.d/straight/build/helm-core/helm-core.el" nil t)  ; Reading at buffer position 1214
  load-with-code-conversion("c:/Users/gcantieni/AppData/Roaming/.emacs.d/straight/build/helm-core/helm-core.el" "c:/Users/gcantieni/AppData/Roaming/.emacs.d/straight/build/helm-core/helm-core.el" nil t)
  require(helm-core)
  eval-buffer(#<buffer  *load*> nil "c:/Users/gcantieni/AppData/Roaming/.emacs.d/straight/build/helm/helm.el" nil t)  ; Reading at buffer position 1537
  load-with-code-conversion("c:/Users/gcantieni/AppData/Roaming/.emacs.d/straight/build/helm/helm.el" "c:/Users/gcantieni/AppData/Roaming/.emacs.d/straight/build/helm/helm.el" nil t)
  require(helm)
  eval((require (quote helm)) nil)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp
```

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by thierryvolpiatto** [comment]
Gus Cantieni ***@***.***> writes:

> What happened?
>
> A minimal install with straight bootstrap code and (require 'helm) fails with:
> Invalid function: (binding (car (where-is-internal (quote
> Control-X-prefix) (list global-map)))).

Couldn't reproduce this on GNULinux with emacs-28.1, straight is
installing helm properly.

> I am not sure how using straight factors in, other than that I think
> it is cloning from the github page instead of melpa.

Of course it does, it is its purpose.

>
>
> How to reproduce?
>
> Config:
>
> ;; Taken from straight github page
> (defvar bootstrap-version)
> (let ((bootstrap-file
>        (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
>       (bootstrap-version 5))
>   (unless (file-exists-p bootstrap-file)
>     (with-current-buffer
>         (url-retrieve-synchronously
>          "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
>          'silent 'inhibit-cookies)
>       (goto-char (point-max))
>       (eval-print-last-sexp)))
>   (load bootstrap-file nil 'nomessage))
>
> ;; Install helm
> (straight-use-package 'helm)
> (require 'helm)
  ^^^^^^^^^^^^^^^
You don't need this, straight-use-package already did it for you.

I have no idea why you have this error, perhaps you should open an issue
on straight?


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Gus Cantieni ***@***.***> writes:

> What happened?
>
> A minimal install with straight bootstrap code and (require 'helm) fails with:
> Invalid function: (binding (car (where-is-internal (quote
> Control-X-prefix) (list global-map)))).

The only reason I think of is that when-let is not loaded initially by
emacs-26, though the backtrace is unclear about this.
I have commited a fix to prevent this, no guarantee it will fix your
issue, let me know.

> 
> I am not sure how using straight factors in, other than that I think
> it is cloning from the github page instead of melpa.
>
> How to reproduce?
>
> Config:
>
> ;; Taken from straight github page
> (defvar bootstrap-version)
> (let ((bootstrap-file
>        (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
>       (bootstrap-version 5))
>   (unless (file-exists-p bootstrap-file)
>     (with-current-buffer
>         (url-retrieve-synchronously
>          "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
>          'silent 'inhibit-cookies)
>       (goto-char (point-max))
>       (eval-print-last-sexp)))
>   (load bootstrap-file nil 'nomessage))
>
> ;; Install helm
> (straight-use-package 'helm)
> (require 'helm)
>
> Helm Version
>
> Melpa or NonGnuElpa
>
> Emacs Version
>
> Emacs-26.3
>
> OS
>
> Windows
>
> Relevant backtrace (if possible)
>
> Debugger entered--Lisp error: (invalid-function (binding (car (where-is-internal (quote Control-X-prefix) (list global-map)))))
>   (binding (car (where-is-internal (quote Control-X-prefix) (list global-map))))()
>   #f(compiled-function () #<bytecode 0x1d46fcd>)()
>   funcall(#f(compiled-function () #<bytecode 0x1d46fcd>))
>   eval((funcall (function #f(compiled-function () #<bytecode 0x1d46fcd>))))
>   custom-initialize-reset(helm-command-prefix-key (funcall (function #f(compiled-function () #<bytecode 0x1d46fcd>))))
>   custom-declare-variable(helm-command-prefix-key (funcall (function #f(compiled-function () #<bytecode 0x1d46fcd>))) "The key `helm-command-prefix' is bound to in the global map." :type (choice (string :tag "Key") (const :tag "no binding")) :group helm-config :set #f(compiled-function (var key) #<bytecode 0x1d46fe9>))
>   byte-code("\300\301\302\303\304DD\305\306\307\310\311\312\313&\011\207" [custom-declare-variable helm-command-prefix-key funcall function #f(compiled-function () #<bytecode 0x1d46fcd>) "The key `helm-command-prefix' is bound to in the global map." :type (choice (string :tag "Key") (const :tag "no binding")) :group helm-config :set #f(compiled-function (var key) #<bytecode 0x1d46fe9>)] 10)
>   require(helm-global-bindings nil t)
>   eval-buffer(#<buffer  *load*-752912> nil "c:/Users/gcantieni/AppData/Roaming/.emacs.d/straight/build/helm-core/helm-core.el" nil t)  ; Reading at buffer position 1214
>   load-with-code-conversion("c:/Users/gcantieni/AppData/Roaming/.emacs.d/straight/build/helm-core/helm-core.el" "c:/Users/gcantieni/AppData/Roaming/.emacs.d/straight/build/helm-core/helm-core.el" nil t)
>   require(helm-core)
>   eval-buffer(#<buffer  *load*> nil "c:/Users/gcantieni/AppData/Roaming/.emacs.d/straight/build/helm/helm.el" nil t)  ; Reading at buffer position 1537
>   load-with-code-conversion("c:/Users/gcantieni/AppData/Roaming/.emacs.d/straight/build/helm/helm.el" "c:/Users/gcantieni/AppData/Roaming/.emacs.d/straight/build/helm/helm.el" nil t)
>   require(helm)
>   eval((require (quote helm)) nil)
>   elisp--eval-last-sexp(nil)
>   eval-last-sexp(nil)
>   funcall-interactively(eval-last-sexp nil)
>   call-interactively(eval-last-sexp nil nil)
>   command-execute(eval-last-sexp
>
> Minimal configuration
>
>   • [*] I agree using a minimal configuration
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.*Message ID: ***@***.***>


-- 
Thierry
