### ISSUE TITLE
helm-dir-smart-do-search erroring with "option ignore is ambigous"

### ISSUE THREAD

**Issue by triccare** [emacs-helm/helm#2521]
### What happened?

In a dired buffer, execute the command

M-x helm-dir-smart-do-search

The `pattern` comes up but when typing in a pattern, the search results just fill with the message

Option ignore is ambigous (ignore-case, ignore-dirs)

### How to reproduce?

As described above.

1. Create a dired buffer
2. M-x helm-dir-smart-do-search
3. At `pattern` start entering the search term

Other relevant information:

- Using under spacemacs
- Buffer mode line for the search results: HELM AG: Using ack
- Significant change: Configuration worked fine under macOS Catalina. This started happening after upgrading to macOS Monterey.

And apologies, but not using the minimal configuration, so I am lying in the checkbox below. Will attempt in the near future but wanted to file this in case something immediate was clear.

### Helm Version

Melpa or NonGnuElpa

### Emacs Version

Emacs-28/29

### OS

MacOSX

### Relevant backtrace (if possible)

```text
not applicable
```

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by thierryvolpiatto** [comment]
triccare ***@***.***> writes:

> What happened?
>
> In a dired buffer, execute the command
>
> M-x helm-dir-smart-do-search

This is not part of Helm, please report to the relevant project
(helm-dir maybe?).

Thanks, closing.

-- 
Thierry
