### ISSUE TITLE
Helm-buffers does not respect buffers that is displayed in other frames

### ISSUE THREAD

**Issue by cpchan** [emacs-helm/helm#2522]
### What happened?

When I press enter on a candidate in helm-buffers, if it is displayed in another frame, I expect that frame to be raised. Instead it just display it in a window in the same frame.

### How to reproduce?

(1) Open helm-buffer
(2) Select a file
(3) Press enter

### Helm Version

Master branch

### Emacs Version

Emacs-28/29

### OS

GNU/Linux

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by thierryvolpiatto** [comment]
cpchan ***@***.***> writes:

> What happened?
>
> When I press enter on a candidate in helm-buffers, if it is displayed
> in another frame,

It is not, at least with RET, if it does, it is you are not using
default configuration.

> I expect that frame to be raised. Instead it just display it in a
> window in the same frame.

So you say that the buffer is displayed in another frame, but it seems
the buffer is displayed on the same frame in a window, what is the "same frame"?

> How to reproduce?
>
> (1) Open helm-buffer
What is helm-buffer ?
Which command please.

> (2) Select a file
It is not a file but a buffer you want to display.

> (3) Press enter
>
> Helm Version
>
> Master branch
>
> Emacs Version
>
> Emacs-28/29
>
> OS
>
> GNU/Linux
>
> Relevant backtrace (if possible)
>
> No response
>
> Minimal configuration
>
>   • [*] I agree using a minimal configuration
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.*Message ID: ***@***.***>


-- 
Thierry

**Comment by cpchan** [comment]
> What is helm-buffer ? Which command please.

The candidates from helm-source-buffers-list in helm-mini.

> (2) Select a file
> It is not a file but a buffer you want to display.

Yes, I misspoke.

Let me give you an example:

(1) I have "File X" displayed in a buffer in "Frame A".
(2) I invoke helm-mini and select "File X" to switch to that buffer with "enter" while in another frame (let's call it "Frame B").
(3) I would expect "Frame A" to be raise, rather then the buffer opening up in "Frame B".

**Comment by cpchan** [comment]
Thanks. After switching the default action to "helm-buffers-maybe-raise-buffer-frame", everything is working well.

**Comment by thierryvolpiatto** [comment]
cpchan ***@***.***> writes:

>     What is helm-buffer ? Which command please.
>    
> The candidates from helm-source-buffers-list in helm-mini.
>
>     (2) Select a file
>     It is not a file but a buffer you want to display.
>    
> Yes, I misspoke.
>
> Let me give you an example:
>
> (1) I have "File X" displayed in a buffer in "Frame A".
> (2) I invoke helm-mini and select "File X" to switch to that buffer with "enter" while in another frame (let's call it "Frame B").
> (3) I would expect "Frame A" to be raise, rather then the buffer opening up in "Frame B".

Thanks for the recipe.
This is not what one wants to do, you want generally to get the buffer
where you are, so I will not implement this in default action
(i.e. RET), however I added a new action to raise frame handling buffer
for you, have a look ("Raise buffer frame maybe").

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.*Message ID: ***@***.***>


-- 
Thierry
