### ISSUE TITLE
Helm Occur: keep closest position broken

### ISSUE THREAD

**Issue by sh-ow** [emacs-helm/helm#2526]
### What happened?

Although `helm-occur-keep-closest-position` is set to t, `helm-occur` is preselecting the first matching candidate in the file and not the one that is nearest to point.

This (faulty) behaviour was introduced by commit 187e358493a598607d11648d76c92850bc9d69f3

### How to reproduce?

Invoke `helm-occur`, enter some string and it will preselect the first matching candidate in the file.

### Helm Version

Master branch

### Emacs Version

Emacs-28/29

### OS

GNU/Linux

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by thierryvolpiatto** [comment]
sh-ow ***@***.***> writes:

> What happened?
>
> Although helm-occur-keep-closest-position is set to t, helm-occur is preselecting the first matching candidate in the file and not the one that is nearest to point.
>
> This (faulty) behaviour was introduced by commit 187e358

Indeed, I have reverted this commit, I will try to make a better fix
later.
Thanks.

> How to reproduce?
>
> Invoke helm-occur, enter some string and it will preselect the first matching candidate in the file.
>
> Helm Version
>
> Master branch
>
> Emacs Version
>
> Emacs-28/29
>
> OS
>
> GNU/Linux
>
> Relevant backtrace (if possible)
>
> No response
>
> Minimal configuration
>
>   • [*] I agree using a minimal configuration
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.*Message ID: ***@***.***>


-- 
Thierry

**Comment by sh-ow** [comment]
Your fix is working for me, thanks @thierryvolpiatto
