### ISSUE TITLE
stll show known hosts after inputting user in find file minibuffer

### ISSUE THREAD

**Issue by maggo007** [emacs-helm/helm#2528]
### Suggestion

helm-find-file is not showing knowns servers as soon as a username is used

### Description

When trying to connect to an server via ssh i normally input the following in the minibuffer with helm-find-file
`/ssh:` as soon as I input the colon the server from the ssh known_hosts file and even the ssh config entries are shown. The problem is that as soon as I type and try to connect to a server with a specific username `/ssh:user@` there are no known servers shown anymore. 

### Solutions

When using a specific user to connect it would be nice to show the known hosts again as soon as I input the `@`.

**Comment by thierryvolpiatto** [comment]
maggo007 ***@***.***> writes:

> Suggestion
>
> helm-find-file is not showing knowns servers as soon as a username is used
>
> Description
>
> When trying to connect to an server via ssh i normally input the following in the minibuffer with helm-find-file
> /ssh: as soon as I input the colon the server from the ssh known_hosts file and even the ssh config entries are shown. The problem is that as soon as I type and try to connect to a server
> with a specific username /ssh:user@ there are no known servers shown anymore.

You can fix this by specifying another host in your ssh config file
(~/.ssh/config), something like this:

host foo
port 22
user john
hostname 192.168.0.12

host bar
port 22
user jack
hostname 192.168.0.12

Then you can connect with /ssh:foo: or /ssh:bar:

Therefore I will not try to fix this which would be a lot of work for a
small benefit.

Thanks.


-- 
Thierry
