### ISSUE TITLE
unable to bind `C-k`

### ISSUE THREAD

**Issue by foosinn** [emacs-helm/helm#2531]
### What happened?

After configuring C-[hjkl] movements C-k does not work

### How to reproduce?

Configuration:

```el
(use-package helm :ensure t
  :bind (
    ([remap apropos] . helm-apropos)
    ([remap find-library] . helm-locate-library)
    ([remap bookmark-jump] . helm-bookmarks)
    ([remap execute-extended-command] . helm-M-x)
    ([remap find-file] . helm-find-files)
    ([remap imenu-anywhere] . helm-imenu-anywhere)
    ([remap imenu] . helm-semantic-or-imenu)
    ([remap noop-show-kill-ring] . helm-show-kill-ring)
    ([remap persp-switch-to-buffer] . helm-mini)
    ([remap switch-to-buffer] . helm-buffers-list)
    ([remap projectile-find-file] . helm-projectile-find-file)
    ([remap projectile-recentf] . helm-projectile-recentf)
    ([remap projectile-switch-project] . helm-projectile-switch-project)
    ([remap projectile-switch-to-buffer] . helm-projectile-switch-to-buffer)
    ([remap recentf-open-files] . helm-recentf)
    :map helm-map
    ("C-k" . helm-previous-line)
    ("C-j" . helm-next-line)
    ("C-p" . helm-previous-line)
    ("C-n" . helm-next-line)
    ("C-h" . helm-find-files-up-one-level)
    ("C-l" . helm-ff-RET)
    ("C-v" . evil-paste-from-register)
    ("ESC" . abort-recursive-edit))

```

### Helm Version

Melpa or NonGnuElpa

### Emacs Version

Emacs-28/29

### OS

GNU/Linux

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by thierryvolpiatto** [comment]
foosinn ***@***.***> writes:

> What happened?
>
> After configuring C-[hjkl] movements C-k does not work
>
> How to reproduce?
>
> Configuration:
>
> (use-package helm :ensure t
>   :bind (
>     ([remap apropos] . helm-apropos)
>     ([remap find-library] . helm-locate-library)
>     ([remap bookmark-jump] . helm-bookmarks)
>     ([remap execute-extended-command] . helm-M-x)
>     ([remap find-file] . helm-find-files)
>     ([remap imenu-anywhere] . helm-imenu-anywhere)
>     ([remap imenu] . helm-semantic-or-imenu)
>     ([remap noop-show-kill-ring] . helm-show-kill-ring)
>     ([remap persp-switch-to-buffer] . helm-mini)
>     ([remap switch-to-buffer] . helm-buffers-list)
>     ([remap projectile-find-file] . helm-projectile-find-file)
>     ([remap projectile-recentf] . helm-projectile-recentf)
>     ([remap projectile-switch-project] . helm-projectile-switch-project)
>     ([remap projectile-switch-to-buffer] . helm-projectile-switch-to-buffer)
>     ([remap recentf-open-files] . helm-recentf)
>     :map helm-map
>     ("C-k" . helm-previous-line)
>     ("C-j" . helm-next-line)
>     ("C-p" . helm-previous-line)
>     ("C-n" . helm-next-line)
>     ("C-h" . helm-find-files-up-one-level)
>     ("C-l" . helm-ff-RET)
>     ("C-v" . evil-paste-from-register)
>     ("ESC" . abort-recursive-edit))

1) emacs-helm.sh (or just helm if build from source)

2) Eval

  (define-key helm-map (kbd "C-k") nil)
  (define-key helm-map (kbd "C-k") 'helm-previous-line)

Now C-k runs helm-previous-line.

> Minimal configuration
>
>   • [*] I agree using a minimal configuration

You are not using a minimal configuration.


-- 
Thierry

**Comment by foosinn** [comment]
you are 100% right, evil was messing with the keybindings. in anyone else runs into this issue:

```el
(use-package evil :ensure t
  ; [...]
  :config
  (evil-mode 1)
  (define-key evil-insert-state-map (kbd "C-k") nil)
```

`evil-insert-state-map` overwrites the keybinding.

> You are not using a minimal configuration.

sorry misunderstood that. thought this was about doom and spacemacs. still you helped me understand what was going on, thanks!
