### ISSUE TITLE
Minibuffer completion is broken (set to ignore)

### ISSUE THREAD

**Issue by root42** [emacs-helm/helm#2533]
### What happened?

Since a couple of days minibuffer completion for ordinary interactive function execution is broken. I fired up the minibuffer with M-x, and then hit C-h d TAB to see what it is bound to:

```
TAB (translated from <tab>) runs the command minibuffer-complete
(found in minibuffer-local-must-match-map), which is an alias for
‘ignore’ in
‘/snap/emacs/1620/usr/share/emacs/28.1/lisp/minibuffer.el’.

It is bound to TAB, <menu-bar> <minibuf> <tab>.

(minibuffer-complete &rest ARGUMENTS)

Do nothing and return nil.
This function accepts any number of ARGUMENTS, but ignores them.
Also see ‘always’.
```

This is obviously not the usual `minibuffer-complete` function...

### How to reproduce?

Using Emacs 28.1 and latest MELPA helm, type M-x TAB TAB. It will produce no results, as TAB is mapped to minibuffer-complete, which in turn has been aliased to ignore.

### Helm Version

Melpa or NonGnuElpa

### Emacs Version

Emacs-28/29

### OS

GNU/Linux

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by root42** [comment]
PS: SPC still works and will complete the next part! So it is definitely TAB that is broken due to the alias.

**Comment by thierryvolpiatto** [comment]
root42 ***@***.***> writes:

> What happened?
>
> Since a couple of days minibuffer completion for ordinary interactive
> function execution is broken. I fired up the minibuffer with M-x, and
> then hit C-h d TAB to see what it is bound to:

Should be fixed by 7c2f0806.

Thanks to catch this.

-- 
Thierry

**Comment by root42** [comment]
I copied the new helm-mode.el over to my elpa installation, restarted Emacs, and it works. Thanks for fixing it!

**Comment by thierryvolpiatto** [comment]
root42 ***@***.***> writes:

> I copied the new helm-mode.el over to my elpa installation, restarted
> Emacs, and it works.

Great, thanks to confirm.
BTW You have better time using helm-M-x instead of
execute-extended-command (M-x) but you may already know this ;-).

-- 
Thierry

**Comment by root42** [comment]
No I didn’t! Since it doesn’t seem to be default, I didn’t know it existed. I am basically using helm in default configuration.

**Comment by thierryvolpiatto** [comment]
root42 ***@***.***> writes:

> No I didn’t! Since it doesn’t seem to be default, I didn’t know it
> existed. I am basically using helm in default configuration.

Ok. So you have many commands you should use instead of the generic ones
provided by helm-mode.

C-x C-f is find-file, bind it to helm-find-files.
M-x is execute-extended-command bind it to helm-M-x.
C-x C-b is list-buffers, bind it to helm-mini or helm-buffers-list.
occur vs helm-occur
etc...

See "Helm functions vs helmized Emacs functions" in Helm documentation
(C-h m from any helm session).

-- 
Thierry

**Comment by root42** [comment]
Thanks. I was already using helm-find-file. Very useful.
