### ISSUE TITLE
integration with helm-org-rifle broken with commit 202a701

### ISSUE THREAD

**Issue by PalaceChan** [emacs-helm/helm#2537]
### What happened?

[This commit](https://github.com/emacs-helm/helm/commit/202a70168ff9afb03f6d540fce9aa9424b489d67) on this [line](https://github.com/emacs-helm/helm/blob/master/helm-core.el#L3711) breaks integration with [helm-org-rifle](https://github.com/alphapapa/org-rifle/blob/master/helm-org-rifle.el) as it no longer handles the case of `hv` being a `list` as the previous commit did

### How to reproduce?

This suffices to reproduce:

```
(package-initialize)
(require 'helm)
(require 'helm-org-rifle)
(helm-org-rifle-org-directory)
```
and this implementation of `helm--run-init-hooks` is one of many ways to potentially fix (not sure whether the older code with `cl-gensym sname` was also trying to handle lists?)

```
(defun helm--run-init-hooks (hook sources)
  "Run after and before init hooks local to source.
See :after-init-hook and :before-init-hook in `helm-source'."
  (cl-loop for s in sources
           for hv = (assoc-default hook s)
           do (cl-typecase hv
                (function (funcall hv))
                (list (when (= (length hv) 1) (funcall (car hv))))
                (t (helm-log-run-hook hv)))))
```

### Helm Version

Melpa or NonGnuElpa

### Emacs Version

Emacs-28/29

### OS

GNU/Linux

### Relevant backtrace (if possible)

```text
Debugger entered--Lisp error: (invalid-function (helm-org-rifle-set-input-idle-delay))
  (helm-org-rifle-set-input-idle-delay)()
  funcall((helm-org-rifle-set-input-idle-delay))
...
```

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by PalaceChan** [comment]
I'm not sure how many packages besides `helm-org-rifle` may fall under this case but if this is a serious misuse of helm hooks in `helm-org-rifle` itself then happy to help try and debug `helm-org-rifle` as well (assuming that @alphapapa is willing to accept such a fix vs freeze further development of `helm-org-rifle` given existence of the newer `org-ql`...)

**Comment by thierryvolpiatto** [comment]
Palace ***@***.***> writes:

> I'm not sure how many packages besides helm-org-rifle may fall under
> this case but if this is a serious misuse of helm hooks in
> helm-org-rifle

The hook should be quoted:

  (let ((source (helm-build-sync-source (buffer-name buffer)
                  :after-init-hook helm-org-rifle-after-init-hook
                                   ^
Hence the error.

-- 
Thierry

**Comment by PalaceChan** [comment]
interesting, thanks for pointing that out - i can test that change to helm-org-rifle against current and older helm tomorrow

**Comment by thierryvolpiatto** [comment]
Palace ***@***.***> writes:

> interesting, thanks for pointing that out - i can test that change to
> helm-org-rifle against current and older helm tomorrow

Thanks, @alphapapa is seriously maintaining his packages and should have
no problems with such a change.

Problem is with unmaintained packages like helm-projectile, when
something change upstream the package is broken forever.

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.*Message ID: ***@***.***>


-- 
Thierry

**Comment by PalaceChan** [comment]
can confirm that simply quoting the hook in `helm-org-rifle` works on all three `helm--run-init-hooks` - i.e. the old one, the one in this issue, and the latest from master (`00bf87a6 Allow usage of list as value for before/after-init-hooks`). Whereas the unquoted use only works on the old one and the latest from master. I deleted the PR and think this issue can be closed.

**Comment by thierryvolpiatto** [comment]
Palace ***@***.***> writes:

> can confirm that simply quoting the hook in helm-org-rifle works on
> all three helm--run-init-hooks - i.e. the old one, the one in this
> issue, and the latest from master (00bf87a6 Allow usage of list as
> value for before/after-init-hooks). Whereas the unquoted use only
> works on the old one and the latest from master. I deleted the PR and
> think this issue can be closed.

Great, thanks to confirm.

-- 
Thierry

**Comment by alphapapa** [comment]
As Thierry said, I would be glad to add this fix to helm-org-rifle if it were necessary, but since the fix was reapplied to Helm, it appears that it's not.

Thanks to both of you.

**Comment by thierryvolpiatto** [comment]
Hello Adam,

Adam Porter ***@***.***> writes:

> As Thierry said, I would be glad to add this fix to helm-org-rifle if
> it were necessary, but since the fix was reapplied to Helm, it appears
> that it's not.

You can make the change anyway, the advantage is if one modify the
customizable hook the change will appear without the need to rebuild the
source.

Thanks.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Palace ***@***.***> writes:

> What happened?
>
> This commit on this line breaks integration with helm-org-rifle as it
> no longer handles the case of hv being a list as the previous commit

The problem is as soon you don't define rules, one will define the hook
as a lambda, the other with a list, another one with a list of lambdas,
a symbol...
I tried in these recent commits to make it more strict, but people of
helm-projectile was not happy (they use a lambda), now @alphapapa use a
defcustom for its hook, that's fine but instead of giving the hook to
helm he gives the value which is wrong.

So what helm--run-init-hooks supports actually is:

- A hook, that is a symbol bound to a list of function(s).
- A lambda to please helm-projectile people (see #2534).

I think it is enough, if one want to quickly add a lambda it will work,
otherwise a real hook will work as expected.

What you propose in your PR is fine but will encourage people to add
anything to these slots.

The correct use of these hooks is with:

(defvar hook nil)
(add-hook 'hook #'foo)
([...] :before-init-hook 'hook [...])

or like @alphapapa did in helm-org-rifle but don't forget to quote the
hook (see run-hooks docstring).

Thanks.

-- 
Thierry
