### ISSUE TITLE
helm-find-files of /tmp on macOS does not work properly

### ISSUE THREAD

**Issue by pedz** [emacs-helm/helm#2542]
### What happened?

I have helm-find-files bound to C-x C-f.  If I do a helm-find-files of /tmp on a Mac, it does not find all of the files in that directory.  On a Mac, /tmp is actually a symbolic link to private/tmp.  If I do a find file on /private/tmp then I see all of the files.

### How to reproduce?

In the process of doing this with the minimal configuration I determined that it has nothing to do with /tmp but the fact that /tmp is a symbolic link.  I created real directories ~/Desktop/Dog/tmp and then a symbolic link ~/Desktop/tmp pointing to Dog/tmp and I get the same issues.  If I do a helm find files via the symbolic link, I see all of the files.  Then if I create a new file outside of Emacs and repeat the find files, I can't see the new file.  I know there is a cache somewhere but I can't figure out how to refresh it.  My guess is you are taking the time stamp from the symbolic link which isn't changing instead of taking the time stamp from the actual real directory.

More experimenting as I write this.  If I delete the symbolic link and recreate it, the timestamp of the link itself updates.  Then a helm find files sees the new files (i.e. it must refresh its cache).

### Helm Version

Melpa or NonGnuElpa

### Emacs Version

Emacs-28/29

### OS

MacOSX

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by thierryvolpiatto** [comment]
Perry Smith ***@***.***> writes:

> What happened?
>
> I have helm-find-files bound to C-x C-f. If I do a helm-find-files of
> /tmp on a Mac, it does not find all of the files in that directory. On
> a Mac, /tmp is actually a symbolic link to private/tmp. If I do a find
> file on /private/tmp then I see all of the files.

Hmm, can't reproduce this on GNU/Linux (I have many directories
symlinked from Dropbox).

> How to reproduce?
>
> In the process of doing this with the minimal configuration I
> determined that it has nothing to do with /tmp but the fact that /tmp
> is a symbolic link. I created real directories ~/Desktop /Dog/tmp and
> then a symbolic link ~/Desktop/tmp pointing to Dog/tmp and I get the
> same issues. If I do a helm find files via the symbolic link, I see
> all of the files. Then if I create a new file outside of Emacs and
> repeat the find files, I can't see the new file. I know there is a
> cache somewhere but I can't figure out how to refresh it.

C-c C-u

> My guess is you are taking the time stamp from the symbolic link which
> isn't changing instead of taking the time stamp from the actual real
> directory.

No, helm-find-files uses file-notify.el, on GNU/Linux, it uses as
backend inotify, on Mac don't know and I guess this is the thing which
is not working properly.  Unfortunately I have no access to a Mac to
try.

> More experimenting as I write this. If I delete the symbolic link and
> recreate it, the timestamp of the link itself updates. Then a helm
> find files sees the new files (i.e. it must refresh its cache).

Yes, in this case helm refresh the cache, so this may confirm it is
file-notify which fail to notify changes on symlinks.

Here it is working as expected:

I have a directory ~/elisp which is a symlink of ~/Dropbox/elisp
If I touch a file toto.txt from outside emacs in either ~/Dropbox/elisp
or ~/elisp, then back to emacs and C-x C-f => ~/elisp and toto.txt is here.

Can you reproduce the bug on a stable emacs e.g. 28.1?

-- 
Thierry

**Comment by pedz** [comment]
I'm using emacs 28.1 that I built myself.  C-c C-u works!  I will explore file-notify and see if I can come up with a useful test case for the emacs maintainers and then submit a bug report to them.

I'm glad C-c C-u works.  But once I figured out what was happening, doing a find file on the real path wasn't too painful.

**Comment by pedz** [comment]
I filed an [Emacs bug report](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=57536)

**Comment by thierryvolpiatto** [comment]
Perry Smith ***@***.***> writes:

> I filed an Emacs bug report

Great thanks.

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.*Message ID: ***@***.***>


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Now the situation is even worst because inotify does not follow anymore symlinks in emacs-29, this is a big regression for Linux+emacs users.
I made an attempt to fix this from Helm, @pedz have a try.
Thanks.

**Comment by pedz** [comment]
It appears to work for  me.  Sorry to be a pain.

Thank you for the change.

**Comment by thierryvolpiatto** [comment]
Perry Smith ***@***.***> writes:

> It appears to work for me. Sorry to be a pain.

No problems you are welcome.

> Thank you for the change.

Great, thanks for testing.

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you modified the open/close state.*Message ID: ***@***.***>


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Works as well for me in GNU/Linux on emacs-28.1/28.2, and on emacs-29 which is no more following symlinks with Inotify backend.
