### ISSUE TITLE
helm follow mode only works on images for helm-find-files

### ISSUE THREAD

**Issue by julia23m** [emacs-helm/helm#2546]
### What happened?

If I try helm-follow mode for helm-find-files, it works only for images.

### How to reproduce?

I used an empty `.emacs.d` and put the following init `init.el` in it:

```
(require 'package)

(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
```
Then I updated the package list and installed helm via package manager (`package-list-packages`). 

Then I added the following two lines to `init.el`

```
(require 'helm)
(helm-mode 1)
```
and restarted emacs.

Then I call `helm-find-files` and try to activate follow mode by `C-c C-f`. After that a `(HF)` occurs in the status line, but the selected (text-)file doesn't preview in another buffer and if I move up and down with the arrow keys nothing happens other than the `(HF)` indicator dissapears and selection inside the helm-buffer moves. Using `C-Up` or `C-Down` doesn't work neither.

If I try it on image files it works as expected.

If I do the same with `helm-find` instead, everything works as expected (also for text files).

### Helm Version

Melpa or NonGnuElpa

### Emacs Version

Emacs-27.1

### OS

GNU/Linux

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by julia23m** [comment]
By searching the commit history, I noticed that this was introduced in 2016 in commit 243761ac8f951c924a7486fc0b2a51e84886c672 to "Prevent error with follow-mode in HFF". What was exactly the problem which was fixed there? Isn't there another fix which makes work helm follow mode on text files as well?

**Comment by thierryvolpiatto** [comment]
julia23m ***@***.***> writes:

> What happened?
>
> If I try helm-follow mode for helm-find-files, it works only for images.

I added a new variable `helm-ff-follow-blacklist-file-exts` which allows
to control this.
So now images files and all other files that have not their extension
member of `helm-ff-follow-blacklist-file-exts` are allowed.
Directories are not allowed.
 
Thanks for your bugreport.

-- 
Thierry
