### ISSUE TITLE
Lisp error: rgrep results in "wrong-type-argument characterp" error

### ISSUE THREAD

**Issue by ChrisHacker** [emacs-helm/helm#2547]
### What happened?

![image](https://user-images.githubusercontent.com/2028238/189266334-f5786553-4816-47bc-ba96-45763c7185f8.png)

M-x rgrep with search value of "test" throws error. Ran with debugger starting on error and generated the above. 

Expected recursive grep results. Hasn't worked for past two weeks approximately. Using Prelude in emacs.

### How to reproduce?

- M-x rgrep
- enter any string and hit enter
- error

### Helm Version

Melpa or NonGnuElpa

### Emacs Version

Emacs-26.3

### OS

GNU/Linux

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by thierryvolpiatto** [comment]
Chris ***@***.***> writes:

> What happened?
>
> image   
>
> M-x rgrep with search value of "test" throws error. Ran with debugger
> starting on error and generated the above.

You are on the wrong place, rgrep is not part of Helm.

-- 
Thierry

**Comment by michael-heerdegen** [comment]
Maybe he is not: rgrep is in Emacs, and that error only happens with helm-mode enabled.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen ***@***.***> writes:

> Maybe he is not: rgrep is in Emacs, and that error only happens with helm-mode enabled.

Ah ok didn't even remember this emacs command...
The problem comes apparently from `grep-read-files` which uses a
completing-read with `read-file-name-internal` as collection, which is a
pain to fix.  I will see what I can do otherwise use (rgrep . nil) in
`helm-completing-read-handlers-alist`.

Thanks.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen ***@***.***> writes:

> Maybe he is not: rgrep is in Emacs, and that error only happens with helm-mode enabled.

Should be fixed now.

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.*Message ID: ***@***.***>


-- 
Thierry

**Comment by michael-heerdegen** [comment]
Thanks - works well for me.

**Comment by ChrisHacker** [comment]
Thanks much!
