### ISSUE TITLE
TAB filename completion doesn't work running sftp inside eshell

### ISSUE THREAD

**Issue by rhstanton** [emacs-helm/helm#2554]
### What happened?

Using eshell in Emacs 28.2 running under MacOS 12.6, I have TAB bound to **helm-esh-pcomplete**. File and directory completion mostly works fine, except when I'm running sftp. At a bash prompt, the TAB key causes sftp to autocomplete file/directory names. Running sftp inside eshell instead, when I press TAB the cursor just moves forward to the next tab stop and I get the Emacs error:

> Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
>   replace-regexp-in-string("\\`\\*" "" nil)
>   helm-esh-pcomplete()
>   funcall-interactively(helm-esh-pcomplete)
>   command-execute(helm-esh-pcomplete)

Since autocompletion in sftp is rather useful, It would be great if someone could suggest a way around this. 

Thanks.

Richard Stanton

### How to reproduce?

At eshell prompt, run command
`
sftp <hostname>
`
Then type 
`
cd_ 
`
where I'm using underscore here to represent a space, and then press the TAB key.

### Helm Version

Melpa or NonGnuElpa

### Emacs Version

Emacs-28/29

### OS

MacOSX

### Relevant backtrace (if possible)

```text
Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
  replace-regexp-in-string("\\`\\*" "" nil)
  helm-esh-pcomplete()
  funcall-interactively(helm-esh-pcomplete)
  command-execute(helm-esh-pcomplete)
```

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by thierryvolpiatto** [comment]
rhstanton ***@***.***> writes:

> What happened?
>
> Using eshell in Emacs 28.2 running under MacOS 12.6, I have TAB bound
> to helm-esh-pcomplete. File and directory completion mostly works
> fine, except when I'm running sftp.

Do you have completion from emacs -Q?

-- 
Thierry

**Comment by rhstanton** [comment]
No. Starting with emacs -Q, when I type "cd " then Tab, I get

`
Warning: pcomplete-completions-at-point failed to return valid completion data!
`

**Comment by thierryvolpiatto** [comment]
rhstanton ***@***.***> writes:

> No. Starting with emacs -Q, when I type "cd " then Tab, I get
>
> Warning: pcomplete-completions-at-point failed to return valid completion data!

Thanks to confirm this.
So you can consider sftp is not supported in Eshell, perhaps try Shell
instead of Eshell if you really need sftp.

-- 
Thierry

**Comment by rhstanton** [comment]
That's always a possibility. But I like eshell! is there a way just to disable completion for the sftp command? It does its own completion, so all I really want to do is pass the Tab through to sftp directly.

**Comment by rhstanton** [comment]
This pretty much does what I want:
`
(add-to-list 'eshell-visual-commands "sftp")
`

**Comment by thierryvolpiatto** [comment]
rhstanton ***@***.***> writes:

> That's always a possibility. But I like eshell! is there a way just to
> disable completion for the sftp command? It does its own completion,
> so all I really want to do is pass the Tab through to sftp directly.

What you can try is use bash-completion package and bind it to eshell (it
is what I do here, though I don't use sftp so I am not sure it will
work).  Here my config for this:
https://github.com/thierryvolpiatto/emacs-config/blob/main/init.el#L1540
and here
https://github.com/thierryvolpiatto/emacs-config/blob/main/init.el#L1908

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.*Message ID: ***@***.***>


-- 
Thierry
