### ISSUE TITLE
function definition is void : all-the-icons-octicon when starting R with helm-M-x after using helm-find-files

### ISSUE THREAD

**Issue by vchouraki** [emacs-helm/helm#2562]
### What happened?

I am using ESS to edit R code and launch R processes, as well as Helm.

Recently I noticed that when I open an R file with `helm-find-files`, then start an R process with `helm-M-x R`, the R process does not start and I get the following error : 
`helm-M-x-execute-command: Symbol’s function definition is void: all-the-icons-octicon`
If I start emacs then immediately start the R process with `helm-M-x R` before using `helm-find-files`, it works.
Installing the all-the-icons package solves the issue (even when it is not explicitely declared in the init.el file).

### How to reproduce?

1. outside emacs : install R
2. install helm and ess and setup minimal init.el with both packages (do not install all-the-icons)
3. open an R file using, for example helm-find-files test.R
4. start an R process using helm-M-x R
5. get the error

### Helm Version

Melpa or NonGnuElpa

### Emacs Version

Emacs-28/29

### OS

GNU/Linux

### Relevant backtrace (if possible)

```text
Debugger entered--Lisp error: (void-function all-the-icons-octicon)
  all-the-icons-octicon("file-directory")
  helm-ff-get-icon(#("home/path" 0 17 (face helm-ff-dotted-directory)) "home/path")
  helm-ff-icons-transformer(...)
  apply(helm-ff-icons-transformer (...))
  helm-apply-functions-from-source(...)
  helm-process-filtered-candidate-transformer(...)
  helm-compute-matches(...)
  helm--collect-matches(...)
  helm-update(nil)
  helm-read-from-minibuffer("R starting project directory? " "home/path" nil noresume nil "home/path" nil)
  helm-internal(...)
  apply(...)
  helm(...)
  apply(helm (...))
  helm(...)
  helm-read-file-name("R starting project directory? " :name "run-ess-r" :buffer "*helm-mode-run-ess-r*" :default "home/path" :initial-input "home/path" :alistp nil :nomark t :marked-candidates nil :must-match t :test file-directory-p :noret t)
  helm--generic-read-file-name("R starting project directory? " "home/path" "home/path" t nil file-directory-p)
  apply(helm--generic-read-file-name ("R starting project directory? " "home/path" "home/path" t nil file-directory-p))
  #f(advice helm--generic-read-file-name :override read-file-name-default)("R starting project directory? " "home/path" "home/path" t nil file-directory-p)
  read-file-name("R starting project directory? " "home/path" "home/path" t nil file-directory-p)
  read-directory-name("R starting project directory? " "home/path" "home/path" t nil)
  ess-prompt-for-directory("home/path" "R starting project directory? ")
  inferior-ess--maybe-prompt-startup-directory("R" "R")
  inferior-ess("--no-readline  " (...))
  run-ess-r(nil)
  R(nil)
  funcall-interactively(R nil)
  call-interactively(R record nil)
  command-execute(R record)
  helm-M-x-execute-command(R)
  helm-execute-selection-action-1()
  helm-execute-selection-action()
  helm-internal(...)
  apply(...)
  helm(...)
  apply(...)
  helm(...)
  helm-M-x-read-extended-command([## ess-icon-directory vc-src-responsible-p nov-mimetype-valid-p tramp-sudoedit-file-name-handler tramp-completion-handle-file-name-all-completions bibtex-entry-right-delimiter org-clock-get-sum-start python-nav-beginning-of-defun-regexp vc-sccs-log-view-mode-hook TeX-print-command help-follow-symbol helm-completing-read-inbuffer-default-handler yas-x-prompt cc-vars &error hs-hide-comments-when-hiding-all C-c helm-ff-query-replace-fnames-history-to ess-keyword-face tramp-compat-string-equal-ignore-case edebug-mode-on-hook message-expand-name-databases reftex-untie-multifile-symbols 0 tree-widget-button-keymap traversed search-emacs-glossary :where mu4e-cited-7-face python-syntax--context-compiler-macro vc-annotate tramp-sudoedit-handle-set-file-acl xref--push-markers vc-bzr-shelve-menu About Above org-agenda-regexp-filter-preset vundo-node org-agenda-menu-show-matcher hs-toggle-hiding helm-grep-save-results-1 dired-do-chmod server--on-display-p no-truncate diredfl-symlink xref-group image-dired-list-tags tramp-handle-make-auto-save-file-name helm-debug-output-function ...])
  helm-M-x(nil)
  funcall-interactively(helm-M-x nil)
  call-interactively(helm-M-x nil nil)
  command-execute(helm-M-x)
```

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by thierryvolpiatto** [comment]
vchouraki ***@***.***> writes:

> What happened?
>
> I am using ESS to edit R code and launch R processes, as well as Helm.
>
> Recently I noticed that when I open an R file with helm-find-files, then start an R process with helm-M-x R, the R process does not start and I get the following error :
> helm-M-x-execute-command: Symbol’s function definition is void: all-the-icons-octicon
> If I start emacs then immediately start the R process with helm-M-x R before using helm-find-files, it works.
> Installing the all-the-icons package solves the issue (even when it is not explicitely declared in the init.el file).

It seems you have enabled helm-ff-icon-mode without installing
all-the-icons, then the R command use presumably a read-file-name and
fails. I will try to reproduce and make it failing more gracefully.
I guess that there is no need to use R nor ess to reproduce, just
enabling helm-ff-icon-mode without all-the icons package and call a
read-file-name should suffice.

Thanks, will look at this soon.

-- 
Thierry

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto ***@***.***> writes:

> It seems you have enabled helm-ff-icon-mode without installing
> all-the-icons [...]

FYI: I saw this error once after updating helm (without having enabled
that mode) some days ago.  The issue was gone after restarting Emacs.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen ***@***.***> writes:

> Thierry Volpiatto ***@***.***> writes:
>
>> It seems you have enabled helm-ff-icon-mode without installing
>> all-the-icons [...]
>
> FYI: I saw this error once after updating helm (without having enabled
> that mode) some days ago.

I have no ideas how this could happen without enabling helm-ff-icon-mode.


-- 
Thierry

**Comment by vchouraki** [comment]
I don't think I explicitely activated helm-ff-icon-mode either. I am using emacs-snapshot (29.0.50) on Ubuntu 22.04 and my config file is based on use-package in an org-mode file. The following config is enough to get an error using `helm-find-files` : 
```emacs-lisp
(use-package helm
 :ensure t
 :bind (("C-c h" . helm-command-prefix)
        ("C-x C-f" . helm-find-files)
        ("M-x" . helm-M-x))
 :config
 (helm-mode 1))
```

**Comment by ChrisHacker** [comment]
I just updated helm via the package manager and am now getting "Cannot open load file: No such file or directory, all-the-icons" when I use helm-find-files.

**Comment by ChrisHacker** [comment]
Installing the "all-the-icons" package did resolve the error.

**Comment by michael-heerdegen** [comment]
> I have no ideas how this could happen without enabling helm-ff-icon-mode.

It happened again - directly after updating helm.  `helm-ff-icon-mode` suddenly was `t`.  I didn't touch it.

I have a theory who was touching it though: the custom setter of ` helm-ff-nohighlight-matches` - in particular  the ` (helm-ff-icon-mode helm-ff-icon-mode)` call.  When `helm-ff-icon-mode` is nil, the mode function will toggle the mode, i.e. turn the mode on.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen ***@***.***> writes:

>     I have no ideas how this could happen without enabling helm-ff-icon-mode.
>    
> It happened again - directly after updating helm. helm-ff-icon-mode suddenly was t. I didn't touch it.
>
> I have a theory who was touching it though: the custom setter of
> helm-ff-nohighlight-matches - in particular the (helm-ff-icon-mode
> helm-ff-icon-mode) call. When helm-ff-icon-mode is nil, the mode
> function will toggle the mode, i.e. turn the mode on.

Indeed, thanks to catch this, I pushed a new commit to fix it, let me
know if it works for you.

Thanks.

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.*Message ID: ***@***.***>


-- 
Thierry

**Comment by vchouraki** [comment]
This new commit fixed the issue on my config.

Many thanks.

**Comment by thierryvolpiatto** [comment]
vchouraki ***@***.***> writes:

> This new commit fixed the issue on my config.

Great, thanks to confirm.

> Many thanks.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.*Message ID: ***@***.***>


-- 
Thierry

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto ***@***.***> writes:

> > This new commit fixed the issue on my config.
>
> Great, thanks to confirm.

Last update of Helm was inconspicuous for me as well.  Hopefully the
problem is completely solved.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen ***@***.***> writes:

> Thierry Volpiatto ***@***.***> writes:
>
>> > This new commit fixed the issue on my config.
>>
>> Great, thanks to confirm.
>
> Last update of Helm was inconspicuous for me as well. Hopefully the
> problem is completely solved.

Great, thanks for your help on this.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.*Message ID: ***@***.***>


-- 
Thierry
