### ISSUE TITLE
`helm-config.el` removed but some packages still depend on it

### ISSUE THREAD

**Issue by tarsius** [emacs-helm/helm#2578]
### What happened?

The file `helm-config.el` was removed in e81fbbc687705595ab65ae5cd3bdf93c17a90743.

A few third-party packages still depend on that library.

- [x] `amx` @DarwinAwardWinner
- [ ] `helm-ag-r` @yuutayamada
- [ ] `helm-cmd-t` @lewang
- [ ] `helm-dirset` @k1LoW
- [ ] `helm-git-files` @kenbeese
- [ ] `serverspec` @k1LoW

I am summoning their maintainers to hopefully get this resolved soon.

All but one of these maintainers have very little activity on Github, so it might be a good idea to restore the file for the time being, even if all it does is to require some other helm library (and provide its own feature of course).

### How to reproduce?

Update to the newest version of helm.

### Helm Version

Master branch

### Emacs Version

Emacs-28/29

### OS

GNU/Linux

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by DarwinAwardWinner** [comment]
Hmm, amx is supposed to optionally depend on helm (it's one of the supported completion backends). It should still install and run fine without it, but I'll look into it. (The tests will probably fail though since they test all the backends.)

**Comment by thierryvolpiatto** [comment]
Jonas Bernoulli ***@***.***> writes:

> What happened?
>
> The file helm-config.el was removed in e81fbbc.
>
> A few third-party packages still depend on that library.
>
>   • [ ] amx @DarwinAwardWinner
>   • [ ] helm-ag-r @yuutayamada
>   • [ ] helm-cmd-t @lewang
>   • [ ] helm-dirset @k1LoW
>   • [ ] helm-git-files @kenbeese
>   • [ ] serverspec @k1LoW
>
> I am summoning their maintainers to hopefully get this resolved soon.

    (require 'helm-config) == (require 'helm-autoloads)

And packages do NOT have to load the autoload file of a package,
packages managers are doing it for them on initialization.
If one install Helm from source, she can just (require 'helm-autoloads).

-- 
Thierry

**Comment by 4e6** [comment]
> (require 'helm-config) == (require 'helm-autoloads)

When I do `(require 'helm-autoloads)` the initialization fails with 

```
error: Loading file /home/dbushev/.emacs.d/elpa/helm-20221212.628/helm-autoloads.el failed to provide feature ‘helm-autoloads’
```

**Comment by thierryvolpiatto** [comment]
@tarsius 
> All but one of these maintainers have very little activity on Github, so it might be a good idea to restore the file for the time being, even if all it does is to require some other helm library (and provide its own feature of course).

No, if I restore this, they will never fix it.

**Comment by tarsius** [comment]
> No, if I restore this, they will never fix it.

I haven't realized that this already was a stub of the kind I was suggesting. I agree, at some point you have to remove such kludges and hope for the best. Maybe you have already informed the maintainers at an earlier time, in which case this at least serves as a reminder.

**Comment by thierryvolpiatto** [comment]
If you installed Helm from package, requiring 'helm-config was an error, what you have to do is just remove `(require 'helm-config)` from your init file, that's all.

**Comment by truthdoug** [comment]
Thank you!

**Comment by rkachach** [comment]
ran in the same issue, it would be good to document this somewhere.

**Comment by rkachach** [comment]
> 

Thanks :+1:

**Comment by tarsius** [comment]
> Hmm, amx is supposed to optionally depend on helm (it's one of the supported completion backends). It should still install and run fine without it, but I'll look into it. (The tests will probably fail though since they test all the backends.)

@DarwinAwardWinner The package still compiles and other backends can be used, but if you try to use the `helm` backend, then that fails. If you do that, then an attempt is made to require `helm-config`, but `helm` doesn't provide such a feature anymore. You should require `helm` instead.

**Comment by herop** [comment]
Still, even if I don't use any depending packages and use nowhere "require helm-config", the error thrown by "doom doctor" always is
<snip>
  x There was an unexpected runtime error
    Message: File is missing
    Details: ("Cannot open load file" "No such file or directory" "helm-config")
    Backtrace:
      (require helm-config)
      (load-with-code-conversion "c:/Users
</snip>
WHAT can I do, please help me out here,
Thank you
