### ISSUE TITLE
Helm goes blank  / doesn't list files sometimes when editing remote file ( sftp/scp )

### ISSUE THREAD

**Issue by purplefishies** [emacs-helm/helm#2582]
### What happened?

When I use Tramp to access a file over sftp, helm gets to a point where it won't display any buffers.

Steps: 

- Open Emacs
- Open a remote file
- I opened a few local files
- Do some editing 
- Open connetion to a remote directory
- I killed some buffers 

Then I get into a stuck state

Where if I typed "C-x b"  I get a *helm-mode-switch-to-buffer with  nothing displayed.

Normally I can type "C-x b  TAB" and select from a list of files.

### How to reproduce?

Work with Helm and edit a file using /sftp:user@host:/somefile.txt

Do some work on it save it...then try to edit another file in your buffer list with C-x b 

![image](https://user-images.githubusercontent.com/774106/211098348-68ad8106-9dc4-4a5c-af66-883313fb0180.png)

After Helm gets stuck in this state I can't ever get  back to listing the buffers again.

While using emacs-helm.sh I was able to get back to displaying the buffers again only after I killed the buffer I was in .

### Helm Version

Master branch

### Emacs Version

Emacs-27.1

### OS

GNU/Linux

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by thierryvolpiatto** [comment]
Jimi Damon ***@***.***> writes:

> How to reproduce?
>
> Work with Helm and edit a file using ***@***.***:/somefile.txt
>
> Do some work on it save it...then try to edit another file in your buffer list with C-x b

I couldn't reproduce. However I tried with ssh and scp methods and both
worked fine. Can you reproduce with ssh or scp?
Unfortunately I have no ftp server to work on.

> image   
>
> After Helm gets stuck in this state I can't ever get back to listing the buffers again.


> While using emacs-helm.sh I was able to get back to displaying the buffers again only after I killed the buffer I was in .
>
> Helm Version
>
> Master branch
>
> Emacs Version
>
> Emacs-27.1
>
> OS
>
> GNU/Linux
>
> Relevant backtrace (if possible)
>
> No response
>
> Minimal configuration
>
>   • [*] I agree using a minimal configuration
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.*Message ID: ***@***.***>


-- 
Thierry

**Comment by purplefishies** [comment]
Hi, 

Happens after a while of editing.

I've found a potential work around

I have to type 
```
eval-expression
(list-buffers)
```

Then select a buffer and kill it ( possibly do this a couple of times ) 
 
Then go back into Helm again with C-x b  and it works.

I'm not sure why list-buffers and killing buffers  can help in this situation

**Comment by thierryvolpiatto** [comment]
Can you give me a clear recipe of what you are doing, actually it is
unclear, the "steps" you described and the "how to reproduce" are
different and not precise.

Thanks.

-- 
Thierry

**Comment by purplefishies** [comment]
I'm trying to give you a recipe.  It's a bit of a hard one to get working.

**Comment by purplefishies** [comment]
Hi, honestly, I've switched to using SSHFS now for my connections to a remote machine and I haven't seen any problems using helm.   Sorry for the trouble.

**Comment by thierryvolpiatto** [comment]
Jimi Damon ***@***.***> writes:

> Hi, honestly, I've switched to using SSHFS now for my connections to a
> remote machine and I haven't seen any problems using helm.

Yes, SSHFS is great.

> Sorry for the trouble.

No problems.


-- 
Thierry
