### ISSUE TITLE
dolist does not catch throw

### ISSUE THREAD

**Issue by braineo** [emacs-helm/helm#2584]
### What happened?

when using other helm packages, I get `progn: No catch for tag: --cl-block-nil--`

### How to reproduce?

run `helm-rg`

seems this commit a0f2a47e11fe90b67e384d7d610dd4beed611cfe is causing the issue

`dolist` does not catch like `cl-dolist`. maybe we can `(require 'cl-lib)` and continue using `cl-dolist`? or this is an intended behavior?

```lisp
(defmacro dolist (spec &rest body)
  "Loop over a list.
Evaluate BODY with VAR bound to each car from LIST, in turn.
Then evaluate RESULT to get return value, default nil.

\(fn (VAR LIST [RESULT]) BODY...)"
  (declare (indent 1) (debug ((symbolp form &optional form) body)))
  (unless (consp spec)
    (signal 'wrong-type-argument (list 'consp spec)))
  (unless (<= 2 (length spec) 3)
    (signal 'wrong-number-of-arguments (list '(2 . 3) (length spec))))
  (let ((tail (make-symbol "tail")))
    `(let ((,tail ,(nth 1 spec)))
       (while ,tail
         (let ((,(car spec) (car ,tail)))
           ,@body
           (setq ,tail (cdr ,tail))))
       ,@(cdr (cdr spec)))))
```

### Helm Version

Master branch

### Emacs Version

Emacs-28/29

### OS

GNU/Linux

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by thierryvolpiatto** [comment]
Binbin ***@***.***> writes:

> What happened?
>
> when using other helm packages, I get progn: No catch for tag: --cl-block-nil--
>
> How to reproduce?
>
> run helm-rg
>
> seems this commit a0f2a47 is causing the issue
>
> dolist does not catch like cl-dolist. maybe we can (require 'cl-lib)
> and continue using cl-dolist? or this is an intended behavior?

We do require already cl-dolist.  When swiching to cl-lib from cl.el
some years ago dolist was changed to cl-dolist for no reasons (using a
script), no code in helm is relaying on the cl-dolist features like
cl-block, so I changed recently to dolist.  If helm-rg worked until now
using a cl-return without really ensuring there is a cl-block on top is
a chance.  I will not switch back to cl-dolist without a good reason, I
think it is to helm-rg to adapt itself to the upstream code, adding
itself a cl-block or using cl-loop or using catch/throw or whatever.
Note also that helm itself provide ripgrep feature out of the box
without the need of an external package.


-- 
Thierry

**Comment by braineo** [comment]
Thanks! In that case I'll report to `helm-rg`.

I'm using `helm-projectile` and `helm-projectile` is using `helm-rg`

**Comment by malb** [comment]
I know zilch about Helm internals, so this might be miles off: But is there perhaps a `catch '--cl-block-nil--` missing in `helm-output-filter` ?  If not, where should the throw from `helm-output-filter--process-source` be caught?

**Comment by thierryvolpiatto** [comment]
"Martin R. Albrecht" ***@***.***> writes:

> I know zilch about Helm internals, so this might be miles off: But is
> there perhaps a catch '--cl-block-nil-- missing in helm-output-filter
> ?

You are right, I missed this one, surprisingly, I have here no errors
such as "no catch for..." and no compilation warnings.  So lets reenable
cl-dolist for this one.

Thanks.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Thierry Volpiatto ***@***.***> writes:

> "Martin R. Albrecht" ***@***.***> writes:
>
>> I know zilch about Helm internals, so this might be miles off: But is
>> there perhaps a catch '--cl-block-nil-- missing in helm-output-filter
>> ?
>
> You are right, I missed this one, surprisingly, I have here no errors
> such as "no catch for..."

Ah! The reason is that candidate-number-limit is set locally in
helm-grep so I never reached the limit recently and BTW cl-return never
been called.


-- 
Thierry

**Comment by malb** [comment]
Thanks!

**Comment by projectgus** [comment]
> I'm using helm-projectile and helm-projectile is using helm-rg

FWIW if anyone else is looking around for possible workarounds, it's possible to make a small interactive function that runs `helm-do-grep-ag` in the projectile root rather than using `helm-projectile-rg`. [This is not my code, but it's what I've switched to using](https://github.com/helpshift/emacs-up/blob/8ecce26ea0c0d13aa481e8d0b26257babee5b965/init.el#L235).
