### ISSUE TITLE
Enhancement: Ability to identify shell variables in Helm detect file name feature

### ISSUE THREAD

**Issue by randomwangran** [emacs-helm/helm#2586]
### What happened?

`Helm` can detect a file name at the point. The file name can be an absolute
or relative path. However, it does not have the ability to identify a
shell variable. If you have a path like `$(FOAM_TUTORIAL)/some/path/`
you will not able to find the file correctly.

### How to reproduce?

Call `helm-find-files` under a path string.

Here is what I do to solve this problem:

First setup some constants:

    (setq wr/project-root-path "/PATH/TO/PROJ/")

Now you can \`M-x wr/find-file-in-project-at-point` to find file path
in this case.

    (defun wr/project-root (filename)
      "Return the root directory of the project containing FILENAME."
      (let ((root (file-name-directory filename)))
        (while (and (not (file-exists-p (expand-file-name ".git" root)))
                    (not (equal root (file-truename (file-name-directory (file-name-directory root))))))
          (setq root (file-name-directory (directory-file-name root))))
        (if (file-exists-p (expand-file-name ".git" root))
            root)))
    
    (defun wr/find-file-in-project-at-point (&optional open-another-window)
      "Find file name in a simulation project. Replace root according
    to the location of the current machine."
      (interactive "P")
      (let* ((filename (or
                        (thing-at-point 'filename)
                        (thing-at-point 'symbol)
                        (ffap-file-at-point)))
             (project-root-dir (wr/project-root (buffer-file-name)))
             (ffip-match-path-instead-of-filename t))
        (cond
         (filename
          (setq filename
                (setq wr/test-filename
                      (replace-regexp-in-string "$(FOAM_TUTORIAL)"
                                                (concat wr/project-root-path
                                                        (car (last
                                                              (split-string
                                                               (locate-dominating-file
                                                                (buffer-file-name)
                                                                ".git")
                                                               "/" t))))
                                                filename)))
          (find-file filename))
         (t
          (message "No file name is provided.")))))

### Helm Version

Master branch

### Emacs Version

Emacs-28/29

### OS

GNU/Linux

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by thierryvolpiatto** [comment]
randomwangran ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
> What happened?
>
> Helm can detect a file name at the point. The file name can be an absolute
> or relative path. However, it does not have the ability to identify a
> shell variable. If you have a path like $(FOAM_TUTORIAL)/some/path/
> you will not able to find the file correctly.

This is unclear, what do you expect from $(FOAM_TUTORIAL)/some/path/?
Helm is able to expand e.g. $HOME/download, in your example above, what
is $(FOAM_TUTORIAL)? Why is it enclosed with parenthesis?

In what is this related to the ffap bug mentioned in previous post?

> How to reproduce?
>
> Call helm-find-files under a path string.
>
> Here is what I do to solve this problem:

Which problem? Helm already detect filename at point.
Please give me a concrete example where Helm fails to do so.
(Start from emacs-helm.sh to reproduce).

Thanks.

> First setup some constants:
>
> (setq wr/project-root-path "/PATH/TO/PROJ/")
>
> Now you can `M-x wr/find-file-in-project-at-point` to find file path
> in this case.


> (defun wr/project-root (filename)
>   "Return the root directory of the project containing FILENAME."
>   (let ((root (file-name-directory filename)))
>     (while (and (not (file-exists-p (expand-file-name ".git" root)))
>                 (not (equal root (file-truename (file-name-directory (file-name-directory root))))))
>       (setq root (file-name-directory (directory-file-name root))))
>     (if (file-exists-p (expand-file-name ".git" root))
>         root)))
>
> (defun wr/find-file-in-project-at-point (&optional open-another-window)
>   "Find file name in a simulation project. Replace root according
> to the location of the current machine."
>   (interactive "P")
>   (let* ((filename (or
>                     (thing-at-point 'filename)
>                     (thing-at-point 'symbol)
>                     (ffap-file-at-point)))
>          (project-root-dir (wr/project-root (buffer-file-name)))
>          (ffip-match-path-instead-of-filename t))
>     (cond
>      (filename
>       (setq filename
>             (setq wr/test-filename
>                   (replace-regexp-in-string "$projRoot"
>                                             (concat wr/project-root-path
>                                                     (car (last
>                                                           (split-string
>                                                            (locate-dominating-file
>                                                             (buffer-file-name)
>                                                             ".git")
>                                                            "/" t))))
>                                             filename)))
>       (find-file filename))
>      (t
>       (message "No file name is provided.")))))
>
> Helm Version
>
> Master branch
>
> Emacs Version
>
> Emacs-28/29
>
> OS
>
> GNU/Linux
>
> Relevant backtrace (if possible)
>
> No response
>
> Minimal configuration
>
>   • [*] I agree using a minimal configuration
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.*Message ID: ***@***.***>


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
randomwangran ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
> What happened?
>
> Helm can detect a file name at the point. The file name can be an absolute
> or relative path. However, it does not have the ability to identify a
> shell variable. If you have a path like $(FOAM_TUTORIAL)/some/path/
> you will not able to find the file correctly.
>
> How to reproduce?
>
> Call helm-find-files under a path string.
>
> Here is what I do to solve this problem:

Now looking at your code I don't understand what you want to achieve.

> First setup some constants:
>
> (setq wr/project-root-path "/PATH/TO/PROJ/")

What is this expected to be set to?

> Now you can `M-x wr/find-file-in-project-at-point` to find file path
> in this case.
>
> (defun wr/project-root (filename)
>   "Return the root directory of the project containing FILENAME."
>   (let ((root (file-name-directory filename)))
>     (while (and (not (file-exists-p (expand-file-name ".git" root)))
>                 (not (equal root (file-truename (file-name-directory (file-name-directory root))))))
>       (setq root (file-name-directory (directory-file-name root))))
>     (if (file-exists-p (expand-file-name ".git" root))
>         root)))

This function seems to do more or less the same thing as
locate-dominating-file (but hardcoded to ".git"), thus it is used nowhere in your code.

> (defun wr/find-file-in-project-at-point (&optional open-another-window)
>   "Find file name in a simulation project. Replace root according
> to the location of the current machine."
>   (interactive "P")
>   (let* ((filename (or
>                     (thing-at-point 'filename)
>                     (thing-at-point 'symbol)
>                     (ffap-file-at-point)))
>          (project-root-dir (wr/project-root (buffer-file-name)))

This is used nowhere.

>          (ffip-match-path-instead-of-filename t))

Same (it is used nowhere) what is this for?

>     (cond
>      (filename
>       (setq filename
>             (setq wr/test-filename

What is wr/test-filename? (used nowhere in your code).

>                   (replace-regexp-in-string "$projRoot"

What is "$projRoot" coming from? filename at point?
What do you expect it expand to? wr/project-root-path?

>                                             (concat wr/project-root-path
>                                                     (car (last
>                                                           (split-string
>                                                            (locate-dominating-file
>                                                             (buffer-file-name)
>                                                             ".git")
>                                                            "/" t))))
>                                             filename)))
>       (find-file filename))
>      (t
>       (message "No file name is provided.")))))
>
> Helm Version
>
> Master branch
>
> Emacs Version
>
> Emacs-28/29
>
> OS
>
> GNU/Linux
>
> Relevant backtrace (if possible)
>
> No response
>
> Minimal configuration
>
>   • [*] I agree using a minimal configuration
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.*Message ID: ***@***.***>


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
randomwangran ***@***.***> writes:

> @thierryvolpiatto
>
> I apologize for the confusion caused earlier. After further
> investigation, I discovered that Helm is capable of detecting shell
> variables as long as they are already pass into emacs. A simple
> way to accomplish this is to add the desired variable in the .bashrc
> file.

Yes, these variables are called environment variables, the best place to
set them is in ~/.bash_profile or in ~/.profile.

Also a feature you may not know is that if you paste such env var in
minibuffer after the current path Helm will instantly expand to this
path.

> Thank you for bringing this to my attention and I hope this helps
> clarify the issue.

Thanks to clarify what you want.

> However, what I found in a case where emacs has no idea about the variable.
>
> I've test it with emacs-helm.sh

Good, this prevents many errors and misunderstanding of what is
happening.

> #+begin_src bash
> $VAR_IN_PROJ=/tmp/this_is_a_testing_folder
>
> $VAR_IN_PROJ
> #+end_src
>
> In this case, ‘helm-find-files’ is not able to open path $VAR_IN_PROJ,
> i.e., /tmp/this_is_a_testing_folder.

Indeed, as long as the variable is not added to env vars Helm doesn't
know about it and expand to defaut-directory.

> So, I believe the snippet provided in this issue has this feature to
> go further with helm-find-files.

Perhaps for your very specific var here (related to your project IIUC),
but more generally I guess it will fail to expand your var.  To achieve
this I think one would have to parse the buffer to get the value of the
var, however I don't think it is the purpose of helm-find-files to do
this.  Actually Helm is for example capable of finding the related file
when point is in a require sexp in a lisp buffer (see
helm-ff-search-library-in-sexp), but only if such file has been loaded.

NOTE: things like LSP may know about such var in real time? If true (my
LSP knowledge is very limited) perhaps there is functions in eglot or
lsp-mode that may be used to find such value?

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.*Message ID: ***@***.***>


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Considering a buffer with the example you gave above:

```sh

#!/bin/bash


VAR_IN_PROJ=/tmp/this_is_a_testing_folder

echo $VAR_IN_PROJ
```
If point is at $VAR_IN_PROJ you can get the value with such code:

```elisp
(defun find-shell-var-value-at-point ()
  (let ((tap (substring (thing-at-point 'filename t) 1)))
    (save-excursion
      (goto-char (point-min))
      (when (re-search-forward (format "%s=\\(.*\\)$" tap) nil t)
        (match-string 1)))))
```

**Comment by thierryvolpiatto** [comment]
And of course if the var has been modified several time along the script, this will become wrong, so such code is not reliable apart for simple scripts.
