### ISSUE TITLE
pdfgrep: highlight matches in pdf when using pdf-tools (pdf-view-mode)

### ISSUE THREAD

**Issue by rdiaz02** [emacs-helm/helm#2590]
### Suggestion

When searching in pdfs (helm-find-files, then select pdf(s), then M-g p) matches are highlighted in the helm pdfgrep output buffer. 

If the pdf is then opened using C-j we are taken to the page with the match. But it is not obvious where the match is.

### Description

It would be great if the matching term was highlighted in the PDF itself when pressing `C-j` (like it happens in other helm searches).

### Solutions

The pdfgrep package (https://github.com/jeremy-compostella/pdfgrep) is capable of this. I know of no other alternatives.

**Comment by thierryvolpiatto** [comment]
Ramon Diaz-Uriarte ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
> Suggestion
>
> When searching in pdfs (helm-find-files, then select pdf(s), then M-g p) matches are highlighted in the helm pdfgrep output buffer.
>
> If the pdf is then opened using C-j we are taken to the page with the match. But it is not obvious where the match is.
>
> Description
>
> It would be great if the matching term was highlighted in the PDF itself when pressing C-j (like it happens in other helm searches).
>
> Solutions
>
> The pdfgrep package (https://github.com/jeremy-compostella/pdfgrep) is capable of this. I know of no other alternatives.

Sorry, but to implement this I would have to look (and learn) pdf-tools
and the pdfgrep you mentioned above. I don't use personaly these tools
and have no motivation to work on this, thus I don't want to depend on
such tools in Helm.

Thanks for your understanding.


> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.*Message ID: ***@***.***>


-- 
Thierry

**Comment by rdiaz02** [comment]
Thanks a lot for your reply. And of course, I understand the answer. Closing this.
