### ISSUE TITLE
helm-grep not support selection as input pattern.

### ISSUE THREAD

**Issue by zw963** [emacs-helm/helm#2591]
### What happened?

e.g. i want search `grep-git` use helm-grep, so i set a mark, select and mark it, like following screenshot.

![image](https://user-images.githubusercontent.com/549126/227709779-ccdfd4bc-b568-4872-8a4b-3cea05046bdf.png)

When i do helm-grep-do-git-grep, it always use current symbol as selection and ignore my highlight region.(check following screenshot)

![image](https://user-images.githubusercontent.com/549126/227709857-fe3410c8-7a2e-480d-81f3-1a8a3d47776c.png)

What i expected is use `grep-git` as pattern instead of it use symbol under the cursor (it is helm-git-grep-1 for current case) as pattern.

I consider this feature should always prefer to use highlighted region if region is active, as does in [helm-ag](https://github.com/emacsorphanage/helm-ag/blob/master/helm-ag.el#L1321-L1322) or [helm-git-grep](https://github.com/yasuyk/helm-git-grep/blob/master/helm-git-grep.el#L466-L469)

Thanks

### How to reproduce?

as above

### Helm Version

Master branch

### Emacs Version

Emacs-28/29

### OS

GNU/Linux

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by thierryvolpiatto** [comment]
"Billy.Zheng" ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
> What happened?
>
> e.g. i want search grep-git use helm-grep, so i set a mark, select and mark it, like following screenshot.
>
> image   
>
> When i do helm-grep-do-git-grep, it always use current symbol as selection and ignore my highlight region.(check following screenshot)
>
> image   
>
> What i expected is use grep-git as pattern instead of it use symbol under the cursor (it is helm-git-grep-1 for current case) as pattern.
>
> I consider this feature should always prefer to use highlighted region if region is active, as does in helm-ag or helm-git-grep

helm-grep-git-1 have a INPUT argument, you can easily create your own
function using it.

> Thanks
>
> How to reproduce?
>
> as above
>
> Helm Version
>
> Master branch
>
> Emacs Version
>
> Emacs-28/29
>
> OS
>
> GNU/Linux
>
> Relevant backtrace (if possible)
>
> No response
>
> Minimal configuration
>
>   • [*] I agree using a minimal configuration
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.*Message ID: ***@***.***>


-- 
Thierry

**Comment by zw963** [comment]
> helm-grep-git-1 have a INPUT argument, you can easily create your own function using it.

Yes, i created new function use helm-grep-git-1 like this: (part of code stolen from helm-git-grep)

```cl
(defun helm-git-grep-get-input-symbol ()
  "Get input symbol."
  (if (not mark-active)
      (thing-at-point 'symbol)
    (when (use-region-p)
      (buffer-substring (region-beginning) (region-end)))))

(defun helm-grep-do-git-grep-hacked (arg)
  "Preconfigured `helm' for git-grepping `default-directory'.
With a prefix arg ARG git-grep the whole repository."
  (interactive "P")
  (require 'helm-files)
  (helm-grep-git-1 default-directory arg nil (helm-git-grep-get-input-symbol)))
```

But, i consider this is a good default, we should add it into helm.(more graceful)

There are maybe exists others function which use helm-grep-git-1 which need updated too.

**Comment by thierryvolpiatto** [comment]
"Billy.Zheng" ***@***.***> writes:

>     helm-grep-git-1 have a INPUT argument, you can easily create your own function using it.
>    
> Yes, i created new function use helm-grep-git-1 like this: (part of code stolen from helm-git-grep)
>
> (defun helm-git-grep-get-input-symbol ()
>   "Get input symbol."
>   (if (not mark-active)
>       (thing-at-point 'symbol)
>     (when (use-region-p)
>       (buffer-substring (region-beginning) (region-end)))))

You can write this in a much better way.

> (defun helm-grep-do-git-grep-hacked (arg)
>   "Preconfigured `helm' for git-grepping `default-directory'.
> With a prefix arg ARG git-grep the whole repository."
>   (interactive "P")
>   (require 'helm-files)
>   (helm-grep-git-1 default-directory arg nil (helm-git-grep-get-input-symbol)))
>
> But, i consider this is a good default, we should add it into helm.(more graceful)

It is not, at least in my opinion, because:

1) The content of a region may not be a safe regexp.
2) Anyway the usage of INPUT is annoying (in contrast with DEFAULT, it
is why we use helm-sources-using-default-as-input mechanism in helm-grep fns).

> There are maybe exists others function which use helm-grep-git-1 which need updated too.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.*Message ID: ***@***.***>


-- 
Thierry

**Comment by zw963** [comment]
> 1) The content of a region may not be a safe regexp.

Compared with the convenience of `grep on the marked region`, this is only a small probability of happening

> 2) Anyway the usage of INPUT is annoying (in contrast with DEFAULT, it
is why we use helm-sources-using-default-as-input mechanism in helm-grep fns).

This is reasonable, but, user's selection should override any default.

thanks

**Comment by thierryvolpiatto** [comment]
Won't fix for the sus mentionned reasons, thanks. Closing now.
