### ISSUE TITLE
(setq helm-split-window-inside-p t) does not seem to be honored by write file

### ISSUE THREAD

**Issue by rdiaz02** [emacs-helm/helm#2593]
### What happened?

When I set `(setq helm-split-window-inside-p t)` I expected `C-x C-f`  and `C-x C-w` to behave similarly with respect to window splitting. They don't. 

### How to reproduce?

1. Start helm with `emacs-helm.sh`
2. In the scratch buffer, type and evaluate `(setq helm-split-window-inside-p t)`.
3. Split the window right: `C-x 3` (or `M-x split-window-right`).
4. To make it easier to recognize the issue, open some file on the right window. 
5. On the left window, do `C-x C-f`:  `helm-find-files`displays on the bottom half of the left window. This is what I expect. (See screen capture f5.png)
![f5](https://user-images.githubusercontent.com/1688611/229247999-3640fef5-d25c-4c04-83a7-cbdb07d152e6.png)

6. `C-g`
7. On the left window, do `C-x C-w`:  the vertical split disappears, and the whole frame has only the upper window  which is occupied by the former left window, and the bottom `helm-mode-write-file`. This is **not** what I expected: find-files and write-file do not behave consistently. (See screen capture f7.png).
![f7](https://user-images.githubusercontent.com/1688611/229248029-3288c688-745d-49b7-9662-0a1bf9994fb9.png)

### Helm Version

Master branch

### Emacs Version

Emacs-28/29

### OS

GNU/Linux

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by thierryvolpiatto** [comment]
Ramon Diaz-Uriarte ***@***.***> writes:

> What happened?
>
> When I set (setq helm-split-window-inside-p t) I expected C-x C-f and
> C-x C-w to behave similarly with respect to window splitting. They
> don't.

Fixed, thanks.

-- 
Thierry

**Comment by rdiaz02** [comment]
Works perfectly. Thank you! Closing.
