### ISSUE TITLE
Opening minibuffer pointer remains in starting buffer (need SPC-w-b to focus minibuffer)

### ISSUE THREAD

**Issue by sfavazza** [emacs-helm/helm#2595]
### What happened?

I am using _helm_ as installed and handled by _spacemacs 0.999.0_. The editor runs in a docker container on a
linux machine (_Ubuntu 22.04.1_), this machine is accessed via the *Remote Desktop* app installed on a Windows 10
mchine.

When I invoke `M-x` (SPC-SPC) or when I invoke `lazy-helm/helm-mini` (SPC-b-b), in certain conditions (see
below) the pointer remains in a particular buffer (see below). As a workaround I always have to invoke "quickly"
SPC-w-b which invokes `spacemacs/switch-to-minibuffer-window` ("quickly" as after pressing SPC in less
than a second the command does not have effect anymore).

See the gif below to observe the issue:

![v0_helm_minibuffer_focus_issue](https://user-images.githubusercontent.com/36377461/230799235-4ee99e40-5f1c-43de-8b8a-eb6ef300afb2.gif)

### How to reproduce?

The issue occurs unexpectedly and never on the first invokation after a spacemacs restart. Though there is a way
I managed to reliably reproduce it:

- start spacemacs
- open new frame (SPC-b-N-f)
- try to invoke helm, with any of those:
  - `hspacemacs/helm-M-x-fuzzy-matching` (SPC-SPC)
  - `spacemacs/helm-M-x-fuzzy-matching` (SPC-b-b)
- before typing anything select the first frame
- in it, invoke helm again

After this, the following is observed:
- the pointer stays in:
  - 1st frame switch the buffer to the one on the 2nd frame (from which `helm` has been invoked first)
  - helm buffer, right under the minibuffer
- successive invokactions of `helm` show the pointer never in the minibuffer
- sometimes the pointer escapes multiple times from the minibuffer (I guess when helm updates its buffer with
  candidates, but I am not sure of the mechanism of behavior)

I searched online about this issue and I am afraid I might be the only one who observed it due to my unconventional setup.

This bug report is a request of help on understanding at which point in the code the pointer is placed in the minibuffer, i.e. when it is activated?
I would like to step-debug it and try to see whether I can find the source of this issue.

### Helm Version

Melpa or NonGnuElpa

### Emacs Version

Emacs-28/29

### OS

GNU/Linux

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by thierryvolpiatto** [comment]
sfavazza ***@***.***> writes:

> Minimal configuration
>
>   • [*] I agree using a minimal configuration

Sorry but you are NOT using a minimal configuration.


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Please report on Spacemacs.

**Comment by thierryvolpiatto** [comment]
sfavazza ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
>   • start spacemacs
>   • open new frame (SPC-b-N-f)
>   • try to invoke helm, with any of those:
>       □ hspacemacs/helm-M-x-fuzzy-matching (SPC-SPC)
>       □ spacemacs/helm-M-x-fuzzy-matching (SPC-b-b)
>   • before typing anything select the first frame
>   • in it, invoke helm again
>
> After this, the following is observed:
>
>   • the pointer stays in:
>       □ 1st frame switch the buffer to the one on the 2nd frame (from which helm has been invoked first)
>       □ helm buffer, right under the minibuffer
>   • successive invokactions of helm show the pointer never in the minibuffer
>   • sometimes the pointer escapes multiple times from the minibuffer (I guess when helm updates its buffer with
>     candidates, but I am not sure of the mechanism of behavior)

NOTE: The handling of such a situation had been fixed perhaps ten years
ago and still working fine, I guess it has been deactivated by
Spacemacs.
 
-- 
Thierry

**Comment by sfavazza** [comment]
Hi @thierryvolpiatto, thanks for the lightening fast reply.

I am aware that my setup is not minimal, but it is the only way I can see this issue and the only setup I can use at work.
Though I open this issue to request help on the code of helm itself more than on an investigation. I tried tens of times to debug the issue but I never find the exact step where the pointer is supposed to point to the active minibuffer.

One of my last investigation brought me in this section of code

![image](https://user-images.githubusercontent.com/36377461/231379899-c10225dc-c7a4-4123-b774-c6fca651f74d.png)

If it does not steal you too much time, would you point me to the function(s) responsible to focus the pointer to the minibuffer? I intend to debug it on my own.

I am using the Elpa package `helm-core-20230317.1729`

**Comment by thierryvolpiatto** [comment]
sfavazza ***@***.***> writes:

> Hi @thierryvolpiatto, thanks for the lightening fast reply.
>
> I am aware that my setup is not minimal, but it is the only way I can
> see this issue and the only setup I can use at work.  Though I open
> this issue to request help on the code of helm itself more than on an
> investigation. I tried tens of times to debug the issue but I never
> find the exact step where the pointer is supposed to point to the
> active minibuffer.

I am sorry, but I can't help you much as long as I can't reproduce the
issue. Debugging with Spacemacs is impossible as there is too much
packages loaded that are incompatible between each others and thus
Spacemacs itself modify Helm (badly IMO according to the number of
issues the Spacemacs users complain about).
The issue is simple, Helm should prevent opening two sessions, if you
try to do so, Helm will kill the initial session (in frame1) and send
you an error message.  If this doesn't happen, this mean Helm has been
modified and I can't do anything about this.

To try to reproduce your issue in a way we can work together on it, open
a terminal and launch Helm with emacs-helm.sh script. You can also start
from Emacs -Q and use a minimal Helm config from there.

-- 
Thierry

**Comment by sfavazza** [comment]
I see your point. Anyway by chance I found out that this setting solves my issue (just for reference to whoever might bump into the same problem):

` (setq minibuffer-follows-selected-frame nil)`

I will refer this issue on the spacemacs repo (although it seems nobody has yet encounter this issue).
