### ISSUE TITLE
helm-locate with es (Everything) does not work 

### ISSUE THREAD

**Issue by tuhdo** [emacs-helm/helm#2599]
### What happened?

I used this code provided by the wiki:

```
  (setq helm-locate-command "es %s -sort run-count %s")
  (defun helm-es-hook ()
    (when (and (equal (assoc-default 'name (helm-get-current-source)) "Locate")
               (string-match "\\`es" helm-locate-command))
      (mapc (lambda (file)
              (call-process "es" nil nil nil
                            "-inc-run-count" (convert-standard-filename file)))
            (helm-marked-candidates))))
  (add-hook 'helm-find-many-files-after-hook 'helm-es-hook)
```

But nothing happened. When I enter some text, just a blank Helm buffer like this:

![image](https://user-images.githubusercontent.com/4818719/235707670-f3d23db7-0db4-48de-8bf5-d12b231c76da.png)

### How to reproduce?

To reproduce, just use the code provided by the wiki and put `es` somewhere in Windows PATH that Emacs can find.

### Helm Version

Master branch

### Emacs Version

Emacs-28/29

### OS

Windows

### Relevant backtrace (if possible)

```text
My Emacs version is 30.0.50.
```

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by tuhdo** [comment]
Even with `helm-locate-command` set as `"es %s %s"` by Helm, no result is returned. But if I run the command in a terminal, I get results, e.g. if I want to find the text `test`, I type `es test` and I got results across disks.

**Comment by thierryvolpiatto** [comment]
PR welcome, I can't fix this as I have no windows box.
