### ISSUE TITLE
Helm lists buffers slow

### ISSUE THREAD

**Issue by EVGVir** [emacs-helm/helm#2600]
### What happened?

Helm is extremly slow when I am trying to kill a compilation buffer. According to profile that happens because Helm tries to guess file names at point. Since the buffer is connected to a remote machine (via TRAMP) this works very slow.

It looks very strange for me that Helm tries to guess any file names at all. Since the only thing is needed is a list of buffers. And this list hardly relates to content of the buffer under the point.

### How to reproduce?

1. Compile a code on a remote machine via tramp.
2. The compilation string is fairly long as well as having a lot of file names.
3. It is better reproduced when there are compilation errors (additional file names?)
4. C-x k

### Helm Version

Melpa or NonGnuElpa

### Emacs Version

Emacs-28/29

### OS

MacOSX

### Relevant backtrace (if possible)

```text
10104  98% - command-execute
       10104  98%  - call-interactively
        6678  65%   - #<compiled 0x1e1c6813041c5850>
        6678  65%    - apply
        6678  65%     - helm--generic-read-buffer
        6678  65%      - helm--completing-read-default
        6678  65%       - helm-mode--apply-helm-handler
        6678  65%        - apply
        6678  65%         - helm-completing-read-default-handler
        6678  65%          - helm-completing-read-default-1
        6678  65%           - helm-comp-read
        6676  65%            - helm
        6676  65%             - apply
        6676  65%              - helm
        6676  65%               - apply
        6676  65%                - helm-internal
        6635  64%                 - helm-read-from-minibuffer
        4780  46%                  - helm-update
        4779  46%                   - helm--collect-matches
        4779  46%                    - helm-compute-matches
        4779  46%                     - helm-process-filtered-candidate-transformer
        4779  46%                      - helm-apply-functions-from-source
        4779  46%                       - apply
        4779  46%                        - helm-fuzzy-highlight-matches
        4779  46%                         - helm-guess-filename-at-point
        4779  46%                          - run-hook-with-args-until-success
        4779  46%                           - ffap-guess-file-name-at-point
        4779  46%                            - ffap-guesser
        4779  46%                             - ffap-file-at-point
        4518  44%                              - ffap-file-exists-string
        4518  44%                               - file-exists-p
        4516  44%                                - tramp-file-name-handler
        4490  43%                                 - apply
        4489  43%                                  - tramp-sh-file-name-handler
        4489  43%                                   - apply
        4482  43%                                    - tramp-sh-handle-file-exists-p
        4471  43%                                     - tramp-send-command-and-check
        4471  43%                                      - tramp-send-command
        4450  43%                                       - tramp-wait-for-output
        4449  43%                                        - tramp-wait-for-regexp
        4449  43%                                         - tramp-accept-process-output
           9   0%                                          + accept-process-output
           1   0%                                            #<compiled 0x23c09f6c2dd468f>
          18   0%                                         tramp-send-string
           1   0%                                         tramp-maybe-open-connection
           9   0%                                     + tramp-get-file-property
           1   0%                                     + tramp-set-file-property
           1   0%                                     + tramp-dissect-file-name
           7   0%                                    + tramp-sh-handle-expand-file-name
           1   0%                                  + tramp-file-name-for-operation
          22   0%                                 + tramp-find-foreign-file-name-handler
           3   0%                                 + tramp-dissect-file-name
           1   0%                                   tramp-tramp-file-p
         259   2%                              + ffap-completable
           1   0%                   + helm--update-move-first-line
          77   0%                  + read-from-minibuffer
          39   0%                 + helm-display-buffer
           1   0%                 + helm-initialize
           1   0%                 + #<compiled 0x1fc31de962275>
           2   0%            + helm-make-source
        3422  33%   + byte-code
           4   0%   + funcall-interactively
         137   1% + ...
          13   0% + redisplay_internal (C function)
           3   0% + #<compiled -0x2222be8f352b999>
           2   0% + global-hl-line-highlight
           2   0% + timer-event-handler
```
```


### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by EVGVir** [comment]
With `emacs-helm.sh` it works faster, however not fast enough.

There are following messages in `*Messages*` buffer when I invoke `C-x k`:
```
File error: tramp-sh-handle-file-name-all-completions: internal error accessing ‘<very long file name>’: ‘’ [2 times]
```

So, anyway Helm goes on a remote machine to prepare a list of buffers. 🤷‍♂️

**Comment by thierryvolpiatto** [comment]
Evgeny Gagauz ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
> What happened?
>
> Helm is extremly slow when I am trying to kill a compilation
> buffer. According to profile that happens because Helm tries to guess
> file names at point.

Did you try with last helm? I removed this check.

> Since the buffer is connected to a remote machine (via TRAMP) this
> works very slow.
>
> It looks very strange for me that Helm tries to guess any file names at all. Since the only thing is needed is a list of buffers. And this list hardly relates to content of the buffer
> under the point.
>
> How to reproduce?
>
>  1. Compile a code on a remote machine via tramp.
>  2. The compilation string is fairly long as well as having a lot of file names.
>  3. It is better reproduced when there are compilation errors (additional file names?)
>  4. C-x k
>
> Helm Version
>
> Melpa or NonGnuElpa
>
> Emacs Version
>
> Emacs-28/29
>
> OS
>
> MacOSX
>
> Relevant backtrace (if possible)
>
> 10104  98% - command-execute
>        10104  98%  - call-interactively
>         6678  65%   - #<compiled 0x1e1c6813041c5850>
>         6678  65%    - apply
>         6678  65%     - helm--generic-read-buffer
>         6678  65%      - helm--completing-read-default
>         6678  65%       - helm-mode--apply-helm-handler
>         6678  65%        - apply
>         6678  65%         - helm-completing-read-default-handler
>         6678  65%          - helm-completing-read-default-1
>         6678  65%           - helm-comp-read
>         6676  65%            - helm
>         6676  65%             - apply
>         6676  65%              - helm
>         6676  65%               - apply
>         6676  65%                - helm-internal
>         6635  64%                 - helm-read-from-minibuffer
>         4780  46%                  - helm-update
>         4779  46%                   - helm--collect-matches
>         4779  46%                    - helm-compute-matches
>         4779  46%                     - helm-process-filtered-candidate-transformer
>         4779  46%                      - helm-apply-functions-from-source
>         4779  46%                       - apply
>         4779  46%                        - helm-fuzzy-highlight-matches
>         4779  46%                         - helm-guess-filename-at-point
>         4779  46%                          - run-hook-with-args-until-success
>         4779  46%                           - ffap-guess-file-name-at-point
>         4779  46%                            - ffap-guesser
>         4779  46%                             - ffap-file-at-point
>         4518  44%                              - ffap-file-exists-string
>         4518  44%                               - file-exists-p
>         4516  44%                                - tramp-file-name-handler
>         4490  43%                                 - apply
>         4489  43%                                  - tramp-sh-file-name-handler
>         4489  43%                                   - apply
>         4482  43%                                    - tramp-sh-handle-file-exists-p
>         4471  43%                                     - tramp-send-command-and-check
>         4471  43%                                      - tramp-send-command
>         4450  43%                                       - tramp-wait-for-output
>         4449  43%                                        - tramp-wait-for-regexp
>         4449  43%                                         - tramp-accept-process-output
>            9   0%                                          + accept-process-output
>            1   0%                                            #<compiled 0x23c09f6c2dd468f>
>           18   0%                                         tramp-send-string
>            1   0%                                         tramp-maybe-open-connection
>            9   0%                                     + tramp-get-file-property
>            1   0%                                     + tramp-set-file-property
>            1   0%                                     + tramp-dissect-file-name
>            7   0%                                    + tramp-sh-handle-expand-file-name
>            1   0%                                  + tramp-file-name-for-operation
>           22   0%                                 + tramp-find-foreign-file-name-handler
>            3   0%                                 + tramp-dissect-file-name
>            1   0%                                   tramp-tramp-file-p
>          259   2%                              + ffap-completable
>            1   0%                   + helm--update-move-first-line
>           77   0%                  + read-from-minibuffer
>           39   0%                 + helm-display-buffer
>            1   0%                 + helm-initialize
>            1   0%                 + #<compiled 0x1fc31de962275>
>            2   0%            + helm-make-source
>         3422  33%   + byte-code
>            4   0%   + funcall-interactively
>          137   1% + ...
>           13   0% + redisplay_internal (C function)
>            3   0% + #<compiled -0x2222be8f352b999>
>            2   0% + global-hl-line-highlight
>            2   0% + timer-event-handler
>
> ### Minimal configuration
>
> - [X] I agree using a minimal configuration
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.*Message ID: ***@***.***>


-- 
Thierry

**Comment by EVGVir** [comment]
Wow, what a speed! `helm-core 20230505.802` works like a charm!

Thanks a lot!
