### ISSUE TITLE
Can't go back in helm pages

### ISSUE THREAD

**Issue by danielkrajnik** [emacs-helm/helm#2604]
How do you go back to previous page in help pages?

**Comment by thierryvolpiatto** [comment]
danielkrajnik ***@***.***> writes:

> What happened?
>
> How do you go back to previous page in help pages?

There is no "pages" in helm help, helm uses org for its help buffer and
all sections are in org headers like in any org files.
The commands to navigate in this buffer are documented in the "* Helm help" section.

> How to reproduce?
>
> arg
>
> Helm Version
>
> Master branch
>
> Emacs Version
>
> Emacs-25*
>
> OS
>
> GNU/Linux
>
> Relevant backtrace (if possible)
>
> erg
>
> Minimal configuration
>
>   • [*] I agree using a minimal configuration
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.*Message ID: ***@***.***>


-- 
Thierry

**Comment by danielkrajnik** [comment]
Thanks, sorry but I can't find Helm help. How do you get to it? I'm on doom emacs, so maybe I shouldn't be allowed to use emacs, but this is not fair to not have access to basic help pages.

**Comment by danielkrajnik** [comment]
If you have any mercy in your heart could you at least please look up "return to previous page" command on that page?

**Comment by thierryvolpiatto** [comment]
danielkrajnik ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
> Thanks, sorry but I can't find Helm help. How do you get to it?

C-h m

-- 
Thierry

**Comment by danielkrajnik** [comment]
this is bound to `describe-mode` in doom emacs

**Comment by progfolio** [comment]
> this is bound to `describe-mode` in doom emacs

Your question is better suited for Doom's support channels.

**Comment by thierryvolpiatto** [comment]
Ok, closing now, next time you fill a bug report please follow the template.
