### ISSUE TITLE
org-roam-node-find produces an "error running timer" error

### ISSUE THREAD

**Issue by mplsgrant** [emacs-helm/helm#2606]
### What happened?

I updated helm via `straight-pull`, and when I use `org-roam-node-find` it produced an error which stated: "error running timer". 

By checking out various commits, I found that 71d46f2d229ae56f34c11e0e54fb02d97b69381b caused the issue because eea5f20da36a21a904e560a21485bbed835a68a1 still works.

### How to reproduce?

# Create `temp_init.el`
```
(setq package-enable-at-startup nil)
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 6))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'use-package)
(setq use-package-always-ensure t)

(use-package org :straight (:type built-in))

(setq org-directory (concat (getenv "HOME") "/testing_org_roam_please_delete_me/"))
(use-package org-roam
  :straight t
  :ensure t
  :after org
  :init (setq org-roam-v2-ack t) ;; Acknowledge V2 upgrade
  :custom
  (org-roam-directory (file-truename org-directory))
  (org-roam-complete-everywhere t)
  :config
  (org-roam-setup))

(use-package helm
    :straight t
    :init (helm-mode t)
)

```
# Make a temp directory and run emacs
`mkdir testing_org_roam_please_delete_me`
`emacs -q -l ~/delme/temp_init.el`

# Try to use this command
`M-x org-roam-node-find` will cause an error while searching.

# Change the straight repo
- Hunt down `straight/repos/` 
- Run `git checkout eea5f20da36a21a904e560a21485bbed835a68a1 -b my-eea5f20da36a21a904e560a21485bbed835a68a1`
- Rerun the emacs -q step and notice that org-roam-node-find now works as expected

### Helm Version

Master branch

### Emacs Version

Emacs-28/29

### OS

GNU/Linux

### Relevant backtrace (if possible)

```text
n/a
```

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by thierryvolpiatto** [comment]
mplsgrant ***@***.***> writes:

> What happened?
>
> I updated helm via straight-pull, and when I use org-roam-node-find it produced an error which stated: "error running timer".
>
> By checking out various commits, I found that 71d46f2 caused the issue because eea5f20 still works.

Thanks, should be fixed now.

-- 
Thierry

**Comment by mplsgrant** [comment]
I checkout out master, and it looks like it works. Thank you!
