### ISSUE TITLE
M-x rgrep fails to execute with wrong type argument

### ISSUE THREAD

**Issue by ChrisHacker** [emacs-helm/helm#2607]
### What happened?

Error message: 

`helm-M-x-execute-command: Wrong type argument: stringp, ("*.clj" "all" "el" "ch" "c" "cc" "cchh" "hh" "h" "l" ...)`

### How to reproduce?

M-x rgrep
Enter search string
Error throws.

Couldn't get a copy of the debugger output. Image below
![image](https://github.com/emacs-helm/helm/assets/2028238/ab396bf8-7060-4ca0-9077-9502745f81cb)

### Helm Version

Melpa or NonGnuElpa

### Emacs Version

Emacs-27.1

### OS

GNU/Linux

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by thierryvolpiatto** [comment]
Chris ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
> What happened?
>
> Error message:
>
> helm-M-x-execute-command: Wrong type argument: stringp, ("*.clj" "all" "el" "ch" "c" "cc" "cchh" "hh" "h" "l" ...)
>
> How to reproduce?
>
> M-x rgrep

Please add rgrep (and grep) to helm-completing-read-handlers-alist and/or
even better use the various helm grep commands from helm-find-files.
I will have a look but no guarantees I can fix this.

> 
> Enter search string Error throws.
>
> Couldn't get a copy of the debugger output. Image below
> image   
>
> Helm Version
>
> Melpa or NonGnuElpa
>
> Emacs Version
>
> Emacs-27.1
>
> OS
>
> GNU/Linux
>
> Relevant backtrace (if possible)
>
> No response
>
> Minimal configuration
>
>   • [*] I agree using a minimal configuration
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.*Message ID: ***@***.***>


-- 
Thierry

**Comment by ChrisHacker** [comment]
I've tried both of the following regarding adding them via custom.el file - the first one throws an error while the latter doesn't throw an error but also doesn't resolve the error thrown by rgrep. 

- Throws error on emacs launch: `(add-to-list helm-completing-read-handlers-alist 'rgrep 'grep)`
- No error on launch, doesn't fix issue: `(add-to-list 'helm-completing-read-handlers-alist 'rgrep 'grep)`

As for using helm-find-files, it doesn't appear to search the body of the files, just the names. Any suggestions? rgrep worked prior to the last helm update I installed.

Thanks.

**Comment by thierryvolpiatto** [comment]
Should be fixed now.
However, I wonder why Emacs rgrep gives a list of strings containing another list of strings which contains itself strings already presents in the inner list (guess it is a bug).

**Comment by ChrisHacker** [comment]
Great. I'll keep an eye out on melpa and report back.

**Comment by thierryvolpiatto** [comment]
Chris ***@***.***> writes:

> I've tried both of the following regarding adding them via custom.el file - the first one throws an error while the latter doesn't throw an error but also doesn't resolve the error thrown
> by rgrep.
>
>   • Throws error on emacs launch: (add-to-list helm-completing-read-handlers-alist 'rgrep 'grep)
>   • No error on launch, doesn't fix issue: (add-to-list 'helm-completing-read-handlers-alist 'rgrep 'grep)

Both calls of add-to-list are wrong, you should use:

    (add-to-list 'helm-completing-read-handlers-alist '(rgrep . nil))
    (add-to-list 'helm-completing-read-handlers-alist '(grep . nil))

> As for using helm-find-files, it doesn't appear to search the body of
> the files, just the names.

I meant using one of the grep action of helm-find-files ;-) which are
much better alternatives to grep/rgrep vanilla Emacs commands.

For recursive grepping files with grep:

1) M-x helm-find-files (bind it to C-x C-f)
2) Navigate to the directory you want to grep
3) Hit C-u C-s
4) select the type of files you want to grep and hit RET

For grepping marked files

Same as above, but mark some files or put selection on only one file and
hit C-s.

Better alternatives for rgrep are using ripgrep as backend and hit `M-g
a` from helm-find files.
Or use git grep if your directory is controlled by git, in this case you
can use `M-g g` 

> Any suggestions? rgrep worked prior to the last helm update I
> installed.

It should be fixed now.

> Thanks.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.*Message ID: ***@***.***>


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
I may have forgotten something, so use C-h m from helm-find-files for better infos about grep and else.
Thanks.

**Comment by ChrisHacker** [comment]
Thanks for that. Much appreciated. The adjustment in custom.el worked and I'll look further into using the helm-find-files method.
