### ISSUE TITLE
highlight-phrase broke with emacs 29.1 and helm

### ISSUE THREAD

**Issue by mariusk** [emacs-helm/helm#2610]
### What happened?

When I try to use `highlight-phrase` after enabling `helm-mode`, I immediately get the following error:

```
Wrong type argument: stringp, ("hi-yellow" "hi-pink" ....)
```

### How to reproduce?

I loaded emacs with any init file, and just manually evaled the following config:

```
(require 'package)
(package-initialize)
(require 'helm-mode)
(helm-mode 1)
```

Then trying to use `highlight-phrase` will trigger the error.

### Helm Version

Master branch

### Emacs Version

Emacs-28/29

### OS

MacOSX

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by thierryvolpiatto** [comment]
Marius Kjeldahl ***@***.***> writes:

> What happened?
>
> When I try to use highlight-phrase after enabling helm-mode, I immediately get the following error:
>
> Wrong type argument: stringp, ("hi-yellow" "hi-pink" ....)

Should be fixed by 88e4d1ae.
Fix also #2607 which has reappeared in Emacs-29.1.

Thanks.

-- 
Thierry

**Comment by mariusk** [comment]
Not sure it's entirely fixed though, I'm getting another error now (assuming the last update of the Helm package was for this fix):

```
Symbol's function definiton is void: help--symbol-class
```

Haven't debugged it yet so could be something else I guess.

**Comment by mariusk** [comment]
Debugged it the same way as described for the original issue, and can confirm it's related to the helm update.

**Comment by mariusk** [comment]
With the latest fix it seems to work fine again. Thanks a bunch!

**Comment by thierryvolpiatto** [comment]
Marius Kjeldahl ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
> With the latest fix it seems to work fine again. Thanks a bunch!

Great! Thanks to confirm.

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you modified the open/close state.*Message ID: ***@***.***>


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
You have no errors but the completion is not exactly what you would expect (compared to vanilla Emacs).
Here is what you expect:
![Capture d’écran_2023-08-03_20-13-23](https://github.com/emacs-helm/helm/assets/1533939/b909bc31-3257-45f9-9ab0-8b3a5b2521b9)
