### ISSUE TITLE
Unhelpful documentation  needs improvement

### ISSUE THREAD

**Issue by sysdbugfactory** [emacs-helm/helm#2612]
### What happened?

After a system upgrade, emacs failed to load .emacs config file due to errors.

after removing obsolete package repository and upgrading packages, helm is now version 3.9.3 and it fails my .emacs due to a remaining older config.

Looking into the documentation for the appropriaté config I'm served with a terrible documentation entry telling me I should not have anything to do and that's it.

I am now stuck with either disabling helm altogether or suffer a broken emacs config due to helm missing a directory.

the exact error message is: 
`Debugger entered--Lisp error: (file-missing "Cannot open load file" "Aucun fichier ou dossier de ce type" "helm-config")`

Please fix your documentation to actually show what the helm config entries should be and cover the edge cases where things do not go as they should.

### How to reproduce?

install emacs and helm years in the past from marmalade repo, follow documentation to enable helm from .emacs, wait several years, remove marmalade repo and upgrade helm, then emacs fails to load.

### Helm Version

Master branch

### Emacs Version

Emacs-28/29

### OS

GNU/Linux

### Relevant backtrace (if possible)

```text
`Debugger entered--Lisp error: (file-missing "Cannot open load file" "Aucun fichier ou dossier de ce type" "helm-config")`
```

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by thierryvolpiatto** [comment]
sysdbugfactory ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
> What happened?
>
> After a system upgrade, emacs failed to load .emacs config file due to errors.
>
> after removing obsolete package repository and upgrading packages, helm is now version 3.9.3 and it fails my .emacs due to a remaining older config.
>
> Looking into the documentation

Which documentation?

> for the appropriaté config I'm served with a terrible documentation
> entry telling me I should not have anything to do and that's it.

Here is the entry about this in helm wiki:

    Note: In the past we had a file called “helm-config.el” that was needed
    for installation from source only (most people were requiring it with an
    installation from package which was unuseful) the file doesn’t exists
    anymore, therefore if you try to require it you will have an error.

https://github.com/emacs-helm/helm/wiki#configure

> I am now stuck with either disabling helm altogether or suffer a broken emacs config due to helm missing a directory.
>
> the exact error message is:
> Debugger entered--Lisp error: (file-missing "Cannot open load file" "Aucun fichier ou dossier de ce type" "helm-config")

You have just to remove (require 'helm-config) from your init file, is
it dramatic?

> Please fix your documentation to actually show what the helm config
> entries should be and cover the edge cases where things do not go as
> they should.

It is fixed, please read a recent documentation.

> How to reproduce?
>
> install emacs and helm years in the past from marmalade repo, follow
> documentation to enable helm from .emacs, wait several years, remove
> marmalade repo and upgrade helm, then emacs fails to load.

Of course, this is true with Emacs itself or any software.
If we want no failures in such case, I have to leave Helm unmodified for
the next ten years.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Duplicate of #2578
