### ISSUE TITLE
Warning (emacs): ... after-init-hook Should be defined as a symbol

### ISSUE THREAD

**Issue by Ypot** [emacs-helm/helm#2614]
### What happened?

I am receiving a warning for each file of the agenda, when I use (helm-org-rifle-agenda-files):

` ⛔ Warning (emacs): Helm source ‘1-file.org’: after-init-hook Should be defined as a symbol`

https://github.com/alphapapa/org-rifle/issues/81

### How to reproduce?

Note: I am not using emacs -q. Since I need org-rifle to reproduce the warning. 

Using command helm-org-rifle-agenda-files, appears the "*Warnings* buffer with that content:

` ⛔ Warning (emacs): Helm source ‘1-file.org’: after-init-hook Should be defined as a symbol`

### Helm Version

Master branch

### Emacs Version

Emacs-29.1

### OS

Windows

### Relevant backtrace (if possible)

```text
No error. It works fine, but Warnings appear every time.
```

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by thierryvolpiatto** [comment]
Ypot ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
> What happened?
>
> I am receiving a warning for each file of the agenda, when I use (helm-org-rifle-agenda-files):
>
> ⛔ Warning (emacs): Helm source ‘1-file.org’: after-init-hook Should be defined as a symbol

Please report to org-rifle, thanks.

> alphapapa/org-rifle#81
>
> How to reproduce?
>
> Note: I am not using emacs -q. Since I need org-rifle to reproduce the warning.
>
> Using command helm-org-rifle-agenda-files, appears the "Warnings buffer with that content:
>
> ⛔ Warning (emacs): Helm source ‘1-file.org’: after-init-hook Should be defined as a symbol
>
> Helm Version
>
> Master branch
>
> Emacs Version
>
> Emacs-29.1
>
> OS
>
> Windows
>
> Relevant backtrace (if possible)
>
> No error. It works fine, but Warnings appear every time.
>
> Minimal configuration
>
>   • [*] I agree using a minimal configuration
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.*Message ID: ***@***.***>


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Same as #2549

**Comment by Ypot** [comment]
> Ypot ***@***.***> writes:
> 1. ( ) text/plain (*) text/html What happened? I am receiving a warning for each file of the agenda, when I use (helm-org-rifle-agenda-files): ⛔ Warning (emacs): Helm source ‘1-file.org’: after-init-hook Should be defined as a symbol
> Please report to org-rifle, thanks.
> […](#)
> [alphapapa/org-rifle#81](https://github.com/alphapapa/org-rifle/issues/81) How to reproduce? Note: I am not using emacs -q. Since I need org-rifle to reproduce the warning. Using command helm-org-rifle-agenda-files, appears the "Warnings buffer with that content: ⛔ Warning (emacs): Helm source ‘1-file.org’: after-init-hook Should be defined as a symbol Helm Version Master branch Emacs Version Emacs-29.1 OS Windows Relevant backtrace (if possible) No error. It works fine, but Warnings appear every time. Minimal configuration • [*] I agree using a minimal configuration — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.*Message ID: ***@***.***>
> -- Thierry

I reported first there
https://github.com/alphapapa/org-rifle/issues/81
