### ISSUE TITLE
Why was helm-comint deleted?

### ISSUE THREAD

**Issue by victorfonsec4** [emacs-helm/helm#2615]
### What happened?

helm-comint.el was delete so some functions are no longer available.

commit that deleted it: 587bed0

### How to reproduce?

Load the package and try using helm-comint-input-ring for example.

### Helm Version

Master branch

### Emacs Version

Emacs-29.1

### OS

GNU/Linux

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by thierryvolpiatto** [comment]
Victor Fonseca ***@***.***> writes:

> What happened?
>
> helm-comint.el was delete so some functions are no longer available.

helm-comint.el is now here https://github.com/emacs-helm/helm-comint

I am in the process of moving stuff outside of Helm, this was is not
widely used and I have no news of his author and maintainer, it will be
soon available as a package, see
https://github.com/emacs-helm/helm-comint/issues/1

Waiting for this you can download it, put it in your load-path and
require it in your config.

Thanks and sorry for the trouble.

> commit that deleted it: 587bed0
>
> How to reproduce?
>
> Load the package and try using helm-comint-input-ring for example.
>
> Helm Version
>
> Master branch
>
> Emacs Version
>
> Emacs-29.1
>
> OS
>
> GNU/Linux
>
> Relevant backtrace (if possible)
>
> No response
>
> Minimal configuration
>
>   • [*] I agree using a minimal configuration
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.*Message ID: ***@***.***>


-- 
Thierry
