### ISSUE TITLE
helm-locate-library broken

### ISSUE THREAD

**Issue by michael-heerdegen** [emacs-helm/helm#2618]
### What happened?

Since some days the command lets me select a known library as expected, but when hitting RET it only finds a file of that name in the current default-directory, i.e., a new empty file most of the time in the current directory, instead of the library in its directory.

### How to reproduce?

M-x helm-locate-library, select e.g. simple.el.gz and hit RET.

### Helm Version

Melpa or NonGnuElpa

### Emacs Version

Emacs-30+

### OS

GNU/Linux

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen ***@***.***> writes:

> How to reproduce?
>
> M-x helm-locate-library, select e.g. simple.el.gz and hit RET.

I guess you are using completions-detailed == nil, this is why it was
not working, should be fixed now.
M-x find-library and locate-library should work as well, with and
without completions-detailed, didn't try yet though.

Thanks.

> Helm Version
>
> Melpa or NonGnuElpa
>
> Emacs Version
>
> Emacs-30+

Fixed on emacs-29.1 but should work as well on 30.


-- 
Thierry

**Comment by michael-heerdegen** [comment]
Thank you - seems to work fine now.  Yes, had been using completions-detailed nil.
