### ISSUE TITLE
`helm-locate-library` triggers error `Can't find library: ucs-utils-6`

### ISSUE THREAD

**Issue by taquangtrung** [emacs-helm/helm#2621]
### What happened?

Hi,

I'm using Emacs with the library https://github.com/rolandwalker/ucs-utils installed. When running `helm-locate-library`, it triggers the error:

```
Can't find library: ucs-utils-6
```

I have a library named `ucs-utils-6.0-delta.el` installed.

When tracing down the code of `helm-locate-library`, I found out that the code `for bn = (helm-basename c 2)` at line 950 truncates `ucs-utils-6.0-delta.el` to `ucs-utils-6` and trigger the bug.

https://github.com/emacs-helm/helm/blob/202928b70eacdb3d9b4175f62b8345520b683c98/helm-elisp.el#L943-L954

Can you help to fix this issue?

Thanks!

### How to reproduce?

- Install https://github.com/rolandwalker/ucs-utils
- Run `helm-locate-library`.

Then the bug will occurs

### Helm Version

Master branch

### Emacs Version

Emacs-29.1

### OS

GNU/Linux

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by thierryvolpiatto** [comment]
Ta Quang Trung ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
> What happened?
>
> Hi,
>
> I'm using Emacs with the library https://github.com/rolandwalker/ucs-utils installed. When running helm-locate-library, it triggers the error:
>
> Can't find library: ucs-utils-6
>
> I have a library named ucs-utils-6.0-delta.el installed.
>
> When tracing down the code of helm-locate-library, I found out that the code for bn = (helm-basename c 2) at line 950 truncates ucs-utils-6.0-delta.el to ucs-utils-6 and trigger the bug.
>
> https://github.com/emacs-helm/helm/blob/202928b70eacdb3d9b4175f62b8345520b683c98/helm-elisp.el#L943-L954
>
> Can you help to fix this issue?

Yes, sure, thanks to report, will fix this as soon as possible.

> Thanks!
>
> How to reproduce?
>
>   • Install https://github.com/rolandwalker/ucs-utils
>   • Run helm-locate-library.
>
> Then the bug will occurs
>
> Helm Version
>
> Master branch
>
> Emacs Version
>
> Emacs-29.1
>
> OS
>
> GNU/Linux
>
> Relevant backtrace (if possible)
>
> No response
>
> Minimal configuration
>
>   • [*] I agree using a minimal configuration
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.*Message ID: ***@***.***>


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Should be fixed now. Thanks.

**Comment by thierryvolpiatto** [comment]
FYI you can have descriptions of libraries when `completions-detailed` is non nil.
![Capture d’écran_2023-10-06_20-40-07](https://github.com/emacs-helm/helm/assets/1533939/8f59ba00-19b2-487d-bed7-f309db24e3fc)

And same with find-libary or locate-library.

**Comment by taquangtrung** [comment]
Thank you! It works now!
