### ISSUE TITLE
helm-mini can't select the matched candidate which in recentf source.

### ISSUE THREAD

**Issue by zw963** [emacs-helm/helm#2623]
### What happened?

This issue only happen on newest master 4ea86315, not happen when use version release 3.9.5

### How to reproduce?

1. start helm use a clear environment.
2. run helm-mini, and filter by a keyword, the matched result both on `Buffers` and `Recentf` source.
3.  keeping move down
4.  when reach the last on in `Buffers` source, it can move down to `Recentf` source.
5. But, if the matched result only exists on `Recentf`, it works.
 

### Helm Version

Master branch

### Emacs Version

Emacs-29.1

### OS

GNU/Linux

### Relevant backtrace (if possible)

```text
No
```

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by thierryvolpiatto** [comment]
"Billy.Zheng" ***@***.***> writes:

> What happened?
>
> This issue only happen on newest master 4ea8631, not happen when use version release 3.9.5
>
> How to reproduce?
>
>  1. start helm use a clear environment.
>  2. run helm-mini, and filter by a keyword, the matched result both on Buffers and Recentf source.
>  3. keeping move down

How?

>  4. when reach the last on in Buffers source, it can move down to
>  Recentf source.

It can or can't?

>  5. But, if the matched result only exists on Recentf, it works.

What works?

Thanks.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
"Billy.Zheng" ***@***.***> writes:

> What happened?
>
> This issue only happen on newest master 4ea8631, not happen when use version release 3.9.5

Oh I think what you mean is that when using C-n you can't move to next
source.
Some default have changed in Helm, see
`helm-move-to-line-cycle-in-source` which is now `t` by default.
So now when you are at end of a source you have to switch to next source
explicitely with helm-next-source.
 
-- 
Thierry

**Comment by zw963** [comment]
> It can or can't?

Sorry, Can't, i fixed it.

> Oh I think what you mean is that when using C-n you can't move to next
source. 

Yes, haha

Thank you very much, `(setq helm-move-to-line-cycle-in-source nil)` reverted to previous behavior
