### ISSUE TITLE
helm-locate-library broken when it finds file locks

### ISSUE THREAD

**Issue by michael-heerdegen** [emacs-helm/helm#2626]
### What happened?

helm-locate-library this time.  I say M-x helm-locate-library and get an error like
helm-M-x-execute-command: Can't find library: .#test

This happens for me when a file lock exists in a directory in load-path.

### How to reproduce?

(cl-pushnew "~/test/" load-path :test #'equal)

then create a file test.el in that directory, add some content, save it, and add some more content.

Emacs creates a file lock that is realized as a symbolic link, looking like this:

.#test.el -> micha@drachen.1935078:1698276464

Then calling helm-locate-library will throw an error in a freshly started emacs-helm.sh Emacs after adding the directory to the load-path like above.

### Helm Version

Melpa or NonGnuElpa

### Emacs Version

Emacs-30+

### OS

GNU/Linux

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by michael-heerdegen** [comment]
Oh, and TIA of course.

**Comment by thierryvolpiatto** [comment]
Hello Michael,

Michael Heerdegen ***@***.***> writes:

> What happened?
>
> helm-locate-library this time. I say M-x helm-locate-library and get an error like
> helm-M-x-execute-command: Can't find library: .#test
>
> This happens for me when a file lock exists in a directory in load-path.

Should be fixed now.

Thanks.

-- 
Thierry

**Comment by michael-heerdegen** [comment]
Yes, looks good, thanks.  I'm also closing this one.

[Your comment in the code speaks about "autoload files" but these are really lock files - see (info "(elisp) File Locks") ]

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen ***@***.***> writes:

> [[PGP Encrypted Part:OK]]
> 1.  ( ) text/plain          (*) text/html           
>
> Yes, looks good, thanks. I'm also closing this one.
>
> [Your comment in the code speaks about "autoload files" but these are really lock files - see (info "(elisp) File Locks") ]

Oops, will correct, I wanted to write "autosave" but lock files is indeed
the right appelation and better.

Thanks.

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.*Message ID: ***@***.***>
> [[End of PGP Encrypted Part]]

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen ***@***.***> writes:

> Yes, looks good, thanks. I'm also closing this one.

Fixed as well for the *-library functions using affixation (b4fe7717).
 
-- 
Thierry

**Comment by michael-heerdegen** [comment]
Looks reasonable, yes.

Thanks again -
Michael.
