### ISSUE TITLE
Multiple warnings from helm-core.el and helm-lib.el when starting emacs

### ISSUE THREAD

**Issue by hhyyrylainen** [emacs-helm/helm#2628]
### What happened?

When I start emacs I get a bunch of warnings from helm like this:
```
Warning (comp): helm-lib.el:315:17: Warning: reference to free variable ‘package--initialized’ Disable showing Disable logging
Warning (comp): helm-lib.el:310:17: Warning: reference to free variable ‘package-archive-contents’ Disable showing Disable logging
Warning (comp): helm-lib.el:316:34: Warning: reference to free variable ‘package-alist’ Disable showing Disable logging
Warning (comp): helm-lib.el:1165:46: Warning: the function ‘pos-eol’ is not known to be defined. Disable showing Disable logging
Warning (comp): helm-lib.el:1114:24: Warning: the function ‘pos-bol’ is not known to be defined. Disable showing Disable logging
Warning (comp): helm-lib.el:401:20: Warning: the function ‘kmacro--to-vector’ is not known to be defined. Disable showing Disable logging
Warning (comp): helm-lib.el:369:42: Warning: the function ‘package-desc-reqs’ is not known to be defined. Disable showing Disable logging
Warning (comp): helm-lib.el:362:12: Warning: the function ‘package--compile’ is not known to be defined. Disable showing Disable logging
Warning (comp): helm-lib.el:360:26: Warning: the function ‘package-desc-dir’ is not known to be defined. Disable showing Disable logging
Warning (comp): helm-lib.el:353:30: Warning: the function ‘package-desc-p’ is not known to be defined. Disable showing Disable logging
Warning (comp): helm-lib.el:343:14: Warning: the function ‘package-delete’ is not known to be defined. Disable showing Disable logging
Warning (comp): helm-lib.el:331:26: Warning: the function ‘package-desc-version’ is not known to be defined. Disable showing Disable logging
Warning (comp): helm-utils.el:601:39: Warning: reference to free variable ‘helm-mode-find-file-target-alist’ Disable showing Disable logging
Warning (comp): helm-core.el:7237:47: Warning: ‘special-display-buffer-names’ is an obsolete variable (as of 24.3); use ‘display-buffer-alist’ instead. Disable showing Disable logging
Warning (comp): helm-core.el:7237:23: Warning: ‘special-display-regexps’ is an obsolete variable (as of 24.3); use ‘display-buffer-alist’ instead. Disable showing Disable logging
Warning (comp): helm-core.el:7236:23: Warning: ‘display-buffer-function’ is an obsolete variable (as of 24.3); use ‘display-buffer-alist’ instead. Disable showing Disable logging
```

### How to reproduce?

I presume it is enough to install helm packages with M-x list-packages and maybe have something in your .emacs file to bytecompile all the installed packages.

### Helm Version

Melpa or NonGnuElpa

### Emacs Version

Emacs-28.3

### OS

GNU/Linux

### Relevant backtrace (if possible)

```text
I tried using the minimal configuration script but it doesn't work at all, it fails with:

$ .emacs.d/elpa/helm-20231108.1729/emacs-helm.sh
Loading /usr/share/emacs/site-lisp/site-start.d/autoconf-init.el (source)...
Loading /usr/share/emacs/site-lisp/site-start.d/clang-format.el (source)...
Loading /usr/share/emacs/site-lisp/site-start.d/clang-include-fixer.el (source)...
Loading /usr/share/emacs/site-lisp/site-start.d/clang-rename.el (source)...
Loading /usr/share/emacs/site-lisp/site-start.d/cmake-init.el (source)...
Loading /usr/share/emacs/site-lisp/site-start.d/desktop-entry-mode-init.el (source)...
Loading /usr/share/emacs/site-lisp/site-start.d/mercurial-site-start.el (source)...
Loading /usr/share/emacs/site-lisp/site-start.d/rpmdev-init.el (source)...
Loading /usr/share/emacs/site-lisp/site-start.d/systemtap-init.el (source)...
find: ‘.emacs.d/elpa/helm-20231108.1729’: Tiedostoa tai hakemistoa ei ole

(emacs:91422): Gtk-CRITICAL **: 08:52:29.380: gtk_distribute_natural_allocation: assertion 'extra_space >= 0' failed

(emacs:91422): Gtk-CRITICAL **: 08:52:29.398: gtk_distribute_natural_allocation: assertion 'extra_space >= 0' failed

(emacs:91422): Gtk-CRITICAL **: 08:52:29.413: gtk_distribute_natural_allocation: assertion 'extra_space >= 0' failed
```

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by thierryvolpiatto** [comment]
Henri Hyyryläinen ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
> What happened?
>
> When I start emacs I get a bunch of warnings from helm like this:
>
> Warning (comp): helm-lib.el:315:17: Warning: reference to free variable ‘package--initialized’ Disable showing Disable logging
> Warning (comp): helm-lib.el:310:17: Warning: reference to free variable ‘package-archive-contents’ Disable showing Disable logging
> Warning (comp): helm-lib.el:316:34: Warning: reference to free variable ‘package-alist’ Disable showing Disable logging
> Warning (comp): helm-lib.el:1165:46: Warning: the function ‘pos-eol’ is not known to be defined. Disable showing Disable logging
> Warning (comp): helm-lib.el:1114:24: Warning: the function ‘pos-bol’ is not known to be defined. Disable showing Disable logging
> Warning (comp): helm-lib.el:401:20: Warning: the function ‘kmacro--to-vector’ is not known to be defined. Disable showing Disable logging
> Warning (comp): helm-lib.el:369:42: Warning: the function ‘package-desc-reqs’ is not known to be defined. Disable showing Disable logging
> Warning (comp): helm-lib.el:362:12: Warning: the function ‘package--compile’ is not known to be defined. Disable showing Disable logging
> Warning (comp): helm-lib.el:360:26: Warning: the function ‘package-desc-dir’ is not known to be defined. Disable showing Disable logging
> Warning (comp): helm-lib.el:353:30: Warning: the function ‘package-desc-p’ is not known to be defined. Disable showing Disable logging
> Warning (comp): helm-lib.el:343:14: Warning: the function ‘package-delete’ is not known to be defined. Disable showing Disable logging
> Warning (comp): helm-lib.el:331:26: Warning: the function
> ‘package-desc-version’ is not known to be defined. Disable showing
> Disable logging

All these are not relevant, ignore them, they are protected but the
native compiler doesn't understand this.

> Warning (comp): helm-utils.el:601:39: Warning: reference to free
> variable ‘helm-mode-find-file-target-alist’ Disable showing Disable
> logging

This one is relevant, fixed now, thanks.

> 
> Warning (comp): helm-core.el:7237:47: Warning:
> ‘special-display-buffer-names’ is an obsolete variable (as of 24.3);
> use ‘display-buffer-alist’ instead. Disable showing Disable logging
> Warning (comp): helm-core.el:7237:23: Warning:
> ‘special-display-regexps’ is an obsolete variable (as of 24.3); use
> ‘display-buffer-alist’ instead. Disable showing Disable logging
> Warning (comp): helm-core.el:7236:23: Warning:
> ‘display-buffer-function’ is an obsolete variable (as of 24.3); use
> ‘display-buffer-alist’ instead. Disable showing Disable logging

These are obsolete function/vars warnings that should not popup but
Unfortunately native compile ignore local vars.

> How to reproduce?
>
> I presume it is enough to install helm packages with M-x list-packages and maybe have something in your .emacs file to bytecompile all the installed packages.
>
> Helm Version
>
> Melpa or NonGnuElpa
>
> Emacs Version
>
> Emacs-28.3
>
> OS
>
> GNU/Linux
>
> Relevant backtrace (if possible)
>
> I tried using the minimal configuration script but it doesn't work at all, it fails with:
>
> $ .emacs.d/elpa/helm-20231108.1729/emacs-helm.sh
> Loading /usr/share/emacs/site-lisp/site-start.d/autoconf-init.el (source)...
> Loading /usr/share/emacs/site-lisp/site-start.d/clang-format.el (source)...
> Loading /usr/share/emacs/site-lisp/site-start.d/clang-include-fixer.el (source)...
> Loading /usr/share/emacs/site-lisp/site-start.d/clang-rename.el (source)...
> Loading /usr/share/emacs/site-lisp/site-start.d/cmake-init.el (source)...
> Loading /usr/share/emacs/site-lisp/site-start.d/desktop-entry-mode-init.el (source)...
> Loading /usr/share/emacs/site-lisp/site-start.d/mercurial-site-start.el (source)...
> Loading /usr/share/emacs/site-lisp/site-start.d/rpmdev-init.el (source)...
> Loading /usr/share/emacs/site-lisp/site-start.d/systemtap-init.el
> (source)...

Don'y know why your Emacs is loading these files.

> find: ‘.emacs.d/elpa/helm-20231108.1729’: Tiedostoa tai hakemistoa ei ole

I don't understand this.
You can use LC_ALL=C to avoid messages in your locale language,
e.g. LC_ALL=C ./emacs-helm.sh

> (emacs:91422): Gtk-CRITICAL **: 08:52:29.380: gtk_distribute_natural_allocation: assertion 'extra_space >= 0' failed
>
> (emacs:91422): Gtk-CRITICAL **: 08:52:29.398: gtk_distribute_natural_allocation: assertion 'extra_space >= 0' failed
>
> (emacs:91422): Gtk-CRITICAL **: 08:52:29.413: gtk_distribute_natural_allocation: assertion 'extra_space >= 0' failed

These are related to emacs -Q not Helm script specifically.

> Minimal configuration
>
>   • [*] I agree using a minimal configuration
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.*Message ID: ***@***.***>

-- 
Thierry

**Comment by hhyyrylainen** [comment]
> Don'y know why your Emacs is loading these files.

I think these are all files from system packages. The first few are from `autoconf-2.71-5.fc38.noarch` and `clang-tools-extra-16.0.6-3.fc38.x86_64`.

> You can use LC_ALL=C to avoid messages in your locale language,

Here's that:

```bash
$ LC_ALL=C .emacs.d/elpa/helm-20231108.1729/emacs-helm.shLoading /usr/share/emacs/site-lisp/site-start.d/autoconf-init.el (source)...
Loading /usr/share/emacs/site-lisp/site-start.d/clang-format.el (source)...
Loading /usr/share/emacs/site-lisp/site-start.d/clang-include-fixer.el (source)...
Loading /usr/share/emacs/site-lisp/site-start.d/clang-rename.el (source)...
Loading /usr/share/emacs/site-lisp/site-start.d/cmake-init.el (source)...
Loading /usr/share/emacs/site-lisp/site-start.d/desktop-entry-mode-init.el (source)...
Loading /usr/share/emacs/site-lisp/site-start.d/mercurial-site-start.el (source)...
Loading /usr/share/emacs/site-lisp/site-start.d/rpmdev-init.el (source)...
Loading /usr/share/emacs/site-lisp/site-start.d/systemtap-init.el (source)...
find: '.emacs.d/elpa/helm-20231108.1729': No such file or directory
```

It was just a non-existent path error which is pretty strange as that does exist:
```bash
$ ls '.emacs.d/elpa/helm-20231108.1729'
emacs-helm.sh      helm-external.elc         helm-misc.el
helm-adaptive.el   helm-fd.el                helm-misc.elc
helm-adaptive.elc  helm-fd.elc               helm-mode.el
helm-autoloads.el  helm-files.el             helm-mode.elc
helm-bookmark.el   helm-files.elc            helm-net.el
helm-bookmark.elc  helm-find.el              helm-net.elc
helm-buffers.el    helm-find.elc             helm-occur.el
helm-buffers.elc   helm-font.el              helm-occur.elc
helm-color.el      helm-font.elc             helm-packages.el
helm-color.elc     helm-for-files.el         helm-packages.elc
helm-command.el    helm-for-files.elc        helm-pkg.el
helm-command.elc   helm-global-bindings.el   helm-regexp.el
helm-dabbrev.el    helm-global-bindings.elc  helm-regexp.elc
helm-dabbrev.elc   helm-grep.el              helm-ring.el
helm-easymenu.el   helm-grep.elc             helm-ring.elc
helm-easymenu.elc  helm-help.el              helm-semantic.el
helm.el            helm-help.elc             helm-semantic.elc
helm.elc           helm-id-utils.el          helm-sys.el
helm-elisp.el      helm-id-utils.elc         helm-sys.elc
helm-elisp.elc     helm-imenu.el             helm-tags.el
helm-epa.el        helm-imenu.elc            helm-tags.elc
helm-epa.elc       helm-info.el              helm-types.el
helm-eshell.el     helm-info.elc             helm-types.elc
helm-eshell.elc    helm-locate.el            helm-utils.el
helm-eval.el       helm-locate.elc           helm-utils.elc
helm-eval.elc      helm-man.el               helm-x-files.el
helm-external.el   helm-man.elc              helm-x-files.elc
```

**Comment by thierryvolpiatto** [comment]
Henri Hyyryläinen ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
>     Don'y know why your Emacs is loading these files.
>    
> I think these are all files from system packages. The first few are from autoconf-2.71-5.fc38.noarch and clang-tools-extra-16.0.6-3.fc38.x86_64.
>
>     You can use LC_ALL=C to avoid messages in your locale language,
>    
> Here's that:
>
> $ LC_ALL=C .emacs.d/elpa/helm-20231108.1729/emacs-helm.sh

Try instead:

$ LC_ALL=C /home/you/.emacs.d/elpa/helm-20231108.1729/emacs-helm.sh

> (source)...  find: '.emacs.d/elpa/helm-20231108.1729': No such file or
> directory
>
> It was just a non-existent path error which is pretty strange as that does exist:

Yes but I guess find expects a full path to your helm directory.

What you can do is symlinking emacs-helm.sh to e.g. ~/bin/helm and call
helm from your terminal.

You can also cd to your helm directory and call ./emacs-helm.sh.

Otherwise you will have to call emacs-helm.sh with a full path.

-- 
Thierry

**Comment by hhyyrylainen** [comment]
Okay calling the script from the folder it is in with `./emacs-helm.sh` does work. The terminal output no doesn't have any errors but in *messages* there's:

```
Unable to activate package ‘helm’.
Required package ‘wfnames-1.1’ is unavailable
```

I guess this also (almost) confirms that byte compiling helm is what triggers the warnings.

**Comment by thierryvolpiatto** [comment]
Henri Hyyryläinen ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
> Okay calling the script from the folder it is in with ./emacs-helm.sh does work. The terminal output no doesn't have any errors but in messages there's:
>
> Unable to activate package ‘helm’.
> Required package ‘wfnames-1.1’ is unavailable

Ha! I forgot to update emacs-helm.sh since we use wfnames as dependency,
is the following patch fix this error?

diff --git a/emacs-helm.sh b/emacs-helm.sh
index de65e44a..cc571188 100755
--- a/emacs-helm.sh
+++ b/emacs-helm.sh
@@ -233,7 +233,7 @@ cat > $CONF_FILE <<EOF
     (setq package-load-list
           (if (equal load-packages '("all"))
               '(all)
-            (append '((helm-core t) (helm t) (async t) (popup t))
+            (append '((helm-core t) (helm t) (async t) (popup t) (wfnames t))
                     (mapcar (lambda (p) (list (intern p) t)) load-packages)))))
 
   (package-initialize))

Thanks.

> I guess this also (almost) confirms that byte compiling helm is what triggers the warnings.

This is a different issue.

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.*Message ID: ***@***.***>

-- 
Thierry

**Comment by hhyyrylainen** [comment]
With that change I don't notice anymore errors happening when using `emacs-helm.sh`.

**Comment by thierryvolpiatto** [comment]
Henri Hyyryläinen ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
> With that change I don't notice anymore errors happening when using emacs-helm.sh.

Great! Thanks for your help on this.

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.*Message ID: ***@***.***>

-- 
Thierry
