### ISSUE TITLE
Add function to clean up any text in Helm input field

### ISSUE THREAD

**Issue by ReneFroger** [emacs-helm/helm#2629]
### Suggestion

A function that will clean up text in helm input field.

### Description

When I open helm swoop, it puts the text under the cursor into the input field. 

Then I have to remove the text input with backspace. So I'm considering to add a keybinding to remove the text in input field.

Something like: 
```
(after! helm-swoop
  (define-key helm-swoop-map ";" 'helm-clear-up-input)) 
```

When I looked in the Helm functions, I couldn't find any relevant functions for this. I found the functions helm-clean-up-minibuffer and `helm-cleanup` but they don't clean up the input in the helm input field.

**Comment by thierryvolpiatto** [comment]
ReneFroger ***@***.***> writes:

> 1.  ( ) multipart/mixed     (*) text/html           
>
> Suggestion
>
> A function that will clean up text in helm input field.

It is C-k.

> Description
>
> When I open helm swoop, it puts the text under the cursor into the input field.

You should not use anymore helm-swoop, you have instead helm-occur, it
is integrated as well with helm-mini or helm-buffers-list (C-s on marked
buffers).
helm-occur doesn't include text at point in minibuffer, it uses default,
that's mean that text at point is searched automatically but you have
nothing in prompt, if you want to search for something else just start
to type.

> When I looked in the Helm functions, I couldn't find any relevant
> functions for this.



> I found the functions helm-clean-up-minibuffer and helm-cleanup but
> they don't clean up the input in the helm input field.

It is helm-delete-minibuffer-contents (C-k) ;-)
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.*Message ID: ***@***.***>

-- 
Thierry

**Comment by ReneFroger** [comment]
Strange that I couldn't find that command earlier. My mind was probably still stuck in 'clear' instead of delete. 

I will give a serious look into helm-occur. Thanks for your advice, Thierry!

**Comment by thierryvolpiatto** [comment]
ReneFroger ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
> Strange that I couldn't find that command earlier. My mind was probably still stuck in 'clear' instead of delete.
>
> I will give a serious look into helm-occur. Thanks for your advice, Thierry!

Hello René, you will find it with C-h m while in Helm ("Helm map" section).

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.*Message ID: ***@***.***>

-- 
Thierry
