### ISSUE TITLE
frameset-register-p in helm-ring.el undefined

### ISSUE THREAD

**Issue by xiongtx** [emacs-helm/helm#2630]
### What happened?

`helm-register-candidates` throws an error b/c `frameset-register-p` is not found.

### How to reproduce?

Evaluate `(helm-register-candidates)`.

### Helm Version

Master branch

### Emacs Version

Emacs-29.1

### OS

GNU/Linux

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by xiongtx** [comment]
It looks like the issue is that [`frameset`](https://github.com/emacs-mirror/emacs/blob/emacs-29/lisp/frameset.el#L1403-L1406) needs to be required first.

**Comment by thierryvolpiatto** [comment]
Thanks, fixed.
