### ISSUE TITLE
Set up GitHub Sponsors as an additional source of donations

### ISSUE THREAD

**Issue by RaulPPelaez** [emacs-helm/helm#2632]
### Suggestion

The Sponsor program allows other developers in GH to setp up a donation with a couple of clicks https://docs.github.com/en/sponsors/receiving-sponsorships-through-github-sponsors/setting-up-github-sponsors-for-your-personal-account

Perhaps it would encourage more donators!

I have been using HELM for years and I love it.

### Description

N/A

### Solutions

N/A

**Comment by thierryvolpiatto** [comment]
Sorry for late reply.  Yes I will try to look into this for 2024.
Thanks.

**Comment by ReneFroger** [comment]
Any update on this? I would like to sponsor you via Github.

**Comment by thierryvolpiatto** [comment]
ReneFroger ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
> Any update on this? I would like to sponsor you via Github.

Sorry, didn't have the time to manage this yet.

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.*Message ID: ***@***.***>

-- 
Thierry

**Comment by ReneFroger** [comment]
Could you perhaps enable it this month?

**Comment by thierryvolpiatto** [comment]
ReneFroger ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
> Could you perhaps enable it this month?

I don't think so, I don't have yet all informations related to french
taxes, don't want to have trouble with this.

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.*Message ID: ***@***.***>

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
I think it is done, if I didn't do mistakes the sponsor button should work.
Thanks for helping on this.

**Comment by RaulPPelaez** [comment]
Thanks @thierryvolpiatto , you are the best.

**Comment by thierryvolpiatto** [comment]
Thanks! Closing now.
