### ISSUE TITLE
helm with a list of sources can only select candidates from the first source in the list

### ISSUE THREAD

**Issue by smferris** [emacs-helm/helm#2637]
### What happened?

I just upgraded both emacs (to 29.2) and helm (from some version from 2022 to 84a49c005310b6f823ae554c0d17c3b63dce6f59), and some of my custom helm functions have been broken by what I think is a bug.

I used to be able to pass (helm :sources ...) a list of sources created dynamically.  I still can, and the helm window will display all of the candidates from all sources as it used to, but the modeline candidate count only counts the candidates from the first source in the list, and C-n/down and C-p/up cycle between candidates from only the first source and never reach the other sources.

I tested it on Linux as well since the emacs-helm.sh script won't work on macOS (find doesn't have -printf),
and it behaved the same on Linux using emacs-helm.sh as in my normal emacs session on macOS.

### How to reproduce?

```
(defun helm-sources-test ()
  "A simplified example of passing a list of sources to helm.
Only a b c will be reachable, and d e f are displayed but unreachable."
  (interactive)
  (helm :sources (list
                  (helm-build-sync-source "source 1"
                    :candidates '(a b c))
                  (helm-build-sync-source "source 2"
                    :candidates '(d e f)))
        :buffer "*helm test*"))
```

### Helm Version

Master branch

### Emacs Version

Emacs-29.1

### OS

MacOSX

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by smferris** [comment]
Nevermind, just a changed default for helm-move-to-line-cycle-in-source tripping me up.

**Comment by thierryvolpiatto** [comment]
"Scott M. Ferris" ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
> Nevermind, just a changed default for helm-move-to-line-cycle-in-source tripping me up.

Glad you found it, and anyway you can move from one source to the other
with helm-previous/next-source (left/right or C-o/M-o) which is
documented (C-h m).  I will add as soon as possible an entry in
documentation about helm-move-to-line-cycle-in-source.

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.*Message ID: ***@***.***>

-- 
Thierry
