### ISSUE TITLE
Error with helm-core : Symbol’s function definition is void: def-edebug-elem-spec

### ISSUE THREAD

**Issue by SvenRieke** [emacs-helm/helm#2641]
### What happened?

Helm packages updated to 20240301.2001 from Melpa yesterday.
Since then any helm command is failing with **Symbol’s function definition is void: def-edebug-elem-spec**
I see it is being using in the helm-core package.

### How to reproduce?

Helm packages updated to 20240301.2001 from Melpa yesterday.
Keybindings:
`  :bind (("C-c h"       . helm-command-prefix)
         ("M-x"         . helm-M-x)
         ("C-x C-m"     . helm-M-x)
         ("C-x b"       . helm-mini)
         ("C-x C-b" . helm-buffers-list)
         ("C-x C-f"     . helm-find-files)
             ("C-h f"   . helm-apropos)
             ("C-h i"   . helm-info-emacs)
         ("C-c y"   . helm-show-kill-ring)
             ("C-h C-l" . helm-locate-library)
         ("C-x C-r" . helm-recentf)
         ("C-x r l" . helm-bookmarks))
`
helm-M-x, helm-find-files, helm-buffers-list, etc, all are giving the same error.

### Helm Version

Melpa or NonGnuElpa

### Emacs Version

Emacs-27.1

### OS

GNU/Linux

### Relevant backtrace (if possible)

```text
Debugger entered--Lisp error: (void-function def-edebug-elem-spec)
  def-edebug-elem-spec(helm-acase-GUARD (&or (symbolp form) sexp))
  byte-code("\300\301\302\303#\210\304\305\306\"\207" [put helm-aand edebug-form-spec (&rest form) def-edebug-elem-spec helm-acase-GUARD (&or (symbolp form) sexp)] 4)
  require(helm-lib)
  eval-buffer(#<buffer  *load*> nil "/home/sven/.emacs.d/elpa/helm-core-20240301.2001/h..." nil t)  ; Reading at buffer position 1171
  load-with-code-conversion("/home/sven/.emacs.d/elpa/helm-core-20240301.2001/h..." "/home/sven/.emacs.d/elpa/helm-core-20240301.2001/h..." nil t)
  require(helm-core)
  byte-code("\300\301!\210\300\302!\210\303\304\305\306\307$\210\303\310\305\306\307$\210\303\311\305\306\307$\210\312\313!\207" [require helm-core helm-global-bindings autoload helm-info-emacs "helm-info" nil t helm-info-gnus helm-info-at-point provide helm] 5)
  require(helm)
  byte-code("\300\301!\210\300\302!\210\300\303!\210\300\304!\210\300\305!\210\300\306!\210\300\307!\210\300\310!\210\300\311!\210\300\312!\210\300\313!\210\300\314!\210\300\315..." [require cl-lib helm helm-types helm-utils helm-grep helm-help helm-locate helm-tags helm-buffers tramp filenotify image-mode image-dired] 2)
  autoload-do-load((autoload "helm-files" "Preconfigured `helm' for helm implementation of `f..." t nil) helm-find-files)
  command-execute(helm-find-files)
```

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by SvenRieke** [comment]
Using the minimal configuration script, I get the same warning during the startup and same error with all helm commands.

**Comment by michael-heerdegen** [comment]
SvenRieke ***@***.***> writes:

> Emacs-27.1

> Debugger entered--Lisp error: (void-function def-edebug-elem-spec)

The function has been introduced in Emacs 28.1, it's newer than your
Emacs version is.  Maybe Thierry can replace the call with what the
function does (which is not much).

**Comment by michael-heerdegen** [comment]
SvenRieke ***@***.***> writes:

> Debugger entered--Lisp error: (void-function def-edebug-elem-spec)

And I guess (defalias 'def-edebug-elem-spec #'ignore) before loading
Helm should work as a workaround.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen ***@***.***> writes:

> SvenRieke ***@***.***> writes:
>
>> Emacs-27.1
>
>> Debugger entered--Lisp error: (void-function def-edebug-elem-spec)
>
> The function has been introduced in Emacs 28.1, it's newer than your
> Emacs version is. Maybe Thierry can replace the call with what the
> function does (which is not much).

Done, thanks.

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.*Message ID: ***@***.***>

-- 
Thierry

**Comment by SvenRieke** [comment]
Yes, thanks, the **defalias** as work-around is doing its job.
Great, thanks for the quick response, I was missing my helm'd Emacs.
It's such an awesome extension, a really great project!

**Comment by SvenRieke** [comment]
Just tested the new package on Melpa, it works like a charm now.
Thanks a lot!

**Comment by thierryvolpiatto** [comment]
SvenRieke ***@***.***> writes:

> Just tested the new package on Melpa, it works like a charm now.

Great, thanks to confirm and sorry for inconvenience.

> 
> Thanks a lot!
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.*Message ID: ***@***.***>

-- 
Thierry
