### ISSUE TITLE
Emacs' "while-no-input" prevents discoverability/debugging of all Helm funcs invoked after "helm-update" 

### ISSUE THREAD

**Issue by karbiv** [emacs-helm/helm#2648]
### What happened?

Helm uses `while-no-input` Emacs' macro to wrap computation of current candidates that are discarded each time when new keyboard input occurs during its evaluation, in order to recompute candidate matches anew and refill Helm buffer.
That macro `throw`s up a call stack to `helm--collect-matches`(invoked in `helm-update`), so any function called by code after `helm-update` is not debuggable by instrumenting with `edebug` for stepping. Pressing space key to step forward in edebug is caught as input by `while-no-input` and thrown up to `helm--collect-matches`.

Helm disables `while-no-input` for remote files in a `helm--maybe-use-while-no-input`, and this conditional can be augmented by a new boolean defcustom "helm-update-edebug" that when set also disables `while-no-input` and all the code in sources/filters/formatters becomes debuggable.

### How to reproduce?

Instrument by `edebug`(C-u C-M-x) one of these functions:
helm-core.el: `helm-process-filtered-candidate-transformer`
helm-core.el: `helm-apply-functions-from-source`
helm-buffers.el: `helm-buffer--details`

Launch `helm-mini` and press space to step forward in those funcs, or "c" to continue.

### Helm Version

Master branch

### Emacs Version

Emacs-29.1

### OS

GNU/Linux

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by karbiv** [comment]
If it's agreed to be an issue, I have a PR for it.

**Comment by thierryvolpiatto** [comment]
Alexander Karbivnichiy ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
> If it's agreed to be an issue, I have a PR for it.

Yes, a PR would be nice, however I am not sure only disabling
while-no-input is enough as helm continue reading all the input
incoming, this overriding all edebug bindings, so probably this would
need to be coupled with helm-suspend-update, but let see your PR and we
will see what we can do.

Thanks.

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.*Message ID: ***@***.***>

-- 
Thierry

**Comment by karbiv** [comment]
> so probably this would need to be coupled with helm-suspend-update

There's already `helm-suspend-update-flag` guard in lambda for `run-with-idle-timer` in `helm-read-from-minibuffer`. It can be toggled by `helm-toggle-suspend-update`.

That PR https://github.com/emacs-helm/helm/pull/2649 just makes possible to turn off `while-no-input` like Helm does for  remote files.

**Comment by thierryvolpiatto** [comment]
Alexander Karbivnichiy ***@***.***> writes:

>     so probably this would need to be coupled with helm-suspend-update
>    
> There's already helm-suspend-update-flag guard in lambda for
> run-with-idle-timer in helm-read-from-minibuffer. It can be toggled by
> helm-toggle-suspend-update.

Yes, I know this, I was thinking of a command suspending update and at
the same time disabling while-no-input (setting your helm-update-edebug
flag to t) but what you did should be enough.

-- 
Thierry

**Comment by karbiv** [comment]
Another question, is `helm-while-no-input` a public API, is it called outside of Helm?

Because the only one place where it's called in Helm is `helm--maybe-use-while-no-input`.
The purpose of `helm-while-no-input` is to replace Emacs' `while-no-input` so that it would not return `t` when exiting on new key input event.
But `helm--collect-matches` has this guard that corrects `while-no-input` return behavior:

`(unless (eq matches t) matches)`

It works with built-in `while-no-input`.

**Comment by thierryvolpiatto** [comment]
Alexander Karbivnichiy ***@***.***> writes:

> Another question, is helm-while-no-input a public API, is it called outside of Helm?

No.

> Because the only one place where it's called in Helm is helm--maybe-use-while-no-input.
> The purpose of helm-while-no-input is to replace Emacs' while-no-input so that it would not return t when exiting on new key input event.
> But helm--collect-matches has this guard that corrects while-no-input return behavior:
>
> (unless (eq matches t) matches)

Yes, probably a vestige of when I was using a plain while-no-input, but
maybe in some cases t is returned as well? As long as it doesn't create
a particular bug I prefer not removing this guard.

> It works with built-in while-no-input.

Not always, in rare cases input-pending-p may causes trouble IIRC.

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.*Message ID: ***@***.***>

-- 
Thierry

**Comment by karbiv** [comment]
> Not always, in rare cases input-pending-p may causes trouble IIRC.

Ah, I see. Ok.

**Comment by karbiv** [comment]
> Not always, in rare cases input-pending-p may causes trouble IIRC.

Ah, I see. Ok.
