### ISSUE TITLE
endless loop in 'helm-candidates-in-buffer-search-default-fn', re-search-forward

### ISSUE THREAD

**Issue by karbiv** [emacs-helm/helm#2657]
### What happened?

Completions buffer may enter endless loop, stopped by C-g.

Can be easily fixed by using `helm-re-search-forward` instead of `re-search-forward`.

https://github.com/emacs-helm/helm/blob/d2aed1340c9dcddee776e88efbe2bd0aaf425230/helm-core.el#L6711-L6715

### How to reproduce?

C-h f
type "??"
try to delete by backspace

### Helm Version

Master branch

### Emacs Version

Emacs-29.1

### OS

GNU/Linux

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by thierryvolpiatto** [comment]
Alexander Karbivnichiy ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
> What happened?
>
> Completions buffer may enter endless loop, stopped by C-g.
>
> Can be easily fixed by using helm-re-search-forward instead of re-search-forward.
>
> https://github.com/emacs-helm/helm/blob/d2aed1340c9dcddee776e88efbe2bd0aaf425230/helm-core.el#L6711-L6715

Thanks fixed.

-- 
Thierry
