### ISSUE TITLE
"helm-split-window-default-side 'other" and helm-always-two-windows

### ISSUE THREAD

**Issue by karbiv** [emacs-helm/helm#2659]
### What happened?

This setting should work as expected, using other existing window for Helm buffer:

`(setq helm-split-window-default-side 'other)`

It doesn't.
It is masked by `helm-always-two-windows` that is by default is `t` in Helm. It makes Helm delete other windows before `helm-split-window-default-side` looks for it, and in result splits windows always horizontally.

### How to reproduce?

In emacs-helm.sh *scratch* buffer eval:

`(setq helm-split-window-default-side 'other)`

Create other vertical window "C-x 3". Open Helm buffer.

### Helm Version

Master branch

### Emacs Version

Emacs-29.1

### OS

GNU/Linux

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by karbiv** [comment]
PR #2660

**Comment by thierryvolpiatto** [comment]
Alexandr Karbivnichiy ***@***.***> writes:

> What happened?
>
> This setting should work as expected, using other existing window for Helm buffer:
>
> (setq helm-split-window-default-side 'other)

Not with helm-always-two-windows.

> It doesn't.  It is masked by helm-always-two-windows that is by
> default is t in Helm. It makes Helm delete other windows before
> helm-split-window-default-side looks for it, and in result splits
> windows always horizontally.

This is the expected behavior, it is documented in docstring.

> How to reproduce?
>
> In emacs-helm.sh scratch buffer eval:
>
> (setq helm-split-window-default-side 'other)
>
> Create other vertical window "C-x 3". Open Helm buffer.
>
> Helm Version
>
> Master branch
>
> Emacs Version
>
> Emacs-29.1
>
> OS
>
> GNU/Linux
>
> Relevant backtrace (if possible)
>
> No response
>
> Minimal configuration
>
>   • [*] I agree using a minimal configuration
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.*Message ID: ***@***.***>

-- 
Thierry

**Comment by karbiv** [comment]
> Not with helm-always-two-windows.

From user's point of view "_other window_" is still "_two windows_", but it requires to turn **off** `helm-always-two-windows`.
And it looks like this:

```
(setq
    helm-always-two-windows nil
    helm-split-window-default-side 'other)
```

Somewhat strange after seeing that in Vertico it's one unambiguous configuration var.
