### ISSUE TITLE
Helm buffers path format. Visual clutter.

### ISSUE THREAD

**Issue by karbiv** [emacs-helm/helm#2664]
### What happened?

`helm-mini` shows buffer paths wrapped with braces and '_in_' prefix word, _(in ~/some/path/file)_.
This format is just a visual clutter, consumes line's width and is not informative.

It's hard-coded in `helm-mode.el : helm-completing-read-buffer-affixation() `at line 1146.
https://github.com/emacs-helm/helm/blob/6ae44dba0cb72a3a6950cbe36d104db9c69dfb49/helm-mode.el#L1146-L1160

The easiest solution is to remove braces and "in".

### How to reproduce?

`helm-mini`

### Helm Version

Master branch

### Emacs Version

Emacs-29.1

### OS

GNU/Linux

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by thierryvolpiatto** [comment]
Alexandr Karbivnichiy ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
> What happened?
>
> helm-mini shows buffer paths wrapped with braces and in word, (in ~/some/path/file).
> This format is just a visual clutter, consumes line's width and is not informative.
>
> It's hard-coded in helm-mode.el : helm-completing-read-buffer-affixation() at line 1146.
> https://github.com/emacs-helm/helm/blob/6ae44dba0cb72a3a6950cbe36d104db9c69dfb49/helm-mode.el#L1146-L1160

This doesn't affect helm-mini, the code is in helm-buffers, but if we
change this in one place, we should do the same everywhere for consistency.

Will look at this soon.

-- 
Thierry

**Comment by karbiv** [comment]
> This doesn't affect helm-mini, the code is in helm-buffers, but if we change this in one place, we should do the same everywhere for consistency.

This issue was created from the UX point of view. Most users use `helm-mini` to have recent files besides buffers.
But that wrapping of buffer paths with braces and "in" prefix looks redundant if not annoying.

BTW in Vertico&Consult "recent files" source breaks the table layout by long filepaths, because all sources there share common column width somehow. So buffer names column becomes as wide as the longest filepath in "recent files" source.
Helm looks better in this aspect, sources layouts are independent from each other.

**Comment by thierryvolpiatto** [comment]
Done, thanks.
