### ISSUE TITLE
Error msg "Key sequence M - m SPC h SPC d SPC m starts with non-prefix key"

### ISSUE THREAD

**Issue by sunlin7** [emacs-helm/helm#2671]
### What happened?

There are error msg "Key sequence M - m SPC h SPC d SPC m starts with non-prefix key" for the `describe-mode` was binded to "M-m h d m" before loading `helm`.
Here are the lines to reproduce the issue, which will bind the `describe-mode` before loading the helm:
```emacs-lisp
(global-set-key "M-m h d m" 'describe-mode)
(load-file "<PATH>/helm-core-20240510.1815/helm-core-autoloads.el")
(load-file "<PATH>/helm-20240510.1833/helm-autoloads.el")
(call-interactively 'helm)
```

The helm has special code to deal the `describe-mode` and leads the issue:
https://github.com/emacs-helm/helm/blob/6d23a65ca6bcb6c0ea6f21f3cf2e58f8570ef75b/helm-core.el#L479-L481
```
(defvar helm-map
;;...
    (define-key map (kbd "M-m")        #'helm-toggle-all-marks)
;;...
    ;; Use `describe-mode' key in `global-map'.
    (dolist (k (where-is-internal #'describe-mode global-map))
      (define-key map k #'helm-help))
;;...
```
This issue acctually happened on *Spacemacs*, was disscussed in https://github.com/syl20bnr/spacemacs/pull/16397.

### How to reproduce?

N/A

### Helm Version

Master branch

### Emacs Version

Emacs-29.1

### OS

GNU/Linux

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by thierryvolpiatto** [comment]
"lin.sun" ***@***.***> writes:

> What happened?
>
> There are error msg "Key sequence M - m SPC h SPC d SPC m starts with non-prefix key" for the describe-mode was binded to "M-m h
> d m" before loading helm.
> Here are the lines to reproduce the issue, which will bind the describe-mode before loading the helm:
>
> (global-set-key "M-m h d m" 'describe-mode)

I don't understand in why this is related to Helm:

1) emacs -Q
2) Eval in scratch buffer: 
(global-set-key (kbd "M-m h d m") 'describe-mode)
=> Debugger entered--Lisp error: (error "Key sequence M-m h d m starts with non-prefix key ...")

As expected...

-- 
Thierry

**Comment by sunlin7** [comment]
Hi @thierryvolpiatto 
Currently helm will stop to work totally if user binding `describe-mode` to `M-m h d m` before loading helm.
The issue only affects one key-binding,  helm can continue works for other features. 
So if helm gives a user-error friendly then continue, it would be better.

**Comment by thierryvolpiatto** [comment]
"lin.sun" ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
> Hi @thierryvolpiatto
> Currently helm will stop to work totally if user binding describe-mode
> to M-m h d m before loading helm.

As (global-set-key (kbd "M-m h d m") 'describe-mode) or 
(global-set-key "M-m h d m" 'describe-mode) return an error I hardly see
how you can bind such key, please enlight me.

> 
> The issue only affects one key-binding, helm can continue works for
> other features.  So if helm gives a user-error friendly then continue,
> it would be better.

Same as above, if you have in your init file:

(global-set-key (kbd "M-m h d m") 'describe-mode)
and
(require 'helm)

(require 'helm) will never run, and all what is after also.

So I wonder how one can bind such a key and continue loading helm
afterward.

-- 
Thierry

**Comment by michael-heerdegen** [comment]
"lin.sun" ***@***.***> writes:

> The issue only affects one key-binding, helm can continue works for
> other features.  So if helm gives a user-error friendly then continue,
> it would be better.

I understand your viewpoint as a user.  But such a rule would apply to
_any_ key binding done anywhere in Emacs or by any other package.  And
this is not how Emacs is designed, or how key bindings are intended to
work or be installed.  AFAIU, your problem is not different from any
other conflicting key bindings.

So, if you explicitly define keys that are used by any package you want
to use, this problem has to be resolved by you, in your configuration.

When the conflicting binding's origin is something not under your
control, e.g. another package, that would be a different story (you
didn't tell us so far).

**Comment by sunlin7** [comment]
Hi @thierryvolpiatto @michael-heerdegen 
Thanks for your explaination, and close this ticket for the original issue hacked by alias `describe-mode` to new name.
Refer: https://github.com/syl20bnr/spacemacs/pull/16397
