### ISSUE TITLE
`helm-delete-char-backward` does not support `delete-active-region`

### ISSUE THREAD

**Issue by CyberShadow** [emacs-helm/helm#2675]
### What happened?

While Helm is active, if I select some some text in the minibuffer, and press Backspace, it only deletes the character before point.

Looking at the implementation of `helm-delete-char-backward`, it seems to invoke `delete-char` unconditionally.

`delete-active-region` seems to be enabled by default in Emacs 29.1.

### How to reproduce?

1. Install Helm
2. Invoke `helm-M-x`
3. Type something, then press <kbd>Home</kbd>, <kbd>Shift</kbd>+<kbd>End</kbd>, <kbd>Backspace</kbd>

### Helm Version

Melpa or NonGnuElpa

### Emacs Version

Emacs-29.1

### OS

GNU/Linux

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by thierryvolpiatto** [comment]
Vladimir Panteleev ***@***.***> writes:

> What happened?
>
> While Helm is active, if I select some some text in the minibuffer, and press Backspace, it only deletes the character before point.
>
> Looking at the implementation of helm-delete-char-backward, it seems to invoke delete-char unconditionally.
>
> delete-active-region seems to be enabled by default in Emacs 29.1.
>
> How to reproduce?
>
>  1. Install Helm
>  2. Invoke helm-M-x
>  3. Type something, then press Home, Shift+End, Backspace

Ah! shift selection! Have completely forgotten  about it, I rarely use it and
never used it in helm.
Should be fixed now.
Thanks.

> Helm Version
>
> Melpa or NonGnuElpa
>
> Emacs Version
>
> Emacs-29.1
>
> OS
>
> GNU/Linux
>
> Relevant backtrace (if possible)
>
> No response
>
> Minimal configuration
>
>   • [*] I agree using a minimal configuration
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.*Message ID: ***@***.***>

-- 
Thierry

**Comment by CyberShadow** [comment]
Works, thank you!
