### ISSUE TITLE
helm-occur stopped to work with Emacs 29

### ISSUE THREAD

**Issue by pietro-coretto** [emacs-helm/helm#2682]
### What happened?

I upgaded from Emacs 28 to  Emacs 29.4 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo
 version 1.16.0). Afterwards I reinstalled helm using  `helm-20240726.954` from MELPA repository.

After this my loved command for incremental search over a file `M-x helm-occur` stopped to work. When I search over a buffer using  `M-x helm-occur` I get the following error

```
helm-grep--ag-command: Wrong type argument: stringp, nil
```

### How to reproduce?

When I search over a buffer using  `M-x helm-occur` I get the following error

```
helm-grep--ag-command: Wrong type argument: stringp, nil
```

By the way if I do the test using  `emacs-helm.sh` it does not work as well and gives the same error as above

### Helm Version

Melpa or NonGnuElpa

### Emacs Version

Emacs-29.4

### OS

GNU/Linux

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by pietro-coretto** [comment]
Didn't know about it. I also installed  [helm-ag](https://stable.melpa.org/#/helm-ag) from MELPA and gave the same problem because nobody says that all this depends on the [ag silver searcher package](https://github.com/ggreer/the_silver_searcher). Therefore installed 

 [ag silver searcher package](https://github.com/ggreer/the_silver_searcher)
 [helm-ag](https://stable.melpa.org/#/helm-ag)

and now everything works!

Thanks. Do you think I can close this issue?

**Comment by thierryvolpiatto** [comment]
Pietro Coretto ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
> Didn't know about it. I also installed helm-ag from MELPA and gave the same problem because nobody says that all this depends on the ag silver searcher package. Therefore installed
>
> ag silver searcher package

Nowadays you have better time using rg which is much faster and
maintained.

> helm-ag

You don't need helm-ag package, helm already provides this
(helm-do-grep-ag) and it is integrated in helm-find-files as well.

> and now everything works!
>
> Thanks. Do you think I can close this issue?

Yes, thanks.

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.*Message ID: ***@***.***>

-- 
Thierry

**Comment by pietro-coretto** [comment]
All works now!
