### ISSUE TITLE
Cannot split side window or parent of side window

### ISSUE THREAD

**Issue by ipocentro87** [emacs-helm/helm#2686]
### What happened?

While trying to access the actions from helm minibuffer, it stops me by telling that it "cannot split side window or parent of side window"

### How to reproduce?

```
(helm-mode 1)

(setq helm-always-two-windows nil)
(setq helm-default-display-buffer-functions '(display-buffer-in-side-window))
```
Helm version 4.0

![Screenshot 2024-09-10 at 14 10 33](https://github.com/user-attachments/assets/aa48b4e6-dd5d-4432-a207-70281676dd5c)

### Helm Version

Melpa or NonGnuElpa

### Emacs Version

Emacs-29.1

### OS

MacOSX

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by thierryvolpiatto** [comment]
Marcello Ranone ***@***.***> writes:

> What happened?
>
> While trying to access the actions from helm minibuffer, it stops me by telling that it "cannot split side window or parent of side window"

As expected with `display-buffer-in-side-window`.

See the documentation of side-windows.

> How to reproduce?
>
> (helm-mode 1)
>
> (setq helm-always-two-windows nil)
> (setq helm-default-display-buffer-functions '(display-buffer-in-side-window))

You should not do this, side-windows are not splittable,
you really have to know what you are doing when modifying this variable. 

-- 
Thierry

**Comment by ipocentro87** [comment]
Hi @thierryvolpiatto thanks for your answer.
What I'd like to do is to have the actions panel to be displayed in the minibuffer, without creating a new buffer. It worked for me before, now it doesn't work anymore.
I am not an expert on this and I hope you can forgive me. Do you know how I can achieve that?

**Comment by thierryvolpiatto** [comment]
Marcello Ranone ***@***.***> writes:

> Hi @thierryvolpiatto thanks for your answer.  What I'd like to do is
> to have the actions panel to be displayed in the minibuffer, without
> creating a new buffer.

It is not possible, in Helm the minibuffer is used only to read the user input.

> It worked for me before, now it doesn't work anymore.

Hmm, so you are speaking of something else, before the default was to
display the action buffer in the helm-buffer now the default is to split
the window to keep a view of the helm-buffer with the selected candidate
while choosing action.

> I am not an expert on this and I hope you can forgive me.

You are welcome.

> Do you know how I can achieve that?

You can control this by customizing
`helm-show-action-window-other-window`.

-- 
Thierry

**Comment by ipocentro87** [comment]
I'd like to go back to the previous default behaviour. Alternatively, I'd be fine to have the split, but still I'd like the helm buffer to be opened below on the full frame width, and the action buffer be a split of that helm buffer.

**Comment by ipocentro87** [comment]
It looks like this seems to mimic the same behaviour
```
(setq helm-default-display-buffer-functions '(display-buffer-at-bottom))
```

However, when I hit tab, and then tab again to exit from the action buffer, the helm buffer becomes taller. Apart from this I'm OK with this.

**Comment by thierryvolpiatto** [comment]
Marcello Ranone ***@***.***> writes:

> I'd like to go back to the previous default behaviour.

(setq helm-show-action-window-other-window nil)

> Alternatively, I'd be fine to have the split, but still I'd like the
> helm buffer to be opened below on the full frame width, and the action
> buffer be a split of that helm buffer.

It is what I use, and it is the default, see screenshot on next post.



> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.*Message ID: ***@***.***>

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Marcello Ranone ***@***.***> writes:

> It looks like this seems to mimic the same behaviour
>
> (setq helm-default-display-buffer-functions '(display-buffer-at-bottom))

As I said you should not modify this, at least basically like that, what
you want is to configure how helm split its window with
`helm-split-window-default-side`.

For example:

(setq helm-always-two-windows t) ; This is the default.
(setq helm-split-window-default-side 'bottom) ; This is the default as well.

> However, when I hit tab, and then tab again to exit from the action
> buffer, the helm buffer becomes taller.

Of course because window.el doesn't know how to manage helm windows so it
use split-window-sensibly which works more or less.

> Apart from this I'm OK with this.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.*Message ID: ***@***.***>

-- 
Thierry

**Comment by ipocentro87** [comment]
This alone is not working for me:
```
(setq helm-show-action-window-other-window nil)
(setq helm-always-two-windows t) ; default
(setq helm-split-window-inside-p nil) ; default
(setq helm-default-display-buffer-functions nil) ; default
```

What I get is that the window layout changes and I only see the helm and the current buffer. What I want is that even if I have two windows displayed, and I do let's say helm-mini on one of the two buffers, the helm buffer is showing at the bottom over the whole frame length regardless of the current window disposition.

**Comment by thierryvolpiatto** [comment]
Marcello Ranone ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
> This alone is not working for me:

It IS working, but it is not what you want apparently ;-)

> (setq helm-show-action-window-other-window nil)
> (setq helm-always-two-windows t) ; default
> (setq helm-split-window-inside-p nil) ; default
> (setq helm-default-display-buffer-functions nil) ; default
>
> What I get is that the window layout changes and I only see the helm
> and the current buffer.

This is what is expected with helm-always-two-windows.

> What I want is that even if I have two windows displayed, and I do
> let's say helm-mini on one of the two buffers, the helm buffer is
> showing at the bottom over the whole frame length regardless of the
> current window disposition.

AFAIK there is no window-* function doing this in Emacs appart
`display-buffer-in-side-window` which makes window unsplittable.
You can if you _really_ want to use this, force
display-buffer-in-side-window to allow splitting your helm window, but
expect other problems (I have not in mind right now):

(setq helm-default-display-buffer-functions '(display-buffer-in-side-window))
(setq window-combination-resize 'side)
 
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.*Message ID: ***@***.***>

-- 
Thierry

**Comment by ipocentro87** [comment]
Ok I see, thanks a lot for the support. I'll stick with what I have done above as it seems to work the way I want.
We can close the ticket if you want 👍
