### ISSUE TITLE
Simplified search (helm-occur)

### ISSUE THREAD

**Issue by Addlai** [emacs-helm/helm#2687]
### Suggestion

As I think is typical, I have Ctrl-S bound to helm-occur. However, helm-occur seems to cast its net a lot wider than I want in most cases. First, it has a rather loose kind of matching that pulls in too many candidates for my liking. Moreover, recently (several months ago) the behavior seems to have changed; it now pulls in matches in other files, with some sort of grep-like functionality. I very, very, very strongly dislike this behavior. I find that I've essentially stopped using helm-occur as a result and instead almost always fall back on Emacs's basic isearch-forward, which I strongly prefer to whatever helm-occur is doing.

### Description

Can someone perhaps suggest a happy medium, that would give me a somewhat improved ui using helm, but for which the search candidates are pretty close to what isearch-forward would give, or at least has behavior under my more direct control. In particular, under no circumstances do I EVER want grep-like functionality mixed with in-buffer searches, or matches in files other than the current buffer appearing for any reason. If this isn't possible with helm, I need to stop using helm, and if it isn't possible with Emacs at all, I'll stop using Emacs. This is completely non-negotiable.

### Solutions

I am not particular that this needs to be done using helm. If it's easier to do what I want by bypassing helm, that's fine. I think at some point, I'll probably be moving on from helm, but in the near term I just want as little disruption as possible. However, the issue of matches in files other than the current buffer is absolutely non-negotiable, so if it's not possible, I suppose now is the time to move on. In any case, any advice is appreciated.

**Comment by thierryvolpiatto** [comment]
Sorry for late reply, I was travelling.

First of all you didn't fill the bug report as expected, so I don't know
if you are using a simple Helm configuration among other things.
I suspect you are using a modified version of Helm (by Spacemacs or
whatever), because here helm-occur is working more or less like you are
asking. Please try from emacs-helm.sh and check the various helm-occur
user variables, also for helm-occur searching in something else than
current buffer, ensure you are using helm-occur and not
helm-occur-visible-buffers.
I will be able to answer in more details in november, busy right now.

Thanks.


Robert Morelli ***@***.***> writes:

> Suggestion
>
> As I think is typical, I have Ctrl-S bound to helm-occur. However, helm-occur seems to cast its net a lot wider than I want in most cases. First, it has a rather loose kind of matching
> that pulls in too many candidates for my liking. Moreover, recently (several months ago) the behavior seems to have changed; it now pulls in matches in other files, with some sort of
> grep-like functionality. I very, very, very strongly dislike this behavior. I find that I've essentially stopped using helm-occur as a result and instead almost always fall back on Emacs's
> basic isearch-forward, which I strongly prefer to whatever helm-occur is doing.
>
> Description
>
> Can someone perhaps suggest a happy medium, that would give me a somewhat improved ui using helm, but for which the search candidates are pretty close to what isearch-forward would give,
> or at least has behavior under my more direct control. In particular, under no circumstances do I EVER want grep-like functionality mixed with in-buffer searches, or matches in files other
> than the current buffer appearing for any reason. If this isn't possible with helm, I need to stop using helm, and if it isn't possible with Emacs at all, I'll stop using Emacs. This is
> completely non-negotiable.
>
> Solutions
>
> I am not particular that this needs to be done using helm. If it's easier to do what I want by bypassing helm, that's fine. I think at some point, I'll probably be moving on from helm, but
> in the near term I just want as little disruption as possible. However, the issue of matches in files other than the current buffer is absolutely non-negotiable, so if it's not possible, I
> suppose now is the time to move on. In any case, any advice is appreciated.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.*Message ID: ***@***.***>

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Seems this bug report is not related to a minimal Helm installation, closing.

**Comment by Addlai** [comment]
I think I figured out what's going on. The problem is that Ctrl-s is bound to helm-run-occur-grep-ag-buffer-directory in the helm-occur-map keymap. I'm accustomed to repeatedly hitting Ctrl-s to do incremental searches, as the classical Emacs isearch-forward does. It seems that helm's paradigm is to use navigation keys to scroll through the candidates once helm-occur is invoked. I'll have to train myself to refrain from using Ctrl-s, or maybe just rebind the keys.

**Comment by kohnish** [comment]
For some reason, helm-occur seems to interpret space as .* in regex. I couldn't find in the code base where such algorithm is applied.  

In the following, both texts match in vanilla helm-occur without any extensions.  

search string: `;; helm`
target texts:
```
;; helm
;; not helm
```

**Comment by thierryvolpiatto** [comment]
kohnish ***@***.***> writes:

> For some reason, helm-occur seems to interpret space as .* in regex.

No, helm-occur uses multi-match, so when you enter a space, like with
";; helm" it searchs in each line text matching ";;" AND "helm" so the
line ";; not helm" matches as well.

> In the following, both texts match in vanilla helm-occur without any extensions.
>
> search string: ;; helm
> target texts:
>
> ;; helm
> ;; not helm

If you want to match only the first line i.e.(";; helm") use either
";;\s-helm" or ";;\ helm".

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you modified the open/close state.*Message ID: ***@***.***>

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Just fixed a special case where pattern is "^;;\ helm".

**Comment by kohnish** [comment]
ahhh, makes sense. thanks!
