### ISSUE TITLE
C-z is backgrounding Emacs

### ISSUE THREAD

**Issue by jbulow** [emacs-helm/helm#358]
C-z is backgrounding Emacs. Seems to prevent helm from working on any OS with job control.

Is helm supposed to work on unix/linux/osx?

**Comment by vaab** [comment]
Wow, that's an unconstructive discussion. Here's some answers around this:
- ``C-z`` for suspending emacs **can be binded** by emacs to another command as any other commands.
- Yes, this is probably a poor choice to bind ``C-z`` to something else than suspending emacs if you are used to suspend your emacs this way.
- But, you can bind another key for your action if needed, default helm installation does NOT require ``C-z`` to be used.

Additionaly, if you use:
```
(define-key helm-map (kbd "C-z")  'helm-select-action)
```
(as suggested in http://tuhdo.github.io/helm-intro.html for instance)
This will keep ``C-z`` normal behavior (yes, in terminal also) except in ``helm-mode`` buffers.

I use exclusively emacs in a terminal on a GNU/Linux system (Ubuntu), and I use ``C-z`` often to suspend emacs for short switches with the shell to issue commands to the system (using ``fg`` to get back to emacs). So ``C-z`` still suspend my emacs except when in ``helm`` interactions.
