### ISSUE TITLE
Sort in reverse

### ISSUE THREAD

**Issue by PythonNut** [emacs-helm/helm#362]
I have recently tried out CTRL-P (for vim), which sorts closer matches at the bottom (the default view is at the bottom of the buffer and you scroll up instead). This puts them closer to the minibuffer, and the eye travels less between higher matches and the minibuffer. Is this already possible in helm, and if not, would it be a good feature to add?

Thanks,
PythonNut

**Comment by egarrulo** [comment]
Another solution would be to open the buffer with completions below the current window, instead of above.  This way, the minibuffer will be above its completions.

**Comment by PythonNut** [comment]
You can open a window below the mnibuffer?

**Comment by egarrulo** [comment]
Yes.  Each window has its own minibuffer, therefore by opening a window below the active window, the new window will be below the active minibuffer.

**Comment by tuhdo** [comment]
This is implemented already, using Helm header line. You can check [this Reddit thread](http://redd.it/3asbyn) for instructions. It was implemented because of this issue: https://github.com/emacs-helm/helm/issues/1064

**Comment by sassanh** [comment]
Actually I think the ability to reverse a list is one of the most essential features any software that shows a list should have.
