### ISSUE TITLE
[Feature request] can filter special mode in helm buffer list. (e.g. dired-mode)

### ISSUE THREAD

**Issue by zw963** [emacs-helm/helm#372]
I hope can auto filter out some mode in all buffer list, e.g. dired-mode

**Comment by zw963** [comment]
Sorry, I have no idea about how to use this. 

I try to ignore all Dired mode buffer with:
``(add-to-list 'helm-boring-buffer-regexp-list "Dired/name")``
But it is not worked for me.

**Comment by thierryvolpiatto** [comment]
Billy <notifications@github.com> writes:

> Sorry, I have no idea about how to use this.

You have no setting to make, if you want to search for example buffer
containing in their name "foo" and exclude in your search all dired
buffer, write:

*!dired foo

As usual see C-c ? for more infos on this.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by zw963** [comment]
Perhaps i have a wrong describe for my need, sorry~

I really needs is in any time, if I load `helm-mini`, I don't want to see any `dired-mode` buffer.

What can I do?
