### ISSUE TITLE
Remove leftover buffers

### ISSUE THREAD

**Issue by julienfantin** [emacs-helm/helm#39]
When using an helm command such as `helm-mini` the buffer is not killed after either performing an action or cancelling.

I understand this is part of a mechanism to reuse helm buffers, but they do accumulate if you use a lot of different helm commands, and I think it'd be nice to be able to customize, i.e. disable, this beahviour.

**Comment by sandric** [comment]
Well I have to say I suffer from this also. For example I bound shortcuts to cycle opened buffers prev and next and have to scroll those not killed buffers. You pointed that if you use helm than you should not see those buffers. Well, I use not only helm, theres much more. Maybe helm have some function for switching prev/next buffers also hiding those that he opened?
