### ISSUE TITLE
helm-completing-read-default forces helm-mode on

### ISSUE THREAD

**Issue by philjackson** [emacs-helm/helm#391]
I've tried to replace anything with helm which is going well so far. The only problem is when I swap out `anything-completing-read` with `helm-completing-read-default` (perhaps the wrong function?) I find that `helm-mode` is on and has hijacked `M-x` and co.

Helm shouldn't be so aggressive in taking over, IMO.

**Comment by gentcys** [comment]
@philjackson  what's the variable you set finally?
