### ISSUE TITLE
Enabling helm-ff-skip-boring-files replaces matches with `nil`

### ISSUE THREAD

**Issue by whirm** [emacs-helm/helm#397]
Starting an Emacs session with ./emacs-helm.sh and setting helm-ff-skip-boring-files to `t` will replace any file matched by the boring exp list with `nil` instead of hiding it.

Tested on: v1.5.9-18-g73941ec

**Comment by ReneFroger** [comment]
Another question about helm. 

I would like to not display the buffers like *sr-speedbar* and *Messages* in helm, under source buffer in `Helm for files. `Setting them to helm-ff-skip-boring-files` didn't help. Any suggestion? 

Thanks in advance!

But how could I do that?

**Comment by thierryvolpiatto** [comment]
ReneFroger <notifications@github.com> writes:

> Another question about helm.
>
> I would like to not display the buffers like sr-speedbar and Messages
> in helm, under source buffer in Helm for files.Setting them to
> helm-ff-skip-boring-files` didn't help. Any suggestion?
>
> Thanks in advance!
>
> But how could I do that?

Use customize to set `helm-ff-skip-boring-files' to t.
Then customize `helm-boring-file-regexp-list' as needed.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by ReneFroger** [comment]
Thanks for your reply, it solved my issue.



2015-02-09 16:35 GMT+01:00 Thierry Volpiatto <notifications@github.com>:

>
> ReneFroger <notifications@github.com> writes:
>
> > Another question about helm.
> >
> > I would like to not display the buffers like sr-speedbar and Messages
> > in helm, under source buffer in Helm for files.Setting them to
> > helm-ff-skip-boring-files` didn't help. Any suggestion?
> >
> > Thanks in advance!
> >
> > But how could I do that?
>
> Use customize to set `helm-ff-skip-boring-files' to t.
> Then customize `helm-boring-file-regexp-list' as needed.
>
> --
> Thierry
> Get my Gnupg key:
> gpg --keyserver pgp.mit.edu --recv-keys 59F29997
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/emacs-helm/helm/issues/397#issuecomment-73528671>.
>



-- 
Sent from my Vmail client. <http://danielchoi.com/software/vmail.html>
