### ISSUE TITLE
Helm-Grep or helm-occur with context

### ISSUE THREAD

**Issue by ronniec95** [emacs-helm/helm#400]
Is there a way to show context around an helm-occur/helm-grep search.

As in regular emacs occur which has C-u 2 occur, shows 2 lines of context.

**Comment by martinraison** [comment]
I think it is useful. C-z forces me to navigate to the item I'm interested in and then press C-z, which is not the same as seeing all the contexts at a glance.

**Comment by xuchunyang** [comment]
> I think it is useful. C-z forces me to navigate to the item I'm interested in and then press C-z, which is not the same as seeing all the contexts at the same time.

See https://github.com/ShingoFukuyama/helm-swoop/#multiline-behavior, it has more function than you want, though I don't use helm-swoop myself.

**Comment by martinraison** [comment]
Looks very promising. Thanks!

**Comment by thierryvolpiatto** [comment]
Chunyang Xu <notifications@github.com> writes:

> See https://github.com/ShingoFukuyama/helm-swoop/#multiline-behavior,
> it has more function than you want, though I don't use helm-swoop
> myself.

You can have the same behavior (more or less) with helm-occur if you enable default as
input for this source and follow-mode, and the code is cleaner.


-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
