### ISSUE TITLE
helm completion-at-point does not show the full completion information

### ISSUE THREAD

**Issue by nojb** [emacs-helm/helm#407]
Hi,

When using usual completion-at-point one can see information that disappears when using helm-mode.

For example, this is with plain Emacs:

![screen shot 2014-01-30 at 23 21 01](https://f.cloud.github.com/assets/113560/2046364/42061d1c-8a05-11e3-8cca-8625fd5e7535.png)

(in the above picture the supplementary information is in italics after each colon)

However, if I do (helm-mode 1), I get:

![screen shot 2014-01-30 at 23 21 09](https://f.cloud.github.com/assets/113560/2046366/468f7c52-8a05-11e3-849f-b92572db5b1b.png)

Is there a way to include the supplementary information in the helm version of completion-at-point? Maybe in the same manner that extra information appears in helm-list-buffers?

Thanks!

**Comment by sboosali** [comment]
Annotations don't work for me.

Reproduce:

`eval-buffer` the following (which does work in vanilla Emacs, with the prompt popping up when you press TAB):

```
;;; Commentary:

;; See URL `http://garethrees.org/2015/02/09/emacs/'.

;;; Code:

(defun my-annotation-function (s)
  (let ((item
	 (assoc s minibuffer-completion-table)))
    (when item
      (concat "  -- " (cdr item)))))

(defvar my-completions
  '(("xxa" . "description of A")
    ("xxb" . "B's description")))

(let ((completion-extra-properties
       '(:annotation-function my-annotation-function)))
  (message
   (completing-read "Prompt: " my-completions)))
```

**Comment by sboosali** [comment]
Annotations don't seem to work for me (including the `completion-at-point` on gnus-` example above).

Version:

```
helm-core-20181117.255
```

To reproduce:

`eval-buffer` the following (which does work in vanilla Emacs, with the prompt popping up when you press TAB):

```
;;; Commentary:

;; See URL `http://garethrees.org/2015/02/09/emacs/'.

;;; Code:

(defun my-annotation-function (s)
  (let ((item
	 (assoc s minibuffer-completion-table)))
    (when item
      (concat "  -- " (cdr item)))))

(defvar my-completions
  '(("xxa" . "description of A")
    ("xxb" . "B's description")))

(let ((completion-extra-properties
       '(:annotation-function my-annotation-function)))
  (message
   (completing-read "Prompt: " my-completions)))
```

**Comment by thierryvolpiatto** [comment]
Spiros Boosalis <notifications@github.com> writes:

> Annotations don't seem to work for me (including the completion-at-point on gnus-` example above).
>
> Version:
>
> helm-core-20181117.255
>
> To reproduce:
>
> eval-buffer the following (which does work in vanilla Emacs, with the prompt popping up when you press TAB):
>
> ;;; Commentary:
>
> ;; See URL `http://garethrees.org/2015/02/09/emacs/'.
>
> ;;; Code:
>
> (defun my-annotation-function (s)
>   (let ((item
>          (assoc s minibuffer-completion-table)))
>     (when item
>       (concat "  -- " (cdr item)))))
>
> (defvar my-completions
>   '(("xxa" . "description of A")
>     ("xxb" . "B's description")))
>
> (let ((completion-extra-properties
>        '(:annotation-function my-annotation-function)))
>   (message
>    (completing-read "Prompt: " my-completions)))

Annotations in helm are not supported yet in plain completing-read, only
via completion-in-region mechanism, thus even for this one, the behavior
seems to have changed in emacs-26 (perhaps earlier versions too).

-- 
Thierry

**Comment by sboosali** [comment]
ah, good to know, thanks!
