### ISSUE TITLE
Helm M-x - persistent command history

### ISSUE THREAD

**Issue by samspo** [emacs-helm/helm#431]
Command history is perfect (see #62 and #86)  but not saved  to be usuable during the next sessions. Is it the normal behavior or just a problem in my emacs config ?

If it is the normal behavior, Is there any possiblity to have persistent command history in Helm M-x accross different emacs sessions?

Thanks for this very useful package

**Comment by ReneFroger** [comment]
@samspo, thanks for mentioning it in your last reply!
