### ISSUE TITLE
ssh on windows

### ISSUE THREAD

**Issue by ev00l** [emacs-helm/helm#446]
I want to switch to helm for finding files, but I don't know to use tramp from the helm file finder.

I am on windows, and typing / just takes me to c:/ 

Typing /ssh:username@host: just prompts me for the creating of a buffer.

The new buffer will have the name ssh:username@host.

If i delete everything in the minibuffer, and type /ssh:user@host: , without letting it autocomplete / to c:/ , i get the following error:

Wrong argument type string p nil

**Comment by varunpatro** [comment]
Hey @thierryvolpiatto I'm experiencing the same issue. Here's the debug log:

Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-directory-p(nil)
  helm-ff-RET()
  funcall-interactively(helm-ff-RET)
  call-interactively(helm-ff-RET nil nil)
  command-execute(helm-ff-RET)
  read-from-minibuffer("Find files or url: " "c:/Users/vpatro/Downloads/emacs-25.2-x86_64/bin/" (keymap (f13 lambda nil (interactive) (helm-select-nth-action 12)) (f12 lambda nil (interactive) (helm-select-nth-action 11)) (f11 lambda nil (interactive) (helm-select-nth-action 10)) (f10 lambda nil (interactive) (helm-select-nth-action 9)) (f9 lambda nil (interactive) (helm-select-nth-action 8)) (f8 lambda nil (interactive) (helm-select-nth-action 7)) (f7 lambda nil (interactive) (helm-select-nth-action 6)) (f6 lambda nil (interactive) (helm-select-nth-action 5)) (f5 lambda nil (interactive) (helm-select-nth-action 4)) (f4 lambda nil (interactive) (helm-select-nth-action 3)) (f3 lambda nil (interactive) (helm-select-nth-action 2)) (f2 lambda nil (interactive) (helm-select-nth-action 1)) (menu-bar keymap (help-menu keymap (describe keymap (describe-mode . helm-help)))) (help keymap (109 . helm-help)) (23 . #[0 "\306\307\310\311\312\305!\313\"\314$\216\315\302!\210\316\304!\317\211\211\301=\203'

**Comment by thierryvolpiatto** [comment]
Varun Patro <notifications@github.com> writes:

> Hey @thierryvolpiatto I'm experiencing the same issue. Here's the debug log:

After /sshx:host: do not hit RET but wait to see what you have in the
helm-buffer and once the completion popup hit C-j before starting
navigating.

Also be sure your ssh connection works outside emacs in a terminal, if
for any reasons you are asked for e.g "Are you sure ....(yes/no)" in the
terminal, this prevent ssh working from emacs, you have to connect once
in the terminal to fix all issues relative to ssh before trying in
emacs.

At each retry don't forget to clean all tramp connections before
retrying (M-x helm-delete-tramp-connection).

> Debugger entered--Lisp error: (wrong-type-argument stringp nil)
> file-directory-p(nil)
> helm-ff-RET()

Seems here you are hitting RET on an empty helm-buffer i.e your ssh
connection failed.

If your connection still persists not working, please send a new
bugreport describing all what you are doing (follow instructions on
debug template), set also tramp-verbose to 6 and send along the tramp
debug buffer.

Thanks.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by varunpatro** [comment]
For this:

> After /sshx:host: do not hit RET but wait to see what you have in the
helm-buffer and once the completion popup hit C-j before starting
navigating.

I don't get any autocompletion.

For this:

> Also be sure your ssh connection works outside emacs in a terminal, if
for any reasons you are asked for e.g "Are you sure ....(yes/no)" in the
terminal, this prevent ssh working from emacs, you have to connect once
in the terminal to fix all issues relative to ssh before trying in
emacs.

No terminal issues on ssh. `ssh aws` works correctly without any prompts

For this:

> At each retry don't forget to clean all tramp connections before
retrying (M-x helm-delete-tramp-connection).

I don't have any tramp connections. My issue occurs even when I first launch emacs

**Comment by thierryvolpiatto** [comment]
Varun Patro <notifications@github.com> writes:

> For this:
>
>     After /sshx:host: do not hit RET but wait to see what you have in the
>     helm-buffer and once the completion popup hit C-j before starting
>     navigating.
>    
> I don't get any autocompletion.

Looks like it is a problem with tramp itself, not helm, did you try with
emacs -Q (without helm) to see if tramp works ?

Try also with other methods (ssh, scp etc...) to see if it works.

Unfortunately I can't help more on this as I have no more access
actually to a Windows box.

Perhaps you can ask on our mailing list to see if there is some Windows
user that can help you ?

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by thierryvolpiatto** [comment]
Forget to mention here that tramp is not working at all with helm-2.7.1 in emacs-26, it is fixed in master though (there is a note in 2.7.1 release about this).
@varunpatro If you are using emacs-26 and helm from melpa stable, helm+tramp will not work at all, you have to use helm from melpa or the master branch from git or just wait for next release (soon).
HTH.
