### ISSUE TITLE
Allow helm-find-files to complete relative path

### ISSUE THREAD

**Issue by tuhdo** [emacs-helm/helm#455]
`helm-find-files` can only insert absolute path. `helm-find-files` should allow to toggle between absolute path and relative path. To have a relative path, `helm-find-files` should add an action to set the current directory in `Find file or Url:` prompt as working directory. This working directory is only local to `helm-find-files`, and act as an anchor for relative path completion. This action can be called `Relative path completion at point`, and bound to `C-c p`. For example, this is my currently displayed directory in `Find file or Url:`:

> /home/tuhdo/.emacs.d

Upon activating `C-c p`, the prompt becomes empty and allows to enter relative path. Candidate buffer of `helm-find-files` should be displayed as usual. So, the input in `Find file or Url:` becomes empty, and if I enter into the prompt such a directory path:

> ../bin

The prompt should not be changed to `/home/tuhdo/bin`, but keep it as it is and display appropriate candidates in that directory. Pressing RET inserts exactly the entered path in `Find file or Url:`.

**Comment by rhalukongor** [comment]
Just here to put my +1. In web development it's all relative paths and being able to insert filename relative to the current file / project root would be immensely useful.

**Comment by thierryvolpiatto** [comment]
rhalukongor <notifications@github.com> writes:

> Just here to put my +1. In web development it's all relative paths and
> being able to insert filename relative to the current file / project
> root would be immensely useful.

See the exp branch:

On insertion (no completion):

- C-u C-c i => insert abbreviate file name.
- C-u C-u C-c i => insert relative file name.

On completion:

- target starts by ~/ => insert abbreviate file name.
- target starts by / or [a-z]:/ => insert full path.
- otherwise insert relative file name.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by madhavan020985** [comment]
@thierryvolpiatto, my upvote for putting relative paths, `Complete at point`. Is this available in helm-find-files as of now???

**Comment by rhalukongor** [comment]
Yes (for some time now): You can use "C-u C-u C-c i" binding in helm find files. You can have a look at most shortcuts typing "C-c ?" if you're using Spacemacs. I don't remember the shortcut in vanilla but it is probably the same.

**Comment by madhavan020985** [comment]
it works without spacemacs, with plain helm find-file.... i did helm-find-file, navigated to the desired file in minibuffer, then pressed `C-u C-u C-c i`, the relative path is inserted at my point.... buah.....

**Comment by CThuleHansen** [comment]
So I just tried the `C-u C-u C-c i` and it works - almost. However, it removes everything before the insertion. 

For example: E.g. `{|}` where `|` marks the cursor position. After using the command I end up with: `../../bib/article.bib}`. I was hoping for just an insertion: 
`{../../bib/article.bib}`

Any ideas?

**Comment by rhalukongor** [comment]
Assumption: You're using spacemacs (or evil mode) and you've tried it on insert mode.
If that's the case then try it in normal mode and it should work as intended...

**Comment by thierryvolpiatto** [comment]
Casper Thule <notifications@github.com> writes:

> So I just tried the C-u C-u C-c i and it works - almost. However, it removes everything before the insertion.
>
> For example: E.g. {|} where | marks the cursor position. After using the command I end up with: ../../bib/article.bib}. I was hoping for just an insertion:
> {../../bib/article.bib}
>
> Any ideas?

Should work now, have a try and let me know.

Thanks.

-- 
Thierry

**Comment by CThuleHansen** [comment]
Hi Thierry, it works now in both insert and normal mode. Thank you!

**Comment by azzamsa** [comment]
> If that's the case, then I hope someday I can add this feature. Currently, I'm too busy to properly learn Elisp.

@tuhdo starting from your issue. now it's already implemented. Btw thanks for your great guide to Helm.
