### ISSUE TITLE
Add mouse selection support

### ISSUE THREAD

**Issue by ghost** [emacs-helm/helm#501]
For example: I'd like to be able to do (helm-buffers-list) and click on the name or row of the buffer I want to go to.  

Bonus points for opening in dired (or eshell) the directory of the (in `directory') part if I click on that specific part of the row.

**Comment by ralesi** [comment]
With the changes referenced, is it possible to get mouse click working again?  Looks like we override all mouse bindings now in `helm-internal`

**Comment by thierryvolpiatto** [comment]
Rich Alesi <notifications@github.com> writes:

> With the changes referenced, is it possible to get mouse click working
> again?

No, no mouse in helm.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by sboosali** [comment]
has this feature been provided? my recently installed `helm` ignores all mode clicks. if it has, and it's bug, i'll add information to reproduce (but I wanted to check before doing so).

if it hasn't, removing a whole mode of input (the mouse) decreases accessibility. this is blocking me from using `helm`.

**Comment by Compro-Prasad** [comment]
The mouse just selects and doesn't execute any action.

**Comment by thierryvolpiatto** [comment]
Please read the documentation about Mouse usage (`C-h m` from any helm session).

**Comment by Compro-Prasad** [comment]
Thanks that helped. But it I would prefer to execute the default action without a second click.

**Comment by thierryvolpiatto** [comment]
Compro Prasad <notifications@github.com> writes:

> Thanks that helped. But it I would prefer to execute the default action without a second click.

When I implemented mouse support in Helm I asked myself the same, but I
finally opted for what we have actually which covers all use cases.

-- 
Thierry

**Comment by mattmundell** [comment]
> Thanks that helped. But I would prefer to execute the default action without a second click.

I worked around it like this, in case it helps anyone:

```
(defun orig-helm-mouse-select-candidate (event)
  (interactive "e")
  (let* ((window (posn-window (event-end event)))
         (pos    (posn-point (event-end event))))
    (unwind-protect
        (with-current-buffer (window-buffer window)
          (if (and (helm-action-window)
                   (eql window (get-buffer-window helm-buffer)))
              (user-error "selection in helm-window not available while selecting action")
            (helm--mouse-reset-selection-help-echo)
            (goto-char pos)
            (when (helm-pos-multiline-p)
              (goto-char (or (helm-get-previous-candidate-separator-pos)
                             (helm-get-previous-header-pos)))
              (forward-line 1)))
          (helm-mark-current-line)
          (helm-follow-execute-persistent-action-maybe))
      (select-window (minibuffer-window))
      (set-buffer (window-buffer window)))))

(defun helm-mouse-select-candidate (event)
  (interactive "e")
  (orig-helm-mouse-select-candidate event)
  (select-window (active-minibuffer-window))
  (helm-maybe-exit-minibuffer))
```
So much smoother to just click.

Thanks @thierryvolpiatto for the work you're doing.

**Comment by thierryvolpiatto** [comment]
Matt Mundell ***@***.***> writes:

>     Thanks that helped. But I would prefer to execute the default action without a second click.
>    
> I worked around it like this, in case it helps anyone:
>
> (defun orig-helm-mouse-select-candidate (event)
>   (interactive "e")
>   (let* ((window (posn-window (event-end event)))
>          (pos    (posn-point (event-end event))))
>     (unwind-protect
>         (with-current-buffer (window-buffer window)
>           (if (and (helm-action-window)
>                    (eql window (get-buffer-window helm-buffer)))
>               (user-error "selection in helm-window not available while selecting action")
>             (helm--mouse-reset-selection-help-echo)
>             (goto-char pos)
>             (when (helm-pos-multiline-p)
>               (goto-char (or (helm-get-previous-candidate-separator-pos)
>                              (helm-get-previous-header-pos)))
>               (forward-line 1)))
>           (helm-mark-current-line)
>           (helm-follow-execute-persistent-action-maybe))
>       (select-window (minibuffer-window))
>       (set-buffer (window-buffer window)))))
>
> (defun helm-mouse-select-candidate (event)
>   (interactive "e")
>   (orig-helm-mouse-select-candidate event)
>   (select-window (active-minibuffer-window))
>   (helm-maybe-exit-minibuffer))
>
> So much smoother to just click.

I decided to not do this because it prevents you from executing another
action on a given candidate i.e. It limits you to the default action
when using mouse.

> Thanks @thierryvolpiatto for the work you're doing.

Thanks ;-)

-- 
Thierry

**Comment by mattmundell** [comment]
> I decided to not do this because it prevents you from executing another action on a given candidate i.e. It limits you to the default action when using mouse.

I see.  I would expect mouse-2 to lead to a menu of options, but I don't know the mouse norms in Emacs (or all the cases Helm is dealing with).

**Comment by thierryvolpiatto** [comment]
Matt Mundell ***@***.***> writes:

>     I decided to not do this because it prevents you from executing another action on a given candidate i.e. It limits you to the default action when using mouse.
>    
> I see. I would expect mouse-2 to lead to a menu of options, but I
> don't know the mouse norms in Emacs (or all the cases Helm is dealing
> with).

Mouse-1: Select.
Mouse-2: Execute default action.
Mouse-3: Popup action menu (menu widget on X).
When in action menu (widget) mouse-1 execute action.
It is also possible dragging a candidate to a dired buffer.

-- 
Thierry
