### ISSUE TITLE
How to adjust helm-mini filename column width?

### ISSUE THREAD

**Issue by zw963** [emacs-helm/helm#514]
I want to adjust filename width a litter more wider to show filename completely, How can I do this? 

Thanks for you help.

**Comment by manateelazycat** [comment]
@zw963 
You can use below code adjust filename column:

(setq helm-buffer-max-length 60)

**Comment by zw963** [comment]
@manateelazycat , Thanks, I set it to `nil` to use the longest buffer-name length found.

**Comment by ltrottier** [comment]
Thanks! This was bothering me so much.
