### ISSUE TITLE
How to properly enable helm-follow-mode

### ISSUE THREAD

**Issue by tuhdo** [emacs-helm/helm#530]
I want to enable `helm-follow-mode` in `helm-occur` and `helm-multi-occur` by doing so:

``` lisp
(add-hook 'helm-after-initialize-hook
          #'(lambda () (helm-attrset 'follow 1 helm-source-occur)))
(add-hook 'helm-after-initialize-hook
          #'(lambda () (helm-attrset 'follow 1 helm-source-moccur)))
```

It works fine in my running Emacs. However, after restarting Emacs, this error occurs:

> Wrong type argument: consp, nil

How do I setup properly?

**Comment by skparkes** [comment]
For anyone else that ends up here, not all of the helm sources have initialization functions.  In particular, it can make a lot of sense to turn on `follow-mode` for `helm-source-grep`, but `helm-source-grep` is initialized to `nil` instead of a dummy source.  I ended up going with this to get always-on follow-mode for greps:
```elisp
(setq helm-source-grep (helm-build-dummy-source "init_grep" :follow 1))
(add-hook 'helm-before-initialize-hook
          (lambda () (helm-attrset 'follow 1 helm-source-grep)))
```
I imagine the `:follow 1` is superfluous, but I'm too worn out after chasing this down to confirm/understand that well enough.

**Comment by thierryvolpiatto** [comment]
skparkes <notifications@github.com> writes:

> For anyone else that ends up here, not all of the helm sources have
> initialization functions. In particular, it can make a lot of sense to
> turn on follow-mode for helm-source-grep, but helm-source-grep is
> initialized to nil instead of a dummy source.

It is not the way to do, dummy sources are not for this.

> I ended up going with this to get always-on follow-mode for greps:
>
> (setq helm-source-grep (helm-build-dummy-source "init_grep" :follow 1))
> (add-hook 'helm-before-initialize-hook
>           (lambda () (helm-attrset 'follow 1 helm-source-grep)))

This hack would work only for grep, please see:

https://github.com/emacs-helm/helm/wiki/FAQ#why-is-a-customizable-helm-source-nil

For the documentation of helm-follow-mode, yes it is deprecated and
should be fixed.

For the helm grep case, I will commit a change that will allow you to
do only:

(defmethod helm-setup-user-source ((source helm-grep-class))
  (set-slot-value source 'follow 1))

Will be ready soon.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
See also helm-follow-mode-persistent.

-- 
Thierry

**Comment by skparkes** [comment]
Thanks for your willingness to help out.

I did read about `helm-follow-mode-persistent`, but I believe that is for making `follow-mode` "sticky" between helm sessions.  I actually don't want it "sticky", I want every `helm-occur` and `helm-grep` session to start with `follow-mode` enabled (even if it was disabled at the end of the last corresponding helm session).

I'll try to read more about `helm-setup-user-source` now.  My elisp prowess is weak, but I can usually (eventually) follow along.

I personally find `follow-mode` quite helpful when searching through file/buffer contents, but I did not feel like installing the third party `helm-swoop` just to get that functionality when it was already in `helm` core.

Thanks for maintaining a very helpful package.

**Comment by michael-heerdegen** [comment]
```
(with-eval-after-load 'helm-regexp
  (setq helm-source-occur
        (helm-make-source "Occur" 'helm-source-multi-occur
          :follow 1)))
```

**Comment by blaenk** [comment]
For what it's worth, this no longer works recently.

```
cl-no-applicable-method: No applicable method: make-instance, helm-source-multi-occur, "Occur", :follow, 1
```

**Comment by thierryvolpiatto** [comment]
Jorge Israel Peña <notifications@github.com> writes:

> For what it's worth, this no longer works recently.
>
> cl-no-applicable-method: No applicable method: make-instance, helm-source-multi-occur, "Occur", :follow, 1

Because helm-source-multi-occur doesn't exists anymore, see issue #2146.

-- 
Thierry

**Comment by blaenk** [comment]
Nice, thanks for letting me know!

**Comment by thierryvolpiatto** [comment]
Now follow-mode is enabled by default in multi occur so you should not have to add some extra config.
