### ISSUE TITLE
Hitting enter immediately after typing pattern into M-x helm-mini results in "Display not ready"

### ISSUE THREAD

**Issue by opsound** [emacs-helm/helm#550]
When I `M-x` `helm-mini`, start typing a search pattern, then immediately press `enter`, the `[Display not ready]` message appears in the mini buffer.  If I wait in between typing the pattern and pressing enter, it behaves as expected.  Is there a way to decrease or eliminate this "dead" period where I have to wait until I press enter?  It is a bit annoying to have to wait before proceeding.

**Comment by IvanMalison** [comment]
> (Although I'd suggest to others looking for a workaround that (customize-variable 'helm-exit-idle-delay) is a better way to go about it than setq…)

@glyp Why is that?

**Comment by rileyrg** [comment]
https://emacs.stackexchange.com/questions/102/advantages-of-setting-variables-with-setq-instead-of-custom-el/106

**Comment by glyph** [comment]
@IvanMalison The answer from @rileyrg has the right idea :).  (Also using *all* the letters in the `@`-mention does make it get through faster :))
