### ISSUE TITLE
Extract a helm-core package

### ISSUE THREAD

**Issue by bbatsov** [emacs-helm/helm#592]
helm is definitely awesome, but the default package is way too big - it currently packs everything but the kitchen sink. It's probably the biggest package I've ever installed (judging by the time it takes to byte-compile it). 3rd party packages that depend on `helm`, like [clojure-cheatsheet](https://github.com/clojure-emacs/clojure-cheatsheet/blob/master/clojure-cheatsheet.el) end up pulling all sort of redundant stuff just to use the core of helm. That seems pretty suboptimal to me.

It's be great if you split the package into two parts (package.el packages) - a `helm-core` package that provides just the generic helm framework and a separate package that bundles popular sources. On a related note - many of the non-essential sources like yaoddmuse, w3m, etc might be better off in packages of their own.

**Comment by lunaryorn** [comment]
I'd also greatly appreciate if Helm was split.

**Comment by thierryvolpiatto** [comment]
What will be provided is a helm-core package available from melpa.
It will be fetched from the current helm repo, so no separate git repo for it.
It will provide the minimum to allow building sources and running helm.
No helm high level  applications will be provided.
It will be intended for developers writing their own helm applications and need a small
package as dependency.

**Comment by bbatsov** [comment]
Sounds great!

On Friday, July 10, 2015, Thierry Volpiatto <notifications@github.com>
wrote:

> What will be provided is a helm-core package available from melpa.
> It will be fetched from the current helm repo, so no separate git repo for
> it.
> It will provide the minimum to allow building sources and running helm.
> No helm high level applications will be provided.
> It will be intended for developers writing their own helm applications and
> need a small
> package as dependency.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/emacs-helm/helm/issues/592#issuecomment-120474668>.
>


-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com

**Comment by thierryvolpiatto** [comment]
Now the helm-core package is available on melpa (should be available on next sync).
