### ISSUE TITLE
 Symbol's function definition is void: helm--make-source

### ISSUE THREAD

**Issue by swwwfactory** [emacs-helm/helm#616]
After latest update: get subject message and helm not working anymore.
Popup messages with warning "Symbol's function definition is void: helm--make-source"
Forced do downgrade to version at 6 september.

Please check - not working helm-occur.

Please more test versions before commit or use stable and unstable branches or notify how upgrade from previous versions.

In last time I see often untested commits that fix manually or downgrade.

Thanks!

**Comment by chrneumann** [comment]
https://github.com/emacs-helm/helm/wiki#11-i-have-updated-from-melpa-and-i-have-errors
