### ISSUE TITLE
`helm-find-files` with point close to "duckduckgo.com" attempts SSHing into DDG

### ISSUE THREAD

**Issue by wasamasa** [emacs-helm/helm#648]
This is probably the most bizarre bug I've ever encountered in my entire Emacs usage.

![](http://i.imgur.com/DZH3jko.png)

As you can see in the screenshot above, I've placed point on a word that's next to the DuckDuckGo URL. If I invoke `M-x helm-find-files`, I get to see a SSH popup by TRAMP that asks me whether I want to continue connecting to DuckDuckGo. No matter whether I tell it to do so or not, I cannot proceed to select a file.

I've looked at the sources and it looks like `helm-find-files-input` eventually uses `expand-file-name` on the context around point. Since `expand-file-name` looks up `file-name-handler-alist` which contains TRAMP file handlers, they try doing something useful with their input and presumably lock up.

I'd like to know whether this behaviour is rather TRAMP's or helm's fault. In any case any suggestions on how to entirely disable guessing sensible defaults that include URLs would be very welcome.

**Comment by freckletonj** [comment]
Since it's not obvious, this helps: `(setq ffap-machine-p-known 'reject)`
