### ISSUE TITLE
Error running timer (args-out-of-range #<buffer *Helm Find Files*> 0 1)

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [emacs-helm/helm#651]
When I try to run helm find files on a remote machine, i.e.:

`/ssh:/user@host:/`

I get the error message:

`Error running timer: (args-out-of-range #<buffer *Helm Find Files*> 0 1)`

I don't think I used to get this error before. 

**Note**: I am running helm from a git repository and I `git pull`, `make clean` and `make` regularly.

**Comment by jwinder** [comment]
I've seen this error every so often. For me, it's always due to the remote server having some funky prompt format that tramp doesn't like (be careful of those creative zsh prompts).

http://www.gnu.org/software/emacs/manual/html_node/tramp/Remote-shell-setup.html
