### ISSUE TITLE
Make FFAP optional or more picky

### ISSUE THREAD

**Issue by russell** [emacs-helm/helm#658]
Hey,

I love helm, but this drives me crazy sometimes.  Basically, I'm on any line that contains a colon and i call `helm-find-files` and FFAP just kicks in and trys to open rubbish..

I like the idea of FFAP but if i had a way to configure it so that it only opened valid urls or absoulte unix paths it might be better?

Some good examples where this crops up are are things like html close tags, times, or the gnus groups list.

**Comment by asok** [comment]
Is it possible to disable the guessing of the input entirely?

**Comment by freckletonj** [comment]
Since it's not obvious, this helps: `(setq ffap-machine-p-known 'reject)`
