### ISSUE TITLE
helm-M-x does not correctly forward C-u arguments

### ISSUE THREAD

**Issue by ecraven** [emacs-helm/helm#696]
For example when using SLIME, C-u - M-x slime should prompt for the lisp to start. This normally works, but if I bind M-x to helm-M-x, it doesn't see the negative argument any longer.

**Comment by louy2** [comment]
So here is your reason of despising giving prefix argument before `M-x`:

> @thierryvolpiatto 
> how one know if a command support a prefix arg, is it a prefix arg a numeric prefix arg etc...

Facing the counter argument to which you have not replied:

> @michael-heerdegen 
> Most of the time, I execute commands with it that you[I] know well.

I align with @michael-heerdegen and I am surprised to see that you abandon the default behavior for basically no reason here. 

Moreover, replying to a pull request:

> @thierryvolpiatto 

>> @michael-heerdegen 
>> Would you mind if I wro[i]te a[n] addon package defining an alternative version of helm-M-x?

> You can of course if you want, but this will confuse even more everybody with a third implementation of M-x, so I will not accept it in emacs-helm.

It is both "you not accepting it" and "implementing it" that is going to make the alternate helm-M-x a third implementation. 

However clever helm might be, your reasoning here is, in your own words, "non sense" (and that should be *nonsense*).

**Comment by thierryvolpiatto** [comment]
I work a lot on helm and I don't want to loose my time to implement something unuseful.
Just get use to this or use something else, I don't care, for me and my usage it is perfectly fine.

NOTE: I am borred of constant attacks and critics from people of spacemacs, please stop using helm guys.
