### ISSUE TITLE
helm-mode completing read -- Allows return empty string even when 'require-match is set, and "" not in list of candidates.

### ISSUE THREAD

**Issue by jeeger** [emacs-helm/helm#700]
Greetings!

helm-comp-read as used by helm-mode doesn't  seem to be fully compatible with completing-read:

```
(helm-mode -1)
(completing-read "P: " '("a" "b" "c") nil 'require-match nil) <Enter> => ""
(helm-mode 1)
(completing-read "P: " '("a" "b" "c") nil 'require-match nil) <Enter> => "a"
```

It seems that helm behavior clashes with this part in the documentation of completing-read:

```
If the input is null, `completing-read' returns DEF, or the first element
of the list of default values, or an empty string if DEF is nil,
regardless of the value of REQUIRE-MATCH.
```

**Comment by cpitclaudel** [comment]
@thierryvolpiatto Can you clarify what the "right" implementation is? My concrete case is that I need the user to pick a collection of entries from a list.  My current implementation repeatedly calls completing-read (each time with one less element in completion candidates) until I get an empty string (which the user can insert using C-j in ido mode).  Once I do, I know the user doesn't want to select more options.

What's the proper way to support this with helm?

**Comment by thierryvolpiatto** [comment]
Clément Pit--Claudel <notifications@github.com> writes:

> @thierryvolpiatto Can you clarify what the "right" implementation is?
> My concrete case is that I need the user to pick a collection of
> entries from a list.  My current implementation repeatedly calls
> completing-read (each time with one less element in completion
> candidates) until I get an empty string (which the user can insert
> using C-j in ido mode). Once I do, I know the user doesn't want to
> select more options.
>
> What's the proper way to support this with helm?

Well it depends if you want to use helm and only helm or use your
approach using a completing-read helmized by helm-mode.

If you want to use only helm, it is easy you can use marked candidates
without having to diminish your list candidate by candidate, you press
RET and helm execute action on marked candidates (if specified in your
action).
If you use your approach I think exiting helm when no more candidates
with C-RET should work ?

--
Thierry

**Comment by cpitclaudel** [comment]
> Well it depends if you want to use helm and only helm or use your
approach using a completing-read helmized by helm-mode.

`completing-read`: This is part of a separate package, and my user may not use helm.

> If you use your approach I think exiting helm when no more candidates
with C-RET should work ?

Sure, but does that mean that the prompt should say "exit with C-RET" for helm users, and "exit with C-j" for others? That's what I did in my latest commit, but it's not pretty.  And helm says (in the header of the completion window) "C-j: DoNothing (keeping session)".  What does that mean?

**Comment by thierryvolpiatto** [comment]
I understand why you are confused, there is a bug introduced by commit d8708168, will fix soon.
Otherwise the information about C-RET while in helm is in the mode line, if helm is not used, well this handled by emacs for vanilla completing-read or ido if ido is used for completion.
C-j in helm is the persistent action, when no persistent action you see do nothing in headline.

**Comment by cpitclaudel** [comment]
Thanks!

**Comment by thierryvolpiatto** [comment]
Just to resume, these two recipe are now working as expected:

```elisp
(completing-read "test: " '(a b c d) nil t)
(completing-read "test: " '(a b c d) nil 'confirm)
```
- In the first one, entering "z" at prompt and hitting `RET` doesn't exit and show in minibuffer "[no match]".
"z" is not shown in `helm-buffer`.

- In the second, entering "z" at prompt and hitting `RET` show in minibuffer "[confirm]", hitting `RET` a second time exit and return "z".
"z" is shown in `helm-buffer` prefixed with "[?]" in yellow.

For the both, hitting `C-RET` exit with empty string (documented in mode-line).

**Comment by thierryvolpiatto** [comment]
About default argument:

```elisp
(completing-read "test: " '(a b c d) nil t nil nil "d")
```
Here when specifying "d" as default, "d" is shown on top of list, so that pressing `RET` with empty pattern allow exiting with "d" as vanilla `completing-read` would do.

```elisp
(completing-read "test: " '(a b c d) nil t nil nil "z")
```
Here when using "z" as default pressing `RET` with empty pattern exit with "z" (same as vanilla `completing-read`), but if you hit `M-n`,  "z" show up in minibuffer and pressing `RET` exit with "z" (which is expected) whereas emacs vanilla `completing-read` exit with "d" which is not expected, at least for me.

**Comment by thierryvolpiatto** [comment]
Also in second example, "z" is shown in the candidates list whereas emacs vanilla `completing-read` doesn't show it in the completion list.

HTH.
