### ISSUE TITLE
Separate help messages into separate Org files

### ISSUE THREAD

**Issue by tuhdo** [emacs-helm/helm#703]
Currently Helm helps are written in plain Emacs Lisp strings. It would be great if we could separate all those Help messages out into Org files, and when Helm is loaded by Emacs, the content of Org files are read and stored into appropriate variables as in current `helm-help.el`. When users open a Helm help buffer, instead of `fundamental-mode`, Org mode is used instead.

If this could be done, it gives these benefits:

- Writing documents in a rich text environment (I wrote all my guides with it).
- Reusable: the Org files can be exported into HTML and PDF formats in addition to being built-in help. So, we could create "Helm manual" out of this.
- Viewing text in Org mode is nicer than viewing it in plain `fundamental-mode`. i.e. you get actual syntax highlighting for Elisp code snippet.

What do you think? If you like, I will implement it at some point.

**Comment by tuhdo** [comment]
I think if we use info, it would make it easier for us to write info and integrate with Helm, since Helm can already be able to collect info topics easily. Info is well integrated with Emacs, and we can Helm help is as simple as (info "helm-command). We can also divide help in many files or in one file as we need, without worrying about all the parsing. We can have an offical document with Info and move all the help string into a richer environment. What do you think? If it is fine, I will convert the help strings and my guide into Info doc.

**Comment by thierryvolpiatto** [comment]
Sorry, forgot to reply to this one.
No I don't want maintaining a documentation with info, any others system (modern preferabily) but not info, it is a pain to maintain.
