### ISSUE TITLE
Can't specify a prefix argument for helm-M-x

### ISSUE THREAD

**Issue by angrybacon** [emacs-helm/helm#714]
I'm trying to use `M-x align-regexp` with prefix argument, I'm using `helm-M-x`.

``` text
user-error: Error: Specifying a prefix arg before calling `helm-M-x'
```

Thanks : j

**Comment by srid** [comment]
I read the embedded documentation, and still came out perplexed. Typing `C-u` results on `[prefarg:4]` tag added, and the next character I type repeats itself 4 times (like `M-x oooorg-timeline`) ... huh? Ok, googling around I came around this issue: https://github.com/emacs-helm/helm/issues/473 where the same issue is logged. So reading that, the solution seems to be to hit `C-u` after entering the full M-x command.

**Comment by thierryvolpiatto** [comment]
Sridhar Ratnakumar <notifications@github.com> writes:

> I read the embedded documentation, and still came out
> perplexed. Typing C-u results on [prefarg:4] tag added, and the next
> character I type repeats itself 4 times (like M-x oooorg-timeline)
> ... huh? Ok, googling around I came around this issue: #473 where the
> same issue is logged. So reading that, the solution seems to be to hit
> C-u after entering the full M-x command.

Read:
http://tinyurl.com/m9bdbce

And for this use case, of course when you hit C-u, the prefix arg is
applied to the next command you type, in your case "o" which is
self-insert-command.
You can try in any buffer to type C-u o you will see "oooo", this is a
feature not a bug, see documentation of self-insert-command.

So here the workflow with helm-M-x:
1) start it
2) type in to narrow down the list
3) when you found the command you want to run, you can type C-u (+ num
arg if necessary) and RET.
When you are unsure what prefix arg to type, hit C-j before typing this
prefix arg to read the doc.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Sridhar Ratnakumar <notifications@github.com> writes:

> I read the embedded documentation, and still came out
> perplexed. Typing C-u results on [prefarg:4] tag added, and the next
> character I type repeats itself 4 times (like M-x oooorg-timeline)
> ... huh? Ok, googling around I came around this issue: #473 where the
> same issue is logged. So reading that, the solution seems to be to hit
> C-u after entering the full M-x command.

BTW for such questions please use the mailing list.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
