### ISSUE TITLE
Make use of `helm-buffers-sort-transformer` customizable

### ISSUE THREAD

**Issue by Fuco1** [emacs-helm/helm#763]
With no narrowing, `helm-buffers-list` lists the buffers in LRU order.  However, as soon as I narrow, it sorts them by buffer name length.  I consider this an anti-feature: I usually want to jump to the least recently used, not to the shortest buffer matching a pattern.

Is there any reason at all to re-sort the candidates?

**Comment by Yevgnen** [comment]
I think when one use `helm-recentf`, he may want to find the most recent file that contains the prefix he typed. **At least** for `helm-recentf`. For other commands like `helm-find-files`, the pattern is more important of course.

#1507

**Comment by fred-apex-ai** [comment]
I stumbled across this old issue today. The behavior I see today is that `helm-recentf` behaves like `helm-buffers-list` was described above, and `helm-buffers-list` today is sort alphabetically from the very beginning, before narrowing even

**Comment by thierryvolpiatto** [comment]
Frederik Beaujean ***@***.***> writes:

> I stumbled across this old issue today. The behavior I see today is
> that helm-recentf behaves like helm-buffers-list was described above,
> and helm-buffers-list today is sort alphabetically > from the very
> beginning, before narrowing even

I installed a change that make
helm-fuzzy-matching-sort-fn-preserve-ties-order working again as
expected.

Is 

    (setq helm-buffers-sort-fn 'helm-fuzzy-matching-sort-fn-preserve-ties-order)

Fixing the issue for you ?

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you modified the open/close state.*Message ID: ***@***.***>

-- 
Thierry
