### ISSUE TITLE
helm-find-files asks for local root password for remote root files

### ISSUE THREAD

**Issue by tuhdo** [emacs-helm/helm#764]
When working over Tramp, trying to edit root files with `C-c r` opens local files instead.

**Comment by thierryvolpiatto** [comment]
I have commited a fix, assuming you have an entry for your remote host in tramp-default-proxies-alist.
WARNING: Fully not tested.

**Comment by thierryvolpiatto** [comment]
I think it should work correctly now, feel free to reopen if not.
