### ISSUE TITLE
Ability to set default background for helm action buffers?

### ISSUE THREAD

**Issue by TheoAndersen** [emacs-helm/helm#766]
I'm trying to set an alternate background color on quitable buffers (buffers you can quit) to make them clearer in emacs.

I'm doing this by using major-mode hooks and looking at the current binding of "q" and "C-g" to see if its a buffer than can be quit, and then using face-remap-add-relative to remap the background color in this buffer only.

face-remap-add-relative only works on the current buffer, and the "magic" in helm does that the action (suggestion) helm buffer isn't the current one.

Do you have a suggestion for how i can change the background color for the helm suggestion buffers without changing the default background for emacs? I've tried to see if the helm buffers have a common default background face, but i think that they use emacs default background color.

Thanks
/Theo

**Comment by ReneFroger** [comment]
I would be interested in this too! When you get it done, could you please share your relevant lines of code with us? I would like to try that out too!

**Comment by michael-heerdegen** [comment]
You probably want something like
```
(let ((buf (helm-buffer-get)))
  (when (get-buffer buf)
    (with-current-buffer buf
      do-something)))
```

**Comment by thierryvolpiatto** [comment]
I am closing this one as it is easy after all to implement this with overlays.
