### ISSUE TITLE
helm-semantic-or-imenu doesn't work properly

### ISSUE THREAD

**Issue by goofansu** [emacs-helm/helm#768]
Create an Erlang file: `test.erl`

```
-module(test).

fun1() ->
    ok.

fun2() ->
    ok.
```

When the cursor is at the beginning of `fun1` or `fun2`, `helm-semantic-or-imenu` cannot be invoked.

![helm-semantic-or-imenu](https://cloud.githubusercontent.com/assets/1143191/5487533/86146c58-86ed-11e4-8dfe-f5a6f446ad16.gif)

**Comment by hhnr** [comment]
Hi @tuhdo @goofansu , i am facing the same issue. With cc-mode, if the cursor is at the name of the function then helm-imenu doesn't list the list of functions in the buffer, instead it moves the cursor to the beginning of the line. Is it possible for helm-imenu to list the list of functions present in the file irrespective of where the cursor is located at?

**Comment by thierryvolpiatto** [comment]
Hariharan R <notifications@github.com> writes:

> Hi @tuhdo @goofansu , i am facing the same issue. With cc-mode, if the
> cursor is at the name of the function then helm-imenu doesn't list the
> list of functions in the buffer, instead it moves the cursor to the
> beginning of the line. Is it possible for helm-imenu to list the list
> of functions present in the file irrespective of where the cursor is
> located at?

Customize `helm-sources-using-default-as-input' (remove helm-imenu).

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
