### ISSUE TITLE
Looking for a way to make return dwim

### ISSUE THREAD

**Issue by milkypostman** [emacs-helm/helm#776]
In `helm-find-file` I'd like the following behavior,

* If I'm on a directory and I hit `return`, then expand that directory like `C-z`.
* If I'm on a file, exit the minibuffer and open that file.

Maybe I am missing it but is there already a way to do this? Otherwise, could you provide some guidance on how I might want to implement a function to do this? I would guess that there are functions available that will tell me whether I am currently on a file or a directory? I just couldn't find them off hand.

**Comment by ReneFroger** [comment]
Hi Thierry, 

Thanks for sharing your code snippet. Are you sure it's working?

I got into errors, when the variable helm-find-files-map doesn't exist.

**Comment by michael-heerdegen** [comment]
You must establish the key binding after the map has been definded, use e.g. 
```
(with-eval-after-load 'helm-files (define-key ...))
```
