### ISSUE TITLE
helm-locate-library + pattern starting with "j" crashes Emacs

### ISSUE THREAD

**Issue by vkz** [emacs-helm/helm#779]
Everything is freshly installed from MELPA (Helm version 20141225.14). Doing nothing fancy. Was just trying to locate **js2-refactor** library. Pattern: **refa** etc works fine. Any pattern that starts with **j** like say **js2-re** flat out crashes Emacs. Always. Tested with my old .emacs.d where I haven't updated any packages for a while and it seems to work just fine (Helm version 20141007).

**Comment by tuhdo** [comment]
@vkz I reinstalled my Mac OS X again and upgraded it to Yosemite. While I did have a crash using Emacs for Mac OS X (if you don't know, look it up on Google), using [emacs-mac-port](https://github.com/railwaycat/emacs-mac-port), I had no issue. It only had a brief freeze when I jammed many keys at once, but as soon as I pressed C-g, it went back to normal. I suggest you should give emacs-mac-port a try, and install it with brew.

**Comment by vkz** [comment]
@tuhdo emacs-mac-port crashes immediately as I type "j" when helm-locate-library. I'm officially out of Emacs 24 versions that work :)

**Comment by tuhdo** [comment]
Are you sure you ran correct Emacs binary? Someone confirmed it work in this issue: https://github.com/bbatsov/projectile/issues/600 (scroll at the end). After installing emacs-mac-port, you need to run it in `/usr/local/Cellar/emacs-mac/emacs-24.4-mac-5.2/bin/`, not just `emacs` in your terminal. If you want to run GUI, make an alias to your `Application` directory, or use `File Inder` and browse to there, then double click. The correct version should have GNU buffalo icon, not Emacs icon.

**Comment by tuhdo** [comment]
People using Spacemacs also solved this issue with `emacs-mac-port`. See it here: https://github.com/syl20bnr/spacemacs/issues/432

**Comment by vkz** [comment]
@tuhdo @thierryvolpiatto oh wow, so it's not just **j**. Beginning pattern in **helm-locate-library** with any of these keys crashes Emacs:

Qwerty(physical) -> Dvorak
------------------------------------
z -> ;
x -> q
c -> j

q -> '
w -> , 
] -> =
= -> ]

And maybe others. Incidentally, I tried switching to Qwerty layout and starting patters with the problematic keys e.g. typing keys **; q j ' , = ]** which are obviously different physical keys in Qwerty but have the same key-codes and they do crash Emacs too. Which leads me to believe that it's not a signal problem, not a hardware issue but rather likely something at Elisp level parsing key-codes and crashing on particular key-codes.

**Comment by tuhdo** [comment]
@vkz What's your OS X version? I confirmed that `helm-locate-library` did crash, but it happened only with the GUI Emacs of the official Brew you mentioned. It did not crash in terminal, and emacs-mac-port did not crash at all. I had more than 140 packages installed. are you sure you run the correct emacs-mac-port?

Probably you should create a new user account with absolute default configuration then try it again.

**Comment by vkz** [comment]
@tuhdo I've been trying GUI only, don't use emacs in terminal. This is how I've been running it:
```shell
95:lib kozin$ ll /Applications/Emacs*
lrwxr-xr-x  1 kozin  admin    56B Jan 16 20:08 /Applications/Emacs.app -> /usr/local/Cellar/emacs-mac/emacs-24.4-mac-5.2/Emacs.app

/Applications/Emacs24.app:
total 0
drwxr-xr-x@  3 kozin  LD\Domain Users   102B Oct 21 04:51 .
drwxrwxr-x+ 70 root   admin             2.3K Jan 16 20:08 ..
drwxr-xr-x@  7 kozin  LD\Domain Users   238B Oct 21 05:08 Contents
95:lib kozin$ open -a /usr/local/Cellar/emacs-mac/emacs-24.4-mac-5.2/Emacs.app -n --args -q -l ~/.personal_configs/emacs.candidate/init.el
95:lib kozin$ open -a Emacs.app -n --args -q -l ~/.personal_configs/emacs.candidate/init.el
```

**Comment by tuhdo** [comment]
@vkz Have you updated to the latest Yosemite? You should try in terminal using stock `emacs-helm.sh` to see if it crashes or not, so we can narrow the error to GUI interaction somewhere that causes this error.

**Comment by vkz** [comment]
Sadly don't know what to tell you. In this thread I tried it in every GUI version I could lay my hands on and as reported they either crashed or stalled. Versions I tried:
- Homebrew
  * default port (24.4)
  * HEAD (25)
  * emacs-mac-port version
- Emacs for Mac OSX binary
- Emacs built from official git repo

I ran most of them with and without clean helm using **emacs-helm.sh**, see earlier posts - it did not make a difference. Ran inside GDB.

**Comment by vkz** [comment]
I believe I'm running the latest Yosemite:
```
95:~ kozin$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: OS X 10.10.1 (14B25)
      Kernel Version: Darwin 14.0.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: ...
      User Name: ...
      Secure Virtual Memory: Enabled
      Time since boot: 18 days 9:21

```

**Comment by tuhdo** [comment]
I installed fresh Mac OS X (that is, format the whole hard drive with its recovery feature) and upgraded to Yosemite. Then I installed a few GNU utilities using Brew then installed both Emacs for Mac OS X and emacs-mac-port. It did not crash in terminal and emacs-mac-port.

We may need to know if it crash in terminal as well, so we can conclude this is a GUI issue.

**Comment by vkz** [comment]
doesn't seem to crash in terminal. Thinks longer than usual on **j** but does the right thing even finds **js2-...** and friends

**Comment by rymndhng** [comment]
+1 I have this problem as well!

**Comment by thierryvolpiatto** [comment]
I am closing this as it is OS specific and even on this OS (mac) few people can reproduce.
Feel free to reopen.

**Comment by acowley** [comment]
I can reproduce with or without an external display. Emacs 24.4 built from source on an updated OS X. I don't use `helm-locate-library`, so it doesn't affect me, but it's certainly an interesting bug.

**Comment by thierryvolpiatto** [comment]
Anthony Cowley <notifications@github.com> writes:

> I can reproduce with or without an external display. Emacs 24.4 built from source on an updated OS X. I don't use helm-locate-library, so it doesn't affect me, but
> it's certainly an interesting bug.

Certainly, but not related to helm IMO.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by rymndhng** [comment]
Yeah — I've moved on to using Emacs head and the problem has gone away.

On Fri, Mar 20, 2015 at 10:01 AM, Thierry Volpiatto <
notifications@github.com> wrote:

>
> Anthony Cowley <notifications@github.com> writes:
>
> > I can reproduce with or without an external display. Emacs 24.4 built
> from source on an updated OS X. I don't use helm-locate-library, so it
> doesn't affect me, but
> > it's certainly an interesting bug.
>
> Certainly, but not related to helm IMO.
>
> --
> Thierry
> Get my Gnupg key:
> gpg --keyserver pgp.mit.edu --recv-keys 59F29997
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/emacs-helm/helm/issues/779#issuecomment-84070704>.
>



-- 
Ray H @rymndhng

**Comment by abelardojarab** [comment]
can someone help me please with this?

my emacs keeps crashing all the time, no matter if im under Mac OS X or Linux. What package should i disable to make this go away?

i use configuration as here https://github.com/abelardojarab/emacsfull.git

1. bt gives this:

(gdb) bt
#0  0x00002aaaafa6b755 in raise () from /lib64/libc.so.6
#1  0x00002aaaafa6cd31 in abort () from /lib64/libc.so.6
#2  0x00002aaaafaa9c1f in __libc_message () from /lib64/libc.so.6
#3  0x00002aaaafaaf338 in malloc_printerr () from /lib64/libc.so.6
#4  0x00002aaaafaaf91f in malloc_consolidate () from /lib64/libc.so.6
#5  0x00002aaaafab0e30 in _int_free () from /lib64/libc.so.6
#6  0x00002aaaafab437c in free () from /lib64/libc.so.6
#7  0x000000000054fc73 in Fgarbage_collect ()
#8  0x0000000006b1c406 in ?? ()
#9  0x00000000000080f7 in ?? ()
#10 0x0000000000000001 in ?? ()
#11 0x01000000065b4ae8 in ?? ()
#12 0x0000000002e70000 in ?? ()
#13 0x0000000002e702c0 in ?? ()
#14 0x0000000000000000 in ?? ()


1. the gdb output after crashing is:

*** glibc detected *** /nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs: corrupted double-linked list: 0x0000000004d61210 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x76338)[0x2aaaafaaf338]
/lib64/libc.so.6(+0x7691f)[0x2aaaafaaf91f]
/lib64/libc.so.6(+0x77e30)[0x2aaaafab0e30]
/lib64/libc.so.6(cfree+0x6c)[0x2aaaafab437c]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x54fc73]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x59e9d8]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x5677af]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x56698a]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs(eval_sub+0x3a3)[0x566de3]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs(eval_sub+0x808)[0x567248]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x5695a1]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs(Ffuncall+0x484)[0x567da4]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x5661a4]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x43531b]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x4353ef]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x44b53e]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x44b6f9]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x44b6f9]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x450808]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x450af1]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x4682ab]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x46b61e]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x565efa]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x455572]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x455ee7]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x4f8912]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x5a9860]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x4288e3]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x4fb6d5]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x4fcfd0]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs(command_loop_1+0x1f9)[0x4fe499]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x565db0]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x4f16b3]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x565c9b]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x4f3913]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x4f3c85]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x41e59f]
/lib64/libc.so.6(__libc_start_main+0xe6)[0x2aaaafa57c16]
/nfs/site/itools/em64t_SLES11/pkgs/wrapper/2.06/bin/emacs[0x41f355]
======= Memory map: ========
00400000-00634000 r-xp 00000000 00:28 6470881                            /nfs/site/itools/em64t_SLES11/pkgs/emacs/24.4/bin/emacs-24.4
00834000-01368000 rw-p 00234000 00:28 6470881                            /nfs/site/itools/em64t_SLES11/pkgs/emacs/24.4/bin/emacs-24.4
01368000-06c16000 rw-p 00000000 00:00 0                                  [heap]
2aaaaaaab000-2aaaaaaca000 r-xp 00000000 08:02 32634                      /lib64/ld-2.11.3.so
2aaaaaaca000-2aaaaaacb000 r-xp 00000000 00:00 0                          [vdso]
2aaaaaacb000-2aaaaaacd000 rw-p 00000000 00:00 0 
2aaaaacc9000-2aaaaacca000 r--p 0001e000 08:02 32634                      /lib64/ld-2.11.3.so
2aaaaacca000-2aaaaaccb000 rw-p 0001f000 08:02 32634                      /lib64/ld-2.11.3.so
2aaaaaccb000-2aaaaaccc000 rw-p 00000000 00:00 0 
2aaaaaccc000-2aaaaad2c000 r-xp 00000000 00:28 2898131                    /nfs/site/itools/em64t_SLES11/pkgs/tiff/3.9.1-64/lib64/libtiff.so.3.9.1
2aaaaad2c000-2aaaaaf2c000 ---p 00060000 00:28 2898131                    /nfs/site/itools/em64t_SLES11/pkgs/tiff/3.9.1-64/lib64/libtiff.so.3.9.1
2aaaaaf2c000-2aaaaaf2e000 r--p 00060000 00:28 2898131                    /nfs/site/itools/em64t_SLES11/pkgs/tiff/3.9.1-64/lib64/libtiff.so.3.9.1
2aaaaaf2e000-2aaaaaf2f000 rw-p 00062000 00:28 2898131                    /nfs/site/itools/em64t_SLES11/pkgs/tiff/3.9.1-64/lib64/libtiff.so.3.9.1
2aaaaaf2f000-2aaaaaf30000 rw-p 00000000 00:00 0 
2aaaaaf30000-2aaaaaf4e000 r-xp 00000000 00:28 5340277                    /nfs/site/itools/em64t_SLES11/pkgs/jpeg/6b-64/lib/libjpeg.so.62.0.0
2aaaaaf4e000-2aaaab04d000 ---p 0001e000 00:28 5340277                    /nfs/site/itools/em64t_SLES11/pkgs/jpeg/6b-64/lib/libjpeg.so.62.0.0
2aaaab04d000-2aaaab051000 rw-p 0001d000 00:28 5340277                    /nfs/site/itools/em64t_SLES11/pkgs/jpeg/6b-64/lib/libjpeg.so.62.0.0
2aaaab051000-2aaaab076000 r-xp 00000000 00:28 18211497                   /nfs/site/itools/em64t_SLES11/pkgs/libpng/1.2.40-64/lib/libpng12.so.0.40.0
2aaaab076000-2aaaab275000 ---p 00025000 00:28 18211497                   /nfs/site/itools/em64t_SLES11/pkgs/libpng/1.2.40-64/lib/libpng12.so.0.40.0
2aaaab275000-2aaaab276000 r--p 00024000 00:28 18211497                   /nfs/site/itools/em64t_SLES11/pkgs/libpng/1.2.40-64/lib/libpng12.so.0.40.0
2aaaab276000-2aaaab277000 rw-p 00025000 00:28 18211497                   /nfs/site/itools/em64t_SLES11/pkgs/libpng/1.2.40-64/lib/libpng12.so.0.40.0
2aaaab277000-2aaaab28a000 r-xp 00000000 00:28 3086824                    /nfs/site/itools/em64t_SLES11/pkgs/zlib/1.2.x-64/lib64/libz.so.1.2.3
2aaaab28a000-2aaaab389000 ---p 00013000 00:28 3086824                    /nfs/site/itools/em64t_SLES11/pkgs/zlib/1.2.x-64/lib64/libz.so.1.2.3
2aaaab389000-2aaaab38b000 rw-p 00012000 00:28 3086824                    /nfs/site/itools/em64t_SLES11/pkgs/zlib/1.2.x-64/lib64/libz.so.1.2.3
2aaaab38b000-2aaaab38c000 r--p 00000000 08:05 254032                     /usr/lib/locale/en_US.utf8/LC_IDENTIFICATION
2aaaab38c000-2aaaab393000 r--s 00000000 08:05 13411                      /usr/lib64/gconv/gconv-modules.cache
2aaaab393000-2aaaab394000 r--p 00000000 08:05 261916                     /usr/lib/locale/en_US.utf8/LC_MEASUREMENT
2aaaab394000-2aaaab395000 r--p 00000000 08:05 261911                     /usr/lib/locale/en_US.utf8/LC_TELEPHONE
2aaaab395000-2aaaab396000 r--p 00000000 08:05 251910                     /usr/lib/locale/en_US.utf8/LC_ADDRESS
2aaaab396000-2aaaab397000 r--p 00000000 08:05 260579                     /usr/lib/locale/en_US.utf8/LC_NAME
2aaaab397000-2aaaab398000 r--p 00000000 08:05 260566                     /usr/lib/locale/en_US.utf8/LC_PAPER
2aaaab398000-2aaaab399000 r--p 00000000 08:05 261912                     /usr/lib/locale/en_US.utf8/LC_MESSAGES/SYS_LC_MESSAGES
2aaaab399000-2aaaab39a000 r--p 00000000 08:05 254033                     /usr/lib/locale/en_US.utf8/LC_MONETARY
2aaaab39a000-2aaaab39b000 r--p 00000000 08:05 254034                     /usr/lib/locale/en_US.utf8/LC_TIME
2aaaab39b000-2aaaab39c000 r--p 00000000 08:05 260632                     /usr/lib/locale/en_US.utf8/LC_NUMERIC
2aaaab3ab000-2aaaab406000 r-xp 00000000 08:02 32403                      /lib64/libm-2.11.3.so
2aaaab406000-2aaaab605000 ---p 0005b000 08:02 32403                      /lib64/libm-2.11.3.so
2aaaab605000-2aaaab606000 r--p 0005a000 08:02 32403                      /lib64/libm-2.11.3.so
2aaaab606000-2aaaab624000 rw-p 0005b000 08:02 32403                      /lib64/libm-2.11.3.so
2aaaab624000-2aaaab625000 rw-p 00000000 00:00 0 
2aaaab625000-2aaaab636000 r-xp 00000000 00:28 32887742                   /nfs/site/itools/em64t_SLES11/pkgs/X11/R7.5-64/lib/libXpm.so.4.11.0
2aaaab636000-2aaaab835000 ---p 00011000 00:28 32887742                   /nfs/site/itools/em64t_SLES11/pkgs/X11/R7.5-64/lib/libXpm.so.4.11.0
2aaaab835000-2aaaab836000 r--p 00010000 00:28 32887742                   /nfs/site/itools/em64t_SLES11/pkgs/X11/R7.5-64/lib/libXpm.so.4.11.0
2aaaab836000-2aaaab837000 rw-p 00011000 00:28 32887742                   /nfs/site/itools/em64t_SLES11/pkgs/X11/R7.5-64/lib/libXpm.so.4.11.0
2aaaab837000-2aaaabc34000 r-xp 00000000 00:28 16585724                   /nfs/site/itools/em64t_SLES11/pkgs/gtk+/2.18.6-64/lib64/libgtk-x11-2.0.so.0.1800.6
2aaaabc34000-2aaaabe34000 ---p 003fd000 00:28 16585724                   /nfs/site/itools/em64t_SLES11/pkgs/gtk+/2.18.6-64/lib64/libgtk-x11-2.0.so.0.1800.6
2aaaabe34000-2aaaabe3b000 r--p 003fd000 00:28 16585724                   /nfs/site/itools/em64t_SLES11/pkgs/gtk+/2.18.6-64/lib64/libgtk-x11-2.0.so.0.1800.6
2aaaabe3b000-2aaaabe3f000 rw-p 00404000 00:28 16585724                   /nfs/site/itools/em64t_SLES11/pkgs/gtk+/2.18.6-64/lib64/libgtk-x11-2.0.so.0.1800.6
2aaaabe3f000-2aaaabe41000 rw-p 00000000 00:00 0 
2aaaabe41000-2aaaabee7000 r-xp 00000000 00:28 6779303                    /nfs/site/itools/em64t_SLES11/pkgs/gtk+/2.18.6-64/lib64/libgdk-x11-2.0.so.0.1800.6
2aaaabee7000-2aaaac0e6000 ---p 000a6000 00:28 6779303                    /nfs/site/itools/em64t_SLES11/pkgs/gtk+/2.18.6-64/lib64/libgdk-x11-2.0.so.0.1800.6
2aaaac0e6000-2aaaac0ea000 r--p 000a5000 00:28 6779303                    /nfs/site/itools/em64t_SLES11/pkgs/gtk+/2.18.6-64/lib64/libgdk-x11-2.0.so.0.1800.6
2aaaac0ea000-2aaaac0ec000 rw-p 000a9000 00:28 6779303                    /nfs/site/itools/em64t_SLES11/pkgs/gtk+/2.18.6-64/lib64/libgdk-x11-2.0.so.0.1800.6
2aaaac0ec000-2aaaac0ed000 rw-p 00000000 00:00 0 
2aaaac0ed000-2aaaac10b000 r-xp 00000000 00:28 29753415                   /nfs/site/itools/em64t_SLES11/pkgs/atk/1.28.0-64/lib64/libatk-1.0.so.0.2809.1
2aaaac10b000-2aaaac30b000 ---p 0001e000 00:28 29753415                   /nfs/site/itools/em64t_SLES11/pkgs/atk/1.28.0-64/lib64/libatk-1.0.so.0.2809.1
2aaaac30b000-2aaaac30d000 r--p 0001e000 00:28 29753415                   /nfs/site/itools/em64t_SLES11/pkgs/atk/1.28.0-64/lib64/libatk-1.0.so.0.2809.1
2aaaac30d000-2aaaac30e000 rw-p 00020000 00:28 29753415                   /nfs/site/itools/em64t_SLES11/pkgs/atk/1.28.0-64/lib64/libatk-1.0.so.0.2809.1
2aaaac30e000-2aaaac3b3000 r-xp 00000000 00:28 9290844                    /nfs/site/itools/em64t_SLES11/pkgs/glib/2.22.3-64/lib64/libgio-2.0.so.0.2200.3
2aaaac3b3000-2aaaac5b3000 ---p 000a5000 00:28 9290844                    /nfs/site/itools/em64t_SLES11/pkgs/glib/2.22.3-64/lib64/libgio-2.0.so.0.2200.3
2aaaac5b3000-2aaaac5b5000 r--p 000a5000 00:28 9290844                    /nfs/site/itools/em64t_SLES11/pkgs/glib/2.22.3-64/lib64/libgio-2.0.so.0.2200.3
2aaaac5b5000-2aaaac5b6000 rw-p 000a7000 00:28 9290844                    /nfs/site/itools/em64t_SLES11/pkgs/glib/2.22.3-64/lib64/libgio-2.0.so.0.2200.3
2aaaac5b6000-2aaaac5b7000 rw-p 00000000 00:00 0 
2aaaac5b7000-2aaaac5df000 r-xp 00000000 00:28 23448439                   /nfs/site/itools/em64t_SLES11/pkgs/pango/1.26.2-64/lib64/libpangoft2-1.0.so.0.2600.2
2aaaac5df000-2aaaac7de000 ---p 00028000 00:28 23448439                   /nfs/site/itools/em64t_SLES11/pkgs/pango/1.26.2-64/lib64/libpangoft2-1.0.so.0.2600.2
2aaaac7de000-2aaaac7df000 r--p 00027000 00:28 23448439                   /nfs/site/itools/em64t_SLES11/pkgs/pango/1.26.2-64/lib64/libpangoft2-1.0.so.0.2600.2
2aaaac7df000-2aaaac7e0000 rw-p 00028000 00:28 23448439                   /nfs/site/itools/em64t_SLES11/pkgs/pango/1.26.2-64/lib64/libpangoft2-1.0.so.0.2600.2
2aaaac7e0000-2aaaac7e1000 rw-p 00000000 00:00 0 
2aaaac7e1000-2aaaac7fc000 r-xp 00000000 00:28 16585719                   /nfs/site/itools/em64t_SLES11/pkgs/gtk+/2.18.6-64/lib64/libgdk_pixbuf-2.0.so.0.1800.6
2aaaac7fc000-2aaaac9fb000 ---p 0001b000 00:28 16585719                   /nfs/site/itools/em64t_SLES11/pkgs/gtk+/2.18.6-64/lib64/libgdk_pixbuf-2.0.so.0.1800.6
2aaaac9fb000-2aaaac9fc000 r--p 0001a000 00:28 16585719                   /nfs/site/itools/em64t_SLES11/pkgs/gtk+/2.18.6-64/lib64/libgdk_pixbuf-2.0.so.0.1800.6
2aaaac9fc000-2aaaac9fd000 rw-p 0001b000 00:28 16585719                   /nfs/site/itools/em64t_SLES11/pkgs/gtk+/2.18.6-64/lib64/libgdk_pixbuf-2.0.so.0.1800.6
2aaaac9fd000-2aaaaca08000 r-xp 00000000 00:28 23448437                   /nfs/site/itools/em64t_SLES11/pkgs/pango/1.26.2-64/lib64/libpangocairo-1.0.so.0.2600.2
2aaaaca08000-2aaaacc08000 ---p 0000b000 00:28 23448437                   /nfs/site/itools/em64t_SLES11/pkgs/pango/1.26.2-64/lib64/libpangocairo-1.0.so.0.2600.2
2aaaacc08000-2aaaacc09000 r--p 0000b000 00:28 23448437                   /nfs/site/itools/em64t_SLES11/pkgs/pango/1.26.2-64/lib64/libpangocairo-1.0.so.0.2600.2
2aaaacc09000-2aaaacc0a000 rw-p 0000c000 00:28 23448437                   /nfs/site/itools/em64t_SLES11/pkgs/pango/1.26.2-64/lib64/libpangocairo-1.0.so.0.2600.2
2aaaacc0a000-2aaaacc7f000 r-xp 00000000 00:28 25890820                   /nfs/site/itools/em64t_SLES11/pkgs/cairo/1.8.8-64/lib/libcairo.so.2.10800.8
2aaaacc7f000-2aaaace7f000 ---p 00075000 00:28 25890820                   /nfs/site/itools/em64t_SLES11/pkgs/cairo/1.8.8-64/lib/libcairo.so.2.10800.8
2aaaace7f000-2aaaace81000 r--p 00075000 00:28 25890820                   /nfs/site/itools/em64t_SLES11/pkgs/cairo/1.8.8-64/lib/libcairo.so.2.10800.8
2aaaace81000-2aaaace82000 rw-p 00077000 00:28 25890820                   /nfs/site/itools/em64t_SLES11/pkgs/cairo/1.8.8-64/lib/libcairo.so.2.10800.8
2aaaace82000-2aaaace83000 rw-p 00000000 00:00 0 
2aaaace83000-2aaaacecb000 r-xp 00000000 00:28 23448435                   /nfs/site/itools/em64t_SLES11/pkgs/pango/1.26.2-64/lib64/libpango-1.0.so.0.2600.2
2aaaacecb000-2aaaad0cb000 ---p 00048000 00:28 23448435                   /nfs/site/itools/em64t_SLES11/pkgs/pango/1.26.2-64/lib64/libpango-1.0.so.0.2600.2
2aaaad0cb000-2aaaad0cd000 r--p 00048000 00:28 23448435                   /nfs/site/itools/em64t_SLES11/pkgs/pango/1.26.2-64/lib64/libpango-1.0.so.0.2600.2
2aaaad0cd000-2aaaad0ce000 rw-p 0004a000 00:28 23448435                   /nfs/site/itools/em64t_SLES11/pkgs/pango/1.26.2-64/lib64/libpango-1.0.so.0.2600.2
2aaaad0ce000-2aaaad14d000 r-xp 00000000 00:28 134817                     /nfs/site/itools/em64t_SLES11/pkgs/freetype/2.3.7-64/lib/libfreetype.so.6.3.18
Program received signal SIGABRT, Aborted.
[Switching to Thread 0x2aaab1a8c880 (LWP 38558)]
0x00002aaaafa6b755 in raise () from /lib64/libc.so.6
(gdb) 


2.
