### ISSUE TITLE
Customizing actions of type classes

### ISSUE THREAD

**Issue by michael-heerdegen** [emacs-helm/helm#781]
Hello,

I would like to be able to customize the actions of type classes
(especially the order).  This is currently not possible because the
action lists are hardcoded in method bodies.

I have two related questions:

1.  Why do the type classes (`helm-type-file' etc.) not directly use
slots?  Why do we define methods that do set the slots?  Currently,
all the methods do is directly oset'ing slots.  Would it not be better
to simply use inheritance instead?

2.  Should the type classes be defined :abstact?  IIUC defining
instances of these classes doesn't make much sense.

I think ideally, the action lists could be defined as class variables
that are initialized from defcustoms.  If you have good reasons to use
methods to set slots, we can still use a defcustom for the action
lists, maybe for other slots as well.

Thanks, Michael.

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> >> I have planned allowing customization of actions, didn't have
> >> decided how though.
> >
> > That's great. The "how" part is not trivial.
>
> Yes, it's why I haven't do it already.

The solution would be easy if we would allow the value of the action
slot of sources to be a symbol.  It's binding would be looked up at run
time to get the actions.  With that approach, all action lists would
just become simple defcustoms instead of the hardcoded lists in some
code that we have now.

This might be a good idea anyhow.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> The solution would be easy if we would allow the value of the action
> slot of sources to be a symbol. It's binding would be looked up at run
> time to get the actions. With that approach, all action lists would
> just become simple defcustoms instead of the hardcoded lists in some
> code that we have now.

Yes, something like this.

> This might be a good idea anyhow.

I didn't look into this yet, I hope I will have the time to start
working on this soon.

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
From now it is possible customizing some sources, some still hardcoded though, I will make them customizable as needed.

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> From now it is possible customizing some sources, some still hardcoded
> though, I will make them customizable as needed.

Thanks for working on this.  I tried it and adopted my setup
accordingly.  So far, everything works as expected.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Thierry Volpiatto <notifications@github.com> writes:
>
>> From now it is possible customizing some sources, some still hardcoded
>> though, I will make them customizable as needed.
>
> Thanks for working on this. I tried it and adopted my setup
> accordingly. So far, everything works as expected.

Great! Thanks for testing.
 
-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Just a reminder:
Probably the defcustoms should have a set function using `helm-make-actions`.
This would allow adding actions with condition like in `helm-make-actions`.
i.e `((lambda () (code returning string or nil)) . action)`

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> Probably the defcustoms should have a set function using
> helm-make-actions.  This would allow adding actions with condition
> like in helm-make-actions.  i.e ((lambda () (code returning string or
> nil)) . action)

I think that makes perfectly sense, yes.
