### ISSUE TITLE
Face helm-selection does not apply to all marked candidates

### ISSUE THREAD

**Issue by trashofmasters** [emacs-helm/helm#784]
When marking candidates in Helm buffers, some candidates randomly ignore the background colour definition (`helm-selection`) while still getting underlined.

On the one hand this is an innocent issue but on the other hand it might become quite aggravating when themes disable text underlining on hover.

The animation below shows the issue reproduced on a vanilla GNU Emacs 24.4.50.1 with only Helm loaded:

<img src="https://cloud.githubusercontent.com/assets/30650/5578113/ee1b361a-9020-11e4-9a4f-c599cff71cfc.gif" width="330px"/>

This issue affects various versions of Helm, specifically I have reproduced it on v1.6.5 and 628ded4.

**Comment by thierryvolpiatto** [comment]
Should be fixed now, sorry for the delay, feel free to reopen if something wrong.
Thanks.
