### ISSUE TITLE
Display the actual number of candidates along side with helm-candidate-number-limit

### ISSUE THREAD

**Issue by tuhdo** [emacs-helm/helm#787]
It's useful to know the real total number of candidates, i.e. how many files this project has, or how many definitions the current file contains, how many commands in `helm-M-x` we have... so we can choose more suitable pattern for completion. For example, for a large number of candidates (like 30k) we might enter longer pattern(s) (exact match is usually better in this case) to get more accurate results; for a small number of candidates, we might enter shorter pattern(s) to get desire result.

Since Helm holds the collection before displaying, we can easily get the length for the current Helm session.

**Comment by tuhdo** [comment]
> AFAIU he wants to see the total number of candidates being matched against.

Yes. For example, `helm-ls-git-ls` can retrieve 10,000 files but it only displays 100 files, the rest is hidden. I want to see something like `100/10,000`.

> BTW you can use always `C-c a' to show all candidates, but I am not sure it is what you want.

It's not always feasible to show all, since the number of candidates can be huge.

**Comment by thierryvolpiatto** [comment]
> I think this number is not necessarily well defined in all cases, e.g. for volatile sources.

This is true so I will close this issue.
