### ISSUE TITLE
bug for cons-cell persistent-action??  (helm-source--header-line)

### ISSUE THREAD

**Issue by genovese** [emacs-helm/helm#788]
The documentation for the persistent action property says:

    Can be a either a Function called with one parameter (the
    selected candidate) or a cons cell where first element is this
    same function and second element a symbol (e.g never-split)
    that inform `helm-execute-persistent-action'to not split his
    window to execute this persistent action.

But whenever I use a cons-cell I get an error in `helm-source--header-line`.

    Debugger entered--Lisp error: (wrong-type-argument sequencep closure)

Sometimes it says `lambda` instead of `closure`. For a toy example:

    (helm-comp-read
     "silly: " '(1 2 3 4 5 6 7 8 9 10 11 12)
     :test 'evenp
     :requires-pattern 0
     :name "Demonstrating help issue"
     :buffer "*helm-source--header-line bug?*"
     :persistent-action (cons (lambda (candidate) (message "%s" candidate)) 'nosplit)
     :persistent-help "Useless message"
     :keymap helm-map
     :candidates-in-buffer t)

On a quick look, it seems to me that the problem is the use of `caar` in
the persistent action case (see code below); shouldn't it just be `car`
in that case?

    (defun helm-source--header-line (source)
      (substitute-command-keys
       (concat "\\<helm-map>\\[helm-execute-persistent-action]: "
               (helm-aif (or (oref source :persistent-action)
                             (oref source :action))
                   (cond ((symbolp it)
                          (symbol-name it))
                         ((listp it)
                          (or (ignore-errors (caar it))  "")))
                 "")
               " (keeping session)")))

Note that the cons structure is used explicitly in `helm-execute-persistent-action`,
so unless there's an  interaction with the eieio object representation of the
sources (which I have not investigated too deeply), this `caar` looks like an inconsistency.

**Comment by genovese** [comment]
P.S. Just as a quick follow up, in case it wasn't clear from what I wrote:
changing to `car` would not be enough in the persistent-action case
because the result of the helm-aif should be converted to a string.
I was just focusing above on what was being accessed.

Converting the `(car it)` to a string inside the `ignore-errors` fixed the problem
for the cases where I was using the cons.  But I only tested the persistent
action case.

**Comment by thierryvolpiatto** [comment]
Christopher Genovese <notifications@github.com> writes:

> But whenever I use a cons-cell I get an error in helm-source--header-line.

Should be fixed now, with also a bug that your recipe raise (with
numbers as candidates).

Thanks to catch this.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
