### ISSUE TITLE
helm-etags doesn't play nice with duplicate tags 

### ISSUE THREAD

**Issue by falbunation** [emacs-helm/helm#790]
TheTAGS file can include multiple entries with the same tag name, by design, but `helm-etags` only displays the first one to occur in the file. 
My project uses more then one language and there are many such collisions. helm is, unusually, not being helpful about it.

I'm using `tags-apropos` out of necessity but would much prefer to stick with helm, if it would learn to handle this.

**Comment by thierryvolpiatto** [comment]
falbunation <notifications@github.com> writes:

> TheTAGS file can include multiple entries with the same tag name, by design, but helm-etags only displays the first one to occur in the file.
> My project uses more then one language and there are many such collisions. helm is, unusually, not being helpful about it.
>
> I'm using tags-apropos out of necessity but would much prefer to stick with helm, if it would learn to handle this.

Is adding this in your init file fix problem ?

(with-eval-after-load "helm-tags.el"
    (helm-attrset 'allow-dups t helm-source-etags-select))

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
falbunation <notifications@github.com> writes:

> TheTAGS file can include multiple entries with the same tag name, by
> design, but helm-etags only displays the first one to occur in the
> file.  My project uses more then one language and there are many such
> collisions. helm is, unusually, not being helpful about it.
>
> I'm using tags-apropos out of necessity but would much prefer to stick
> with helm, if it would learn to handle this.

BTW could you give me a recipe to reproduce issue with small sample
files in diverses language as in your project (or just the link to your
project so that I can clone it)

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by falbunation** [comment]
Is adding this in your init file fix problem ?
    (with-eval-after-load "helm-tags.el" 
         (helm-attrset 'allow-dups t helm-source-etags-select))

I'm afraid that doesn't seem to help. I've manually eval'd `helm-attrset` and am using `helm-20141222.1353`.

    could you give me a recipe to reproduce issue

Sure. I've put up a [repo](https://github.com/falbunation/helm-tags-issue-repo) that duplicates the issue artificially. Just run `make` to generate the TAGS file, Ignore the invalid c code.
`tag-apropos` shows two locations for `foo1`, but `find-tag` completion with helm shows a single entry, that is the matching tag but not the locations it maps to.

Is there a way to get helm to show all tag locations or an indication that more then one location exists for a given tag?

Thanks very much for the help and quick reply.

**Comment by tuhdo** [comment]
Don't use `find-tag`, which is just a hemified version. Use `helm-etags-select`, the actual Helm command for etags. It solves this problem of yours.

**Comment by falbunation** [comment]
I love helm.

Thank you!

**Comment by tuhdo** [comment]
You should update to latest Helm. It has been added with faces for filename and line number, make it easier for the eyes.

**Comment by falbunation** [comment]
I will and also read through your fantastic "C++ on emacs" guide , thanks for that too.
