### ISSUE TITLE
find-files: Preselect first non . or .. entry in directory

### ISSUE THREAD

**Issue by rootzlevel** [emacs-helm/helm#792]
In helm-find-files:

When drilling down into a directory with helm-persistant-action, the selected candidate of the new directory is the first entry, namly ".". This is almost always useless and a much better default would be the first entry that is not "." or ".." (if it exists, of course). 

Chances that the intended target is already selected are higher, especially in directories that only contain one entry. Even if the first entry is not the right one, selecting other entries requires 2 C-n less.

The reason that "." is not a good default is, that if one wants to execute an action on this directory, it would have been possible before hitting helm-persistant-action. So if the user drilled down into this new directory, she probably want's to do something with the content, not the directory itself.

**Comment by scturtle** [comment]
When `haskell-mode` starts a project, it involves steps to select directories not files. Usually we just hit `enter` to select the default one guessed by `haskell-mode` but this change in `helm` causes problem. Please reconsider this situation.

**Comment by thierryvolpiatto** [comment]
scturtle <notifications@github.com> writes:

> When haskell-mode starts a project, it involves steps to select
> directories not files. Usually we just hit enter to select the default
> one guessed by haskell-mode but this change in helm causes
> problem. Please reconsider this situation.

Done, reverted.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
I welcome reverting this change, because it also complicated calling dired  (yes, I know you find it obsolete Thierry, but some of us are using it).

**Comment by dsemke** [comment]
Could this feature be reconsidered? I feel the same way as @rootzlevel, in that this default behavior is not a very good default. Perhaps have a configuration option so it doesn't interfere with the workflows the other posters mentioned

**Comment by thierryvolpiatto** [comment]
dsemke <notifications@github.com> writes:

> Could this feature be reconsidered?

No, as you can see other people don't like this (and me too).

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
@dsemke  You can of course just advice "helm-ff-move-to-first-real-candidate" to do what you want.
