### ISSUE TITLE
find-files: Show other matches, even if an exact match is available

### ISSUE THREAD

**Issue by rootzlevel** [emacs-helm/helm#793]
Currently, if a directory contains the files "a", "ab" and "abc", typing "a" in helm-find-files shows only one candidate, namly "a". This is unfortunate, because maybe the user wasn't trying to match "a", but "abc" and the current behavious requires him to type two extra letters of the name blindly without being shown his target file as a candidate.

Of course, the exact match should still be selected (and/or) first candidate, but not the only candidate

**Comment by thierryvolpiatto** [comment]
Hans-Peter Deifel <notifications@github.com> writes:

> Currently, if a directory contains the files "a", "ab" and "abc",
> typing "a" in helm-find-files shows only one candidate, namly
> "a". This is unfortunate, because maybe the user wasn't trying to
> match "a", but "abc" and the current behavious requires him to type
> two extra letters of the name blindly without being shown his target
> file as a candidate.

This issue have been submited several times, but never really fixed
because it was removing other features, now it should be fixed.

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
