### ISSUE TITLE
find-files: Sort order changes if directory is matched exactly

### ISSUE THREAD

**Issue by rootzlevel** [emacs-helm/helm#794]
In a directory with the two subdirectories "foo" and ".foobar", typing "f" or "fo" shows "foo" as first candidate. But typing "foo" changes the sort order and shows ".foobar" as first candidate. That alone is suprising, but it gets worse if there are 3 subdirectories:

-  foc/
-  foo/
-  .foobar/

Then it's not possible to select "foo" just by typing its name. Typing "fo" still matches "foc" and typing "foo" suddenly matches ".foobar"

**Comment by dakrone** [comment]
This is related to #145 I believe

**Comment by thierryvolpiatto** [comment]
Hans-Peter Deifel <notifications@github.com> writes:

> In a directory with the two subdirectories "foo" and ".foobar", typing "f" or "fo" shows "foo" as first candidate. But typing "foo" changes the sort order and shows
> ".foobar" as first candidate. That alone is suprising, but it gets worse if there are 3 subdirectories:
>
>   * foc/
>   * foo/
>   * .foobar/
>
> Then it's not possible to select "foo" just by typing its name. Typing "fo" still matches "foc" and typing "foo" suddenly matches ".foobar"

This can be fixed if you enable auto completion (hit C-<backspace>) or
enable it by default with helm-ff-auto-update-initial-value.
Unfortunately it is not the default because new users are confused by
this when they want to create a new file or directory because they don't
know C-<backspace>.

Otherwise no special sorting is done actually on directories 
(It is string-lessp from directory-files)

If "foo", "foc" and ".foobar" are files sorting will be done and "foo"
will appear in first position.
 
-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by rootzlevel** [comment]
Well, I have auto-update explicitly turned off, but this has nothing to do with the creation of new files or me not knowing about C-<backspace>.

The problem with auto-update is actually this: I (and presumably many other users) type 3-5 letters of a word faster than I can process changes on the display. So my mode of operation is to to type part of a word, hit tab if my intended file is selected or type more letters and repeat. With auto-update, I would have to check afer every single letter if my directory (or another directory that happens to be an exact match, but is not what I wanted) is already expanded.

I gave auto-update it's fair chance, but it just slowed me down. I found myself either actively pausing and checking after each letter or constantly deleting excess letters that I typed without noticing that the directory had already expanded.

**Comment by thierryvolpiatto** [comment]
Hans-Peter Deifel <notifications@github.com> writes:

> The problem with auto-update is actually this: I (and presumably many
> other users) type 3-5 letters of a word faster than I can process
> changes on the display.

When you are used to auto update it is really efficient and allow you to
move much faster, but well you need to get used to this, I personally
use this and I am happy with it.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
I have finally fixed this without breaking anything else (I hope).
Was easier that expected.
Should be merged tomorrow.

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Now you can have this by setting `helm-find-files-sort-directories` to non--nil.
Expect slowdown though.
