### ISSUE TITLE
Helm locate, a way to enable limit the search results? 

### ISSUE THREAD

**Issue by ReneFroger** [emacs-helm/helm#795]
Hi there!

Forgive my frequently questions, but I couldn't find any answer on this. 
When I use `Helm for-files`, and Helm is initialized, I found the amount of results that I receive often too overwhelming. 

When I took a look in the Helm wiki, I see I could give a argument with my patern, like for example: `foo -n 30`. But I would like to set it as default.
If this is not possible, what about another option to initiate helm locate in Helm for-files, after putting 6 characters? 

Sorry for my many questions, by the way. I couldn't find a possible answer anywhere.

**Comment by tuhdo** [comment]
You can ask usage questions in [Helm Google group](https://groups.google.com/forum/#!forum/emacs-helm).

> I found the amount of results that I receive often too overwhelming.

One way is to narrow more, or to remember a unique pattern of the subset of candidates you want to narrow to. For example, if you want a filename, just type in filename first, and if there many results, move cursor to the beginning and keep adding more text to filter. Remember that you helm-locate uses regular expression (as well as other helm commands, by default), so you can use regex to yield more accurate matching. i.e. if you want to find a file named `helm-files.el`, but the `.elc` files got mixed in, add `$` to the end of the pattern to narrow to only `.el` files.

Btw, after I answered you on my page, I realized that it's possible to integrate Everything with helm-locate. It is explicitly written [in helm-locate comment](https://github.com/emacs-helm/helm/blob/master/helm-locate.el). I haven't used Everything, so it's a good chance to ask @thierryvolpiatto proper command line arguments for helm-locate to consume. Then, I will update my guide with additional detail about helm-locate for Windows as well.

**Comment by ReneFroger** [comment]
Yes. I could type more relevant regex to narrow the files in Helm Locate. 

But that's not the problem. The thing here is that I use autoresizing for Helm. When I type a word, and I get one hit, it's located on the top of my 2560x1600 screen. But I must search good where my hit goes, because the rest of my screen is filled with Helm Locate, which I find it personally annoying. My relevant recentf or file are crammed into the top. 

So I would prefer to limit the showed results in Helm Locate to 30 or something, or initiate after some characters. A screenshot to illustrate my issue: 

![schermafdruk 2015-01-03 16 41 24](https://cloud.githubusercontent.com/assets/5211845/5602824/b02f1c64-9367-11e4-804d-718bc62e4b98.png)

**Comment by tuhdo** [comment]
You can set the maximum height (by lines) of current Helm buffer, using the same code for autoresizing previously but with a little modification:

```
;; get-buffer-window returns the current window buffer is in
(defun helm-autoresize-hook ()
  (with-helm-window (fit-window-to-buffer (get-buffer-window) 20))) ; maximum 20 lines

(add-hook 'helm-after-update-hook 'helm-autoresize-hook)

(setq helm-always-two-windows  t)
```

**Comment by ReneFroger** [comment]
Great, that solves my issue. 

By the way,how would you know to give 20 as argument for fit-window-to-buffer? Is there a way to look up that?

**Comment by tuhdo** [comment]
There are four ways:

- Eldoc is a minor mode which shows you the argument list of function at point in the echo area. Here is [an example](http://3.bp.blogspot.com/_WYfJEM2p5Uo/SxKo1BROC6I/AAAAAAAAAL4/LJxE8o6uQkk/s1600/eldoc-demo.png). When point is at the 2rd argument, the 2rd parameter is also highlighted in the echo area, as you can see in the screenshot. When point is on a variable, docstring is displayed.

- Using <kbd>C-h f</kbd>, which runs `described-function`. It will display docstring in a separate buffer, if you need more details of what the function and each parameter does. By default, if point is on a symbol, it will prompt the symbol as default item to be displayed, but you can type in other symbol.

- Using `elisp-slime-nav--read-symbol-at-point` from the package [elisp-slime-nav](https://github.com/purcell/elisp-slime-nav) to jump to symbol definition if you want to see how it is implemented.

- Using info: Helm provides these commands for Emacs Lisp: 

  - `helm-info-at-point`: Display the info at point for a symbol using Emacs Lisp manual, if an info entry is available.
  - `helm-info-elisp`: Display Emacs Lisp index using Helm. You can interactively search for an entry with this command. Much better than static index.

Helm displays many other info commands for other utilities as well (i.e. helm-info-make, helm-info-ld, helm-info-gdb`...).

**Comment by tuhdo** [comment]
Helm also provides `helm-locate-library` command that allows you to jump to any loaded file into Emacs.

**Comment by tuhdo** [comment]
@thierryvolpiatto What's the proper way to use [Everything](http://www.voidtools.com/) with `helm-locate`? Maybe the docstring of `helm-locate` should be updated with instructions to setup Everything for `helm-locate`.

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> @thierryvolpiatto What's the proper way to use Everything with
> helm-locate?

Well IIRC there is nothing to do on helm side once the "es" executable
is in your PATH.

Just tried now on Virtualbox and a minimal helm config and it works out
of the box.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment]
Nice! I will try it tomorrow.

@ReneFroger you don't need to do anything except making Emacs see Everything executable. Helm will automatically use it.

**Comment by ReneFroger** [comment]
Thnx Tuhdo for asking that. 
I added some filters (like .dropbox.cache) and some folders to ignore (like Windows and Recycle Bin) in Everything, and it works directly. My Locate is now filled with only relevant results. 

No difficult configuration and difficult paths to tie at each other. It works automagically. 

I'm impressed. :smiley:  If I could give some donation for the development of Helm, @thierryvolpiatto, let me know!

**Comment by thierryvolpiatto** [comment]
ReneFroger <notifications@github.com> writes:

> If I could give some donation for the development of Helm,
> @thierryvolpiatto, let me know!

Donations are always welcome ;-), you will find a link on top page of
Readme.

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by ReneFroger** [comment]
With pleasure! I can really recommend bitcoin for this type of donations, by the way.

**Comment by ReneFroger** [comment]
Create a random Bitcoin address, and paste it on the front of your Helm frontpage. Then you're done. :-)


-----Original Message-----

**Comment by ReneFroger** [comment]
Any update on getting the relevant results on bottom, instead on top?

**Comment by thierryvolpiatto** [comment]
Nothing is planned for this see #387

**Comment by ReneFroger** [comment]
I don't think you get the idea, when I read the issue you linked. I mean, I like the idea of auto-resizing, because it enables me to see more of the buffer. I appreciate it that you found a way to implement that. :smiley: 

But it makes me hard to stay in focus, because the top with the relevant section is moving all the way around when autoresizing. This makes the autoreszing not useful. On contraction, it makes it even harder to use Helm. :cry:

Well, as I showed in the movie, this could be solved when the relevant section is on the bottom, close to the input. Then you don't need to try hard to have any focus on the moving bar when filtering the results, and get a view of your buffer above.

**Comment by ReneFroger** [comment]
I don't think you get the idea, when I read the issue you linked. I mean, I like the idea of auto-resizing, because it enables me to see more of the buffer. I appreciate it that you found a way to implement that. :smiley: 

But it makes me hard to stay in focus, because the top with the relevant section is moving all the way around when autoresizing. This makes the autoreszing not useful. On contrary, the autoresizing fature makes it even harder to use Helm. :cry:

Well, [as I showed in the movie](https://www.youtube.com/watch?v=fwqhBSxhGU0), this could be solved when the relevant section is on the bottom, close to the input. Then you don't need to try hard to have any focus on the moving bar when filtering the results, and get a view of your buffer above.

**Comment by thierryvolpiatto** [comment]
ReneFroger <notifications@github.com> writes:

> I don't think you get the idea, when I read the issue you linked. I
> mean, I like the idea of auto-resizing, because it enables me to see
> more of the buffer. I appreciate it that you found a way to implement
> that. :sm
>
> But it makes me hard to stay in focus, because the top with the
> relevant section is moving all the way around when autoresizing. This
> makes the autoreszing not useful. On contrary, the autoresizing fature
> makes it even harder to use Helm. :cr
>
> Well, as I showed in the movie, this could be solved when the relevant
> section is on the bottom, close to the input. Then you don't need to
> try hard to have any focus on the moving bar when filtering the
> results, and get a view of your buffer above.

I understand your point, but it is not possible to do because what you
see in helm-buffer is the output of a process that comes in many small
chunk of test that are linked all together at each time helm update.
If at each time you revert the list of candidates then the next wave of
text will be linked to this reversed text and so on, and of course the
result would be wrong. (Sorry for my english, it is quite hard to
explain, perhaps look at the emacs manual about process filters,
processes etc.. for a better explanation).

Maybe what you could do to not see the top of buffer moving when
autoresizing is configure helm to have the helm-window above your
current-buffer (See `helm-split-window-default-side').
You can quickly change where helm-window is by hitting repetitively C-t
while in helm.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by PythonNut** [comment]
@ReneFroger I believe your issue (regarding putting most relevant options at the bottom) is a duplicate of #362. See it's resolution.

**Comment by michael-heerdegen** [comment]
Just for the record, because the question had been raised: it is possible to limit the number of results of the locate source:
```

(setq helm-source-locate
      (helm-make-source "Locate" 'helm-locate-source
        :pattern-transformer 'helm-locate-pattern-transformer
        :candidate-number-limit 15))
```

**Comment by PythonNut** [comment]
@michael-heerdegen Also, you can limit the number of candidates that `locate` produces to begin with:
```emacs
(setq helm-locate-command "locate %s -r %s -be -l 15")
```

**Comment by thierryvolpiatto** [comment]
PythonNut <notifications@github.com> writes:

> @michael-heerdegen Also, you can limit the number of candidates that locate produces to begin with:
>
> (setq helm-locate-command "locate %s -r %s -be -l 15")

Note that you can add the "-n 15" if needed after entering your pattern.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by ReneFroger** [comment]
I just noticed that my reply was in the wrong issue. The limit of locale is not the issue, but thanks for replying. 

I thought I was replying in the issue https://github.com/emacs-helm/helm/issues/791  after learning that the wrong location of relevant lines makes hard to stay in focus. 

I was really surprised when reading that this should be not possible in Elisp, while the 'bad' Vim Script is able to do this.

**Comment by tuhdo** [comment]
It is possible and was made, see [grizzl](https://github.com/d11wtq/grizzl) (now abandoned, probably the author is using something else rather than Emacs). Helm is fast because it uses output directly from the external process, immediately without being blocked and wait for the whole process to finish. What you want is doable but it takes more time to rearrange the output from external command. Does Unite display more than the visible buffer? Can it display more than hundreds or thousands of candidates from shell command and allow you to scroll? So, what if a grep search return 2000 results, what can you do with Unite? Did you try Unite on a large set of candidates, i.e. 10000 or 20000?

That's said, I still think it's a nice feature in combination with helm-autoresize-mode and I would want to see it, but not so soon. Doing this sort in reverse also makes Helm slower because of additional processing.

**Comment by tuhdo** [comment]
If Helm does it that way, the async commands you use (grep, locate...) will all become synchrnous and block Emacs waiting for it to finish. That's the price. But, if you set your displaying numbers of candidates small (i.e. 10 or 15), it should not be a problem. Otherwise helm-locate will be unusable because you will always have to wait a brief while to retrieve candidates.

**Comment by ReneFroger** [comment]
https://github.com/emacs-helm/helm/issues/791#issuecomment-69802551

**Comment by ReneFroger** [comment]
Sometimes es.exe (from Everything) is not fast enough responding, which causes Emacs/helm to be frozen and crashed. It is happening too often the last time. 
But for Vim Unite, I need es.exe which runs fine. The Vim directory with the es.exe is in my path. 

Is there a way to exclude Everything/Es.exe for use in Helm Locate? 

Thanks in advance (I will try your comment on the another issue, when I'm home, by the way. Thanks for that).

**Comment by tuhdo** [comment]
@ReneFroger I guess you use `locate/es` to search for file in a project. If so, I suggest you give [Projectile](https://github.com/bbatsov/projectile) with its package Helm Projectile a try. Using Helm and Helm Projectile, I rarely use `find` or `locate`, unless I want to find file in root directory or random location.

**Comment by ReneFroger** [comment]
It seems you're still alive, @tuhdo . :)

Yes, I was planning to take a closer look at Helm Projectile. But first, I need to fix my issues with various things in Emacs, beginning with Helm. When all things in Emacs are running fine, I wanted to start with Helm Projectile. 

But thanks for your tip, it's appreciated.

**Comment by tuhdo** [comment]
@ReneFroger Yes, one way to fix your problem is using Helm Projectile, or [helm-ls-git](https://github.com/emacs-helm/helm-ls-git), also created by @thierryvolpiatto, but as its name suggests, it only supports Git.

**Comment by tuhdo** [comment]
And yes, I'm alive and active :) It's just [semantic-refactor](https://github.com/tuhdo/semantic-refactor) consumed most of my times the past days.

**Comment by yilihong** [comment]
(setq helm-candidate-number-limit 6)
