### ISSUE TITLE
Lastest 'master' branch can't be installed properly by 'el-get'

### ISSUE THREAD

**Issue by enzochiau** [emacs-helm/helm#796]
Use `el-get` to install `helm`. I got this error when I update it today:

    Debugger entered--Lisp error: (file-error "Cannot open load file" "no such file or directory" "helm-source")
      require(helm-source)
      byte-code("\300\301!\210\300\302!\207" [require cl-lib helm-source] 2)
      (helm-multi-key-defun helm-toggle-resplit-and-swap-windows "Multi key command to resplit and swap helm window.\nFirst call run `helm-toggle-resplit-window',\nsecond call within 0.5s run `helm-swap-windows'." (quote (helm-toggle-resplit-window helm-swap-windows)) 1)
      eval-buffer(#<buffer  *load*-449659> nil "/home/user1/.emacs.d/el-get/.loaddefs.el" nil t)  ; Reading at buffer position 43473
      load-with-code-conversion("/home/user1/.emacs.d/el-get/.loaddefs.el" "/home/user1/.emacs.d/el-get/.loaddefs.el" nil t)
      load("/home/user1/.emacs.d/el-get/.loaddefs" nil t)
      el-get-load-fast("/home/user1/.emacs.d/el-get/.loaddefs.el")

**Comment by enzochiau** [comment]
The lastest `emacs` break several things. I would reopen it if it is still there after `emacs` fix their issues first.

**Comment by tuhdo** [comment]
If it is the case, why don't you use MELPA?

**Comment by saqihel** [comment]
i have the same problems. hmm..

**Comment by thierryvolpiatto** [comment]
saqihel <notifications@github.com> writes:

> i have the same problems. hmm..

Please report such bugs to el-get, this is not related to helm, in same
conditions with any other package you will hit the same bug, the point is
to recompile your files outside of your current emacs, it is why we are
using async as dependency with MELPA, to compile our files async in a
clean emacs.
You can use also the make file provided in the git repo.
See our FAQ on helm wiki.

Actually I am maintaining installation of helm from MELPA and of course
from git with make, I don't support el-get and other alternatives, not
that it is a bad stuff (I never used it), 
just a question of choice as I have not the time
to handle everything.

Hope that help.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by saqihel** [comment]
@thierryvolpiatto thank you for your comment.
