### ISSUE TITLE
toggle-input-method is not working in helm-find-files

### ISSUE THREAD

**Issue by ineu** [emacs-helm/helm#797]
Hello.
Just noticed that `toggle-input-method` is not working in `helm-find-files`. You can type only latin characters, pressing `C-\` does nothing.
Meanwhile it does work in all `helm-mini`, `helm-ls-git-ls`, `helm-resume`.
Furthermore, `helm-find-files` doesn't inherit input method from current buffer, it always resets to english.
This basically means that I cannot visit directories or open files with non-latin names (cyrillic in my case) in any other way than with `dired`.
Reproduced in clean `emacs -q` with
```elisp
(add-to-list 'load-path "/home/ineu/.emacs.d/elpa/helm-20150102.2126")
(require 'helm-config)
```
EDIT: It's more tricky. Seems like it works, but in very weird way. Switching to russian input method and typing some arbitrary strings in `helm-find-files` inputs *mostly* latin characters, but sometimes few cyrillic characters appear, and then latin again.

**Comment by thierryvolpiatto** [comment]
Related to #785 .

**Comment by ineu** [comment]
Yes, in inheritance part. But this is just a tiny inconvenience. The real problem is with

> It's more tricky. Seems like it works, but in very weird way. Switching to russian input method and typing some arbitrary strings in helm-find-files inputs mostly latin characters, but sometimes few cyrillic characters appear, and then latin again.

**Comment by thierryvolpiatto** [comment]
This is really tricky to fix.
Actually with current-input-method set in helm-buffer to the
current-buffer's value, it works in some places but not others places.

With this code, we can set current-input-method in helm-buffer:

(add-hook 'helm-before-initialize-hook (lambda ()
                                         (helm-set-local-variable
                                          'current-input-method
                                          current-input-method)))

Now in a simple source like this:

(helm :sources (helm-build-sync-source "test"
                 :candidates '("а" "аб" "абц" "абцд" "аѕертз"))
      :buffer "*helm test*")

We can input "cyrillic-ukrainian" chars in minibuffer to match some
candidates; It is working.

However it doesn't work (or partially) with others sources.
I still don't understand why for the moment and don't know yet how to
debug this.
Help welcome on this.
 
-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Ok the problem comes from the updating of keymap, it seems it overhide self-insert-command.

So from *scratch* buffer, following code allow entering local chars in minibuffer:

```elisp
(helm :sources (helm-build-sync-source "test"
                 :candidates (lambda () (directory-files default-directory t))
                 ;:keymap (current-local-map)
                 )
      :buffer "*helm test*")
```

But as soon `:keymap` is commented out characters from `default-input-method` are used.

**Comment by michael-heerdegen** [comment]
I guess this is due to how helm--maybe-update-keymap is implemented (using set-transient-map, set-temporary-overlay-map).

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> Yes it comes from helm--maybe-update-keymap, but I still don't
> understand why set-transient-map doesn't update the keymap according
> to the value of input-method in helm-buffer.

set-transient-map works by setting overriding-terminal-local-map
(temporarily).

Obviously, setting overriding-terminal-local-map confuses input
methods.  Try e.g.

```
(let ((map (make-sparse-keymap)))
  (define-key map [f12] #'make-frame)
  (setq overriding-terminal-local-map map))
```

in scratch in emacs -Q and try to use an input method.  It wont work.
This doesn't seem to be documented anywhere.

**Comment by michael-heerdegen** [comment]
Michael Heerdegen <michael_heerdegen@web.de> writes:

> This doesn't seem to be documented anywhere.

Though, I guess set-transient-map was never intended to be used like we
do.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Michael Heerdegen <michael_heerdegen@web.de> writes:
>
>> This doesn't seem to be documented anywhere.

It is documented, see documenation of input-method-function.
When overriding-terminal-local-map or overriding-local-map are non--nil,
the input-method-function just return its argument with no translation.

> Though, I guess set-transient-map was never intended to be used like we
> do.

Probably, but it serve us well until now, and our task in helm is not
easy, we have to redefine the keymap each time we change source.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Now with the helm-minor-mode branch, it should work.

What should work ?

1) Enable a new input-method in a buffer.
2) Run any helm command starting from this buffer.
3) Start writing in minibuffer.
    You should have the expected character (cyrillic or whatever)
4) In helm commands that have multiples sources, you should have the 
    right keymap corresponding to the current source.

**Comment by tuhdo** [comment]
@Fuco1 You should try `helm-minor-mode` to see if solves your issue with input method.

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> @Fuco1 You should try helm-minor-mode to see if solves your issue with input method.

NO!!! helm-minor-mode should not be used by user, it is internal, IOW
for input method working user have just NOTHING to do, just run helm as
usual after toggling input method in current-buffer.

BTW I have renamed it to helm--minor-mode and make it unusable
interactively, docstring is updated too.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment]
Ah so in other words input method won't be malfunctioned in the minibuffer anymore without doing anything? Nice.

**Comment by ineu** [comment]
Tried in helm-find-files, works great: inherits keymap from the current buffer and allows to switch keymap.
Is it possible to display current keymap in the helm buffer's modeline just like it is displayed in ordinary buffers?

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> Ah so in other words input method won't be malfunctioned in the
> minibuffer anymore without doing anything?

Yes.


-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Eugene Diachkin <notifications@github.com> writes:

> Tried in helm-find-files, works great: inherits keymap from the
> current buffer and allows to switch keymap.

Great, merged to master.

> Is it possible to display current keymap in the helm buffer's modeline
> just like it is displayed in ordinary buffers?

You can see the current keymap bindings with `C-c ?`.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by ineu** [comment]
Great, thank you!
