### ISSUE TITLE
helm-locate mdfind doesnot support helm-locate-fuzzy-match

### ISSUE THREAD

**Issue by jixiuf** [emacs-helm/helm#799]
on mac 
```
(setq-default helm-locate-command (case system-type
                                    ('gnu/linux (expand-file-name "~/.emacs.d/bin/everything.sh %s %s"))
                                    ;; "locate  %s -e -A %s"
                                    ('berkeley-unix "locate %s %s")
                                    ('windows-nt "es %s %s")
                                    ('darwin "mdfind -name %s %s")
                                    (t "locate %s %s"))
              )
(setq helm-locate-fuzzy-match t)

```
if I set  helm-locate-fuzzy-match t
there is no result of helm-locate
so helm-locate doesnot support  helm-locate-fuzzy-match if I use mdfind?

**Comment by thierryvolpiatto** [comment]
jixiuf <notifications@github.com> writes:

> on mac
>
> (setq-default helm-locate-command (case system-type
>                                     ('gnu/linux (expand-file-name
>                                     "~/.emacs.d/bin/everything.sh %s
>                                     %s"))
On GNU/Linux, no script is needed if you use a recent version of locate,
you can use these settings: "locate %s -e -A --regex %s"
 
>                                     ;; "locate  %s -e -A %s"
>                                     ('berkeley-unix "locate %s %s")
>                                     ('windows-nt "es %s %s")
>                                     ('darwin "mdfind -name %s %s")
>                                     (t "locate %s %s"))
>               )
> (setq helm-locate-fuzzy-match t)
>
> if I set helm-locate-fuzzy-match t
> there is no result of helm-locate
> so helm-locate doesnot support helm-locate-fuzzy-match if I use mdfind?

You need a locate version that support the "-b" option, I don't know mdfind.
 
-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
