### ISSUE TITLE
throw-on-input annoyances

### ISSUE THREAD

**Issue by michael-heerdegen** [emacs-helm/helm#812]
Hi,

here on Debian, changing the active desktop (workspace) confuses helm. It stops matching and raises an error.

Here is a recipe:

```
(helm :sources
      `((name . "Test")
        (candidates . ,(lambda () (let ((i 0))
                               (mapcar
                                (lambda (i)
                                  (dotimes (k 500000)
                                    (* k k))
                                  i)
                                (number-sequence 1 10)))))
        ))
```

Change the desktop while helm is collecting candidates, or click on a different app. You probably get an window-live-p error.

helm-dictionary is a real-live example that shows this symptom.

If you modify the helm code so that the error is avoided, helm is still stopping collecting candidates when I change the desktop.

The core of the problem is that binding throw-on-input lets Emacs throw even when you only change the desktop.  Try this:

```
(catch 'tag
  (let ((throw-on-input 'tag))
    (while t)))
```

and switch to another desktop. The loop stops immediatly.

Is there anything we can do to improve the behavior of helm in this case?

Do you think it is a bug in vanilla Emacs?

Thanks,

Michael.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Hi,
>
> here on Debian, changing the active desktop (workspace) confuses helm. It stops matching and raises an error.
>
> Here is a recipe:
>
> (helm :sources
>       `((name . "Test")
>         (candidates . ,(lambda () (let ((i 0))
>                                (mapcar
>                                 (lambda (i)
>                                   (dotimes (k 500000)
>                                     (* k k))
>                                   i)
>                                 (number-sequence 1 10)))))
>         ))
>
> Change the desktop while helm is collecting candidates, or click on a different app. You probably get an window-live-p error.
>
> helm-dictionary is a real-live example that shows this symptom.
>
> If you modify the helm code so that the error is avoided, helm is still stopping collecting candidates when I change the desktop.
>
> The core of the problem is that binding throw-on-input lets Emacs throw even when you only change the desktop. Try this:
>
> (catch 'tag
>   (let ((throw-on-input 'tag))
>     (while t)))
>
> and switch to another desktop. The loop stops immediatly.
>
> Is there anything we can do to improve the behavior of helm in this case?

I can for now avoid the error by using with-helm-buffer instead of
with-helm-window.
For helm stopping matching I don't know what to do for now, a solution
would be to reactivate updating when emacs retrieve focus ?
I will have a look at this.

> Do you think it is a bug in vanilla Emacs?

Maybe, but not really sure for now, need to investigate.

Thanks for the recipes and reporting this.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Hi,
>
> here on Debian, changing the active desktop (workspace) confuses helm. It stops matching and raises an error.
>
> Here is a recipe:
>
> (helm :sources
>       `((name . "Test")
>         (candidates . ,(lambda () (let ((i 0))
>                                (mapcar
>                                 (lambda (i)
>                                   (dotimes (k 500000)
>                                     (* k k))
>                                   i)
>                                 (number-sequence 1 10)))))
>         ))
>
> Change the desktop while helm is collecting candidates, or click on a different app. You probably get an window-live-p error.

1) Modify helm--maybe-update-keymap to use with-helm-buffer instead of
   with-helm-window (I will install this tomorrow morning).
2) Use these hooks fix the update problem:

(add-hook 'focus-in-hook (lambda ()
                           (when helm-alive-p
                             (with-helm-buffer (helm-force-update))
                             (helm-autoresize-mode 1))))
(add-hook 'focus-out-hook (lambda ()
                            (helm-autoresize-mode -1)))

Note: If you haven't enabled helm-autoresize-mode you can remove the
corresponding code.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> 1) Modify helm--maybe-update-keymap to use with-helm-buffer instead of
> with-helm-window (I will install this tomorrow morning).

Seems reasonable.

> 2) Use these hooks fix the update problem:
>
> (add-hook 'focus-in-hook (lambda ()
> (when helm-alive-p
> (with-helm-buffer (helm-force-update))
> (helm-autoresize-mode 1))))
> (add-hook 'focus-out-hook (lambda ()
> (helm-autoresize-mode -1)))

(I guess we don't need to add to the global binding?)

This doesn't seem to work reliable here.  When I set debug-on-error t, I
still see a debugger pop up most of the time when switching workspaces.

I think the reason is that when focus-in-hook is run, `helm-window'
still gives nil (note the second arg we give to `get-buffer-window').

Thinking more about it, I think what Emacs does is wrong, and switching
workspaces should not make throw-on-input "fire".  I don't see a good
reason for such a behavior.  I'll probably make a bug report tomorrow.

**Comment by michael-heerdegen** [comment]
Michael Heerdegen <michael_heerdegen@web.de> writes:

> I think the reason is that when focus-in-hook is run, `helm-window'
> still gives nil (note the second arg we give to `get-buffer-window').

Mmh, maybe, as an alternative approach, consider to change
`with-helm-window' so that it also DTRT when "the helm window" is not
visible in the sense of get-buffer-window.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Thinking more about it, I think what Emacs does is wrong, and switching
> workspaces should not make throw-on-input "fire". I don't see a good
> reason for such a behavior. I'll probably make a bug report tomorrow.

It is definitely an emacs bug, because when I disable the touchpad on my
laptop, everything is working as expected, even with with-helm-window.
And helm is continuing updating as expected.

I have noticed a problem long time ago about loosing focus when I quit
emacs, have been reported the bug to emacs, but always ignored, I think
it is linked.

When I quit emacs the keyboard become irresponsive until I click in the
middle of the desktop.
As I often disable the touchpad I run always a hook reenabling the
touchpad when emacs is killed to be sure to be able to use my keyboard 
(otherwise I must restart my laptop brutally with the power button as I
have no more control).
Emacs is the only app doing this.
BTW I use Lucid, but IIRC it was the same with an emacs build with Gtk.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Michael Heerdegen <michael_heerdegen@web.de> writes:
>
>> I think the reason is that when focus-in-hook is run, `helm-window'
>> still gives nil (note the second arg we give to `get-buffer-window').
>
> Mmh, maybe, as an alternative approach, consider to change
> `with-helm-window' so that it also DTRT when "the helm window" is not
> visible in the sense of get-buffer-window.

I won't do this, the helm-window IS visible in such cases, up to
get-buffer-window to detect this.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> I won't do this, the helm-window IS visible in such cases, up to
> get-buffer-window to detect this.

No, not when you switch to a different workspace (which is the thing I
was talking about) and use visible as second arg to get-buffer-window.

Try

```
(run-with-timer
 1 1
 (lambda (b) (message "%s" (get-buffer-window b 'visible)))
 (current-buffer))
```

switch to a different desktop, get back and check *Messages*.

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> When I quit emacs the keyboard become irresponsive until I click in
> the middle of the desktop.  As I often disable the touchpad I run
> always a hook reenabling the touchpad when emacs is killed to be sure
> to be able to use my keyboard (otherwise I must restart my laptop
> brutally with the power button as I have no more control).  Emacs is
> the only app doing this.  BTW I use Lucid, but IIRC it was the same
> with an emacs build with Gtk.

I don't think this is related (btw have you tried with a different
window manager?).  Anyway, I never faced this problem.

For the problem we discuss here, I think kbd_buffer_store_event_hold in
keyboard.c would have to be changed to exclude more event types from
counting as input (look at the end of the defun).

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Thierry Volpiatto <notifications@github.com> writes:
>
>> I won't do this, the helm-window IS visible in such cases, up to
>> get-buffer-window to detect this.
>
> No, not when you switch to a different workspace (which is the thing I
> was talking about) and use visible as second arg to get-buffer-window.

You say that (get-buffer-window b 'visible) is not returning "true" when
you change workspace, while I am saying the "buffer is visible", this is
two different things.

IOW when the buffer is "visible" get-buffer-window should return what is
expected.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
I have opened bug#19547: 25.0.50; throw-on-input "fires" when switching workspace.

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> You say that (get-buffer-window b 'visible) is not returning "true"
> when you change workspace, while I am saying the "buffer is visible",
> this is two different things.
>
> IOW when the buffer is "visible" get-buffer-window should return what
> is expected.

Dunno what you "expect", but I guess we both understand how it works.
Your fix using with-helm-buffer instead of with-helm-window will work,
of cause.

But we should be sure that all other occurrences of with-helm-window are
not problematic wrt switching desktops.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Dunno what you "expect", but I guess we both understand how it works.

I expect that when buffer is visible on the display by human,
get-buffer-window returns this buffer when called, which is not the case
apparently when switching back from another desktop.

> But we should be sure that all other occurrences of with-helm-window are
> not problematic wrt switching desktops.

Some other occurences may cause problems, but well this use case is
really rare and trying some workaround will lead to other bug with
windows in helm (would like to avoid extra work in helm).

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> > But we should be sure that all other occurrences of with-helm-window
> > are not problematic wrt switching desktops.

Often, there is preliminary stuff done before displaying happens.

In case of focus-in-hook, the hook is probably run before redisplay
happens.

Similar things happen when creating frames.  After creating a frame, the
frame and its windows are first not visible after leaving make-frame,
although already existing as Lisp objects.  We have to live with the
fact that displaying/deiconifying frames and windows happen delayed in
comparison with the Lisp code we are running.

**Comment by michael-heerdegen** [comment]
Michael Heerdegen <michael_heerdegen@web.de> writes:

> In case of focus-in-hook, the hook is probably run before redisplay
> happens.

I think, instead of toggling autoresize in focus-in/focus-out hooks,
helm--autoresize-hook should find out itself if the window to be resized
is "visible".  That currently cannot be expressed by using
with-helm-window or so, but is IMHO more reasonable than your
suggestion.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Michael Heerdegen <michael_heerdegen@web.de> writes:
>
>> In case of focus-in-hook, the hook is probably run before redisplay
>> happens.
>
> I think, instead of toggling autoresize in focus-in/focus-out hooks,
> helm--autoresize-hook should find out itself if the window to be resized
> is "visible". That currently cannot be expressed by using
> with-helm-window or so, but is IMHO more reasonable than your
> suggestion.

Using focus*hooks was just to demonstrate the problem was coming from
emacs focus, but certainly not a definitive suggestion.

Like toggling touchpad, i.e your problem disapear when disabling
touchpad, but is is certainly not a solution (most people are using
their mouse/touchpad while in emacs).

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> Like toggling touchpad, i.e your problem disapear when disabling
> touchpad, but is is certainly not a solution (most people are using
> their mouse/touchpad while in emacs).

Are you REALLY sure that disabling the touchpad does solve the issue for
you?  That doesn't make sense to me, I see no connection between the
generation of the events that let throw-on-input fire (focus-out,
iconify-frame) and enabling or disabling a touchpad.

Anyway, I tried myself to disable the touchpad here.  I edited

/usr/share/X11/xorg.conf.d/50-synaptics.conf

and commented out every configuration line.  That disabled the touchpad
after restarting, but the behavior I see in Emacs and Helm was exactly
the same.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> and commented out every configuration line. That disabled the touchpad
> after restarting, but the behavior I see in Emacs and Helm was exactly
> the same.

Indeed after retrying it didn't work, then sometimes it works sometime
no.

BTW, to disable your touchpad, use this script, (bind it to a key in
your window manager)

https://github.com/thierryvolpiatto/shell_scripts/blob/master/toggletouchpad.sh

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
Thanks, I'll test that commit.

BTW, you should correct the rewritten with-helm-window and make the variable FRAME an uninterned symbol.
There are other macros in that file that suffer from the same problem. Not all, though.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Thanks, I'll test that commit.
>
> BTW, you should correct the rewritten with-helm-window and make the
> variable FRAME an uninterned symbol.  There are other macros in that
> file that suffer from the same problem. Not all, though.

Can you clarify ?
Even better you can send a PR.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
```
(info "(elisp) Surprising Local Vars")
```

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> (info "(elisp) Surprising Local Vars")

Indeed, I remember this now, thanks.

As I said PR are welcome.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
Would you want something handy as with-gensyms in Common Lisp?  Personally I use something like
```
(defmacro with-gensyms (symbols &rest body) 
  "Bind symbols in list SYMBOLS to fresh gensyms and eval BODY."
  (declare (indent 1))
  (cl-check-type symbols list)
  (let ((gensyms (mapcar
		  (lambda (symbol) (cl-gensym (concat (symbol-name symbol) "_")))
		  symbols)))
    `(let (,@(cl-mapcar (lambda (x y) `(,x ',y)) symbols gensyms))
       ,@body)))
```

That could also help you remebering to DTRT.

**Comment by michael-heerdegen** [comment]
But note that some people prefer using "symbols with strange names" instead of gensyms which easens debugging. I guess that's the reason why Emacs doesn't have with-gensyms at all. In the Elisp sources, unintererned symbols are are avoided where justifiable.

**Comment by PythonNut** [comment]
My helm has started locking my cursor whenever I'm in a helm session. Does this have anything to do with it? It's actually a bit paralyzing.

**Comment by thierryvolpiatto** [comment]
PythonNut <notifications@github.com> writes:

> My helm has started locking my cursor whenever I'm in a helm
> session. Does this have anything to do with it? It's actually a bit
> paralyzing.

Be sure you have reinstalled helm properly.
Please be clear on what is happening, I don't know what mean "locking my
cursor".

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by PythonNut** [comment]
* Fedora 19
* Emacs 24.4 GTK+
* Most recent helm

Starting a helm session moves the cursor to the top right corner of helm's window and locks it there (if I move it away, it instantly teleports back). If I switch focus, it's instantly stolen my emacs. This loop continues until helm is closed.

**Comment by thierryvolpiatto** [comment]
PythonNut <notifications@github.com> writes:

>   * Fedora 19
>   * Emacs 24.4 GTK+
>   * Most recent helm
>
> Starting a helm session moves the cursor to the top right corner of
> helm's window and locks it there (if I move it away, it instantly
> teleports back). If I switch focus, it's instantly stolen my
> emacs. This loop continues until helm is closed.

Ok, I can't reproduce, but I have disabled last changes in
with-helm-window for now, should work now, please confirm.

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by PythonNut** [comment]
@thierryvolpiatto Oddly enough, I think that did fix the issue for me. Strange...

**Comment by michael-heerdegen** [comment]
> As I said PR are welcome.

See https://github.com/emacs-helm/helm/pull/820.

**Comment by thierryvolpiatto** [comment]
@michael-heerdegen Can we close this ?  I think all what can be done on helm side have been done, and the patch you sended on emacs-bug will make its way to trunk (ping them maybe).

**Comment by michael-heerdegen** [comment]
Yes, I think we can close this.  Thanks for your fixes!
