### ISSUE TITLE
Make buffer listing use the same faces as helm-find-files

### ISSUE THREAD

**Issue by tuhdo** [emacs-helm/helm#817]
The reason: currently faces are hard coded to be compatible with default Emacs. Once it is changed by customizing, the help string for buffer faces becomes invalid. Hard code faces make it more difficult for users to change theme, unless the theme supports Helm.

We can still keep the Helm faces of buffer listing as is, except making it use the default from helm-find-files, which follows the current theme's faces. For example, we should use the same directory face of the current theme to for directory buffer in buffer listing. Doing this, we can remove help section about color meaning for each buffer type.

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> The reason: currently faces are hard coded to be compatible with
> default Emacs. Once it is changed by customizing, the help string for
> buffer faces becomes invalid.  Hard code faces make it more difficult
> for users to change theme, unless the theme supports Helm.
>
> We can still keep the Helm faces of buffer listing as is, except
> making it use the default from helm-find-files, which follows the
> current theme's faces. For example, we should use the same directory
> face of the current theme to for directory buffer in buffer
> listing. Doing this, we can remove help section about color meaning
> for each buffer type.

helm-find-files doesn't have all the faces that buffers listing use.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment]
Yes, but we should reuse as many as we can for consistency and theme compatibility. At least we can reuse file and directory faces. Maybe we can give non-file buffers (i.e. *Message*) its own face and just leave normal buffers no face.

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> Yes, but we should reuse as many as we can for consistency and theme
> compatibility. At least we can reuse file and directory faces.

Ok for these two, but we must keep the others..

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment]
@thierryvolpiatto `helm-buffer-directory` should also be set to `helm-ff-directory`. It will be easier to detect that a buffer is a directory because it is consistent with the rest of Helm commands related to files (i.e. helm-find-files, helm-locate, helm-find....).

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> @thierryvolpiatto helm-buffer-directory should also be set to
> helm-ff-directory. It will be easier to detect that a buffer is a
> directory because it is consistent with the rest of Helm commands
> related to files (i.e. helm-find-files, helm-locate, helm-find....).

The two definitions are exactly the same, what's the problem ?

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment]
@thierryvolpiatto But once we change themes, those two faces will be synced again. It's better for `helm-buffer-directory` to inherit from `helm-ff-directory` since `helm-locate` and `helm-file` also reuse helm-ff faces. It makes Helm adapt to colour theme easier. Let make it the default until someone wants to treat directories in buffer differently than directories in other places, then he can change it.

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> @thierryvolpiatto But once we change themes, those two faces will be
> synced again. It's better for helm-buffer-directory to inherit from
> helm-ff-directory since helm-locate and helm-file also reuse helm-ff
> faces. It makes Helm adapt to colour theme easier. Let make it the
> default until someone wants to treat directories in buffer differently
> than directories in other places, then he can change it.

This will complicate things, as helm-ff-directory live in helm-files and
if I require helm-files, we will end up in require infloop, this just
for a face, so let people setting this themself.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
