### ISSUE TITLE
Helm mysteriously using TRAMP connections when jumping to file in dired

### ISSUE THREAD

**Issue by dakrone** [emacs-helm/helm#818]
When I use the `j` key in a dired buffer (bound to `dired-goto-file`) helm pops open a buffer so I can perform completion on the filenames in dired. Upon pressing ENTER on a file to move the point to it (this is all in a local directory), helm then tries to contact all of my latest TRAMP servers (?!) before actually moving the point to the file.

I see this is `*Messages*`:

```
Tramp: Opening connection for writequit using scp...
Tramp: Sending command `exec ssh    -e none writequit'
Tramp: Waiting for prompts from remote shell...done
Tramp: Found remote shell prompt on `writequit'
Tramp: Opening connection for writequit using scp...done
Tramp: Opening connection for hinmanm@delta-local using ssh...
Tramp: Sending command `exec ssh -l hinmanm   -e none delta-local'
Tramp: Waiting for prompts from remote shell...done
Tramp: Found remote shell prompt on `delta-local'
Tramp: Opening connection for hinmanm@delta-local using ssh...done
```

How can I tell helm this buffer has absolutely nothing to do with TRAMP and that it just needs to jump the point to the file I've selected?

**Comment by thierryvolpiatto** [comment]
Lee Hinman <notifications@github.com> writes:

> When I use the j key in a dired buffer (bound to dired-goto-file) helm
> pops open a buffer so I can perform completion on the filenames in
> dired. Upon pressing ENTER on a file to move the point to it (this is
> all in a local directory), helm then tries to contact all of my latest
> TRAMP servers (?!) before actually moving the point to the file.

Sorry but I can't reproduce this.
Can you try starting from ./emacs-helm.sh.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by dakrone** [comment]
So this is interesting, after a lot of testing, I narrowed it down to one thing:

```elisp
(setq ido-enable-tramp-completion nil)
```

Even setting it to `nil` makes the tramp connections happen... :-/ I've removed the setting entirely and there are no connections now made. Crazy.

Closing this as it doesn't seem helm-related, thanks :)

**Comment by thierryvolpiatto** [comment]
Lee Hinman <notifications@github.com> writes:

> So this is interesting, after a lot of testing, I narrowed it down to one thing:
>
> (setq ido-enable-tramp-completion nil)
>
> Even setting it to nil makes the tramp connections happen... :-/ I've removed the setting entirely and there are no connections now made. Crazy.
>
> Closing this as it doesn't seem helm-related, thanks :)

BTW you can get rid completely of dired by using helm-find-files.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by dakrone** [comment]
> BTW you can get rid completely of dired by using helm-find-files.

I do way more things with dired than `helm-find-files` currently supports, unfortunately, like copying files from one directory to another (via TRAMP or otherwise), previewing, renaming, marking/deleting, opening with external program, etc.

Thanks for helm, by the way, it is much appreciated!

**Comment by thierryvolpiatto** [comment]
Lee Hinman <notifications@github.com> writes:

>     BTW you can get rid completely of dired by using helm-find-files.
>    
> I do way more things with dired than helm-find-files currently
> supports, unfortunately, like copying files from one directory to
> another (via TRAMP or otherwise), previewing, renaming,
> marking/deleting, opening with external program, etc.

helm-find-files does all this in a much better way than dired.
I think what you are using is find-file (original C-x C-f) 
helmized by helm-mode, just try M-x helm-find-files and appreciate!
If you like it you can rebind C-x C-f to helm-find-files and never have
again tons of dired buffers around...

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by dakrone** [comment]
I'll have to play around with it more, thanks! (not that I mind dired buffers, really :) )

**Comment by thierryvolpiatto** [comment]
Lee Hinman <notifications@github.com> writes:

> I'll have to play around with it more, thanks!

Once you get used to it, I am sure you will leave dired behind you and
don't come back to it, or rarely.
BTW many thanks for your support to helm ;-)


-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment]
It depends, really. I use Helm-find-files daily, but I still use Dired for the following reason: it can be used as an anchor, so you can go back to a Dired buffer and invoke commands that depend on defaut-directory. For example, compile command, gdb, cache file listing over Tramp.
