### ISSUE TITLE
helm-ff autoupdate inconsistency

### ISSUE THREAD

**Issue by michael-heerdegen** [emacs-helm/helm#819]
Hello,

I stumbled upon this inconsistent behavior.  In helm.sh, eval

```
(setq helm-ff-auto-update-initial-value t)
```

and then

```
(helm-read-file-name "File: ")
```

You'll see that auto-update is off. Now hit C-x C-f C-q. Then eval

```
(helm-read-file-name "File: ")
```

again. Now, auto-update is ON. I would expect that either helm-ff-auto-update-initial-value is respected from the beginning on or ignored by helm-read-file-name.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> You'll see that auto-update is off. Now hit C-x C-f C-q. Then eval

What is C-q doing ?


-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> > You'll see that auto-update is off. Now hit C-x C-f C-q. Then eval
>
> What is C-q doing ?

Oops, typo, it should have been C-g, not C-q.

**Comment by michael-heerdegen** [comment]
I found out that the value of helm-ff--auto-update-state makes the difference.

auto update when calling  helm-read-file-name (not via helm-find-files) is currently controlled by the value of helm-ff--auto-update-state, whereby helm-ff-auto-update-initial-value has no influence.

Calling helm-find-files the first time sets helm-ff--auto-update-state as side effect, and this leads to a change in behavior of direct helm-read-file-name calls.

**Comment by michael-heerdegen** [comment]
This is a real-life problem btw., but not the end of the world of course. Try  e.g.
```
(setq helm-ff-auto-update-initial-value t)
```
C-x d  ==> auto update off

C-x C-f C-g

C-x d  ==> auto update on now

**Comment by michael-heerdegen** [comment]
If you consider this a minor problem and think there are more important things to work on, feel free to close, I won't mind (this time :P).

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> If you consider this a minor problem and think there are more
> important things to work on, feel free to close, I won't mind (this
> time :P).

No, it's ok, leave it open, I will look into this, it is just not an
urgent one.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Now we have:

`(setq helm-ff-auto-update-initial-value t)`

`C-x d` => autoupdate is on
`C-x-C-f` => auto update is on
`C-x d` => autoupdate is on

**Comment by michael-heerdegen** [comment]
Thanks, that did it.

When we did not have a quoted lambda at that place, we would have gotten a compiler warning.

With other words: if a lambda expression appears inside a quoted list, use a colon in front of it to unquote.  Quoting lambdas is not necessary anymore now we have lexical binding, AFAIK it has only disadvantages because quoted lambdas can't be compiled.

**Comment by michael-heerdegen** [comment]
What I said especially includes backquoted lambdas of course.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Thanks, that did it.
>
> When we did not have a quoted lambda at that place, we would have gotten a compiler warning.
>
> With other words: if a lambda expression appears inside a quoted list,
> use a colon in front of it to unquote. Quoting lambdas is not
> necessary anymore now we have lexical binding, AFAIK it has only
> disadvantages because quoted lambdas can't be compiled.

These are the vestiges of the switch to lexical-binding, which was a big
work.
I remove them slowly, but I remove them, thanks to remind me to do it in
more places.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Thanks, that did it.

Apart the refactoring of helm-mode (in particular) about lambda's, if
the problem is fixed, you can close this.

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
Yip, it behaves as expected now in all tests I did.  Thanks for fixing.
