### ISSUE TITLE
Helm buffer flashes a lot when helm-quick-update is set

### ISSUE THREAD

**Issue by PythonNut** [emacs-helm/helm#821]
I just recently discovered `helm-quick-update`. A _marvelous_ idea.

Unfortunately, for me it appears that the entire buffer is emptied and refilled on every keystroke, which makes the buffer appear to "blink" as I type. This reproduces in `emacs24.4 -Q`. I'm fairly certain that this is not what you intended. 

I can make a screencast, but It'll probably weigh in at about 30MB, and of course if you can reproduce it then it's not needed.

**Comment by tuhdo** [comment]
As I understood, when `helm-quick-update` is enabled, Helm only inserts enough candidates to visible area, so every time you type it will reinsert again. When `helm-quick-update` is disabled, every candidate is inserted into Helm buffer until it reaches `helm-candidate-number-limit`.

**Comment by thierryvolpiatto** [comment]
PythonNut <notifications@github.com> writes:

> I just recently discovered helm-quick-update. A marvelous idea.

It is not, it is deprecated and need to be rewrited or removed.
Since the time it have been introduced and now, helm have been modified
considerably and this have not exactly the same effect as initially.

> Unfortunately, for me it appears that the entire buffer is emptied and
> refilled on every keystroke, which makes the buffer appear to "blink"
> as I type. This reproduces in emacs24.4 -Q. I'm fairly certain that
> this is not what you intended.

Yes, it is a known issue (which is not indeed) that have been fixed, but
then reverted because it was buggy.

> I can make a screencast, but It'll probably weigh in at about 30MB,
> and of course if you can reproduce it then it's not needed.

It is not needed thanks.


-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> As I understood, when helm-quick-update is enabled, Helm only inserts
> enough candidates to visible area, so every time you type it will
> reinsert again. When helm-quick-update is disabled, every candidate is
> inserted into Helm buffer until it reaches
> helm-candidate-number-limit.

No, not exactly, when it is enabled computation of candidates of current
source is delayed, that's all.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
For more info on this see #380 which have been partially reverted because it was introducing bug in display and execution or certain type of actions.
