### ISSUE TITLE
Resume for helmified buffers?

### ISSUE THREAD

**Issue by ineu** [emacs-helm/helm#827]
`helm-resume` is very handy with helm buffers, but is not available with 'helmified' buffers: standard buffers, but with `helm-mode` enabled globally. For example, if I search for some package-related variable via `C-h v`, I'd like to have a quick way to resurrect search results to enter the next match. Is it somehow possible?
Persistent action in this case is not what I want because for `describe-variable` buffer it just displays quick explanation in the modeline instead of a window with full description and customize link.

**Comment by thierryvolpiatto** [comment]
Eugene Diachkin <notifications@github.com> writes:

> helm-resume is very handy with helm buffers, but is not available with
> 'helmified' buffers: standard buffers, but with helm-mode enabled
> globally. For example, if I search for some package-related variable
> via C-h v, I'd like to have a quick way to resurrect search results to
> enter the next match. Is it somehow possible?

No, it would work in many places but would fails in some cases so it is
disabled globally.

> Persistent action in this case is not what I want because for
> describe-variable buffer it just displays quick explanation in the
> modeline instead of a window with full description and customize link.

Use helm-apropos for all your C-h v/f tasks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by ineu** [comment]
Indeed, thank you.
