### ISSUE TITLE
Have helm-find-files not auto-resolve symlinks

### ISSUE THREAD

**Issue by dakrone** [emacs-helm/helm#829]
I have my `~/org` directory symlinked to `~/Dropbox/org`, so when I use `helm-find-files` I have the following:

![screen shot 2015-01-19 at 12 27 17 pm](https://cloud.githubusercontent.com/assets/19060/5799772/86cd91e0-9fd6-11e4-9436-17eb7d1fb077.png)

And then I hit `TAB`, but helm automatically expands it to `Dropbox/org`:

![screen shot 2015-01-19 at 12 27 24 pm](https://cloud.githubusercontent.com/assets/19060/5799779/9e40d62a-9fd6-11e4-8362-184c57d86f73.png)

Is there a way I can inhibit this behavior and have helm keep the directory as `~/org`? Resolving the symlink breaks my `org-publish` configuration since it is directory based and I have it set up to use `~/org` instead of `~/Dropbox/org`.

**Comment by thierryvolpiatto** [comment]
Lee Hinman <notifications@github.com> writes:

> I have my ~/org directory symlinked to ~/Dropbox/org,

Why ?

> so when I use helm-find-files I have the following:


> screen s
>
> And then I hit TAB, but helm automatically expands it to Dropbox/org:

Yes, this is the correct behavior.

> screen s
>
> Is there a way I can inhibit this behavior and have helm keep the
> directory as ~/org? Resolving the symlink breaks my org-publish
> configuration since it is directory based and I have it set up to use
> ~/org instead of ~/Dropbox/org.

Why this complication, why not using `org-directory' bound to your
"dropbox/org" directory ?
Then in your different configs of org or whatever you can always refer
to `org-directory' and you can get rid of your symlink.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by dakrone** [comment]
On Jan 19, 2015 1:24 PM, "Thierry Volpiatto" <notifications@github.com>
wrote:
>
>
> Lee Hinman <notifications@github.com> writes:
>
> > I have my ~/org directory symlinked to ~/Dropbox/org,
>
> Why ?

On some computers this directory is shared via dropbox, on others it is
*not* (and thus, not symlinked). Using ~/org means I can use the same
config everywhere.

> Why this complication, why not using `org-directory' bound to your
> "dropbox/org" directory ?
> Then in your different configs of org or whatever you can always refer
> to `org-directory' and you can get rid of your symlink.

I would prefer to keep using ~/org for non-symlinked computers (like I
described above)

**Comment by thierryvolpiatto** [comment]
Lee Hinman <notifications@github.com> writes:

> On some computers this directory is shared via dropbox, on others it is
> *not* (and thus, not symlinked). Using ~/org means I can use the same
> config everywhere.

Hmm, I see, in what the behavior of helm-find-files affect your
different org configs?

> I would prefer to keep using ~/org for non-symlinked computers (like I
> described above)

This is not possible, the actual behavior is the right thing to do.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by dakrone** [comment]
> Hmm, I see, in what the behavior of helm-find-files affect your different org configs?

Sorry, I didn't specify the config, I meant I can use the same org-publish and agenda configuration (which is always configured to use ~/org) across all the machines, whether the have ~/org symlinked or not. It's not a configuration from helm-find-files.

For example, using `ido-find-file` without helm, hitting `ENTER` on the ~/org directory just enters it, and I edit `~/org/foo.org` instead of `~/Dropbox/org/foo.org`.

> This is not possible, the actual behavior is the right thing to do.

Okay, I think instead I will make `~/org` a concrete directory and add a cron job to copy all the files to `~/Dropbox/org` periodically if this isn't possible to change.

**Comment by thierryvolpiatto** [comment]
Lee Hinman <notifications@github.com> writes:

>     Hmm, I see, in what the behavior of helm-find-files affect your different org configs?
>    
> Sorry, I didn't specify the config, I meant I can use the same
> org-publish and agenda configuration (which is always configured to
> use ~/org) across all the machines, whether the have ~/org symlinked
> or not. It's not a configuration from helm-find-files.
>
> For example, using ido-find-file without helm, hitting ENTER on the
> ~/org directory just enters it, and I edit ~/org/foo.org instead of
> ~/Dropbox/org/foo.org.

This still doesn't explain what is the problem here:

If ~/org/foo.org is a symlink of ~/Dropbox/org/foo.org, you are editing
the same file (i.e ~/org/foo.org and ~/Dropbox/org/foo.org are the same
file) right ?

If on another machine you edit ~/org/foo.org and this file is not a
symlink, no problem to edit it right ?

What am I missing ?

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by dakrone** [comment]
> If ~/org/foo.org is a symlink of ~/Dropbox/org/foo.org, you are editing the same file (i.e ~/org/foo.org and ~/Dropbox/org/foo.org are the same file) right ?

Yep, that's correct, the file's content is the same.

> If on another machine you edit ~/org/foo.org and this file is not a symlink, no problem to edit it right ?

No, no problem to edit it.

> What am I missing ?

The issue is if I edit a file that is `~/org/foo.org`, emacs sees the base-directory of the file as `~/org`. If I edit the same file at `~/Dropbox/org/foo.org`, emacs sees the base-directory as `~/Dropbox/org`, so with the following config:

```emacs-lisp
(setq org-publish-project-alist
  '(
("org-org"
  :base-directory "~/org/"
  :base-extension "org\\|html"
  :publishing-directory
  "/ssh:hinmanph@writequit:~/public_html/wq/paste/org/"
  :publishing-function org-html-publish-to-html
  :with-toc t
  :html-preamble t)))
```

(forgive the horrendous indentation, this is a subset of the full configuration)

Then, from within the org buffer, if I try to publish the file (using `C-c C-e`, then `P`, then `f`), only the file I've opened from `~/org/foo.org` works, the other file complains about not being associated to a project.

**Comment by thierryvolpiatto** [comment]
Lee Hinman <notifications@github.com> writes:

> The issue is if I edit a file that is ~/org/foo.org, emacs sees the
> base-directory of the file as ~/org. If I edit the same file at
> ~/Dropbox/org/foo.org, emacs sees the base-directory as ~/Dropbox/org,
> so with the following config:

Try instead something like this:

(setq org-publish-project-alist
      `(
        ("org-org"
         :base-directory ,(file-truename "~/org/")
         :base-extension "org\\|html"
         :publishing-directory
         "/ssh:hinmanph@writequit:~/public_html/wq/paste/org/"
         :publishing-function org-html-publish-to-html
         :with-toc t
         :html-preamble t)))

This should work on all your machines.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
BTW same for org-directory:

(setq org-directory (file-truename "~/org"))

Which will work on all your machines.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by dakrone** [comment]
@thierryvolpiatto great, that seems to work well, thanks!

Going to close this issue now.
