### ISSUE TITLE
[feature request] add Emacs bookmark into helm-mini

### ISSUE THREAD

**Issue by stardiviner** [emacs-helm/helm#830]
I wish to use helm-mini to quickly access buffers, recentf, and also bookmarks.
bookmarks is quite a efficient way to access buffer and positions.

**Comment by michael-heerdegen** [comment]
Why don't you just add helm-source-bookmarks to helm-mini-default-sources in your config?

**Comment by dakrone** [comment]
@michael-heerdegen hey neat, I didn't know you could do that, but it's quite helpful, so thanks!
