### ISSUE TITLE
[feature request] add helm support for Emacs apropos commands

### ISSUE THREAD

**Issue by stardiviner** [emacs-helm/helm#831]
How to let Helm support complete for apropos commands like `apropos-command`, `apropos-documentation` `apropos-value` etc ?

**Comment by michael-heerdegen** [comment]
helm-apropos covers the first one, no?

For the other two, I'm not sure if the performance of a helm version would be good enough.  AFAICT there are Icicles commands that do that, but they are quite slow.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> helm-apropos covers the first one, no?
>
> For the other two, I'm not sure if the performance of a helm version
> would be good enough. AFAICT there are Icicles commands that do that,
> but they are quite slow.

I have to say helm-apropos cover most of the need one can have and more,
apropos-* is slooow, give unrelated results, doesn't cover cl-* symbols
for documentation etc...

helm-apropos features:

- help for symbols (elisp and cl)
- documentation for symbols (elisp and cl)
- separate symbols in categories (class, method, functions, commands
  etc...)
- Allow setting variables quickly.
- show the symbol at point.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> apropos-* is slooow

IMHO the user interface of the vanilla apropos-* commands should be
improved.

Anyway, here's an example matching against all symbols' printed values
using all-completions and considering only atomic values:

```
(let ((example-pattern "^10$")
      (vals ()))
  (do-symbols (s)
    (when (and (boundp s) (atom (symbol-value s)))
      (push (propertize (prin1-to-string
                         (symbol-value s))
                        'symbol (symbol-name s)) vals)))
  (let ((completion-regexp-list (list example-pattern)))
    (mapcar
     (lambda (s) (cons (get-text-property 0 'symbol s)
                  (progn (remove-text-properties
                          0 (length s) '(symbol) s)
                         s)))
     (all-completions ""  vals))))
```

Needs ~1sec here. I don't think we can get much better. Mmh.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Thierry Volpiatto <notifications@github.com> writes:
>
>> apropos-* is slooow
>
> IMHO the user interface of the vanilla apropos-* commands should be
> improved.

Well probably, but this is not really our problem, we have helm-apropos
which is fast enough, improving vanilla emacs apropos-* commands is off
topic here.
BTW I never used apropos-* commands, except to find out they were
inefficient.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
