### ISSUE TITLE
Bad matches in upper sources outrank good matches in other sources

### ISSUE THREAD

**Issue by PythonNut** [emacs-helm/helm#837]
Right now, candidates that score very poorly let's take this example use case.

* I recently visited the file `arch/mips/include/asm/pmc-sierra/msp71xx/cpu-feature-overrides.h`
* I have `helm-for-files` with the default setup
* I have a file named `cards.h` in the current directory.

Typing `cards.h` result in this sorting:
1. ar<b>c</b>h/mips/include/<b>a</b>sm/pmc-sie<b>r</b>ra/msp71xx/cpu-feature-overri<b>d</b>e<b>s.h</b>
2. **cards.h**

Clearly the file `cards.h` is a better match. However, it's sorted below because it belongs to a source of a lower rank. In this case, long candidates in the highest ranked source will probably eat most patterns you throw at them. That one long candidate also matches:

* a<b>r</b>ch/mips/include/asm/pmc-si<b>e</b>rra/ms<b>p</b>71xx/cpu-f<b>eat</b>ure-overrides.h
* arch/mips/includ<b>e</b>/asm/p<b>m</b>c-sierr<b>a</b>/msp71xx/<b>c</b>pu-feature-override<b>s</b>.h
* ar<b>c</b>h/mips/inclu<b>d</b>e/<b>a</b>sm/pmc-sierr<b>a</b>/msp71xx/cpu-fe<b>a</b>ture-ove<b>r</b>rides.h

The point is, a few large candidates can easily match just about anything (poorly) leading to a lot of noise. All of these hypothetical matches would be sorted above extremely high-quality matches because they are grouped with a higher-priority source.

Some solutions include:
1. Sorting the sources by a function of the quality of their matches.
2. Not grouping candidates by source?
3. etc.

I'm not currently sure what the best solution is. We can discuss that here.

**Comment by tuhdo** [comment]
I think it only works for standard sources that use the flag `:fuzzy-match t`. Using `helm-projectile-find-file`, it returns exact matches, in your case, anything with `cards.h`

**Comment by PythonNut** [comment]
Well, this only applies to helm sessions with multiple sources. I _believe_ all the `helm-projectile` commands use a single source.

**Comment by tuhdo** [comment]
helm-projectile has a command with multiple sources of is own: helm-projectile.

All helm-projectile sources can be combined like other Helm sources fine. Only helm-source-projectile-buffers gives error if used outside of a project.

**Comment by thierryvolpiatto** [comment]
PythonNut <notifications@github.com> writes:

> Right now, candidates that score very poorly let's take this example use case.

Add -b at end of pattern or toggle basename (C-])

When you add the basename flag or toggle to basename, it have the same
effect as this:

(helm :sources (helm-build-in-buffer-source "test"
                 :data '("arch/mips/include/asm/pmc-sierra/msp71xx/cpu-feature-overrides.h"
                         "arch/mips/include/asm/pmc-sierra/msp71xx/cpu-feature-overrides.h"
                         "arch/mips/include/asm/pmc-sierra/msp71xx/cpu-feature-overrides.h"
                         "arch/mips/include/asm/pmc-sierra/msp71xx/card.h")
                 :fuzzy-match t
                 :match-part (lambda (c) (helm-basename c)))
      :buffer "*helm test*")


-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> I think it only works for standard sources that use the flag
> :fuzzy-match t. Using helm-projectile-find-file, it returns exact
> matches, in your case, anything with cards.h

Also note that even in source with fuzzy match enabled, as soon as you
add a space, helm stop fuzzy matching and start multi regexp matching.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by lewang** [comment]
@PythonNut brings up a great point, and I think it should be considered.  I think \#2 solution by @PythonNut is the most intuitive way forward.  I would want to shore up some issues I have with fuzzy API as it stands, before tackling this though. (PRs soon)

@thierryvolpiatto He's talking about scrambling all candidates across sources and then sorting them as one big collection.
