### ISSUE TITLE
helm crash Emacs

### ISSUE THREAD

**Issue by Pitometsu** [emacs-helm/helm#838]
with helm-mode t, just type:
M-x \\^
And that's it. Crash.

**Comment by tuhdo** [comment]
What is your OS? If it's Mac OS X, have a look at this issue: https://github.com/bbatsov/projectile/issues/600

**Comment by Pitometsu** [comment]
Yes,
```
> uname -a
Darwin Netsus-HackBook.local 14.0.0 Darwin Kernel Version 14.0.0: Fri Sep 19 00:26:44 PDT 2014; root:xnu-2782.1.97~2/RELEASE_X86_64 x86_64 i386 MacBookPro11,2 Darwin
```

**Comment by Pitometsu** [comment]
```
> emacs --version
GNU Emacs 24.4.1
Copyright (C) 2014 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```
From http://emacsformacosx.com

**Comment by Pitometsu** [comment]
Result of `~/.emacs.d > ./el-get/helm/emacs-helm.sh` is:
```elisp
("emacs" "-Q" "-l" "/tmp/helm-cfg.el")
Loading encoded-kb...done
For information about the GNU Project and its goals, type C-h C-p.
eval-buffer: Cannot open load file: helm-config
```

**Comment by tuhdo** [comment]
In the issue I refered above, people also had that issue with certain input crashed Emacs. They switched to [emacs-mac-port](https://github.com/railwaycat/emacs-mac-port) or install Emacs 25.0 that fixed the issue (few days ago).

**Comment by Pitometsu** [comment]
Thank you for suggestion. Emacs 25.0, sadly, is not released yet and some plugins not work with it.
So I'll try version from macports.

**Comment by thierryvolpiatto** [comment]
Netsu <notifications@github.com> writes:

> with helm-mode t, just type:
> M-x ^
> And that's it. Crash.

Please be sure to reinstall your helm correctly, either by running make
again outside of emacs after updating from git or by just deleting and
reinstalling helm from package.

Also, what is M-x ? is it execute-extended-command or helm-M-x ?
Note that people here, included me are using M-x (helm-M-x) all day
without any crash, so the issue is not reproductible and I need more
infos.
If emacs crash, you will have to run it under GDB to provide a good
backtrace, without such debug info I have no idea what could happen on
your side.
Also I need helm version, emacs version and OS version.

Be sure also to start with ./emacs-helm.sh if it is possible.

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by Pitometsu** [comment]
@thierryvolpiatto, It's helm-M-x for sure.
About build version, please, see information above.
This build without gdb debugging support as I know.
I'll provide additional info later, when try suggested macports version.

**Comment by thierryvolpiatto** [comment]
Netsu <notifications@github.com> writes:

> Result of ~/.emacs.d > ./el-get/helm/emacs-helm.sh is:
>
> ("emacs" "-Q" "-l" "/tmp/helm-cfg.el")

You have to run ./emacs-helm.sh from the helm directory.

> Loading encoded-kb...done
> For information about the GNU Project and its goals, type C-h C-p.
> eval-buffer: Cannot open load file: helm-config

Of course.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by Pitometsu** [comment]
```
("emacs" "-Q" "-l" "/tmp/helm-cfg.el")
Loading encoded-kb...done
For information about the GNU Project and its goals, type C-h C-p.
require: Cannot open load file: cl-lib
GNU Emacs 22.1.1 (mac-apple-darwin) of 2014-09-19 on glow.apple.com
```
It work wrong, because use system emacs, not Emacs.app
```
which emacs
emacs: aliased to /Applications/Emacs.app/Contents/MacOS/Emacs
```

**Comment by thierryvolpiatto** [comment]
Netsu <notifications@github.com> writes:

> ("emacs" "-Q" "-l" "/tmp/helm-cfg.el")
> Loading encoded-kb...done
> For information about the GNU Project and its goals, type C-h C-p.
> require: Cannot open load file: cl-lib
> GNU Emacs 22.1.1 (mac-apple-darwin) of 2014-09-19 on glow.apple.com
>
> It work wrong, because use system emacs, not Emacs.app

You can use the -P option to specify the path to your emacs executable.
./emacs-helm.sh -h
=> Usage: emacs-helm [-P} Emacs path [-h} help [--] EMACS ARGS


-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by Pitometsu** [comment]
@thierryvolpiatto `./emacs-helm.sh -P /Applications/Emacs.app/Contents/MacOS/Emacs`
work fine. Seems like something wrong with whole configuration.

**Comment by lewang** [comment]
On Fri, Jan 23, 2015 at 4:01 PM, Netsu <notifications@github.com> wrote:

>  Seems like something wrong with whole configuration.
>

Still shouldn't crash.  It would be nice to figure out what happened.

**Comment by halbtuerke** [comment]
I also experienced this crash and could fix it by disabling `helm-M-x-fuzzy-match`.
