### ISSUE TITLE
Filter helm return list agian. (i hope effect looks like occur/isearch)

### ISSUE THREAD

**Issue by zw963** [emacs-helm/helm#844]
I use a some many helm plugins, e.g. helm-ls-git.el, helm-etags+.el

all those will result a list when I press one hotkey, some times result is a lot.

I hope run occur in result again (or same effect function, e.g. isearch),  helm have this function ?

Thanks.

**Comment by tuhdo** [comment]
You can start typing to narrow the list. [My guide](http://tuhdo.github.io/helm-intro.html) could help you with basic Helm usage.

**Comment by thierryvolpiatto** [comment]
Billy <notifications@github.com> writes:

> I hope run occur in result again (or same effect function,
> e.g. isearch), helm have this function ?

Yes, helm-occur.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by lewang** [comment]
Press `space` followed by more narrow terms.

On Tue, Jan 27, 2015 at 1:33 PM, Thierry Volpiatto <notifications@github.com
> wrote:

>
> Billy <notifications@github.com> writes:
>
> > I hope run occur in result again (or same effect function,
> > e.g. isearch), helm have this function ?
>
> Yes, helm-occur.
>
> --
> Thierry
> Get my Gnupg key:
> gpg --keyserver pgp.mit.edu --recv-keys 59F29997
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/emacs-helm/helm/issues/844#issuecomment-71701373>.
>



-- 
Le

**Comment by thierryvolpiatto** [comment]
I am closing this, please use the mailing list for such discussions.
Thanks.
