### ISSUE TITLE
Cannot use helm-M-x-key face

### ISSUE THREAD

**Issue by angrybakon** [emacs-helm/helm#846]
I'm trying to edit the face as such:

```elisp
(with-eval-after-load 'helm
  (set-face-attribute 'helm-M-x-key nil :underline nil))
```

But I get:

```none
error: Invalid face, helm-M-x-key
```

I only get the error on startup, if I eval the code after startup it works fine.

**Comment by thierryvolpiatto** [comment]
Mathieu Marques <notifications@github.com> writes:

> I'm trying to edit the face as such:
>
> (with-eval-after-load 'helm
>   (set-face-attribute 'helm-M-x-key nil :underline nil))
>
> But I get:
>
> error: Invalid face, helm-M-x-key
>
> I only get the error on startup, if I eval the code after startup it works fine.

Please use the customize interface.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
Try using with-eval-after-load with helm-command. Anyway, no bug here.

**Comment by angrybakon** [comment]
> Try using with-eval-after-load with helm-command. Anyway, no bug here.

Yes that was it, thanks.
