### ISSUE TITLE
When going to directory, don't switch to Dired, but stay in Helm? 

### ISSUE THREAD

**Issue by ReneFroger** [emacs-helm/helm#848]
I have the files `C:\Foo\bar1.txt` and `C:\Foo\bar2.txt`

But when I type `Foo`, I see Helm is pointing on `C:\Foo`. 

When I press Enter, I get switched to Dired, and I see bar1.txt and bar2.txt. I would like to stay in Helm, but see the contents of the directory `Foo` instead. 

I studied the Helm wiki, but found no answer yet. Any suggestions to get this behaviour? 

Thanks in advance for your reply!

**Comment by thierryvolpiatto** [comment]
ReneFroger <notifications@github.com> writes:

> I have the files C:\Foo\bar1.txt and C:\Foo\bar2.txt
>
> But when I type Foo, I see Helm is pointing on C:\Foo.
>
> When I press Enter, I get switched to Dired, and I see bar1.txt and
> bar2.txt. I would like to stay in Helm, but see the contents of the
> directory Foo instead.
>
> I studied the Helm wiki, but found no answer yet. Any suggestions to
> get this behaviour?

I guess you are refering to helm-find-files.
Use persistent action (C-j) on C:/Foo
Use C-l to come back to C:/
If you customize helm-ff-auto-update-initial-value as soon as you type
Foo, Foo directory will be expanded.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by ReneFroger** [comment]
Sorry for my belated response. Thanks for your reply. 

But I like more the idea when Helm stumbles upon a directory, when pressed Enter, it will automatically change directory to the stumbled directory, and gives a list, instead of switching. Would that be possible? 

If more easier, a way to add `helm-find-files` to the current `Helm-for-files` screen?

**Comment by thierryvolpiatto** [comment]
No helm should switch to dired when hitting RET on a directory.
And no, don't use helm-find-files in helm-for-files or anywhere else, it should be used alone.
You should get used with C-j and C-l or arrow keys to navigate you files.

**Comment by ReneFroger** [comment]
>> No helm should switch to dired when hitting RET on a directory.

Why? 

>> And no, don't use helm-find-files in helm-for-files or anywhere else, it should be used alone.

Could you explain that? Thanks. 

You should get used with C-j and C-l or arrow keys to navigate you files.

The problem is that I have already bounded C-j for Pageup and Pagedown. :smile: So I'm trying to see if I could bind it to Enter.

**Comment by tuhdo** [comment]
@ReneFroger You can do it using this code snioppet here (also from @thierryvolpiatto ): https://github.com/emacs-helm/helm/issues/776

**Comment by thierryvolpiatto** [comment]
Remember that binding a command to RET in helm is a bad idea, of course you can do it, but you will break some mechanisms (i.e helm-maybe-exit-minibuffer).

For helm-find-files, it is the same, expect bad things happen if you use it among other sources, I wrote it to be used alone, anyway it is non--sense to use it among other sources.
Generally I think it is a bad concept to use multi source command like helm-for-files for searching files.  I try to develop helm applications to be used chained one after the other, i.e helm-find-files => browse-project => grep etc...
