### ISSUE TITLE
Automatically expand file path after narrowing basename

### ISSUE THREAD

**Issue by tuhdo** [emacs-helm/helm#849]
Currently, we can toggle on/off file path with `C-]`. However, it is inconvenient when there are duplicate filenames. so we have to toggle off again. I suggest an automatic behaviour that makes it easier to use: if basename matching is toggled (path is hidden), then after user enters some pattern, Helm narrows to a set of files, and when user adds a space, the full paths of the narrowed files are revealed. 

Doing it this way, we can make better use of basename matching, without the hassle of turning on/off, and with this behaviour we can actually set basename matching the default matching for any Helm command. I would say it would be even more effective than fuzzy matching against filename with full path.

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> Currently, we can toggle on/off file path with C-]. However, it is
> inconvenient when there are duplicate filenames. so we have to toggle
> off again. I suggest an automatic behaviour that makes it easier to
> use: if basename matching is toggled (path is hidden), then after user
> enters some pattern, Helm narrows to a set of files, and when user
> adds a space, the full paths of the narrowed files are revealed.

I don't know what command you are speaking about, but I guess it is
helm-for-files.
Space is used to start a multi regexp matching.
I think that what we have actually is enough for this command, thus you
can make your search using basename just with the "-b" flag, this allow
to show full path and match only basename.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment]
It would benefit commands like `helm-git-ls-git` or similar. For example, using `helm-ls-git-ls`, when using basename to narrow, I got many files with same basename. At this point, the only way to narrow to unique candidate is to toggle the file paths, manually and start narrowing more. It would be more convenient if we can do this process automatically:

- First, narrow to a set of files with some basename.
- Seconds, add a space " ".
- Last, file paths are revealed, and we start narrowing more.

Doing it that way, we can actually set basename matching as the default for `helm-ls-git`.

**Comment by lewang** [comment]
I propose some different semantics to fuzzy.  Currently, the search is considered "fuzzy" until you press `<space>`, and afterwards the entire query is considered a normal helm search.

I propose when fuzzy is enabled, search for "fuzzy1 term2 !term3" means

1. fuzzy search/sort fuzzy1
2. normal search term2
3. negate term3.

In @tuhdo's usecase, `flx` would score matches in the basename higher automatically.  i.e. We solve this problem algorithmically, instead of *explicitly spelling out a term is intended to be a "basename" search*, we simply move the most relevant results to the top.

**Comment by thierryvolpiatto** [comment]
Le Wang <notifications@github.com> writes:

> I propose some different semantics to fuzzy. Currently, the search is considered "fuzzy" until you press <space>, and afterwards the entire query is considered a
> normal helm search.
>
> I propose when fuzzy is enabled, search for "fuzzy1 term2 !term3" means
>
>  1. fuzzy search/sort fuzzy1
>  2. normal search term2
>  3. negate term3.

I would prefer keeping the actual behavior.

> In @tuhdo's usecase, flx would score matches in the basename higher
> automatically. i.e. We solve this problem algorithmically, instead of
> explicitly spelling out a term is intended to be a "basename" search,
> we simply move the most relevant results to the top.

This imply modifying the scoring to give a better score to basename, why
not if that can be done without performance loss.

So if you want to reimplement completely fuzzy in helm, keep in mind:

- preserve multi regexp matching as soon as we enter space.
- keep correct performances.
- make it working both with in-buffer and sync sources.

Actually your branch is breaking helm and it is unsafe to merge it.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by lewang** [comment]
On Thu, Feb 5, 2015 at 12:10 AM, Thierry Volpiatto <notifications@github.com
> wrote:

> > I propose when fuzzy is enabled, search for "fuzzy1 term2 !term3" means
> >
> > 1. fuzzy search/sort fuzzy1
> > 2. normal search term2
> > 3. negate term3.
>
> I would prefer keeping the actual behavior.
>

Fuzzy is best used when available pervasively (except for the sources that
take a regexp, obviously).  I believe this change is necessary to implement
features such as #837 . We can accomplish this in small steps however.


> So if you want to reimplement completely fuzzy in helm, keep in mind:
>
> - preserve multi regexp matching as soon as we enter space.
> - keep correct performances.
> - make it working both with in-buffer and sync sources.
>

I will definitely keep this in mind.  Thanks.


> Actually your branch is breaking helm and it is unsafe to merge it.


It's a work in progress.  :-)  I'll update the pull request as I change it.

Thanks for your comments.


>
> --
> Thierry
> Get my Gnupg key:
> gpg --keyserver pgp.mit.edu --recv-keys 59F29997
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/emacs-helm/helm/issues/849#issuecomment-72995310>.
>



-- 
Le
