### ISSUE TITLE
helm-buffers-list does not wrap line like helm-mini

### ISSUE THREAD

**Issue by tuhdo** [emacs-helm/helm#851]
When a window is small enough, `helm-mini` can wrap its line but not `helm-buffers-list`.

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> When a window is small enough, helm-mini can wrap its line but not helm-buffers-list.

Can you develop ?

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment]
That is, when you split window small enough (i.e. 2 vertical windows on a small 13 inches laptop screen), long buffer names are truncated in `helm-buffers-list`, while `helm-mini` it is wrapped to another line.

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> That is, when you split window small enough (i.e. 2 vertical windows
> on a small 13 inches laptop screen), long buffer names are truncated
> in helm-buffers-list, while helm-mini it is wrapped to another line.

Indeed, it is because truncate-lines is not set like in *buffers-list.
I don't use helm-mini (and helm-for-files) at all, so I never notice
this.
Will fix it soon.

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
