### ISSUE TITLE
Abnormal high amount of report about helm issues after update

### ISSUE THREAD

**Issue by syl20bnr** [emacs-helm/helm#853]
Maintainer of [spacemacs](https://github.com/syl20bnr/spacemacs) here. Since several weeks I noticed a higher number of people complaining of broken spacemacs due to random helm errors after upgrading their MELPA packages.

I have yet to investigate where the issue lies (spacemacs, paradox, helm ?) so I open this thread to keep track of it and gather all the issues related to it.

My first thought is to look at helm though because it is the only package that breaks like this among an average number of 100+ packages used by spacemacs users. OTOH there does not seem to have a lot of issue with prelude users (but helm is not mandatory unlike with spacemacs).

**Comment by thierryvolpiatto** [comment]
Sylvain Benner <notifications@github.com> writes:

> Maintainer of spacemacs here. Since several weeks I noticed a higher
> number of people complaining of broken spacemacs due to random helm
> errors after upgrading their MELPA packages.

We have no errors actually, most recently errors were due to eieio bugs
depending the emacs version in use (true for all packages using eieio), 
all of them have been fixed upstream.

As long as you are not able to tell me what error you encountered, I see
this bug report as unuseful.
So please report real errors, not the fact you are not happy with helm.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by syl20bnr** [comment]
?? Where did I say I'm not happy with helm ?

Gathering the helm related issues I get is unuseful... Weird way of reasoning.

You prefer that I say to people to post all this issues here instead of gathering them maybe ??

Maybe something useful is to check this issues and provide info to your user.

Because even if you don't like it, any user of spacemacs is de facto à user of helm.

So we should better collaborate which I started to do here.

**Comment by thierryvolpiatto** [comment]
None of the issues here are bugs, only bad installation or bad usagge (pony-manage) of helm.
You send me a bunch of issues here and I have to fix them ?
Forget it.
So if you want something happen send me an issue about:
helm is not working after a good installation as described in our readme and started with a minimal install like ./emacs-helm.sh.
So I am closing this.

**Comment by syl20bnr** [comment]
You are making conclusions too quickly with false assumptions.

I clearly stated that I have to invetigate. Since it is all related to helm and happens after an update it was clearly a good move to gather them here to get feedback and work together on them.

I have now well noted that you are a poor team player and will take this into account in put future discussions.

So yes I'm happy with helm but not with his maintainer.

**Comment by thierryvolpiatto** [comment]
Sylvain Benner <notifications@github.com> writes:

> I have now well noted that you are a poor team player and will take
> this into account in put future discussions.

I think there will be no more discussion with you.
And if you are not happy I suggest you use something else as dependency
instead of helm.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by syl20bnr** [comment]
As I said... Poor team player.
