### ISSUE TITLE
Helm fails to start with minibuffer-setup-hook

### ISSUE THREAD

**Issue by tuhdo** [emacs-helm/helm#855]
It will throw this error: `"Error: trying to run helm within a running helm session"`

Here is example code:

```elisp
(setq tmp '("cat" "dog" "fish"))

(minibuffer-with-setup-hook 'minibuffer-complete
  (completing-read (concat "Pick one (" 
                           (mapconcat 'identity (all-completions "" tmp) " ") 
                           "): ") 
                   tmp))
```

The above code opens a window listing all available candidates for completion, but failed when Helm mode is enabled.

It is related to this issue in [Spacemacs](https://github.com/syl20bnr/spacemacs/issues/517). `minibuffer-with-setup-hook` is used [here](https://github.com/davidmiller/pony-mode/blob/master/src/pony-mode.el#L745-L758) in `pony-mode`.

Is it possible to make `helm-comp-read` compatible with such use case?

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> It will throw this error: "Error: trying to run helm within a running helm session"
>
> Here is example code:
>
> (setq tmp '("cat" "dog" "fish"))
>
> (minibuffer-with-setup-hook 'minibuffer-complete
>   (completing-read (concat "Pick one (" 
>                            (mapconcat 'identity (all-completions "" tmp) " ") 
>                            "): ") 
>                    tmp))
>
> The above code opens a window listing all available candidates for completion, but failed when Helm mode is enabled.
>
> It is related to this issue in Spacemacs. minibuffer-with-setup-hook is used here in pony-mode.
>
> Is it possible to make helm-comp-read compatible with such use case?

No, this code is non sense, why are they using minibuffer-complete, it
is similar to (completing-read prompt (completing-read ...) which is
non sense.  And putting the result of collection is an even more bad
idea.
Why make complex when we can make simple:
(completing-read "Pick one: " tmp) is enough.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment]
I guess it's the only way to open a buffer initially with completion candidates, so the users know what candidates there are. Stock `completing-read` requires you to press `TAB` to show the candidates.

And such a case is bad code writing, what's your suggestion to keep the same behaviour but is still compatible with `helm-mode`?

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> I guess it's the only way to open a buffer initially with completion
> candidates,

Why ?
They write such code just to show candidates in prompt, that's the only
purpose of this code, and it is a bad idea.

> so the users know what candidates there are. Stock completing-read
> requires you to press TAB to show the candidates.
>
> And such a case is bad code writing, what's your suggestion to keep
> the same behaviour but is still compatible with helm-mode?

As I said, (completing-read "prompt: " candidates)

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment]
> They write such code just to show candidates in prompt, 

It doesn't show candidates in prompt, but show it in a separate buffer above minibuffer. I tested it.

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

>     They write such code just to show candidates in prompt,
>    
> It doesn't show candidates in prompt, but show it in a separate buffer above minibuffer. I tested it.

So use with-temp-buffer-window or something similar.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

>     They write such code just to show candidates in prompt,
>    
> It doesn't show candidates in prompt, but show it in a separate buffer above minibuffer. I tested it.

And anyway it is not needed to show candidates in a separate window when
helm show all candidates in its buffer.

@tuhdo Don't care too much of such issue, let people adapt their code to
helm instead of wanting fixing helm to adapt to such code.

As long as there is no issue on our side you can close this bug.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment]
The code is actually as simple as this:

```elisp
(setq tmp '("cat" "dog" "fish"))

(minibuffer-with-setup-hook 'minibuffer-complete
  (completing-read (concat "Pick one: ") tmp))
```

The code adds the command `minibuffer-complete` to `minibuffer-setup-hook` (via the macro `minibuffer-with-setup-hook`), so completion candidates are shown immediately in a buffer. In normal `completing-read`, `minibuffer-complete` is bound to `TAB`; in other word, the author of `pony-mode` makes his package automatically press `TAB` for its user to show all available candidates in a buffer. When `completing-read` is in `helm-mode`, it is bound to `helm-execute-persistent-action`, so no `minibuffer-complete` is going to be executed and there will be no error.

> Don't care too much of such issue, let people adapt their code to helm instead of wanting fixing helm to adapt to such code.

Well, I just want to understand the root cause and propose a fix for either side. In this case, I think someone should propose a PR for the author of `pony-mode` to use either `ido-completing-read` or handle it when `helm-mode` is active. 

Or, is it possible to remap `minibuffer-complete` to `helm-execute-persistent-action` when `helm-mode` is activated, and restore it `helm-mode` is deactivated and make Helm compatible with `minibuffer-setup-hook`?

Also, I'm planning to use Spacemacs with my custom configuration.

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> The code is actually as simple as this:
>
> (setq tmp '("cat" "dog" "fish"))
>
> (minibuffer-with-setup-hook 'minibuffer-complete
>   (completing-read (concat "Pick one: ") tmp))

As I said one can use someting like

(with-helm-display-marked-candidates
  "*test*"
  '("foo" "bar" "baz")
  (completing-read "test: " '("foo" "bar" "baz")))

They can use with-temp-buffer-window for compatibility.

> Or, is it possible to remap minibuffer-complete to
> helm-execute-persistent-action when helm-mode is activated, and
> restore it helm-mode is deactivated and make Helm compatible with
> minibuffer-setup-hook?

No, I don't want to introduce such hack.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Thierry Volpiatto <thierry.volpiatto@gmail.com> writes:

> As I said one can use someting like
>
> (with-helm-display-marked-candidates
>   "*test*"
>   '("foo" "bar" "baz")
>   (completing-read "test: " '("foo" "bar" "baz")))

Which is BTW as silly as the initial code with minibuffer-setup-hook but
is working.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment]
> No, I don't want to introduce such hack.

Alright. I guess so.

I will suggest them to account for Helm like this:

```elisp
(minibuffer-with-setup-hook (lambda () (unless helm-mode
                                         (minibuffer-complete)))
  (completing-read (concat "Pick one: ") tmp))
```

So we can keep the original behaviour and still account for Helm.

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

>     No, I don't want to introduce such hack.
>    
> Alright. I guess so.
>
> I will suggest them to account for Helm like this:
>
> (minibuffer-with-setup-hook (lambda () (unless helm-mode
>                                          (minibuffer-complete)))
>   (completing-read (concat "Pick one: ") tmp))
>
> So we can keep the original behaviour and still account for Helm.

Yes, but such hack still unuseful even when
helm is disabled, just need to hit TAB to show completions.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
