### ISSUE TITLE
Not an issue, but for Evil users, a good tip for Helm! 

### ISSUE THREAD

**Issue by ReneFroger** [emacs-helm/helm#859]
Not really a issue, but totally worth mentioning it. You could install Hydra: http://angelic-sedition.github.io/blog/2015/02/03/a-more-evil-helm/

After installing, try the following: 

    ;; Hydra for in Helm
    (defhydra helm-like-unite ()
      ("q" keyboard-escape-quit "exit")
      ("<SPC>" helm-toggle-visible-mark "mark")
      ("a" helm-toggle-all-marks "(un)mark all")
      ("v" helm-execute-persistent-action)
      ("g" helm-beginning-of-buffer "top")
      ("h" helm-previous-source)
      ("l" helm-next-source)
      ("G" helm-end-of-buffer "bottom")
      ("j" helm-next-line "down")
      ("k" helm-previous-line "up")
      ("i" nil "cancel"))

        (key-chord-define helm-map "jk" 'helm-like-unite/body)

So when you're opening helm, press `jk` to toggle to navigation on your home row. `h` and `l` to switch from source, and `j`/`k` to navigate. 

Sorry if this is misplaced, but I couldn't think about another place where Helm users gather.

**Comment by thierryvolpiatto** [comment]
ReneFroger <notifications@github.com> writes:

> Sorry if this is misplaced, but I couldn't think about another place where Helm users gather.

We have a mailing list for such things:

https://groups.google.com/group/emacs-helm?hl=en

Thanks anyway.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
