### ISSUE TITLE
Allow Helm action for open other window opens more than one

### ISSUE THREAD

**Issue by tuhdo** [emacs-helm/helm#861]
Currently, even with marking, we can only open at most one other window. It would be nice if we can open two windows side by side if more than one buffer/file is marked. For example, if I mark 3 or 4 buffers, it should open two buffers side by side and the remaining hidden. This way, I don't have to open all buffers/files with `RET`, and then `C-x b` then `C-c o` to open other window.

**Comment by tuhdo** [comment]
@thierryvolpiatto I tried and it is still the same: `C-c o` to open buffers/files in other window, only one is opened.

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> @thierryvolpiatto I tried and it is still the same: C-c o to open
> buffers/files in other window, only one is opened.

In helm-buffers-list:

RET open buffers in their own windows.
C-c o same but keep the current window with its buffer.

In helm-find-files:

RET open files in their own window.
C-c o haven't changed (and will not change).

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment]
> RET open files in their own window.

Yes, it's even better :)

However, could you make it customizable? That is, instead of horizontal splitting, I can make it horizontal splitting.
