### ISSUE TITLE
[Feature Request] let helm-occur worked like helm-git-grep.

### ISSUE THREAD

**Issue by zw963** [emacs-helm/helm#862]
I like worked with helm, as helm plugins, 

I have a personal advice about helm-occur, when I press one self-defined hotkey, I hope helm-occur can grep some result for me immediately, use read input function read current point symbol to me as default.

following is my pesonal hacking, just for convenient occur same symbol in only one ruby buffer.

```cl
(defun helm-occur (&optional input)
  "Preconfigured helm for Occur."
  (interactive)
  (helm-occur-init-source)
  (let ((bufs (list (buffer-name (current-buffer)))))
    (helm-attrset 'moccur-buffers bufs helm-source-occur)
    (helm-set-local-variable 'helm-multi-occur-buffer-list bufs)
    (helm-set-local-variable
     'helm-multi-occur-buffer-tick
     (cl-loop for b in bufs
              collect (buffer-chars-modified-tick (get-buffer b)))))
  (helm :sources 'helm-source-occur
        :buffer "*helm occur*"
        :history 'helm-grep-history
        :input (or input
                   (if (use-region-p)
                       (replace-regexp-in-string
                        " " "\\\\s"
                        (buffer-substring (region-beginning) (region-end))
                        )

                     (progn
                       (if (looking-back "::\\w+" (line-beginning-position))
                           (thing-at-point 'word)
                         (thing-at-point 'symbol))
                       )))
        :preselect (and (memq 'helm-source-occur helm-sources-using-default-as-input)
                        (format "%s:%d:" (buffer-name) (line-number-at-pos (point))))
        :truncate-lines t))
```

if with active region, will use region result, if no region, use current symbol, 
otherwise, input myself.

Thanks.

**Comment by thierryvolpiatto** [comment]
Billy <notifications@github.com> writes:

> I like worked with helm, as helm plugins,
>
> I have a personal advice about helm-occur, when I press one
> self-defined hotkey, I hope helm-occur can grep some result for me
> immediately, use read input function read current point symbol to me
> as default.

No, you have for this M-n and C-w, not only in helm-occur but in all
helm commands.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Thanks to submit your own code anyway, I am closing this as I don't want a default input as default in helm, as said above it is always provided by M-n, and also C-w (a different thing though).

**Comment by zw963** [comment]
Thanks, Cool!
