### ISSUE TITLE
How get source M-x into helm-for-files-preferred-list? 

### ISSUE THREAD

**Issue by ReneFroger** [emacs-helm/helm#863]
I have the folowing setup

       (setq helm-for-files-preferred-list
      '(
        helm-source-buffers-list
        helm-source-recentf
        helm-source-files-in-current-dir
        helm-source-locate
     )) 

I would like to add  the following source`helm-M-x` into the list above. But `helm-M-x` and `helm-source-M-x` both didn't worked. I couldn't find any documentation about Helm M-x. Any suggestions? 

Thanks in advance!

**Comment by thierryvolpiatto** [comment]
ReneFroger <notifications@github.com> writes:

> I have the folowing setup
>
>    (setq helm-for-files-preferred-list
>   '(
>     helm-source-buffers-list
>     helm-source-recentf
>     helm-source-files-in-current-dir
>     helm-source-locate
>
> ))
>
> I would like to add the following sourcehelm-M-x into the list
> above. But helm-M-x and helm-source-M-x both didn't worked. I couldn't
> find any documentation about Helm M-x. Any suggestions?

helm-M-x have no source, it use internally helm-comp-read, one
motivation of making helm-M-x like this was to avoid doing what you want
to do, which is not a good idea IMO.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by ReneFroger** [comment]
Ok, I guess M-x is a slow source for Helm-for-files?

**Comment by thierryvolpiatto** [comment]
ReneFroger <notifications@github.com> writes:

> Ok, I guess M-x is a slow source for Helm-for-files?

Thus it is unrelated to files.

Costly sources should be used alone or with low cost sources, I have
accepted helm-locate by default because it is the only costly source
used there, but IMO it is not a good idea to have it in this list, it is
removed in my config, I use it alone typically launched from
helm-find-files when needed.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by ReneFroger** [comment]
I understand that `Helm M-x` is not a low cost source, and thus should not be combined with another sources in your configuration. 

But my systems have huge resources available for that. So I would like to give a try. 

I understand it's removed from your configuration. My configuration is different than yours, so I would like to add. If you could give me some tips how to do, it would be great. It will not ruin your confirguration by the way, so there is nothing to lose for you. Only win for me, if it seems to run well along with my desktop resources. :+1:

**Comment by thierryvolpiatto** [comment]
ReneFroger <notifications@github.com> writes:

> I understand that Helm M-x is not a low cost source, and thus should
> not be combined with another sources in your configuration.
>
> But my systems have huge resources available for that. So I would like to give a try.

You can't, I would have to rewrite helm-M-x for that...  As I said
helm-M-x have no source.

> I understand it's removed from your configuration.

It is not removed from my configuration, it is not possible to add.

What you can do is writing your own source, here is a starting point:

(helm-build-in-buffer-source "test"
     :data (all-completions "" obarray 'commandp)
     :action 'command-execute
     :coerce 'intern)

This will give you a very basic source to execute commands.
(It will miss a lot of features from helm-M-x though)

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
