### ISSUE TITLE
git oopsie

### ISSUE THREAD

**Issue by lewang** [emacs-helm/helm#864]
@thierryvolpiatto I meant to offer 3e446d0 and 65ff4d1 as a pull-request, but accidentally committed them to master.  They are pretty trivial, though.  I'll be more careful in future.

**Comment by thierryvolpiatto** [comment]
Le Wang <notifications@github.com> writes:

> @thierryvolpiatto I meant to offer 3e446d0 and 65ff4d1 as a
> pull-request, but accidentally committed them to master. They are
> pretty trivial, though. I'll be more careful in future.

No problem ;-), I will update the update slot accordingly in helm-source.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
