### ISSUE TITLE
Allow grep command to colorize its own output

### ISSUE THREAD

**Issue by lewang** [emacs-helm/helm#865]
Right now, helm does its own highlighting based on the query.  This means the the style of regexp needs to match (i.e. Emacs style) for this to work.

A problem manifests when this isn't the case.

1. I use ack and search for `\(with`.  The backslash is necessary for ack to work, but it's broken as a Emacs regexp.

Both ack and grep are capable of highlighting matches using ANSI codes, it would be both faster and more consistent to do what `grep-filter` already does - search for ansi codes instead of re-evaluating the query.

**Comment by thierryvolpiatto** [comment]
Le Wang <notifications@github.com> writes:

> Right now, helm does its own highlighting based on the query. This
> means the the style of regexp needs to match (i.e. Emacs style) for
> this to work.
>
> A problem manifests when this isn't the case.
>
>  1. I use ack and search for \(with. The backslash is necessary for
>  ack to work, but it's broken as a Emacs regexp.

ack doesn't support "\(" you have to use "[(]", but not for group, in
emacs you have to use "\(group1\)" with ack you just write "(group1)".

> Both ack and grep are capable of highlighting matches using ANSI

You will have an error anyway if you enter "\(".

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by lewang** [comment]
On Wed, Feb 11, 2015 at 2:16 AM, Thierry Volpiatto <notifications@github.com
> wrote:

>
> Le Wang <notifications@github.com> writes:
>
> > Right now, helm does its own highlighting based on the query. This
> > means the the style of regexp needs to match (i.e. Emacs style) for
> > this to work.
> >
> > A problem manifests when this isn't the case.
> >
> > 1. I use ack and search for \(with. The backslash is necessary for
> > ack to work, but it's broken as a Emacs regexp.
>
> ack doesn't support "\(" you have to use "[(]", but not for group, in
> emacs you have to use "\(group1\)" with ack you just write "(group1)".
>

It seems to over here.

https://asciinema.org/u/8659


-- 
Le

**Comment by thierryvolpiatto** [comment]
Thierry Volpiatto <thierry.volpiatto@gmail.com> writes:

> Le Wang <notifications@github.com> writes:
>
>> Right now, helm does its own highlighting based on the query. This
>> means the the style of regexp needs to match (i.e. Emacs style) for
>> this to work.
>>
>> A problem manifests when this isn't the case.
>>
>>  1. I use ack and search for \(with. The backslash is necessary for
>>  ack to work, but it's broken as a Emacs regexp.
>
> ack doesn't support "\(" you have to use "[(]",

Seems I was wrong about this.

> but not for group, in emacs you have to use "\(group1\)" with ack you
> just write "(group1)".
>
>> Both ack and grep are capable of highlighting matches using ANSI

Unfortunately emacs is not able to compute a grep ansi sequence, it
is though working fine for ack and it's a nice feature to add.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
So now ANSI is usable both with ack and grep, see the docstring of
`helm-grep-default-command' for more infos.
For grep you need to modify the GREP_COLORS env var (an emacs bug ?).

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
I am closing because now ANSI is working in ack, grep and git-grep.
