### ISSUE TITLE
Helm google suggest, replace search query. 

### ISSUE THREAD

**Issue by ReneFroger** [emacs-helm/helm#866]
Keep in mind that my knowledge of Lisp is not very well, but I aim to improve it. 
I have a query, that allows me to direct Google me to my direct result (on the first hit): `http://www.google.com/search?source=ig&hl=en&rlz=1G1GGLQ_ENUS264&q=%s&btnI=I%27m+Feeling+Lucky` 

where %s is replaced by the string of desired subject. 

When I look in the code of helm-net.el, I see the following: 

>(defcustom helm-google-suggest-search-url
>  "http://www.google.com/search?ie=utf-8&oe=utf-8&q="
>  "URL used for Google searching."
>  :type 'string
>  :group 'helm-net)

Okay. In my `.emacs` configuration file, I do a `setq`, from this [tutorial](https://www.gnu.org/software/emacs/manual/html_node/eintr/defcustom.html) , so

>(setq helm-google-suggest-search-url
>  "http://www.google.com/search?source=ig&hl=en&rlz=1G1GGLQ_ENUS264&q=%s&btnI=I%27m+Feeling+Lucky"
>  "Modified URL used for Google searching."
>  :type 'string
>  :group 'helm-net)

I assume the `%s` will be replaced by the given input, because `helm-surfraw-duckduckgo-url` uses the same technique. However, I get errors. Any suggestions from anyone here to get this working? 

Thanks in advance.

**Comment by michael-heerdegen** [comment]
setq is not defcustom. It accepts only two args: a variable, and a value.  So you probably want

```
(setq helm-google-suggest-search-url
"http://www.google.com/search?source=ig&hl=en&rlz=1G1GGLQ_ENUS264&q=%s&btnI=I%27m+Feeling+Lucky")
```

**Comment by ReneFroger** [comment]
Thanks for your help. The change works, but instead replacing the %s with
the input, it redirects me to the first hit of the search word '%s'. But I
see the Helm-duckduck go works fine with replacing the %s. Any idea how I
could change this?

Thanks in advance!

2015-02-11 1:11 GMT+01:00 Michael Heerdegen <notifications@github.com>:

> setq is not defcustom. It accepts only two args: a variable, and a value.
> So you probably want
>
> (setq helm-google-suggest-search-url
> "http://www.google.com/search?source=ig&hl=en&rlz=1G1GGLQ_ENUS264&q=%s&btnI=I%27m+Feeling+Lucky")
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/emacs-helm/helm/issues/866#issuecomment-73812118>.
>



-- 
Sent from my Vmail client. <http://danielchoi.com/software/vmail.html>

**Comment by thierryvolpiatto** [comment]
ReneFroger <notifications@github.com> writes:

> Thanks for your help. The change works, but instead replacing the %s with
> the input, it redirects me to the first hit of the search word '%s'. But I
> see the Helm-duckduck go works fine with replacing the %s. Any idea how I
> could change this?

Should work now (helm-google-suggest-search-url was not a format string):

(setq helm-google-suggest-search-url
  "http://www.google.com/search?source=ig&hl=en&rlz=1G1GGLQ_ENUS264&q=%s&btnI=I%27m+Feeling+Lucky")

> Thanks in advance!
>
> 2015-02-11 1:11 GMT+01:00 Michael Heerdegen <notifications@github.com>:
>
>> setq is not defcustom. It accepts only two args: a variable, and a value.
>> So you probably want
>>
>> (setq helm-google-suggest-search-url
>> "http://www.google.com/search?source=ig&hl=en&rlz=1G1GGLQ_ENUS264&q=%s&btnI=I%27m+Feeling+Lucky";)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/emacs-helm/helm/issues/866#issuecomment-73812118>.
>>

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by ReneFroger** [comment]
I upgraded Helm with Melpa, thanks for that.

But unfortunately, I tried `M-x helm-google-suggest`, then typing "test examples". And then I got a error, see the screenshot. It mentions there are not enough arguments for the string? 

![schermafdruk 2015-02-11 16 22 53](https://cloud.githubusercontent.com/assets/5211845/6149656/742617c4-b20a-11e4-8a55-ff06aab9baa6.png)

Have you tested the changes, by the way?

**Comment by thierryvolpiatto** [comment]
ReneFroger <notifications@github.com> writes:

> I upgraded Helm with Melpa, thanks for that.
>
> But unfortunately, I tried M-x helm-google-suggest, then typing "test
> examples". And then I got a error, see the screenshot. It mentions
> there are not enough arguments for the string?

Because you still have a helm-google-suggest-search-url customization
somewhere that is still using the old non--format string, just remove it
or add you own settings with setq:

(setq helm-google-suggest-search-url
  "http://www.google.com/search?source=ig&hl=en&rlz=1G1GGLQ_ENUS264&q=%s&btnI=I%27m+Feeling+Lucky")

> Have you tested the changes, by the way?

Of course, it is working fine with default settings.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by ReneFroger** [comment]
Thanks for your reply. 

I don't want be rude. But you're wrong. I haven't any helm-google-suggest-search-url customization around somewhere (helm-ag confirmed this), I haven't somewhere in my emacs configuration. 

To confirm this, I did `C-x C-e` on 
`(setq helm-google-suggest-search-url
  "http://www.google.com/search?source=ig&hl=en&rlz=1G1GGLQ_ENUS264&q=%s&btnI=I%27m+Feeling+Lucky")`

If you look at the window on the right side, you see same new string for query. Maybe you have another configuration?

**Comment by thierryvolpiatto** [comment]
ReneFroger <notifications@github.com> writes:

> I don't want be rude. But you're wrong.

I am not wrong, starting from emacs-helm.sh works fine here, and there
is few chances I made a mistake on such a trivial code.

Please start from a minimal configuration, and check also that your helm
installation is correct (See the FAQ).

> I haven't any helm-google-suggest-search-url customization around
> somewhere (helm-ag confirmed this), I haven't somewhere in my emacs
> configuration.

Search harder, what's the value of helm-google-suggest-search-url ?
(eval it in M-:)

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by ReneFroger** [comment]
`M-:` with Eval input: `helm-google-suggest-search-url` 

gives me: 

"http://www.google.com/search?source=ig&hl=en&rlz=1G1GGLQ_ENUS264&q=%s&btnI=I%27m+Feeling+Lucky"

**Comment by michael-heerdegen** [comment]
Rene is right, it fails for me too with his url.  Probably because of the "%27m" substring his search string includes. It is treated by format as replace string.

Urls are likely to have such %nn escape codes in them. We need to handle that somehow.

**Comment by michael-heerdegen** [comment]
The easiest solution would probably to use replace-regexp-in-string to substitute the %s.  Or can it even happen that an url even includes "%s"?

**Comment by thierryvolpiatto** [comment]
ReneFroger <notifications@github.com> writes:

> M-: with Eval input: helm-google-suggest-search-url
>
> gives me:
>
> "http://www.google.com/search?source=ig&hl=en&rlz=1G1GGLQ_ENUS264&q=%s&btnI=I%27m+Feeling+Lucky"

This is not the default, which mean you are not starting with a minimal
config.
Please start with a minimal config:

emacs -Q
(add-to-list 'load-path "path/to/helm")
(require 'helm-config)
M-x toggle-debug-on-error
M-x helm-google-suggest (or C-x c C-c g)

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Rene is right, it fails for me too with his url. Probably because of the "%27m" substring his search string includes. It is treated by format as replace string.
>
> Urls are likely to have such %nn escape codes in them. We need to handle that somehow.

No, it is just he have copied/pasted the url from his navigator without
formatting it, user should provide a decent url, to see the good url to
use, eval this:

(url-unhex-string
"http://www.google.com/search?source=ig&hl=en&rlz=1G1GGLQ_ENUS264&q=%s&btnI=I%27m+Feeling+Lucky")

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by ReneFroger** [comment]
Sorry thierryvolpiatto for my questions, propably I didn't something wrong. Or your settings are just only working with your setup? I just started out with clean Emacs with empty emacs configuration file. Added MELPA to package manager, to get the latest modified version of Helm. Installed Helm in package manager. 

Then I evaluated the url-unhex-string. Gives me the same output as I posted earlier. 

Then I configured `helm-google-suggest-search-url`. I evaluated it. To be sure, I restarted Emacs again. The .emacs file was already saved, and Emacs confirmed that it reads from same .emacs. 

After `M-x toggle-debug-on-error`, I type `M-x helm-google-suggest` then I type "example words".  

![schermafdruk 2015-02-13 11 12 16](https://cloud.githubusercontent.com/assets/5211845/6185651/500afe5a-b371-11e4-975a-7d21fd54992d.png)

 This is the empty Emacs. I use Windows 7 x64 with Emacs 25.1 by the way.

**Comment by thierryvolpiatto** [comment]
ReneFroger <notifications@github.com> writes:

> Sorry thierryvolpiatto for my questions, propably I didn't something
> wrong.

You are indeed doing something wrong.

> Or your settings are just only working with your setup?

My settings are never involved here as I am always refering to helm
default starting to a minimal config (i.e emacs-helm.sh)

> I just started out with clean Emacs with empty emacs configuration
> file. Added MELPA to package manager, to get the latest modified
> version of Helm. Installed Helm in package manager.
>
> Then I evaluated the url-unhex-string. Gives me the same output as I posted earlier.

No.

(url-unhex-string
"http://www.google.com/search?source=ig&hl=en&rlz=1G1GGLQ_ENUS264&q=%s&btnI=I%27m+Feeling+Lucky")
=>                                                                          ^^^^^
"http://www.google.com/search?source=ig&hl=en&rlz=1G1GGLQ_ENUS264&q=%s&btnI=I'm+Feeling+Lucky"
                                                                            ^^^^^
>
> After M-x toggle-debug-on-error, I type M-x helm-google-suggest then I type "example words".
>

No, it seems you don't understand the problem, you are giving a wrong
value to `helm-google-suggest-search-url', that is you have copied the
url from your browser and pasted it in `helm-google-suggest-search-url'.

> schermaf

BTW It seems people habit is now to send screenshots to see what happen,
which is most of the time unuseful, please paste the plain text
backtrace in your messages so that I can read it.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by ReneFroger** [comment]
I noticed the %27 too. 
Earlier I assumed the hexed %27 single quote-sign was put by Google, to replace the single-quote sign to provide a hex value for in search bar. The single-quote was thus the culprit in all of this, after at all. :smile: 

Given your advice, and I just wanted to be sure, I uninstalled Emacs, and started with clean Helm base. So I wonder why you was not just mentioning that. Your formatted string contained the %27 value too. How am I supposedly to know that the string was faulty, and not my configuration. But I should see the difference in the url-unhex-string, by the way. That's true.   

I just thought that any screenshots would help to find all the the details. Good to know that you don't appreciate it. Will put text only messages for now.

And I appreciate your help. I'm gonna donate agian, because the Helm and their support are just awesome. This issue can be considered as closed now.

**Comment by michael-heerdegen** [comment]
Thierry is quite terse most of the time, we have to live with that. After having worked with him for a while, I even fancy this terseness now, but it might be irritating for newbies (and others).

**Comment by ReneFroger** [comment]
Thanks for your tip, Michael. I appreciate it.

**Comment by thierryvolpiatto** [comment]
ReneFroger <notifications@github.com> writes:

> I noticed the %27 too.  Earlier I assumed the hexed %27 single
> quote-sign was put by Google, to replace the single-quote sign to
> provide a hex value for in search bar. The single-quote was thus the
> culprit in all of this, after at all. :sm
>
> Given your advice, and I just wanted to be sure, I uninstalled Emacs,
> and started with clean Helm base. So I wonder why you was not just
> mentioning that. Your formatted string contained the %27 value
> too. How am I supposedly to know that the string was faulty, and not
> my configuration. But I should see the difference in the
> url-unhex-string, by the way. That's true.

To be sure always start with emacs -Q and a minimal setting of helm.
On GNU/Linux we can use emacs-helm.sh for this, on windows it is not
possible but you can create one small helm config based on the content
of emacs-helm.sh and name it helm-cfg.el for example, then you can start
emacs like this:

emacs -Q -l /path/to/helm-cfg.el

> I just thought that any screenshots would help to find all the the
> details. Good to know that you don't appreciate it. Will put text only
> messages for now.

A part of the backtrace is always truncated in screenshot, sometimes it
is not important, but here the most interesting part is hidden.

> And I appreciate your help. I'm gonna donate agian, because the Helm
> and their support are just awesome.

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Thierry is quite terse most of the time, we have to live with
> that. After having worked with him for a while, I even fancy this
> terseness now, but it might be irritating for newbies (and others).

Is it people from the south of France that are terse, or german people
that are more rigourous? :-)

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
I'm not sure.  Most people here in Schwaben (Southwest Germany) are cleaning their house all the time and working in their garden etc.  And they drive cars extremely aggressively because they have so much work to do.  I really wish they would be terse instead.

**Comment by ReneFroger** [comment]
Another little question: 

When I typing words in Helm google suggest, my typing is interrupted with the message 

    error in process filter: Transfer interrupted!

Especially when you're typing fast, or backspacing a whole word. Is there a way to suppress that message? [This issue](http://stackoverflow.com/questions/19949212/emacs-helm-completion-how-to-turn-off-persistent-help-line) might be useful.

**Comment by thierryvolpiatto** [comment]
ReneFroger <notifications@github.com> writes:

> Another little question:
>
> When I typing words in Helm google suggest, my typing is interrupted with the message
>
> error in process filter: Transfer interrupted!

As the message say, the connection closed up for some reason, it is not
reproductible here.
As always, turn on the debugger for more infos.
> Especially when you're typing fast, or backspacing a whole word.

Why are you backspacing a word ???

> Is there a way to suppress that message? This issue might be useful.

This issue is not related to this, thus I saw in your precedent
screencast you were using this area to display the minibuffer contents.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by ReneFroger** [comment]
With backspacing I mean I delete the word with pressing <kbd>Backspace</kbd>. And I couldn't copy the debugger info, because my Emacs froze every time when I get the error. But I was able to make a screenshot, after typing some characters in Helm google.  

![untitled](https://cloud.githubusercontent.com/assets/5211845/9294321/1b1080ca-444a-11e5-9bc7-f3379fa572c0.png)

![image](https://cloud.githubusercontent.com/assets/5211845/9294322/1ee84bce-444a-11e5-91d4-9d60ae255a42.png)

If the info above is not useful for you, please let me know. Thanks in advance.

**Comment by thierryvolpiatto** [comment]
ReneFroger <notifications@github.com> writes:

> With backspacing I mean I delete the word with pressing Backspace. And
> I couldn't copy the debugger info, because my Emacs froze every time
> when I get the error.

Run your emacs under GDB.
GDB is not installed by default on Windoze, you should install it
yourself, it is a good tool to have specially when using emacs on windoze.
Use C-h C-d to learn how to use it.

> But I was able to make a screenshot, after typing some characters in
> Helm google.

Thanks.
This bug is not related to helm but to url.el.
You should report it to emacs bug (Use M-x report-emacs-bug).

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
BTW you can use curl instead of url-retrieve if you have installed curl
on your system and emacs can find it in PATH env var.
To tell helm to do this once curl is properly installed use:

(setq helm-google-suggest-use-curl-p t)

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by ReneFroger** [comment]
Good to read it's not related to Helm, I have the bug reported. I just tested GDB, seem promising. I will test it further. 

I have curl installed in my PATH environment. And yes, with the `(setq helm-google-suggest-use-curl p t)` it worked like charm without any error. Thanks for the support. This issue is solved now.

**Comment by artemyarulin** [comment]
@ReneFroger Thank you! This is awesome idea and it saves a ton of time for me!

**Comment by ReneFroger** [comment]
@artemyarulin Glad to read it! I hope you will enjoy it as me. :smiley: .
