### ISSUE TITLE
helm-mode--in-file-completion-p returns true if a completion candidate or target ends with a forward slash, which breaks completion-at-point in languages where the forward slash is used

### ISSUE THREAD

**Issue by enaeher** [emacs-helm/helm#867]
In Clojure, the forward slash delimits a namespace from a var within that namespace. In Clojure buffers I commonly type something like `log/<M-tab>` to choose among the vars in the log namespace, but with Helm, when I select one of them, `helm-mode--in-file-completion-p` wrongly returns true, which causes Helm to replace the original `log/` with `log/log/some-var` instead of the correct `log/some-var`. I believe this is due to the following code in `helm--completion-in-region`:

```elisp
(delete-region (if (and file-comp-p
                        (save-excursion
                          (re-search-backward "~?/" start t)))
                   (match-end 0) start)
               end)
```

I don't understand the purpose of `helm-mode--in-file-completion-p` here well enough to propose a fix.

**Comment by thierryvolpiatto** [comment]
Sorry for late reply.

Eli Naeher <notifications@github.com> writes:

> In Clojure, the forward slash delimits a namespace from a var within
> that namespace. In Clojure buffers I commonly type something like
> log/<M-tab> to choose among the vars in the log namespace, but with
> Helm, when I select one of them, helm-mode--in-file-completion-p
> wrongly returns true, which causes Helm to replace the original log/
> with log/log/some-var instead of the correct log/some-var. I believe
> this is due to the following code in helm--completion-in-region:
>
> (delete-region (if (and file-comp-p
>                         (save-excursion
>                           (re-search-backward "~?/" start t)))
>                    (match-end 0) start)
>                end)
>
> I don't understand the purpose of helm-mode--in-file-completion-p here well enough to propose a fix.

No need to use clojure to reproduce, I am here using some "tv/" prefixed
function in elisp and I could reproduce your problem, thanks to catch
this.
I have reinforced regexps for fname matching and the regexps should not
match such symbols now, commit following soon.

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
