### ISSUE TITLE
need fix in helm--completion-in-region

### ISSUE THREAD

**Issue by mdraven** [emacs-helm/helm#871]
[helm-mode.el#L981](https://github.com/emacs-helm/helm/blob/b8956755343add909296d7da829da76168b1f955/helm-mode.el#L981)

When `input` is empty, `concat` makes string with one space " ". After that, `helm-comp-read` not complete-at-point, but writes "No matches". `collection` argument of `helm-comp-read` contains elements.

**Comment by thierryvolpiatto** [comment]
Ramil Iljasov <notifications@github.com> writes:

> helm-mode.el#L981
>
> When input is empty, concat makes string with one space " ". After
> that, helm-comp-read not complete-at-point, but writes "No
> matches". collection argument of helm-comp-read contains elements.

completion on nothing (i.e empty input) should return "no matches", that
is the expected behavior and not a bug, you can try in emacs -Q or
without helm-mode turned on, you will have no match.
So this is not a bug.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by mdraven** [comment]
But without helm-mode I have.

I try to use `irony-mode`'s `irony-completion-at-point-async`. The `irony-completion-at-point-async` calls `completion-at-point` to make completion.
If I try to complete "a.|", then `input` is empty and `helm-comp-read` print "No matches". But if I thre to complete "a.r|" and `input` is "r ", then I get "rend", "rbegin", "reverse" and other items.
Without `helm-mode` `irony-completion-at-point-async` completes "a.|". I don't know `helm` architecture, but when I replaced ':initial-input (cond ((and....)' to ':initial-input ""', completion works well.

**Comment by thierryvolpiatto** [comment]
Ramil Iljasov <notifications@github.com> writes:

> But without helm-mode I have.
>
> I try to use irony-mode's irony-completion-at-point-async. The
> irony-completion-at-point-async calls completion-at-point to make
> completion.  If I try to complete "a.|", then input is empty and
> helm-comp-read print "No matches". But if I thre to complete "a.r|"
> and input is "r ", then I get "rend", "rbegin", "reverse" and other
> items.  Without helm-mode irony-completion-at-point-async completes

The reference for helm-mode is emacs -Q behavior, not irony-mode or
whatever third party package.
So the behavior of helm-mode actually is correct.

> "a.|". I don't know helm architecture, but when I replaced
> ':initial-input (cond ((and....)' to ':initial-input ""', completion
> works well.

No, it is not what I want, completion, I mean generally mean completing
against something, so I don't accept empty input for completion.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
