### ISSUE TITLE
How make Helm-ag editable and saving? 

### ISSUE THREAD

**Issue by ReneFroger** [emacs-helm/helm#872]
In Vim, you type :Ag example. Then you see the lines which contains the word 'example' in Quickfix window. Then with Quickfix Reflector, you change the values of each line, and save it back to multiple files. An example:
![agcontent](https://cloud.githubusercontent.com/assets/5211845/6201457/bba1d00a-b4aa-11e4-9d81-807189bc7bea.gif)

 I haven't figured out how to the same with Helm Ag. Could this even be possible?

**Comment by michael-heerdegen** [comment]
helm-ag is not hosted here but there: https://github.com/syohex/emacs-helm-ag

But it doesn't look like it currently supports editing. Anyway, I guess you should better ask that project's maintainer.

**Comment by ReneFroger** [comment]
You're right. It's in the wrong place, I noticed now. 

Thanks for your suggestion.

**Comment by thierryvolpiatto** [comment]
ReneFroger <notifications@github.com> writes:

> I haven't figured out how to the same with Helm Ag. Could this even be possible?

Don't know with helm-ag but here it is supported through Wgrep.
It is supported for grep, ack-grep, git-grep and (m)occur.
You just have to C-x C-s and then C-c C-p edit and when done C-x C-s.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
