### ISSUE TITLE
Compiler warnings

### ISSUE THREAD

**Issue by michael-heerdegen** [emacs-helm/helm#874]
I wonder if we could get rid of the many compiler warnings.
Most warnings are in one of these two classes:

- unknown function.  We could get easily rid of them with declare-function.

- unknown variable (aka "reference to free variable" or "Unused lexical variable").  I'm not sure how to fix this.  defvar is not sufficient in the second case.

I guess to fix the second class warnings, we would have to invest some work, which is maybe not worth it.  Or is there an easy solution (without suppressing warnings with byte-compile-warnings)?

Anyway, getting rid of the warnings would be good so we had a better chance not to oversee the relevant warnings.

**Comment by michael-heerdegen** [comment]
No, defvar helps in all cases I think. Maybe this was different in later builds, or my memories are not correct.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> I wonder if we could get rid of the many compiler warnings.
> Most warnings are in one of these two classes:

Why do you have warnings ?
Unless you compile with emacs-24.3 you should not, I have no warnings
here.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> Why do you have warnings ?
> Unless you compile with emacs-24.3 you should not, I have no warnings
> here.

Not from within the Emacs session when recompiling, but when doing
"make", a whole bunch.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Thierry Volpiatto <notifications@github.com> writes:
>
>> Why do you have warnings ?
>> Unless you compile with emacs-24.3 you should not, I have no warnings
>> here.
>
> Not from within the Emacs session when recompiling, but when doing
> "make", a whole bunch.

I don't understand why you have warnings with "make", I have no warnings
here.
What is your emacs version ?

Here the output of make with emacs-25:

rm -f helm-adaptive.elc helm-aliases.elc helm-apt.elc helm-autoloads.elc helm-bbdb.elc helm-bookmark.elc helm-buffers.elc helm-color.elc helm-command.elc helm-config.elc helm-dabbrev.elc helm.elc helm-elisp.elc helm-elisp-package.elc helm-elscreen.elc helm-emms.elc helm-eshell.elc helm-eval.elc helm-external.elc helm-files.elc helm-firefox.elc helm-font.elc helm-gentoo.elc helm-grep.elc helm-help.elc helm-imenu.elc helm-info.elc helm-locate.elc helm-man.elc helm-match-plugin.elc helm-misc.elc helm-mode.elc helm-net.elc helm-org.elc helm-pkg.elc helm-plugin.elc helm-regexp.elc helm-ring.elc helm-semantic.elc helm-source.elc helm-sys.elc helm-tags.elc helm-utils.elc helm-w3m.elc helm-yaoddmuse.elc
emacs -Q -batch --eval "(let ((generated-autoload-file (expand-file-name \"helm-autoloads.el\" \".\")) \
(backup-inhibited t)) (update-directory-autoloads \".\"))"
emacs -Q -batch -L . -f batch-byte-compile helm-adaptive.el helm-aliases.el helm-apt.el helm-autoloads.el helm-bbdb.el helm-bookmark.el helm-buffers.el helm-color.el helm-command.el helm-config.el helm-dabbrev.el helm.el helm-elisp.el helm-elisp-package.el helm-elscreen.el helm-emms.el helm-eshell.el helm-eval.el helm-external.el helm-files.el helm-firefox.el helm-font.el helm-gentoo.el helm-grep.el helm-help.el helm-imenu.el helm-info.el helm-locate.el helm-man.el helm-match-plugin.el helm-misc.el helm-mode.el helm-net.el helm-org.el helm-pkg.el helm-plugin.el helm-regexp.el helm-ring.el helm-semantic.el helm-source.el helm-sys.el helm-tags.el helm-utils.el helm-w3m.el helm-yaoddmuse.el
ad-handle-definition: `tramp-read-passwd' got redefined

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Thierry Volpiatto <notifications@github.com> writes:
>
>> Why do you have warnings ?
>> Unless you compile with emacs-24.3 you should not, I have no warnings
>> here.
>
> Not from within the Emacs session when recompiling, but when doing
> "make", a whole bunch.

I have just checked in your helm branch and compiled it with make with
no warnings (emacs-25).

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Not from within the Emacs session when recompiling, but when doing
> "make", a whole bunch.

And it seems your helm copy is not updated.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
No, I use only temporary branches, I tried with master, of course.  Here is what I get:

```
rm -f helm-utils.elc helm-locate.elc helm-autoloads.elc helm-eval.elc helm-yaoddmuse.elc helm-plugin.elc helm-semantic.elc helm-grep.elc helm-gentoo.elc helm-aliases.elc helm-adaptive.elc helm-elisp-package.elc helm-w3m.elc helm-match-plugin.elc helm-ring.elc helm-sys.elc helm-pkg.elc helm-dabbrev.elc helm-elisp.elc helm-imenu.elc helm-org.elc helm-color.elc helm-command.elc helm-font.elc helm-bbdb.elc helm-bookmark.elc helm-net.elc helm-tags.elc helm-source.elc helm-config.elc helm-emms.elc helm-regexp.elc helm-elscreen.elc helm-external.elc helm.elc helm-eshell.elc helm-mode.elc helm-misc.elc helm-help.elc helm-files.elc helm-firefox.elc helm-apt.elc helm-buffers.elc helm-man.elc helm-info.elc
emacs -Q -batch --eval "(let ((generated-autoload-file (expand-file-name \"helm-autoloads.el\" \".\")) \
(backup-inhibited t)) (update-directory-autoloads \".\"))"
emacs -Q -batch -L . -f batch-byte-compile helm-utils.el helm-locate.el helm-autoloads.el helm-eval.el helm-yaoddmuse.el helm-plugin.el helm-semantic.el helm-grep.el helm-gentoo.el helm-aliases.el helm-adaptive.el helm-elisp-package.el helm-w3m.el helm-match-plugin.el helm-ring.el helm-sys.el helm-pkg.el helm-dabbrev.el helm-elisp.el helm-imenu.el helm-org.el helm-color.el helm-command.el helm-font.el helm-bbdb.el helm-bookmark.el helm-net.el helm-tags.el helm-source.el helm-config.el helm-emms.el helm-regexp.el helm-elscreen.el helm-external.el helm.el helm-eshell.el helm-mode.el helm-misc.el helm-help.el helm-files.el helm-firefox.el helm-apt.el helm-buffers.el helm-man.el helm-info.el

In helm-quit-and-find-file:
helm-utils.el:419:34:Warning: reference to free variable
    `helm-ff-transformer-show-only-basename'
helm-utils.el:427:52:Warning: reference to free variable `bookmark-alist'
helm-utils.el:438:23:Warning: reference to free variable `org-directory'
helm-utils.el:443:50:Warning: reference to free variable `ffap-url-regexp'

In helm-ff-get-host-from-tramp-invalid-fname:
helm-utils.el:562:54:Warning: reference to free variable `tramp-methods'

In end of data:
helm-utils.el:967:1:Warning: the following functions are not known to be
    defined: org-reveal, helm-grep-split-line, bookmark-get-filename

In helm-ff-find-locatedb:
helm-locate.el:126:17:Warning: reference to free variable
    `helm-ff-default-directory'

In helm-locate-1:
helm-locate.el:158:36:Warning: reference to free variable
    `helm-ff-default-directory'
helm-locate.el:196:1:Warning: Unused lexical variable `helm-ff-transformer-show-only-basename'
helm-locate.el:298:1:Warning: Unused lexical variable `helm-ff-transformer-show-only-basename'

In helm-locate:
helm-locate.el:333:9:Warning: assignment to free variable
    `helm-ff-default-directory'

In end of data:
helm-locate.el:345:1:Warning: the function `helm-read-file-name' is not known
    to be defined.

In helm-grep--prepare-cmd-line:
helm-grep.el:334:51:Warning: reference to free variable
    `helm-ff-default-directory'
helm-grep.el:376:1:Warning: Unused lexical variable `tramp-verbose'

In helm-grep-init:
helm-grep.el:378:51:Warning: reference to free variable
    `helm-ff-default-directory'
helm-grep.el:383:25:Warning: reference to free variable `helm-tramp-verbose'

In helm-grep-action:
helm-grep.el:472:43:Warning: reference to free variable
    `helm-ff-default-directory'

In helm-grep-ack-types-transformer:
helm-grep.el:758:27:Warning: reference to free variable
    `helm-grep-ack-types-cache'

In helm-do-grep-1:
helm-grep.el:836:14:Warning: reference to free variable
    `helm-ff-default-directory'
helm-grep.el:913:25:Warning: assignment to free variable
    `helm-ff-default-directory'

In helm-ff-zgrep-1:
helm-grep.el:925:28:Warning: reference to free variable
    `helm-ff-default-directory'

In helm-grep-filter-one-by-one:
helm-grep.el:981:29:Warning: reference to free variable
    `helm-ff-default-directory'
helm-grep.el:1013:1:Warning: Unused lexical variable `helm-ff-default-directory'

In helm-grep-buffers-1:
helm-grep.el:1021:11:Warning: reference to free variable
    `helm-ff-default-directory'

In helm-pdfgrep-init:
helm-grep.el:1064:33:Warning: reference to free variable
    `helm-ff-default-directory'

In helm-do-grep:
helm-grep.el:1166:40:Warning: reference to free variable
    `helm-ff-transformer-show-only-basename'

In helm-do-zgrep:
helm-grep.el:1184:35:Warning: reference to free variable
    `helm-ff-transformer-show-only-basename'

In helm-do-pdfgrep:
helm-grep.el:1204:37:Warning: reference to free variable
    `helm-ff-transformer-show-only-basename'

In end of data:
helm-grep.el:1220:1:Warning: the following functions are not known to be
    defined: helm-comp-read, helm-read-file-name

In helm-gentoo-install:
helm-gentoo.el:89:9:Warning: assignment to free variable
    `helm-external-commands-list'

In helm-el-package-upgrade-all:
helm-elisp-package.el:178:9:Warning: reference to free variable
    `helm-marked-buffer-name'
ad-handle-definition: `tramp-read-passwd' got redefined

In end of data:
helm-elisp.el:830:1:Warning: the function `helm-read-file-name' is not known
    to be defined.
```
rm -f helm-utils.elc helm-locate.elc helm-autoloads.elc helm-eval.elc helm-yaoddmuse.elc helm-plugin.elc helm-semantic.elc helm-grep.elc helm-gentoo.elc helm-aliases.elc helm-adaptive.elc helm-elisp-package.elc helm-w3m.elc helm-match-plugin.elc helm-ring.elc helm-sys.elc helm-pkg.elc helm-dabbrev.elc helm-elisp.elc helm-imenu.elc helm-org.elc helm-color.elc helm-command.elc helm-font.elc helm-bbdb.elc helm-bookmark.elc helm-net.elc helm-tags.elc helm-source.elc helm-config.elc helm-emms.elc helm-regexp.elc helm-elscreen.elc helm-external.elc helm.elc helm-eshell.elc helm-mode.elc helm-misc.elc helm-help.elc helm-files.elc helm-firefox.elc helm-apt.elc helm-buffers.elc helm-man.elc helm-info.elc
emacs -Q -batch --eval "(let ((generated-autoload-file (expand-file-name \"helm-autoloads.el\" \".\")) \
(backup-inhibited t)) (update-directory-autoloads \".\"))"
emacs -Q -batch -L . -f batch-byte-compile helm-utils.el helm-locate.el helm-autoloads.el helm-eval.el helm-yaoddmuse.el helm-plugin.el helm-semantic.el helm-grep.el helm-gentoo.el helm-aliases.el helm-adaptive.el helm-elisp-package.el helm-w3m.el helm-match-plugin.el helm-ring.el helm-sys.el helm-pkg.el helm-dabbrev.el helm-elisp.el helm-imenu.el helm-org.el helm-color.el helm-command.el helm-font.el helm-bbdb.el helm-bookmark.el helm-net.el helm-tags.el helm-source.el helm-config.el helm-emms.el helm-regexp.el helm-elscreen.el helm-external.el helm.el helm-eshell.el helm-mode.el helm-misc.el helm-help.el helm-files.el helm-firefox.el helm-apt.el helm-buffers.el helm-man.el helm-info.el

In helm-quit-and-find-file:
helm-utils.el:419:34:Warning: reference to free variable
    `helm-ff-transformer-show-only-basename'
helm-utils.el:427:52:Warning: reference to free variable `bookmark-alist'
helm-utils.el:438:23:Warning: reference to free variable `org-directory'
helm-utils.el:443:50:Warning: reference to free variable `ffap-url-regexp'

In helm-ff-get-host-from-tramp-invalid-fname:
helm-utils.el:562:54:Warning: reference to free variable `tramp-methods'

In end of data:
helm-utils.el:967:1:Warning: the following functions are not known to be
    defined: org-reveal, helm-grep-split-line, bookmark-get-filename

In helm-ff-find-locatedb:
helm-locate.el:126:17:Warning: reference to free variable
    `helm-ff-default-directory'

In helm-locate-1:
helm-locate.el:158:36:Warning: reference to free variable
    `helm-ff-default-directory'
helm-locate.el:196:1:Warning: Unused lexical variable `helm-ff-transformer-show-only-basename'
helm-locate.el:298:1:Warning: Unused lexical variable `helm-ff-transformer-show-only-basename'

In helm-locate:
helm-locate.el:333:9:Warning: assignment to free variable
    `helm-ff-default-directory'

In end of data:
helm-locate.el:345:1:Warning: the function `helm-read-file-name' is not known
    to be defined.

In helm-grep--prepare-cmd-line:
helm-grep.el:334:51:Warning: reference to free variable
    `helm-ff-default-directory'
helm-grep.el:376:1:Warning: Unused lexical variable `tramp-verbose'

In helm-grep-init:
helm-grep.el:378:51:Warning: reference to free variable
    `helm-ff-default-directory'
helm-grep.el:383:25:Warning: reference to free variable `helm-tramp-verbose'

In helm-grep-action:
helm-grep.el:472:43:Warning: reference to free variable
    `helm-ff-default-directory'

In helm-grep-ack-types-transformer:
helm-grep.el:758:27:Warning: reference to free variable
    `helm-grep-ack-types-cache'

In helm-do-grep-1:
helm-grep.el:836:14:Warning: reference to free variable
    `helm-ff-default-directory'
helm-grep.el:913:25:Warning: assignment to free variable
    `helm-ff-default-directory'

In helm-ff-zgrep-1:
helm-grep.el:925:28:Warning: reference to free variable
    `helm-ff-default-directory'

In helm-grep-filter-one-by-one:
helm-grep.el:981:29:Warning: reference to free variable
    `helm-ff-default-directory'
helm-grep.el:1013:1:Warning: Unused lexical variable `helm-ff-default-directory'

In helm-grep-buffers-1:
helm-grep.el:1021:11:Warning: reference to free variable
    `helm-ff-default-directory'

In helm-pdfgrep-init:
helm-grep.el:1064:33:Warning: reference to free variable
    `helm-ff-default-directory'

In helm-do-grep:
helm-grep.el:1166:40:Warning: reference to free variable
    `helm-ff-transformer-show-only-basename'

In helm-do-zgrep:
helm-grep.el:1184:35:Warning: reference to free variable
    `helm-ff-transformer-show-only-basename'

In helm-do-pdfgrep:
helm-grep.el:1204:37:Warning: reference to free variable
    `helm-ff-transformer-show-only-basename'

In end of data:
helm-grep.el:1220:1:Warning: the following functions are not known to be
    defined: helm-comp-read, helm-read-file-name

In helm-gentoo-install:
helm-gentoo.el:89:9:Warning: assignment to free variable
    `helm-external-commands-list'

In helm-el-package-upgrade-all:
helm-elisp-package.el:178:9:Warning: reference to free variable
    `helm-marked-buffer-name'
ad-handle-definition: `tramp-read-passwd' got redefined

In end of data:
helm-elisp.el:830:1:Warning: the function `helm-read-file-name' is not known
    to be defined.
```

(emacs-version) ==> "GNU Emacs 25.0.50.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.14.5)\n of 2015-02-06 on drachen"

I guess the difference between you and me is just the order in which the files are compiled, which is probably system dependent.

**Comment by michael-heerdegen** [comment]
Master of your repo, of course.  I use my clone only for pull requests, not persistently.

**Comment by michael-heerdegen** [comment]
And I use the master branch of your remote as parent for my fix branches, I don't use the master branch of my clone at all.  After having done the PR, I always checkout master of your remote... So, everything should be ok with my setup.

**Comment by HKey** [comment]
Hi, I got some warnings too.
I'm using emacs-24.4.

> I guess the difference between you and me is just the order in which the files are compiled, which is probably system dependent.

I think so, because I guess `byte-compile-file` evaluates `require` forms while compilation by `byte-compile-file-form-require`.

@thierryvolpiatto Would you check `make compile`?

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> I guess the difference between you and me is just the order in which
> the files are compiled, which is probably system dependent.

What is the value of $SHELL where you run make ?

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> emacs -Q -batch -L . -f batch-byte-compile helm-utils.el helm-locate.el helm-autoloads.el helm-eval.el helm-yaoddmuse.el helm-plugin.el helm-semantic.el helm-grep.el helm-gentoo.el helm-aliases.el helm-adaptive.el helm-elisp-package.el helm-w3m.el helm-match-plugin.el helm-ring.el helm-sys.el helm-pkg.el helm-dabbrev.el helm-elisp.el helm-imenu.el helm-org.el helm-color.el helm-command.el helm-font.el helm-bbdb.el helm-bookmark.el helm-net.el helm-tags.el helm-source.el helm-config.el helm-emms.el helm-regexp.el helm-elscreen.el helm-external.el helm.el helm-eshell.el helm-mode.el helm-misc.el helm-help.el helm-files.el helm-firefox.el helm-apt.el helm-buffers.el helm-man.el helm-info.el

Your files here should be sorted alphabetically, they are here.

What if instead of "make", you run "sh -c make" ?

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Should be fixed now, feel free to reopen if you still have warnings.

**Comment by michael-heerdegen** [comment]
That works, thanks.  My shell is fish, btw.  It is not sh compatible.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> That works, thanks. My shell is fish, btw. It is not sh compatible.

Probably it is the reason why wilcard is not sorted, I guess
"echo *.el" is not sorted too ?

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
No, that is perfectly sorted in fish.

How does make resolve the "$(wildcard helm*.el)" in the makefile? I don't have any binary named wildcard installed.  Is there a shell involved at all?

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> No, that is perfectly sorted in fish.

So I don't know why `wilcard' doesn't sort files.

> How does make resolve the "$(wildcard helm*.el)" in the makefile? I
> don't have any binary named wildcard installed. Is there a shell
> involved at all?

IIUC the documentation of make, it's an internal make function.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
The make documentation doesn't say anything about order when "wildcard" is used. So it's probably not an issue with my shell.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> The make documentation doesn't say anything about order when
> "wildcard" is used. So it's probably not an issue with my shell.

Hmm, I would like to know though why your files are not sorted.

Did you try with "bash -c make" or "sh -c make" ?
(with only wildcard in makefile of course)

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> Did you try with "bash -c make" or "sh -c make" ?
> (with only wildcard in makefile of course)

I always get a non-sorted order.  No matter if I run make outside Emacs
or inside, and with any shell I tried.

But hey, now I tried to downgrade make from testing to stable, and the
order is alphabetically now.  So it is an issue with the make version in
the testing repo - though I don't know whether it's a bug, or if the
order is just unspecified, and has recently changed.

**Comment by michael-heerdegen** [comment]
This page says it's expected, and suggests to do what we did to fix the problem: http://docs.electric-cloud.com/accelerator_doc/7_1/Mobile/eMake/Advanced/Content/emake%20Guide/5_Make_Compatibility/8_Wildcard_Sort_Order.htm

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> This page says it's expected, and suggests to do what we did to fix the problem: 
> http://docs.electric-cloud.com/accelerator_doc/7_1/Mobile/eMake/Advanced/Content/emake%20Guide/5_Make_Compatibility/8_Wildcard_Sort_Order.htm

Good to know, I was not aware of other existing versions of Make,

thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
HKey <notifications@github.com> writes:

> I think so, because I guess byte-compile-file evaluates require forms
> while compilation by byte-compile-file-form-require.

Indeed.

> @thierryvolpiatto Would you check make compile?

Yes we will still have warnings when using "make compile", to fix this I
would have to allow each helm library to compile alone, this is a
headache to fix all the resursive requires.
I will probably fix this when separating core helm from the rest of helm
libraries.
For now you better have not using "compile".

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by HKey** [comment]
Thank you for your reply!

> Yes we will still have warnings when using "make compile", to fix this I would have to allow each helm library to compile alone, this is a headache to fix all the resursive requires. I will probably fix this when separating core helm from the rest of helm libraries. For now you better have not using "compile".

OK, I'll wait for warnings to be fixed.
