### ISSUE TITLE
Allow to customize whether to open other window horizontal or vertically

### ISSUE THREAD

**Issue by tuhdo** [emacs-helm/helm#875]
When opening two files, two horizontal windows are created. However, what I really want is two vertical windows. It would be better if this can be customized, and make the vertical opening default. I'm currently have to delete a window and create another vertical window every time I open two or more files.

**Comment by thierryvolpiatto** [comment]
I am actually reusing a dired function for files, which doesn't support what you want, to implement what you want I will have to rewrite this dired function...
Not a big motivation for now, will see later...

**Comment by thierryvolpiatto** [comment]
I think what we have actually is enough, what you probably need is a function to split a set of horizontal buffers vertically and the contrary.
Closing.

**Comment by michael-heerdegen** [comment]
I think it's already easy enough to (advice-add 'helm-split-window-default-fn ...), that would be five lines or so.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> I think it's already easy enough to (advice-add
> 'helm-split-window-default-fn ...), that would be five lines or so.

No `helm-split-window-default-fn' have nothing to do with this.


-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
Sorry, I misread what tuhdo meant.

We call dired-simultaneous-find-file, which doesn't support vertical splitting.  So, actually, this is an Emacs issue, it would have to be fixed in dired.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Sorry, I misread what tuhdo meant.
>
> We call dired-simultaneous-find-file, which doesn't support vertical
> splitting.

Which is perfectly fine, up to user to switch this set of horizontal
windows to a vertical one if she want.

Note that for buffers we don't use this function (we have our own function).

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
