### ISSUE TITLE
ffap getting in the way

### ISSUE THREAD

**Issue by jdahm** [emacs-helm/helm#876]
Originally posted on emacs-helm group:

I like this occasionally when I'm editing code and there's a clear reference to another file, but other times it gets in the way. Is there a command I can bind to a key to go back to where it would look first without the context-specific search (which is presumably the directory of the file the active buffer is based on)? I've searched with customize-group and looked for similar sounding commands with M-x but have had no luck so far.

**Comment by thierryvolpiatto** [comment]
Type "/./" at end of pattern.

**Comment by jdahm** [comment]
Ah, great. Sorry, I didn't understand that on the group thread at the time. I thought that just took me back to / but it indeed takes me to the default directory as I wanted. Thanks!
