### ISSUE TITLE
helm-buffers-list: make @ and * commutative

### ISSUE THREAD

**Issue by michael-heerdegen** [emacs-helm/helm#880]
Hi,

no big deal, but I had to find this out cause it's a bit unexpected:

"*lisp @string" works, "@string *lisp" doesn't.  I think it would be better if both would work the same way.

With other words: allow an @ or * specification at any place in the input, and treat them regardless of their position.

Thanks!

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Hi,
>
> no big deal, but I had to find this out cause it's a bit unexpected:
>
> "*lisp @string" works, "@string *lisp" doesn't. I think it would be
> better if both would work the same way.
>
> With other words: allow an @ or * specification at any place in the
> input, and treat them regardless of their position.

Same problem with "/", I am aware of this...

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
This have been fixed, I forget to link the commits though...

**Comment by michael-heerdegen** [comment]
And i didn't identify the commit as belonging to this issue.

But it works well now, many thanks!
