### ISSUE TITLE
Partial incompatibility with org-contacts contact lists

### ISSUE THREAD

**Issue by WorldsEndless** [emacs-helm/helm#881]
In former version of Helm, I had no problems with compatibility with org-contacts[1], which I use in conjunctino with Gnus to auto-complete addressee fields. Even now the completion for a single name in one of my To: columns works fine. However, I also rely upon a function of org-contacts whereby starting with "+<CATEGORY>" and pressing tab will autofill the field with all addresses belonging to that category; essentially, this allows me to make contact lists. But this no longer works in conjunction with Helm. I receive the following error: 

    completion-in-region: Wrong type argument: listp, #("Testerly <test@test.com>, Testerness <testerness@test.com>, Testednot <testednot@test.com>" 0 8 (fontified t org-category "contacts" face org-level-1) 26 36 (fontified t org-category "contacts" face org-level-1) 60 69 (fontified t org-category "contacts" face org-level-1))

As far as I can tell, it's conflicting with the function `org-contacts-message-complete-function` shown below. I'm guessing helm is intercepting some part of the command chain and altering the output. Neither uninstalling Helm nor uninstalling org-contacts are desirable solutions for me; can anyone help me get this working again? 

--8<---------------cut here---------------start------------->8---
(defun org-contacts-message-complete-function (&optional start)
  "Function used in `completion-at-point-functions' in `message-mode'."
  ;; Avoid to complete in `post-command-hook'.
  (when completion-in-region-mode
    (remove-hook 'post-command-hook #'completion-in-region--postch))
  (let ((mail-abbrev-mode-regexp
         "^\\(Resent-To\\|To\\|B?Cc\\|Reply-To\\|From\\|Mail-Followup-To\\|Mail-Copies-To\\|Disposition-Notification-To\\|Return-Receipt-To\\):"))
    (when (mail-abbrev-in-expansion-header-p)
      (lexical-let*
	  ((end (point))
	   (start (or start
		      (save-excursion
			(re-search-backward "\\(\\`\\|[\n:,]\\)[ \t]*")
			(goto-char (match-end 0))
			(point))))
	   (string (buffer-substring start end)))
	(or (org-contacts-complete-group start end string)
	    (org-contacts-complete-name start end string))))))
--8<---------------cut here---------------end--------------->8---

Footnotes: 
[1]  https://julien.danjou.info/projects/emacs-packages#org-contacts

**Comment by thierryvolpiatto** [comment]
Tory S. Anderson <notifications@github.com> writes:

> In former version of Helm,

What was this version (or when).

> I had no problems with compatibility with org-contacts[1], which I use
> in conjunctino with Gnus to auto-complete addressee fields. Even now
> the completion for a single name in one of my To: columns works
> fine. However, I also rely upon a function of org-contacts whereby
> starting with "+" and pressing tab will autofill the field with all
> addresses belonging to that category; essentially, this allows me to
> make contact lists. But this no longer works in conjunction with
> Helm. I receive the following error:

Can you provide a full backtrace? 
Also is it working with helm-mode disabled ?

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by WorldsEndless** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> Tory S. Anderson <notifications@github.com> writes:
>
>> In former version of Helm,
>
> What was this version (or when).
Until recenlty I was running emacs 24.3, and the latest helm that was still compatible with that one offered no problems with this functionality. 

>
>> I had no problems with compatibility with org-contacts[1], which I
> use
>> in conjunctino with Gnus to auto-complete addressee fields. Even
> now
>> the completion for a single name in one of my To: columns works
>> fine. However, I also rely upon a function of org-contacts whereby
>> starting with "+" and pressing tab will autofill the field with all
>> addresses belonging to that category; essentially, this allows me
> to
>> make contact lists. But this no longer works in conjunction with
>> Helm. I receive the following error:
>
> Can you provide a full backtrace?
Hmm... I'd love to. I'm a bit new to this, though; how can I provide a full backtrace? 

> Also is it working with helm-mode disabled ?
Yeah, it works when I use emacs -Q (and selectively evaluate things), or when I remove my helm config settings.

**Comment by michael-heerdegen** [comment]
Providing a backtrace is easy: Load all the involved source files (e.g. with L from dired; it is important to load the uncompiled files to get a readable backtrace), enable debug-on-error: M-: (setq debug-on-error t) RET, and perform your recipe.  Send us the popped up backtrace.

Even more helpful would be a recipe that would allow us to reproduce the problem easily.  Starting from helm.sh preferably.  Thanks!

**Comment by WorldsEndless** [comment]
Ok,  here's the backtrace: 
Debugger entered--Lisp error: (wrong-type-argument listp #("Testerly <test@test.com>, Testerness <testerness@test.com>, Testednot <testednot@test.com>" 0 8 (fontified nil org-category "contacts") 26 36 (fontified nil org-category "contacts") 60 69 (fontified nil org-category "contacts")))
  helm--completion-in-region(#<marker at 5 in *unsent mail*> 10 (lambda (&rest --cl-rest--) (apply (quote (lambda (G47606 string pred &optional to-ignore) (mapconcat (quote identity) (let* ((--cl-var-- ...) (contact nil) (contact-name nil) (email nil) (--cl-var-- nil)) (while (consp --cl-var--) (setq contact ...) (setq contact-name ...) (setq email ...) (if email ...) (setq --cl-var-- ...)) (nreverse --cl-var--)) ", "))) (quote --tag--) --cl-rest--)) nil)
  completion-in-region(#<marker at 5 in *unsent mail*> 10 (lambda (&rest --cl-rest--) (apply (quote (lambda (G47606 string pred &optional to-ignore) (mapconcat (quote identity) (let* ((--cl-var-- ...) (contact nil) (contact-name nil) (email nil) (--cl-var-- nil)) (while (consp --cl-var--) (setq contact ...) (setq contact-name ...) (setq email ...) (if email ...) (setq --cl-var-- ...)) (nreverse --cl-var--)) ", "))) (quote --tag--) --cl-rest--)) nil)
  completion-at-point()
  message-tab()
  funcall-interactively(message-tab)
  call-interactively(message-tab)
  (progn (call-interactively func))
  (if func (progn (call-interactively func)))
  (when func (call-interactively func))
  (let ((func (or binding (unless disable (quote orgstruct-error))))) (when func (call-interactively func)))
  (if (keymapp binding) (org-set-transient-map binding) (let ((func (or binding (unless disable (quote orgstruct-error))))) (when func (call-interactively func))))
  (let* ((orgstruct-mode) (binding (let ((key [tab])) (catch (quote exit) (dolist (rep (quote ...) nil) (when rep (setq key ...)) (when (key-binding key) (throw ... ...))))))) (if (keymapp binding) (org-set-transient-map binding) (let ((func (or binding (unless disable (quote orgstruct-error))))) (when func (call-interactively func)))))
  (if fallback (let* ((orgstruct-mode) (binding (let ((key [tab])) (catch (quote exit) (dolist (rep ... nil) (when rep ...) (when ... ...)))))) (if (keymapp binding) (org-set-transient-map binding) (let ((func (or binding (unless disable ...)))) (when func (call-interactively func))))) (org-run-like-in-org-mode (lambda nil (interactive) (let* ((org-heading-regexp (concat "^" orgstruct-heading-prefix-regexp "\\(\\*+\\)\\(?: +\\(.*?\\)\\)?[		]*$")) (org-outline-regexp (concat orgstruct-heading-prefix-regexp "\\*+ ")) (org-outline-regexp-bol (concat "^" org-outline-regexp)) (outline-regexp org-outline-regexp) (outline-heading-end-regexp "\n") (outline-level (quote org-outline-level)) (outline-heading-alist)) (call-interactively (quote org-cycle))))))
  (let* ((disable nil) (fallback (or disable (not (let* ((org-heading-regexp ...) (org-outline-regexp ...) (org-outline-regexp-bol ...) (outline-regexp org-outline-regexp) (outline-heading-end-regexp "\n") (outline-level ...) (outline-heading-alist)) (org-context-p (quote headline) (quote item) nil)))))) (if fallback (let* ((orgstruct-mode) (binding (let ((key [tab])) (catch (quote exit) (dolist ... ... ...))))) (if (keymapp binding) (org-set-transient-map binding) (let ((func (or binding ...))) (when func (call-interactively func))))) (org-run-like-in-org-mode (lambda nil (interactive) (let* ((org-heading-regexp (concat "^" orgstruct-heading-prefix-regexp "\\(\\*+\\)\\(?: +\\(.*?\\)\\)?[		]*$")) (org-outline-regexp (concat orgstruct-heading-prefix-regexp "\\*+ ")) (org-outline-regexp-bol (concat "^" org-outline-regexp)) (outline-regexp org-outline-regexp) (outline-heading-end-regexp "\n") (outline-level (quote org-outline-level)) (outline-heading-alist)) (call-interactively (quote org-cycle)))))))
  orgstruct-hijacker-org-cycle-4(1)
  funcall-interactively(orgstruct-hijacker-org-cycle-4 1)
  call-interactively(orgstruct-hijacker-org-cycle-4 nil nil)
  command-execute(orgstruct-hijacker-org-cycle-4)

Recipe for duplication: 
1. download and unpack minimal files for problem reduplication: http://toryanderson.com/files/helm.zip
2. Start helm.sh
3. Navigate to where you unpacked the files, and evaluate config.el
4. `C-x m` to create a new message; in the "To:" field type "+t" and <TAB> to finish the list of names. 

You will now see the error.

**Comment by michael-heerdegen** [comment]
Thanks, I can reproduce it.

@thierryvolpiatto The problem is that all-completions doesn't return a list but a string which helm doesn't expect:

```
Debugger entered--Lisp error: (wrong-type-argument listp #("Testerly <test@test.com>, Testerness <testerness@test.com>, Testednot <testednot@test.com>" 0 8 (fontified t face org-level-1 org-category #1="contacts") 26 36 (fontified t face org-level-1 org-category #1#) 60 69 (fontified t face org-level-1 org-category #1#)))
  car(#("Testerly <test@test.com>, Testerness <testerness@test.com>, Testednot <testednot@test.com>" 0 8 (fontified t face org-level-1 org-category #1="contacts") 26 36 (fontified t face org-level-1 org-category #1#) 60 69 (fontified t face org-level-1 org-category #1#)))
  (helm-mode--in-file-completion-p input (car data))
  (let* ((enable-recursive-minibuffers t) (input (buffer-substring-no-properties start end)) (current-command (or (helm-this-command) this-command)) (str-command (symbol-name current-command)) (buf-name (format "*helm-mode-%s*" str-command)) (require-match (or (and (boundp (quote require-match)) require-match) minibuffer-completion-confirm (not (boundp (quote prompt))))) (afun (plist-get completion-extra-properties :annotation-function)) (data (all-completions input collection predicate)) (init-space-suffix (if helm-completion-in-region-fuzzy-match nil " ")) (file-comp-p (helm-mode--in-file-completion-p input (car data))) (result (helm-comp-read (or (and (boundp (quote prompt)) prompt) "Pattern: ") (if file-comp-p (let* ((#1=#:--cl-var-- data) (f nil) (#2=#:--cl-var-- nil)) (while (consp #1#) (setq f ...) (if ... ... ...) (setq #1# ...)) (nreverse #2#)) (if afun (mapcar (function ...) data) data)) :name str-command :fuzzy helm-completion-in-region-fuzzy-match :nomark t :initial-input (cond ((and file-comp-p (not ...)) (concat (helm-basename input) (if ... nil init-space-suffix))) ((string-match "/\\'" input) nil) ((or (null require-match) (stringp require-match)) input) (t (concat input init-space-suffix))) :buffer buf-name :fc-transformer (append (list (quote helm-cr-default-transformer)) (list (function (lambda ... ...)))) :exec-when-only-one t :quit-when-no-cand (function (lambda nil (run-with-timer 0.01 nil (function ...)) t)) :must-match require-match))) (if result (progn (delete-region (if (and file-comp-p (save-excursion (re-search-backward "~?/" start t))) (match-end 0) start) end) (insert (if file-comp-p (shell-quote-argument result) result)))))
  (unwind-protect (let* ((enable-recursive-minibuffers t) (input (buffer-substring-no-properties start end)) (current-command (or (helm-this-command) this-command)) (str-command (symbol-name current-command)) (buf-name (format "*helm-mode-%s*" str-command)) (require-match (or (and (boundp (quote require-match)) require-match) minibuffer-completion-confirm (not (boundp (quote prompt))))) (afun (plist-get completion-extra-properties :annotation-function)) (data (all-completions input collection predicate)) (init-space-suffix (if helm-completion-in-region-fuzzy-match nil " ")) (file-comp-p (helm-mode--in-file-completion-p input (car data))) (result (helm-comp-read (or (and (boundp ...) prompt) "Pattern: ") (if file-comp-p (let* (... ... ...) (while ... ... ... ...) (nreverse #2=#:--cl-var--)) (if afun (mapcar ... data) data)) :name str-command :fuzzy helm-completion-in-region-fuzzy-match :nomark t :initial-input (cond ((and file-comp-p ...) (concat ... ...)) ((string-match "/\\'" input) nil) ((or ... ...) input) (t (concat input init-space-suffix))) :buffer buf-name :fc-transformer (append (list (quote helm-cr-default-transformer)) (list (function ...))) :exec-when-only-one t :quit-when-no-cand (function (lambda nil (run-with-timer 0.01 nil ...) t)) :must-match require-match))) (if result (progn (delete-region (if (and file-comp-p (save-excursion ...)) (match-end 0) start) end) (insert (if file-comp-p (shell-quote-argument result) result))))) (advice-remove (quote lisp--local-variables) (function helm-mode--advice-lisp--local-variables)))
  (if (memq major-mode helm-mode-no-completion-in-region-in-modes) (funcall helm--old-completion-in-region-function start end collection predicate) (advice-add (quote lisp--local-variables) :around (function helm-mode--advice-lisp--local-variables)) (unwind-protect (let* ((enable-recursive-minibuffers t) (input (buffer-substring-no-properties start end)) (current-command (or (helm-this-command) this-command)) (str-command (symbol-name current-command)) (buf-name (format "*helm-mode-%s*" str-command)) (require-match (or (and (boundp ...) require-match) minibuffer-completion-confirm (not (boundp ...)))) (afun (plist-get completion-extra-properties :annotation-function)) (data (all-completions input collection predicate)) (init-space-suffix (if helm-completion-in-region-fuzzy-match nil " ")) (file-comp-p (helm-mode--in-file-completion-p input (car data))) (result (helm-comp-read (or (and ... prompt) "Pattern: ") (if file-comp-p (let* ... ... ...) (if afun ... data)) :name str-command :fuzzy helm-completion-in-region-fuzzy-match :nomark t :initial-input (cond (... ...) (... nil) (... input) (t ...)) :buffer buf-name :fc-transformer (append (list ...) (list ...)) :exec-when-only-one t :quit-when-no-cand (function (lambda nil ... t)) :must-match require-match))) (if result (progn (delete-region (if (and file-comp-p ...) (match-end 0) start) end) (insert (if file-comp-p (shell-quote-argument result) result))))) (advice-remove (quote lisp--local-variables) (function helm-mode--advice-lisp--local-variables))))
  helm--completion-in-region(#<marker at 5 in *unsent mail*<2>> 7 (lambda (&rest --cl-rest--) (apply (quote (lambda (#1=#:G9603 string pred &optional to-ignore) (mapconcat (quote identity) (let* ((#2=#:--cl-var-- ...) (contact nil) (contact-name nil) (email nil) (#3=#:--cl-var-- nil)) (while (consp #2#) (setq contact ...) (setq contact-name ...) (setq email ...) (if email ...) (setq #2# ...)) (nreverse #3#)) ", "))) (quote #:--tag--) --cl-rest--)) nil)
  completion-in-region(#<marker at 5 in *unsent mail*<2>> 7 (lambda (&rest --cl-rest--) (apply (quote (lambda (#1=#:G9603 string pred &optional to-ignore) (mapconcat (quote identity) (let* ((#2=#:--cl-var-- ...) (contact nil) (contact-name nil) (email nil) (#3=#:--cl-var-- nil)) (while (consp #2#) (setq contact ...) (setq contact-name ...) (setq email ...) (if email ...) (setq #2# ...)) (nreverse #3#)) ", "))) (quote #:--tag--) --cl-rest--)) nil)
  completion-at-point()
  message-tab()
```

whereby "data" is the return value of all-completions, which is a string.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Thanks, I can reproduce it.
>
> @thierryvolpiatto The problem is that all-completions doesn't return a list but a string which helm doesn't expect:

Thanks, should work now.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Tory S. Anderson <notifications@github.com> writes:

> Recipe for duplication:
> 1. download and unpack minimal files for problem reduplication: http://toryanderson.com/files/helm.zip
> 2. Start helm.sh
> 3. Navigate to where you unpacked the files, and evaluate config.el
> 4. C-x m to create a new message; in the "To:" field type "+t" and to finish the list of names.
>
> You will now see the error.

I wish recipes like this one for all bugs :-)

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by WorldsEndless** [comment]
Ah, you guys are beautiful. Thanks for the fix; this is a tremendous help for my workflow. Also, thanks for the hand-holding; I was previously unaware of either helm.sh or how to do a backtrace.
