### ISSUE TITLE
emacsclient confused by helm-mini

### ISSUE THREAD

**Issue by Phlogistique** [emacs-helm/helm#883]
How to reproduce:
1. `emacs --daemon`
2. In terminal 1: `emacsclient -t foo.txt`
3. `M-x helm-mini`
4. With helm-mini still open, run `emacsclient -t bar.txt` in terminal 2

Expected behaviour: terminal 2 displays the contents of bar.txt
Actual behaviour: terminal 2 displays the helm buffer in full screen. After a click anywhere, helm-mini is closed, terminal 1 displays the contents of bar.txt and terminal 2 displays the contents of foo.txt (this is the contrary of what is expected)

**Comment by thierryvolpiatto** [comment]
Noé Rubinstein <notifications@github.com> writes:

> How to reproduce:
> 1. emacs --daemon
> 2. In terminal 1: emacsclient -t foo.txt
> 3. M-x helm-mini
> 4. With helm-mini still open, run emacsclient -t bar.txt in terminal 2
>
> Expected behaviour: terminal 2 displays the contents of bar.txt Actual
> behaviour: terminal 2 displays the helm buffer in full screen. After a
> click anywhere, helm-mini is closed, terminal 1 displays the contents
> of bar.txt and terminal 2 displays the contents of foo.txt (this is
> the contrary of what is expected)

I guess this is not supported by emacsclient (i.e handling a minibuffer active), 
instead of helm in step 3, run `M-:' and then run step 4, you will
observe the same disorder.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by Phlogistique** [comment]
Ok, will file a bug in emacsclient.

**Comment by thierryvolpiatto** [comment]
Thanks to fill bug in emacs, closing now.
http://debbugs.gnu.org/cgi/bugreport.cgi?bug=19945
