### ISSUE TITLE
helm-org inserts link to wrong location

### ISSUE THREAD

**Issue by scottmartincampbell** [emacs-helm/helm#884]
When calling `helm-org-in-buffer-headings`, if I try to insert a heading, it ends up inserted immediately after the heading, and not at point. This also happens with `helm-org-agenda-files-headings`, if the header selected is the same as the current buffer. Example:

`* Book [[*Book]]`

The problem is in `helm-org-insert-link-to-heading-at-marker`. It assumes the header buffer is different from the current buffer, and `goto-char` ends up moving the point to the header, but `with-helm-current-buffer` doesn't return the point back to the current location. 

I fixed it like this, but there may be a better solution:

```elisp
(defun helm-org-insert-link-to-heading-at-marker (marker)
  (let ((old-pnt (point-marker)))
    (with-current-buffer (marker-buffer marker)
      (goto-char (marker-position marker))
      (let ((heading-name (nth 4 (org-heading-components)))
            (file-name buffer-file-name))
        (message heading-name)
        (message file-name)
        (with-helm-current-buffer
          (goto-char old-pnt)
          (org-insert-link
           file-name (concat "file:" file-name "::*" heading-name)))))))
```

**Comment by thierryvolpiatto** [comment]
scottmartincampbell <notifications@github.com> writes:

> When calling helm-org-in-buffer-headings, if I try to insert a
> heading, it ends up inserted immediately after the heading, and not at
> point. This also happens with helm-org-agenda-files-headings, if the
> header selected is the same as the current buffer. Example:
>
> * Book [[*Book]]
>
> The problem is in helm-org-insert-link-to-heading-at-marker. It
> assumes the header buffer is different from the current buffer, and
> goto-char ends up moving the point to the header, but
> with-helm-current-buffer doesn't return the point back to the current
> location.
>
> I fixed it like this, but there may be a better solution:

Thanks but with-helm-current-buffer should not be used at all, because
if I call helm-org* from an unrelated buffer e.g a lisp buffer, this
buffer will be used as current and org insertion will belong in this buffer.

I will look into this as soon as possible.

Thanks.


-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Thierry Volpiatto <thierry.volpiatto@gmail.com> writes:

> scottmartincampbell <notifications@github.com> writes:
>
>> When calling helm-org-in-buffer-headings, if I try to insert a
>> heading, it ends up inserted immediately after the heading, and not at
>> point. This also happens with helm-org-agenda-files-headings, if the
>> header selected is the same as the current buffer. Example:
>>
>> * Book [[*Book]]
>>
>> The problem is in helm-org-insert-link-to-heading-at-marker. It
>> assumes the header buffer is different from the current buffer, and
>> goto-char ends up moving the point to the header, but
>> with-helm-current-buffer doesn't return the point back to the current
>> location.
>>
>> I fixed it like this, but there may be a better solution:
>
> Thanks but with-helm-current-buffer should not be used at all, because
> if I call helm-org* from an unrelated buffer e.g a lisp buffer, this
> buffer will be used as current and org insertion will belong in this buffer.
>
> I will look into this as soon as possible.

Oh! I realize that it is the intention of this function, inserting link
in current-buffer, sorry my org usage is very limited.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
@IvanMalison Could you look into this?
Thanks.

**Comment by IvanMalison** [comment]
Yeah sure. Thanks for the heads up.

**Comment by IvanMalison** [comment]
@scottmartincampbell Why not just use save-excursion?

**Comment by scottmartincampbell** [comment]
Thanks for getting to this so quickly! I figured `save-excursion` was better but didn't think to put it in the `let`.
