### ISSUE TITLE
helm-browse-menubar: prefix arg vs. multiple sources

### ISSUE THREAD

**Issue by michael-heerdegen** [emacs-helm/helm#885]
Hi,

would you accept a PR regarding the following:

You decided for "helm-browse-menubar" to control which parts from the menu-bar are candidates (global, minor-mode, major-mode menus) via prefix arg.  But I think in this case, it would be simpler and justifiable to use a combined session for all of them, since the decomposition of the menu-bar in parts is an implementation detail - there is only one menu bar.  This is what I use and would suggest more or less:

```
  (defun my-helm-browse-menubar ()
    "My helm interface to the menubar using lacarte.el."
    (interactive)
    (require 'lacarte)
    (helm :sources (mapcar 
                    (lambda (spec) (helm-make-source (car spec) 'helm-lacarte
                                :candidates (lambda () (helm-lacarte-get-candidates (cdr spec)))))
                    '(("Major Mode"  . (local))
                      ("Minor Modes" . (minor))
                      ("Global Map"  . (global))))
          :buffer "*helm lacarte*"))
```

Thanks.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Hi,
>
> would you accept a PR regarding the following:

Yes but the code below is not working at all, please fix it before.

>   (defun my-helm-browse-menubar ()
>     "My helm interface to the menubar using lacarte.el."
>     (interactive)
>     (require 'lacarte)
>     (helm :sources (mapcar 
>                     (lambda (spec) (helm-make-source (car spec) 'helm-lacarte
>                                 :candidates (lambda () (helm-lacarte-get-candidates (cdr spec)))))
>                     '(("Major Mode"  . (local))
>                       ("Minor Modes" . (minor))
>                       ("Global Map"  . (global))))
>           :buffer "*helm lacarte*"))

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Thierry Volpiatto <thierry.volpiatto@gmail.com> writes:

> Michael Heerdegen <notifications@github.com> writes:
>
>> Hi,
>>
>> would you accept a PR regarding the following:
>
> Yes but the code below is not working at all, please fix it before.
>
>>   (defun my-helm-browse-menubar ()
>>     "My helm interface to the menubar using lacarte.el."
>>     (interactive)
>>     (require 'lacarte)
>>     (helm :sources (mapcar 
>>                     (lambda (spec) (helm-make-source (car spec) 'helm-lacarte
>>                                 :candidates (lambda () (helm-lacarte-get-candidates (cdr spec)))))
>>                     '(("Major Mode"  . (local))
>>                       ("Minor Modes" . (minor))
>>                       ("Global Map"  . (global))))
>>           :buffer "*helm lacarte*"))

Something like this is working: (don't know if it is what you want)

(defun my-helm-browse-menubar ()
  "My helm interface to the menubar using lacarte.el."
  (interactive)
  (require 'lacarte)
  (helm :sources
        (cl-loop for (name . spec) in '(("Major Mode"  . (local))
                                        ("Minor Modes" . (minor))
                                        ("Global Map"  . (global)))
                 collect (helm-make-source name 'helm-lacarte
                           :candidates `(lambda () (helm-lacarte-get-candidates ',spec))))
        :buffer "*helm lacarte*"))
-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
Your code does what mine does, in the same way, and raises the same error in helm.sh.

The error message is more confusing than helpful.  Seems we have a bug here.

BTW, my posted code is in my init file, which I always compile, and it works there for several days without problems or warnings.

Here is a shorter piece of code to hit the bug from helm.sh:

```
(helm-make-source "Test" 'helm-lacarte :candidates #'ignore)
```

Can you please have a look?  Thanks.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Your code does what mine does, in the same way, and raises the same error in helm.sh.
>
> The error message is more confusing than helpful. Seems we have a bug here.
>
> BTW, my posted code is in my init file, which I always compile, and it works there for several days without problems or warnings.
>
> Here is a shorter piece of code to hit the bug from helm.sh:
>
> (helm-make-source "Test" 'helm-lacarte :candidates #'ignore)

This is working as soon you require helm-misc.

Evaluated from scratch:

Your version is returning always an empty helm-buffer.
My version is working as expected.

The two versions return the error you see because they are not
autoloaded yet (you have to require helm-misc as said above)

Probably the lambda in your version is working when compiled in a
lexical environment (not tested), some tests with macroexpand* should show
you quickly what your code is expanded to.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> Probably the lambda in your version is working when compiled in a
> lexical environment (not tested), some tests with macroexpand* should
> show you quickly what your code is expanded to.

There is nothing wrong with my code, it just depends on lexical-binding,
which is the case for lots of stuff in helm.  Evaluating stuff requiring
lexical-binding in scratch will give you broken resuls - that's
expected, and will also be the case for every piece of helm code
requiring lexical binding.

My code example also works when interpreted, as long as lexical-binding
is in effect.

Since all helm files use lexical-binding since some time, I don't see
any problem.

Your code OTOH uses a quoted lambda again, which is something we want
to get rid of.

BTW, until lexical-binding t is the default in Emacs, you can use
  
    (setq-default initial-major-mode
                  (lambda () (prog1 (emacs-lisp-mode) (setq lexical-binding t))))

to enable lexical-binding in scratch when starting Emacs.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Thierry Volpiatto <notifications@github.com> writes:
>
>> Probably the lambda in your version is working when compiled in a
>> lexical environment (not tested), some tests with macroexpand* should
>> show you quickly what your code is expanded to.
>
> There is nothing wrong with my code, it just depends on lexical-binding,
> which is the case for lots of stuff in helm. Evaluating stuff requiring
> lexical-binding in scratch will give you broken resuls - that's
> expected, and will also be the case for every piece of helm code
> requiring lexical binding.
>
> My code example also works when interpreted, as long as lexical-binding
> is in effect.
>
> Since all helm files use lexical-binding since some time, I don't see
> any problem.

Michael, I had a lot of work today to fix stuff in helm and couldn't
look carefully at your code, there is no bug anyway, just put your
function in file, add the autoload cookie and you are done.
Compile, restart emacs, test and send the PR, I will merge.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
