### ISSUE TITLE
make helm help mode searchable and selectable

### ISSUE THREAD

**Issue by slymz** [emacs-helm/helm#887]
While in Helm Help mode -- the help buffer that pops up when you hit C-c ? in a helm buffer -- the help text is not searchable or selectable. 

These help buffers are long and full of precious info.  It would be great if this info was easier to consume (e.g. locate a specific command via search)

cf: http://emacs.stackexchange.com/questions/9440/helm-help-mode-can-not-search-or-select

**Comment by thierryvolpiatto** [comment]
slymz <notifications@github.com> writes:

> While in Helm Help mode -- the help buffer that pops up when you hit
> C-c ? in a helm buffer -- the help text is not searchable or
> selectable.
>
> These help buffers are long and full of precious info. It would be
> great if this info was easier to consume (e.g. locate a specific
> command via search)
>
> cf: http://emacs.stackexchange.com/questions/9440/helm-help-mode-can-not-search-or-select

The embeded documentation for specific command you have via C-c ? is to
have a quick look while you are running helm, for more, try M-x
helm-documentation.


-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by slymz** [comment]
thanks for the tip, very useful stuff!   

It'd still be nice to have at least C-s in C-c ? buffers; most of these have 100+ lines, eyeballing to pinpoint specifics during that "quick look" is a pain point.

**Comment by tuhdo** [comment]
This is fixed now. You should check it again.

**Comment by slymz** [comment]
Search works..  Very welcome addition, thanks tuhdo!
