### ISSUE TITLE
New tramp multihop syntax support

### ISSUE THREAD

**Issue by ineu** [emacs-helm/helm#894]
New syntax for multihop was added in emacs 24: http://www.emacswiki.org/emacs/TrampMode#toc13
Unfortunately currently it does not work with Helm.
Usual usecase is editing files as root on server with root login disabled. So following works in `emacs -q` with standard `find-file`:
```
/ssh:non-root-user@example.com|sudo:example.com:/etc/fstab
```
But unfortunately not in Helm.

**Comment by thierryvolpiatto** [comment]
Eugene Diachkin <notifications@github.com> writes:

> New syntax for multihop was added in emacs 24: http://www.emacswiki.org/emacs/TrampMode#toc13
> Unfortunately currently it does not work with Helm.
> Usual usecase is editing files as root on server with root login disabled. So following works in emacs -q with standard find-file:
>
> /ssh:non-root-user@example.com|sudo:example.com:/etc/fstab
>
> But unfortunately not in Helm.

This is not implemented yet, you have to use `tramp-default-proxies-alist',
and use /sudo:non-root-user@example.com:/etc/fstab

I assume that is you have the right to edit files as root on a remote
machine, you are familiar to this machine and BTW have it configured in
`tramp-default-proxies-alist'.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by ineu** [comment]
Ok, thank you. Are there plans to implement it someday or should I close the ticket?

**Comment by thierryvolpiatto** [comment]
Eugene Diachkin <notifications@github.com> writes:

> Ok, thank you. Are there plans to implement it someday or should I close the ticket?

You can close, thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
