### ISSUE TITLE
Fallback options in situations with no matching candidates.

### ISSUE THREAD

**Issue by tmalsburg** [emacs-helm/helm#895]
When using helm-bibtex and helm-dictionary, it often happens that I don't find a candidate matching the query.  In these situations, I typically have a number of plan-B-type options, e.g., look up an online bibliographic database or online dictionary.  To present these plan-Bs to the user, I use a second dummy source that simply lists all options below the main source.  See here for an example:

![screenshot of helm-bibtex](https://github.com/tmalsburg/helm-bibtex/raw/master/screenshot.png)

I'm not completely happy with this solution because the plan-B options are not really candidates, they are actions.  Would it make sense to introduce a new attribute for helm sources in which we can list plan-B actions?

**Comment by thierryvolpiatto** [comment]
Titus von der Malsburg <notifications@github.com> writes:

> When using helm-bibtex and helm-dictionary, it often happens that I
> don't find a candidate matching the query. In these situations, I
> typically have a number of plan-B-type options, e.g., look up an
> online bibliographic database or online dictionary. To present these
> plan-Bs to the user, I use a second dummy source that simply lists all
> options below the main source. See here for an example:
>
> screensh
>
> I'm not completely happy with this solution because the plan-B options
> are not really candidates, they are actions. Would it make sense to
> introduce a new attribute for helm sources in which we can list plan-B
> actions?

They are not really actions as you use a full source to display this, so
I don't see the problem, seems good what you use actually.
The only thing that need to be fixed is the candidates-in-file which is
not available in helm-source actually, but is is unrelated to your
question.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tmalsburg** [comment]
Ok, thanks for your response.
