### ISSUE TITLE
Turn in image viewer

### ISSUE THREAD

**Issue by E3D3** [emacs-helm/helm#897]
Emacs-helm wiki! paragraph 7.4. Turn in image viewer
tells to use C-u C-z but that is the default command for suspend-frame.
Luckily helm works as image viewer without that command, at least in my GNU Emacs 24.4.1.

**Comment by thierryvolpiatto** [comment]
E3D3 <notifications@github.com> writes:

> Emacs-helm wiki! paragraph 7.4. Turn in image viewer
> tells to use C-u C-z but that is the default command for
> suspend-frame.

This is not the same keymap, please read how keymap works in the emacs
manual.

> Luckily helm works as image viewer without that command, at least in my GNU Emacs 24.4.1.

And it works with this command too in all emacs versions.

You can use C-<up>/<down> to navigate your images.

Use C-c ? for more infos.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by E3D3** [comment]
You are right about the keymap, sorry for my mistake.
C-u C-z in helm-find-files open helm action menu,
and I don't know what to do with it after activating follow-mode.

**Comment by thierryvolpiatto** [comment]
E3D3 <notifications@github.com> writes:

> You are right about the keymap, sorry for my mistake.
> C-u C-z in helm-find-files open helm action menu,

No it doesn't.  C-u C-z open file or kill buffer (on second hit), this
have for effect displaying an image directly without expanding to
filename.

> and I don't know what to do with it after activating follow-mode.

Once you have activated follow-mode you just have to hit arrow keys up
and down to navigate in your images.

You can also INSTEAD of activating follow-mode hit C-up/down to navigate
your images.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
I suggest you read the excellent [Guide](https://tuhdo.github.io/helm-intro.html) of @tuhdo

**Comment by E3D3** [comment]
I didn't know I have to hit C-u C-z twice to exit the action menu.
Maybe I have some difference with the normal helm because the C-c ? help tells nothing about C-u prefix, only that C-z is select action. But hitting it twice worked, although I don't understand why to use it. 
Activating follow-mode and arrow keys seems to be enough to display images.
Also without activating follow-mode did it work with C+arrow and I didn't notice any difference.
I have read @tuhdo's guide and also helm's GitHub page but can't remember it all at once.
There I also couldn't find an explanation.

**Comment by michael-heerdegen** [comment]
You have probably bound C-z to something different from the default in your configt.  There are lots of people out there recommending switching TAB And C-z, I guess you have done something like that.

**Comment by thierryvolpiatto** [comment]
I am closing this, feel free to continue this discussion on the google mailing list, thanks.

**Comment by E3D3** [comment]
You're right, I changed the C-z binding like @thudo's tutorial suggested.
I'm sure I grepped my configuration more than a dozen times,
although 'sure' just lost it meanings in my vocabulary.
I offer my sincere apologies to Thierry Volpiatto
and I am so unbelievable ashamed about this conversation that I close my
GitHub-account immediately
and hope that this stupid conversation can be deleted from GitHub.
Thank you.


2015-03-06 11:57 GMT+07:00 Michael Heerdegen <notifications@github.com>:

**Comment by michael-heerdegen** [comment]
I hope that was a joke!  That can happen to us all.  Half of the bug reports here end similarly as this one, and often, after a much longer discussion.  But you are the first one I remember that offered apologies.

**Comment by thierryvolpiatto** [comment]
E3D3 <notifications@github.com> writes:

> You're right, I changed the C-z binding like @thudo's tutorial suggested.
> I'm sure I grepped my configuration more than a dozen times,
> although 'sure' just lost it meanings in my vocabulary.
> I offer my sincere apologies to Thierry Volpiatto
> and I am so unbelievable ashamed about this conversation that I close my
> GitHub-account immediately
> and hope that this stupid conversation can be deleted from GitHub.
> Thank you.

Hey! Configuring emacs and all its bindings is not an easy task and
anyone can make mistakes, forgetting an old binding or a old file laying
somewhere etc...
No need for apologies, and no need to remove your github account ;-), you
are welcome to ask questions about helm if you have difficulties in the
future.

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
