### ISSUE TITLE
Using Helm for C-u org-clock-in

### ISSUE THREAD

**Issue by WorldsEndless** [emacs-helm/helm#898]
I know there must be orgmode users here, so I'm looking for help. Using:

    ;; Org clock-in
    (org-clock-persistence-insinuate)
    (setq org-clock-persist t)

I am able to pass an arg to (org-clock-in) to pull up a list of recent org tasks; to be precise, it invokes (org-clock-select-task). For Helm users, however, it would be much preferable to do away with the hot-key mini-buffer of org-clock-select-task and just be able to make a selection using Helm. Being completely ignorant of Helm development myself, can anyone offer suggestions/code that would make this possible? I assume that somewhere in the command tree lists of tasks are being passed around that Helm would be suited to navigate (although I'm not familiar with how/where/what Helm receives). Ultimately I imagine patching the org-clock-in function to just check for a 'use-helm variable in order to stop using the org-clock-select-task minibuffer.

Thanks in advance for your help. Helm is a great package that fundamentally changes and improves my emacs work-flow.

**Comment by thierryvolpiatto** [comment]
I don't use this org feature, but I guess that should be handled on the org side i.e org-clock-select-task should be at least handled by a variable that allow using another function, or even better use a completing-read.

**Comment by WorldsEndless** [comment]
I'm not familiar with what a completing-read is. Where can I learn more? I was thinking that it should be pretty simple to to "downgrade" to passing some kind of list instead of using the advanced functionality of the mini-buffer. Is this incorrect?

**Comment by thierryvolpiatto** [comment]
M-x helm-apropos => completing-read.

The Idea is to advice (or fix upstream) org-clock-select-task to use a completing-read instead of its kind of bar.
They do this for tags IIRC, don't remember which is the command. (i.e you can disable the special org menu).

**Comment by thierryvolpiatto** [comment]
I am closing this as it is not really related to helm.

Thanks.

**Comment by stardiviner** [comment]
I checked out Org-mode source code of `org-clock-select-task`, seems it use own way to implement completing function. And I use Org-mode for a long time, found that it use ido or helm in some cases, but not in some other cases, weird.

**Comment by andersjohansson** [comment]
`org-clock-select-task` seems to do many things, like offering tasks from a few different "sources" to be selected. This means it's not just a simple task for a single `completing-read`. It would work very well with helm's concept of sources though! 

One thing that could be done (which I guess is to go a little far for something like `helm-org`) is to make a new helm version of `org-clock-select-task` and advice an override for org's own version:

    (advice-add 'org-clock-select-task :override #'helm-org-clock-select-task)

This function `helm-org-clock-select-task` should than gather the stuff that `org-clock-select-task` does, put them in helm sources (with nice formatting) and let helm choose among them.

A different option is following Sacha Chua's lead and integrate refiling and clocking in with the help of helm: http://sachachua.com/blog/2015/03/getting-helm-org-refile-clock-create-tasks/

(sorry to linger on on this topic, which is not the task of helm core)

**Comment by andersjohansson** [comment]
Oh, well. I started implementing my above suggestion. Here is the code in a gist:
https://gist.github.com/andersjohansson/c031dc357cc81537d7c3
It's not done yet, it needs sources for "default task" etc. It would also be good if `helm-org-get-candidates` could support filtering for todo-states or tags etc, so we could get a list of only actual tasks. This could perhaps be done with org's `matcher`-facilities (`org-map-entries` and `org-make-tags-matcher`).

**Comment by andersjohansson** [comment]
More discussion on the topic: https://lists.gnu.org/archive/html/emacs-orgmode/2015-04/msg00052.html
