### ISSUE TITLE
Helm issued errors: helm-match-from-candidates

### ISSUE THREAD

**Issue by zilvinasu** [emacs-helm/helm#899]
```Helm issued errors: helm-match-from-candidates in source `Project buffers': void-function (helm-buffers-list--match-fn)```

This is something I get every time I start writing anything when I open helm-projectile.

**Comment by thierryvolpiatto** [comment]
Žilvinas <notifications@github.com> writes:

> Helm issued errors: helm-match-from-candidates in source `Project
> buffers': void-function (helm-buffers-list--match-fn)
>
> This is something I get every time I start writing symbols when I open
> helm-projectile.

`helm-buffers-list--match-fn' doesn't exists anymore, that's mean you
have not recompiled properly helm. See the FAQ on helm wiki.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment]
It is addressed with this PR: https://github.com/bbatsov/projectile/pull/681

**Comment by thierryvolpiatto** [comment]
Ok, thanks, closing.
