### ISSUE TITLE
helm project buffers not working anymore.

### ISSUE THREAD

**Issue by Dickby** [emacs-helm/helm#901]
Hi,
I'm using emacs 24.4.1, helm and helm-projectile.
If I update helm to newer than helm-20150304.747 and use helm projectile with open project-buffers,
after typing Characters for narrowing the selections, I get the following Error-Message:
"Helm issued errors: helm-match-from-candidates in source `Project buffers': void-function (helm-buffers-list--match-fn)"
and the "project-buffer" part of the helm-projectile buffer disapears.
I got the same Error by starting emacs with -q and only loading helm, helm-projectile and projectile.

**Comment by tuhdo** [comment]
@Dickby This is being addressed by this PR from Projectile side: https://github.com/bbatsov/projectile/pull/681. Please close the issue here.

**Comment by Dickby** [comment]
Thanks!
