### ISSUE TITLE
Unable to switch to buffers with stars in the name (scratch, messages, eshell)

### ISSUE THREAD

**Issue by dakrone** [emacs-helm/helm#903]
After updating to the latest helm from MELPA (`helm-20150309.619`), I am unable to switch to any buffers that aren't backed by files or that have stars in the name!

Example:

`C-x b`

![screen shot 2015-03-09 at 4 18 15 pm](https://cloud.githubusercontent.com/assets/19060/6565735/f9842042-c677-11e4-9a3f-b6548b5d2aa6.png)

Okay, I have some buffers with stars like the "eshell" buffers, "`*Messages*`" and "`*scratch*`". If I try typing in "eshell" to pick between the eshell buffers:

![screen shot 2015-03-09 at 4 18 56 pm](https://cloud.githubusercontent.com/assets/19060/6565736/fb5c7d9c-c677-11e4-9e48-c02cbf3a4bfc.png)

I suddenly can't pick any buffers. Same with typing "scratch" to go to the "`*scratch*`" buffer or "messages" to go to the "`*Messages*`" buffer.

**Comment by michael-heerdegen** [comment]
Does that happen with helm.sh?  I don't see this here.  I tried helm-buffers-list and helm-mini.

**Comment by thierryvolpiatto** [comment]
Lee Hinman <notifications@github.com> writes:

> After updating to the latest helm from MELPA (helm-20150309.619), I am
> unable to switch to any buffers that aren't backed by files or that
> have stars in the name!

Should work now, thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by dakrone** [comment]
Whew thanks! I was going crazy trying to reproduce it!
