### ISSUE TITLE
helm-ff-run-toggle-basename errors when toggled when there are no current matches

### ISSUE THREAD

**Issue by alvinfrancis** [emacs-helm/helm#904]
Using version `20150309.619`, I get the following error when trying to toggle the basename (`C-]`) after typing out a pattern with no matches.

    helm-ff-run-toggle-basename: Wrong type argument: consp, nil

Following the error, the basename remains untoggled. Also, the error does not trigger when there is at least one match for the pattern. (I'm referring to the toggled basename to mean to show the full path of the selection.)

**Comment by thierryvolpiatto** [comment]
Alvin Francis Dumalus <notifications@github.com> writes:

> Using version 20150309.619, I get the following error when trying to
> toggle the basename (C-]) after typing out a pattern with no matches.
>
> helm-ff-run-toggle-basename: Wrong type argument: consp, nil

Well yes, what is the basename of nothing ?
I fixed that anyway, there is no error now just nothing happen when you
do that.

> Following the error, the basename remains untoggled.

As expected, you are trying to toggle basename of nothing.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Closing this, feel free to reopen if something wrong for you.

**Comment by alvinfrancis** [comment]
The expectation I had was that toggling the fullpath would cause helm to match candidates on those.  For example, if using a recent files source such that I have a recently used files in a path with a `foo` folder but with no file named `foo`, and I have basename (fullpath?) untoggled, then I could type foo without getting any matches.  Toggling basename in this state, however, does not cause helm to refresh with full path candidates.

On the other hand, if I did have a file named `foo`, so the pattern matches at least one non-full-path-qualified file, I can toggle basename and it would work as I expect: helm refreshes narrowed down on all candidates with `foo` in their path.

**Comment by thierryvolpiatto** [comment]
Alvin Francis Dumalus <notifications@github.com> writes:

> The expectation I had was that toggling the fullpath would cause helm to match candidates on those. For example, if using a recent files source such that I have a
> recently used files in a path with a foo folder but with no file named foo, and I have basename (fullpath?) untoggled, then I could type foo without getting any
> matches. Toggling basename in this state, however, does not cause helm to refresh with full path candidates.
>
> On the other hand, if I did have a file named foo, so the pattern matches at least one non-full-path-qualified file, I can toggle basename and it would work as I
> expect: helm refreshes narrowed down on all candidates with foo in their path.

I understood what you wanted to do, but helm is not doing this, OTOH you
can use the "-b" flag at end of your full path.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by alvinfrancis** [comment]
Ah. I guess I misunderstood the toggling of the basename to primarily be a means for changing candidates to choose from instead of a means to change how to display currently shown candidates. I often use helm with the full path toggled off, but sometimes I type out a pattern hoping to search against the path while forgetting to first toggle on the full path. And by the time, I finish typing the pattern and realise my mistake, toggling with `C-]` doesn't work. So, kind of my fault there I guess.

In any case, no need to reopen the issue. Thanks for the help!
