### ISSUE TITLE
Can someone with a printer check is helm-ff-print works.

### ISSUE THREAD

**Issue by thierryvolpiatto** [emacs-helm/helm#905]
You will have to apply #900 or use the helm-ff-print branch.

Thanks.

**Comment by tuhdo** [comment]
What command should I invoke to test it? I will test it at work tomorrow.

**Comment by thierryvolpiatto** [comment]
Hi Tudho,

it should work with no settings, helm should detect your printer(s).
Otherwise you can configure `lpr-switches` as recommended in emacs (Don't add the "-P" switch, it should be added automatically by helm with the new var `lpr-printer-switch`).
For more infos about this bug, see the conversation on our mailing list:
https://groups.google.com/forum/?hl=en#!topic/emacs-helm/SWuE2V_KgxM

Thanks.

**Comment by tuhdo** [comment]
@thierryvolpiatto I got his error:

> apply: Symbol's value as variable is void: lpr-printer-switch

That is after I cloned Helm and fetch the PR. `lpr-printer-switch` is available in `helm-files.el` but for some reason even after evaluating the whole buffer, it still does not show up in `describe-variable`. I tested with `./emacs-helm.sh`.

**Comment by michael-heerdegen** [comment]
I stumbled over that, too.  You must require lpr, it's defined there, the variable not autoloaded.

**Comment by michael-heerdegen** [comment]
But you get an error when trying the PR, right?  That would mean we would need to load lpr when helm-ff-print is called, or just add a value to our defvar of it.

**Comment by tuhdo** [comment]
@thierryvolpiatto @michael-heerdegen 

Ok after loading `lpr`, I was able to print from Helm. This is the command shown:

```sh
lpr -PHP-LaserJet-400-M401
```

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> @thierryvolpiatto @michael-heerdegen
>
> Ok after loading lpr, I was able to print from Helm. This is the command shown:
>
> lpr -PHP-LaserJet-400-M401

Ok so I will merge, I have done some more changes for loading lpr.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> But you get an error when trying the PR, right? That would mean we
> would need to load lpr when helm-ff-print is called, or just add a
> value to our defvar of it.

I have required lpr in helm-ff-print and declared lpr-printer-switch
with no value.
I think dired is loading this by using lpr-command which is a defcustom
autoloaded (sic), I don't want to count on this as I am pretty sure that
this autoload will be removed at some point and we will endup will the
same problem again.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> Michael Heerdegen <notifications@github.com> writes:
>
> > But you get an error when trying the PR, right? That would mean we
> > would need to load lpr when helm-ff-print is called, or just add a
> > value to our defvar of it.

> I think dired is loading this by using lpr-command which is a
> defcustom autoloaded (sic), I don't want to count on this as I am
> pretty sure that this autoload will be removed at some point and we
> will endup will the same problem again.

But just referencing an autoloaded defcustom doesn't load a package,
AFAIK.

And if you do (setq printer-name "my-printer") in emacs -Q and hit P in
dired, you get an error.  That's simply a bug in Emacs, no?

**Comment by michael-heerdegen** [comment]
And I think that instead of removing autoloads, it would be better to autoload "lpr-printer-switch" in vanilla Emacs in addition to the other vars.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> And I think that instead of removing autoloads, it would be better to
> autoload "lpr-printer-switch" in vanilla Emacs in addition to the
> other vars.

defcustom should not be autoloaded in emacs.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
> That's simply a bug in Emacs, no?

Yes.

**Comment by thierryvolpiatto** [comment]
I am closing this, it should work now.

Thanks @tuhdo and @michael-heerdegen for testing.

Feel free to reopen if something wrong.
