### ISSUE TITLE
Action buffer is often empty

### ISSUE THREAD

**Issue by jwiegley** [emacs-helm/helm#907]
I'm using the latest Git version of helm, with nothing byte-compiled (at the moment).  If I run `helm-regexp` or `helm-find-files`, and then type TAB to show the action buffer, it is always empty.  However, I can verify by debugging that the action list is correct, I just can't find where in the code it's supposed to insert the text into the action buffer.

**Comment by jwiegley** [comment]
I think I've found the problem: After pressing TAB, helm retains the minibuffer contents, which act as a filter on the action buffer (perhaps because I have the match plugin enabled?).  This filter causes none of the actions to match, which makes the buffer appear empty.

**Comment by jwiegley** [comment]
Ok, here's the bug: When `helm-delete-minibuffer-contents-from-point` is configured to a non-nil value, selecting the action buffer will fail to clear the minibuffer contents after displaying its buffer, causing the previous minibuffer contents to match against the contents of the action buffer.

**Comment by thierryvolpiatto** [comment]
Hi John,

John Wiegley <notifications@github.com> writes:

> I think I've found the problem: After pressing TAB, helm retains the
> minibuffer contents, which act as a filter on the action buffer
> (perhaps because I have the match plugin enabled?). This filter causes
> none of the actions to match, which makes the buffer appear empty.

I doubt this is the reason, the minibuffer is reset when switching to
action buffer, I can't reproduce here, can you reproduce from ./emacs-helm.sh ?

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
John Wiegley <notifications@github.com> writes:

> Ok, here's the bug: When helm-delete-minibuffer-contents-from-point is
> configured to a non-nil value, selecting the action buffer will fail
> to clear the minibuffer contents after displaying its buffer, causing
> the previous minibuffer contents to match against the contents of the
> action buffer.

Great, can reproduce now, will fix soon.

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
John Wiegley <notifications@github.com> writes:

> Ok, here's the bug: When helm-delete-minibuffer-contents-from-point

Ok assuming you will not need this feature in the action buffer , it is
fixed, thanks to catch this.


-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Thierry Volpiatto <thierry.volpiatto@gmail.com> writes:

> John Wiegley <notifications@github.com> writes:
>
>> Ok, here's the bug: When helm-delete-minibuffer-contents-from-point
>
> Ok assuming you will not need this feature in the action buffer , it is
> fixed, thanks to catch this.

Now the behavior of helm-delete-minibuffer-contents have changed, see
its docstring.
Also now helm-delete-minibuffer-contents-from-point is enabled by
default.
And it behave the same in action buffer and normal buffer.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by jwiegley** [comment]
Thanks, @thierryvolpiatto!  I'm really enjoying Helm these days.
