### ISSUE TITLE
allow negation for helm-locate

### ISSUE THREAD

**Issue by michael-heerdegen** [emacs-helm/helm#908]
I think it is a good idea - especially now after it had been discouraged to use helm-source-locate in combination with other sources - to allow negation of patterns in helm-locate a la

match-this-pattern this-pattern-also !not-this-pattern

WDYT?

**Comment by jixiuf** [comment]
I like the way : locate  foo  |grep bar 
so I write this script named everything.sh
```
#!/bin/bash

cmd="locate -i $1"
while [ $# -gt 0 ];
do
    cmd="$cmd | grep -i $1";
    shift;
done

eval $cmd
```
then 
```
(setq-default helm-locate-command (cl-case system-type
                                    ('gnu/linux (expand-file-name "~/.emacs.d/bin/everything.sh %s %s"))
                                    ;; "locate  %s -e -A %s"
                                    ('berkeley-unix "locate %s %s")
                                    ('windows-nt "es %s %s")
                                    ('darwin (expand-file-name "~/.emacs.d/bin/everything.sh %s %s")) ;mdfind -name %s %s
                                    (t "locate %s %s")))
```
you just need type "foo bar"  
hope this is helpful

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> I think it is a good idea - especially now after it had been discouraged to use helm-source-locate in combination with other sources - to allow negation of patterns
> in helm-locate a la
>
> match-this-pattern this-pattern-also !not-this-pattern
>
> WDYT?

We are already emulating fuzzy matching for locate (I don't use it
personally for this) so using this should happen in non--fuzzy match,
remember that we are not using the fuzzy mechanism of helm nor the
matchplugin one, so we have to handle this in a pattern transformer
again, by just removing the !foo part of the splitted pattern.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
jixiuf <notifications@github.com> writes:

> I like the way : locate foo |grep bar
> so I write this script named everything.sh

Your script is a really good alternative for people using an old
version of locate, I was aware of it.
However with new versions of locate coming with ubuntu 14.04, you can
use "locate %s -e -A --regex %s" which have the same effect.

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> We are already emulating fuzzy matching for locate (I don't use it
> personally for this) so using this should happen in non--fuzzy match,
> remember that we are not using the fuzzy mechanism of helm nor the
> matchplugin one, so we have to handle this in a pattern transformer
> again, by just removing the !foo part of the splitted pattern.

That's what I roughly thought too, I think.

**Comment by thierryvolpiatto** [comment]
After looking at this more closely, it seems it is not enough just removing the negation part of the pattern, it is much more complex than that, and is difficult to implement.

**Comment by michael-heerdegen** [comment]
There is no hurry for this one.  Thanks so far.

**Comment by michael-heerdegen** [comment]
I don't yet see why this is complicated.  Naively using :filtered-candidate-transformer seems to do it, e.g. this runs locate sorting out files in "/home/":

```
(helm
 (helm-make-source "Locate" 'helm-locate-source
   :pattern-transformer 'helm-locate-pattern-transformer
   :filtered-candidate-transformer
   (lambda (cands _source)
     (delq nil
           (mapcar (lambda (cand)
                     (if (string-match-p "/home/" (cdr cand))
                         nil cand))
                   cands)))))
```

We would just have to make the lambda a named function receiving the removed negation patterns, no...?

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> I don't yet see why this is complicated. Naively using
> :filtered-candidate-transformer seems to do it, e.g. this runs locate
> sorting out files in "/home/":

This is just a hack, the backend is still computing "/home/".

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> This is just a hack, the backend is still computing "/home/".

Every solution will be a hack, since the backend doesn't support
negation.

But obviously, my suggestion can lead to long delays until matches
appear, so I agree that this is not so great.  Too bad.

**Comment by michael-heerdegen** [comment]
Anyway, thanks for listening.
