### ISSUE TITLE
Fuzzy matching only selects files

### ISSUE THREAD

**Issue by lvh** [emacs-helm/helm#909]
This happened after my current helm upgrade from MELPA. Previous one was no more than a week or so old.

Basically, non-boring non-file buffers like e.g. `*Messages*` can no longer be reached by fuzzy search. When I start typing, only files are shown. For example:

![screen shot 2015-03-11 at 4 21 21 pm](https://cloud.githubusercontent.com/assets/97816/6609095/c5e2e7b6-c80a-11e4-93dd-b872b038a0c1.png)
![screen shot 2015-03-11 at 4 21 38 pm](https://cloud.githubusercontent.com/assets/97816/6609096/c6015b1a-c80a-11e4-9123-dfda8b63dbde.png)

**Comment by thierryvolpiatto** [comment]
lvh <notifications@github.com> writes:

> This happened after my current helm upgrade from MELPA. Previous one
> was no more than a week or so old.
>
> Basically, non-boring non-file buffers like e.g. *Messages* can no
> longer be reached by fuzzy search. When I start typing, only files are
> shown. For example:

Same as (#903), it is not related to fuzzy.
Update helm, it has been fixed.

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by lvh** [comment]
Awesome, thanks!
