### ISSUE TITLE
Is there an option to display the match candidates alphabetically ordered?

### ISSUE THREAD

**Issue by triklsbg** [emacs-helm/helm#912]
![helm_candidates1](https://cloud.githubusercontent.com/assets/3647083/6629097/a26f3b5c-c90b-11e4-94d9-dc37b2d2dcae.jpeg)

What makes the longest candidate to the "best" match of the depicted case ?
Perhaps you can accompanie the case-agnostic-ascii-sorted candidates with a match score number ? Lists with more than lets say 10 candidates which are not obviasly sorted look irritating, i think not only to me.

Thank you

**Comment by thierryvolpiatto** [comment]
triklsbg <notifications@github.com> writes:

> Perhaps you can accompanie the case-agnostic-ascii-sorted candidates with a match score number ? Lists with more than lets say 10 candidates which are not obviasly
> sorted look irritating, i think not only to me.

It's would be stupid to change the sorting function, which is adapted to
fuzzy, alpha sorting is non--sense here, but if you really want this you
can write your own function and add it here:

(defmethod helm-setup-user-source ((source helm-source-ffiles))
  (oset source :filtered-candidate-transformer 'my-own-sort-function))

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Don't know why I thought we were speaking of *find-files here, sorry.
What you want to modify here is helm-comp-read sorting, though you should use helm-apropos instead of this.

**Comment by thierryvolpiatto** [comment]
So now candidates are sorted like in helm-apropos, should be enough.
If you really want to use C-h f/v to list your symbols, and what helm is currently providing is not what you want, you can write your own function and add it to `helm-completing-read-handlers-alist`.
