### ISSUE TITLE
Helm implementation of read-file-name doesn't return the correct default value

### ISSUE THREAD

**Issue by giordano** [emacs-helm/helm#913]
The doc string of `read-file-name` reads

> If `DEFAULT-FILENAME` is omitted or
nil, then if `INITIAL` is non-nil, the default is `DIR` combined with
`INITIAL`; otherwise, if the current buffer is visiting a file,
that file serves as the default; otherwise, the default is simply
the string inserted into the minibuffer.

but helm implementation of that function returns by default the first selected file (usually "." I think) if both `default-filename` and `initial` are nil even when the buffer is visiting a file.

**Comment by michael-heerdegen** [comment]
Indeed, we are not conform here.

Though the vanilla behavior is also a bit strange - you confirm one string and get another one as result.

May I ask for which use case the current behavior of helm is problematic?

**Comment by thierryvolpiatto** [comment]
Should be fixed now, if you find some corner cases, let me know.
Also fixed when default-filename is a list (was returning the list instead of its car).

**Comment by giordano** [comment]
I found this bug using AUCTeX: `TeX-master-file-ask' always inserted `"."` instead of t, as it should be for the default case.  After the last commit it works as expected.  Thank you so much!  I'm closing this ticket.
