### ISSUE TITLE
Add full command next to an aliased command

### ISSUE THREAD

**Issue by tuhdo** [emacs-helm/helm#914]
I have a list of aliased commands for convenient and not wasting key bindings, i.e. `M-x eb` to `eval-buffer`. It would be nice if the full command is shown next to it, so I can narrow to both commands: the abbreviated and the full ones. This is useful in case when I forgot some command that I aliased long time ago and when needing the command again, I type its full form and realized that there is the abbreviated form of that command. The next time, I would remember to use the abbreviated version instead.

It is also nice to know which command is aliased and not a real command.

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> I have a list of aliased commands for convenient and not wasting key
> bindings, i.e. M-x eb to eval-buffer.

A bad idea, doing this you are just polluating your symbol namespace,
adding names with no meaning you don't remember yourself.

Specially with fuzzy, typing a pattern such as "evb" make eval-buffer
popping up in first position...

So no, sorry I don't want to make this happen.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment]
That's hust an example. Perhaps you could think the aliases are just key bindings to be executed after pressing M-x. Or you could do the other way around: show the abbreviated command with prefix "alias: " next to the full command if available.

**Comment by tuhdo** [comment]
For example, next to eval-buffer will be "alias: eb". The "alias" part is in normal text while "eb" has the same highlighting as other key bindings in helm-m-x.

**Comment by michael-heerdegen** [comment]
FWIW, Emacs 25 now has something similar: if you type e.g. M-x eval-buffer RET, you get a message "You can run the command `eval-buffer' with M-x ev-b RET" (if there is no real key binding for the command).

There are also things like command abbrevs implemented somewhere.  I don't use such stuff.

**Comment by tuhdo** [comment]
Alias is quite convenient, especially if you want to use commands that are not so frequently but nice to use when you have chance. i.e. sometimes I use `delete-matching-lines` to delete certain lines. Intead of `M-x line match` or some fuzzy patterns, I could just type `M-x dml` and `helm-M-x` always gives me the alias as first result. It should be. But sometimes I forgot and type full command i.e. `M-x del mat lin` that I already defined an alias. In this case, showing that I have an alias is nice since it reinforces me about the shortcut in the future, similar to how `helm-M-x` has been helping me with the key bindings..

**Comment by michael-heerdegen** [comment]
I agree that having something like that would probably be good, but like Thierry I don't like using aliases for that purpose.

AFAICT, in Icicles there is some mechanism like that built on top of its M-x implementation, by providing an abbrev mapping  for commands.

**Comment by thierryvolpiatto** [comment]
With fuzzy one can type delml => delete-matching-lines, evb => eval-buffer etc...
