### ISSUE TITLE
Make RET move into a directory and backspace move out

### ISSUE THREAD

**Issue by tuhdo** [emacs-helm/helm#915]
@thierryvolpiatto Since you consider `helm-find-files` a Dired replacement, would it be better to bind `RET` to move into a directory and backspace to move out of directory? To enter Dired, simply press `M-Ret`. It would make `helm-find-files` even more friendly to many people who are used to Ido.

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> @thierryvolpiatto Since you consider helm-find-files a Dired
> replacement, would it be better to bind RET to move into a directory
> and backspace to move out of directory? To enter Dired, simply press
> M-Ret. It would make helm-find-files even more friendly to many people
> who are used to Ido.

No, this have been already asked, but no I don't want this happen.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
