### ISSUE TITLE
Switching buffers in erc doesn't work

### ISSUE THREAD

**Issue by rpglover64** [emacs-helm/helm#916]
Pressing <kbd>C-c C-b</kbd> in erc should bring up a list of buffers, and it does, but the list is weirdly formatted and switching to a pressing enter yields the "[Display not ready]" message.

**Comment by thierryvolpiatto** [comment]
Alex R <notifications@github.com> writes:

> Pressing C-c C-b in erc should bring up a list of buffers, and it
> does, but the list is weirdly formatted and switching to a pressing
> enter yields the "[Display not ready]" message.

iswitchb is not supported and is deprecated, I don't know why it is
still used in emacs, just disable helm completion for this:

(add-to-list 'helm-completing-read-handlers-alist '(erc-iswitchb))

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Erc should allow customizing this or better just use `read-buffer`.

**Comment by rpglover64** [comment]
How would one go about writing a handler that only presents the appropriate buffers (erc buffers related to the same server, or all erc buffers when given a prefix argument)?

**Comment by thierryvolpiatto** [comment]
Alex R <notifications@github.com> writes:

> How would one go about writing a handler that only presents the
> appropriate buffers (erc buffers related to the same server, or all
> erc buffers when given a prefix argument)?

If you want to write an handler, you can reopen this bug.

Here a first shot, fully not tested, but it can be a good starting point.

(defun helm-erc-iswitchb (prompt _collection _test _require-match _init
                          _hist _default _inherit-input-method _name _buffer)
  (run-hooks 'iswitchb-make-buflist-hook)
  (let ((helm--reading-passwd-or-string t))
    (helm-comp-read prompt iswitchb-temp-buflist
                    :default (if (boundp 'erc-modified-channels-alist)
                                 (buffer-name (caar (last erc-modified-channels-alist)))
                                 nil)
                    :must-match t)))
(add-to-list 'helm-completing-read-handlers-alist '(erc-iswitchb . helm-erc-iswitchb))


NOTE: the best would be to fix this function (erc-iswitchb) upstream.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Thierry Volpiatto <thierry.volpiatto@gmail.com> writes:

> NOTE: the best would be to fix this function (erc-iswitchb) upstream.

Like this (probably you can use this waiting a fix upstream):

(defadvice erc-iswitchb (around no-iswitchb activate)
  (switch-to-buffer
   (completing-read "Switch-to: "
                    (mapcar 'buffer-name
                            (erc-buffer-list
                             nil
                             (when arg erc-server-process)))
                    nil t nil nil
                    (when (boundp 'erc-modified-channels-alist)
                      (buffer-name (caar (last erc-modified-channels-alist)))))))

So no need to modify helm-completing-read-handlers-alist with this.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Thierry Volpiatto <thierry.volpiatto@gmail.com> writes:

> Thierry Volpiatto <thierry.volpiatto@gmail.com> writes:
>
>> NOTE: the best would be to fix this function (erc-iswitchb) upstream.

I have submitted a bug report (bug#20116).

http://debbugs.gnu.org/cgi/bugreport.cgi?bug=20116

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Now fixed in emacs-25, closing, if you want compatibility in other version, use the defadvice, you can test with `(when (fbound 'erc-iswitchb) (defadvice [...]))`.

**Comment by rpglover64** [comment]
Thank you.
