### ISSUE TITLE
The header line is not hidden after starting Helm

### ISSUE THREAD

**Issue by tuhdo** [emacs-helm/helm#918]
It is only hidden when I move point to the end of buffer. This is when I set `helm-display-header-line` to `nil`.

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> It is only hidden when I move point to the end of buffer. This is when I set helm-display-header-line to nil.

Probably something wrong on your side, double check, it is working fine
here.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment]
I tested with `./emacs-helm.sh`. When I set it to nil, I still get the big header line "Find Files (`C-l': Go up on level)".

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> I tested with ./emacs-helm.sh. When I set it to nil, I still get the
> big header line "Find Files (`C-l': Go up on level)".

This is not the header-line, this should not be removed (never).

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment]
Why not? After using Helm for so long, I don't need such info, and in default them it costs 2 lines, along with header line that is 3 lines in total.

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> Why not?

Many infos are fetched from there, it is used also as separator when
using multiple sources, If you remove this you break helm in many parts.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment]
I see. Is it possible to turn it off when Helm detects there's only a single source? Of course, only when user enables it to do so.

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> I see. Is it possible to turn it off when Helm detects there's only a
> single source? Of course, only when user enables it to do so.

No.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment]
Actually I found out how to customize it with the face `helm-source-header`. Setting the height to 0.1 gives me what I want.

**Comment by tuhdo** [comment]
This is what I did: turn on the header line when there's multiple sources and turn off when there's one:

```elisp
(defun helm-toggle-header-line ()
  ;; (message "helm-sources is %s" helm-sources)
  (message "length: %d" (length helm-sources))
  (if (= (length helm-sources) 1)
      (set-face-attribute 'helm-source-header nil :height 0.1)
    (set-face-attribute 'helm-source-header nil :height 1.0)))

(add-hook 'helm-before-initialize-hook 'helm-toggle-header-line)
```

I'm pretty satisfied.

**Comment by thierryvolpiatto** [comment]
Jim Myhrberg <notifications@github.com> writes:

> As of December 2018, @tuhdo's solution doesn't work as is. It looks
> like the helm-sources variable is no longer global, so I've had to
> modify his solution for it to work with the latest helm version:
>
> (defun helm-toggle-source-header-line ()
>   (if (= (length (ignore-errors (with-helm-buffer helm-sources))) 1)
>       (set-face-attribute 'helm-source-header nil :height 0.1)
>     (set-face-attribute 'helm-source-header nil :height 1.0)))
>
> (add-hook 'helm-after-initialize-hook 'helm-toggle-source-header-line)
>
> It doesn't seem to work with helm-projectile related invocations, the
> with-helm-buffer function throws an error.

If with-helm-buffer throws an error, it is there is something wrong in
helm-projectile, not helm, please report to helm-projectile.
The code above is working as expected in regular helm (without ignore-errors).

> That's why I've wrapped it in ignore-errors so helm still works as
> expected, despite showing the source header for helm-projectile stuff.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.*


--
Thierry
