### ISSUE TITLE
Set helm-source-header to 1.0 in height by default

### ISSUE THREAD

**Issue by tuhdo** [emacs-helm/helm#920]
When Helm is started with default theme (i.e. `emacs-helm.sh`), the source header line is *HUGE* (it seems like the default value is 2.0). It bothers many users to use Helm because it consumes screen space. If you look at my screenshots on the homepage, you will see that the header line is at 1.0 . I think the current helm-source-header is distinguishable enough (different background colour and with a box), I don't think we need to make it huge.

**Comment by thierryvolpiatto** [comment]
The default is 1.3 and is good, I want to keep this value.
