### ISSUE TITLE
Treat more cases to use helm-completing-read-symbols

### ISSUE THREAD

**Issue by michael-heerdegen** [emacs-helm/helm#921]
Hello,

the first part of this issue is an easy request: add trace-function[-background] to helm-completing-read-handlers-alist to use helm-completing-read-symbols.

The second part, mmh, maybe don't.  I wonder whether we can do better than adding to a hardcoded list in this case.

As I currently see, all elements of helm-completing-read-handlers-alist whose cdr is helm-completing-read-symbols are actually cases where completing-read is called with obarry as COLLECTION arg in the original code.  Maybe we could autodetect this case in helm--completing-read-default and DTRT.

I don't like doing, this, too (assuming you dislike the idea), but the exception list is not so beautiful as well.. . WDYT?  Thanks.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Hello,
>
> the first part of this issue is an easy request: add
> trace-function[-background] to helm-completing-read-handlers-alist to
> use helm-completing-read-symbols.

Will do.


> The second part, mmh, maybe don't. I wonder whether we can do better
> than adding to a hardcoded list in this case.
>
> As I currently see, all elements of
> helm-completing-read-handlers-alist whose cdr is
> helm-completing-read-symbols are actually cases where completing-read
> is called with obarry as COLLECTION arg in the original code. Maybe we
> could autodetect this case in helm--completing-read-default and DTRT.

You can know COLLECTION is a vector, a function or whatever (it can come
in many diverses form) but you don't know if what come to you have been
initiated in original code as OBARRAY.

> I don't like doing, this, too (assuming you dislike the idea), but the
> exception list is not so beautiful as well.. .

I don't know what is "no so beautiful" in
`helm-completing-read-handlers-alist' but I am very happy with it, it
provide a lot of flexibility.

> WDYT?

I think we don't need this.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> You can know COLLECTION is a vector, a function or whatever (it can
> come in many diverses form) but you don't know if what come to you
> have been initiated in original code as OBARRAY.

I though there is only one obarray, and as argument is it passed by
reference, as in

(let ((test obarray))
  (intern "sdfgdbg")
  (eq test obarray))

==> t

With other words, using (eq the-arg obarray) as test should be perfectly
fine.  I think the suggestion is not as dumb as it sounds.  We would
safely catch all cases we currently hardcode, plus commands maybe
defined by the user.

But if you don't like the idea, please close.

> I don't know what is "no so beautiful" in
> `helm-completing-read-handlers-alist' but I am very happy with it, it
> provide a lot of flexibility.

I also do not want to get rid of it.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Thierry Volpiatto <notifications@github.com> writes:
>
>> You can know COLLECTION is a vector, a function or whatever (it can
>> come in many diverses form) but you don't know if what come to you
>> have been initiated in original code as OBARRAY.
>
> I though there is only one obarray, and as argument is it passed by
> reference, as in
>
> (let ((test obarray))
> (intern "sdfgdbg")
> (eq test obarray))
>
> ==> t
>
> With other words, using (eq the-arg obarray) as test should be perfectly
> fine.

Yes you are right, but it may come in other forms, the completing-read
can be called with a mapatoms call as COLLECTION, or a loop or anything
else.


> I think the suggestion is not as dumb as it sounds. We would safely
> catch all cases we currently hardcode, plus commands maybe defined by
> the user.

What we have actually is enough, we are going to complicate things for
no benefit, there is tons of things much more important to fix actually
in helm.

> But if you don't like the idea, please close.

Thanks for your understanding.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
