### ISSUE TITLE
TRAMP is broken

### ISSUE THREAD

**Issue by ineu** [emacs-helm/helm#923]
.. in 01205d25fd87306a9f19873ca667f03e9f09b096, according to `git blame`.
How to reproduce:
Start `helm-find-files`.
type `/ssh:u` (for **u**sername)
on first letter after `u` error comes:
`Error running timer: (wrong-type-argument stringp nil)`

**Comment by thierryvolpiatto** [comment]
Eugene Diachkin <notifications@github.com> writes:

> .. in 01205d2, according to git blame.
> How to reproduce:
> Start helm-find-files.
> type /ssh:u (for username)
> on first letter after u error comes:
> Error running timer: (wrong-type-argument stringp nil)

Thanks, should be fixed now.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by ineu** [comment]
It is, thank you.
