### ISSUE TITLE
Error running timer: (wrong-type-argument stringp nil) when add dotted files to helm-boring-file-regexp-list

### ISSUE THREAD

**Issue by tuhdo** [emacs-helm/helm#924]
So, I added the dotted files `.` and `..` to hide it but got the above error.

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> So, I added the dotted files . and .. to hide it but got the above error.

I guess you have this from helm-find-files, please always send what you
are exactly running.
You should not do this for helm-find-files, it is now prevented.
IOW your regexp will have no effect in helm-find-files.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment]
Sorry about that I will be more specific next time. But, why are dotted files invalid to ignore?

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> Sorry about that I will be more specific next time. But, why are
> dotted files invalid to ignore?

They are an important part of the helm-find-files mechanism.


-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment]
Alright. then.

**Comment by asok** [comment]
@tuhdo I think that `helm-files` without those dotted files is much nicer. If I want to go to one level up I just hit `C-l`. In such usage scenario those entries seem like a noise to me.
Could `helm-files` be refactored to not needing them?

**Comment by thierryvolpiatto** [comment]
Adam Sokolnicki <notifications@github.com> writes:

> Could helm-files be refactored to not needing them?

No.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by listx** [comment]
Is there a way to move the `.` and `..` files to the bottom?

**Comment by thierryvolpiatto** [comment]
Linus <notifications@github.com> writes:

> Is there a way to move the . and .. files to the bottom?

No.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
