### ISSUE TITLE
Handle winner-mode

### ISSUE THREAD

**Issue by tuhdo** [emacs-helm/helm#925]
At the moment, I have to copy your code for handling winner-mode [here](https://github.com/thierryvolpiatto/emacs-tv-config/blob/152ae87028971dd1e1491654aee58dca0af3a6b3/.emacs.el#L1709). Isn't it better to handle it from within Helm, so user won't get surprise when using Helm with `winner-mode`?

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> At the moment, I have to copy your code for handling winner-mode
> here. Isn't it better to handle it from within Helm, so user won't get
> surprise when using Helm with winner-mode?

Now you can just:

(add-hook 'helm-cleanup-hook #'helm-handle-winner-boring-buffers)

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment]
Great. It's much simpler. Is it possible to add that hook by default? After all, user should not be aware about this. Otherwise. in the future someone will ask the same thing again.

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> Great. It's much simpler. Is it possible to add that hook by default?
> After all, user should not be aware about this. Otherwise. in the
> future someone will ask the same thing again.

Really I don't know yet what to do, because I know many people have copied/pasted
the old code in their config files.
Of course the old snippet of code and this hook should not clash, but
well...
May be an entry in the FAQ would be enough?

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment]
Did it break something seriously? I will test if there's any problem. If not, then it should be enabled by default. Otherwise, yes, at least you should put an entry in FAQ or better, somewhere more visible on the homepage, probably in "Basic Usage" section.

**Comment by thierryvolpiatto** [comment]
Finally added hook by default.

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
