### ISSUE TITLE
helm-selection-line face and light frame background

### ISSUE THREAD

**Issue by michael-heerdegen** [emacs-helm/helm#926]
The helm-selection-line face def doesn't distinguish the frame's background mode.  With light background, it is much too dark, and covered text is hardly readable.

And does it really have to use underline?

Thanks!

**Comment by michael-heerdegen** [comment]
Personally, I have used this for a while (i.e. khaki for light bg):

```
((((class color) (background light)) (:background "khaki"))
 (((class color) (background dark))  (:background "#371717")) ;like default, but darker
      )
```

**Comment by michael-heerdegen** [comment]
Much better, thanks.  Though I would prefer a solution that avoids setting :foreground.  But probably not with khaki.

Maybe I can find something that works by rotating the hue value of the highlight face (which obviously suffices with setting background) - unless you don't want that.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Much better, thanks. Though I would prefer a solution that avoids
> setting :foreground.

What's the problem with foreground ?

> But probably not with khaki.
>
> Maybe I can find something that works by rotating the hue value of the
> highlight face (which obviously suffices with setting background) -
> unless you don't want that.

I don't understand what you want to to, sorry.
That make me think you want to do something complicated, and I want
to keep things simple for defining faces.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> What's the problem with foreground ?

Erasing the font lock colors.  Not the end of the world, OTOH, if we can
avoid it, that would be better.

> > Maybe I can find something that works by rotating the hue value of
> > the highlight face (which obviously suffices with setting
> > background) - unless you don't want that.
>
> I don't understand what you want to to, sorry.
> That make me think you want to do something complicated, and I want
> to keep things simple for defining faces.

It meant that I wanted to look for a better color.  Nothing complicated
in helm.


Would you consider making helm-selection-line simply inherit from the
"highlight" face?  Pros:

- it is guaranteed to work with font-lock foreground colors, thus, no
  need to change foreground explicitly

- would still look good with custom themes

- it's easy

- users are already accustomed to the color for highlighting purposes,
  it feels natural

**Comment by tuhdo** [comment]
I agree with @michael-heerdegen that making Helm faces inherit as much as possible for compatibility with themes. Current only a few themes support Helm to make it looks nice such as `Zenburn` or `Monokai`.

**Comment by michael-heerdegen** [comment]
Thanks!
