### ISSUE TITLE
Filtering not working on tramp home directory

### ISSUE THREAD

**Issue by jeeger** [emacs-helm/helm#928]
Greetings! Another tramp bug, I'm afraid:

When I use tramp to connect to a remote host via C-x C-f '/host:', tramp successfully displays the file list of the user's home directory. However, entering anything to filter that file list leads to an empty tramp file list. However, in a URL like "/host:/etc/", filtering works correctly.

**Comment by thierryvolpiatto** [comment]
jeeger <notifications@github.com> writes:

> Greetings! Another tramp bug, I'm afraid:
>
> When I use tramp to connect to a remote host via C-x C-f '/host:',
> tramp successfully displays the file list of the user's home
> directory. However, entering anything to filter that file list leads
> to an empty tramp file list. However, in a URL like "/host:/etc/",
> filtering works correctly.

It's not a bug, at first connection, you have to expand path with C-j
before typing something.
When the connection is established, "/ssh:host:" expand directly
minibuffer to "/ssh:host:/home/you".

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by jeeger** [comment]
Yeah, that works now. Strange, I normally have helm-ff-auto-update-initial-value set to t, so this should have updated automatically. No matter, thanks for your quick reply!

**Comment by thierryvolpiatto** [comment]
jeeger <notifications@github.com> writes:

> Yeah, that works now. Strange, I normally have
> helm-ff-auto-update-initial-value set to t,

Even with this (I use this too), you will always have at the first
connection the minibuffer not expanded, you can reproduce with 
M-x tramp-cleanup-all-connections, and C-x C-f /ssh:host: , once you
quit helm and redo C-x C-f /ssh:host: you minibuffer will now be
expanded to /ssh:host:/home/you.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
