### ISSUE TITLE
How can i config the default input of helm-semantic-or-imenu

### ISSUE THREAD

**Issue by zijianyue** [emacs-helm/helm#929]
Because I just want to see functions in most case.
By the way , I think in C/C++ mode ,displaying function param in helm-semantic-or-imenu as one line is a little bit wasteful .
![image](https://cloud.githubusercontent.com/assets/6119928/6723314/1d6028fc-ce21-11e4-92ca-452a822a2c74.png)

**Comment by tuhdo** [comment]
I will add some styles to make it adaptable to different needs.

**Comment by tuhdo** [comment]
Please reopen it. It's not yet merged.

**Comment by tuhdo** [comment]
@zijianyue if you want to narrow to functions only, just type `f` in the pattern prompt.

**Comment by thierryvolpiatto** [comment]
@tuhdo I have merged your PR yesterday night, thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by zijianyue** [comment]
Thanks for your work! I found that in the .h files ,contents in a struct  are displayed which cause the user can not see the file outline clearly at the first glance.This is just my opinion.
![image](https://cloud.githubusercontent.com/assets/6119928/6765390/eadcc2a6-d018-11e4-870b-ec89372da766.png)
