### ISSUE TITLE
Speedup full outline path in org helm candidates

### ISSUE THREAD

**Issue by SkydiveMike** [emacs-helm/helm#933]
c22e412d391ee4103ea478b3df21cd07e882d88c adds full outline path to Org Helm Candidates; very useful—but very slow with many, large Org files. Can this use  the [fast mode](http://orgmode.org/cgit.cgi/org-mode.git/tree/lisp/org.el?id=6f66c57e61703ff899cf1f6eeb6317285c7235c5#n11671) of `org-get-outline-path`? Could this be made optional via a new `defcustom`?

**Comment by thierryvolpiatto** [comment]
Fixed by da915e6.
