### ISSUE TITLE
Fix Helm compatibility with themes

### ISSUE THREAD

**Issue by tuhdo** [emacs-helm/helm#935]
Currently the face is unusable in `dark-theme`. I think it should inherit from a built-in face to differentiate from the `helm-ff-directory`.

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> Currently the face is unusable in dark-theme.

Just tried now with dark-theme1/2/3 and I didn't see what's the problem.

What do you mean by unusable ?

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment]
Sorry about the wording but I tested it on a theme with gray background and couldn't read. Anyway, it still looks ugly on dark theme with dark background. I propose that `helm-ff-dotted-directory` should use the background of `default` face as background and use any of `font-lock-*` (i.e. `font-lock-constant-face`) as foreground for consistency.

**Comment by thierryvolpiatto** [comment]
You should be able to read on gray background as the foreground is black isn't it ?
I do use dark background:

![screenshot_-_21032015_-_09 47 20](https://cloud.githubusercontent.com/assets/1533939/6764443/1474864e-cfb0-11e4-83f0-d3c3c2bd2f9f.png)

**Comment by tuhdo** [comment]
Well it was in terminal. Don't you think that `helm-find-files` looks better without all the backgrounds on directories? It's annoying when I use it in terminal. Here is how it look likes in default theme:

![helm-ff-terminal](https://cloud.githubusercontent.com/assets/4818719/6764500/5eacb3ec-cfe4-11e4-9193-93b5f31a047f.gif)

In the above example, `blog` is the only directory. Imagine how it would look like when I have 10 or more directories.

Here is how it looks like with Zenburn (which makes Helm look really nice in GUI version but failed with terminal):

![helm-ff-terminal-zenburn](https://cloud.githubusercontent.com/assets/4818719/6764505/94c97cda-cfe4-11e4-89e7-18111e9edcdf.gif)

Here is how Zenburn in GUI looks like:

![helm-ff](https://cloud.githubusercontent.com/assets/4818719/6764482/c0948928-cfe3-11e4-9531-bf264a7af542.gif)

The theme was nice with `helm-find-files` before the dotted face was added. I think we should reuse internal faces to make Helm compatible with more themes out there.

**Comment by tuhdo** [comment]
In the above screenshots in terminal, I forgot to enable 256 colours. With 256 colours, it looks better but still hard to read compare with `helm-ff-directory`:

![helm-ff-terminal-zenburn-256](https://cloud.githubusercontent.com/assets/4818719/6764561/4b572bf2-cfe8-11e4-9bad-44dfcc3cabec.gif)

**Comment by tuhdo** [comment]
Here is how Helm looks in default theme with 256 colours:

![helm-ff-terminal-default](https://cloud.githubusercontent.com/assets/4818719/6764563/b6e2b40e-cfe8-11e4-8a2c-b27d27b4781f.gif)

**Comment by thierryvolpiatto** [comment]
BTW Do you know the command `customize-themes', it allow you to
customize your themes...

This added to the ability of customizing faces individually, I think you
should be able to customize you emacs properly.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment]
Yes, I know that command. But I think it would be better to not add overhead for users (especially the ones new to Helm) to handle the incompatibility between Helm and their existing themes. There are themes that I really want to try but I don't really want spend time choosing colors that fit the themes. So I use a few themes like `Zenburn` or `Monokai` that actually supports Helm.

If we can solve this incompatibility issue, it is a great help to new Helm users to have less hassle to deal with.

**Comment by tuhdo** [comment]
And I don't have to add to my guide for new users to handle this theme issue.

**Comment by tuhdo** [comment]
Ok I changed the title to "Fix Helm compatibility with themes" to correctly reflect the problem.

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> Yes, I know that command. But I think it would be better to not add
> overhead for users (especially the ones new to Helm) to handle the
> incompatibility between Helm and their existing themes. There are
> themes that I really want to try but I don't really want spend time
> choosing colors that fit the themes. So I use a few themes like
> Zenburn or Monokai that actually supports Helm.
>
> If we can solve this incompatibility issue, it is a great help to new
> Helm users to have less hassle to deal with.

They will face the same problem with other packages that use like me
:foreground and :background, and they are many, among them packages that
come with emacs like gnus, whiteline etc...

IOW I don't want spending my time writing defface's, I have things much
more important in helm actually to fix, so if you want to modify faces,
you can, just send PR's, but IMO it is wasting your time, most of the
time, you will always find users not happy with what you provide.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment]
Sure I will try and see if it is fixable and send PR. I will make Helm faces inherit from built-in faces as much as possible.

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> Sure I will try and see if it is fixable and send PR. I will make Helm
> faces inherit from built-in faces as much as possible.

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
@tuhdo I appreciate your efforts here, if you need a second opinion, don't hesitate to ask me.

**Comment by tuhdo** [comment]
Actually I'm fine with this now. As more people use Helm, many themes start supporting in. It's just that the default themes come with Emacs look terrible with Helm though. I wish Helm could look better with `wombat`.
