### ISSUE TITLE
Helm performance decays to unusability

### ISSUE THREAD

**Issue by WorldsEndless** [emacs-helm/helm#936]
After a full day or two of heavy usage I find that Helm becomes unusably slow until I restart emacs; we're talking, 5+ second delays when I hit C-x b (helm-mini) or M-x (display commands). I've tried killing all temporary buffers, but it doesn't help. Neither does disabling and re-enabling helm mode. What's the solution to "clear the caches"? Everything else in emacs runs quick, as long as I don't need to change buffers (ouch). 

**EDIT** Other times it just seems to get back to business as it should, but not right when I need it to. What's going on? How can I force a helm reboot or refresh? 

GNU Emacs 25.0.50.6 (x86_64-unknown-linux-gnu, GTK+ Version 3.10.9) of 2015-02-10 on localhost.localdomain

**Comment by thierryvolpiatto** [comment]
Tory S. Anderson <notifications@github.com> writes:

> After a full day or two of heavy usage I find that Helm becomes
> unusably slow until I restart emacs; we're talking, 5+ second delays
> when I hit C-x b (helm-mini) or M-x (display commands). I've tried
> killing all temporary buffers, but it doesn't help.

You don't have to do that.

> Neither does disabling and re-enabling helm mode. What's the solution
> to "clear the caches"?

There is no cache you have to "clear".

> Everything else in emacs runs quick, as long as I don't need to change
> buffers (ouch).

I guess it is not a problem with helm but your emacs, try to use
emacs-24 during some days to see what happen.

I use sometimes emacs during several days with many buffers (100~150)
and never had such problem.
 
> EDIT Other times it just seems to get back to business as it should,
> but not right when I need it to.

Hmm, don't understand this sentence, sorry.

> What's going on? How can I force a helm reboot or refresh?

See above I guess you problem comes from emacs, not helm.

> GNU Emacs 25.0.50.6 (x86_64-unknown-linux-gnu, GTK+ Version 3.10.9) of
> 2015-02-10 on localhost.localdomain

As said above try a stable version of emacs.


NOTE: helm is at the front end of everything and as soon there is a
crash or an emacs problem helm is the first to suffer of this and people
have a tendency to immediately blame it.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by WorldsEndless** [comment]
I first noticed this happening occasionally with emacs 24.3, so I don't think it has to do with bleeding edge Emacs. Thanks for the notes about how helm works and can be misdiagnosed. Do you know of a way of monitoring the resources that emacs is consuming to try and diagnosing such things? Or why the  non-helm versions of the commands would be working fine?

**Comment by tuhdo** [comment]
It would be useful to know:

- Do you have fuzzy matching enabled?
- Do you use `workgroups2`? When I use `workgroups2` with Helm and especially when fuzzy matching is enabled, Helm is getting slow really quick.

**Comment by michael-heerdegen** [comment]
As for lots of such issues, M-x profiler is a simple yet powerful mean to find out where the time is spent.

**Comment by thierryvolpiatto** [comment]
Tory S. Anderson <notifications@github.com> writes:

> I first noticed this happening occasionally with emacs 24.3, so I
> don't think it has to do with bleeding edge Emacs. Thanks for the
> notes about how helm works and can be misdiagnosed. Do you know of a
> way of monitoring the resources that emacs is consuming to try and
> diagnosing such things?

Well top or htop running aside emacs can tell you what emacs is consuming.
Verify also the emacs processes running in your emacs (M-x
helm-list-emacs-process)
But I guess that when you experiment slowdown, emacs is consuming a lot
of memory.
Also check if you are using tramp that you don't have remote processes
running, specially file copying.
Also if you have a /tmp directory mounted in tmpfs, be carefull with tramp
when copying large files, as it will use all you memory in few time.
(i.e it is first copying to /tmp before copying to remote).


> Or why the non-helm versions of the commands would be working fine?

Because they are not completing at first.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by WorldsEndless** [comment]
Thanks all; profiler is new to me and I'll be using it. I'm very familiar with the tramp problems and go to lengths to kill tramp buffers when I'm done now. I've only recently started playing with workgroups and don't do much with them right now, so I doubt that has effected much. I do have fuzzy matching on; however, the real wait problem is BEFORE any typing has been done (initial call with M-x or to C-x b). For what it's worth, I grabbed these settings from some of the documentation, I think: 

    (setq helm-quick-update                     t ; do not display invisible candidates
	  helm-split-window-in-side-p           t ; open helm buffer inside current window, not occupy whole other window
	  helm-buffers-fuzzy-matching           t ; fuzzy matching buffer names when non--nil
	  helm-move-to-line-cycle-in-source     t ; move to end or beginning of source when reaching top or bottom of source.
	  helm-ff-search-library-in-sexp        t ; search for library in `require' and `declare-function' sexp.
	  helm-scroll-amount                    8 ; scroll 8 lines other window using M-<next>/M-<prior>
	  helm-ff-file-name-history-use-recentf t)

I'll keep my eyes peeled next time it occurs.

**Comment by tuhdo** [comment]
@WorldsEndless That's it. As I suspected, you are using `workgroups2` AND fuzzy matching on. I had the same problem before, and Helm quickly gets performance degrade even after a few times, and yes, this is just opening Helm window, not even entering something. You should try disabling or remove `workgroups2`and use Helm again to see if the problem still persists. I had to remove `workgroups2` and look for the alternative.
