### ISSUE TITLE
Feature request: step through helm-resume

### ISSUE THREAD

**Issue by WorldsEndless** [emacs-helm/helm#937]
As is mentioned in documentation, helm-resume is valuable enough to be bound to its own short keys. I also see that I can get to any previous helm session by passing a prefix arg. But it seems obvious (and would be extremely convenient) that there should be a way to cycle through those helm sessions without needing to select from a menu, similar to Winner-mode or undo function. 

Perhaps repeated callings of helm-resume could serve to continue cycling through helm sessions?

**Comment by thierryvolpiatto** [comment]
After writing and trying this (i.e cycling in helm-buffers from helm-resume) I am not convinced it is a good idea, it is much more efficient IMO to use `C-x C-b`, so I will not introduce this in helm.
Thus it add more code to helm with possible conflicts with keybinding, need also to inline code from
other library or depend on it.

**Comment by talwrii** [comment]
To be clear, I think not including this feature in helm on the grounds of minimising code size is completely reasonable.

However, my poor feeble brain really dislikes the multitasking of finding the correct helm buffer while doing something else, and cycling can avoid this do a degree

For other people like me here is a hacky implementation of this feature that can be used outside of helm. Be aware that this will shadow the C-o and C-i keybindings in helm *everywhere*.   Also this is potentially a little friendly with the innards of helm, but in practice I think the features it relies on are unlikely to change...

```
(defvar hf-helm-resume-next-key (kbd "C-o"))
(defvar hf-helm-resume-prev-key (kbd "C-i"))

(defun hf-helm-resume ()
  (interactive)
  (define-key helm-map hf-helm-resume-next-key 'hf-helm-resume-next)
  (define-key helm-map hf-helm-resume-prev-key 'hf-helm-resume-prev)
  (set-default 'helm-map helm-map)
  (setq hf-helm-resume-index 1)
  (helm-resume (nth 0 helm-buffers)))


(defun hf-helm-resume-incr (incr)
  (let (callback)
    (setq callback
          (lexical-let ((lexical-incr incr))
            (lambda ()
                         (let ((resume-buffer (nth hf-helm-resume-index helm-buffers)))
                           (setq hf-helm-resume-index  (hf-uniq-mod (+ hf-helm-resume-index lexical-incr) (length helm-buffers )))
                           (helm-resume resume-buffer)))))
    (helm-run-after-exit callback)))

(defun hf-helm-resume-next ()
  (interactive)
  (hf-helm-resume-incr 1))

(defun hf-helm-resume-prev ()
  (interactive)
  (hf-helm-resume-incr -1))

(defun hf-uniq-mod (a b)
  "% returns negative index if input is negative"
  (let (maybe-neg-rep some-pos-rep)
    (setq maybe-neg-rep (% a b))
    (setq some-pos-rep (+ b maybe-neg-rep))
    (% some-pos-rep b)))

```

**Comment by michael-heerdegen** [comment]
talwrii <notifications@github.com> writes:

> To be clear, I think not including this feature in helm on the grounds
> of minimising code size is completely reasonable.
>
> However, my poor feeble brain really dislikes the multitasking of
> finding the correct helm buffer while doing something else,

I have a similar brain.

> and cycling can avoid this do a degree.

An alternative to your cycling approach could be to make helm-resume a
"multi-command": when called multiple times in succession, it resumes
older and older sessions.
