### ISSUE TITLE
Wrong option passed to locate: -r should be --regex

### ISSUE THREAD

**Issue by alphapapa** [emacs-helm/helm#940]
I'm using Emacs 24.4 with Helm 20150322.1049.  When I use helm-locate and type in two separate words, I get this error: `locate: non-option arguments are not allowed with --regexp`.  The locate man page says:
```
-r, --regexp REGEXP
    Search for a basic regexp REGEXP.  No PATTERNs are allowed if this option is used, 
    but this option can be specified multiple times.

--regex
    Interpret all PATTERNs as extended regexps.
```
`helm-locate-command` is `"locate %s -e -r %s"`, but it looks like `-r` should be `--regex` instead.  

I also think that `-A` should be used, and the variable's documentation even says:
```
If nil it will be calculated when `helm-locate' startup with these default 
values for different systems:
   
   Gnu/linux: "locate %s -e -A %s"
```
But when I used `customize-variable` and set it to nil, that's not what it was set to.  In fact, at https://github.com/emacs-helm/helm/blob/master/helm-locate.el#L190 it's actually set to:

 `gnu/linux "locate %s -e -r %s"`.

I sent this pull request to fix it: https://github.com/emacs-helm/helm/pull/941

Thanks.

**Comment by thierryvolpiatto** [comment]
alphapapa <notifications@github.com> writes:

> I'm using Emacs 24.4 with Helm 20150322.1049. When I use helm-locate
> and type in two separate words, I get this error: locate: non-option
> arguments are not allowed with --regexp. The locate man page says:

This is the doc of the last locate version bundled with last OS's, old
versions of locate doesn't support this option, it is why we are using
old command line by default.

You have to set new options yourself in your config, here what I am
using:

"locate %s -e -A --regex %s"

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by alphapapa** [comment]
Really?  How old are the versions that don't support it?

Maybe neither `-r` nor `--regex` should be in the default.  As it is, most people will encounter this error, and that seems like a bug.

**Comment by thierryvolpiatto** [comment]
alphapapa <notifications@github.com> writes:

> Really? How old are the versions that don't support it?

At least Ubuntu 12.04 is using old locate and people are still using it.

> Maybe neither -r nor --regex should be in the default. As it is, most
> people will encounter this error, and that seems like a bug.

It is not a bug, the backend send you an error as expected.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by alphapapa** [comment]
I wonder if this is not an issue of old versions but of different packages.  I'm on Ubuntu 14.04 and using `mlocate`.  I looked at its changelog, and version 0.26 added `-A/--all`, but I see no mention in the entire changelog of `-r`, `--regexp`, or `--regex`.  So it seems like even old versions of `mlocate` would give the same error with the default `helm-locate-command`.  What distro and locate package are you using?

Regardless, I think it is a bug, because it gives the user an error when the user does nothing wrong.  In fact, the user does exactly what he is accustomed to doing in Helm--typing multiple patterns--but it fails, and the user has no idea why.  Regexps aren't even the default matching type in the rest of Helm, nor for the locate command used anywhere else, so why is it the default for helm-locate?

At least, I think `helm-locate-set-command` should check `locate -h`, and if `--regex` is not supported, it should not use it.  

In any case, `-r` should not be the default, because it will cause this error for everyone who uses `mlocate`, which is the default in Ubuntu and probably most other distros.  If someone really wants regexp matching (which isn't the default for `locate` or `find`), he can add the option himself.

**Comment by michael-heerdegen** [comment]
Actually, helm-locate didn't use regexp matching until a year or so, where we changed it because helm uses regexp matching everywhere.

Leaving your personal likes out of consideration, whatever we do, every solution will behave  unexpectedly for some users.

**Comment by alphapapa** [comment]
Thanks for the tip about the regexp matching.  I didn't realize that it's the default now.  Maybe that's because helm-swoop doesn't seem to use it (and I didn't find any customizable variables for it), and the only place I've tried to use regexps in Helm is in helm-swoop.  :)

I'm sorry if I was rude.  I don't care about this for myself, because I already customized the variable and fixed it for myself.  But it seems a shame for nearly all new Helm users (and approaching 100% as time passes) to run into this bug, because it will happen by default.

This is hardly a comprehensive search, but as points of comparison, I looked up the locate man page from Fedora 12, which was released in November of 2009, and it has the same `-r/--regexp` and `--regex` options as the current release of Ubuntu does.  So, on Fedora at least, going back 5 years, the current helm-locate-command will cause this error.  

For Ubuntu, going back to Ubuntu 10.04 LTS, the default package providing `locate` is `mlocate`, which even in 10.04 supported these same options and would encounter this error by default.  So Ubuntu, by default, 5 years ago, was the same way.  

And it appears that even in 2009, the default in Debian was `mlocate`.

Emacs and Helm have changed a lot during that time, so I don't understand how this is a case of backward-compatibility.  It seems more like forward-incompatibility-starting-over-5-years-ago.  :)  What is the benefit of keeping `-r` instead of using `--regex` by default?  What distros use the `findutils` locate by default?  If Fedora, Ubuntu, and Debian all have used `mlocate` by default for at least 5 years, surely that covers the vast majority of users, all of whom will encounter this error by default and have to manually fix `helm-locate-command` in order to be able to use spaces and multiple patterns in `helm-locate`.  Shouldn't this be fixed?

Thanks.

**Comment by thierryvolpiatto** [comment]
alphapapa <notifications@github.com> writes:

> I'm sorry if I was rude. I don't care about this for myself, because I
> already customized the variable and fixed it for myself. But it seems
> a shame for nearly all new Helm users (and approaching 100% as time
> passes) to run into this bug,

It is NOT a bug.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by alphapapa** [comment]
Well, by default, people who use `helm-locate` in the same way they use the rest of Helm will get an unexpected and confusing error message, and they will have to manually customize a variable to fix it.

There will be many more people who encounter this error and have to fix it manually than people whose distro uses `findutils`'s locate and do not encounter this error.

Basically, for the majority of distros and users, `helm-locate-command` is using incorrect options by default.

It's not a logic error-type bug, but it's an incorrect default setting for the vast majority of people.  If you don't want to call this a "bug," that's fine, but it should be fixed.

**Comment by thierryvolpiatto** [comment]
For the last time, this is an error message from the backend (locate) which tells you you are not using it (the backend, locate) correctly, helm is using the backend, not its matching mechanism, so with the default command line multiple regexp matching is not supported, as @michael-heerdegen told you, if you change the default command line to what you ask, people not having the new version of locate will have something that DO NOT WORK at all, with one regexp or two.
So please stop insisting.

**Comment by alphapapa** [comment]
I understand all of that.

But as I pointed out, it appears that the vast majority of people for the past 5 years have been using the new version of locate.  Doesn't it make sense to fix it for them?  Then the few who are not can make the change locally.  As it is now, most people will have to make the opposite change locally, so most people will be confused and inconvenienced.

**Comment by michael-heerdegen** [comment]
@alphapapa  We have changed the default for Gnu/Linux to ```"locate %s -e --regex %s"``` now.

**Comment by alphapapa** [comment]
Cool, thanks for letting me know.  Keep up the good work, Helm is awesome.  :)
