### ISSUE TITLE
helm-find-files: hide dotted lines

### ISSUE THREAD

**Issue by manuel-uberti** [emacs-helm/helm#943]
![shot](https://cloud.githubusercontent.com/assets/8199224/6809714/6e9cfbca-d25c-11e4-8662-a30816eedcd2.png)

Is it possible to hide the the first two lines? I don't need ```.``` and ```..``` when using ```helm-find-files```. I already set ```helm-ff-skip-boring-files``` to ```t```.

**Comment by thierryvolpiatto** [comment]
Manuel Uberti <notifications@github.com> writes:

> shot    
>
> Is it possible to hide the the first two lines?

No.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by manuel-uberti** [comment]
Ok, thanks.

**Comment by justmytwospence** [comment]
A variable for this, or at least being able to add these to helm-boring-file-regexp-list would be nice

**Comment by thierryvolpiatto** [comment]
Spencer Boucher <notifications@github.com> writes:

> A variable for this, or at least being able to add these to
> helm-boring-file-regexp-list would be nice

Have been asked several times and the answer is no.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by zeroDivisible** [comment]
> Have been asked several times and the answer is no.

@thierryvolpiatto I'm wondering - would you maybe know why the answer here is "no"? I'm genuinely wondering what would be the reason for that?

**Comment by thierryvolpiatto** [comment]
Michal Stolarczyk <notifications@github.com> writes:

>     Have been asked several times and the answer is no.
>    
> @thierryvolpiatto I'm wondering - would you maybe know why the answer
> here is "no"?

They are used internally by helm-find-files for navigation, thus they
are needed for compatibility with empty directories on all platforms
(e.g Windows works very badly without them, contrarily to what emacs
developers think).

Remember that helm-find-files (despite its name) is a file/directory
browser, not a tool to find files (like locate or find) and when
browsing a directory dotted files are part of the files of this
directory, and the only files in it when directory is empty.

IOW don't expect I (the author of helm-find-file) will remove them from
the listing :-)

-- 
Thierry
https://emacs-helm.github.io/helm/
