### ISSUE TITLE
how to use helm filter better?

### ISSUE THREAD

**Issue by stardiviner** [emacs-helm/helm#944]
I have an issue in this https://github.com/areina/helm-dash/issues/72

But I'm not an elisp ninja. So I can't under helm code much, even though I can read a little about it.

I hope the author can give me some hints about this.

**Comment by thierryvolpiatto** [comment]
stardiviner <notifications@github.com> writes:

> I have an issue in this areina/helm-dash#72
>
> But I'm not an elisp ninja. So I can't under helm code much, even though I can read a little about it.
>
> I hope the author can give me some hints about this.

Can you isolate the issue by debugging and tell me which part of your
code fail ?

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
