### ISSUE TITLE
More consistency needed between helm backends

### ISSUE THREAD

**Issue by jwiegley** [emacs-helm/helm#945]
I know this isn't really an issue for `helm` itself, and I'm fine if you just want to close it right away, but I wanted to write this down so you could give some thought to better ways of encouraging `helm` backend authors to be more consistent in the functionality they provide.

For example, one of the best features of `helm-do-grep-r` is the ability to type `C-x C-s` and have the search results be persisted to a buffer so that I can interact with them or edit them without having to stay in the `helm` interaction mode.  However, backends like `helm-ag` do not function this way, so although there are times when `helm-ag` is a better choice of search utility, it doesn't feel the same and none of my intuitions match up.

`helm-swoop`, which is also a great backend, uses `C-c C-e` to enter "edit mode" on its search results, rather than `C-x C-s`.

Further, some modes use `C-]` to toggle insertion of filename prefixes, and some don't.

I think it would be great for the helm "universe" if there was a single pattern of keybindings that all backends could benefit from following, so that users wouldn't have to read the help page for each backend almost every time they use them (which is what happens to me).  In fact, even how you enter the help page isn't consistent!  Some backends use `C-c ?`, and some use `C-h m`.

**Comment by thierryvolpiatto** [comment]
Hi John,

John Wiegley <notifications@github.com> writes:

> I know this isn't really an issue for helm itself, and I'm fine if you
> just want to close it right away, but I wanted to write this down so
> you could give some thought to better ways of encouraging helm backend
> authors to be more consistent in the functionality they provide.

Unfortunately, I have no control under the helm packages wrote outside
emacs-helm organization.

> For example, one of the best features of helm-do-grep-r is the ability
> to type C-x C-s and have the search results be persisted to a buffer
> so that I can interact with them or edit them without having to stay
> in the home interaction mode.

Yes, you can even refresh this buffer with "g" and have more than one buffer.

> However, back ends like helm-ag do not function this way, so although
> there are times when helm-ag is a better choice of search utility, it
> doesn't feel the same and none of my intuitions match up anymore.

I have plans to add support for "ag" but I didn't find the time yet.
I don't know helm-ag itself but I know its author, which is really open
for changes and write nice packages (syhoei).

> helm-swoop, which is also a great backend, uses C-c C-e to enter "edit
> mode" on its search results, rather than C-x C-s.

I never used these one, and never add contact with its author AFAIK, 
IIRC it is derived from helm-(m)occur, isn't it ?

helm-(m)occur is able to save its buffer (with C-x C-s too) and have a
nice mechanism to warn you if refreshing is needed, refreshing can be
done automatically too.
 
> Further, some modes use C-] to toggle insertion of filename prefixes,
> and some don't.

Normally I try to use C-] everywhere in helm itself, let me know which
ones use another binding.
 
> I think it would be great for the helm "universe" if there was a
> single pattern of keybindings that all backend could benefit from
> following, so that users wouldn't have to read the help page for each
> backend almost every time they use them (which is what happens to
> me). In fact, even how you enter the help page isn't consistent!  Some
> backends use C-c ?, and some use C-h m.

From helm itself C-h m is still here in the commands which have no
documentation and provide a global documentation, I will bind this
global doc to C-c ? for consistency.
But as I said above many people write helm-* packages outside of
emacs-helm and I have indeed no control on these packages.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment]
> helm-(m)occur is able to save its buffer (with C-x C-s too) and have a nice mechanism to warn you if refreshing is needed, refreshing can be done automatically too.

The nice thing with `helm-swoop` is that it highlights the lines that matched and also highlight the search terms inside that line, so you can quickly locate the location of the terms you want to search for, and when press `RET`, it moves point directly on the search term. With `helm-occur`, I have to manually scan the line myself and jump to it manually.

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> The nice thing with helm-swoop is that it highlights the lines that
> matched

helm-occur also.

> and also highlight the search terms inside that line,

helm-occur doesn't do this, it could be done.

> so you can quickly locate the location of the terms you want to search
> for, and when press RET, it moves point directly on the search
> term.

Same as helm-occur

> With helm-occur, I have to manually scan the line myself and jump to
> it manually.

Not sure to understand this.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment]
> Not sure to understand this.

I did not notice that `helm-occur` can jump to search term. Initially, because it didn't highlight the search terms in other buffer, I thought it jumps to beginning of line. However, when navigating matches, I have to find where the terms occur in each match manually with my eyes.

**Comment by tuhdo** [comment]
`helm-swoop` can match multiple lines as well. You can see the demo [here](https://github.com/ShingoFukuyama/helm-swoop#multiline-behavior).

**Comment by michael-heerdegen** [comment]
I'm currently writing something that should once become a superset of helm-grep and helm-swoop.  It's already quite usable.  I'll upload it later today, maybe you can give it a try then.

**Comment by michael-heerdegen** [comment]
@tuhdo I've just uploaded it here: https://github.com/michael-heerdegen/helm-browse.  Comments welcome.

**Comment by jwiegley** [comment]
@thierryvolpiatto Sure, I realize you can't control the decisions that other authors make, but perhaps a "Helm best practices" guide, or a code template for new authors to base their mode on.  There are lots of things that Helm does whose behavior recurs through all of the backends, so one would hope that the only varying keybindings between packages would come from unique features contributed by those backends.  My guess is that variant keybindings for common behavior are being chosen because there is no clear standard to follow, other than the code to helm itself?

**Comment by thierryvolpiatto** [comment]
John Wiegley <notifications@github.com> writes:

> @thierryvolpiatto Sure, I realize you can't control the decisions that
> other authors make, but perhaps a "Helm best practices" guide, or a
> code template for new authors to base their mode on. There are lots of
> things that Helm does whose behavior recurs through all of the
> backends, so one would hope that the only varying keybindings between
> packages would come from unique features contributed by those
> backends. My guess is that variant keybindings for common behavior are
> being chosen because there is no clear standard to follow, other than
> the code to helm itself?

Exactly, we lack a section in wiki for developing with helm, we have
currently only documentation user oriented.
Unfortunately I never found the time to do it.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Now `C-h m` and `C-c ?` are doing the same thing in all helm.
A convention section is opened on wiki (need to be improved).

About helm-swoop<vs>helm-moccur.

`helm-moccur` is doing more or less what swoop is doing AFAICS or anyway can be configured so.
The buffer selection from helm-buffers-list is much better than helm-swoop with more features (e.g "@").

**Comment by jwiegley** [comment]
Thank you!
