### ISSUE TITLE
How to make helm-related commands create a new window instead of occupying whole existed window above?

### ISSUE THREAD

**Issue by c02y** [emacs-helm/helm#947]
How can I make Emacs do things like http://tuhdo.github.io/static/part3/helm-autoresize-fix.gif , I mean, I got windows side-by-side in one frame, how to make helm command like M-x or helm-swoop create a small new window just like that demo instead of occupying whole existed window above?

**Comment by tuhdo** [comment]
I've just replied when you asked on my page, but I will post it here again for future reference:

- Activate `(helm-autoresize-mode 1)`
- Set `helm-autoresize-min-height` and `helm-autoresize-max-height` equal to a number. This number is the percentage size of your frame i.e. 30 means 30% of your current frame height.

**Comment by tuhdo** [comment]
To have extra space, set `helm-display-header-line` to `nil`.

**Comment by c02y** [comment]
Yes, but not for `helm-swoop`, and don't forget `(setq helm-split-window-in-side-p t)`, is there a chance that I can make helm-swoop action this way?

**Comment by tuhdo** [comment]
`helm-swoop` works fine for me with the above settings.

**Comment by c02y** [comment]
Not for me, not even I remove all the configuration but the helm related, the `helm-swoop` will always occupy the other whole window if I got two windows side by side. Can you share your init.el?

**Comment by tuhdo** [comment]
Here is [my Helm config](https://bitbucket.org/hoangtu/.emacs.d/src/4ae1e7eabfa180fb474d7268854845b51a5c6329/custom/setup-helm.el?at=master). But I think it is because the setting of `helm-split-window-default-side` to `'right`. You must set it to `'below`:

```elisp
(setq helm-split-window-default-side 'below)
```

**Comment by c02y** [comment]
`below` is the default value of `helm-split-window-default-side`, I didn't set it.

**Comment by tuhdo** [comment]
It seems like [you are setting it to 'other](https://github.com/c02y/dotemacs.d/blob/master/init.el#L2122).

**Comment by c02y** [comment]
It was old, I modified my init.el a lot today and haven't pushed it to github yet, and I'm sure that the split-method of helm-swoop is controlled by `(setq helm-swoop-split-with-multiple-windows t)` according to your configuration.

**Comment by tuhdo** [comment]
Did it work for you after setting that variable?

**Comment by c02y** [comment]
I said I'm sure. So yes, it works.
