### ISSUE TITLE
`helm-M-x` errors in new helm version

### ISSUE THREAD

**Issue by jcpetkovich** [emacs-helm/helm#951]
I'm getting the following error executing `helm-M-x`:

    helm-init-candidates-in-buffer: Wrong type argument: characterp, "ÁÂÃ!

The interesting part of this bug is if you install `helm` using `package.el` from a clean emacs with no packages previously installed, then this bug never happens.

If however, you install/compile `helm` after already installing and loading some packages (I'm not sure which ones cause the problem) then the resulting helm `*.elc` files will always produce the above error, regardless of what packages are loaded, or if you use `emacs -Q` or not.

I'm currently using `spacemacs` and have reported the bug there as well: https://github.com/syl20bnr/spacemacs/issues/983

I'm having trouble tracking down the cause of this, any suggestions for how I can find it?

**Comment by tuhdo** [comment]
You should try to reproduce with the script `emacs-helm.sh` in your Helm installation in `elpa/`. Then try if any error. If not, you can close the issue here and we can start investigating in Spacemacs side.

**Comment by jcpetkovich** [comment]
The error still occurs in the elpa directory using the `emacs-helm.sh` script.

After deleting all the compiled elisp in that directory and running emacs-helm.sh again, it works fine.

Any other suggestions? Or information you need from me? In the meantime I will try and reproduce this error without the use of `spacemacs`.

**Comment by tuhdo** [comment]
In this case, it's a bad installation. Simply delete your Helm installation in `elpa/` directory and reinstall it, then everything should work fine.

**Comment by jcpetkovich** [comment]
Found the problem. Turns out it was a foolish mistake of mine `(defvar it)`. This made the helm package compilation process mess up in a number of ways.

Thanks for the help and prompt responses!
