### ISSUE TITLE
Add helm-interesting-buffer-list

### ISSUE THREAD

**Issue by tuhdo** [emacs-helm/helm#952]
So, I can exclude all buffers start with `*`, except a few buffers in `helm-intersting-buffer-list`.

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> So, I can exclude all buffers start with *, except a few buffers in
> helm-intersting-buffer-list.

You have `helm-boring-buffer-regexp-list' for this.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment]
Yes but it's easier to exclude all buffers with `^\*`  and specify a few exceptions, i.e. `*eshell*`.

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> Yes but it's easier to exclude all buffers with ^\* and specify a few
> exceptions, i.e. *eshell*.

Please use `helm-boring-buffer-regexp-list', it's enough easy.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment]
I meant, excludes all `*` buffers using `helm-boring-buffer-regexp-list`, except a few specified in `helm-intersting-buffer-list`.

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> I meant, excludes all * buffers using helm-boring-buffer-regexp-list,
> except a few specified in helm-intersting-buffer-list.

Just don't add "few" in `helm-boring-buffer-regexp-list'.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment]
> Just don't add "few" in `helm-boring-buffer-regexp-list'.

But then, I won't be able to ignore everything starts with `*` anymore and have to manually specify which buffer that has `*` to be ignored and which to be not ignored. 

I want to add this regex: `^\*` to `helm-boring-buffer-regexp-list` to ignore every buffer starts with `*`. But then, it ignores buffers like `*eshell*`, `*shell*`, `*terminal*`... I would like to ignore all, except those, hence that's why we need an interesting list.

**Comment by thierryvolpiatto** [comment]
So don't use `^\\*`.

**Comment by tuhdo** [comment]
Isn't it better if we can use it, or regexp in similar situations?

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> Isn't it better if we can use it, or regexp in similar situations?

No it just complicate things uselessly.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
