### ISSUE TITLE
allow to control size of helm-window when helm-always-two-windows == t

### ISSUE THREAD

**Issue by michael-heerdegen** [emacs-helm/helm#953]
Hello,

I have helm-always-two-windows == t and helm-autoresize-mode nil.  In this case, AFAICT you currently always get a splitting with two equally sized windows, i.e. there is no way to control the size of the helm-window.  Would it be worth to make this configurable (we could e.g. allow a number value of helm-always-two-windows to define the preferred size of the helm window)?

This is what I currently do:

```
  (advice-add 'helm-split-window-default-fn :filter-return
              (defun my-helm-split-window-default-fn-set-window-height (new-win)
                (set-window-text-height new-win 11)
                new-win))
```

which shows that it would be quite easy to do. WDYT?  Thanks.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Hello,
>
> I have helm-always-two-windows == t and helm-autoresize-mode nil. In this case, AFAICT you currently always get a splitting with two equally sized windows, i.e. there
> is no way to control the size of the helm-window. Would it be worth to make this configurable (we could e.g. allow a number value of helm-always-two-windows to define
> the preferred size of the helm window)?
>
> This is what I currently do:
>
>   (advice-add 'helm-split-window-default-fn :filter-return
>               (defun my-helm-split-window-default-fn-set-window-height (new-win)
>                 (set-window-text-height new-win 11)
>                 new-win))
>
> which shows that it would be quite easy to do. WDYT? Thanks.

Probably you can get the same result by using autoresize mode and play
with `helm-autoresize-min-height' and `helm-autoresize-max-height' (give
more or less same value).

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
That's worth a try.  I'll tell you if it satisfies me, thanks.

**Comment by michael-heerdegen** [comment]
For now, it seems to do what I want.  Closing, thanks
