### ISSUE TITLE
helm-complex-command-history: exit-minibuffer: No catch for tag: exit, nil

### ISSUE THREAD

**Issue by michael-heerdegen** [emacs-helm/helm#954]
Hello,

in helm.sh, having already filled the complex-command-history by using Emacs normally, do M-x helm-complex-command-history.  Select any item and hit RET.  You get the following error:

```
Debugger entered--Lisp error: (no-catch exit nil)
  throw(exit nil)
  exit-minibuffer()
  helm-exit-minibuffer()
  helm-run-after-quit(helm-sexp-eval "(where-is (quote helm-complex-command-history) nil)")
  (lambda (candidate) (and (boundp (quote helm-sexp--last-sexp)) (setq helm-sexp--last-sexp candidate)) (helm-run-after-quit (quote helm-sexp-eval) candidate))("(where-is (quote helm-complex-command-history) nil)")
  apply((lambda (candidate) (and (boundp (quote helm-sexp--last-sexp)) (setq helm-sexp--last-sexp candidate)) (helm-run-after-quit (quote helm-sexp-eval) candidate)) "(where-is (quote helm-complex-command-history) nil)")
  helm-funcall-with-source(((match helm-mp-exact-match helm-mp-match) (name . "Complex Command History") (candidates lambda nil (cl-loop for i in command-history unless (equal i (quote (helm-complex-command-history))) collect (prin1-to-string i))) (type . sexp) (header-line . helm-persistent-help-string) (action ("Eval" lambda (candidate) (and (boundp (quote helm-sexp--last-sexp)) (setq helm-sexp--last-sexp candidate)) (helm-run-after-quit (quote helm-sexp-eval) candidate)) ("Edit and eval" lambda (cand) (minibuffer-with-setup-hook (lambda nil (insert cand)) (call-interactively (function eval-expression))))) (persistent-action . helm-sexp-eval)) (lambda (candidate) (and (boundp (quote helm-sexp--last-sexp)) (setq helm-sexp--last-sexp candidate)) (helm-run-after-quit (quote helm-sexp-eval) candidate)) "(where-is (quote helm-complex-command-history) nil)")
  helm-execute-selection-action-1()
  helm-execute-selection-action()
  helm-internal(helm-source-complex-command-history nil nil nil nil "*helm complex commands*" nil nil nil)
  apply(helm-internal (helm-source-complex-command-history nil nil nil nil "*helm complex commands*" nil nil nil))
  helm(helm-source-complex-command-history nil nil nil nil "*helm complex commands*" nil nil nil)
  apply(helm (helm-source-complex-command-history nil nil nil nil "*helm complex commands*" nil nil nil))
  helm(:sources helm-source-complex-command-history :buffer "*helm complex commands*")
  helm-complex-command-history()
  funcall-interactively(helm-complex-command-history)
  call-interactively(helm-complex-command-history record nil)
  command-execute(helm-complex-command-history record)
  helm-M-x()
  funcall-interactively(helm-M-x)
  call-interactively(helm-M-x nil nil)
  command-execute(helm-M-x)
```

Thanks in advance.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Hello,
>
> in helm.sh, having already filled the complex-command-history by using
> Emacs normally, do M-x helm-complex-command-history. Select any item
> and hit RET. You get the following error:
>
> Debugger entered--Lisp error: (no-catch exit nil)

Indeed I have removed this catch, I thought it was now unuseful, I will
add it again.

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
Fixed, thanks.

Nitpick: for the catch/throw tag, we should better use an uninterned (and thus unique) symbol.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Fixed, thanks.
>
> Nitpick: for the catch/throw tag, we should better use an uninterned
> (and thus unique) symbol.

I didn't invent the exit tag, it already exists in emacs.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> I didn't invent the exit tag, it already exists in emacs.

I see.  Then why do we need to catch it here?

I don't understand why the "Eval" action in the "sexp" type definition
uses "helm-run-after-quit" which seems to call "exit-minibuffer" when
the minibuffer seemingly already had been exited.

**Comment by michael-heerdegen** [comment]
You introduced "helm-run-after-quit" as part of fixing #489.  I guess the background was to delay the execution to get a proper entry in command-history, or something like that.

But AFAIU, we don't need "helm-run-after-quit" but only the "run-timer" part of it.

**Comment by michael-heerdegen** [comment]
Maybe the intention was rather to get rid of the backtrace frames produced by the helm session, and the recursive edit.

Anyway, my conclusion stays the same.

**Comment by thierryvolpiatto** [comment]
Michael Heerdegen <notifications@github.com> writes:

> Maybe the intention was rather to get rid of the backtrace frames produced by the helm session, and the recursive edit.
>
> Anyway, my conclusion stays the same.

I have removed the exit catch tag and use directly the timer, seems to
work fine.

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment]
Ok, thanks, hopefully it was the right thing to do.  Closing.
