### ISSUE TITLE
Cannot navigate cursor to "Emacs Commands" category in *helm M-x* buffer

### ISSUE THREAD

**Issue by kelvinh** [emacs-helm/helm#955]
Hi,

I am new to helm, and I met a weird issue with helm, I mapped `helm-M-x` to `M-x`, and also enabled `helm-M-x-fuzzy-match` with `(setq helm-M-x-fuzzy-match t)`, then I press `M-x` and input `op/new-post`, the \*helm M-x\* buffer gives following options:

    Emacs Commands History
    op/new-repository

    Emacs Commands
    op/new-post
    op/new-repository

As you see, there are two commands match the input, however, I can **NOT** navigate my cursor to `op/new-post`, no matter I press `C-p`, `C-n` or `<TAB>`, the cursor always stay at `op/new-repository`, the one under *Emacs Commands History*. However, the command I want to call is `op/new-post`, thus, the command cannot be called unless I disable helm, or call the original `M-x` instead of `helm-M-x`.

Do I configure something wrong?

**Comment by kelvinh** [comment]
After I submitted this issue, I searched the issue list again and found issue #683, it is the same issue as this one, now I can use `C-o` to switch as @tuhdo suggests. In fact I searched the issue list before submitting this issue, but I used wrong keywords so #683 is not in search result...

Really sorry for the inconvenience, closing now.

**Comment by michael-heerdegen** [comment]
No problem, thanks for searching.
