### ISSUE TITLE
helm-find-files : How to create a file whose name is a prefix of existing file

### ISSUE THREAD

**Issue by phtrivier** [emacs-helm/helm#956]
Hi .

I have Ctrl-f bound to "helm-find-files". 
I have a buffer open with name like "fooSpec.js".
I want to create buffer named "foo.js" in the same folder. 

What I would expect to be able to do is : 

* Ctrl-f (open helm-find-files)
* Type "foo.js"
* Type "Enter"
* Since the file does not exist, confirm that I want to create a new file
* End up in a new buffer

What happens : 

* Ctrl-F
* Type "foo.js"
* Type "Enter"
* End up in the buffer for "fooSpec", since what I type is a pattern that matches the buffer name.

Is there a way to work around this ?

Thanks

**Comment by tuhdo** [comment]
Is that `fooSpec.js` in the same directory? If so, Helm will prioritize the first match; but you can create a new file if you want. In this case, when you type `foo.js`, at the top line there is a candidate like this: `[?] foo.js`. Move the highlighter to that line and press `RET`, and you will have a brand new buffer created.

**Comment by thierryvolpiatto** [comment]
Pierre-Henri Trivier <notifications@github.com> writes:

> Is there a way to work around this ?

You have to understand that with helm, what you have in minibuffer is
not what you will get.

See:
https://github.com/emacs-helm/helm/wiki#helmis**completionwindowcentric**

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by phtrivier** [comment]
That did it. Thanks.
