### ISSUE TITLE
Is it possible to open occur buffer with helm-occur results?

### ISSUE THREAD

**Issue by Pitometsu** [emacs-helm/helm#958]
To edit some of them, for example.

**Comment by thierryvolpiatto** [comment]
Netsu <notifications@github.com> writes:

> To edit some of them, for example.

Not sure to understand what you want, but I guess you want to run
helm-(m)occur on a theme buffer, save the result and edit this buffer,
right ?

If so you have to install wgrep
https://github.com/mhayashi1120/Emacs-wgrep
and then:

1) run helm-(m)occur on your buffer(s).
2) once the wanted results are here save with C-x C-s.
3) C-c C-p to edit the buffer(s).
4) C-x C-s to save your changes.

I will add an entry in documentation.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by Pitometsu** [comment]
Thanks a lot, that's what I need.
