### ISSUE TITLE
Incorporate helm-info-elisp into helm-apropos?

### ISSUE THREAD

**Issue by tuhdo** [emacs-helm/helm#959]
One thing `helm-apropos` is missing compare with stock `apropos` is that `apropos` can get things from info manual. It would be useful to have `helm-info-elisp` inside `helm-apropos`.

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> One thing helm-apropos is missing compare with stock apropos is that
> apropos can get things from info manual. It would be useful to have
> helm-info-elisp inside helm-apropos.

Use f3.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment]
But not every symbol has an info manual. Currently I have to guess which one having an actual Info page. And it's different from `helm-info-elisp`: I cannot execute persistent action to read it and I have to exit my current `helm-apropos` session. This makes it really inconvenient.

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> But not every symbol has an info manual. Currently I have to guess
> which one having an actual Info page. And it's different from
> helm-info-elisp: I cannot execute persistent action to read it and I
> have to exit my current helm-apropos session.

Just hit helm-resume to be back in helm-apropos.

> This makes it really inconvenient.

In this case use the right command, which is helm-info-at-point.

Please don't explain me again why you need this, I understood, but I
think what we have actually is good enough.

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment]
Alright. I can work around with my own `helm-def-source--info-elisp`:

```elisp
(defun helm-def-source--info-elisp (&optional default) 
   helm-source-info-elisp)
```

It works fine now.
