### ISSUE TITLE
Add per source height and width to utilize helm-autoresize-mode

### ISSUE THREAD

**Issue by tuhdo** [emacs-helm/helm#961]
There are Helm commands that I want smaller window and Helm commands that I want larger windows. Currently, I create wrappers like this:

```lisp
(defun my-helm-occur ()
  (interactive)
  (let ((helm-autoresize-max-height 25)
        (helm-autoresize-min-height 25))
    (call-interactively 'helm-occur)))
```

So, I can use `helm-occur` like Isearch without the window taking too much screen space. I can write a macro to generate such commands, but it would be nice if I can simply use `helm-attrset` to set the `:height` and `:width` of a source.

**Comment by tuhdo** [comment]
By default, it uses the global height and width of `helm-autoresize-mode`, until a user specifies a value for a source.

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> By default, it uses the global height and width of
> helm-autoresize-mode, until a user specifies a value for a source.

No, I won't implement this by source.

Use a hook instead (something like this):

(defun helm-moccur-autoresize-hook ()
  (with-helm-buffer
    (let ((sname (assoc-default 'name (helm-get-current-source))))
      (when (member sname'("Occur" "Moccur"))
        (helm--autoresize-hook 25 25)))))

(add-hook 'helm-after-persistent-action-hook 'helm-moccur-autoresize-hook)

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment]
Alright, that's good enough.

**Comment by tuhdo** [comment]
@thierryvolpiatto Why resize only after executing a persistent action? I want to have a small "*helm occur*" window at the start, so I can use it as an Isearch replacement. To replace Isearch, Helm window must not take too much screen space, otherwise it's too heavy for a quick search.

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> @thierryvolpiatto Why resize only after executing a persistent action?

Because when you run persistent action I guess the intention is to focus
on the other window, not the helm window, so we enlarge it.

> I want to have a small "helm occur" window at the start,

This is non sense, sorry.

> so I can use it as an Isearch replacement. To replace Isearch, Helm
> window must not take too much screen space, otherwise it's too heavy
> for a quick search.

I don't see what Isearch have to do with this, and I don't see why we
would have a very small window.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment]
@thierryvolpiatto Not a very small window but small enough to not being the main focus. I mentioned Isearch as an example use case: instead of using Isearch, I use `helm-occur` (global bind `helm-occur` to `C-s`). Currently, `helm-occur` consumes almost half of my screen, so it's hard to replace. Ideally, I want it to consume about 25% of my window and make it function like Isearch, except having a Helm window as an overview of all collected results, so I can easily navigate back and forth instead of repeatedly pressing `C-s` or `C-r`.

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> except having a Helm window as an overview of all collected results,

Indeed, this is why it is not interesting to have a small window.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment]
@thierryvolpiatto yes, but depends on the use case. Most of the times, we are not interested in having to many results and we would narrow to something like 5 or 10 visible results. Example commands:

- `helm-info-at-point`: I don't care at the start it list almost everything in the info index. After narrowing down, I only have a few candidates in my Helm window. It is always the case, so why do I want a large Helm window at first?

- `helm-occur`: the same. Most of the time, I only have 10-15 candidates after narrowing down, and in this case, I use it to replace Isearch (one less key binding for `C-r`, so I can bind it to `undo-tree-redo`). I use Isearch to navigate cloest matches around point, so only a few results in `helm-occur` interests me. Do you usually have a 100 candidates in your `helm-occur` window and go through it one by one?

- `helm-semantic-or-imenu`: I only interested in a few items most of the time to jump to it or have a look.

- `helm-apropos`: same thing. most of the time I only have less than 10 candidates. The benefit of having small window is that I have huge help buffer when executing persistent action.

Just a few example where this might be useful.

**Comment by tuhdo** [comment]
@thierryvolpiatto you may also question me why I don't use `helm-autoresize-mode` for all those in the first place. It is because there are sources that are legitimate to have a big window. For examples:

- `helm-grep` usually gives many results, i.e. more than 20, so it's good to have a big window to see most of the matches.

- `helm-locate`: same thing.

- `helm-find-files`: same thing

That's why I want to be able to resize per source. Currently, I don't understand why I have to split vertically to resize. I just want to have a small horizontal window that displays around 10 matches, since most other commands contain that many after narrowing down.

**Comment by tuhdo** [comment]
@thierryvolpiatto So, this is concluded? Sigh, I have to manually remove and add the hook to proper places myself then.

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> @thierryvolpiatto So, this is concluded? Sigh, I have to manually
> remove and add the hook to proper places myself then.

Use helm-buffers-to-resize-on-pa and helm-resize-on-pa-text-height.


-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment]
@thierryvolpiatto I know that. I mean, I have to remove `helm-persistent-autoresize-hook` from the persistent hook and add it to per source hook.
