### ISSUE TITLE
Make helm 1.6.9 fail in mingw environment using Emacs 25.0.5

### ISSUE THREAD

**Issue by zijianyue** [emacs-helm/helm#968]
$ make
rm -f helm-adaptive.elc helm-aliases.elc helm-apt.elc helm-bookmark.elc helm-buf
fers.elc helm-color.elc helm-command.elc helm-config.elc helm-dabbrev.elc helm-e
lisp-package.elc helm-elisp.elc helm-elscreen.elc helm-eshell.elc helm-eval.elc
helm-external.elc helm-files.elc helm-font.elc helm-grep.elc helm-help.elc helm-
imenu.elc helm-info.elc helm-locate.elc helm-man.elc helm-match-plugin.elc helm-
misc.elc helm-mode.elc helm-net.elc helm-org.elc helm-pkg.elc helm-plugin.elc he
lm-regexp.elc helm-ring.elc helm-semantic.elc helm-source.elc helm-sys.elc helm-
tags.elc helm-utils.elc helm.elc
emacs -Q -batch --eval "(let ((generated-autoload-file (expand-file-name \"helm-
autoloads.el\" \".\")) \
(backup-inhibited t)) (update-directory-autoloads \".\"))"
emacs -Q -batch -L . -f batch-byte-compile helm-adaptive.el helm-aliases.el helm
-apt.el helm-bookmark.el helm-buffers.el helm-color.el helm-command.el helm-conf
ig.el helm-dabbrev.el helm-elisp-package.el helm-elisp.el helm-elscreen.el helm-
eshell.el helm-eval.el helm-external.el helm-files.el helm-font.el helm-grep.el
helm-help.el helm-imenu.el helm-info.el helm-locate.el helm-man.el helm-match-pl
ugin.el helm-misc.el helm-mode.el helm-net.el helm-org.el helm-pkg.el helm-plugi
n.el helm-regexp.el helm-ring.el helm-semantic.el helm-source.el helm-sys.el hel
m-tags.el helm-utils.el helm.el
ad-handle-definition: `tramp-read-passwd' got redefined
make: *** [batch-compile] Error 3

GNU Emacs 25.0.50.1 (i686-pc-mingw32)
 of 2015-04-05 on LEG570

**Comment by thierryvolpiatto** [comment]
If helm compile fine on GNU/Linux and emacs-25, it should compile on windows, if it doesn't it looks it is an emacs bug on windows, I will try to compile a new emacs-25 on GNU/Linux and see if it compile fine ASAP.

**Comment by thierryvolpiatto** [comment]
I confirm helm compile fine on GNU/Linux with emacs-25.
I suggest you try with the very last version of emacs-25, if it still not working, consider it is an emacs bug.
