### ISSUE TITLE
helm-autoresize-mode crash emacs in terminal

### ISSUE THREAD

**Issue by Abraxas228** [emacs-helm/helm#969]
I've been experiencing crashes recently, and it turns out it goes away if I remove '(helm-autoresize-mode 1)' from my .emacs file. I made sure that this is the sole causes by removing everything BUT helm.

steps to reproduce (on ubuntu 14.04 64bit over ssh):
1. open file A
2. (split-window-right)
2. (helm-find-files) in the right window
3. open file B

The issue may not occur depending on the selection of file A&B 

Segfault Message: 
Fatal error 11: Segmentation fault
Backtrace:
emacs[0x5125ed]
emacs[0x4f61f8]
emacs[0x5124a8]
Fatal error 11: Segmentation fault
Backtrace:4-linux-gnu/libpthread.so.0(+0x10340)[0x7f0347809340]
emacs[0x5125ed]
emacs[0x4f61f8]
emacs[0x5124a8]
emacs[0x51493c]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x10340)[0x7f59c0f63340]
emacs[0x4b68c7]
emacs[0x4b5e3e]
emacs[0x41b42c]
emacs[0x4175c0]
emacs[0x4172cf]
emacs[0x438440]
emacs[0x4fd2de]
emacs[0x4fab3b]
emacs[0x4fa2e8]
emacs[0x56da75]
emacs[0x509274]ux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7f0346f36ec5]
emacs[0x56d4ea]

GDB:
(gdb) bt
#0  turn_on_face (f=0xbdb918, face_id=28) at term.c:1900
#1  0x00000000004b5e3e in tty_write_glyphs (f=0xbdb918, string=<optimized out>, len=<optimized out>) at term.c:775
#2  0x000000000041b42c in update_frame_line (f=0xbdb918, vpos=115) at dispnew.c:4832
#3  0x00000000004175c0 in update_frame_1 (f=0xbdb918, force_p=<optimized out>, inhibit_id_p=<error reading variable: Cannot access memory at address 0x1>, set_cursor_p=true) at dispnew.c:4534
#4  0x00000000004172cf in update_frame (f=0xbdb918, force_p=<optimized out>, inhibit_hairy_id_p=false) at dispnew.c:3122
#5  0x0000000000438440 in redisplay_internal () at xdisp.c:13775
#6  0x00000000004fd2de in read_char (commandflag=1, map=33920163, prev_event=0, used_mouse_menu=0x7fffffffe4cf, end_time=0x0) at keyboard.c:2541
#7  0x00000000004fab3b in read_key_sequence (bufsize=30, keybuf=<optimized out>, prompt=<optimized out>, dont_downcase_last=<optimized out>, can_return_switch_frame=<optimized out>,
    fix_current_buffer=<optimized out>, prevent_redisplay=<optimized out>) at keyboard.c:9157
#8  0x00000000004fa2e8 in command_loop_1 () at keyboard.c:1407
#9  0x000000000056da75 in internal_condition_case (bfun=0x4f9140 <command_loop_1>, handlers=<optimized out>, hfun=<optimized out>) at eval.c:1348
#10 0x0000000000509274 in command_loop_2 (ignore=<optimized out>) at keyboard.c:1139
#11 0x000000000056d4ea in internal_catch (tag=<optimized out>, func=0x509250 <command_loop_2>, arg=0) at eval.c:1108
#12 0x00000000004f8912 in command_loop () at keyboard.c:1118
#13 recursive_edit_1 () at keyboard.c:728
#14 0x00000000004f8a3b in Frecursive_edit () at keyboard.c:799
#15 0x00000000004f77df in main (argc=<error reading variable: Cannot access memory at address 0x0>, argv=<optimized out>) at emacs.c:1626
(gdb)

**Comment by thierryvolpiatto** [comment]
Not reproductible.

**Comment by thierryvolpiatto** [comment]
Also it seems it is not related to helm as the crash happen after opening a file and not while in helm.

**Comment by Abraxas228** [comment]
Thanks for looking into the issue. 
The crash occurs deep in the emacs c functions that I wasn't able to pin down the problem.

But the culprit seems to be the "global-nlinum-mode". It creates line nums even in the helm buffers and causes some sort of race in redisplaying when helm buffer quickly appears then disappears.

**Comment by lewang** [comment]
Is there a emacs bug for this?  It seems like this should be addressed
there.

On Mon, Apr 13, 2015 at 4:20 AM, HJ <notifications@github.com> wrote:

> Thanks for looking into the issue.
> The crash occurs deep in the emacs c functions that I wasn't able to pin
> down the problem.
>
> But the culprit seems to be the "global-nlinum-mode". It creates line nums
> even in the helm buffers and causes some sort of race in redisplaying when
> helm buffer quickly appears then disappears.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/emacs-helm/helm/issues/969#issuecomment-92265526>.
>



-- 
Le

**Comment by sdwolf** [comment]
I am able to reproduce this bug, see the discussion here: https://github.com/syl20bnr/spacemacs/issues/8197#issuecomment-285901168

Right now i'm trying to figure out the lifecycle of elements in the face cache to see why the face required to draw helm related glyphs is missing.

Any insight on this? Is helm doing anything funky with fonts?

**Comment by thierryvolpiatto** [comment]
Codruț Constantin Gușoi <notifications@github.com> writes:

> I am able to reproduce this bug,

This is not reproductible from ./emacs-helm.sh -nw and
helm-autoresize-mode enabled.

Please try always to reproduce your bugs from ./emacs-helm.sh, I am not
responsible of what happen on spacemacs.

Thanks.

-- 
Thierry

**Comment by sdwolf** [comment]
Actually to reproduce this you need a few planets aligned:
- spacemacs with helm
- linum-format set to "%d "
- opening a relatively large file (2000+ lines) with helm
- the file needs to be opened by spacemacs at a large line number (ex: 1800) and not at the beginning.

I've added a comment here since the backtrace is similar with what I am experiencing. I will try to reproduce it with your script once I finish what I am looking into right now.

**Comment by thierryvolpiatto** [comment]
Codruț Constantin Gușoi <notifications@github.com> writes:

> Actually to reproduce this you need a few planets aligned:
>
>   * spacemacs with helm

As I said I am not concerned by this.

>   * linum-format set to "%d "

Looks the recommended  format string is "%7d ".

Again not concerned by this.

So here starting with ./emacs-helm.sh -nw
M-x global-linum-mode (didn't modify default value of linum-format)
M-x helm-autoresize-mode

Insert in scratch buffer this line (modify the path):

/path/to/helm/directory/helm.el:1850

And with point on it do C-x C-f RET

The file is opened at line 1850 as expected without any crash or
whatever error.

-- 
Thierry

**Comment by sdwolf** [comment]
Yes you are right, I can not reproduce this by itself on a clean emacs install.

The more I look into it the more I believe it's just an internal emacs bug due to bad handling of cached faces and helm's involvement is just a coincidence. I'l try to contact the emacs mailing list to see what can be done.

Thank you very much for your assistance.
