### ISSUE TITLE
ediff fails if only 1 window open

### ISSUE THREAD

**Issue by salvesis** [emacs-helm/helm#970]
With 1 window open select 2 files via helm-locate etc. then f11 to ediff:
>    Debugger entered--Lisp error: (wrong-type-argument stringp nil)
>      expand-file-name(nil)
>      helm-dwim-target-directory() ...

Split the window beforehand and ediff works. `helm-dwim-target-directory` assumes `helm-ff-history` is not nil:
>      (expand-file-name
>       (if (> num-windows 1)
>           (save-selected-window
>             (other-window 1)
>             default-directory)
>           (car helm-ff-history))))))

**Comment by thierryvolpiatto** [comment]
Thanks, should work now.
