### ISSUE TITLE
make helm-list-elisp-packages use cache

### ISSUE THREAD

**Issue by psibi** [emacs-helm/helm#971]
Every time I use the command helm-list-elisp-packages it downloads all the index files from melpa, gnu etc. I would like an option or a new function which will actually allow me to configure to use the previous downloaded index files from melpa, gnu etc.

This is similar to how `package-list-packages-no-fetch` command operate.

**Comment by thierryvolpiatto** [comment]
Sibi <notifications@github.com> writes:

> Every time I use the command helm-list-elisp-packages it downloads all
> the index files from melpa, gnu etc.

It doesn't, at least on emacs-24.4 and 24.5 unless you call
`helm-list-elisp-packages' with a prefix arg.

Maybe you use the development version of emacs (25) which have had
recently many changes in package.el and the way it fetch packages
(async).

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by psibi** [comment]
@thierryvolpiatto Sorry, I think I should have restated it more clearly.

The problem is it downloads the entire index file if I quit the Emacs session and re-open it again. Also, I'm using Emacs version 24.4.1. 

I would like to have an option for having the cache enabled untill I manually refresh it again or something like that.

**Comment by thierryvolpiatto** [comment]
Sibi <notifications@github.com> writes:

> @thierryvolpiatto Sorry, I think I should have restated it more
> clearly.
>
> The problem is it downloads the entire index file if I quit the Emacs
> session and re-open it again. Also, I'm using Emacs version 24.4.1.
>
> I would like to have an option for having the cache enabled untill I
> manually refresh it again or something like that.

Ok, you can now use M-x helm-list-elisp-packages-no-fetch

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by psibi** [comment]
Thanks, this works great!
