### ISSUE TITLE
Ignore Dired buffers in Helm window?

### ISSUE THREAD

**Issue by ReneFroger** [emacs-helm/helm#975]
You have the variable `helm-boring-buffer-regexp-list` to ignore certain buffers. 

This is based on the name of the buffer. So for example, you could do the following: 

`(setq helm-boring-buffer-regexp-list
  '("\\*Messages"  "\\*Help" "\\*Shell Command Output" "\\*Flycheck error message" "\\*Compile-Log"))`

Sometimes I use Dired, and then the current directory name is used as buffer name. But I see the type is `"DIred by name"`, as displayed in the third column. 
So I would like to ingore the Dired buffers. When I try to add `\\*Dired by name` it doesn't works. 

Any suggestion? 

Thanks in advance.

**Comment by thierryvolpiatto** [comment]
ReneFroger <notifications@github.com> writes:

> You have the variable helm-boring-buffer-regexp-list to ignore certain
> buffers.
>
> This is based on the name of the buffer. So for example, you could do
> the following:
>
> (setq helm-boring-buffer-regexp-list '("\\*Messages" "\\*Help"
> "\\*Shell Command Output" "\\*Flycheck error message"
> "\\*Compile-Log"))
>
> Sometimes I use Dired, and then the current directory name is used as
> buffer name. But I see the type is "DIred by name", as displayed in
> the third column.  So I would like to ingore the Dired buffers. When I
> try to add \\*Dired by name it doesn't works.

"Dired by name" is the pretty name of major-mode, not a buffer-name.

> Any suggestion?

You can filter buffers by mode, use e.g for dired:

*!dired foo

will find all buffers matching "foo" but the dired buffers.

As always, hit `C-c ?' for more infos.
 
-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment]
I think he want to filter it by default.

**Comment by ReneFroger** [comment]
Yes, @tuhdo, you're right I don't want to find buffers that matches " foo" only, but find all buffers, except "dired".

**Comment by ReneFroger** [comment]
Yes, @tuhdo, you're right I don't want to find buffers that matches " foo" only, but find all buffers, except the Dired buffers. 

For clarifity: I just added a screenshot and I marked the Dired buffers inside Helm by white background. 
![schermafdruk 2015-04-14 20 59 14](https://cloud.githubusercontent.com/assets/5211845/7144951/28195124-e2e9-11e4-8a94-3a124d6a614a.png)

So, is it possible to filter the Dired buffers, like with the others buffers on their name, but with `Dired by name` or something else?

**Comment by thierryvolpiatto** [comment]
"foo" is just an example, if you want all your buffers but the dired ones, use:

*!dired

Again, look in C-c ? it is all explained how to filter buffers.

**Comment by ReneFroger** [comment]
I am aware that foo is an example, and I used in that same manner. 

"*!dired" solves my question. Thanks for the clarifity, it's appreciated.

**Comment by ReneFroger** [comment]
In the manual with `C-c ?`, I readthe following:
`"if I enter in pattern prompt, "*lisp ^helm @moc", helm will narrow dow the list by selecting only buffers that are in Lisp mode "`

`*!dired`will not work in the helm-boring-buffer-regexp-list. But I see the mode is displayed as `Dired by name`. So I tried also '
 (setq helm-boring-buffer-regexp-list '("*!Dired by name" )) which is also not working. 

In the manual I learnt a lot about Helm, but I found no reference about filtering the buffers with the mode, instead displaying them. Any suggestions?

**Comment by michael-heerdegen** [comment]
No, what you try won't work that way.  AFAICT there is no user option that could be used for that  - you would have to use an advice.

But why is omitting all dired buffers so useful?  If you don't want to use dired anyway, why do you care about dired buffers at all?

**Comment by michael-heerdegen** [comment]
Anyway, here is how you could do it:

```
(defun my-filter-dired-buffers (buffer-list)
  (delq nil (mapcar
             (lambda (buffer)
               (if (eq (with-current-buffer buffer major-mode)  'dired-mode)
                   nil
                 buffer))
             buffer-list)))

(advice-add 'helm-skip-boring-buffers :filter-return 'my-filter-dired-buffers)
```

**Comment by ReneFroger** [comment]
@michael-heerdegen 

Sometimes I stumbled into Dired, even when I'm using `helm-find-files`. But your solution works like a charm! My thanks are eternally... By the way, interesting Lisp code to learn from it!

**Comment by bechampion** [comment]
thank you @michael-heerdegen  i've been looking for this for a long while.
