### ISSUE TITLE
How to prevent leaving Helm-mode-Dired? 

### ISSUE THREAD

**Issue by ReneFroger** [emacs-helm/helm#976]
I made a gif about it, to clarifity my problem:

![voorbeeld](https://cloud.githubusercontent.com/assets/5211845/7147093/adb380ac-e2f8-11e4-8ac3-6d41ff83df51.gif)
 
When I open Dired, it turns automatically on Helm-mode-Dired. When I enter my desired file of directory, and press `RET`, it will switch to Dired, then I need to input my desired file of directory again to open it. 

Is there any way to go the file directly inside Helm-mode-Dired? 

There is no mention about the options for the helm-mode-dired. I know that I'm asking sometimes too much. So that's why I appreciate all the suggestions here, if anyone is wanting to help.

**Comment by thierryvolpiatto** [comment]
ReneFroger <notifications@github.com> writes:

> I made a gif about it, to clarifity my problem:
>
> voorbeel
>
> When I open Dired, it turns automatically on Helm-mode-Dired.

You are confused by the name of helm-buffer, what you are using is only
dired helmized by helm-mode.
There is no "helm-mode-dired", see the emacs documentation about the
infos displayed in mode-line.

> When I enter my desired file of directory, and press RET, it will
> switch to Dired, then I need to input my desired file of directory
> again to open it.
>
> Is there any way to go the file directly inside Helm-mode-Dired?

Stop using dired and use only helm-find-files.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by ReneFroger** [comment]
I see. I stop with Dired and I will only use helm-find-files for now. 

Thanks for the suggestion.
