### ISSUE TITLE
helm-esh-source should honour pcomplete-termination-string

### ISSUE THREAD

**Issue by jedahu** [emacs-helm/helm#979]
How about adding `(insert pcomplete-termination-string)` to the end of `helm-ec-insert`?

**Comment by thierryvolpiatto** [comment]
Jeremy Hughes <notifications@github.com> writes:

> How about adding (insert pcomplete-termination-string) to the end of helm-ec-insert?

Probably this would be better, but actually, insertion of final space is
handled differently, and just adding this would break insertion I guess.
(I have to look at the code, I don't remember exactly how I handled this)

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
