### ISSUE TITLE
Creating helm action

### ISSUE THREAD

**Issue by zxcvbn97** [emacs-helm/helm#983]
Hi there,

I'm writin my own helm extension according to this guide http://wikemacs.org/wiki/How_to_write_helm_extensions

How do I create my own Helm action.

**Comment by thierryvolpiatto** [comment]
zxcvbn97 <notifications@github.com> writes:

> How do I create my own Helm action.

The action are functions called with one arg "candidate".

Example:

(helm :sources (helm-build-sync-source "test"
                 :candidates '(a b c d e f)
                 :action (lambda (candidate)
                           (message (format "Result: %s" candidate))))
      :buffer "*helm test*")

You can have more than an action, in this case what you put in the
action slot is an alist of actions:

(helm :sources (helm-build-sync-source "test"
                 :candidates '(a b c d e f)
                 :action '(("Result1" . (lambda (candidate)
                                         (message "Result1: %s" candidate)))
                           ("Result2" . (lambda (candidate)
                                         (message "Result2: %s" candidate)))))
                           
      :buffer "*helm test*")

For building more complex list of actions, you can use
`helm-make-actions'.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
