### ISSUE TITLE
find-file-at-point with Helm

### ISSUE THREAD

**Issue by slymz** [emacs-helm/helm#984]
I have a buffer in Emacs that contains bunch of path names:

```
/etc/apache2
/etc/apache2/magic
/etc/apache2/apache2.conf
/etc/apache2/ports.conf
/etc/apache2/envvars
/etc/apache2/mods-enabled
../../../conf/netl.cfg
q3/bfg.cfg
[etc.]
```
When I try to visit via `find-file-at-point`, Helm buffer comes up and does not visit the file under point!  My only workaround is to disable Helm.  Is there a configuration option for Helm to recognize these absolute and relative paths?

Thanks

**Comment by thierryvolpiatto** [comment]
slymz <notifications@github.com> writes:

> I have a buffer in Emacs that contains bunch of path names:
>
> /etc/apache2
> /etc/apache2/magic
> /etc/apache2/apache2.conf
> /etc/apache2/ports.conf
> /etc/apache2/envvars
> /etc/apache2/mods-enabled
> ../../../conf/netl.cfg
> q3/bfg.cfg
> [etc.]
>
> When I try to visit via find-file-at-point, Helm buffer comes up and
> does not visit the file under point! My only workaround is to disable
> Helm. Is there a configuration option for Helm to recognize these
> absolute and relative paths?

I have disabled this command in helm right now.
Why are you using this command ?
Use instead helm-find-files for all your tasks against file.

I repeat it for everybody:

Use helm-find-files!

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
I have fixed find-file-at-point, but really, you should use
helm-find-files for such tasks ;-)

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by slymz** [comment]
Thank T. Indeed, helm-find-files is very useful. I will utilize that more often. Although occasionally, the use case for `find-file-at-point` is just explicitly and deliberately jumping to the file that is known to exist (especially useful when browsing through compilation logs etc), without the heuristic of `helm-find-files`.  So you fix is very welcome.

**Comment by chrissound** [comment]
I seem to be running into this issue... When using spacemacs. :/

**Comment by thierryvolpiatto** [comment]
@chrissound  I fixed an error introduced when merging branches sometime ago, should work now.
Until now `find-file-at-point` was badly implemented and had unpredictable behavior sometimes.   In emacs-27, it have been fixed, removing the usage of `read-file-name-internal` which is evil when used in elisp code.
