### ISSUE TITLE
helm-org-in-buffer-headings does not work in cloned buffer.

### ISSUE THREAD

**Issue by LeoUfimtsev** [emacs-helm/helm#987]
Steps to reproduce:
- Open any org file 
- run `clone-indirect-buffer`
- Attempt to run helm-org-in-buffer-headings

Expected result:
 - Header search 

Actual result:
 - Error message: `find-file-noselect: Wrong type argument: stringp, nil`

Note:
 - Renaming buffer does not fix the issue. 
 - Using Emacs 25.0.50.4, with all packages updated today from melpa unstable.

**Comment by LeoUfimtsev** [comment]
I currently use worf-goto as workaround.

**Comment by thierryvolpiatto** [comment]
Don't know what worf-goto is.
Should be fixed now.
Thanks.

**Comment by LeoUfimtsev** [comment]
Verified. Now works.
