### ISSUE TITLE
Emacs 24.3 void function add-function in helm-mode.el

### ISSUE THREAD

**Issue by tmccombs** [emacs-helm/helm#989]
In the most recent version of helm, I get a warning on initialization saying that `add-function` is a void function.

**Comment by thierryvolpiatto** [comment]
Thayne McCombs <notifications@github.com> writes:

> In the most recent version of helm, I get a warning on initialization
> saying that add-function is a void function.

Actually helm requires emacs-24.4, please upgrade emacs or use for now
version 1.6.9 of helm (from melpa-stable).

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Thierry Volpiatto <thierry.volpiatto@gmail.com> writes:

> Thayne McCombs <notifications@github.com> writes:
>
>> In the most recent version of helm, I get a warning on initialization
>> saying that add-function is a void function.
>
> Actually helm requires emacs-24.4, please upgrade emacs or use for now
> version 1.6.9 of helm (from melpa-stable).

I will make the compatibility with 24.3 soon, but for now keep with
this.

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tmccombs** [comment]
oh, ok.
