### ISSUE TITLE
Sending the text from a menu to the kill-ring

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [emacs-helm/helm#990]
Consider a `helm` menu (e.g. `helm-M-x` after typing some pattern). Is there any way to send the contents of the menu to the `kill-ring`? For example, I am hoping to get a list of the commands that match a given pattern. Any way to do this with Helm?

**Comment by michael-heerdegen** [comment]
You can just hit C-g and visit the buffer "*helm M-x*" using C-x b.  When visiting the buffer, you'll have no visible cursor, but you can simply C-x C-w to save the contents to a file and revisit.

**Comment by thierryvolpiatto** [comment]
You can also insert the commands in current buffer one by one with `C-c C-i`.
In other sources when candidates are marked `C-c C-i` is inserting all these 
candidates at once, but marking is disabled both in `helm-M-x` and 
`helm-apropos` so it is impossible to do.
Maybe I can reenable marking in helm-apropos if asked...

**Comment by thierryvolpiatto** [comment]
Note also that with `C-h f` with `helm-mode` enabled this is possible.
