### ISSUE TITLE
Invalid matches

### ISSUE THREAD

**Issue by tmalsburg** [emacs-helm/helm#991]
When I `helm-find-file` and search for "rut", the section "Files from current directory" shows the following entry:

* /home/use**r**name/.m**ut**trc

In general, I get a match for every entry that has the characters of the search term in the correct order, even if they are not consecutive.

I observed the same problem in `helm-mu-contacts` but not in some other sources.

This is using a very recent development version of Emacs and the current version of Helm from Melpa.

**Comment by thierryvolpiatto** [comment]
Titus von der Malsburg <notifications@github.com> writes:

> When I helm-find-file

I guess what you are using is not helm-find-file, which doesn't exists,
but helm-for-files or helm-multi-files.

> and search for "rut", the section "Files from current directory" shows
> the following entry:
>
>   * /home/username/.muttrc

Yes fuzzy matching is enabled in this source and have no variable yet to
disable it.
So it is fine, you are matching here against the full path of the file:

r => match the "r" of "username".
ut=> match "ut" from ".muttrc".

If you want to match only against basename, use "rut -b" or toggle
basename.

Even better, use `helm-find-files'.

> In general, I get a match for every entry that has the characters of
> the search term in the correct order, even if they are not
> consecutive.
>
> I observed the same problem in helm-mu-contacts but not in some other
> sources.

Same, with the PR applied, you have fuzzy matching on the whole line.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tmalsburg** [comment]
> I guess what you are using is not helm-find-file, 

Sorry, it was `helm-for-files`.

> Yes fuzzy matching is enabled in this source 

Ok, I see.  It may be a matter of taste but in my experience the additional matches produced by fuzzy matching are 99% garbage.  I like the idea of fuzzy matching but the current implementation doesn't match my intuition about what fuzzy means.  The current definition seems to be something like this: the characters of the search term have to occur in the correct order in the candidate but there can be arbitrary material between the characters. A more sensible definition would be: the candidate has to have a substring matching the search term or any substring that has a Levenshtein distance of 1 from a matching string.  This unfortunately sounds like a hard problem.

**Comment by thierryvolpiatto** [comment]
Titus von der Malsburg <notifications@github.com> writes:

> Ok, I see. It may be a matter of taste but in my experience the
> additional matches produced by fuzzy matching are 99% garbage.

Indeed, such matching give you of course more results that an exact
match, it is the goal of it, matching all what you would never match
with classic pattern matching.
It is why sorting is an important part of it.

> I like the idea of fuzzy matching but the current implementation
> doesn't match my intuition about what fuzzy means.

With helm-files-in-current-dir-source, you are not trying the best
source in helm to give you a good impression of fuzzy, this source is
old and not developed at its best, all my efforts for file matching are
based on helm-find-files mostly.

> The current definition seems to be something like this: the characters
> of the search term have to occur in the correct order in the candidate
> but there can be arbitrary material between the characters. A more
> sensible definition would be: the candidate has to have a substring
> matching the search term or any substring that has a Levenshtein
> distance of 1 from a matching string. This unfortunately sounds like a
> hard problem.

Not that it is hard but the Levenshtein solution is too slow.
What we are using in helm is more or less similar to this:

http://scottfrazersblog.blogspot.com.au/2009/12/emacs-better-ido-flex-matching.html

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tmalsburg** [comment]
Just out of curiosity, I did some research and found [this POSIX compliant regexp library](http://laurikari.net/tre/about/) which does fuzzy matching (up to some Levenshtein distance specified by the user) and seems to be reasonably efficient.  I see that there are practical reasons not to use this library but I think an ideal solution would use a similar approach to fuzzy matching because it limits false positives, of which there are currently too many.  Even if you find a clever way to sort the matches, the large number of false positives will unnecessarily slow down processes like sorting and candidate transformation.

Anyway, it's great to see Helm evolving.  Helm makes my life easier every single day and Emacs would not be what it is without it.  Thanks, Thierry.

**Comment by thierryvolpiatto** [comment]
Titus von der Malsburg <notifications@github.com> writes:

> Just out of curiosity, I did some research and found this POSIX
> compliant regexp library which does fuzzy matching (up to some
> Levenshtein distance specified by the user) and seems to be reasonably
> efficient.

Interesting, will have a look.
It is available as tre-agrep package in debian/ubuntu.

> I see that there are practical reasons not to use this library but I
> think an ideal solution would use a similar approach to fuzzy matching
> because it limits false positives, of which there are currently too
> many. Even if you find a clever way to sort the matches, the large
> number of false positives will unnecessarily slow down processes like
> sorting and candidate transformation.

I like the idea of setting (limiting) the distance between two matches.

> Anyway, it's great to see Helm evolving. Helm makes my life easier
> every single day and Emacs would not be what it is without it. Thanks,
> Thierry.

Many thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
