### ISSUE TITLE
switch-to-buffer should confirm before switching and creating empty buffer

### ISSUE THREAD

**Issue by pclouds** [emacs-helm/helm#992]
This happens when I select an item from the buffer history after restarting emacs, or try to open a buffer i killed before. When the buffer does not exist, helm creates an empty one. This is confusing. I'm opening foo.c, then I see an empty "file" because the buffer foo.c is already closed.

If helm can retain the info to reopen the buffer, that would be great, but hard (e.g. run-scheme or *info* buffers). Otherwise I think it should ask the user first. At least I'll notice that maybe I closed the buffer before.

**Comment by tuhdo** [comment]
You could use `helm-mini` or `helm-buffers-list`, which are the proper buffer switching commands of Helm. It will asks when switching to a non-existent buffer. Stock `switch-to-buffer` is just helmizied command. The good thing is that when you create an empty buffer with `helm-mini` or `helm-buffers-list` with a file extension, the commands set proper major mode accordingly. This is not for stock `switch-to-buffer` command.

But maybe this should be fixed to not surprise new users.

**Comment by pclouds** [comment]
helm-mini shows recentf, which is nice to quickly reopen recent files. But neither mode lets me access buffer switching history, very useful when I need to switch quickly between 2-4 buffers. I'm new to helm, so I may be missing something. Still reading docs..

**Comment by tuhdo** [comment]
The commands do not need such history, since the buffer list is sorted accordingly most recently used buffers. So, when you switch to another buffer, the first buffer in the list is the most recently accessed buffer; the second buffer in the list is the second and so on. There's no need for two duplicated buffer lists with just different sorting.

**Comment by pclouds** [comment]
You are right. I didn't notice that. Thank you.

**Comment by tuhdo** [comment]
@pclouds :+1: 

Glad that you moved on to Helm :)
