### ISSUE TITLE
helm-buffer-run-kill-persistent: avoid confirmation

### ISSUE THREAD

**Issue by manuel-uberti** [emacs-helm/helm#993]
Not an issue, just a question about ```helm-buffer-run-kill-persistent```: is it possible to avoid the confirmation?

I got this snippet in my config:

```
(bind-keys :map helm-buffer-map
           ("C-k" . helm-buffer-run-kill-persistent))
```
I was wondering if there is a setting to avoid confirmation.

Thanks for this awesome package, by the way.

**Comment by thierryvolpiatto** [comment]
No, you can use `M-D` if you don't want to be asked.
Thanks.

**Comment by manuel-uberti** [comment]
Even better. :)
Thank you, Thierry.

**Comment by dato** [comment]
Is `M-D` still supposed to kill without confirmation? I can’t get it to work.

Thanks.

**Comment by manuel-uberti** [comment]
Still working with no confirmation here.

**Comment by dato** [comment]
This is what I'm doing:

- start Emacs with this config:

        (require 'package)
        (package-initialize)
        (helm-mode)

- open _~/.emacs_ and type some words

- call `M-x helm-buffers-list`

- use `C-n` to go to _~/.emacs_, and press `Meta-Shift-d`: I see: _Buffer init.el modified; kill anyway?_

Thanks.

**Comment by manuel-uberti** [comment]
Well, yes, if a buffer is modified is asking for confirmation on my setup too, but I've always thought that's a good thing. :-)

**Comment by dato** [comment]
Hm; the vanilla `C-x C-b` doesn't ask for confirmation...

**Comment by thierryvolpiatto** [comment]
Dato Simó <notifications@github.com> writes:

> This is what I'm doing:
>
>   * start Emacs with this config:
>    
>     (require 'package)
>     (package-initialize)
>     (helm-mode)
>     
>   * open ~/.emacs and type some words
>    
>   * call M-x helm-buffers-list
>    
>   * use C-n to go to ~/.emacs, and press Meta-Shift-d: I see: Buffer init.el modified; kill anyway?

You will be happy one day to have the choice to not kill the buffer with
a lot of unsaved work.
The message is not coming from helm but from emacs.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by thierryvolpiatto** [comment]
Dato Simó <notifications@github.com> writes:

> Is M-D still supposed to kill without confirmation?

Yes unless your buffer is not saved.


-- 
Thierry
https://emacs-helm.github.io/helm/
