### ISSUE TITLE
Add common Emacs key bindings to hgrep

### ISSUE THREAD

**Issue by tuhdo** [emacs-helm/helm#995]
So today I got feedback from some users and they wish that `hgrep` should be easy to navigate without switching to `*hgrep*` buffer using `M-g n` and `M-g p`, similar to `*compilation*` buffer.

**Comment by tuhdo** [comment]
I think that's a good idea too. Currently it's just inconvenient to navigate `*hgrep*` buffer.

**Comment by thierryvolpiatto** [comment]
I wonder why people don't use M-x grep for such cases...

**Comment by tuhdo** [comment]
- It's a valid use case when your grep search takes a while and you want to save it. What's wrong with people who want to have both `helm-do-grep` for live searching and a static buffer for navigating?

- Having a saved search buffer prevent you from accidentally delete a character and the expensive search starts all over again.

- You can have multiple search buffers for multiple queries. Currently with `helm-resume` we can only have one and it can be quite hard to get back when we have many Helm buffers around.

PR welcome?

**Comment by tuhdo** [comment]
Ok so here is my propose fix: I guess you don't like too fanciful PR, so I only add `M-p` and `M-n` key bindings to `*hgrep*` mode. It is also symmetric with `C-n` and `C-p`. Is this ok?

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> Ok so here is my propose fix: I guess you don't like too fanciful PR,
> so I only add M-p and M-n key bindings to *hgrep* mode.

You were speaking of next/prev-error which have nothing to do with
M-p/n.

To implement next-error you will have to write a `next-error-function'
and bind it to the helm-grep-mode buffer locally (basically),
you will have also to fix the revert-buffer fn accordingly, 
it is a lot of work to have something particularly unuseful to my eyes.
It will allow you to jump blindly to next candidate of the hgrep buffer without
passing by the hgrep buffer.
Emacs vanilla commands grep, occur etc... are particularly attached to
this by tradition mostly, I personally never believe this feature is
useful and never used it.

> It is also symmetric with C-n and C-p.  Is this ok?

No, try first to understand what next/prev-error is.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment]
@thierryvolpiatto I understood what you was saying and that's why I said that I won't implement such fancy feature but simply bind the existing key bindings:

- `C-<down>`: go to next match and open the match.
- `C-<up>`: go to previous match and open the match.
- `M-<down>`: go to next match without opening the match.
- `M-<up>`: go to next match without opening the match.

to `C-f/C-n/M-f/M-p` in places of arrow keys.

**Comment by tuhdo** [comment]
@thierryvolpiatto In sum, this issue now reduces to adding more common key bindings, and that's it. It's trivial to add, so maybe you add those 4 key bindings?

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> @thierryvolpiatto I understood what you was saying and that's why I said that I won't implement such fancy feature but simply bind the existing key bindings:
>
>   * C-<down>: go to next match and open the match.
>   * C-<up>: go to previous match and open the match.
>   * M-<down>: go to next match without opening the match.

No this one go to previous file.

>   * M-<up>: go to next match without opening the match.

And this one to next file.

> to C-f/C-n/M-f/M-p in places of arrow keys.

C-f is forward-char and should stay forward-char.
C-n is next-line and should stay next-line.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> @thierryvolpiatto In sum, this issue now reduces to adding more common
> key bindings,

No I just want to be sure we are speaking of the same thing.
I also want to be sure you know what the actual bindings do and what you
want exactly to provide.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment]
It should be `C-p/C-n` not `C-f/C-n`. I made a typo there. About `M-n` and `M-p` ok I justt tried without reading the command descriptions and at that time I had multiple files for each match that made me thought so.

Currently `M-n` and `M-p` is unbound, so perhaps we could give them commands similar to `C-<down>/C-<up>`?

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> Currently M-n and M-p is unbound, so perhaps we could give them commands similar to C-<down>/C-<up>?

Ah! here we are :-), ok for M-n and M-p, go ahead.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
