### ISSUE TITLE
Just wanting to express my appreciation for Helm

### ISSUE THREAD

**Issue by ReneFroger** [emacs-helm/helm#996]
Sometimes I discover small things to realize how clever Helm actually implemented is. For today, I discovered when I have two buffers opened, he will indicate only the different path name. 

For example, you have two buffers from the locations:

`C:/console/foo/core/status/header.inc`

and 

`C:/console/bar/core/status/header.inc`

Then Helm will displaying from the buffers, the `header.inc<foo>` and `header.inc<bar>` instead only `header.inc`. 
What a nifty trick from the authors of Helm! 

Awesome... Thierry, you rocks! :+1:

**Comment by thierryvolpiatto** [comment]
ReneFroger <notifications@github.com> writes:

> Then Helm will displaying from the buffers, the header.inc<foo> and
> header.inc<bar> instead only header.inc.  What a nifty trick from the
> authors of Helm!

Many thanks to support helm, but...
It looks the feature you are describing is not coming from helm, but
from emacs itself, namely uniquify.el ;-)

To configure it, see `uniquify-buffer-name-style', looks that actually
you are using the default value `post-forward-angle-brackets'.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
