### ISSUE TITLE
helm-dabbrev and python buffers.

### ISSUE THREAD

**Issue by proofit404** [emacs-helm/helm#997]
Suppose following python buffer:
```python
class SomeClass(base.P|):
    pass
```
where `|` signify a point.  `helm-dabbrev` will try to complete whole `base.P` instead of simply `P`. Since there is no completion for `base.P` it doesn't work.

The second question is there a way to use case insensitive completions for `C-M-/` command?

Thanks for all your work.

Regards, Artem.

**Comment by thierryvolpiatto** [comment]
Malyshev Artem <notifications@github.com> writes:

> Suppose following python buffer:
>
> class SomeClass(base.P|):
>     pass
>
> where | signify a point. helm-dabbrev will try to complete whole
> base.P instead of simply P. Since there is no completion for base.P it
> doesn't work.

Indeed.

Is

(setq helm-dabbrev--regexp "\\s-\\|\t\\|[(\[\{\"'`=<$;]\\|\\s\\\\|^\\|\\.")

Fixing the problem ?

> The second question is there a way to use case insensitive completions
> for C-M-/ command?

See `helm-dabbrev-case-fold-search'.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by proofit404** [comment]
`(setq helm-dabbrev--regexp "\\s-\\|\t\\|[(\[\{\"'`=<$;]\\|\\s\\\\|^\\|\\.")`
Yes it is. Thanks.

**Comment by thierryvolpiatto** [comment]
Malyshev Artem <notifications@github.com> writes:

> (setq helm-dabbrev--regexp "\\s-\\|\t\\|[(\[\{\"'=<$;]\|\s\\|^\|\.")`
> Yes it is. Thanks.

Ok I will apply this change.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by proofit404** [comment]
Works fine with last melpa build. Thanks.
