### ISSUE TITLE
Naming changes for some eldoc functions break helm-eval-expression-with-eldoc

### ISSUE THREAD

**Issue by kriesoff** [emacs-helm/helm#998]
Some eldoc functions were moved to elisp-mode.el in this commit:

http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=e6cfa098ae23e34c5415642e2f848a92982924ef

This involved replacing the `eldoc-` prefix with `elisp--`, which breaks `helm-eval-expression-with-eldoc`. For me, it works again when defining corresponding aliases for `eldoc-current-symbol`, `eldoc-fnsym-in-current-sexp`, `eldoc-get-var-docstring` and `eldoc-get-fnsym-args-string`.

**Comment by thierryvolpiatto** [comment]
kriesoff <notifications@github.com> writes:

> Some eldoc functions were moved to elisp-mode.el in this commit:

Ah! Yes, I have fixed this in eldoc-eval but I forget fixing it here,
will do tomorrow morning, many thanks to catch this!

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Should be fixed now.
